containerd/containerd

Makefile
Makefile.linux

Added -trimpath flag in -gcflags to reduce codepath in stack trace.
Fixes #2000

trim code path in stack trace.

---

Makefile

Per the request in #2021, add a link to the issue in case this situation
changes in the future.

Add Golang issue link re: -trimpath to Makefile

---

.travis.yml
RUNC.md
vendor.conf
vendor/github.com/opencontainers/runc/libcontainer/system/linux.go

This fixes issues for init and exec hanging forever when an error
happens on start.
Fixes #1882

Update runc to 9f9c96235cc97674e935002fc3d78361b69

---

client_test.go
container_checkpoint_test.go
container_linux_test.go
container_test.go
metadata/gc_test.go
snapshots/overlay/overlay_test.go

Cleanup some tests to use `t.Fatal()` instead of returning

Replace t.Error(); return with t.Fatal()

---

archive/tar.go
archive/tar_windows.go
cio/io.go
cio/io_unix.go
cio/io_windows.go
cmd/containerd/main.go
cmd/containerd/main_unix.go
cmd/ctr/commands/shim/io_unix.go
linux/bundle.go
linux/proc/io.go
linux/proc/utils.go
linux/shim/service.go
linux/shim/service_linux.go
linux/shim/service_unix.go

To avoid buffer bloat in long running processes, we try to use buffer
pools where possible. This is meant to address shim memory usage issues,
but may not be the root cause.
Partial fix for #2020

archive, cio, cmd, linux: use buffer pools

---

.travis.yml
RUNC.md
vendor.conf
vendor/github.com/opencontainers/runc/libcontainer/system/linux.go

This fixes issues for init and exec hanging forever when an error
happends on start.

[release/1.0] Update runc to 9f9c96235cc97674e935002fc3d78361b69

---

archive/tar.go
cio/io.go
cio/io_unix.go
cio/io_windows.go
cmd/containerd/main.go
cmd/containerd/main_unix.go
cmd/ctr/commands/shim/io_unix.go
linux/bundle.go
linux/proc/io.go
linux/proc/utils.go
linux/shim/service.go
linux/shim/service_linux.go
linux/shim/service_unix.go

To avoid buffer bloat in long running processes, we try to use buffer
pools where possible. This is meant to address shim memory usage issues,
but may not be the root cause.
(cherry picked from commit cd72819b53ff30976570d0a8b80e1a4cf96f2095)

[release/1.0] archive, cio, cmd, linux: use buffer pools

---

remotes/docker/resolver.go

I was debugging why I was getting a token auth failure when attempting to pull an image, @jessvalarezo realized that the image was just misspelled.
This adds extra error context when the failure is caused by failed auth to indicate that the repository just might not exist.
```
PS H:\bin\containerd> .\ctr images pull docker.io/image/doesnotexist:latest
docker.io/image/doesnotexist:latest: resolving      |--------------------------------------|
elapsed: 0.8 s                       total:   0.0 B (0.0 B/s)
ctr: failed to resolve reference "docker.io/image/doesnotexist:latest": pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
```
cc @stevvooe FYI this was what I thought was a failed token auth. Just a …

content.Fetch: better error when auth fails

---

cmd/containerd-shim/main_unix.go

To avoid having the shim hold on to too much memory, we've made a few
adjustments to favor more aggressive reclamation of memory from the
operating system. Typically, this would be negligible, on the order of a
few megabytes, but this is impactful when running several containers.
The first fix is to lower the threshold used to determine when to run
the garbage collector. The second runs `runtime/debug.FreeOSMemory` at a
regular interval.
Under test, this result in a sustained memory usage of around 3.7 MB.
Fixes #2020

cmd/containerd-shim: aggressive memory reclamation

---

archive/tar.go
archive/tar_test.go

Currently directory changes are not added to the list of included directories, allowing those directories to receive duplicate entries where there is both a metadata change to the directory and a change to a file under that directory.
Adding this for cherry-pick, this could be considered a regression in 1.0.1 since 1.0 would have had the correct behavior by not including the directory as a parent. Note this only effects created content, the main consumer of which right now is buildkit or other build tools using containerd.
See https://github.com/moby/buildkit/issues/266

Fix duplicate directories entries on metadata change

---

cmd/containerd-shim/main_unix.go

To avoid having the shim hold on to too much memory, we've made a few
adjustments to favor more aggressive reclamation of memory from the
operating system. Typically, this would be negligible, on the order of a
few megabytes, but this is impactful when running several containers.
The first fix is to lower the threshold used to determine when to run
the garbage collector. The second runs `runtime/debug.FreeOSMemory` at a
regular interval.
Under test, this result in a sustained memory usage of around 3.7 MB.
(cherry picked from commit 0e8f08476cc3ae0996ed5d814892b8e342cb2e7f)

[release/1.0] cmd/containerd-shim: aggressive memory reclamation

---

vendor.conf
vendor/github.com/containerd/go-runc/runc.go
vendor/github.com/containerd/go-runc/utils.go

vendor: update go-runc to reduce gc pressure

---

archive/tar.go
archive/tar_test.go

cherry-pick of #2054
Fixes a regression to diff behavior in 1.0.1 affecting builders

[release/1.0] archive: fix duplicate directories entries on metadata change

---

cmd/ctr/commands/images/export.go
cmd/ctr/commands/images/pull.go
cmd/ctr/commands/images/push.go

For missing required parameters adds error return before attempting any
actions to `ctr images` commands.
Fixes: #2064

Add error return for missing params in ctr images

---

content/helpers.go
content/helpers_test.go
content/testsuite/testsuite.go

Prevents the copy method from calling discard on the writer when the reader is not seekable. Instead, the copy method will discard up to the offset. Truncate is a more expensive operation since any bytes that are truncated already have their hash calculated and are stored on disk in the backend. Re-writing bytes which were truncated requires transfering the data over GRPC again and re-computing the hash up to the point of truncation.

content: update copy to discard instead of truncate

---

content/helpers.go
content/helpers_test.go
content/testsuite/testsuite.go

Prevents the copy method from calling discard on the writer when the reader is not seekable. Instead, the copy method will discard up to the offset. Truncate is a more expensive operation since any bytes that are truncated already have their hash calculated and are stored on disk in the backend. Re-writing bytes which were truncated requires transferring the data over GRPC again and re-computing the hash up to the point of truncation.
Cherry-pick #2065

[release/1.0] content: update copy to discard instead of truncate

---

cmd/ctr/commands/containers/containers.go
cmd/ctr/commands/run/run.go
cmd/ctr/commands/run/run_unix.go
cmd/ctr/commands/run/run_windows.go

1. Add `ctr c create` command which only creates a container (as opposed to run which creates and runs a container).
2. Add `--config` flag to `ctr c create` and `ctr run` 
~~which opens the given `config.toml` file. This file can define any flags used in creating a new container.~~
which opens given `config.json` file containing a oci runtime-spec

ctr: add container create cmd and config flag

---

content/local/store_test.go
content/testsuite/testsuite.go
content_test.go
metadata/content_test.go

Cherrypick #2076 from @stevvooe onto 1.0.x branch

[release/1.0] Cherrypick ensure content unique

---

mount/lookup_test/lookup_linux_test.go
mount/lookup_unix.go

In cri-containerd we do encountered an problem that `/etc/xxx` is on a different device with `/etc`, when `/etc` is mounted as overlayfs.
It seems fine to purely reply on the path, like what docker is doing https://github.com/moby/moby/blob/master/daemon/oci_linux.go#L387
@AkihiroSuda @miaoyq 

Simplify mount.Lookup.

---

cmd/containerd/config_linux.go
cmd/containerd/config_windows.go
cmd/containerd/main.go

This uses a simple `IsAbs` check to see if we are using an on disk path
for a unix socket vs an address since we do not prefix addresses with
`unix://` or `tcp://`.

Allow tcp debug address

---

.travis.yml
contrib/Dockerfile.test
fs/dtype_linux_test.go
mount/lookup_test/lookup_linux_test.go
script/setup/install-protobuf
script/setup/install-runc
snapshots/btrfs/btrfs_test.go
testutil/loopback_linux.go

This provides a dockerfile for building an image to run the containerd tests.
Signed-off-by: Christopher Jones <tophj@linux.vnet.ibm.com>
few WIP issues:
```
failed to make btrfs filesystem (out: "ERROR: '/dev/loop3' is too small to make a usable filesystem\nERROR: minimum size for each btrfs device is 142606336\nbtrfs-progs v4.7.3\nSee http://btrfs.wiki.kernel.org for more information.\n\n")
```

running tests in a container

---

vendor.conf
vendor/github.com/containerd/cgroups/blkio.go
vendor/github.com/containerd/cgroups/errors.go

This fixes performance issues with walking `/dev` to get device paths.

Bump cgroups to c0710c92e8b3a44681d1321dcfd1360fc5

---

vendor.conf
vendor/github.com/containerd/cgroups/blkio.go
vendor/github.com/containerd/cgroups/errors.go

This fixes performance issues with walking `/dev` to get device paths.

[release 1.0] Bump cgroups to c0710c92e8b3a44681d1321dcfd1360fc5

---

script/validate/vendor

vendor/ must be removed first, otherwise files added to vendor/ that aren't added to
vendor.conf will not cause the validation to fail.

Fix vendor validation

---

vendor.conf
vendor/github.com/BurntSushi/toml/COPYING
vendor/github.com/BurntSushi/toml/lex.go

Follow-up to #2088
v0.3.0 still contains "WTFPL"
https://github.com/BurntSushi/toml/commits/master

vendor: update BurntSushi/toml for MIT license

---

vendor.conf
vendor/github.com/BurntSushi/toml/COPYING
vendor/github.com/BurntSushi/toml/lex.go

cherry-pick https://github.com/containerd/containerd/pull/2090

[release/1.0] vendor: update BurntSushi/toml for MIT license

---

content/testsuite/testsuite.go

checkUploadStatus actaully verifys contents on Updating already written buffers,
hence should be called as checkUpdateStatus

Testcase name corrected

---

sys/stat_unix.go

This ensures the `time.Unix` function is given int64 arguments so that a 32 bit Unix OS can run `make`. This fixes an issue when running `make` that I ran into on a Raspberry Pi with 32 bit Debian 9.1:
```
sys/stat_unix.go:27:26: cannot use st.Atim.Sec (type int32) as type int64 in argument to time.Unix
sys/stat_unix.go:27:39: cannot use st.Atim.Nsec (type int32) as type int64 in argument to time.Unix
Makefile:150: recipe for target 'bin/ctr' failed
make: *** [bin/ctr] Error 2
```
Seems like this happened after [this commit](https://github.com/containerd/containerd/commit/184bc256293eb7fba619514078c7b575b8a5f6aa) removed the `int64` type conversion for unix systems when the unconvert linter was added [in this PR.](https://github.com/containerd/containerd/pull/1975)

Add time type conversions for 32bit Unix platforms

---

.appveyor.yml
.travis.yml
Makefile
script/setup/install-dev-tools
script/validate/vendor
vendor.conf
vendor/github.com/BurntSushi/toml/README.md
vendor/github.com/BurntSushi/toml/doc.go
vendor/github.com/BurntSushi/toml/encode.go
vendor/github.com/BurntSushi/toml/lex.go
vendor/github.com/BurntSushi/toml/parse.go
vendor/github.com/opencontainers/runc/libcontainer/system/syscall_linux_32.go

Backport of #2092
release/1.0 didn't have any vendor validation so I had to backport the change to install vndr as well.

[release/1.0] Fix vendor validation

---

plugin/plugin.go
server/config.go
server/server.go

Fixes https://github.com/containerd/containerd/issues/2061.
With this PR, we can disable a `cri` and `healthcheck` plugin by adding following line in the containerd config file:
```
disable_plugins = ["cri", "healthcheck"]
```

Support disable plugins.

---

log/context.go

When trying to update and use this in cri-containerd, I find this error.
This is a bit confusing:
* `entry.Level` is only set when actually outputs log (see [here](https://github.com/sirupsen/logrus/blob/master/entry.go#L94)). It's just Level of a particular log entry.
* `entry.Logger.Level` is the thing we should use. Note that we need `atomic` to avoid race condition. (see [here](https://github.com/sirupsen/logrus/blob/master/logger.go#L316)).

Fix trace level support.

---

contrib/seccomp/seccomp_default.go

This is so confusing, and not needed.

Remove a really confusing fallthrough

---

client.go
images/handlers.go
images/image.go
images/oci/exporter.go
remotes/handlers.go

Fix issue where manifest content must always be fetched even if it is already fully downloaded or shared locally. Simplify children label setting and platform filtering. Prevent getting a fetcher when content shared locally.
Note this makes the filtering and labeling more composable, so we could change the behavior more easily (such as if we only wanted to label content which was saved locally, the wrapping order could just be changed).
This is the first PR to support content sharing on the client side. This PR can be backported into 1.0.x to support content sharing in clients based on 1.0.x and containerd 1.1+.

content: support manifest labeling on completed content ingests on the client

---

archive/tar_test.go
vendor.conf
vendor/github.com/containerd/continuity/fs/diff.go

Ensures the remove directory marker gets updated when a new directly delete is found right after an old one. This was causing a bug where deletion events were being sent under a removed directory, causing the archiver to error when attempting to include the parent of a removed file.
fixes #2119

archive/diff: fix consecutive directory removal bug

---

archive/tar_test.go
fs/diff.go
fs/diff_test.go

Cherry pick of #2126 
Since fs package was moved to continuity in master, this creates an identical fix for the fs package in the release/1.0 branch. There has been no functionality divergence since moving from master.

[release/1.0] archive/diff: fix consecutive directory removal bug

---

.gitignore
Makefile
docs/man/config.toml.5.md
docs/man/containerd-config.1.md
docs/man/containerd.1.md
docs/man/ctr.1.md
script/setup/install-dev-tools

The start of manpage generation for a few basic containerd commands.
Still needed:
Doing a [WIP] PR to make sure other constituents are comfortable with the way this is being done before finishing it off.
Fixes: #1467

Add initial man pages

---

contrib/Dockerfile.test

Use golang:latest instead of a specific version.
Signed-off-by: Christopher Jones <tophj@linux.vnet.ibm.com>

[contrib] bump golang

---

client.go

Was helping someone find something in the docs today and noticed a typo; but also seemed reasonable to make the wording a bit clearer on `client.Subscribe`.

Clean up client Subscribe docs; remove a typo

---

snapshots/btrfs/btrfs_test.go

Uses a much smaller value when creating this file to be used
as a loopback device on non-ppc64le platforms.
This file has to be so large on ppc64le, because mkfs.btrfs
uses the default architecture pagesize as blocksize, which is 64KB
on ppc64le, but only 4KB on amd64 and s390x.
Signed-off-by: Christopher Jones <tophj@linux.vnet.ibm.com>

[testing] use smaller filesize on 4KB pagesize systems

---

cmd/ctr/commands/run/run.go
cmd/ctr/commands/run/run_unix.go

Adds a useful flag to `ctr` to enable joining any existing Linux
namespaces for any namespace types (network, pid, ipc, etc.) using the
existing With helper in the oci package.
This is useful for simple use cases, for example: network namespaces are created outside containerd and the user wants to test this out without having to manage/assemble an entire `config.json` with the unique namespace path set.

Add --with-ns flag to ctr run/create

---

vendor.conf
vendor/github.com/containerd/continuity/fs/stat_linux.go
vendor/github.com/containerd/continuity/sysx/xattr_openbsd.go
vendor/github.com/containerd/continuity/sysx/xattr_unsupported.go

Needed for building `containerd` on 32bit systems
Includes the following PR's:
* https://github.com/containerd/continuity/pull/107
* https://github.com/containerd/continuity/pull/105
* https://github.com/containerd/continuity/pull/104
Signed-off-by: Eli Uriegas <eli.uriegas@docker.com>

Update continuity vendor to d8fb85

---

windows/runtime.go
windows/task.go

This removes the Windows Servicing container infrastructure. This is being removed from the platform, and was never used in production.
See https://github.com/Microsoft/hcsshim/pull/158
Signed-off-by: Darren Stahl <darst@microsoft.com>

Removing Windows servicing containers

---

.appveyor.yml
.travis.yml
api/events/container.pb.go
api/services/events/v1/events.pb.go

Given that containerd states Go 1.9 "and up", it's probably a good thing to have a pr checking if CI is successful on Go 1.10 now that it is in beta
To find out what has changed in Go 1.10, read the draft release notes:
https://beta.golang.org/doc/go1.10
Documentation for Go 1.10 is available at:
https://beta.golang.org/

Bump to Go 1.10

---

client.go
client_test.go

This adds a reconnect api to the client so that the client instance
stays the same and on reconnect, all tasks and containers with
references to the *Client have the correct connection.

Add client.Reconnect API

---

cio/io_unix.go
cio/io_unix_test.go

Add nil checks before closing fifos to avoid panic when fifo was never
opened.
Signed-off-by: Cody Roseborough <crrosebo@amazon.com>

Fix panics in cio/io_unix.go

---

cmd/containerd-stress/density.go
cmd/containerd-stress/main.go
cmd/containerd-stress/rlimit_unix.go
cmd/containerd-stress/rlimit_windows.go

Running the density tool will report Pss and Rss total and per container
values for shim memory usage. Values are reported in KB.
```bash
containerd-stress density --count 500
INFO[0000] pulling docker.io/library/alpine:latest
INFO[0000] generating spec from image
{"pss":421188,"rss":2439688,"pssPerContainer":842,"rssPerContainer":4879}
```

Add density stress test

---

images/handlers.go
images/image.go
platforms/platforms.go
platforms/platforms_test.go

This PR is the first step in a solution for #2029, handling multi-arch images.
Here the `Parse` function now returns a Platform spec, which allows us to decouple the matcher.

Update Parse to return a Platform spec

---

linux/bundle.go
linux/runtime.go

The `runtime_root` option in `config.toml` was not propagated to the shim.

linux: propagate --runtime-root to shim properly

---

BUILDING.md
contrib/Dockerfile.test

To match build requirements for containerd now that we are using 1.10.
Fixes: #2167

Update recommended versions to Go 1.10

---

archive/tar_unix.go

`ctr images pull docker.io/library/ubuntu:latest` was failing with `lchown /home/suda/.local/share/containerd/tmpmounts/containerd-mount363494842/dev/agpgart: no such file or directory.`

archive: fix logic for skipping mknod when running in userns

---

remotes/docker/resolver.go

This fix adds support for image registries that expect authentication for POST /v2/token such as used by the GET. E.g., JFrog Artifactory has been observed to respond with a 401 (Unauthorized) in that case. Adding 401 in addition to the current handling of 405 and 404 in the resolver solves the authentication problem. Finally, this enables image pulls also for Artifactory.
Fixes https://github.com/containerd/containerd/issues/2148
Signed-off-by: Ruediger Maass <ruediger.maass@de.ibm.com>

Adds handling of 401 for POST /v2/token without authentication

---

archive/tar_unix.go

cherry-pick https://github.com/containerd/containerd/pull/2163

[release/1.0] archive: fix logic for skipping mknod when running in userns

---

linux/proc/io.go

This changes the copyIO in the shim to support logging to files from
client requests in addition to fifos.

Refactor shim to support file logging

---

cmd/ctr/commands/run/run.go

compatible oci runtime version printed along with parse error.
Should fix #925

better image config parse error.

---

.travis.yml
cio/io_unix_test.go
cmd/containerd/builtins_cri_linux.go
mount/temp.go
mount/temp_unix.go
mount/temp_unsupported.go
script/setup/install-cni
script/setup/install-critools
script/validate/fileheader
script/validate/template/bash.txt
script/validate/template/dockerfile.txt
script/validate/template/go.txt
script/validate/template/makefile.txt

file-header check using github.com/kunalkushwaha/ltag
follow-up  of #2108

CI check for file-header added

---

client_test.go
daemon_config_linux_test.go
daemon_test.go
linux/bundle.go
linux/runtime.go

#2173 fixed the propagation of `--runtime-root` flag for `ShimRemote` but `ShimLocal` was not fixed in the commit.
This PR also adds integration test suite for `config.toml`.

linux: fix runtime-root propagation

---

vendor.conf
vendor/github.com/containerd/cgroups/blkio.go
vendor/github.com/containerd/cgroups/cgroup.go
vendor/github.com/containerd/cgroups/control.go
vendor/github.com/containerd/cgroups/cpu.go
vendor/github.com/containerd/cgroups/cpuacct.go
vendor/github.com/containerd/cgroups/cpuset.go
vendor/github.com/containerd/cgroups/devices.go
vendor/github.com/containerd/cgroups/errors.go
vendor/github.com/containerd/cgroups/freezer.go
vendor/github.com/containerd/cgroups/hierarchy.go
vendor/github.com/containerd/cgroups/hugetlb.go
vendor/github.com/containerd/cgroups/memory.go
vendor/github.com/containerd/cgroups/named.go
vendor/github.com/containerd/cgroups/net_cls.go
vendor/github.com/containerd/cgroups/net_prio.go
vendor/github.com/containerd/cgroups/paths.go
vendor/github.com/containerd/cgroups/perf_event.go
vendor/github.com/containerd/cgroups/pids.go
vendor/github.com/containerd/cgroups/state.go
vendor/github.com/containerd/cgroups/subsystem.go
vendor/github.com/containerd/cgroups/systemd.go
vendor/github.com/containerd/cgroups/ticks.go
vendor/github.com/containerd/cgroups/utils.go
vendor/github.com/containerd/cgroups/v1.go

The containerd **master** branch version of #2198 

Update cgroups vendor for license headers/bug fix

---

vendor.conf
vendor/github.com/containerd/cgroups/blkio.go
vendor/github.com/containerd/cgroups/cgroup.go
vendor/github.com/containerd/cgroups/control.go
vendor/github.com/containerd/cgroups/cpu.go
vendor/github.com/containerd/cgroups/cpuacct.go
vendor/github.com/containerd/cgroups/cpuset.go
vendor/github.com/containerd/cgroups/devices.go
vendor/github.com/containerd/cgroups/errors.go
vendor/github.com/containerd/cgroups/freezer.go
vendor/github.com/containerd/cgroups/hierarchy.go
vendor/github.com/containerd/cgroups/hugetlb.go
vendor/github.com/containerd/cgroups/memory.go
vendor/github.com/containerd/cgroups/named.go
vendor/github.com/containerd/cgroups/net_cls.go
vendor/github.com/containerd/cgroups/net_prio.go
vendor/github.com/containerd/cgroups/paths.go
vendor/github.com/containerd/cgroups/perf_event.go
vendor/github.com/containerd/cgroups/pids.go
vendor/github.com/containerd/cgroups/state.go
vendor/github.com/containerd/cgroups/subsystem.go
vendor/github.com/containerd/cgroups/systemd.go
vendor/github.com/containerd/cgroups/ticks.go
vendor/github.com/containerd/cgroups/utils.go
vendor/github.com/containerd/cgroups/v1.go

Fixes a bug with OCI spec cgroup device name/paths as well as bringing
in the license header additions from the cgroups sub-project.

[release/1.0] Update cgroups vendor for licenses/bug fix

---

snapshots/overlay/check.go
snapshots/overlay/check_test.go
testutil/helpers_unix.go

This function is not called during plugin initialization (#2140),
but should be useful for downstream projects that uses overlayfs
snapshotter as a Go library.
Benchmark result on Ubuntu 17.10, GCE n1-standard-4:
BenchmarkOverlaySupportedOnExt4-4                    100          20490598 ns/op
BenchmarkOverlayUnsupportedOnFType0XFS-4           30000             39316 ns/op
BenchmarkOverlaySupportedOnFType1XFS-4               100          19287083 ns/op
BenchmarkOverlayUnsupportedOnFAT-4                   100          14217772 ns/op
i.e. the overhead is typically about 20 msec on this machine.

overlay: add Supported() checker

---

content/helpers.go
content/testsuite/testsuite.go
content_test.go
metadata/buckets.go
metadata/content.go
metadata/content_test.go
metadata/db.go
metadata/db_test.go
metadata/migrations.go
namespaces/context.go
services/content/service.go

Update content ingests to use content from another namespace. Ingests must be committed to make content available and the client will see the sharing as an ingest which has already been fully written to, but not completed.
Updated the database version to change the ingest record in the database from a link key to an object with a link and expected value. This expected value is used to indicate that the content already exists and an underlying writer may not yet exist.
Fixes #1696
This does not address #1713 and assumes a shared default mode

content: shared content across namespaces

---

metadata/snapshot.go
snapshots/overlay/overlay.go
snapshots/storage/bolt.go

Updates overlay remove to simply remove the reference and adds a cleanup method for discarding the directory. Updates snapshot create to setup the directory structure while in the transaction to prevent cleanup from removing directories which are part of a create.
This effectively adds a 3rd phase to the garbage collection which completes all the on disk snapshot cleanup. During this disk cleanup the snapshotter will be unlocked to allow for the management of snapshots. The garbage collection scheduler will still wait for the completion of this 3rd phase, however it will not consider it when calculating pause time.
Added options to overlay snapshotter to allow configuring the asynchronous removal of keeping remove synchronous

snapshots/overlay: add overlay cleanup

---

cmd/ctr/commands/images/images.go

cmd/ctr/images: add `i` alias for images command

---

windows/runtime.go

before, the windows runtime plugin had no platform defined. updated to add the default platform during initialization. 
before:
```
$ ctr plugins
TYPE                            ID                    PLATFORMS        STATUS
io.containerd.service.v1        snapshots-service     -                ok
io.containerd.runtime.v1        windows               -                ok
```
now:
```
$ ctr plugins
TYPE                            ID                    PLATFORMS        STATUS
io.containerd.service.v1        snapshots-service     -                ok
io.containerd.runtime.v1        windows               windows/amd64    ok
```

windows: define platform in runtime plugin init

---

cmd/ctr/commands/tasks/delete.go

when using `ctr`, it is not possible to delete a `PAUSED` or `RUNNING` task: 
``` ctr t resume test
/go/src/github.com/containerd/containerd # ctr t ls
TASK    PID     STATUS
test    6543    RUNNING
/go/src/github.com/containerd/containerd # ctr t delete test
ctr: task must be stopped before deletion: running: failed precondition
/go/src/github.com/containerd/containerd # ctr t pause test
/go/src/github.com/containerd/containerd # ctr t delete test
ctr: task must be stopped before deletion: paused: failed precondition
/go/src/github.com/containerd/containerd # ctr t ls
TASK    PID     STATUS
test    6543    PAUSED
```
add a `--force` flag which will kill the task process, and successfully delete the task.

ctr: allow for force kill when deleting task process

---

client.go
client_opts.go
client_test.go
cmd/ctr/commands/content/fetch.go
cmd/ctr/commands/images/pull.go
images/handlers.go
images/image.go
images/oci/exporter.go
remotes/handlers.go

Modified FilterPlatforms handler and RemoteContext so that either one specific platforms, various platforms, or all platforms can be pulled. Additionally, it is possible to push the content for all platforms to a remote registry. 
This is the second step in allowing for multi-arch images on multi-arch platforms #2029
This closes #1772. Please run `ctr images pull` with the flag `--all-platforms`

allow content to be pulled for specific platform(s), all platforms

---

snapshots/overlay/overlay.go

Fixes a bug where a writable transaction may create or make changes to a directory while the cleanup is running, leading to removal of a directory which will be referenced.
fixes #2210

overlay: fix cleanup directory deletion race

---

gc/scheduler/scheduler.go

I ran the `containerd` service with the default config, the service failed when loading config file with error log:
```
containerd[10993]: containerd: time: missing unit in duration 100000000
```
That's because `toml.Decode` can not decode `100000000` to `time.Duration` variable.
We should encode `time.Duration` variable to string with unit (e.g.: `100000000`  -> `"100ms"`) when print the the default config with `containerd config default`.
This pr fixes the bug.

Fixes a default config bug of gc scheduler

---

archive/tar.go
archive/tar_test.go
vendor.conf
vendor/github.com/containerd/continuity/fs/fstest/file.go
vendor/github.com/containerd/continuity/fs/fstest/testsuite.go

The go-tar implementation which is used cannot handle sockets.
There's no good reason to preserve a socket, they are basically useless without
the process which made them.
I discovered this with https://github.com/dotnet/dotnet-docker-samples/tree/master/aspnetapp and buildkit's dockerfile frontend which gave:
```
aspnetapp$ sudo $(which buildctl) build --frontend=dockerfile.v0 --local context=. --local dockerfile=. --exporter=image --exporter-opt=name=foo --frontend-opt target=build-env
[...]
=> ERROR exporting to image                                                                               1.0s
=> => exporting layers                                                                                    4.0s
------
> exporting to …
```

Ignore sockets when creating a tar stream of a layer

---

client.go
cmd/ctr/commands/snapshots/snapshots.go
content/testsuite/testsuite.go
content_test.go
image.go
lease.go
metadata/content_test.go
task.go
vendor.conf
vendor/github.com/containerd/cri/pkg/containerd/importer/importer.go

Allows the client to choose the context to finish the lease. This allows the client to switch contexts when the main context used to the create the lease may have been cancelled.
Requires temporary cri vendor until this is merged and fixed in cri
Closes #2193

lease: pass in context to lease done function in client

---

linux/proc/exec.go

Under certain conditions in the client, the fifo for a container may not
be created. A timeout has been added to this operation to ensure the
shim can recover when the client fails to open the fifos.
(cherry picked from commit 9754696ff53dd177a343615e6c6d7dbdc94e21a3)
Cherry pick of #2229 into release/1.0

[release/1.0] linux/prox: timeout fifo creation

---

RELEASES.md

Based on feedback to add a note about CRI as unstable. Now that CRI is an interface out of containerd, we need to be clear about its stability and support across versions.

Add CRI API to releases file

---

image.go

The uncompressed label should be placed on content instead of snapshots. Currently the uncompressed label is getting passed into as a label option for apply, which is used to commit snapshots. The content is already committed, but after apply the uncompressed diff digest is verified and can be reliably used to update the content with the label.

client/pull: fix label being put on snapshot instead of content

---

image.go

Backport #2237
The uncompressed label should be placed on content instead
of snapshots. Currently the uncompressed label is getting
passed into as a label option for apply, which is used to commit
snapshots. The content is already committed, but after apply
the uncompressed diff digest is verified and can be reliably used
to update the content with the label.

[release/1.0] client/pull: fix label being put on snapshot instead of content

---

metadata/containers_test.go

Incorrectly spelled "containerd" in test string.

Fix typo in metadata test typeurl string

---

archive/tar_windows.go

hcsshim's `LayerWriter.Close` method does some necessary post processing on the layer during layer apply, so an error closing the layer should be considered a fatal error. Priority is given to errors encountered in the rest of the function, but if the function would otherwise not fail, a `Close` failure should be returned to the caller.
Signed-off-by: Darren Stahl <darst@microsoft.com>

Make hcsshim layerwriter close a fatal error

---

metadata/containers_test.go

[release/1.0] Incorrectly spelled "containerd" in test string.

[release/1.0] cherry-pick: Fix typo in metadata test typeurl string

---

contrib/seccomp/seccomp_default.go

No capabilities can be granted outside the bounding set, so there
is no point looking at any other set for the largest scope.

The set of bounding capabilities is the largest group

---

.travis.yml
BUILDING.md
RUNC.md
contrib/Dockerfile.test

As of opencontainers/runc@db093f621f4e6d40feafbe6d7b89a9bee6f6ff85 runc
no longer depends on libapparmor thus libapparmor-dev no longer needs to
be installed to build it. Adjust the documentation accordingly.
Signed-off-by: Tobias Klauser <tklauser@distanz.ch>

Drop libapparmor dependency from runc build docs

---

cmd/containerd-shim/main_unix.go
linux/shim/client/client.go
sys/socket_unix.go

---
Closes #2252
We don't support BSDs (yet?), but I still went ahead and limited according to their lower length.

Return a better error message is unix socket path is too long.

---

cmd/containerd-shim/main_unix.go
linux/shim/client/client.go
sys/socket_unix.go

(cherry picked from commit 3c3a676490970dd759b940c9982130aa2f71da87)

[release/1.0] Return a better error message is unix socket path is too long.

---

sys/socket_unix.go

Fix typo in CreateUnixSocket error message

---

oci/spec_opts_unix.go

Address comments from https://github.com/containerd/containerd/pull/2257.

Improve WithUser comments and code style.

---

sys/socket_unix.go

(cherry picked from commit 81feacd39359a6c7934219723c4468d03f1d4700)

[release/1.0] Fix typo in CreateUnixSocket error message

---

api/1.1.pb.txt

While there were no changes to the core API for the 1.1 release, we
still need to lock down the 1.1 version of the API to follow the
process.

api: lock down api for 1.1 release

---

oci/spec_opts.go
oci/spec_opts_unix.go
oci/spec_opts_windows.go

In a few places we check for nil types when modifying a spec,
but in many cases we do not so we could get a panic if the
passed in type was not filled. Because the generated spec is
filled we will not notice this but users may get unexpected
panics.

Consistently add empty types where they are nil in spec

---

client_test.go

Remove architecture not included in buysbox image and ensures amd64 is included since it may already exist in the content store. (Using a separate namespace just for this test might be more difficult).

client: fix multi-platform pull test

---

cmd/ctr/commands/run/run.go
cmd/ctr/commands/run/run_unix.go
oci/spec_opts.go
oci/spec_opts_unix.go
oci/spec_unix_test.go

This is for my conversion of cri to use the containerd OCI functions.
I also added a Compose function because we all love functional programming...

Add a WithPrivileged OCI constructor and the options needed to build it

---

.travis.yml
container_linux_test.go

Fix the tests that were using an invalid container ID and fix travis script to not mask error exit return codes.

Fix broken tests; make sure we don't mask travis script exit codes

---

metadata/containers.go
metadata/containers_test.go

This allows a container's image and snapshot key to be updated via the
Update APIs.

Allow image and snapshotkey to be updated

---

.travis.yml

I assume we don't want to lock to Go 1.10.0.

Track Go 1.10 point releases in travis

---

RELEASES.md
releases/v1.1.0-rc.2.toml
version/version.go

This RC has a few more changes than the last but closes out the 1.1 related milestones
- CRI doesn't need nsenter https://github.com/containerd/cri/releases/tag/v1.0.0-rc.2
- GRPC update
- Client updates
- GC support for container referencing multiple snapshots
Note the release notes have no changed since the last RC with the exception of the support time frame moving along with the release train.

Prepare 1.1.0-rc.2

---

cmd/ctr/commands/run/run.go

Small fix to `ctr run --mount` help message

ctr: fix --mount help message

---

mount/lookup_test/lookup_linux_test.go
snapshots/overlay/check_test.go

Fixes a case where loopback devices wouldn't get cleaned up
when a test was being skipped
Signed-off-by: Christopher Jones <tophj@linux.vnet.ibm.com>

testing: cleanup loopback devices on test skip

---

cmd/ctr/commands/tasks/list.go

Removed, from `ctr tasks list` help usage for quiet flag, the text `& pid` as no pid is displayed as shown in the [line](https://github.com/containerd/containerd/blob/1381f8fddc4f826e12b48d46c9def347d5aa338a/cmd/ctr/commands/tasks/list.go#L54)

Update ctr tasks list usage for quiet flag

---

script/setup/install-critools
vendor.conf
vendor/github.com/containerd/cri/README.md
vendor/github.com/containerd/cri/pkg/server/sandbox_portforward.go
vendor/github.com/containerd/cri/pkg/server/sandbox_stop.go
vendor/github.com/containerd/cri/vendor.conf

Update `cri` to v1.0.0.
`cri` v1.0.0 release note https://github.com/containerd/cri/releases/tag/v1.0.0.

Update cri plugin to v1.0.0.

---

cmd/ctr/commands/events/events.go

Fixes #2308 
Channel handling was backwards, the bool represents more not closed. 

Correctly handle reading from events channel

---

cio/io_unix.go
container_linux_test.go

This adds `NewDirectIOWithTerminal` as well as a test for PTY (`TestContainerPTY`) to test that output has control codes.
Refs: #2307

Add NewDirectIOWithTerminal

---

archive/tar.go
cmd/ctr/commands/content/content.go
contrib/apparmor/apparmor.go
mount/temp.go
rootfs/init.go
services/tasks/local.go

This allows non-privileged users to use containerd. This is part of a
larger track of work integrating containerd into Cloudfoundry's garden
with support for rootless.
Also, runc already supports the `XDG_RUNTIME_DIR` so supporting the variable here as well makes sense.
Here is a link to our tracker on the containerd work: https://www.pivotaltracker.com/n/projects/1158420/search?q=label%3A%22containerd%22
[#156343575]
Signed-off-by: Claudia Beresford <cberesford@pivotal.io>

Use user-specific temp directory if set

---

cmd/ctr/commands/snapshots/snapshots.go

This adds gc.root label to snapshots created with prepare and commit via
the CLI. WIthout this, created snapshots get immediately garbage
collected. There may be a better solution but this seems to be a solid
stop gap.
We may also need to add more functionality around snapshot labeling for
the CLI but current use cases are unclear.
Signed-off-by: Stephen J Day <stevvooe@gmail.com>

cmd/snapshots: add gc.root to created snapshots

---

mount/mountinfo_linux.go
mount/mountinfo_linux_test.go

The mountinfo parser implemented via `fmt.Sscanf()` is slower than the one using `strings.Split()` and `strconv.Atoi()`. This rewrite helps to speed it up to a factor of 8x, here is a result from `go bench`:
```
BenchmarkParsingScanf-4            300          22294112 ns/op
BenchmarkParsingSplit-4           3000           2780703 ns/op
```
I tried other approaches, such as using `fmt.Sscanf()` for the first three (integer) fields and `strings.Split()` for the rest, but it still slows things down considerably:
```
BenchmarkParsingMixed-4           1000           8827058 ns/op
```
Note the old code uses `fmt.Sscanf` first, then a linear search for '-' field, then a split for the last 3 fields. The new code relies on a single split.
One other thing is, the new code is more future proof as it …

mount/mountinfo_linux: parser speed up

---

RUNC.md

Actually we have been testing containerd with the runc version that is defined
in vendor.conf rather than the one defined in RUNC.md. (`script/setup/install-runc`, https://github.com/containerd/containerd/pull/1957#discussion_r165016025).
This commit makes sure that the revision defined in vendor.conf is always the desired one.

fix RUNC.md vs vendor.conf mismatch

---

client.go
cmd/ctr/commands/content/fetch.go
cmd/ctr/commands/images/pull.go
rootfs/apply.go

A few races exist today if deleting an image during pull that are addressed by this PR.
1. `ctr image pull` does not hold the same lease between fetch and unpack
- Solved by getting a lease in the cli handler and passing to both functions
2. Rootfs apply holds no references while checking layer existence (stat from bottom up and layers can get garbage collected during check).
- Solved by reversing the check order from top down, using prepare to check existence of parent rather than stat
3. Image object can get removed while unpack is taking place
- Move image creation to after unpack, originally it existed before unpack because nothing else was holding reference to the content before leases
This did expose a common problematic pattern of relying on stat object + use object in the client. …

Fix image pull and remove race

---

cmd/containerd/builtins.go
metadata/buckets.go
plugin/plugin.go
restart/monitor/change.go
restart/monitor/monitor.go
restart/restart.go

This PR adds a restart manager that allows containerd to keep tasks running for containers.  It is built decoupled so that clients create and manage containers like always but and optionally set a state with the restart manager.
```go
container, err := client.NewContainer(ctx, id , restart.WithStatus(containerd.Running))
// update status
container.Update(ctx, restart.WithUpdatedStatus(containerd.Stopped))
// clear management 
container.Update(ctx, restart.WithNoRestart)
```

Add restart manager to containerd

---

README.md

containerd images moved based on website dir layout changes.

Reference new location for images

---

linux/runtime.go
runtime/runtime.go
services/tasks/local.go
windows/runtime.go

This renames the runtime interface to PlatformRuntime to denote the
layer at which the runtime is being abstracted.  This should be used to
abstract different platforms that vary greatly and do not have full
compat with OCI based binary runtimes.

Rename Runtime to PlatformRuntime

---

script/setup/install-critools
vendor.conf
vendor/github.com/containerd/cri/README.md
vendor/github.com/containerd/cri/pkg/server/container_create.go
vendor/github.com/containerd/cri/pkg/server/container_stats_list.go
vendor/github.com/containerd/cri/vendor.conf

Update `cri` plugin to v1.0.1 in release/1.1 branch.
I'm not sure why my `vndr` deleted some non-go files.
Release note: https://github.com/containerd/cri/releases/tag/v1.0.1

Update cri plugin to v1.0.1.

---

container.go
container_opts.go
oci/spec.go
oci/spec_opts.go
oci/spec_opts_test.go
oci/spec_opts_unix.go
oci/spec_opts_windows.go
oci/spec_unix.go
oci/spec_windows.go

This allows Go to build third party packages correctly without vendoring
issues what want to create their own SpecOpts.
Fixes #2289

Type alias spec in oci package

---

MAINTAINERS

Evan is an active contributor and been contributing for awhile now. He has been gaining expertise in the runtime code and has been helping review PRs. I think we should add him as a reviewer.

Add Evan Hazlett as a reviewer

---

client.go
content/proxy/content_reader.go
content/proxy/content_store.go
content/proxy/content_writer.go
snapshots/proxy/proxy.go

The client implementations for content store and snapshotters are just proxy implementations of the interface. Move these next to the other implementations. These could be used for any proxy implementation.

Move client implementations for content store and snapshotter

---

remotes/docker/fetcher.go
remotes/docker/fetcher_test.go

Ensures that the client can handle cases where the registry ignores content length.
Some registries ignore the content range and in some cases supports inconsistently. For example the Docker Hub appears to use Cloudflare and Cloudfront for serving content, cloudflare will ignore the content range while cloudfront uses it. This has lead to many cases of the mismatched layer size error on pull but without a consistent reproduction. 
Closes #2306

Fix size validation bug with some registries

---

remotes/docker/fetcher.go
remotes/docker/fetcher_test.go

Ensures that the client can handle cases where the registry ignores content range. This also has an impact on the CRI plugin.
Cherrypick of #2364

[release/1.1] Fix size validation bug on pull

---

remotes/docker/fetcher.go
remotes/docker/fetcher_test.go

Ensures that the client can handle cases where the registry ignores content range.
Cherrypick of #2364

[release/1.0] Fix size validation bug on pull 

---

releases/v1.1.1-rc.0.toml
version/version.go

This is a relatively light release. I think it is important though to get these changes out there, especially the image pull issue since it is impacting cri users.

Prepare 1.1.1-rc.0 release

---

version/version.go

Correction from prepare branch, normally the rc is put on the version for rc releases.

[release/1.1] Set rc.0 on version

---

services/server/server.go

Fixes upgrade issue where existing configs cause the max message size to get set to 0.

Ignore zero max message size in grpc config

---

cmd/containerd/command/main.go
cmd/containerd/command/oci-hook.go
cmd/ctr/commands/run/run.go
cmd/ctr/commands/run/run_unix.go
container_test.go
contrib/nvidia/nvidia.go

Update:
This PR now uses the `nvidia-container-cli` tool and a generic hook added to containerd.
Usage:
```
ctr run --rm --gpus 0 docker.io/nvidia/cuda:latest gpus nvidia-smi
```

Add nvidia gpu support

---

runtime/linux/proc/deleted_state.go
runtime/linux/proc/exec.go
runtime/linux/proc/init.go
runtime/linux/proc/init_state.go
runtime/linux/proc/process.go
runtime/proc/proc.go
runtime/shim/service.go

This separates the `proc` interface into a standalone package.  This will be used by the host process runtime referenced in https://github.com/containerd/containerd/issues/2352 to implement different platform specific process implementations.

Separate proc interfaces into standalone package

---

MAINTAINERS

Updates the maintainers file to align with the process we have been following for adding maintainers and reviewers.
I do not believe this to be a rules change as it is just reflecting the rules we have already been following. Any maintainer is free to disagree though if this doesn't sound accurate.

Update adding maintainer section

---

vendor.conf
vendor/github.com/containerd/cri/pkg/containerd/opts/container.go
vendor/github.com/containerd/cri/pkg/server/container_create.go

Update cri to v1.0.3 to fix 2 bugs.
Release note: https://github.com/containerd/cri/releases/tag/v1.0.3

[release/1.1] update cri to v1.0.3.

---

platforms/database.go
platforms/platforms.go
platforms/platforms_test.go

The normalization was being inconsistently applied causing a failure to match some platforms in manifest lists. Fix the matcher and normalization to be more consistent and add changes to parser to prevent the defaulted variants from being set in the platform structure.
Fixes #2409

Fix arm platform matching

---

platforms/database.go
platforms/platforms.go

Updates arm64 normalization to match what is described in https://github.com/golang/go/wiki/GoArm
The output of `Parse` should remain the same, the `Normalize` function should now have an empty variant for `arm64`.

Normalize arm64 to an empty variant

---

cmd/ctr/commands/commands.go
cmd/ctr/commands/commands_unix.go
cmd/ctr/commands/containers/containers.go
cmd/ctr/commands/run/run.go
cmd/ctr/commands/run/run_unix.go

Commit 05513284e7f7559a9064acf25b302a28f5f040cf exposed the "rootfs"
and "no-pivot" flags for the "containers" command, but it accidentally
removed them for "run" since package-level variables are initialized
before package-level init functions in golang. Hoisting these flags to
a package imported by both commands solves the problem.
Signed-off-by: Felix Abecassis <fabecassis@nvidia.com>

Move ContainerFlags to "commands" package

---

runtime/shim/client/client.go

This sets the shim's max procs to 2, like we already have hard coded in
the shim, with the env var so that it is set at go runtime boot.

Set shim max procs via env var

---

cio/io.go
cmd/ctr/commands/containers/containers.go
cmd/ctr/commands/tasks/delete.go
container.go

This adds a `Load` Opt for cio to load a tasks io/fifos without
attaching or starting the copy routines.
It adds the load method in `ctr` by default so that fifos or other IO
are removed from disk on delete methods inbetween command runs.  It is
not the default for all task loads for backwards compat. and a user may
want to keep io around to reuse or if log files are used.
Fixes #2421

Add cio.Load for loading io set

---

platforms/database.go
platforms/platforms.go
platforms/platforms_test.go

The normalization was being inconsistently applied causing a failure to match some platforms in manifest lists. Fix the matcher and normalization to be more consistent and add changes to parser to prevent the defaulted variants from being set in the platform structure.
(cherry picked from commit 37ab93e2c89fd8bc1e08c914246926fabf902893)

[release/1.1] Fix arm platform matching

---

releases/v1.1.1-rc.2.toml
vendor.conf
vendor/github.com/containerd/cri/pkg/server/container_create.go
vendor/github.com/containerd/cri/pkg/server/sandbox_run.go
vendor/github.com/containerd/cri/pkg/server/service.go
version/version.go

This creates the release file for 1.1.1-rc.2 and updates the version.
The vendor change is included and the only change for this release. This fixes a startup panic when starting up containerd on a filesystem which does not have d_type support.
Note: this is vendoring against the cri release branch rather than a tag. For the final release the tag will be made in cri and used here.

Prepare 1.1.1-rc.2

---

cmd/ctr/commands/plugins/plugins.go

`Ctr` interface follows the pattern `ctr <command> <subcommand>` except
for the `plugins` command which does not have subcommands. This feels
unnatural to certain users and they would expect that they can list
containerd plugins via `ctr plugins list`.
This commit implements their expectation so that `plugins` becomes a
command "group" and its `list` subcommand actually lists the plugins.
Signed-off-by: Danail Branekov <danailster@gmail.com>

Introduce plugins/list subcommand

---

.travis.yml

containerd now only supports Go 1.10+, and travis is not configured to run on older versions, so this check became redundant.

Remove Go version check in travis

---

vendor.conf
vendor/github.com/containerd/console/console_linux.go

Full diff: https://github.com/containerd/console/compare/9290d21dc56074581f619579c43d970b4514bc08...5d1b48d6114b8c9666f0c8b916f871af97b0a761
brings in https://github.com/containerd/console/pull/27 "console_linux: Fix race: lock Cond before Signal"
relates to https://github.com/moby/moby/issues/35865

update containerd/console to fix race: lock Cond before Signal

---

oci/spec_unix.go

relates to CVE-2018-10892
should probably be cherry-picked to release-branches

Add /proc/acpi and /proc/keys to masked paths

---

oci/spec_unix.go

relates to CVE-2018-10892
cherry-picking for cri to 1.1

[release/1.1] Add /proc/acpi and /proc/keys to masked paths

---

snapshots/btrfs/btrfs_test.go

With btrfs-prog 4.17 as shipped with Alpine 3.8 the btrfs tests
fail with:
ERROR: '/dev/loop1' is too small to make a usable filesystem
ERROR: minimum size for each btrfs device is 114294784
btrfs-prog commit 997f9977c243 ("btrfs-progs: mkfs: Prevent
temporary system chunk to use space in reserved 1M range")
changed the code to compute the minimum size for a btrfs size
and is the likely reason for this error.
Increase the size of the loop back device to 128MB for
the btrfs test.
With this fix, the containerd tests pass on Alpine 3.8,
tested in LinuxKit with kernel 4.14.53.
fixes #2447
Signed-off-by: Rolf Neugebauer <rolf.neugebauer@gmail.com>

test: Increase btrfs loopback device size to 128MB

---

snapshots/btrfs/btrfs_test.go

[release/1.1] test: Increase btrfs loopback device size to 128MB

---

releases/v1.1.1.toml
version/version.go

The final 1.1.1 release notes
Awaiting 1 more change on the `release/1.1` branch #2446

Prepare 1.1.1 release notes

---

remotes/docker/resolver.go

This is very useful to implement high level policies like registry mirror. See https://github.com/containerd/cri/pull/838

Support specifying host in resolver.

---

vendor.conf
vendor/github.com/containerd/cri/pkg/config/config.go
vendor/github.com/containerd/cri/pkg/ioutil/write_closer.go
vendor/github.com/containerd/cri/pkg/server/container_log_reopen.go
vendor/github.com/containerd/cri/pkg/server/container_start.go
vendor/github.com/containerd/cri/pkg/server/io/logger.go
vendor/github.com/containerd/cri/pkg/server/restart.go

Update `cri` version to 1.0.4. https://github.com/containerd/cri/releases/tag/v1.0.4
This is mainly to backport the `max-container-log-line-size` feature.

Update `cri` version to 1.0.4.

---

diff/walking/differ.go
rootfs/apply.go
services/leases/local.go

Addresses at least part of #2451...
In early-boot situations on systems without HWRNGs, `containerd` will hang on start until enough entropy has been gathered for `crypto/rand`'s `Read` to unblock. In these cases, `math/rand`'s `Read` is a more ideal choice since it's non-blocking.
Note that this is a much bigger deal than it was before patches for [CVE-2018-1108](https://nvd.nist.gov/vuln/detail/CVE-2018-1108) landed in the Linux kernel.
Signed-off-by: Dave Henderson <dhenderson@gmail.com>

Switching from crypto/rand to math/rand to avoid blocking

---

BUILDING.md

Including some build information about runc that has been helpful in my
development environment. This should allow one to build and install runc
next to containerd so that both can be worked on simultaneously.
Signed-off-by: Stephen Day <stephen.day@getcruise.com>

build: include instructions for runc build

---

api/next.pb.txt
windows/hcsshimtypes/next.pb.txt

An upstream change caused the options to now be ordered. Not sure how the order was determined before, but now it is sorted. This may need to be backported or a similar change made in release branches.

Fix options ordering in proto api txt files

---

content/testsuite/testsuite.go
snapshots/testsuite/testsuite.go

Go 1.11 uses a different formatting for maps, and now aligns values; running `gofmt -s -w` on this file resulted in this diff (see https://github.com/containerd/containerd/pull/2435);
```patch
diff --git a/content/testsuite/testsuite.go b/content/testsuite/testsuite.go
index 974c7cb8ed..d9ae9dc160 100644
--- a/content/testsuite/testsuite.go
+++ b/content/testsuite/testsuite.go
@@ -365,8 +365,8 @@ func checkLabels(ctx context.Context, t *testing.T, cs content.Store) {
rootTime := time.Now().UTC().Format(time.RFC3339)
labels := map[string]string{
-		"k1": "v1",
-		"k2": "v2",
+		"k1":                    "v1",
+		"k2":                    "v2",
"containerd.io/gc.root": rootTime,
}
@@ -402,7 +402,7 @@ func checkLabels(ctx context.Context, t *testing.T, cs content.Store) {
}
info.Labels = …
```

Workaround for gofmt change in Go 1.11

---

docs/ops.md

It is also useful when testing local changes, I just run:
sudo systemd-run -p Delegate=yes -p KillMode=process bin/containerd
Signed-off-by: Alban Crequy <alban@kinvolk.io>

Document how to use systemd-run

---

cmd/containerd/command/config.go
services/server/config.go
services/server/server.go

Allows creation of proxy plugins by name, type, and address in the daemon configuration. If multiple plugins are using the same address, containerd will only use a single grpc client conn for that address.

Add support for proxy plugins

---

api/next.pb.txt
windows/hcsshimtypes/next.pb.txt

An upstream change caused the options to now be ordered
(cherry picked from commit d3cd5f1d015da1f8a9107f0b58b9c614c4b153cf)

[release/1.1] Fix options ordering in proto api txt files

---

BUILDING.md

Go 1.11 includes a fix to os/user to be working in a static binary
(fixing https://github.com/golang/go/issues/23265). The fix requires
`osusergo` build tag to be set for static binaries, which is what
this commit documents.

BUILDING.md: add osusergo for static build

---

snapshots/native/native.go
snapshots/testsuite/testsuite.go

Unlike other snapshotters, the permission was previously set to 0700
unexpectedly.
Fix https://github.com/moby/buildkit/issues/520#issuecomment-406329609

native: set '/' permission to 0755

---

windows/process.go
windows/task.go

Compilation failed;
windows\process.go:124: Wrapf format %s has arg s of wrong type github.com/containerd/containerd/runtime.Status
windows\task.go:287: Wrapf format %d has arg id of wrong type string
windows\task.go:300: Wrapf format %d has arg t.id of wrong type string

Fix compilation failures on Go 1.11

---

metrics/cgroups/oom.go

This removes a log fatal on epoll wait for OOM events.

Don't fatal on epoll wait

---

snapshots/native/native.go
snapshots/testsuite/testsuite.go

Unlike other snapshotters, the permission was previously set to 0700
unexpectedly.
---
Cherry-pick https://github.com/containerd/containerd/pull/2485

[release/1.1] native: set '/' permission to 0755

---

oci/spec_opts_unix.go

This allows users to provide args for the process arguments while
creating the base spec with an image.  It provides the same symantics as
Docker where additional args replace the CMD while leaving the
ENTRYPOINT the same.

Add WithImageConfigArgs to replace CMD on image

---

cmd/ctr/commands/run/run.go
cmd/ctr/commands/run/run_unix.go
cmd/ctr/commands/run/run_windows.go
container_opts.go
oci/spec.go
oci/spec_opts.go
oci/spec_opts_test.go
oci/spec_unix.go
oci/spec_windows.go

We introduce a WithSpecFromFile option combinator to allow creation
simpler creation of OCI specs from a file name. Often used as the first
option in a `SpecOpts` slice, it simplifies choosing between a local
file and the built-in default.
The code in `ctr run` has been updated to use the new option, with out
changing the order of operations or functionality present there.
Signed-off-by: Stephen Day <stephen.day@getcruise.com>

oci: introduce WithSpecFromFile combinator

---

README.md

This function was removed from the containerd package in da1b5470cd26e9e2b4b1cd0100c876ce8db87471
Signed-off-by: Felix Abecassis <fabecassis@nvidia.com>

Remove reference to WithExit in README

---

cmd/ctr/commands/tasks/metrics.go

This is a very simple new subcommand to `ctr tasks` that just displays a few metrics from a given container task.  I wrote this as I was trying to understand how to deserialize a `*types.Metric.Data`, which is a `*google_protobuf1.Any` and there wasn't already an example in `ctr`.
I just picked a format and selected a few fields to display; happy to change any of these.

ctr: add new metrics subcommand

---

contrib/nvidia/nvidia.go

This helps with mappings so that we are not translating multiple times
from caller to hook.

Change gpu Capability type to string

---

runtime/restart/monitor/monitor.go
runtime/v2/manager.go

This cleans up persistent work dirs on TaskManager boot.  These dirs can
be left behind in a machine reboot.  The state in /run will not exist
but the work dir in the root does, we should cleanup work dirs when
tasks are not loaded.
This also improves error handling that would prevent the task manager
from loading when a single task fails to load or cleanup.

Cleanup workdirs on manager load

---

content/local/store.go
metadata/buckets.go
metadata/content.go
metadata/content_test.go
metadata/db.go
metadata/gc.go
metadata/gc_test.go
metadata/leases.go

Allow content ingests to be cleaned up during gc.  Use a default expiration on content ingests or make use of the lease expiration when provided.
closes #2400

Add content ingests to lease and gc

---

client.go
client_test.go
cmd/ctr/commands/content/fetch.go
cmd/ctr/commands/images/pull.go
export_test.go
image.go
import_test.go

Separate Fetch and Pull commands in client to distinguish between platform specific and non-platform specific operations.
`ctr images pull` with all platforms will now unpack all platforms.
`ctr content fetch` now supports platform flags.
This enables using the client to unpack on a specified platform which is useful for cross compilation in buildkit or using the client to drive a container/filesystem on a different platform.

Update client Image to have configurable platform

---

contrib/nvidia/nvidia.go

This is for consumers like Docker that manage a `docker-containerd`.

Add nvidia Opts to lookup containerd binary or hook path

---

cmd/ctr/commands/commands.go
cmd/ctr/commands/commands_unix.go
cmd/ctr/commands/containers/containers.go
cmd/ctr/commands/run/run.go
cmd/ctr/commands/run/run_unix.go

Commit 05513284e7f7559a9064acf25b302a28f5f040cf exposed the "rootfs"
and "no-pivot" flags for the "containers" command, but it accidentally
removed them for "run" since package-level variables are initialized
before package-level init functions in golang. Hoisting these flags to
a package imported by both commands solves the problem.
Signed-off-by: Felix Abecassis <fabecassis@nvidia.com>
(cherry picked from commit 5dd22a20afa959490436472076d5b8bb04dadb79)
Signed-off-by: Stephen Day <stephen.day@getcruise.com>

[release/1.1] Move ContainerFlags to "commands" package

---

client.go
client_opts.go
container.go
import.go
task.go

The default platform had previously been provided using the empty string. This change ensures that the platforms field is always filled in correctly and empty string is properly interpreted.
Also replace manual image struct creation with the image constructor which is there to do just that.
Fixes image objects returned by the client using an empty platform because the platform was empty on the image struct.
Also fixes an unintentional break in client backwards compatibility used by some tests. These uses can also be updated to remove `WithPlatform` or explicitly set the default.

Fix for empty platform

---

.travis.yml

Prior PR fixed the wrong use of `exit` built-in within a Travis script,
but lost the reporting of a failure result of CRI testing in the process.
Fixes: #2515

Fix loss of CRI test failure status in CI

---

cio/io_windows.go
cmd/ctr/commands/tasks/tasks_windows.go
runtime/v2/shim/util_windows.go

- Removes an unused and unneeded wait group.
- Reorders the code so that it doesnt overwrite the previous allocation
when creating a NewTask via ctr.exe
- Adds retry support to AnonDialer if the pipe does not exist. This will
retry up to the timeout for the pipe to exist and connect. This solves
the race between the containerd-shim-* start command and the
reinvocation.
FYI - @crosbymichael  @jhowardmsft

Various Windows fixes to support the runtime v2 shim workflow

---

client_test.go
image_test.go

This updates the tests to be more resilient to problems with the official Docker hub images having a periodic incomplete set of architectures. The K8s pause container is a more stable choice for testing the pull of specific architectures. Continue using the busybox image for all platform pull test since the set of architectures does not need to be fixed. Update the pull test to be explicit about expecting to pull and unpack for linux/amd64.

Update multi-arch image tests

---

archive/tar.go
archive/tar_opts.go
archive/tar_opts_windows.go
cmd/containerd/builtins.go
cmd/ctr/app/main.go
cmd/ctr/commands/install/install.go
install.go
install_opts.go
services/opt/path_unix.go
services/opt/path_windows.go
services/opt/service.go
vendor.conf
vendor/github.com/containerd/go-runc/command_other.go

This adds a way for users to programatically install containerd binary
dependencies.
With runtime v2 and new shim's being built, it will be a challenge to
get those onto machines.  Users would have to find the link, download,
place it in their path, yada yada yada.
With this functionality of a managed `/opt` directory, containerd can
use existing image and distribution infra. to get binarys, shims, etc
onto the system.
Configuration:
*default:* `/opt/containerd`
*containerd config:*
```toml
[plugins.opt]
path = "/opt/mypath"
```
Usage:
*code:*
```go
image, err := client.Pull(ctx, "docker.io/crosbymichael/runc:latest")
client.Install(ctx, image)
```
*ctr:*
```bash
ctr content fetch docker.io/crosbymichael/runc:latest
ctr install docker.io/crosbymichael/runc:latest
```
You can manage …

Add install support for binary images

---

services/tasks/local.go
services/tasks/local_unix.go
services/tasks/local_windows_v2.go

Removes the start dependency on V1 runtimes in the TasksService for:
// +build windows_v2. For unix and windows (v1) this code remains to load all
v1 runtimes as expected.

Refactors the TasksService requires per platform

---

container_linux_test.go
oci/spec_opts_unix.go

This change is to match Docker's implementaion of setting gid and groups
to 0 when no gid is specified but an explicit uid is set.
Fixes #2527

Set gid 0 when no group is specified

---

runtime/v2/README.md
runtime/v2/binary.go
runtime/v2/shim.go
runtime/v2/shim/shim.go
runtime/v2/shim/shim_unix.go
runtime/v2/shim/shim_windows.go
runtime/v2/shim_unix.go
runtime/v2/shim_windows.go

A fifo on unix or named pipe on Windows will be provided to the shim.
It can be located inside the `cwd` of the shim named "log".
The shims can use the existing `github.com/containerd/containerd/log` package to log debug messages.
Messages will automatically be output in the containerd's daemon logs with the correct fiels and runtime set.
Using a pipe allows containerd to reconnect after a reboot and collect logs from shims. 

Add shim log pipe for log forwarding to the daemon

---

Makefile
docs/man/containerd-config.1.md
docs/man/containerd-config.toml.5.md
docs/man/containerd.1.md
docs/man/ctr.1.md

The man page namespace is global, so in order to avoid colliding with
other man pages named "config.toml" rename ours to be more descriptive.
This also helps with discoverability (now tab-completion of 'man
containerd<tab>' will return the config man page), as well as making it
much cleaner from the perspective of distributions that want to package
containerd.
Signed-off-by: Aleksa Sarai <asarai@suse.de>

docs: man: rename config.toml(5) to be more descriptive

---

.mailmap
cmd/containerd-release/main.go
cmd/containerd-release/template.go
cmd/containerd-release/util.go

Updated the release tool to improve changes output to include sub-projects and automate the manual tasks which get done during the release. Currently the author remapping and including of subprojects is a time consuming process. This should make releasing much faster, making it easier to release the 1.2 betas and rcs.
- Allow inclusion of sub-project changes
- Order contributors by number of contributions
- Add mailmap
- Fix output formatting with extra new lines

Update release tool

---

oci/spec_opts_unix.go

The behaviour was changed in 99df1a9e11f3 ("Set gid 0 when no group is
specified"), part of #2529.
Take the opportunity to tighten up the grammar a bit too.

oci: Update docs for `oci.WithUserID`

---

runtime/v2/shim/shim_windows.go
runtime/v2/shim_windows.go

Switches the client/server direction of the shim-log pipe on Windows so
that the shim is the listener. This allows the containerd client to
reconnect as needed to the log streams.

switch shim log Windows client/server direction

---

vendor.conf
vendor/github.com/containerd/cri/pkg/config/config.go
vendor/github.com/containerd/cri/pkg/server/container_start.go
vendor/github.com/containerd/cri/pkg/server/sandbox_run.go

Update `cri` to v1.0.5. Here is the release note https://github.com/containerd/cri/releases/tag/v1.0.5.
This is mainly for minikube support. See https://github.com/kubernetes/minikube/pull/3040.

Update cri plugin to v1.0.5.

---

mount/mount_linux.go
mount/mount_linux_test.go
snapshots/testsuite/testsuite.go
sys/mount_linux.go
sys/mount_linux_test.go
sys/subprocess_unsafe_linux.go
sys/subprocess_unsafe_linux.s

Auto-detect longest common dir in lowerdir option and compact it if the
option size is hitting one page size. If does, Use chdir + CLONE to do
mount thing to avoid hitting one page argument buffer in linux kernel
mount.
More information is here #2497

support more overlayfs layers

---

cmd/ctr/commands/content/fetch.go
cmd/ctr/commands/images/pull.go

This makes it easier for callers to call this function and populate the
config without relying on specific flags across commands.

Move content.Fetch configuration to struct

---

platforms/platforms.go

This function is analogous to `regexp.MustCompile` and can simplify production
of a `Platform` from a hard-coded strings, e.g. for global variable
initialisation.

platforms: Add `MustParse`

---

cmd/ctr/commands/run/run_unix.go
oci/spec_opts_unix.go

These opts either inherit the parent cgroup device.list or append the
default unix devices like /dev/null /dev/random so that the container
has access.

Add opt for default unix device permissions

---

archive/tar_windows.go
vendor.conf
vendor/github.com/Microsoft/go-winio/fileinfo.go
vendor/github.com/Microsoft/go-winio/pipe.go
vendor/github.com/Microsoft/hcsshim/container.go
vendor/github.com/Microsoft/hcsshim/interface.go
vendor/github.com/Microsoft/hcsshim/legacy.go

Signed-off-by: John Howard <john.howard@microsoft.com>
Bumps hcsshim to v0.6.14 and go-winio to v0.4.10. Required as a pre-req to re-vendoring these to moby/moby (https://github.com/moby/moby/pull/37674) as containerd pulls in a previous version of go-winio and compilation otherwise fails.
@jterry75 FYI

Revendor Microsoft/hcsshim and go-winio

---

cmd/ctr/commands/run/run_unix.go
oci/spec_opts_unix.go

Signed-off-by: kadisi <iamkadisi@163.com>
if i create container with this commond:
```
ctr c create -c ./ctr.json -t docker.io/library/busybox:latest busybox
```
and `ctr.json` content is  :
```
{
"ociVersion": "1.0.1",
"process": {
"terminal": true,
"user": {
"uid": 0,
"gid": 0
},
"args": [
"sleep",
"100000"
],
... 
...
}
```
the args is `"sleep",  "100000"`
and then start container
` ctr task start busybox`
i found the args in container status (/run/containerd/io.containerd.runtime.v1.linux/default/busybox/config.json) is  `sh`
```
{
"ociVersion": "1.0.1",
"process": {
"terminal": true,
"user": {
"uid": 0,
"gid": 0
},
"args": [
"sh"
],
...
}
```
i think if the `args` is not nil in the runtime-specific spec config file, we should use the spec config file args values , not image config`s …

set args value of process if args is nil

---

README.md

All the website files has been moved to the containerd.io. The banner
should use the containerd.io file.

README.md: add missing banner

---

container_linux_test.go
oci/spec_opts_unix.go

Closes #2516
This can be used for non-root users binding to low ports.

Add WithAmbientCapabilities opt

---

.mailmap
cmd/containerd-release/main.go
cmd/containerd-release/template.go
cmd/containerd-release/util.go

Saves a step of adding the first line when creating a tag, this gets us a step close to auto tag creation in the release script.
Added option to create links in the changelog. This ensures that the links both exist in the git tag and in the Github release notes, additionally this ensures that the dependencies on Github are also linked, avoiding the creation of incorrect PR links for subprojects.
Updated mailmap to deduplicate John and use a real name for @kadisi (let me know if you would prefer to not have this here or I am using the wrong name)

Update release script

---

runtime/v2/runc/epoll.go
runtime/v2/runc/service.go

This improves shim locking where we only hold the lock for shim state, and not system level operations.

Shim locking improvements and context cancel

---

container_linux_test.go
runtime/v1/linux/proc/init.go
runtime/v1/shim/service.go
runtime/v2/runc/service.go

- Still KillAll if the task uses the hosts pid namespace
- Tests for both host pid namespace and normal cases
See [2258](https://github.com/containerd/containerd/issues/2558) for more context.
Closes #2558
Co-authored-by: Oliver Stenbom <ostenbom@pivotal.io>
Co-authored-by: Georgi Sabev <georgethebeatle@gmail.com>

Do not KillAll on task delete by default

---

runtime/v1/linux/proc/init.go

The error returned by `runtime.State` is a composed error [`fmt.Errorf("%s: %s", err, data)`](https://github.com/containerd/go-runc/blob/master/runc.go#L89). We can't use `os.IsNotExist` directly on it.
If the runc container is successfully deleted, but rootfs unmount fails [here](https://github.com/containerd/containerd/blob/master/runtime/v1/linux/proc/init.go#L272), we won't be able to load the task and retry deletion again, we'll keep getting:
```
failed to load task for sandbox: OCI runtime state failed: container "6a701add28f27c7e1442fa2c75354c86676ff22f3d9773b4d71f1014100c1205" does not exist: unknown
```
This is not urgent, because rootfs unmount won't fail in normal cases.

Fix `runc state` error handling.

---

contrib/nvidia/nvidia.go
contrib/seccomp/seccomp.go
remotes/docker/fetcher.go
remotes/docker/httpreadseeker.go

Fix type: 
./contrib/nvidia/nvidia.go (explaination -> explanation)
./contrib/seccomp/seccomp.go (formated -> formatted)
./remotes/docker/fetcher.go (considerd -> considered)
./remotes/docker/httpreadseeker.go (satisified -> satisfied)

Fix typo in contirb dir

---

oci/spec.go
oci/spec_opts.go
oci/spec_test.go
runtime/v2/runhcs/service.go

When creating a default OCI spec on Windows that is targeting the LCOW
platform it needs to contain a Windows section as well. This adds the
Windows section by default. It also protects against this case for all
OCI creation that doesnt use the OCI package in the runhcs-shim.

Add a Windows section for Linux oci on LCOW

---

mount/mount_linux.go
mount/mount_linux_test.go
snapshots/testsuite/testsuite.go
sys/env.go
sys/mount_linux.go
sys/mount_linux_test.go
sys/oom_unix.go
sys/oom_unix_test.go
sys/subprocess_unsafe_linux.go
sys/subprocess_unsafe_linux.s

I believe this fix makes sense in the 1.1.x line as well
---
Auto-detect longest common dir in lowerdir option and compact it if the
option size is hitting one page size. If does, Use chdir + CLONE to do
mount thing to avoid hitting one page argument buffer in linux kernel
mount.

[release/1.1] Cherrypick: Support >= 128 layers in overlayfs snapshots

---

cio/io.go
container_linux_test.go
runtime/v1/linux/proc/exec.go
runtime/v1/linux/proc/init.go
runtime/v1/linux/proc/io.go
vendor.conf
vendor/github.com/containerd/go-runc/io.go
vendor/github.com/containerd/go-runc/io_unix.go
vendor/github.com/containerd/go-runc/io_windows.go
vendor/github.com/containerd/go-runc/runc.go

This makes sure that runc does not get any valid IO for the pipe.  Some
builds and other containers will be stuck if they inspect stdin
expecially and its a pipe but not connected to any user input.

Don't provide IO when it's not set

---

cmd/ctr/commands/containers/containers.go
cmd/ctr/commands/run/run.go
cmd/ctr/commands/run/run_unix.go

Signed-off-by: Lifubang <lifubang@aliyun.com>
After Merged pull request #2544 
When run a command:
ctr run --config ./config.json --rootfs ./rootfs redis
or
ctr run --config ./config.json docker.io/library/redis:latest redis
The param Image/RootFS will be ignored. It will make the user puzzled when Image/RootFS's value is different from root.path in config.json.
I think pr #2544 may be can improved with a different solution, or if you accept pr #2544, you need to consider this PR.
Please check it. Thanks.
After this PR, more improves will be achieved, such as: ctr run --help, ctr c create --help.

fix when --config provided, don't need Image/RootFS

---

runtime/v1/linux/proc/exec_state.go
runtime/v1/shim/service.go

func (e *execProcess) delete(ctx context.Context) error {
e.wg.Wait()
...
}
delete exec process will wait for io copy finish, if wait here,
other process can not get lock of shim service.
1. add lock before and after p.Delete.
2. put lock after wait io copy in exec Delete.
1. run a container `sudo ctr run -d docker.io/library/busybox:latest b1 top`
2. create start.sh 
```
$ sudo ctr t exec --exec-id e1 -t b1 sh
/ # vi start.sh
/ # cat start.sh 
sleep 100 &
echo "ok"
/ # chmod +x start.sh 
/ # exit
```
3.   run start.sh which will wait for io .
```
$ sudo ctr t exec --exec-id e1 b1 sh -c '/start.sh'
ok
real	1m40.102s
user	0m0.024s
sys	0m0.040s
```
4.  run an other exec process will wait for `e1` finish.
```
$ time sudo ctr t exec --exec-id e1 b1 …
```

fix: modify lock location of exec delete avoid exec hang

---

cmd/ctr/commands/install/install.go
install.go
install_opts.go

This allows users to consume the install functionality but also install
to other areas instead of the managed `/opt` dir.
```bash
> ctr install --path /usr/local
```

Add optional install path

---

oci/spec_opts_unix.go

[Backported to release/1.1]
Can be used to conform to Docker engine behavior of adding additional
GIDs to spec when found in /etc/group of image filesystem

[release/1.1] Backport: With-helper for supplemental gid support

---

oci/spec_opts.go

I can do another temporary mount to convert uid to username, but I think it is better to just do it in `WithAdditionalGIDs` reusing the same temporary mount.

Support uid in WithAdditionalGIDs.

---

content/local/store_test.go
content/local/writer.go
content/testsuite/testsuite.go
diff/walking/differ.go
metadata/buckets.go
metadata/content.go
services/content/service.go
task.go

I found a bug in the content store which was causing a race condition in some cases in setting labels. The main issue is that the `Commit` was not consistently returning an already exists error. The local store implementation had an incorrect error check since `os.Rename` does not return an exists error. The metadata implementation was only checking this condition when the local store returned the error, allowing the new `Commit` to overwrite data for an existing blob. This was leading to labels getting stripped allowing a garbage collection while a blob was getting read due to another object attempting to create the same blob. This problem showed up in the case where the expected value of the blob is not known beforehand, not allowing us to either skip the Write+Commit or lease the …

Fix content store bug when already exists

---

.travis.yml

Many of the setup/dev programs installed are not used because no testing
is executed on GOOS=darwin builds. Makes sense to remove them and make
darwin runs much shorter.

Remove setup steps unnecessary when travis runs on darwin

---

benchmark_test.go
container_checkpoint_test.go
container_linux_test.go
container_test.go
daemon_config_linux_test.go
oci/spec_opts.go

If we are using an image config, we should by default add any additional
GIDs that are found from reading /etc/group, even if the default user is
root.
*The more I thought about this I'm not sure there is any downside to just handling additional GIDs by default when an image is involved. Other opinions? API users can still override; the CRI model will still work by collecting it's own GIDs and merging with any found in `/etc/group`*

Add additional GIDs by default if they exist in /etc/group

---

releases/v1.2.0-rc.toml

Prepare release notes ahead of 1.2.0-rc.1
I did a test generation of the release notes in a gist since the markdown won't show up from the toml.
https://gist.github.com/dmcgowan/20bc5d9e19fd91136135586465e31e81

Add release notes for containerd 1.2.0

---

vendor.conf
vendor/github.com/containerd/cri/pkg/containerd/opts/spec.go
vendor/github.com/containerd/cri/pkg/os/os.go
vendor/github.com/containerd/cri/pkg/server/container_create.go
vendor/github.com/containerd/cri/pkg/server/container_stop.go
vendor/github.com/containerd/cri/pkg/server/helpers.go
vendor/github.com/containerd/cri/pkg/server/sandbox_stop.go
vendor/github.com/containerd/cri/vendor.conf
vendor/github.com/opencontainers/selinux/go-selinux/label/label_selinux.go
vendor/github.com/opencontainers/selinux/go-selinux/selinux_linux.go
vendor/github.com/opencontainers/selinux/go-selinux/selinux_stub.go
vendor/github.com/opencontainers/selinux/go-selinux/xattrs.go

* Fixed an issue that HOSTNAME environment variable is not set in the container.
* Fixed an issue that a directory mount can override sub-directory mount.
* Fixed an issue that addtional gids from `/etc/group` in the image is not set.
* Fixed an issue that a container can't be stopped when container processes are accidentally moved out of container cgroups.
* Fix an issue that invalid selinux format is not rejected.

[release/1.1] Update cri to f117382467baf182382c44332bfbf488effc34bb.

---

oci/spec.go

This is to match the same mount options as the host.

Add nosuid,noexec,nodev to proc

---

cmd/ctr/commands/commands.go
cmd/ctr/commands/run/run_unix.go
oci/spec_opts.go

Add flag and With-helper to set NoNewPrivileges to false since it is on
by default in the default UNIX spec for containerd, but off by default
in Docker and CRI plugin use. This allows for easy testing with the feature
off for doing comparison.
Fixes: #2643

Add flag to ctr for running with "NoNewPrivileges: false"

---

cmd/ctr/commands/commands.go
cmd/ctr/commands/run/run_unix.go
oci/spec_opts_unix.go

Add flag and With-helper to set NoNewPrivileges to false since it is on
by default in the default UNIX spec for containerd, but off by default
in Docker and CRI plugin use. This allows for easy testing with it off
for comparison.

[release/1.1] Backport: Add flag to ctr for running with NoNewPrivileges: false

---

cmd/ctr/commands/run/run_unix.go

WithUser... helpers **do** support non-snapshot rootfs now.

Remove a TODO from the code comments that is complete

---

containers/containers.go

Signed-off-by: Starnop <starnop@163.com>
fix misspells in comments of containers/contaienrs.go including:
`s/nameapace/namespace`
`s/contaienr/container`

typo: fix misspells in comments of containers/contaienrs.go

---

cmd/ctr/commands/run/run_unix.go
cmd/ctr/commands/signals.go
cmd/ctr/commands/tasks/kill.go
container_opts.go
signal_map_linux.go
signal_map_unix.go
signal_map_windows.go
signals.go

The OCI image specification includes a StopSignal field in the image configuration, denoting the system call signal to be sent to the container to exit.  This commit adds an option to `ctr task kill` that reads the StopSignal from the image configuration and sends that signal.

ctr: make kill optionally use stop-signal

---

cmd/ctr/commands/resolver.go
remotes/docker/authorizer.go
remotes/docker/resolver.go
remotes/docker/resolver_test.go

This creates an authorizer interface which can be shared across multiple requests and more configurable for setting the authorization. This fixes a bug today which doesn't case sharing of tokens between resolve and fetch due to creation of a different base object which caches. Additionally this change moves the implementation closer to being focused on the OCI distribution specification while keeping the Docker specific authorization as a separate component.
An additional change can be done later to remove the credentials function after the callers have updated. There is also an additional change to allow the host/scheme specification to be more robust and have better support for mirrored configuration without needing to create multiple instances for each host. I wanted to keep that …

Update Docker resolver to pass in Authorizer interface

---

runtime/v2/binary.go
runtime/v2/runhcs/service.go
runtime/v2/shim/shim.go
runtime/v2/shim/shim_windows.go
runtime/v2/shim/shim_windows_test.go
runtime/v2/shim/util_windows.go

- Adds Windows shim reconnect logs support
- Decrease shim timeout on pipe not found
On Windows because of the way the log pipe is forwarded to the shim there is a
condition where the pipe listener may not yet be active when a client tries to
connect. To handle this case we allow polling on the file and retry on pipe not
found. This limits the pipe not found retry to 5 seconds but leaves the connect
timeout alone as if there is a listener we want to connect to it normally.
- Handle shim delete workdir on Windows

Various runhcs shim fixes

---

oci/spec_opts.go

Skip AdditionalGID's for LCOW oci spec

---

diff/lcow/lcow.go
vendor.conf
vendor/github.com/Microsoft/hcsshim/cmd/go-runhcs/runhcs.go
vendor/github.com/Microsoft/hcsshim/cmd/go-runhcs/runhcs_create.go
vendor/github.com/Microsoft/hcsshim/cmd/go-runhcs/runhcs_exec.go
vendor/github.com/Microsoft/hcsshim/ext4/internal/compactext4/compact.go
vendor/github.com/Microsoft/hcsshim/ext4/internal/format/format.go
vendor/github.com/Microsoft/hcsshim/ext4/tar2ext4/tar2ext4.go
vendor/github.com/Microsoft/hcsshim/ext4/tar2ext4/vhdfooter.go
vendor/github.com/Microsoft/hcsshim/internal/runhcs/container.go
vendor/github.com/Microsoft/hcsshim/internal/runhcs/util.go
vendor/github.com/Microsoft/hcsshim/internal/runhcs/vm.go
vendor/github.com/Microsoft/hcsshim/version.go

This change no longer requires the use of a UtlityVM on Windows to convert the
layer tar to an ext4 vhd for LCOW. This has a significant performance boost
that makes linux/amd64 layer extraction comparable to native Linux performance.

Remove dependency on tar2vhd for LCOW differ

---

platforms/cpuinfo.go

Opening PR as per https://github.com/containerd/containerd/issues/2693.
We are working on enabling support for ARM on Windows. As part of that, we have hit an issue when getCPUVariant gets called. getCPUVariant calls into getCPUInfo which expects Linux OS and as such it fails for Windows. This change uses GOARM global for Windows and Linux path is unaltered.
@estesp FYI

Add support to detect ARM variant on Windows

---

cmd/ctr/commands/pprof/pprof.go

The default duration of cpu profile collection in net/http/pprof is 30
seconds. User should have chance to set the specific duration for the
collection.

enhance: support specific duration for profile collection

---

remotes/docker/schema1/converter.go

containerd should cache empty label for docker schema1 image.
if not, the original empty layer will be non-empty layer and the image
config will be changed too. in this case, the image ID will be changed.
check the blob empty label to avoid changing image ID when repull docker
schema1 image.
#2678

bugfix: cache empty layer for docker schema1 image

---

content/content.go
content/local/store.go
content/local/writer.go
content/testsuite/testsuite.go
metadata/content.go
services/content/service.go

The local store could end up in a state where the writer is closed but the reference is locked after a commit on an existing object.
This PR cleans up Commit logic to always close the writer even after an error occurs, guaranteeing the reference is unlocked after commit.
Also
Adds a test to the content test suite to verify this behavior.
Updates the content store interface definitions to clarify the behavior.
Fixes #2708

Fix writer deadlock in local store

---

cmd/ctr/commands/tasks/metrics.go

add memory limit, pid info into metric subcommand, since moby also
show them. As blkio read/write IO need more calculation，not add them.
after this patch, format like:
```
$ sudo bin/ctr t metric vv2
ID     TIMESTAMP                                  
vv2    2018-10-16 08:59:13.749647292 +0000 UTC    
METRIC                   VALUE                               
memory.usage_in_bytes    376832                              
memory.limit_in_bytes    9223372036854771712                 
memory.stat.cache        331776                              
cpuacct.usage            12810199                            
cpuacct.usage_percpu     [1712085 2246486 437550 8414078]    
pids.current             1                                   
pids.limit …
```

ctr: add some metric item

---

cmd/ctr/commands/containers/containers.go

Closes #2568
Signed-off-by: Lifubang <lifubang@aliyun.com>
Before this commit, the Spec.value field  are incomprehensible:
```
root@dockerdemo:/opt/runctest/redis# ctr c info busybox
{
"ID": "busybox",
"Labels": null,
"Image": "docker.acmcoder.com/public/busybox:latest",
"Runtime": {
"Name": "io.containerd.runtime.v1.linux",
"Options": null
},
"Spec": {
"type_url": "types.containerd.io/opencontainers/runtime-spec/1/Spec",
"value": "eyJvY2lWZXJzaW9uIjoiM*************"
},
"SnapshotKey": "busybox",
"Snapshotter": "overlayfs",
"CreatedAt": "2018-08-23T05:16:17.371767147Z",
"UpdatedAt": "2018-08-23T05:16:17.371767147Z",
"Extensions": null
}
```
After the commit, there are some useful information for us:
```
root@dockerdemo:/opt/runctest/redis# …
```

decode spec in `ctr c info`

---

vendor.conf
vendor/github.com/opencontainers/runc/libcontainer/configs/config.go
vendor/github.com/opencontainers/runc/libcontainer/configs/intelrdt.go
vendor/github.com/opencontainers/runc/libcontainer/nsenter/nsexec.c
vendor/github.com/opencontainers/runc/libcontainer/user/lookup_unix.go
vendor/github.com/opencontainers/runc/vendor.conf

This includes fixes for user namespaces as well as a long standing bug
for running docker and containerd inside an lxc container.

Update runc to 58592df56734acf62e574865fe40b9e53e

---

README.md

With the website assets now moved out of this repo, the URL for the README banner needs to be updated. This PR sets it to a URL from the repo for CNCF's visual assets (which will be stable indefinitely).

Update banner URL

---

metrics/cgroups/metrics.go

Address issue/comment:
https://github.com/moby/moby/pull/37932#issuecomment-426599691
by allowing idempotence when adding a task to cgroups metrics collection...  

allow idempotence when adding a task to cgroup metrics collection

---

vendor.conf
vendor/github.com/containerd/cri/pkg/config/config.go
vendor/github.com/containerd/cri/pkg/server/container_create.go
vendor/github.com/containerd/cri/pkg/server/container_start.go
vendor/github.com/containerd/cri/pkg/server/container_status.go
vendor/github.com/containerd/cri/pkg/server/helpers.go
vendor/github.com/containerd/cri/pkg/server/image_pull.go
vendor/github.com/containerd/cri/pkg/server/sandbox_run.go
vendor/github.com/containerd/cri/pkg/server/sandbox_status.go
vendor/github.com/containerd/cri/pkg/server/sandbox_stop.go
vendor/github.com/containerd/cri/pkg/store/sandbox/netns.go
vendor/github.com/containerd/cri/vendor.conf
vendor/github.com/containerd/go-cni/cni.go

* Fixes https://github.com/containerd/cri/issues/942
* Fixes https://github.com/containerd/cri/issues/948
* Support runtime type specific configuration.
I also want https://github.com/containerd/cri/pull/950 in 1.2, but if we can't make it in time, I'm fine with adding it to a patch release.

Update cri to f913714917d2456d7e65a0be84962b1ce8acb487.

---

runtime/v2/shim/util.go

add validation for runtime name, if runtime name is invalid,
containerd will got panic.
The problem is found when I test with kata-shim, and write the wrong runtime
```
#ctr run --runtime containerd-shim-kata-v2 -d reg.docker.alibaba-inc.com/base/busybox:latest c1 top
ctr: transport is closing: unavailable
```
containerd panic log
```
panic: runtime error: index out of range
goroutine 129 [running]:
github.com/containerd/containerd/runtime/v2/shim.BinaryName(0xc42003f4e0, 0x17, 0x3, 0x6)
/home/ace/gosrc/src/github.com/containerd/containerd/runtime/v2/shim/util.go:76 +0x157
github.com/containerd/containerd/runtime/v2/shim.Command(0x7fcfef4c4f60, 0xc4205232c0, 0xc42003f4e0, 0x17, 0xc42035a000, 0x1f, 0xc4203cc640, 0x38, 0xc420315ac0, 0x3, ...) …
```

runtime-v2: add validation for runtime name

---

events.go

> NOTE: This is edge case raised in the testing. But it is hard to reproduce. That is why I don't add case for this.

bugfix: return the context error during event subscribe

---

.appveyor.yml
.travis.yml
contrib/Dockerfile.test

Already saw some breakage in https://github.com/moby/moby/pull/37358, so lets run it here as well
Changelog: https://tip.golang.org/doc/go1.11

Bump to Go 1.11.0

---

runtime/v1/shim/service.go

apply lock only around process map of shim service, avoid lock affect
other procs operations.
should also fix #2739 .

bugfix: optimize shim lock in runtime v1 avoid dead lock

---

linux/proc/exec_state.go
linux/shim/service.go

Backport https://github.com/containerd/containerd/pull/2624 to release/1.1.
For issues like https://github.com/containerd/containerd/issues/2438.
Exec deletion can take forever if the exec leaks processes in the container. This will cause:
1) Process leakage in the system;
2) Goroutine leakage in `containerd-shim` and `cri`;
3) containerd-shim hangs forever.
This doesn't fix 1) and 2), but it does fix 3).
In any case, `containerd-shim` shouldn't hang, so that users can at least stop the bad container.
@lbernail @Ace-Tang

[release/1.1] Backport: modify lock location of exec delete avoid exec hang

---

.appveyor.yml

Appveyor choco install updated to a newer version of mingw which at the
moment is breaking Golang 1.11 compiles.

Fix mingw version back to working version with Golang

---

Makefile.linux

These break the build on i386 in some very specific circumstances (where
/bin/sh breaks when handling unicode), and are completely useless when
it comes to actually building the project.
Signed-off-by: Aleksa Sarai <asarai@suse.de>

makefile: remove emoji

---

ADOPTERS.md
README.md

Per request of the CNCF, adding known containerd adopters to GitHub
project.

Add ADOPTERS.md file

---

linux/shim/service.go

We also need this fix in release 1.1.
I think this is the last piece for https://github.com/containerd/containerd/issues/2709.
Note that the lock location for `Create` is not updated in this cherry-pick, because:
1) It is not necessary. `Create` should be called as the first function, and no other functions will be called at the same time.
2) It is matches the behavior of shim v2 https://github.com/containerd/containerd/blob/master/runtime/v2/runc/service.go#L226.
3) In `release/1.1`, all logic is in `proc.New`. There is no way for us to add the lock at the same place with https://github.com/containerd/containerd/pull/2743.
/cc @Ace-Tang

[release/1.1] cherry-pick: optimize shim lock in runtime v1

---

services/tasks/local.go

make user know correct error when start a non created status container.
Before this patch, if we start a non created container, we will get error 
```
$ sudo ctr t start vv2
ctr: mkdir /var/run/containerd/io.containerd.runtime.v2.task/default/vv2: file exists: unknown
```
After the patch , we can get more exact error message
```
$ sudo ctr t start -d s3
ctr: cannot start a non created status container s3
```

check task existence before new task

---

cmd/ctr/commands/run/run.go
cmd/ctr/commands/run/run_unix.go
docs/rootless.md

* ctr: add --cgroup for oci.WithCgroup
* add docs/rootless.md
No change on the daemon side at all. (CRI plugin will support "cgroupless" configuration in a separate PR)
- - -
Replaces https://github.com/containerd/containerd/pull/2006
Closes https://github.com/containerd/containerd/issues/2262
Relates to https://github.com/moby/moby/pull/38050

Rootless mode

---

runtime/v1/shim/service.go
runtime/v2/runc/service.go
runtime/v2/shim/shim_unix.go

1. avoid dead lock during kill, fetch allProcesses before handle events
2. use argu's ctx instead of context.Backgroud() in openlog

enhance: update v1/v2 runtime

---

runtime/v1/shim/reaper.go

Per discussion at https://github.com/containerd/containerd/pull/2762#issuecomment-436436146, we decided not to discard events, because it breaks the assumption that client can rely on `TaskExit` events to detect container stop.
If `TaskExit` events can be discarded, the client has to do periodically state check, which is not ideal.

Partially revert the event discard change in #2748.

---

containerd.service
docs/ops.md

When running containerd inside LXC, due to systemd being unable to execute
`modprobe overlay` inside the container (module is already loaded in host kernel).
This patch adds a `-` prefix to the `ExecStartPre` command, so that failures
are ignored, and the service can start as usual.
fixes https://github.com/containerd/containerd/issues/2772

Ignore modprobe failures in ExecStartPre (systemd unit)

---

containerd.service
docs/ops.md

Backport of https://github.com/containerd/containerd/pull/2776 for the 1.1 branch
fixes https://github.com/containerd/containerd/issues/2772 for the 1.1.x releases
```
git checkout -b 1.1_backport_ignore_modprobe_failures upstream/release/1.1
git cherry-pick -s -S -x 555ea3fb43505512bba51563183a80b2d4a1d028
```
When running containerd inside LXC, due to systemd being unable to execute
`modprobe overlay` inside the container (module is already loaded in host kernel).
This patch adds a `-` prefix to the `ExecStartPre` command, so that failures
are ignored, and the service can start as usual.

[release/1.1] cherry-pick: Ignore modprobe failures in ExecStartPre (systemd unit)

---

api/next.pb.txt
windows/hcsshimtypes/next.pb.txt

Backport of https://github.com/containerd/containerd/pull/2470 for the release/1.0 branch;
```
git checkout -b 1.0_backport_fix_checkprotos upstream/release/1.0
git cherry-pick -s -S -x d3cd5f1d015da1f8a9107f0b58b9c614c4b153cf
```
An upstream change caused the options to now be ordered

[release/1.0] Fix options ordering in proto api txt files

---

containerd.service
docs/ops.md

Backport of https://github.com/containerd/containerd/pull/2776 for the 1.2 branch
fixes https://github.com/containerd/containerd/issues/2772 for the 1.2.x releases
```
git checkout -b 1.2_backport_ignore_modprobe_failures upstream/release/1.2
git cherry-pick -s -S -x 555ea3fb43505512bba51563183a80b2d4a1d028
```
When running containerd inside LXC, due to systemd being unable to execute
`modprobe overlay` inside the container (module is already loaded in host kernel).
This patch adds a `-` prefix to the `ExecStartPre` command, so that failures
are ignored, and the service can start as usual.

[release/1.2] cherry-pick: Ignore modprobe failures in ExecStartPre (systemd unit)

---

containerd.service
docs/ops.md

Backport of https://github.com/containerd/containerd/pull/2776 for the 1.0 branch
fixes https://github.com/containerd/containerd/issues/2772 for the 1.0.x releases
```
git checkout -b 1.0_backport_ignore_modprobe_failures upstream/release/1.0
git cherry-pick -s -S -x 555ea3fb43505512bba51563183a80b2d4a1d028
```
When running containerd inside LXC, due to systemd being unable to execute
`modprobe overlay` inside the container (module is already loaded in host kernel).
This patch adds a `-` prefix to the `ExecStartPre` command, so that failures
are ignored, and the service can start as usual.

[release/1.0] cherry-pick: Ignore modprobe failures in ExecStartPre (systemd unit)

---

linux/shim/client/client.go

Backport of https://github.com/containerd/containerd/pull/2423 for the 1.0 branch
```
git checkout -b 1.0_backport_shim_procs upstream/release/1.0
git cherry-pick -s -S -x 68e144c63791fc4982afedc0fe6fcbf924b5d59b
```
This sets the shim's max procs to 2, like we already have hard coded in
the shim, with the env var so that it is set at go runtime boot.

[release/1.0 backport] Set shim max procs via env var

---

linux/shim/client/client.go

Backport of https://github.com/containerd/containerd/pull/2423 for the 1.1 branch
```
git checkout -b 1.1_backport_shim_procs upstream/release/1.1
git cherry-pick -s -S -x 68e144c63791fc4982afedc0fe6fcbf924b5d59b
```
This sets the shim's max procs to 2, like we already have hard coded in
the shim, with the env var so that it is set at go runtime boot.

[release/1.1 backport] Set shim max procs via env var

---

vendor.conf
vendor/github.com/containerd/cri/pkg/server/instrumented_service.go

Changes: https://github.com/containerd/cri/compare/ac043660063cf4fd93aa17aeb8bfcaf2d7d249ab...bad0ae1102e1bf9e53876f75eacc42bc97cfb557
Bug fixes:
* Do not log `AuthConfig`. https://github.com/containerd/cri/issues/960

[release/1.1] Update cri to bad0ae1102e1bf9e53876f75eacc42bc97cfb557.

---

reaper/reaper.go

Cherry-pick #2748
Cherry-pick #2770 
This increases the buffer size for process exit subscribers. ~It also
implements a non-blocking send on the subscriber channel.  It is better
to drop an exit even than it is to block a shim for one slow subscriber.~

[release/1.1] cherry-pick: Increase reaper buffer size

---

runtime/v1/shim/service.go
runtime/v2/runc/service.go
runtime/v2/shim/shim_unix.go

1. avoid dead lock during kill, fetch allProcesses before handle events
2. use argu's ctx instead of context.Backgroud() in openlog
Brings #2769 to `release/1.2` branch for 1.2.1

[release/1.2] Cherrypick v1/v2 runtime fix

---

contrib/nvidia/nvidia.go

Otherwise the proper kernel mods might not be loaded when trying to
stand up a container with GPUs, resulting eg in the `nvidia-container-cli`
command failing because `/dev/nvidia-modeset` wasn't around.
There performance impact of having `nvidia-container-cli` check for kernel
modules being loaded every time is negligible.
Signed-off-by: Jean Rouge <jer329@cornell.edu>

Adding a --load-kmods flag to the NVIDIA OCI hook

---

runtime/proc/proc.go
runtime/v1/linux/proc/exec.go
runtime/v1/linux/proc/exec_state.go
runtime/v1/linux/proc/init.go
runtime/v1/linux/proc/init_state.go

There were races with the way process states.  This displayed in ways,
especially around pausing the container for atomic operations.  Users
would get errors like, cannnot delete container in paused state and
such.
This can be eaisly reproduced with `docker` and the following command:
```bash
> (for i in `seq 1 25`; do id=$(docker create  alpine usleep 50000);docker start $id;docker commit $id;docker wait $id;docker rm $id; done)
```
This two issues that this fixes are:
* locks must be held by the owning process, not the state operations.
* If a container ends up being paused but before the operation
completes, the process exists, make sure we resume the container before
setting the the process as exited.

Fix process locking and state management

---

vendor.conf
vendor/github.com/opencontainers/runc/README.md
vendor/github.com/opencontainers/runc/libcontainer/README.md
vendor/github.com/opencontainers/runc/libcontainer/configs/config.go
vendor/github.com/opencontainers/runc/libcontainer/configs/intelrdt.go
vendor/github.com/opencontainers/runc/libcontainer/configs/namespaces_linux.go
vendor/github.com/opencontainers/runc/libcontainer/configs/namespaces_syscall.go
vendor/github.com/opencontainers/runc/libcontainer/devices/devices.go
vendor/github.com/opencontainers/runc/libcontainer/nsenter/README.md
vendor/github.com/opencontainers/runc/libcontainer/nsenter/nsexec.c
vendor/github.com/opencontainers/runc/libcontainer/system/linux.go
vendor/github.com/opencontainers/runc/libcontainer/system/unsupported.go
vendor/github.com/opencontainers/runc/libcontainer/user/lookup_unix.go
vendor/github.com/opencontainers/runc/libcontainer/user/user.go
vendor/github.com/opencontainers/runc/vendor.conf

- https://github.com/containerd/containerd/pull/2555 Update runc vendor
- Synchronizes with the version used by buildkit, which is currently ahead of containerd
- https://github.com/containerd/containerd/pull/2674 Update runc to 00dc70017d222b178a002ed30e9321b126
- https://github.com/containerd/containerd/pull/2724 Update runc to 58592df56734acf62e574865fe40b9e53e
- includes fixes for user namespaces as well as a long standing bug
for running docker and containerd inside an lxc container.
- https://github.com/containerd/containerd/pull/2788 Update runc to 10d38b660a77168360df3522881e2dc2be
```
git checkout -b 1.1.1_backport_bump_runc upstream/release/1.1
git cherry-pick -s -S -x ddc53c9cd277222025023d7ff51d1accbd9eea90
git cherry-pick -s -S -x 806a8f98bb5fbb8826cd8fc1e576f6fd406a26ae
git …
```

[release/1.1 backport] Update runc to 10d38b660a77168360df3522881e2dc2be

---

cmd/ctr/commands/containers/containers.go

For we support `ctr c create -t docker.acmcoder.com/public/busybox:latest topdemo top -d 1`.
But `ctr c create --help` doesn't indicate it:
```
root@dockerdemo:~/gocode/src/github.com/containerd/containerd# ctr c create --help
NAME:
ctr containers create - create container
USAGE:
ctr containers create [command options] [flags] Image|RootFS CONTAINER
OPTIONS:
```
After this change:
```
root@dockerdemo:~/gocode/src/github.com/containerd/containerd# bin/ctr c create --help
NAME:
ctr containers create - create container
USAGE:
ctr containers create [command options] [flags] Image|RootFS CONTAINER [COMMAND] [ARG...]
OPTIONS:
```

change args usage for ctr c create

---

runtime/v1/shim/service.go

apply lock only around process map of shim service, avoid lock affect
other procs operations.
Cherry-pick: #2743

[release/1.2] Cherry-pick: optimize shim lock in runtime v1

---

cmd/ctr/commands/tasks/exec.go

I think we should support `-d` flag when run `ctr t exec`.
For example:
```
root@dockerdemo:~/gocode/src/github.com/containerd/containerd# bin/ctr t exec --exec-id test2 -d redis sleep 1000
root@dockerdemo:~/gocode/src/github.com/containerd/containerd# bin/ctr t ps redis
PID     INFO
5851    &ProcessDetails{ExecID:redis,}
6279    &ProcessDetails{ExecID:test2,}
```

add flag -d for ctr t exec to run a service in container

---

runtime/v1/linux/proc/init.go

`KillAll` should be locked.
Previously, it was called in [`delete` (process state locked)](https://github.com/containerd/containerd/blob/release/1.1/linux/proc/init.go#L293) and [`checkProcesses` (shim locked)](https://github.com/containerd/containerd/blob/release/1.1/linux/shim/service.go#L470), both are locked.
However, recently we optimized the locks. [`checkProcesses` doesn't hold a shim lock for process operations any more](https://github.com/containerd/containerd/commit/665815b62730523666a80d68f8fbb27e6fe7425e#diff-35a5ec8c1a43230b5166d81b6727db13).
In release/1.2 and HEAD, `KillAll` is not called in `delete` any more, so we can simply hold a lock in `KillAll` directly.
In release/1.1, since `KillAll` is still called in `delete` (process state locked), we need a private `killAll` …

Lock `KillAll`.

---

runtime/v1/shim/service_linux.go
runtime/v2/runc/service_linux.go

There is an issue in moby:  https://github.com/moby/moby/issues/38064
It's hard to reproduce, but if you are lucky, you'll reproduce it successfully with probability about 0.1. Wish you success. If someone can write a go program with libcontainerd to reproduce it, it will help for us to debug it.
For container in created state, if pipe in broken, moby will call DeleteTask, and it will cause a wait in: 
https://github.com/containerd/containerd/blob/e76a8879eb10594113d70556c80dd2e456202e22/runtime/v1/linux/proc/init.go#L252 
Because in https://github.com/containerd/containerd/blob/e76a8879eb10594113d70556c80dd2e456202e22/runtime/v1/shim/service_linux.go#L78  , if pipe out broken, it will set wg done.
But in …

fix pipe in broken may cause shim lock forever

---

remotes/docker/authorizer.go

Check if credentials function was passed with resolver config before calling it to avoid a panic when the server wants to do basic auth. The token variant already has this check.

remotes: avoid panic with default resolver conf

---

runtime/proc/proc.go
runtime/v1/linux/proc/exec.go
runtime/v1/linux/proc/exec_state.go
runtime/v1/linux/proc/init.go
runtime/v1/linux/proc/init_state.go

There were races with the way process states.  This displayed in ways,
especially around pausing the container for atomic operations.  Users
would get errors like, cannnot delete container in paused state and
such.
This can be eaisly reproduced with `docker` and the following command:
```bash
> (for i in `seq 1 25`; do id=$(docker create  alpine usleep 50000);docker start $id;docker commit $id;docker wait $id;docker rm $id; done)
```
This two issues that this fixes are:
* locks must be held by the owning process, not the state operations.
* If a container ends up being paused but before the operation
completes, the process exists, make sure we resume the container before
setting the the process as exited.

[release/1.2] Fix process locking and state management

---

runtime/v1/shim/service_linux.go
runtime/v2/runc/service_linux.go

backport of https://github.com/containerd/containerd/pull/2807 for the 1.2 branch
relates to https://github.com/moby/moby/issues/38064
```
git checkout -b 1.2_backport_shimlockwhenstdinclose upstream/release/1.2
git cherry-pick -s -S -x b3438f7a6f63849d2179a2a76b804aea460affd9
git cherry-pick -s -S -x e76a8879eb10594113d70556c80dd2e456202e22
git push -u origin
```

[release/1.2] fix pipe in broken may cause shim lock forever

---

linux/shim/service_linux.go

backport of https://github.com/containerd/containerd/pull/2807 for the 1.1 branch (only the V1 changes)
relates to https://github.com/moby/moby/issues/38064
```
git checkout -b 1.1_backport_shimlockwhenstdinclose upstream/release/1.1
git cherry-pick -s -S -x e76a8879eb10594113d70556c80dd2e456202e22
git push -u origin
```
cherry-pick wasn't clean because the `v1` commit contained a comment-only
change in a `v2` file, but trivial to resolve

[release/1.1] fix pipe in broken may cause shim lock forever for runtime v1

---

cmd/ctr/commands/tasks/delete.go

After we kill an exec task, we can't rerun a new exec with the same name. For example:
```
root@dockerdemo:~/containerd# bin/ctr t exec -d --exec-id test1000 redis sleep 1000
root@dockerdemo:~/containerd# bin/ctr t ps redis
PID     INFO
1703    &ProcessDetails{ExecID:redis,}
6448    &ProcessDetails{ExecID:test1000,}
root@dockerdemo:~/containerd# bin/ctr t kill --exec-id test1000 -s 9 redis
root@dockerdemo:~/containerd# bin/ctr t ps redis
PID     INFO
1703    &ProcessDetails{ExecID:redis,}
root@dockerdemo:~/containerd# bin/ctr t exec -d --exec-id test1000 redis sleep 1000
ctr: id test1000: already exists
```
We have a interface `DeleteProcess`, so we can use it in ctr, for example(After this patch).
```
root@dockerdemo:~/containerd# bin/ctr t delete --exec-id test1000 redis …
```

add ctr delete --exec-id to help debug DeleteProcess

---

linux/proc/init.go

[release/1.1] Cherrypick: Lock `KillAll`.

---

client.go
cmd/ctr/commands/commands.go
cmd/ctr/commands/containers/containers.go
cmd/ctr/commands/run/run_unix.go
container.go
container_checkpoint_opts.go
container_checkpoint_test.go
container_opts_unix.go
container_restore_opts.go
images/mediatypes.go

This refactors the checkpoint and restore to be on the containerd client.  
ToDo
Example
```
$> ctr run --runtime io.containerd.runc.v1 -d docker.io/library/redis:alpine redis
$>  ctr c checkpoint --rw --task redis checkpoint/redis:20180911
$> ctr c restore redis-debug checkpoint/redis:20180911
$> ctr c restore --live redis-debug checkpoint/redis:20180911
```
Refs #2602

Refactor checkpoint and restore to client

---

releases/v1.1.5.toml
version/version.go

Feel free to comment if the anything is missing or there is any mistake.

Prepare 1.1.5 release notes

---

cmd/ctr/commands/tasks/checkpoint.go

when use `ctr t checkpoint`, runtime name should get from container
info, but not passed by flag, since task has already running with
specified runtime
remove flag `ctr task checkpoint --runtime`

fix: should get runtime name from container info

---

client_test.go
cmd/containerd-shim/main_unix.go
container_linux_test.go
runtime/v1/linux/runtime.go
runtime/v1/shim.go
runtime/v1/shim/client/client.go

Closes #2606
When waiting for a golang cmd to exit, golang will block exiting on all of its process streams being closed. Currently, the containerd server is configuring each shim processes output (stdout/stderr) to redirect to the server’s stdout/stderr. When running the containerd restart tests, these do not get closed - and waiting for the server process to finish hangs.
Since restarting the containerd server does not restart the shim processes, the shims output streams *could* still be outputting logs, never to be closed. The aim of this PR is to let the shim instead log to named pipes.
* When a new task is created, the server:
* creates a new named pipe (one for stdout and one for stderr).
* assigns the start shim command stdout/err to the write ends of these pipes
* schedules a go …

Use named pipes for shim logs

---

runtime/v1/linux/proc/deleted_state.go
runtime/v1/linux/proc/exec.go
runtime/v1/linux/proc/exec_state.go

@crosbymichael As I mentioned in #2823 , there will be a process locking state when waiting for one exec process IO finished.
I'm so sorry to say that I think this is because of your PR #2803 , you modify the location of process lock in delete func(#2624 ).
The correct location: https://github.com/Ace-Tang/containerd/blob/079292e3fc20b7319b6e7c35dcda6864bb128f1c/runtime/v1/linux/proc/exec_state.go#L170-L177 
After your modify: https://github.com/containerd/containerd/blob/release/1.2/runtime/v1/linux/proc/exec.go#L103-L108 
So, when exec proc A is waiting for it's IO finished, it will hold A's process lock.
When at this time, exec proc B is finished, shim service will trigger `checkProcesses(e runc.Exit)`, it will call A.Pid(), but A.Pid() need A's process lock, so it is stucked, and …

Fixes: shim service event blocked when waiting for IO finished

---

errdefs/grpc.go
filters/parser.go
metadata/containers.go
metadata/images.go
metadata/leases.go
windows/io.go

In many cases code is calling errors.Wrapf with an arbitrary string
instead of a format string. This causes confusing errors when the
wrapped error message contains '%' characters.
This change replaces such calls with calls to errors.Wrap.
Signed-off-by: John Starks <jostarks@microsoft.com>

Eliminate misuses of errors.Wrapf

---

oci/spec.go

This ports https://github.com/moby/moby/pull/38299 to containerd
relates to https://github.com/moby/moby/issues/38285
While looking through the Moby source code was found /proc/asound to be shared
with containers as read-only.
This can lead to two information leaks.
---
**Leak of media playback status of the host**
Steps to reproduce the issue:
- Listen to music/Play a YouTube video/Do anything else that involves sound
output
- Execute docker run --rm ubuntu:latest bash -c "sleep 7; cat
/proc/asound/card*/pcm*p/sub*/status | grep state | cut -d ' ' -f2 | grep
RUNNING || echo 'not running'"
- See that the containerized process is able to check whether someone on the
host is playing music as it prints RUNNING
- Stop the music output
- Execute the command again (The sleep is delaying the …

Add /proc/asound to masked paths

---

oci/spec_unix.go

Backport of https://github.com/containerd/containerd/pull/2846 for the 1.0 branch
While looking through the Moby source code was found /proc/asound to be shared
with containers as read-only.
This can lead to two information leaks.
---
**Leak of media playback status of the host**
Steps to reproduce the issue:
- Listen to music/Play a YouTube video/Do anything else that involves sound
output
- Execute docker run --rm ubuntu:latest bash -c "sleep 7; cat
/proc/asound/card*/pcm*p/sub*/status | grep state | cut -d ' ' -f2 | grep
RUNNING || echo 'not running'"
- See that the containerized process is able to check whether someone on the
host is playing music as it prints RUNNING
- Stop the music output
- Execute the command again (The sleep is delaying the output because
information regarding …

[release/1.0 backport] Add /proc/asound to masked paths

---

oci/spec_unix.go

Backport of https://github.com/containerd/containerd/pull/2846 for the 1.1 branch
This ports https://github.com/moby/moby/pull/38299 to containerd
relates to https://github.com/moby/moby/issues/38285
While looking through the Moby source code was found /proc/asound to be shared
with containers as read-only.
This can lead to two information leaks.
---
**Leak of media playback status of the host**
Steps to reproduce the issue:
- Listen to music/Play a YouTube video/Do anything else that involves sound
output
- Execute docker run --rm ubuntu:latest bash -c "sleep 7; cat
/proc/asound/card*/pcm*p/sub*/status | grep state | cut -d ' ' -f2 | grep
RUNNING || echo 'not running'"
- See that the containerized process is able to check whether someone on the
host is playing music as it prints RUNNING …

[release/1.1 backport] Add /proc/asound to masked paths

---

oci/spec.go

Backport of https://github.com/containerd/containerd/pull/2846 for the 1.2 branch
```
git checkout -b 1.2_backport_mask_asound upstream/release/1.2
git cherry-pick -s -S -x 70084ea6c3bb92a772b5e3f23c30879c32166bef
git push -u origin
```
This ports https://github.com/moby/moby/pull/38299 to containerd
relates to https://github.com/moby/moby/issues/38285
While looking through the Moby source code was found /proc/asound to be shared
with containers as read-only.
This can lead to two information leaks.
---
**Leak of media playback status of the host**
Steps to reproduce the issue:
- Listen to music/Play a YouTube video/Do anything else that involves sound
output
- Execute docker run --rm ubuntu:latest bash -c "sleep 7; cat …

[release/1.2 backport] Add /proc/asound to masked paths

---

vendor.conf
vendor/github.com/opencontainers/runc/libcontainer/configs/config.go

Backport of https://github.com/containerd/containerd/pull/2838 for the 1.2 release branch
```
git checkout -b 1.2_backport_update_runc_1.0-rc6 upstream/release/1.2
git cherry-pick -s -S -x 97dd5df66fb70cf3ec0c6e4bdb17f01d1d6936d9
```
minor conflict in vendor.conf, but trivial to fix

[release/1.2 backport] Update runc to v1.0.0-rc6

---

runtime/v1/linux/proc/deleted_state.go
runtime/v1/linux/proc/exec.go
runtime/v1/linux/proc/exec_state.go

I think release 1.2 may need #2826 .
Backport of #2826  for the 1.2 release branch
```
git cherry-pick -xsS bbc2a995f97c84670ba47126a2bbba1b302c4211
```
(cherry picked from commit bbc2a995f97c84670ba47126a2bbba1b302c4211)

[release/1.2 backport] shim service event blocked when waiting for IO finished

---

cmd/ctr/commands/tasks/exec.go

For this PR: #2798 , `add flag -d for ctr t exec to run a service in container`.
There is a small error in Line 97: https://github.com/lifubang/containerd/blob/01f5aa3878cf153c36fcc1dcd3789d4e229c835f/cmd/ctr/commands/tasks/exec.go#L93-L99 , because when we use `detach`, we should not call `defer process.Delete(ctx)`. This is my fault.
But there is no error for ctr, because we don't print the error for `process.Delete(ctx)`. If we print, we will get an error: `process must be stopped before deletion: failed precondition`.
So, if this is not import, feel free to close this PR.

fixes: should no defer when detach

---

runtime/v1/linux/proc/init_state.go

For https://github.com/containerd/containerd/issues/2744.
For Kubernetes, https://github.com/containerd/containerd/pull/2597 is not enough, because besides host pid namespace and container pid namespace, we also have pod level pid namespace sharing. In that case `KillAll` should also be called, but pid namespace in OCI spec is set.
This is fine, because in the CRI plugin, we can use `task.Delete(ctx, WithProcessKill)` to do the final cleanup.
However, the problem is that once init process dies, the shim transits to stopped state , and following `kill --all` won't be called at all. https://github.com/containerd/containerd/blob/master/runtime/v1/shim/service.go#L525
This PR currently changes the state machine to allow kill no matter `all=true/false`:
1) When `all=true`, the `runc kill` is …

Allow Kill in stopped state

---

cmd/ctr/commands/run/run.go
cmd/ctr/commands/tasks/exec.go

For ctr t exec:
```
root@dockerdemo:~/gocode/src/github.com/containerd/containerd# bin/ctr t exec redis echo -e "test"
Incorrect Usage: flag provided but not defined: -e
```
For ctr run:
```
root@dockerdemo:~/gocode/src/github.com/containerd/containerd# bin/ctr run docker.acmcoder.com/public/redis:latest redist echo -e "test"
Incorrect Usage: flag provided but not defined: -e
```
Set SkipArgReorder to true can resolve this problem.

fix container cmd args may parsed as ctr args

---

runtime/v1/linux/proc/utils.go
vendor.conf
vendor/github.com/opencontainers/runc/libcontainer/configs/intelrdt.go

This fixes a regression in runc that didn't allow signals being sent to
paused containers.

Update runc to 96ec2177ae841256168fcf76954f7177af

---

runtime/v1/linux/proc/utils.go
vendor.conf
vendor/github.com/opencontainers/runc/libcontainer/configs/intelrdt.go

This fixes a regression in runc that didn't allow signals being sent to
paused containers.

[release/1.2] Update runc to 96ec2177ae841256168fcf76954f7177af 

---

version/version.go

Prepares release 1.2.1 with no updates to the release notes necessary this time
The RC has been tested and verified and there have been 3 changes since the RC that I don't believe warrant another RC.
- #2847 Updates mask in default OCI configuration
- #2842 Updates runc to a tagged version, no functional changes
- #2845 Fixes issue introduced since last release
Added 
- #2856 Fixes kill in stopped state
- #2860 Updated CRI to fix stopped state
- #2861 Fixes regression related to signals to paused containers

[release/1.2] Prepare 1.2.1

---

linux/proc/utils.go
vendor.conf
vendor/github.com/opencontainers/runc/libcontainer/configs/config.go
vendor/github.com/opencontainers/runc/libcontainer/configs/intelrdt.go

backport of https://github.com/containerd/containerd/pull/2857 for the 1.1 branch.
minor conflict in vendor.conf, but trivial to resolve.
This fixes a regression in runc that didn't allow signals being sent to
paused containers.

[release/1.1 backport] Update runc to 96ec2177ae841256168fcf76954f7177af

---

vendor.conf
vendor/github.com/containerd/cgroups/README.md
vendor/github.com/containerd/cgroups/blkio.go
vendor/github.com/containerd/cgroups/cgroup.go
vendor/github.com/containerd/cgroups/control.go
vendor/github.com/containerd/cgroups/cpuset.go
vendor/github.com/containerd/cgroups/devices.go
vendor/github.com/containerd/cgroups/net_prio.go
vendor/github.com/containerd/cgroups/subsystem.go
vendor/github.com/containerd/cgroups/systemd.go
vendor/github.com/containerd/cgroups/utils.go

```
1152b960fcee041f50df15cdc67c29dbccf801ef (HEAD -> master, origin/master)
Merge pull request #73 from gliptak/gofmt1
afd5981a16647b45b6dba3a50a88418b576cc17d Gofmt cgroup_test
65ce98b3dfeb0a9a8fecd7e4ebffb24ad0bfe28f Merge pull request #69 from
cclerget/master-weight-pointer
0f372c6d4a65a49c72b0afbd1aee6214637958bf Merge pull request #71 from
JoeWrightss/patch-1
f48bd85c9cbc306fada0cebc3a646a1f1fe99afe Fixs return error message
10cd53efd916e22b9bdea67223d287684f57f1f4 Merge pull request #70 from
gliptak/patch-1
64bade4cea6c438ee51a7a12528225946b42c6ca Take value instead of pointer
value
b49c4713f3824e81bfa67faddcdde1414171b54e Correct ineffassign warning
3bc6dde829bc2dc8d4097ce8ad5acc275de3df06 Merge pull request #68 from
cclerget/master-net_prio-typo …
```

Update cgroups to 1152b960fcee041f50df15cdc67c29db

---

cmd/ctr/commands/commands.go
cmd/ctr/commands/commands_windows.go
cmd/ctr/commands/run/run_unix.go
cmd/ctr/commands/run/run_windows.go
oci/spec_opts.go
oci/spec_opts_test.go
oci/spec_opts_windows.go
oci/spec_opts_windows_test.go

Adds ctr run --memory-limit for all platforms.
Adds ctr run --cpu-count for Windows platforms.

Adding ctr memory and cpu flags

---

archive/tar.go
archive/tar_test.go

from golang code
https://github.com/golang/go/blob/bad6b6fa9190e9079a6d6958859856a66f0fab87/src/archive/tar/common.go#L110

fix: SCHILY.xattrs should be SCHILY.xattr

---

Makefile
script/setup/install-cni
script/setup/install-critools

Attempt to fix CI is failing due to a regression in Go 1.10.6 / 1.11.3 (see https://github.com/golang/go/issues/29241)
```
package github.com/containernetworking/plugins/...: github.com/containernetworking/plugins/...: invalid import path: malformed import path "github.com/containernetworking/plugins/...": double dot
```

Fix CI due to Golang 1.10.6 / 1.11.3 regressions (workaround)

---

Makefile
script/setup/install-cni
script/setup/install-critools

Backport of https://github.com/containerd/containerd/pull/2879 for the 1.1 release branch.
Minor conflict;
```patch
diff --cc script/setup/install-critools
index 828cb9d6,a75431e2..00000000
--- a/script/setup/install-critools
+++ b/script/setup/install-critools
@@@ -21,8 -21,14 +21,19 @@@
set -eu -o pipefail
go get -u github.com/onsi/ginkgo/ginkgo
++<<<<<<< HEAD
+CRITEST_COMMIT=v1.0.0-beta.1
+go get -d github.com/kubernetes-incubator/cri-tools/...
++=======
+ CRITEST_COMMIT=v1.12.0
+ 
+ # FIXME temporarily disabled due to a regression in Go 1.10.6 / 1.11.3 (https://github.com/golang/go/issues/29241)
+ # go get -d github.com/kubernetes-incubator/cri-tools/...
+ go get -d github.com/kubernetes-incubator/cri-tools || true
+ PACKAGES=$(go list github.com/kubernetes-incubator/cri-tools/... | …
```

[release/1.1 backport] Fix CI due to Golang 1.10.6 / 1.11.3 regressions (workaround)

---

Makefile
script/setup/install-cni
script/setup/install-critools

Backport of https://github.com/containerd/containerd/pull/2879 for the 1.2 release branch
Attempt to fix CI is failing due to a regression in Go 1.10.6 / 1.11.3 (see https://github.com/golang/go/issues/29241)
```
package github.com/containernetworking/plugins/...: github.com/containernetworking/plugins/...: invalid import path: malformed import path "github.com/containernetworking/plugins/...": double dot
```
(cherry picked from commit 52de3717005eb20141c305bd93ff0d6ee5dfecb6)

[release/1.2 backport] Fix CI due to Golang 1.10.6 / 1.11.3 regressions (workaround)

---

image.go

There are two images, A and B. A is based on B. If user pulls A first,
then user pulls B. containerd already has the unpacked snapshots in the
backend. During unpacking B, the client doesn't set gc snapshot
reference label to the config descriptor. That is the problem.
The gc module cannot reach the snapshot from the config descriptor. If
user removes the image B, the snapshot will be deleted by gc module.
That is why we should always set the snapshot gc label to config
descriptor.

bugfix: unpack should always set the snapshot gc label

---

cmd/containerd-shim/shim_freebsd.go
cmd/containerd-stress/rlimit_freebsd.go
runtime/v2/shim/shim_freebsd.go

This brings freebsd in line with Darwin, ie it builds, but some parts may not yet
be fully functional. There is now a WIP `runc` port for FreeBSD at
https://github.com/clovertrail/runc/tree/1501-SupportOnFreeBSD so should be able
to test further.
Signed-off-by: Justin Cormack <justin@specialbusservice.com>

Fix freebsd build

---

Makefile
script/setup/install-cni
script/setup/install-critools

This reverts commit 52de3717005eb20141c305bd93ff0d6ee5dfecb6 (https://github.com/containerd/containerd/pull/2879)
Golang 1.10.7 and 1.11.4 have been released, which address the regression, so we no longer need this temporary workaround

Revert "Fix CI due to Golang 1.10.6 / 1.11.3 regressions (workaround)"

---

Makefile
script/setup/install-cni
script/setup/install-critools

This reverts commit 66a3eeb5b78ef409b7520dae64e17bc3aceb1ebc (https://github.com/containerd/containerd/pull/2880)
Golang 1.10.7 and 1.11.4 have been released, which address the regression, so we no longer need this temporary workaround

[release/1.1] Revert "Fix CI due to Golang 1.10.6 / 1.11.3 regressions (workaround)"

---

Makefile
script/setup/install-cni
script/setup/install-critools

This reverts commit 27c6449c2c50f7e66076a4186e81aa3167e0dd5a (https://github.com/containerd/containerd/pull/2881)
Golang 1.10.7 and 1.11.4 have been released, which address the regression, so we no longer need this temporary workaround

[release/1.2] Revert "Fix CI due to Golang 1.10.6 / 1.11.3 regressions (workaround)"

---

docs/.dockerignore
docs/.editorconfig
docs/.gitignore

The website content moved to the github.com/containerd/containerd.io repository.
Commit da1fba00503610dce2e9f8a835cf0f1668fc4328 (https://github.com/containerd/containerd/pull/2572) removed all website-related content, but there were some stray files left behind. This patch removes those files, and updates the `.editorconfig` file to only match Markdown files.
@estesp

docs: remove website leftovers

---

content/testsuite/testsuite.go
identifiers/validate.go

1. "intitialization" to "initialization" in line 1000.
2. "insensitvity" to "insensitivity" in line 48.

Fix annotation typo errors

---

content/testsuite/testsuite.go
docs/ops.md
metadata/content.go
metadata/content_test.go
metadata/db.go
services/server/config/config.go
services/server/server.go

This changeset modifies the metadata store to allow one to set a
"content sharing policy" that defines how blobs are shared between
namespaces in the content store.
The default mode "shared" will make blobs available in all namespaces
once it is pulled into any namespace.  The blob will be pulled into
the namespace if a writer is opened with the "Expected" digest that
is already present in the backend.
The alternative mode, "isolated" requires that clients prove they have
access to the content by providing all of the content to the ingest
before the blob is added to the namespace.
Both modes share backing data, while "shared" will reduce total
bandwidth across namespaces, at the cost of allowing access to any
blob just by knowing its digest.
Note: Most functional codes and changelog of …

metadata: define content sharing policy

---

RELEASES.md

Brings versions and statuses up to date.
This updates the EOL status for 1.0. If any maintainer (or reviewer) wants to continue support of this branch or non-maintainer requests for a someone to own this, we can update the status to extended support along with the maintainer who will own the branch.

Update releases files

---

runtime/v2/runhcs/io.go

The call was closing all upstream IO when a shim.CloseIO call was made rather
than just the Stdin as it is supposed to.

Fix issue in runhcs shim CloseIO

---

vendor.conf

Changes: https://github.com/opencontainers/runc/compare/96ec2177ae841256168fcf76954f7177af9446eb...12f6a991201fdb8f82579582d5e00e28fba06d0a
Including critical security fix for `runc run --no-pivot` (`DOCKER_RAMDISK=1`): https://github.com/opencontainers/runc/pull/1962

bump up runc

---

vendor.conf

Changes: https://github.com/opencontainers/runc/compare/96ec2177ae841256168fcf76954f7177af9446eb...12f6a991201fdb8f82579582d5e00e28fba06d0a
Including critical security fix for `runc run --no-pivot` (`DOCKER_RAMDISK=1`): https://github.com/opencontainers/runc/pull/1962
(cherry picked from commit 3aec9e7beb211cf79e292dae14fc312350427cbf)

[release/1.1] bump up runc

---

vendor.conf

Changes: https://github.com/opencontainers/runc/compare/96ec2177ae841256168fcf76954f7177af9446eb...12f6a991201fdb8f82579582d5e00e28fba06d0a
Including critical security fix for `runc run --no-pivot` (`DOCKER_RAMDISK=1`): https://github.com/opencontainers/runc/pull/1962
(cherry picked from commit 3aec9e7beb211cf79e292dae14fc312350427cbf)

[release/1.2] bump up runc

---

vendor.conf
vendor/github.com/containerd/ttrpc/README.md
vendor/github.com/containerd/ttrpc/client.go
vendor/github.com/containerd/ttrpc/server.go
vendor/github.com/containerd/ttrpc/types.go

At a bit of a loss on how to write a test case for this.
Existing ttrpc libs will already honor a canceled context if it's canceled before dispatch in the ttrpc client is called.
Other methods on the containerd client go through grpc which is already going to return early on a cancelled context.
Thought of writing a custom shim implementation but then that's not really testing much, certainly not anything more than what's being tested in the ttrpc repo already.
Thoughts?

Update ttrpc to support context timeout.

---

snapshots/native/native.go
snapshots/overlay/overlay.go

```
func foo() error {
defer func() {
...
}
}()
...
}
```
use defer func to do something when err not nil, if foo() not use
named error, `err != nil` can not catch all errors, since when err
re-defined in if condition, it is a new variable.

fix: miss remove temp file in createSnapshot

---

cio/io.go
cio/io_unix.go
cio/io_windows.go

Adds ability to create a new `DirectIO` from a FIFOSet. This is needed for the work to get moby on Windows to use containerd for the runtime. This PR replaces https://github.com/containerd/containerd/pull/2928. You can see a working version of this PR hacked in my moby WIP PR at https://github.com/moby/moby/pull/38541.
@jterry75 FYI

Windows:NewDirectIOFromFIFOSet

---

runtime/runtime.go
runtime/v1/linux/runtime.go
runtime/v2/manager.go
windows/runtime.go

The two new method Add/Delete can allow custom plugin to add or migrate
existing task into major Runtime plugin.
close: #2888

runtime: add Add/Delete method in PlatformRuntime interface

---

.gometalinter.json
archive/tar_test.go
archive/tar_windows.go
cmd/containerd/command/service_windows.go
container_linux_test.go
container_test.go
content/local/locks.go
diff/apply/apply.go
diff/lcow/lcow.go
diff/windows/windows.go
filters/scanner.go
import.go
metadata/content.go
metadata/db.go
metadata/snapshot.go
pkg/progress/escape.go
pkg/testutil/helpers_unix.go
plugin/plugin.go
remotes/docker/auth.go
runtime/v2/shim/shim_unix.go
runtime/v2/shim/shim_windows.go
runtime/v2/shim/util_windows.go
services/containers/local.go
services/images/local.go

megacheck, gosimple and unused has been deprecated and subsumed by
staticcheck. And staticcheck also has been upgraded. we need to update
code for the linter issue.
close: #2945

fix: linter issue

---

.gometalinter.json
archive/tar.go
archive/tar_test.go
archive/tar_windows.go
container_linux_test.go
container_test.go
content/local/locks.go
contrib/seccomp/seccomp.go
diff/apply/apply.go
diff/lcow/lcow.go
diff/windows/windows.go
filters/scanner.go
import.go
metadata/content.go
metadata/db.go
metadata/snapshot.go
mount/mountinfo_linux.go
pkg/progress/escape.go
pkg/testutil/helpers_unix.go
plugin/plugin.go
remotes/docker/auth.go
runtime/v2/shim/shim_unix.go
runtime/v2/shim/shim_windows.go
runtime/v2/shim/util_windows.go
services/containers/local.go
services/images/local.go

megacheck, gosimple and unused has been deprecated and subsumed by
staticcheck. And staticcheck also has been upgraded. we need to update
code for the linter issue.
close: #2945

[release/1.2] fix: linter issue

---

.gometalinter.json
archive/tar.go
archive/tar_test.go
archive/tar_windows.go
container_linux_test.go
container_test.go
content/local/locks.go
contrib/seccomp/seccomp.go
diff/apply/apply.go
diff/windows/windows.go
filters/scanner.go
metadata/content.go
metadata/db.go
metadata/snapshot.go
mount/mountinfo_linux.go
plugin/plugin.go
progress/escape.go
remotes/docker/auth.go
services/containers/local.go
services/images/local.go
testutil/helpers_unix.go

megacheck, gosimple and unused has been deprecated and subsumed by
staticcheck. And staticcheck also has been upgraded. we need to update
code for the linter issue.
close: #2945

[release/1.1] fix: linter issue

---

archive/tar.go
archive/tar_test.go

backport of https://github.com/containerd/containerd/pull/2873 for 1.2. Relates to https://github.com/containerd/containerd/issues/2942
from golang code
https://github.com/golang/go/blob/bad6b6fa9190e9079a6d6958859856a66f0fab87/src/archive/tar/common.go#L110
add unit test for tar xattr
Fixes: #2863
(cherry picked from commit 6f944e41909625e90540585c0032a33c9b5be801)

[release/1.2 backport] fix: SCHILY.xattrs should be SCHILY.xattr

---

runtime/v1/linux/proc/exec.go
runtime/v1/linux/proc/init.go
runtime/v1/linux/proc/init_state.go
runtime/v1/linux/proc/io.go
runtime/v2/runc/service_linux.go
runtime/v2/shim_unix.go

Cherrypick of #2944 .
In release 1.2, we don't have new ttrpc, so we don't have the `OpenFifo` stopped by context cancellation issue. However, we still have the un-cancelled 30s timeout context issue mentioned in https://github.com/containerd/containerd/pull/2944#issuecomment-456644470.

[release/1.2] cherrypick: Use context.Background for `O_NONBLOCK` `OpenFifo`.

---

archive/tar.go
archive/tar_test.go

backport of https://github.com/containerd/containerd/pull/2873 for 1.1. Relates to https://github.com/containerd/containerd/issues/2942
**cherry-pick was not clean** conflicts in archive/tar_test.go, due to https://github.com/containerd/containerd/commit/b6107dca86c9755599071e0ac817dd4e8a7251d6 (https://github.com/containerd/containerd/pull/2696) missing, which moved some things to `archive/tartest`. I resolved those conflicts by removing the `tartest.` package name from the test, and removed the import.
from golang code
https://github.com/golang/go/blob/bad6b6fa9190e9079a6d6958859856a66f0fab87/src/archive/tar/common.go#L110
add unit test for tar xattr
Fixes: #2863
(cherry picked from commit 6f944e41909625e90540585c0032a33c9b5be801) …

[release/1.1 backport] fix: SCHILY.xattrs should be SCHILY.xattr

---

client.go
remotes/docker/converter.go

Even though application/octet-stream issue has been fixed in docker,
there exists lots of images which contains the invalid mediatype.
In order to pull those images, containerd client side modifies the
manifest content before insert/update image reference.
(cherry picked from commit 5137fc6f11d222eff1293dc7e212cf851568e858)

[release/1.2] cherrypick: bugfix: support application/octet-stream during pull

---

runtime/runtime.go
runtime/v1/linux/runtime.go
runtime/v2/manager.go
windows/runtime.go

The two new method Add/Delete can allow custom plugin to add or migrate
existing task into major Runtime plugin.
close: #2888
(cherry picked from commit 568b5be936dbb0d4e958ba2b32dc11968545eb2d)

[release/1.2] cherrypick: runtime: add Add/Delete method in PlatformRuntime interface

---

runtime/v2/README.md
runtime/v2/binary.go
runtime/v2/process.go
runtime/v2/runhcs/process.go
runtime/v2/runhcs/service.go
runtime/v2/shim.go

Changes the requirement of a Runtime v2 shim in order to avoid race conditions
between shim and shim client sending async events. Places a requirement of what
events and what order a shim must comply to.

Implement the Runtime v2 Shim async task model for runhcs

---

pkg/progress/bar.go

`copy` permits using to mix `[]byte` and `string` arguments without
explicit conversion. I removed explicit conversion to make the code simpler.
Signed-off-by: Iskander Sharipov <quasilyte@gmail.com>

remove excessive []byte(s) conversion

---

client.go
client_opts.go
client_test.go
images/handlers.go
remotes/handlers.go
vendor.conf
vendor/golang.org/x/sync/README
vendor/golang.org/x/sync/README.md
vendor/golang.org/x/sync/errgroup/errgroup.go
vendor/golang.org/x/sync/semaphore/semaphore.go

For https://github.com/containerd/containerd/issues/2886
Fixes https://github.com/containerd/containerd/issues/2195
* Containerd HEAD: 40.347s
* Containerd HEAD + #2913: 35.65s
* Containerd HEAD + #2913 + #2918: 32.95s
* Containerd HEAD + #2913 + #2918 + this change (with `MaxConcurrentDownloads = 3`): 28.89s
The result is almost the same with docker now! :)

Add image pull concurrency limit.

---

snapshots/snapshotter.go

Fixes #2941. When following the normal snapshots tutorial, any delay or unpacking large layers lets the garbage collector delete the snapshot in use. Add a no garbage collector label to the docs to make that clear.
Also, calling `Commit` should [remove the active snapshot](https://github.com/containerd/containerd/blob/f35c3527b24b728bb87788f647fbe7f205c20c7d/snapshots/snapshotter.go#L299) so no need to do that in the tutorial.
Signed-off-by: Oliver Stenbom <oliver@stenbom.eu>

Update snapshots docs with garbage collector label

---

metadata/gc.go

The noop-loop does nothing.
The containerd doesn't have any snapshotter buckets at the beginning.
If user uses specific dir as rootfs to create container, and sets
`snapshotter` key to the container, like `overlayfs` by mistake,
the gc scheduler will try to scan the snapshotter and panic.
In order to avoid this case, remove the noop-loop here.
for example,

metadata/gc: remove the noop-loop for snapshot reference

---

runtime/v2/shim/util.go

Fix bug in shim path lookup

---

metadata/gc.go

The noop-loop does nothing.
The containerd doesn't have any snapshotter buckets at the beginning.
If user uses specific dir as rootfs to create container, and sets
`snapshotter` key to the container, like `overlayfs` by mistake,
the gc scheduler will try to scan the snapshotter and panic.
In order to avoid this case, remove the noop-loop here.
(cherry picked from commit 34672d483d95b45aabd7ff1bc55eaf24b5aea177)

[Release 1.1] Cherry-pick: metadata/gc: remove the noop-loop for snapshot reference

---

metadata/gc.go

The noop-loop does nothing.
The containerd doesn't have any snapshotter buckets at the beginning.
If user uses specific dir as rootfs to create container, and sets
`snapshotter` key to the container, like `overlayfs` by mistake,
the gc scheduler will try to scan the snapshotter and panic.
In order to avoid this case, remove the noop-loop here.
(cherry picked from commit 34672d483d95b45aabd7ff1bc55eaf24b5aea177)

[Release 1.2] Cherry-pick: metadata/gc: remove the noop-loop for snapshot reference

---

README.md

fix example for checkpoint usage.
1) change `containerd.WithCheckpoint(checkpoint, "redis-rootfs")` to `containerd.WithNewSnapshot("redis-rootfs", checkpoint)`
2) `containerd.WithTaskCheckpoint(checkpoint)` , checkpint should be type `Image`

readme: fix example for checkpoint

---

runtime/v2/example/README.md
runtime/v2/example/cmd/main.go
runtime/v2/example/example.go

This allows runtime authors to quickly bootstrap new shim
implementations.

Add shim skeleton code

---

cmd/ctr/commands/run/run_windows.go
oci/spec.go
oci/spec_opts_windows.go
oci/spec_opts_windows_test.go

No longer sets defaults for
- .Process.ConsoleSize
- .Windows.IgnoreFlushesDuringBoot
- .Windows.Network.AllowUnqualifiedDNSQuery
Adds helper functions and tests for
- WithWindowsIgnoreFlushesDuringBoot
- WithWindowNetworksAllowUnqualifiedDNSQuery
Updates `ctr run` on Windows to use the new helper functions,
ConsoleSize is already handled.

OCI Modifiers for Windows

---

runtime/v2/runhcs/service.go

Due to an error in the OCI specf for layerFolders, the runhcs shim was
passing the layers for LCOW in reverse order. This fixes the ordering
by simply removing the code which reversed the layers for LCOW.

Fix LCOW layer ordering

---

vendor.conf
vendor/github.com/containerd/cri/pkg/server/container_create.go
vendor/github.com/containerd/cri/pkg/server/helpers.go
vendor/github.com/containerd/cri/pkg/server/instrumented_service.go
vendor/github.com/containerd/cri/pkg/server/sandbox_run.go

full diff: https://github.com/containerd/cri/compare/c3cf754321fc38c6af5dfd2552fdde0ad192b31d...da0c016c830b2ea97fd1d737c49a568a816bf964
includes backports of:
- containerd/cri#1042 Set /etc/hostname (fixes containerd/cri#1041)
- containerd/cri#1045 Fix env performance issue (fixes containerd/cri#1044)

[release/1.2] update containerd/cri to da0c016c830b2ea97fd1d737c49a568a816bf964

---

vendor.conf
vendor/github.com/containerd/cri/pkg/server/container_create.go
vendor/github.com/containerd/cri/pkg/server/container_status.go
vendor/github.com/containerd/cri/pkg/server/container_stop.go
vendor/github.com/containerd/cri/pkg/server/events.go
vendor/github.com/containerd/cri/pkg/server/helpers.go
vendor/github.com/containerd/cri/pkg/server/image_pull.go
vendor/github.com/containerd/cri/pkg/server/instrumented_service.go
vendor/github.com/containerd/cri/pkg/server/io/logger.go
vendor/github.com/containerd/cri/pkg/server/sandbox_run.go
vendor/github.com/containerd/cri/pkg/store/container/metadata.go
vendor/github.com/containerd/cri/pkg/util/strings.go

full diff: https://github.com/containerd/cri/compare/bad0ae1102e1bf9e53876f75eacc42bc97cfb557...f0b5665a959119b6a6234001e6d55206d9200e95 
includes backports of:
- containerd/cri#984 filter events for non k8s.io namespaces (resolves https://github.com/firecracker-microvm/firecracker-containerd/issues/35)
- containerd/cri#991 Remove container lifecycle image dependency (fixes containerd/cri#990)
- containerd/cri#1016 [release/1.0] Specify platform for image pull (fixes containerd/cri#1015)
- containerd/cri#1027 Fix the log ending newline handling (fixes containerd/cri#1026)
- containerd/cri#1042 Set /etc/hostname (fixes containerd/cri#1041)
- containerd/cri#1045 Fix env performance issue (fixes containerd/cri#1044)

[release/1.1] update containerd/cri to f0b5665a959119b6a6234001e6d55206d9200e95

---

releases/v1.1.6.toml
version/version.go

Create a new release to fix runc CVE-2019-5736
~~Requires #2999 to be merged before cutting a release.~~
Also includes several cherry-picked CRI fixes via #3015 

Prepare v1.1.6 release

---

releases/v1.2.4.toml
version/version.go

Updated vendor of runc to fix CVE-2019-5736.
~~Requires: #2998 to be merged before release can be cut.~~
Now includes CRI fixes and a Windows fix; all are added to the notes

Prepare v1.2.4 release

---

releases/README.md

Update release process with step to get downloads list updated on
containerd.io website

Add website update to release process

---

cmd/containerd/command/main_windows.go

Doing a blanket update of the event name for consistency across docker, containerd, containerd-shim-runhcs-v1 and docker-signal to make life a lot easier and less typing.
@jterry75 PTAL
Associated PRs: https://github.com/moby/moby/pull/38741, https://github.com/Microsoft/hcsshim/pull/480

Windows: Update stackdump event name

---

client.go
client_opts.go
pull.go
remotes/handlers.go

Gives clients more control of the pull process, allowing
the client to operate on a descriptor after it has been
pulled. This could be useful for filtering output or
tracking children before they dispatched to. This can
also be used to call custom unpackers to have visibility
into a pulled config in parallel to the downloads.
@Random-Liu I move the pull logic like you did in #2918, hopefully
that makes rebasing easier.

Add image handler wrapper

---

metadata/snapshot.go

metadata: merge snapshot labels with metadata's labels

---

archive/tar.go

Fixes #3017 
This keeps consistent behavior with docker. :)

Unpack should set 0755 when the parent directory doesn't exist.

---

runtime/v2/manager.go
runtime/v2/manager_unix.go
runtime/v2/manager_windows.go

Allow defining supported runtime platforms list from config as a node may support multiple.
@crosbymichael @dmcgowan 

runtime: allow specifying supported platforms with config

---

.travis.yml
Makefile
Makefile.linux
client.go
client_test.go
cmd/containerd-shim-runc-v1/main.go
cmd/containerd-shim-runc-v2/main.go
cmd/containerd-stress/main.go
cmd/ctr/commands/run/run_unix.go
cmd/ctr/commands/tasks/checkpoint.go
container_checkpoint_test.go
container_linux_test.go
daemon_config_linux_test.go
oci/spec_opts.go
plugin/plugin.go
runtime/v2/runc/container.go
runtime/v2/runc/epoll.go
runtime/v2/runc/platform.go
runtime/v2/runc/util.go
runtime/v2/runc/v1/service.go
runtime/v2/runc/v2/service.go
runtime/v2/shim.go
runtime/v2/shim/util.go
services/tasks/local.go
task.go
task_opts.go

**History**
We added the ability to group containers under a single shim after the initial integration so existing runc containers used one shim per container.
**Groups**
The grouping feature in this shim allows for using `Annotations` on the runtime spec to group multiple containers and only launch one shim for this group of containers.  
Two ways of grouping are supported using the following labels:
* `io.containerd.runc.v2.group=<group>`
* `io.kubernetes.cri.sandbox-id=<group>`
Using the sandbox-id label, this shim with automatically group containers in the same k8s pod into one shim.
**Examples**
Place two containers in a group, resulting in one shim being the parent of the `redis-server` and `sh` processes. 
Commands:
```bash
> sudo ctr run --label io.containerd.runc.v2.group=test …
```

io.containerd.runc.v2 with Container Groups

---

archive/tar.go

For https://github.com/containerd/containerd/issues/3017.
Cherrypick of #3018 

[release/1.2] Unpack should set 0755 when the parent directory doesn't exist.

---

archive/tar.go

For https://github.com/containerd/containerd/issues/3017.
Cherrypick of #3018 

[release/1.1] Unpack should set 0755 when the parent directory doesn't exist.

---

docs/man/containerd-config.1.md
docs/man/containerd-config.toml.5.md
docs/man/containerd.1.md
docs/man/ctr.1.md

As described in https://lintian.debian.org/tags/manpage-has-bad-whatis-entry.html
each manual page should start with a "NAME" section.
Signed-off-by: Shengjing Zhu <zhsj@debian.org>

docs: Add NAME section in all manpages

---

runtime/v2/shim_windows.go

With the change to unified shims (ie: 1 shim per multiple tasks) the shimLog
on Windows for the 2nd-Nth worload containers will not have an associated
named pipe listener.
Due to a subtle bug in errors.Wrap passing a nil error we would unblock the
disconnected listener and return 0 byte successfull reads which would cause go
to continually read and cap the CPU.

Fix a bug in shim log on Windows that can cause 100% CPU utilization

---

BUILDING.md

The integration-parallel has been removed by https://github.com/containerd/containerd/pull/1759/commits/4df7075a740def1b68f345dd20bca73ff9fd04b0.
Update Makefile targets in BUILDING.md.

BUILDING.md: update testing section

---

container.go
container_checkpoint_test.go
task.go
task_opts.go
task_opts_unix.go

This allows opts to handle the runtime better than requiring the client to pass the runtime information.

Fix runtime v2 option handling

---

metadata/gc.go
metadata/gc_test.go

Currently the objects which can retain content from labels are limited. This limitation has required clients to work around this and and in some cases add outside reference counting (e.g. buildkit keeping content for snapshots). Updated the logic to treat content and snapshot labels equally and simplified the code in the process.
I would also recommend we consider backporting this to 1.2 since the change is tightly scoped with clearly defined tests. Current GC performance is good enough that any effect based from additional calls (additional cursor seek for every image, container, and snapshot) is negligible and offset by one less seek for each content (single call to sendLabelRefs saves an extra bucket lookup).

Add content gc ref labels from containers, images, and snapshots

---

.appveyor.yml
.travis.yml
content/testsuite/testsuite.go
contrib/Dockerfile.test
metadata/content_test.go
snapshots/testsuite/testsuite.go

backport of https://github.com/containerd/containerd/pull/2420, https://github.com/containerd/containerd/pull/2436 and https://github.com/containerd/containerd/pull/2435
Go 1.12 was released, with which Go 1.10 reached end of support, so let's update this release branch to test against Go 1.11 (Go 1.12 still has some issues, but we could update to Go 1.12.1 once that's released)

[release/1.1 backport] Bump to Go 1.11.x

---

.appveyor.yml
.travis.yml
contrib/Dockerfile.test

backport of https://github.com/containerd/containerd/pull/2435
Go 1.12 was released, with which Go 1.10 reached end of support, so let's update this release branch to test against Go 1.11 (Go 1.12 still has some issues, but we could update to Go 1.12.1 once that's released)

[release/1.2 backport] Bump to Go 1.11.x

---

container_opts.go

- Allows `WithNewSnapshot` and `WithNewSnapshotView` to take in snapshotter opts.
Signed-off-by: Eric Hotinger <ehotinger@gmail.com>

Allow WithNewSnapshot and WithNewSnapshotView to take in snapshotter opts

---

vendor.conf
vendor/go.etcd.io/bbolt/README.md
vendor/go.etcd.io/bbolt/db.go
vendor/go.etcd.io/bbolt/freelist.go
vendor/go.etcd.io/bbolt/freelist_hmap.go

full diff https://github.com/etcd-io/bbolt/compare/v1.3.1-etcd.8...v1.3.2
Relevant changes:
- ectd-io/bbolt#139 update the freelist readIDs
- etcd-io/bbolt#140 add getFreePageIDs
- etcd-io/bbolt#141 use segregated hashmap to boost the freelist allocate and release performance
> use segregated hashmap to replace the original freeids allocating and releasing approach.
It is much faster than the original version, especially when the db size is large or the fragmentation in the db is large, we can gain 1000x faster performance.

Update go.etcd.io/bbolt to v1.3.2

---

vendor.conf
vendor/github.com/opencontainers/runc/README.md
vendor/github.com/opencontainers/runc/libcontainer/nsenter/cloned_binary.c
vendor/github.com/opencontainers/runc/vendor.conf

full diff: https://github.com/opencontainers/runc/compare/6635b4f0c6af3810594d2770f662f34ddc15b40d...2b18fe1d885ee5083ef9f0838fee39b62d653e30
This includes an improved fix for CVE-2019-5736 to reduce the
increased memory-consumption introduced by the original patch,
RHEL 7.6 getting into a loop due to a kernel bug in those kernels,
and improve compatibility with older kernels.
- opencontainers/runc#1973 Vendor opencontainers/runtime-spec 29686dbc
- opencontainers/runc#1978 Remove detection for scope properties, which have always been broken
- opencontainers/runc#1963 Vendor in go-criu and use it for CRIU's RPC definition
- opencontainers/runc#1995 exec: expose --preserve-fds
- opencontainers/runc#2000 fix preserve-fds flag may cause runc hang
- opencontainers/runc#1968 …

update runc to 2b18fe1d885ee5083ef9f0838fee39b62d653e30

---

metadata/gc.go
metadata/gc_test.go

Currently the objects which can retain content from labels are limited. This limitation has required clients to work around this and and in some cases add outside reference counting (e.g. buildkit keeping content for snapshots). Updated the logic to treat content and snapshot labels equally and simplified the code in the process.

[release/1.2] Add content gc ref labels from containers, images, and snapshots

---

vendor.conf
vendor/github.com/containerd/cri/pkg/annotations/annotations.go
vendor/github.com/containerd/cri/pkg/server/container_create.go
vendor/github.com/containerd/cri/pkg/server/helpers.go
vendor/github.com/containerd/cri/pkg/server/sandbox_run.go
vendor/github.com/containerd/cri/vendor.conf

* Fix a bug that pod can't get started when a volume is defined in both the image and the pod spec, but only one of them has a tailing `/`. https://github.com/containerd/cri/issues/1059
* CRI plugin now passes the pod log directory down to the OCI runtime with a new OCI annotation `io.kubernetes.cri.sandbox-log-directory`. Sandbox based runtime can generate sandbox level logs into the pod log directory, and kubelet will manage its disk usage and handle its cleanup.

[release/1.2] Update cri to 8e7ca12f411d65de58ca672e8e4a0c1464b4fe34.

---

image.go

There are two images, A and B. A is based on B. If user pulls A first,
then user pulls B. containerd already has the unpacked snapshots in the
backend. During unpacking B, the client doesn't set gc snapshot
reference label to the config descriptor. That is the problem.
The gc module cannot reach the snapshot from the config descriptor. If
user removes the image B, the snapshot will be deleted by gc module.
That is why we should always set the snapshot gc label to config
descriptor.
(cherry picked from commit 2d96aad771b3a0ea70e9d057c8d00aa734b55c40)

[release/1.2 backporting] bugfix: unpack should always set the snapshot gc label

---

vendor.conf
vendor/github.com/opencontainers/runc/README.md
vendor/github.com/opencontainers/runc/libcontainer/nsenter/cloned_binary.c
vendor/github.com/opencontainers/runc/vendor.conf

backport of https://github.com/containerd/containerd/pull/3081
This includes an improved fix for CVE-2019-5736 to reduce the
increased memory-consumption introduced by the original patch,
RHEL 7.6 getting into a loop due to a kernel bug in those kernels,
and improve compatibility with older kernels.
- opencontainers/runc#1973 Vendor opencontainers/runtime-spec 29686dbc
- opencontainers/runc#1978 Remove detection for scope properties, which have always been broken
- opencontainers/runc#1963 Vendor in go-criu and use it for CRIU's RPC definition
- opencontainers/runc#1995 exec: expose --preserve-fds
- opencontainers/runc#2000 fix preserve-fds flag may cause runc hang
- opencontainers/runc#1968 Create bind mount mountpoints during restore
- opencontainers/runc#1984 nsenter: …

[release/1.2 backport] update runc to 2b18fe1d885ee5083ef9f0838fee39b62d653e30

---

image.go

There are two images, A and B. A is based on B. If user pulls A first,
then user pulls B. containerd already has the unpacked snapshots in the
backend. During unpacking B, the client doesn't set gc snapshot
reference label to the config descriptor. That is the problem.
The gc module cannot reach the snapshot from the config descriptor. If
user removes the image B, the snapshot will be deleted by gc module.
That is why we should always set the snapshot gc label to config
descriptor.
(cherry picked from commit 2d96aad771b3a0ea70e9d057c8d00aa734b55c40)

[release/1.1 backporting] bugfix: unpack should always set the snapshot gc label 

---

vendor.conf
vendor/github.com/containerd/cgroups/cgroup.go
vendor/github.com/containerd/cgroups/control.go
vendor/github.com/containerd/cgroups/cpuset.go
vendor/github.com/containerd/cgroups/metrics.pb.go
vendor/github.com/containerd/cgroups/metrics.proto
vendor/github.com/containerd/cgroups/rdma.go
vendor/github.com/containerd/cgroups/subsystem.go
vendor/github.com/containerd/cgroups/utils.go
vendor/github.com/containerd/go-runc/console.go
vendor/github.com/containerd/go-runc/runc.go
vendor/github.com/containerd/go-runc/utils.go
vendor/github.com/opencontainers/runc/README.md
vendor/github.com/opencontainers/runc/libcontainer/nsenter/cloned_binary.c
vendor/github.com/opencontainers/runc/vendor.conf
vendor/github.com/opencontainers/runtime-spec/README.md
vendor/github.com/opencontainers/runtime-spec/specs-go/config.go
vendor/github.com/opencontainers/runtime-spec/specs-go/version.go

backport of https://github.com/containerd/containerd/pull/3081
This includes an improved fix for CVE-2019-5736 to reduce the
increased memory-consumption introduced by the original patch,
RHEL 7.6 getting into a loop due to a kernel bug in those kernels,
and improve compatibility with older kernels.
- opencontainers/runc#1973 Vendor opencontainers/runtime-spec 29686dbc
- opencontainers/runc#1978 Remove detection for scope properties, which have always been broken
- opencontainers/runc#1963 Vendor in go-criu and use it for CRIU's RPC definition
- opencontainers/runc#1995 exec: expose --preserve-fds
- opencontainers/runc#2000 fix preserve-fds flag may cause runc hang
- opencontainers/runc#1968 Create bind mount mountpoints during restore
- opencontainers/runc#1984 nsenter: …

[release/1.1 backport] update runc to 2b18fe1d885ee5083ef9f0838fee39b62d653e30

---

.mailmap

Fix to show real names in contributor list, to be updated for 1.2.5 as well

Update mailmap for cgroup authors

---

.mailmap

Fix to show real names in contributor list. Updates for 2 new author from cgroup repo in next release.

[release/1.2] Update mailmap for cgroup authors

---

vendor.conf
vendor/github.com/containerd/cri/pkg/server/container_create.go

Bug fixes:
* Fix a bug causes container start failure after in-place upgrade to containerd 1.2.4+ or 1.1.6+.

[release/1.2] Update cri to a92c40017473cbe0239ce180125f12669757e44f.

---

client.go
client_opts.go
client_test.go
cmd/ctr/commands/content/fetch.go
image_test.go
pull.go
remotes/docker/handler.go
remotes/docker/handler_test.go
remotes/handlers.go

We can use cross repository push feature to reuse the existing blobs in
the same registry. Before make push fast, we know where the blob comes
from.
Use the `containerd.io/distribution.source. = [,]` as label format. For
example, the blob is downloaded by the docker.io/library/busybox:latest
and the label will be
containerd.io/distribution.source.docker.io = library/busybox
If the blob is shared by different repos in the same registry, the repo
name will be appended, like:
containerd.io/distribution.source.docker.io = library/busybox,x/y
NOTE:
1. no need to apply for legacy docker image schema1.
2. the concurrent fetch actions might miss some repo names in label, but
it is ok.
3. it is optional. no need to add label if the engine only uses images
not push.
Signed-off-by: Wei Fu …

remotes: add distribution labels to blob data

---

cio/io.go
cmd/ctr/commands/run/run.go
cmd/ctr/commands/tasks/start.go
cmd/ctr/commands/tasks/tasks_unix.go
cmd/ctr/commands/tasks/tasks_windows.go
runtime/proc/proc.go
runtime/v1/linux/proc/exec.go
runtime/v1/linux/proc/init.go
runtime/v1/linux/proc/init_state.go
runtime/v1/linux/proc/io.go
runtime/v1/linux/proc/utils.go
runtime/v1/shim/service_linux.go
runtime/v1/shim/service_unix.go
runtime/v2/README.md
runtime/v2/logging/logging.go
runtime/v2/runc/platform.go

Closes #603
This adds logging facilities at the shim level to provide minimal I/O
overhead and pluggable logging options.  Log handling is done within the
shim so that all I/O, cpu, and memory can be charged to the container.
A sample logging driver setting up logging for a container the systemd
journal looks like this:
```go
package main
import (
"bufio"
"context"
"fmt"
"io"
"sync"
"github.com/containerd/containerd/runtime/v2/logging"
"github.com/coreos/go-systemd/journal"
)
func main() {
logging.Run(log)
}
func log(ctx context.Context, config *logging.Config, ready func() error) error {
// construct any log metadata for the container
vars := map[string]string{
"SYSLOG_IDENTIFIER": fmt.Sprintf("%s:%s", config.Namespace, config.ID),
}
var wg sync.WaitGroup
wg.Add(2)
// forward both stdout …
```

Shim pluggable logging

---

Makefile

With this patch applied, the package-name in the `--version` output can be overridden;
make PACKAGE=containerd.io binaries
./bin/containerd --version
containerd containerd.io v1.2.0-329-ga15b6e20.m a15b6e2097c48b632dbdc63254bad4c62b69e709.m

Makefile: allow overriding package name

---

Makefile

backport of https://github.com/containerd/containerd/pull/3096 for the 1.2 release branch
With this patch applied, the package-name in the `--version` output can be overridden;
make PACKAGE=containerd.io binaries
./bin/containerd --version
containerd containerd.io v1.2.0-329-ga15b6e20.m a15b6e2097c48b632dbdc63254bad4c62b69e709.m
(cherry picked from commit b858cfb41b4f49d93990380faed2af5dd9269ffe)

[release/1.2 backport] Makefile: allow overriding package name

---

Makefile

backport of https://github.com/containerd/containerd/pull/3096 for the 1.1 release branch
With this patch applied, the package-name in the `--version` output can be overridden;
make PACKAGE=containerd.io binaries
./bin/containerd --version
containerd containerd.io v1.2.0-329-ga15b6e20.m a15b6e2097c48b632dbdc63254bad4c62b69e709.m
(cherry picked from commit b858cfb41b4f49d93990380faed2af5dd9269ffe)

[release/1.1 backport] Makefile: allow overriding package name

---

container_test.go
runtime/v1/linux/bundle.go
runtime/v1/shim/client/client.go
runtime/v2/shim/util_unix.go

Use sha256 hash to shorten the unix socket path to satisfy the
length limitation of abstract socket path
This commit also backports the feature storing address path to
a file from v2 to keep compatibility
Fixes #3032
Signed-off-by: Eric Lin <linxiulei@gmail.com>

Shorten the unix socket path for shim

---

oci/spec_opts.go
oci/spec_opts_test.go

Add additional capability handling opts

---

cmd/ctr/commands/images/images.go

ctr image list/check 's ArgsUsage should be filter, not ref

ctr: fix image cmd ArgsUsage

---

contrib/seccomp/seccomp_default.go

io_pgetevents() is a new Linux system call, similar to the already-whitelisted
io_getevents(). It has no security implications. Whitelist it so applications can
use the new system call.
Fixes #3105.
Signed-off-by: Avi Kivity <avi@scylladb.com>

seccomp: whitelist io_pgetevents

---

cmd/ctr/commands/images/import.go
import.go

Add `all-platforms` option to `ctr images import`.
Fixes #3103

Allow to import an image for the default platform only.

---

contrib/seccomp/seccomp_default.go

backport of https://github.com/containerd/containerd/pull/3107 for the release/1.1 branch
io_pgetevents() is a new Linux system call, similar to the already-whitelisted
io_getevents(). It has no security implications. Whitelist it so applications can
use the new system call.
Fixes #3105.

[release/1.1 backport] seccomp: whitelist io_pgetevents

---

contrib/seccomp/seccomp_default.go

backport of https://github.com/containerd/containerd/pull/3107 for the release/1.2 branch
io_pgetevents() is a new Linux system call, similar to the already-whitelisted
io_getevents(). It has no security implications. Whitelist it so applications can
use the new system call.
Fixes #3105.

[release/1.2 backport] seccomp: whitelist io_pgetevents

---

contrib/seccomp/seccomp_default.go

This whitelists the statx syscall; libseccomp-2.3.3 or up
is needed for this, older seccomp versions will ignore this.
Equivalent of https://github.com/moby/moby/pull/36417
addresses https://github.com/docker/for-linux/issues/616

seccomp: whitelist statx syscall

---

contrib/seccomp/seccomp_default.go

backport of https://github.com/containerd/containerd/pull/3111 for the release/1.1 branch
This whitelists the statx syscall; libseccomp-2.3.3 or up
is needed for this, older seccomp versions will ignore this.
Equivalent of https://github.com/moby/moby/pull/36417
addresses https://github.com/docker/for-linux/issues/616

[release/1.1 backport] seccomp: whitelist statx syscall

---

contrib/seccomp/seccomp_default.go

backport of https://github.com/containerd/containerd/pull/3111 for the release/1.2 branch
This whitelists the statx syscall; libseccomp-2.3.3 or up
is needed for this, older seccomp versions will ignore this.
Equivalent of https://github.com/moby/moby/pull/36417
addresses https://github.com/docker/for-linux/issues/616

[release/1.2 backport] seccomp: whitelist statx syscall

---

defaults/defaults_windows.go
services/server/server.go
sys/filesys_unix.go
sys/filesys_windows.go

@jterry75 PTAL. This: 
- moves the default root to under programdata rather than `program files`;
- creates the root/state directories ACL'd to administrators & localsystem
- fixes a bug in the recursion of the previously unused `mkdirall` which wasn't passing the requested `adminAndLocalSystem`
After this change:
```
PS C:\programdata> icacls containerd
containerd BUILTIN\Administrators:(OI)(CI)(F)
NT AUTHORITY\SYSTEM:(OI)(CI)(F)
Successfully processed 1 files; Failed processing 0 files
PS C:\programdata> icacls .\containerd\root\
.\containerd\root\ BUILTIN\Administrators:(OI)(CI)(F)
NT AUTHORITY\SYSTEM:(OI)(CI)(F)
Successfully processed 1 files; Failed processing 0 files
PS C:\programdata> icacls .\containerd\state\
.\containerd\state\ …
```

Windows: Root/state create with right ACL and in right place

---

api/next.pb.txt
api/types/descriptor.pb.go
api/types/descriptor.proto
container_checkpoint_opts.go
diff.go
image_store.go
import_test.go
metadata/boltutil/helpers.go
metadata/images.go
metadata/images_test.go
services/diff/local.go
services/images/helpers.go
services/tasks/local.go
task.go
task_opts.go

Add the annotations map to the gRPC Descriptor message.
For the container image encryption we intend to use the annotations map to temporarily store the image decryption parameters ('dcparameters'), which are primarily keys, in form of a JSON document under the map key '_dcparameters', and pass them to the applier's Apply() method. This helps us to access decryption keys and start the pipeline with the layer decryption before the layer data are unzipped and untarred. This map key '_dcparameters' will be removed from the annotations map. Using this 'trick' we avoid having to extend the Apply() method's signature with another parameter.
Signed-off-by: Harshal Patil <harshal.patil@in.ibm.com>

Add missing annotations map to Descriptor for gRPC transfer

---

metadata/adaptors.go

Extend the adaptImage function with a case for handling the annotations
so they can be used in the filter adaptors for fieldpaths.
This PR addresses issue #3121.

Extend adaptImage function with annotations case

---

oci/spec_opts.go
oci/spec_opts_test.go

With the following code:
```
var WithAllCapabilities = WithCapabilities(GetAllCapabilities())
```
All `WithAllCapabilities` option will share the same instance of capability list returned by GetAllCapabilities(). This means that dropping a cap will actually drop the cap for all `WithAllCapabilities` callers.
This is very bad, and we may want to cherry-pick this fix.
Without the fix, the newly added test will fail:
```
--- FAIL: TestDropCaps (0.00s)
spec_opts_test.go:487: cap list 0 doesn't contain non-dropped cap
spec_opts_test.go:487: cap list 1 doesn't contain non-dropped cap
spec_opts_test.go:487: cap list 2 doesn't contain non-dropped cap
spec_opts_test.go:487: cap list 3 doesn't contain non-dropped cap
FAIL
exit status 1
FAIL	github.com/containerd/containerd/oci	0.032s
```
When …

Fix capability option race and panic.

---

vendor.conf
vendor/github.com/containerd/cgroups/cgroup.go

full diff: https://github.com/containerd/cgroups/compare/dbea6f2bd41658b84b00417ceefa416b979cbf10...4994991857f9b0ae8dc439551e8bebdbb4bf66c1
brings in https://github.com/containerd/cgroups/pull/79 Return ErrCgroupDeleted when no subsystems
fixes https://github.com/containerd/containerd/issues/3133 Custom cgroup path does not work in containerd 1.2.5

bump containerd/cgroups 4994991857f9b0ae8dc439551e8bebdbb4bf66c1

---

vendor.conf
vendor/github.com/opencontainers/runc/libcontainer/nsenter/cloned_binary.c
vendor/github.com/opencontainers/runc/vendor.conf

full diff: https://github.com/opencontainers/runc/compare/2b18fe1d885ee5083ef9f0838fee39b62d653e30...v1.0.0-rc7
- opencontainers/runc#2012 Need to setup labeling of kernel keyrings
- opencontainers/runc#2014 Add $RUNC_USE_SYSTEMD to run tests using systemd cgroup driver
- opencontainers/runc#2015 Use getenv not secure_getenv
- fixes opencontainers/runc#2013 build fails with musl libc
- relates to https://github.com/linuxkit/linuxkit/pull/3306
- opencontainers/runc#2023 Fixes regression causing zombie runc:[1:CHILD] processes
- fixes https://github.com/opencontainers/runc/pull/1966 ensure we call wait() on children created by nsenter

update opencontainers/runc v1.0.0-rc7

---

vendor.conf
vendor/github.com/opencontainers/runc/libcontainer/nsenter/cloned_binary.c
vendor/github.com/opencontainers/runc/vendor.conf

backport of https://github.com/containerd/containerd/pull/3139 for the 1.1 release branch
full diff: https://github.com/opencontainers/runc/compare/2b18fe1d885ee5083ef9f0838fee39b62d653e30...v1.0.0-rc7
- opencontainers/runc#2012 Need to setup labeling of kernel keyrings
- opencontainers/runc#2014 Add $RUNC_USE_SYSTEMD to run tests using systemd cgroup driver
- opencontainers/runc#2015 Use getenv not secure_getenv
- fixes opencontainers/runc#2013 build fails with musl libc
- opencontainers/runc#2023 Fixes regression causing zombie runc:[1:CHILD] processes
- fixes https://github.com/opencontainers/runc/pull/1966 ensure we call wait() on children created by nsenter

[release/1.1 backport] update opencontainers/runc v1.0.0-rc7

---

vendor.conf
vendor/github.com/opencontainers/runc/libcontainer/nsenter/cloned_binary.c
vendor/github.com/opencontainers/runc/vendor.conf

backport of https://github.com/containerd/containerd/pull/3139 for the 1.2 release branch
full diff: https://github.com/opencontainers/runc/compare/2b18fe1d885ee5083ef9f0838fee39b62d653e30...v1.0.0-rc7
- opencontainers/runc#2012 Need to setup labeling of kernel keyrings
- opencontainers/runc#2014 Add $RUNC_USE_SYSTEMD to run tests using systemd cgroup driver
- opencontainers/runc#2015 Use getenv not secure_getenv
- fixes opencontainers/runc#2013 build fails with musl libc
- opencontainers/runc#2023 Fixes regression causing zombie runc:[1:CHILD] processes
- fixes https://github.com/opencontainers/runc/pull/1966 ensure we call wait() on children created by nsenter

[release/1.2 backport] update opencontainers/runc v1.0.0-rc7

---

vendor.conf
vendor/github.com/containerd/cgroups/cgroup.go

backport of https://github.com/containerd/containerd/pull/3142 for the 1.2 release branch
full diff: https://github.com/containerd/cgroups/compare/dbea6f2bd41658b84b00417ceefa416b979cbf10...4994991857f9b0ae8dc439551e8bebdbb4bf66c1
brings in https://github.com/containerd/cgroups/pull/79 Return ErrCgroupDeleted when no subsystems
fixes https://github.com/containerd/containerd/issues/3133 Custom cgroup path does not work in containerd 1.2.5

[release/1.2 backport] bump containerd/cgroups 4994991857f9b0ae8dc439551e8bebdbb4bf66c1

---

oci/spec_opts.go
oci/spec_opts_test.go

This backports https://github.com/containerd/containerd/pull/3137 to fix the `WithAllCapabilities` race condition.

[release/1.2 backport] Fix race and panic.

---

runtime/v1/linux/proc/io.go

This resolves #3118 by introducing synchronization to the `wc.Close()` calls.

runtime/v1/linux/proc/io: io race

---

runtime/v1/linux/proc/io.go

Backport of for the release/1.2 branch
first commit didn't apply clean due to https://github.com/containerd/containerd/pull/3085 not being in the 1.2 branch

[release/1.2 backport] runtime/v1/linux/proc/io: io race

---

linux/proc/io.go

backport of https://github.com/containerd/containerd/pull/3153 for the 1.1 branch
This code moved around between 1.1 and 1.2 (with the introduction of the V2 runtime), so I applied the patch manually;
```
git format-patch --relative HEAD~ 
git checkout -b 1.1_backport_issue_3118 upstream/release/1.1 
git am -p3 --reject 0001-runtime-log-IO-error-when-copying-output-streams.patch
git am -p3 --reject 0002-runtime-guard-Close-until-both-streams-are-complete.patch
```

[release/1.1 backport] runtime/v1/linux/proc/io: io race

---

mount/mountinfo_linux.go
mount/mountinfo_linux_test.go

equivalent to https://github.com/moby/moby/pull/38977, for containerd
relates to https://github.com/moby/moby/issues/38458
relates to https://github.com/kubernetes/kubernetes/issues/35062
`/proc/self/mountinfo` uses `\040` for spaces, however, `parseInfoFile()`
did not decode those spaces in paths, therefore attempting to use `\040`
as a literal part of the path.
This patch un-quotes the `root` and `mount point` fields to fix
situations where paths contain spaces.
Note that the `mount source` field is not modified, given that
this field is documented (man `PROC(5)`) as:
filesystem-specific information or "none"
Which I interpreted as "the format in this field is undefined".
Thanks to @remexre for reporting, and @itizir, @sergei-utinski for suggesting the patch.

Fix parseInfoFile does not handle spaces in filenames

---

mount/mountinfo_linux.go
mount/mountinfo_linux_test.go

backport of https://github.com/containerd/containerd/pull/3159 for the 1.2 branch
equivalent to https://github.com/moby/moby/pull/38977, for containerd
relates to https://github.com/moby/moby/issues/38458
relates to https://github.com/kubernetes/kubernetes/issues/35062
`/proc/self/mountinfo` uses `\040` for spaces, however, `parseInfoFile()`
did not decode those spaces in paths, therefore attempting to use `\040`
as a literal part of the path.
This patch un-quotes the `root` and `mount point` fields to fix
situations where paths contain spaces.
Note that the `mount source` field is not modified, given that
this field is documented (man `PROC(5)`) as:
filesystem-specific information or "none"
Which I interpreted as "the format in this field is undefined".
Thanks to @remexre for reporting, …

[release/1.2 backport] Fix parseInfoFile does not handle spaces in filenames

---

client.go
client_test.go
container_opts.go
container_opts_unix.go
defaults/defaults.go
docs/namespaces.md

This is in reference to #2285. I tried to configure default runtime and snapshotter using namespace labels. Please suggest me the right approach if this is not the best way to do it.
Signed-off-by: Nikhil Soni <krsoninikhil@gmail.com>

Uses namespace labels for default options

---

vendor.conf
vendor/github.com/containerd/cri/pkg/server/container_stop.go
vendor/github.com/containerd/cri/pkg/server/sandbox_run.go
vendor/github.com/containerd/cri/pkg/server/sandbox_stop.go
vendor/github.com/containerd/cri/vendor.conf

* Fix a bug that containers being gracefully stopped are SIGKILLed when kubelet is restarted. https://github.com/containerd/cri/issues/1098
* Fix a bug that pod UTS namespace is used for host network. https://github.com/containerd/cri/pull/1111
* Update CNI plugins to v0.7.5 for [CVE-2019-9946](https://nvd.nist.gov/vuln/detail/CVE-2019-9946).

[release/1.2] Update cri to ffd9a66034aee582db04cf4c59e9b2262fd4fc59.

---

vendor.conf
vendor/github.com/containerd/cri/pkg/server/container_create.go
vendor/github.com/containerd/cri/pkg/server/container_stop.go
vendor/github.com/containerd/cri/pkg/server/helpers.go
vendor/github.com/containerd/cri/pkg/server/sandbox_run.go
vendor/github.com/containerd/cri/pkg/server/sandbox_stop.go
vendor/github.com/containerd/cri/vendor.conf

* Fix a bug that pod can't get started when the same volume is defined differently in the image and the pod spec. https://github.com/containerd/cri/issues/1059
* Fix a bug that causes container start failure after in-place upgrade containerd to 1.2.4+ or 1.1.6+. https://github.com/containerd/cri/issues/1082
* Fix a bug that containers being gracefully stopped are SIGKILLed when kubelet is restarted. https://github.com/containerd/cri/issues/1098
* Fix a bug that pod UTS namespace is used for host network. https://github.com/containerd/cri/pull/1111
* Update CNI plugins to v0.7.5 for [CVE-2019-9946](https://nvd.nist.gov/vuln/detail/CVE-2019-9946).

[release/1.1] Update cri to b9c06fd1410f1e6699a83277887af399a1342736.

---

contrib/aws/snapshotter_bench_readme.md
snapshots/benchsuite/benchmark.go
snapshots/benchsuite/benchmark_test.go

Addressing @dmcgowan 's [comment](https://github.com/containerd/containerd/pull/3152#issuecomment-478762805) and moving benchmark code to a separate package.
Its not quite possible to split bench tests and still run them simultaneously in one command (as benchmarks complain about cli args of each other), so agreed to move it to a separate package instead.

Move snapshotters benchmark to a separate package

---

vendor.conf
vendor/github.com/sirupsen/logrus/README.md
vendor/github.com/sirupsen/logrus/alt_exit.go
vendor/github.com/sirupsen/logrus/entry.go
vendor/github.com/sirupsen/logrus/exported.go
vendor/github.com/sirupsen/logrus/json_formatter.go
vendor/github.com/sirupsen/logrus/logger.go
vendor/github.com/sirupsen/logrus/logrus.go
vendor/github.com/sirupsen/logrus/terminal_check_aix.go
vendor/github.com/sirupsen/logrus/terminal_check_bsd.go
vendor/github.com/sirupsen/logrus/terminal_check_notappengine.go
vendor/github.com/sirupsen/logrus/terminal_check_unix.go
vendor/github.com/sirupsen/logrus/text_formatter.go

Full diff: https://github.com/sirupsen/logrus/compare/v1.3.0...v1.4.1
Fixes:
- Remove dependency on golang.org/x/crypto
- Fix wrong method calls Logger.Print and Logger.Warningln
- Update Entry.Logf to not do string formatting unless the log level is enabled
- Fix infinite recursion on unknown Level.String()
- Fix race condition in getCaller
- Fix Entry.WithContext method to return a copy of the initial entry
New:
- Add DeferExitHandler, similar to RegisterExitHandler but prepending the handler to the list of handlers (semantically like defer)
- Add CallerPrettyfier to JSONFormatter and `TextFormatter`
- Add Entry.WithContext() and Entry.Context, to set a context on entries to be used e.g. in hooks
- Enhance TextFormatter to not print caller information when they are empty

bump sirupsen/logrus v1.4.1

---

vendor.conf
vendor/github.com/containerd/cri/pkg/server/helpers.go
vendor/github.com/containerd/cri/vendor.conf
vendor/github.com/opencontainers/selinux/README.md
vendor/github.com/opencontainers/selinux/go-selinux/label/label.go
vendor/github.com/opencontainers/selinux/go-selinux/label/label_selinux.go
vendor/github.com/opencontainers/selinux/go-selinux/selinux_linux.go
vendor/github.com/opencontainers/selinux/go-selinux/selinux_stub.go

* Update `github.com/opencontainers/selinux` to `v1.2.1`.

[release 1.1] Update cri to f8171b4530bed8992973cc4a2f24efe53b821d53.

---

vendor.conf
vendor/github.com/containerd/cri/pkg/server/helpers.go

The Kubernetes e2e test for containerd repository is failing:
* https://k8s-testgrid.appspot.com/sig-node-containerd#containerd-e2e-gci
* https://k8s-testgrid.appspot.com/sig-node-containerd#containerd-node-e2e
* https://k8s-testgrid.appspot.com/sig-node-containerd#containerd-node-e2e-features
* https://k8s-testgrid.appspot.com/sig-node-containerd#containerd-e2e-ubuntu
The test result for the `cri` repository is good.
This is because we enabled per-pod shim in https://github.com/containerd/cri/pull/1116, but the change is not in this repository yet.

Update cri to 6d353571e64417d80c9478ffaea793714dd539d0.

---

vendor.conf
vendor/github.com/opencontainers/runc/vendor.conf

this updates runc to the same version as master (https://github.com/containerd/containerd/pull/3169); see https://github.com/containerd/containerd/pull/3181#discussion_r272423235
no changes in vendored files
full diff: https://github.com/opencontainers/runc/compare/v1.0.0-rc7...029124da7af7360afa781a0234d1b083550f797c
- opencontainers/runc#2031 Add selinux validate in runc exec
- opencontainers/runc#2032 Fix SELinux failures on disabled SELinux Machines
- addresses opencontainers#2030 "container init caused "write /proc/self/attr/keycreate: invalid argument"

[release/1.1] bump runc to 029124da (v1.0.0-rc7-6-g029124da)

---

vendor.conf
vendor/github.com/opencontainers/runc/vendor.conf

this updates runc to the same version as master (https://github.com/containerd/containerd/pull/3169); see https://github.com/containerd/containerd/pull/3180#discussion_r272423032
no changes in vendored files
full diff: https://github.com/opencontainers/runc/compare/v1.0.0-rc7...029124da7af7360afa781a0234d1b083550f797c
- opencontainers/runc#2031 Add selinux validate in runc exec
- opencontainers/runc#2032 Fix SELinux failures on disabled SELinux Machines
- addresses opencontainers#2030 "container init caused "write /proc/self/attr/keycreate: invalid argument"

[release/1.2] bump runc to 029124da (v1.0.0-rc7-6-g029124da)

---

Makefile

When tests fail they could leave debris behind such as
- overlay mounts
- cgroups
- metadata
These debris can cause subsequent tests to fail
Co-authored-by: Danail Branekov <danailster@gmail.com>
Signed-off-by: Georgi Sabev <georgethebeatle@gmail.com>

Introduce 'clean-test' target in Makefile

---

releases/v1.1.7.toml

Prepare v1.1.7 release 

---

RELEASES.md

Update active releases with latest version and timeline. Extend 1.1 an additional 3 months to align with k8s 1.11 EOL and ensure we have 2 active releases. Also add 3 months extended for security patches.
This updates the release cycle to reflect a desire to support 2-3 containerd releases at any given time and define a period where the maintainers will continue to support security patches.
Policy changes require 9 (2/3) maintainer LGTM

Extend release timeline

---

cmd/containerd/command/config_linux.go
cmd/containerd/command/config_unsupported.go
cmd/containerd/command/config_windows.go
services/server/config/config.go
services/server/server.go

By default, containerd keeps running when a plugin fails to be initialized. However, some users may require some plugins for their use case, e.g. the `cri` plugin is critical for Kubernetes users.
This is even worse when we add more and more config validations in the CRI plugin, e.g. https://github.com/containerd/cri/pull/1125. If a bad CRI config is given, containerd will continue running without the CRI plugin, which makes it very hard to figure out what is wrong.
This PR added the `required_plugins` config. If a required plugin is missing or fails to be loaded/started, containerd will exit directly.

Add support for required plugins.

---

.travis.yml

We should be testing runc.v1 and runc.v2 with cri test as well.
This can help us catch regressions like https://github.com/containerd/containerd/issues/3203.

Use $TEST_RUNTIME for cri test.

---

client.go

In [firecracker-containerd](https://github.com/firecracker-microvm/firecracker-containerd) project we use GRPC plugins to extend containerd's functionality and we have to manage a separate client in order to make calls.
It would be great if we could reuse existing containerd's client (e.g. reuse connection object, namespace handling, reconnect logic, etc) to invoke external grpc services as well.
The proposed solution adds `ExternalService` and looks as follows:
```go
client, err := containerd.New(...)
panic(err)
}
var firecrackerClient proto.FirecrackerClient
client.ExternalService(func(conn *grpc.ClientConn) {
firecrackerClient = proto.NewFirecrackerClient(conn)
})
firecrackerClient.XXX();
```

Allow reuse client for external GRPC services

---

remotes/resolver.go
services/server/server_solaris.go

Fixes #3212.
This PR corrects an import statement in `services/server/server_solaris.go` and updates the `PusherFunc` type's function signature in the `containerd/remotes` package to match the `Pusher` interface.

Correct import path and PusherFunc signature

---

.mailmap

No affiliation change (NTT).
The former email address will continue to be available for the time being.
For daily communication, I still prefer to use my gmail.com address.

.maimap: update Akihiro Suda's email address

---

client_test.go
client_windows_test.go

~~Testing whether there is an actual problem running `make integration` on Windows, or whether AppVeyor is just extremely slow...~~
Updating nanoserver image with available exact tag; fix from @fuweid to not have CI hang in the future when this (or another image pull transient failure) happens.
Fixes: #3227

Update to sha-specific nanoserver image reference to fix AppVeyor CI runs

---

cmd/containerd/command/main.go

As it says in the title. @jterry75 PTAL.

Write stack dump to `os.TempDir()` as well 

---

vendor.conf
vendor/github.com/containerd/console/LICENSE
vendor/github.com/containerd/console/README.md
vendor/github.com/syndtr/gocapability/capability/capability.go
vendor/github.com/syndtr/gocapability/capability/capability_linux.go
vendor/github.com/syndtr/gocapability/capability/syscall_linux.go

full diff: https://github.com/syndtr/gocapability/compare/db04d3cc01c8b54962a58ec7e491717d06cfcc16...d98352740cb2c55f81556b63d4a1ec64c5a319c2
- syndtr/gocapability#14 capability: Deprecate NewPid and NewFile for NewPid2 and NewFile2
- syndtr/gocapability#16 Fix capHeader.pid type
Also bumped containerd/console just to keep up, but no local changes were introduced

Bump syndtr/gocapability d983527, containerd/console

---

remotes/resolver.go
services/server/server_solaris.go

This backports #3213 to fix an import path (in `services/server/server_solaris.go`) and `PusherFunc` signature.
Signed-off-by: Jared Cordasco <jcordasc@coglib.com>

[release/1.2 backport] Correct import path and PusherFunc signature

---

cmd/containerd/command/main.go
cmd/containerd/command/main_unix.go
cmd/containerd/command/main_windows.go

ETW provides its own retention mechanism, so don't need to write out dumped stacks to file when its triggered by ETW.

Don't write dumped stacks to file for ETW capture state

---

client_windows_test.go

Cherrypick #3230 commit (e6fc0ed22d3f670597c9a363810d5e1dbd7f192e)

[release/1.2] cherry-pick: Convert Windows CI to use Microsoft MCR image urls

---

vendor.conf
vendor/github.com/docker/go-units/duration.go
vendor/github.com/docker/go-units/size.go
vendor/github.com/docker/go-units/ulimit.go

relevant changes:
- docker/go-units#19 make 1 second not to be plural seconds
- docker/go-units#20 Add `HumanSizeWithPrecision` function
- docker/go-units#21 change week display rule
- docker/go-units#22 Better human duration precision
- docker/go-units#23 Removes spaces before unit
- docker/go-units#27 Fix #26 - RAMInBytes Bug
- docker/go-units#33 Fix handling of unlimited (-1) ulimit values
- docker/go-units#34 Revert 46 minute threshold

bump docker/go-units v0.4.0

---

runtime/v2/shim/shim.go

Before this change, the v2 runtime shim setup code was hardcoded to always
configure logrus to write logs to the "log" FIFO present in the current working
directory. This only happens in the "default" action codepath
(i.e. not shim start or shim delete).
This is problematic for shims that execute outside the current working
directory of a bundle. For example, it often doesn't make sense for shims that
manage multiple containers to execute in a single bundle directory. Additionally,
shim processes that require being pre-created, i.e. spun up before tasks they
will handle are actually created, won't have a log FIFO to write to until a task
is created.
This change leaves the default behavior as is but introduces a Binary Config
field that will optionally disable automatic configuration of …

Support disabling default setup of shim logger.

---

content/local/writer.go
diff/walking/differ.go

In https://github.com/moby/buildkit/issues/960 differ error is produced that was fixed in https://github.com/containerd/continuity/pull/140 . When this error was reached the writer was not properly released resulting a "locked" message for next invocations. This PR fixes the line involved so the error does not get masked, and two other cases where errors would have also been swallowed previously.

differ: fix deadlock on commit error

---

vendor.conf
vendor/github.com/opencontainers/runc/vendor.conf
vendor/github.com/opencontainers/selinux/go-selinux/selinux_linux.go

~runc v1.0.0-rc8 wasn't tagged yet, but took the commit of the version bump~
- runc diff: https://github.com/opencontainers/runc/compare/029124da7af7360afa781a0234d1b083550f797c...425e105d5a03fabd737a126ad93d62a9eeede87f
- opencontainers/runc#2043 Vendor in latest selinux code for keycreate errors
- selinux diff: https://github.com/opencontainers/selinux/compare/v1.2.1...v1.2.2
- opencontainers/selinux#51 Older kernels do not support keyring labeling

Bump runc 1.0.0-rc8, opencontainers/selinux v1.2.2

---

vendor/github.com/gogo/googleapis/go.mod
vendor/github.com/gogo/protobuf/go.mod
vendor/github.com/google/uuid/go.mod
vendor/github.com/konsorten/go-windows-terminal-sequences/go.mod
vendor/github.com/sirupsen/logrus/go.mod
vendor/golang.org/x/crypto/go.mod
vendor/golang.org/x/sys/go.mod
vendor/gopkg.in/yaml.v2/go.mod
vendor/gotest.tools/go.mod

As @thajeztah in Slack `vndr` recently updated and now creates additional `go.mod` files that need to be included to pass the CI vendor checks.
See https://github.com/LK4D4/vndr/pull/75 for the recently merged change.

Update vendor/ with new required vndr go.mod files

---

README.md

Fixes the broken URL to containerd logo in the root README. No source code changes.

Fix broken link to containerd logo

---

vendor.conf
vendor/github.com/opencontainers/runc/vendor.conf
vendor/github.com/opencontainers/selinux/go-selinux/selinux_linux.go

back port of https://github.com/containerd/containerd/pull/3240 for the 1.1 branch
- runc diff: https://github.com/opencontainers/runc/compare/029124da7af7360afa781a0234d1b083550f797c...425e105d5a03fabd737a126ad93d62a9eeede87f
- opencontainers/runc#2043 Vendor in latest selinux code for keycreate errors
- selinux diff: https://github.com/opencontainers/selinux/compare/v1.2.1...v1.2.2
- opencontainers/selinux#51 Older kernels do not support keyring labeling

[release/1.1 backport] Bump runc 1.0.0-rc8, opencontainers/selinux v1.2.2

---

vendor.conf
vendor/github.com/opencontainers/runc/vendor.conf
vendor/github.com/opencontainers/selinux/go-selinux/selinux_linux.go

back port of https://github.com/containerd/containerd/pull/3240 for the 1.2 branch
- runc diff: https://github.com/opencontainers/runc/compare/029124da7af7360afa781a0234d1b083550f797c...425e105d5a03fabd737a126ad93d62a9eeede87f
- opencontainers/runc#2043 Vendor in latest selinux code for keycreate errors
- selinux diff: https://github.com/opencontainers/selinux/compare/v1.2.1...v1.2.2
- opencontainers/selinux#51 Older kernels do not support keyring labeling

[release/1.2 backport] Bump runc 1.0.0-rc8, opencontainers/selinux v1.2.2

---

vendor/gopkg.in/yaml.v2/go.mod

Similar to #3249, we need to commit the `go.mod` files produced by the latest version of vndr. For 1.2, only `gopkg.in/yaml.v2` has a vendored version that includes a `go.mod` file.
Signed-off-by: Jared Cordasco <jcordasc@coglib.com>

[release/1.2] Add new required vndr go.mod files

---

cmd/ctr/commands/images/import.go

Implements https://github.com/containerd/containerd/issues/3258. `ctr images import ...`  with the new `--no-unpack` option will return after `Import`, skipping image `Unpack`. 
This can be used to import images into the content store for E.G. VM image baking without unpacking them to a snapshotter.
Signed-off-by: Benjamin Elder <bentheelder@google.com>

ctr images import: add --no-unpack option

---

runtime/v1/shim/client/client.go
runtime/v2/binary.go
runtime/v2/shim.go
vendor.conf
vendor/github.com/containerd/ttrpc/README.md
vendor/github.com/containerd/ttrpc/client.go
vendor/github.com/containerd/ttrpc/server.go
vendor/github.com/containerd/ttrpc/services.go
vendor/github.com/containerd/ttrpc/types.go

backports of;
- https://github.com/containerd/containerd/pull/2930 Update ttrpc to support context timeout
- https://github.com/containerd/containerd/pull/3246 bump containerd/ttrpc 699c4e40d1e7416e08bf7019c7ce2e9beced4636
- containerd/ttrpc#33 Fix returns error message
- containerd/ttrpc#35 Make onclose an option

[release/1.2 backport] Update ttrpc

---

mount/mount_linux.go
runtime/v1/linux/bundle.go
runtime/v1/linux/proc/init.go
runtime/v1/shim/service.go
runtime/v2/bundle.go
runtime/v2/runc/container.go

We (Cloud Foundry Garden) are trying to run containerd as a non-root user for extra security. We have our own component for creating container images so we are not using a snapshotter. While this mostly works we hit the following problem:
- Currently when you create a new task, the [client](https://github.com/containerd/containerd/blob/c80dd7929ee7600ab2684e9ab02ef427cf40c0b9/container.go#L214-L231) will ask the snapshotter (if any) about any mount points that containerd should make and pass them on with the request so that they are performed by the shim [over here](https://github.com/containerd/containerd/blob/c80dd7929ee7600ab2684e9ab02ef427cf40c0b9/runtime/v1/shim/service.go#L148-L157). If there is no snapshotter the request will contain an empty list of mounts and the shim will not …

Skip rootfs unmount when no mounts are provided

---

runtime/v1/linux/proc/deleted_state.go
runtime/v1/linux/task.go
runtime/v2/shim.go

We've seen this issue in a Kubernetes benchmark test https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-cri-containerd-node-e2e-benchmark/1120454833061498892.
The initial container deletion hit a timeout, and returned at https://github.com/containerd/containerd/blob/v1.2.6/runtime/v1/linux/task.go#L89. I guess because we are stopping >200 containers at the same time:
```
Apr 22 22:50:40 n1-standard-1-cos-stable-60-9592-90-0-81227dd7 containerd[1037]: time="2019-04-22T22:50:40.732760213Z" level=error msg="Failed to handle exit event &TaskExit{ContainerID:fdab5da3258b6cf5488148cb9e4295e0fe5d1a3fe4fb6f64b7091a78c74504d9,ID:fdab5da3258b6cf5488148cb9e4295e0fe5d1a3fe4fb6f64b7091a78c74504d9,Pid:1466,ExitStatus:0,ExitedAt:2019-04-22 22:50:30.720718714 +0000 UTC,XXX_unrecognized:[],} for …
```

Return NotFound error for kill and delete in deleted state.

---

api/next.pb.txt
api/types/descriptor.pb.go
api/types/descriptor.proto
diff.go
image_store.go
import_test.go
metadata/adaptors.go
metadata/boltutil/helpers.go
metadata/images.go
metadata/images_test.go
services/diff/local.go
services/images/helpers.go
services/tasks/local.go
task.go
task_opts.go

In working on a custom differ plugin that has logic around annotations on the image layer descriptors, I ran into the issue fixed in #3000 and #3121. It would be useful to have this ability in a released version rather than working off master.
Note: In cherry-picking commit 0b711d616ab13e9bad2801db7b53d5ffeb6934dc, the changes for container_checkpoint_opts.go were dropped as that functionality is not present in the the 1.2 branch.

[release/1.2 backport] Add missing annotations map to Descriptor for gRPC transfer 

---

remotes/docker/resolver.go
remotes/docker/schema1/converter.go

Adds a fallback to manually compute the manifest digest when it is not presented as the Docker-Content-Digest header by the registry server. This is to address https://github.com/containerd/containerd/issues/3238.

Compute manifest metadata when not provided

---

snapshots/devmapper/dmsetup/dmsetup.go
snapshots/devmapper/pool_device.go
snapshots/devmapper/pool_device_test.go
snapshots/devmapper/snapshotter.go
snapshots/testsuite/testsuite.go

1. reason to deactivate committed snapshot
The thin device will not be used for IO after committed,
and further thin snapshotting is OK using an inactive thin
device as origin. The benefits to deactivate are:
- device is not unneccesary visible avoiding any unexpected IO;
- save useless kernel data structs for maintaining active dm.
Quote from kernel doc (Documentation/device-mapper/provisioning.txt):
"
ii) Using an internal snapshot.
Once created, the user doesn't have to worry about any connection
between the origin and the snapshot.  Indeed the snapshot is no
different from any other thinly-provisioned device and can be
snapshotted itself via the same method.  It's perfectly legal to
have only one of them active, and there's no ordering requirement on
activating or removing them both. …

snapshots/devmapper: deactivate thin device after committed

---

container_linux_test.go
runtime/v1/shim/client/client.go
runtime/v2/shim_unix.go

Open shim log with the flag `O_RDWR` will cause the `Read()` block forever even if the pipe has been closed on the shim side. Then the `io.Copy()` would never return and lead to a fd leak.
It happens on both shim v1 and v2  but may only have effect on shim v2. Because when using shim v1 , the fd leak is on containerd-shim which will exit when the runtime shim exit. But under shim v2 the shim log is opened by the containerd process so the fd won't be closed until containerd exit.
Run a pod using shim v2 and `lsof` on containerd:
```
COMMAND     PID USER   FD   TYPE             DEVICE SIZE/OFF       NODE NAME
container 51419 root   12u  FIFO                8,8      0t0  351013697 /run/containerd/io.containerd.runtime.v2.task/k8s.io/cd7e64d216e7376e51463f3d9d20571ae2ae9eb009b13a315193bdf9b713 …
```

Fix fd leak of shim log

---

runtime/v1/shim/service.go
runtime/v2/runc/v2/service.go

For issue https://github.com/moby/moby/issues/38978 :
We should let `KillAll` run when pid namespace path is not empty.
Signed-off-by: Lifubang lifubang@acmcoder.com

fix killall when use pidnamespace

---

.zuul.yaml
.zuul/playbooks/containerd-build/run.yaml

This patch adds the CI configuration to enable the support for arm build in OpenLab.
After this, each pull request in containerd will trigger the ``containerd-arm64-build`` job which verified the arm build on ARM cluster.
As the first version, we mark this job as non-voting job, that means the build job result is just a reference for developer and would not block the PR to be merged. Once we make sure the job can be executed stable, then we can mark it as normal "voting" job.
Related: https://github.com/containerd/containerd/issues/2901

Add OpenLab CI configuration for ARM64 build

---

platforms/compare.go
platforms/cpuinfo.go

This commit improves ARM platform matching in two instances:
* Some old kernels reported the CPU architecture of arm64 cpus as
Aarch64 [1].
* In cases where the user is running with armv8 cpu and kernel but amrhf
user land (so armhf containerd), a possibility given the compatibility
of armv8 with armv7.
[1] https://elixir.bootlin.com/linux/v3.14.29/source/arch/arm64/kernel/setup.c#L420
Signed-off-by: Jaime Caamaño Ruiz <jcaamano@suse.com>

Improve ARM platform matching

---

runtime/v2/binary.go
runtime/v2/manager.go
runtime/v2/shim.go

Fixes https://github.com/containerd/containerd/issues/3199
Depends on https://github.com/containerd/ttrpc/pull/35.
When containerd-shim is killed when containerd is running:
```
INFO[2019-04-11T10:39:37.413880563-07:00] shim disconnected                             id=753143c31aa85fe7f1424f1e13cf1891510d377bbc86b8daa520c72b084051b6
WARN[2019-04-11T10:39:37.414006366-07:00] cleaning up after shim disconnected           id=753143c31aa85fe7f1424f1e13cf1891510d377bbc86b8daa520c72b084051b6 namespace=k8s.io
INFO[2019-04-11T10:39:37.414034377-07:00] cleaning up dead shim                        
WARN[2019-04-11T10:39:37.581877377-07:00] cleanup warnings time="2019-04-11T10:39:37-07:00" level=info msg="starting signal loop" namespace=k8s.io pid=75143 
DEBU[2019-04-11T10:39:37.582387101-07:00] …
```

Cleanup dead v2 shim.

---

runtime/v1/shim/service.go

Backport of https://github.com/containerd/containerd/pull/3149 for the 1.2 branch (only the first commit (cherry picked from commit fa5f744a790356472d4649b9ad1d955e36d0c7c0))
addresses https://github.com/moby/moby/issues/38978

[release/1.2 backport] fix killall when use pidnamespace

---

client_test.go
cmd/containerd-shim/main_unix.go
container_linux_test.go
runtime/v1/linux/runtime.go
runtime/v1/shim.go
runtime/v1/shim/client/client.go
runtime/v2/shim_unix.go

Open shim v2 log with the flag `O_RDWR` will cause the `Read()` block
forever even if the pipe has been closed on the shim side. Then the
`io.Copy()` would never return and lead to a fd leak.
Fix typo when closing shim v1 log which causes the `stdouLog` leak.
Update `numPipes` function in test case to get the opened FIFO
correctly.
(cherry picked from commit cf6e008)

[cherry-pick release/1.2] Fix fd leak of shim log

---

cmd/containerd-shim/main_unix.go

Redirect is used to make sure that containerd still can read the log of
shim after restart.

containerd-shim: redirect output into stdout fifo

---

runtime/v1/linux/runtime.go

Currently when we restart containerd it will load all tasks with shim
logs whether the `shim_debug` is set or not.

v1:Respect the `shim_debug` flag when load tasks

---

cmd/containerd-shim/main_unix.go

Redirect is used to make sure that containerd still can read the log of
shim after restart.
(cherry picked from commit fbb80b9510db14a95b8ffa6c7842666ecf520489)

[cherry-pick release/1.2] containerd-shim: redirect output into stdout fifo

---

runtime/v1/linux/runtime.go

Currently when we restart containerd it will load all tasks with shim
logs whether the `shim_debug` is set or not.
(cherry picked from commit 66036d9206ceaef83005260700d7e0b13b057830)

[cherry-pick release/1.2] v1: Respect the `shim_debug` flag when load tasks

---

cmd/ctr/commands/shim/shim.go

make ctr shim command easy to use for user, shim socket is generated
through sha256, and it can not get directly, change socket flag to id
command, generated socket in code.
It also avoid fail to connect shim v2, since shim v2 have multiple
containers, `ctr shim --socket state` should specify container id, or
get error `rpc error: code = NotFound desc = container not created: not
found`

ctr: make ctr shim command easy to use

---

runtime/v1/linux/bundle.go
runtime/v1/linux/runtime.go
runtime/v2/bundle.go
runtime/v2/manager.go

skip hidden directories in load task, and return soon if path not exist
in atomicDelete
carry of #3233
Closes #3233

Improve atomic delete

---

metadata/content.go

The namespaced writer Commit method must always have a
namespace in the context as checked by the removeIngestLease
function, resulting in a panic when not provided. Use the
namespace on the writer since it is always correct and supersedes
any other namespace provided on the Commit context.

Ensure namespaced writer commit has correct namespace

---

images/annotations.go
images/archive/exporter.go
images/archive/importer.go
images/archive/reference.go
import.go
import_test.go

Remove annotation prefix and add multiple index records
for manifests with multiple image names. This makes the
custom annotation more consistent with the OCI ref name
annotation. Additionally, ensure the OCI image annotation
always represents the tag (partial image name) as recommended
by the specification. The containerd image name annotation
will always contain the full image name.

Use a single custom annotation for export

---

container_linux_test.go
runtime/v2/binary.go
runtime/v2/manager.go
runtime/v2/runc/v1/service.go
runtime/v2/runc/v2/service.go
runtime/v2/shim/util.go
task_opts_unix.go

This also has a change where task opts are passed to shims via STDIN for early inspection.

Add shim cgroup support for v2 runtimes

---

runtime/v1/linux/runtime.go
runtime/v1/shim/client/client.go

The patch do two things, 
1. refactor cleanupAfterDeadShim function, judge if task is available, if
has, do cleanup.
2. add kill shim in cleanupDeadShim, in cleanup , `r.tasks.Delete(ctx, id)` will be called, then the task should be removed from task list, so do more killShim function, make less leak shim.

runtime-v1: kill shim in exit handler

---

runtime/v1/shim/service.go
runtime/v2/runc/container.go

Not return error when rootfs already exists.
If we use the new containerd-shim with containerd 1.2, it will break. I know that we don't have guarantee for that kind of version skew, but it is still better not to break that when possible.
```
$ sudo ctr run --rm --tty docker.io/library/alpine:latest test
ctr: mkdir /run/containerd/io.containerd.runtime.v1.linux/default/test/rootfs: file exists: already exists
```

Not return error when rootfs already exists

---

cmd/containerd/command/service_windows.go

Previously we waited for 60 seconds after the service faults to restart
it. However, there isn't much benefit to waiting this long. We expect
15 seconds to be a more reasonable delay.

Change restart delay for Windows service to 15s

---

diff.go
diff/apply/apply.go
diff/diff.go
diff/lcow/lcow.go
diff/windows/windows.go
services/diff/local.go

Extend the Applier interface's Apply method with an optional
options map[string]string.

Extend Applier's Apply() method with an optional options parameter

---

contrib/seccomp/seccomp_default.go

All clone flags for namespace should be denied.
Also x/sys should be used instead of syscall.
Signed-off-by: Kenta Tada <Kenta.Tada@sony.com>

Fix seccomp contributed profile for clone syscall

---

errdefs/errors.go
errdefs/grpc.go
errdefs/grpc_test.go

Add support to gRPC errdefs for context cancel/deadline exceeded

---

api/next.pb.txt
api/services/leases/v1/leases.pb.go
api/services/leases/v1/leases.proto
lease_test.go
leases/lease.go
leases/proxy/manager.go
metadata/leases.go
metadata/leases_test.go
services/leases/local.go
services/leases/service.go

Add three methods for lease service so that the client can use it to
manage the resource by lease, not just gc.root label. With the following
methods, it is easy for client to maintain their own cache system.
```
- AddResource(context.Context, Lease, Resource) error
- RemoveResource(context.Context, Lease, Resource) error
- ListResources(context.Context, Lease) ([]Resource, error)
```
And the resource is to be
```golang
type Resource {
ID   string
Type string
}
```
For the snapshots, the Type field will be formatted by
snapshots/%{type}, like snapshots/overlayfs.
fix: #3295

leases: support resource management

---

runtime/v1/linux/bundle.go
runtime/v2/bundle.go

This fixes issues running gvisor on top of containerd without docker.

Ensure that the rootfs dir is created in the bundle

---

runtime/v2/bundle.go

This ensures that a container does not have a mounted rootfs in the
bundle directory before RemoveAll is called.  Having the rootfs removed
first with a Remove ensures that the directory is not mounted and empty
before the bundle directory is removed.

Unmount rootfs with separate Remove() in bundle

---

runtime/v1/linux/runtime.go

Signed-off-by: Jing Rui <jingrui@huawei.com>

fix shim std logs not close after shim exit

---

vendor.conf
vendor/github.com/containerd/cri/pkg/server/container_execsync.go
vendor/github.com/containerd/cri/pkg/server/container_remove.go
vendor/github.com/containerd/cri/pkg/server/container_start.go
vendor/github.com/containerd/cri/pkg/server/container_stop.go
vendor/github.com/containerd/cri/pkg/server/events.go
vendor/github.com/containerd/cri/pkg/server/helpers.go
vendor/github.com/containerd/cri/pkg/server/restart.go
vendor/github.com/containerd/cri/pkg/server/sandbox_run.go
vendor/github.com/containerd/cri/pkg/server/sandbox_stop.go
vendor/github.com/containerd/cri/pkg/store/container/status.go
vendor/github.com/containerd/cri/pkg/store/sandbox/sandbox.go
vendor/github.com/containerd/cri/pkg/store/sandbox/status.go
vendor/github.com/containerd/cri/vendor.conf

* Fix a bug that container can't be stopped when the exit event is not successfully published by the containerd shim. https://github.com/containerd/containerd/issues/3125, https://github.com/containerd/containerd/issues/3177
* Fix a bug that exec process is not cleaned up if grpc context is canceled or timeout. https://github.com/containerd/cri/pull/1159

[release/1.2] Update cri to 49ca74043390bc2eeea7a45a46005fbec58a3f88

---

remotes/docker/authorizer.go
remotes/docker/resolver.go

Currently the user agent is only being used on the initial resolve request, then switching to the default user agent. This ensures the correct user agent is always used. There is a larger fix in progress which does this is a cleaner way, but the scope of this change is fixing the user agent issue.

Add user agent header to all requests

---

.travis.yml
cmd/containerd/command/config.go
cmd/containerd/command/config_linux.go
cmd/containerd/command/config_unsupported.go
cmd/containerd/command/config_windows.go

Closes #3336 
The fix here is when `containerd config default` is called, generate a new v2 config, however, keep the default code set at v1 so that when the containerd main loads, it merges the default config with what is loaded from disk causing a backwards incompat change. 

Fix backwards compat with v2 containerd configs

---

docs/client-opts.md
docs/man/containerd.1.md
docs/man/ctr.1.md

Signed-off-by: BoWen Yan <loneybw@gmail.com>

docs: Fix typo to some markdown files in /docs.

---

remotes/docker/authorizer.go
remotes/docker/handler.go
remotes/docker/pusher.go
remotes/docker/scope.go
remotes/docker/scope_test.go
remotes/handlers.go

With distribution source label in content store, select the longest
common prefix components as condidate mount blob source and try to push
with mount blob.
Fix #2964

remotes: support cross-repo-push

---

releases/v1.2.7.toml
version/version.go

@containerd/containerd-release @containerd/containerd-reviewers @containerd/containerd-maintainers 
Let's do a v1.2.7 release this week. There are a lot of important bug fixes.
Feel free to comment.

Prepare v1.2.7 release

---

.appveyor.yml

go1.12.6 (released 2019/06/11) includes fixes to the compiler, the linker,
the go command, and the crypto/x509, net/http, and os packages. See the
Go 1.12.6 milestone on the issue tracker for details:
https://github.com/golang/go/issues?q=milestone%3AGo1.12.6
full diff: https://github.com/golang/go/compare/go1.12.5...go1.12.6

AppVeyor: Bump golang 1.12.6

---

runtime/v1/linux/proc/io.go

Make `func newBinaryIO(...) (runc.IO, error)` public so third-party runtimes
can reuse it for binary shim logging (and use in conjunction with `logging.Run(...)`).

Make newBinaryIO public

---

.appveyor.yml
.travis.yml

[release/1.2 backport] update Go 1.12 and travis/appveyor changes
- https://github.com/containerd/containerd/pull/3040 Update travis to xenial worker
- https://github.com/containerd/containerd/pull/2896 Add Golang 1.12.5
- https://github.com/containerd/containerd/pull/3343 AppVeyor: Bump golang 1.12.6
**not included**
Travis;
- https://github.com/containerd/containerd/pull/3004 io.containerd.runc.v2 with Container Groups
- https://github.com/containerd/containerd/pull/3205 Use $TEST_RUNTIME for cri test
AppVeyor;
- https://github.com/containerd/containerd/pull/2760 Fix mingw version back to working version with Golang
- https://github.com/containerd/containerd/pull/3128 (https://github.com/containerd/containerd/commit/8710940165aa66e39700eb56a9bb8fe25bda7d40#diff-11c909939117928998b102a1ff …

[release/1.2 backport] update Go 1.12 and travis/appveyor changes

---

README.md

The Join Slack link is broke...
Use a dynamic link this time.

switch to a working link

---

metadata/snapshot.go
metadata/snapshot_test.go
snapshots/snapshotter.go

- Allow opts to flow to the backend snapshotter during snapshot creation. For example, this would allow the underlying snapshotter to make decisions based on pass through labels.
/cc @dmcgowan 
Closes #2907
Signed-off-by: Eric Hotinger <ehotinger@gmail.com>

Allow opts to flow to the backend snapshotter during snapshot creation.

---

cmd/containerd-shim/main_unix.go

containerd-shim has dup the fd 3, and it don't need fd 3 any more.
before this pr,
```
[root@centos3 containerd]# ps -eaf|grep shim   
root     26959 24846  0 19:31 ?        00:00:00 docker-containerd-shim -namespace moby -workdir /var/lib/docker/containerd/daemon/io.containerd.runtime.v1.linux/moby/b6faed158d9f22c3a47409714972affdb1af2d98363962f5e2fa9a3ef533ae52 -address /var/run/docker/containerd/docker-containerd.sock -containerd-binary /usr/bin/containerd -runtime-root /var/run/docker/runtime-kata-runtime -debug
[root@centos3 containerd]# ls /proc/26959/fd
lr-x------. 1 root root 64 Jun 20 19:24 0 -> /dev/null
lrwx------. 1 root root 64 Jun 20 19:24 1 -> socket:[198373]
lrwx------. 1 root root 64 Jun 20 19:24 10 -> socket:[459676]
lrwx------. 1 root root 64 Jun 20 19:24 11 -> …
```

Close the inherited socket fd

---

runtime/v1/linux/proc/exec.go
runtime/v1/linux/proc/init.go
runtime/v1/linux/proc/utils.go

Closes #3286
This and a combination of a couple Docker changes are needed to fully
resolve the issue on the Docker side.  However, this ensures that after
processes exit, we still leave some time for the I/O to fully flush
before closing.  Without this timeout, the delete methods would block
forever.

Add timeout for I/O waitgroups

---

vendor.conf
vendor/github.com/opencontainers/runc/libcontainer/nsenter/nsexec.c
vendor/github.com/opencontainers/runc/vendor.conf

full diff: https://github.com/opencontainers/runc/compare/v1.0.0-rc8...f4982d86f7fde0b6f953cc62ccc4022c519a10a9
possibly relevant changes included:
- opencontainers/runc#2074 Update dependency libseccomp-golang
- fixes https://nvd.nist.gov/vuln/detail/CVE-2017-18367
- opencontainers/runc#2065 Fix cgroup hugetlb size prefix for kB
- opencontainers/runc#2042 libcontainer: intelrdt: add missing destroy handler in defer func
- opencontainers/runc#2042 main: not reopen /dev/stderr
- opencontainers/runc#2038 `r.destroy` can defer exec in `runner.run` method
- opencontainers/runc#2035 specconv: always set "type: bind" in case of MS_BIND
- opencontainers/runc#2035 Move systemd.Manager initialization into a function in that module
- opencontainers/runc#2034 Support for logging from children …

bump runc v1.0.0-rc8-32-gf4982d86

---

.travis.yml
Makefile

As binaries are built and put on GitHub in an archive it would also
make sense to provide a checksum so that users can validate the
archives integrity.

Add hashsum for release archives

---

vendor.conf
vendor/github.com/seccomp/libseccomp-golang/README
vendor/github.com/seccomp/libseccomp-golang/seccomp.go
vendor/github.com/seccomp/libseccomp-golang/seccomp_internal.go

full diff: https://github.com/seccomp/libseccomp-golang/compare/32f571b70023028bd57d9288c20efbcb237f3ce0...689e3c1541a84461afc49c1c87352a6cedf72e9c
Release notes:
* Version 0.9.1 - May 21, 2019
- Minimum supported version of libseccomp bumped to v2.2.0 (https://github.com/seccomp/libseccomp-golang/commit/fc0298087f328ac97a1fa781392de96b2ebb8aac)
- PowerPC and S390(x) architectures are unavailable below library version v2.3.0 and will return errors if used with incompatible libraries
- Use Libseccomp's `seccomp_version` API to retrieve library version
- Unconditionally set TSync attribute for filters, due to Go's heavily threaded nature
- Fix [CVE-2017-18367](https://nvd.nist.gov/vuln/detail/CVE-2017-18367) - Multiple syscall arguments were incorrectly combined with logical-OR, instead of …

bump libseccomp-golang v0.9.1

---

vendor.conf
vendor/github.com/seccomp/libseccomp-golang/README
vendor/github.com/seccomp/libseccomp-golang/seccomp.go
vendor/github.com/seccomp/libseccomp-golang/seccomp_internal.go

backport of https://github.com/containerd/containerd/pull/3371 for the 1.1 branch
full diff: https://github.com/seccomp/libseccomp-golang/compare/32f571b70023028bd57d9288c20efbcb237f3ce0...689e3c1541a84461afc49c1c87352a6cedf72e9c
Release notes:
* Version 0.9.1 - May 21, 2019
- Minimum supported version of libseccomp bumped to v2.2.0 (https://github.com/seccomp/libseccomp-golang/commit/fc0298087f328ac97a1fa781392de96b2ebb8aac)
- PowerPC and S390(x) architectures are unavailable below library version v2.3.0 and will return errors if used with incompatible libraries
- Use Libseccomp's `seccomp_version` API to retrieve library version
- Unconditionally set TSync attribute for filters, due to Go's heavily threaded nature
- Fix [CVE-2017-18367](https://nvd.nist.gov/vuln/detail/CVE-2017-18367) - …

[release/1.1 backport] bump libseccomp-golang v0.9.1

---

vendor.conf
vendor/github.com/seccomp/libseccomp-golang/README
vendor/github.com/seccomp/libseccomp-golang/seccomp.go
vendor/github.com/seccomp/libseccomp-golang/seccomp_internal.go

backport of https://github.com/containerd/containerd/pull/3371 for the 1.2 branch
full diff: https://github.com/seccomp/libseccomp-golang/compare/32f571b70023028bd57d9288c20efbcb237f3ce0...689e3c1541a84461afc49c1c87352a6cedf72e9c
Release notes:
* Version 0.9.1 - May 21, 2019
- Minimum supported version of libseccomp bumped to v2.2.0 (https://github.com/seccomp/libseccomp-golang/commit/fc0298087f328ac97a1fa781392de96b2ebb8aac)
- PowerPC and S390(x) architectures are unavailable below library version v2.3.0 and will return errors if used with incompatible libraries
- Use Libseccomp's `seccomp_version` API to retrieve library version
- Unconditionally set TSync attribute for filters, due to Go's heavily threaded nature
- Fix [CVE-2017-18367](https://nvd.nist.gov/vuln/detail/CVE-2017-18367) - …

[release/1.2 backport] bump libseccomp-golang v0.9.1

---

docs/ops.md

this ops is removed in commit fd2e3cd326b5ef58a7118658515911921d6731a1,
remove from doc avoid misleading users.

docs: remove shim_no_newns in ops.md

---

container_linux_test.go
runtime/v1/shim/client/client.go
runtime/v2/runc/v1/service.go
runtime/v2/runc/v2/service.go
runtime/v2/shim/util_unix.go
runtime/v2/shim/util_windows.go

This changes the shim's OOM score from a static max killable of -999 to
be +1 of the containerd daemon's score.  This should allow the shim's to
be killed first in an OOM condition but leave the daemon alone for a bit
to help cleanup and manage the containers during this situation.

Set shim OOM scores to +1 containerd daemon score

---

remotes/docker/fetcher_test.go
remotes/docker/resolver.go

Retry 5 times in case of StatusRequestTimeout StatusTooManyRequests
This fixes the issue #2680 "Make content fetch retry more robust"
Signed-off-by: Konstantin Maksimov <kmaksimov@gmail.com>

Handle RequestTimeout and TooManyRequests

---

cmd/ctr/commands/namespaces/namespaces.go
cmd/ctr/commands/namespaces/namespaces_linux.go
cmd/ctr/commands/namespaces/namespaces_other.go
metadata/namespaces.go
namespaces.go
namespaces/store.go
namespaces_opts_linux.go

Closes #3305
This adds an opt and a `--cgroup,-c` flag to `ctr namespaces rm` to
remove the cgroup that is commonly created with runtimes.

Add cgroup delete opt for ns deletion

---

cmd/containerd/command/main_windows.go
snapshots/lcow/lcow.go
snapshots/windows/windows.go
vendor.conf
vendor/github.com/Microsoft/go-winio/file.go
vendor/github.com/Microsoft/go-winio/go.mod
vendor/github.com/Microsoft/go-winio/hvsock.go
vendor/github.com/Microsoft/go-winio/pkg/etw/etw.go
vendor/github.com/Microsoft/go-winio/pkg/etw/eventdata.go
vendor/github.com/Microsoft/go-winio/pkg/etw/eventopt.go
vendor/github.com/Microsoft/go-winio/pkg/etw/fieldopt.go
vendor/github.com/Microsoft/go-winio/pkg/etw/newprovider.go
vendor/github.com/Microsoft/go-winio/pkg/etw/newprovider_unsupported.go
vendor/github.com/Microsoft/go-winio/pkg/etw/provider.go
vendor/github.com/Microsoft/go-winio/pkg/etw/wrapper_32.go
vendor/github.com/Microsoft/go-winio/pkg/etw/wrapper_64.go
vendor/github.com/Microsoft/go-winio/pkg/etw/zsyscall_windows.go
vendor/github.com/Microsoft/go-winio/pkg/etwlogrus/hook.go
vendor/github.com/Microsoft/go-winio/pkg/fs/fs_windows.go
vendor/github.com/Microsoft/go-winio/pkg/guid/guid.go
vendor/github.com/Microsoft/go-winio/syscall.go
vendor/github.com/Microsoft/go-winio/zsyscall_windows.go

This PR bumps the version of go-winio to the latest commit and refactors the lcow and windows snapshotters to use go-winio's utility functions for checking the filesystem type. This means other folks like myself can write more windows-based snapshotters without copy/pasting this code everywhere.
It seems there is one breaking change in the `EnableCallback` func in https://github.com/microsoft/go-winio/commit/a2a7cd6b7d9f8b079b910d0a8c21a1e9968df090#diff-affd4dec288883c3d72b7e20004dfae5 - hence the changes to `etwCallback`.
This PR closes #3362 
@kevpar / @jterry75 / @jhowardmsft PTAL.
Signed-off-by: Eric Hotinger <ehotinger@gmail.com>

Bump go-winio and refactor Windows snapshotters

---

cmd/ctr/commands/tasks/exec.go

This PR adds `--log-uri` flag for exec
`sudo ctr t exec --log-uri="file:///tmp/1.txt" ...`

Support --log-uri in exec subcommand

---

vendor.conf
vendor/github.com/containerd/go-runc/README.md
vendor/github.com/containerd/go-runc/runc.go

bump go-runc to 9007c2405372fe28918845901a3276c0915689a1
in order to support get actually error log if checkpint fail, this
version get two new diff
Add common project content/checks:
https://github.com/containerd/go-runc/commit/8e51df421218b765f393e1fdf97fac668913a8f4
Fix Method of judging command execution
failure:https://github.com/containerd/go-runc/commit/4e99c72acdb052ba374135c009bbc8ac9dd68249

vendor: bump go-runc

---

cmd/ctr/commands/images/images.go
cmd/ctr/commands/images/tag.go

Adds a subcommand for tagging images managed by containerd.
Usage:
```
ctr images tag docker.io/library/alpine:latest docker.io/library/alpine:new
```
Comes with a `--force` flag to allow you to gracefully overwrite image references
that already exist.
```
ctr images tag --force docker.io/library/alpine:latest docker.io/library/alpine:new
```
Also supports tagging to multiple images as well:
```
ctr images tag docker.io/library/alpine:latest docker.io/library/alpine:new docker.io/library/alpine:hello
```
Signed-off-by: Eli Uriegas <eli.uriegas@docker.com>

Add ctr images tag subcommand

---

runtime/v1/linux/proc/init.go
runtime/v1/shim/service.go

backport of #3148 for the 1.2 branch
Co-authored-by: Julia Nedialkova <julianedialkova@hotmail.com>
Signed-off-by: Georgi Sabev <georgethebeatle@gmail.com>

[release/1.2 backport] Skip rootfs unmount when no mounts are provided

---

client.go
cmd/ctr/commands/commands.go
cmd/ctr/commands/namespaces/namespaces.go
container.go
container_opts.go
container_opts_unix.go
image.go

- This PR slightly improves handling of default labels across containerd.
- Also respect `containerd.io/defaults/snapshotter` label in `ctr` pull/push and others
- Adds a few aliases for ctr namespace subcommand (`ctr ns ls` and `ctr ns c ...`)
ref: https://github.com/containerd/containerd/issues/2285

Better default label handling

---

platforms/compare.go
platforms/cpuinfo.go

This commit improves ARM platform matching in two instances:
* Some old kernels reported the CPU architecture of arm64 cpus as
Aarch64 [1].
* In cases where the user is running with armv8 cpu and kernel but amrhf
user land (so armhf containerd), a possibility given the compatibility
of armv8 with armv7.
[1] https://elixir.bootlin.com/linux/v3.14.29/source/arch/arm64/kernel/setup.c#L420
Closes #3387
Signed-off-by: Jaime Caamaño Ruiz <jcaamano@suse.com>

[release/1.2] Improve ARM platform matching

---

snapshots/testsuite/testsuite.go

For block device like devicemapper, umount before committing
active snapshot can sync data onto disk. Otherewise:
1. deactivating a block device in use will fail or IO error
when forced;
2. new snapshot on it will not catch the data not laid on disk yet.
Ref: #3405
Signed-off-by: Eric Ren <renzhen.rz@alibaba-linux.com>

[release/1.2] test/snapshots: umount before committing snapshot

---

cmd/ctr/commands/events/events.go

Without the open variable in use, no reason to define it or use it as the
for loop control.
cc: @fuweid 

Small refactor due to CI linter changes

---

Makefile
benchmark_test.go
client_test.go
container_checkpoint_test.go
container_linux_test.go
container_test.go
content/testsuite/testsuite.go
daemon_config_linux_test.go
export_test.go
image_test.go
import_test.go
lease_test.go
log/logtest/context.go
log/logtest/log_hook.go
metadata/containers_test.go
metadata/db_test.go
snapshots/testsuite/testsuite.go

Adds a function for configuring a context with logger which outputs to the test logs with debug level enabled. This allows for cleaner and more verbose test output with clearer ordering of logs along with failure conditions and time correlation for the daemon logs in integration tests.
Disables verbose logging by default in CI since this will cause more test log output by default. Verbose logging has little value as this output will always get shown now when the corresponding test fails.

Add unit test logging hook

---

images/image.go

When client uses Pull action to pull image, it will limit the number of
manifest as one. But Unpack action will call Manifest to traverse all
the manifests including non-dowloaded one. If the platform has more than
one manifest, the Pull with unpack action will fail. And also, there is
no need to read non-best matched manifest. Therefore, the Manifest can
do the sort earlier.

images: only fetch the best matched manifest info

---

client.go

The snapshot command calls the snapshotter service directly, therefore,
the name must be resolved.

Fix regression from #3403 with snapshot cmd

---

images/archive/importer.go
import_test.go

Ensure the manifest which gets created using the Docker compatibility code compresses the blob before creating the manifest. This ensures consistency with manifests generated by Docker.

Compress import blobs in Docker compatibility code

---

runtime/v1/linux/task.go

Fix a Rootless Docker-in-Docker issue on Fedora 30: https://github.com/docker-library/docker/pull/165#issuecomment-511717143
Related: #1598

runtime/v1/linux: ignore ErrCgroupDeleted in Task.Start

---

images/image.go

When client uses Pull action to pull image, it will limit the number of
manifest as one. But Unpack action will call Manifest to traverse all
the manifests including non-dowloaded one. If the platform has more than
one manifest, the Pull with unpack action will fail. And also, there is
no need to read non-best matched manifest. Therefore, the Manifest can
do the sort earlier.

[release/1.2] images: only fetch the best matched manifest info

---

Makefile

for example, `make DESTDIR=/usr install`.

Makefile: allow custom base path to install

---

remotes/docker/authorizer.go
remotes/docker/fetcher.go
remotes/docker/fetcher_test.go
remotes/docker/pusher.go
remotes/docker/registry.go
remotes/docker/registry_test.go
remotes/docker/resolver.go
remotes/docker/resolver_test.go

Adds support for registry mirrors
Adds support for multiple pull endpoints
Adds registry capabilities to limit trust in public mirrors or avoid pushing to mirrors
Adds support for generic header addition

Update resolver to handle endpoint configuration

---

remotes/docker/pusher.go
remotes/docker/resolver.go

Go documentation says `Use of GetBody still requires setting Body`.
This change ensures the body is always set in addition to GetBody. This fixes a bug where sometimes the body is nil.
Fixes #3427

Fix bug in setting request body

---

gc/gc.go
metadata/db_test.go
metadata/gc.go
metadata/gc_test.go

Provide a flag which configures a lease to only hold reference to its given references and ignore label references during garbage collection rooted from the lease.
This covers a use case to enable using longer lived leases which need to treat the references it is holding as immutable. Since labels are mutable, holding onto an object may cause the number of objects being referenced to grow even when the lease is only intending on keeping the original object. For example, a lease wants to keep a manifest, but not the blobs referred to within the manifest. When another process pulls in those blobs that lease now additionally holds those blobs even if the original process removed its reference to the manifest.
Also added higher level lease tests to test this case and normal leases.
cc …

Add flat GC label for leases

---

metadata/snapshot.go

fix the no-op issue.
(cherry picked from commit 4b3e0a8aaae2244e0239091fdd51dd3b4e08e28e)
cherry-pick: #3025

[cherry-pick release/1.2] metadata: merge snapshot labels with metadata's labels

---

client_test.go

If the registry returns a manifest without platform info, the
`manifest.Platform` will be `nil` and cause panic when dereferencing. Such as:
```
=== RUN   TestImagePullSomePlatforms
--- FAIL: TestImagePullSomePlatforms (0.02s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1371cf3]
```

test: Check manifest.Platform before dereferencing

---

cmd/ctr/commands/images/crypt_utils.go
docs/encryption.md
image_enc_test.go
images/encryption/encryption.go

There are some fixes required for garbage collection, as well as some optimizations for removal of certain resources from the lease for the image encryption feature introduced in https://github.com/containerd/containerd/pull/3134.
This PR aims to fix these known GC issues.

Made fixes and optimizations to encryption GC

---

RELEASES.md

Fix some wording and status of 1.1 release.
Note we have some unreleased stuff on the 1.1 branch. We can do a 1.1.8 release when needed with more than just a security fixes. Also I think we should keep that branch open for in flight fixes and allow a last update from CRI if needed. However after 1.1.8, we should deny any non-security patch.
Note: do not merge until tomorrow.

Update releases doc for 1.1 release

---

cmd/ctr/commands/tasks/delete.go

This pr include two things:
1. Add an aliase "rm" to task delete command
2. Update ctr to support deleting multiple tasks at a time
For the 2nd update now we can use "ctr task rm $(ctr task ls -q)" to quickly remove unused tasks.
The main body of the "exec-id" flag stays unchanged, which can only delete one exec at a time, the behavior of "exec-id" may need more discussion
Signed-off-by: BoWen Yan <loneybw@gmail.com>

Update ctr to support deleting multiple tasks at a time

---

cmd/ctr/commands/images/crypt_utils.go
cmd/ctr/commands/images/decrypt.go
cmd/ctr/commands/images/encrypt.go
image_enc_test.go
images/encryption/encryption.go
pkg/encryption/config/config.go
pkg/encryption/config/constructors.go
pkg/encryption/gpg.go

As a first step to https://github.com/containerd/containerd/issues/3443, we've provided interfaces via the encryption library to create the necessary `CryptoConfig` structures for encryption/decryption without the need to know internals of the encryption scheme..
We've implemented the following interfaces and updated `ctr` usage to use it. In addition, there is no longer any use of `dcparameters` in the codebase outside the encryption library - which uses its internals. 
```
func EncryptWithJwe(pubKeys [][]byte) (CryptoConfig, error) 
func EncryptWithPkcs7(x509s [][]byte) (CryptoConfig, error) 
func EncryptWithGpg(gpgRecipients [][]byte, gpgPubRingFile []byte) (CryptoConfig, error) 
func DecryptWithPrivKeys(privKeys [][]byte, privKeysPasswords [][]byte) (CryptoConfig, error) 
func …
```

Create CryptoConfig constructors to replace dcparameters

---

cmd/ctr/commands/images/import.go
images/archive/importer.go
import.go

Change the default back to leave uncompressed and add option to do the compression.
Fixes #3453
```
$ time ctr images import /tmp/kube-apiserver.tar                                                           
unpacking gcr.io/google-containers/kube-apiserver:v1.15.1 (sha256:91db5f34e0511159cb0eb24cd334f80be45561867f570b54b8aff9bcd3201073)...done
ctr images import /tmp/kube-apiserver.tar  0.85s user 0.17s system 15% cpu 6.537 total
$ time ctr images import --compress-blobs /tmp/kube-apiserver.tar
unpacking gcr.io/google-containers/kube-apiserver:v1.15.1 (sha256:2245106da92a70e3ed831b597641dcfefd5489a3e736598fb5598a14e37eb350)...done
ctr images import --compress-blobs /tmp/kube-apiserver.tar  18.03s user 6.20s system 81% cpu 29.866 total
```
As seen from above, the compression may add a …

Add option to compress blobs on import

---

runtime/v1/shim/client/client.go

fix mis-spelling in client.go

---

archive/compression/compression.go

fix wrong spells in compression.go

fix wrong spells in compression.go

---

docs/garbage-collection.md

Adds a doc related to the `containerd` daemon's garbage collector with what a user might need to know and how they might interact with it.

Add garbage collection doc

---

.mailmap
releases/v1.3.0-beta.toml

First draft of 1.3 release notes under beta. Please feel free to recommend further updates to the notes now or after the 1.3 beta notes are merged. Targeting for this to be merged and beta on Wednesday, July 31st.
As with previous betas, the beta will be cut directly from master and the betas and rcs will continue to be released from master. There is no restriction on merging during the beta period, however if a feature is specifically not intended for 1.3, we should wait to merge it. Once the rc period has started, then merges into master should only be bug/stability fixes or low risk changes. We will cut the 1.3.0 tag directly from master.
View a test generation of the notes [here](https://gist.github.com/dmcgowan/faa870c4a0890e739fd1aaf0cfd76eff)

Add 1.3 beta release notes

---

cmd/ctr/commands/images/crypt_utils.go
cmd/ctr/commands/images/encrypt.go
docs/encryption.md

Second part to address https://github.com/containerd/containerd/issues/3443. Modified `ctr images encrypt` command `--recipient` option to add a protocol prefix. i.e. `pgp:lumjjb@gmail.com`, `jwe:/path/to/pubkey`, `pkcs7:/path/to/x509`

Specify protocols in ctr encrypt recipients

---

pkg/ttrpcutil/client_windows.go
runtime/v2/shim/util_windows.go

AnonDialer will now return a "not found" error if the pipe is not found
before the timeout is reached. If the pipe exists but the timeout is
reached while attempting to connect, the timeout error will still be
returned.
This will allow the error handling logic to work properly when
connecting to the shim log pipe. An error message is only logged if the
error is not "not found", so now log noise from log pipes that were
never intended to be created by the shim will be hidden.
This change also cleans up the control flow for AnonDialer on Windows.
The new code should be more easily readable, but the only semantic
change is the error return value change.

Improve error return from AnonDialer on Windows

---

client.go
remotes/docker/pusher.go
remotes/docker/resolver.go

When pushing a manifest list, all manifests should be pushed by digest and only the final manifest pushed by tag. The Pusher was preventing this by mistakenly disallowing objects to contain a digest. When objects have a digest, only push tags associated with that digest.
Fixes #2639

Prevent push by tag for sub-manifests

---

services/tasks/local_unix.go
services/tasks/local_windows.go

Containerd on windows doesn't work now, because task service can't start because of the missing `io.containerd.runtime.v1`.
/cc @jterry75 

Fix containerd on windows.

---

remotes/docker/authorizer.go

Although the changes here are minimal, https://github.com/golang/go/blob/master/src/fmt/print.go#L978
I feel that it is better to avoid this unnecessary formatting.

remotes: remove unnecessary string formatting

---

snapshots/devmapper/device_info.go
snapshots/devmapper/metadata.go
snapshots/devmapper/metadata_test.go
snapshots/devmapper/pool_device.go
snapshots/testsuite/testsuite.go

This PR attempts to mitigate some cases described in https://github.com/containerd/containerd/pull/3436
It introduces faulty state for devices and devmapper device ID.
A device that is failed to create/activate and failed to rollback (delete back), will be marked as faulty in metadata store (instead of cleaning up the metadata and ending up in an inconsistent state). The snapshotter will try to recreate this device with a different devID in a subsequent call. This would allow us to move on and prevent the snapshotter to entirely stuck on a first faulty ID. 
A faulty device ID means that the snapshotter could not handle it (nor create nor rollback), and it needs manual handling. It'll be marked in metadata store and won't be reused by snapshotter until addressed and manually marked as ok. …

Better error recovery in device mapper

---

.travis.yml

Move matrix components next to each other for clarity.
Explicitly add special matrix combinations (Darwin and Linux V1 runtime)
This addresses the matrix part of #3491

Fix travis matrix

---

runtime/v2/shim.go

This avoids potential socket leak when the connected v2 shim of runtime
serving multiple containers.

v2: Close ttrpc connection when Delete()

---

.travis.yml

Explicitly add runc v1 runtime test on Linux.
Attempt at fixing slowness and flakiness from ppc64le before completely disabling.

Limit default matrix to runc v2 runtime

---

client.go

This is a regression introduced by https://github.com/containerd/containerd/issues/2285.
The CRI integration test [stops passing](https://github.com/containerd/cri/pull/1227) after upgrading containerd:
```
Error Trace:    containerd_image_test.go:47
Error:		Received unexpected error failed precondition
github.com/containerd/cri/vendor/github.com/containerd/containerd/errdefs.init.ializers
/usr/local/google/home/lantaol/workspace/src/github.com/containerd/cri/vendor/github.com/containerd/containerd/errdefs/errors.go:47
runtime.main
/usr/local/go/src/runtime/proc.go:188
runtime.goexit
/usr/local/go/src/runtime/asm_amd64.s:1337
namespace is required
github.com/containerd/cri/vendor/github.com/containerd/containerd/namespaces.NamespaceRequired …
```

Save default namespace in the client.

---

RELEASES.md

Add some clarifying language around the expectations on `ctr`.

Clarify text on `ctr` support/inclusion

---

.travis.yml

The tests run too slow and flaky. Once the flakiness and speed are addressed we can re-enable after the next release. Currently this is slowing down our release process.

Remove ppc64le from travis

---

images/image.go

client.Pull will only pull one matching platform by default.
When checking the size of image we match that behavior so that
we don't look for multiple platforms that might not exist on disk.
Fixes #3387 and #2991

Limit multiple platform manifests to one for size check

---

images/image.go

client.Pull will only pull one matching platform by default.
When checking the size of image we match that behavior so that
we don't look for multiple platforms that might not exist on disk.
Signed-off-by: Darren Shepherd <darren@rancher.com>
(cherry picked from commit 1161409779f0275f5e65a697d587ff893f9f9188)
cherry-pick: #3484

[release/1.2] cherry-pick: Limit multiple platform manifests to one for size check

---

.appveyor.yml

Use the latest Go release for testing on AppVeyor
> go1.12.7 (released 2019/07/08) includes fixes to cgo, the compiler,
> and the linker. See the Go 1.12.7 milestone on our issue tracker for details:
> 
> https://github.com/golang/go/issues?q=milestone%3AGo1.12.7

AppVeyor: update to go 1.12.7

---

vendor.conf
vendor/go.etcd.io/bbolt/freelist.go
vendor/go.etcd.io/bbolt/tx.go

this brings the dependency back to a released version:
full diff: go.etcd.io/bbolt https://github.com/etcd-io/bbolt/compare/2eb7227adea1d5cf85f0bc2a82b7059b13c2fa68...v1.3.3
- etcd-io/bbolt#153 fix rollback panic bug
- fixes etcd-io/bbolt#152 Panic (index out of range) on writeable tx rollback with db.NoFreelistSync

bump go.etcd.io/bbolt v1.3.3

---

cmd/ctr/commands/run/run.go
cmd/ctr/commands/run/run_unix.go
cmd/ctr/commands/run/run_windows.go

Cherry-pick #2828 since it is effectively a bug-fix as there is no use of the flag on non-Windows.

[release/1.2] cherry-pick: Move ctr run --isolation to Windows only

---

.appveyor.yml
contrib/Dockerfile.test

backports of:
- https://github.com/containerd/containerd/pull/3185 Update contrib/Dockerfile.test 
- https://github.com/containerd/containerd/pull/3523 AppVeyor: update to go 1.12.7
- https://github.com/containerd/containerd/pull/3531 AppVeyor: update to go 1.12.8 (CVE-2019-9512, CVE-2019-9514)

[release/1.2 backport] update to go 1.12.8 (CVE-2019-9512, CVE-2019-9514)

---

.appveyor.yml

go1.12.8 (released 2019/08/13) includes security fixes to the net/http and net/url packages.
See the Go 1.12.8 milestone on our issue tracker for details:
https://github.com/golang/go/issues?q=milestone%3AGo1.12.8
- net/http: Denial of Service vulnerabilities in the HTTP/2 implementation
net/http and golang.org/x/net/http2 servers that accept direct connections from untrusted
clients could be remotely made to allocate an unlimited amount of memory, until the program
crashes. Servers will now close connections if the send queue accumulates too many control
messages.
The issues are CVE-2019-9512 and CVE-2019-9514, and Go issue golang.org/issue/33606.
Thanks to Jonathan Looney from Netflix for discovering and reporting these issues.
This is also fixed in version …

AppVeyor: update to go 1.12.8 (CVE-2019-9512, CVE-2019-9514)

---

vendor.conf
vendor/github.com/containerd/cri/pkg/config/config.go
vendor/github.com/containerd/cri/pkg/server/container_create.go
vendor/github.com/containerd/cri/pkg/server/helpers.go
vendor/github.com/containerd/cri/pkg/server/image_pull.go
vendor/github.com/containerd/cri/pkg/server/sandbox_run.go
vendor/github.com/containerd/cri/pkg/store/image/image.go
vendor/github.com/containerd/cri/vendor.conf

* CRI: Fix a bug that if an image is deleted immediately after being pulled, the image may still exist after the deletion finishes successfully. (https://github.com/containerd/cri/issues/1161)
* CRI: Updated libseccomp-golang to v0.9.1. ***NOTE: The minimum requirement of libseccomp is bumped to 2.3.0.*** (https://github.com/containerd/cri/pull/1191)
* CRI: Fix a bug that `runc` and `crictl` binaries shipped in https://storage.googleapis.com/cri-containerd-release are versioned with the containerd version. (https://github.com/containerd/cri/pull/1193)
* CRI: Fix a bug that the images become unusable if 2 images have the same image ID and RepoTag, but different RepoDigests. (https://github.com/containerd/containerd/issues/3401)
* CRI: Fix …

[release/1.2] Update cri to d928a4dd337fd2a992dbe72380eff2063c3ec62f.

---

vendor.conf
vendor/github.com/seccomp/libseccomp-golang/README
vendor/github.com/seccomp/libseccomp-golang/seccomp.go
vendor/github.com/seccomp/libseccomp-golang/seccomp_internal.go

This reverts commit d8f4da4fef8a8f82b2252defd1778271e9640225 (https://github.com/containerd/containerd/pull/3376), which was a backport of https://github.com/containerd/containerd/pull/3371
Per the discussion on https://github.com/containerd/containerd/pull/3371#issuecomment-515634600, this bump caused the minimum supported seccomp version to be changed from 2.3.0, which caused older distros to no longer be supported.
Note that the fix for [CVE-2017-18367](https://nvd.nist.gov/vuln/detail/CVE-2017-18367) was already in the version we vendored before the bump (and the actual issue is in RunC; RunC 1.0.0-rc8 has the fix in place already.

[release/1.2] Revert "bump libseccomp-golang v0.9.1"

---

vendor.conf
vendor/github.com/seccomp/libseccomp-golang/README
vendor/github.com/seccomp/libseccomp-golang/seccomp.go
vendor/github.com/seccomp/libseccomp-golang/seccomp_internal.go

This reverts commit f2d1981758b0b3a8e39da9c367c3c733d97d6999 (https://github.com/containerd/containerd/pull/3375)
which was a backport of https://github.com/containerd/containerd/pull/3371
Per the discussion on https://github.com/containerd/containerd/pull/3371#issuecomment-515634600, this bump caused the minimum supported seccomp version to be changed from 2.3.0, which caused older distros to no longer be supported.
Note that the fix for [CVE-2017-18367](https://nvd.nist.gov/vuln/detail/CVE-2017-18367) was already in the version we vendored before the bump (and the actual issue is in RunC; RunC 1.0.0-rc8 has the fix in place already.

[release/1.1] Revert "bump libseccomp-golang v0.9.1"

---

.appveyor.yml

Signed-off-by: Jintao Zhang <zhangjintao9020@gmail.com>
go1.12.9 (released 2019/08/15) includes fixes to the linker,
and the <code>os</code> and <code>math/big</code> packages.
See the <a href="https://github.com/golang/go/issues?q=milestone%3AGo1.12.9+label%3ACherryPickApproved">Go
1.12.9 milestone</a> on our issue tracker for details.
Full diff https://github.com/golang/go/compare/go1.12.8...go1.12.9
Going ahead and filing this.  Follow #3531

AppVeyor: update to go 1.12.9

---

.appveyor.yml

backport of https://github.com/containerd/containerd/pull/3541
(cherry picked from commit 7682acb9e7c97a1d8d2b0a56f61801dbfe1a1518)
Addresses https://github.com/containerd/containerd/issues/3481, https://github.com/golang/go/issues/33405

[release/1.2 backport] AppVeyor: update to go 1.12.9

---

oci/spec_opts.go
oci/spec_opts_test.go

the Env in image should be default value, it should has override by the Env in process. otherwise the Env in image is immutable,  setting the Env in process will be meaningless

bugfix: override image.Env with process.Env, rather than be contrary

---

oci/spec_opts.go
oci/spec_opts_test.go

Signed-off-by: Yangyang <1032120121@163.com>
Signed-off-by: Andrey Kolomentsev <andrey.kolomentsev@docker.com>
*includes backport of some test framework code due to cherry-pick conflicts around the env/image config test*
Cherry-pick/backport of #3542 
Backport of #2887

[release/1.2] backport bugfix: override image.Env with process.Env, rather than be contrary

---

runtime/v2/binary.go
runtime/v2/shim_unix.go
runtime/v2/shim_unix_test.go
runtime/v2/shim_windows.go
runtime/v2/shim_windows_test.go

When using a multi-container shim, the fifo of the 2nd to Nth container will not be opened when the ctx is done. This will cause a "closed fifo" error that can be ignored.

Ignore fifo error when using v2 multi-container shim

---

cmd/containerd/command/config.go
pkg/timeout/timeout.go
runtime/v2/shim.go
services/server/config/config.go
services/server/server.go
services/tasks/local.go

This adds a singleton `timeout` package that will allow services and user
to configure timeouts in the daemon.  When a service wants to use a
timeout, it should declare a const and register it's default value
inside an `init()` function for that package.  When the default config
is generated, we can use the `timeout` package to provide the available
timeout keys so that a user knows that they can configure.
These show up in the config as follows:
```toml
[timeouts]
"io.containerd.timeout.shim.cleanup" = "5s"
"io.containerd.timeout.shim.load" = "5s"
"io.containerd.timeout.shim.shutdown" = "300ms"
"io.containerd.timeout.task.state" = "100ms"
```
Timeouts in the config are specified as a string and parsed as a duration.
Timeouts are very hard to get right and giving this power to the user to …

Allow timeouts to be configured in config

---

oci/spec.go
oci/spec_opts.go

With the change in #3542 it breaks $PATH handling for images becuase our
default spec always sets a PATH on the process's .Env.
This removes the default and adds an Opt to add this back.

Remove the process default ENV

---

sys/reaper/reaper_unix.go

Shim use non-blocking send now, there is no need to set bufferSize to 2048,
it's a waste.
link to https://github.com/containerd/containerd/pull/3540
Signed-off-by: Shukui Yang <keloyangsk@gmail.com>

Change bufferSize back to 32

---

runtime/v1/shim/service.go
runtime/v2/runc/v2/service.go

When containerd-shim does reaper, the most processes are not init
process. Since json.Decode consumes more CPU resource, we should check
killall option for init process only.
link to https://github.com/containerd/containerd/pull/3540#issuecomment-522949740

runtime: only check killall for init process

---

oci/spec.go
oci/spec_opts.go

With the change in #3542 it breaks $PATH handling for images becuase our
default spec always sets a PATH on the process's .Env.
This removes the default and adds an Opt to add this back.
Cherry-pick of #3551

[release/1.2] cherry-pick: Remove the process default ENV

---

diff/apply/apply.go

This was removed by mistake during the direct unpack PR refactoring.
Test needed, but this fixes a pull regression
Closes #3569

Read trailing data on apply

---

.mailmap
releases/v1.3.0-rc.toml

The beta period has ended, start preparing rc release notes.
Updated note about Windows runtime, please advice here on what our messaging should be (ping @jterry75). As far as I understand it, we will accept backports to 1.3 related to the Windows runtime , which is our criteria for support.

Update 1.3 release notes and mailmap

---

.mailmap
releases/v1.2.8.toml
version/version.go

Add release notes and update version in preparation for v1.2.8 release
of containerd.
Preview of release notes: https://gist.github.com/estesp/d39a93bf47ed57ba2251265a4b718f25

Prepare v1.2.8 point release

---

cmd/containerd/command/main.go
plugin/context.go
runtime/v2/binary.go
runtime/v2/example/example.go
runtime/v2/manager.go
runtime/v2/runc/v1/service.go
runtime/v2/runc/v2/service.go
runtime/v2/shim/shim.go
runtime/v2/shim/util.go
services/server/config/config.go
services/server/server.go

Previously the TTRPC address was generated as "<GRPC address>.ttrpc".
This change now allows explicit configuration of the TTRPC address, with
the default still being the old format if no value is specified.
As part of this change, a new configuration section is added for TTRPC
listener options.

Allow explicit configuration of TTRPC address

---

runtime/v2/runc/v1/service.go
runtime/v2/runc/v2/service.go
runtime/v2/shim/shim.go
runtime/v2/shim/util.go

Because of the way go handles flags, passing a flag that is not defined
will cause an error. In our case, if we kept this as a flag, then
third-party shims would break when they see this new flag.  To fix this,
I moved this new configuration option to an env var.  We should use env
vars from here on out to avoid breaking shim compat.

Pass ttrpc address to shim via env

---

.travis.yml
script/setup/install-seccomp

lib seccomp 2.4 has huge performance regressions.
This change pins to 2.3.3 where that is not an issue

Pin to libseccomp 2.3.3

---

client.go
client_unix_test.go
pull.go
unpacker.go

For #2886.
Time consumed to pull k8s.gcr.io/kube-cross:v1.10.3-1 on my machine:
* Containerd HEAD: 40.347s
* Containerd HEAD + https://github.com/containerd/containerd/pull/2913: 35.65s
* Containerd HEAD + this change: 37.86s
* Containerd HEAD + https://github.com/containerd/containerd/pull/2913 + this change: 32.95s

Add simultaneous unpack support

---

cmd/containerd-stress/rlimit_unix.go

When we ran the containerd-stress command, we met that 
```
panic: invalid argument
goroutine 1 [running]:
main.init.0()
/home/fesu/go/src/github.com/containerd/containerd/cmd/containerd-stress/main.go:59 +0x4aa
```
In our os, the value of nofile is 
```
RESOURCE   DESCRIPTION                             SOFT      HARD UNITS
NOFILE     max number of open files                1024      4096
```
It will cause EINVAL error if we set soft value is 100000 and keep the hard value is 4096

update the max if cur will be greater than max for setting the limit

---

vendor.conf
vendor/github.com/containerd/zfs/zfs.go

https://github.com/containerd/zfs/compare/31af176f2ae84fe142ef2655bf7bb2aa618b3b1f...2ceb2dbb8154202ed1b8fd32e4ea25b491d7b251
Fix containerd/zfs#22

bump containerd/zfs 2ceb2dbb8154202ed1b8fd32e4ea25b491d7b251

---

oci/spec_opts.go
oci/spec_opts_unix_test.go

Fixes: #3597 
Only open question IMO is whether we want to investigate whether a config has a `$PATH` set versus simply checking for a nil/empty environment in the image config.

Use default UNIX env when image has no environment

---

cmd/ctr/commands/commands.go
cmd/ctr/commands/run/run_unix.go
contrib/seccomp/seccomp.go
contrib/seccomp/seccomp_default.go
contrib/seccomp/seccomp_default_unsupported.go

This also adds a `--seccomp` flag to ctr to help in testing seccomp related changes.

Add sigprocmask to default seccomp profile

---

oci/spec_opts.go
oci/spec_opts_unix_test.go

Cherry-pick bc692cc59dd6f9d475e92e2bf17742fce38ca0a3 from master PR #3599 

[release/1.2] cherry-pick: Use default UNIX env when image has no environment

---

snapshots/devmapper/pool_device.go
snapshots/devmapper/pool_device_test.go

- reproducer
1. stop a container;
2. reboot, or dmsetup remove its corresponding dm device;
3. start the container, it will fail like:
"""
Error: failed to start containers: {"message":"failed to create container(4f33d2760760c41518a84821153ccdf7f80980b797b783cdd75178fc6ca0bf4b) on containerd: failed to create task for container(4f33d2760760c41518a84821153ccdf7f80980b797b783cdd75178fc6ca0bf4b): failed to mount rootfs component &{ext4 /dev/mapper/vg0-mythinpool-snap-2 []}: no such file or directory: unknown"}
"""
- how the fix works
activate the dm device if necessary, and give a warn msg:
"""
time="2019-08-21T22:44:08.422695797+08:00" level=warning msg="devmapper device \"vg0-mythinpool-snap-2\" marked as \"Activated\" but not active, activating it"
"""
Signed-off-by: Eric Ren …

devmapper: activate dm device if snap device marked as activated

---

cmd/containerd/command/main_unix.go

When containerd receives more than 1 terminate signal before shutdown, it may panic:
```
panic: close of closed channel
goroutine 10 [running]:
github.com/containerd/cri/vendor/github.com/containerd/containerd/cmd/containerd/command.handleSignals.func1(0xc00015dd40, 0xc00015dce0, 0x1fa21a0, 0xc0000420f0, 0xc0000a43c0)
/usr/local/google/home/lantaol/workspace/src/github.com/containerd/cri/vendor/github.com/containerd/containerd/cmd/containerd/command/main_unix.go:60 +0x2e2
created by github.com/containerd/cri/vendor/github.com/containerd/containerd/cmd/containerd/command.handleSignals
/usr/local/google/home/lantaol/workspace/src/github.com/containerd/cri/vendor/github.com/containerd/containerd/cmd/containerd/command/main_unix.go:41 +0x89
```

Fix potential containerd panic during graceful shutdown.

---

cio/io_unix.go
container.go

We added unknown state support for task in https://github.com/containerd/containerd/commit/101d4b78eb7fc0ef2be6dea1cfe2e5cf277df622. And task in unknown state will have empty fifos path.
However, we continue attach IO for task in unknown state https://github.com/containerd/containerd/blob/master/container.go#L386, which will potentially trigger a panic, because `copyIO` tries access nil `stdout`.
This PR:
1) Avoids attaching IO if task is in unknown state;
2) Fix io attaching helper to tolerant empty stdout fifo path.

Fix potential panic for task in unknown state.

---

cmd/ctr/commands/namespaces/namespaces_linux.go
runtime/opts/opts_linux.go

The cgroup dependency brings in quite a lot only for WithNamespaceCgroupDeletion, which is a namespaces.DeleteOpt.
Signed-off-by: Tibor Vass <tibor@docker.com>

runtime/opts: move WithNamespaceCgroupDeletion from containerd to its own package

---

.travis.yml

Using bionic (current LTS) as default, and adding `xenial` (Ubuntu 16.04 LTS) to the matrix, to test the previous LTS release as well
(see discussion on https://github.com/rootless-containers/usernetes/pull/111)

travis: add Bionic (Ubuntu 18.04) to test matrix

---

services/server/config/config.go

Proxy plugins are keyed only on the identifier, the type is specified within the proxy plugin configuration which maps to the full URI. The proxy plugin configuration is not passed to the plugin for configuration like other plugins.
Fixes a compatibility error with proxy plugins from v1 configs. Fixing the validation caused the proxy plugin ID to be wrong since "io.containerd.snapshotter.v1" or "io.containerd.content.v1" is always added based on the type.

Fix proxy plugin config validation

---

archive/tar.go

Cherry-pick commit 372472b5f648bccb7c3045ccd5921b0082fd87bb from master PR #3589 

[release/1.2] cherry-pick: archive: truncate modification time

---

unpacker.go

Fix unpacker for foreign layers and encrypted layers.
Not sure whether we should add a helper to check whether a media type is a layer.

Support foreign and encrypted layers in the unpacker.

---

client.go
client_opts.go
container_opts.go
container_opts_unix.go
container_restore_opts.go
image.go
import.go
install.go
pull.go

For https://github.com/containerd/cri/issues/1257
The default platform may not always work, we should have getters for users to specify platforms.
In the CRI plugin, our first planned milestone for windows support is WCOW with process isolation only ([previous discussion](https://docs.google.com/document/d/1PKlmTIh0-qSzGDPhYmc_5BJjdD9GRdMGIATzvlhUAwM/edit)). And the [default platform matcher](https://github.com/containerd/containerd/blob/master/platforms/defaults_windows.go#L27) in containerd won't work for that, because LCOW is included.

Make default platform configurable in the client

---

services/server/config/config_test.go

config imports is in random order after LoadConfig call so that the
testing check should be done after sort.Strings(out.Imports).

config_test: sort result before check

---

remotes/docker/authorizer.go
remotes/docker/resolver.go
remotes/docker/schema1/converter.go

backport of https://github.com/containerd/containerd/pull/3245 for the 1.2 branch
Adds a fallback to manually compute the manifest digest when it is not presented as the Docker-Content-Digest header by the registry server. This is to address #3238.
closes #3238
addresses parts of https://github.com/containerd/containerd/issues/3291

[release/1.2 backport] Compute manifest metadata when not provided.

---

platforms/database.go

Update the lists in isKnownOS and isKnownOS according to goosList and
goarchList taken from Go 1.13, see
https://github.com/golang/go/blob/release-branch.go1.13/src/go/build/syslist.go
Signed-off-by: Tobias Klauser <tklauser@distanz.ch>

platforms: update known OS and arch values

---

.mailmap
releases/v1.2.9.toml
version/version.go

Only change is fixes for gRPC CVE issues by updating vendor to gRPC 1.23.0 release via PR #3586.
Preview draft of release notes: https://gist.github.com/estesp/8dfeab5baf156ea1dc92793043193167

Prepare v1.2.9 release

---

.mailmap

Add new contributors for 1.3.
Simplify mailmap by removing unnecessary commit names. Refer to https://git-scm.com/docs/git-check-mailmap for how the mapping occur. Verified change with `git log --format='%aN <%aE>' | sort -u`

Update and simplify mailmap

---

cmd/ctr/commands/resolver.go

ctr: use NewDockerAuthorizer instead of deprecated NewAuthorizer

---

.travis.yml
Makefile
script/release/release-cri
vendor.conf
vendor/github.com/containerd/cri/pkg/server/io/container_io.go
vendor/github.com/containerd/cri/pkg/server/io/helpers.go

For https://github.com/containerd/containerd/issues/3627
This depends on https://github.com/containerd/cri/pull/1267.
Currently this should be triggered every build and deploy to `cri-containerd-staging`. After testing that this works, I'll change it to only build on new tag and deploy to `cri-containerd-release`.
@dmcgowan 

Automate CRI tarball release.

---

Makefile

The CRI plugin build script doesn't like the `v` in the version.

Fix CRI release build.

---

.travis.yml
script/setup/install-critools

Update cri validation test to fix the image reference test:
```
• Failure [1.718 seconds]
[k8s.io] Image Manager
/home/travis/gopath/src/github.com/kubernetes-sigs/cri-tools/pkg/framework/framework.go:72
public image without tag should be pulled and removed [Conformance] [It]
/home/travis/gopath/src/github.com/kubernetes-sigs/cri-tools/pkg/validate/image.go:47
failed to pull image: rpc error: code = NotFound desc = failed to pull and unpack image "gcr.io/cri-tools/test-image-latest:latest": unpack: failed to prepare extraction snapshot "extract-151995760-DQ8D sha256:749539d5cc3b63b2fd60be0340a8e7ca88fd6fe0c639a605d46d3513778ac7f7": parent snapshot sha256:0d315111b4847e8cd50514ca19657d1e8d827f4e128d172ce8b2f76a04f3faea does not exist: not found
Unexpected error:
<*status.statusError | …
```

Update cri test to fix image reference test.

---

vendor.conf
vendor/github.com/containerd/go-runc/command_linux.go

Includes fix for user namespaces and NOTIFY_SOCKET.

Update go-runc to e029b79d8cda8374981c64eba71f28e

---

vendor.conf
vendor/github.com/containerd/go-runc/README.md
vendor/github.com/containerd/go-runc/command_linux.go
vendor/github.com/containerd/go-runc/runc.go

Includes fix for user namespaces and NOTIFY_SOCKET.

[release/1.2] Update go-runc to e029b79d8cda8374981c64eba71f28e

---

.travis.yml
script/release/deploy-cri

This PR:
1) Add `skip_clean: true`, so that release tarballs won't be cleaned up before deploy. See the following log without such change:
```
Cleaning up git repository with `git stash --all`. If you need build artifacts for deployment, set `deploy.skip_cleanup: true`. See https://docs.travis-ci.com/user/deployment#Uploading-Files-and-skip_cleanup.
```
2) Skip tarball upload if it already exists. This is important because we have builds for shim v1 and v2. It is possible that shim v1 build uploads the eventual tarball, but shim v2 build uploads the eventual sha256 file.

Skip cleanup in travis deploy and avoid gcs race condition.

---

.travis.yml

Currently removing this incomplete build is part of the release
process. Skip this deployment to make releases easier.

Skip darwin deploy on release

---

cmd/ctr/commands/client.go

the `connect-timeout` global flag was already defined, but not used.

implement ctr --connect-timeout

---

runtime/v2/binary.go
runtime/v2/shim.go
runtime/v2/shim/util_unix.go
runtime/v2/shim/util_windows.go
runtime/v2/shim_unix.go
runtime/v2/shim_windows.go

Previously for windows, when containerd restarts and attempts to reconnect to shim pipes, if the pipe file is not found for a shim, containerd would wait up to 5 seconds before returning a failure. If containerd is still attempting to connect to shims after 30 seconds, the windows service manager will kill containerd. This work breaks up the cases of connecting to shims into two cases: shim starting and shim reconnecting. In the former, containerd will still wait up to 5 seconds for a pipe to be served by a starting shim. In the latter, containerd will return file not found immediately when attempting to connect to a nonexistent or dead shim.  

fail on file not found for shim reconnect on containerd restart

---

remotes/handlers.go
remotes/handlers_test.go

Adds a method for setting a custom media type key prefix used by the
fetch handler.
This allows both overwriting a built-in prefix (for reasons?) as well as
supplying a custom media type.
I added this because I was getting an error on `FetchHandler` when
pulling docker plugin images which have their own media type.

Get media type key from context

---

remotes/docker/scope.go
remotes/docker/scope_test.go

Currently auth.docker.io uses a custom auth scope for (docker) plugins
`repository(plugin):<repo>:<perms>`.
This makes it impossible to use containerd distribution tooling to fetch
plugins without also supplying a totally custom authorizer.
This changes allows clients to set the correct scope on the context.
It's a little bit nasty but "works".
I'm also a bit suspect of some a couple of these unexported context
functrions. Before the primary one used `contextWithRepositoryScope`
overwrites any scope value and there is nother one that appends the
scope value.
With this change they both append...

Add function to set custom auth scope in context

---

.golangci.yml
Makefile

As mentioned [here](https://github.com/containerd/containerd/pull/3660#issuecomment-532750302) might as well put it in our existing config file.

Move golangci-lint deadline to config file

---

diff/stream.go
images/image.go
images/mediatypes.go
remotes/handlers.go
unpacker.go

Updates layer support to generically handle the OCI layer types, removing the need to continue to add to a long list of possible values. For example, encrypted containers are using "+enc", however this is not yet standardized but support is desirable. Additionally, OCI has added "+zstd" to define zstd compression. This change ensures "+zstd" defines the correct compression algorithm and adds it to the compression library.

Generic layer support

---

metrics/cgroups/blkio.go
metrics/cgroups/cpu.go
metrics/cgroups/hugetlb.go
metrics/cgroups/memory.go
metrics/cgroups/metric.go
metrics/cgroups/metrics.go
metrics/cgroups/pids.go
metrics/types/v1/types.go

This will help to decouple the import in CRI from the cgroups package
directly by importing the type alias in containerd repo.

Add metrics type alias

---

daemon_config_linux_test.go

Don't search for state.json path in tests

---

pkg/process/utils.go

Check for more kill error types

---

cmd/gen-manpages/main.go

`make genman` does not work if the `man` directory does not exist first

gen-manpages: Create man directory if it does not exist

---

vendor.conf
vendor/github.com/containerd/cri/pkg/server/container_create.go

* Fix a bug that the default `PATH` is not set in the container https://github.com/containerd/cri/issues/1279.

[release/1.2] Update cri to 40affe7c7402d41618b9791a8cf105ac74ce56d0.

---

.appveyor.yml

full diff: https://github.com/golang/go/compare/go1.12.9...go1.12.10
```
Hi gophers,
We have just released Go 1.13.1 and Go 1.12.10 to address a recently reported security issue. We recommend that all affected users update to one of these releases (if you're not sure which, choose Go 1.13.1).
net/http (through net/textproto) used to accept and normalize invalid HTTP/1.1 headers with a space before the colon, in violation of RFC 7230. If a Go server is used behind an uncommon reverse proxy that accepts and forwards but doesn't normalize such invalid headers, the reverse proxy and the server can interpret the headers differently. This can lead to filter bypasses or request smuggling, the latter if requests from separate clients are multiplexed onto the same upstream connection by the proxy. …
```

AppVeyor: bump golang 1.12.10 (CVE-2019-16276)

---

.appveyor.yml

backport of https://github.com/containerd/containerd/pull/3686
full diff: https://github.com/golang/go/compare/go1.12.9...go1.12.10
```
Hi gophers,
We have just released Go 1.13.1 and Go 1.12.10 to address a recently reported security issue. We recommend that all affected users update to one of these releases (if you're not sure which, choose Go 1.13.1).
net/http (through net/textproto) used to accept and normalize invalid HTTP/1.1 headers with a space before the colon, in violation of RFC 7230. If a Go server is used behind an uncommon reverse proxy that accepts and forwards but doesn't normalize such invalid headers, the reverse proxy and the server can interpret the headers differently. This can lead to filter bypasses or request smuggling, the latter if requests from separate clients …
```

[release/1.2 backport] AppVeyor: bump golang 1.12.10 (CVE-2019-16276)

---

linux/proc/exec.go
linux/proc/utils.go

Backport for #3361
This and a combination of a couple Docker changes are needed to fully
resolve the issue on the Docker side.  However, this ensures that after
processes exit, we still leave some time for the I/O to fully flush
before closing.  Without this timeout, the delete methods would block
forever.

[release/1.1] Add timeout for I/O waitgroups

---

releases/v1.2.10.toml
version/version.go

Draft of the release notes: https://gist.github.com/estesp/6d8443467f23c039f85725ed69a91e89

[release/1.2] Prepare v1.2.10 release

---

script/release/release-cri

Get CRI dependency versions from the containerd vendor.conf.
The `vendor.conf` in `cri` might be out of date, the containerd `vendor.conf` should be the source of truth for actual release.

Get CRI dependency versions from containerd vendor.conf.

---

script/setup/install-critools
vendor.conf

Update cri to 5d49e7e51b43e36a6b9c4386257c7d08c602237f, and critest to v1.16.1.
All CRI changes are done for 1.3.0 after this I believe.

Update cri to 5d49e7e51b43e36a6b9c4386257c7d08c602237f.

---

remotes/docker/fetcher.go
remotes/docker/pusher.go
remotes/docker/resolver.go

Fixes the media type to align with Accept HTTP header RFC which specifies glob syntax */*
See https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html
Related to #3291

Fix all media types in Accept header to match RFC

---

RELEASES.md
releases/v1.3.0.toml
version/version.go

Updated release docs and notes for 1.3.0 final
Hold on this until after 1.1.8 and 1.2.10
Example of generated notes https://gist.github.com/dmcgowan/faa870c4a0890e739fd1aaf0cfd76eff

Update release docs for 1.3.0

---

Makefile
cmd/ctr/app/main.go
vendor/github.com/urfave/cli/autocomplete/bash_autocomplete
vendor/github.com/urfave/cli/autocomplete/zsh_autocomplete

This enables shell autocompletion for ctr command. I whitelisted the autocompletes in urfave/cli so users can enable and distribute it. See also: https://github.com/urfave/cli#bash-completion

ctr: Enable shell autocompletion

---

README.md

Add more detail to the README.md where releases are found and also add
the documentation for how to use the new auto-completion capabilities
provided by urfave and enabled in a recent PR.
(Related to comment in #3706)

Add more detail on releases to README

---

pkg/process/deleted_state.go
pkg/process/exec.go
pkg/process/exec_state.go
pkg/process/init.go
pkg/process/init_state.go
pkg/process/utils.go

See https://github.com/kubernetes/kubernetes/issues/82440 and https://github.com/moby/moby/issues/39102
I think we should cherry-pick this into 1.2 and 1.3.
In Kubernetes, we observed that exec in containerd is fair expensive. With Docker 18.09, for each exec process, 8 `runc state` processes will be spawned.
The followings are results of `sudo strace -f -p SHIM_PID -e execve` when we simply run a `crictl exec CONTAINER_ID echo hello`.
* Containerd with `containerd-shim` (I believe most people are still using this):
```console
$ cat result | grep execve
[pid 229037] execve("/usr/local/sbin/runc", ["runc", "--root", "/run/containerd/runc/k8s.io", "--log", "/run/containerd/io.containerd.ru"..., "--log-format", "json", "state", "174c9870fbd569c79d7e8d706323134a"...], 0xc000059000 /* 6 vars …
```

Use cached state instead of `runc state`.

---

lease.go

It's sometimes useful to specify a custom lease configuration. In this
case clients have to deal with LeaseManager manually to create/defer delete lease (essentially dup
`WithLease` logic). This PR adds lease opts to `WithLease`, so options
can be specified inline.

Make client's WithLease more flexible

---

vendor.conf

No code changes since the last vendor bump (https://github.com/containerd/containerd/pull/3713)

bump runc v1.0.0-rc9

---

snapshots/btrfs/btrfs.go
snapshots/btrfs/btrfs_test.go

The btrfs tests are still flaky, this change may not fix the flaky test but will provide more information. Previously the error message was not helpful since it was the result of a creation attempt after unmount.
Add logging and move the creation of the snapshotter inside
the attempt loop to catch cases where the mountinfo may
not be updated yet. When all attempts are reached there
is no reason to create the snapshotter as the unmount has
already occurred.

Fix flaky btrfs test

---

Makefile
cmd/ctr/commands/version/version.go
version/version.go

Signed-off-by: fahed dorgaa <fahed.dorgaa@gmail.com>
It is important to have the go version in the client and server description. This PR handle only the go version in the client. We should do the same think for server.

adding go version to client description

---

vendor.conf
vendor/github.com/opencontainers/runc/README.md
vendor/github.com/opencontainers/runc/libcontainer/apparmor/apparmor.go
vendor/github.com/opencontainers/runc/libcontainer/configs/config.go
vendor/github.com/opencontainers/runc/libcontainer/seccomp/config.go
vendor/github.com/opencontainers/runc/libcontainer/seccomp/seccomp_linux.go
vendor/github.com/opencontainers/runc/libcontainer/utils/cmsg.go
vendor/github.com/opencontainers/runc/libcontainer/utils/utils.go
vendor/github.com/opencontainers/runc/libcontainer/utils/utils_unix.go
vendor/github.com/opencontainers/runc/vendor.conf
vendor/github.com/seccomp/libseccomp-golang/README
vendor/github.com/seccomp/libseccomp-golang/seccomp.go
vendor/github.com/seccomp/libseccomp-golang/seccomp_internal.go

backport of:
- revert https://github.com/containerd/containerd/pull/3538 [release/1.2] Revert "bump libseccomp-golang v0.9.1"
- brings back https://github.com/containerd/containerd/pull/3376 [release/1.2 backport] bump libseccomp-golang v0.9.1, which was a backport of https://github.com/containerd/containerd/pull/3371 bump libseccomp-golang v0.9.1
- Per the discussion on https://github.com/containerd/containerd/pull/3371#issuecomment-515634600, this causes the minimum supported seccomp version to be changed from 2.3.0, if containerd is compiled on a machine that has this version of seccomp installed, in which case, it will cause older distros to no longer be supported.
- https://github.com/containerd/containerd/pull/3713 Bump runc to 1b8a1eeec3f337ab5d94f28980
- …

[release/1.2 backport] bump runc v1.0.0-rc9

---

vendor.conf
vendor/github.com/opencontainers/runc/README.md
vendor/github.com/opencontainers/runc/libcontainer/apparmor/apparmor.go
vendor/github.com/opencontainers/runc/libcontainer/configs/config.go
vendor/github.com/opencontainers/runc/libcontainer/seccomp/config.go
vendor/github.com/opencontainers/runc/libcontainer/seccomp/seccomp_linux.go
vendor/github.com/opencontainers/runc/libcontainer/utils/cmsg.go
vendor/github.com/opencontainers/runc/libcontainer/utils/utils.go
vendor/github.com/opencontainers/runc/libcontainer/utils/utils_unix.go
vendor/github.com/opencontainers/runc/vendor.conf
vendor/github.com/seccomp/libseccomp-golang/README
vendor/github.com/seccomp/libseccomp-golang/seccomp.go
vendor/github.com/seccomp/libseccomp-golang/seccomp_internal.go

backport of:
- revert https://github.com/containerd/containerd/pull/3539 [release/1.1] Revert "bump libseccomp-golang v0.9.1"
- brings back https://github.com/containerd/containerd/pull/3375 [release/1.1 backport] bump libseccomp-golang v0.9.1, which was a backport of https://github.com/containerd/containerd/pull/3371 bump libseccomp-golang v0.9.1
- Per the discussion on https://github.com/containerd/containerd/pull/3371#issuecomment-515634600, this causes the minimum supported seccomp version to be changed from 2.3.0, if containerd is compiled on a machine that has this version of seccomp installed, in which case, it will cause older distros to no longer be supported.
- https://github.com/containerd/containerd/pull/3713 Bump runc to 1b8a1eeec3f337ab5d94f28980
- …

[release/1.1 backport] bump runc v1.0.0-rc9

---

vendor.conf
vendor/github.com/opencontainers/runc/README.md
vendor/github.com/opencontainers/runc/libcontainer/apparmor/apparmor.go
vendor/github.com/opencontainers/runc/libcontainer/configs/config.go
vendor/github.com/opencontainers/runc/libcontainer/seccomp/config.go
vendor/github.com/opencontainers/runc/libcontainer/seccomp/seccomp_linux.go
vendor/github.com/opencontainers/runc/libcontainer/utils/cmsg.go
vendor/github.com/opencontainers/runc/libcontainer/utils/utils.go
vendor/github.com/opencontainers/runc/libcontainer/utils/utils_unix.go
vendor/github.com/opencontainers/runc/vendor.conf

backport of:
- https://github.com/containerd/containerd/pull/3713 Bump runc to 1b8a1eeec3f337ab5d94f28980
- https://github.com/containerd/containerd/pull/3721 bump runc v1.0.0-rc9

[release/1.3 backport] bump runc v1.0.0-rc9

---

runtime/v1/shim/service.go

The delete error code is not properly propagated.
Found this when working on https://github.com/containerd/cri/pull/1309.
Let's cherrypick the fix, because the correct error code can avoid unnecessary retries in the CRI plugin.

Fix shim delete error code.

---

.travis.yml
Makefile
cmd/gen-manpages/main.go

Seems to be that docs/man/ctr.1.md and docs/man/containerd.1.md were
removed in #3637 and were not updated correctly in the Makefile, leading
to build failures like:
+ make man
make: *** No rule to make target `man/ctr.1', needed by `man'.  Stop.
Changes the gen-manpages command to be specific on which manpages are to
be generated.
Signed-off-by: Eli Uriegas <eli.uriegas@docker.com>
Also added a check in the travis yml so that this gets checked on PRs
Signed-off-by: Eli Uriegas <eli.uriegas@docker.com>

build: Fix manpage generation

---

runtime/v1/linux/task.go
runtime/v2/shim.go
services/tasks/local.go

With more test, I found that https://github.com/containerd/containerd/pull/3730 is not enough:
1) The containerd daemon doesn't return grpc error properly;
2) The fix https://github.com/containerd/containerd/pull/3244 never worked, because the returned error is not converted to internal errors. And after converting to internal error, we didn't handle the `nil` response properly.

Fix delete error code on the containerd daemon side.

---

runtime/v1/linux/task.go
runtime/v2/shim.go
services/tasks/local.go

Slight backport of the cherry-pick due to small code differences in `runtime/v2/shim.go`

[release/1.2] backport: Fix delete error code on the containerd daemon side.

---

containerd.service

This will ensure that containerd is started after the /etc/fstab entries
Ref: #3671

Add local-fs.target to service file

---

client_test.go

This this fixes issues with custom and testing flags in Go 1.3 and should work
in previous go versions.

Move flag.Parse in tests to TestMain

---

container_test.go
pkg/process/io.go
runtime/v1/shim/service.go
runtime/v1/shim/service_linux.go
runtime/v2/runc/platform.go

Reized the I/O buffers to align with the size of the kernel buffers with fifos
and move the close aspect of the console to key off of the stdin closing.
Fixes #3738

Handle large output in v2 shim with TTY

---

containerd.service

This will ensure that containerd is started after the /etc/fstab entries

[release/1.3] Add local-fs.target to service file

---

containerd.service

This will ensure that containerd is started after the /etc/fstab entries

[release/1.2] Add local-fs.target to service file

---

containerd.service

This will ensure that containerd is started after the /etc/fstab entries

[release/1.1] Add local-fs.target to service file
