containerd/containerd

.travis.yml, cmd/ctr/commands/tasks/tasks_unix.go, container_checkpoint_test.go, linux/proc/init_state.go, vendor.conf, vendor/github.com/containerd/go-runc/console.go, vendor/github.com/containerd/go-runc/runc.go
runc already supports this case, so we just need to run it with proper
options.
Signed-off-by: Andrei Vagin <avagin@virtuozzo.com>
=> Allow to checkpoint and restore a container with console

client.go, import.go
=> Move import/export code to separate client file

client.go, vendor/github.com/docker/docker/contrib/README.md, vendor/github.com/docker/docker/contrib/nnp-test/nnp-test.c, vendor/github.com/docker/docker/contrib/syscall-test/acct.c, vendor/github.com/docker/docker/contrib/syscall-test/exit32.s, vendor/github.com/docker/docker/contrib/syscall-test/ns.c, vendor/github.com/docker/docker/contrib/syscall-test/raw.c, vendor/github.com/docker/docker/contrib/syscall-test/setgid.c, vendor/github.com/docker/docker/contrib/syscall-test/setuid.c, vendor/github.com/docker/docker/contrib/syscall-test/socket.c, vendor/github.com/docker/docker/contrib/syscall-test/userns.c, vendor/golang.org/x/crypto/otr/libotr_test_helper.c, vendor/golang.org/x/crypto/otr/otr.go, vendor/golang.org/x/crypto/otr/smp.go, vendor/golang.org/x/crypto/ssh/test/doc.go, vendor/golang.org/x/crypto/ssh/test/sshd_test_pw.c, vendor/golang.org/x/sys/windows/svc/event.go, vendor/golang.org/x/sys/windows/svc/go12.c, vendor/golang.org/x/sys/windows/svc/go12.go, vendor/golang.org/x/sys/windows/svc/go13.go, vendor/golang.org/x/sys/windows/svc/security.go, vendor/golang.org/x/sys/windows/svc/service.go, vendor/golang.org/x/sys/windows/svc/sys_386.s, vendor/golang.org/x/sys/windows/svc/sys_amd64.s, vendor/k8s.io/kubernetes/build/README.md, vendor/k8s.io/kubernetes/build/pause/orphan.c, vendor/k8s.io/kubernetes/build/pause/pause.c
=> [release/1.1] Add missing return statement on pull unpack

cmd/containerd-shim/main_unix.go, cmd/containerd-shim/shim_darwin.go, cmd/containerd-shim/shim_linux.go, cmd/containerd-shim/shim_unix.go, linux/shim/reaper.go, linux/shim/service.go
This is some work to cleanup the root dir. 
=> Move reaper under shim package

vendor/golang.org/x/sys/windows/svc/event.go, vendor/golang.org/x/sys/windows/svc/go12.c, vendor/golang.org/x/sys/windows/svc/go12.go, vendor/golang.org/x/sys/windows/svc/go13.go, vendor/golang.org/x/sys/windows/svc/security.go, vendor/golang.org/x/sys/windows/svc/service.go, vendor/golang.org/x/sys/windows/svc/sys_386.s, vendor/golang.org/x/sys/windows/svc/sys_amd64.s
Required for CI to pass on release branch
=> [release/1.0] fix vendor

fs/copy_linux.go, fs/copy_test.go, fs/fstest/file.go
Cherry-picks commits from continuity:
- containerd/continuity@afba265
- containerd/continuity@a3fa14c
=> [1.0] fix copy file range large files

vendor.conf, vendor/github.com/containerd/cri/pkg/containerd/resolver/fetcher.go, vendor/github.com/containerd/cri/pkg/server/image_pull.go, vendor/github.com/containerd/cri/vendor.conf
For https://github.com/containerd/cri/pull/785
cc @ehazlett @Random-Liu
=> update cri vendor

vendor.conf, vendor/github.com/containerd/cri/pkg/containerd/resolver/fetcher.go, vendor/github.com/containerd/cri/pkg/server/events.go, vendor/github.com/containerd/cri/pkg/server/service.go
Update cri plugin to v1.0.2 for containerd 1.1.1 release.
Release note: https://github.com/containerd/cri/releases/tag/v1.0.2
=> Update cri plugin to v1.0.2.

vendor.conf, vendor/github.com/Microsoft/go-winio/file.go, vendor/github.com/Microsoft/go-winio/pipe.go, vendor/github.com/Microsoft/go-winio/zsyscall_windows.go, vendor/github.com/Microsoft/hcsshim/README.md, vendor/github.com/Microsoft/hcsshim/legacy.go
Full diff:
- https://github.com/Microsoft/hcsshim/compare/v0.6.10...v0.6.11
- https://github.com/Microsoft/go-winio/compare/v0.4.5...v0.4.7
=> Update go-winio and hcsshim

remotes/docker/pusher.go
Fix #2385 
Signed-off-by: Bin Du <bindu@microsoft.com>
=> docker/pusher: handle location string containing path and query

client_test.go, remotes/docker/schema1/converter.go
Fix https://github.com/containerd/containerd/issues/2389
=> fix schema1 fetchBlob()

BUILDING.md
Fixes: #2396
Signed-off-by: Harshal Patil <harshal.patil@in.ibm.com>
=> Docs: Fix incomplete instructions for building using docker

releases/v1.1.1-rc.1.toml, version/version.go
Expecting this to be the last RC with final release this week.
=> Prepare 1.1.1-rc.1

images/image.go
Provide a better error if pull fails because there is no match for current platform in the manifest list. 
Instead of returning early I remember manifest list in a bool to not break possible cases of nested manifest lists.
Error on pull:
Previously:
`manifest sha256:32efb15cbb8a46f4b564857e534fd4c26a4a15813885f91b1a95b5758fea3fd5: not found`
New:
`no match for current platform linux/arm/v7 in manifest sha256:32efb15cbb8a46f4b564857e534fd4c26a4a15813885f91b1a95b5758fea3fd5: not found`
=> images: provide better error for manifest list match error

design/architecture.md
=> Update architecture.md (Carry PR 2363)

cmd/containerd-shim/main_unix.go, vendor.conf, vendor/github.com/containerd/ttrpc/server.go
=> Update ttrpc to 94dde388801693c54f88a6596f713b51a8

cmd/containerd-release/main.go, metadata/content_test.go
Signed-off-by: Sudeesh John <sudeesh@linux.vnet.ibm.com>
Ref: https://github.com/containerd/containerd/issues/2404
=> Fixing the formatting directives error during compilation

cmd/containerd/command/oci-hook.go
=> Handle abs path for rootfs in oci hook

cmd/containerd-stress/main.go
=> Set runtime for stress tests

archive/tar.go, archive/tar_test.go
With `fs.RootPath`, the target file will be the file which the softlink points to, like:
```
touch /tmp/zzz
ln -s /tmp/zzz /tmp/xxx
ln /tmp/xxx /tmp/yyy
```
The `/tmp/yyy` should be same with the `/tmp/xxx`, not `/tmp/zzz`.
=> bugfix: allow hardlink to softlink file

Protobuild.toml, cmd/containerd-shim-runc-v1/main.go, cmd/containerd/builtins_linux.go, cmd/ctr/commands/client.go, cmd/ctr/commands/run/run_unix.go, cmd/ctr/commands/tasks/checkpoint.go, runtime/v2/binary.go, runtime/v2/runc/options/next.pb.txt, runtime/v2/runc/service.go, runtime/v2/shim/shim.go, task.go
=> Fixes for runtimev2 and checkpoint restore

runtime/v2/manager.go
=> Fast path bundle cleanup on load

vendor.conf, vendor/github.com/containerd/cgroups/cgroup.go, vendor/github.com/containerd/cgroups/control.go, vendor/github.com/containerd/cgroups/cpuset.go, vendor/github.com/containerd/cgroups/metrics.pb.go, vendor/github.com/containerd/cgroups/metrics.proto, vendor/github.com/containerd/cgroups/rdma.go, vendor/github.com/containerd/cgroups/subsystem.go, vendor/github.com/containerd/cgroups/utils.go, vendor/github.com/containerd/go-runc/console.go, vendor/github.com/containerd/go-runc/runc.go, vendor/github.com/containerd/go-runc/utils.go, vendor/github.com/opencontainers/runtime-spec/README.md, vendor/github.com/opencontainers/runtime-spec/specs-go/config.go, vendor/github.com/opencontainers/runtime-spec/specs-go/version.go
=> Update containerd dependencies for 1.2

archive/compression/compression.go, remotes/docker/schema1/converter.go
blob for schemav1 could be uncompressed, which can be pulled by docker but cannot pull by ctr, because when docker downloading a blob layer it will check if it is compressed or not.
in our company we have a image registry which use schemaV1 and has uncompressed layers, these layers can be download by docker but cannot download by ctr, after dig a while i found that maybe we should check the downloading stream in advance, and if it is uncompressed we don't use the gzip reader to decompress it.
PTAL, and thanks.
Signed-off-by: frank yang <yyb196@gmail.com>
=> fixbug: blob for schemav1 could be uncompressed

runtime/v2/shim/util.go
Fixes an issue where the runtime v2 was not using an absolute path to
the executable but setting the .Dir field on the exec.Cmd. This causes
the executable to need to be relative to .Dir but no shim is actually
copied to the bundle directory that its work dir is set to.
=> Runtime v2 absolute shim path to executable

cmd/containerd-shim-runc-v1/main.go
=> Fix a typo in runc-v1 shim

docs/managed-opt.md
=> Add docs for managed opts dir

containers/containers.go
=> Image and snapshot key are mutable

releases/v1.2.0-beta.0.toml, version/version.go
Update version and add release notes
=> Add first v1.2.0 beta release notes

client.go, client_opts.go
This also sets the default timeout to 10s instead of 60s.
=> Add WithTimeout as client Opt

releases/v1.2.0-beta.0.toml
=> Add release notes for v2 runtime and opts

vendor.conf, vendor/github.com/opencontainers/runc/libcontainer/configs/config.go, vendor/github.com/opencontainers/runc/libcontainer/devices/devices.go, vendor/github.com/opencontainers/runc/libcontainer/nsenter/nsexec.c, vendor/github.com/opencontainers/runc/libcontainer/system/linux.go, vendor/github.com/opencontainers/runc/libcontainer/system/unsupported.go, vendor/github.com/opencontainers/runc/libcontainer/user/lookup_unix.go, vendor/github.com/opencontainers/runc/libcontainer/user/user.go
Synchronizes with the version used by buildkit, which is currently ahead of containerd
=> Update runc vendor

container_linux_test.go, oci/spec_opts_unix.go
Cherrypick commits from #2529 and #2535 for the 1.1.x branch
=> [release/1.1] Cherrypick "Set gid 0 when no group is specified" and docs update

services/content/service.go
=> Export content service New

releases/v1.1.3.toml, version/version.go
=> Prepare 1.1.3 release notes

vendor.conf, vendor/github.com/containerd/go-runc/io.go
=> revendor go-runc to acb7c88c

releases/v1.2.0-beta.1.toml, version/version.go
Time to cut another beta, we have had the Windows runtime merged and a few other fixes to go into this one.
=> Add v1.2.0 beta 1 release notes

runtime/v2/runhcs/service.go
Sometimes the wrong ID was being used because its not correct to assume
that ExecID is always set. The assumption was that for API's where it is
not an exec ID == ExecID but thats not true. ExecID == "" if it is not
an exec. This uses the correct ID in all cases.
=> Fix incorrect ID usage in Windows runtime v2

README.md
=> Add Windows build status

containerd.service
=> Update unit file for resources and task max

daemon_config_linux_test.go
=> Wait before start with runtime root test

runtime/v1/linux/runtime.go, runtime/v1/linux/task.go
=> remove useless parameter from newTask

remotes/docker/schema1/converter.go
Use containerd.io/uncompressed label to avoid to re-calculate blob
diffID.
=> bugfix: avoid to re-calculate blob state for schema1

cmd/containerd-stress/main.go
Signed-off-by: ruicao <ruicao@alauda.io>
=> Typo fix: outputing -> outputting

api/services/events/v1/events.pb.go, api/services/events/v1/events.proto, events/exchange/exchange.go
Signed-off-by: Xiaoxi He <xxhe@alauda.io>
=> Fix 'forward' typos

export.go, import.go
Signed-off-by: Jie Zhang <iamkadisi@163.com>
=> move Exports method to export.go files

runtime/v2/binary.go, runtime/v2/runhcs/service.go, runtime/v2/shim.go, snapshots/lcow/lcow.go, snapshots/overlay/check.go
Signed-off-by: Xiaodong Zhang <a4012017@sina.com>
=> Fix some typo in runtime and snapshots

container_opts_unix.go, task_opts.go, task_opts_unix.go, task_opts_unix_test.go
=> move WithXXXX to task_opts.go

oci/spec_opts.go
Can be used to conform to Docker engine behavior of adding additional
GIDs to spec when found in /etc/group of image filesystem
=> Add With-helper for supplemental gid support

vendor.conf, vendor/gopkg.in/yaml.v2/LICENSE, vendor/gopkg.in/yaml.v2/NOTICE, vendor/gopkg.in/yaml.v2/README.md, vendor/gopkg.in/yaml.v2/apic.go, vendor/gopkg.in/yaml.v2/decode.go, vendor/gopkg.in/yaml.v2/emitterc.go, vendor/gopkg.in/yaml.v2/encode.go, vendor/gopkg.in/yaml.v2/parserc.go, vendor/gopkg.in/yaml.v2/readerc.go, vendor/gopkg.in/yaml.v2/resolve.go, vendor/gopkg.in/yaml.v2/scannerc.go, vendor/gopkg.in/yaml.v2/sorter.go, vendor/gopkg.in/yaml.v2/writerc.go, vendor/gopkg.in/yaml.v2/yaml.go, vendor/gopkg.in/yaml.v2/yamlh.go
This has releases, and the vendored version is very old predating
the change from LGPL to Apache licensing.
=> Update Go yaml library

daemon_config_linux_test.go
=> Don't start top container in test

oci/spec_opts_unix.go
Backport #2641 into release/1.1
=> [release/1.1] Backport: Support uid in WithAdditionalGIDs

vendor.conf, vendor/github.com/opencontainers/runtime-spec/specs-go/config.go
Signed-off-by: Madhan Raj Mookkandy <madhanm@microsoft.com>
=> Vendor in runtime spec referencing windows namespace

README.md
=> Update slack invite link for direct signup

releases/v1.2.0-rc.toml
I got the doc link from @tallclair. https://github.com/kubernetes/website/blob/release-1.12/content/en/docs/concepts/containers/runtime-class.md
I previous link is the proposal link.
=> Update v1.2.0-rc release note.

content/local/store_test.go, content/local/writer.go, content/testsuite/testsuite.go, diff/walking/differ.go, metadata/buckets.go, metadata/content.go, services/content/service.go, task.go
This is a cherry-pick/backport of #2642 for the release/1.1 branch
=> [release/1.1] Backported: check exists on content commit + testcase

cmd/containerd/command/publish.go
=> Reduce publish connection timeout

.mailmap, version/version.go
https://gist.github.com/dmcgowan/20bc5d9e19fd91136135586465e31e81
=> Update version for v1.2.0-rc.0

vendor.conf, vendor/github.com/containerd/ttrpc/client.go, vendor/github.com/containerd/ttrpc/server.go
=> Update ttrpc for client timeout support

vendor.conf, vendor/github.com/opencontainers/runc/README.md, vendor/github.com/opencontainers/runc/libcontainer/nsenter/README.md, vendor/github.com/opencontainers/runc/libcontainer/nsenter/nsexec.c
=> Update runc to 00dc70017d222b178a002ed30e9321b126

releases/v1.1.4.toml, version/version.go
=> [release/1.1] Prepare for v1.1.4 fix release

snapshots/lcow/lcow.go
=> Fix race in lcow snapshot scratch.vhdx creation

archive/compression/compression.go
A panic was seen related to the buffer being reset in one goroutine while being read in another. In the case of pigz an early cancellation will cause the reader to close, resetting the buffer and signaling the process to shut down, but races since the process must stop reading before the reset otherwise the a panic may occur. This fix guarantees that the bufio is always reset and returned to the pool on the same goroutine that is doing the read. If a buffer is not fully read the buffered reader should just be discarded and not returned back to the pool.
=> Fix panic when bufio Reader called in 2 goroutines

runtime/v2/binary.go, runtime/v2/runhcs/service.go, runtime/v2/shim/shim.go, runtime/v2/shim/shim_test.go, vendor.conf, vendor/github.com/Microsoft/hcsshim/cmd/go-runhcs/runhcs.go, vendor/github.com/Microsoft/hcsshim/cmd/go-runhcs/runhcs_create.go, vendor/github.com/Microsoft/hcsshim/cmd/go-runhcs/runhcs_exec.go, vendor/github.com/Microsoft/hcsshim/hnsendpoint.go
- Forward containerd debug to shim invocation
- Fixes containerd-shim-runhcs Delete on exec id
- Fixes containerd-shim-runhcs State on exec id
- Adds containerd-shim-runhcs verbose logging support
=> Various containerd-shim-runhcs bug fixes/improvements

mount/lookup_linux_test.go, snapshots/btrfs/btrfs_test.go, snapshots/overlay/check_test.go, vendor.conf, vendor/github.com/containerd/continuity/testutil/helpers.go, vendor/github.com/containerd/continuity/testutil/helpers_unix.go, vendor/github.com/containerd/continuity/testutil/helpers_windows.go, vendor/github.com/containerd/continuity/testutil/loopback/loopback_linux.go, vendor/github.com/containerd/continuity/testutil/mount_linux.go, vendor/github.com/containerd/continuity/testutil/mount_other.go
=> remove pkg/testutil/loopback_linux.go and use continuity/testutil/loopback

archive/tar_test.go, archive/tartest/tar.go, images/archive/importer.go, import_test.go, metadata/content.go
Test all supported formats for import and a couple small fixes in the import.
Move tar creation test utilities to separate package.
=> Content store fix and import integration test

version/version.go
Time for another RC with the bug fixes since the first RC
https://gist.github.com/dmcgowan/dc5fd2fd45da346f6aea2c70bf33c9ea
=> Update version to 1.2-rc.1

diff/walking/differ.go
Diff expects to set the uncompressed label on Commit, however if the blob already exists in the content store no labels will get set, requiring an Update. Check if the uncompressed label is on the blob and set it if not.
Fixes #2707
=> Set uncompressed label on diff when already exists

cmd/containerd-stress/exec_worker.go, cmd/containerd-stress/main.go, cmd/containerd-stress/worker.go
=> Fix stress test for image config opt requirements

version/version.go
=> Update version to 1.2.0-rc.2

cmd/ctr/commands/tasks/metrics.go
Found problem when test with containerd-shim-kata-v2,  pointer should be judged whether is null.
=> ctr: fix potential panic in metric

RELEASES.md, api/1.2.pb.txt, releases/v1.2.0.toml, version/version.go
Update release document and release notes for 1.2
Still some additions that need to be made to the release notes
=> Prepare 1.2 release

vendor.conf, vendor/github.com/containerd/aufs/aufs.go
=> Bump aufs for unsupported errors

services/tasks/local.go
=> bugfix: CloseIO should return correct status code

runtime/v1/shim/reaper.go, runtime/v2/shim/reaper_unix.go
Fixes #2709
This increases the buffer size for process exit subscribers. It also
implements a non-blocking send on the subscriber channel.  It is better
to drop an exit even than it is to block a shim for one slow subscriber.
=> Increase reaper buffer size and non-blocking send

README.md
=> update link for slack invite

cmd/ctr/commands/resolver.go
=> bugfix: use skip-verify flag not insecure in ctr

vendor.conf, vendor/github.com/Microsoft/hcsshim/hnspolicylist.go, vendor/github.com/Microsoft/hcsshim/interface.go, vendor/github.com/Microsoft/hcsshim/internal/hns/hnspolicylist.go, vendor/github.com/Microsoft/hcsshim/internal/schema2/memory_2.go, vendor/github.com/Microsoft/hcsshim/internal/schema2/virtual_p_mem_controller.go
=> Revendor github.com/Microsoft/hcsshim

.appveyor.yml, vendor.conf, vendor/github.com/Microsoft/hcsshim/hnspolicylist.go, vendor/github.com/Microsoft/hcsshim/interface.go, vendor/github.com/Microsoft/hcsshim/internal/hns/hnspolicylist.go, vendor/github.com/Microsoft/hcsshim/internal/schema2/memory_2.go, vendor/github.com/Microsoft/hcsshim/internal/schema2/virtual_p_mem_controller.go
Cherry-pick #2775 
Temporary 2nd commit to enable appveyor on this branch to test if this fixes the build break found in #2791 which enables appveyor on this branch.
=> [release/1.2] Cherrypick update hcsshim vendor

vendor.conf, vendor/github.com/opencontainers/runc/README.md, vendor/github.com/opencontainers/runc/libcontainer/README.md, vendor/github.com/opencontainers/runc/libcontainer/configs/namespaces_linux.go, vendor/github.com/opencontainers/runc/libcontainer/configs/namespaces_syscall.go, vendor/github.com/opencontainers/runc/libcontainer/nsenter/nsexec.c
=> Update runc to 10d38b660a77168360df3522881e2dc2be

runtime/v2/shim/reaper_unix.go
=> Revert v2 dropped events

runtime/v1/shim/reaper.go, runtime/v2/shim/reaper_unix.go
Cherry-pick #2748 and #2770 for `release/1.2`
=> [release/1.2] Cherrypick: increase buffer size and event discard + partial revert PR

vendor.conf, vendor/github.com/opencontainers/runc/README.md, vendor/github.com/opencontainers/runc/libcontainer/README.md, vendor/github.com/opencontainers/runc/libcontainer/configs/namespaces_linux.go, vendor/github.com/opencontainers/runc/libcontainer/configs/namespaces_syscall.go, vendor/github.com/opencontainers/runc/libcontainer/nsenter/nsexec.c
=> [release/1.2] Update runc to 10d38b660a77168360df3522881e2dc2be5056bd

remotes/docker/resolver.go
=> Add custom headers resolver option

runtime/v1/linux/proc/init.go
=> [release/1.2] Cherrypick: Lock `KillAll`.

releases/v1.2.1.toml, version/version.go
Includes 1.2.1 release notes and version update for the first rc.
=> Prepare 1.2.1-rc.0

vendor.conf, vendor/github.com/opencontainers/runc/libcontainer/configs/config.go
full diff: https://github.com/opencontainers/runc/compare/10d38b660a77168360df3522881e2dc2be5056bd...v1.0.0-rc6
=> Update runc to v1.0.0-rc6

cmd/containerd/command/main.go, cmd/containerd/command/main_unix.go, cmd/containerd/command/main_windows.go
=> Add dumpStacks support for containerd on Windows

runtime/v2/shim/util.go, vendor.conf, vendor/github.com/Microsoft/hcsshim/pkg/go-runhcs/runhcs.go
=> Cache shim v2 exec.LookPath results

cmd/ctr/commands/run/run.go, cmd/ctr/commands/run/run_unix.go, cmd/ctr/commands/run/run_windows.go
=> Move ctr run --isolation to Windows only

archive/tar.go, contrib/seccomp/seccomp.go, mount/mountinfo_linux.go, sys/oom_unix_test.go
Signed-off-by: zhangyue <zy675793960@yeah.net>
just fix several bad code style.
=> fix: fix error info start capitalized

ADOPTERS.md
Add the newly announced AWS Firecracker and the Kata containers
integration work.
=> Add more adopters

runtime/v1/linux/proc/init_state.go
For https://github.com/containerd/containerd/issues/2744.
=> [release 1.2] Kill should still work in stopped state.

releases/v1.2.1.toml, vendor.conf, vendor/github.com/containerd/cri/pkg/server/container_stop.go, vendor/github.com/containerd/cri/pkg/server/events.go, vendor/github.com/containerd/cri/pkg/server/sandbox_stop.go, vendor/github.com/containerd/cri/vendor.conf
Fixes https://github.com/containerd/containerd/issues/2744
Release note is also updated.
=> [release 1.2] Update cri to 0ca1e3c2b73b5c38e72f29bb76338d0078b23d6c

runtime/v2/shim/shim.go, runtime/v2/shim/shim_unix.go, runtime/v2/shim/shim_windows.go
=> Add shim config for shim binary options

cmd/ctr/commands/content/content.go
The $EDITOR is not clear for user. If the env doesn't set the value for
$EDITOR, the users don't know how to use this subcommand when they get
error like this:
```
sh: 1: /tmp/edit-605573012: Permission denied
```
=> ctr/content: make editor flag is required

remotes/docker/authorizer.go
Fixes #2870
Signed-off-by: Eric Lin <linxiulei@gmail.com>
=> Explicitly stating utf-8 when fetching oauth token

runtime/v1/linux/proc/exec.go, runtime/v1/linux/proc/init.go
There is still a special case where the client side fails to open or
load causes things to be slow and the shim can lock up when this
happens.  This adds a timeout to the context for this case to abort fifo
creation.
=> Add timeout and cancel to shim fifo open

runtime/v1/linux/proc/exec.go, runtime/v1/linux/proc/init.go
Backport of #2877
```
$ git cherry-pick -s -x a2a4241
[backport-1.2-fifo-timeout 18f57e20] Add timeout and cancel to shim fifo open
Author: Michael Crosby <crosbymichael@gmail.com>
Date: Thu Dec 13 14:43:41 2018 -0500
2 files changed, 10 insertions(+)
```
There is still a special case where the client side fails to open or
load causes things to be slow and the shim can lock up when this
happens.  This adds a timeout to the context for this case to abort fifo
creation.
(cherry picked from commit a2a4241979f615eb0a1084c7638c21f830f48ac5)
Signed-off-by: Andrew Hsu <andrewhsu@docker.com>
=> [release/1.2] Add timeout and cancel to shim fifo open

install.go
Signed-off-by: zhangyue <zy675793960@yeah.net>
fix defer in loop to reduce resource leak risk.
=> fix: fix defer in loop

runtime/v2/README.md
=> Update the delete docs for Runtime V2 on Windows

runtime/v2/shim.go
=> Fix spurious ttrpc client shutdown error log on success

oci/spec_opts.go, oci/spec_opts_test.go
fix parameters passing for windows when use  oci.WithImageConfigArgs
=> fix oci.WithImageConfigArgs for windows

.mailmap, releases/v1.2.2.toml, version/version.go
Add release notes, update version, and add Mike's new email to mailmap
ping @Random-Liu @crosbymichael for release note review
=> [release/1.2] 1.2.2 release

runtime/v2/runhcs/process.go, runtime/v2/runhcs/service.go
When an exec occurs the pid was not properly updated on the in memory state
value causing many queries to see a 0.
=> Fixes a bug in runhcs shim Exec.Pid

runtime/v2/runhcs/process.go
Before this change, the shim was only publishing a non-zero exit status (exit code) in the case that the process.Wait() call failed. This grabs the exit status correctly when process.Wait() succeeds too. Otherwise, if a process exits with a non-zero exit-code, it's dropped on the floor and never sent in the event.
@jterry75 PTAL
=> Windows: Publish exit status correctly in TaskExit

cmd/ctr/commands/images/export.go, export.go, export_test.go, images/oci/exporter.go, import_test.go
Signed-off-by: Jie Zhang <iamkadisi@163.com>
fix #2590   
may be need some test case
=> fix ctr image export not found error

images/oci/exporter.go
Update comment and streamline getting the default platform spec; final two unresolved comments from #2622 
// cc: @fuweid 
=> Handle additional cleanups from prior PR

runtime/v1/linux/proc/exec.go, runtime/v1/linux/proc/init.go, runtime/v1/linux/proc/init_state.go, runtime/v1/linux/proc/io.go, runtime/v1/shim.go, runtime/v2/runc/service_linux.go, runtime/v2/shim_unix.go
Fixes https://github.com/containerd/containerd/issues/2937
Fixes https://github.com/containerd/containerd/issues/2938
We can have a better fix after https://github.com/containerd/fifo/issues/18 is addressed.
More details at https://github.com/containerd/containerd/pull/2944#issuecomment-456653617.
=> Don't cancel context passed to `OpenFifo`.

runtime/v2/shim/shim_windows.go
=> Return out of windows signal handler

runtime/v2/runc/service.go
=> Move task events to runc v2 shim

Makefile
Make will generate GDB friendly binary with this build option.
Signed-off-by: Hui Zhu <teawater@hyper.sh>
=> Add build option "GODEBUG=1"

BUILDING.md
Improve documentation
Signed-off-by: Nitesh Konkar niteshkonkar@in.ibm.com
=> BUILDING: update BUILDING.md

runtime/v2/runhcs/process.go, runtime/v2/runhcs/service.go
=> Fix deadlock in Windows runhcs shim exec

runtime/v1/linux/proc/deleted_state.go, runtime/v1/linux/proc/exec.go, runtime/v1/linux/proc/exec_state.go, runtime/v1/linux/proc/init.go, runtime/v1/linux/proc/utils.go
Fixes https://github.com/containerd/containerd/issues/2969.
No one likes nested locks. :( I know.
I'm happy to change the fix if people come up with better ideas.
/cc @containerd/containerd-maintainers @containerd/containerd-reviewers
=> Fix exec race condition

runtime/v1/linux/proc/deleted_state.go, runtime/v1/linux/proc/exec.go, runtime/v1/linux/proc/exec_state.go, runtime/v1/linux/proc/init.go, runtime/v1/linux/proc/utils.go
Cherry pick of commits in #2970
=> [release/1.2] Fix exec race condition

process.go, task.go
Fix a potential panic in containerd. This is needed in https://github.com/containerd/cri/pull/1037.
=> Fix potential containerd panic.

process.go, task.go
=> [release/1.2] Fix potential containerd panic.

metadata/buckets.go
Adds comment showing the structure of the buckets as stored in boltdb. Includes all bucket names, key names and descriptions of the stored values.
Note: It shows up better as [raw](https://raw.githubusercontent.com/containerd/containerd/d25007e548c08eb16712381fdb1b727b1ffb50ea/metadata/buckets.go)
=> Add structure documentation for metadata

.mailmap, releases/v1.2.3.toml, version/version.go
Please update if I'm missing something or need to add/change the notables.
=> [release/1.2] Prepare v1.2.3

vendor.conf, vendor/github.com/opencontainers/runtime-spec/specs-go/config.go
Updates to the latest runtime-spec.
=> Vendor opencontainers/runtime-spec 29686dbc

cmd/ctr/commands/tasks/tasks_windows.go
=> Stop sending stderr with TTY on Windows

content/helpers_test.go
"commitedDigest" to "committedDigest".
=> Fix some misspells in helpers_test.go

RELEASES.md
Use latest 1.1 and 1.2 version
=> Update supported versions

cmd/containerd/command/service_windows.go, containers/containers.go
Signed-off-by: Veeraiah Chowdary Nuvvula <venuvvul@microsoft.com>
=> fixing typo and added a missing comment.

.travis.yml
=> Update travis to xenial worker

vendor.conf, vendor/github.com/containerd/cgroups/cgroup.go, vendor/github.com/containerd/cgroups/opts.go, vendor/github.com/containerd/cgroups/paths.go
This fixes issues for systemd 420 and non-existant cgroups.
=> Bump cgroups to dbea6f2bd41658b84b00417ceefa416b97

snapshots/snapshotter.go
- Update the snapshotter docs to refer to the snapshots package for WithLabels.
Signed-off-by: Eric Hotinger <ehotinger@gmail.com>
=> Update the snapshotter docs to refer to the snapshots package

cio/io_windows.go, cio/io_windows_test.go
=> Fix issue with NewFIFOSetInDir with Terminal true

cmd/ctr/commands/images/push.go
If user sets debug mode, the command push should only show the debug log
information. If the stdout is with flush by the progress status, it is
hard to see the debug log.
=> ctr/commands/images/push: don't show progress if it is debug mode

vendor.conf, vendor/github.com/containerd/cgroups/README.md, vendor/github.com/containerd/cgroups/blkio.go, vendor/github.com/containerd/cgroups/cgroup.go, vendor/github.com/containerd/cgroups/control.go, vendor/github.com/containerd/cgroups/cpuset.go, vendor/github.com/containerd/cgroups/devices.go, vendor/github.com/containerd/cgroups/net_prio.go, vendor/github.com/containerd/cgroups/opts.go, vendor/github.com/containerd/cgroups/paths.go, vendor/github.com/containerd/cgroups/subsystem.go, vendor/github.com/containerd/cgroups/systemd.go, vendor/github.com/containerd/cgroups/utils.go
This fixes issues for systemd 420 and non-existant cgroups.
=> [release1.2] Bump cgroups to dbea6f2bd41658b84b00417ceefa416b97

releases/v1.2.5.toml, version/version.go
Please feel free to comment if you want to add anything or change anything.
=> Prepare v1.2.5 release.

contrib/nvidia/nvidia.go
Signed-off-by: Tibor Vass <tibor@docker.com>
=> contrib/nvidia: export helper binary path and list of Nvidia capabilities

oci/spec_opts.go, task.go
=> Fastpath opt and ExecProcess loading

BUILDING.md, cmd/containerd/builtins_devmapper_linux.go, cmd/containerd/builtins_linux.go, snapshots/devmapper/README.md, snapshots/devmapper/config.go, snapshots/devmapper/config_test.go, snapshots/devmapper/device_info.go, snapshots/devmapper/dmsetup/dmsetup.go, snapshots/devmapper/dmsetup/dmsetup_test.go, snapshots/devmapper/losetup/losetup.go, snapshots/devmapper/losetup/losetup_test.go, snapshots/devmapper/metadata.go, snapshots/devmapper/metadata_test.go, snapshots/devmapper/pool_device.go, snapshots/devmapper/pool_device_test.go, snapshots/devmapper/snapshotter.go, snapshots/devmapper/snapshotter_test.go
This PR adds device mapper snapshotter plugin to `containerd`.
Original issue and discussion [here](https://github.com/containerd/containerd/issues/2988).
/cc @samuelkarp @nmeyerhans
=> Integrate device mapper snapshotter

daemon_config_linux_test.go
avoid issue #3133 occurs again
=> test: add custom cgroup test

services/server/config/config.go, services/server/server.go
=> Add configurable plugin path

runtime/v2/runc/v1/service.go, runtime/v2/runc/v2/service.go, runtime/v2/runhcs/service.go
splitting this off from https://github.com/containerd/containerd/pull/3116
=> do not use unkeyed fields in composite literals

vendor.conf, vendor/github.com/containerd/cri/pkg/server/helpers.go, vendor/github.com/containerd/cri/vendor.conf, vendor/github.com/opencontainers/selinux/README.md, vendor/github.com/opencontainers/selinux/go-selinux/label/label.go, vendor/github.com/opencontainers/selinux/go-selinux/label/label_selinux.go, vendor/github.com/opencontainers/selinux/go-selinux/selinux_linux.go, vendor/github.com/opencontainers/selinux/go-selinux/selinux_stub.go
* Update `github.com/opencontainers/selinux` to `v1.2.1`.
=> [release 1.2] Update cri to eb926cd79d3bac188dcc4ed7694fc9298f8831be

remotes/docker/fetcher.go
=> Update handling of registry errors

process.go
=> Export ExitStatus init func

cmd/containerd-shim/main_unix.go, runtime/v2/shim/shim_unix.go
We should return stdout/stderr from the event publish process. Only "failed to publish event" doesn't include any information for debugging.
See https://github.com/containerd/containerd/issues/3177 and https://github.com/containerd/containerd/issues/3125
=> Return event publish errors

releases/v1.2.6.toml
=> Prepare v1.2.6 release

content/local/store.go
Fix: https://github.com/containerd/containerd/issues/3089
=> delete the ingest when any errors happen during resuming status

api/next.pb.txt, api/services/ttrpc/events/v1/events.pb.go, api/services/ttrpc/events/v1/events.proto, runtime/v2/example/example.go, runtime/v2/runc/epoll.go, runtime/v2/runc/v1/service.go, runtime/v2/runc/v2/service.go, runtime/v2/runhcs/service.go, runtime/v2/shim/dialer.go, runtime/v2/shim/publisher.go, runtime/v2/shim/shim.go, runtime/v2/shim/shim_unix.go, runtime/v2/shim/shim_windows.go, services/events/ttrpc.go
=> Fix API forward events for shims

containerd.service
=> Set nofile to 1048576

cmd/containerd/command/main.go, plugin/plugin.go, services/server/config/config.go, services/server/server.go
=> Add tcp service for grpc listeners

runtime/v2/shim/publisher.go, services/server/server.go
=> Requeue events in the ttrpc publisher

runtime/v1/linux/runtime.go
When using v1 shim, if we:
1) Create a container;
2) Restart containerd;
3) Stop the container.
There will always be 2 `TaskExit` events, and an annoying `failed to delete bundle` cleanup error:
```
INFO[2019-04-11T16:24:48.724104626-07:00] StopPodSandbox for "a"                       
DEBU[2019-04-11T16:24:48.866783282-07:00] event published                               ns=k8s.io topic=/tasks/exit type=containerd.events.TaskExit
DEBU[2019-04-11T16:24:48.866904411-07:00] Received containerd event timestamp - 2019-04-11 23:24:48.866764485 +0000 UTC, namespace - "k8s.io", topic - "/tasks/exit" 
INFO[2019-04-11T16:24:48.867071445-07:00] TaskExit event &TaskExit{ContainerID:ac959381b7c00ea872d3e09030e4157cbd81c5205a8d3060069b5e21a40f57d9,ID:ac959381b7c00ea872d3e09030e4157cbd81c5205a8d3060069b …
```
=> Shim v1: Check task list to avoid unnecessary cleanup.

vendor.conf, vendor/golang.org/x/crypto/curve25519/curve25519.go, vendor/golang.org/x/crypto/otr/otr.go, vendor/golang.org/x/crypto/ssh/terminal/terminal.go, vendor/golang.org/x/crypto/ssh/terminal/util.go, vendor/golang.org/x/crypto/ssh/terminal/util_aix.go, vendor/golang.org/x/crypto/ssh/terminal/util_plan9.go, vendor/golang.org/x/crypto/ssh/terminal/util_solaris.go, vendor/golang.org/x/crypto/ssh/terminal/util_windows.go
full diff: https://github.com/golang/crypto/compare/49796115aa4b964c318aad4f3084fdb41e9aa067...88737f569e3a9c7ab309cdc09a07fe7fc87233c3
=> Update x/crypto to 88737f569e3a9c7ab309cdc09a07fe7fc87233c3

client_test.go, client_windows_test.go
Cherry-pick commits from #3222 for `release/1.2`
=> [release/1.2] cherry-pick: Appveyor fixes from master

client_windows_test.go
=> Convert Windows CI to use Microsoft MCR image urls

runtime/v1/shim/client/client.go, runtime/v2/binary.go, runtime/v2/shim.go, vendor.conf, vendor/github.com/containerd/ttrpc/client.go, vendor/github.com/containerd/ttrpc/services.go
full diff: https://github.com/containerd/ttrpc/compare/f02858b1457c5ca3aaec3a0803eb0d59f96e41d6...699c4e40d1e7416e08bf7019c7ce2e9beced4636
- containerd/ttrpc#33 Fix returns error message
- containerd/ttrpc#35 Make onclose an option
=> bump containerd/ttrpc 699c4e40d1e7416e08bf7019c7ce2e9beced4636

remotes/docker/handler.go, snapshots/benchsuite/benchmark_test.go
Signed-off-by: Davor Kapsa <davor.kapsa@gmail.com>
=> Fix misspells

cmd/ctr/commands/containers/containers.go, images/archive/importer.go, metadata/content.go, services/server/server.go, snapshots/devmapper/metadata.go
Signed-off-by: Davor Kapsa <davor.kapsa@gmail.com>
=> Remove redundant error checks

runtime/v2/binary.go, runtime/v2/shim.go
=> Stop logging error on v2 multi shim log failure

runtime/v1/linux/proc/io.go
Signed-off-by: Davor Kapsa <davor.kapsa@gmail.com>
=> Use cancel on errors

runtime/v2/shim.go
Follow up of https://github.com/containerd/containerd/pull/3244.
I'm really sorry... I think I had a typo in that fix.
=> Fix error handling for task deletion.

runtime/v1/linux/proc/deleted_state.go, runtime/v1/linux/task.go, runtime/v2/shim.go
Cherrypick of https://github.com/containerd/containerd/pull/3244 and https://github.com/containerd/containerd/pull/3263 to release/1.2.
=> [release/1.2] Return NotFound error for kill and delete in deleted state.

linux/proc/deleted_state.go, linux/runtime.go
Cherrypick of #3244 and #3263 to release/1.1.
=> [release/1.1] Return NotFound error for kill and delete in deleted state.

vendor.conf, vendor/github.com/containerd/ttrpc/server.go
Co-authored-by: Giuseppe Capizzi <gcapizzi@pivotal.io>
Signed-off-by: Georgi Sabev <georgethebeatle@gmail.com>
This PR brings the [file descriptor leak fix](https://github.com/containerd/ttrpc/pull/37) to containerd
=> Bump ttrpc

runtime/v1/linux/proc/init.go, runtime/v1/linux/proc/init_state.go
=> Remove unused Resize method from initState

.appveyor.yml, .travis.yml
Hopefully CI here will have a better color than in https://github.com/moby/moby/pull/38404
=> Add Golang 1.12.5

defaults/defaults.go
=> Fix typo in description comment

cmd/ctr/commands/run/run.go, cmd/ctr/commands/run/run_unix.go, container_opts.go
Adds the platform flag to the run command and resolves the image based on that platform.
=> Fix run with specified platform

diff/lcow/lcow.go
=> Forcibly sync writes on lcow layer.vhd after write

runtime/v1/linux/proc/utils.go
Signed-off-by: Danni Xia <xiadanni1@huawei.com>
=> Close file r.log after used to release resources.

vendor.conf, vendor/github.com/containerd/ttrpc/server.go
cherry-pick #3278 for `release/1.2`
=> [release/1.2] cherry-pick: Bump ttrpc

content/helpers.go
=> Ignore EOF from ReadAt in content.ReadBlob

content/local/store.go, content/testsuite/testsuite.go
This helps some failures in the windows CI
=> Ensure close in content test

content/local/writer.go, diff/walking/differ.go
=> [release/1.2] differ: fix deadlock on commit error

.travis.yml, client_test.go, cmd/containerd/command/config.go, cmd/containerd/command/config_linux.go, cmd/containerd/command/config_unsupported.go, cmd/containerd/command/config_windows.go, daemon_config_linux_test.go, plugin/plugin.go, services/server/config/config.go, services/server/server.go
=> Add v2 server config support with plugin URIs

remotes/docker/authorizer.go, remotes/docker/resolver.go
This is a backport of the user agent fix for 2.7. Since the custom header change wasn't added in yet to 1.2, this just always sets the user agent to the default (the only difference was in creation of a new resolver).
=> [release/1.2] Add user agent header to all requests

namespaces/ttrpc.go, vendor.conf, vendor/github.com/containerd/ttrpc/channel.go, vendor/github.com/containerd/ttrpc/client.go, vendor/github.com/containerd/ttrpc/config.go, vendor/github.com/containerd/ttrpc/interceptor.go, vendor/github.com/containerd/ttrpc/metadata.go, vendor/github.com/containerd/ttrpc/server.go, vendor/github.com/containerd/ttrpc/services.go, vendor/github.com/containerd/ttrpc/types.go
=> Update ttrpc for interceptors, closure, and metadata

diff/walking/differ.go
=> Ensure labels is not nil in differ

diff/walking/differ.go
=> [release/1.2] ensure labels is not nil in differ

client.go, container.go, container_opts.go, container_opts_unix.go, image.go
=> Fix snapshotter getter in client code

runtime/v2/shim.go
add timeout in connect shim v2 avoid starting containerd hang
=> Add timeout in load shim v2

remotes/docker/schema1/converter.go
Signed-off-by: zhangyue <zy675793960@yeah.net>
the two error msg same in different scenario， this pr just to polish them
=> fix: polish log to make more clear

cmd/containerd-shim/main_unix.go
Cherrypick of https://github.com/containerd/containerd/pull/3359 to release/1.1.
Signed-off-by: Shukui Yang <keloyangsk@gmail.com>
=> [release/1.1] Close socket fd

cmd/containerd-shim/main_unix.go
Cherrypick of https://github.com/containerd/containerd/pull/3359 to release/1.2.
Signed-off-by: Shukui Yang <keloyangsk@gmail.com>
=> [release/1.2] Close socket fd

runtime/v1/linux/proc/io.go
In current implementation the shim attempts to open a URI file path for logging and fails with something like:
```bash
$ sudo ctr run --log-uri file:///tmp/1.txt docker.io/library/hello-world:latest hello1
ctr: failed to start io pipe copy: unable to copy pipes: containerd-shim: opening file "file:///tmp/1.txt" failed: open file:///tmp/1.txt: no such file or directory: unknown
```
=> Fix shim's file IO logging

runtime/v2/runc/container.go, runtime/v2/runc/v1/service.go, runtime/v2/runc/v2/service.go
=> Reserve exec id to prevent race

runtime/v1/linux/proc/exec.go, runtime/v1/linux/proc/init.go, runtime/v1/linux/proc/init_state.go, runtime/v1/linux/proc/process.go, runtime/v1/linux/proc/utils.go
=> Robust pid locking for shim processes

runtime/v2/manager.go
When shimv2 dead, the container would be cleanup, but
the corresponding runtime task still existed in runtime
task lists, it should be deleted too.
Signed-off-by: lifupan <lifupan@gmail.com>
=> shimv2: remove the dead task from runtime task list

metadata/content.go
=> Fix metadata content store to call writer digest after commit

RELEASES.md
=> Add RELEASE note about config versioning

.travis.yml
=> Bump travis to criu 3.12

cmd/ctr/commands/snapshots/snapshots.go
When using devmapper snapshotter to execute the following command error:
ctr snapshots --snapshotter devmapper diff idA idB
Root cause: view snapshot is deleted before diff
Signed-off-by: Peng Wang <wang_peng168@163.com>
=> fix: view snapshot is deleted before diff

client.go, cmd/containerd/command/error.go, cmd/containerd/command/main.go, cmd/containerd/command/publish.go, cmd/containerd/command/service_windows.go, cmd/ctr/commands/containers/containers.go, cmd/ctr/commands/error.go, errdefs/errors.go, error.go
=> Replace hard coded error messages 

vendor.conf, vendor/github.com/containerd/cgroups/blkio.go, vendor/github.com/containerd/cgroups/cgroup.go, vendor/github.com/containerd/cgroups/memory.go
=> Update cgroups to c4b9ac5c7601384c965b9646fc51588

runtime/v1/linux/task.go
Cherry-pick https://github.com/containerd/containerd/pull/3419
=> [release/1.2] runtime/v1/linux: ignore ErrCgroupDeleted in Task.Start

cmd/containerd-stress/exec_worker.go, cmd/containerd-stress/main.go, cmd/containerd-stress/size.go
=> Add new shims for checking binary sizes and concurrent exec

cmd/ctr/commands/commands.go, cmd/ctr/commands/run/run_unix.go, oci/spec_opts.go, oci/spec_opts_linux.go, oci/spec_opts_unix.go, oci/spec_opts_windows.go
=> Add linux device options and --devices flag to ctr

cmd/ctr/commands/images/decrypt.go, cmd/ctr/commands/images/encrypt.go, image_enc_test.go, images/encryption/encryption.go, pkg/encryption/config/config.go
=> Wrap creation of CryptoConfig in constructors

archive/time_unix.go
=> archive: return chtimes error with path information

services/tasks/local.go
Fixes #3440
This also returns the task that times out or has an error on the state
call in an UNKNOWN status so that the user can manually kill and remove
the task.
=> Add timeout to task state calls

cmd/containerd/command/service_windows.go
Creating a console for containerd causes it to be inherited by any child
processes, which gives us performance and reliability improvements. See
comment in code for more information.
Another option considered here would be to invoke each child process
with the DETACHED_PROCESS flag. This would save us the containerd
console allocation. The difficulty of this approach would be ensuring
that all process invocation points have had this flag added, and that
any future invocations also use the flag.
=> Allocate a conhost during Windows service startup

runtime/task.go, runtime/v1/linux/task.go, runtime/v2/shim.go, services/tasks/local.go
=> Fast path getting pid from task

cmd/ctr/commands/tasks/exec.go, cmd/ctr/commands/tasks/tasks_unix.go
=> Call CloseIO when stdin closes in ctr

container_opts.go
fix issue https://github.com/containerd/containerd/issues/3448
Signed-off-by: BoWen Yan <loneybw@gmail.com>
=> bug fix:#3448

metadata/snapshot.go
Closes https://github.com/containerd/containerd/issues/3434
=> Call Update of snapshotter plugin

RELEASES.md
=> Add note about pb.txt files

daemon_config_linux_test.go
=> Improve custom cgroup test

images/archive/exporter.go
When providing multiple names, the shared annotation map was causing the names to get overridden.
Combined the WithManifest options which had compatible interfaces.
=> Fix bug in export named manifest option

pkg/encryption/gpg.go
Rather than passing the passphrase via command line write it into
a temp. file and pass the name of the file using passphrase-file option.
=> ECI: gpg: Pass the passphrase to the gpg2 tool using a pipe

.travis.yml, api/next.pb.txt, script/setup/install-protobuf
Enable travis CI for ppc64le arch
Signed-off-by: Nitesh Konkar <niteshkonkar@in.ibm.com>
=> travis: Enable travis CI for ppc64le arch

snapshots/devmapper/metadata.go, snapshots/devmapper/metadata_test.go, snapshots/devmapper/pool_device.go, snapshots/devmapper/pool_device_test.go
This PR addresses comment https://github.com/containerd/containerd/pull/3470#discussion_r309991702 from my previous PR.
In case of hard reset or crash, the snapshotter will mark devices as `Faulty` after restart if they're in incomplete (intermediate) state. 
cc @renzhengeek @samuelkarp 
ref https://github.com/containerd/containerd/pull/3436
=> Mark devices with invalid state as faulty

cmd/ctr/commands/tasks/exec.go, cmd/ctr/commands/tasks/tasks_unix.go
Cherry-pick/backport of #3462 
Had to detangle logURI support in master to fix cherry-pick conflicts; otherwise a straight copy back to `release/1.2`
=> [release/1.2] cherry-pick: Call CloseIO when stdin closes in ctr

remotes/docker/pusher.go
Signed-off-by: Guangming Wang <guangming.wang@daocloud.io>
=> pusher.go: error message typo correction

vendor.conf, vendor/github.com/Microsoft/go-winio/pkg/etw/provider.go, vendor/github.com/Microsoft/go-winio/pkg/fs/fs_windows.go, vendor/github.com/Microsoft/go-winio/pkg/guid/guid.go, vendor/github.com/Microsoft/go-winio/vhd/vhd.go
=> Update Microsoft/go-winio v0.4.14

.mailmap, releases/v1.3.0-beta.toml
Add CRI changes and update the rest of the notes to look as good as those. Update mailmap to handle duplicate entries.
See test generation of notes here https://gist.github.com/dmcgowan/faa870c4a0890e739fd1aaf0cfd76eff
=> Update 1.3 beta release notes

oci/spec_opts_linux.go
Signed-off-by: wanghuaiqing <wanghuaiqing@loongson.cn>
=> cast Rdev of Stat_t to uint64 for mips

client.go, pull.go
=> Add UnpackOpts to RemoteContext

releases/v1.3.0-beta.toml
=> Add release notes for stream processor

namespaces/ttrpc_test.go
If there are multiple goroutines calling `namespace.WithNamespace` on a
ctx that already had namespace, there will be a data race when
`withTTRPCNamespaceHeader` calling `MD.Set()`. So we have to copy the md
before using it.
Fixes https://github.com/containerd/containerd/issues/3504
=> namespace: Copy ttrpc metadata before setting header

remotes/docker/pusher.go
=> remotes: remove useless line

docs/stream_processors.md
=> Add docs for stream processors

image.go, image_test.go, images/handlers.go
The image usage function allows more configurable and accurate calculations of the resources held by an image.
=> Add image usage function to client

metadata/leases.go
Signed-off-by: Guangming Wang <guangming.wang@daocloud.io>
=> cleanup code typos in leases.go

vendor.conf, vendor/github.com/containerd/fifo/errors.go, vendor/github.com/containerd/fifo/fifo.go, vendor/github.com/containerd/fifo/raw.go, vendor/github.com/containerd/fifo/readme.md
Update containerd/fifo vendor.
=> Update fifo vendoring for typed errors

releases/v1.3.0-beta.toml
Update 1.3 containerd release note for the CRI plugin.
=> Update release note for CRI plugin for 1.3.

events/exchange/exchange.go, import.go, process.go
Signed-off-by: Guangming Wang <guangming.wang@daocloud.io>
=> Cleanup: fix some typos in code comment

contrib/nvidia/nvidia.go
Make the comment more readable
=> fix mis-spelling in nvidia.go

.travis.yml
Attempt number two (after https://github.com/containerd/containerd/pull/3606)
=> travis: fix Xenial tests not being run on master

cmd/containerd/command/config.go, docs/man/containerd-config.toml.5.md, docs/stream_processors.md, services/server/config/config.go, services/server/config/config_test.go, services/server/server.go, vendor.conf, vendor/github.com/imdario/mergo/LICENSE, vendor/github.com/imdario/mergo/README.md, vendor/github.com/imdario/mergo/doc.go, vendor/github.com/imdario/mergo/map.go, vendor/github.com/imdario/mergo/merge.go, vendor/github.com/imdario/mergo/mergo.go
Carry https://github.com/containerd/containerd/pull/3310
Fixes https://github.com/containerd/containerd/issues/3289
=> Support config imports

vendor.conf, vendor/github.com/containerd/cri/pkg/server/container_create.go, vendor/github.com/containerd/cri/pkg/server/image_pull.go
Update for https://github.com/containerd/cri/pull/1254
=> [release/1.2] Update cri to ad5dcc6cba067488d017540d06ebc08b21bb82bc

cmd/ctr/commands/commands.go, cmd/ctr/commands/run/run_unix.go, cmd/ctr/commands/run/run_windows.go, oci/spec_opts.go
=> Add --env-file to ctr

.travis.yml, Makefile
Fix Darwin build and split release target for cri release
=> [CI] fix darwin build for cri release

Makefile, script/setup/install-dev-tools
=> Try set GOGC for golint

cmd/containerd-stress/density.go
=> Fix density spec generation

Makefile
=> Makefile: increase deadline to 2m for golangci-lint

oci/spec_opts.go, oci/spec_opts_test.go, oci/spec_opts_unix_test.go
=> Add Opt for modifying shm size

cmd/containerd/command/service_unsupported.go, container_linux_test.go, images/archive/importer.go, oci/spec.go, process.go, remotes/handlers_test.go
Signed-off-by: yuxiaobo <yuxiaobogo@163.com>
=> Word spelling correction

metadata/db.go, namespaces/context.go, reports/2017-01-13.md, reports/2017-04-28.md, reports/2017-05-19.md, reports/2017-05-26.md, reports/2017-06-09.md
Signed-off-by: yuxiaobo <yuxiaobogo@163.com>
=> Perfect documentation

releases/v1.3.0-rc.toml
Adds note for garbage collection fix related to removal of leases, containers, and images.
=> Add release note for gc fix

snapshots/btrfs/btrfs_test.go
=> Sync and stat btrfs loopback in tests

metadata/db.go
Signed-off-by: yuxiaobo <yuxiaobogo@163.com>
A little mistake.
=> fix-up typo

vendor.conf, vendor/github.com/opencontainers/runc/libcontainer/README.md, vendor/github.com/opencontainers/runc/libcontainer/configs/blkio_device.go, vendor/github.com/opencontainers/runc/libcontainer/configs/cgroup_linux.go, vendor/github.com/opencontainers/runc/libcontainer/configs/cgroup_unsupported.go, vendor/github.com/opencontainers/runc/libcontainer/devices/devices.go, vendor/github.com/opencontainers/runc/libcontainer/nsenter/nsenter_unsupported.go, vendor/github.com/opencontainers/runc/libcontainer/nsenter/nsexec.c, vendor/github.com/opencontainers/runc/libcontainer/system/syscall_linux_64.go, vendor/github.com/opencontainers/runc/vendor.conf
=> Bump runc for CVE-2019-16884

vendor.conf, vendor/github.com/opencontainers/runc/libcontainer/README.md, vendor/github.com/opencontainers/runc/libcontainer/configs/blkio_device.go, vendor/github.com/opencontainers/runc/libcontainer/configs/cgroup_linux.go, vendor/github.com/opencontainers/runc/libcontainer/configs/cgroup_unsupported.go, vendor/github.com/opencontainers/runc/libcontainer/devices/devices.go, vendor/github.com/opencontainers/runc/libcontainer/nsenter/nsenter_unsupported.go, vendor/github.com/opencontainers/runc/libcontainer/nsenter/nsexec.c, vendor/github.com/opencontainers/runc/libcontainer/system/syscall_linux_64.go, vendor/github.com/opencontainers/runc/vendor.conf
=> [release/1.2] Bump runc for CVE-2019-16884

vendor.conf, vendor/github.com/opencontainers/runc/libcontainer/README.md, vendor/github.com/opencontainers/runc/libcontainer/configs/blkio_device.go, vendor/github.com/opencontainers/runc/libcontainer/configs/cgroup_linux.go, vendor/github.com/opencontainers/runc/libcontainer/configs/cgroup_unsupported.go, vendor/github.com/opencontainers/runc/libcontainer/devices/devices.go, vendor/github.com/opencontainers/runc/libcontainer/nsenter/nsenter_unsupported.go, vendor/github.com/opencontainers/runc/libcontainer/nsenter/nsexec.c, vendor/github.com/opencontainers/runc/libcontainer/system/syscall_linux_64.go, vendor/github.com/opencontainers/runc/vendor.conf
=> [release/1.1] Update runc for CVE-2019-16884

.travis.yml, releases/v1.1.8.toml, version/version.go
Add release notes and update version
Example generated notes https://gist.github.com/dmcgowan/1ddff904838d8d6ac29ed681073d3a5e
=> [release/1.1] Prepare 1.1.8

releases/v1.1.8.toml
Small but important misspelling
=> [release/1.1] Fix typo in 1.1.8 release notes

images/archive/exporter.go
Signed-off-by: yuxiaobo <yuxiaobogo@163.com>
Some new typos.
=> fix-up :typo

.travis.yml
Prevent Travis from building and pushing up multiple times
Fixes #3704
=> Limit travis release script to a single build

vendor.conf, vendor/github.com/opencontainers/runc/README.md, vendor/github.com/opencontainers/runc/libcontainer/apparmor/apparmor.go, vendor/github.com/opencontainers/runc/libcontainer/configs/config.go, vendor/github.com/opencontainers/runc/libcontainer/seccomp/config.go, vendor/github.com/opencontainers/runc/libcontainer/seccomp/seccomp_linux.go, vendor/github.com/opencontainers/runc/libcontainer/utils/cmsg.go, vendor/github.com/opencontainers/runc/libcontainer/utils/utils.go, vendor/github.com/opencontainers/runc/libcontainer/utils/utils_unix.go, vendor/github.com/opencontainers/runc/vendor.conf
=> Bump runc to 1b8a1eeec3f337ab5d94f28980

Makefile, version/version.go
=> version: use runtime.Version() directly

runtime/v1/shim/service.go
Cherrypick https://github.com/containerd/containerd/pull/3730 into release 1.2
=> [release/1.2] Fix shim delete error code.

runtime/v1/shim/service.go
Cherrypick #3730 into release 1.3.
=> [release/1.3] Fix shim delete error code. 

runtime/v1/linux/task.go, runtime/v2/shim.go, services/tasks/local.go
Cherry-pick of #3736 for `release/1.3`
=> [release/1.3] cherry-pick: Fix delete error code on the containerd daemon side.

diff/apply/apply_linux.go
`OverlayConvertWhiteout` calls `mknod c 0 0` which is not allowed when
running in a user namespace, even in Ubuntu kernel.
Although there is an alternative hacky way to create whiteouts without
calling mknod as Moby `overlay2` actually does(see #3762), let's use
naive applier when running in UserNS and call it a day.
Close #3762
=> apply: use naive applier when running in UserNS

cmd/containerd/builtins_linux.go, vendor.conf, vendor/github.com/containerd/aufs/LICENSE, vendor/github.com/containerd/aufs/README.md, vendor/github.com/containerd/aufs/aufs.go, vendor/github.com/containerd/zfs/LICENSE, vendor/github.com/containerd/zfs/README.md, vendor/github.com/containerd/zfs/zfs.go, vendor/github.com/mistifyio/go-zfs/LICENSE, vendor/github.com/mistifyio/go-zfs/README.md, vendor/github.com/mistifyio/go-zfs/error.go, vendor/github.com/mistifyio/go-zfs/utils.go, vendor/github.com/mistifyio/go-zfs/utils_notsolaris.go, vendor/github.com/mistifyio/go-zfs/utils_solaris.go, vendor/github.com/mistifyio/go-zfs/zfs.go, vendor/github.com/mistifyio/go-zfs/zpool.go
=> bring back aufs and zfs

docs/managed-opt.md, install.go, services/opt/service.go
Install windows shim dependencies in containerd managed opt directory.
=> Windows process shim installer

docs/managed-opt.md, install.go, services/opt/service.go
Signed-off-by: Ameya Gawde <ameya.gawde@docker.com>
(cherry picked from commit d21f0f116e29e498eeebf8440e9f43a06cf39cfc)
clean cherry-pick.
=> [release/1.3 backport] windows process shim installer

services/server/server_test.go
Signed-off-by: fahedouch <fahed.dorgaa@gmail.com>
=> add tests to server_test

Makefile
=> Add CGO makefile flag

cmd/ctr/commands/run/run_unix.go
from https://github.com/containerd/containerd/pull/3799
=> ctr: add --runc-binary --runc-systemd-cgroup

.mailmap
Looked ad duplicates in the AUTHORS file that was generated, and fixed some of them
=> Update .mailmap to reduce duplicates

snapshots/storage/bolt.go
(cherry picked from commit 843423ec3887eb47ac70308cee9267ef6a1fa435)
from #3819
=> [release/1.3] snapshots: return error if readSnapshot fails

snapshots/storage/bolt.go
(cherry picked from commit 843423ec3887eb47ac70308cee9267ef6a1fa435)
from #3819
=> [release/1.2] snapshots: return error if readSnapshot fails

.github/workflows/nightly.yml, README.md
This adds a few more architectures for Linux builds.
Example: https://github.com/mxpv/containerd/runs/303871920
ref: https://github.com/containerd/containerd/pull/3827 https://github.com/containerd/containerd/pull/3828
cc: @estesp
=> Cross-build nightly builds (arm64, s390x, ppc64el)

cmd/containerd/command/service_windows.go
Event and tracing are good, but the traditional log file is also very useful, e.g. I can't find an ETW plugin for fluentd yet.
`--log-file` is what we are doing for kubelet and kube-proxy on windows, too. It is optional, old behavior is kept if the flag is not specified.
@jterry75 
=> Add `--log-file` flag for windows service.

pull.go, unpacker.go
Cherrypick #3825 to release/1.3.
=> [release/1.3] Avoid deadlock in unpacker.

oci/spec_opts_test.go, oci/spec_test.go
Signed-off-by: fahedouch <fahed.dorgaa@gmail.com>
=> improve oci test coverage

cmd/containerd/command/service_windows.go
Backport of #3831 
Clean cherry-pick
=> [release/1.3]  Add `--log-file` flag for windows service.

container_test.go, pkg/process/exec.go, pkg/process/init.go, pkg/process/init_state.go, pkg/process/utils.go
=> [release/1.3] Fix container pid.

.appveyor.yml, releases/v1.3.2.toml, version/version.go
Generated release notes preview https://gist.github.com/dmcgowan/dedf1faf317604342cbf887942a80f35
=> [release/1.3] Prepare v1.3.2 release

image.go
=> Return the underlying images metadata

vendor.conf, vendor/github.com/containerd/go-runc/runc.go, vendor/github.com/containerd/go-runc/utils.go
=> Bump go-runc for buffer race fix

vendor.conf, vendor/github.com/containerd/console/console.go, vendor/github.com/containerd/console/console_unix.go, vendor/github.com/containerd/console/console_windows.go, vendor/github.com/containerd/console/go.mod
=> Bump containerd console for os.File changes

BUILDING.md
Signed-off-by: Daniel Bevenius <daniel.bevenius@gmail.com>
=> Correct grammar/typo in BUILDING.MD

cmd/ctr/commands/tasks/start.go
Signed-off-by: Joakim Roubert <joakimr@axis.com>
=> start.go: Improve help text

snapshots/devmapper/pool_device.go
This PR adds retries when deactivating a devmapper device, this might help address "device busy" errors.
ref: https://github.com/containerd/containerd/issues/3697 https://github.com/firecracker-microvm/firecracker-containerd/issues/137
=> Attempt to make device mapper snapshotter tests less flaky

script/setup/install-cni, script/setup/install-critools, script/setup/install-dev-tools, script/setup/install-protobuf, script/setup/install-runc, script/setup/install-seccomp
* Make string comparisons POSIX compatible
* Handle whitespace(s) in GOPATH
* Remove superfluous quotes in variable assignments
Signed-off-by: Joakim Roubert <joakimr@axis.com>
=> Improve install scripts

cmd/ctr/commands/tasks/metrics.go, metrics/cgroups/v2/cpu.go, metrics/cgroups/v2/memory.go, metrics/cgroups/v2/metrics.go
Partially fixes #3726 
Added memory and cpu metrics for cgroupv2
Signed-off-by: bpopovschi <zyqsempai@mail.ru>
=> Added memory and cpu metrics for cgroupv2

ADOPTERS.md
=> Add more adopters to ADOPTERS.md

vendor.conf, vendor/github.com/containerd/console/console_linux.go
Bring fix into master for containerd/console#34
=> Update containerd/console vendor for fix

client.go, cmd/ctr/commands/plugins/plugins.go, install.go, services.go, services/introspection/introspection.go, services/introspection/local.go, services/introspection/service.go, services/services.go
=> create local version of introspection service

.travis.yml, script/setup/install-runc
=> .travis.yml: run test with crun

gc/gc.go
=> Fix outdated comments

snapshots/lcow/lcow.go
Windows snapshot usage was completed in ref: #3785 but lcow didnt get updated.
=> Support disk usage in windows-lcow snapshot

Makefile
=> [release/1.3] Add Makefile variable to skip test packages

runtime/v2/runc/v1/service.go, runtime/v2/runc/v2/service.go
=> [release/1.3 backport] eventfd leak

vendor.conf, vendor/github.com/containerd/btrfs/README.md, vendor/github.com/containerd/btrfs/btrfs.go, vendor/github.com/containerd/btrfs/doc.go, vendor/github.com/containerd/btrfs/go.mod, vendor/github.com/containerd/btrfs/helpers.go, vendor/github.com/containerd/btrfs/info.go, vendor/github.com/containerd/btrfs/ioctl.go
=> vendor: bump containerd/btrfs to 153935315f4ab9be5bf03650a1341454b05efa5d

releases/README.md
=> Fix broken link to release-tool

snapshots/lcow/lcow.go, snapshots/windows/windows.go
=> Add support for custom wcow and lcow sandbox scratch sizes

vendor.conf, vendor/github.com/containerd/cri/vendor.conf, vendor/gopkg.in/yaml.v2/decode.go, vendor/gopkg.in/yaml.v2/scannerc.go, vendor/gopkg.in/yaml.v2/yaml.go, vendor/gopkg.in/yaml.v2/yamlh.go
Synchronizes dependency across master and 1.2 release branch
=> [release/1.3] Update yaml dependency

.mailmap, releases/v1.3.3.toml, version/version.go
Sample generation https://gist.github.com/dmcgowan/e99805e56a976c3275c6487bc22063e0
=> [release/1.3] Add release notes for v1.3.3

remotes/docker/fetcher.go, remotes/docker/resolver.go, remotes/docker/resolver_test.go
=> [release/1.3 backport] Improve host fallback behaviour in docker remote

script/setup/install-seccomp
=> Fix incorrect comment from copy/paste of starting script

remotes/docker/pusher.go
Cherry pick #4017
Signed-off-by: Josh Dolitsky <393494+jdolitsky@users.noreply.github.com>
=> [release/1.3] cherry-pick: Set octet-stream content-type on put request

.mailmap
includes the changes made in https://github.com/containerd/containerd/pull/4037
=> [release/1.3] Update .mailmap with changes from master

cmd/containerd/builtins_aufs_linux.go, cmd/containerd/builtins_zfs_linux.go
These plugins do not always need to be built-in.
=> support building with BUILDTAGS="no_zfs no_aufs"

filters/filter_test.go
=> Add unit test for func in filter.go

runtime/v2/binary.go
The background context aovids shim blocking when the ctx is cancelled unexpectedly during shim start (https://github.com/containerd/containerd/pull/3921). But if the shim exits unexpectedly before opening the pipe, the fd will never be closed. `onCloseWithShimLog` makes sure that the shim log fd is closed properly once the shim disconnects.
=> v2: Cancel shim log ctx when ttrpc is closed

container.go
In NewContainer if a SnapshotKey is used and the spec has a mountLabel specified, that mountLabel should be used to mount the rootfs.
This functionality is need to support full SELinux MCS support in containerd-cri. container-cri delegates mounting the rootfs to containerd by using the NewContainer method with a SnapshotKey. In this scenario the rootfs is not getting the proper selinux context="..." mount option applied.
=> Use spec's mountLabel when mounting the rootfs

runtime/v1/linux/runtime.go
When there is timeout or cancel for create container, killShim will fail
because of canceled context. The shim will be dangling and unmanageable.
Need to use new context to do cleanup.
=> bugfix: cleanup dangling shim by brand new context

runtime/v1/linux/runtime.go
When there is timeout or cancel for create container, killShim will fail
because of canceled context. The shim will be dangling and unmanageable.
Need to use new context to do cleanup.
(cherry picked from commit 18e581dd91fd671aaeba86dcae2b6c97142a1cb0)
from #4048
=> [release/1.3 backport] bugfix: cleanup dangling shim by brand new context

vendor.conf, vendor/github.com/opencontainers/selinux/go-selinux/selinux_linux.go, vendor/github.com/opencontainers/selinux/go-selinux/xattrs.go, vendor/github.com/opencontainers/selinux/go.mod
Here are the differences:
https://github.com/opencontainers/selinux/compare/3a1f366feb7aecbf7a0e71ac4cea88b31597de9e...5215b1806f52b1fcc2070a8826c542c9d33cd3cf
Found this when reviewing dependencies in kubernetes
=> Update to a released version of opencontainers/selinux (1.3.3)

oci/spec_opts.go, oci/spec_opts_linux.go
=> Add linux resource oci.SpecOpts

cmd/containerd/command/main.go, cmd/containerd/command/main_unix.go, cmd/containerd/command/main_windows.go, cmd/containerd/command/notify_linux.go, cmd/containerd/command/notify_unsupported.go, containerd.service, vendor/github.com/coreos/go-systemd/v22/daemon/sdnotify.go, vendor/github.com/coreos/go-systemd/v22/daemon/watchdog.go
=> Support NOTIFY_SOCKET

sys/filesys_windows.go
similar to https://github.com/moby/moby/pull/33399 and https://github.com/moby/moby/pull/40645
=> sys: windows: use golang.org/x/sys/windows

BUILDING.md
=> Update btrfs dependencies in docs

.golangci.yml, cmd/containerd/command/service_windows.go, script/setup/install-dev-tools
full diff: https://github.com/golangci/golangci-lint/compare/v1.18.0...v1.23.8
relates to the discussion on https://github.com/containerd/containerd/pull/4097#issuecomment-597017609
=> Update Golangci-lint v1.23.8

cmd/ctr/commands/run/run_unix.go
If runtime is not runc, it doesn't make sense to send runc Options
as container create options, which will confuse other runtimes and
it actually makes kata shimv2 to fail to unmarshal.
/cc @AkihiroSuda @lifupan
=> ctr: do not assume runc options by default

remotes/docker/handler_test.go
=> Add unit test for func in remotes/docker/handler.go

vendor.conf, vendor/github.com/cilium/ebpf/abi.go, vendor/github.com/cilium/ebpf/collection.go, vendor/github.com/cilium/ebpf/elf_reader.go, vendor/github.com/cilium/ebpf/internal/btf/btf.go, vendor/github.com/cilium/ebpf/internal/btf/btf_types.go, vendor/github.com/cilium/ebpf/internal/btf/doc.go, vendor/github.com/cilium/ebpf/internal/btf/ext_info.go, vendor/github.com/cilium/ebpf/internal/btf/strings.go, vendor/github.com/cilium/ebpf/internal/btf/types.go, vendor/github.com/cilium/ebpf/internal/errors.go, vendor/github.com/cilium/ebpf/internal/fd.go, vendor/github.com/cilium/ebpf/internal/io.go, vendor/github.com/cilium/ebpf/internal/ptr.go, vendor/github.com/cilium/ebpf/internal/ptr_32_be.go, vendor/github.com/cilium/ebpf/internal/ptr_32_le.go, vendor/github.com/cilium/ebpf/internal/ptr_64.go, vendor/github.com/cilium/ebpf/internal/syscall.go, vendor/github.com/cilium/ebpf/linker.go, vendor/github.com/cilium/ebpf/map.go, vendor/github.com/cilium/ebpf/marshalers.go, vendor/github.com/cilium/ebpf/prog.go, vendor/github.com/cilium/ebpf/syscalls.go, vendor/github.com/cilium/ebpf/types.go, vendor/github.com/cilium/ebpf/types_string.go
full diff: https://github.com/cilium/ebpf/compare/60c3aa43f488292fe2ee50fb8b833b383ca8ebbb...4032b1d8aae306b7bb94a2a11002932caf88c644
relates to https://github.com/containerd/containerd/pull/4146, which updated the cgroups package, but didn't include this dependency (which is listed as dependency for the cgroups package)
=> vendor: cilium/ebbf 4032b1d8aae306b7bb94a2a11002932caf88c644

vendor.conf, vendor/github.com/opencontainers/runtime-spec/README.md, vendor/github.com/opencontainers/runtime-spec/specs-go/config.go, vendor/github.com/opencontainers/runtime-spec/specs-go/version.go
full diff: https://github.com/opencontainers/runtime-spec/compare/29686dbc5559d93fb1ef402eeda3e35c38d75af4...v1.0.2
=> vendor: runtime-spec v1.0.2

vendor.conf, vendor/github.com/opencontainers/selinux/go-selinux/label/label.go, vendor/github.com/opencontainers/selinux/go-selinux/label/label_selinux.go, vendor/github.com/opencontainers/selinux/go-selinux/label/label_stub.go, vendor/github.com/opencontainers/selinux/go-selinux/selinux_linux.go, vendor/github.com/opencontainers/selinux/go-selinux/selinux_stub.go, vendor/github.com/opencontainers/selinux/go-selinux/xattrs.go, vendor/github.com/opencontainers/selinux/pkg/pwalk/README.md, vendor/github.com/opencontainers/selinux/pkg/pwalk/pwalk.go
Changes are listed here:
https://github.com/opencontainers/selinux/compare/v1.3.3...v1.5.1
Not urgent as such, just keep up with eco-system.
=> Update to selinux 1.5.1

pkg/process/io.go, runtime/v2/logging/logging.go
backport https://github.com/containerd/containerd/pull/4162 (https://github.com/containerd/containerd/issues/4159)
=> [release/1.3 backport] Rework shim logger shutdown process

sys/mount_linux.go
backport of https://github.com/containerd/containerd/pull/4160
forkAndMountat forks a process to chdir then mount layers. Signals are
blocked (using runtime_beforeFork) during fork.
There is a race condition that the child process finishes before the
parent process is scheduled and can unblock signal handling. The SIGCHLD
signal sent from the finished process may have been delivered to the
shim process's reaper thread and caused the parent process fail with
ECHLD error.
This patch sets up a pipe for communication between child and parent
instead of waiting for child exit status.
Fixes #4009.
Signed-off-by: Haitao Li <hli@atlassian.com>
(cherry picked from commit 35c14c6b56d38aaf100fb598c11cd4ffc2928209)
=> [release/1.3 backport] sys/mount_linux: use pipe for communicating mount result

RELEASES.md
=> RELEASES.md: update release1.2 status

content/local/store.go, content/local/store_test.go, content/local/writer.go
Signed-off-by: Stephen Day <stephen.day@getcruise.com>
=> content/local: validate digest before calculating path

runtime/v2/shim/shim_test.go
Signed-off-by: fahedouch <fahed.dorgaa@gmail.com>
=> v2 runtime shim test

.github/workflows/ci.yml, script/setup/install-dev-tools
=> Fix protobuild and CI check protos

script/setup/install-dev-tools
Backport https://github.com/containerd/containerd/pull/4188
=> Backport CI fix to 1.3

releases/v1.3.4.toml, version/version.go
=> Prepare release 1.3.4

script/setup/install-dev-tools
=> Fix retrieval of golangci-lint specific version

cmd/containerd/command/notify_linux.go
Signed-off-by: fahedouch <fahed.dorgaa@gmail.com>
=> remove if condition because it is handled by the sdNotify daemon func

vendor.conf, vendor/github.com/containerd/cri/pkg/server/sandbox_run.go
Commit ID: 65830369b6b2b4edc454bf5cebbd9b76c1c1ac66 from master
compare diff is here https://github.com/containerd/cri/compare/dc7afe8fbe53db06c3f883f6f8c9895a9dfb2314...65830369b6b2b4edc454bf5cebbd9b76c1c1ac66
=> vendor: update containerd/cri with 65830369b6b2b4edc454bf5cebbd9b76c1c1ac66 from master

vendor.conf, vendor/github.com/pkg/errors/README.md, vendor/github.com/pkg/errors/errors.go, vendor/github.com/pkg/errors/go113.go, vendor/github.com/pkg/errors/stack.go
full diff: https://github.com/pkg/errors/compare/v0.8.1...v0.9.1
=> vendor: github.com/pkg/errors v0.9.1

vendor.conf, vendor/github.com/containerd/ttrpc/go.mod, vendor/github.com/containerd/ttrpc/server.go, vendor/github.com/containerd/ttrpc/services.go, vendor/github.com/containerd/typeurl/LICENSE, vendor/github.com/containerd/typeurl/README.md, vendor/github.com/containerd/typeurl/doc.go, vendor/github.com/containerd/typeurl/go.mod, vendor/github.com/containerd/typeurl/types.go
This updates the two packages to their released versions.
=> Update ttrpc/typeurl to v1.0.1

README.md
=> doc: update example about task in README.md

.mailmap, releases/v1.4.0-beta.toml, version/version.go
Generated release notes at https://gist.github.com/dmcgowan/74e0b9fd6d1c93da2a954ee8e5c6894f
=> Add release notes for 1.4 beta

remotes/docker/pusher.go
Fix data race on err variable in the goroutine
=> docker: fix data race on err

vendor.conf, vendor/github.com/containerd/cri/README.md, vendor/github.com/containerd/cri/pkg/containerd/opts/spec_unix.go, vendor/github.com/containerd/cri/pkg/server/container_create.go, vendor/github.com/containerd/cri/pkg/server/container_create_unix.go, vendor/github.com/containerd/cri/pkg/server/helpers_unix.go, vendor/github.com/containerd/cri/pkg/server/sandbox_run.go, vendor/github.com/containerd/cri/pkg/server/sandbox_run_unix.go, vendor/github.com/containerd/cri/pkg/server/service.go, vendor/github.com/containerd/cri/pkg/store/container/container.go, vendor/github.com/containerd/cri/pkg/store/container/metadata.go, vendor/github.com/containerd/cri/pkg/store/label/label.go, vendor/github.com/containerd/cri/pkg/store/sandbox/metadata.go, vendor/github.com/containerd/cri/pkg/store/sandbox/sandbox.go, vendor/github.com/containerd/cri/vendor.conf, vendor/github.com/containerd/go-cni/README.md, vendor/github.com/containerd/go-cni/errors.go, vendor/github.com/containerd/go-cni/go.mod, vendor/github.com/containerd/go-cni/opts.go, vendor/github.com/containerd/go-cni/vendor.conf, vendor/github.com/opencontainers/selinux/go-selinux/label/label.go, vendor/github.com/opencontainers/selinux/go-selinux/label/label_selinux.go, vendor/github.com/opencontainers/selinux/go-selinux/label/label_stub.go
This bump contains updates for CRI with selinux support.
=> Update CRI to 52c2c6b5df15790b671ebd6cbbc6039a4d30

releases/v1.4.0-beta.toml, version/version.go
For preparing the next beta release
=> Update release notes for 1.4.0-beta.1

vendor.conf, vendor/github.com/containerd/cri/pkg/config/config.go, vendor/github.com/containerd/cri/pkg/server/container_create.go, vendor/github.com/containerd/cri/pkg/server/container_create_unix.go, vendor/github.com/containerd/cri/pkg/server/container_create_windows.go, vendor/github.com/containerd/cri/pkg/server/sandbox_run_unix.go, vendor/github.com/containerd/cri/pkg/server/sandbox_run_windows.go, vendor/github.com/containerd/cri/pkg/server/service.go
=> Revendor CRI to 8898550e348932e406049e937d98fb7564ac4e7a

SCOPE.md, contrib/seccomp/seccomp_default.go, contrib/seccomp/seccomp_default_unsupported.go
=> Update usage of whitelist in project

snapshots/overlay/overlay.go
kernel version > 4.13rc1 support index=on feature, it will be failed
with EBUSY when trying to mount.
Related: https://github.com/moby/moby/pull/37993
Signed-off-by: Rudy Zhang <rudyflyzhang@gmail.com>
=> overlay: use index=off to fix EBUSY on mount

pkg/process/init.go
The type of PdeathSignal is different between https://github.com/containerd/containerd/blob/v1.4.0-beta.1/runtime/v1/linux/runtime.go#L509 and https://github.com/containerd/containerd/blob/v1.4.0-beta.1/pkg/process/init.go#L90
I think we use x/sys instead of syscall.
I'll modify go-runc.
Signed-off-by: Kenta Tada <Kenta.Tada@sony.com>
=> Change the type of PdeathSignal

vendor.conf, vendor/github.com/containerd/cri/pkg/config/config.go, vendor/github.com/containerd/cri/pkg/config/config_unix.go, vendor/github.com/containerd/cri/pkg/config/config_windows.go, vendor/github.com/containerd/cri/pkg/containerd/opts/spec_windows.go, vendor/github.com/containerd/cri/pkg/server/container_create.go, vendor/github.com/containerd/cri/pkg/server/container_create_windows.go, vendor/github.com/containerd/cri/pkg/server/image_pull.go, vendor/github.com/containerd/cri/pkg/server/sandbox_run.go, vendor/github.com/containerd/cri/vendor.conf, vendor/github.com/opencontainers/selinux/go-selinux/label/label_selinux.go, vendor/github.com/opencontainers/selinux/go-selinux/selinux_linux.go, vendor/github.com/opencontainers/selinux/go-selinux/selinux_stub.go
=> Bump CRI for 1.4x release

contrib/apparmor/apparmor_unsupported.go
Will help compile code at least ...
=> Explicitly fail apparmor when not running on linux

.github/workflows/ci.yml, .github/workflows/nightly.yml, .github/workflows/release.yml, .travis.yml, .zuul/playbooks/containerd-build/run.yaml, Vagrantfile, contrib/Dockerfile.test
Changes: https://github.com/golang/go/milestone/148?closed=1
=> Bump Golang 1.13.12

docs/content-flow.md
As discussed on Slack with @cpuguy83 . Hopefully this helps future people have an easier time understanding the flow (and not having to ask all of the basic questions on Slack).
I am sure some of this is incorrect; if we can get it fixed here, that would be great.
=> describe content flow and dependencies

runtime/v2/runc/v2/service.go
=> decrease log level of cgroup2 ToggleController error when running in UserNS

.github/workflows/release.yml, releases/v1.3.5.toml, version/version.go
Full changes: https://github.com/containerd/containerd/compare/v1.3.4...60cf2f0374671df31d0c61b02fdc4b56fd0dd340
Also cherry-picks commits for `.github/workflows/release.yml`: https://github.com/containerd/containerd/pull/4282 https://github.com/containerd/containerd/pull/4291 https://github.com/containerd/containerd/pull/4292 https://github.com/containerd/containerd/pull/4303
Required by https://github.com/moby/moby/pull/41115
=> Prepare release v1.3.5

script/setup/install-runc
changes: https://github.com/containers/crun/releases/tag/0.14
=> update crun to v0.14

cio/io_unix.go, cio/io_unix_test.go, container_linux_test.go
=> cio: should not open fifo for stderr if terminal

.github/workflows/ci.yml
So sue me--maybe one of the silliest PRs I've done in a long time, but looking at the actions list it was bugging me that it didn't look like the rest 😸 
=> Make title similar with other CI workflow jobs

version/version.go
Last beta before rc
I didn't see anything big to add to the notes, please let me know if you have something to add
=> Update version to 1.4.0-beta.2

platforms/cpuinfo.go
=> platforms: don’t log arm variant error on darwin

vendor.conf, vendor/github.com/coreos/go-systemd/v22/README.md, vendor/github.com/opencontainers/selinux/go-selinux/label/label.go, vendor/github.com/opencontainers/selinux/go-selinux/label/label_selinux.go, vendor/github.com/opencontainers/selinux/go-selinux/label/label_stub.go
caught these when i was looking at cadvisor's deps.
- go-systemd is purely cosmetic (README update)
- selinux changes are here : https://github.com/opencontainers/selinux/compare/v1.5.1...v1.5.2
=> Updates to go-systemd and selinux

.github/workflows/ci.yml, Vagrantfile
Previously we were only testing cgroup2 with crun
=> cgroup2 CI: add RUNC_FLAVOR=runc

vendor.conf, vendor/github.com/containerd/cri/pkg/config/config.go, vendor/github.com/containerd/cri/pkg/config/config_unix.go, vendor/github.com/containerd/cri/pkg/config/config_windows.go, vendor/github.com/containerd/cri/pkg/containerd/opts/spec_unix.go, vendor/github.com/containerd/cri/pkg/server/container_create_unix.go, vendor/github.com/containerd/cri/pkg/server/container_update_resources_unix.go
Changes: https://github.com/containerd/cri/compare/8fb244a65baad2457e6c8658db18ed28b1f77cfe...fcda0cf4a7e70f0317238b09556329239321353b
=> vendor: update containerd/cri

snapshots/devmapper/pool_device.go
Hello containerd folks,
We have found this issue in our testing stack and the fix seems working so far. I still haven't reproduced the issue locally with containerd-stress though.
----
According to https://github.com/torvalds/linux/blob/c309b6f24222246c18a8b65d3950e6e755440865/Documentation/admin-guide/device-mapper/thin-provisioning.rst#internal-snapshots;
> If the origin device that you wish to snapshot is active, you
> must suspend it before creating the snapshot to avoid corruption.
However the devmapper snapshotter is currently not doing that.
=> snapshots/devmapper: suspend a device to avoid data corruption

mount/mount_linux.go
`exec.CombinedOutput()` intermittently returns `ECHILD` due to our
signal handling.
`wait(2)`: https://man7.org/linux/man-pages/man2/wait.2.html
> ECHILD (for waitpid() or waitid()) The process specified by pid
>   (waitpid()) or idtype and id (waitid()) does not exist or is
>   not a child of the calling process.  (This can happen for
>   one's own child if the action for SIGCHLD is set to SIG_IGN.
>   See also the Linux Notes section about threads.)
Fix #4387
=> mount: retry executing the helper binary on ECHILD

cmd/ctr/commands/run/run_unix.go, oci/spec_opts_unix.go
=> Add --cpus flag to ctr

container.go, container_linux_test.go, task.go
=> Add Spec() method to task

RELEASES.md, services/tasks/local.go
=> Deprecate legacy shims

vendor.conf, vendor/github.com/containerd/continuity/context.go, vendor/github.com/containerd/continuity/devices/devices_unix.go, vendor/github.com/containerd/continuity/digests.go, vendor/github.com/containerd/continuity/driver/driver_windows.go, vendor/github.com/containerd/continuity/fs/fstest/continuity_util.go, vendor/github.com/containerd/continuity/fs/fstest/testsuite.go, vendor/github.com/containerd/continuity/fs/path.go, vendor/github.com/containerd/continuity/go.mod, vendor/github.com/containerd/continuity/groups_unix.go, vendor/github.com/containerd/continuity/hardlinks.go, vendor/github.com/containerd/continuity/hardlinks_unix.go, vendor/github.com/containerd/continuity/manifest.go, vendor/github.com/containerd/continuity/sysx/xattr_unsupported.go, vendor/github.com/containerd/continuity/testutil/loopback/loopback_linux.go
full diff: https://github.com/containerd/continuity/compare/d3ef23f19fbb106bb73ffde425d07a9187e30745...efbc4488d8fe1bdc16bde3b2d2990d9b3a899165
Fix sameFile() to recognize empty files as the same
- fixes "Empty files can diff as "modified" even when they're not"
=> vendor: update containerd/continuity efbc4488d8fe1bdc16bde3b2d2990d9b3a899165

images/archive/importer.go, import_test.go
Cherry pick #3904 to `release/1.3`
Fixes: #4424
=> [release/1.3] cherry-pick: Replace ocispec.MediaTypeImageManifest with manifest.MediaType

.mailmap
=> [release/1.3] Update mailmap

releases/v1.3.7.toml, version/version.go
Signed-off-by: Joe Julian <me@joejulian.name>
=> Prepare v1.3.7 fix release

releases/v1.4.0-rc.toml, version/version.go
Move beta release notes and update version
=> Prepare 1.4.0-rc.0 release

cmd/containerd/command/oci-hook.go, vendor.conf, vendor/github.com/opencontainers/runc/go.mod, vendor/github.com/opencontainers/runc/libcontainer/configs/config.go, vendor/github.com/opencontainers/runtime-spec/specs-go/config.go, vendor/github.com/opencontainers/runtime-spec/specs-go/state.go
Changes: https://github.com/opencontainers/runc/releases/tag/v1.0.0-rc92
=> update runc to v1.0.0-rc92

version/version.go
No notable additions to the changelog
=> Update version for 1.4.0-rc.1

Vagrantfile
=> Vagrantfile: increase memory

.mailmap, RELEASES.md, releases/v1.4.0.toml, version/version.go
Update release notes form rc to GA.
Update mailmap
Update version
This merge commit will be the v1.4.0 tag and start of the release/1.4 branch
=> Prepare v1.4.0

runtime/v2/bundle.go
=> runtime: ignore ErrNotExist when remove rootfs

script/setup/install-cni, vendor.conf, vendor/github.com/containerd/go-cni/README.md, vendor/github.com/containerd/go-cni/go.mod, vendor/github.com/containernetworking/cni/README.md, vendor/github.com/containernetworking/cni/libcni/api.go, vendor/github.com/containernetworking/cni/libcni/conf.go, vendor/github.com/containernetworking/cni/pkg/invoke/args.go, vendor/github.com/containernetworking/cni/pkg/invoke/raw_exec.go, vendor/github.com/containernetworking/cni/pkg/types/020/types.go, vendor/github.com/containernetworking/cni/pkg/types/args.go, vendor/github.com/containernetworking/cni/pkg/types/current/types.go, vendor/github.com/containernetworking/cni/pkg/types/types.go, vendor/github.com/containernetworking/cni/pkg/utils/utils.go, vendor/github.com/containernetworking/plugins/README.md, vendor/github.com/containernetworking/plugins/go.mod, vendor/github.com/containernetworking/plugins/pkg/ns/README.md, vendor/github.com/containernetworking/plugins/pkg/ns/ns_linux.go
bump cni dependencies so we can benefits from its
bugfixes and improvements
xref: https://github.com/containerd/go-cni/pull/56
=> bump cni dependencies

cmd/ctr/commands/run/run_unix.go
=> Add --runtime-root to ctr

cmd/containerd/builtins_btrfs_linux.go, snapshots/btrfs/btrfs.go, snapshots/btrfs/plugin/plugin.go
Signed-off-by: knight42 <anonymousknight96@gmail.com>
Part of #4513 and #4514
=> feat(snapshot::btrfs): config root_path

cmd/ctr/commands/run/run_unix.go
Signed-off-by: Qian Xiao <heyheyco@gmail.com>
=> Fix ctr command typo.

cmd/ctr/commands/tasks/metrics.go
=> ctr: Return error if task.Metrics fails

runtime/v1/shim/client/client.go
These fifos fill up if unconsumed, so always consume them.
Before this change, it was only being consumed if shim debug is set.
Fixes #4509
Closes #4545
This issue became evident in https://github.com/containerd/containerd/commit/e3ab8bda604dbafb6c69f4c42979e92ead445138 where a new log entry was added that happens to get logged every time an exec exits when the client deletes the exec before the event is processed in the shim.
=> Always consume shim logs

Makefile
backport of https://github.com/containerd/containerd/pull/4490
This prevents packages with no Go included files due to build constraints
being included in the package list. These packages cause the test command
to fail with "can't load package build constraints exclude all Go files".
(cherry picked from commit 3275a216fd3bc3a86ecf84981323290d1ec5b146)
=> [release/1.4 backport] Update go list to respect build tags

contrib/gce/configure.sh
Signed-off-by: Roy Yang <royyang@google.com>
=> Refractor the script to work in both python2 and python3

runtime/v1/shim/client/client.go
These fifos fill up if unconsumed, so always consume them.
Backport of #4546
=> [release/1.4] Always consume shim logs

.github/workflows/ci.yml, .github/workflows/nightly.yml, .github/workflows/release.yml, .travis.yml, .zuul/playbooks/containerd-build/run.yaml, Vagrantfile, contrib/Dockerfile.test
opening as draft, to see if there are regressions/failures
~temporarily rebased on https://github.com/containerd/containerd/pull/4072~
=> Update to golang 1.15.2

releases/v1.4.1.toml, version/version.go
Notes preview https://gist.github.com/dmcgowan/4aba9f29890a5576340568cb9480f439
=> Prepare v1.4.1 release

RELEASES.md
=> Update latest release in RELEASES.md

cmd/containerd/builtins_devmapper_linux.go, snapshots/devmapper/plugin/plugin.go, snapshots/devmapper/snapshotter.go
Solves devicemapper part of #4513
=> Separate devmapper plugin

cmd/containerd/builtins_aufs_linux.go, vendor.conf, vendor/github.com/containerd/aufs/README.md, vendor/github.com/containerd/aufs/aufs.go, vendor/github.com/containerd/aufs/go.mod, vendor/github.com/containerd/aufs/plugin/plugin.go
It solves the aufs part of the #4514 and #4513 .
https://github.com/containerd/aufs/pull/21 needs to be merged along with this.
Signed-off-by: Siddharth Yadav <sedflix@gmail.com>
=> feat(snapshot::aufs): config root_path

test/build-utils.sh, test/build.sh
=> k8s cri prow build test

cmd/ctr/commands/tasks/tasks_unix.go
Signed-off-by: Guanjun Gong <gongguanjun@hotmail.com>
https://github.com/containerd/containerd/blob/f543f2fbcd1eb7f7bcb0994b80da490736cd0aab/cmd/ctr/commands/tasks/tasks_unix.go#L75-L99
`ioCreator` can be built at most 4 times, we should avoid unnecessary init.
=> avoid unnecessary NewCreator calls

script/setup/install-runc
Changes: https://github.com/containers/crun/releases/tag/0.15
=> CI: update crun to v0.15

vendor.conf, vendor/github.com/containerd/nri/client.go, vendor/github.com/containerd/nri/types/v1/types.go
Signed-off-by: Maksym Pavlenko <mxpv@apple.com>
=> Revendor NRI

pkg/cri/server/sandbox_remove.go
=> Fix comment in RemovePodSandbox

content/proxy/content_reader.go
Fixes #4617
Short summary: we go down the following chain when we try to read data from containerd via grpc:
1. [NewContentStore](https://github.com/containerd/containerd/blob/1ac546b3c4a3331a9997427052d1cb9888a2f3ef/content/proxy/content_store.go#L37) returns a `content.Store` implementation, specifically, [proxyContentStore](https://github.com/containerd/containerd/blob/1ac546b3c4a3331a9997427052d1cb9888a2f3ef/content/proxy/content_store.go#L31-L33)
1. When attempting to get a reader via [proxyContentStore.ReaderAt](https://github.com/containerd/containerd/blob/1ac546b3c4a3331a9997427052d1cb9888a2f3ef/content/proxy/content_store.go#L93) returns a `content.ReaderAt` implementation, specifically [remoteReaderAt](https://github.com/containerd/containerd/blob/1ac546b3c4a3331a9997427052d1cb98 …
=> ensure we cancel child context when reading grpc

.github/workflows/ci.yml, Makefile, hack/test-cri-integration.sh, hack/test-utils.sh, integration/main_test.go
=> getting cri integration up and running

.github/workflows/ci.yml
=> Use project checks

ADOPTERS.md
Add D2iQ Konvoy product as an adopter.
Signed-off-by: Hector Fernandez hfernandez@d2iq.com
=> Add d2iq as an adopter

runtime/v2/shim/shim_unix.go, vendor.conf, vendor/github.com/containerd/fifo/fifo.go
=> Fix panic in shim not logged

vendor.conf, vendor/github.com/containerd/fifo/fifo.go
fixes build on arm64 -- see: https://github.com/containerd/containerd/pull/4657#issuecomment-716814975, https://github.com/containerd/fifo/issues/27, https://github.com/containerd/fifo/pull/28
Signed-off-by: Benjamin Elder <bentheelder@google.com>
=> Revender latest containerd/fifo

remotes/docker/httpreadseeker.go
sorry, lame PR 😅 but saw this while looking into https://github.com/containerd/containerd/issues/4672
=> httpReadSeeker: fix typo in error-message

docs/config.md
docs change for: https://github.com/containerd/containerd/pull/4665/files#diff-ed442831d4918259dd77aea42ecc207d001e4e14afa88a0051c0bb4074ced55eR46
=> change default for disable snapshot annotations

docs/testing.md
=> refresh cri testing guide after move

hack/utils.sh, script/setup/install-critools
=> updates cri-tools to latest version

.github/workflows/ci.yml, hack/test-utils.sh
=> ci: run cri-integration target for all runtimes

.github/workflows/ci.yml
=> ci: run critest target for all runtimes

.github/workflows/ci.yml, .github/workflows/nightly.yml, .github/workflows/release.yml, .zuul/playbooks/containerd-build/run.yaml, Vagrantfile, contrib/Dockerfile.test
Changes: https://golang.org/doc/devel/release.html#go1.15
=> Bump Golang 1.15.5

.github/workflows/ci.yml, .github/workflows/nightly.yml, .github/workflows/release.yml, .travis.yml, .zuul/playbooks/containerd-build/run.yaml, Vagrantfile, contrib/Dockerfile.test
Changes: https://golang.org/doc/devel/release.html#go1.15
Cherry-pick https://github.com/containerd/containerd/pull/4735
=> [release/1.4] Bump Golang 1.15.5

.github/workflows/ci.yml
Also switch to use pre-packaged containerd project checks
=> [release/1.4] Fix GH Actions CI deprecations

.github/workflows/nightly.yml, .github/workflows/release.yml
=> Update other actions for env/path CVE fix

.github/workflows/release.yml
=> [release/1.3] Fix release.yml script for GH Actions changes to env/path

.github/workflows/nightly.yml, .github/workflows/release.yml
(cherry picked from commit 159fb2e7e248a1865e26d9db42f72e5dbe003cd9)
From: #4745
=> [release/1.4] cherry-pick: Update other actions for env/path CVE fix

cmd/containerd/command/service_windows.go
backport of https://github.com/containerd/containerd/pull/4589
=> [release/1.3 backport] Fix integer overflow on windows

cmd/containerd/command/service_windows.go
backport of https://github.com/containerd/containerd/pull/4589
=> [release/1.4 backport] Fix integer overflow on windows

container_restore_opts.go
backport of https://github.com/containerd/containerd/pull/4688
fixes https://github.com/containerd/containerd/issues/4646
=> [release/1.3 backport] bug fix:#3448: invalid use of nil pointer in container restoring

container_restore_opts.go
backport of https://github.com/containerd/containerd/pull/4688
fixes https://github.com/containerd/containerd/issues/4646
=> [release/1.4 backport] bug fix:#3448: invalid use of nil pointer in container restoring

RELEASES.md
Minor improvements to the documentation on creating backports.
=> Update backports documentation

.github/workflows/ci.yml, snapshots/overlay/overlay_test.go, snapshots/testsuite/testsuite.go, sys/oom_unix_test.go, vendor.conf, vendor/github.com/containerd/btrfs/btrfs.go, vendor/github.com/containerd/btrfs/go.mod
=> [release/1.4] re-enable unit tests in GitHub Actions environment

.mailmap, releases/v1.4.2.toml, vendor.conf, vendor/github.com/containerd/cri/pkg/server/events.go, version/version.go
Still a couple pending PRs, but please review notes
https://gist.github.com/dmcgowan/20b66d6aee48aa473886fa3358fdc215
=> [release/1.4] Prepare 1.4.2 release

script/setup/install-runc
Changes since 0.15:
- https://github.com/containers/crun/releases/tag/0.16
- https://github.com/containers/crun/releases/tag/0.15.1
=> CI: update crun to 0.16

README.md
I've fixed some typos and grammars.
Retry [#4774](https://github.com/containerd/containerd/pull/4774)
=> Fix some typos and grammars

.mailmap, releases/v1.3.8.toml, version/version.go
Generated notes: https://gist.github.com/dmcgowan/aa2d8a4eefbc6ad98366c0731d65f099
=> Prepare 1.3.8 release

README.md
Hi there,
As title says: fixing 1 typo in README
Best,
Didier
Signed-off-by: Didier Durand <durand.didier@gmail.com>
=> Fixing 1 typo in README

content/local/locks_test.go
When multiple clients are pulling the same image, we may have this
lock error. Short-lived locks are probably fine, but long-lived locks
may indicate that containerd has some issues.
=> content: include the staleness of the lock when tryLock() fails

cmd/ctr/commands/content/fetch.go
Expected to be used by nerdctl
=> ctr/commands/contents: expose ShowProgress

oci/spec_opts.go
These functions are planned to be used for implementing `nerdctl exec --user`.
=> oci: expose getUserFromPath and getGIDFromPath

remotes/docker/pusher.go
=> pusher: add missing authentication support for requests

remotes/docker/resolver.go
=> docker: avoid concurrent map access panic

images/mediatypes.go
Signed-off-by: Guangwen Feng <fenggw-fnst@cn.fujitsu.com>
=> Fix typo in comment

pkg/cri/io/container_io.go, pkg/cri/io/exec_io.go, pkg/cri/server/container_execsync.go, pkg/cri/server/instrumented_service.go
=> [CRI] Reduce clutter of log entries during process execution

cmd/containerd/command/main_unix.go
If we print message when SIG_PIPE occuers in signal handler.
There is a loop {print->SIG_PIPE->print->SIG_PIPE...}, which consume
a lot of cpu time. So do not print message in this situaiton.
Signed-off-by: Liu Hua <weldonliu@tencent.com>
=> signal: do not print message when dealing with SIG_PIPE

.github/workflows/ci.yml, .github/workflows/nightly.yml, .github/workflows/release.yml, .zuul/playbooks/containerd-build/run.yaml, Vagrantfile, contrib/Dockerfile.test
Changes: https://golang.org/doc/devel/release.html#go1.15
=> Bump Golang 1.15.6

sys/stat_openbsd.go
Hello, these are some small changes which are made to have docker/cli buildable and run on OpenBSD (I'm the maintainer of the sysutils/docker-cli port).
Thanks!
=> Bring OpenBSD support

remotes/docker/resolver.go
(cherry picked from commit bf323c5bdd5c9bdd2f957e03c4cdaa43e4c1c5a6)
Signed-off-by: Shengjing Zhu <zhsj@debian.org>
cherry-pick #4855
=> [release/v1.4] docker: avoid concurrent map access panic

remotes/docker/pusher.go
(cherry picked from commit 4dfec7fa0175c2728301d5da1e431641a9e50f28)
Signed-off-by: Shengjing Zhu <zhsj@debian.org>
cherry-pick #4854
=> [release/v1.4] pusher: add missing authentication support for requests

pkg/cri/opts/spec_linux.go, pkg/cri/server/container_create_linux.go
=> [cri] label etc files for selinux containers

.github/workflows/ci.yml, .github/workflows/nightly.yml, .github/workflows/release.yml, .zuul/playbooks/containerd-build/run.yaml, Vagrantfile, contrib/Dockerfile.test
Changes: https://golang.org/doc/devel/release.html#go1.15.minor
=> Bump Golang 1.15.7

RELEASES.md
The file was not updated to reflect the current status.
=> RELEASES.md: v1.2 reached EOL on October 15, 2020

script/setup/install-runc
https://github.com/containers/crun/releases/tag/0.17
=> CI: update crun to 0.17

runtime/v2/binary.go, runtime/v2/shim.go, runtime/v2/shim_unix.go
Signed-off-by: Zhiyu Li <payall4u@qq.com>
(cherry picked from commit 957fa33)
Cherry-pick: #4906
=> [release/1.4] bugfix change flag from RDONLY to RDWR and close the fifo correct

vendor.conf, vendor/github.com/containerd/continuity/fs/du_unix.go, vendor/github.com/containerd/continuity/go.mod
=> [release/1.4] Update continuity

mount/losetup_linux.go
=> FIx file is not closed

pkg/cri/server/container_stop.go, pkg/cri/store/container/container.go
Fixes #5020
xref https://github.com/kubernetes/kubernetes/pull/98507
=> Fix repeated sending signal

.github/workflows/ci.yml
=> [release/1.4] CI: fix "ls: cannot access '/etc/cni/net.d': Permission denied"

runtime/v2/runc/v1/service.go
=> Fix missing close

.github/workflows/ci.yml
=> CI: cache ~/.vagrant.d/boxes

.github/workflows/ci.yml
Cherry-pick https://github.com/containerd/containerd/pull/5099
=> [release/1.4] CI: cache ~/.vagrant.d/boxes

pkg/cri/server/cni_conf_syncer.go
carry: https://github.com/containerd/containerd/pull/4825/commits/612f5f9f44927a558ee3e35b7c7233baf39169e8
----------
close: #4825
=> cri: check fsnotify watcher when receiving cni conf dir events

contrib/gce/configure.sh
=> Fix pull-containerd-node-e2e failure on master

releases/v1.5.0-beta.toml, version/version.go
See rendered release notes for reviewing format https://gist.github.com/dmcgowan/dc3cacd6f1c6fbb5ae69d7d0e392cc35
=> Prepare release notes for 1.5.0-beta.3

test/e2e
Same as f70c579c3a442a1f946a052eda8af1af7e2a27a9 which was in the containerd/cri repo
=> Create symlink to avoid duplicate cloud init

client_test.go, contrib/ansible/cri-containerd.yaml, docs/PLUGINS.md, docs/cri/config.md, docs/cri/crictl.md, integration/main_test.go, pkg/cri/config/config_unix.go, pkg/cri/config/config_windows.go
issue: https://github.com/containerd/containerd/issues/5013
Wait for https://github.com/kubernetes/kubernetes/pull/98205 to be merged
=> move to v3.4.1 for the pause image

snapshots/overlay/check.go, snapshots/overlay/overlay.go, snapshots/overlay/overlay_test.go
Cherry-pick https://github.com/containerd/containerd/pull/5076
=> [release/1.4] overlay: support "userxattr" option (kernel 5.11)

restart_monitor_linux_test.go
=> deflake TestRestartMonitor

client.go
=> Document the Runtime public method

.github/workflows/ci.yml, .github/workflows/nightly.yml, .github/workflows/release.yml, .zuul/playbooks/containerd-build/run.yaml, Vagrantfile, contrib/Dockerfile.test
=> Update to Go 1.16.2

remotes/handlers.go
Fixes: #5124 
Any chance you have a way to try this fix @amouat? I am only able to force this error with a contrived setup that just forces the size to zero earlier in the code flow from a pull operation.
=> Better error when handling a descriptor of size zero

cmd/ctr/commands/images/export.go
=> cmd/ctr: fix export command

cmd/ctr/commands/images/export.go
(cherry picked from commit 231bbdc37950098926b5e41db8b134bd70f14a85)
cherry-pick: https://github.com/containerd/containerd/pull/5197
=> [release/1.4] cmd/ctr: fix export command

runtime/v2/shim.go, runtime/v2/shim_unix.go, runtime/v2/shim_unix_test.go
=> runtime: ignore file-already-closed error if dead shim

.mailmap, releases/v1.5.0-beta.toml, version/version.go
https://gist.github.com/dmcgowan/dc3cacd6f1c6fbb5ae69d7d0e392cc35
=> Prepare release notes for v1.5.0-beta.4

archive/tar_freebsd.go, integration/client/container_linux_test.go, integration/client/daemon_config_linux_test.go
=> gofmt -s -w all the things

runtime/v2/runc/v1/service.go, runtime/v2/runc/v2/service.go, runtime/v2/shim/shim.go
When runC shimv2 starts, the StartShim interface will re-exec itself as
long-running process, which will read the `address` during initializing.
```happycase
Process
containerd-shim-runc-v1/v2 start             containerd-shim-runc-v1/v2
initializing socket
reexec containerd-shim-runc-v1/v2
write address into file
initializing
read address
write back to containerd daemon
serving
...
remove address in Shutdown call
```
However, there is no synchronization after reexec. Then the data race is
like:
```leaking-case
Process
containerd-shim-runc-v1/v2 start             containerd-shim-runc-v1/v2
initializing socket
reexec containerd-shim-runc-v1/v2
initializing
read address
write address into file
write back to containerd daemon
serving
...
fail to remove address
because of empty address
``` …
=> runtime/v2/runc: fix leaking socket path

runtime/v2/runc/v1/service.go, runtime/v2/runc/v2/service.go, runtime/v2/shim/shim.go
cherry-pick: #5195 and #5051 (5051 is to fix conflict)
=> [release/1.4] runtime/v2/runc: fix leaking socket path

cmd/ctr/commands/content/prune.go, diff/apply/apply.go, diff/lcow/lcow.go, diff/windows/windows.go
=> Change dgst to digest in debug

runtime/v1/linux/runtime.go
=> Fix error log when kill shim

remotes/docker/pusher_test.go
=> Add unit test for func in remotes/docker/pusher.go

pkg/process/init.go
=> Fix error log when copy file

docs/cri/registry.md
Added reference to previous config syntax.
Signed-off-by: Andrei Dobre <andreidobre.web@gmail.com>
Fixes #5151
=> Make CRI registry docs more clear

cmd/ctr/commands/tasks/exec.go
set user in exec container
$ ctr t exec --exec-id e1 --user admin container id
uid=500(admin) gid=500(admin) groups=500(admin)
Signed-off-by: chuangxue <chenglong.lcl@alibaba-inc.com>
Signed-off-by: acetang <aceapril@126.com>
=> ctr: add --user for task exec

pkg/cri/server/sandbox_portforward_linux.go
port-forward needs to open a connection inside the namespace to the localhost address.
localhost can resolve to both IPv4 and IPv6 addresses in dual-stack systems
but the application can be listening in one of the IP families only.
golang has enabled RFC 6555 Fast Fallback (aka HappyEyeballs)
by default in 1.12. It means that if a host resolves to both IPv6 and IPv4,
it will try to connect to any of those addresses and use the
working connection.
However, the implementation uses go routines to start both connections in parallel,
and this has limitations when running inside a namespace, so we try to the connections
serially disabling the Fast Fallback support.
xref golang/go#44922
Signed-off-by: Antonio Ojea <aojea@redhat.com>
I've tested it with this snippet
```go
func main() { …
```
=> use (sort of) happy-eyeballs for port-forwarding

pkg/process/init.go
Cherry pick of #5229 on release/1.4.
#5229: Fix error log when copy file
=> [release/1.4] Cherry pick of #5229: Fix error log when copy file

releases/v1.5.0-rc.toml, version/version.go
See generated release notes https://gist.github.com/dmcgowan/dc3cacd6f1c6fbb5ae69d7d0e392cc35
=> Prepare v1.5.0-rc.0

script/setup/install-runc
Release notes: https://github.com/containers/crun/releases
=> CI: update crun to 0.19

metadata/boltutil/helpers.go, metadata/containers.go
This PR extracts out a few more bolt utils from the codebase for easier management.
=> Add more bolt utils

.github/workflows/ci.yml, RELEASES.md, cmd/containerd/command/config.go, integration/client/client_test.go, integration/client/daemon_config_linux_test.go, script/test/utils.sh, services/server/config/config.go, services/server/config/config_test.go, vendor/github.com/Microsoft/hcsshim/pkg/ociwclayer/export.go
We are telling folks to switch to version `2`, so we should do this ourselves as well :)
=> Switch all our tests to version 2 of config.toml

runtime/v2/manager.go
As part of my sandbox effort I need to refactor task manager's `Create` func, and have shim start and task create as separate pieces. This area contains numerous clean up patches and a bit fragile, so I'd like to get feedback on this separately.
=> Decouple shim start from task creation

pkg/cri/config/config.go, pkg/cri/config/config_test.go
the following config issue
https://github.com/kubernetes/kubernetes/pull/100992/files
shows we needed more help in the error messaging
=> address recent runtimes config confusion

.mailmap, releases/v1.5.0-rc.toml, version/version.go
See https://gist.github.com/dmcgowan/dc3cacd6f1c6fbb5ae69d7d0e392cc35 for generated notes
=> Prepare 1.5.0-rc.1 release

cmd/containerd/command/main.go, cmd/containerd/command/main_unix.go, cmd/containerd/command/main_windows.go
fix https://github.com/containerd/containerd/issues/5356
=> fix(windows): create debug npipe failure

pkg/cri/io/logger.go
From #5285 
I try to reduce the cpu usage of the function redirectLogs of cri. 
Signed-off-by: Zhiyu Li <payall4u@qq.com>
=> cri: Reduce the cpu usage of  the function redirectLogs in cri

runtime/v1/shim/service.go
Add the missing locks in ListPids
=> runtime/v1: Add lock for ListPids

content/local/store.go
=> Optimize content/local/store.Writer backoff

remotes/docker/resolver.go
Cherry-pick #5351
(cherry picked from commit d21fe462508cbc46264749cc153e4673c4b1e391)
=> [release/1.4] adds log for each failed host and status not found on host

runtime/v2/shim/shim.go
Check the namespace parameters before doing anything more
=> runtime/shim: check the namespace flag first

test/build-test-images.sh, test/init-buildx.sh
borrowed from https://github.com/kubernetes/release/blob/master/hack/init-buildx.sh
=> prow needs some additional setup for docker buildx

releases/v1.5.0.toml, version/version.go
For 1.5.0 final
https://gist.github.com/dmcgowan/dc3cacd6f1c6fbb5ae69d7d0e392cc35
=> Prepare 1.5.0 release notes

pkg/cri/server/image_pull.go
Fixes https://github.com/containerd/containerd/issues/5330.
=> Fix different registry hosts referencing the same auth config.

.github/workflows/ci.yml, .github/workflows/release.yml, .zuul/playbooks/containerd-build/integration-test.yaml, script/setup/install-seccomp
=> update seccomp version

vendor.conf, vendor/github.com/containerd/cri/pkg/server/image_pull.go
=> vendoring in cherry pick #5446 from v1.4 CRI release for next 1.4 service refresh

.github/workflows/ci.yml, .github/workflows/nightly.yml, .github/workflows/release.yml, .zuul/playbooks/containerd-build/run.yaml, Makefile, Vagrantfile, contrib/Dockerfile.test
Backports build updates from #5450 #5461
=> [release/1.5] Backport build updates

pkg/cri/server/image_pull.go
For https://github.com/containerd/containerd/issues/5330.
=> [release/1.5] Backport #5446 to release 1.5.

pkg/cri/server/image_pull.go
Signed-off-by: Aditi Sharma <adi.sky17@gmail.com>
https://github.com/containerd/containerd/issues/4826
=> Skip TLS verification for localhost

docs/hosts.md
1.5 brought support for hosts configuration using the hosts directory, this backports the related documentation
=> [release/1.5] hosts documentation

script/setup/imgcrypt-version, script/setup/install-imgcrypt
=> [release/1.5] Update imgcrypt release

releases/v1.5.1.toml, version/version.go
See generated release notes https://gist.github.com/dmcgowan/dc4311ba5142fb77b665444de45916d1
=> Prepare release notes for v1.5.1

remotes/docker/resolver.go
This PR is based on https://github.com/containerd/containerd/pull/4575#issuecomment-760631425.
Fixes #4531
Closes #4575
=> Try next mirror in case of non-404 errors, too

releases/v1.4.6.toml
See https://gist.github.com/dmcgowan/b73f1ae0e4b846536ddbe2e235e4a8d8
=> [release/1.4] Prepare release notes for v1.4.6

version/version.go
Also update the version for the release
=> [release/1.4] Update v1.4.6 version

releases/v1.5.2.toml, version/version.go
See https://gist.github.com/dmcgowan/f400889ca651f6ddb785448b4a9a41a2
=> [release/1.5] Prepare release notes for v1.5.2
