ctr/container.go
io.go

Close stdin after data has been copied

---

Dockerfile
Makefile

This is going to fail for crap load of vet/lint errors

add dockerfile/makefile additions for ci

---

chanotify/chanotify.go
chanotify/chanotify_test.go

Fix adding to chanotify on blocking select

---

linux/linux.go

Fixes the compile issue #62

---

ctr/container.go

container start with `-a` exit will not restore the terminal settings and not close
the stdin.
<pre><code># ctr containers start -a busybox /home/lei/containers/busybox
/ # ls
bin   dev   etc   home  proc  root  sys   tmp   usr   var
/ # exit
[root@centos-188 src]# [root@centos-188 src]# [root@centos-188 src]# [root@centos-188 src]# [root@centos-188 src]#</code></pre>
after container exit, the terminal mess up and I have to close the terminal.
We should restore the terminal settings and close the stdin before `os.Exist` and `fatal`
since this will terminate the process immediately

Fix container exit not restore terminal and close stdin

---

README.md

Clean up option output tabbing; update to latest

---

chanotify/chanotify.go

Rename the receiver name

---

api/grpc/types/api.proto

Signed-off-by: Antonio Murdaca <runcom@redhat.com>

api: grpc: types: align fields in api.proto

---

chanotify/chanotify_test.go

Take advantage of having interface{} chanotify keys

---

ctr/checkpoint.go
ctr/container.go
ctr/events.go
ctr/main.go

main packages are not importable; see the discussion at https://github.com/golang/go/issues/4210

Do not export symbols from the main package

---

containerd/main.go

Following up with #87.
/cc @crosbymichael

containerd: do not export any symbols

---

chanotify/chanotify.go

chanotify: do not allow adding new channels if notifier is closed

---

ctr/container.go

ctr: convert bundle paths to absolute

---

api/grpc/server/server.go
linux/linux.go
runtime/container.go
supervisor/event.go
supervisor/update.go

runtime: remove unnecessary intermediate type, Status

---

chanotify/chanotify.go
chanotify/chanotify_test.go

Reject duplicate keys on the notifier

---

chanotify/chanotify.go

Clarify chanotify docs about the usage of Add and Close

---

supervisor/stats.go

Fix stats command not returning

---

osutils/windows.go

As the title says :smile:  Fixes the osutils directory.

First step towards compiling on Windows

---

runtime/container.go
runtime/container_linux.go
runtime/container_windows.go
runtime/process.go
runtime/spec_linux.go
runtime/spec_windows.go

Refactors getRootIDs

---

api/grpc/server/server.go
runtime/container.go
runtime/container_linux.go
runtime/container_windows.go
runtime/process.go
runtime/process_linux.go
runtime/process_windows.go
runtime/runtime.go
runtime/runtime_linux.go
runtime/runtime_windows.go
runtime/spec_linux.go
runtime/spec_windows.go
specs/unsupported.go
specs/windows.go
supervisor/add_process.go
supervisor/sort_test.go

Fixes the compile of the runtime/ directory on Windows. @mlaventure @crosbymichael

runtime compiles on Windows

---

api/grpc/server/server.go
api/grpc/server/server_linux.go
api/grpc/server/server_windows.go
containerd/main.go
containerd/main_linux.go
containerd/main_windows.go
osutils/windows.go

Last PR towards compiling the daemon on Windows, but still entirely non-functional. Run make all and make dtest successfully on Linux locally.
@crosbymichael @mlaventure

Final bit of compiling on Windows

---

containerd-shim/main.go
containerd-shim/process.go
runtime/container_linux.go

Handle start errors sync with runc

---

containerd-shim/main.go
containerd-shim/process.go

Don't treat runtime error as shim error

---

Makefile
containerd/main.go
ctr/main.go
version.go

-- 
Thanks to @crosbymichael for finding the weird syntax (although in insight, it makes sense)

Add the git commit to the output version

---

api/grpc/types/api.proto

This is linked to in the readme as the API docs, but it's a bit hard to read in the GitHub web UI:

Fix spacing in api.proto

---

Makefile

This allows us to build a static binary for all three binaries, from the make file using ``make static``.
Signed-off-by: Ken Cochrane <KenCochrane@gmail.com>

Add a static build target to Makefile

---

Makefile

Add missing GIT_BRANCH variable to Makefile

---

containerd-shim/process.go
runtime/container_linux.go

Signed-off-by: Tibor Vass <tibor@docker.com>
This is a few things I missed in #146

Factor out some leftover direct references to runc binary

---

ctr/container.go
runtime/container_linux.go
supervisor/supervisor.go

Fix go vet errors

---

runtime/container_linux.go

Add prefixes to external errors

---

ctr/container.go
ctr/main.go

Fix cases where ctr wouldn't properly restore the terminal termios

---

.gitignore
ctr/container.go
ctr/main.go

Add grpc timeout

---

integration-test/start_test.go

Update busybox top to check validity of running container list

---

integration-test/start_test.go

Add test for the kill/signal operations

---

integration-test/exec_test.go

Add test for exec'ing new process in existing container

---

integration-test/start_test.go

Add test checking that non fatal signals are correctly handled

---

runtime/container_linux.go
supervisor/update.go

Return the runtime error message on failed pause and resume calls

---

integration-test/start_test.go

Add test for pause/resume commands

---

Dockerfile
Makefile

Remove govet

---

README.md

Signed-off-by: Adam Herzog <adam@docker.com>

Changed Containerd to containerd for consistency

---

archutils/epoll_aarch64.go

Use flag for aarch64 EpollCreate1

---

supervisor/supervisor.go

Truncate events log after read

---

runtime/container_linux.go

---
Should help debugging #201

Return runtime output on checkpoint operation errors

---

api/http/pprof/pprof.go

those handlers already added by init functions

api: fix pprof-address usage

---

containerd/main.go
runtime/container.go
runtime/container_linux.go
runtime/runtime.go
supervisor/create.go
supervisor/supervisor.go

Signed-off-by: mYmNeo <mymneo@163.com>

let user to specify the shim name or path

---

containerd/main.go
supervisor/supervisor.go

Truncate the event log on disk and in memory so that it does not
grow forever.  This is mainly used for higher levels to receive past
events if they miss any.
At the current setting of 500 events the log's filesize will be around 78K. 

Set fixed event log size

---

hack/vendor.sh
vendor/src/github.com/opencontainers/runc/libcontainer/README.md
vendor/src/github.com/opencontainers/runc/libcontainer/cgroups/cgroups.go
vendor/src/github.com/opencontainers/runc/libcontainer/cgroups/fs/memory.go
vendor/src/github.com/opencontainers/runc/libcontainer/cgroups/utils.go
vendor/src/github.com/opencontainers/runc/libcontainer/configs/config.go
vendor/src/github.com/opencontainers/runc/libcontainer/configs/namespaces_syscall.go
vendor/src/github.com/opencontainers/runc/libcontainer/configs/namespaces_syscall_unsupported.go
vendor/src/github.com/opencontainers/runc/libcontainer/container_linux.go
vendor/src/github.com/opencontainers/runc/libcontainer/factory_linux.go
vendor/src/github.com/opencontainers/runc/libcontainer/init_linux.go
vendor/src/github.com/opencontainers/runc/libcontainer/label/label.go
vendor/src/github.com/opencontainers/runc/libcontainer/label/label_selinux.go
vendor/src/github.com/opencontainers/runc/libcontainer/process_linux.go
vendor/src/github.com/opencontainers/runc/libcontainer/rootfs_linux.go
vendor/src/github.com/opencontainers/runc/libcontainer/seccomp/seccomp_linux.go
vendor/src/github.com/opencontainers/runc/libcontainer/setns_init_linux.go
vendor/src/github.com/opencontainers/runc/libcontainer/standard_init_linux.go
vendor/src/github.com/opencontainers/runc/libcontainer/state_linux.go
vendor/src/github.com/opencontainers/runc/libcontainer/system/linux.go
vendor/src/github.com/opencontainers/runc/libcontainer/user/user.go
vendor/src/github.com/opencontainers/runc/libcontainer/utils/utils.go

This bumps the runc dependence to
e87436998478d222be209707503c27f6f91be0c5 with fixes for cgroup updating
and hanlding of process labels.

Bump runc to e87436998478d222be209707503c27f6f91be

---

api/grpc/server/server.go

Fix including memory stats field

---

ctr/container.go

Signed-off-by: Mrunal Patel <mrunalp@gmail.com>

Add missing state command to command list

---

hack/vendor.sh
vendor/src/github.com/opencontainers/runc/libcontainer/cgroups/utils.go
vendor/src/github.com/opencontainers/runc/libcontainer/rootfs_linux.go
vendor/src/github.com/opencontainers/runc/libcontainer/selinux/selinux.go
vendor/src/github.com/opencontainers/runc/libcontainer/standard_init_linux.go

Update runc to 89c3c97a8482f3a57cd4bb683df1a7b2c61405d8

---

api/grpc/server/server.go

This fixes the issues that are visible after updating docker with the latest version.
https://github.com/docker/docker/pull/22511#issuecomment-217883025

Use state for container create

---

Makefile

Signed-off-by: thomassong <thomassong@tencent.com>

add uninstall target

---

ctr/container.go

Fix panic within ctr if the daemon dies while attached to a container

---

Dockerfile
hack/vendor.sh
vendor/src/github.com/opencontainers/runtime-spec/specs-go/config.go
vendor/src/github.com/opencontainers/runtime-spec/specs-go/state.go
vendor/src/github.com/opencontainers/runtime-spec/specs-go/version.go

Bump runc to 85873d917e86676e44ccb80719fcb47a79467

---

Dockerfile
hack/vendor.sh

It fixes issue encountered while inside a user namespace

Update runc to version cc29e3dded8e27ba8f65738f40d251c885030a28

---

containerd-shim/main.go

Make sure that if we get an error from start it is returned and that we
reap the container's process from create before existing if we were to
send a kill signal.

Return the start error and reap

---

runtime/container.go
supervisor/supervisor.go

set default shim if shim is nil for backward compatibility

---

containerd-shim/process.go
docs/attach.md
docs/bundle-changes.md

Minor fix for spelling and nits.

Refactoring minor fix

---

api/grpc/types/api.proto
ctr/checkpoint.go

cc @mlaventure 
Minor fix for wrong name/comment/ etc
Signed-off-by: Harry Zhang <harryz@hyper.sh>

Fix wrong name comment etc

---

containerd-shim/main.go
runtime/runtime_test.go
supervisor/delete.go
supervisor/exit.go
supervisor/supervisor.go
supervisor/worker.go

-- 
I introduced that bug in my previous PR :angel:

Fix shim deadlock when joining an existing pid namespace

---

version.go

Update version to 0.2.3

---

containerd/main.go

Dump runtime stacks on USR1 reception

---

Makefile
containerd/main.go
integration-test/start_test.go
runtime/container.go
runtime/process.go

Should fix docker/docker#26129

Handle sigkilled shim

---

runtime/container.go
runtime/process.go
runtime/runtime.go

--
Address docker/docker#26374

Handle shim being sigkilled while containerd is down

---

runtime/container.go

Add missing printf parameter when starttime write fails

---

runtime/process.go
runtime/runtime.go
supervisor/delete.go
supervisor/exit.go
supervisor/sort_test.go
supervisor/supervisor.go

Use uint32 as Event's Status type everywhere

---

containerd-shim/main.go

-- 
Fix support for containers joining a pre-existing PID namespace.

Notify containerd of init death before waiting for children in Shim

---

runtime/container_linux.go

Signed-off-by: allencloud <allen.sun@daocloud.io>

correct func name memeory to memory

---

containerd-shim/process_linux.go

Signed-off-by: Amit Krishnan <krish.amit@gmail.com>

fix build issues in containerd-shim/process_linux.go

---

api/grpc/server/server.go
api/grpc/server/server_linux.go
containerd-shim/process_linux.go
runtime/container.go
runtime/runtime_test.go
supervisor/add_process.go
supervisor/create.go
supervisor/worker.go

Signed-off-by: Kenfe-Mickael Laventure mickael.laventure@gmail.com
Once vendor'ed in docker, this should take care of docker/docker#27761

Honor context termination on Start and Exec

---

containerd/main.go

Signed-off-by: Wang Long <long.wanglong@huawei.com>

Remove unused function getDefaultID()

---

supervisor/supervisor.go

try to fix https://github.com/docker/docker/issues/28470

Fix exec old running container with live-restore

---

integration-test/start_linux_test.go

Add test case for exec after restore

---

runtime/container.go
runtime/process.go

-- 
Addresses docker/docker#28336

Fix orphan detection for short lived processes

---

ctr/container.go

Cleanup ctr stdio tmp directory

---

README.md

Update state of branches and slack link

---

design/snapshots.md

Fixes a couple of typos in design/snapshots.md
Signed-off-by: Federico Padua <federico_padua@yahoo.it>

Fix some typos in snapshots.md

---

design/architecture.md

architecture.md: fix typo

---

api/shim/shim.proto

Signed-off-by: Antonio Murdaca <runcom@redhat.com>

api/shim: fix indent

---

.gitignore

Signed-off-by: Antonio Murdaca <runcom@redhat.com>

.gitignore: remove unnecessary entries

---

api/shim/shim.proto

fix "make fmt" failure by switching from spaces to tabs

Indent proto files with tabs only

---

cmd/containerd/main.go
execution/service.go
snapshot/btrfs_test.go

Correct vet warnings

---

README.md

Fix a description error

---

content/content.go
content/content_test.go
content/helpers.go
content/writer.go

Signed-off-by: Gábor Lipták <gliptak@gmail.com>
https://github.com/docker/containerd/pull/398
@stevvooe

Point digest import to opencontainers/go-digest

---

cmd/ctr/run.go

ctr: set raw mode when using --tty

---

Makefile

e.g.
$ TESTFLAGS="-race -v -parallel 16" make test

Makefile: new variable: TESTFLAGS

---

vendor.conf

vendor: clean up

---

reports/JAN-13-2017.md

Let me know what you think about this format.

Add status report for Jan 13, 2017

---

snapshot/btrfs/btrfs.go
snapshot/btrfs/btrfs_test.go
snapshot/manager_test.go
snapshot/naive/naive.go
snapshot/naive/naive_test.go
snapshot/overlay/overlayfs.go
snapshot/overlay/overlayfs_test.go
snapshot/testutil/helpers.go

snapshots: separate implementations into packages

---

cmd/ctr/utils.go

Fix io closer

---

supervisor/monitor_linux.go

This deadlock occurs when the oom channel get full as a process gets
added to the Monitor. Since the channel is full the lock monitor will
never be released preventing the task trying to add a new process to
the monitor to ever complete.
--
Addresses https://github.com/docker/docker/issues/30026
@sandyskies do you think you could test this version of the fix?

Fix deadlock in monitor

---

containerd-shim/console.go

This fix https://github.com/docker/docker/issues/30156
The default terminal setting for a new pty on Linux (unix98) has +ONLCR,
resulting in '\n' writes by a container process to be converted to
'\r\n' reads by the managing process. This is quite unexpected, To fix it, make
the terminal sane after opening it by setting -ONLCR.
this patch fix method comes from: https://github.com/opencontainers/runc/commit/eea28f480db435dbef4a275de9776b9934818b8c
thanks @cyphar Aleksa Sarai <asarai@suse.de>
Signed-off-by: Wang Long <long.wanglong@huawei.com>

io: stop screwing with \n in console output

---

README.md

typo: fix typo in README.md

---

CONTRIBUTING.md
cmd/containerd-shim/console_solaris.go
cmd/containerd-shim/main.go
content/content_test.go
design/architecture.md
design/snapshots.md
execution/executors/shim/process.go
execution/service.go
gc/gc.go
rootfs/apply.go
snapshot/manager.go

Signed-off-by: Aaron.L.Xu <likexu@harmonycloud.cn>

Fix all typos I found in this repo.

---

Makefile

Fix makefile install

---

reports/2017-01-13.md
reports/2017-01-20.md

Add Development Report for Jan 20

---

bundle/bundle.go

Signed-off-by: Ma Shimiao <mashimiao.fnst@cn.fujitsu.com>

bundle: add check before Load return

---

content/content.go
content/content_test.go
content/helpers.go
content/writer.go

The package exports are now cleaned up to remove a lot of stuttering in
the API. We also remove direct mapping of refs to the filesystem, opting
for a hash-based approach. This *does* affect insertion performance,
since it requires more individual file ios. A benchmark baseline has
been added and we can fix this later.

content: cleanup package exports

---

cmd/containerd-shim/main.go
cmd/ctr/run.go

*: clean up

---

cmd/ctr/delete.go
cmd/ctr/inspect.go

Signed-off-by: Jizhong Jiang <jiangjizhong@gmail.com>
➜  ctr help delete
NAME:
ctr delete - delete a process from containerd store
USAGE:
ctr delete [command options] CONTAINER
OPTIONS:
--pid value, -p value  process id to be deleted
➜  ctr help inspect
NAME:
ctr inspect - inspect a container
USAGE:
ctr inspect CONTAINER

optimal help info for ctr cli.

---

cmd/containerd/main.go

Add some logrus info for containerd

---

design/lifecycle.md

This is still a very simple document and does not have any drawling because I'm bad at it and don't have good software to produce these.  
If anyone is confused about things let me know on the areas I need to expand on.  If you are good at drawling then we could use some help here. 
Closes #383

Add container lifecycle document

---

reports/2017-01-27.md

cc @docker/core-containerd-maintainers

reports: development report for 2017-01-27

---

MAINTAINERS

Derek McGowan will be joining as a maintainer of containerd. He will
bring his extensive experience in graphdrivers and distribution to
ensure success in this project.
Please welcome him!
cc @docker/core-containerd-maintainers 
LGTMs (need 5/7):

MAINTAINERS: add dmcgowan

---

cmd/containerd/main.go

Currently this enabled by default and  is not guarded by any compiler flag.
- Part of fix for #364 and enabling profiling data through ``ctr``.

Exposing pprof and expvars interfaces on default containerd socket

---

content/content.go

content: use buffer pool in hash copy

---

content/content.go

Signed-off-by: fate-grand-order <chenjg@harmonycloud.cn>

fix misspell "scrutiny" in content/content.go

---

cmd/containerd/main.go

closing http connection

---

cmd/containerd-shim/main.go

Remove duplicated close

---

fs/copy.go

Just fix copyFile error message.
Signed-off-by: sakeven <jc5930@sina.cn>

Fix copyFile error message

---

design/architecture.md
design/lifecycle.md
design/mounts.md
events/events_test.go
events/transaction.go

Signed-off-by: fate-grand-order <chenjg@harmonycloud.cn>

fix some typos

---

cmd/ctr/main.go
cmd/ctr/pprof.go

pprof support through ``ctr`` added

---

cmd/containerd/main.go

Allow specifying the log level. #30349
Signed-off-by: Daniel Zhang jmzwcn@gmail.com

Allow specifying the log level

---

cmd/containerd/main.go
cmd/ctr/delete.go
cmd/ctr/inspect.go
cmd/ctr/list.go
cmd/ctr/shim.go
cmd/dist/active.go
cmd/dist/fetch.go
testutil/helpers.go

Use errors.New() instead of fmt.Errorf() to output the error message
Signed-off-by: fate-grand-order <chenjg@harmonycloud.cn>

Use errors.New() directly to output the error message

---

hack/vendor.sh
vendor/src/github.com/Sirupsen/logrus/.travis.yml
vendor/src/github.com/Sirupsen/logrus/CHANGELOG.md
vendor/src/github.com/Sirupsen/logrus/README.md
vendor/src/github.com/Sirupsen/logrus/alt_exit.go
vendor/src/github.com/Sirupsen/logrus/entry.go
vendor/src/github.com/Sirupsen/logrus/formatter.go
vendor/src/github.com/Sirupsen/logrus/json_formatter.go
vendor/src/github.com/Sirupsen/logrus/logger.go
vendor/src/github.com/Sirupsen/logrus/terminal_appengine.go
vendor/src/github.com/Sirupsen/logrus/terminal_bsd.go
vendor/src/github.com/Sirupsen/logrus/terminal_linux.go
vendor/src/github.com/Sirupsen/logrus/terminal_notwindows.go
vendor/src/github.com/Sirupsen/logrus/terminal_solaris.go
vendor/src/github.com/Sirupsen/logrus/terminal_windows.go
vendor/src/github.com/Sirupsen/logrus/text_formatter.go
vendor/src/github.com/Sirupsen/logrus/writer.go

This fixes logrus terminal detection.
-- 
Fixes #466

Update logrus to v0.11.2

---

reports/2017-01-10.md

Add dev report for 2-10-2017

---

content/content.go

Signed-off-by: kevinetc123 <kaiwentan@harmonycloud.cn>

Remove redundant code

---

rootfs/apply.go

Use new snapshot interface in rootfs instead of defining its own interface.

Update rootfs to use snapshot interface

---

integration-test/check_test.go
integration-test/container_utils_test.go
integration-test/exec_test.go
supervisor/supervisor.go

--
Fix the panic reported as part of https://github.com/docker/docker/issues/30984

Create exec sync channel on restore

---

snapshot/btrfs/btrfs_test.go

After reviewing this closer, we removed a few buffers in favor
`(*exec.Command).Output` and simplified the loop file creation method to
just use `(*os.File).Truncate`.

snapshot/btrfs: simplify test setup

---

.travis.yml

travis: Use 1.7.x and 1.8.x

---

cmd/ctr/run.go

e.g.
```console
$ sudo ctr run -r ~/bundles/busybox/rootfs --runtime-config ~/bundles/busybox/config.json --id foo -t
/ # 
```

ctr: add --runtime-config

---

cmd/ctr/run.go

Ensure to read all io in error cases

---

cmd/containerd/main.go

Fix interceptor handler parameter

---

cmd/dist/fetch.go
events/transaction.go

Signed-off-by: fate-grand-order <chenjg@harmonycloud.cn>

correct misspell in cmd/dist/fetch.go and events/transaction.go

---

linux/shim.go

Close shim file when cmd.Start fail

---

README.md

Update short url scheme from http url to https (picked up by @stevvooe) from PR https://github.com/docker/containerd/pull/534#pullrequestreview-23051882
Signed-off-by: Alex Ellis <alexellis2@gmail.com>

Update short url http url to https.

---

design/snapshots.md

Mostly minor changes for readability and a few corrections to words or
word use.

Some language cleanup in snapshots design doc

---

vendor.conf
vendor/github.com/opencontainers/image-spec/README.md
vendor/github.com/opencontainers/image-spec/specs-go/v1/config.go
vendor/github.com/opencontainers/image-spec/specs-go/v1/descriptor.go
vendor/github.com/opencontainers/image-spec/specs-go/v1/image_index.go
vendor/github.com/opencontainers/image-spec/specs-go/v1/layout.go
vendor/github.com/opencontainers/image-spec/specs-go/v1/manifest.go
vendor/github.com/opencontainers/image-spec/specs-go/v1/mediatype.go
vendor/github.com/opencontainers/image-spec/specs-go/version.go
vendor/github.com/opencontainers/image-spec/specs-go/versioned.go

vendor: update oci image spec dependency

---

content/helpers.go

content: close writer after opening

---

reports/2017-02-24.md

This includes the summary from the containerd summit.

Add report for feb 24

---

rootfs/apply.go
snapshot/btrfs/btrfs.go
snapshot/btrfs/btrfs_test.go
snapshot/overlay/overlay.go
snapshot/overlay/overlay_test.go
snapshot/snapshotter.go

snapshot: Add context to Snapshotter interface

---

cmd/containerd/main.go

cmd/containerd: set correct module on interceptor for content

---

cmd/dist/common.go
cmd/dist/fetch.go
cmd/dist/main.go

cmd/dist: add global connect-timeout for GRPC

---

services/content/service.go

services/content: ignore io.EOF after successful commit

---

linux/runtime.go

Do not leak open fd to config.json in newBundle

---

cmd/dist/get.go
cmd/dist/ingest.go
content/content.go
content/helpers.go
content/store.go
content/writer.go
services/content/helpers.go
services/content/ingester.go
services/content/provider.go
services/content/service.go

services/content: move service client into package

---

cmd/dist/fetchobject.go

To make using the `fetch-object` for demonstrations much easier, the
mediatypes are defaulted when a non-digest object identifier is
provided. We also add support for OCI mediatypes, although they are
mostly unavailable.

cmd/dist: default mediatypes to oci and docker

---

cmd/ctr/run.go

Added new --runtime option for 'ctr run' to specify a user defined runtime.
Signed-off-by: Volodymyr Burenin <vburenin@gmail.com>

Added new --runtime option for 'ctr run' to specify user defined runtime.

---

cmd/containerd/builtins.go
cmd/containerd/config.go
cmd/containerd/main.go
plugin/plugin.go
snapshot/btrfs/btrfs.go
snapshot/overlay/overlay.go

Update existing snapshot drivers to register as plugins.
Load snapshot driver at containerd startup.

Add snapshot plugin type

---

docs/dockercon-summit.md

We can use this document to collect discussion points for the Dockercon containerd summit.  If you want to add a topic, submit a PR to this document. 

Add dockercon summit discussion points

---

docs/dockercon-summit.md

Add link to signup form

---

reports/2017-03-10.md

Add development report for Mar 10

---

snapshot/testsuite/testsuite.go

Testcase for multiple Prepare/View on same key.

---

content/store.go

Signed-off-by: chchliang <chen.chuanliang@zte.com.cn>

Closed stream in store.go Active()

---

containerd/main.go
supervisor/supervisor.go

Ensure state dir is created before starting server

---

cmd/containerd/builtins.go
cmd/containerd/main.go
services/metrics/metrics.go
vendor.conf
vendor/github.com/grpc-ecosystem/go-grpc-prometheus/LICENSE
vendor/github.com/grpc-ecosystem/go-grpc-prometheus/README.md
vendor/github.com/grpc-ecosystem/go-grpc-prometheus/client.go
vendor/github.com/grpc-ecosystem/go-grpc-prometheus/client_reporter.go
vendor/github.com/grpc-ecosystem/go-grpc-prometheus/server.go
vendor/github.com/grpc-ecosystem/go-grpc-prometheus/server_reporter.go
vendor/github.com/grpc-ecosystem/go-grpc-prometheus/util.go

This provideds generic grpc metrics via prometheus for all the grpc services running in containerd

Add grpc prometheus metrics

---

services/rootfs/service.go

services/rootfs: return grpc code on existence

---

reports/2017-03-17.md

Add dev report for mar 17 2017

---

reference/reference.go

Addresses https://github.com/docker/containerd/pull/612#discussion_r107039230. @samuelkarp PTAL

reference: clarify digest description

---

cmd/ctr/run.go
cmd/ctr/utils.go
cmd/dist/common.go
cmd/dist/fetch.go
cmd/dist/images.go
cmd/dist/pull.go
images/handlers.go
images/image.go
images/storage.go
remotes/handlers.go

images: move image package to images

---

reports/2017-03-24.md

Add development report for Mar 24 2017

---

docs/dockercon-summit.md

Propose discussion for image filesystem metrics.

Propose discussion of image filesystem metrics.

---

cmd/ctr/run.go

Replace 'gocontext.Background' with the var 'ctx'

---

services/images/service.go

For some reason, when I wrote this, I forgot about the `View` and
`Update` helpers on boltdb. These are now used and makes the code much
easier to follow.

services/images: simplify transaction management

---

cmd/ctr/main.go
cmd/dist/main.go

Fix dist socket parameter

---

.travis.yml
cmd/ctr/run.go
cmd/ctr/run_unix.go
cmd/ctr/run_windows.go
vendor.conf
vendor/github.com/crosbymichael/console/console_windows.go
windows/container.go
windows/hcs/hcs.go
windows/hcs/process.go
windows/hcs/shimio.go
windows/pid/pid.go
windows/process.go
windows/runtime.go

- Refactor windows runtime the code for clarity
- Implement Pty and CloseStdin for windows
- Make travis work with windows

Windows Pty and CloseStdin

---

cmd/dist/get.go

Correct the description of `dist get`.

---

vendor.conf
vendor/github.com/urfave/cli/README.md
vendor/github.com/urfave/cli/command.go
vendor/github.com/urfave/cli/errors.go
vendor/github.com/urfave/cli/help.go

relate to https://github.com/containerd/containerd/pull/723

update `urfave/cli` to 8ba6f23b6e36d03666a14bd9421f5e3efcb59aca

---

docs/dockercon-summit.md

containerd summit: suggest a discussion about disk quotas

---

cmd/dist/apply.go

cmd/dist: correct `dist apply` help

---

rootfs/apply.go

Delete the temporary diractory at the end of the function "ApplyLayer"

---

linux/runtime.go
metrics/cgroups/cgroups.go
plugin/monitor.go
vendor.conf
vendor/github.com/crosbymichael/cgroups/prometheus/metrics.go
vendor/github.com/crosbymichael/cgroups/prometheus/oom.go

Emit oom events 

---

docs/index.md

Signed-off-by: David Lyle <david.lyle@intel.com>

fix relative image paths

---

cmd/ctr/list.go

This is so I can delete all the containers I keep creating.

cmd/ctr: add quiet mode to `ctr list`

---

cmd/ctr/list.go

Add an alias for ctr list

---

snapshot/snapshotter.go

the api for these functions have since added `context.Context`
Signed-off-by: Vincent Batts <vbatts@hashbangbash.com>

snapshot: the examples need context

---

services/execution/service.go

execution: properly check container.Exec return value

---

reports/2017-04-28.md

Add dev report for april 28th

---

cmd/ctr/delete.go
cmd/ctr/exec.go
cmd/ctr/kill.go

add exec arg check first.
and some other cleanup for cmd/ctr
Signed-off-by: CuiHaozhi <cuihz@wise2c.com>

ctr exec: container id must be provided

---

reports/2017-05-05.md

Add dev report for may 5

---

cmd/ctr/delete.go

Use consistent errors package

---

reaper/reaper.go

User 'defer Unlock' to replace two 'Unlock's

---

cmd/containerd/main.go

Don't print a warning when getting a healtcheck request

---

cmd/dist/edit.go

cmd/dist: close and remove tempfile after edit

---

fs/fsutils/fsutils_linux.go
fs/fsutils/fsutils_linux_test.go
snapshot/overlay/overlay.go

From https://github.com/moby/moby/pull/27433

overlay: abort if backing fs lacks support for d_type

---

linux/shim/exec.go
linux/shim/init.go
linux/shim/io.go

Fixes #770
Use a wait group to wait for the `io.Copy` go routines to be scheduled
before continuing to start the container.

Wait for copy routines to be scheduled

---

cmd/containerd/main.go
linux/container.go
linux/runtime.go
metrics/cgroups/cgroups.go
plugin/container.go
plugin/errors.go
plugin/monitor.go
plugin/plugin.go
plugin/runtime.go
services/execution/collector.go
services/execution/service.go
windows/container.go
windows/hcs/hcs.go
windows/hcs/process.go
windows/process.go
windows/runtime.go

Also remove the `LinuxContainer` type as it is no longer used.

Move container and runtime to plugin pkg

---

snapshot/overlay/overlay.go

Rollback was not being called when the function was called with a key which does not exist. This failure to call rollback kept the database open and caused all new requests to block.

overlay: call rollback on commit error

---

cmd/containerd/main.go

With this `make vet` should pass
Signed-off-by: Daniel Dao <dqminh89@gmail.com>

remove unused import

---

reaper/reaper.go

-- 
This fixes a deadlock for cases wgere the call to `runc create` fails.

Make reaper.Monitor returns an error when exit code is not 0

---

supervisor/monitor_linux.go

add syscall.EPOLL_CLOEXEC

---

linux/runtime.go
linux/shim/init.go

linux: error out if no rootfs specified

---

linux/runtime.go

Since an error is returned via the RPC clients will assume (rightly so)
that a call to the Delete() RPC is not necessary.

Terminate linux shim on create failure

---

Makefile
api/services/execution/execution.proto
api/services/shim/shim.proto
api/types/container/container.proto
cmd/protoc-gen-gogoctrd/customnameid.go
cmd/protoc-gen-gogoctrd/main.go
snapshot/storage/proto/record.proto

Credit to Aaron Lehmann for the implementation from SwarmKit.

protos: remove need for customname on ID fields

---

README.md
RUNC.md

Add RUNC.md file for runc supported version

---

linux/shim/init.go
linux/shim/service.go

Ensure shim start & exit events are sent in right order

---

reports/2017-05-19.md

Add dev report for may 19

---

vendor.conf
vendor/github.com/Microsoft/go-winio/backup.go
vendor/github.com/Microsoft/go-winio/file.go
vendor/github.com/Microsoft/go-winio/fileinfo.go
vendor/github.com/Microsoft/go-winio/pipe.go
vendor/github.com/Microsoft/go-winio/zsyscall_windows.go

This update to go-winio includes some mandatory bug fixes for go1.8.x
Signed-off-by: Darren Stahl <darst@microsoft.com>

Update go-winio to v0.4.1

---

vendor.conf
vendor/github.com/containerd/fifo/LICENSE
vendor/github.com/containerd/fifo/fifo.go

This updates the `containerd/fifo` dependency to 69b9952.
Fixes #856

Bump fifo dependency to 69b995

---

vendor.conf
vendor/github.com/containerd/console/LICENSE
vendor/github.com/containerd/console/README.md
vendor/github.com/containerd/console/console_unix.go
vendor/github.com/containerd/console/tc_darwin.go
vendor/github.com/containerd/console/tc_freebsd.go
vendor/github.com/containerd/console/tc_linux.go
vendor/github.com/containerd/go-runc/LICENSE
vendor/github.com/containerd/go-runc/README.md
vendor/github.com/containerd/go-runc/console.go

This removes need for cgo in both of these, and updates licenses.

Update go-runc and console

---

.travis.yml

Add Darwin build support in Travis

---

linux/shim/service.go

delete the redundant func "waitExit"

---

cmd/dist/fetch.go
cmd/dist/main.go
cmd/dist/push.go
images/handlers.go

Implements image push with progress tracking.
https://asciinema.org/a/dj6ktiyt8ip9981vmq13hrqiw

Add image push to dist tool

---

reports/2017-05-26.md

Add dev report for May 26

---

cmd/containerd/main.go
cmd/containerd/main_linux.go
cmd/containerd/main_unix.go

Add SIGUSR1 to print the stack of containerd

---

cmd/ctr/pprof.go

Fix the description of cmd 'pprof threadcreate'

---

container_test.go
process.go
task.go

Add Processes() to client

---

cmd/dist/common.go

cmd/dist: remove unnecessary path manipulation

---

cmd/dist/images.go

cmd/dist: don't display undeleted images

---

cmd/dist/images.go
cmd/dist/main.go

cmd/dist: better organization and aliases for image command

---

.travis.yml
checkpoint_test.go
client.go
client_test.go
container.go
container_linux.go
container_test.go
images/image.go
linux/runtime.go
linux/shim/init.go
reaper/reaper.go
services/execution/service.go
task.go

Add checkpoint and restore to client package

---

checkpoint_test.go
client_test.go

Only run checkpoint test if criu is installed

---

cmd/containerd-shim/main_unix.go
linux/runtime.go
linux/shim.go
linux/shim/client.go
linux/shim/init.go
linux/shim/service.go

Namespace tasks via runc --root

---

metadata/buckets.go
metadata/containers.go

metadata: properly namespace containers storage

---

cmd/dist/images.go

Remove the redundant alias of 'dist images'

---

snapshot/btrfs/btrfs_test.go
snapshot/overlay/overlay_test.go
snapshot/storage/bolt.go
snapshot/storage/metastore_test.go
snapshot/testsuite/testsuite.go

Marked as WIP until we address a few other bugs.
Closes #969.

snapshot/storage: namespace snapshot drivers

---

cmd/ctr/attach.go
cmd/ctr/delete.go
cmd/ctr/main.go
container.go
task.go

Add `ctr attach` for reattaching to running task

---

rootfs/apply.go
rootfs/diff.go
services/diff/client.go

Conflicting with definition of plugin.Differ

Fix context package imports

---

reports/2017-06-09.md

Add dev report for june 9th

---

checkpoint_test.go
container_test.go

Use t.Name() for container ids in tests

---

client.go
cmd/dist/common.go
cmd/dist/push.go
cmd/dist/pushobject.go
content/content.go
content/readerat.go
content/store.go
remotes/docker/pusher.go
remotes/docker/resolver.go
remotes/docker/resolver_test.go
remotes/docker/status.go
remotes/handlers.go
remotes/resolver.go
services/content/reader.go
services/content/store.go

Add reader at interface to content store.
Updated pusher to use content writer.
Then just use the same copy method used by pull.

Update push to use copy

---

client.go
grpc.go

Adds a default namespace to the client. Intercepts client requests to add namespace to context.

Add default namespace to client

---

cmd/ctr/list.go
container.go

containerd: allow containers without an image

---

README.md

For ease of playing with the client API

README.md: add GoDoc badge

---

content/store.go

Content store writer checks expected

---

benchmark_test.go
checkpoint_test.go
client.go
container_test.go

Set image on rootfs options

---

containerd.service

Add containerd unit file

---

cmd/ctr/list.go
cmd/ctr/namespaces.go
cmd/dist/active.go
cmd/dist/images.go

cmd/{dist, ctr}: cleanup flushing and alignment

---

plugin/runtime.go

Signed-off-by: Samuel Ortiz <sameo@linux.intel.com>

plugin: Fix runtime interface documentation

---

images/image.go

images: calculate size using ChildrenHandler

---

services/content/service.go

Don't log AlreadyExists errors

---

reaper/reaper.go

Handle start process errors in reaper

---

client_unix.go
client_windows.go
cmd/containerd/config_linux.go
cmd/ctr/main.go

Add DefaultAddress to client

---

linux/task.go
services/execution/service.go

-- 
This was starting to drive me nuts :sweat_smile:

Rename variables holding a task from `c` to `t`

---

content/store.go

build conflict from #992 merge
@estesp 

Fix store errors build conflict

---

content/errors.go
metadata/errors.go

Cleanup per additional comments in PR #992.
// ping @tonistiigi

Error handler cleanup

---

containers/containers.go
metadata/buckets.go
metadata/containers.go

metadata: expand container runtime into bucket

---

namespaces/context.go
namespaces/context_test.go

Per conversation with @stevvooe this can help reduce some duplicate code in clients.

namespaces: Add NamespaceFromEnv

---

metadata/namespaces.go
namespaces/context.go
namespaces/validate.go
namespaces/validate_test.go
services/containers/helpers.go
services/images/helpers.go

namespaces: enforce a character set for namespaces

---

cmd/ctr/main.go
cmd/dist/main.go
namespaces/context.go
namespaces/context_test.go

Follow-up to https://github.com/containerd/containerd/pull/1056#pullrequestreview-45596174

namespaces: Export env var and default value

---

services/tasks/service.go

This allow returning a more meaningful message when a request context
doesn't hold a namespace.

Update execution.getTask() to provide more fine grained error

---

namespaces/validate_test.go

namespaces: ensure that tests actually fail

---

Makefile

Makefile: replace whale with D

---

linux/shim/init.go

shim: Use correct error when trying to expand runc error

---

task.go

Simplify task.Wait() a bit

---

client_test.go
cmd/containerd/config.go
cmd/containerd/config_linux.go
cmd/containerd/config_unix.go
cmd/containerd/config_windows.go
cmd/containerd/main.go
cmd/containerd/main_linux.go
cmd/containerd/main_unix.go
cmd/containerd/main_windows.go
plugin/context.go
server/config.go
server/server.go
server/server_linux.go
server/server_unsupported.go

This is so you can embed the containerd daemon into other Go programs.
ping @ibuildthecloud 

Create server package for containerd daemon

---

cmd/ctr/list.go
container.go
container_test.go
linux/shim/exec.go
linux/shim/init.go
linux/shim/service.go
plugin/errors.go
task.go

This returns a typed error for calls to Kill when the process has
already finished.
Fixes #999

Fix error on double Kill calls

---

cmd/ctr/list.go

[ctr] fix tasks service reference

---

benchmark_test.go
checkpoint_test.go
container.go
container_test.go

Add DeleteOpts for container deletion

---

events/convert_test.go

Other: How do you know these event conversions work?
Steve: Well, they've been tested and benchmarked, of course!
Other: Where are the tests?
Steve: It's easy, just check out the branch you want to test on my
machine and the tests are right there. So easy!
Other: `<facepalm>`

events: add conversion tests

---

cmd/containerd-shim/main_unix.go
cmd/containerd-shim/shim_linux.go
cmd/containerd-shim/shim_unix.go
cmd/containerd/main.go
cmd/ctr/run.go
cmd/ctr/shim.go
cmd/ctr/snapshot.go
events/sink.go
linux/bundle.go
linux/runtime.go
linux/shim/client.go
linux/shim/service.go
server/server.go

@crosbymichael I was thinking about something like this.
WDYT?

containerd-shim: Use abstract namespace for shim socket

---

reports/2017-06-23.md

Dev report for changes from last week and summit notes

Add dev report for June 23, 2017

---

client.go

Add NewWithGRPCOpts to specify grpc dial opts

---

cmd/ctr/delete.go

Fix the behavior of removing snapshot on container delete.
Adds a flag to keep the snapshot if desired.

Fix ctr delete to remove snapshot

---

filters/filter_test.go
filters/parser.go

filters: handle presence syntax correctly

---

image.go

image.go: fix duplicated import

---

Makefile

Makefile: fix INTEGRATION_PACKAGE

---

errdefs/grpc_test.go

errdefs: add tests error conversions

---

fs/du_unix.go

fs: fix hardlinks detection on usage calc

---

api/services/containers/v1/containers.proto

quick typo fix in proto comment

fixes typo in proto comment

---

server/server.go

Rename ctx module execuiton->tasks

---

metadata/containers.go
metadata/images.go

metadata: preserve createdat on update

---

archive/tar.go

archive: fix allocation leak

---

.travis.yml
cmd/ctr/run_windows.go
spec_unix.go
spec_windows.go
vendor.conf
vendor/github.com/opencontainers/runtime-spec/specs-go/config.go
vendor/github.com/opencontainers/runtime-spec/specs-go/version.go

This should be the same commit tagged as the 1.0 release

Update runtime-spec rc6

---

.travis.yml
cmd/ctr/run_windows.go
container.go
container_test.go
io.go
io_unix.go
io_windows.go
process.go
spec_unix.go
spec_windows.go
task.go
vendor.conf
vendor/github.com/opencontainers/runtime-spec/specs-go/config.go
vendor/github.com/opencontainers/runtime-spec/specs-go/version.go

Fixes #1162
Fixes #1161
This is based on the rc6 update PR

Fix process and task io Wait hang when fails to start

---

snapshot/btrfs/btrfs.go

We may want to create this as a subvolume if the parent is btrfs
or support mounting on load in the future.
Ping @cyphar, if you have any thoughts,  right now it is assuming the parent is btrfs but we can create a follow up to do something better here.

Create btrfs directory if it does not exist

---

.travis.yml
vendor.conf
vendor/github.com/containerd/cgroups/memory.go
vendor/github.com/opencontainers/runtime-spec/README.md
vendor/github.com/opencontainers/runtime-spec/specs-go/config.go
vendor/github.com/opencontainers/runtime-spec/specs-go/state.go
vendor/github.com/opencontainers/runtime-spec/specs-go/version.go

Update runtime spec to 96de01bbb42c7af89bff100e10a

---

client.go
cmd/ctr/info.go
cmd/ctr/list.go
container.go
container_unix.go
containerstore.go
spec_unix.go
spec_windows.go
task.go

containerd: remove GRPC service export

---

version/version.go

containerd: prepare for v1.0.0-alpha0

---

cmd/ctr/fetch.go

comment: dist -> ctr

---

cmd/ctr/list.go

cmd/ctr: container list should not look up image

---

cmd/containerd/main.go

cmd/containerd: show version and revision on startup

---

README.md

README: add go report card badge

---

cmd/ctr/snapshot.go

~This changeset adds `-t` flag to `ctr snapshot ls` and prints the snapshots
with their branches in tree view.~
Signed-off-by: Sunny Gogoi <me@darkowlzz.space>
Part of #1082 
```
$ sudo ctr snapshot ls -t
\_ sha256:cb11ba6054003d39da5c681006ea346e04fb3444086331176bf57255f149c670
\_ sha256:1118f33a0ee7a874a04318248a886b2bdaf44cba286644ab7ded870aefe64b62
\_ manualsnapshot1
\_ sha256:11a2a269cf6ec2cefcb4e24370b8b2d7a4875450bafd3a70bd42eb787481d798
\_ sha256:80e85c818fa0447c96a42501ca7457ad83e5834aa76f22c366342106889b7411
\_ sha256:dd864b96a38e849779c42a04159bbb39c7ab47253bf222049b471d8f26b60d14
\_ sha256:3a1dff9afffd3eeb8a202017ed4fe2bf197a8e6703947aafe7c252f34988326d
\_ manualsnapshot2
\_ manualsnapshot3
\_ sha256:5bef08742407efd622d243692b79ba0055383bbce12900324f75e56f589aedb0
```

cmd/ctr: add tree subcommand in snapshot

---

linux/shim/service.go
runtime/events.go
services/tasks/service.go

This also remove the duplicate events for Task{Create,Start,Delete}

Update linux events topic

---

filters/parser.go
images/handlers.go
remotes/docker/schema1/converter.go
snapshot/snapshotter.go

Signed-off-by: Helen <chenjg@harmonycloud.cn>

correct some misspellings to make Go Report more happy

---

BUILDING.md

Signed-off-by: Jovi Zhangwei <zw.xianwei@alibaba-inc.com>

Claim Go 1.8.x version requirement in BUILDING.md

---

cmd/ctr/snapshot.go

This changeset:
- adds `mount` subcommand to `ctr snapshot`
- adds `snapshot-name` flag for specifying target snapshot name in both `mount` and `prepare` snapshot subcommands
Signed-off-by: Sunny Gogoi <me@darkowlzz.space>
Part of #1082

cmd/ctr: add mount subcommand to snapshot

---

Makefile

Makefile: add release target

---

version/version.go

containerd: prepare for v1.0.0-alpha1

---

Protobuild.toml

Signed-off-by: He Xiaoxi <tossmilestone@gmail.com>

Fix typo error in Protobuild.toml

---

typeurl/types.go
typeurl/types_test.go

Panic on typeurl registration when you register the same type but
different urls for that type.

Panic when registering the same type but diff urls

---

runtime/process.go

fix #1222
kill(0) seems useless here because we have already waited shim to exit
through `<-p.cmdDoneCh` in following steps.
Signed-off-by: Yuanhong Peng <pengyuanhong@huawei.com>

Remove kill(0) in `handleSigkilledShim()`

---

cmd/ctr/delete.go
cmd/ctr/main.go

cmd/ctr: allow deleting multiple containers at once

---

cmd/containerd-shim/main_unix.go
linux/bundle.go
linux/runtime.go
linux/shim/client.go
linux/shim/service.go

event forwarding without shim

---

cmd/containerd-shim/main_unix.go
linux/shim/client.go
linux/shim/local.go
linux/shim/service.go

linux/shim: use events.Publisher interface

---

integration-test/exec_test.go

This test that we don't panic if a container init process shim is
SiGKILL'ed while having an exec attach to that container.

Add a test for #872

---

vendor.conf
vendor/github.com/opencontainers/image-spec/specs-go/v1/config.go
vendor/github.com/opencontainers/image-spec/specs-go/version.go

vendor: update OCI image-spec dependency

---

linux/shim/init.go
linux/task.go

Shutdown console after process exits

---

version/version.go

release: prepare for 1.0.0-alpha3

---

cmd/ctr/fetch.go

ctr: dismiss progressbar on --debug

---

client.go
container.go
container_unix.go
image.go
io.go
process.go
spec_unix.go
task.go

Update godoc for client package

---

.appveyor.yml
.travis.yml
cmd/ctr/utils.go
container_test.go
progress/bar.go
remotes/docker/schema1/converter.go
snapshot/overlay/overlay_test.go

Partially fix #578
Lint is the big one (well, it's mostly a matter of documentation missing, which we can tackle once we're out of alpha).

Enable ineffassign in CI

---

README.md
docs/getting-started.md

Add getting started guide

---

vendor.conf
vendor/github.com/opencontainers/runc/libcontainer/nsenter/nsexec.c
vendor/github.com/opencontainers/runc/libcontainer/user/lookup.go
vendor/github.com/opencontainers/runc/libcontainer/user/lookup_unix.go
vendor/github.com/opencontainers/runc/libcontainer/user/lookup_unsupported.go
vendor/github.com/opencontainers/runc/libcontainer/user/user.go

-- 
I was going to wait for rc4, but the freeze period for docker is fast approaching.

Update runc to d40db12e72a40109dfcf28539f5ee0930d2f0277

---

container_test.go
spec_opts.go
spec_opts_unix.go

Add cgroup paths and hostname spec opts

---

docs/client-opts.md

Add doc for extending client opts

---

spec_unix.go

Use lchown when remapping rootfs

---

api/README.md

Minor typo found during reviewing code.

Minor typo fix.

---

cmd/ctr/snapshot.go

The argument order, naming and behavior of the snapshots command didn't
really follow any of the design constraints or conventions of the
`Snapshotter` interface. This brings the command into line with that
interface definition.
The `snapshot archive` command has been removed as it requires more
thought on design to correctly emit diffs.
Closes  #1317

cmd/snapshot: follow conventions from Snapshotter

---

docs/namespaces.md

This documents namespaces as it pertains to clients and multi-tenancy. 

Add namespace doc for containerd

---

docs/namespaces.md

Add info on labels. Some wording updates.

Minor updates to the namespaces doc

---

version/version.go

release: prepare for 1.0.0-alpha4

---

README.md
RELEASES.md

Define the release process for containerd and outline the components
that are and are not covered by versioning guarantees. Please read the
document for details.

RELEASES: define the release process

---

container.go
io.go
process.go
task.go

Sent this out for discussion. @crosbymichael @mlaventure 

Change IO to interface.

---

Makefile
cmd/containerd-stress/main.go

stress -> containerd-stress

---

cmd/ctr/snapshot.go

Would be useful for https://github.com/containerd/containerd/issues/1368

ctr: add `ctr snapshot view`

---

version/version.go

release: prepare for 1.0.0-alpha5

---

spec_opts_unix.go

client: Resoveconf -> Resolvconf

---

vendor.conf
vendor/github.com/containerd/cgroups/net_cls.go
vendor/github.com/containerd/cgroups/paths.go
vendor/github.com/containerd/cgroups/utils.go

This bumps the cgroups package with various fixes to logging and net_cls
changes.

Update cgroups to e6d1aa8c71c6103624b2c6e6f4be0863

---

errdefs/grpc.go

errdefs: Provide a valid stack in all cases

---

content/local/writer.go

Make close a no-op after commit and disallow committing after close.

Ensure content writer only unlocks resource once

---

cmd/ctr/task_delete.go
container_test.go
process.go
task.go

go-client: Return an ExitStatus struct when calling process.Delete()

---

version/version.go

Preparation for alpha6 release

release: updated version to alpha6

---

spec_opts_unix.go

This PR:
1) Addresses a comment in https://github.com/containerd/containerd/pull/1425. I don't know why I forgot to push my local change, sorry...
2) Change `WithUserID` not to return error if `/etc/passwd` does not exist, because there are many images from scratch which don't have that.

WithUserID should not return error when /etc/passwd doesn't exist.

---

README.md
RELEASES.md

Add security mailing list to readme and releases

---

cmd/ctr/run_unix.go

ctr: net-host: bind-mount host /etc/{hosts,resolv.conf}

---

cmd/ctr/exec.go

Wait on exec process not task

---

client.go
events/events.go

containerd: export Subscribe method on client

---

services/containers/service.go

service/containers: correctly plumb fieldpaths

---

snapshot/snapshotter.go

snapshot: use switch to parse snapshot.Kind

---

vendor.conf
vendor/github.com/containerd/go-runc/runc.go

This fixes an issue with Exec not returning a proper error

Update go-runc to b3c048c028ddd789c6f9510c597f8b9c62f25359

---

rootfs/init.go
rootfs/init_linux.go
rootfs/init_other.go

This reverts commit 4e2337794c2624278f1e7fa83c456fbc5b48fee5.

Revert "rootfs: remove unused functions"

---

rootfs/apply.go

Prevent unpack failures due to id collision or the need to wait for another process to finish unpacking. Always attempt to unpack a layer and handle collisions on commit. Commit collisions are easily handled as it could be considered the same as a successful unpack.
Fixes #1041 
Fixes #1240
Replaces #1432

Support simultaneous unpacking of same layer

---

docs/getting-started.md

[carry] Improve getting started guide

---

differ/differ.go

ref: https://github.com/moby/buildkit/pull/116/files#r137484219

differ: expose newWalkingDiff() for standalone buildkit

---

snapshot/testsuite/testsuite.go

Movement of files/folder from base layer to folder in
new layer should be allowed

Testcase added for Moving files in snapshot layers

---

.travis.yml
RUNC.md
vendor.conf
vendor/github.com/opencontainers/runc/libcontainer/nsenter/nsexec.c
vendor/github.com/opencontainers/runc/libcontainer/user/lookup.go
vendor/github.com/opencontainers/runc/libcontainer/user/lookup_unix.go
vendor/github.com/opencontainers/runc/libcontainer/user/lookup_unsupported.go
vendor/github.com/opencontainers/runc/libcontainer/user/user.go
vendor/github.com/opencontainers/runc/vendor.conf

This bumps runc to the newest version as of this date.

Update runc to 593914b8bd5448a93f7c3e4902a03408b6d

---

cmd/ctr/images.go
cmd/ctr/pull.go
images/handlers.go
images/image.go

cmd/ctr: show resolved image platform

---

server/config.go

Cann't use the new created config in server.LoadConfig When arg v is nil
fix #1483

Improve server.LoadConfig function

---

.travis.yml

Remove solaris from travis

---

README.md
RELEASES.md

Update security reporting text

---

contrib/README.md

Add readme to contib

---

RELEASES.md

RELEASES: update component table

---

remotes/docker/fetcher.go

Signed-off-by: Allen Sun <shlallen1990@gmail.com>

add a response body close

---

cmd/ctr/container_delete.go
cmd/ctr/content.go
cmd/ctr/export.go
cmd/ctr/images.go
cmd/ctr/import.go
cmd/ctr/labels.go
cmd/ctr/namespaces.go
cmd/ctr/pprof.go
cmd/ctr/push.go
cmd/ctr/pushobject.go
cmd/ctr/rootfs.go
cmd/ctr/run_unix.go
cmd/ctr/snapshot.go
cmd/ctr/utils.go

When I try to use ctr to utilize containerd, 
I found there is a little bit improvement I could do to make display consistent.
Signed-off-by: Allen Sun <shlallen1990@gmail.com>

make command help display consistent

---

api/services/containers/v1/containers.pb.go
api/services/containers/v1/containers.proto
api/services/content/v1/content.pb.go
api/services/content/v1/content.proto
api/services/images/v1/images.pb.go
api/services/images/v1/images.proto
api/services/namespaces/v1/namespace.pb.go
api/services/namespaces/v1/namespace.proto
api/services/snapshot/v1/snapshots.pb.go
api/services/snapshot/v1/snapshots.proto
cmd/ctr/images.go
labels/validate.go
labels/validate_test.go
metadata/containers.go
metadata/content.go
metadata/images.go
metadata/namespaces.go
metadata/snapshot.go
services/content/service.go

* Label key and value max size is 4096 bytes
Addresses #1513. Feedback is request on how to test this. Thanks! @mlaventure @stevvooe @crosbymichael @dmcgowan 

Labels are consistently validated across services.

---

design/architecture.md

design: remove distribution GRPC service

---

.travis.yml
version/version.go

release: prepare 1.0.0-beta.1

---

design/architecture.md
design/lifecycle.md
remotes/handlers.go
server/server_linux.go
server/server_solaris.go
server/server_unsupported.go

When I read the docs about containerd, I found that some nit via reading or IDE.
So I update docs and comments.
Signed-off-by: Allen Sun <shlallen1990@gmail.com>

update docs and comments

---

client.go

client: Allow specifying filters when listing images

---

CONTRIBUTING.md

This is a priority that tests are added for regressions and new
functionality.

State adding tests when submitting changes

---

dialer.go
dialer_unix.go

Move unix specific tidbits into dialer_unix.go

---

container_test.go
task.go

client: Prevent Out-Of-Range panic in task.Metrics()

---

client.go
client_opts.go
cmd/ctr/fetch.go
cmd/ctr/import.go
cmd/ctr/pull.go
cmd/ctr/utils.go
import.go

client: Allow setting image labels on Pull()

---

archive/tar.go
archive/tar_test.go
cmd/containerd-shim/shim_linux.go
cmd/ctr/namespaces.go
cmd/ctr/ps.go
containers/containers.go
content/content.go
content/helpers.go
content/local/store.go
errdefs/errors.go
errdefs/grpc.go
events/events.go
events/exchange.go
filters/adaptor.go
filters/filter.go
filters/filter_test.go
filters/scanner.go
fs/du.go
fs/fstest/file.go
fs/fstest/file_unix.go
fs/fstest/testsuite.go
fs/hardlink.go

Continuing work on making the code base go lint approved. 

Update files based on go lint

---

linux/bundle.go

Thanks for tell me if the fix is properly

Remove a blank line

---

images/handlers.go
images/image.go

images: provide separated children function for images

---

container.go
container_linux_test.go
container_opts.go
container_test.go

This adds an update method to the container interface for the client
package.
cc @Random-Liu @mikebrow 

Add container update method

---

images/image.go
metadata/images.go
metadata/images_test.go

metadata: validation and testing of image store

---

cmd/ctr/images.go
images/image.go

The `Check` function returns information about an image's content components
over a content provider. From this information, one can tell which content is
required, present or missing to run an image.
The utility can be demonstrated with the `check` command:
```console
$ ctr images check
REF                               TYPE                                                      DIGEST                                                                  STATUS            SIZE
docker.io/library/alpine:latest   application/vnd.docker.distribution.manifest.list.v2+json sha256:f006ecbb824d87947d0b51ab8488634bf69fe4094959d935c0c103f4820a417d incomplete (1/2)  1.5 KiB/1.9 MiB
docker.io/library/postgres:latest application/vnd.docker.distribution.manifest.v2+json …
```

images: support checking status of image content

---

cmd/ctr/run.go
cmd/ctr/run_unix.go
cmd/ctr/run_windows.go
spec_opts.go

ctr run: add --cwd

---

metadata/db.go
metadata/migrations.go

Add documentation and explanation for migrations.
Addresses documentation feedback from #1582

Add documentation for metadata database

---

metrics/cgroups/cgroups.go
metrics/cgroups/metrics.go

metrics/cgroups: handle error on call to cgroup

---

container.go
io.go

Add docs around multiple attach

---

mount/lookup_test/lookup_linux_test.go
mount/lookup_unix.go

I execute the mount comment like: 
```bash
$ mount --bind /tmp /tmp
```
Then look up the mount info through `mount.Lookiup("/tmp")`,  and get the result like:
```
65 0 253:0 / / rw,relatime shared:1 - xfs /dev/mapper/cl-root rw,seclabel,attr2,inode64,noquota
```
But I expect getting the mount info like:
```
124 65 253:0 /tmp /tmp rw,relatime shared:1 - xfs /dev/mapper/cl-root rw,seclabel,attr2,inode64,noquota
```
This PR ensure getting the correct mountinfo corresponds to path.
/cc @Random-Liu

Fixes looking up mountinfo corresponds to path

---

cmd/containerd-release/main.go
releases/v1.0.0-beta.2.toml
version/version.go

release: prepare 1.0.0-beta.2

---

BUILDING.md
README.md
docs/getting-started.md

Update docs with go 1.9 requirement.

---

snapshot/snapshotter.go

containerd/snapshot/snapshotter.go

a typo in comment of Snapshotter.Update

---

cmd/ctr/snapshot.go
metadata/db.go

Ensures that all callers and the garbage collector are using the same lock instances to prevent cleanup of objects during creation.
Locks tend to work better when everything is using the same lock. This was missed during a refactor of the gc code before merge. This should fix the snapshot does not exist test failures.
Also added snapshot label command which I needed to debug.

gc: fix race and test failures

---

progress/writer.go

When we try to pull an image with "ctr pull xxx", the progress bar
display will flush all the screen and make it so hard to find useful
information for user.
This commit fixes bugs for the progress bar, by correcting "line counting"
algorithm. Previous algorithm only counts number of "\n", but one line
can be longer than screen width, in which case it should be counted as
two lines. Also updated the screen cleaning ESC chars.
Signed-off-by: Zhang Wei <zhangwei555@huawei.com>

[progress] Fix wrong display of progress bar

---

cmd/containerd-release/build.go
cmd/containerd-release/main.go
cmd/containerd-release/template.go
cmd/containerd-release/util.go

This allows the build to to build the release binaries and hash the resulting tar and include the hash in the release notes. 

refactor release tool

---

container_linux_test.go

tests: skip user namespace tests in kernels which have it disabled

---

task.go

Reverse checkpoint url

---

README.md
RELEASES.md

README, RELEASES: update security email

---

io_unix.go

Signed-off-by: Tao Qingyun <845767657@qq.com>

move the fifo locations /run/containerd

---

container_linux_test.go
container_test.go

Add additional container test for missing methods

---

client.go
cmd/containerd/main.go
linux/bundle.go
metadata/content.go
plugin/context.go
runtime/task.go
runtime/task_list.go
server/config.go
services/containers/service.go
services/content/service.go
services/events/service.go
services/healthcheck/service.go
services/images/service.go
services/introspection/service.go
services/namespaces/service.go
services/tasks/service.go
services/version/service.go
snapshot/btrfs/btrfs.go
snapshot/btrfs/btrfs_test.go
snapshot/overlay/overlay.go
snapshot/storage/bolt.go
task.go
testutil/loopback_linux.go
windows/hcsshimtypes/doc.go

After these changes we only have <30 lint issues remaining.

Fix more lint issues across services

---

BUILDING.md

Add more detail on how to test containerd with `Makefile` targets,
`containerd-stress`, and external projects like `bucketbench`.

Add testing information to BUILDING.md

---

client.go
cmd/ctr/content.go
cmd/ctr/events.go
cmd/ctr/namespaces.go
cmd/ctr/pushobject.go
cmd/ctr/snapshot.go
cmd/ctr/utils.go
cmd/ctr/utils_unix.go
cmd/ctr/utils_windows.go

Signed-off-by: Tao Qingyun <845767657@qq.com>

ctr use client's underlying service

---

cmd/ctr/attach.go
cmd/ctr/checkpoint.go
cmd/ctr/container_delete.go
cmd/ctr/containers.go
cmd/ctr/content.go
cmd/ctr/events.go
cmd/ctr/exec.go
cmd/ctr/export.go
cmd/ctr/fetch.go
cmd/ctr/images.go
cmd/ctr/import.go
cmd/ctr/info.go
cmd/ctr/kill.go
cmd/ctr/labels.go
cmd/ctr/namespaces.go
cmd/ctr/pause.go
cmd/ctr/plugins.go
cmd/ctr/ps.go
cmd/ctr/pull.go
cmd/ctr/push.go
cmd/ctr/pushobject.go
cmd/ctr/resume.go
cmd/ctr/rootfs.go
cmd/ctr/run.go
cmd/ctr/snapshot.go
cmd/ctr/start.go
cmd/ctr/task.go
cmd/ctr/task_delete.go
cmd/ctr/utils.go
cmd/ctr/version.go

[ctr] streamline new client creation

---

vendor.conf
vendor/github.com/urfave/cli/README.md
vendor/github.com/urfave/cli/app.go
vendor/github.com/urfave/cli/cli.go
vendor/github.com/urfave/cli/command.go
vendor/github.com/urfave/cli/context.go
vendor/github.com/urfave/cli/flag.go
vendor/github.com/urfave/cli/funcs.go
vendor/github.com/urfave/cli/help.go

Update cli to 7bc6a0acffa589f415f88aca16cc1de5ffd6

---

cmd/ctr/run_unix.go
cmd/ctr/run_windows.go

ctr: error if tty && nullIO

---

cmd/containerd-release/build.go
cmd/containerd-release/main.go
cmd/containerd-release/template.go
releases/v1.0.0-beta.2.toml

@crosbymichael PTAL
Signed-off-by: Antonio Murdaca <runcom@redhat.com>

cmd: containerd-release: abstract it out to create a new project

---

.travis.yml
Makefile
Makefile.darwin
Makefile.freebsd
Makefile.linux
Makefile.windows
gc/gc.go
metadata/db.go

Add buildmode=pie to makefile

---

docs/getting-started.md

I adjust the log to the sample in getting started.
Signed-off-by: bando-shintaro <bando142141@gmail.com>

Fix docs, log output in getting started

---

spec_opts_unix.go

Remapped snapshots are not currently referenced by any root allowing clean up of the snapshot. Check for not found on prepare to account for cleanup after stat.
Reference #1730

Fix not found caused by race to remove snapshot

---

releases/v1.0.0-beta.3.toml
version/version.go

Please add commits to this PR with notes for features.

release: prepare 1.0.0-beta.3

---

linux/shim/exec.go

containerd-shim: Delete exec pidfile on exit

---

progress/writer.go

Two issues with a prior PR for handling line-spanning progress bars are
fixed in this PR:
- corner case where output line length is exactly == term width: extra line was being
added
- line length calculation was including escape characters causing
calculations to span lines when output was still only on one line

Handle progress line length properly for formatting

---

Makefile
content/local/store_test.go

Reduce runtime from 170s to 3s (on my desktop)

Reduce number of blobs in TestWalkBlobs

---

cmd/ctr/commands/snapshot/snapshot.go

ctr: fix args

---

.travis.yml
README.md

README, travis: update protobuf compiler version

---

metadata/containers.go
metadata/leases.go
metadata/snapshot.go
remotes/docker/pusher.go

Fix some error messages where they were wrong or redundant.

Normalize 'already exists' errors

---

.appveyor.yml
.travis.yml
content/testsuite/testsuite.go
fs/diff_test.go
fs/diff_windows.go
metadata/snapshot_test.go
platforms/platforms_test.go
snapshot/naive/naive_test.go

Re-enable unit tests on appveyor

---

RELEASES.md

Add plugin stability guarantees to release.md

---

metadata/gc_test.go

Resurrects the `addContainer` function and uses it to test containers are gc roots from the scanner function.

metadata: add test for container as gc root

---

cmd/ctr/commands/events/events.go

Fixes #1804
Add import to register event types with grpc

Fix ctr events

---

metrics/cgroups/cgroups.go

Possible fix for https://github.com/moby/moby/issues/35587, although I'm not that familiar with it. Maybe if this feature is not available the monitor should just warn and continue to monitor other things.

Warn if OOM monitoring is not available instead of error

---

cmd/containerd-stress/main.go

Fix race in stress test tool

---

client.go
lease.go
task.go

@dmcgowan @crosbymichael @stevvooe @Random-Liu 
Can we provide withLease() to the user for using? 
We need to import image from tar in cri-containerd. so we need it.
ref https://github.com/containerd/containerd/pull/1690#discussion_r152505174

provide client.WithLease to user

---

image.go

This breaks the build.
/cc @dmcgowan Fix the build.

Fix build.

---

cmd/containerd/config_unsupported.go
cmd/containerd/config_windows.go
defaults/defaults_unix.go
defaults/defaults_windows.go
defaults/doc.go
server/server_solaris.go
server/server_unsupported.go
server/server_windows.go

Use defaults pkg for all platforms

---

cmd/ctr/commands/commands.go

ctr: add EnvVar `CONTAINERD_SNAPSHOTTER` for `--snapshotter`

---

events/events.go

events: define fieldpath implement for envelope

---

cmd/containerd-stress/main.go

Fix stress test tool exec kill

---

vendor.conf
vendor/github.com/stevvooe/ttrpc/README.md
vendor/github.com/stevvooe/ttrpc/channel.go
vendor/github.com/stevvooe/ttrpc/client.go
vendor/github.com/stevvooe/ttrpc/server.go

vendor: update ttrpc with latest changes

---

README.md

Add details on kernel version, criu, snapshotters, and links to existing
sections for developers/criu details.

Add runtime requirements section to README

---

releases/v1.0.0-rc.0.toml

Please add release notes to branch or request a section to be added

Add release notes for v1.0.0-rc.0

---

releases/v1.0.0-rc.0.toml

Update previous version to beta not current rc

---

version/version.go

Prepare release v1.0.0-rc.0

---

cmd/containerd-shim/main_unix.go
cmd/containerd-shim/shim_darwin.go
cmd/containerd-shim/shim_unix.go
vendor.conf
vendor/github.com/stevvooe/ttrpc/config.go
vendor/github.com/stevvooe/ttrpc/handshake.go
vendor/github.com/stevvooe/ttrpc/server.go
vendor/github.com/stevvooe/ttrpc/unixcreds.go

cmd/containerd-shim: require unix socket credentials

---

containerd.service

Add rlimits to service file

---

metadata/containers.go

Part of an effort to make error messages consistent and as helpful as possible. Very open to any suggestions!!

metadata: update container error messages

---

snapshots/overlay/overlay.go
snapshots/storage/bolt.go

Signed-off-by: yason <yan.xuean@zte.com.cn>
use defer

snapshots/overlay: cleanup rollback code for overlay.prepare

---

vendor.conf
vendor/github.com/stevvooe/ttrpc/unixcreds_linux.go

vendor: update ttrpc to pull in euid change

---

cmd/ctr/commands/content/content.go

cmd/ctr: move log messages to debug

---

cmd/containerd-stress/main.go
linux/bundle.go
linux/runtime.go
linux/shim/client/client.go
linux/shim/client/client_linux.go
linux/shim/client/client_unix.go
oci/spec_opts_windows.go

Remove mount namespace from shim

---

metadata/db.go
metadata/gc.go
metadata/snapshot.go
services/content/service.go
services/images/service.go
services/snapshots/service.go
snapshots/btrfs/btrfs.go
snapshots/naive/naive.go
snapshots/overlay/overlay.go

Make the tense and casing consistent. Add useful log messages in image service.

Update snapshot and content related log messages

---

container_opts_unix.go
diff/walking/differ.go
linux/runtime.go
linux/shim/local.go
mount/mount_linux.go
oci/spec_opts_unix.go

This is another WIP to fix #1785.

Retry unmount on EBUSY and return errors

---

README.md
docs/getting-started.md

docs: fix usage of cio package in docs

---

snapshots/overlay/overlay.go
snapshots/storage/bolt.go

Signed-off-by: yason <yan.xuean@zte.com.cn>
1. fix a small bug. But it don't affect us, because we don't use it.
2. improve error message for CommitActive
3. slove comment https://github.com/containerd/containerd/pull/1854#discussion_r154387443
Closes #1851

get wrong parents bucket in withSnapshotBucket

---

snapshots/storage/bolt.go

Update snapshot storage error message

---

client.go

Adds a more descriptive error message for pushing indexes/manifest list
references with missing content references to a docker v2 API supporting
container registry. This can be followed up with a more complete review
of how to handle "deep" references for manifest lists on push/pull post
containerd 1.0.
Reference: #1772

Add more descriptive error on manifest list push

---

BUILDING.md
README.md

Partly addresses #1819
- makes BUILDING.md the developer quick start
- organizes BUILDING.md

docs: update BUILDING and README

---

RELEASES.md
cmd/containerd-release/template.go
releases/v1.0.0.toml
version/version.go

release: prepare 1.0.0

---

api/1.0.pb.txt
linux/runctypes/1.0.pb.txt
windows/hcsshimtypes/1.0.pb.txt

api: lock down 1.0 API descriptors

---

linux/shim/client/client.go

Remove panic from newCommand

---

RELEASES.md

Fix typo in release link

---

server/server_linux.go

server: only warn on failed OOM score adjust

---

cmd/containerd/main.go

Cherrypick #1907 into containerd 1.0.

[Cherrypick] Fix containerd deadlock.

---

cmd/ctr/commands/snapshots/snapshots.go

Preserves the order of the tree output between each execution. Slightly
refactored the behavior to be more "object oriented".

cmd/ctr: stablize output of snapshot tree

---

cmd/containerd-stress/main.go
cmd/containerd-stress/size.go
cmd/containerd-stress/worker.go

Add binary sizes to stress test metrics

---

cmd/containerd-stress/main.go

Fix gauge constant

---

archive/tar.go
archive/tar_test.go

Fix parent directories not included in tar

---

Makefile

This PR adds the `go build` option `-i` that installs the packages that are dependencies of the target (to speed up future builds).
This was removed in #1179 because it caused problems when cross-compiling, when the install was being done on the incorrect (not native) path (this [comment](https://github.com/containerd/containerd/issues/1905#issuecomment-352911114) gives a clear example).
The [`GOHOSTOS`](https://golang.org/doc/install/source#environment) environment variable was added to the Makefile to detect when the build was being done against the native platform, and only then add the `-i` option.
Also the `GO_BUILD_FLAGS` variable was added to encapsulate this option (and possible future ones), instead of just hard coding it into the `go build` command. According to the [`go …

Add go build option '-i' only for native builds

---

linux/shim/service.go
linux/task.go

Check that process exists before it is returned

---

cmd/ctr/commands/snapshots/snapshots.go

Adds `ctr snapshots diff`
Two options for usage:
1. provide two snapshot ids to be diff'd
2. provide a single snapshot id, and it will be diff'd against its parent
```
ctr snapshots tree
\_ sha256:04a094fe844e055828cb2d64ead6bd3eb4257e7c7b5d1e2af0da89fa20472cf4
\_ test
ctr snapshots diff sha256:04a094fe844e055828cb2d64ead6bd3eb4257e7c7b5d1e2af0da89fa20472cf4 test | tar -tz
root/.ash_history
test/
test/test/
ctr snapshots diff test | tar -tz
root/.ash_history
test/
test/test/
```
Addresses #1919

ctr: snapshots diff command

---

rootfs/diff.go

[cherry-pick] rootfs: remove upper snapshot after use

---

ROADMAP.md

This PR updates the roadmap.md file to detail how roadmap issues and milestones work within containerd. 

Update roadmap.md with issue labels and milestones

---

MAINTAINERS

LGTM required from 6 Maintainers
LGTM from new maintainers and reviewers

Add cri-containerd maintainers and reviewers

---

cmd/ctr/commands/run/run.go
cmd/ctr/commands/run/run_unix.go
cmd/ctr/commands/run/run_windows.go
cmd/ctr/commands/tasks/start.go
cmd/ctr/commands/tasks/tasks_unix.go
cmd/ctr/commands/tasks/tasks_windows.go
container_opts_unix.go

Add no-pivot flag to ctr

---

vendor.conf
vendor/github.com/stevvooe/ttrpc/client.go
vendor/github.com/stevvooe/ttrpc/server.go

vendor: update ttrpc for shutdown fix

---

vendor.conf
vendor/github.com/stevvooe/ttrpc/client.go
vendor/github.com/stevvooe/ttrpc/server.go

(cherry picked from commit 87cb12de3277ffc73f7901e76d9307641333221c)

[release/1.0] vendor: update ttrpc for shutdown fix

---

releases/v1.0.1-rc.0.toml
version/version.go

Review Checklist:
Tag will be pushed after successful build, merge, build of this branch.

release: prepare v1.0.1-rc.0

---

version/version.go

release: use correct version number

---

archive/tar.go
archive/tar_test.go

Ensure whiteout is not pointing to the current directory or parent directory before removing. Protects against invalid removal of the parent or current directory.
Add whiteout related tar tests using manufactured tar conditions.
credit to @tonistiigi for finding

archive: check whiteout path before removal

---

archive/tar.go
archive/tar_test.go

Cherry pick of #2001
Ensure whiteout is not pointing to the current directory
or parent directory before removing. Protects against invalid
removal of the parent or current directory.
Add whiteout related tar tests using manufactured tar conditions.

[release/1.0] archive: check whiteout path before removal

---

cmd/ctr/commands/run/run_unix.go
oci/spec_opts_unix.go

Cherry-pick: https://github.com/containerd/containerd/pull/1994

[release/1.0] fix running a container with config.User

---

metadata/buckets.go
metadata/db_test.go
metadata/images.go
metadata/images_test.go
metadata/namespaces.go
services/images/service.go

Backport of #1960 
This includes some minor refactoring to fix the original bug. Includes more test coverage.

[release/1.0] metadata: image removal triggers GC

---

dialer/dialer.go

Cherry-pick #2022 
Signed-off-by: Li Yi <denverdino@gmail.com>

[release/1.0] cherrypick Fix NPE in dialer

---

Makefile

Makefile: ensure that `containerd-shim` gets added when installing

---

server/server.go

Fixes https://github.com/containerd/containerd/issues/2043.
Add `Closer` in plugin to allow containerd "close" plugin before stop.
Initially, I thought about naming it `Finalize` or `Stop`. However, I find in that way we need to change all existing snapshotters to wrap their `Close` functions.
So I decided to use `Close` directly to make it compatible with existing snapshotters. Should we add type assertion in `snapshotter/snapshotter.go` for `plugin.Closer`?
@containerd/containerd-maintainers WDYT?

Add `Closer` in plugin.

---

cmd/containerd-shim/shim_linux.go
reaper/reaper.go

cmd/containerd-shim, reaper: reduce channel allocation

---

cmd/containerd-shim/shim_linux.go
reaper/reaper.go

(cherry picked from commit 71e9f6dac2205129523055de37a3dfc09cb2eb6d)

[release/1.0] cmd/containerd-shim, reaper: reduce channel allocation

---

vendor.conf
vendor/github.com/containerd/go-runc/runc.go
vendor/github.com/containerd/go-runc/utils.go

(cherry picked from commit f534a20173fffcac5a5295e6796ccf8c895509f6)

[release/1.0] vendor: update go-runc to reduce gc pressure

---

content/local/store_test.go
content/testsuite/testsuite.go
content_test.go
metadata/content_test.go

content/testsuite: ensure unique content per test

---

releases/v1.0.2-rc.0.toml
version/version.go

release: prepare 1.0.2-rc.0

---

client.go
remotes/handlers.go

Related to use case for: #2075
After using a schema1 to schema2 converter, the blobs are written to the content store. In order to migrate schema1 manifests stored on a registry, they need to converted and then re-pushed. In `(*Client).Push` the client's content store is used, but could be refactored out to take a `content.Provider`. This PR refactors it out so that outside of client, `PushContent` helper can be used to push content specified by a descriptor from a `content.Provider`.

Refactor client push into helper function

---

vendor.conf
vendor/github.com/BurntSushi/toml/README.md
vendor/github.com/BurntSushi/toml/doc.go
vendor/github.com/BurntSushi/toml/encode.go
vendor/github.com/BurntSushi/toml/lex.go
vendor/github.com/BurntSushi/toml/parse.go

vendor: update BurntSushi/toml for MIT license

---

client.go
cmd/containerd/builtins.go
cmd/ctr/commands/snapshots/snapshots.go
diff.go
diff/apply/apply.go
diff/diff.go
diff/walking/differ.go
diff/walking/plugin/plugin.go
diff/windows/windows.go
rootfs/apply.go
rootfs/diff.go
services/diff/service.go
task.go

Discussed in https://github.com/moby/buildkit/pull/155
cc @tonistiigi

diff: resplit Applier from Differ

---

cmd/containerd/main.go
log/context.go

Fixes https://github.com/containerd/containerd/issues/2028.
I'm not sure whether people are fine about this. Send it here for opinions.
We do need this in cri-containerd. See https://github.com/containerd/containerd/issues/2028#issuecomment-359112375

Support trace level.

---

linux/bundle.go
linux/runtime.go
linux/shim/client/client.go
runtime/task_list.go
vendor.conf
vendor/github.com/stevvooe/ttrpc/channel.go
vendor/github.com/stevvooe/ttrpc/client.go
vendor/github.com/stevvooe/ttrpc/server.go
windows/runtime.go

Closes #2083
Fixes #2078
This is an alternative to #2083 that does not have a blocking wait

Use ttrpc OnClose to fix restored dead shims

---

remotes/docker/schema1/converter.go

I want to utilize containerd's `schema1.Converter` to migrate a registry's schema1 manifests to schema2 manifests in the storage backend (not only for pull conversion). I've written a POC that does just that, except that registry doesn't accept manifest mediatype for `application/vnd.oci.image.manifest.v1+json`.
I added an optional `ConvertOpt` as an argument to `(*Converter).Convert` to specify the manifest and manifest config media types. If not provided, it will default to the OCI media types.

Allow specifying media type for a converted schema1 manifest for compatibility with distribution

---

linux/bundle.go
linux/runtime.go
linux/shim/client/client.go
runtime/task_list.go
vendor.conf
vendor/github.com/stevvooe/ttrpc/channel.go
vendor/github.com/stevvooe/ttrpc/client.go
vendor/github.com/stevvooe/ttrpc/server.go
windows/runtime.go

[release 1.0] Handle shim killed on restore

---

releases/v1.0.2-rc.1.toml
version/version.go

release: prepare 1.0.2-rc.1

---

cmd/containerd-stress/exec_worker.go
cmd/containerd-stress/worker.go

Capture more error locations during stress tests

---

RUNC.md
vendor.conf
vendor/github.com/opencontainers/runc/libcontainer/nsenter/nsexec.c

Update runc to a618ab5a0186905949ee463dbb762c3d23e

---

container_opts_unix.go
diff/apply/apply.go
images/importexport.go
images/oci/exporter.go
images/oci/importer.go
task.go

*: use narrower content interfaces

---

docs/index.md

Add to #1951 updates with recent releases/news, as well as some corrections to content.
Closes #1951

Carry #1951: Website update

---

oci/spec_opts.go

Fix typo in variable name

---

releases/v1.0.2.toml
version/version.go

release: prepare 1.0.2

---

cmd/ctr/commands/commands.go
cmd/ctr/commands/run/run.go
cmd/ctr/commands/tasks/start.go

Add --pid-file to `ctr`

---

task.go

Fixes https://github.com/containerd/containerd/issues/2150.
Option 3 of https://github.com/containerd/containerd/issues/2150.

Fix task load.

---

cmd/ctr/commands/run/run_unix.go

ctr: add UNIX-specific flags to `ctr c create`

---

cmd/containerd-shim/main_unix.go
cmd/containerd-shim/shim_linux.go

ref: https://github.com/moby/moby/issues/36464

Handle SIGPIPE in shims

---

cmd/containerd-shim/main_unix.go
cmd/containerd-shim/shim_linux.go

ref: https://github.com/moby/moby/issues/36464

[release 1.0] Handle SIGPIPE in shims

---

vendor.conf
vendor/github.com/containerd/btrfs/README.md
vendor/github.com/containerd/btrfs/btrfs.go
vendor/github.com/containerd/btrfs/doc.go
vendor/github.com/containerd/btrfs/helpers.go
vendor/github.com/containerd/btrfs/info.go

Provides updates for licensing and a build problem with fedora28.
Closes #2189.

vendor: update btrfs dependency

---

cmd/ctr/commands/run/run_unix.go

Without this `ctr run` can fail with:
ctr: parent snapshot sha256:70798fd80095f40b41baa5d107fb61532bfe494d96313fea01e8fcbf4e8743ee does not exist: not found
My image was produced by buildkit, which doesn't unpack (I think this makes
sense since buildkit doesn't know if I am going to run the image or export/push
it etc).

ctr: unpack the image on run if necessary

---

CONTRIBUTING.md

Adds note about applying license header

---

client_test.go
daemon_config_linux_test.go
daemon_test.go
linux/bundle.go
linux/runtime.go

Kunal Kushwaha <kushwaha_kunal_v7@lab.ntt.co.jp>
Cherry-pick https://github.com/containerd/containerd/pull/2173 https://github.com/containerd/containerd/pull/2182

[release/1.0] linux: fix runtime-root propagation

---

vendor.conf
vendor/github.com/opencontainers/runc/README.md
vendor/github.com/opencontainers/runc/libcontainer/user/lookup.go
vendor/github.com/opencontainers/runc/libcontainer/user/lookup_unix.go
vendor/github.com/opencontainers/runc/libcontainer/user/lookup_windows.go
vendor/github.com/opencontainers/runc/libcontainer/user/user.go
vendor/github.com/opencontainers/runc/vendor.conf

Bump runc to 69663f0bd4b60df09991c08812a60108003fa

---

process.go
task.go

Add task.ID() API

---

content/helpers.go
remotes/docker/schema1/converter.go
remotes/handlers.go

Updates blob writer helper to use new open and ensure unavailable errors are always handled. Removes duplication of unavailable handling code.
Fixes #1545

content: add writer open helper to handle unavailable refs

---

cmd/ctr/app/main.go
cmd/ctr/app/main_unix.go
cmd/ctr/main.go

cmd/ctr/app: remove redundant package name

---

archive/tar.go
archive/tar_test.go
fs/fstest/file.go
fs/fstest/testsuite.go
gc/scheduler/scheduler.go

[release/1.0] socket in archive and gc config fixes

---

cmd/containerd/builtins_linux.go
vendor.conf
vendor/github.com/containerd/aufs/LICENSE
vendor/github.com/containerd/aufs/README.md
vendor/github.com/containerd/aufs/aufs.go

cmd/containerd: include aufs by default

---

client.go
cmd/containerd/command/config_windows.go
defaults/defaults.go
server/config.go
server/server.go

server: allow configuration default send/recv message sizes

---

linux/proc/exec.go

Under certain conditions in the client, the fifo for a container may not
be created. A timeout has been added to this operation to ensure the
shim can recover when the client fails to open the fifos.
Possible fix for https://github.com/moby/moby/issues/36661.

linux/prox: timeout fifo creation

---

RELEASES.md
releases/v1.1.0-rc.0.toml
version/version.go

Add the release notes and update release docs. Increments version number.
Please review release notes and propose additional items to be added. Also we should consider more changes to the releases document related to CRI.

Prepare 1.1.0-rc.0 release

---

vendor.conf
vendor/github.com/containerd/aufs/aufs.go

Closes https://github.com/containerd/containerd/issues/2249

vendor: update aufs dependency

---

vendor.conf
vendor/github.com/containerd/zfs/zfs.go

vendor: update zfs dependency

---

container_linux_test.go
oci/spec_opts_unix.go

For https://github.com/containerd/cri/pull/710.
Add a `oci.WithUser` helper function which accepts valid user string defined in OCI image config.
This also addresses the `// TODO: support username and groupname`. In Kubernetes 1.10, we recently supported group id, and will support group name soon. This helper function will be very useful. :)

Add oci.WithUser helper function.

---

releases/v1.0.3.toml
version/version.go

release: prepare 1.0.3 release

---

RELEASES.md
releases/v1.1.0-rc.1.toml
version/version.go

Second RC with bug fixes in containerd and cri plugin

Prepare 1.1.0-rc.1

---

remotes/docker/resolver.go

remotes/docker: protect secret with a mutex

---

remotes/docker/resolver.go

Cherry picks https://github.com/containerd/containerd/pull/2171 and #2276

[release/1.0] remotes/docker: protect secret with a mutex

---

api/1.1.pb.txt

api: update API capture for 1.1 release

---

client.go

For internal services like cri, close will panic

Only close if conn exists

---

image.go

Add NewImage to return a client Image impl

---

content/helpers.go

Deferring the put back of the buffer is not necessary since it can be done immediately after use, before checking error. This decreases the amount of the time the buffer is out of the pool and not in use.

content: remove unnecessary defer in helpers

---

archive/tar_test.go
client.go
container_linux_test.go
defaults/doc.go
diff/windows/windows.go
filters/filter.go
gc/scheduler/scheduler.go
images/image.go
linux/runtime.go
plugin/plugin.go
process.go
services/diff/local.go
snapshots/storage/metastore_test.go
snapshots/testsuite/testsuite.go

Signed-off-by: Michael Wan <zirenwan@gmail.com>

fix words misspell

---

cmd/ctr/commands/events/events.go

[release/1.1] Correctly handle reading from events channel

---

linux/runtime.go

Enable runc debug for shim.
/cc @Random-Liu 
closes #2243

Enable runc debug in shim

---

cio/io.go

Add LogFile as a cio IO option
