- snapshots/native/native.go
`secuity.*` xattrs cannot be copied in most cases
For moby/buildkit#1189
> snapshots/native: ignore xattr errors during CopyDir

- .travis.yml
- Makefile
- cmd/gen-manpages/main.go
Seems to be that docs/man/ctr.1.md and docs/man/containerd.1.md were
removed in #3637 and were not updated correctly in the Makefile, leading
to build failures like:
+ make man
make: *** No rule to make target `man/ctr.1', needed by `man'.  Stop.
Changes the gen-manpages command to be specific on which manpages are to
be generated.
Same as #3729 but for the `release/1.3` branch
Signed-off-by: Eli Uriegas <eli.uriegas@docker.com>
(cherry picked from commit 036db34f37617d6a02f07b04fc2d35a91732c6e3)
Signed-off-by: Eli Uriegas <eli.uriegas@docker.com>
> [release/1.3] build: Fix manpage generation

- snapshots/native/native.go
> [release/1.3] snapshots/native: ignore xattr errors during CopyDir

- remotes/docker/pusher.go
When using containerd, I noticed that I would get an `unexpected status: 202 Accepted` when pushing manifests to Quay.
> Allow 202 response code for commit

- container_test.go
- pkg/process/io.go
- runtime/v1/shim/service.go
- runtime/v1/shim/service_linux.go
- runtime/v2/runc/platform.go
Resized the I/O buffers to align with the size of the kernel buffers with fifos
and move the close aspect of the console to key off of the stdin closing.
Cherry-picked #3743 for `release/1.3`
> [release/1.3] cherry-pick: Handle large output in v2 shim with TTY

- .appveyor.yml
- contrib/Dockerfile.test
Golang 1.12.12
-------------------------------
go1.12.12 (released 2019/10/17) includes fixes to the go command, runtime,
syscall and net packages. See the Go 1.12.12 milestone on our issue tracker for
details.
https://github.com/golang/go/issues?q=milestone%3AGo1.12.12
Golang 1.12.11 (CVE-2019-17596)
-------------------------------
go1.12.11 (released 2019/10/17) includes security fixes to the crypto/dsa package.
See the Go 1.12.11 milestone on our issue tracker for details.
https://github.com/golang/go/issues?q=milestone%3AGo1.12.11
[security] Go 1.13.2 and Go 1.12.11 are released
Hi gophers,
We have just released Go 1.13.2 and Go 1.12.11 to address a recently reported
security issue. We recommend that all affected users update to one of these
releases (if you're not sure which, choose …
> Update Golang 1.12.12 (CVE-2019-17596)

- vendor.conf
- vendor/google.golang.org/grpc/internal/transport/http2_server.go
- vendor/google.golang.org/grpc/internal/transport/http_util.go
- vendor/google.golang.org/grpc/version.go
full diff: https://github.com/grpc/grpc-go/compare/v1.23.0...v1.23.1
- grpc/grpc-go#3018 server: set and advertise max frame size of 16KB
- grpc/grpc-go#3017 grpclb: fix deadlock in grpclb connection cache
- Before the fix, if the timer to remove a SubConn fires at the
same time NewSubConn cancels the timer, it caused a mutex leak
and deadlock.
> bump google.golang.org/grpc v1.23.1

- README.md
- contrib/autocomplete/ctr
- contrib/autocomplete/zsh_autocomplete
Since recent versions of `vndr` are going to remove the autocomplete
scripts from the urfave vendored content, we will just move them into
`contrib/` and reference them in the documentation from that location.
See #3759 for background
> Move autocomplete files to contrib/

- vendor/github.com/opencontainers/runc/README.md
Due to a temporarily broken containerd/project script the vendor dir was slightly
out of state with what it should have been after the last runc vendor
update.
> [release/1.2] Catch up vndr with state of vendor/ dir

- vendor/github.com/opencontainers/runc/README.md
Due to a temporarily broken containerd/project script the vendor dir
was slightly out of state with what it should have been after the
last runc vendor update.
> [release/1.3] Catch up vndr with state of vendor/ dir

- .appveyor.yml
- .travis.yml
- contrib/Dockerfile.test
backport of https://github.com/containerd/containerd/pull/3760
Golang 1.12.12
-------------------------------
go1.12.12 (released 2019/10/17) includes fixes to the go command, runtime,
syscall and net packages. See the Go 1.12.12 milestone on our issue tracker for
details.
https://github.com/golang/go/issues?q=milestone%3AGo1.12.12
Golang 1.12.11 (CVE-2019-17596)
-------------------------------
go1.12.11 (released 2019/10/17) includes security fixes to the crypto/dsa
package. See the Go 1.12.11 milestone on our issue tracker for details.
https://github.com/golang/go/issues?q=milestone%3AGo1.12.11
[security] Go 1.13.2 and Go 1.12.11 are released
Hi gophers,
We have just released Go 1.13.2 and Go 1.12.11 to address a recently reported
security issue. We recommend that all affected users …
> [release/1.3 backport] Update Golang 1.12.12 (CVE-2019-17596)

- .appveyor.yml
- .travis.yml
- contrib/Dockerfile.test
backport of https://github.com/containerd/containerd/pull/3760
Golang 1.12.12
-------------------------------
go1.12.12 (released 2019/10/17) includes fixes to the go command, runtime,
syscall and net packages. See the Go 1.12.12 milestone on our issue tracker for
details.
https://github.com/golang/go/issues?q=milestone%3AGo1.12.12
Golang 1.12.11 (CVE-2019-17596)
-------------------------------
go1.12.11 (released 2019/10/17) includes security fixes to the crypto/dsa
package. See the Go 1.12.11 milestone on our issue tracker for details.
https://github.com/golang/go/issues?q=milestone%3AGo1.12.11
[security] Go 1.13.2 and Go 1.12.11 are released
Hi gophers,
We have just released Go 1.13.2 and Go 1.12.11 to address a recently reported
security issue. We recommend that all affected users …
> [release/1.2 backport] Update Golang 1.12.12 (CVE-2019-17596)

- cmd/containerd/command/config.go
- docs/man/containerd-config.toml.5.md
- services/server/config/config.go
This PR:
1) Updated man file for https://github.com/containerd/containerd/issues/3776;
2) Add missing `Timeouts` support in `containerd config dump` output;
There are still 2 problems:
1) The import behavior is very confusing. For example, as a user using `config.toml`, you don't know whether a section is a map or struct underlying. It's impossible for them to tell whether the subsequent config will be merged or overwritten... I understand that we do this because of the limitation of `mergo`, but we should at least make the behavior consistent, for example all 1st level section will be overwritten directly.
2) It is hard to maintain future map fields. IIUC, any new map fields added in the config (maybe in a child struct), needs to be taken care in `mergeConfig`. It seems a bit hard to …
> Fix `containerd config dump`.

- diff/apply/apply_linux.go
Cherry-pick https://github.com/containerd/containerd/pull/3763
> [release/1.3] apply: use naive applier when running in UserNS

- cmd/containerd/command/main.go
- log/context.go
- vendor.conf
- vendor/github.com/containerd/cri/cri.go
- vendor/github.com/containerd/cri/vendor.conf
This PR depends on https://github.com/containerd/cri/pull/1323.
Logrus supports trace level natively now. See https://github.com/sirupsen/logrus/pull/844
> Use logrus trace support.

- RELEASES.md
v1.1 reached EOL on October 23, 2019
> RELEASES.md: 1.1 EOL

- Makefile
Since autocompletions moved to contrib/ in https://github.com/containerd/containerd/pull/3766 we can remove this from the Makefile as well.
> Makefile: Drop vndr whitelist

- Makefile.linux
Almost the same as https://github.com/containerd/containerd/pull/3784
Go doesn´t support pie for mips architectures.
So fix build for mips architectures and don´t use -buildmode=pie on mips, mipsle, mips64 and mips64le.
Signed-off-by: Johann Neuhauser <johann@it-neuhauser.de>
> mips: -buildmode=pie is not supported for the mips arch

- Protobuild.toml
This fixes proto compiles on alpine based systems.
> Add proto path /usr/include to Protobuild

- .appveyor.yml
- .travis.yml
- contrib/Dockerfile.test
go1.12.13 (released 2019/10/31) fixes an issue on macOS 10.15 Catalina
where the non-notarized installer and binaries were being rejected by
Gatekeeper. Only macOS users who hit this issue need to update.
> Update to Golang 1.12.13

- .appveyor.yml
- .travis.yml
- contrib/Dockerfile.test
backport of https://github.com/containerd/containerd/pull/3806 for the 1.3 release branch
go1.12.13 (released 2019/10/31) fixes an issue on macOS 10.15 Catalina
where the non-notarized installer and binaries were being rejected by
Gatekeeper. Only macOS users who hit this issue need to update.
> [release/1.3 backport] Update to Golang 1.12.13

- .appveyor.yml
- .travis.yml
- contrib/Dockerfile.test
go1.13.4 (released 2019/10/31) includes fixes to the net/http and syscall
packages. It also fixes an issue on macOS 10.15 Catalina where the non-
notarized installer and binaries were being rejected by Gatekeeper.
See the Go 1.13.4 milestone on the issue tracker for details:
https://github.com/golang/go/issues?q=milestone%3AGo1.13.4
go1.13.3 (released 2019/10/17) includes fixes to the go command, the toolchain,
the runtime, syscall, net, net/http, and crypto/ecdsa packages. See the Go
1.13.3 milestone on the issue tracker for details:
https://github.com/golang/go/issues?q=milestone%3AGo1.13.3
go1.13.2 (released 2019/10/17) includes security fixes to the crypto/dsa
package and the compiler. See the Go 1.13.2 milestone on the issue tracker
for details: …
> Update to Golang 1.13.4

- .appveyor.yml
- .travis.yml
- contrib/Dockerfile.test
backport of https://github.com/containerd/containerd/pull/3806 for the 1.2 release branch
some small conflicts due to travis having diverged a bit on master, but trivial to resolve
go1.12.13 (released 2019/10/31) fixes an issue on macOS 10.15 Catalina
where the non-notarized installer and binaries were being rejected by
Gatekeeper. Only macOS users who hit this issue need to update.
> [release/1.2 backport] Update to Golang 1.12.13

- contrib/Dockerfile.test
Change noted in #3814 is also needed in our contributed `Dockerfile.test`. Left the `btrfs-progs` as an install candidate for potential use for debugging even though not required to compile the daemon.
> Update name for btrfs headers package

- BUILDING.md
btrfs/ioctl.h is now included in libbtrfs-dev instead of btrfs-tools.
Update BUILDING.md Dockerfile to install the correct dependency.
Resolves: #3813
Signed-off-by: Reid Li <reid.li@utexas.edu>
> Fix dependency in BUILDING.md

- reference/reference.go
Fix #3817 
Signed-off-by: Shiwei Zhang <shizh@microsoft.com>
> Fix panic on reference.Spec.Hostname()

- snapshots/storage/bolt.go
> snapshots: return error if readSnapshot fails

- .travis.yml
back port of https://github.com/containerd/containerd/pull/3705
fixes https://github.com/containerd/containerd/issues/3704 "Release script race on upload sha256sum"
Prevent Travis from building and pushing up multiple times
> [release/1.3 backport] Limit travis release script to a single build

- Makefile
- Makefile.windows
`make clean` and `make install` doesn't work for `.exe` binaries with linux shell today.
This fixed it. Please note that I'm not a Makefile expert, feel free to propose a better solution. :)
> Better support windows binaries.

- snapshots/overlay/overlay.go
- snapshots/windows/windows.go
Add `Usage` support in windows snapshotter.
For https://github.com/containerd/cri/issues/1299.
/cc @jterry75 
> Support disk usage in windows snapshot.

- .github/workflows/nightly.yml
Let's give a try to Github Actions.
This PR adds a workflow that will trigger nightly jobs to build containerd binaries (both linux and windows).
Job artifacts will be uploaded to [Github Storage](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/persisting-workflow-data-using-artifacts#about-workflow-artifacts)  and available for 90 days.
Here is an example how job execution looks like: https://github.com/mxpv/containerd/commit/23f980b71cf63e99a07446bc35c1e932530c30ee/checks?check_suite_id=307992957
Binaries can be downloaded from the menu at top right corner:
> containerd binaries nightly builds

- client_opts.go
Added `RemoteOpt` to initialize remote context unpack option.
> Add client unpack opts

- pull.go
- unpacker.go
Fixes https://github.com/containerd/containerd/issues/3816.
It turns out that some layers are downloaded with error `response.status="206 Partial Content"`. However, we don't stop unpacker when there are layer download errors, thus it will wait for those layers forever.
This PR:
1) Stoped the unpacker if any error happens during fetch;
2) Avoided sending update when unpacker is stopped, this can prevent another potential deadlock when `updateCh` is full.
/cc @dmcgowan @ungureanuvladvictor  
> Avoid deadlock in unpacker.

- image_test.go
Simply delete the image will not clean up the snapshots.
> test: Do SynchronousDelete cleanup before testing ImageIsUnpacked

- releases/v1.3.1.toml
- version/version.go
* Update the runc vendor to v1.0.0-rc9 which includes an additional mitigation for [CVE-2019-16884](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-16884).
- More details on the runc CVE in [opencontainers/runc#2128](https://github.com/opencontainers/runc/issues/2128), and the additional mitigations in [opencontainers/runc#2130](https://github.com/opencontainers/runc/pull/2130).
* Add local-fs.target to service file to fix corrupt image after unexpected host reboot. Reported in [containerd/containerd#3671](https://github.com/containerd/containerd/issues/3671), and fixed by [containerd/containerd#3745](https://github.com/containerd/containerd/pull/3745).
* Fix large output of processes with TTY getting occasionally truncated. Reported in …
> [release/1.3] Prepare v1.3.1 release

- snapshots/devmapper/README.md
base_image_size effectively is the limit of a layer size that can be
created using the devmapper snapshotter. While this will also depend on
the thinpool size itself, something closer to the total image size
(80%?) is more appropriate.
As is, if you try to run an image like elastic, you'll need a much
larger base_image_size than 128MB.
As a reference point, this is my reference thinpool setup for devmapper, [1]. It may be useful to maintain a reference script in the docs with a big "YMMV" warning, for setting this up.  
Happy to add this if there's interest.
[1] - https://github.com/egernst/k8s-pod-overhead/blob/master/node-setup/containerd_devmapper_setup.sh 
Signed-off-by: Eric Ernst <eric.ernst@intel.com>
> devmapper: update example base image size in README

- metadata/adaptors.go
- metadata/db_test.go
- metadata/snapshot.go
- metadata/snapshot_test.go
- snapshots/storage/bolt.go
- snapshots/testsuite/testsuite.go
Allows backend snapshots to bring existing snapshots into a namespace without requiring clients to fully snapshots when the target reference is known. Backend snapshots must explicitly implement this functionality, it is equivalent to sharing across namespaces and is up to the backend to use the label when it is given or ignore it.
This enables remote snapshot functionality for a backend to query for a target snapshot before a client has performed any work to create that snapshot.
Further documentation is needed. I will likely create a documented related to remote snapshotters when the remainder of the work is done for those. Additionally, the behavior of snapshotters in regards to errors (and these labels) should be more fully defined in the snapshot interface definition.
There is a …
> Support target snapshot references on prepare

- vendor.conf
- vendor/github.com/containerd/go-runc/runc.go
full diff: https://github.com/containerd/go-runc/compare/e029b79d8cda8374981c64eba71f28ec38e5526f...a2952bc25f5116103a8b78f3817f6df759aa7def
- containerd/go-runc#56 fix typo in successfully
> bump containerd/go-runc a2952bc25f5116103a8b78f3817f6df759aa7def

- releases/v1.2.11.toml
- version/version.go
* Update the runc vendor to v1.0.0-rc9 which includes an additional mitigation for
[CVE-2019-16884](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-16884).
- More details on the runc CVE in [opencontainers/runc#2128](https://github.com/opencontainers/runc/issues/2128), and the additional mitigations in [opencontainers/runc#2130](https://github.com/opencontainers/runc/pull/2130).
* Add local-fs.target to service file to fix corrupt image after unexpected host reboot.
Reported in [containerd/containerd#3671](https://github.com/containerd/containerd/issues/3671),
and fixed by [containerd/containerd#3746](https://github.com/containerd/containerd/pull/3746).
* Update Golang runtime to 1.12.13, which includes security fixes to the `crypto/dsa`
package made in Go 1.12.11 …
> [release/1.2] Prepare v1.2.11 release

- content_test.go
A race occurs today where the cleanup runs after the lease has been deleted, making all the content and statuses eligible for collection during the cleanup. There is a case where a status could be listed but removed before the abort is called. In this case, abort will return a not found and the test cleanup should ignore it.
> Fix cleanup error on content client test

- content_test.go
A race occurs today where the cleanup runs after the lease
has been deleted, making all the content and statuses
eligible for collection during the cleanup. There is a case
where a status could be listed but removed before the
abort is called. In this case, abort will return a not found
and the test cleanup should ignore it.
(cherry picked from commit 8da4346686f339241efed3e6bf752cc4f8670103)
cherry-pick #3853
> [release 1.3] Fix cleanup error on content client test

- content_test.go
A race occurs today where the cleanup runs after the lease
has been deleted, making all the content and statuses
eligible for collection during the cleanup. There is a case
where a status could be listed but removed before the
abort is called. In this case, abort will return a not found
and the test cleanup should ignore it.
(cherry picked from commit 8da4346686f339241efed3e6bf752cc4f8670103)
cherry-pick #3853
> [release 1.2] Fix cleanup error on content client test

- pkg/process/deleted_state.go
- pkg/process/exec.go
- pkg/process/exec_state.go
- pkg/process/init.go
- pkg/process/init_state.go
- pkg/process/utils.go
backport of https://github.com/containerd/containerd/pull/3711
- relates to https://github.com/kubernetes/kubernetes/issues/82440 High system load/CPU utilization with trivial liveness and readiness probes
- relates to https://github.com/moby/moby/issues/39102 Docker healthcheck causes high CPU utilization
- relates to https://github.com/google/gvisor-containerd-shim/issues/39 Reduce `runsc state` call
cherry-pick was clean
> [release/1.3 backport] Use cached state instead of `runc state`.

- runtime/v1/linux/proc/deleted_state.go
- runtime/v1/linux/proc/exec.go
- runtime/v1/linux/proc/exec_state.go
- runtime/v1/linux/proc/init.go
- runtime/v1/linux/proc/init_state.go
- runtime/v1/linux/proc/process.go
- runtime/v1/linux/proc/utils.go
Backports of:
- https://github.com/containerd/containerd/pull/3361 Add timeout for I/O waitgroups
- fixes https://github.com/containerd/containerd/issues/3286 docker exec hang if earlier docker exec left a zombie process
- https://github.com/containerd/containerd/pull/3366 Robust pid locking for shim processes
- closes https://github.com/containerd/containerd/pull/2832 fixes: pid reuse attack when kill a exec process
- https://github.com/containerd/containerd/pull/3711 Use cached state instead of `runc state`
- relates to https://github.com/kubernetes/kubernetes/issues/82440 High system load/CPU utilization with trivial liveness and readiness probes
- relates to https://github.com/moby/moby/issues/39102 Docker healthcheck causes high CPU utilization
First two cherry-picks were clean:
``` …
```
> [release/1.2 backport] backport exec fixes

- script/release/release-cri
- script/setup/install-cni
- script/setup/install-runc
- vendor.conf
Since it doesn't look like this repo will switch to using go mod soon, let's reformat this file to make comparing with other repositories slightly easier and to encourage pinning 
Best to review individual commits (no dependencies were updated, so vendored files should stay unmodified)
> Reformat vendor.conf: use columns, pin by git-sha, and sort alphabetically

- platforms/cpuinfo.go
The cpuinfo of kunpeng920 is like this:
```
model name	: Kunpeng 920-4826 
BogoMIPS	: 200.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt lpae evtstrm
CPU implementer	: 0x48
CPU architecture: aarch64
CPU variant	: 0x1
CPU part	: 0xd01
CPU revision	: 0
```
The variant will be unknown, because `aarch64` doesn't match `AArch64`.
So I update the cpuinfo logic to deal with `aarch64`, `AArch64`
> update cpuinfo to match kunpeng920 Architecture:aarch64

- container_test.go
- pkg/process/exec.go
- pkg/process/init.go
- pkg/process/init_state.go
- pkg/process/utils.go
If you try docker with containerd 1.3, and run `docker run hello-world`, it will stuck.
After https://github.com/containerd/containerd/pull/3366, we change pid after container/exec process created, this causes various issues:
1) The pid we get from `task.Start` might be `-1` if the container is a short running container, because `Start` and `State` are not called in a transaction: https://github.com/containerd/containerd/blob/master/services/tasks/local.go#L230.
2) This is fine for Kubernetes integration, because we stopped relying on containerd event and pid matching. However, this will break Docker: https://github.com/moby/moby/blob/05469b5fa2b48cf20cd0137ca8c45645b63049ff/daemon/monitor.go#L50
3) In all higher level apis, pid is an `uint`, returning `-1` will eventually make it …
> Fix container pid race condition.

- vendor.conf
- vendor/github.com/containerd/cri/pkg/config/config.go
- vendor/github.com/containerd/cri/pkg/server/image_pull.go
Added `insecure_skip_verify` option in the registry tls config to allow skipping registry certificate verification (https://github.com/containerd/containerd/issues/3847)
> [release/1.3] Update cri to b1bef15fbeb6c6f0569b67322acfa74ca3597755.

- .appveyor.yml
This is already added in release/1.3 and release/1.2 was fixed with a
specific branch name at some point.
> Make sure for next release branch appveyor runs

- cmd/ctr/commands/run/run_unix.go
We pass `--read-only` argument to `ctr` to be interpreted at
https://github.com/containerd/containerd/blob/master/cmd/ctr/commands/commands.go#L100-L103
`ctr run` looks for if `readonly` is defined instead of `read-only`, which is not defined. This allows for `ctr run` to set the container's filesystem as readonly.
> Modify ctr run to search for read-only flag instead of readonly

- container_linux_test.go
- oci/spec_opts.go
- oci/spec_opts_test.go
User namespaces used to remap both UID and GID to the same mapping given. This commit will split the UID and GID remapping.
Signed-off-by: Jie Hao Liao <liaojh1998@gmail.com>
Refer to #3876 
cc @AkihiroSuda, @estesp
> Split uid and gid user ns remapping in oci

- cmd/ctr/commands/run/run_unix.go
- task_opts_unix.go
* requires #3881
* --uidmap support for one remapping
* --gidmap support for one remapping
* create IoUid and IoGid options for getNewTaskOpts
Refer to #3841 
Signed-off-by: Jie Hao Liao <liaojh1998@gmail.com>
Note: I'll work on the multiple remapping in later commits.
> support user remapping in ctr

- remotes/docker/authorizer.go
Registries may allow using token authorization without explicitly setting the scope. This may cover use cases where no scope is required for an endpoint or the registry is only covering authentication using the token. This aligns with the oauth2 spec which specifies the scope as optional.
> Allow empty scope authorization

- cmd/ctr/commands/run/run_unix.go
> Use logrus instead of printf for warning

- metrics/cgroups/cgroups.go
- metrics/cgroups/v1/blkio.go
- metrics/cgroups/v1/cgroups.go
- metrics/cgroups/v1/cpu.go
- metrics/cgroups/v1/hugetlb.go
- metrics/cgroups/v1/memory.go
- metrics/cgroups/v1/metric.go
- metrics/cgroups/v1/metrics.go
- metrics/cgroups/v1/oom.go
- metrics/cgroups/v1/pids.go
- metrics/cgroups/v2/pids.go
dicussed in #3726
Also unifies the task monitor instances to avoid the name collision issue across multiple instances: https://github.com/containerd/containerd/issues/3726#issuecomment-565316687
> metrics: rename pids_v2 to pids

- remotes/docker/fetcher.go
- remotes/docker/resolver.go
- remotes/docker/resolver_test.go
This commit improves the fallback behaviour when resolving and
fetching images with multiple hosts. If an error is encountered
when resolving and fetching images, and more than one host is being
used, we will try the same operation on the next host. The error
from the first host is preserved so that if all hosts fail, we can
display the error from the first host.
fixes #3850
Signed-off-by: Alex Price <aprice@atlassian.com>
> Improve host fallback behaviour in docker remote

- pull.go
- unpacker.go
Moves the content fetching into the unpack process and defers the download until the snapshot needs it and is ready to apply. As soon as a layer is reached which requires fetching, all remaining layers are fetched.
This should allow supporting the remote snapshotters through the already exists error. This could also support cross namespace snapshot sharing if the snapshotter allows it.
I am working on an update to ctr to use the updated code (since simultaneous unpack), I am going to keep that separate since it is not a trivial change. I needed that to manually test this though, it can also be tested through CRI.
> Defer layer download until unpack

- .travis.yml
- Makefile
Until we resolve what's wrong with the criu tests with the update to the 5.0.0 kernel in Travis. Also updates installed criu to latest version so any bug reports will be against latest release.
> Temporarily disable criu tests in Travis CI

- sys/socket_unix.go
Fix `buildkitd --group GROUP` issue when `/run/buildkit` already exists
and is owned by the root.
> sys: mkdirAs: do chown if dir already exists

- runtime/v2/runc/v2/service.go
Previously, the platform was closed as part of the Delete method when the
process was an init for a task and there were no more tasks after its deletion.
This can create problems if another task is created within the shim right after
the delete runs, which results in the platform being closed but the shim
continuing to run.
This change moves closing the platform to the Shutdown method after the shim's
context is canceled, which ensures the platform is only closed once the shim
is sure its done servicing containers.
Signed-off-by: Erik Sipsma <sipsma@amazon.com>
Fixes #3895
> runtime v2: Close platform in runc shim's Shutdown method.

- .travis.yml
- Makefile
Temporarily disable criu tests until the 5.0.0 CI kernel issue is
resolved. Also update criu to v3.13
Cherry-picked: #3898 for `release/1.3`
> [release/1.3] cherry-pick: Disable criu tests in Travis CI

- .travis.yml
- Makefile
Temporarily disable criu tests until the 5.0.0 CI kernel issue is
resolved. Also update criu to v3.13
Cherry-picked: #3898 for `release/1.2`
> [release/1.2] backport: Disable criu tests in Travis CI

- runtime/v2/runc/v2/service.go
Previously, the platform was closed as part of the Delete method when the
process was an init for a task and there were no more tasks after its deletion.
This can create problems if another task is created within the shim right after
the delete runs, which results in the platform being closed but the shim
continuing to run.
This change moves closing the platform to the Shutdown method after the shim's
context is canceled, which ensures the platform is only closed once the shim
is sure its done servicing containers.
Signed-off-by: Erik Sipsma <sipsma@amazon.com>
> [release/1.3] cherry-pick: runtime v2: Close platform in runc shim's Shutdown method.

- .appveyor.yml
- .github/workflows/nightly.yml
- .travis.yml
- contrib/Dockerfile.test
go1.13.5 (released 2019/12/04) includes fixes to the go command, the runtime, the
linker, and the net/http package. See the Go 1.13.5 milestone on our issue tracker
for details:
https://github.com/golang/go/issues?q=milestone%3AGo1.13.5+label%3ACherryPickApproved
> Bump golang 1.13.5

- .appveyor.yml
- .travis.yml
- contrib/Dockerfile.test
go1.12.14 (released 2019/12/04) includes a fix to the runtime. See the Go 1.12.14
milestone on our issue tracker for details:
https://github.com/golang/go/issues?q=milestone%3AGo1.12.14+label%3ACherryPickApproved
> [release/1.3] Update Golang 1.12.14

- .appveyor.yml
- .travis.yml
- contrib/Dockerfile.test
backport of https://github.com/containerd/containerd/pull/3917 for the release/1.2 branch
go1.12.14 (released 2019/12/04) includes a fix to the runtime. See the Go 1.12.14
milestone on our issue tracker for details:
https://github.com/golang/go/issues?q=milestone%3AGo1.12.14+label%3ACherryPickApproved
(cherry picked from commit f4824d5a6109362dad8abff552193f7ff08d9e2e)
> [release/1.2 backport] Update Golang 1.12.14

- metadata/snapshot.go
- metadata/snapshot_test.go
- pull.go
- snapshots/snapshotter.go
- unpacker.go
Though containerd gives ChainID to backend snapshotters during unpack for
searching snapshots to be skipped downloading the contents, ChainID isn't enough
for some snapshotters which require additional information of layers.
Some examples are remote snapshotters which is based on stargz filesystem
(requires image-related information to query the contents to docker registry)
and those which is based on CernVM-FS (requires manifest digest, etc. for
providing squashed rootfs).
This commit solves this issue by enabling a handler to inject additional
information of layers to snapshotters during unpack.
Related discussion
- Issue: https://github.com/containerd/containerd/issues/3731
- Initial version of patch: https://github.com/containerd/containerd/pull/3846
- Related patch: …
> Enable to propagate necessary information to snapshotter during unpack

- images/archive/importer.go
- import_test.go
Signed-off-by: Xiaodong Ye <xiaodongy@vmware.com>
Import a tar with `manifest.json`, `ctr image ls` returns incorrect `TYPE`.
```
REF                              TYPE                                       DIGEST                                                                  SIZE      PLATFORMS   LABELS 
docker.io/library/myimage:latest application/vnd.oci.image.manifest.v1+json sha256:663a45ec27ca42bd4ad37eab55a7ad96db3ee5d7ad5c6dc5bbec958b9e63ad53 745.9 KiB linux/amd64 -   
```
> Replace ocispec.MediaTypeImageManifest with manifest.MediaType

- runtime/v2/binary.go
- runtime/v2/manager.go
- runtime/v2/shim.go
If the context is cancelled during `shim.Create()`, such as the client disconnects unexpectedly. The created shim will never be deleted.
What's more, if the context is cancelled during `openShimLog()`, the fifo will be closed and block the shim output.
> v2: Call shim.Delete at first when create is failed

- cmd/ctr/commands/images/push.go
Signed-off-by: Xiaodong Ye <xiaodongy@vmware.com>
Pull a fat image like docker.io/library/hello-world:latest with `--platform linux/amd64` then push the image to a local registry using `ctr`, `ctr: content digest sha256:1e44d8bca6fb0464794555e5ccd3a32e2a4f6e44a20605e4e82605189904f44d: not found` shows.
This PR adds `--platform` to the `push` command, so `ctr` can only push a specific platform to the registry without the manifest list.
> Support pushing a specific platform of a multi-architecture docker image to a registry

- client_test.go
backport #3744, for some reasons, I need to build with go1.13..
> [release/1.3 backport] Move flag.Parse in tests to TestMain

- snapshots/btrfs/btrfs.go
- snapshots/btrfs/btrfs_test.go
backport #3720 
Actually I didn't meet the origin problem. But I failed to build btrfs_test.go on i386.
Because using `unix.BTRFS_SUPER_MAGIC` without type cast, causes `btrfs_test.go:79:17: constant 2435016766 overflows int32`.
I checked master, the use of `unix.BTRFS_SUPER_MAGIC` was removed in #3720. So I think backporting is better than fixing the overflow.
> [release/1.3 backport] Fix flaky btrfs test

- runtime/v2/binary.go
Related to https://github.com/containerd/containerd/pull/3921#discussion_r363046745
/cc @TBBle
> v2: Fix missing ns when openShimLog on windows

- mount/mount_linux.go
- mount/mount_linux_test.go
When `m.Type` starts with either `fuse.` or `fuse3`, the mount helper binary `mount.fuse` or `mount.fuse3` is executed.
This is expected to be used by `fuse-overlayfs` plugin: https://github.com/AkihiroSuda/containerd-fuse-overlayfs
The purpose of the containerd `fuse-overlayfs` snapshotter plugin is to provide OverlayFS functionality for rootless mode without depending on the Ubuntu/Debian kernel patch.
Although `fuse-overlayfs` provides shiftfs functionality and supports CRFS plugin, these functionalities are not planned to be supported by the containerd `fuse-overlayfs` snapshotter plugin. (**EDIT**: shiftfs functionality using fuse-overlayfs snapshotter is being covered in https://github.com/containerd/containerd/pull/3885)
> mount: support FUSE helper

- cmd/ctr/app/main.go
- docs/rootless.md
`$CONTAINERD_ADDRESS` can be specified instead of the `ctr --address` flag.
> ctr: support $CONTAINERD_ADDRESS env var

- snapshots/overlay/overlay_test.go
- snapshots/testsuite/testsuite.go
AsynchronousRemove opt was untested while it is specified by default in the plugin init.
> overlay: test actual Opts

- Makefile
The package lists for testing/build are currently auto generated with no way to explicitly skip packages for test. This adds a variable which can be set to filter out packages.
Fixes #3940
> Add Makefile variable to skip test packages

- platforms/platforms.go
- platforms/platforms_test.go
arm has been supported, but something is missing, causes test failure
```
--- FAIL: TestParseSelector (0.00s)
--- SKIP: TestParseSelector/* (0.00s)
platforms_test.go:288: this case is not yet supported
--- SKIP: TestParseSelector/linux/* (0.00s)
platforms_test.go:288: this case is not yet supported
--- SKIP: TestParseSelector/*/arm64 (0.00s)
platforms_test.go:288: this case is not yet supported
--- PASS: TestParseSelector/linux/arm64 (0.00s)
--- PASS: TestParseSelector/linux/arm64/v8 (0.00s)
--- PASS: TestParseSelector/linux/arm (0.00s)
--- PASS: TestParseSelector/linux/arm/v6 (0.00s)
--- PASS: TestParseSelector/linux/arm/v7 (0.00s)
--- PASS: TestParseSelector/arm (0.00s)
--- PASS: TestParseSelector/armel (0.00s)
--- PASS: TestParseSelector/armhf (0.00s)
--- PASS: …
```
> platforms: fill default arm variant when parse platform specifier

- .zuul/playbooks/containerd-build/run.yaml
Otherwise the exit code is always 0.
Fixes: #3943
> ci: set pipefail in zuul script

- platforms/platforms.go
- platforms/platforms_test.go
> [release/1.3 backport] platforms: fill default arm variant when parse platform specifier

- filters/filter_test.go
- filters/parser.go
- filters/scanner.go
- filters/scanner_test.go
- services/content/contentserver/contentserver.go
Prevent error messages from being output to stderr. Return illegal token when a quoted string is invalid and capture the error.
> Fix filter errors

- unpacker.go
Ran into this issue when using encrypted images via CRI where the payloads were not registering for the stream processor. This fixed it.
> Fix unpacker to pass apply options

- vendor.conf
- vendor/github.com/Microsoft/hcsshim/container.go
- vendor/github.com/Microsoft/hcsshim/go.mod
- vendor/github.com/Microsoft/hcsshim/hcn/hcn.go
- vendor/github.com/Microsoft/hcsshim/hcn/hcnglobals.go
- vendor/github.com/Microsoft/hcsshim/hcn/hcnloadbalancer.go
- vendor/github.com/Microsoft/hcsshim/hcn/hcnsupport.go
- vendor/github.com/Microsoft/hcsshim/internal/hcs/process.go
- vendor/github.com/Microsoft/hcsshim/internal/hcs/system.go
- vendor/github.com/Microsoft/hcsshim/internal/vmcompute/vmcompute.go
- vendor/github.com/Microsoft/hcsshim/osversion/windowsbuilds.go
Update vendored dependency hcsshim to v0.8.7
It has been a long time since the last version update, some bugs were fixed in the middle, and a new version was finally released recently
https://github.com/microsoft/hcsshim/releases/tag/v0.8.7
> bump microsoft/hcsshim to 0.8.7

- filters/filter_test.go
- filters/parser.go
- filters/scanner.go
- filters/scanner_test.go
- services/content/contentserver/contentserver.go
Prevent error messages from being output to stderr.
Return illegal token when a quoted string is invalid and capture the error.
This issue occurs on the daemon and a good candidate to backport.
> [release/1.3] Fix filter errors

- runtime/v2/runc/v1/service.go
- runtime/v2/runc/v2/service.go
Only start watching the cgroup for OOMs when the first process starts instead of on every process.
In my testing this addresses the repro steps in #3949 and resolves the leak we were observing for kubernetes pods that have an exec healthcheck.
> fix: eventfd leak

- gc/scheduler/scheduler_test.go
Fix some flaky tests.
(I think time sensitive test is not good...)
Some failure test examples:
https://buildd.debian.org/status/fetch.php?pkg=containerd&arch=armhf&ver=1.3.2%7Eds1-3&stamp=1578476094&raw=0
```
--- FAIL: TestDeletionThreshold (0.02s)
scheduler_test.go:102: GC wait timed out
```
https://tests.reproducible-builds.org/debian/logs/bullseye/amd64/containerd_1.3.2~ds1-3.build2.log.gz
```
--- FAIL: TestStartupDelay (0.01s)
scheduler_test.go:168: unexpected gc run count 0, expected 1
```
https://tests.reproducible-builds.org/debian/logs/unstable/armhf/containerd_1.3.2~ds1-3.build2.log.gz
```
--- FAIL: TestStartupDelay (0.01s)
scheduler_test.go:168: unexpected gc run count 0, expected 1
```
> gc: increase sleep time in test

- snapshots/storage/metastore_test.go
Today in my two PR(#3962, #3963), the openlab-ci bot sometimes reports failure...
For example,
https://logs.openlabtesting.org/logs/62/3962/35a8e6e589eb37a73f94cdbd5c8d7938b2b04140/check/containerd-build-arm64/de237af/logs/make_test.txt
```
--- FAIL: TestMetastore (18.27s)
--- FAIL: TestMetastore/GetInfo (13.91s)
metastore_test.go:242: assertion failed:
--- expected
+++ info
{snapshots.Info}.Created:
-: s"0001-01-01 00:00:00 +0000 UTC"
+: s"2020-01-15 14:15:38.71882571 +0000 UTC"
{snapshots.Info}.Updated:
-: s"0001-01-01 00:00:00 +0000 UTC"
+: s"2020-01-15 14:15:38.71882571 +0000 UTC"
: on key committed-1
```
It seems the test runs 13.91s...
> snapshots: fix flaky TestMetastore

- runtime/v1/shim/service.go
- runtime/v2/runc/service.go
When containerd-shim does reaper, the most processes are not init
process. Since json.Decode consumes more CPU resource, we should check
killall option for init process only.
backport https://github.com/containerd/containerd/pull/3559
and fixes #3958.
> [backport release/1.2] runtime: only check killall for init process

- metrics/cgroups/v2/io.go
- metrics/cgroups/v2/metrics.go
- metrics/types/v2/types.go
Related to #3726 
Added only Prometheus metrics for IO, since it's multi-line metrics and it can brake table in cmd metrics.
Signed-off-by: Boris Popovschi <zyqsempai@mail.ru>
> Added IO metrics for cgroup v2

- .appveyor.yml
- .travis.yml
- contrib/Dockerfile.test
full diff: https://github.com/golang/go/compare/go1.12.14...go1.12.15
go1.12.15 (released 2020/01/09) includes fixes to the runtime and the net/http
package. See the Go 1.12.15 milestone on the issue tracker for details:
https://github.com/golang/go/issues?q=milestone%3AGo1.12.15+label%3ACherryPickApproved
> [release/1.3] Update Golang 1.12.15

- .appveyor.yml
- .travis.yml
- contrib/Dockerfile.test
backport of https://github.com/containerd/containerd/pull/3967
full diff: https://github.com/golang/go/compare/go1.12.14...go1.12.15
go1.12.15 (released 2020/01/09) includes fixes to the runtime and the net/http
package. See the Go 1.12.15 milestone on the issue tracker for details:
https://github.com/golang/go/issues?q=milestone%3AGo1.12.15+label%3ACherryPickApproved
> [release/1.2 backport] Update Golang 1.12.15

- .appveyor.yml
- .github/workflows/nightly.yml
- .travis.yml
- contrib/Dockerfile.test
full diff: https://github.com/golang/go/compare/go1.13.5...go1.13.6
go1.13.6 (released 2020/01/09) includes fixes to the runtime and the net/http
package. See the Go 1.13.6 milestone on the issue tracker for details.
https://github.com/golang/go/issues?q=milestone%3AGo1.13.6+label%3ACherryPickApproved
> Update Golang 1.13.6

- vendor.conf
- vendor/github.com/opencontainers/runc/README.md
- vendor/github.com/opencontainers/runc/vendor.conf
We have a new release of runc ( opencontainers/runc#2217 ). This release
has a fix for a race condition we are struggling with in kubernetes
(especially CI jobs) which was fixed in opencontainers/runc#2185
The v1.0.0-rc10 includes the fix for CVE-2019-19921 as well. The full
diff upstream is here:
https://github.com/opencontainers/runc/compare/v1.0.0-rc9...v1.0.0-rc10
`Signed-off-by: Davanum Srinivas <davanum@gmail.com>`
> Bump to opencontainers/runc new version - v1.0.0-rc10

- vendor.conf
- vendor/github.com/opencontainers/runc/README.md
- vendor/github.com/opencontainers/runc/vendor.conf
We have a new release of runc ( opencontainers/runc#2217 ). This release
has a fix for a race condition we are struggling with in kubernetes
(especially CI jobs) which was fixed in opencontainers/runc#2185
The v1.0.0-rc10 includes the fix for CVE-2019-19921 as well. The full
diff upstream is here:
https://github.com/opencontainers/runc/compare/v1.0.0-rc9...v1.0.0-rc10
`Signed-off-by: Davanum Srinivas <davanum@gmail.com>`
> [release/1.3 backport] Bump to opencontainers/runc new version - v1.0.0-rc10

- vendor.conf
- vendor/github.com/opencontainers/runc/README.md
- vendor/github.com/opencontainers/runc/vendor.conf
We have a new release of runc ( opencontainers/runc#2217 ). This release
has a fix for a race condition we are struggling with in kubernetes
(especially CI jobs) which was fixed in opencontainers/runc#2185
The v1.0.0-rc10 includes the fix for CVE-2019-19921 as well. The full
diff upstream is here:
https://github.com/opencontainers/runc/compare/v1.0.0-rc9...v1.0.0-rc10
> [release/1.2 backport] Bump to opencontainers/runc new version - v1.0.0-rc10

- vendor.conf
- vendor/github.com/opencontainers/selinux/go-selinux/label/label_selinux.go
- vendor/github.com/opencontainers/selinux/go-selinux/selinux_linux.go
- vendor/github.com/opencontainers/selinux/go-selinux/selinux_stub.go
Picking up the changes in the following diff:
https://github.com/containerd/containerd/compare/master...dims:bump-opencontainers/selinux-for-CVE-2019-16884-release-1.3?expand=1
specifically so we can include:
https://github.com/opencontainers/selinux/commit/03b517dc4fd57245b1cf506e8ba7b817b6d309da
> [release/1.3 backport] Pick up fix for CVE-2019-16884 in opencontainers/selinux

- vendor.conf
- vendor/github.com/opencontainers/selinux/go-selinux/label/label_selinux.go
- vendor/github.com/opencontainers/selinux/go-selinux/selinux_linux.go
- vendor/github.com/opencontainers/selinux/go-selinux/selinux_stub.go
Picking up the changes in the following diff:
https://github.com/containerd/containerd/compare/master...dims:bump-opencontainers/selinux-for-CVE-2019-16884-release-1.3?expand=1
specifically so we can include:
https://github.com/opencontainers/selinux/commit/03b517dc4fd57245b1cf506e8ba7b817b6d309da
> [release/1.2 backport] Pick up fix for CVE-2019-16884 in opencontainers/selinux

- cmd/ctr/commands/events/events.go
Errors like "type with url %s: not found" are typical for non-builtin event types, and should not resultin exiting `ctr`.
> ctr events: do not exit on an error

- docs/man/containerd-config.toml.5.md
Without this patch, the containerd daemon fails to start using the
default configuration example:
containerd[37139]: containerd: time: missing unit in duration 100000000
Signed-off-by: Mihai Coman <mihai.cmn@gmail.com>
> Fix startup_delay within default configuration

- client.go
- pull.go
When pull image with unpack option, the fetch action will defer blobs
download until unpack. If create image record in ImageService before
blobs download, the following requests to use image will fail because
there is still missing blobs download.
In order to fix concurrent issue, need to create image record after
blobs download.
Fix: #3937
> Pull: create image record after blobs download

- vendor.conf
- vendor/github.com/containerd/cri/pkg/client/client.go
- vendor/github.com/containerd/cri/pkg/server/events.go
- vendor/github.com/containerd/cri/pkg/server/helpers.go
- vendor/github.com/containerd/cri/pkg/server/restart.go
- vendor/github.com/containerd/cri/pkg/store/container/status.go
- vendor/github.com/containerd/cri/vendor.conf
- vendor/gopkg.in/yaml.v2/decode.go
- vendor/gopkg.in/yaml.v2/encode.go
- vendor/gopkg.in/yaml.v2/resolve.go
- vendor/gopkg.in/yaml.v2/scannerc.go
- vendor/gopkg.in/yaml.v2/yaml.go
- vendor/gopkg.in/yaml.v2/yamlh.go
full diff: https://github.com/containerd/cri/compare/bab7348fcfcc795e0dda2cc02e8cac6316c85edc...b075cc4e9f394780dbed101601c48dcc3d37c828
relevant changes:
- containerd/cri#1305 [release/1.2] Sync vendors with containerd
- containerd/cri#1354 [release/1.2] Better handle unknown state
- containerd/cri#1388 [release/1.2] vendor: bump gopkg.in/yaml.v2 v2.2.8
full diff: https://github.com/go-yaml/yaml/compare/v2.2.1...v2.2.8
Includes https://github.com/go-yaml/yaml/commit/bb4e33bf68bf89cad44d386192cbed201f35b241
to address CVE-2019-11253
> [release/1.2] vendor: bump containerd/cri b075cc4e9f394780dbed101601c48dcc3d37c828 (release/1.2 branch)

- snapshots/devmapper/losetup/losetup.go
- snapshots/devmapper/losetup/losetup_test.go
This PR fixes
```
1538    --- FAIL: TestLosetup/RemoveLoopDevicesAssociatedWithImage (0.06s)
1539        losetup_test.go:90: assertion failed: error is not nil: losetup --detach /dev/loop5
1540            error: losetup: /dev/loop5: detach failed: No such device or address
1541            
1542            : exit status 1
1543FAIL
```
that I've seen in other PRs.
> Make losetup tests less flaky

- vendor.conf
- vendor/google.golang.org/grpc/internal/transport/http2_server.go
- vendor/google.golang.org/grpc/internal/transport/http_util.go
- vendor/google.golang.org/grpc/version.go
backport of https://github.com/containerd/containerd/pull/3767
full diff: https://github.com/grpc/grpc-go/compare/v1.23.0...v1.23.1
- grpc/grpc-go#3018 server: set and advertise max frame size of 16KB
- grpc/grpc-go#3017 grpclb: fix deadlock in grpclb connection cache
- Before the fix, if the timer to remove a SubConn fires at the
same time NewSubConn cancels the timer, it caused a mutex leak
and deadlock.
> [release/1.2 backport] bump google.golang.org/grpc v1.23.1

- BUILDING.md
- contrib/Dockerfile.test
Building containerd inside a container showed that the Dockerfile was broken (due to the `golang:1.12.x` image now using Debian Buster as base image)
Nothing critical, but let's make the Dockerfile work again. Backports of:
- https://github.com/containerd/containerd/pull/3814 Fix dependency in BUILDING.md
- fixes https://github.com/containerd/containerd/issues/3813 Dependency missing after following Docker build instructions
- https://github.com/containerd/containerd/pull/3815 Update name for btrfs headers package
> [release/1.2 backport] Fix btrfs packages in contrib Dockerfile

- .mailmap
- releases/v1.2.12.toml
- version/version.go
* Update the runc vendor to v1.0.0-rc10 which includes a mitigation for [CVE-2019-19921](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-19921).
* Update the opencontainers/selinux which includes a mitigation for [CVE-2019-16884](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-16884).
* Update Golang runtime to 1.12.15, which includes a fix to the runtime (Go 1.12.14, Go 1.12.15) and and the `net/http` package (Go 1.12.15)
* A fix to prevent `SIGSEGV` when starting containerd-shim [containerd/containerd#3960](https://github.com/containerd/containerd/pull/3960)
* Fixes to `exec` [containerd/containerd#3755](https://github.com/containerd/containerd/pull/3755)
- Prevent `docker exec` hanging if an earlier `docker exec` left a zombie process
- Prevent High system load/CPU …
> [release/1.2] Prepare v1.2.12 release

- vendor.conf
- vendor/github.com/containerd/cri/vendor.conf
- vendor/gopkg.in/yaml.v2/decode.go
- vendor/gopkg.in/yaml.v2/scannerc.go
- vendor/gopkg.in/yaml.v2/yaml.go
- vendor/gopkg.in/yaml.v2/yamlh.go
full diff: https://github.com/containerd/cri/compare/19589b4bf9663815649f1125fb45a1674d52a702...c0294ebfe0b4342db85c0faf7727ceb8d8c3afce
- containerd/cri#1387 vendor: bump gopkg.in/yaml.v2 v2.2.8
full diff: https://github.com/go-yaml/yaml/compare/v2.2.4...v2.2.8
includes:
- go-yaml/yaml@f90ceb4 Fix check for non-map alias merging in v2
- fix for "yaml.Unmarshal crashes on "assignment to entry in nil map""
- go-yaml/yaml 543 Port stale simple_keys fix to v2
- go-yaml/yaml@1f64d61 Fix issue in simple_keys improvements
- fixes "Invalid simple_keys now cause panics later in decode"
- go-yaml/yaml 555 Optimize cases with long potential simple_keys
> vendor: bump cri, gopkg.in/yaml.v2 v2.2.8

- contrib/autocomplete/ctr
- contrib/autocomplete/zsh_autocomplete
Fix completion when argument startswith `-`
Merged in upstream https://github.com/urfave/cli/pull/1062
> Fix zsh autocomplete script

- remotes/docker/pusher.go
According to [the spec](https://github.com/opencontainers/distribution-spec/blob/master/spec.md):
> Monolithic Upload
A monolithic upload is simply a chunked upload with a single chunk and MAY be favored by clients that would like to avoided the complexity of chunking. To carry out a "monolithic" upload, one can simply put the entire content blob to the provided URL:
```
PUT /v2/<name>/blobs/uploads/<session_id>?digest=<digest>
Content-Length: <size of layer>
Content-Type: application/octet-stream
<Layer Binary Data>
```
> Set octet-stream content-type on put request

- README.md
Dedicated to our anonymous contributor @x448. Thanks for alerting us to this broken link!
Ref: #4014 
> Fix reference to LICENSE in README.md

- platforms/cpuinfo.go
Fixes: #3990 
Don't rely on `/proc/cpuinfo` denoting a 64-bit ARMv8 processor if the
runtime detected `GOARCH` == `arm`. This allows aarch64 32-bit userspace
distros to run containers properly via a 32-bit runtime.
> Support 32-bit userspace on 64-bit ARM cores

- script/setup/install-seccomp
Cherry-pick #4022 for `release/1.3`
> [release/1.3] cherry-pick: Fix incorrect comment from copy/paste of starting script

- .travis.yml
- script/setup/install-seccomp
Besides the fact that lib seccomp 2.4 has huge performance regressions, it also breaks support for older distros like Debian 9 and RHEL/CentOS 7, as discussed in https://github.com/containerd/containerd/issues/4008.
This change pins to 2.3.3 where that is not an issue.
Fixes #4008.
(cherry picked from commits b5f03eacd34c7beffe5c8cc2a5cfee852335f681 and 75d0c5f2e74b44353da357c5603a52871bea3940)
Signed-off-by: Ciprian Hacman <ciprian.hacman@sematext.com>
> [release/1.2 backport] Pin to libseccomp 2.3.3

- .appveyor.yml
- .travis.yml
- contrib/Dockerfile.test
full diff: https://github.com/golang/go/compare/go1.12.16...go1.12.17
go1.12.17 (released 2020/02/12) includes a fix to the runtime. See the Go 1.12.17
milestone on the issue tracker for details:
https://github.com/golang/go/issues?q=milestone%3AGo1.12.17+label%3ACherryPickApproved
> [release/1.3] Update Golang 1.12.17

- .appveyor.yml
- .travis.yml
- contrib/Dockerfile.test
backport of https://github.com/containerd/containerd/pull/4030 for the 1.2 branch
full diff: https://github.com/golang/go/compare/go1.12.16...go1.12.17
go1.12.17 (released 2020/02/12) includes a fix to the runtime. See the Go 1.12.17
milestone on the issue tracker for details:
https://github.com/golang/go/issues?q=milestone%3AGo1.12.17+label%3ACherryPickApproved
> [release/1.2 backport] Update Golang 1.12.17

- script/setup/install-critools
When we call `go get -d -v
github.com/kubernetes-incubator/cri-tools/...` which repos has been
moved to `github.com/kubernetes-sigs/cri-tools`, `go get` will create
package `github.com/kubernetes-sigs/cri-tools`.
```
go get -d -v github.com/kubernetes-incubator/cri-tools/...
github.com/kubernetes-incubator/cri-tools (download)
github.com/kubernetes-sigs/cri-tools (download)
```
According to old version of `github.com/kubernetes-incubator/cri-tools`
Makefile, if there is no `github.com/kubernetes-sigs/cri-tools` package,
it will create softlink self to `github.com/kubernetes-sigs/cri-tools`.
But `go get` will create `github.com/kubernetes-sigs/cri-tools` and
there is no softlink. Therefore, the critools are always latest one, not
specific version.
So, use …
> script: use github.com/kubernetes-sigs/cri-tools directly

- script/setup/install-critools
When we call `go get -d -v
github.com/kubernetes-incubator/cri-tools/...` which repos has been
moved to `github.com/kubernetes-sigs/cri-tools`, `go get` will create
package `github.com/kubernetes-sigs/cri-tools`.
```
go get -d -v github.com/kubernetes-incubator/cri-tools/...
github.com/kubernetes-incubator/cri-tools (download)
github.com/kubernetes-sigs/cri-tools (download)
```
According to old version of `github.com/kubernetes-incubator/cri-tools`
Makefile, if there is no `github.com/kubernetes-sigs/cri-tools` package,
it will create softlink self to `github.com/kubernetes-sigs/cri-tools`.
But `go get` will create `github.com/kubernetes-sigs/cri-tools` and
there is no softlink. Therefore, the critools are always latest one, not
specific version.
So, use …
> [release/1.3 backport] script: use github.com/kubernetes-sigs/cri-tools directly

- script/setup/install-critools
When we call `go get -d -v
github.com/kubernetes-incubator/cri-tools/...` which repos has been
moved to `github.com/kubernetes-sigs/cri-tools`, `go get` will create
package `github.com/kubernetes-sigs/cri-tools`.
```
go get -d -v github.com/kubernetes-incubator/cri-tools/...
github.com/kubernetes-incubator/cri-tools (download)
github.com/kubernetes-sigs/cri-tools (download)
```
According to old version of `github.com/kubernetes-incubator/cri-tools`
Makefile, if there is no `github.com/kubernetes-sigs/cri-tools` package,
it will create softlink self to `github.com/kubernetes-sigs/cri-tools`.
But `go get` will create `github.com/kubernetes-sigs/cri-tools` and
there is no softlink. Therefore, the critools are always latest one, not
specific version.
So, use …
> [release/1.2 backport] script: use github.com/kubernetes-sigs/cri-tools directly

- remotes/docker/pusher.go
Backport #4017 to release/1.2.
Signed-off-by: Josh Dolitsky <393494+jdolitsky@users.noreply.github.com>
> [release/1.2] backport: Set octet-stream content-type on put request

- .appveyor.yml
- .github/workflows/nightly.yml
- .travis.yml
- contrib/Dockerfile.test
full diff: https://github.com/golang/go/compare/go1.13.7...go1.13.8
go1.13.8 (released 2020/02/12) includes fixes to the runtime, the crypto/x509,
and net/http packages. See the Go 1.13.8 milestone on the issue tracker for details.
https://github.com/golang/go/issues?q=milestone%3AGo1.13.8+label%3ACherryPickApproved
> Update Golang 1.13.8

- container_test.go
- runtime/v1/linux/proc/exec.go
- runtime/v1/linux/proc/init.go
- runtime/v1/linux/proc/init_state.go
- runtime/v1/linux/proc/process.go
- runtime/v1/linux/proc/utils.go
alternative for https://github.com/containerd/containerd/pull/4024 ([1.2] Revert #3366)
closes https://github.com/containerd/containerd/pull/4024 ([1.2] Revert #3366)
backport of:
- a6b6097c90c02ad2c8aac45e4f0332dc1a00a60c  https://github.com/containerd/containerd/pull/3857 Fix container pid race condition
- relates to https://github.com/containerd/containerd/pull/3366 / https://github.com/containerd/containerd/pull/3755 Robust pid locking for shim processes
- fixes https://github.com/containerd/containerd/issues/4023 [v1.2] regression in v1.2.12 leaves container/shim hanging
- Minor conflict in `container_test.go`, because https://github.com/containerd/containerd/pull/3743 and https://github.com/containerd/containerd/pull/3046 are not yet backported to the 1.2 branch
- no real …
> [release/1.2 backport] Fix container pid race condition

- .mailmap
- releases/v1.2.13.toml
- version/version.go
depends on:
The thirteenth patch release for `containerd` 1.2 fixes a regression introduced
in v1.2.12 that caused container/shim to hang on single core machines, fixes an
issue with blkio, and updates the Golang runtime to 1.12.17.
Notable Updates
----------------------------------
* Fix container pid race condition [containerd#4025](https://github.com/containerd/containerd/pull/4025)
* Update containerd/cgroups dependency to address blkio issue [containerd#4001](https://github.com/containerd/containerd/pull/4001)
* Set octet-stream content-type on PUT request [containerd#4028](https://github.com/containerd/containerd/pull/4028)
* Pin to libseccomp 2.3.3 to preserve compatibility with hosts that do not have libseccomp 2.4 or up installed …
> [release/1.2] Prepare v1.2.13 release

- vendor.conf
- vendor/golang.org/x/crypto/ssh/terminal/terminal.go
related PR in containerd/cri: https://github.com/containerd/cri/pull/1402
full diff: https://github.com/golang/crypto/compare/69ecbb4d6d5dab05e49161c6e77ea40a030884e1...1d94cc7ab1c630336ab82ccb9c9cda72a875c382
I'm doing a around across repositories to update in preparation of a security release that was announced for tomorrow (so that we can update again with just the changes related to that fix);
https://groups.google.com/d/msgid/golang-announce/CA%2B2K_Kox3xkjj6gWkp%3DY6fmp7sO4T%2BbgudjjZZ%3Duwgp476pmEw%40mail.gmail.com
> vendor: golang.org/x/crypto 1d94cc7ab1c630336ab82ccb9c9cda72a875c382

- image_test.go
TestImageIsUnpacked will unpacked docker.io/library/busybox:latest with
linux/amd64 platform. If the TestImageUsage doesn't wait for cleanup
finish (snapshotter is cleanup by gc asynchronously) and fetch image,
the Usage(ctx) will get 10767844 bytes(manifestUsage + snapshotUsage).
However, the manifestUsage is 9466142 bytes. That is why we got the
error:
```
Expected actual usage to equal manifest reported usage of 9466142:
got 10767844
```
This commit is to make sure that the image has been cleanup fully.
> cleanup the image synchronously for Usage case

- runtime/v1/linux/runtime.go
When there is timeout or cancel for create container, killShim will fail
because of canceled context. The shim will be dangling and unmanageable.
Need to use new context to do cleanup.
(cherry picked from commit 18e581dd91fd671aaeba86dcae2b6c97142a1cb0)
from #4052
> [release/1.2 backport] bugfix: cleanup dangling shim by brand new context

- .appveyor.yml
Downloading packages is quite noisy in the logs. This patch disables
the download progress output, which should save +/- 4000 lines of
output;
```
[00:00:15] Progress: Downloading mingw 5.3.0... 12%
[00:00:15] Progress: Downloading mingw 5.3.0... 35%
[00:00:15] Progress: Downloading mingw 5.3.0... 58%
[00:00:15] Progress: Downloading mingw 5.3.0... 82%
[00:00:15] Progress: Downloading mingw 5.3.0... 100%
[00:00:15] 
[00:00:15] mingw v5.3.0 [Approved]
[00:00:15] mingw package files install completed. Performing other installation steps.
[00:00:17] Get-BinRoot is going to be deprecated in v1 and removed in v2. It has been replaced with Get-ToolsLocation (starting with v0.9.10), however many packages no longer require a special separate directory since package folders no longer have versions …
```
> AppVeyor: disable download progress on choco installs

- content/local/store.go
- content/testsuite/testsuite.go
backport of https://github.com/containerd/containerd/pull/3324
hopefully addresses https://github.com/containerd/containerd/issues/3701 for the 1.2 branch
> [release/1.2 backport] Ensure close in content test

- runtime/v2/runc/v1/service.go
backport of https://github.com/containerd/containerd/pull/4063, which was a follow-up to https://github.com/containerd/containerd/pull/3149. (relates to https://github.com/moby/moby/issues/38978)
> [release/1.3 backport] fix killall when use pidnamespace

- runtime/v2/runc/v2/service.go
For service#StartShim, the deferred func was referencing error variable err which is declared prior to line 204. And the error return is not named.
Meaning, the deferred func wouldn't check err variables on and after line 211.
This PR changes the return values to be named (and makes the deferred func operational).
> Use named error return for service#StartShim

- .appveyor.yml
- .travis.yml
- contrib/Dockerfile.test
Go 1.14 has been released, which means that Go 1.12 reached EOL, so updating supported branches to Go 1.13
This pull request backports updates to Golang 1.13 and related changes.
I first reverted the intermediate 1.12.x updates in the branch, then cherry-picked
each bump from master; doing so to preserve the commit message from those, and
to make sure we didn't miss changes associated with each Go update.
Updates to `.github/workflows/nightly.yml`, were ignored, because that file is not
not in the 1.3 branch.
backports of:
- revert https://github.com/containerd/containerd/pull/4030 [release/1.3] Update Golang 1.12.17
- revert golang bump from https://github.com/containerd/containerd/pull/3989 [release/1.3] Update Golang 1.12.16, x/crypto (CVE-2020-0601, CVE-2020-7919)
- revert …
> [release/1.3 backport] Update to Golang 1.13.8

- .appveyor.yml
- .travis.yml
- client_test.go
- contrib/Dockerfile.test
- platforms/database.go
~based on top of https://github.com/containerd/containerd/pull/4061~ (merged)
Go 1.14 has been released, which means that Go 1.12 reached EOL, so updating supported branches to Go 1.13
This pull request backports updates to Golang 1.13 and related changes.
I first reverted the intermediate 1.12.x updates in the branch, then cherry-picked
each bump from master; doing so to preserve the commit message from those, and
to make sure we didn't miss changes associated with each Go update.
Updates to `travis.yml` in this branch don't apply cleanly due to travis.yml being
refactored on master; for those I applied the equivalent changes, but keeping the
original commit message.
backports of:
- https://github.com/containerd/containerd/pull/3744 Move flag.Parse in tests to TestMain
- …
> [release/1.2 backport] Update to Golang 1.13.8

- cmd/containerd/builtins_cri.go
The builtins_cri_linux.go file only being included for _linux builds which
means that the builds for Windows do not contain the CRI plugin. This can
be disabled for either platform with the no_cri tag.
Picking up the change from #4047 and fixing the file header to pass CI.
> Enable CRI plugin for Windows builds as well

- cmd/ctr/commands/containers/containers.go
This flag makes it easy to view only the OCI spec for the container.
> Add ctr c info --spec flag to output spec

- runtime/v1/shim/service.go
- runtime/v2/runc/util.go
- runtime/v2/runc/v1/service.go
- runtime/v2/runc/v2/service.go
Signed-off-by: Ted Yu <yuzhihong@gmail.com>
Closes #4057
The changes I made were to unify the method for the v2 shims and update the logging strings as well as removing the error return on this method.
> [carry] Check error return from json.Unmarshal

- vendor.conf
follow-up to https://github.com/containerd/containerd/pull/4042
closes https://github.com/containerd/containerd/issues/4082
This version contains a fix for CVE-2020-9283, but the code-path is not in use in this repository.
Updating the dependency in case people are concerned that we use a version of the dependency that doesn't have the fix.
> vendor: bump golang.org/x/crypto bac4c82f6975

- client.go
- client_opts.go
- pull.go
- rootfs/apply.go
- snapshots/snapshotter.go
- unpacker.go
This PR is a variation of https://github.com/containerd/containerd/pull/4044.
There are cases when, in addition to `ChainID`, a remote snapshotter needs to know more context about an image - API URL to query remote layer from, credentials to use, etc.
It would be useful to have this info passed from the client.
This PR slighly extends `WithPullSnapshotter` to pass extra labels to a snapshotter.
@ktock @dmcgowan would be interested in your opinion on this.
> Pass snapshotter opts from client Pull

- RELEASES.md
1. Update release status
2. Add Extended state for release v1.2
> RELEASES.md: update release status

- runtime/v1/shim/service.go
For checkProcesses(), we obtain slice of Processes via allProcesses() and only use one of them where Pid matches.
allProcesses() is not exported and not used elsewhere in service.go.
This PR replaces allProcesses() by finding Process given Pid inside checkProcesses().
> Avoid allocating slice for finding Process

- metrics/cgroups/v1/cgroups.go
- metrics/cgroups/v1/metrics.go
- metrics/cgroups/v2/cgroups.go
- metrics/cgroups/v2/metrics.go
This makes it easier to extend the collectors to be used by external code and
task managers
> export cgroups collectors

- sys/epoll.go
These were not used and just an alias for the ones in golang.org/x/sys/unix
> sys: deprecate EpollCreate1, EpollCtl, EpollWait

- sys/filesys_windows.go
reverts some changes from https://github.com/containerd/containerd/pull/4093
- preserve `syscall.ENOTDIR` to match os.MkDirAll
- change back parameter name to `adminAndLocalSystem`
- revert accidental change of permissions of parent-dir 😓 (my bad)
see the discussion on https://github.com/moby/moby/pull/40645#discussion_r389694799
> Partial revert of sys: windows: use golang.org/x/sys/windows

- client.go
- runtime/v2/runc/v1/service.go
- runtime/v2/runc/v2/service.go
Re-use the import aliased as `ptypes`.
Signed-off-by: Tobias Klauser <tklauser@distanz.ch>
> Avoid duplicate imports of github.com/gogo/protobuf/types

- mount/mountinfo_linux.go
- oci/spec_opts.go
- runtime/v2/README.md
The `Err()` method should be called after the `Scan()` loop, not inside it.
Found by: `git grep -A3 -F '.Scan()'`
> Nit: fix use of bufio.Scanner.Err

- snapshots/devmapper/README.md
- snapshots/devmapper/config.go
- snapshots/devmapper/metadata.go
- snapshots/devmapper/pool_device.go
- snapshots/devmapper/snapshotter.go
Snapshots GC takes use of pruneBranch() function to remove snapshots,
but GC will stop if snapshotter.Remove() returns error and the error
number is not ErrFailedPrecondition. This results in thousands of
dm snapshots not deleted if one snapshot is not deleted, due to
errors like "contains a filesystem in use".
1. the first method:
So return ErrFailedPrecondition error number in Remove() function where
appropriate, and let GC process go on collecting other snapshots.
2. the second method:
Also, we add a "async_remove" for devmapper as overylay does, mark the snapshot as `removed` quickly,  and really delete it on the next cleanup() method.
I'd like to have both them merged, so that:
- the first way doesn't have overhead to iterate devices to find the `removed` device to cleanup, it should …
> snapshots/devmapper: do not stop snapshot GC when one snapshot removing fails

- client_ttrpc_test.go
- pkg/ttrpcutil/client.go
- runtime/v2/shim/publisher.go
fixes #3971 
As indicated in #3971 by @wswfc, this problem is fixed by https://github.com/containerd/containerd/pull/3204/commits/047348e198cc17404e34717d00ece685bfe3fbfa , but reintroduced by #3279 
This PR only add a similar mechanism like #3204 .
Don't get a real conn when we create a new event publisher, but create a `connector`, and we use this `connector` to get a real conn when we want to forward a event.
@mxpv @crosbymichael PTAL
Signed-off-by: lifubang <lifubang@acmcoder.com>
> fix dial error when clean up a dead shim

- cmd/containerd/command/main.go
- cmd/containerd/command/main_unix.go
- cmd/containerd/command/main_windows.go
- cmd/containerd/command/notify_linux.go
- cmd/containerd/command/notify_unsupported.go
- containerd.service
- vendor/github.com/coreos/go-systemd/daemon/sdnotify.go
- vendor/github.com/coreos/go-systemd/daemon/watchdog.go
Backporting fix for https://github.com/containerd/containerd/issues/4043 from PR in master https://github.com/containerd/containerd/pull/4088
Picking up the change in master for notifying systemd when containerd is ready : ddae905b824a264be620cea03d3dee66f779f19a
> [release/1.3 backport] Backport notify socket support

- runtime/v2/shim/shim.go
Request came from a slack message that shims do not output their versions making
it hard for users and operators to know what version of a shim they have on the
system.  This adds a `-v` flag to the shims so that users can see if a shim is
in sync with containerd or what versions of shims that they are running.
> add -v to shim binaries

- signals_test.go
- signals_unix.go
The kernel will return an error anyway.
> ParseSignal: drop add'l check for numeric signals

- snapshots/devmapper/README.md
This PR adds a few examples of how to configure devmapper thin-pool device. 
This should lower entry barrier of using devmapper snapshotter.
ref: https://github.com/containerd/containerd/issues/3931
> Add devmapper configuration examples

- archive/tar_unix.go
handleLChmod() does not properly check that files behind the handlinks exist
before calling os.Chmod(). We've seen base images where this results in
"no such file or directory" error from os.Chmod() when unpacking the image.
os.Stat() follows symlinks and tells us if the destination file exists.
Use that as the pre-check before os.Chmod() to avoid errors.
The failing case for me was:
`sudo ctr i pull docker.io/library/clearlinux:base`
> archive: skip chmod IsNotExist error

- vendor.conf
The following repos have been tagged as v1.0.0:
- https://github.com/containerd/console/commit/8375c3424e4d7b114e8a90a4a40c8e1b40d1d4e6
- https://github.com/containerd/ttrpc/commit/92c8520ef9f86600c650dd540266a007bf03670f
- https://github.com/containerd/typeurl/commit/a93fcdb778cd272c6e9b3028b2f42d813e785d40
> Add version numbers for newly tagged repos

- vendor.conf
Update `containerd/cri` in release/1.3 branch.
Signed-off-by: Salvador Fuentes <salvador.fuentes@intel.com>
Hi, 
Want to update the `containerd/cri` commit in the `vendor.conf` as we use this entry to checkout and run cri tests using kata-containers and current commit is broken when running the tests with go1.13. The new `cri` commit fixes that issue. 
There are no changes in the `vendor` directory as the fix only touches tests files.
> [release/1.3] vendor containerd/cri f864905c93b97db15503c217dc9a43eb65670b53

- metrics/cgroups/v1/metric.go
- metrics/cgroups/v2/metric.go
This makes the metrics package more extensible by allowing the default name of
`container_id` to be changed by the package caller.
> Allow the id for cgroup metrics to be changed

- BUILDING.md
Since CRI is compiled in with containerd, builders should be aware that
these buildtags are available.
> Add docs for build tags used by cri.

- container.go
- pkg/process/io.go
- sys/filesys.go
Fixes: #4019
Only delete files which are FIFOs and only delete directories which are empty after deleting FIFOs.
*Also contains a commit to move `isFifo()` from a private function in pkg/process/io.go to a public function in `sys/`*
> Correct logic of FIFO cleanup

- .github/workflows/checks.yml
This PR ports the majority of our checks that we currently do on Travis (golangci-lint, dco, headers, vendor, protobuf).
Currently `golangci-lint` doesn't pass on windows platform, so I disabled them. Will follow up once I get proper env. 
@estesp I took your DCO checks, hope you don't mind :) 
> Move checks to Github actions

- vendor.conf
- vendor/go.etcd.io/bbolt/README.md
- vendor/go.etcd.io/bbolt/bolt_386.go
- vendor/go.etcd.io/bbolt/bolt_amd64.go
- vendor/go.etcd.io/bbolt/bolt_arm.go
- vendor/go.etcd.io/bbolt/bolt_arm64.go
- vendor/go.etcd.io/bbolt/bolt_mips64x.go
- vendor/go.etcd.io/bbolt/bolt_mipsx.go
- vendor/go.etcd.io/bbolt/bolt_ppc.go
- vendor/go.etcd.io/bbolt/bolt_ppc64.go
- vendor/go.etcd.io/bbolt/bolt_ppc64le.go
- vendor/go.etcd.io/bbolt/bolt_riscv64.go
- vendor/go.etcd.io/bbolt/bolt_s390x.go
- vendor/go.etcd.io/bbolt/bolt_unix_aix.go
- vendor/go.etcd.io/bbolt/bucket.go
- vendor/go.etcd.io/bbolt/cursor.go
- vendor/go.etcd.io/bbolt/db.go
- vendor/go.etcd.io/bbolt/freelist.go
- vendor/go.etcd.io/bbolt/freelist_hmap.go
- vendor/go.etcd.io/bbolt/go.mod
- vendor/go.etcd.io/bbolt/node.go
- vendor/go.etcd.io/bbolt/page.go
- vendor/go.etcd.io/bbolt/tx.go
full diff: https://github.com/etcd-io/bbolt/compare/v1.3.3...v1.3.4
- Fix unsafe pointer conversions caught by Go 1.14 checkptr
- Fix unexpected delete bucket error: "delete bucket: incompatible value"
- Add support for aix
- Add go.mod
- db.Path() resolves to db.file.Name()
As mentioned in https://github.com/containerd/containerd/pull/4050#issuecomment-596146277 - this update fixes issues when using Go 1.14 / revealed by Go 1.14
> vendor: update go.etcd.io/bbolt v1.3.4

- remotes/docker/handler_test.go
> Add unit test for func in remotes/docker/handler.go

- runtime/v1/linux/proc/utils.go
From #4020 . When use cri-containerd and k8s, pod may be  stuck in terminating. It happens when container is delete by runc, however containerd unawares of this or deletes container failed.  When cri retry to delete container it will got a runc error `container <cid> does not exist`. This is because cri ignore IsNotFound error, but shim is not converting the runc error to a containerd NotFound error.
> when kill a container check if it has been deleted

- Makefile
- docs/man/containerd-config.1.md
- docs/man/containerd-config.toml.5.md
The generated file was incorrectly named containerd.1 and should
be in section 8 (see [MAN-PAGES(7)]: Sections of the manual pages)
This patch fixes the filename and updates references to containerd(1)
to refer to containerd(8).
The generated file itself already had the correct section set in its
header, so didn't need updating.
[MAN-PAGES(7)]: http://man7.org/linux/man-pages/man7/man-pages.7.html
> Makefile: man page: rename containerd.1 to containerd.8

- Makefile
- cmd/gen-manpages/main.go
- docs/man/containerd-config.8.md
- docs/man/containerd-config.toml.5.md
I missed this in my previous change: the ctr man page is also in Section 8, because it's considered an administrative tool, and containerd-config is related to containerd so updating these as well.
> man: move ctr.1 and containerd-config to section 8

- vendor.conf
- vendor/go.etcd.io/bbolt/README.md
- vendor/go.etcd.io/bbolt/bolt_386.go
- vendor/go.etcd.io/bbolt/bolt_amd64.go
- vendor/go.etcd.io/bbolt/bolt_arm.go
- vendor/go.etcd.io/bbolt/bolt_arm64.go
- vendor/go.etcd.io/bbolt/bolt_mips64x.go
- vendor/go.etcd.io/bbolt/bolt_mipsx.go
- vendor/go.etcd.io/bbolt/bolt_ppc.go
- vendor/go.etcd.io/bbolt/bolt_ppc64.go
- vendor/go.etcd.io/bbolt/bolt_ppc64le.go
- vendor/go.etcd.io/bbolt/bolt_riscv64.go
- vendor/go.etcd.io/bbolt/bolt_s390x.go
- vendor/go.etcd.io/bbolt/bolt_unix_aix.go
- vendor/go.etcd.io/bbolt/bucket.go
- vendor/go.etcd.io/bbolt/cursor.go
- vendor/go.etcd.io/bbolt/db.go
- vendor/go.etcd.io/bbolt/freelist.go
- vendor/go.etcd.io/bbolt/freelist_hmap.go
- vendor/go.etcd.io/bbolt/go.mod
- vendor/go.etcd.io/bbolt/node.go
- vendor/go.etcd.io/bbolt/page.go
- vendor/go.etcd.io/bbolt/tx.go
backport of https://github.com/containerd/containerd/pull/4134
full diff: https://github.com/etcd-io/bbolt/compare/v1.3.3...v1.3.4
- Fix unsafe pointer conversions caught by Go 1.14 checkptr
- Fix unexpected delete bucket error: "delete bucket: incompatible value"
- Add support for aix
- Add go.mod
- db.Path() resolves to db.file.Name()
> [release/1.3 backport] vendor: update go.etcd.io/bbolt v1.3.4

- vendor.conf
- vendor/github.com/containerd/console/console.go
- vendor/github.com/containerd/console/console_linux.go
- vendor/github.com/containerd/console/console_unix.go
- vendor/github.com/containerd/console/console_windows.go
- vendor/github.com/containerd/console/go.mod
backports of:
- https://github.com/containerd/containerd/pull/4125 Add version numbers for newly tagged repos
- https://github.com/containerd/containerd/pull/3906 Update containerd/console vendor for fix
- brings in https://github.com/containerd/console/pull/34 Only close epoller FD at most once
- relates to https://github.com/containerd/containerd/issues/3895 runtime: runc v2 shim closes platform prematurely and multiple times
- relates to https://github.com/firecracker-microvm/firecracker-containerd/issues/363 TestMultipleVMs: "bad file descriptor" cleaning up task bundle in agent 
- https://github.com/containerd/containerd/pull/3878 Bump containerd console for os.File changes
> [release/1.3 backport] Update containerd/console vendor for fix

- container.go
- pkg/process/io.go
- sys/filesys.go
backport of https://github.com/containerd/containerd/pull/4123
fixes https://github.com/containerd/containerd/issues/4019 for the 1.3 branch
> [release/1.3 backport] Correct logic of FIFO cleanup

- vendor.conf
- vendor/github.com/containerd/console/LICENSE
- vendor/github.com/containerd/console/README.md
- vendor/github.com/containerd/console/console.go
- vendor/github.com/containerd/console/console_linux.go
- vendor/github.com/containerd/console/console_unix.go
- vendor/github.com/containerd/console/console_windows.go
- vendor/github.com/containerd/console/go.mod
backports of:
- https://github.com/containerd/containerd/pull/3906 Update containerd/console vendor for fix
- brings in https://github.com/containerd/console/pull/34 Only close epoller FD at most once
- relates to https://github.com/containerd/containerd/issues/3895 runtime: runc v2 shim closes platform prematurely and multiple times
- relates to https://github.com/firecracker-microvm/firecracker-containerd/issues/363 TestMultipleVMs: "bad file descriptor" cleaning up task bundle in agent 
- https://github.com/containerd/containerd/pull/3878 Bump containerd console for os.File changes
- https://github.com/containerd/containerd/pull/3223 Bump syndtr/gocapability d983527, containerd/console
> [release/1.2 backport] Update containerd/console vendor for fix

- remotes/docker/config/hosts.go
- remotes/docker/config/hosts_test.go
If there is not specific host config, like ctr does, the resolver will
fail to get host path. And this patch is to add default host config if
needs.
And default config host config should have all caps for pull and push.
> bugfix: add default host config if not set

- vendor.conf
- vendor/github.com/docker/go-events/retry.go
- relates to moby/buildkit 1111
- relates to moby/buildkit 1079
- relates to docker/buildx 129
full diff: https://github.com/docker/go-events/compare/9461782956ad83b30282bf90e31fa6a70c255ba9...e31b211e4f1cd09aa76fe4ac244571fab96ae47f
> vendor: update go-events to fix alignment for 32bit systems

- .github/workflows/ci.yml
Also few changes to names of workflow jobs. Integration tests can get
canceled without full completing at 10 minutes.
> Update integration test timeout

- .travis.yml
Reduce duplication while we test GH actions.
For now:
- no Darwin/macOS build: done in Actions and is a simple build with no testing
- project "pre-checks" (DCO, whitespace, vendor, golangci-lint) all working well in actions
- remove protobufs checks; working well in actions
- remove manpage generation test (also working fine in actions)
> Start removal of Travis CI components

- pkg/process/io.go
- runtime/v2/logging/logging.go
A few changes in shim logger process shutdown flow:
- Close pipes first, so shim logger's `s.Scan()` exit loops.
- Rework shutdown flow, so the process receives SIGTERM first (so logger implementations can process cancelled context) with configured timeout, and then kills the process. SIGTERM timeout can be configured with `io.containerd.timeout.shim.logger.shutdown` timeout key.
- Reworks error handling a bit.
Fixes: #4159
> Rework shim logger shutdown process

- sys/mount_linux.go
forkAndMountat forks a process to chdir then mount layers. Signals are
blocked (using runtime_beforeFork) during fork.
There is a race condition that the child process finishes before the
parent process is scheduled and can unblock signal handling. The SIGCHLD
signal sent from the finished process may have been delivered to the
shim process's reaper thread and caused the parent process fail with
ECHLD error.
This patch sets up a pipe for communication between child and parent
instead of waiting for child exit status.
Fixes #4009.
> sys/mount_linux: use pipe for communicating mount result

- .appveyor.yml
- .github/workflows/ci.yml
- .github/workflows/nightly.yml
- .travis.yml
- contrib/Dockerfile.test
go1.13.10 (released 2020/04/08) includes fixes to the go command, the runtime,
os/exec, and time packages. See the Go 1.13.10 milestone on the issue tracker
for details:
https://github.com/golang/go/issues?q=milestone%3AGo1.13.10+label%3ACherryPickApproved
full diff: https://github.com/golang/go/compare/go1.13.9...go1.13.10
> Bump Golang 1.13.10

- .appveyor.yml
- .travis.yml
- contrib/Dockerfile.test
backport of https://github.com/containerd/containerd/pull/4145 and https://github.com/containerd/containerd/pull/4169
go1.13.10 (released 2020/04/08) includes fixes to the go command, the runtime,
os/exec, and time packages. See the Go 1.13.10 milestone on the issue tracker
for details:
https://github.com/golang/go/issues?q=milestone%3AGo1.13.10+label%3ACherryPickApproved
full diff: https://github.com/golang/go/compare/go1.13.9...go1.13.10
> [release/1.3 backport] Bump Golang 1.13.10

- vendor.conf
- vendor/github.com/docker/go-events/retry.go
backport of https://github.com/containerd/containerd/pull/4153
- relates to moby/buildkit 1111
- relates to moby/buildkit 1079
- relates to docker/buildx 129
full diff: https://github.com/docker/go-events/compare/9461782956ad83b30282bf90e31fa6a70c255ba9...e31b211e4f1cd09aa76fe4ac244571fab96ae47f
(cherry picked from commit 056d60224046ef4ede772633ebdba6c61784be3b)
> [release/1.3 backport] vendor: update go-events to fix alignment for 32bit systems

- .appveyor.yml
- .travis.yml
- contrib/Dockerfile.test
backport of https://github.com/containerd/containerd/pull/4145 and https://github.com/containerd/containerd/pull/4169
go1.13.10 (released 2020/04/08) includes fixes to the go command, the runtime,
os/exec, and time packages. See the Go 1.13.10 milestone on the issue tracker
for details:
https://github.com/golang/go/issues?q=milestone%3AGo1.13.10+label%3ACherryPickApproved
full diff: https://github.com/golang/go/compare/go1.13.9...go1.13.10
> [release/1.2 backport] Bump Golang 1.13.10

- .github/workflows/ci.yml
This file was still on Go 1.13.8, which caused it to be missed when updating Go 1.13.9 to 1.13.10
> CI: Some Go 1.13.10 updates that were missed

- vendor.conf
Continue using git tags to pin vendors when available. This needs needs more discussion on master and was not agreed on to backport. This currently breaks the release tool version comparison logic. Going forward, either the release tool needs to be updated to resolve sha to tag (and vendor checking validating tag comments), or we continue to use git tags to pin vendors.
> [release/1.3] revert pin vendors by git sha

- Makefile
A simple `grep selinux_stub bin/containerd` shows that we are not using
selinux tag when building containerd. The CRI plugin pulls in a bunch of
selinux related code, so we need to enable this tag as well.
> CRI plugin needs selinux tag as well

- README.md
Updates the build pass/fail status from using Travis indicator to GH Actions indicator; also fix nightlies to have a link to status.
> Use GH Actions CI status for badge

- BUILDING.md
- script/setup/install-runc
docker-ce seems to be building runc with selinux support, let us follow
the same pattern here please:
https://github.com/docker/docker-ce/search?p=1&q=RUNC_BUILDTAGS&unscoped_q=RUNC_BUILDTAGS
> Build runc with selinux support

- vendor.conf
- vendor/github.com/containerd/cgroups/blkio.go
Backport cgroups bug fix https://github.com/containerd/cgroups/pull/147
master: https://github.com/containerd/containerd/pull/4146
> [release/1.3 backport] cgroups: throttle.* metrics must be kept for non-CFQ schedulers

- .github/workflows/ci.yml
- script/setup/install-cni
- script/setup/install-critools
- script/setup/install-runc
Integration tests were running with latest Go release rather than the
version used everywhere else. Also, we don't need to install protoc from
tarball and also apt-get the package for Ubuntu when used as a
dependency for criu build.
> Small fixes to our Actions CI workflow

- .travis.yml
This allows Travis to continue running on PRs for release/1.x branches
where we have not enabled GH Actions.
> Disable Travis CI on master

- docs/getting-started.md
- docs/ops.md
This was changed to `no_subreaper` in
6e9f24b71129ea9457ad707b0880a8277232ab3b and, as far as I can tell,
`no_subreaper` doesn't exist as a config anymore.
> This config no longer exists, so remove from docs.

- pkg/process/io.go
- pkg/process/io_test.go
This PR:
- Addresses @fuweid's [comment](https://github.com/containerd/containerd/pull/4162/files#r405644727) to cleanup allocated resources in case of error in `NewBinaryIO`.
- Hardcodes SIGTERM timeout to 10 seconds. No longer rely on `timeout` package, since shim binary doesn't load `config.toml` file and hence doesn't contain configured timeouts.
- Adds tests to make sure proper resource cleanup (by counting open descriptors).
> Binary IO fixes and tests

- runtime/v2/shim.go
- vendor.conf
- vendor/github.com/containerd/ttrpc/client.go
- vendor/github.com/containerd/ttrpc/go.mod
For some reason, shimv2 process doesn't exist. The ttrpc doesn't detect
the connection closed by server until delete task. For this case, we
should ignore the ttrpc.ErrClosed and let task manager handle the
cleanup.
And update ttrpc vendor with 6e416eafd26e6e738df716b21d421d5b59702bb4 to have better ErrClosed filter.
> runtime: ignore ttrpc closed error

- .zuul/playbooks/containerd-build/run.yaml
- runtime/v2/shim/shim_test.go
* update go version for aarch64 testing
* fix flaky test case
* TestRuntimeWithEmptyMaxEnvProcs should restore the GoMaxProcs after
test so that the temporary change of GoMaxProcs will not impact other
case, like TestRuntimeWithNonEmptyMaxEnvProcs.
> .zuul: update go version to 1.13.10

- client_test.go
Test hardcoded 2 seconds and in GitHub actions we see a cancel randomly
right at 2 seconds even though containerd is within milliseconds of
being ready.
Example:
```
FAIL	github.com/containerd/containerd	2.043s
```
> Allow more time for containerd to start for integration

- vendor.conf
- vendor/github.com/konsorten/go-windows-terminal-sequences/README.md
- vendor/github.com/konsorten/go-windows-terminal-sequences/sequences.go
- vendor/github.com/konsorten/go-windows-terminal-sequences/sequences_dummy.go
full diff: https://github.com/konsorten/go-windows-terminal-sequences/compare/v1.0.1...v1.0.3
- Fixes a panic when using logrus on Go 1.14
- Fix compile error on linux and darwin
> vendor konsorten/go-windows-terminal-sequences v1.0.3

- cmd/containerd-shim/shim_linux.go
Libcontainer was only used for a single function, which in itself was just a tiny wrapper around `golang.org/x/sys/unix`; https://github.com/opencontainers/runc/blob/dbe44cbb1099eabfaa753322be2055a0a6e8fe2d/libcontainer/system/linux.go#L127-L130
```go
// SetSubreaper sets the value i as the subreaper setting for the calling process
func SetSubreaper(i int) error {
return unix.Prctl(unix.PR_SET_CHILD_SUBREAPER, uintptr(i), 0, 0, 0)
}
```
This patch replaces it with the implementation in our sys package
> Remove libcontainer from containerd-shim

- vendor.conf
- vendor/github.com/sirupsen/logrus/entry.go
- vendor/github.com/sirupsen/logrus/go.mod
- vendor/github.com/sirupsen/logrus/text_formatter.go
v1.6.0 was just released to fix some regressions in v1.5.0
full diff: https://github.com/sirupsen/logrus/compare/v1.5.0...v1.6.0
- Add flag to disable quotes in TextFormatter
- Revert "fix race conditions on entry"
- fixes Deadlock during Entry.Infof after upgrade to v1.5.0
- fixes Deadlock when using WithField inside of hook
- fixes Overly-aggressive mutex locks
> vendor: sirupsen/logrus v1.6.0

- archive/tar_unix.go
- diff/apply/apply_linux.go
- sys/oom_unix.go
- sys/userns_linux.go
- sys/userns_unsupported.go
follow-up to https://github.com/containerd/containerd/pull/4227
after this, the only remaining use of this package is in containerd/cri, for which I'll open a PR
> Remove remaining uses of libcontainer/system package

- snapshots/devmapper/pool_device.go
- snapshots/devmapper/snapshotter.go
The issue beblow happens several times beforing the root
cause found:
1. A `fdisk -l` process has being hung up for a long time;
2. A image layer snapshot device is visiable to dmsetup, which
should *not* happen because it should be deactivated after
`Commit()`;
The backtrace of `fdisk` is always the same over time:
```bash
[<ffffffff810bbc6a>] io_schedule+0x2a/0x80
[<ffffffff81295a3f>] do_blockdev_direct_IO+0x1e9f/0x2f10
[<ffffffff81296aea>] __blockdev_direct_IO+0x3a/0x40
[<ffffffff81290e43>] blkdev_direct_IO+0x43/0x50
[<ffffffff811b8a14>] generic_file_read_iter+0x374/0x960
[<ffffffff81291ad5>] blkdev_read_iter+0x35/0x40
[<ffffffff8125229b>] new_sync_read+0xfb/0x240
[<ffffffff81252406>] __vfs_read+0x26/0x40
[<ffffffff81252b96>] vfs_read+0x96/0x130
[<ffffffff812540e5>] SyS_read+0x55/0xc0 …
```
> snapshots/devmapper: fix race windown causing IO hangup

- .github/workflows/ci.yml
- script/setup/install-runc
Signed-off-by: fahedouch fahed.dorgaa@gmail.com
removing `sudo` from the script  `install-runc` command lines and call  `install-runc` with sudo privileges using `gosu` in GH Actions ci.
PS : Sudo and Golang do not get along in GH Actions. ([source](https://github.com/containerd/containerd/pull/4224#issuecomment-622990022))
> [ci] install runc with gosu

- cmd/ctr/commands/images/images.go
- cmd/ctr/commands/images/mount.go
- cmd/ctr/commands/images/unmount.go
- lease.go
Example:
```terminal
$ mkdir /opt/busybox
$ ctr image mount docker.io/library/busybox:latest /opt/busybox
/opt/busybox
$ ls -lh /opt/busybox
total 40K
drwxr-xr-x 2 root   root     12K Apr 14 01:10 bin
drwxr-xr-x 2 root   root    4.0K Apr 14 01:10 dev
drwxr-xr-x 3 root   root    4.0K Apr 14 01:10 etc
drwxr-xr-x 2 nobody nogroup 4.0K Apr 14 01:10 home
drwx------ 2 root   root    4.0K Apr 14 01:10 root
drwxrwxrwt 2 root   root    4.0K Apr 14 01:10 tmp
drwxr-xr-x 3 root   root    4.0K Apr 14 01:10 usr
drwxr-xr-x 4 root   root    4.0K Apr 14 01:10 var
$ ctr image unmount /opt/busybox
$ ls -lh /opt/busybox
total 0
```
---
I was writing this for myself, basically, and thought this may be interesting for `ctr`. It's a lot simpler than manually creating all the things... figured I'd it it out …
> Add commands to mount/unmount image from ref

- archive/tar.go
- archive/tar_test.go
- container_linux_test.go
- container_opts.go
- errdefs/errors.go
- errdefs/grpc_test.go
- events/exchange/exchange_test.go
- images/handlers.go
- lease_test.go
- metadata/containers_test.go
- metadata/images_test.go
- metadata/leases_test.go
- plugin/plugin.go
- remotes/docker/pusher.go
- remotes/docker/resolver.go
- remotes/docker/resolver_test.go
- runtime/v1/linux/process.go
- runtime/v1/linux/task.go
- runtime/v2/process.go
- runtime/v2/shim.go
- runtime/v2/shim_windows.go
- snapshots/btrfs/btrfs_test.go
- snapshots/devmapper/metadata_test.go
- sys/mount_linux_test.go
- unpacker.go
follow-up to https://github.com/containerd/containerd/pull/4237
Dependencies may be switching to use the new `%w` formatting option to wrap errors; switching to use `errors.Is()` makes sure that we are still able to unwrap the error and detect the underlying cause.
> Replace errors.Cause() with errors.Is()

- vendor.conf
- vendor/github.com/modern-go/reflect2/type_map.go
- Reverts change from tagged versions to sha. Maintainers agreed to use tagged versions before 1.3 release, this fixes the issue before 1.4.
- Removes tag ambiguity on what version a sha points to when multiple tags available. The sha may end up representing the release commit or the sha of the tag object, when it points to a release commit, multiple tags are possible adding ambiguity to automated tag dereferencing. Parsing the comment to reduce the ambiguity is not a great solution for the release tooling.
- Fixes sync issue between tag in comment and sha, the selinux comment was incorrect here.
- Updates reflect2 library to correctly tagged version, includes global variable fix.
> Use tagged versions in vendor file

- .github/workflows/ci.yml
- container_test.go
- pkg/process/utils.go
From #4020 #4019 
We encountered the same problem after upgrading containerd from v1.2.7 to v1.3.3 .Same as pr #4121.
> When use cri-containerd and k8s, pod may be stuck in terminating. It happens when container is delete by runc, however containerd unawares of this or deletes container failed.When cri retry to delete container it will got a runc error container <cid> does not exist. This is because cri ignore IsNotFound error, but shim is not converting the runc error to a containerd NotFound error.
> Transfer error to ErrNotFound when kill a not exist container

- codecov.yml
Until we totally remove codecov, this will keep it from commenting on
PRs but reports will still be available on codecov.io
> Set codecov to not comment on PRs

- vendor.conf
full diff: https://github.com/opencontainers/go-digest/compare/28d3ccc31a47933556673856d9807b4ca436108e...v1.0.0
> vendor: opencontainers/go-digest v1.0.0

- remotes/docker/config/hosts.go
The `DualStack` option was deprecated in Go 1.12, and is now enabled by default (through commit https://github.com/golang/go/commit/efc185029bf770894defe63cec2c72a4c84b2ee9).
> The Dialer.DualStack field is now meaningless and documented as deprecated.
>
> To disable fallback, set FallbackDelay to a negative value.
The default `FallbackDelay` is 300ms; to make this more explicit, this patch sets `FallbackDelay` to the default value.
Note that Docker Hub currently does not support IPv6 (https://github.com/docker/hub-feedback/issues/1945) (DNS for registry-1.docker.io has no AAAA records, so we should not hit the 300ms delay).
> ConfigureHosts: remove deprecated DualStack option

- .github/workflows/nightly.yml
Run nightly build job in PRs that modify `nightly.yml`. This will help to test changes within PR itself (for instance https://github.com/containerd/containerd/pull/4191)
> Trigger nightly builds on pull reuqest events

- .appveyor.yml
- .github/workflows/ci.yml
- .github/workflows/nightly.yml
- .travis.yml
- .zuul/playbooks/containerd-build/run.yaml
- contrib/Dockerfile.test
full diff: https://github.com/golang/go/compare/go1.13.10...go1.13.11
go1.13.11 (released 2020/05/14) includes fixes to the compiler. See the Go 1.13.11
milestone on the issue tracker for details:
https://github.com/golang/go/issues?q=milestone%3AGo1.13.11+label%3ACherryPickApproved
> Bump Golang 1.13.11

- unpacker.go
The iterator variable i should be captured in the go func() through an argument to avoid possible data race and data corruption.
> unpacker: Fix data race and possible data corruption

- contrib/seccomp/seccomp_default.go
porting https://github.com/moby/moby/pull/40929 to containerd
relates to https://github.com/moby/moby/issues/40919
------------
This only allows making the syscall. CAP_SYS_TIME is still required
for time adjustment (enforced by the kernel):
```
kernel/time/posix-timers.c:
1112 SYSCALL_DEFINE2(clock_adjtime, const clockid_t, which_clock,
1113                 struct __kernel_timex __user *, utx)
...
1121         err = do_clock_adjtime(which_clock, &ktx);
1100 int do_clock_adjtime(const clockid_t which_clock, struct __kernel_timex * ktx)
1101 {
...
1109         return kc->clock_adj(which_clock, ktx);
1299 static const struct k_clock clock_realtime = {
...
1304         .clock_adj              = posix_clock_realtime_adj,
188 static int posix_clock_realtime_adj(const clockid_t which_clock,
189 …
```
> seccomp: Whitelist `clock_adjtime`

- contrib/seccomp/seccomp_default.go
query_module(2) is only in kernels before Linux 2.6.
This issue is as same as https://github.com/moby/moby/pull/40995
Signed-off-by: Kenta Tada <Kenta.Tada@sony.com>
> seccomp: remove the unused query_module(2)

- .golangci.yml
- remotes/docker/resolver_test.go
- script/setup/install-dev-tools
Backported test code fix from master, checkout specific version of
golangci-lint, and set timeout to 3m like master
> [release/1.2] golangci-lint update and fix

- remotes/docker/pusher.go
In master the change added the header set inside the block which created the blob request. This got incorrectly backported outside of the block, overriding the correctly set manifest header with the incorrect octet-stream header on manifest push.
This fix only applies to the 1.2 branch, and other branches were correctly backported and this bug does not happen in master.
Fixes #4252
> [release/1.2] fix regression caused by pushing manifests as octet stream

- image.go
- image_test.go
Including snapshotter usage in total calculation should be gated by the
option `snapshotter` boolean.
Sometimes a flaky test is trying to tell you something 😄 The intermittent failures of `TestImageUsage` were actually always reporting the same "offset"; turns out that offset was the exact size of the unpacked root fs of the busybox amd64 build. What was happening is since busybox is used throughout other tests, a snapshot was created that was sometimes not garbage collected by the time `TestImageUsage` ran, and therefore since the label was associated with the amd64 manifest, it would be added to the size calculation and cause this test to fail.
// cc: @fuweid since I know you had tried to fix this at one point; I also added a deferred deletion of the image reference pinned to the sha256 …
> Fix image usage calculation error

- Makefile.linux
While trying to update the containerd package in Ubuntu to version 1.3.4 I faced a build failure on riscv64 (full build log [here](https://launchpadlibrarian.net/480602209/buildlog_ubuntu-groovy-riscv64.containerd_1.3.4-0ubuntu1_BUILDING.txt.gz)):
```
make[2]: Entering directory '/<<PKGBUILDDIR>>'
+ bin/ctr
-buildmode=pie not supported on linux/riscv64
```
This PR simply filters out riscv64 arch when adding the `-buildmode=pie` option, as it is already done for other architectures.
> riscv64 arch does not support -buildmode=pie

- .github/workflows/ci.yml
- .golangci.yml
- cmd/containerd/command/service_windows.go
- remotes/docker/resolver_test.go
- script/setup/install-cni
- script/setup/install-critools
- script/setup/install-dev-tools
- script/setup/install-runc
Configuration that matches the Travis setup for release/1.3.
Copied script changes from master for actions; lint fix in resolver test and updated to golangci-lint version from master, as well as matched 3m timeout for linting from master.
Cherry picked 4756258faf55c1e2b4eb601c9fb669ecb3b43e8b from master to fix lint issue on Windows (unused var).
> [release/1.3] Enable GH Actions for release/1.3 branch

- .travis.yml
- codecov.yml
Now that release/1.3 has working GH Actions for CI we can disable Travis
on PRs for this branch. Also copied the codecov comment disable setting
from master.
> [release/1.3] Disable TravisCI and Codecov comments

- pkg/process/io.go
- pkg/process/io_test.go
Backport of #4195.
I know that we may not have 1.3.5 anytime soon though. Let me know if we have the right way to backport changes!
> [release/1.3 backport] Binary IO fixes and tests

- .github/workflows/ci.yml
- .gitignore
- Vagrantfile
- container_linux_test.go
- daemon_config_linux_test.go
- script/setup/install-runc
Fedora 32 Vagrant is used for testing cgroup2.
Currently the test is executed with `RUNC_FLAVOR=crun`.
> cgroup2 CI

- image.go
- image_test.go
Cherry-picked 0c9b05fa60e9b3a8ab2b0eb0254833741a73db74 from #4275 for `release/1.3`
Including snapshotter usage in total calculation should be gated by the
option `snapshotter` boolean.
> [release/1.3] cherry-pick: Fix image usage calculation error

- cmd/ctr/commands/commands.go
- cmd/ctr/commands/resolver.go
This adds new flags to the `ctr` tool for configuring TLS credentials:
* `--tlscacert` is the path to a root CA certificate, to be used when verifying the server's identity.
* `--tlscert` and `--tlskey` are paths to the components of a TLS client keypair, used to authenticate with a server that requires mTLS authn.
See https://github.com/containerd/containerd/issues/3071 for context. This approach is more flexible than the `hosts.toml` solution (at the cost of higher per-call config verbosity), and can be used for cases such as integration tests and ad-hoc administrative scripts where maintaining a separate directory structure of per-registry certs is impractical.
R: @crosbymichael,@estesp
CC: @mmoriarity-stripe
> Add `ctr` flags for configuring default TLS credentials for registry

- .github/workflows/release.yml
This will check that the tag is signed and then checkout the tag, build
official binaries, sha256sum the tarball, and upload those assets to the
release, officially generating a release in GitHub from the signed tag.
> Add release GH Action triggered by signed tag

- .github/workflows/release.yml
Specify a much larger linecount for extracting tag annotation from git.
> Don't inadvertently clip release notes

- cmd/ctr/app/main.go
- cmd/ctr/commands/oci/oci.go
This adds `ctr oci spec` to output the default OCI spec.
ref: https://github.com/containerd/cri/issues/1488
> Add ctr subcommand to print default OCI spec

- vendor.conf
- vendor/github.com/containerd/cri/pkg/config/config.go
- vendor/github.com/containerd/cri/pkg/config/config_unix.go
- vendor/github.com/containerd/cri/pkg/containerd/opts/spec_unix.go
- vendor/github.com/containerd/cri/pkg/server/container_create_unix.go
- vendor/github.com/containerd/cri/pkg/server/container_update_resources_unix.go
Pick up a fix for a "regression" (notice the code quotes) found when testing 1.4 beta with kind. Details are here:
https://github.com/kubernetes-sigs/kind/issues/1637
PR we need from `containerd/cri` is here:
https://github.com/containerd/cri/pull/1501
TL;DR is as follows:
in containerd 1.3.x, we ignored any hugepages limits kubernetes was requesting, in 1.4, we introduced a change where we "fixed" that issue by picking up the limits and passing it onto runc. However this fails on a class of machines where the `hugeTLB cgroup controller` is not present. So we have to choose between, "fail if cgroup controller for huge pages is absent" and "warn if  cgroup controller for huge pages is absent". This PR defaults to a warning, So we give people time to adjust. Note that CRI-O behaves the same …
> Revendor CRI to 62c91260d2f43b57fff408a9263a800b7a06a647

- runtime/v1/shim/client/client.go
Currently, we send a single SIGKILL to the shim process
once and then we spin in a loop where we use kill(pid, 0)
to detect when the pid has disappeared completely.
Unfortunately, this has a race condition since pids can be reused causing us 
to spin in an infinite loop when that happens.
This adds a timeout to this loop which logs a warning and exits the infinite loop.
This fixes https://github.com/containerd/cri/issues/1427
> Make killing shims more resilient

- script/setup/install-critools
Use the critools version currently being used in the CRI project CI.
*Based on the comment from @mikebrow [here](https://github.com/containerd/containerd/pull/4296#pullrequestreview-423024118)*
> Match version used in CRI project

- .github/workflows/release.yml
Improvements to acquire/build hcsshim from source in the release
workflow. Removes a step from the Windows build flow.
Thanks to @mxpv for the suggestion. // cc: @cpuguy83 
> Streamline hcsshim build addition to release flow

- pkg/process/io.go
The goroutine executing `b.cmd.Wait()` can leak if it time outs and there is no corresponding reader for the `done` channel. To fix this, make `error` an asynchronous buffered channel.
> Process I/O: Fix goroutine leak

- sys/oom_unix_test.go
The goroutine fetching the Process pid may timeout and cause a leak if there is no reader for the channel. To fix this, make it a buffered channel.
> waitForPid: fix goroutine leak

- BUILDING.md
- script/setup/install-runc
docker-ce seems to be building runc with selinux support, let us follow
the same pattern here please:
https://github.com/docker/docker-ce/search?p=1&q=RUNC_BUILDTAGS&unscoped_q=RUNC_BUILDTAGS
(cherry picked from commit 7a252f3ca1f158203574f2c7786a28e6c0368f5e)
> [release/1.3 backport] Build runc with selinux support

- BUILDING.md
- script/setup/install-runc
docker-ce seems to be building runc with selinux support, let us follow
the same pattern here please:
https://github.com/docker/docker-ce/search?p=1&q=RUNC_BUILDTAGS&unscoped_q=RUNC_BUILDTAGS
(cherry picked from commit 7a252f3ca1f158203574f2c7786a28e6c0368f5e)
> [release/1.2 backport] Build runc with selinux support

- cio/io.go
- cio/io_test.go
- runtime/restart/monitor/change.go
- runtime/restart/monitor/monitor.go
- runtime/restart/restart.go
Introduce LogURIGenerator helper function in cio package. It is used in
the restart options, like WithBinaryLogURI and WithFileLogURI.
And restart.LogPathLabel might be used in production and work well. In
order to reduce breaking change, the LogPathLabel is still recognized if
new LogURILabel is not set. In next release 1.5, the LogPathLabel will
be removed.
---------
fix: #4294
> restart plugin: support binary log uri

- runtime/v1/shim/client/client.go
Currently, we send a single SIGKILL to the shim process
once and then we spin in a loop where we use kill(pid, 0)
to detect when the pid has disappeared completely.
Unfortunately, this has a race condition since pids can be reused causing us
to spin in an infinite loop when that happens.
This adds a timeout to this loop which logs a warning and exits the
infinite loop.
Signed-off-by: Ashray Jain <ashrayj@palantir.com>
(cherry picked from commit 3e95727f390b530b91908aedf20a2769435d93bf)
----------
cherry-pick: #4204 
Not sure that it is good to do cherry-pick 4204. If not and we recommend user to use shim v2, I will close it. :)
cc @ashrayjain
> [release/1.3] Make killing shims more resilient

- container_linux_test.go
containerd 1.4 uses io.containerd.runc.v2 as the default runtime for both CRI and non-CRI.
The test is updated to assume v2 shim by default.
> integration: assume TEST_RUNTIME to be io.containerd.runc.v2 by default

- runtime/v2/runc/container.go
- runtime/v2/runc/v1/service.go
- runtime/v2/runc/v2/service.go
Previously shim v2 (`io.containerd.runc.{v1,v2}`) always used `/run/containerd/runc` as the runc root.
Fix #4326
Fix https://github.com/containerd/containerd/issues/2767
> shim v2 runc: propagate options.Root to Cleanup

- runtime/v2/runc/container.go
- runtime/v2/runc/v1/service.go
- runtime/v2/runc/v2/service.go
Previously shim v2 (`io.containerd.runc.{v1,v2}`) always used `/run/containerd/runc` as the runc root.
backport of https://github.com/containerd/containerd/pull/4327
fixes https://github.com/containerd/containerd/issues/4326
fixes https://github.com/containerd/containerd/issues/2767
> [release/1.3 backport] shim v2 runc: propagate options.Root to Cleanup

- vendor.conf
- vendor/go.etcd.io/bbolt/README.md
- vendor/go.etcd.io/bbolt/bolt_386.go
- vendor/go.etcd.io/bbolt/bolt_amd64.go
- vendor/go.etcd.io/bbolt/bolt_arm.go
- vendor/go.etcd.io/bbolt/bolt_arm64.go
- vendor/go.etcd.io/bbolt/bolt_mips64x.go
- vendor/go.etcd.io/bbolt/bolt_mipsx.go
- vendor/go.etcd.io/bbolt/bolt_ppc.go
- vendor/go.etcd.io/bbolt/bolt_ppc64.go
- vendor/go.etcd.io/bbolt/bolt_ppc64le.go
- vendor/go.etcd.io/bbolt/bolt_riscv64.go
- vendor/go.etcd.io/bbolt/bolt_s390x.go
- vendor/go.etcd.io/bbolt/bolt_unix_aix.go
- vendor/go.etcd.io/bbolt/bucket.go
- vendor/go.etcd.io/bbolt/cursor.go
- vendor/go.etcd.io/bbolt/db.go
- vendor/go.etcd.io/bbolt/freelist.go
- vendor/go.etcd.io/bbolt/freelist_hmap.go
- vendor/go.etcd.io/bbolt/go.mod
- vendor/go.etcd.io/bbolt/node.go
- vendor/go.etcd.io/bbolt/page.go
- vendor/go.etcd.io/bbolt/tx.go
- vendor/go.etcd.io/bbolt/unsafe.go
We had once updated bbolt from v1.3.3 to v1.3.4 in #4134, but reverted to v1.3.3 in #4156 due to "fatal error: sweep increased allocation count" (etcd-io/bbolt#214).
The issue was fixed in bbolt v1.3.5 (etcd-io/bbolt#220).
Full changes: https://github.com/etcd-io/bbolt/compare/v1.3.3...v1.3.5
> vendor: update bbolt to v1.3.5

- .appveyor.yml
- .github/workflows/ci.yml
- .travis.yml
- contrib/Dockerfile.test
Essentially cherry-picking #4260 #4333
(but without `git-cherry-pick(1)` due to the code divergence between v1.3 and master caused by CI changes)
> [release/1.3] Bump Golang 1.13.12

- .appveyor.yml
- .travis.yml
- contrib/Dockerfile.test
Essentially cherry-picking #4260 #4333
(but without `git-cherry-pick(1)` due to the code divergence between v1.2 and master caused by CI changes)
> [release/1.2] Bump Golang 1.13.12

- .github/workflows/ci.yml
[BeforeEach] [k8s.io] Security Context
/home/runner/work/containerd/containerd/src/github.com/kubernetes-sigs/cri-tools/pkg/framework/framework.go:50
W0624 12:26:28.532644   30569 util_unix.go:103] Using "/var/run/containerd/containerd.sock" as endpoint is deprecated, please consider using full url format "unix:///var/run/containerd/containerd.sock".
W0624 12:26:28.532700   30569 util_unix.go:103] Using "/var/run/containerd/containerd.sock" as endpoint is deprecated, please consider using full url format "unix:///var/run/containerd/containerd.sock".
> Fix deprecation warnings in CRI tests due to missing unix:// scheme

- mount/mountinfo_linux.go
- mount/mountinfo_linux_test.go
This PR resolves the double quote problem described in issue https://github.com/containerd/containerd/issues/4257
> Cope with double quotes in Linux Mountinfo

- contrib/seccomp/seccomp_default.go
Restartable Sequences (rseq) are a kernel-based mechanism for fast
update operations on per-core data in user-space. Some libraries, like
the newest version of Google's TCMalloc, depend on it [1].
This also makes dockers default seccomp profile on par with systemd's,
which enabled 'rseq' in early 2019 [2].
1: https://google.github.io/tcmalloc/design.html
2: systemd/systemd@6fee3be
> seccomp: allow 'rseq' syscall in default seccomp profile

- images/image.go
This log message shows up in the client's logs. For any media type that
the client doesn't know about it will wind up with a warning log.
Downgrade this to debug since it is more of a development concern.
We encountered this trying to fetch Docker plugins which has a media
type for plugin configs.
Replacement for #4345
> Change log for unknown mt to debug

- .github/workflows/release.yml
Use the same pinning we were using in Travis CI to not force
dependencies on the newer libseccomp 2.4.x in our binaries.
Fixes: #4349
> [release/1.3] Pin libseccomp to 2.3.3 for GH Actions release.yml

- releases/v1.3.6.toml
- version/version.go
> Prepare v1.3.6 fix release

- .github/workflows/ci.yml
- .github/workflows/release.yml
- always apt-get update before installing packages
- move to tagged official `create_release` action
The official GH `create_release` action now has support for body text from
file.
> Minor actions fixes/updates

- remotes/docker/config/hosts.go
- remotes/docker/config/hosts_test.go
- remotes/docker/registry.go
- remotes/docker/resolver.go
Fixes a few unresolved bugs in the host config code including a few uninitialized values.
Adds support for per registry host HTTP headers. (Related to https://github.com/containerd/cri/issues/1400)
> Registry config header support and fixes

- vendor.conf
- vendor/github.com/containerd/cri/pkg/server/container_remove.go
- vendor/github.com/containerd/cri/pkg/server/sandbox_remove.go
- vendor/github.com/containerd/cri/pkg/server/sandbox_stop.go
Update to latest containerd/cri master, namely with fix for forcibly removing containers (per CRI spec) for RemoveContainer and RemovePodSandbox requests.
> update to latest containerd/cri 

- events/exchange/exchange_test.go
The goroutine writing to errChan will block on the reader (main routine), however the main routine will block for the goroutine to finish with the wait() before it can read from errChan thus causing the deadlock. 
An example here: https://play.golang.com/p/zwk-FHPKx-4
For this case, we don't really need the sync.WaitGroup at all since the main routine's execution is already blocked on the errChan (read or close). Fix this by removing the wait logic.
> [events] Fix deadlock in TestExchangeBasic

- .github/workflows/ci.yml
The previous names were confusing because v1 may look like shim API v1 (io.containerd.runtime.v1.linux").
Also, v2 may look like cgroup v2.
> CI: {v1, v2} -> io.containerd.runc.{v1,v2}

- BUILDING.md
Build doc specifies Go 1.10.x as min version. But it does not build at version below 1.13. Updating Go to 1.13 allows build to complete successfully. Updating build doc to reflect this. Closes #4363
> Update build doc with Go 1.13 requirement

- events/exchange/exchange_test.go
xref #4353 
The goroutine writing to errChan will block on the reader (main routine), however the main routine will block for the goroutine to finish with the wait() before it can read from errChan thus causing the deadlock.
An example here: https://play.golang.com/p/zwk-FHPKx-4
> [events/exchange_test] Fix deadlock in TestExchangeFilters

- vendor.conf
- vendor/github.com/containerd/cgroups/README.md
- vendor/github.com/containerd/cgroups/blkio.go
- vendor/github.com/containerd/cgroups/cgroup.go
- vendor/github.com/containerd/cgroups/cpu.go
- vendor/github.com/containerd/cgroups/cpuset.go
- vendor/github.com/containerd/cgroups/devices.go
- vendor/github.com/containerd/cgroups/freezer.go
- vendor/github.com/containerd/cgroups/go.mod
- vendor/github.com/containerd/cgroups/hugetlb.go
- vendor/github.com/containerd/cgroups/memory.go
- vendor/github.com/containerd/cgroups/net_cls.go
- vendor/github.com/containerd/cgroups/net_prio.go
- vendor/github.com/containerd/cgroups/opts.go
- vendor/github.com/containerd/cgroups/paths.go
- vendor/github.com/containerd/cgroups/pids.go
- vendor/github.com/containerd/cgroups/rdma.go
- vendor/github.com/containerd/cgroups/systemd.go
- vendor/github.com/containerd/cgroups/utils.go
- vendor/github.com/containerd/cgroups/v2/errors.go
- vendor/github.com/containerd/cgroups/v2/manager.go
- vendor/github.com/containerd/cgroups/v2/paths.go
- vendor/github.com/containerd/cgroups/v2/utils.go
full diff: https://github.com/containerd/cgroups/compare/0dbf7f05ba59274095946e2c0c89540726e8a8aa...318312a373405e5e91134d8063d04d59768a1bff
relevant changes:
- cpuset: typo fix for function name
- Retry file writes on EINTR errors to work with Go 1.14 asynchronous preemption
- Various linting issues and cleanup
> vendor: containerd/cgroups 318312a373405e5e91134d8063d04d59768a1bff

- .github/workflows/ci.yml
- .github/workflows/nightly.yml
- .github/workflows/release.yml
- .travis.yml
- .zuul/playbooks/containerd-build/run.yaml
- Vagrantfile
- contrib/Dockerfile.test
Includes security fixes to the `crypto/x509` and `net/http` packages.
https://github.com/golang/go/issues?q=milestone%3AGo1.13.13+label%3ACherryPickApproved
> Bump Go 1.13.13

- .github/workflows/ci.yml
- script/setup/install-critools
GH runners now have a systemd-run containerd running on the standard
socket, impacting the CRI test's expectation of our CI-built containerd
running there.
> Don't clash with GH Actions runner's containerd

- .github/workflows/ci.yml
- container_test.go
We are going to deprecate shim v1 (#4365), but it is still early to disable the tests for them
> CI: add back shim v1 test

- diff/lcow/lcow.go
- diff/windows/windows.go
- images/mediatypes.go
This makes it possible to see _what_ is not implemented from the caller.
Signed-off-by: Paul "TBBle" Hampson <Paul.Hampson@Pobox.com>
> Annotate bare ErrNotImplemented returns

- .github/workflows/ci.yml
- .github/workflows/nightly.yml
- .github/workflows/release.yml
- .travis.yml
- .zuul/playbooks/containerd-build/run.yaml
- Vagrantfile
- contrib/Dockerfile.test
full diff: https://github.com/golang/go/compare/go1.13.13...go1.13.14
go1.13.14 (released 2020/07/16) includes fixes to the compiler, vet, and the
database/sql, net/http, and reflect packages. See the Go 1.13.14 milestone on
https://github.com/golang/go/issues?q=milestone%3AGo1.13.14+label%3ACherryPickApproved
> Bump Golang 1.13.14

- .github/workflows/ci.yml
- Vagrantfile
SELinux is currently disabled.  (It doesn't expect the binaries to be under `/usr/local/bin`: https://github.com/containers/container-selinux/blob/988431700370bf7f554ab6507c836a9aa19e47ff/container.fc#L6)
SELinux will be enabled in a follow-up PR.
> CI: run CRI tests on Fedora 32

- cmd/ctr/commands/run/run_unix.go
> parseIDMapping: accept 32-bit IDs

- runtime/v2/runc/v2/service.go
- runtime/v2/shim/publisher.go
Before this change, if an event fails to send on the first attempt,
subsequent attempts will fail with context.Cancelled because the the
caller of publish passes a cancellable timeout, which the publisher uses
to send the event.
The publisher returns immediately if the send fails, but adds the event
to an async queue to try again.
Meanwhile the caller will return cancelling the context.
Additionally, subsequent attempts may fail to send because the timeout
was expected to be for a single request but the queue sleeps for
`attempt*time.Second`.
In the shim service, the timeout was set to 5s, which means the send
will fail with context.DeadlineExceeded before it reaches `maxRequeue`
(which is currently 5).
This change moves the timeout to the publisher so each send attempt gets
its own …
> shim: move event context timeout to publsher

- .github/workflows/ci.yml
Fixes a warning with the version test.
Outputs the list of CNI configs at the default cat /etc/cni/net.d path.. 
Useful for investigating CI problems ... collisions with github actions use of containerd and dependencies...
> update for CI warning

- client.go
- client_opts.go
- client_test.go
- images/handlers.go
- images/mediatypes.go
- pull.go
- unpacker.go
This change gives control of the content labeling process for children to the client. This allows the client to control the names associated with the labels and filter out labels.
Includes and replaces changes from #4332 
This newer approach avoids the additional label mutation pass after unpack. This prevents the process for removing previously set labels and better ensures the content gets garbage collected if the client ends the operation before the removal.
Comment from #4332 
----
Fixes: #4304
This commit adds a flag through Pull API for allowing GC to clean layer contents up after unpacking these contents completed.
This patch takes an approach to directly delete GC labels pointing to layers from the manifest blob. This will result in other snapshotters cannot reuse these contents …
> Set content labels based on content type

- .github/workflows/ci.yml
- .github/workflows/release.yml
- container_linux_test.go
- container_test.go
- image_test.go
- pkg/process/utils.go
- script/setup/install-critools
Backports:
-   Transfer error to ErrNotFound when kill a not exist container #4214
Fixes #4359
-   Minor actions fixes/updates #4356
Fixes build issues
-   test: Do SynchronousDelete cleanup before testing ImageIsUnpacked #3832
cleanup the image synchronously for Usage case #4049
Fixes race that causes `TestImageUsage` to fail
-   Don't clash with GH Actions runner's containerd #4380
Fixes Github Actions
Not-backport:
-   fixes for backports to 1.3 from 1.4
Fixes up backport changes that didn't fit 1.3        
Signed-off-by: Joe Julian <me@joejulian.name>
> [release/1.3] backport: Transfer error to ErrNotFound when kill a not exist container, also add test case.

- client_test.go
- client_windows_test.go
Some stuff I hit while trying to reproduce an integration test failure seen on CI:
* When running the integration tests with `-v`, output the server log even on success, to help diagnose whatever you're trying to diagnose by adding `-v`.
* Add test image repository for Windows 10 2004/Windows Server 2004
* Fail early and with a useful course of action, if a test image cannot be determined on Windows, since there is no reasonable fallback option.
> Some small test improvements

- snapshots/devmapper/pool_device.go
> [release/1.3 backport] snapshots/devmapper: suspend a device to avoid data corruption 

- remotes/docker/authorizer.go
Backport of #3889.
----
Registries may allow using token authorization without
explicitly setting the scope. This may cover use cases where
no scope is required for an endpoint or the registry is only
covering authentication using the token. This aligns with the
oauth2 spec which specifies the scope as optional.
> [release/1.3 backport] Allow empty scope authorization

- runtime/v2/runc/v2/service.go
- runtime/v2/shim/publisher.go
Backports #4412 to the 1.3 branch
---
Before this change, if an event fails to send on the first attempt,
subsequent attempts will fail with context.Cancelled because the the
caller of publish passes a cancellable timeout, which the publisher uses
to send the event.
The publisher returns immediately if the send fails, but adds the event
to an async queue to try again.
Meanwhile the caller will return cancelling the context.
Additionally, subsequent attempts may fail to send because the timeout
was expected to be for a single request but the queue sleeps for
`attempt*time.Second`.
In the shim service, the timeout was set to 5s, which means the send
will fail with context.DeadlineExceeded before it reaches `maxRequeue`
(which is currently 5).
This change moves the timeout to the publisher …
> [release/1.3] shim: move event context timeout to publisher

- vendor.conf
- vendor/github.com/opencontainers/runc/go.mod
- vendor/github.com/opencontainers/runc/libcontainer/configs/cgroup_linux.go
- vendor/github.com/opencontainers/runc/libcontainer/configs/device.go
- vendor/github.com/opencontainers/runc/libcontainer/configs/device_unix.go
- vendor/github.com/opencontainers/runc/libcontainer/configs/device_windows.go
- vendor/github.com/opencontainers/runc/libcontainer/devices/devices.go
- vendor/github.com/opencontainers/runc/libcontainer/user/user.go
runc v1.0.0-rc91 has some modifications, it will break docker. https://github.com/opencontainers/runc/pull/2529
More detail https://github.com/moby/moby/pull/41178
--- 
Or we can wait until runc rc92 is released and then merge.
> vendor runc library to v1.0.0-rc91-48-g67169a9d

- remotes/docker/authorizer.go
- remotes/docker/scope.go
- remotes/docker/scope_test.go
Authorizer interface can’t be really implemented because scopes are passed in on a side channel via private value in context.
The current structure of the resolver/fetcher/pusher where hardcoded auth scopes are passed in with a context that bypasses the Authorizer interface is quite awful. I'm willing to do a refactor as a follow-up if we can agree on the updated interface.
@AkihiroSuda 
> remotes: mark GetTokenScopes public

- docs/remote-snapshotter.md
containerd 1.4 will support snapshotter based on shared storage. It's better to have docs for it. This commit adds the description to godoc but we might want it also to design/snapshots.md or somewhere else?
> Add doc about snapshotter based on shared remote storage

- .github/workflows/ci.yml
- .github/workflows/release.yml
Recent changes removed the need for libseccomp-dev when building
containerd. The btrfs tools package is already installed on GH Actions
runners and was already a no-op so the whole step can be removed.
> Remove seccomp/Linux deps steps in GH Actions

- .zuul.yaml
The old nodeset is unstable and apt source is unavailable, we change the nodeset from `ubuntu-xenial-arm64` to `ubuntu-xenial-arm64-openlab` to enable stable new nodeset.
> Change nodeset to `ubuntu-xenial-arm64-openlab`

- remotes/docker/fetcher.go
- remotes/docker/fetcher_test.go
- remotes/docker/registry.go
- remotes/docker/resolver.go
- remotes/docker/resolver_test.go
Proxy registries are designed to serve content from upstreams. However, the proxy hostname will usually not match the hostname of the upstream, requiring the proxy to only use a single upstream or use its own pattern matching to determine the upstream. To solve this issue, the client will pass along the namespace which is being used for the request, allowing mirrors to easily map to multiple upstreams. This query parameter can safely be ignored if multiple upstreams are not supported.
This is has been approved in the OCI spec to be merged after 1.0
See https://github.com/opencontainers/distribution-spec/pull/66
> Add namespace query parameter for registry proxying

- snapshots/devmapper/snapshotter.go
The snapshotter doesn't have to exclude non-amd64 platforms.
> snapshots/devmapper: don't hardcord the platform strings

- script/setup/install-critools
taken from https://github.com/containerd/containerd/pull/4050
full diff: https://github.com/kubernetes-sigs/cri-tools/compare/16911795a3c33833fa0ec83dac1ade3172f6989e...2bf7674922a424337d7580a08166d666c6802818
> Update cri-tools to v1.18.0-100-g2bf7674 for Go 1.15 compatibility

- .github/workflows/ci.yml
- .github/workflows/nightly.yml
- .github/workflows/release.yml
- .travis.yml
- .zuul/playbooks/containerd-build/run.yaml
- Vagrantfile
- contrib/Dockerfile.test
full diff: https://github.com/golang/go/compare/go1.13.14...go1.13.15
go1.13.15 (released 2020/08/06) includes security fixes to the encoding/binary
package. See the Go 1.13.15 milestone on the issue tracker for details.
https://github.com/golang/go/issues?q=milestone%3AGo1.13.15+label%3ACherryPickApproved
> Bump Golang 1.13.15

- .github/workflows/ci.yml
- .github/workflows/release.yml
- .travis.yml
- .zuul/playbooks/containerd-build/run.yaml
- contrib/Dockerfile.test
Backports of:
- https://github.com/containerd/containerd/pull/3944 ci: set pipefail in zuul script
- fixes https://github.com/containerd/containerd/issues/3943 openlab ci is broken
- https://github.com/containerd/containerd/pull/4199 .zuul: update go version to 1.13.10
- only the first commit; skipped the second commit
- https://github.com/containerd/containerd/pull/4375 Bump Go 1.13.13
- https://github.com/containerd/containerd/pull/4398 Bump Golang 1.13.14
- https://github.com/containerd/containerd/pull/4462 Bump Golang 1.13.15
> [release/1.3 backport] Bump Golang 1.13.15

- .appveyor.yml
- .travis.yml
- contrib/Dockerfile.test
Backports of:
- https://github.com/containerd/containerd/pull/4375 Bump Go 1.13.13
- https://github.com/containerd/containerd/pull/4398 Bump Golang 1.13.14
- https://github.com/containerd/containerd/pull/4462 Bump Golang 1.13.15
Cherry-picks weren't clean, but trivial to fix
> [release/1.2 backport] Bump Golang 1.13.15

- .github/workflows/ci.yml
- Vagrantfile
- script/setup/config-containerd
- script/setup/config-selinux
- script/setup/install-runc
`vagrant up` will build and install containerd and all dependencies,
setting up proper SELinux contexts on the runc and containerd binaries.
The VM is configured to be SELinux Enforcing by default but this gets
changed during various CI passes via a matrix param to Disabled and
Permissive before running tests. I have an open PR to fix the
container-selinux policy for containerd at
https://github.com/containers/container-selinux/pull/98 which once
accepted we will want to update the CI matrix to use Enforcing mode
instead of Permissive.
All tests currently pass in SELinux permissive mode with containerd
configured with `enable_selinux=true`. To see which tests are failing
with SELinux enforcing and an already spun up VM:
`SELINUX=Enforcing vagrant up --provision-with=selinux,test-cri`
To …
> Update Vagrantfile for testing SELinux

- cmd/ctr/commands/commands_unix.go
- cmd/ctr/commands/run/run_unix.go
Signed-off-by: Kenneth Kang <kenneth.kang@lge.com>
> Add --cpu-quota, --cpu-period flag to ctr

- containerd.service
I thought this would make sense, as this is a file that would likely be shipped in packages, but wasn't sure if this was desired or not, and if https://github.com/kunalkushwaha/ltag should be updated to allow verifying `.service` files
> systemd: add license header to systemd unit

- containerd.service
According to the systemd documentation, `infinity` can be used for all limits;
https://www.freedesktop.org/software/systemd/man/systemd.exec.html#Process%20Properties
> Resource limits may be specified in two formats: either as single value to set a
> specific soft and hard limit to the same value, or as colon-separated pair soft:hard
> (...) Use the string infinity to configure no limit on a specific resource.
> systemd: use LimitNOFILE=infinity instead of hard-coded max value

- snapshots/devmapper/metadata.go
- snapshots/devmapper/pool_device.go
- snapshots/devmapper/pool_device_test.go
The rollback mechanism is implemented by calling deleteDevice() and
RemoveDevice(). But RemoveDevice() is internally calling
deleteDevice() as well.
Since the device will be deleted by first deleteDevice(),
RemoveDevice() always will see ENODATA. The specific error must be
ignored to remove its associated metadata correctly.
> snapshots/devmapper: fix rollback

- snapshots/devmapper/metadata.go
- snapshots/devmapper/pool_device.go
- snapshots/devmapper/pool_device_test.go
Backport of #4437. I will create another backport PR for 1.4 later.
---
The rollback mechanism is implemented by calling deleteDevice() and
RemoveDevice(). But RemoveDevice() is internally calling
deleteDevice() as well.
Since a device will be deleted by first deleteDevice(),
RemoveDevice() always will see ENODATA. The specific error must be
ignored to remove the device's metadata correctly.
> [release/1.3 backport] snapshots/devmapper: fix rollback

- snapshots/devmapper/metadata.go
- snapshots/devmapper/pool_device.go
- snapshots/devmapper/pool_device_test.go
Backport of #4437.
---
The rollback mechanism is implemented by calling deleteDevice() and
RemoveDevice(). But RemoveDevice() is internally calling
deleteDevice() as well.
Since a device will be deleted by first deleteDevice(),
RemoveDevice() always will see ENODATA. The specific error must be
ignored to remove the device's metadata correctly.
> [release/1.4 backport] snapshots/devmapper: fix rollback

- runtime/v2/bundle.go
(cherry picked from commit 73b14492782983b43444a2208d5e618f399052b0)
cherry-pick #4472
> [release/1.4] runtime: ignore ErrNotExist when remove rootfs

- services/tasks/local.go
When containerd is restarted, only v1 tasks are monitored again. 
This leads to the lack of existing v2 task metrics.
> tasks: Monitor v2 tasks in initFunc as well

- contrib/seccomp/seccomp_default.go
equivalent of https://github.com/moby/moby/pull/37929
This call is what is used to implement `dmesg` to get kernel messages
about the host. This can leak substantial information about the host.
It is normally available to unprivileged users on the host, unless
the sysctl `kernel.dmesg_restrict = 1` is set, but this is not set
by standard on the majority of distributions. Blocking this to restrict
leaks about the configuration seems correct.
Relates to docker/docker#37897 "docker exposes dmesg to containers by default"
See also https://googleprojectzero.blogspot.com/2018/09/a-cache-invalidation-bug-in-linux.html
> seccomp: move the syslog syscall to be gated by CAP_SYS_ADMIN or CAP_SYSLOG

- remotes/docker/auth/fetch.go
- remotes/docker/auth/parse.go
- remotes/docker/authorizer.go
- remotes/docker/resolver.go
Avoid custom implementations of `Authorizer` to copy-paste a lot of utility functions.
@AkihiroSuda 
> docker: split private token helper functions to reusable pkg

- snapshots/overlay/config.go
- snapshots/overlay/overlay.go
Fixes https://github.com/containerd/containerd/issues/4500
This allows configuring the location of the overlayfs snapshotter by
adding the following in config.toml
```
[plugins]
[plugins.overlayfs]
root_path = "/custom_location"
```
This is useful to isolate disk i/o for overlayfs from the rest of
containerd and prevent containers saturating disk i/o from negatively
affecting containerd operations and cause timeouts.
> Add configurable overlayfs path

- cmd/containerd/builtins_linux.go
- snapshots/overlay/overlay.go
- snapshots/overlay/plugin/plugin.go
Put the overlay plugin in a separate package to allow the overlay package to be used without needing to import and initialize the plugin.
Downstream implementations will need to account for this one, but considering the other plugin refactoring being targeted for 1.5, it makes sense to do it now.
> Separate overlay implementation from plugin

- services/tasks/local.go
When containerd is restarted, only v1 tasks are monitored again. This
leads to the lack of existing v2 task metrics.
(cherry picked from commit 4422ae363828c035f76a7b2c45e3419f77d164f9)
cherry-pick: #4486
> [realease/1.3] tasks: Monitor v2 tasks in initFunc as well

- services/tasks/local.go
When containerd is restarted, only v1 tasks are monitored again. This
leads to the lack of existing v2 task metrics.
(cherry picked from commit 4422ae363828c035f76a7b2c45e3419f77d164f9)
cherry-pick: #4486
> [release/1.4] tasks: Monitor v2 tasks in initFunc as well

- runtime/v1/shim/service.go
This `Info` log shows up for all exec processes that use the v1 shim
with Docker because Docker deletes the process once it receives the exit
event from containerd.
> shimv1: downgrade poroccess missing log to debug

- README.md
Updates slack link to point to CNCF slack.
Adds a help wanted section to let people know help is needed, wanted, and welcome.  
Need more documentation / material outlining how said helpers can contribute. But wanted to at least make it known/visible on the repo.
> add help wanted, update slack

- vendor.conf
- vendor/github.com/containerd/cri/pkg/server/container_create.go
- vendor/github.com/containerd/cri/pkg/server/helpers_unix.go
- vendor/github.com/containerd/cri/pkg/server/helpers_windows.go
- vendor/github.com/containerd/cri/pkg/server/sandbox_run.go
- vendor/github.com/containerd/cri/pkg/seutil/seutil.go
This includes changes for kata or other kvm based runtimes with selinux support.
> update cri to 35e623e6bf7512e8c82b8ac6052cb1d7201

- remotes/docker/auth/fetch.go
- remotes/docker/authorizer.go
- remotes/docker/pusher.go
- remotes/errors/errors.go
This accomplishes a few long-standing TODO items, but also helps users in showing exact registry error messages.
I was stuck for a while trying to debug https://github.com/docker/buildx/issues/300 without this, not realising the responses had pretty clear error messages attached.
> Log unexpected responses

- cmd/containerd/builtins_linux.go
- cmd/containerd/builtins_unix.go
- snapshots/native/native.go
- snapshots/native/plugin/plugin.go
Signed-off-by: knight42 <anonymousknight96@gmail.com>
Part of #4513 and #4514
> feat(snapshot::native): config root_path

- cmd/ctr/commands/signals.go
- cmd/ctr/commands/signals_linux.go
- cmd/ctr/commands/signals_notlinux.go
Previously the signal loop can end up racing with the process exiting.
Intead of logging and continuing the loop, exit early.
Starting with go1.14, the go runtime hijacks SIGURG but with no way to
not send to other signal handlers.
In practice, we get this signal frequently.
I found this while testing out go1.15 with ctr and multiple execs with
only `echo hello`. When the process exits quickly, if the previous
commit is not applied, you end up with an error message that it couldn't
forward SIGURG to the container (due to the process being gone).
> Fix some signal forwarder issues

- platforms/cpuinfo.go
On the very popular Raspberry Pi 1 and Zero devices, the CPU is actually ARMv6, but the chip happens to support the feature bit the kernel uses to differentiate v6/v7, so it gets reported as "CPU architecture: 7" and thus fails to run many of the images that get pulled.
To account for this very popular edge case, this also checks "model name" which on these chips will begin with "ARMv6-compatible" -- we could also check uname, but getCPUInfo is already handy, low overhead, and mirrors the code before this.
To give a small taste of how common this issue is and why (in my opinion) it warrants a special case:
- https://github.com/moby/moby/issues/41017
- https://github.com/moby/moby/issues/37647
- https://github.com/moby/moby/issues/34875
- https://github.com/biarms/mysql/issues/4
(I …
> Add RPi1/RPi0 workaround

- cmd/ctr/commands/signals.go
- cmd/ctr/commands/signals_linux.go
- cmd/ctr/commands/signals_notlinux.go
backport of https://github.com/containerd/containerd/pull/4532
> ### Exit signal forward if process not found
> Previously the signal loop can end up racing with the process exiting.
> Intead of logging and continuing the loop, exit early.
> 
> ### Ignore SIGURG signals in signal forwarder
> Starting with go1.14, the go runtime hijacks SIGURG but with no way to
> not send to other signal handlers.
> 
> In practice, we get this signal frequently.
> I found this while testing out go1.15 with ctr and multiple execs with
> only `echo hello`. When the process exits quickly, if the previous
> commit is not applied, you end up with an error message that it couldn't
> forward SIGURG to the container (due to the process being gone).
> [release/1.3 backport] Fix some signal forwarder issues

- cmd/ctr/commands/signals.go
- cmd/ctr/commands/signals_linux.go
- cmd/ctr/commands/signals_notlinux.go
backport of https://github.com/containerd/containerd/pull/4532
> ### Exit signal forward if process not found
> Previously the signal loop can end up racing with the process exiting.
> Intead of logging and continuing the loop, exit early.
> 
> ### Ignore SIGURG signals in signal forwarder
> Starting with go1.14, the go runtime hijacks SIGURG but with no way to
> not send to other signal handlers.
> 
> In practice, we get this signal frequently.
> I found this while testing out go1.15 with ctr and multiple execs with
> only `echo hello`. When the process exits quickly, if the previous
> commit is not applied, you end up with an error message that it couldn't
> forward SIGURG to the container (due to the process being gone).
> [release/1.4 backport] Fix some signal forwarder issues

- vendor.conf
- vendor/github.com/containerd/cgroups/memory.go
- vendor/github.com/containerd/cgroups/stats/v1/metrics.pb.go
- vendor/github.com/containerd/cgroups/stats/v1/metrics.proto
full diff: https://github.com/containerd/cgroups/compare/318312a373405e5e91134d8063d04d59768a1bff...0b889c03f102012f1d93a97ddd3ef71cd6f4f510
Relevant changes:
- v1/stats: add all fields of memory.oom_control
- memory: remove wrong memory.kmem.limit_in_bytes check
> vendor: containerd/cgroups 0b889c03f102012f1d93a97ddd3ef71cd6f4f510

- runtime/v1/shim/service.go
backport of https://github.com/containerd/containerd/pull/4519
relates to https://github.com/containerd/containerd/issues/4509
This `Info` log shows up for all exec processes that use the v1 shim
with Docker because Docker deletes the process once it receives the exit
event from containerd.
> [release/1.4 backport] shimv1: downgrade poroccess missing log to debug

- contrib/seccomp/seccomp_default.go
backport of https://github.com/containerd/containerd/pull/4481
> related to https://patchwork.kernel.org/patch/11167585/
> 
> Note: `openat2()` first appeared in Linux 5.6. And Glibc does not provide a wrapper for this system call; call it using
> `syscall(2)`.
> 
> ref: https://man7.org/linux/man-pages/man2/openat2.2.html
> [release/1.4] seccomp: add `openat2` and `faccessat2` syscall

- BUILDING.md
backport of https://github.com/containerd/containerd/pull/4470
* `-linkmode external` is required since Go 1.15 for static builds: https://github.com/golang/go/issues/40711
* Clarify the meaning of "loading plugins"
(cherry picked from commit 43cbdf89e9142b9b8cb54fb0932e4c7a45f1daeb)
> [release/1.4 backport] BUILDING.md: fix description about static builds

- cmd/ctr/commands/tasks/metrics.go
backport of https://github.com/containerd/containerd/pull/4468
Windows container stats were reporting incorrect metrics for cpu kernel runtime.
Signed-off-by: Prashant Bhutani <prbhutan@microsoft.com>
(cherry picked from commit 35b63c064ff040727e685fdcc188a99de67136b6)
> [release/1.4 backport] Report correct stats for windows containers

- script/setup/install-cni
- vendor.conf
- vendor/github.com/containerd/go-cni/README.md
- vendor/github.com/containerd/go-cni/go.mod
- vendor/github.com/containernetworking/cni/README.md
- vendor/github.com/containernetworking/cni/libcni/api.go
- vendor/github.com/containernetworking/cni/libcni/conf.go
- vendor/github.com/containernetworking/cni/pkg/invoke/args.go
- vendor/github.com/containernetworking/cni/pkg/invoke/raw_exec.go
- vendor/github.com/containernetworking/cni/pkg/types/020/types.go
- vendor/github.com/containernetworking/cni/pkg/types/args.go
- vendor/github.com/containernetworking/cni/pkg/types/current/types.go
- vendor/github.com/containernetworking/cni/pkg/types/types.go
- vendor/github.com/containernetworking/cni/pkg/utils/utils.go
- vendor/github.com/containernetworking/plugins/README.md
- vendor/github.com/containernetworking/plugins/go.mod
- vendor/github.com/containernetworking/plugins/pkg/ns/README.md
- vendor/github.com/containernetworking/plugins/pkg/ns/ns_linux.go
backport of https://github.com/containerd/containerd/pull/4308
> bump cni dependencies so we can benefits from its
> bugfixes and improvements
> 
> xref: [containerd/go-cni#56](https://github.com/containerd/go-cni/pull/56)
> [release/1.4 backport] bump cni dependencies

- contrib/seccomp/seccomp_default.go
backport of https://github.com/containerd/containerd/pull/4481
> related to https://patchwork.kernel.org/patch/11167585/
> 
> Note: `openat2()` first appeared in Linux 5.6. And Glibc does not provide a wrapper for this system call; call it using
> `syscall(2)`.
> 
> ref: https://man7.org/linux/man-pages/man2/openat2.2.html
> [release/1.3] seccomp: add `openat2` and `faccessat2` syscall

- vendor.conf
- vendor/github.com/willf/bitset/README.md
- vendor/github.com/willf/bitset/bitset.go
- vendor/github.com/willf/bitset/go.mod
relates to https://github.com/opencontainers/selinux/pull/114, https://github.com/opencontainers/selinux/issues/116
The changes needed by opencontainers/selinux are now in a tagged release. This will make our dependency slightly ahead of what's used by opencontainers/selinux until a v1.6.1 is tagged.
full diff: https://github.com/willf/bitset/compare/d5bec3311243...v1.1.11
> vendor: github.com/willf/bitset v1.1.11

- services/tasks/local.go
This fixes an issue with restoring from a checkpoint image. One either restores from an image *or* a path, but currently restoring from an image only works if a path is set as well.
It looks like a simple logical error: The path apparently is supposed to take precedence over the image, so restoring form an image should only be done when *no* checkpoint path is set. Therefore a `checkpointPath == ""` makes more sense than `checkpointPath != ""`.
I haven't tested this (yet), but I'll do so when I have the time.
> cr: fix checkpoint from image getting skipped

- vendor.conf
- vendor/github.com/willf/bitset/README.md
- vendor/github.com/willf/bitset/bitset.go
- vendor/github.com/willf/bitset/go.mod
backport of https://github.com/containerd/containerd/pull/4566
The changes needed by opencontainers/selinux are now in a tagged
release. This will make our dependency slightly ahead of what's
used by opencontainers/selinux until a v1.6.1 is tagged.
full diff: https://github.com/willf/bitset/compare/d5bec3311243...v1.1.11
(cherry picked from commit a6fc9ca490044ed5c6f10b954e929633a151067c)
> [release/1.4 backport] vendor: github.com/willf/bitset v1.1.11

- vendor.conf
- vendor/github.com/containerd/cri/README.md
- vendor/github.com/containerd/cri/pkg/server/image_pull.go
- vendor/github.com/containerd/cri/vendor.conf
This includes the fix for additional labels passed to snapshotter (https://github.com/containerd/cri/pull/1572).
Full diff: https://github.com/containerd/cri/compare/35e623e6bf7512e8c82b8ac6052cb1d720189f28...210a86ca5bf6c8ca5f2553272d72c774b21fdec2
> vendor: update containerd/cri 210a86ca5bf6c8ca5f2553272d72c774b21fdec2

- cmd/containerd/builtins_zfs_linux.go
- vendor.conf
- vendor/github.com/containerd/zfs/README.md
- vendor/github.com/containerd/zfs/go.mod
- vendor/github.com/containerd/zfs/plugin/plugin.go
- vendor/github.com/containerd/zfs/zfs.go
It solves a the zfs part of containerd/containerd#4514 and containerd/containerd#4513.
https://github.com/containerd/zfs/pull/31 needs to merged along with this.
Signed-off-by: Siddharth Yadav <sedflix@gmail.com>
> zfs: seperate implementation pkg from plugin pkg

- runtime/v2/manager.go
- runtime/v2/shim.go
- vendor.conf
- vendor/github.com/containerd/ttrpc/client.go
The shim delete action needs bundle information to cleanup resources
created by shim. If the cleanup dead shim is called after delete bundle,
the part of resources maybe leaky.
The ttrpc client UserOnCloseWait() can make sure that resources are
cleanup before delete bundle, which synchronizes task deletion and
cleanup deadshim. It might slow down the task deletion, but it can make
sure that resources can be cleanup and avoid EBUSY umount case. For
example, the sandbox container like Kata/Firecracker might have mount
points over the rootfs. If containerd handles task deletion and cleanup
deadshim parallelly, the task deletion will meet EBUSY during umount and
fail to cleanup bundle, which makes case worse.
And also update cleanupAfterDeadshim, which makes sure that
cleanupAfterDeadshim …
> runtime/v2: cleanup dead shim before delete bundle

- content/local/store_unix.go
- sys/stat_bsd.go
I have tested that by building and trying - successfully! (at least for
basic testing) - the Docker CLI on NetBSD/amd64 (and only a couple of
patches are needed for
[containerd/console](https://github.com/containerd/console) that I will share in
the next minutes).
> Add support for NetBSD

- .github/workflows/release.yml
- .gitignore
- Makefile
Allows building the cri-release package outside of the github action. This is also much simpler than the `cri-release` which was recently removed as it uses the locally built binaries and scripts which are now in containerd/containerd.
Verified Github release changes at https://github.com/dmcgowan/containerd/runs/1153643111
> Move CRI release logic to Makefile

- RELEASES.md
The maintainers discussed extending the end of life date for 1.2 to allow time for EOL announcement and migration to 1.3.
> Set 1.2.x end of life date to October 15

- .github/workflows/ci.yml
- Makefile
- script/setup/install-cni
- script/setup/install-critools
- test/build-utils.sh
- test/build.sh
- test/push.sh
- test/utils.sh
This enables to the CRI e2e tests to use the build from a PR
WIP: for testing
> Update CRI tests to build and push to gcs

- BUILDING.md
I got these errors when I try to build containerd:
```
go build "-mod=vendor" "-buildmode=pie"  -tags "seccomp selinux apparmor" -ldflags "-X main.gitCommit="a220b9c6cc100f71ddc67152a12fc04622313dca" -X main.version=1.0.0-rc92+dev " -o runc .
Package libseccomp was not found in the pkg-config search path.
Perhaps you should add the directory containing `libseccomp.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libseccomp' found
Package libseccomp was not found in the pkg-config search path.
Perhaps you should add the directory containing `libseccomp.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libseccomp' found
pkg-config: exit status 1
```
Solved this problem by installing one extra dependency `libseccomp-dev`. I am using Ubuntu 20.04 and everything works …
> Update BUILDING.md - add dependency libseccomp-dev

- script/setup/install-cni-windows
Fixes packaging via GH Actions script, which sets DESTDIR and is used
across many scripts.
Found while bringing the CNI/CRI packaging work back to `release/1.3`. Will backport to `release/1.4` to fix next point release of v1.4.x as well.
> Windows CNI install script using lowercase "destdir"

- script/setup/install-cni-windows
Fixes packaging via GH Actions script, which sets DESTDIR and is used
across many scripts.
Cherry picking #4599 
(cherry picked from commit 615af428a30e0d22c80dcb3db64e92147779c7e0)
> [release/1.4] cherry-pick: Windows CNI install script using lowercase "destdir"

- remotes/docker/fetcher.go
- remotes/docker/pusher.go
- remotes/docker/resolver.go
- remotes/docker/scope.go
- remotes/docker/scope_test.go
`docker.Authorizer` requires library clients to configure scope via context.
It is helpful for the clients to use the helper (currently private) function for
generating scope string and to use that function with the combination of other
scope-related ones (e.g. `docker.WithScope`).
> Allow to use repository scope helper function from other packages

- mount/mount_linux.go
This function was added in https://github.com/containerd/containerd/pull/3765; the error itself was unused, so may as well remove it.
> mount.isFUSE(): remove unused error return, and extract FUSE unmount to a function

- .gitattributes
- .github/workflows/ci.yml
- remotes/docker/auth/fetch.go
- runtime/v2/example/example.go
This PR:
- Enables linter checks on Windows
- Uses the Github Action for golangci-lint, so setup is a bit simpler and we have less things to manage (they also [promise](https://github.com/golangci/golangci-lint-action#performance) better performance due to caching).
This will also make linter errors more expressive:
> Enable linter checks on Windows

- cio/io.go
- pkg/process/exec.go
- pkg/process/init.go
- pkg/process/init_state.go
- runtime/io.go
- runtime/v1/shim/service_linux.go
- runtime/v1/shim/service_unix.go
- runtime/v2/runc/platform.go
Currently the shims only support starting the logging binary process if the
io.Creator Config does not specify Terminal: true. This means that the program
using containerd will only be able to specify FIFO io when Terminal: true,
rather than allowing the shim to fork the logging binary process. Hence,
containerd consumers face an inconsistent behavior regarding logging binary
management depending on the Terminal option.
Allowing the shim to fork the logging binary process will introduce consistency
between the running container and the logging process. Otherwise, the logging
process may die if its parent process dies whereas the container will keep
running, resulting in the loss of container logs.
Signed-off-by: Akshat Kumar kshtku@amazon.com
----
Code to start logging binary referenced …
> Add logging binary support when terminal is true

- .github/workflows/ci.yml
> Move proto format ci check to proto job

- .github/workflows/nightly.yml
Carry https://github.com/containerd/containerd/pull/4191
> Update nightly CI

- test/build.sh
- test/e2e_node/gci-init.sh
- test/e2e_node/init.yaml
Updates the build to support the configuration used for `containerd-master` in the prow k8s tests. After this is in, `containerd-master` will be updated to use the added `e2e_node` configuration here, unblocking the failing e2e tests today which fail since cri is no longer checked out.
> Update test build script to push containerd variant

- docs/registry.md
`[plugin.` -> `[plugins.`
Signed-off-by: shouhei <shouhei.yamaguchi.be@gmail.com>
> Fix typo in examples of registry config

- pkg/cri/server/sandbox_run_linux.go
no_pivot not working in io.containerd.runtime.v1.linux
relates to [1582](https://github.com/containerd/cri/pull/1582)
Signed-off-by: zhangjianming <zhang.jianming7@zte.com.cn>
> fix no-pivot not working in io.containerd.runtime.v1.linux

- .github/workflows/ci.yml
These checks had to be disabled to get the CRI merge completed.
Now these should be added back.
After CRI merge, more time for lint is needed on mac.
> Enable project checks

- diff/lcow/lcow.go
Not reading all the data from the tar reader causes the layer digest mismatch which causes failures during unpack of certain images for lcow. This is the same issue as that of #3569.
> Read trailing data from tar reader

- contrib/apparmor/apparmor_test.go
- contrib/apparmor/template.go
The fix is ported from https://github.com/moby/moby/pull/41518#issue-496766512
Ubuntu 20.10 uses AppArmor 3.0.0-beta1 version.
This causes container not able to start due to invalid syntax in parsing AppArmor version.
Signed-off-by: Evan Tsai <devillordking@gmail.com>
> Support AppArmor beta version format for Ubuntu 20.10

- pkg/cri/server/container_create.go
- pkg/cri/server/sandbox_run.go
Made a change yesterday (https://github.com/containerd/containerd/pull/4630) that passed through snapshotter labels into the wrapper of WithNewSnapshot, but it passed the entirety of the annotations into the snapshotter. This change just filters the set that we care about down to snapshotter specific labels.
Will probably be future changes to add some more labels for LCOW/WCOW and the corresponding
behavior for these new labels.
> Filter snapshotter labels passed to wrapper of WithNewSnapshot

- cmd/ctr/commands/run/run.go
- cmd/ctr/commands/run/run_unix.go
This adds linux cni support to `ctr run` via a `--cni` flag.  This uses the
default configuration for CNI on `ctr` to configure the network namespace for a
container.
> Add CNI support to ctr run

- .github/workflows/ci.yml
`echo "::set-env name=GOPATH::${{ github.workspace }}"` is now [deprecated](https://github.com/containerd/containerd/runs/1260889026?check_suite_focus=true#step:3:5) on Github, so this updates script to use the suggested one `echo "GOPATH=${{ github.workspace }}" >> $GITHUB_ENV`
Also this PR does some cleanup to avoid code repetition.
> Cleanup CI

- cluster/gce
- test/build.sh
> Fixes to run node e2e tests

- container_linux_test.go
- runtime/v2/shim.go
Fixes #4632. See also https://github.com/containerd/containerd/commit/8e598fcb21a41dcdb28046981d69ef1fda171112 for an identical fix made on runc runtime v1.
This does not come with a test, as I don't have enough context to write one, but I'd be happy to add one with some help from the team. FWIW this makes [this test](https://github.com/cloudfoundry/guardian/blob/master/rundmc/runcontainerd/nerd/nerd_linux_test.go#L391-L396) on Garden pass, even after removing [the workaround](https://github.com/cloudfoundry/guardian/blob/3da697a62154c6d1f797aede3a0fb23f2297e6cd/rundmc/runcontainerd/nerd/nerd.go#L222-L234) we have in place at the moment.
> Check if a process exists before returning it

- container_linux_test.go
- runtime/v2/shim.go
Cherry-pick #4645 for `release/1.4`
Signed-off-by: Giuseppe Capizzi <gcapizzi@pivotal.io>
Co-authored-by: Danail Branekov <danailster@gmail.com>
(cherry picked from commit 8eda32e10780dc1adabc2c40f7295d4638d8915d)
> [release/1.4] cherry-pick: Check if a process exists before returning it

- container_linux_test.go
- runtime/v2/shim.go
Cherry-pick #4645 for `release/1.3`
Signed-off-by: Giuseppe Capizzi <gcapizzi@pivotal.io>
Co-authored-by: Danail Branekov <danailster@gmail.com>
(cherry picked from commit 8eda32e10780dc1adabc2c40f7295d4638d8915d)
> [release/1.3] cherry-pick: Check if a process exists before returning it

- diff/lcow/lcow.go
Cherry-pick #4628 for `release/1.4`.
Not reading all the data from the tar reader causes the
layer digest mismatch which causes failures during unpack
of certain images for lcow. This changes fixes that.
Signed-off-by: Amit Barve <ambarve@microsoft.com>
(cherry picked from commit d3b817b95c39d44b94346fa4da3476157f255b91)
> [release/1.4] cherry-pick: Read trailing data from tar reader

- pkg/cri/server/events.go
fixes: https://github.com/containerd/containerd/issues/4655
Signed-off-by: jerryzhuang <zhuangqhc@gmail.com>
> CRI: always set unknown to false when handling exit event

- cmd/ctr/commands/content/content.go
The command-line `ctr content get` uses `io.Copy()`, with the default buffer size of 32KB. This creates significant slow-downs on large files, as the grpc overhead must be incurred with each 32KB chunk. 
This PR changes it to 1MB (1<<20), which is what we use for ingesting content, using `io.CopyBuffer()` instead.
I ran 10 tests on a 1.0GB file, `ctr content get` each with and without the change (yeah, I probably should do a proper go benchmark with hundreds of iterations; if people insist, I can, but it seems unnecessary for such a small change). In all cases I sent the results to `/dev/null`, to avoid any potential issues with disk writes.
* Average before: 13.752s
* Average after: 2.678s
I was rather blown away by the results.
Obviously, little difference on blobs not much bigger than …
> use proper buffer size for content get

- pkg/cri/server/image_pull.go
Signed-off-by: Samarth Shah <samarthmshah@gmail.com>
We leverage stargz-based snapshotter and have implemented our own Filesystem interface. We need the image digest to get some metadata for the image itself.
cc: @cpuguy83 @juliusl @northtyphoon @mikebrow
> Add manifest digest annotation for snapshotters

- pkg/cri/config/config_unix.go
This experimental feature should not be enabled by default as it is not used by any default snapshotters.
For 1.5 we have discussed other ways to handle storing this information rather than continuing to grow the number of labels.
This should also be backported to 1.4 along with the regression fix for labels over the size limit (https://github.com/containerd/cri/pull/1572)
> Update make snapshot annotations disabled by default

- cmd/ctr/commands/commands.go
- cmd/ctr/commands/run/run_unix.go
This adds an option to pass the config path for an external runtime via `runtime-config-path`.
Signed-off-by: Evan Hazlett <ejhazlett@gmail.com>
> config path option to ctr for runtime

- README.md
> README.md: Use go.dev instead of godoc

- container_restore_opts.go
bug fix:#4646
invalid use of nil pointer in container restoring
> bug fix:#4646

- vendor.conf
- vendor/github.com/containerd/cri/README.md
- vendor/github.com/containerd/cri/pkg/config/config_unix.go
- vendor/github.com/containerd/cri/pkg/server/container_create_unix.go
- vendor/github.com/containerd/cri/vendor.conf
This is the "cherry pick" of the CRI config change in #4665, but via a PR against the 1.4 branch in the now-merged CRI sub-project and now a re-vendor.
This includes a few other minor changes in the CRI branch.
> [release/1.4] Re-vendor CRI to get disabled annotation config default

- .github/workflows/ci.yml
cherry pick https://github.com/containerd/containerd/pull/4687
cc @mikebrow @AkihiroSuda
> [release/1.4] cherry-pick: ci: run critest target for all runtimes

- .github/workflows/ci.yml
This is a follow-up to #4232, #4224
See also https://github.com/actions/virtual-environments/issues/731
(`sudo -E` wasn't considered sufficient previously thanks to `secure_path` in `/etc/sudoers` but that's trivially overcome via `PATH=$PATH`)
As the author of `gosu`, I can say without reservation that running it with setuid bits is definitely not recommended (even in a temporary/ephemeral environment with passwordless `sudo`).
> Remove setuid gosu in favor of "sudo -E PATH=$PATH ..."

- .github/workflows/ci.yml
- script/setup/install-critools
Backport of https://github.com/containerd/containerd/pull/4687 (including a bugfix where `EOF"` was not seen as a valid heredoc end marker by bash, preventing the tests from running) and use a version of critest compatible with the vendored containerd/cri.
cc @mikebrow @tianon
> [release/1.3 backport] ci: run critest target for all runtimes + use compatible critest version

- .github/workflows/ci.yml
Signed-off-by: Tianon Gravi <admwiggin@gmail.com>
(cherry picked from commit 17688a733ad0d472ffcf87dabf5d206626f0f338)
Backport #4692 for `release/1.3`
> [release/1.3] backport: Remove setuid gosu in favor of "sudo -E PATH=$PATH ..."

- .github/workflows/ci.yml
Signed-off-by: Tianon Gravi <admwiggin@gmail.com>
(cherry picked from commit 17688a733ad0d472ffcf87dabf5d206626f0f338)
Backport of #4692 to `release/1.4`
> [release/1.4] backport: Remove setuid gosu in favor of "sudo -E PATH=$PATH ..."

- pkg/cri/server/container_create_linux.go
Address an issue originally seen in the k3s 1.3 and 1.4 forks of containerd/cri, https://github.com/rancher/k3s/issues/2240
Even with updated container-selinux policy, container-local /dev/shm
will get mounted with container_runtime_tmpfs_t because it is a tmpfs
created by the runtime and not the container (thus, container_runtime_t
transition rules apply). The relabel mitigates such, allowing envoy
proxy to work correctly (and other programs that wish to write to their
/dev/shm) under selinux.
Tested locally with:
- SELINUX=Enforcing vagrant up --provision-with=shell,selinux,test-integration
- SELINUX=Enforcing CRITEST_ARGS=--ginkgo.skip='HostIpc is true' vagrant up --provision-with=shell,selinux,test-cri
- SELINUX=Permissive CRITEST_ARGS=--ginkgo.focus='HostIpc is true' vagrant up …
> cri: selinux relabel /dev/shm

- .github/workflows/ci.yml
Noticed this in the CI output:
Requested golangci-lint 'v1.29', using 'v1.29.0', calculation took 7969ms
Installing golangci-lint v1.29.0...
Downloading https://github.com/golangci/golangci-lint/releases/download/v1.29.0/golangci-lint-1.29.0-darwin-amd64.tar.gz ...
Using nearly 8 seconds to convert v1.29 to v1.29.0 seems a bit long,
so hard-coding to the full version to speedup CI somewhat.
> gha: specify full version for golang-ci-lint to speedup selection

- Makefile
- script/setup/install-runc
This is no longer needed, as the script is already run with sudo (see https://github.com/containerd/containerd/commit/65df8db2896e6a9f4352bc65bedb4a580b057a66).
> install-runc: remove unused USESUDO variable

- cmd/ctr/commands/commands.go
- cmd/ctr/commands/run/run_unix.go
e.g.
```
$ sudo ./bin/ctr run --apparmor-default-profile "cri-containerd.apparmor.d" docker.io/library/alpine:latest foo cat /proc/self/attr/current
cri-containerd.apparmor.d (enforce)
```
> ctr: add AppArmor flags

- .github/workflows/ci.yml
- Vagrantfile
With container-selinux policy updated to 2.145+ (the default for Fedora 32+) we
can enable SELinux=Enforcing mode in the CI workflow and pass all integration
and CRI tests except one, see https://github.com/containerd/containerd/issues/4460,
which has been marked as skipped.
Tested locally with:
- SELINUX=Enforcing vagrant up --provision-with=shell,selinux,test-integration
- SELINUX=Enforcing vagrant up --provision-with=shell,selinux,test-cri
Signed-off-by: Jacob Blain Christen <jacob@rancher.com>
> test: run tests with selinux enforcing

- .github/workflows/ci.yml
CI was timing out after 15 minutes on the crun tests; extending the timeout to 20 minutes (we can make it shorter again if we know the exact time it takes to run)
e.g. https://github.com/containerd/containerd/pull/4578/checks?check_run_id=1380571893
> ga: Linux Integration: extend timeout to 20 minutes

- .github/workflows/ci.yml
- .github/workflows/nightly.yml
- .github/workflows/release.yml
- .travis.yml
- .zuul/playbooks/containerd-build/run.yaml
- Vagrantfile
- contrib/Dockerfile.test
Cherry-pick https://github.com/containerd/containerd/pull/4050
> [release/1.4] update to golang 1.15.2

- remotes/docker/pusher.go
When write calls have succeeded on push but the request fails after that, the original error is hidden away and error just shows "no response". This PR keeps the original error.
> docker: don’t hide pusher response error

- cmd/ctr/commands/images/unmount.go
Fix the following incorrect unmount error hint:
[root@localhost ~]# ctr images unmount
ctr: please provide a target path to mount to
Signed-off-by: Li Ning <lining@cmss.chinamobile.com>
> ctr: fix the incorrect image unmount error hint

- docs/content-flow.md
- docs/getting-started.md
- docs/installation.md
This change fixes broken links in docs/.
> docs: fix broken links

- vendor.conf
- vendor/github.com/containerd/btrfs/btrfs.go
- vendor/github.com/containerd/btrfs/go.mod
> Update btrfs vendor for chkptr fix for Go >= 1.14

- contrib/seccomp/seccomp_default.go
Similar to the changes merged in https://github.com/moby/moby/pull/41665 (thanks @mikroskeem)
- seccomp: add `pidfd_open` and `pidfd_send_signal`
- seccomp: add `pidfd_getfd` syscall (gated by `CAP_SYS_PTRACE`)
> seccomp: add pidfd syscalls

- content/helpers.go
Private registries that does not support http 2.0 such as Azure Container Registry streams back content in a max of 16KB chunks (max TLS record size). The small chunks introduce an overhead when copying the layers to the content store sine each chunk incurs the overhead of  grpc message that has to be sent to the content store.
This change reduces this overhead by buffering the chunks into 1MB chunks and only then writes a message to the content store.
Below is a per comparsion between the 2 approaches using a couple of large images that are being pulled from the docker hub (http 2.0) and a private Azure CR (http 1.1) in seconds.
image                                                   | Buffered copy | master
------- …
> Improve image pull performance from http 1.1 container registries

- contrib/seccomp/seccomp_default.go
backport of https://github.com/containerd/containerd/pull/4730
Similar to the changes merged in https://github.com/moby/moby/pull/41665
- seccomp: add `pidfd_open` and `pidfd_send_signal`
- seccomp: add `pidfd_getfd` syscall (gated by `CAP_SYS_PTRACE`)
> [release/1.4 backport] seccomp: add pidfd syscalls

- diff/lcow/lcow.go
- platforms/defaults_windows.go
- snapshots/lcow/lcow.go
> Do not hardcode "amd64" on LCOW and Windows-related files

- .github/workflows/ci.yml
Also switch to use pre-packaged containerd project checks
(cherry picked from commit 0a3488c712d699694f7b2c2458e7498f29d5e89a)
From #4743
> [release/1.3] cherry-pick: Fix GH Actions CI deprecations

- cmd/containerd/command/service_windows.go
You can test this by doing:
```
make binaries GOOS=windows GOARCH=arm
```
Before this there are compiler errors due to integer overflows.
> Fix integer overflow on windows

- content/helpers.go
Improve image pull performance from http 1.1 container registries
(cherry picked from commit cc3785c815a1b560c088e3c349a91d3e0851b0bf)
Signed-off-by: Amr Mahdi <amramahdi@gmail.com>
> [release/1.4] Improve image pull performance from http 1.1 container registries

- .github/workflows/ci.yml
- snapshots/overlay/overlay_test.go
- snapshots/testsuite/testsuite.go
- sys/oom_unix_test.go
Related to #4705:  re-enable tests hidden by removal of "coverage" targets
I will drop the first commit and rebase when #4705 is merged but want to verify we can get passing tests
> Reenable make test targets in GH Actions CI

- cmd/containerd/command/service_windows.go
Go 1.14 introduced a change to os.OpenFile (and syscall.Open) on Windows
that uses the permissions passed to determine if the file should be
created read-only or not. If the user-write bit (0200) is not set, then
FILE_ATTRIBUTE_READONLY is set on the underlying CreateFile call.
This is a significant change for any Windows code which created new
files and set the permissions to 0 (previously the permissions had no
affect, so some code didn't set them at all).
This change fixes the issue for the Windows service panic file. It will
now properly be created as a non-read-only file on Go 1.14+.
I have looked over the rest of the containerd code and didn't see other
places where this seems like an issue.
> Fix Windows service panic file to not be read-only

- cmd/containerd/command/service_windows.go
Go 1.14 introduced a change to os.OpenFile (and syscall.Open) on Windows
that uses the permissions passed to determine if the file should be
created read-only or not. If the user-write bit (0200) is not set, then
FILE_ATTRIBUTE_READONLY is set on the underlying CreateFile call.
This is a significant change for any Windows code which created new
files and set the permissions to 0 (previously the permissions had no
affect, so some code didn't set them at all).
This change fixes the issue for the Windows service panic file. It will
now properly be created as a non-read-only file on Go 1.14+.
I have looked over the rest of the containerd code and didn't see other
places where this seems like an issue. …
> [release/1.4] Fix Windows service panic file to not be read-only

- rootfs/apply.go
- snapshots/lcow/lcow.go
- snapshots/snapshotter.go
- snapshots/windows/windows.go
- unpacker.go
For LCOW currently we copy (or create) the scratch.vhdx for every single snapshot
so there ends up being a sandbox.vhdx in every directory seemingly unnecessarily. With the default scratch
size of 20GB the size on disk is about 17MB so there's a 17MB overhead per layer plus the time to copy the
file with every snapshot. Only the final sandbox.vhdx is actually used so this would be a nice little
optimization.
For WCOW we essentially do the exact same except copy the blank vhdx from the base layer.
> Optimize Windows and LCOW snapshotters to only create scratch layer on the final snapshot

- reference/reference.go
- reference/reference_test.go
An image ref must be a scheme-less URI. A reference with scheme (such
as `http://`) must return ErrInvalid.
> Handle an image ref with scheme

- container_linux_test.go
- container_test.go
- runtime/v2/shim.go
If the shim has been killed and ttrpc connection has been
closed, the shimErr will not be nil. For this case, the event
subscriber, like moby/moby, might have received the exit or delete
events. Just in case, we should allow ttrpc-callback-on-close to
send the exit and delete events again. And the exit status will
depend on result of shimV2.Delete.
If not, the shim has been delivered the exit and delete events.
So we should remove the task record and prevent duplicate events from
ttrpc-callback-on-close.
Fix: #4769
> runtime: should not send duplicate task exit event

- ADOPTERS.md
Add the Inclavare-Containers container runtime which launches the containers in hardware-assisted TEE to the adopters list.
> Add the Inclavare-Containers container runtime to the adopters list

- pkg/cri/server/container_create_linux.go
When a base runtime spec is being used, admins can configure defaults for the
spec so that default ulimits or other security related settings get applied for
all containers launched.
> [cri] don't clear base security settings

- archive/tar.go
- archive/tar_opts.go
- archive/tar_windows.go
- go.mod
- go.sum
- vendor/github.com/Microsoft/go-winio/backuptar/noop.go
- vendor/github.com/Microsoft/go-winio/backuptar/strconv.go
- vendor/github.com/Microsoft/go-winio/backuptar/tar.go
- vendor/modules.txt
_archive/tar\_windows.go_ mostly consisted of two large functions reimplementing functions in https://github.com/microsoft/go-winio/, which is already a dependency of this file.
This uses those functions instead, as a deduplication, and preparation for implementing `diff.Comparer`, per #4394.
~~Note that until https://github.com/microsoft/go-winio/pull/175 is merged and vendored, this brings in a fork of Go's `archive/tar`, used as `winio_tar` **only in _archive/tar\_windows.go_**. Once that lands, the changes in _archive/tar.go_ and _archive/tar\_opts.go_ can be reverted.~~ <== This is now done in v0.4.15.
~~https://github.com/microsoft/go-winio/ is revendored from v0.4.14 to v0.4.15, but most of [the upstream changes](https://github.com/microsoft/go-winio/compare/v0.4.14...v0.4.15) were …
> Use go-winio for applying tarballs

- cmd/containerd/command/main.go
- log/context.go
- services/server/config/config.go
This PR allows configuring logrus to output in 2 different formats:
- text (default which is today)
- json (new addition)
The way I've configured this is to be via the `debug` section in the toml config. I did not add a CLI flag for this, curious if you folks think this would be useful here. In my experience I've found all my interactions with containerd via the toml config.
> Allow configuration of different log formats: text, json

- pkg/apparmor/apparmor.go
- pkg/apparmor/apparmor_unsupported.go
- pkg/cri/server/helpers_linux.go
Expose `hostSupportsAppArmor()` as `pkg/apparmor.HostSupports`.
This function is expected to be used by https://github.com/AkihiroSuda/nerdctl
> expose hostSupportsAppArmor()

- pkg/cri/config/config.go
Go uses the same address variable while iterating in a range, so use a copy when using its address.
Sample code to highlight the issue: https://play.golang.org/p/YSqm1Gu3O0i
> [cri/config] : fix range iterator issue in ValidatePluginConfig

- BUILDING.md
- Makefile
- pkg/apparmor/apparmor.go
- pkg/apparmor/apparmor_unsupported.go
The "apparmor" build tag does not have any cgo dependency and can be removed safely.
Related: https://github.com/opencontainers/runc/issues/2704
> remove "apparmor" build tag

- cmd/ctr/commands/content/fetch.go
The additional `[]containerd.RemoteOpt` is not used by ctr currently, but planned to be used by [nerdctl](https://github.com/AkihiroSuda/nerdctl) and also probably by stargz's ctr-remote.
> ctr: FetchConfig: allow setting additional []containerd.RemoteOpt

- .github/workflows/ci.yml
- archive/tar_freebsd.go
- archive/tar_mostunix.go
- archive/tar_unix.go
- cmd/containerd-shim/shim_freebsd.go
- go.mod
- go.sum
- vendor/github.com/containerd/continuity/AUTHORS
- vendor/github.com/containerd/continuity/README.md
- vendor/github.com/containerd/continuity/devices/devices_unix.go
- vendor/github.com/containerd/continuity/devices/mknod_freebsd.go
- vendor/github.com/containerd/continuity/devices/mknod_unix.go
- vendor/github.com/containerd/continuity/fs/copy_darwinopenbsdsolaris.go
- vendor/github.com/containerd/continuity/fs/copy_freebsd.go
- vendor/github.com/containerd/continuity/fs/copy_unix.go
- vendor/github.com/containerd/continuity/fs/du_unix.go
- vendor/modules.txt
This PR updates continuity to include https://github.com/containerd/continuity/pull/173 and updates containerd to compile for FreeBSD.  The built containerd and ctr binaries run, with some plugins not yet loading.
```
% sudo ctr plugin ls
TYPE                            ID                       PLATFORMS        STATUS    
io.containerd.content.v1        content                  -                ok        
io.containerd.snapshotter.v1    native                   freebsd/amd64    ok        
io.containerd.metadata.v1       bolt                     -                ok        
io.containerd.differ.v1         walking                  freebsd/amd64    ok        
io.containerd.gc.v1             scheduler                -                ok        
io.containerd.service.v1 …
```
> Build on FreeBSD

- contrib/apparmor/apparmor.go
Expected to be used by nerdctl: https://github.com/AkihiroSuda/nerdctl/blob/6026ae740a52136a5674f322f133f9e3998dc0dc/internal_oci_hook.go#L170-L180
> contrib/apparmor: expose LoadDefaultProfile

- runtime/v2/binary.go
- runtime/v2/manager.go
- runtime/v2/shim.go
This back ports;
- https://github.com/containerd/containerd/pull/3921 v2: Call shim.Delete at first when create is failed
- https://github.com/containerd/containerd/pull/3929 v2: Fix missing ns when openShimLog on windows
- follow up to https://github.com/containerd/containerd/pull/3921#discussion_r363046745
- https://github.com/containerd/containerd/pull/4046: v2: Cancel shim log ctx when ttrpc is closed
- was marked for cherry-picking; https://github.com/containerd/containerd/pull/4046#issuecomment-589662202
The first two cherry-picks were to get a clean backport, but (from the description) seem good to have
> [release/1.3 backport] v2: Cancel shim log ctx when ttrpc is closed

- runtime/restart/restart.go
The new function `WithLogURI(uri *url.URL)` replaces `WithBinaryLogURI(binary string, args map[string]string)` so as to allow passing an existring URI object.
> restart: allow passing existing log URI object

- .github/workflows/ci.yml
- snapshots/devmapper/pool_device.go
- snapshots/devmapper/snapshotter.go
Enables the devmapper tests back (after disabling them in https://github.com/containerd/containerd/pull/4719#issuecomment-730002886)
We have included a few patches recently that affected unit tests:
- 2b87d4554f08456b7b4476bf2d15a3dbd9083c26 adds a fix to pass tests after https://github.com/containerd/containerd/pull/4374
- da686098668ec60eaca77dd82076044b5aad6698 partially reverts changes from https://github.com/containerd/containerd/pull/4235 (makes device removal deferred). @renzhengeek PTAL whether this still works for your case.
> Enable devmapper tests

- container_opts.go
`WithAdditionalContainerLabels()` preserves the existing entries in c.Labels.
OTOH, `WithContainerLabels()` clears them.
> container_opts.go: add WithAdditionalContainerLabels

- client.go
- client_test.go
- image.go
- image_test.go
- services/introspection/introspection.go
- snapshots/windows/windows.go
- unpacker.go
This work is to prevent a snapshotter from attempting to unpack an image with a platform the snapshotter doesn't support. 
For example, a windows snapshotter attempting to unpack an image with a target linux/amd64 platform. Previously, the snapshotter would attempt to unpack this image and fail with an obscure message. This work instead returns an error earlier on indicating the underlying issue that the snapshotter doesn't support the target image platform. 
Additionally updated the target windows image used for testing. 
> add check that snapshotter supports the image platform when unpacking

- README.md
containder/containerd changes for https://github.com/containerd/containerd/issues/4572
Some of the commands mentioned in the old cri README are now outdated with the integration. 
Such as the build tags, way to install dependencies, running a Kubernetes local cluster with ./hack/local-up-cluster.sh
So reduced scope of Getting Started for Developers section
> Mention built-in CRI support in README

- container_linux_test.go
- runtime/v1/shim/client/client.go
- runtime/v2/shim/util_unix.go
- sys/oom_unix.go
- sys/oom_windows.go
oom_score_adj must be in the range -1000 to 1000. In AdjustOOMScore if containerd's score is already at the maximum value we should set that value for the shim instead of trying to set 1001 which is invalid.
Fixes #4837
Signed-off-by: Simon Kaegi <simon_kaegi@ca.ibm.com>
> Add bounds on max oom_score_adj value for AdjustOOMScore

- pkg/cri/server/helpers_linux.go
containerd is responsible for creating the log but there is no code to ensure
that the log dir exists.  While kubelet should have created this there can be
times where this is not the case and this can cause stuck tasks.
> [cri] ensure log dir is created

- container_linux_test.go
- runtime/v2/runc/v2/service.go
When the shim returns a plain error when a process does not exist,
the server is unable to recognise its GRPC status code and assumes
UnknownError. This is awkward for containerd client users as they are
unable to recognise the actual reason for the error.
When the shim returns a NotFound GRPC error, it is properly translated
by the server and clients receive a proper NotFound error instead of
Unknown
Please note that we (CF Garden) would like to have the eventual fix backported to 1.4 as well.
Co-authored-by: Georgi Sabev <georgethebeatle@gmail.com>
> Return GRPC not found error instead of plain one

- container_linux_test.go
- runtime/v1/shim/client/client.go
- runtime/v2/shim/util_unix.go
- sys/oom_unix.go
- sys/oom_windows.go
oom_score_adj must be in the range -1000 to 1000. In AdjustOOMScore if containerd's score is already at the maximum value we should set that value for the shim instead of trying to set 1001 which is invalid.
Signed-off-by: Simon Kaegi <simon_kaegi@ca.ibm.com>
(cherry picked from commit da2fd657ab109d71e68ae46799eec54d4f8e21a6)
> [release/1.4] cherry-pick: Add bounds on max oom_score_adj value for AdjustOOMScore

- container_linux_test.go
- runtime/v1/shim/client/client.go
- runtime/v2/shim/util_unix.go
- sys/oom_unix.go
- sys/oom_windows.go
oom_score_adj must be in the range -1000 to 1000. In AdjustOOMScore if containerd's score is already at the maximum value we should set that value for the shim instead of trying to set 1001 which is invalid.
Signed-off-by: Simon Kaegi <simon_kaegi@ca.ibm.com>
(cherry picked from commit da2fd657ab109d71e68ae46799eec54d4f8e21a6)
> [release/1.3] cherry-pick: Add bounds on max oom_score_adj value for AdjustOOMScore

- fuzz/filters_fuzzers.go
- fuzz/platforms_fuzzers.go
This PR adds two fuzzers to set up continuous fuzzing for containerd on the OSS-fuzz platform.
Fuzzing is a method for testing whereby pseudo-random data is passed to a target entry point in an application - which in these two fuzzers are filters.Parse and platforms.Parse respectively. The application is then observed in the hope of finding bugs and vulnerabilities.
Integrating containerd into OSS-fuzz will allow these two fuzzers to run continuously and look for harder-to-find bugs. If bugs are found maintainers get notified with emails containing a link to a detailed bug report that includes stacktrace and reproducible test case.
I have set up a draft integration PR on the OSS-fuzz side that will be updated according to the progression of this PR: …
> Add two fuzzers to integrate containerd into OSS-fuzz

- container_linux_test.go
- runtime/v2/runc/v2/service.go
When the shim returns a plain error when a process does not exist,
the server is unable to recognise its GRPC status code and assumes
UnknownError. This is awkward for containerd client users as they are
unable to recognise the actual reason for the error.
When the shim returns a NotFound GRPC error, it is properly translated
by the server and clients receive a proper NotFound error instead of
Unknown
Co-authored-by: Danail Branekov <danailster@gmail.com>
Co-authored-by: Danail Branekov <danailster@gmail.com>
Signed-off-by: Danail Branekov <danailster@gmail.com>
Signed-off-by: Georgi Sabev <georgethebeatle@gmail.com>
> [release/1.4 backport] Return GRPC not found error instead of plain one

- .github/ISSUE_TEMPLATE/config.yml
Add `.github/ISSUE_TEMPLATE/config.yml` to clarify where is the right place (in the most cases) to ask questions.
ref: https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/configuring-issue-templates-for-your-repository#configuring-the-template-chooser
> add guidance about GitHub Discussions

- platforms/compare_test.go
This adds a test for `platforms.Only` (previously untested, as far as I can tell).
(This is the hopefully less-controversial part of #4528? :sweat_smile: :heart:)
> Add platforms.Only test

- image_test.go
- platforms/compare.go
This improves the hard-coded list of ARM fallbacks in the `platform.Only` implementation (by doing a descending loop over variant numbers instead, which is all the hard-coded list was doing).
Making this a separate function can then more easily be recursive later for handling an `arm64`->`arm` fallback (or similar), but I think it makes the code a lot more clear too (so we're calculating a vector of platforms separately from building a matcher object).
This also makes a minor adjustment in `TestImagePullWithDistSourceLabel` which had an implicit assumption that `platforms.Only` would only ever result in a single suitable manifest, which isn't strictly true (and is likely failing as-is when run on any 32bit `arm` system that's `v6` or higher, which this fixes 😅).
Additionally, this makes …
> Refactor platforms.Only with a "platformVector" helper

- .github/ISSUE_TEMPLATE/config.yml
"report a security issue" button was shown redundantly in https://github.com/containerd/containerd/issues/new/choose
> ISSUE_TEMPLATE: remove redundant "report a security issue" button

- cmd/ctr/commands/images/export.go
- images/archive/exporter.go
- images/mediatypes.go
The flag skips adding non-distributable blobs such as Windows layers to archive.
> export: add --skip-non-distributable

- api/events/container.proto
- api/events/content.proto
- api/events/image.proto
- api/events/namespace.proto
- api/events/snapshot.proto
- api/events/task.proto
- api/services/containers/v1/containers.proto
- api/services/content/v1/content.proto
- api/services/diff/v1/diff.proto
- api/services/events/v1/events.proto
- api/services/images/v1/images.proto
- api/services/introspection/v1/introspection.proto
- api/services/leases/v1/leases.proto
- api/services/namespaces/v1/namespace.proto
- api/services/snapshots/v1/snapshots.proto
- api/services/tasks/v1/tasks.proto
- api/services/ttrpc/events/v1/events.proto
- api/services/version/v1/version.proto
- api/types/descriptor.proto
- api/types/metrics.proto
- api/types/mount.proto
- api/types/platform.proto
- api/types/task/task.proto
- runtime/v1/shim/v1/shim.proto
- runtime/v2/task/shim.proto
I was copy-pasting proto files for a personal containerd-related project and noticed that we don't have copyright headers (which makes it sort of uncomfortable to copy-paste). 
> Add copyright header to proto files

- services/introspection/introspection.go
Demote `Info("remote introspection plugin filters")` to `Debug()`
> introspection: demote log level

- mount/mount_freebsd.go
- mount/mount_unix.go
- snapshots/native/native.go
- snapshots/native/native_default.go
- snapshots/native/native_freebsd.go
This PR adds support for the native snapshotter on FreeBSD using FreeBSD [nullfs](https://www.freebsd.org/cgi/man.cgi?query=nullfs&sektion=&n=1).
The native snapshotter passes its test suite and is able to unpack an image for the `freebsd`/`amd64` platform:
```
% freebsd-version
12.1-RELEASE-p4
% pwd
/home/sam/go/src/github.com/containerd/containerd/snapshots/native
% sudo go test -v -test.root .
[...trimmed output...]
--- PASS: TestNaive (0.01s)                                                                                                                                              
--- PASS: TestNaive/Basic (0.03s)                                                                                                                                    
--- PASS: TestNaive/128LayersMount …
```
> Support the native snapshotter on FreeBSD

- runtime/v2/manager.go
> runtime/v2: should use defer ctx to cleanup

- diff/stream.go
- diff/stream_unix.go
- diff/stream_windows.go
- services/server/config/config.go
- services/server/server.go
Add support for an 'envs' field to the StreamProcessor configuration
and append it to the os.Environ() array.
The envs field takes environment variables in the form of key=value.
> Allow passing environent variables to StreamProcessors

- runtime/v2/manager.go
(cherry picked from commit 846cb963cc4fe20237092bdbe62828dfe2ff1541)
cherry-pick: https://github.com/containerd/containerd/pull/4923
> [release/1.4] runtime/v2: should use defer ctx to cleanup

- runtime/v2/manager.go
(cherry picked from commit 846cb963cc4fe20237092bdbe62828dfe2ff1541)
cherry-pick: https://github.com/containerd/containerd/pull/4923
> [release/1.3] runtime/v2: should use defer ctx to cleanup

- remotes/docker/resolver.go
Recently I started reading the containerd 's source code, when I read at `remotes/docker/resolver.go`,  find there are some codes are too similar and repetitive.
So I just add a `resolveDockerBase` helper for it , the changed code looks more  simple.
> Refactor dockerResolver with resolveDockerBase helper

- platforms/compare.go
- platforms/compare_test.go
This ~~adds a test for `platforms.Only` (previously untested, as far as I can tell), improves the hard-coded list of ARM fallbacks in the `platform.Only` implementation (by doing a descending loop over variant numbers instead, which is all the hard-coded list was doing), and~~ adds `386` as a fallback architecture for `amd64`.
I'd like to do something similar for `arm64` (falling back to `linux/arm/v8`, `linux/arm/v7`, etc, which I think would more accurately fix what was reported in https://github.com/containerd/containerd/issues/3990 and allow us to revert https://github.com/containerd/containerd/pull/4013), but figured I'd start with this and see what the interest in the approach is. :heart:
> Add amd64->386 fallback

- remotes/docker/resolver.go
Header.Clone() will return `nil` if called on a nil object.
Fixes a panic seen in the unit tests after #4302 was merged.
> Ensure request.header is never nil

- platforms/compare.go
- platforms/compare_test.go
- platforms/cpuinfo.go
This isn't supported by *all* arm64 chips, but it is common enough that I think it's worth an explicit fallback.  I think it will be more common for images to have arm64 support without arm support, but even if a user has an arm64 chip that does not support arm32, having it fail to run the arm32 image is an acceptable compromise (because it's non-trivial to detect arm32 support without running a binary, AFAIK).
Also, before this change the failure would've simply been "no such image" instead of "failed to run" so I think it's pretty reasonable to allow it to try the additional 32bit set of images just in case one of them actually does work (like it will on many popular chips like 64bit Raspberry Pis and AWS Graviton).
This also reverts https://github.com/containerd/containerd/pull/4013 …
> Allow arm64 to fallback to arm (v8, v7, v6, v5)

- platforms/cpuinfo.go
- platforms/defaults.go
- platforms/defaults_test.go
- platforms/platforms.go
- platforms/platforms_test.go
This changes `platforms.Parse` to hit `/proc` to look up CPU info only when it's needed, instead of in `init()`. This makes the package a bit easier for other packages to consume, especially clients that don't call `platforms.Parse` or need to lookup CPU info.
This recently came up in https://github.com/google/go-containerregistry/issues/916 since go-containerregistry imports moby/moby, which imports containerd/containerd/platforms to call `platforms.Parse` when starting a container -- go-containerregistry never starts containers and doesn't care about the value of `platforms.Parse` or `cpuInfo`.
cc @jonjohnsonjr
> Derive cpuinfo as needed, instead of at init-time

- platforms/compare.go
- platforms/compare_test.go
- platforms/defaults.go
`OnlyStrict()` returns a match comparer for a single platform.
Unlike `Only()`, `OnlyStrict()` does not match sub platforms.
So, "arm/vN" will not match "arm/vM" where M < N, and "amd64" will not also match "386".
`OnlyStrict()` matches non-canonical forms. So, "arm64" matches "arm/64/v8".
> platforms: add subarchless version of Only()

- releases/v1.5.0-beta.toml
- version/version.go
First draft for 1.5 release notes.
This release is quite a bit smaller than 1.4 in terms of number of feature PRs. Most of the fix PRs in this release were already backported to 1.4.
> Add release notes for v1.5.0-beta.0

- cmd/ctr/commands/images/pull.go
- cmd/ctr/commands/snapshots/snapshots.go
This PR is the follow up to discussion in https://github.com/containerd/containerd/pull/4797. 
This PR adds the option to print the pulled image's chain id in a ctr "images pull" call. This can be used to feed into a call to "snapshots prepare/view" for creating new snapshots for the user. 
From the previous PR: 
> This new command is helpful for functional/unit tests in shims because it allows users to retrieve the layer mounts that would be used for creating a new container. Users can then manipulate or use these layer mounts as needed to test specific scenarios.
> 
> As an example, in https://github.com/microsoft/hcsshim we have a functional tests package for unit testing here. However, in order for us to unit test our shim, we must manually start a container or VM with an image's …
> Add a new flag to ctr "images pull" to print the image's chainID

- snapshots/lcow/lcow.go
Currently we would create a new disk and mount this into the LCOW UVM for every container but there
are certain scenarios where we'd rather just mount a single disk and then have every container share this one
storage space instead of every container having it's own xGB of space to play around with.
This is accomplished by just making a symlink to the disk that we'd like to share and then
using ref counting later on down the stack in hcsshim if we see that we've already mounted this
disk.
> Add scratch space re-use functionality to LCOW snapshotter

- cmd/ctr/commands/images/convert.go
- cmd/ctr/commands/images/images.go
- convert_test.go
- images/converter/converter.go
- images/converter/default.go
- images/converter/uncompress/uncompress.go
- images/diffid.go
- images/mediatypes.go
- labels/labels.go
Go example:
```go
opts := []converter.Opt{
// convert Docker media types to OCI ones
converter.WithDocker2OCI(true),
// convert tar.gz layers to uncompressed tar layers
converter.WithLayerConvertFunc(uncompress.LayerConvertFunc),
}
srcRef := "example.com/foo:orig"
dstRef := "example.com/foo:converted"
dstImg, err = converter.Convert(ctx, client, dstRef, srcRef, opts...)
fmt.Println(dstImg.Target)
```
ctr example: `ctr images convert --oci --uncompress example.com/foo:orig example.com/foo:converted`
Go test: `go test -exec sudo -test.root -test.run TestConvert`
The implementation is from https://github.com/containerd/stargz-snapshotter/pull/224, but eStargz-specific functions are not included in this PR.
eStargz converter can be specified by importing `estargz` package and using …
> add Image content converter

- cmd/ctr/commands/tasks/tasks_windows.go
- runtime/v2/logging/logging.go
- runtime/v2/logging/logging_unix.go
- runtime/v2/logging/logging_windows.go
Add windows version of the logging driver. Add log-uri parsing to windows ctr.
Signed-off-by: Maksim An <maksiman@microsoft.com>
> Enhance logging driver to support windows

- cmd/containerd/builtins_btrfs_linux.go
- snapshots/btrfs/btrfs.go
- snapshots/btrfs/btrfs_test.go
- snapshots/btrfs/plugin/plugin.go
btrfs plugin needs CGO support. However on riscv64, cgo
is only support on go1.16 (not released yet).
Instead of setting no_btrfs manually, adding a cgo tag tells
the compiler to skip it automatically.
> Add cgo tag to btrfs plugin

- cmd/ctr/commands/content/content.go
- cmd/ctr/commands/content/prune.go
This removes the layer reference labels on content and calls a synchronous garbage collection afterwards. This can be used to remove layer content from the content store without having an affect on any content which is being actively used or pulled. The pull leases will content to hold these actively used layers even while the prune is being called.
> Add prune command to remove layer references

- pkg/cri/server/container_start.go
- pkg/cri/server/container_stop.go
- pkg/cri/server/events.go
- pkg/cri/server/restart.go
- pkg/cri/server/sandbox_run.go
- pkg/cri/server/sandbox_stop.go
The current design is that all the task exit events are put into one queue. The event consumer will consume the event one by one, serially and there is only one consumer. The consumer is required to handle one task in 10 seconds. If timeout, consumer will put it back into backoff queue and retry it later.
If the node has to evict many pods for some reason, like disk pressure, the backlog of handling task exit event will increases. If each one exit event needs 10 seconds, the deletion of pods will take long time. 
For this case, I would like to propose to handle task exit event in parallel. When the container/sandbox monitors receive the task exit event, the monitor should handle it first. If it failed, it can put the event into backoff queue and event consumer can try it later. …
> cri: handle sandbox/container exit event in parallel

- content/adaptor.go
- content/local/store.go
- metadata/adaptors.go
- metadata/content.go
While Walk() has been taking filter string, it was not using the parameter.
This change actually makes the filtering work.
> content: support filters on local.store#Walk()

- pkg/cri/annotations/annotations.go
- pkg/cri/server/container_create_linux.go
- pkg/cri/server/container_create_linux_test.go
- pkg/cri/server/container_create_windows.go
- pkg/cri/server/container_create_windows_test.go
- pkg/cri/server/sandbox_run_linux.go
- pkg/cri/server/sandbox_run_linux_test.go
- pkg/cri/server/sandbox_run_windows.go
- pkg/cri/server/sandbox_run_windows_test.go
cri-o has annotations for pod name, namespace and container name:
https://github.com/containers/podman/blob/master/pkg/annotations/annotations.go
But so far containerd had only the container name.
This patch will be useful for seccomp agents to have a different behaviour depending on the pod (see runtime-spec PR 1074 and runc PR 2682). This should simplify the code in:
https://github.com/kinvolk/seccompagent/blob/b2d423695d6dfc976d2456769acb19765a9d7524/pkg/kuberesolver/kuberesolver.go#L16-L27
Signed-off-by: Alban Crequy <alban@kinvolk.io>
cc @rata @mauriciovasquezbernal
> cri: add annotations for pod name and namespace

- pkg/cri/server/instrumented_service.go
This was dumping untrusted output to the debug logs from user containers.
We should not dump this type of information to reduce log sizes and any
information leaks from user containers.
> remove exec sync debug contents from logs

- Makefile
relates to https://github.com/containerd/containerd/pull/4717#issuecomment-768295224
`make vendor` did not do a `go mod tidy` after vendoring, whereas CI does this as part of the vendor validation, causing CI to fail if `make vendor` was used to update vendoring, without doing a `go mod tidy` afterwards.
> Makefile: run "go mod tidy" when vendoring

- runtime/v2/binary.go
- runtime/v2/shim.go
- runtime/v2/shim_unix.go
From #4905 
If shim never call openLog or died, some thread of containerd will hang on openat.
Considering #3266 and #4046, open the fifo with RDWR and close the fifo-wrapper when shim closed.
Signed-off-by: payall4u <payall4u@qq.com>
> bugfix: change the flag of open log fifo to avoid containerd hang on syscall open

- snapshots/devmapper/snapshotter_test.go
This test has been flaky in GitHub Actions. This change logs the
values from devmapper to further investigate the issue.
> snapshot/devmapper: log actual values to investigate #4965

- runtime/v2/runc/v2/service.go
@crosbymichael 
Even if the service is no longer in use after `Shutdown`, I think it is important to unlock `service.mu`
If `os.Exit` is called, it may be possible not to unlock `service.mu`
https://github.com/containerd/containerd/pull/3204/files#diff-784b061d666f1368d1c3be590b14a7bdc559e199b0855349b993a395bbd2cdb5L573
> runtime: fix shutdown runc v2 service

- runtime/v2/runc/v2/service.go
Signed-off-by: IceberGu <wei.cai-nat@daocloud.io>
(cherry picked from commit b458583b76e84204dca17587625757247bb4053e)
Cherry-pick: https://github.com/containerd/containerd/pull/4988
> [release/1.3] runtime: fix shutdown runc v2 service

- runtime/v2/runc/v2/service.go
Signed-off-by: IceberGu <wei.cai-nat@daocloud.io>
(cherry picked from commit b458583b76e84204dca17587625757247bb4053e)
Cherry-pick: https://github.com/containerd/containerd/pull/4988
> [release/1.4] runtime: fix shutdown runc v2 service

- client_test.go
The variable `buf` is connected to containerd's stdout. So, accessing
the variable before killing containerd can cause a race condition.
> test: stop containerd before accessing the stdout

- pkg/cri/config/config.go
- pkg/cri/config/config_test.go
In the old field `registry.auths` in containerd 1.2, the field has the scheme. https://github.com/containerd/cri/blob/release/1.4/docs/registry.md#configure-registry-credentials
However, in the new field `registry.configs` introduced in containerd 1.3 and above, the field doesn't need the scheme any more. https://github.com/containerd/cri/blob/master/docs/registry.md#configure-registry-credentials
Although containerd 1.2 is End-Of-Life, the config option field is not removed yet, so we should do the conversion correctly.
This should probably be cherrypicked into 1.3 and 1.4.
> Fix deprecated registry auth conversion.

- .github/workflows/ci.yml
relates to https://github.com/containerd/containerd/pull/4717#issuecomment-773465081
using the same hack as https://github.com/opencontainers/runc/pull/2787 to reduce flakiness
> download.fedoraproject.org gives HTTP 404 at times, breaking the CI. Let's give it another chance.
> ci/gha/fedora: retry vagrant up

- cio/io.go
- cio/io_unix.go
- cio/io_windows.go
This relates to https://github.com/docker/for-linux/issues/1186. Perhaps this needs synchronisation elsewhere, but looks like this could potentially panic here as well. Seems not harmful to check for `nil`.
This change is mostly defensive; when checking for the returned error, it's easy to make a mistake, and check for a "local" error, not the actual returned error.
This patch changes the function to use a named return variable, which is checked in the defer.
The defer functions were checking the local variable, and would therefore not be executed, as the function returned if an error occurred.
Perhaps best illustrated when renaming the local variables;
```go
if fifos.Stdin != "" {
l, err1 := winio.ListenPipe(fifos.Stdin, nil)
if err1 != nil {
return nil, errors.Wrapf(err1, "failed to …
```
> cio: prevent NPE when closing, and fix pipes potentially not being closed on Windows 

- snapshots/devmapper/snapshotter_test.go
The change I made at db6075fc2 didn't show its parameters correctly.
> test: fix assert.Check's argumets to show its parameters correctly

- mount/losetup_linux.go
- mount/losetup_linux_test.go
- mount/mount_linux.go
setupLoop()'s Autoclear (LO_FLAGS_AUTOCLEAR) will destruct the
loopback device when all FDs are closed.
However since setupLoop() returns a file name, not a file handle,
the looppack device will be destructed at the end of the function all the time.
> mount: setupLoop() doesn't work with with Autoclear

- .github/workflows/ci.yml
- .github/workflows/nightly.yml
- .github/workflows/release.yml
- .zuul/playbooks/containerd-build/run.yaml
- Vagrantfile
- contrib/Dockerfile.test
go1.15.8 (released 2021/02/04) includes fixes to the compiler, linker, runtime,
the go command, and the net/http package. See the Go 1.15.8 milestone on the
issue tracker for details.
https://github.com/golang/go/issues?q=milestone%3AGo1.15.8+label%3ACherryPickApproved
full diff: https://github.com/golang/go/compare/go1.15.7...go1.15.8
> Update to go 1.15.8

- .github/workflows/ci.yml
- .github/workflows/nightly.yml
- .github/workflows/release.yml
- .travis.yml
- .zuul/playbooks/containerd-build/run.yaml
- Vagrantfile
- contrib/Dockerfile.test
go1.15.8 (released 2021/02/04) includes fixes to the compiler, linker, runtime,
the go command, and the net/http package. See the Go 1.15.8 milestone on the
issue tracker for details.
https://github.com/golang/go/issues?q=milestone%3AGo1.15.8+label%3ACherryPickApproved
The 1.4 branch was still on Go 1.15.5, so this patch also includes previous
patch updates;
full diff: https://github.com/golang/go/compare/go1.15.5...go1.15.8
back ports the equivalent of;
- https://github.com/containerd/containerd/pull/4934
- https://github.com/containerd/containerd/pull/4959
- https://github.com/containerd/containerd/pull/5004
> [release/1.4] Update to go 1.15.8

- .github/workflows/ci.yml
- .github/workflows/nightly.yml
- .github/workflows/release.yml
https://github.com/actions/setup-go/tree/v2.1.3#v2
The V2 offers:
- Adds GOBIN to the PATH
- Proxy Support
- stable input
- Bug Fixes (including issues around version matching and semver)
> GHA: use setup-go@v2

- .github/workflows/ci.yml
- pkg/cri/server/container_create_linux.go
- pkg/cri/server/sandbox_run_linux.go
The first commit updates golangci-lint. The second commit fixes lint issues.
> Upgrade golangci-lint from v1.29.0 to v1.36.0

- pkg/cri/annotations/annotations.go
- pkg/cri/server/container_create.go
- pkg/cri/server/container_create_linux.go
- pkg/cri/server/container_create_linux_test.go
- pkg/cri/server/container_create_other.go
- pkg/cri/server/container_create_test.go
- pkg/cri/server/container_create_windows.go
- pkg/cri/server/container_create_windows_test.go
For some tools having the actual image name in the annotations is helpful for
debugging and auditing the workload.
> [cri] add image-name annotation

- .mailmap
- releases/v1.5.0-beta.toml
- version/version.go
See https://gist.github.com/dmcgowan/dc3cacd6f1c6fbb5ae69d7d0e392cc35
A couple more dependency issues we may need to solve in the release tool
`github.com/Microsoft/hcsshim/test d3e5debf77da new`
and
```
DEBU[0019] git ls-remote git://github.com/kubernetes/klog/v2 v2.2.0 v2.2.0^{}  cache=miss
DEBU[0019] not using sha                                 error="exit status 128: fatal: remote error: \n  kubernetes/klog/v2 is not a valid repository name\n  Visit https://support.github.com/ for help\n" key="git ls-remote git://github.com/kubernetes/klog/v2 v2.2.0 v2.2.0^{}"
```
> Prepare release notes for 1.5.0-beta.1

- pkg/cri/annotations/annotations.go
- pkg/cri/server/sandbox_run.go
This additional information is helpful for CNI plugins when creating the network stack for a container.  The plugin still has to have this capability added in its config to take advantage of this information.
ref: https://github.com/containernetworking/cni/blob/master/CONVENTIONS.md#dynamic-plugin-specific-fields-capabilities--runtime-configuration
> [cri] add pod annotations to CNI call

- docs/cri/config.md
- pkg/cri/config/config.go
- pkg/cri/server/sandbox_run.go
- pkg/netns/netns_linux.go
- pkg/netns/netns_other.go
- pkg/netns/netns_windows.go
The directory where cri puts the netns references is currently hardcoded. This moves it into StateDir which can be configured.
Having this configurable is useful for systems with read-only root filesystems where one needs tight controls over where software
is able to write to.
> Allow moving netns directory into StateDir 

- cmd/containerd/command/main.go
Previously we simply ignored any not found error when loading the
containerd config. This created unintuitive behavior:
- If the user specified a path that didn't exist via --config, we would
silently ignore the error.
- If a config specified an import that didn't exist, we would silently
ignore the error.
In either of these cases, it appears we would end up using a potentially
corrupted config, as it would contain any files that were merged into it
before the not found error was hit.
However, we can't just remove the check for !os.IsNotExist(err),
as we shouldn't throw an error when --config is not passed, but the
default config doesn't exist.
This change updates the logic to only attempt to load the config if
we know it exists, or the user passed --config.
Signed-off-by: Kevin Parsons …
> Improve error detection when loading config

- snapshots/windows/windows.go
* Currently we rely on making the UVMs sandbox.vhdx in the shim instead of this being made by the snapshotter. This change adds a label that affects whether to create the UVMs scratch layer in the snapshotter itself.
* Adds container and UVM scratch size customization. Before adding the computestorage calls (vendored in with https://github.com/containerd/containerd/pull/4859) there was no way to make a containers or UVMs scratch size less than the default (20 for containers and 10 for the UVM).
> Scratch size customization and UVM scratch creation for WCOW snapshotter

- integration/runtime_handler_test.go
Resolving issue #5032:
- An empty `--runtime-handler` flag results in testing against the default runtime so modified and removed logging to clarify.
- Added a TODO for future work on potentially adding test(s) for multiple runtimes at the same time.
> Fix TestRuntimeHandler logging

- pkg/cri/server/container_create.go
> Fix empty error warpping

- pkg/cri/server/container_create_linux.go
Fix #5023 
When call CreateContainer for multiple pods **with the same image config but different envs in container spec** at nearly the same time,  they get image config from imagestore but the **Envs slice in the image config is pointing to the same object**.  The Envs is [json.Unmarshal](https://github.com/containerd/containerd/blob/master/pkg/cri/store/image/image.go#L143) from the content db, so the cap and len of the Envs slice maybe not equal. 
So the operation for [appending container env into the image env](https://github.com/containerd/containerd/blob/master/pkg/cri/server/container_create_linux.go#L164) may cause the first few envs of the first container is overlapped by the second container (maybe from another pods) with some probability if the two container has the same image …
> cri: append envs from image config to empty slice to avoid env lost 

- pkg/cri/server/container_create_windows.go
Signed-off-by: Justin Terry (SF) <juterry@microsoft.com>
> cri: append envs from image config to empty slice to avoid env lost

- .github/workflows/ci.yml
We have enough failures these days; getting timed out when tests are
almost done is the last thing we need :)
On avg. the Linux integration tests are taking 15-17 min, but sometimes
they end up at 20 or a bit over and get canceled. I've seen rare cases
where the Vagrant setup+build+test runs gets very close to 40 min as
well.
> Tune test timeouts for GH Actions

- oci/spec_opts_linux.go
- oci/spec_opts_unix.go
The file mode of the device in the OCI runtime specification does not contain file type bits
`unix.Stat_t.Mode` contains the file type and mode，details are in "The file type and mode" section of [inode](https://man7.org/linux/man-pages/man7/inode.7.html)
This issue causes some `config.json` to fail [the runtime spec schema validation](https://github.com/opencontainers/runtime-spec/tree/master/schema#utility)
For example, the `config.json` for the kube-proxy container
```json
devices:
[
{
"path":"/dev/sda",
"type":"b",
"major":8,
"minor":0,
"fileMode":25008,
"uid":0,
"gid":6
},
{
"path":"/dev/null",
"type":"c",
"major":1,
"minor":3,
"fileMode":8630,
"uid":0,
"gid":0
},
{
"path":"/dev/tty0",
"type":"c",
"major":4,
"minor":0,
"fileMode":8592,
"uid":0,
"gid":5
},
...
]
```
Discussions about …
> oci: fix the file mode of the device

- .github/workflows/ci.yml
The CI host was probably updated recently and the permission bits of the directory was changed.
Fix #5077
> CI: fix "ls: cannot access '/etc/cni/net.d': Permission denied"

- runtime/restart/monitor/monitor.go
The only shared variable `m.client` is thread-safe, so we can safely parallelize the loops.
> restart: parallelize reconcile()

- restart_monitor_linux_test.go
Add a test for the `restart` service (`runtime/restart/monitor`).
Surprised to notice we didn't have  😄
> restart: add an integration test

- pkg/cri/server/container_create_linux.go
- pkg/cri/server/container_create_linux_test.go
Fixes #5029.
Signed-off-by: Yohei Ueda <yohei@jp.ibm.com>
> cri: set default masked/readonly paths to empty paths

- docs/PLUGINS.md
- docs/ops.md
Found a broken link replaced it with the relative path to it. 
Also, suggest some wording changes.
> Fixed wording in docs, and broken link

- runtime/restart/monitor/monitor.go
Previously, containers were not started until the daemon completes the first sleep.
Before:
```console
$ go test -v -exec sudo -test.kill-daemon -run TestRunRestart
test target: "nerdctl"
=== RUN   TestRunRestart
run_restart_test.go:44: NOTE: this test may take a while
run_restart_test.go:71: killing "containerd.service"
run_restart_test.go:72: checking activity of "containerd.service"
run_restart_test.go:72: (retry=0) activating
run_restart_test.go:72: (retry=1) activating
run_restart_test.go:72: (retry=2) active
run_restart_test.go:72: daemon "containerd.service" is now running
run_restart_test.go:79: (retry 0) ps -a: "CONTAINER ID    IMAGE                                      COMMAND                   CREATED          STATUS     PORTS                     NAMES\n46ba66a9a3a5 …
```
> restart: skip Sleep() for the first iteration of the reconcilation

- .mailmap
- releases/v1.5.0-beta.toml
- version/version.go
Updates release notes, version, and mailmap for 1.5.0-beta.2
> Prepare 1.5.0-beta.2 release

- oci/spec_opts.go
> oci: fix superfluous slice operations

- contrib/linuxkit/README.md
Although [linuxkit/kubernetes](https://github.com/linuxkit/kubernetes) has not been updated for a long time
> update linuxkit readme

- runtime/v2/shim/util.go
The current code simply ignores the full binary path when starting the
shimv2 process, and instead fallbacks to a binary in the path, and this
is problematic (and confusing) for those using CRI-O, which has this
bits vendored.
The reason it's problematic with CRI-O is because the user can simply
set the full binary path and, instead of having that executed, CRI-O
will simply fail to create the container unless that binary is part of
the path, which may not be case in a few different scenarios (testing
being the most common one).
Fixes: #5006
Signed-off-by: Fabiano Fidêncio <fidencio@redhat.com>
> v2, util: Take the full binary path when starting the shimv2 process

- script/setup/install-cni
- script/setup/install-cni-windows
- script/setup/install-critools
- script/setup/install-runc
relates to https://github.com/containerd/containerd/pull/5005
`go get -d` uses go modules by default in Go 1.16 and up, which results
in modules being fetched for the "latest" module version, after which we
tried to "git checkout" to `<VERSION>`.
For runc, this means that (possibly incorrectly), `go get` will download
runc `v0.1.1` (most recent non-"pre-release", which caused failures (e.g
the old `Sirupsen/logrus` being downloaded).
In addition, some of the dependencies we're installing use vendoring, and
thus would not require the modules to be downloaded (and vendored files
will be ignored when using `go get` with modules).
This patch switches several uses `go get -d` to use a regular
git clone, after which the desired version is checked out,
and the binaries are built.
> script/setup: use git clone instead of go get -d

- cmd/ctr/commands/images/images.go
- cmd/ctr/commands/images/pull.go
- cmd/ctr/commands/images/push.go
Enables a Go embedded feature for tracing certain aspects of HTTP connections; useful for debug of connectivity, DNS, etc. issues with registry interactions.
Example output:
```
DEBU[0000] fetching                                      image="docker.io/library/alpine:latest"
DEBU[0000] resolving                                     host=registry-1.docker.io
DEBU[0000] do request                                    host=registry-1.docker.io request.header.accept="application/vnd.docker.distribution.manifest.v2+json, ap
plication/vnd.docker.distribution.manifest.list.v2+json, application/vnd.oci.image.manifest.v1+json, application/vnd.oci.image.index.v1+json, */*" request.header.
user-agent=containerd/v1.5.0-beta.1-9-g87c9aeb6c.m request.method=HEAD …
```
> Enable Go HTTP tracing of registry interactions

- snapshots/devmapper/snapshotter_test.go
Close https://github.com/containerd/containerd/issues/4965
> Remove flaky devmapper check

- .github/ISSUE_TEMPLATE/bug_report.md
Since both cri-containerd and runC runtime are widely used, the relevent
information should include runC and CRI configuration when file bug.
> .github: update bug_report.md with hint and tip

- pkg/cri/server/container_status.go
- pkg/cri/server/container_status_test.go
fix crictl: https://github.com/kubernetes-sigs/cri-tools/pull/724
fix dockershim: https://github.com/kubernetes/kubernetes/pull/99585
In some container states, the startedAt and finishedAt should not be specified
https://github.com/containerd/containerd/blob/134f7a737074727a6e87214323629b87ba658658/vendor/k8s.io/cri-api/pkg/apis/runtime/v1alpha2/api.pb.go#L4211-L4223
> cri: fix container status

- RELEASES.md
Mark 1.3 as end of life as of the 1.3.10 release on March 4th.
Update 1.4 to latest release.
> Update RELEASES.md to reflect latest releases

- contrib/apparmor/apparmor.go
- contrib/apparmor/apparmor_test.go
This function will be used by [nerdctl](https://github.com/AkihiroSuda/nerdctl) for printing the default AppArmor profile: `nerdctl system inspect apparmor-profile`
```console
$ go test -v -run TestDumpDefaultProfile
=== RUN   TestDumpDefaultProfile
apparmor_test.go:117: Generated profile "test-dump-default-profile"
apparmor_test.go:118: 
#include <tunables/global>
profile test-dump-default-profile flags=(attach_disconnected,mediate_deleted) {
#include <abstractions/base>
network,
capability,
file,
umount,
deny @{PROC}/* w,   # deny write for all files directly in /proc (not in a subdir)
deny @{PROC}/{[^1-9],[^1-9][^0-9],[^1-9s][^0-9y][^0-9s],[^1-9][^0-9][^0-9][^0-9]*}/** w,
deny @{PROC}/sys/[^k]** w,  # deny /proc/sys except /proc/sys/k* (effectively /proc/sys/kernel)
deny …
```
> apparmor: add DumpDefaultProfile

- releases/v1.4.4.toml
This was pointing to the wrong advisory. The link has already been fixed in the release notes on GitHub; this updates the toml file to match.
> [release/1.4] Fix advisory link in release notes for containerd 1.4.4

- snapshots/devmapper/pool_device.go
When an error is returned here, unlike the other error returns in the function, nothing is done to mark the added device as faulty or remove it.
I have observed this causing future snapshot creations to continue to attempt to use the same ID (from the sequence) to create new devices and get blocked because the device already exists because it was not rolled back here.
Hopefully fixes #5110
> mark device faulty after parent fails to suspend

- content/content.go
- content/local/readerat.go
- content/local/store.go
Add `OpenReader`func  to create `ReaderAt` interface from a file system path to simplify local store hacking.
This doesn't change any logic, just makes existing code more reusable.
> Add OpenReader to local store

- contrib/apparmor/template.go
- contrib/apparmor/template_test.go
On newer kernels and systems, AppArmor will block sending signals in
many scenarios by default resulting in strange behaviours (container
programs cannot signal each other, or host processes like containerd
cannot signal containers). [This issue was fixed in Docker in 2018][1] but
this code was copied before then and thus the patches weren't carried.
It also contains [a new fix for a more esoteric case][2].
Ideally this code should live in a project like "containerd/apparmor" so
that Docker, libpod, and containerd can share it, but that's probably
something to do separately.
In addition, the copyright header is updated to reference that the code
is copied from Docker (and thus was not written entirely by the
containerd authors).
[1]: https://github.com/docker/docker/pull/37831
[2]: …
> apparmor: handle signal mediation

- runtime/v2/shim/util.go
Previously a typo was introduced that caused the wrong error to be
checked against when calling exec.LookPath. This had the effect that
containerd would never locate the shim binary if it was in the same
directory as containerd's binary, but not in PATH.
> Fix error checking when resolving shim binary path

- snapshots/overlay/check.go
- snapshots/overlay/overlay.go
- snapshots/overlay/overlay_test.go
The "userxattr" option is needed for mounting overlayfs inside a user namespace with kernel >= 5.11.
The "userxattr" option is NOT needed for the initial user namespace (aka "the host").
Also, Ubuntu (since circa 2015) and Debian (since 10) with kernel < 5.11 can mount the overlayfs in a user namespace without the "userxattr" option.
The corresponding kernel commit: torvalds/linux@2d2f2d7322ff43e0fe92bf8cccdc0b09449bf2e1
> **ovl: user xattr**
>
> Optionally allow using "user.overlay." namespace instead of "trusted.overlay."
> ...
> Disable redirect_dir and metacopy options, because these would allow privilege escalation through direct manipulation of the
> "user.overlay.redirect" or "user.overlay.metacopy" xattrs.
Fix issue #5060
> overlay: support "userxattr" option (kernel 5.11)

- cmd/ctr/commands/images/pull.go
This provides additional insight into how much time is being spent in
unpacking and is helpful in performance comparison for just this stage
without resorting to running under time command in linux for example.
> Print elapsed time for image unpack

- go.mod
- go.sum
- vendor/github.com/moby/sys/mountinfo/mountinfo.go
- vendor/github.com/moby/sys/mountinfo/mountinfo_filters.go
- vendor/github.com/moby/sys/mountinfo/mountinfo_linux.go
- vendor/modules.txt
full diff: https://github.com/moby/sys/compare/mountinfo/v0.4.0...mountinfo/v0.4.1
Fixes and improvements:
- Fix PrefixFilter() being too greedy
- TestMountedBy*: add missing pre-checks
- Documentation improvements
> go.mod: github.com/moby/sys/mountinfo v0.4.1

- .github/workflows/ci.yml
Without a name the logs use a carriage return followed by the long
comment ("# Retry if it fails"...) as the name of the job step which is messy when working with the
actions API/logs.
> CI: Add a name for the vagrant up step

- .github/workflows/ci.yml
- .github/workflows/nightly.yml
- .github/workflows/release.yml
- .zuul/playbooks/containerd-build/run.yaml
- Vagrantfile
- contrib/Dockerfile.test
- go.mod
> Update to Go 1.16.1

- .zuul.yaml
Just use the same default merge mode as github, don't use the conservative thing zuul defaults to. More info at:
https://zuul-ci.org/docs/zuul/reference/project_def.html
```
project.merge-mode
Default: merge-resolve
merge
Uses the default git merge strategy (recursive). This maps to the merge mode merge in Github.
merge-resolve
Uses the resolve git merge strategy. This is a very conservative merge strategy which most closely matches the behavior of Gerrit. This maps to the merge mode merge in Github.
```
> Switch from merge-resolve(default) to merge mode for containerd-build-arm64

- script/setup/install-runc
fixes the issue reported by @tghartland in https://github.com/containerd/containerd/pull/5036#discussion_r593332821
Both runc and containerd use BUILDTAGS to customize go build-tags.
When building containerd with custom build-tags, runc inherited
those, causing the default to be overwritten, e.g.;
make BUILDTAGS=no_btrfs cri-cni-release
(in script/setup/install-runc)
HEAD is now at 12644e61 VERSION: release 1.0.0~rc93
make[1]: Entering directory '/tmp/tmp.ZJzc2KtI0A/runc'
go build -trimpath "-mod=vendor" "-buildmode=pie"  -tags "no_btrfs" -ldflags "-X main.gitCommit="12644e614e25b05da6fd08a38ffa0cfe1903fdec" -X main.version=1.0.0-rc93 " -o runc .
^^^^^^^^^^^^^^^^
This patch brings back the BUILDTAGS make-var in the runc-install
script, which fixates the buildtags to our defaults.
> Prevent runc inheriting BUILDTAGS from containerd

- cmd/ctr/commands/commands.go
E.g. is used before an item or list of items that serve as examples for the previous statement.
I.e. is used to restate something said previously in order to clarify its meaning.
e.g. should be used here.
> cmd/ctr: use e.g. in the command usage

- rootfs/init.go
If the `snapshotter.Commit` return an error, then the `snapshotter.Remove` should also be called.
https://github.com/containerd/containerd/blob/6b410ba41ff28471134ca508665f89a10610eb7f/rootfs/init.go#L112-L117
https://github.com/containerd/containerd/blob/e231b955dd9a0fa88f7928f5c69b09e8ed95e4dd/rootfs/init.go#L88-L96
@dmcgowan @dnephin PTAL. Thanks
> rootfs: fix the error handling of the snapshotter.Commit

- remotes/docker/config/hosts.go
- remotes/docker/config/hosts_test.go
The certs dir parsing was skipping over files instead of reading them,
as such the certs would never load.
It was also stating the file name rather than the full path for cert
pairs.
---
This takes the first commit from #4978 so that it can be merged separate from that PR.
> Fix docker style cert loading.

- docs/cri/config.md
- pkg/cri/config/config.go
- pkg/cri/config/config_test.go
- pkg/cri/server/image_pull.go
- remotes/docker/config/hosts.go
- remotes/docker/config/hosts_test.go
Exposes the hosts dir config to CRI.
This will be used instead of the cri registry config in the main config toml.
Also fixes some bugs with the docker style cert file handling.
Closes #3071
Closes #4904
> Add support for using a host registry dir in cri

- archive/tar_linux_test.go
- snapshots/overlay/overlay.go
- snapshots/overlay/overlay_test.go
- snapshots/overlay/overlayutils/check.go
- snapshots/overlay/overlayutils/check_test.go
This allows using the utilities without importing the whole snapshotter.
relates to the discussion on https://github.com/moby/moby/pull/42068#discussion_r591498492. This potentially allows moby to use this package, instead of maintaining the moby `overlayutils` package
> move overlay-checks to an overlayutils package

- cmd/ctr/commands/plugins/plugins.go
```
[root@daocloud ~]# ctr plugin ls
TYPE                            ID                       PLATFORMS      STATUS
io.containerd.content.v1        content                  -              ok
io.containerd.snapshotter.v1    aufs                     linux/amd64    error
io.containerd.snapshotter.v1    devmapper                linux/amd64    error
io.containerd.snapshotter.v1    native                   linux/amd64    ok
io.containerd.snapshotter.v1    overlayfs                linux/amd64    ok
io.containerd.snapshotter.v1    zfs                      linux/amd64    error
```
```
Type:          io.containerd.snapshotter.v1
ID:            zfs
Platforms:     linux/amd64
Exports:
root      /var/lib/containerd/io.containerd.snapshotter.v1.zfs
Error:
Code:        Unknown
Message:     path …
```
> ctr plugin ls: plugin status should be skip, not error

- runtime/v2/runc/container.go
**The cleanup operation does not take effect in many cases**
e.g.
https://github.com/containerd/containerd/blob/2755ead927bbdc5b042990964332d78a0fdaddf4/runtime/v2/runc/container.go#L112-L116
https://github.com/containerd/containerd/blob/2755ead927bbdc5b042990964332d78a0fdaddf4/runtime/v2/runc/container.go#L130-L132
https://github.com/containerd/containerd/blob/2755ead927bbdc5b042990964332d78a0fdaddf4/runtime/v2/runc/container.go#L143-L152
> runtime/v2/runc: fix the defer cleanup of the NewContainer

- remotes/docker/registry.go
- remotes/docker/registry_test.go
- changed the `MatchLocalhost` function in remotes/docker/registry.go
- Added additional tests for modified code in remotes/docker/registry_test.go
Fixes: #5129
Signed-off-by: Madhav Jivrajani <madhav.jiv@gmail.com>
> Use net.IP.IsLoopback() to match loopback addresses

- cmd/ctr/commands/commands.go
- cmd/ctr/commands/run/run_unix.go
- oci/spec_opts.go
- oci/spec_opts_linux.go
- oci/spec_opts_linux_test.go
- oci/spec_opts_unix.go
- oci/spec_opts_windows.go
- pkg/cri/opts/spec_linux.go
This enables cases where devices exist in a subdirectory of /dev,
particularly where those device names are not portable across machines,
which makes it problematic to specify from a runtime such as cri.
Added this to `ctr` as well so I could test that the code at least
works.
Closes #4846
> Support adding devices by dir

- runtime/v2/binary.go
- runtime/v2/shim.go
After #4906, containerd opens fifo in read/write mode in linux platform
The original comment doesn't correct and is removed by #5174.
```
// original comment
// When using a multi-container shim, the fifo of the 2nd to Nth
// container will not be opened when the ctx is done. This will
// cause an ErrReadClosed that can be ignored.
```
However, we should add comment for checkCopyShimLogError to mention why
we call checkCopyShimLogError. The checkCopyShimLogError, it is to prevent
the flood of expected error messages after task die and the expected
errors depend on platform.
> runtime/v2: add comment for checkCopyShimLogError

- cmd/containerd-stress/main.go
This fixes following warning message by changing the default runtime
to io.containerd.runc.v2 and does not require user to set the runtime
from command line anymore.
"WARN[2021-03-17T21:11:01.441207858Z] runtime v1 is deprecated since
containerd v1.4, consider using runtime v2"
> change default runtime for containerd-stress app

- contrib/ansible/cri-containerd.yaml
- docs/PLUGINS.md
- docs/cri/config.md
- docs/cri/crictl.md
- integration/client/client_test.go
- integration/client/image_test.go
- integration/client/lease_test.go
- integration/main_test.go
- pkg/cri/config/config_unix.go
- pkg/cri/config/config_windows.go
After https://github.com/kubernetes/k8s.io/pull/1793 is promoted, update pause image in containerd
> upgrade pause image to 3.5 for non-root

- .github/workflows/ci.yml
To investigate issues like #4969, it would be helpful to understand
the status of the VM at the end.
> ci: log the status of GitHub Actions' VM at the end

- content/proxy/content_writer.go
Committing writer does not close the grpc stream, causing resource leak and making it not possible to close the client side cleanly.
@AkihiroSuda 
buildkit issue moby/buildkit#2025
> contentproxy: ensure grpc stream is closed on commit

- .github/workflows/ci.yml
- integration/client/client_test.go
- integration/client/container_checkpoint_test.go
- pkg/process/init.go
- runtime/v2/runc/container.go
While the issue hasn't been fixed in the kernel yet, we can workaround
the issue by not using overlayfs snapshotter.
Fixes #3930.
> Re-enable CRIU tests by not using overlayfs snapshotter

- snapshots/devmapper/snapshotter.go
- snapshots/devmapper/snapshotter_test.go
Before the change, the error on the caller-side (e.g. ctr) was
something like
> unpack: failed to prepare extraction snapshot "...": exit status 5:
> unknown
which was too cryptic.
> Specifically mention "mkfs.ext4" on the error from the command

- integration/client/client_unix_test.go
- integration/client/container_linux_test.go
Builds on changes from #5189 to default to a non rate-limited `testImage` used across many of the client tests since we are still having a lot of rate-limiting on the macos nodes running the SELinux/Cgroupsv2 tests.
> Switch test image to a non rate-limited manifest list

- Makefile
on macos , make binaries not compile contained
> standard makefile,fix not work no  macos

- integration/client/container_linux_test.go
Due to the lack of an existing /proc dir in the rootfs of the busybox image, there
seems to be a race between the `mkdir` prior to the mount of /proc and whether
the root dir is already readonly? May need investigation, but for now use an image
that has a /proc dir existing.
Follow-on to comments in #5216 // cc @crosbymichael 
> Use specific image for user namespaces tests

- .github/workflows/nightly.yml
> night ci: add packages for ubuntu 20.04

- go.mod
- go.sum
- vendor/github.com/containerd/zfs/plugin/plugin.go
- vendor/github.com/containerd/zfs/zfs.go
- vendor/modules.txt
Contains "Implements zfs usage by returning the USED field from the zfs snapshot"
(https://github.com/containerd/zfs/pull/38)
> go.mod: github.com/containerd/zfs v0.0.0-20210322090317-0e92c2247fb7 (for snapshot usage)

- archive/tar_unix.go
- diff/apply/apply_linux.go
- pkg/cri/server/service_linux.go
- pkg/userns/userns_linux.go
- pkg/userns/userns_unsupported.go
- runtime/v2/runc/v2/service.go
- snapshots/overlay/overlayutils/check.go
- sys/oom_unix.go
- sys/userns_deprecated.go
Trying to prevent the `sys` package to become too much of a kitchen-sink 😅 
This allows using the utility without bringing whole of "sys" with it.
> Move RunningInUserNS() to its own package

- log/logtest/context.go
issue: https://github.com/containerd/containerd/issues/5093
It may be inconvenient to have no caller information in the test log when a problem occurs.
output:
```
=== RUN   TestLogTest
log_hook.go:40: time="2021-02-27T02:19:31.384471000+08:00" level=info msg="test message" func=logtest.TestLogTest file="/Users/icebergu/workspace/containerd/log/logtest/context_test.go:12"
--- PASS: TestLogTest (0.00s)
PASS
ok      github.com/containerd/containerd/log/logtest    0.008s
```
> add caller info to the testHook

- sys/oom_linux.go
- sys/oom_linux_test.go
- sys/oom_unsupported.go
OOM procfs is linux specific, so should not be running on mac os, freebsd, etc.
> Fix oom tests on non Linux

- .github/workflows/ci.yml
The integration test times have slightly increased and are often
hitting the 25 minutes timeout. This increases to give more room
but still keeps it low enough to catch regressions in tests
causing longer than expected execution.
> Increase timeout for linux integration tests

- pkg/cri/store/image/image.go
- pkg/cri/store/image/image_test.go
- pkg/cri/store/image/sort.go
- pkg/cri/store/image/sort_test.go
Currently image references end up being stored in a
random order due to the way maps are iterated through
in Go. This leads to inconsistent identifiers being
resolved when a single reference is needed to identify
an image and the ordering of the references is used for
the selection.
Sort references in a consistent and ranked manner,
from higher information formats to lower.
Note: A `name + tag` reference is considered higher
information than a `name + digest` reference since a
registry may be used to resolve the digest from a
`name + tag` reference.
Original Issue:
References is created using https://github.com/containerd/containerd/blob/master/pkg/cri/util/strings.go#L46 which does not guarantee any order
The [first item of this array then gets used to set the image …
> Fix reference ordering in CRI image store

- cmd/ctr/commands/commands.go
- cmd/ctr/commands/content/fetch.go
- cmd/ctr/commands/images/images.go
- cmd/ctr/commands/images/pull.go
- cmd/ctr/commands/images/push.go
- cmd/ctr/commands/resolver.go
- remotes/docker/config/hosts.go
This PR adds:
- `http-dump` flag can dump HTTP request/responses when interacting with container registry.
- `http-trace` is https://github.com/containerd/containerd/pull/5040 follow up
> Support HTTP debug in ctr

- cmd/containerd/command/config.go
- cmd/containerd/command/config_linux.go
- cmd/containerd/command/config_unsupported.go
- cmd/containerd/command/config_windows.go
- cmd/containerd/command/main.go
- cmd/containerd/command/main_unix.go
- cmd/containerd/command/main_windows.go
- defaults/defaults_unix.go
- defaults/defaults_windows.go
- docs/cri/decryption.md
- images/mediatypes.go
- pkg/cri/config/config_unix.go
- pkg/cri/config/config_windows.go
Enable the following config by default:
```toml
version = 2
[plugins."io.containerd.grpc.v1.cri".image_decryption]
key_model = "node"
[stream_processors]
[stream_processors."io.containerd.ocicrypt.decoder.v1.tar.gzip"]
accepts = ["application/vnd.oci.image.layer.v1.tar+gzip+encrypted"]
returns = "application/vnd.oci.image.layer.v1.tar+gzip"
path = "ctd-decoder"
args = ["--decryption-keys-path", "/etc/containerd/ocicrypt/keys"]
env = ["OCICRYPT_KEYPROVIDER_CONFIG=/etc/containerd/ocicrypt/ocicrypt_keyprovider.conf"]
[stream_processors."io.containerd.ocicrypt.decoder.v1.tar"]
accepts = ["application/vnd.oci.image.layer.v1.tar+encrypted"]
returns = "application/vnd.oci.image.layer.v1.tar"
path = "ctd-decoder"
args = ["--decryption-keys-path", "/etc/containerd/ocicrypt/keys"]
env = …
```
> add imgcrypt stream processors to the default config

- client.go
- client_opts.go
- cmd/ctr/commands/content/fetch.go
- cmd/ctr/commands/images/pull.go
- cmd/ctr/commands/images/push.go
- remotes/handlers.go
Also add flags for push/pull subcommand to limit max concurrent
uploads/downloads.
> remotes/ctr: allow to limit max concurrent uploads like downloads

- integration/remote/util/util_unix.go
- integration/util/util_unix.go
relates to https://github.com/microsoft/hcsshim/pull/984
Having this log should not be critical, and removing it allows
using this package without pulling in the explicit dependency
on k8s.io/klog.
> integration/util: remove dependency on k8s.io/klog/v2

- .github/workflows/ci.yml
- go.mod
- go.sum
- vendor/github.com/Microsoft/go-winio/pkg/etw/newprovider.go
- vendor/github.com/Microsoft/go-winio/pkg/etw/newprovider_unsupported.go
- vendor/github.com/Microsoft/go-winio/pkg/etw/provider.go
- vendor/github.com/containerd/zfs/zfs.go
- vendor/modules.txt
This makes sure we can compile on all the platforms and prevent things
like integer overflows.
> Add CI job to cross compile all the things

- Vagrantfile
When integration tests are run under nested VM (for SELinux, Cgroupsv2
testing) they are regularly starting to push past 10 minutes, causing
`go test` to fatally kill the test run (default timeout is 10m).
(Recent example in #5266)
> Extend default timeout for nested VM integration run

- .github/workflows/ci.yml
- archive/tar_test.go
- pkg/cri/server/container_create_test.go
- pkg/cri/server/sandbox_run_test.go
Though we don't officially support Macs, we should at least run unit tests
to make sure things are not broken on this platform.
> Run unit tests on CI for MacOS

- integration/client/container_checkpoint_test.go
- task.go
task.Checkpoint should check status of container before handle
checkpoint. If the container has been paused, task.Checkpoint should
handle checkpoint and leave it paused.
Signed-off-by: Baijia <baijia.wr@antfin.com>
> task: allow checkpoint on pause state

- snapshots/devmapper/dmsetup/dmsetup.go
Instead of calling blockdev(1), this change uses os.File#Seek which
would be more effecient.
https://github.com/firecracker-microvm/firecracker/pull/1371
> Use os.File#Seek() to get the size of a block device

- remotes/handlers.go
This allows a pusher to be used for more than one tag without creating a
new resolver/pusher. The current implementation checks the ref key
tracker status based on type and hash and will skip the push even if the
repository reference is unique.
**Note:** refkeys are visually used in `ctr images pull` for status, which will be impacted by this change, but many images do not use the OCI annotations at this point, so impact seems minimal; for example with this patch, you can see the official alpine image has no `ref.name` annotation so the output is unchanged:
```
$ sudo bin/ctr images pull
ctr: please provide an image reference to pull
docker.io/library/alpine:latest:                                                  resolved …
```
> Add OCI ref.name to unique key in remotes handler

- .github/workflows/ci.yml
cri-tools is hardcoded to use images which are broken within their registry. Disable the tests to unblock CI until fixed.
See https://github.com/kubernetes-sigs/cri-tools/pull/733
> Temporarily disable cri-tools critest

- remotes/docker/pusher.go
- remotes/docker/status.go
The `(dockerPusher).Push` method uses a `StatusTracker` to check if an
upload already happened, before repeating the upload. However, there is
no provision for failure handling. If a PUT request returns an error,
the `StatusTracker` will still see the upload as if it happened
successfully. Add a status boolean so that only successful uploads
short-circuit `Push`.
Signed-off-by: Aaron Lehmann <alehmann@netflix.com>
> remotes/docker: Only return "already exists" on push when the upload was sucessful

- oci/spec_opts.go
- oci/spec_opts_linux.go
- oci/spec_opts_test.go
- pkg/cri/opts/spec_linux.go
- pkg/cri/server/container_create_linux.go
- pkg/cri/server/sandbox_run_linux.go
Move `pkg/cri/opts.WithoutRunMount` function to `oci.WithoutRunMount` so that it can be used without dependency on CRI.
Also add `oci.WithoutMounts(dests ...string)` for generality.
--- 
Will be used by nerdctl: https://github.com/containerd/nerdctl/pull/158
> pkg/cri/opts.WithoutRunMount -> oci.WithoutRunMount

- docs/cri/config.md
- docs/cri/registry.md
- pkg/cri/config/config_unix.go
- pkg/cri/config/config_windows.go
Some clean up of the docs around registry config.
A fix to remove old style mirrors config from the default config. Without the fix init will report 
`WARN[2021-04-07T09:21:29.773381274-05:00] failed to load plugin io.containerd.grpc.v1.cri  error="invalid plugin config: `mirrors` cannot be set when `config_path` is provided"`
> remove mirrors from default; document the deprecation of registry.configs and registry.mirrors

- pkg/cri/config/config.go
- pkg/cri/server/helpers.go
Trying to fix the issue in which runtime options does not get printed in `crictl info`.  
<strike>Added separate field for runtime options in status response. </strike>
Update the type of `Options *toml.Tree` to `Options *toml.Tree map[string]interface{}`. This is correctly marshalling the options in CRI status response. 
Ref Issue: https://github.com/kubernetes-sigs/cri-tools/issues/728
> Change the type of CRI runtime option 

- go.mod
- go.sum
- integration/client/go.sum
- vendor/github.com/klauspost/compress/fse/compress.go
- vendor/github.com/klauspost/compress/fse/decompress.go
- vendor/github.com/klauspost/compress/huff0/README.md
- vendor/github.com/klauspost/compress/huff0/compress.go
- vendor/github.com/klauspost/compress/snappy/snappy.go
- vendor/github.com/klauspost/compress/zstd/README.md
- vendor/github.com/klauspost/compress/zstd/blockdec.go
- vendor/github.com/klauspost/compress/zstd/blockenc.go
- vendor/github.com/klauspost/compress/zstd/decodeheader.go
- vendor/github.com/klauspost/compress/zstd/decoder.go
- vendor/github.com/klauspost/compress/zstd/enc_base.go
- vendor/github.com/klauspost/compress/zstd/enc_best.go
- vendor/github.com/klauspost/compress/zstd/enc_better.go
- vendor/github.com/klauspost/compress/zstd/enc_dfast.go
- vendor/github.com/klauspost/compress/zstd/enc_fast.go
- vendor/github.com/klauspost/compress/zstd/encoder.go
- vendor/github.com/klauspost/compress/zstd/encoder_options.go
- vendor/github.com/klauspost/compress/zstd/fse_encoder.go
- vendor/github.com/klauspost/compress/zstd/seqdec.go
- vendor/github.com/klauspost/compress/zstd/snappy.go
- vendor/github.com/klauspost/compress/zstd/zstd.go
- vendor/modules.txt
full diff: https://github.com/klauspost/compress/compare/v1.11.3...v1.11.13
various performance improvements
> go.mod github.com/klauspost/compress v1.11.13

- pkg/cri/config/config_unix.go
When running the `containerd default config` command this pr adds output to show the available runc options:
```
[plugins."io.containerd.grpc.v1.cri".containerd.runtimes]
[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc]
base_runtime_spec = ""
container_annotations = []
pod_annotations = []
privileged_without_host_devices = false
runtime_engine = ""
runtime_root = ""
runtime_type = "io.containerd.runc.v2"
[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
BinaryName = ""
CriuImagePath = ""
CriuPath = ""
CriuWorkPath = ""
IoGid = 0
IoUid = 0
NoNewKeyring = false
NoPivotRoot = false
Root = ""
ShimCgroup = ""
SystemdCgroup = false
```
and here's the `containerd default dump` output with just `SystemdCgroup = false` set
``` …
```
> shows our runc.v2 default options

- pkg/cri/platforms/default_windows.go
- platforms/defaults_windows.go
- platforms/defaults_windows_test.go
This refactors the cri platform code to the base containerd platform code so it can be re-used across solutions.
fixes #5297 
Signed-off-by: James Sturtevant <jstur@microsoft.com>
> Support multi-arch images for Windows via ctr

- docs/cri/config.md
- pkg/cri/config/config.go
- pkg/cri/config/config_test.go
Must be reverted due to discovery of v1 configs using v1 default runtimes
Reverts containerd/containerd#5303
> Revert "remove two very old no longer used runtime options"

- archive/tar.go
- archive/tar_linux_test.go
- archive/tar_opts.go
- archive/tar_opts_windows.go
- archive/tar_windows.go
- diff/walking/differ.go
- diff/windows/windows.go
- integration/client/export_test.go
- integration/client/import_test.go
- vendor/github.com/Microsoft/hcsshim/pkg/ociwclayer/export.go
- vendor/github.com/Microsoft/hcsshim/pkg/ociwclayer/import.go
- vendor/modules.txt
This builds on #4395 to implement the `Compare` side of the differ and similarly to `Apply`, adds a redirect for WCOW to `archive.WriteDiff`.
With this change, (and a bunch of buildkit hacks), I can now export an image I built with buildkit to any of the types `oci`, `docker`, or `image`.
Fixes: #4394
> Implement windowsDiff.Compare to allow outputting OCI images

- go.mod
- go.sum
- vendor/github.com/containerd/console/README.md
- vendor/github.com/containerd/console/console_unix.go
- vendor/github.com/containerd/console/go.mod
- vendor/github.com/containerd/console/go.sum
- vendor/github.com/containerd/console/pty_freebsd_cgo.go
- vendor/github.com/containerd/console/pty_freebsd_nocgo.go
- vendor/github.com/containerd/console/pty_unix.go
- vendor/github.com/containerd/console/tc_freebsd_cgo.go
- vendor/github.com/containerd/console/tc_freebsd_nocgo.go
- vendor/modules.txt
Contains fix for s390x and support for FreeBSD
https://github.com/containerd/console/compare/v1.0.1...v1.0.2
> go.mod: github.com/containerd/console v1.0.2

- snapshots/devmapper/dmsetup/dmsetup.go
- snapshots/devmapper/snapshotter.go
if mkfs on device mapper thin pool fails, it will show pool status
as returned by dmsetup for enahnced error reporting.
> devmapper: log pool status when mkfs fails

- cmd/containerd-stress/density.go
- cmd/containerd-stress/exec_worker.go
- cmd/containerd-stress/main.go
- cmd/containerd-stress/worker.go
containerd-stress utility does not have an option to pass snapshotter. This adds a cli option to pass other snapshotter e.g. devmapper. This is useful for comparing two different snapshotters.
> Add snapshotter cli option to containerd-stress utility

- docs/cri/config.md
I find the link in docs/cri/config.md is outdate,so I fix it.
> fix the 404 link in docs/cri/config.md

- go.mod
- go.sum
- integration/client/go.sum
- vendor/github.com/containerd/imgcrypt/CHANGES
- vendor/modules.txt
relates to https://github.com/containerd/containerd/issues/5345
No code changes other than an updated changelog, and updating to
the tagged v1.1.1:
diff: https://github.com/containerd/imgcrypt/compare/0bed51b9522c...v1.1.1
> go.mod: github.com/containerd/imgcrypt v1.1.1

- go.mod
- go.sum
- integration/client/go.sum
- vendor/modules.txt
relates to https://github.com/containerd/containerd/issues/5345
no code changes as this is the same commit, but now tagged:
https://github.com/Microsoft/go-winio/compare/5516f17a5958...v0.4.17
> go.mod: github.com/Microsoft/go-winio v0.4.17

- cmd/containerd-shim/main_unix.go
Fix that the returned event publishing error may contain historical error messages and memory leaks
>  Fix return event publishing error 

- docs/rootless.md
Recommend "easy way" using `containerd-rootless-setuptool.sh`.
Also update outdated info.
> docs/rootless.md: recommend "easy way" over "hard way"

- remotes/docker/resolver.go
When debugging multiple host mirrors additional debug output is desired.
Example debug output:
```
INFO[2021-04-14T13:44:53.182712069-05:00] PullImage "gcr.io/hello-world"               
DEBU[2021-04-14T13:44:53.182820627-05:00] PullImage using normalized image ref: "gcr.io/hello-world:latest" 
DEBU[2021-04-14T13:44:53.183979170-05:00] resolving                                     host="172.18.0.7:5000"
DEBU[2021-04-14T13:44:53.184026001-05:00] do request                                    host="172.18.0.7:5000" request.header.accept="application/vnd.docker.distribution.manifest.v2+json, application/vnd.docker.distribution.manifest.list.v2+json, application/vnd.oci.image.manifest.v1+json, application/vnd.oci.image.index.v1+json, */*" …
```
> adds some debug log for each failed host

- images/converter/uncompress/uncompress.go
When several goroutines call uncompress converter in parallel, the ref name conflicts with each other. This leads to Writer method failing with Unavaliable error  without retry.
For solving this issue, OpenWriter helper should be used. This allows them to retry in such situations.
> converter: use OpenWriter helper function

- cmd/containerd/command/config.go
- services/server/config/config.go
- services/server/config/config_test.go
Related: https://github.com/containerd/containerd/pull/5335
According to [the doc about `config.toml`](https://github.com/containerd/containerd/blob/5c6ea7fdc1247939edaddb1eba62a94527418687/RELEASES.md#daemon-configuration) of containerd:
```
If no version number is specified inside the config file then it is assumed to be a version 1 config and parsed as such.
```
However, it's not true recently.
```console
[plugins]
[plugins.overlayfs]
root_path = "/dummy"
EOF
containerd: failed to load TOML from /tmp/config.toml: invalid plugin key URI "overlayfs" expect io.containerd.x.vx
```
This will break the backward-compatibility in some environment (e.g. [stargz-snapshotter project CI](https://github.com/containerd/stargz-snapshotter/runs/2329093209?check_suite_focus=true#step:4:1358)).
This …
> Fix backword-compatibility issue of non-versioned config file

- .github/workflows/ci.yml
- .github/workflows/publish_test_results.yml
- Makefile
- Vagrantfile
- script/setup/install-gotestsum
ci: upload junit formatted test results
This allows us to dig more details out of test runs and maintain a
better history.
For this we can use `gotestsum`, which is a utility that wraps `go test`
so that it outputs test2json (go's format) and output junit (a format
more easily imported into other systems).
The PR makes it possible to override the Makefile's use of `go test` to
use any other command tto execute the test. For CI we'll use `gotestsum
--`, where `gotestsum` expects everything after the `--` to be flags for
`go test`.
We then use environment variables to configure `gotestsum` (e.g.
`GOTESTSUM_JUNITFILE` is an env var accepted by `gotestsum`).
For cri tests, the test suite supports outputing test results to a
directory, these are in junit format already. The file is not named …
> ci: upload junit formatted test results

- runtime/v2/binary.go
- services/tasks/local_freebsd.go
This PR contains two commits adding runtime support for FreeBSD.  These commits are usable with [runj](https://github.com/samuelkarp/runj) and the `containerd-shim-runj-v1` shim.
> freebsd: runtime support

- runtime/runtime.go
- runtime/task.go
- runtime/v2/example/example.go
- runtime/v2/runc/v1/service.go
- runtime/v2/runc/v2/service.go
- runtime/v2/shim/shim.go
A few minor runtime changes:
- b83d04f adds variable names to runtime's interface definitions to ease readability.
- 993b863 extracts out `ShimStart` params into a separate structure `shim.StartOpts`. This will make easier adding new options and keep backward compatibility. For instance, turns out we [pass shim runtime options via Stdin](https://github.com/containerd/containerd/blob/master/runtime/v2/shim/util.go#L116), but don't really use those in the shim itself. I think we should expose this option in 1.6.
> Runtime cleanup

- metadata/namespaces.go
- metadata/namespaces_test.go
Deleting a non-empty namespace fails with
> namespace must be empty: failed precondition
This change improves the error message by listing all objects in
the namespace that prevent deletion.
> metadata: improve deleting a non-empty namespace's error message

- go.mod
- go.sum
- vendor/github.com/containerd/aufs/plugin/plugin.go
- vendor/github.com/containerd/zfs/plugin/plugin.go
- vendor/modules.txt
Updating dependencies to address https://github.com/containerd/zfs/issues/42.
> go.mod: github.com/containerd/zfs and github.com/containerd/aufs

- cmd/containerd/builtins_freebsd.go
~Note: this PR will remain in draft until https://github.com/containerd/zfs/pull/43 https://github.com/containerd/containerd/pull/5380 is merged.~
```
$ sudo ctr run \
--snapshotter=native \
--runtime wtf.sbk.runj.v1 \
--rm \
public.ecr.aws/samuelkarp/freebsd:12.1-RELEASE test-native mount
/var/lib/containerd/io.containerd.snapshotter.v1.native/snapshots/153 on / (nullfs, local)
$ sudo ctr run \
--snapshotter=zfs \
--runtime wtf.sbk.runj.v1 \
--rm \
public.ecr.aws/samuelkarp/freebsd:12.1-RELEASE test-zfs mount   
zroot/containerd/4 on / (zfs, local, noatime, nfsv4acls)
```
> freebsd: add zfs to the default plugins

- go.mod
- go.sum
- integration/client/go.sum
- vendor/github.com/google/uuid/hash.go
- vendor/github.com/google/uuid/sql.go
- vendor/github.com/google/uuid/uuid.go
- vendor/github.com/google/uuid/version4.go
- vendor/modules.txt
full diff: https://github.com/google/uuid/compare/v1.1.2...v1.2.0
I did not switch to us the `uuid.NewString()` function; we are not currently using
`uuid.New()`, probably because it can `panic` in case an invalid UUID is produced;
in stead we are using `uuid.NewRandom()`, which is equivalent, but returns an
error instead.
Changes:
- v1.2.0: Add NewString()
This release introduces the NewString() function which is the equivalent of
uuid.New().String().
- v1.1.5: Syntactic cleanup
There are no code changes. A missing period was add to a godoc comment and the
linter was told to not complain that the results of hash.Write() are ignored
(the function cannot fail)
- v1.1.4: Further error optimizations
Do not allocate memory for errors (it is only one word)
- v1.1.3: Optimize error reporting …
> go.mod: github.com/google/uuid v1.2.0

- snapshots/windows/windows.go
This builds on #4399 (itself on top of #4395) to implement `func (s *snapshotter) Commit` for Windows layers.
Contributes towards #1920, with the goal of resolving https://github.com/moby/buildkit/issues/616
It's a bit odd, but it seems that the only way to get this to work is to restream the read-write layer back on top of itself. I suspect this means that it is consuming extra space, but that appears to be necessary. Restreaming into a new snapshot means you cannot get a diff against the parent layer, which we often need to do.
The main weirdness here is that it seems that a windows-layer has two completely distinct filesystems, and you cannot diff all the combinations of them that you'd like, so we have to keep the writable-layer file around even after converting into the …
> Commit writable WCOW layers as read-only parent layers

- .github/workflows/ci.yml
- .github/workflows/nightly.yml
- .github/workflows/release.yml
- .zuul/playbooks/containerd-build/run.yaml
- Vagrantfile
- contrib/Dockerfile.test
go1.16.3 (released 2021/04/01) includes fixes to the compiler, linker, runtime,
the go command, and the testing and time packages. See the Go 1.16.3 milestone
on our issue tracker for details:
https://github.com/golang/go/issues?q=milestone%3AGo1.16.3+label%3ACherryPickApproved
full diff: https://github.com/golang/go/compare/go1.16.2...go1.16.3
> Update Go to 1.16.3

- .github/workflows/ci.yml
- .github/workflows/nightly.yml
- .github/workflows/release.yml
- .travis.yml
- .zuul/playbooks/containerd-build/run.yaml
- Vagrantfile
- contrib/Dockerfile.test
This patch is specific for the 1.4 release-branch, which is not on Go1.16, and
brings the branch to the latest patch release of Go 1.15
full diff: https://github.com/golang/go/compare/go1.15.8...go1.15.11
go1.15.9 (released 2021/03/10) includes security fixes to the encoding/xml
package. See the Go 1.15.9 milestone on our issue tracker for details.
https://github.com/golang/go/issues?q=milestone%3AGo1.15.9+label%3ACherryPickApproved
go1.15.10 (released 2021/03/11) includes fixes to the compiler, the go command,
and the net/http, os, syscall, and time packages. See the Go 1.15.10 milestone
on our issue tracker for details.
https://github.com/golang/go/issues?q=milestone%3AGo1.15.10+label%3ACherryPickApproved
go1.15.11 (released 2021/04/01) includes fixes to cgo, the compiler, linker, …
> [release/1.4] update Go to 1.15.11

- .github/workflows/ci.yml
- .github/workflows/release.yml
Using `-E` preserves environment variables, except for PATH, so PATH has to be manually set to match the current environment.
I removed env-vars that were redundant (such as `GOPATH=$GOPATH`), which should be handled by `-E`.
> gha: use sudo -E in some places to prevent dropping env-vars

- go.mod
- go.sum
- remotes/docker/pusher.go
- remotes/docker/status.go
- remotes/handlers.go
- remotes/resolver.go
- vendor/github.com/moby/locker/LICENSE
- vendor/github.com/moby/locker/README.md
- vendor/github.com/moby/locker/go.mod
- vendor/github.com/moby/locker/locker.go
- vendor/modules.txt
Fixes: https://github.com/containerd/containerd/issues/2706
Currently, `remotes.PushHandler` fails to push images that contain duplicated blobs. This is because when multiple and parallel calls of `dockerPusher.Push` with the same digest occur, each call races to update `StatusTracker`. This breaks the `Status` of the upload and `dockerPusher.Commit()` fails occasionally.
This commit tries to solve this issue without breaking backward compatibility.
This commit introduces a new backward-compatible extension for `StatusTracker` called `StatusTrackLocker` which implements named mutex for ensuring atomic update.
Additionally, this commit introduces `content.Ingester` API to `dockerPusher`. If there is already an ongoing upload of blob with ref "A", the second call with "A" returns …
> Fix PushHandler cannot push image that contains duplicated blobs

- releases/v1.5.0-rc.toml
- version/version.go
Last rc, after https://github.com/containerd/containerd/pull/5393
> Prepare 1.5.0-rc.2 release notes

- pkg/process/io.go
- pkg/process/io_util.go
- runtime/v1/shim/service_linux.go
- runtime/v1/shim/service_unix.go
- runtime/v2/runc/platform.go
Clean up the code, move `runtime.NewBinaryCmd` to `process.NewBinaryCmd` and use `process.NewBinaryCmd` directly 
https://github.com/containerd/containerd/blob/bbbd851381338e96eea77abb3dd14a3d2f18b9f3/runtime/io.go#L25-L45
> Cleanup code

- cmd/ctr/commands/images/images.go
resolving issue: https://github.com/containerd/containerd/issues/5352
check command returns errors for some cases when check fails, but not for the case when the image being checked via filter does not exist.. 
```
check       check that an image has all content available locally
```
we should fix or.. document and maybe add another sub command for the desired check  
...
After discussion with Derek decision is to document existing usage a little better, and add a -q quiet option to output only the images that are ready.  Idea being that script writers can then use `wc -l` and check for non-zero ... etc.
example outputs after changes:
```
mike@mike-VirtualBox:~/go/src/github.com/containerd/containerd$ sudo bin/ctr i check --help
NAME:
ctr images check - check existing images to ensure all …
```
> add check quiet option and update usage 

- .github/workflows/ci.yml
- .github/workflows/nightly.yml
- .github/workflows/release.yml
partial backports of:
- https://github.com/containerd/containerd/pull/5011 GHA: use setup-go@v2 
- https://github.com/containerd/containerd/pull/4741 gha: use sudo -E in some places to prevent dropping env-vars
To get a clean cherry-pick we'd have to backport a lot more changes, which I don't think is worth the effort, but we can update other changes manually if we think it's worth it
> [release/1.4] backport some github-action changes

- pkg/process/utils.go
The `done` is used as a signal channel to do notifications by closing, no data will be written, so `done`  does not need to be a buffer channel.
> process: use the unbuffered channel as the done signal

- pkg/cri/opts/spec_linux.go
- pkg/cri/server/container_create_linux.go
- pkg/cri/server/container_start.go
- pkg/cri/server/helpers.go
- pkg/cri/server/helpers_test.go
Fixes #5008 
As mentioned in the issue, support for the namespace mode TARGET is needed for debugging with kubernetes ephemeral containers. Kubernetes is already passing a TargetID, so containerd just needs to set up the new container with the existing PID namespace of the target container.
I'll need some guidance on these things:
And @verb I'd like you to take a look to ensure that this implementation matches what is expected by kubernetes.
> Support PID NamespaceMode_TARGET

- runtime/v2/runc/container.go
(cherry picked from commit 5e484c96139d2e4c93a277ff0c0caf815acb466f)
cherry-pick: https://github.com/containerd/containerd/pull/5206
> [release/1.4] runtime/v2/runc: fix the defer cleanup of the NewContainer

- .zuul.yaml
- .zuul/playbooks/containerd-build/integration-test.yaml
- .zuul/playbooks/containerd-build/unit-test.yaml
Running the following tests:
```
make test
make root-test
make integration EXTRA_TESTFLAGS=-no-criu TESTFLAGS_RACE=-race
TESTFLAGS_PARALLEL=1 make integration EXTRA_TESTFLAGS=-no-criu
CONTAINERD_RUNTIME="io.containerd.runc.v2" make cri-integration
```
Should be easy to add more as needed or break this into multiple jobs.
NOTE: some tests are failing.
> New Openlab based job to run ARM64 tests

- integration/images/volume-copy-up/Makefile
- integration/images/volume-ownership/Dockerfile
- integration/images/volume-ownership/Makefile
- Add a multi-arch image with linux/amd64 and linux/arm64 (limit to just
what we are running in CI)
- Bump versions to 2.0 as 1.0 is the single-arch image
- Use `docker buildx` instead of just docker, so we don't need to build
manifests by hand
- busybox now does not have `nogroup`, since the test needs it, switch
over from busybox to ubuntu for just the volume-ownership image
NOTE: not switching over integration/volume_copy_up_test.go to this newer image yet as it has not yet been pushed to the gcr repo.
> Add multi-arch support for test images

- .zuul/playbooks/containerd-build/integration-test.yaml
We need/use `lsof` in integration tests:
https://github.com/containerd/containerd/blob/master/integration/client/container_linux_test.go#L493
`TestShimDoesNotLeakPipes` fails if `lsof` is not present
> integration tests needs lsof

- test/build-test-images.sh
Add a script that can be run from prow, looks like the secret needed to push images to `k8s-cri-containerd` is already there.
> Add script to build test images

- integration/volume_copy_up_test.go
Follow up to https://github.com/containerd/containerd/pull/5416, We need to push those images first and then merge this change
> Use the multi-arch versions of the test images

- .github/workflows/release.yml
ARM64 is pretty popular these days because of the new t4g, c6g, m6g and r6g instance types in AWS. Would make sense to have an official release for containerd.
Fixes: #2901
Ref: https://github.com/containerd/containerd/pull/5262#issuecomment-806401121
CC: @AkihiroSuda
Signed-off-by: Ciprian Hacman <ciprian@hakman.dev>
> Release artifacts for Linux ARM64

- releases/v1.5.0-rc.toml
- version/version.go
See https://gist.github.com/dmcgowan/dc3cacd6f1c6fbb5ae69d7d0e392cc35
Pending clearing the [1.5 milestone](https://github.com/containerd/containerd/milestone/30)
> Prepare v1.5.0-rc.3 release notes

- Makefile
- integration/addition_gids_test.go
- integration/common.go
- integration/container_log_test.go
- integration/container_stop_test.go
- integration/container_without_image_ref_test.go
- integration/containerd_image_test.go
- integration/image_list.sample.toml
- integration/image_load_test.go
- integration/imagefs_info_test.go
- integration/main_test.go
- integration/pod_dualstack_test.go
- integration/pod_hostname_test.go
- integration/restart_test.go
- integration/truncindex_test.go
- integration/volume_copy_up_test.go
- script/test/cri-integration.sh
Currently, the ``cri-integration`` tests do not work on Windows due to various reasons. One of the reasons is because all the tests are using Linux-specific images. This commit refactors the image pulling / usage in the ``cri-integration`` tests, making it
easier to update, and easier to configure the a custom registry to pull those images from.
For Windows runs, custom registries can be created, which will also contain Windows images, and the ``cri-integration`` tests can be configured to use those registries by specifying the ``--image-list`` argument, a YAML file which will contain an alternative
mapping of the default images.
> tests: Refactors container image usage

- RELEASES.md
aufs was removed from Ubuntu kernel in Ubuntu 21.04, and Ubuntu 16.04 is going to reach EOL on Apr 30,  so deprecate the built-in aufs snapshotter.
The aufs snapshotter can be still maintained as a non-builtin snapshotter.
> Deprecate built-in aufs snapshotter

- .github/workflows/release.yml
- script/setup/install-seccomp
seccomp's build scripts require setting the target arch that will be
built when cross compiling.
> Specify seccomp target arch for CC

- integration/common.go
- integration/container_stats_test.go
We can check that the reported containers stats are not lower than it should by using the ``resource-consumer`` image. This image contains ``stress`` / ``testlimit.exe`` which can consume a specified amount of memory.
> tests: Adds consumed memory stats test

- .github/workflows/ci.yml
Docker/Moby still uses Go 1.13 for building containerd binaries.
> CI: allow Go 1.13 for Docker/Moby compatibility

- .github/workflows/release.yml
- releases/v1.5.0-rc.toml
- script/setup/install-seccomp
The ARM builds are failing during the release process. These need a bit more work to cross compile all the binaries and be tested before going into a release.
> Revert arm64 release builds

- README.md
Currently, we can not reproduce the given Namespaces section examples written in the README, since it's not clear to which package should we import to.
Signed-off-by: Furkan Turkal <furkan.turkal@trendyol.com>
> doc: add missing namespaces package

- pkg/os/os.go
- pkg/os/os_unix.go
- pkg/os/os_windows.go
- pkg/os/os_windows_test.go
This change splits the definition of pkg/cri/os.ResolveSymbolicLink by
platform (windows/!windows), and switches to an alternate implementation
for Windows. This aims to fix the issue described in #5405.
The previous implementation which just called filepath.EvalSymlinks has
historically had issues on Windows. One of these issues we were able to
fix in Go, but EvalSymlinks's behavior is not well specified on
Windows, and there could easily be more issues in the future, so it
seems prudent to move to a separate implementation for Windows.
The new implementation uses the Windows GetFinalPathNameByHandle API,
which takes a handle to an open file or directory and some flags, and
returns the "real" name for the object. See comments in the code for
details on the implementation.
I have tested …
> windows: Use GetFinalPathNameByHandle for ResolveSymbolicLink

- pkg/os/os.go
- pkg/os/os_unix.go
- pkg/os/os_windows.go
- pkg/os/os_windows_test.go
Cherry-pick of #5411 for `release/1.5`
This change splits the definition of pkg/cri/os.ResolveSymbolicLink by
platform (windows/!windows), and switches to an alternate implementation
for Windows. This aims to fix the issue described in containerd/containerd#5405.
The previous implementation which just called filepath.EvalSymlinks has
historically had issues on Windows. One of these issues we were able to
fix in Go, but EvalSymlinks's behavior is not well specified on
Windows, and there could easily be more issues in the future, so it
seems prudent to move to a separate implementation for Windows.
The new implementation uses the Windows GetFinalPathNameByHandle API,
which takes a handle to an open file or directory and some flags, and
returns the "real" name for the object. See comments in …
> [release/1.5] cherry-pick: windows: Use GetFinalPathNameByHandle for ResolveSymbolicLink

- oci/spec_opts.go
- oci/spec_opts_test.go
I think that as an exported function, it should be robust enough.
* `WithDevShmSize` should only set the size of the `/dev/shm`
* size options should be de-duplicated to prevent overwriting of the latter options
* [`m`](https://github.com/containerd/containerd/pull/5063/files#diff-0baf32d622b0e06b22e45cb92391d05d9505d2eba6ff93c8b773c8c705fbd7feL1265) is not a pointer，fix `m.Options = append(m.Options, fmt.Sprintf("size=%dk", kb))`
> oci: fix WithDevShmSize

- .github/workflows/ci.yml
- .github/workflows/nightly.yml
- .github/workflows/release.yml
- .zuul/playbooks/containerd-build/run.yaml
- Vagrantfile
- contrib/Dockerfile.test
fix [#45710](https://github.com/golang/go/issues/45710) and CVE-2021-31525.
full diff: https://github.com/golang/go/compare/go1.16.3...go1.16.4
Signed-off-by: Jintao Zhang <zhangjintao9020@gmail.com>
> Update Go to 1.16.4

- script/setup/install-critools
Address #5460
build:
```
root@mike-VirtualBox:/home/mike/go/src/github.com/containerd/containerd# make clean
+ clean
root@mike-VirtualBox:/home/mike/go/src/github.com/containerd/containerd# make cri-cni-release
+ bin/ctr
+ bin/containerd
+ bin/containerd-stress
+ bin/containerd-shim
+ bin/containerd-shim-runc-v1
+ bin/containerd-shim-runc-v2
echo "CONTAINERD_VERSION: '1.5.0-1-ge60322b80'" | tee /home/mike/go/src/github.com/containerd/containerd/_output/cri/opt/containerd/cluster/version
CONTAINERD_VERSION: '1.5.0-1-ge60322b80'
DESTDIR=/home/mike/go/src/github.com/containerd/containerd/_output/cri script/setup/install-runc
Cloning into '/tmp/tmp.gtWLv0hENH/runc'...
remote: Enumerating objects: 29131, done.
remote: Counting objects: 100% (1292/1292), done.
remote: Compressing objects: 100% …
```
> update to new cri-tools make install

- Makefile
This is required for environments/build systems where a specific
go version / command needs to be used.
> Makefile: allow overriding go command by environment

- content/adaptor_test.go
I noticed AdaptInfo missing test cases. I think this func a bit important to test since we use this func in other packages like content, store (walking), etc.
Signed-off-by: Furkan Turkal <furkan.turkal@trendyol.com>
> tests: add test for adaptor

- cmd/ctr/commands/snapshots/snapshots.go
- content/testsuite/testsuite.go
- images/archive/importer.go
- install.go
`content.ReaderAt` is used in many places but not closed, It will actually call `os.Open`, this PR complements this close.
https://github.com/containerd/containerd/blob/01ca105b6a7c3d4307fe3d9cd847c7d48519a7bd/content/local/store.go#L128-L141
https://github.com/containerd/containerd/blob/01ca105b6a7c3d4307fe3d9cd847c7d48519a7bd/content/local/readerat.go#L35-L56
> Fix `content.ReaderAt` close

- releases/v1.4.5.toml
- version/version.go
See generate notes at https://gist.github.com/dmcgowan/b6e2032d5ad03f6c9fb7b6565fb87bf7
> [release/1.4] Prepare v1.4.5 release notes

- .github/workflows/release.yml
The `-E` is incorrect for the seccomp build. This causes environment set through `DESTDIR: ${{ github.workspace }}/cri-release` to get passed to seccomp, which installs the seccomp in the release directory, rather than the system directory needed for runc build.
> Fix seccomp build in release

- docs/hosts.md
Putting together some docs to describe configuring registries, authentication, and mirrors.
> adds description for hosts.toml

- Makefile
Let install-man depend on man, so manpages are really built before
trying to install them.
> Makefile: make sure manpages are built before install-man

- metadata/leases.go
`metadata.LeaseManager` is usually used as `leases.Manager`, and the purpose of the `metadata.LeaseManager` should alse be to implement `leases.Manager`
https://github.com/containerd/containerd/blob/087d03bc55006cb2550ab60333dc84130dc7c4e5/services/leases/local.go#L29-L60
> metadata: modify NewLeaseManager to return leases.Manager

- plugin/plugin.go
Optimize the check for the last registration
I originally wanted to change it to:
```go
var last bool
for _, requires := range r.Requires {
if requires == "*" {
last = true
break
}
}
if last && len(r.Requires) != 1 {
panic(ErrInvalidRequires)
}
```
But I found that the `last` would not be used elsewhere, so I changed it to:
```go
for _, requires := range r.Requires {
if requires == "*" && len(r.Requires) != 1 {
panic(ErrInvalidRequires)
}
}
```
> plugin: optimize the check for the last registration

- integration/addition_gids_test.go
- integration/common.go
- integration/container_log_test.go
- integration/container_stop_test.go
- integration/container_without_image_ref_test.go
- integration/containerd_image_test.go
- integration/imagefs_info_test.go
- integration/pod_dualstack_test.go
- integration/pod_hostname_test.go
- integration/restart_test.go
- integration/truncindex_test.go
- integration/volume_copy_up_test.go
Most of the tests are pulling and deleting the same test images, which can be quite inefficient, especially on Windows nodes, where the images are larger than the Linux ones (a nanoserver Container image is ~250MB in size). We can instead pull them
only once, and reuse them. This will reduce the test run time on Windows considerably.
Additionally, some of the test images are currently hosted on dockerhub (``busybox`` image), which has introduced image ratelimiting in November 2020, which means that test runners could potentially hit that limit faster with the current implementation. This will reduce that risk.
Some tests are specifically deleting images, so we always have to ensure that they are pulled.
> cri-integration tests: Pull images once

- integration/client/container_linux_test.go
The latest tag is no longer available for alpine, pin to the latest version rather than using latest.
> Pin integration test image for alpine

- integration/client/container_linux_test.go
The latest tag is no longer available for alpine, pin
to the latest version rather than using latest
> [release/1.5] integration pin image

- remotes/docker/resolver.go
Allows redirects to be authorized if authorization is provided for the redirected to host. The authorization will always go to the redirect and never to the referrer.
Matches redirect logic done by Docker today.
Fixes #5503
> Update docker resolver to authorize redirects

- Makefile
- integration/common.go
- integration/container_log_test.go
- integration/container_restart_test.go
- integration/container_stats_test.go
- integration/container_stop_test.go
- integration/container_update_resources_test.go
- integration/container_without_image_ref_test.go
- integration/containerd_image_test.go
- integration/duplicate_name_test.go
- integration/image_load_test.go
- integration/imagefs_info_test.go
- integration/main_test.go
- integration/no_metadata_test.go
- integration/pod_dualstack_test.go
- integration/pod_hostname_test.go
- integration/restart_test.go
- integration/truncindex_test.go
- integration/volume_copy_up_test.go
- script/test/cri-integration.sh
- script/test/utils.sh
Currently, the cri-integration tests do not work on Windows due to various reasons. One of the reasons is because all the tests are using Linux-specific images. This commit refactors the image pulling / usage in the cri-integration tests, making it
easier to update, and easier to configure the a custom registry to pull those images from.
For Windows runs, custom registries can be created, which will also contain Windows images, and the cri-integration tests can be configured to use those registries by specifying the ``--repo-list`` argument, a YAML file which will contain an alternative
mapping of the default registries. This is similar to how E2E tests are handled for Windows runs in Kubernetes.
Some of the tests are Skipped, as they do not pass yet on Windows.
Windows does not collect …
> tests: Adds support for Windows cri-integration tests

- Makefile
Packaging systems often want to override the install(1) command via INSTALL
environment variable, in order to do distro specific fixups (eg. splitting
out debug symbols from binaries to separate files).
Also use it for creating install target directories.
> Makefile: allow overriding install command via environment

- go.mod
- go.sum
- vendor/github.com/Microsoft/go-winio/README.md
- vendor/github.com/Microsoft/go-winio/privilege.go
- vendor/modules.txt
Just hygiene! not much changes are picked up. Though here's the history.
Bumps [github.com/Microsoft/go-winio](https://github.com/Microsoft/go-winio) from 0.4.15 to 0.5.0.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a href="https://github.com/Microsoft/go-winio/releases">github.com/Microsoft/go-winio's releases</a>.</em></p>
<blockquote>
<h2>v0.5.0</h2>
<ul>
<li>Added GetFileStandardInfo which returns information from the GetFileInformationByHandleEx syscall with FileStandardInfo specified.
<ul>
<li>This is a potentially breaking change, see <a href="https://github-redirect.dependabot.com/moby/moby/pull/42307">moby/moby#42307</a></li>
</ul>
</li>
</ul>
<h2>v0.4.19</h2>
<ul>
<li>Temporarily reverted implementation of GetFileStandardInfo which returns information from …
> Bump github.com/Microsoft/go-winio from 0.4.15 to 0.5.0

- Makefile
Make rules can be formulated more generic by using the $@ symbol, instead
of duplicating the target file name.
Just a little cleanup for better maintainability.
> Makefile: use $@ for target file names

- cmd/ctr/commands/tasks/exec.go
This series adjusts the pty behavior in `ctr task exec` to be consistent with `ctr run`.  Two changes are made:
1. The `console.Console` is found prior to `task.Exec` and used as with `cio.WithStreams`
2. Initial pty resize and signal handling is moved after `task.Start`
Both of these changes seem necessary on FreeBSD with [runj](https://github.com/samuelkarp/runj); without change 1 keyboard input did not seem to be correctly sent to the shim and without change 2 the initial resize was lost.
I also tested these changes on Linux and `ctr task exec` seemed to continue to work fine both before and after these commits.  I do not currently have access to a Windows machine to test any behavioral differences there.
> ctr: make exec pty behavior consistent with run

- cmd/ctr/commands/run/run.go
FreeBSD mount options may have embedded = characters.  For example, devfs(5) supports the `ruleset` option which can be passed as `ruleset=4` to indicate that ruleset 4 should be used.
> ctr: parse mount options with embedded = character

- remotes/docker/auth/fetch.go
Previously, containerd uses Go's default UA "Go-http-client/1.1" while authenticating with registry.
This commit changes it to the pattern like "containerd/v1.5.2" which is used for all other requests.
Fixes #5532
> Fix incorrect UA used for registry authentication

- snapshots/btrfs/btrfs_test.go
Check if btrfs module is loaded. if not do not run btrfs test.
> Do not run btrfs tests if btrfs kernel module is not loaded
