containerd/containerd

content/local/store.go
The function does not guarantee atomicity, because the same temporary file will be opened multiple times.
https://github.com/containerd/containerd/blob/75a0c2b7d35cb91714bbfdf0fcadfe25f777ee8d/content/local/store.go#L689-L701
Should be changed to write a random temporary file Instead of writing a fixed temporary file.
Like this https://github.com/containerd/continuity/blob/93e15499afd51cdc830773dc804c89c11673fc63/ioutils.go#L34-L63
=> Rename atomicWrite to writeToCompletion

.github/workflows/windows-periodic.yml, script/setup/enable_ssh_windows.ps1, script/setup/install-cni-windows, script/setup/prepare_env_windows.ps1
Part of the ongoing work described here: https://github.com/containerd/containerd/issues/5039
This introduces a periodic Windows 1909 testing job. This will be expanded to multiple Windows Versions. The goal is to improve testing volume & coverage on multiple Windows versions in order to pick up any regression or intermittent issue with containerD for Windows. 
TO-DOs:
- This step has been commented out , pending reenabling when #5163 merges. It seems appropriate to not wait for that PR to merge as to not slow the process for this one unnecessarily
=> Add CI periodic Windows Jobs.

docs/cri/crictl.md, docs/cri/decryption.md
1. fix crictl version link
2. [containers/ocicrypt](https://github.com/containers/ocicrypt): branch master was renamed to main.
=> docs/cri: update links

docs/ops.md
It is under `/v1/metrics`, which should be explicitly called out.
=> docs: explicitly mention containerd's Prometheus path

.zuul/playbooks/containerd-build/integration-test.yaml
fix for `containerd-integration-test-arm64` CI job failing with missing apparmor.
=> Install apparmor parser for arm64 environment

content/local/store.go
Fixes: #3974 
Per this [comment](https://github.com/containerd/containerd/issues/3974#issuecomment-851400334) in #3974 there is definitely a problem in that the `Wrapf` is wrapping a non-error and therefore the return has no error.
=> Change Wrapf of non-error to an actual error

BUILDING.md, Makefile
The DESTDIR environment variable is used in the wrong way: since 30+ years
it's common practise using it for specifying *temporary* target *root*
(where eg. packaging infrastructure picks up the install image), instead
of the installation *prefix* on the final target.
Fixing this by introducing PREFIX variable (with default /usr/local) and
using both variables according to the 30 years matured common practise.
That way, distro packagers and other standardized build/installation
systems can easily do correct deployments w/o individual hacks.
=> Makefile: fix DESTDIR environment variable behaviour

integration/container_volume_test.go, integration/main_test.go
There was a known issue regarding how the symlink files mounted as volumes were being handled on Windows. This commit adds tests that will check against those issue to ensure there won't be any regressions.
Related issue: https://github.com/containerd/containerd/issues/4915
=> tests: Symlink volume tests

snapshots/windows/windows.go
It seems that something has shifted in an API, and `vhd.DetachVhd` is returning "failed to open virtual disk: invalid argument" on Windows Server LTSC 2019.
Since the snapshotter test suite is not being run for Windows, nothing is likely to have been exercising this code on CI. #4419 is trying to get the snapshot suite working, and was seeing errors like the below a bit randomly on both CI, and an LTSC 2019 eval instance, but _not_ on my Windows 10 20H2 desktop:
```
issues.go:89: Check snapshots failed: rename C:\Users\ADMINI~1\AppData\Local\Temp\2\snapshot-suite-Windows-014324559\root\snapshots\6 C:\Users\ADMINI~1\AppData\Local\Temp\2\snapshot-suite-Windows-014324559\root\snapshots\rm-6: Access is denied.
failed to detach VHD: failed to open virtual disk: invalid argument …
```
=> Use DeactivateLayer to unlock layers that we cannot rename

sys/filesys_windows.go
ForceRemoveAll has special logic on Windows for cleaning up a Windows
snapshotter directory. The logic was missing proper handling for an
error case that can be returned in some cases.
This fixes the CI failure seen in #5326.
=> Fix error case in Windows layer cleanup

.github/workflows/windows-periodic.yml
When creating a resource group in Azure for the Windows Periodic Job, we need to tag it with a timestamp so that the automatic cleanup tool will not delete the RG mid run.
Signed-off-by: Adelina Tuvenie <atuvenie@cloudbasesolutions.com>
=> Windows periodic job: Add creation timestamp to RG

diff/walking/differ.go
`err` may be overwritten
https://github.com/containerd/containerd/blob/c8b33ba297d86550dd5e530527cf5d92246d292f/diff/walking/differ.go#L143-L147
https://github.com/containerd/containerd/blob/c8b33ba297d86550dd5e530527cf5d92246d292f/diff/walking/differ.go#L156-L162
=> diff/walking: fix defer cleanup

metadata/containers.go, metadata/content.go
validateContainer and validateInfo returning immediately if a label exists 
found these while reviewing if we had any issues regarding calling "github.com/pkg/errors"`.Wrapf(err,` where err is nil... turns out yes. Was looking thanks to learning from https://github.com/containerd/containerd/pull/5560 that if wrapping nil you get nil .. 
** side note `github.com/hashicorp/errorwrap.Wrapf` in our vendor tree (didn't check why) does in fact wrap nil with as `<nil>` and thus returns the nil wrapped vs returning nil) 
=> fix invalid validation error checking

diff/walking/differ.go
Clarify error scope and create variable for deferring cleanup
Reverts #5551
=> Revert diff/walking error change

pkg/cri/server/sandbox_run.go
Similar to other deferred cleanup operations, teardownPodNetwork should use a different context as the original context may have expired, otherwise CNI wouldn't been invoked, leading to leak of network resources, e.g. IP addresses.  
Signed-off-by: Quan Tian <qtian@vmware.com>
Fixes #5438
=> Fix cleanup context of teardownPodNetwork

docs/cri/config.md
Had a question in slack from a user:
```
Hi，what’s the default seccomp profile for containerd? Is it undefined?  I mean if k8s provided the runtime/default , what seccomp profile would containerd use?
From this parameter settings I think it’s undefined , but I am not sure:
unset_seccomp_profile = ""
```
This doc update should resolve further questions in this regard..
=> adds explanation for seccomp unset/unconfined default vs runtime default

metadata/containers.go, metadata/content.go
fix invalid validation error checking - validateContainer and validateInfo were returning immediately if a label exists
(cherry picked from commit 014748bc04623346725d2a1330d7a2292563a4df)
#5565
=> [release/1.5] cherry pick #5565 to release 1.5 - fix invalid validation error checking

metadata/containers.go, metadata/content.go
fix invalid validation error checking - validateContainer and validateInfo were returning immediately if a label exists
(cherry picked from commit 014748bc04623346725d2a1330d7a2292563a4df)
#5565
=> [release/1.4] cherry pick #5565 to release 1.4 - fix invalid validation error checking

.github/workflows/ci.yml
Due to a change in Go, the go.mod file cannot declare a version of Go
above the installed `go version`; until the default Go version in GitHub
Actions virtual environments is 1.16 or above, we have to install 1.16 before
running the project checks now.
More details: https://github.com/golang/go/issues/46143
The *20210606 version* of virtenv **ubuntu-18.04** is still rolling out so I have only seen this fail one PR build in the last 24 hours, but we should get this change in before it starts breaking all PR runs once rollout of the new virt. env. image is complete.
=> Add proper Go version before project checks

.github/workflows/ci.yml
Due to a change in Go, the go.mod file cannot declare a version of Go
above the installed `go version`; until the default Go version in GitHub
actions virt environments is 1.16, we have to install 1.16 before
running the project checks now.
(cherry picked from commit 3ab97443360775ff3fb13a7be2efedb875805824)
Cherry pick of #5594
=> [release/1.5] cherry-pick: Add proper Go version before project checks

pkg/cri/server/sandbox_run.go
Similar to other deferred cleanup operations, teardownPodNetwork should
use a different context as the original context may have expired,
otherwise CNI wouldn't been invoked, leading to leak of network
resources, e.g. IP addresses.
Signed-off-by: Quan Tian <qtian@vmware.com>
(cherry picked from commit 728743eb2858764df05fbb012cb03eb7c6cb0423)
Cherry pick of #5569
=> [release/1.5] cherry pick #5569 to release 1.5 - Fix cleanup context of teardownPodNetwork

remotes/docker/auth/fetch.go
Previously, containerd uses Go's default UA "Go-http-client/1.1" while authenticating with registry.
This commit changes it to the pattern like "containerd/v1.5.2" which is used for all other requests.
Signed-off-by: Ethan Chen <pov@mahou-shoujo.moe>
(cherry picked from commit 50ad4b96c4acfde425e1fc6e7411b52658d7af92)
Cherry-pick of https://github.com/containerd/containerd/pull/5533
I saw there is a cherry-pick label but no PR is created, so I help create this for cherry-picking.
=> [release/1.5] cherry-pick #5533: Fix incorrect UA used for registry authentication

Makefile
FHS mandates manpages should go to /usr/share/man (or /usr/local/share/man,
for site local installations) -- /usr/man was an fallout of some ancient
Unices that haven't been fully FHS conformant and usually just a symlink to
/usr/share/man, if existing at all.
Distros sometimes need to override this (eg. MVCC installs), therefore go
the 30+ years common practise way and introduce MANDIR environment variable.
Since it's a subdir under the prefix for general constant and machine
architecture independ data -- which in turn also sometimes wants to be
overridden by distros, it shall be derived from DATADIR variable.
=> Makefile: FHS conformant manpage installation pathes

contrib/nvidia/nvidia.go
Fixes https://github.com/containerd/containerd/issues/5603
Through discussion in https://github.com/moby/moby/issues/38729#issuecomment-463493866 and https://github.com/containerd/nerdctl/pull/251#pullrequestreview-682850894, it turns out we need to pass `--no-cgroups` option to `nvidia-container-cli` for using it in rootless environmetns.
This commit allows `nvidia` pkg to do this.
=> Allow to pass --no-cgroups option to nvidia-container-cli

script/setup/install-gotestsum
The current release of gotestsum is missing timestamps in the junit
data, which makes it difficult to import in an external system later.
https://github.com/gotestyourself/gotestsum/commit/012a85e34a7ce5554057d512e55dcb
includes the necessary changes to add the timestamp for the test run to
the junit output.
=> Update gotestsum to add timestamps to junit output

cmd/ctr/commands/commands_unix.go, cmd/ctr/commands/run/run_unix.go
Implement #5381.
A new flag `--rootfs-propagation` is added to `ctr run` and `ctr container create` to set propagation of the container rootfs.
Its value can be one of the propagation settings lists in [Configuare bind propagation](https://docs.docker.com/storage/bind-mounts/#configure-bind-propagation).
If the flag is set, say "rshared", users can check settings through `ctr c info CONTAINER`, and get the output below.
```json
{
"Spec": {
"linux": {
"rootfsPropagation": "rshared"
}
}
}
```
=> ctr flags of container rootfs propagation

.golangci.yml
https://github.com/containerd/containerd/pull/5615#issuecomment-863057676
> Linter timeouts ( level=error msg="Timeout exceeded: try increasing it by passing --timeout option").
> Could we rerun tests?
Recently I experienced the timeout of linter. This PR increases the timeout limit +5m for avoiding the same CI failure.
=> CI: Increase golangci-lint timeout

runtime/v2/binary.go
Currently the shimv2 debug is only enabled when containerd is,
specifically, on debug mode.  However, it should be enabled whenever the
CRI runtime is on debug *or any other lower* mode, as in trace mode.
=> runtime,v2: Enable debug when containerd is on debug+ log level

.github/workflows/ci.yml
Ubuntu kernel updates claim that the criu+overlayfs bug is finally fixed
in released kernels.
=> Re-enable criu in main integration runs

docs/cri/config.md
based on https://github.com/containerd/containerd/blob/master/pkg/cri/config/config.go#L305, we still can use
- [plugins."io.containerd.grpc.v1.cri".containerd.default_runtime]
- [plugins."io.containerd.grpc.v1.cri".containerd.untrusted_workload_runtime]
Alo fix typo `plugins."io.containerd.grpc.v1.cri".runtimes` to `plugins."io.containerd.grpc.v1.cri".containerd.runtimes`.
=> docs: fix deprecation config for default runtime

integration/client/client_unix_test.go, integration/client/container_linux_test.go
This PR will fix recent CI flakiness.
e.g. https://github.com/containerd/containerd/pull/5624/checks?check_run_id=2872129388#step:10:24
```
failed to resolve reference "mirror.gcr.io/library/busybox:1.32.0": mirror.gcr.io/library/busybox:1.32.0: not found: time="2021-06-21T05:13:34.429018623Z" level=info msg="starting containerd" revision=7a05fcc46b77bd0f0250a3f4d6d74c08c803d794 version=7a05fcc
```
`mirror.gcr.io/library/busybox:1.32.0` is unavailable.
```console
$ curl -s https://mirror.gcr.io//v2/library/busybox/tags/list | jq '.tags'
[
"1.26.2",
"1.27.2",
"1.28",
"1.29",
"1.29.2",
"1.29.3",
"1.30",
"1.30.1",
"1.31",
"1.31.0",
"1.31.1",
"1.32",
"latest"
]
```
`mirror.gcr.io/library/alpine:3.13` is unavailable.
```console
$ curl -s https://mirror.gcr.io//v2/library/alpine/tags/list | jq …
```
=> CI: Switch to the available latest images

archive/tar.go, archive/tar_linux_test.go
`changeWriter` in `archive` package provides a generic functionality to create tar archives from the filesystem change information. Especially `*archive.changeWriter.HandleChange` is useful for creating filesystem diff archive combining with continuity's diff computing functionality (`fs.Changes()`).
This PR allows containerd users to customize diffing logic relying on `changeWriter` for creating tar archives. An example use case of this is for the overlayfs-oriented diff logic discussed in BuildKit (https://github.com/moby/buildkit/pull/2181 and https://github.com/containerd/continuity/pull/145).
=> archive: Expose ChangeWriter to allow customized diff computing

content/local/store_bsd.go, content/local/store_openbsd.go
relates to https://github.com/docker/cli/pull/3154
The sys.StatATimeAsTime() utility is currently only used in a single place, but because it's living in the "sys" package, also brings in other dependencies, such as Microsoft/hcsshim.
This patch inlines the code from sys.StatATimeAsTime(), to remove that dependency.
We can consider removing the utilities in `sys` in favor of their copy in containerd/continuity; https://github.com/containerd/containerd/blob/b12c3215a0af92b9244b14c8555fc028b0d1d8c1/sys/stat_unix.go#L26-L44
https://github.com/containerd/continuity/blob/33a84563724b68f70fc71fbb632cf9e0ad60ba5d/fs/stat_linuxopenbsd.go#L26-L45
(I'll have a look at that in a follow-up)
=> content/local: inline sys.StatATimeAsTime()

content/local/store_bsd.go, content/local/store_openbsd.go
cherry-pick of https://github.com/containerd/containerd/pull/5633
relates to https://github.com/docker/cli/pull/3154
The sys.StatATimeAsTime() utility is currently only used in a single place,
but because it's living in the "sys" package, also brings in other dependencies,
such as Microsoft/hcsshim.
This patch inlines the code from sys.StatATimeAsTime(), to remove that dependency.
=> [release/1.5 backport] content/local: inline sys.StatATimeAsTime()

pkg/cri/server/sandbox_run.go
CNI plugins that need to wait for network state to converge
may want to cancel waiting when a short lived pod is deleted.
However, there is a race between when kubelet asks the runtime
to create the sandbox for the pod, and when the plugin is able
request the pod object from the apiserver. It may be the case
that the plugin receives the new pod, rather than the pod
the sandbox request was initiated for.
Passing the pod UID to the plugin allows the plugin to check
whether the pod it gets from the apiserver is actually the
pod its sandbox request was started for.
(corresponding crio PR is https://github.com/cri-o/cri-o/pull/5026, FWIW)
@estesp @fuweid
=> sandbox: send pod UID to CNI plugins as K8S_POD_UID

pkg/cri/server/sandbox_run.go
CNI plugins that need to wait for network state to converge
may want to cancel waiting when a short lived pod is deleted.
However, there is a race between when kubelet asks the runtime
to create the sandbox for the pod, and when the plugin is able
request the pod object from the apiserver. It may be the case
that the plugin receives the new pod, rather than the pod
the sandbox request was initiated for.
Passing the pod UID to the plugin allows the plugin to check
whether the pod it gets from the apiserver is actually the
pod its sandbox request was started for.
Cherry-pick of https://github.com/containerd/containerd/pull/5640
@estesp @fuweid
=> [release/1.5] sandbox: send pod UID to CNI plugins as K8S_POD_UID

integration/addition_gids_test.go, integration/container_log_test.go, integration/container_restart_test.go, integration/container_stats_test.go, integration/container_stop_test.go, integration/container_update_resources_test.go, integration/container_volume_test.go, integration/container_without_image_ref_test.go, integration/containerd_image_test.go, integration/duplicate_name_test.go, integration/image_load_test.go, integration/imagefs_info_test.go, integration/main_test.go, integration/no_metadata_test.go, integration/pod_dualstack_test.go, integration/runtime_handler_test.go, integration/volume_copy_up_test.go
Most of the tests creating and using Pod Sandboxes in the same way. We can create a common function that will do that for us, so we can have less duplicated code, and make it easier to add new tests in the future.
Most tests require pulling a test image, and most of them are doing it in the same way. A function ``PulImageWithCleanup`` was introduced in a previous commit. Using it will reduce the amount of duplicated code.
=> Cri integration cleanup

Makefile
Commits 77374e8 (https://github.com/containerd/containerd/pull/5577) and b5f530a  https://github.com/containerd/containerd/pull/5535) changed handling of the `DESTDIR` and `PREFIX` variables, and introduced a `MANDIR` variable.
However, in those commits, the variables are concatenated with a directory separator (`/`); `$DESTDIR/$PREFIX`. The `$PREFIX` variable (and consequently, the `MANDIR` variable) already should have a leading `/` (absolute path), so there should be no need to add it. In addition, adding the `/`, would not allow either an empty path to be passed (well, it would result in `//` in the path), or for `$PREFIX` to be used with a relative path (with an empty `$PREFIX`).
This patch removes the directory separator.
=> Makefile: fix DESTDIR and PREFIX concatenation

.github/workflows/ci.yml, .github/workflows/nightly.yml, .github/workflows/release.yml, .travis.yml, .zuul/playbooks/containerd-build/run.yaml, Vagrantfile, contrib/Dockerfile.test
go1.15.13 (released 2021-06-03) includes security fixes to the archive/zip, math/big,
net, and net/http/httputil packages, as well as bug fixes to the linker, the go
command, and the math/big and net/http packages. See the Go 1.15.13 milestone on
https://github.com/golang/go/issues?q=milestone%3AGo1.15.13+label%3ACherryPickApproved
go1.15.12 (released 2021-05-06) includes a security fix to the net/http package,
as well as bug fixes to the runtime, the compiler, and the archive/zip, time,
and syscall packages. See the Go 1.15.12 milestone on the issue tracker for details:
https://github.com/golang/go/issues?q=milestone%3AGo1.15.12+label%3ACherryPickApproved
=> [release/1.4] Update Go to 1.15.13

snapshots/devmapper/snapshotter.go
- View was somehow logging itself as "prepare"
- Cleanup should have its debug log as like other exported methods
=> snapshot/devmapper: log exported methods correctly

cmd/ctr/commands/commands.go, cmd/ctr/commands/containers/containers.go, cmd/ctr/commands/run/run.go, cmd/ctr/commands/run/run_unix.go
Pass command label to snapshotter can help it determine which kind of writable snapshots should be provide.
For some snapshotter, such as overlaybd ( https://github.com/alibaba/accelerated-container-image ), it can provide 2 kind of writable snapshot(overlayfs dir or blockdevice) by command label values.
=> Add ctr command label in NewContainerOpts

script/setup/prepare_env_windows.ps1
For Periodic Windows runs we installed the latest available golang version.
It seems 1.16.5 is creating problems with go.sum. We now introduce the
ability to install specific versions for required packages when preparing
the testing env.
This was noticed after the merge of PR: #5562
Trying to run integration tests with golang v1.16.5 results in:
```
$ make integration
+ integration
..\..\container.go:40:2: missing go.sum entry for module providing package github.com/opencontainers/selinux/go-selinux/label (imported by github.com/containerd/containerd); to add:
go get github.com/containerd/containerd@v1.5.1
FAIL    github.com/containerd/containerd/integration/client [setup failed]
make: *** [Makefile:192: integration] Error 1
```
The usual suspects like `go mod tidy` do not work.
Every …
=> Install specific golang version in Windows CI.

archive/tar.go, archive/tar_freebsd.go, archive/tar_mostunix.go, archive/tar_unix.go, archive/tar_windows.go
Move to single lchmod interface mirroring other implementations.
Separate logic for freebsd which supports symlink no follow flag.
Also see https://github.com/containerd/continuity/tree/main/driver
=> archive: cleanup lchmod logic

README.md, docs/hosts.md, remotes/docker/config/hosts.go, remotes/docker/config/hosts_test.go
Clarifies in stronger language which registries are supported by containerd now that OCI distribution specification has reached 1.0 and has compliance testing.
Adds a "workaround" for registries which do not properly implement the "/v2" prefix as defined by the specification. This helps some Harbor users which are using non-compliant mirror endpoints.
Closes #5518
=> Update for distribution spec 1.0

.github/workflows/ci.yml, Vagrantfile, contrib/Dockerfile.test, contrib/Dockerfile.test.d/cri-in-userns/docker-entrypoint.sh, contrib/Dockerfile.test.d/cri-in-userns/etc_containerd_config.toml
The `cri-in-userns` stage is for testing "CRI-in-UserNS", which should be used in conjunction with "Kubelet-in-UserNS":
https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/2033-kubelet-in-userns-aka-rootless
This feature is mostly expected to be used for `kind` and `minikube` (but not limited to them):
- https://github.com/kubernetes-sigs/kind/issues/1797
- https://github.com/kubernetes/minikube/issues/10836
Requires Rootless Docker/Podman/nerdctl with cgroup v2 delegation: https://rootlesscontaine.rs/getting-started/common/cgroup2/
Usage:
```
podman build --target cri-in-userns -t cri-in-userns -f contrib/Dockerfile.test .
podman run -it --rm --privileged cri-in-userns
```
Rootless Docker/Podman/nerdctl prepares the UserNS, so we do not need to create UserNS by …
=> Dockerfile.test: add "cri-in-userns" (aka rootless) test stage

.github/workflows/release.yml
=> gha: make release workflow work in forks

go.mod, go.sum, vendor/modules.txt
0.8.18 contains a fix for shim delete behavior, please see:
https://github.com/microsoft/hcsshim/pull/1041
There's no new vendored files as nothing from hcsshim/cmd/containerd-shim-runhcs-v1
gets imported here but for containerd releases the runhcs shim binary is built from whatever
commit is vendored into containerd.
This should resolve  #5094
We'll need to additionally backport this to the 1.5 branch
=> [Vendor] Update hcsshim to 0.8.18

pkg/cri/cri.go, runtime/restart/monitor/monitor.go, services.go
Before this change, for several of the services that `WithServices`
handles, only the grpc client is supported.
Now, for instance, one can use an `images.Store` directly instead of
only an `imagesapi.StoreClient`.
Some of the methods have been renamed to satisfy the difference between
using a grpc `<Foo>Client` vs the main interface.
I did not see a good candidate for TaskService so have left that mostly
unchanged.
=> Allow WithServices to use custom implementations

remotes/docker/pusher.go
Discovered this while using HTTP tracing via OpenTelemetry inside of
buildkitd, where the trace spans were not being reported for the
registry PUT http requests.  The spans are only reported on the Close
for the Body, after adding these Close calls, the spans are reported as
expected.
[related buildkit code](https://github.com/moby/buildkit/blob/1d0597e85a1ee56c24b11c800a185eec31758332/util/tracing/tracing.go#L130-L133)
cc @tonistiigi
=> Fix missing Body.Close() calls on push to docker remote

client.go
gRPC-Go recently added grpc.WithReturnConnectionError() which improves
the situation of #2576.
Permission errors:
```
% ./bin/ctr t ls
ctr: failed to dial "/run/containerd/containerd.sock": connection error: desc = "transport: error while dialing: dial unix /run/containerd/containerd.sock: connect: permission denied"
%
```
Non-existent sockets:
```
% ./bin/ctr -a notfound t ls
ctr: failed to dial "notfound": context deadline exceeded: connection error: desc = "transport: error while dialing: dial unix://notfound: timeout"
%
```
=> client: surface a connection error more clearly

remotes/docker/pusher.go
backport of https://github.com/containerd/containerd/pull/5712
Discovered this while using HTTP tracing via OpenTelemetry inside of
buildkitd, where the trace spans were not being reported for the
registry PUT http requests.  The spans are only reported on the Close
for the Body, after adding these Close calls, the spans are reported as
expected.
Signed-off-by: coryb <cbennett@netflix.com>
(cherry picked from commit 894b6ae39b9266411d0d4e6325235390c06fc0ab)
=> [release/1.5 backport] Fix missing Body.Close() calls on push to docker remote

remotes/docker/pusher.go
> note: This is a slightly modified version of the commit in main, because
> pusher.Commit() uses a regular http.Response, not a wrapped one.
backport of https://github.com/containerd/containerd/pull/5712
Discovered this while using HTTP tracing via OpenTelemetry inside of
buildkitd, where the trace spans were not being reported for the
registry PUT http requests.  The spans are only reported on the Close
for the Body, after adding these Close calls, the spans are reported as
expected.
Signed-off-by: coryb <cbennett@netflix.com>
(cherry picked from commit 894b6ae39b9266411d0d4e6325235390c06fc0ab)
=> [release/1.4 backport] Fix missing Body.Close() calls on push to docker remote

integration/client/restart_monitor_linux_test.go
This adds the timestamp to the final log to help debug this flaky test. See logs below
```
default:     restart_monitor_linux_test.go:92: 2021-07-13 16:21:49.450742838 +0000 UTC m=+145.976532745: status={"stopped" '\u0089' "2021-07-13 16:21:49.446496309 +0000 UTC"}
default:     restart_monitor_linux_test.go:92: 2021-07-13 16:21:50.459980678 +0000 UTC m=+146.985770567: status={"stopped" '\u0089' "2021-07-13 16:21:49.446496309 +0000 UTC"}
default:     restart_monitor_linux_test.go:92: 2021-07-13 16:21:51.467907321 +0000 UTC m=+147.993697215: status={"stopped" '\u0089' "2021-07-13 16:21:49.446496309 +0000 UTC"}
default:     restart_monitor_linux_test.go:92: 2021-07-13 16:21:52.47103632 +0000 UTC m=+148.996826201: status={"stopped" '\u0089' "2021-07-13 16:21:49.446496309 +0000 UTC"}
default: …
```
=> Add timestamp to flaky restart monitor test

runtime/v2/runc/v2/service.go
cgroupsv2.LoadManager() already performs VerifyGroupPath(), and returns an error if the path is invalid, so this check is redundant.
see https://github.com/containerd/containerd/blob/34fb8d8967595292adce04b53b12ee33499cd6b8/vendor/github.com/containerd/cgroups/v2/manager.go#L196-L200
=> runtime: runc v2: remove redundant validation

contrib/gce/configure.sh
Set systemdCgroup for cgroupv2 Kuberentes e2e tests.
Signed-off-by: Aditi Sharma <adi.sky17@gmail.com>
=> Use systemd cgroup driver for Kubernetes e2e tests with cgroupsv2

script/setup/install-gotestsum
removes golang.org/x/cryto dependency:
full diff: https://github.com/gotestyourself/gotestsum/compare/012a85e34a7ce5554057d512e55dcb54b6f2505e...1a9438079330f60c1301fdfacafbfac8763214a5
=> update gotestsum to current master

remotes/docker/resolver.go
Signed-off-by: Sebastian Hasler <sebastian.hasler@gmx.net>
(cherry picked from commit c0e2f4b5d2c28b22da552156dae5239935b6a343)
cherry-pick from #5275
=> [release/1.5] Try next mirror in case of non-404 errors, too

contrib/Dockerfile.test, script/setup/install-critools
relates to https://github.com/containerd/containerd/pull/5700
Various changes to the Dockerfile.test. See individual commits for details:
- install-critools: make sure DESTDIR exists
- Dockerfile.test: split dev stage, and optimize order
- Dockerfile.test: skip curl, gcc, git and make install
These are already installed by default in the golang image.
- Dockerfile.test: split dev stage, and optimize order
This makes the following changes:
- The containerd/config.toml, and docker-entrypoint.sh only occasionally change,
so copy them before copying the source code to allow them to be cached.
- The cri-in-userns stage does not need files from proto3, so do not copy them
- The dev environment does need the file from the proto3 stage, so copy them there.
- Change the order of stages. Our CI …
=> Refactor / optimize contrib/Dockerfile.test

remotes/docker/resolver.go
backport of https://github.com/containerd/containerd/pull/5504
fixes https://github.com/containerd/containerd/issues/5503
Allows redirects to be authorized if authorization is provided
for the redirected to host. The authorization will always go
to the redirect and never to the referrer.
=> [release/1.5 backport] Update docker resolver to authorize redirects

remotes/docker/authorizer.go
This is the equivalent of 50ad4b96c4acfde425e1fc6e7411b52658d7af92 (https://github.com/containerd/containerd/pull/5533), but modified for the release/1.4 branch. From the original commit:
> Previously, containerd uses Go's default UA "Go-http-client/1.1" while authenticating with registry.
> This commit changes it to the pattern like "containerd/v1.5.2" which is used for all other requests.
Fixes https://github.com/containerd/containerd/issues/5532 for 1.4.x
=> [release/1.4] Fix incorrect UA used for registry authentication

.github/workflows/ci.yml, script/setup/install-dev-tools
full diff: https://github.com/cpuguy83/go-md2man/compare/v2.0.0...v2.0.1
- Fix handling multiple definition descriptions
- Fix inline markup causing table cells to split
- Remove escaping tilde character (prevents tildes (`~`) from disappearing).
- Do not escape dash, underscore, and ampersand (prevents ampersands (`&`) from disappearing).
- Ignore unknown HTML tags to prevent noisy warnings
Note that this only updates the binaries we install. The vendor code also
includes go-md2man (as indirect dependency of urfave/cli). I don't think we use that
feature, so I did not add it to our go.mod
=> Update cpuguy83/go-md2man binary to v2.0.1

remotes/docker/fetcher.go
missing Close() call on fetch from docker remote under certain failed condition
=> remotes/docker/fetcher.go: Fix missing Close() on fetch from docker remote

remotes/docker/pusher.go
=> remotes/docker/pusher.go: Fix missing Close() on push to docker remote

remotes/docker/fetcher.go, remotes/docker/pusher.go
Backport of https://github.com/containerd/containerd/pull/5769 and https://github.com/containerd/containerd/pull/5770
=> [release/1.5 backport] add missing body.Close() in docker/fetcher and docker/pusher

remotes/docker/fetcher.go, remotes/docker/pusher.go
Backport of https://github.com/containerd/containerd/pull/5769 and https://github.com/containerd/containerd/pull/5770
Second commit did not apply cleanly, and had a minor conflict in the `if resp.StatusCode != http.StatusNotFound` block, because commit 2de55060ee151f7b5301abc8d7d3c0062101d07e is not in this branch.
=> [release/1.4 backport] add missing body.Close() in docker/fetcher and docker/pusher

snapshots/devmapper/snapshotter.go
backport of https://github.com/containerd/containerd/pull/5655
- View was somehow logging itself as "prepare"
- Cleanup should have its debug log as like other exported methods
=> [release/1.5 backport] snapshot/devmapper: log exported methods correctly

snapshots/devmapper/snapshotter.go
backport of https://github.com/containerd/containerd/pull/5655
- View was somehow logging itself as "prepare"
- Cleanup should have its debug log as like other exported methods
=> [release/1.4 backport] snapshot/devmapper: log exported methods correctly

contrib/fuzz/docker_fuzzer.go, contrib/fuzz/oss_fuzz_build.sh
Adds a fuzzer that targets the `request` and `open` APIs in `remotes/docker.Fetch`.
This fuzzer can run continuously through OSS-fuzz, and I will add it on the OSS-fuzz side once this PR has been merged.
=> Add docker.Fetch fuzzer

integration/client/container_test.go
The test is failing on
https://github.com/containerd/containerd/runs/3129202049#step:10:43.
I'd like to know whether the order of the array is the cause, or
the result is completely off.
=> integration: log all processes to investigate the test failure

metrics/cgroups/v1/cgroups.go, metrics/cgroups/v1/metrics.go, metrics/cgroups/v2/cgroups.go, metrics/cgroups/v2/metrics.go, runtime/monitor.go, services/tasks/local.go
This change extends `TaskMonitor` interface to provide optional map of labels to be added to task's metrics namespace.
Shim runtime now adds `runtime` label to be able to differentiate containers by runtime class on dashboards.
Output example: https://gist.github.com/mxpv/171ebdc312499493df9833899433ccda
note: this doesn't handle daemon restarts, for kube that's not the case (as we usually drain node before doing anything), I'll follow up later if this something we want to have as well.
=> Add runtime label to metrics

Makefile
Several fixes in Makefile regarding passing of build tags to the go toolchain.
=> Makefile: fix passing build tags

snapshots/devmapper/README.md, snapshots/devmapper/blkdiscard/blkdiscard.go, snapshots/devmapper/config.go, snapshots/devmapper/dmsetup/dmsetup.go, snapshots/devmapper/dmsetup/dmsetup_test.go, snapshots/devmapper/pool_device.go, snapshots/devmapper/pool_device_test.go
dmsetup does not discard blocks when removing a thin device. The unused blocks
are reused by the thin-pool, but will remain allocated in the underlying
device indefinitely. For loop device backed thin-pools, this results in
"lost" disk space in the underlying file system as the blocks remain allocated
in the loop device's backing file.
This change adds an option, discard_blocks, to the devmapper snapshotter which
causes the snapshotter to issue blkdiscard ioctls on the thin device before
removal. With this option enabled, loop device setups will see disk space
return to the underlying filesystem immediately on exiting a container.
Fixes #5691
Signed-off-by: Kern Walster <walster@amazon.com>
=> Discard blocks when removing a thin device

script/setup/install-gotestsum
Same as previous commit, but a release was tagged (https://github.com/gotestyourself/gotestsum/issues/206);
https://github.com/gotestyourself/gotestsum/compare/1a9438079330f60c1301fdfacafbfac8763214a5...v1.7.0
=> update gotestsum to v1.7.0

integration/images/volume-copy-up/Dockerfile, integration/images/volume-copy-up/Dockerfile_windows, integration/images/volume-copy-up/Makefile
For Windows, the container image's OS version must closely match the host's OS version. For this reason, we need to add the ``--os-version`` annotation in image manifest lists, so the Windows nodes can pull the appropriate image from the list.
Previously, the docker manifest CLI did not have the capability to set the ``--os-version``, it, but it has been introduced in docker 20.10.0.
We're also adding ``busybox.exe`` in the image, so we can run Linux commands inside the container, so the tests will be simpler.
When building Windows images, a docker buildx builder needs to be created and used. When building Windows images with ``docker buildx``, the flag ``--output=type=registry`` is required, otherwise it cannot be referenced on a Linux node.
The ``volume-copy-up`` image is used in the …
=> integration: Windows volume-copy-up images

runtime/v2/shim/util.go
under the efforts of https://github.com/containerd/containerd/pull/3206, https://github.com/containerd/cri/pull/924, https://github.com/containerd/cri/pull/884, containerd works fine in many cases. However, containerd still cannot to recover if there exist some shim which hang forever(start and delete), the timeout here takes no effect https://github.com/containerd/containerd/blob/main/runtime/v2/shim.go#L143   
Signed-off-by: jerryzhuang <zhuangqhc@gmail.com>
=> respect context timeout in shim binary call

snapshots/overlay/overlay.go, snapshots/overlay/plugin/plugin.go
Overlayfs snapshotter provides a generic snapshotting functionality based on overlayfs but it doesn't expose the location of each snapshot's `upperdir` where the changeset between that snapshot and its parent is stored.
From the snapshotter users perspective, `upperdir` can be used for performing overlayfs-specific optimization. For example, this enables to compute diff between a snapshot and its parent faster than comparing the entire filesystem objects between them like done by `walking` differ.
This PR adds as an optional label `containerd.io/snapshot/overlay.upperdir` and this stores the location of `upperdir` that contains the changeset between the labelled snapshot and its parent. This is defined as an **optional** label because this is an implementation detail of overlayfs …
=> overlay: expose upperdir location of each snapshot via an optional label

script/setup/install-protobuf
The protobuf repository is under the protocolbuffers org
NOTE: The Github redirect which was being used before seems to have broke
=> Update protobuf install to use correct repository

BUILDING.md
The protobuf repo has moved from github.com/google/protobuf -> github.com/protocolbuffers/protobuf. This updates the scripts/docs to reference this new repo.
=> Updates the location of protobuf downloads

platforms/database.go
I noticed these were added in golang;
- GOOS iOS was added in https://go-review.googlesource.com/c/go/+/254740, and part of go1.16beta1
- GOARCH loong64 was added in https://go-review.googlesource.com/c/go/+/333909, and currently only in master
=> platforms: add "ios" as known OS, "loong64" as known ARCH

docs/ops.md, labels/labels.go, metadata/buckets.go, metadata/buckets_test.go, metadata/content.go, metadata/images.go
This changed based on feedback on the PR to use a different method. I kept the previous description for clarity below.
This PR adds the ability to tag namespaces with a special label, `containerd.io/namespace/sharable` that indicates that images in this namespace are shareable with other namespaces. 
The goal is to be able to have namespace isolation while being able to share some common content across all namespaces.
---
This PR adds a 'shared' namespace setting that enables content to be shared from a single, configured namespace when content_sharing_policy is set to isolated. It does this by looking for content first in the calling namespace and then, if configured, in the 'shared' namespace.
The config looks like:
```toml
[plugins.bolt]
content_sharing_policy = "isolated" …
```
=> Add a sharedNamespace label

.github/workflows/ci.yml, Makefile, api/go.mod, script/verify-go-modules.sh
Ensure that the root go.mod and the module specific go.mod have the
same `require` and `replace` directives for different dependencies.
=> Script to check if entries in go.mod files are in sync

.github/workflows/release.yml
Unlike [containerd/cri](https://github.com/containerd/cri) releases (https://storage.googleapis.com/cri-containerd-release), current release workflow doesn't publish binaries without CNI.
Signed-off-by: Sunghoon Kang <hoon@linecorp.com>
=> Update release workflow to upload binary without CNI

releases/v1.5.5.toml, version/version.go
See generated release notes https://gist.github.com/dmcgowan/eb5be5217bf35696e07441c8923a1e8b
=> [release/1.5] Prepare release notes for v1.5.5

.github/workflows/ci.yml
The current latest version of CRIU is 3.15 and soon will be released 3.16. If CRIU is installed from PPA it would always test with the latest released version.
=> ci: install criu from PPA

go.mod, go.sum, integration/client/go.sum, vendor/github.com/imdario/mergo/.travis.yml, vendor/github.com/imdario/mergo/README.md, vendor/github.com/imdario/mergo/merge.go, vendor/modules.txt
This should fix the issue in #5808.  If it can be reasonably backported, that'd be greatly appreciated.
=> mergo: Upgrade to 0.3.12 to fix panic

contrib/fuzz/container_fuzzer.go, contrib/fuzz/oss_fuzz_build.sh
Adds a fuzzer that:
1. Creates a client
2. Imports a number of tar archives
3. Creates a number of containers
4. Unpacks some of the images
This fuzzer needs some of the containerd binaries, so we build these statically in the oss-fuzz build file and move them to `$OUT/containerd-binaries` which the fuzzer has access to when running.
The fuzzer needs a socket, and this socket occasionally becomes unavailable. For this reason the fuzzer includes the `deleteSocket()` helper which deletes the socket which allows for the creation of a new one during next iteration.
It is unclear at this point whether this fuzzer should stop and kill the daemon during each iteration. This fuzzers perfomance is much different depending on whether it is running 1 hour or 100 hours, and to consider this it would …
=> Fuzzing: Add container fuzzer

go.mod, go.sum, integration/client/go.sum, vendor/github.com/imdario/mergo/.travis.yml, vendor/github.com/imdario/mergo/README.md, vendor/github.com/imdario/mergo/merge.go, vendor/modules.txt
Signed-off-by: Jayme Howard <g.prime@gmail.com>
Run `go mod tidy`
Signed-off-by: Jayme Howard <g.prime@gmail.com>
Follow correct procedure by running `make vendor`
Signed-off-by: Jayme Howard <g.prime@gmail.com>
(cherry picked from commit ce437864b2e7e2f9b94e02ba564e010a5ea2248d)
=> [release/1.5] cherry-pick: mergo: Upgrade to 0.3.12 to fix panic

contrib/fuzz/container_fuzzer.go
The fuzzer runs fine, but OSS-fuzz's CI includes a test that uses a different `/out` which means that the binaries that are there will not be available and the panics will cause the CI to fail. This PR removes the panics so there will not be complications with the CI.
This PR will allow https://github.com/google/oss-fuzz/pull/6145 to become green.
=> Fuzzing: Remove panics of container_fuzzer

platforms/platforms.go, platforms/platforms_test.go
relates to https://github.com/moby/moby/pull/42623/files#r669000608
path.Join() also skips empty components, making it the equivalent of this function.
=> platforms: Format(): use path.Join() instead of joinNotEmpty()

contrib/fuzz/container_fuzzer.go, contrib/fuzz/oss_fuzz_build.sh
Currently the `container_fuzzer.go` breaks when creating `/run/containerd-test` in `init()`.
The error does not reproduce locally.
This PR adds two fixes for this:
1. Remove the `panic` to disable notifications about this breakage.
2. Use `/tmp/containerd-test` instead of `/run/containerd-test`. 
=> Fuzzing: Fix for OSS-fuzz issue 36825

defaults/defaults_darwin.go, mount/temp_unix.go, mount/temp_unsupported.go
A couple of minor fixes that prevent containerd from launching on darwin:
```
containerd: mkdir /run: read-only file system
```
```
unmounting temp mounts  error="not implemented on darwin/amd64"
```
```
containerd: failed to get listener for debug endpoint: mkdir /run: read-only file system
```
=> Change default directories on Darwin

.github/workflows/ci.yml, .github/workflows/nightly.yml, .github/workflows/release.yml, .zuul/playbooks/containerd-build/integration-test.yaml, .zuul/playbooks/containerd-build/run.yaml, .zuul/playbooks/containerd-build/unit-test.yaml, Vagrantfile, contrib/Dockerfile.test, script/setup/prepare_env_windows.ps1
go1.16.7 (released 2021-08-05) includes a security fix to the net/http/httputil
package, as well as bug fixes to the compiler, the linker, the runtime, the go
command, and the net/http package. See the Go 1.16.7 milestone on the issue
https://github.com/golang/go/issues?q=milestone%3AGo1.16.7+label%3ACherryPickApproved
=> Update Go to 1.16.7

.github/workflows/ci.yml
For some reason the Linux CI runs end up using go 1.15.14 instead of 1.16.6 like the Windows runs, or any of the other CI steps. Not sure if this is due to the linter installing it's own version of go or something else.
Remedy this by running the `actions/setup-go@v2` action for the Linters and setting `skip-go-installation` to true for golangci-lint
=> Fix Linux CI Linter using Go 1.15.14

.github/workflows/ci.yml, .github/workflows/nightly.yml, .github/workflows/release.yml, .travis.yml, .zuul/playbooks/containerd-build/run.yaml, Vagrantfile, contrib/Dockerfile.test
go1.15.15 (released 2021-08-05) includes a security fix to the net/http/httputil
package, as well as bug fixes to the compiler, the runtime, the go command, and
the net/http package. See the Go 1.15.15 milestone on the issue tracker for details:
https://github.com/golang/go/issues?q=milestone%3AGo1.15.15+label%3ACherryPickApproved
=> [release/1.4] Update Go to 1.15.15

cmd/containerd/builtins.go, events/plugin/plugin.go, metrics/cgroups/cgroups.go, pkg/cri/cri.go, plugin/context.go, plugin/plugin.go, runtime/restart/monitor/monitor.go, runtime/v1/linux/runtime.go, runtime/v2/manager.go, services/containers/local.go, services/content/store.go, services/events/service.go, services/namespaces/local.go, services/server/server.go, services/snapshots/snapshotters.go, services/tasks/local.go, services/tasks/local_freebsd.go, services/tasks/local_unix.go
This updates plugins to make use of an events plugin rather than use `Events` from the `InitContext`. The second step would be to remove the `Events` field. I didn't do it in this PR since there may be a possibility of external builds of containerd adding plugins which use of this field. It likely does not take waiting for 2.0 to remove, but we can discuss or try that in a follow-up.
=> Move plugin context events into separate plugin

.github/workflows/ci.yml, .github/workflows/nightly.yml, .github/workflows/release.yml, .zuul/playbooks/containerd-build/integration-test.yaml, .zuul/playbooks/containerd-build/run.yaml, .zuul/playbooks/containerd-build/unit-test.yaml, Vagrantfile, contrib/Dockerfile.test
backport of https://github.com/containerd/containerd/pull/5842
go1.16.7 (released 2021-08-05) includes a security fix to the net/http/httputil
package, as well as bug fixes to the compiler, the linker, the runtime, the go
command, and the net/http package. See the Go 1.16.7 milestone on the issue
https://github.com/golang/go/issues?q=milestone%3AGo1.16.7+label%3ACherryPickApproved
(cherry picked from commit 42a28ad2ca7faecfa3e2024952781136211c1fbf)
=> [release/1.5 backport] Update Go to 1.16.7

BUILDING.md
We can disable most of snapshotters, but they are not documented.
=> docs: list all snapshotter-related build flags

script/test/cri-integration.sh
The cri-integration.sh script sets errexit option. This does not
work properly on Bash in Windows, espectially when the script is
piped to something else ( tee in this case ). In this particular
case, the problem arises from the fact that if the script exits
prematurely, it will not get a chance to call test_teardown and
thus clean the remaining containerd process, thus the whole
command will hang indefinetly.
Adding a simple trap on EXIT to call test_teardown will easily
fix this.
Signed-off-by: Adelina Tuvenie <atuvenie@cloudbasesolutions.com>
=> [Scripts] Add trap to cri-integration test script

BUILDING.md, docs/RUNC.md
See the discussion on https://github.com/containerd/containerd/issues/5780
the "build in docker" section also needs some rewriting (probably should use the contrib/Dockerfile.test), I can have a look at that in a follow-up
=> BUILDING.md: remove some bits about building runc

README.md
The automated scan doesn't work correctly and it would give
contributors a doubt regarding containerd's license.
=> docs: remove FOSSA's badge

Makefile
Somehow messed up the TMPDIR expansion
=> Fix bad `make protos` failure

content/local/locks.go, content/local/locks_test.go
The current timestamp is probably included in production logs, but
won't be in testing environments such as GitHub Actions.
=> content: return the error with its timestamp

README.md, RELEASES.md, archive/tar.go, archive/tar_opts_windows.go
containerd and opencontainers/image-spec have renamed its main branch
from "master" to "main"
=> docs: rename main to master

cmd/ctr/commands/run/run_unix.go, oci/spec_opts_nonlinux.go
This allows the cpu shares to be modified via ctr.
=> add cpu-shares to ctr

contrib/fuzz/container_fuzzer.go, contrib/fuzz/oss_fuzz_build.sh
1. Adds another version of the container_fuzzer that downloads the containerd binaries when starting a new fuzz run, instead of using the binaries that were built by `make`.
2. Moves the initialization out of `init()` since it now does not apply to all fuzzers.
The current approach to managing the containerd binaries works fine locally in the OSS-fuzz environment, but when running continuously by OSS-fuzz, then the performance is unsatisfactory. It would be great to get this version of the fuzzer up and running to observe it when running continuously.
=> Fuzzing: Add experimental version of container fuzzer

runtime/runtime.go, runtime/task.go, runtime/v1/linux/runtime.go, runtime/v1/linux/task.go, runtime/v2/binary.go, runtime/v2/manager.go, runtime/v2/shim.go, services/tasks/local.go
In current shim v2 implementation there are 2 routines for shim deletion - `Task.Delete` and `TaskManager.Delete`.
Most of the cleanup logic is happening in `Task`, however there is also need to delete self from Manager’s task list and do proper cleanup after.
This requirements adds a lot of boilerplate logic and unnecessary relation between task, bundle, and manager.
This PR aims to simplify `shim` object and basically turns it into a stateless entity, that just translates API calls to the underlying shim. Instead of calling Task’s delete, we call TaskManager’s Delete (so it’s not useless anymore), which in turn calls Task’s delete. This makes cleanup logic more linear and with less dependencies between shim and the manager. All existing task cleanup logic preserved.
Shim before: …
=> Cleanup v2 shim

pkg/cri/server/helpers_linux.go, pkg/cri/server/sandbox_run_linux.go, pkg/cri/server/sandbox_run_linux_test.go
Fixes https://github.com/containerd/containerd/issues/5877
According to https://man7.org/linux/man-pages/man5/resolv.conf.5.html,
```
In glibc 2.25 and earlier, the search list is limited to
six domains with a total of 256 characters.  Since glibc
2.26, the search list is unlimited.
```
This PR removes obsolete limitation to the DNS search paths, and allows expanded DNS configuration.
=> Allow expanded DNS configuration

.github/workflows/ci.yml, .github/workflows/release.yml, .zuul/playbooks/containerd-build/integration-test.yaml, script/setup/install-seccomp
backport of:
- https://github.com/containerd/containerd/pull/5445 (to get a conflict-free cherry-pick) update seccomp version
- https://github.com/containerd/containerd/pull/5558 Install apparmor parser for arm64 environment
resolves https://github.com/containerd/containerd/issues/5444 for the 1.5 branch
=> [release/1.5 backport] install apparmor parser for arm64, and update seccomp to 2.5.1

contrib/gce/configure.sh
Adding a Kubernetes node e2e job with systemd cgroup driver,  Need to enable systemd cgroup driver via env variable
https://github.com/kubernetes/test-infra/pull/23253
Signed-off-by: Aditi Sharma <adi.sky17@gmail.com>
=> Make Cgroup driver configurable in gce configure script

cmd/ctr/commands/run/run_unix.go
Set the hostname environment var when using host networking via ctr
=> [ctr] add HOSTNAME env for host network

integration/client/client_unix_test.go, integration/client/container_linux_test.go
Cherry-pick PR #5625 from main to `release/1.5` to fix CI
--------
`mirror.gcr.io/library/busybox:1.32.0` is unavailable.
```console
$ curl -s https://mirror.gcr.io//v2/library/busybox/tags/list | jq '.tags'
[
"1.26.2",
"1.27.2",
"1.28",
"1.29",
"1.29.2",
"1.29.3",
"1.30",
"1.30.1",
"1.31",
"1.31.0",
"1.31.1",
"1.32",
"latest"
]
```
`mirror.gcr.io/library/alpine:3.13` is unavailable.
```console
$ curl -s https://mirror.gcr.io//v2/library/alpine/tags/list | jq '.tags'
[
"20200428",
"3",
"3.10",
"3.11",
"3.12",
"3.12.0",
"3.12.1",
"3.13.5",
"3.3",
"3.4",
"3.6",
"3.7",
"3.8",
"3.9",
"latest"
]
```
Signed-off-by: Kohei Tokunaga <ktokunaga.mail@gmail.com>
(cherry picked from commit cd33c007cecdee2c8e5333190cad1bbce4ade13d)
=> [release/1.5] cherry-pick: CI: Switch to available latest images

integration/client/container_test.go
task.Pids returns the task's processes, but the order is not guaranteed.
=> integration: fix TestContainerPids

pkg/cri/server/helpers_linux.go, pkg/cri/server/sandbox_run_linux.go, pkg/cri/server/sandbox_run_linux_test.go
Cherry pick of #5878 on release/1.5.
#5878: Allow expanded DNS configuration
=> [release/1.5 backport] Allow expanded DNS configuration

.github/workflows/ci.yml, .github/workflows/nightly.yml, .github/workflows/release.yml, .zuul/playbooks/containerd-build/integration-test.yaml, .zuul/playbooks/containerd-build/run.yaml, .zuul/playbooks/containerd-build/unit-test.yaml, Vagrantfile, contrib/Dockerfile.test
Go 1.17 has been released.
Release Notes: https://golang.org/doc/go1.17
Has small performance gains and binary size improvements; new architecture support for arm64 on Windows (https://twitter.com/kelseyhightower/status/1427400588900241410)
=> Update to Go 1.17

.github/workflows/ci.yml, .golangci.yml, pkg/cri/server/sandbox_run.go, pkg/os/os_windows.go, script/setup/install-dev-tools, snapshots/testsuite/testsuite.go
golint has been deprecated and replaced by revive since v1.41.0.
=> script: update golangci-lint from v1.38.0 and v1.36.0 to v1.42.0

pkg/cri/annotations/annotations.go, pkg/cri/server/container_create_windows.go, pkg/cri/server/container_create_windows_test.go, pkg/cri/server/restart.go, pkg/cri/server/sandbox_run.go, pkg/cri/server/sandbox_run_windows.go, pkg/cri/server/sandbox_run_windows_test.go, pkg/cri/server/sandbox_status.go
This PR adds support for Windows HostProcess containers introduced in HCSShim https://github.com/microsoft/hcsshim/pull/903 by @dcantah and skips CNI calls for HostProcess Containers as they are not used, allowing pods to schedule before CNI is Ready and therefore allowing CNI agents to be scheduled in HostProcess Pods
=> Add Windows HostProcess Support

pkg/cri/opts/container.go
Exclude the `security.selinux` xattr when copying content from layer
storage for image volumes. This allows for the already correct label
at the target location to be applied to the copied content, thus
enabling containers to write to volumes that they implicitly expect to be
able to write to.
- Fixes containerd/containerd#5090
- See rancher/rke2#690
Signed-off-by: Jacob Blain Christen <jacob@rancher.com>
=> cri: filter selinux xattr for image volumes

platforms/defaults.go, platforms/defaults_unix.go, platforms/defaults_unix_test.go, platforms/defaults_windows.go, platforms/defaults_windows_test.go
The Windows Default matcher also checks the the OS Version prefix, however, the platforms.DefaultSpec does not include it, which means that it won't match the matcher.
This solves the issue by adding the OS Version to the DefaultSpec.
=> windows: The DefaultSpec platform should match the Default matcher

oci/spec_opts_linux.go, oci/spec_opts_linux_test.go
The bug prevents all major/minor combinations that exists on a directory to be enabled, only the last one on the list is enabled. This problem exists on main, 1.5 branches and the Issue #4847 is also bring backported to 1.4.
Another suggestion is including the line dev := dev that will create a new copy of the dev variable inside the loop as suggested by @cpuguy83.
=> Fix dir support for devices

oci/spec_opts_unix.go, pkg/cri/config/config.go, pkg/cri/opts/spec_linux.go, pkg/cri/server/container_create_linux.go, pkg/cri/server/container_create_linux_test.go
CRI container runtimes mount devices (set via kubernetes device plugins)
to containers by taking the host user/group IDs (uid/gid) to the
corresponding container device.
This triggers a problem when trying to run those containers with
non-zero (root uid/gid = 0) uid/gid set via runAsUser/runAsGroup:
the container process has no permission to use the device even when
its gid is permissive to non-root users because the container user
does not belong to that group.
It is possible to workaround the problem by manually adding the device
gid(s) to supplementalGroups. However, this is also problematic because
the device gid(s) may have different values depending on the workers'
distro/version in the cluster.
This patch suggests to take RunAsUser/RunAsGroup set via SecurityContext
as the device …
=> cri: Devices ownership from SecurityContext

cmd/ctr/commands/tasks/exec.go
It seems like the cwd flag isn't used anywhere for `ctr tasks exec`. This change
just sets the cwd field on the spec for the execed process if a new one was
asked for, otherwise it will continue using whatever was on the containers spec.
=> Fix cwd flag for `ctr tasks exec`

Makefile.linux
Since go 1.16, -buildmode=pie is supported on riscv [1],
so let's remove the platform from the exclusion list.
This reverts commit e34bf08e5891bb805aba7b80a35d4267721eaa0e.
[1] https://golang.org/doc/go1.16#riscv
=> Makefile.linux: build on RISC-V with PIE

go.mod, go.sum, integration/client/go.mod, integration/client/go.sum, vendor/github.com/Microsoft/hcsshim/errors.go, vendor/github.com/Microsoft/hcsshim/hcn/hcn.go, vendor/github.com/Microsoft/hcsshim/hcn/hcnsupport.go, vendor/github.com/Microsoft/hcsshim/hnsendpoint.go, vendor/github.com/Microsoft/hcsshim/internal/hcs/errors.go, vendor/github.com/Microsoft/hcsshim/internal/hns/hnsendpoint.go, vendor/modules.txt
This version brings in some bug fixes to layer handling. The actual fix isn't
present in the diff as it's not used here, but the Windows shim is built from
the tag present in go.mod, so the fix will be in the Windows shim on a new release
of Containerd if this tag is in.
=> go.mod: Update hcsshim to v0.8.21

go.mod, go.sum, integration/client/go.mod, integration/client/go.sum, vendor/github.com/Microsoft/hcsshim/errors.go, vendor/github.com/Microsoft/hcsshim/hcn/hcn.go, vendor/github.com/Microsoft/hcsshim/hcn/hcnsupport.go, vendor/github.com/Microsoft/hcsshim/hnsendpoint.go, vendor/github.com/Microsoft/hcsshim/internal/hcs/errors.go, vendor/github.com/Microsoft/hcsshim/internal/hns/hnsendpoint.go, vendor/modules.txt
This version brings in some bug fixes to layer handling. The actual fix isn't
present in the diff as it's not used here, but the Windows shim is built from
the tag present in go.mod, so the fix will be in the Windows shim on a new release
of Containerd if this tag is in.
=> [release/1.5] Backport go.mod: Update hcsshim to v0.8.21

.github/workflows/windows-periodic.yml
Some extra steps were added for WS2022 in accordance with
the published image on Azure:
- Install Container Feature & reboot VM
- Create NAT network
Temporarily we skip critest steps for WS2022 until all test images
are updated in that project.
Signed-off-by: Adelina Tuvenie <atuvenie@cloudbasesolutions.com>
=> Add WS2022 support in Windows Periodic tests

archive/tar.go
This seems to ignore the error message log of `WriteDiff`
=> archive: Add WriteDiff error logs

defaults/defaults_darwin.go, platforms/defaults_darwin.go, runtime/v2/shim/util_unix.go, services/tasks/local_darwin.go, services/tasks/local_unix.go
(splitting from the original patchset: https://github.com/containerd/containerd/pull/4526)
This PR proposes the runtime support on darwin platform.  containerd can run directly on darwin (i.e., without a Linux VM) using [runu](https://github.com/ukontainer/runu) runtime with the external shim (`containerd-shim-runu-v1`), though it's not limited to.
There are no integration tests in this PR: this can be followed up by subsequent PRs.
=> darwin: runtime support

pkg/cri/server/image_pull.go
The CRI-plugin subscribes the image event on k8s.io namespace. By
default, the image event is created by CRI-API. However, the image can
be downloaded by containerd API on k8s.io with the customized labels.
The CRI-plugin should use patch update for `io.cri-containerd.image`
label in this case.
Fixes: #5900
=> cri: patch update image labels

docs/cri/config.md, pkg/cri/config/config.go, pkg/cri/server/sandbox_run.go, pkg/cri/server/sandbox_run_test.go
This fixes the TODO of this function and also expands on how the primary pod ip
is selected. This change allows the operator to prefer ipv4, ipv6, or retain the
ordering provided by the return results of the CNI plugins.
This makes it much more flexible for ops to configure containerd and how IPs are
set on the pod.
=> add ip_pref CNI options for primary pod ip

content/helpers.go, content/helpers_test.go
Also fixes the incorrect unit test which was no actually copying anything because of its reuse of a fully read reader
=> Fix content copy to not ignore unexpected EOF

go.mod, go.sum, integration/client/go.sum, vendor/github.com/containerd/continuity/AUTHORS, vendor/github.com/containerd/continuity/README.md, vendor/github.com/containerd/continuity/fs/copy_darwin.go, vendor/github.com/containerd/continuity/fs/copy_openbsdsolaris.go, vendor/github.com/containerd/continuity/fs/du_unix.go, vendor/github.com/containerd/continuity/fs/hardlink_unix.go, vendor/github.com/containerd/continuity/fs/stat_darwinbsd.go, vendor/github.com/containerd/continuity/go.mod, vendor/github.com/containerd/continuity/go.sum, vendor/github.com/containerd/continuity/manifest.go, vendor/github.com/containerd/continuity/testutil/loopback/loopback_linux.go, vendor/modules.txt
This PR pulls to update continuity update for darwin support.
https://github.com/containerd/continuity/pull/186
(also related to #4526)
=> vendor: update continuity for darwin support

pkg/cri/server/service.go, plugin/plugin.go, runtime/v2/shim/shim.go, services/server/server.go
Refactor shim v2 to load and register plugins. Update init shim interface to not require task service implementation on returned service, but register as plugin if it is.
=> Add support for shim plugins

snapshots/devmapper/config.go, snapshots/devmapper/config_test.go, snapshots/devmapper/snapshotter.go, snapshots/devmapper/snapshotter_test.go
ext4 file system was supported before. This adds support for xfs as
well. containerd config file can have fs_type as an additional option
with possible values as "xfs" and "ext4" for now. In future other
fstype support can be added.
Issue: https://github.com/containerd/containerd/issues/5665
Notes: Initial draft of this PR was based on reading file system type from device and using that for mkfs and other related code. Due to concerns of overhead and inconsistency, switched the design to use labels instead. A new file system type label is introduced that is passed along. If a snapshot has no parents, then file system type passed in config or default in case no type is found. For child snapshots, file system type is inherited from parents. …
=> add xfs support to devicemapper snapshotter

integration/client/client_unix_test.go
`mirror.gcr.io/library/busybox:1.32` is unavailable.
```console
$ curl -s https://mirror.gcr.io//v2/library/busybox/tags/list | jq '.tags'
[
"1-musl",
"1.26.2",
"1.27.2",
"1.28",
"1.29",
"1.29.2",
"1.29.3",
"1.30",
"1.30.1",
"1.31",
"1.31.0",
"1.31.1",
"1.32.0",
"1.33",
"latest",
"stable"
]
```
and latest is the same as 1.33
```
tag: [
"1.33",
"latest",
"stable"
],
```
Signed-off-by: wllenyj <wllenyj@linux.alibaba.com>
=> CI: Switch to available latest images

contrib/seccomp/seccomp_default.go
clone3 is explicitly requested to give ENOSYS instead of the default EPERM, when CAP_SYS_ADMIN is unset.
See moby/moby#42681 (thanks to @berrange).
Without this commit, rawhide image does not work:
```console
$ sudo ctr run --rm --net-host --seccomp registry.fedoraproject.org/fedora:rawhide foo /usr/bin/curl google.com
curl: (6) getaddrinfo() thread failed to start
```
=> seccomp: support "clone3" (return ENOSYS unless SYS_ADMIN is granted)

pkg/cri/io/helpers_windows.go, task.go
After containerd restarts, it will try to recover its sandboxes, containers, and images. If it detects a task in the Created or
Stopped state, it will be removed. This will cause the containerd process it hang on Windows on the t.io.Wait() call.
Calling t.io.Close() beforehand will solve this issue.
Additionally, the same issue occurs when trying to stopp a sandbox after containerd restarts. This will solve that case as well.
Fixes: https://github.com/containerd/containerd/issues/5621
=> task delete: Closes task IO before waiting

.github/workflows/ci.yml, .github/workflows/nightly.yml, .github/workflows/release.yml, .zuul/playbooks/containerd-build/integration-test.yaml, .zuul/playbooks/containerd-build/run.yaml, .zuul/playbooks/containerd-build/unit-test.yaml, Vagrantfile, contrib/Dockerfile.test
This includes additional fixes for CVE-2021-39293.
go1.16.8 (released 2021-09-09) includes a security fix to the archive/zip package,
as well as bug fixes to the archive/zip, go/internal/gccgoimporter, html/template,
net/http, and runtime/pprof packages. See the Go 1.16.8 milestone on the issue
https://github.com/golang/go/issues?q=milestone%3AGo1.16.8+label%3ACherryPickApproved
=> [release/1.5] update Go to 1.16.8

cmd/containerd/command/main.go, cmd/containerd/command/main_unix.go, cmd/containerd/command/main_windows.go
Some cases can cause the server initialization to block (namely running
a 2nd containerd instance by accident against the same root dir). In
this case there is no way to quit the daemon except with `kill -9`.
This changes context things so that server init is done in a goroutine
and we wait on a channel for it to be ready while we also wait for a
ctx.Done(), which will be cancelled if there is a termination signal.
Closes #5963
=> Make sure exit signals trigger an exit during init

contrib/seccomp/seccomp_default.go
Cherry-pick #5982 (clean)
- - -
clone3 is explicitly requested to give ENOSYS instead of the default EPERM, when CAP_SYS_ADMIN is unset.
See moby/moby PR 42681 (thanks to berrange).
Without this commit, rawhide image does not work:
```console
$ sudo ctr run --rm --net-host --seccomp registry.fedoraproject.org/fedora:rawhide foo /usr/bin/curl google.com
curl: (6) getaddrinfo() thread failed to start
```
=> [release/1.5] seccomp: support "clone3" (return ENOSYS unless SYS_ADMIN is granted)

contrib/seccomp/seccomp_default.go
Cherry-pick #5982 (clean)
- - -
clone3 is explicitly requested to give ENOSYS instead of the default EPERM, when CAP_SYS_ADMIN is unset.
See moby/moby PR 42681 (thanks to berrange).
Without this commit, rawhide image does not work:
```console
$ sudo ctr run --rm --net-host --seccomp registry.fedoraproject.org/fedora:rawhide foo /usr/bin/curl google.com
curl: (6) getaddrinfo() thread failed to start
```
=> [release/1.4] seccomp: support "clone3" (return ENOSYS unless SYS_ADMIN is granted)

cmd/ctr/commands/run/run.go, cmd/ctr/commands/run/run_unix.go, cmd/ctr/commands/run/run_windows.go, container_opts.go, pkg/cri/server/container_create.go, pkg/cri/server/helpers.go, pkg/cri/server/helpers_test.go, pkg/cri/server/sandbox_run.go
Cherry pick #6012 into `release/1.5`
(cherry picked from commit f40df3d72ba85700c737aca2cb21212d8f0caaed)
=> [release/1.5] cherry-pick: Enable image config labels in ctr and CRI container creation

pkg/cri/server/container_create_linux.go
Cherry-pick PR #5939 from main to release/1.5
=> [release/1.5] cherry-pick: cri: add devices for privileged container

go.mod, go.sum, integration/client/go.sum, vendor/github.com/containerd/console/console_windows.go, vendor/github.com/containerd/console/console_zos.go, vendor/github.com/containerd/console/go.mod, vendor/github.com/containerd/console/go.sum, vendor/github.com/containerd/console/tc_unix.go, vendor/github.com/containerd/console/tc_zos.go, vendor/modules.txt
bump console version to v1.0.3 that remove pkg/errors from their vendoring
xref: https://github.com/containerd/console/issues/56
=> bump console version to v1.0.3 that remove pkg/errors 

cmd/ctr/commands/namespaces/namespaces.go
Fixed a typo in `ctr namespaces create --help`.
Added description for clearing a label in `ctr namespaces label --help`.
Signed-off-by: Kaijie Chen <chen@kaijie.org>
=> ctr namespaces: improve usage string

cmd/ctr/commands/images/import.go, import.go
Currently, import's `WithDigestRef` always creates digest image for all manifests
in an index even if some of them are named in the image tarball (by `RepoTag` of
manifest.json and annotations in index.json, etc).
However, there can be client tools that want to avoid duplicated digest images
for named images.
This commit addresses such requirements.
This should be needed to address the issue of duplicated images in nerdctl (https://github.com/containerd/nerdctl/issues/177, https://github.com/containerd/nerdctl/pull/357)
cc: @AkihiroSuda @fahedouch
=> import: Add option to prevent duplicated digest image

archive/tar.go, archive/tar_unix.go
On FreeBSD + zfs, stat call seem to return garbage in RDev for regular
files & folders. The value returned is large enough not to fit into
`Devmajor` & `Devminor` fields of the tar header. Fortunately, these
fields are required just for special devices.
This change
* adds a check into `setHeaderForSpecialDevice` that the
input header represents a special device. If it's not the case, we
don't set the Devmajor & Devminor fields.
* fixes the nil check on `getxattr`: it never returns nils, but rather
an empty slice instead
=>  FreeBSD: fix tar headers & the nil check on getxattr 

process.go
It will aid debugging if a procees delete fails, to figure out whether
it is paused or running.
=> add current process state to the error message

.github/workflows/images.yml
This action mirrors an image into containerd's package namespace `ghcr.io/containerd` and can be triggered manually with a provided upstream image.
Tested at https://github.com/dmcgowan/containerd/actions/workflows/images.yml
=> Add github action to mirror image

cmd/containerd/builtins.go, cmd/containerd/command/main.go, plugin/plugin.go, services/server/config/config.go, tracing/plugin/otlp.go, tracing/tracing.go
This just makes the implementation a little cleaner.
It also makes the trace exporter pluggable.
=> Move tracing to plugin

metadata/content.go
The `createAndCopy` function is only called when `nw.w` is nil in order to create a new writer and prepare it. The current code is attempting to close `nw.w` when there is a copy error. The correct behavior would be to close the new writer and not touch `nw.w`.
This issue has existed for awhile, but was recently seen when `content.CopyReaderAt(w, ra, desc.Size)` returned an error during testing another change.
=> Fix panic in metadata content writer on copy error

images/handlers.go, import.go, integration/client/import_test.go
During import, if an image does not match the host's platform, it won't have any children labels set, which will result in the
Garbage Collector deleting its content later, resulting in an unusable image. In this case, we should fail early.
This can still be bypassed by using ``ctr import --all-platforms``.
Depends On: https://github.com/containerd/containerd/pull/5916
=> import: Raise error if the imported image is filtered out

metadata/content.go
The `createAndCopy` function is only called when `nw.w` is nil
in order to create a new writer and prepare it. The current code
is attempting to close `nw.w` when there is a copy error. The
correct behavior would be to close the new writer and not touch `nw.w`.
(cherry picked from commit b9cf0d75a9f4a8a09ab55caa1983a8988ba4834d)
=> [release/1.5] Fix panic in metadata content writer on copy error

metadata/content.go
The `createAndCopy` function is only called when `nw.w` is nil
in order to create a new writer and prepare it. The current code
is attempting to close `nw.w` when there is a copy error. The
correct behavior would be to close the new writer and not touch `nw.w`.
(cherry picked from commit b9cf0d75a9f4a8a09ab55caa1983a8988ba4834d)
=> [release/1.4] Fix panic in metadata content writer on copy error

.empty-mod/go.mod, pkg/cri/server/container_remove.go, pkg/cri/server/container_status.go, pkg/cri/server/container_stop.go, pkg/cri/server/events.go, pkg/cri/server/helpers.go, pkg/cri/server/helpers_test.go, pkg/cri/server/image_remove.go, pkg/cri/server/image_status.go, pkg/cri/server/sandbox_remove.go, pkg/cri/store/container/container.go, pkg/cri/store/container/container_test.go, pkg/cri/store/errors_test.go, pkg/cri/store/image/image.go, pkg/cri/store/image/image_test.go, pkg/cri/store/sandbox/sandbox.go, pkg/cri/store/sandbox/sandbox_test.go, pkg/cri/store/snapshot/snapshot.go, pkg/cri/store/snapshot/snapshot_test.go
These errors have been DEPRECATED and will be removed in 1.5, switch usage directly to `errdefs.ErrAlreadyExists`.
=> switch usage directly to errdefs.(ErrAlreadyExists and ErrNotFound)

oci/spec_opts.go
The `oci.WithUser` function relies on checking a path on the hosts disk to
grab/validate the uid:gid pair for the user string provided. For LCOW it's a
bit harder to confirm that the user actually exists on the host as a rootfs isn't
mounted on the host and shared into the guest, but rather the rootfs is constructed
entirely in the guest itself. To accommodate this, a spot to place the user string
provided by a client as-is is needed.
The `Username` field on the runtime spec is marked by Platform as only for Windows,
and in this case it *is* being set on a Windows host at least, but will be used as a
temporary holding spot until the guest can use the string to perform these same
operations to grab the uid:gid inside.
=> Change `oci.WithUser` behavior for LCOW

cmd/containerd/command/main.go, log/context.go, log/context_test.go, tracing/log.go
This adds valuable logging data to the open telemetry traces.
When the trace is not recording we don't bother doing anything as it is
relatively expensive to convert logrus data to otel just due to the
nature of how logrus works.
The way this works is that we now set a context on the logrus.Entry that
gets passed around which the hook then uses to determine if there is an
active span to forward the logs to.
Example output, note the logrus debug info in the middle blog:
=> Add open telemetry logging hook for logrus

integration/main_test.go, integration/windows_hostprocess_test.go, script/test/cri-integration.sh, script/test/utils.sh
Windows HostProcess containers can run containerized workloads on a Windows host. These containers operate as normal processes but have access to the host network namespace, storage, and devices when given the appropriate user privileges.
HostProcess containers support the ability to run as one of the following Windows service accounts: ``LocalSystem``, ``LocalService``, ``NetworkService``.
Additionally, the host - container image matching OS versions restriction does not apply to Windows HostProcesses.
=> integration: Adds Windows HostProcess tests

.github/workflows/ci.yml, .github/workflows/nightly.yml, .github/workflows/release.yml, .travis.yml, .zuul/playbooks/containerd-build/run.yaml, Vagrantfile, contrib/Dockerfile.test
This includes additional fixes for CVE-2021-39293.
go1.16.8 (released 2021-09-09) includes a security fix to the archive/zip package,
as well as bug fixes to the archive/zip, go/internal/gccgoimporter, html/template,
net/http, and runtime/pprof packages. See the Go 1.16.8 milestone on the issue
https://github.com/golang/go/issues?q=milestone%3AGo1.16.8+label%3ACherryPickApproved
This brings the 1.4 branch to use Go 1.16 (as Go1.15 now reached end of support)
It first reverts the Go updates that were only in the 1.4 release branch:
- https://github.com/containerd/containerd/pull/5841 [release/1.4] Update Go to 1.15.15
- https://github.com/containerd/containerd/pull/5724 [release/1.4] Update Go to 1.15.14
- https://github.com/containerd/containerd/pull/5664 …
=> [release/1.4] Update Go to 1.16.8

reference/docker/reference.go
replace deprecated function `SplitHostname`
=> replace deprecated function with Domain and Path

cmd/ctr/commands/tasks/exec.go
make exec-id flag required in exec command
```bash
$ ./ctr t exec
NAME:
ctr tasks exec - execute additional processes in an existing container
USAGE:
ctr tasks exec [command options] [flags] CONTAINER CMD [ARG...]
OPTIONS:
--cwd value       working directory of the new process
--tty, -t         allocate a TTY for the container
--detach, -d      detach from the task after it has started execution
--exec-id value   exec specific id for the process
--fifo-dir value  directory used for storing IO FIFOs
--log-uri value   log uri for custom shim logging
--user value      user id or name
ctr: Required flag "exec-id" not set
```
=> fix: make exec-id flag required in exec command

.github/workflows/images.yml
Allow overwriting the target tag to support mirror images from multiple sources under our single namespace.
To handle this case in old branches, which currently would just all attempt to overwrite to the same tag
```
41         switch runtime.GOARCH {
42         case "386":
43                 testImage = "docker.io/i386/alpine:latest"
44         case "arm":
45                 testImage = "docker.io/arm32v6/alpine:latest"
46         case "arm64":
47                 testImage = "docker.io/arm64v8/alpine:latest"
48         case "ppc64le":
49                 testImage = "docker.io/ppc64le/alpine:latest" 
50         case "s390x": 
51                 testImage = "docker.io/s390x/alpine:latest"
52         default:
53                 testImage = "docker.io/library/alpine:latest" 
54         }
``` …
=> Update mirror images to take target image name

client_test.go, client_unix_test.go, image_test.go, lease_test.go
This is important to increase test stability on the 1.4 branch. No single commit to backport for this, main and 1.5 has refactored and already made this change.
=> [release/1.4] Update test images to use Github package registry

services/tasks/local.go
Found this error in a docker daemon log classified as an "uknown" error.
Since we know what this is return the correct error type so it can be
handled.
=> task service: return known error type

script/setup/prepare_env_windows.ps1
Changes in this PR:
- Install nssm - needed for updates in the way cir-integration tests run on Windows
- Update Go to version 1.17.1 - to be in line with recent changes in containerD
- Pin Mingw to version 10.2.0 - newer versions consistently result in error "ThreadSanitizer failed to allocate 0x000002561000 (39194624) bytes at 0x200d952c5c000"
=> Fixes for Windows CI

contrib/fuzz/container_fuzzer.go, contrib/fuzz/containerd_import_fuzzer.go, contrib/fuzz/metadata_fuzzer.go, contrib/fuzz/oss_fuzz_build.sh
1. Add 4 fuzzers for the `metadata` package
2. `goimports` `container_fuzzer.go`
3. Change `init()` to be manually invoked to only use it for fuzzers that need it.
4. Clone stable branch of runc instead of `master`.
=> Fuzzing: Add fuzzers + small modifications

test/e2e_node/gci-init.sh
As discovered, `if uname -a | grep -q cos; then` only works for k8bs node e2e tests, not for cluster e2e tests. Change the way for verifying the cos by using `/etc/os-release` information
=> modify the way for checking cos

archive/compression/compression.go, archive/compression/compression_test.go
As a matter of fact, there are two frame formats defined by Zstandard: Zstandard frames and Skippable frames.
So we should probably support zstd algorithms with skippable frames.
See https://tools.ietf.org/id/draft-kucherawy-dispatch-zstd-00.html#rfc.section.2 for more details.
Signed-off-by: Da McGrady <dabkb@aol.com>
Related to https://github.com/moby/moby/pull/42862
=> compression: support zstd with skippable frame

sys/reaper/reaper_unix.go
The channel is created with no capacity that it needs receiver when
sending data. Otherwise, the sending-data goroutine will be blocked
forever. For the #6166 pr, the exec command timeout will return and
no receiver for the data. It will cause goroutine leaky.
This commit allocates buffered channel for the command status and closes
the channel after sending. And also use time.Timer with Stop for
performance concern.
---------
followup: https://github.com/containerd/containerd/pull/6166#discussion_r738470917
=> sys/reaper: avoid leaky goroutine when exec timeout

contrib/Dockerfile.test
The Dockerfile.test used to test containerd in a container does not work. It fails with error 
```
mv: cannot move '/usr/local/bin/protoc' to '/build/usr/local/bin/protoc': No such file or directory
```
This PR adds `mkdir -p` to ensure required folders exist.
Tested on Linux Ubuntu 18.04 LTS with Docker 20.10.7.
=> Add mkdir on Dockerfile

integration/runtime_handler_test.go
The test is passing on Windows.
Test logs: https://paste.ubuntu.com/p/p5c8KPqkHz/
=> integration: Enables TestRuntimeHandler for Windows

integration/client/restart_monitor_test.go
restart monitor test was failing due to occasionally taking past the
deadline on windows tests. Add a small additional grace period to
deflake the test.
=> test: Add grace period for restart monitor test

cmd/ctr/commands/run/run.go, pkg/cri/server/helpers.go, pkg/cri/server/helpers_test.go
This patch seems to needed to fix https://github.com/kubernetes-sigs/kind/issues/2518.
Backporting from https://github.com/containerd/containerd/pull/6124 (fixes https://github.com/containerd/containerd/issues/6123).
This change ignore errors during container runtime due to large
image labels and instead outputs warning. This is necessary as certain
image building tools like buildpacks may have large labels in the images
which need not be passed to the container.
Signed-off-by: Sambhav Kothari <sambhavs.email@gmail.com>
(cherry picked from commit 2a8dac12a7629c1c9f1be66c40e6cd5d25d9c70b)
Signed-off-by: Kohei Tokunaga <ktokunaga.mail@gmail.com>
=> [release/1.5] Output a warning for label image labels instead of erroring

integration/client/container_linux_test.go, plugin/plugin.go, runtime/runtime.go, runtime/task_list.go, runtime/v2/binary.go, runtime/v2/manager.go, runtime/v2/process.go, runtime/v2/shim.go, runtime/v2/shim_load.go, services/tasks/local.go, services/tasks/local_freebsd.go, services/tasks/local_unix.go, services/tasks/local_windows.go
This PR decouples shim v2 TaskManger into ShimManager + TaskManager.
ShimManager manages shim instances and implements Start/Delete with cleanup/Get funcs.
This can be exposed as separate containerd service to deal with shims from client (will follow up).
TaskManager works on top of shim manager and manages tasks to keep things compatible. 
ref: https://github.com/containerd/containerd/issues/5742
=> Decouple task manager

.github/workflows/windows-periodic.yml
The latest version of AZ CLI breaks the windows-periodic workflow. This PR pins the az CLI version to 2.29.2.
See:
https://github.com/Azure/cli/issues/56
=> Pin az CLI version in windows-periodic workflow

.github/workflows/ci.yml, .github/workflows/nightly.yml, .github/workflows/release.yml, .travis.yml, .zuul/playbooks/containerd-build/run.yaml, Vagrantfile, contrib/Dockerfile.test
go1.16.10 (released 2021-11-04) includes security fixes to the archive/zip and
debug/macho packages, as well as bug fixes to the compiler, linker, runtime, the
misc/wasm directory, and to the net/http package. See the Go 1.16.10 milestone
for details: https://github.com/golang/go/issues?q=milestone%3AGo1.16.10+label%3ACherryPickApproved
From the announcement e-mail:
[security] Go 1.17.3 and Go 1.16.10 are released
We have just released Go versions 1.17.3 and 1.16.10, minor point releases.
These minor releases include two security fixes following the security policy:
- archive/zip: don't panic on (*Reader).Open
Reader.Open (the API implementing io/fs.FS introduced in Go 1.16) can be made
to panic by an attacker providing either a crafted ZIP archive containing
completely invalid names or …
=> [release/1.4] update Go to 1.16.10

.github/workflows/ci.yml, .github/workflows/images.yml, .github/workflows/nightly.yml, .github/workflows/release.yml, .zuul/playbooks/containerd-build/integration-test.yaml, .zuul/playbooks/containerd-build/run.yaml, .zuul/playbooks/containerd-build/unit-test.yaml, Vagrantfile, contrib/Dockerfile.test, script/setup/prepare_env_windows.ps1
go1.17.3 (released 2021-11-04) includes security fixes to the archive/zip and
debug/macho packages, as well as bug fixes to the compiler, linker, runtime, the
go command, the misc/wasm directory, and to the net/http and syscall packages.
See the Go 1.17.3 milestone on our issue tracker for details.
From the announcement e-mail:
[security] Go 1.17.3 and Go 1.16.10 are released
We have just released Go versions 1.17.3 and 1.16.10, minor point releases.
These minor releases include two security fixes following the security policy:
- archive/zip: don't panic on (*Reader).Open
Reader.Open (the API implementing io/fs.FS introduced in Go 1.16) can be made
to panic by an attacker providing either a crafted ZIP archive containing
completely invalid names or an empty filename argument.
Thank you to …
=> Update Go to 1.17.3

.github/workflows/ci.yml, .github/workflows/nightly.yml, .github/workflows/release.yml, .zuul/playbooks/containerd-build/integration-test.yaml, .zuul/playbooks/containerd-build/run.yaml, .zuul/playbooks/containerd-build/unit-test.yaml, Vagrantfile, contrib/Dockerfile.test
go1.16.10 (released 2021-11-04) includes security fixes to the archive/zip and
debug/macho packages, as well as bug fixes to the compiler, linker, runtime, the
misc/wasm directory, and to the net/http package. See the Go 1.16.10 milestone
for details: https://github.com/golang/go/issues?q=milestone%3AGo1.16.10+label%3ACherryPickApproved
From the announcement e-mail:
[security] Go 1.17.3 and Go 1.16.10 are released
We have just released Go versions 1.17.3 and 1.16.10, minor point releases.
These minor releases include two security fixes following the security policy:
- archive/zip: don't panic on (*Reader).Open
Reader.Open (the API implementing io/fs.FS introduced in Go 1.16) can be made
to panic by an attacker providing either a crafted ZIP archive containing
completely invalid names or …
=> [release/1.5] update Go to 1.16.10

pkg/cri/store/container/container.go
I ran into this panic when testing out `main`. This should be part of 1.6
=> use write lock when updating container stats

remotes/docker/fetcher.go
Fixes #6220
Currently, containerd cannot pull OCI images that contain non-`http(s)://` urls.
This commit fixes this issue by allowing fallback when pull fails on a non-`http(s)://` url.
=> Fix containerd fails to pull OCI image with non-`http(s)://` urls

remotes/docker/fetcher.go
Backporting #6221
Fixes #6220
Currently, containerd cannot pull OCI images that contain non-http(s):// urls.
This commit fixes this issue by allowing fallback when pull fails on a non-http(s):// url.
=> [release/1.4] Fix containerd fails to pull OCI image with non-`http(s)://` urls

remotes/docker/fetcher.go
Backporting #6221
Fixes #6220
Currently, containerd cannot pull OCI images that contain non-http(s):// urls.
This commit fixes this issue by allowing fallback when pull fails on a non-http(s):// url.
=> [release/1.5] Fix containerd fails to pull OCI image with non-`http(s)://` urls

Makefile
In prior releases we were not using this variable and instead were
self-constructing a release tar file.
This was changed in 27d7c50384b11d6a3c5982c7e20e89ec360d542a
The change means the variable is being used now and is causing the
artifacts to be produced to have a different name which may break
download scripts.
=> release: change tar name to match prior releases

script/setup/prepare_env_windows.ps1
The current Windows CI setup script assumes it will always be run under the `azureuser` username.
While this username is defined in the Windows CI GitHub action, the current version of the script both exposes us to a future risk of breaking should the CI action be changed, and is also unfriendly to`curl | sh`-ing it for quick test environment setups.
This patch makes the Windows CI setup script work with any username provided they have administrative privileges.
=> Integration: Generalize Windows CI setup scripts for any username.

pkg/cri/server/container_create.go, pkg/cri/server/container_list.go, pkg/cri/server/container_remove.go, pkg/cri/server/container_start.go, pkg/cri/server/container_stop.go, pkg/cri/server/metrics.go, pkg/cri/server/sandbox_list.go, pkg/cri/server/sandbox_remove.go, pkg/cri/server/sandbox_run.go, pkg/cri/server/sandbox_stop.go
These are simple metrics that allow users to view more fine grained metrics on
internal operations.
=> [cri] add sandbox and container latency metrics

docs/cri/config.md, pkg/cri/config/config.go, pkg/cri/server/sandbox_run_linux.go, pkg/cri/server/sandbox_run_linux_test.go
Borrowing logic from https://github.com/moby/moby/pull/41030 to solve #4936 (and https://github.com/kubernetes/kubernetes/issues/102612 ) by adding options `enable_unprivileged_icmp` and `enable_unprivileged_ports`. However in-this point those are disabled by default.
~Only open question is do we need similar logic like was added by https://github.com/moby/moby/pull/42736 here too? (I'm not familiar enough to be able answer that question).~
=> CRI: Support enable_unprivileged_icmp and enable_unprivileged_ports options

services/server/config/config.go, services/server/server.go
When running containerd as a service it may be hard to
override the TMP location of the process. This is especially
true on Windows when running containerd in SCM. This change
allows you to set the 'temp' location in the config.toml when
the service starts up that overrides its TEMP/TMP/TMPDIR usage.
This is helpful on Linux as well but it primarily solves the
performance issue on Windows when running containerd across
volumes. IE: If you configure your data/root paths on a volume
other than the SystemDrive the snapshotter does a temporary unpack
on the SystemDrive and then has to copy contents of that data
to the snapshot folder on the destination volume. By alinging the
tmp with the destination it is a simple move operation instead of
a copy operation.
Note: Docker has been doing this …
=> Add support for TMP override on toml

pkg/cri/server/image_pull.go
When containerd use this config:
```
[plugins."io.containerd.grpc.v1.cri".registry.mirrors]
[plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:5000"]
endpoint = ["http://localhost:5000"]
```
Due to the `newTransport` function does not initialize the `TLSClientConfig` field.
Then use `TLSClientConfig` to cause nil pointer dereference
Signed-off-by: wanglei01 <wllenyj@linux.alibaba.com>
=> [CRI] Fix panic when registry.mirrors use localhost

.github/workflows/release.yml, go.mod, integration/client/go.mod, releases/v1.6.0-beta.toml, vendor/modules.txt, version/version.go
See sample generated notes at https://gist.github.com/dmcgowan/d9eba0f8f79c11c46734a109b6f7faef
Included API update this time, the `api/v1.6.0-beta.3` tag is created already
=> Prepare release notes for v1.6.0-beta.3

cmd/containerd/command/main.go
The return error should be`r.err`
=> fix: server error return

docs/cri/crictl.md, integration/image_load_test.go
I think the correct target is `install-deps`. [1]
[1]: https://github.com/containerd/containerd/blob/main/Makefile#L376
Signed-off-by: Takumasa Sakao <sakataku7@gmail.com>
=> Fix wrong make target on documentation

.github/workflows/windows-periodic.yml
In the Windows CI's periodic runs the `azure/CLI` GitHub action library is leveraged to run various Azure-related commands.
To avoid possible desyncing between the auth libraries of `azure/Login` and `azure/CLI` as described [here](https://github.com/Azure/cli/issues/56#issuecomment-958705517), this patch neglects to pass an explicit `azcliversion` to `azure/CLI` in order to have it default to the Azure CLI version set up by `azure/Login`.
=> Integration: Remove explicit version passing to `azure/CLI`.

.github/workflows/windows-periodic.yml
winIntegration ci job will failed for fork repository because of less of azure credentials.
https://github.com/jonyhy96/containerd/runs/4306903963?check_suite_focus=true
=> feat: skip ci for fork

RELEASES.md
Sync RELEASES.md with changes in https://github.com/containerd/containerd.io/pull/106
=> releases: mark 1.4 as Extended

integration/container_stats_test.go
```
// from  https://github.com/containerd/containerd/pull/6150#issuecomment-974747473
container_stats_test.go:364:
Error Trace:	container_stats_test.go:364
Error:      	Received unexpected error:
unexpected stats length
github.com/containerd/containerd/integration.TestContainerListStatsWithIdSandboxIdFilter.func4
/home/runner/work/containerd/containerd/integration/container_stats_test.go:371
github.com/containerd/containerd/integration.Eventually
/home/runner/work/containerd/containerd/integration/main_test.go:324
github.com/containerd/containerd/integration.TestContainerListStatsWithIdSandboxIdFilter
/home/runner/work/containerd/containerd/integration/container_stats_test.go:364
testing.tRunner
/opt/hostedtoolcache/go/1.17.3/x64/src/testing/testing.go:1259
runtime.goexit …
```
=> integration: add stats result in error message

cmd/ctr/commands/commands.go, cmd/ctr/commands/run/run_unix.go
This allows Linux Capabilities to be modified via `ctr`.
e.g.
```
$ sudo ./bin/ctr run --cap-add "CAP_SYS_ADMIN" --cap-drop "CAP_NET_RAW" \
--rm docker.io/library/busybox:latest foo cat /proc/self/status | grep Cap
CapInh: 00000000a82405fb
CapPrm: 00000000a82405fb
CapEff: 00000000a82405fb
CapBnd: 00000000a82405fb
CapAmb: 0000000000000000
```
Signed-off-by: Manabu Sugimoto <Manabu.Sugimoto@sony.com>
=> ctr: Add Linux Capabilities control flags

cmd/ctr/commands/snapshots/snapshots.go
By default, diff subcommand will print tar(.gz) on stdout. If we print
the media-type in stdout, the output will create invalid tar(.gz) data.
```
// before
➜  containerd git:(move_stdout_to_stderr) sudo ctr snapshot diff sha256:9f54eef412758095c8079ac465d494a2872e02e90bf1fb5f12a1641c0d1bb78b > /tmp/1.tar
➜  containerd git:(move_stdout_to_stderr) file /tmp/1.tar
/tmp/1.tar: data
// after change
➜  containerd git:(move_stdout_to_stderr) make bin/ctr
+ bin/ctr
➜  containerd git:(move_stdout_to_stderr) sudo bin/ctr snapshot diff sha256:9f54eef412758095c8079ac465d494a2872e02e90bf1fb5f12a1641c0d1bb78b > /tmp/2.tar
media-type: application/vnd.oci.image.layer.v1.tar+gzip
➜  containerd git:(move_stdout_to_stderr) file /tmp/2.tar
/tmp/2.tar: gzip compressed data, original size modulo 2^32 75155456 …
```
=> ctr/snapshots/diff: show media-type in stderr

runtime/v2/shim_load.go
Fixes `exec: \"io.containerd.runc.v2\": executable file not found in $PATH"` caught in [nerdctl CI](https://github.com/containerd/nerdctl/runs/4286643328?check_suite_focus=true).
=> Fix executable file not found when restoring shims

integration/images/README.md, integration/images/volume-copy-up/Makefile, integration/images/volume-ownership/Dockerfile_windows, integration/images/volume-ownership/Makefile, integration/images/volume-ownership/tools/get_owner_windows.go
Short overview of changes:
* Adds Windows dockerfile for volume-ownership image
* Build volume-copy-up on Windows
* Adds a helper tool that fetches the owner username and SID of a file or folder
* Adds README
* Remove 2004 from Windows versions
* Add ltsc2022 to Windows versions
This change builds Windows images on a Windows node. This is necessary in order for the volume tests to be relevant. Building images on Linux via buildx does not allow setting Windows specific file security info (ACLs, owner, etc).
Related: https://github.com/containerd/continuity/pull/188
Fixes: https://github.com/containerd/containerd/issues/6235 
=> Build volume test images on Windows

.github/workflows/windows-periodic-trigger.yml, .github/workflows/windows-periodic.yml
Following PR #6284, the Windows Periodic Workflow is prevented from
running on any repository outside of the original.
While this achieves the goal of preventing senseless Windows workflow
failures in contributors' forks, it makes running the workflow for
contributors (even manually) impossible.
This PR adds a separate workflow file which triggers the Windows
Integration workflow iff it is being run off of the original repository,
thus maintaining the upstream scheduling, while allowing contributors to
manually trigger the workflow on their forks if they so desire.
=> Integration: Separate Windows Periodic Tests workflow trigger.

.github/workflows/build-test-images.yml, script/setup/enable_docker_tls_on_windows.ps1, script/setup/prepare_windows_docker_helper.ps1
This change adds a new workflow that builds the volume test images and pushes them to a remote registry. This action needs to be manually triggered and can be configured to push to any remote repository to which the google cloud credentials configured as secrets have access to push.
For Windows images, a single image builder helper is used. Hyper-V isolation is leveraged to build images for all supported targets.
The easiest way to use this workflow is to fork the repo then configure your own secrets, run a build, test the images, then mirror the images to gcr.io.
Depends-on: https://github.com/containerd/containerd/pull/6274
=> Integration: Add image build workflow

integration/client/import_test.go
This change skips the TestExportAndImportMultiLayer test in integration/client
for the time being. It seems the image was updated recently and no longer
has a Windows entry in the manifest so the test will always fail. This should
be reverted when we figure out what happened to the image, but this is to
unblock PRs for the time being.
=> Skip TestExportAndImportMultiLayer on Windows

oci/utils_unix.go, oci/utils_unix_test.go
Relates to https://github.com/moby/moby/pull/42638 (https://github.com/moby/moby/pull/42638#discussion_r760048516)
This ports the changes of https://github.com/opencontainers/runc/commit/95a59bf206f86bc449c4ccc22e2c08e78c707eb6 (https://github.com/opencontainers/runc/pull/2529) to this repository.
From that PR:
(mode&S_IFCHR == S_IFCHR) is the wrong way of checking the type of an
inode because the S_IF* bits are actually not a bitmask and instead must
be checked using S_IF*. This bug was neatly hidden behind a (major == 0)
sanity-check but that was removed by [1].
In addition, add a test that makes sure that HostDevices() doesn't give
rubbish results -- because we broke this and fixed this before[2].
[1]: https://github.com/opencontainers/runc/commit/24388be71e1aef7facd0d78dda22e696c169427 …
=> oci/deviceFromPath(): correctly check device types

.github/workflows/build-test-images.yml
This change adds a login step that authenticates the runner to ghcr.io. This allows whomever triggers the action to use github packages as a destination for the container images.
An example run can be seen here:
https://github.com/gabriel-samfira/containerd/runs/4395940700?check_suite_focus=true
The resulting images can be viewed here:
https://github.com/gabriel-samfira?repo_name=containerd&tab=packages
=> Authenticate against ghcr.io

.github/workflows/build-test-images.yml, integration/client/client_unix_test.go, integration/client/client_windows_test.go, integration/client/import_test.go, integration/images/volume-copy-up/Makefile, integration/images/volume-ownership/Makefile
With the ghcr images now built and working, switch over to use these new images and update the default name.
See packages at https://github.com/orgs/containerd/packages
=> Move test volume images from gcr to ghcr

integration/client/restart_monitor_test.go
Use the time for the last non-running status to determine
whether the restart did not occur as expected. The
current timestamp only accounts for when the running
status was seen, however, the restart would have always
occurred in between the previous check and latest check.
Therefore, it makes more sense to use the previous check
to determine whether a failure was seen from the restart
monitor not restarting as expected.
(Opening as draft to force a few runs to check flakiness)
=> Update TestRestartMonitor expected time check

go.mod, go.sum, integration/client/go.sum, integration/common.go, vendor/github.com/Microsoft/go-winio/README.md, vendor/github.com/Microsoft/go-winio/backuptar/tar.go, vendor/github.com/Microsoft/go-winio/pkg/etw/provider.go, vendor/github.com/Microsoft/go-winio/pkg/etw/wrapper_32.go, vendor/github.com/Microsoft/go-winio/pkg/etw/wrapper_64.go, vendor/github.com/Microsoft/go-winio/pkg/security/syscall_windows.go, vendor/github.com/Microsoft/go-winio/pkg/security/zsyscall_windows.go, vendor/github.com/Microsoft/go-winio/vhd/vhd.go, vendor/github.com/Microsoft/go-winio/vhd/zvhd_windows.go, vendor/github.com/containerd/continuity/fs/copy.go, vendor/github.com/containerd/continuity/fs/copy_linux.go, vendor/github.com/containerd/continuity/fs/copy_unix.go, vendor/github.com/containerd/continuity/fs/copy_windows.go, vendor/github.com/containerd/continuity/go.mod, vendor/github.com/containerd/continuity/go.sum, vendor/modules.txt
This change updates the volume test images and vendors in the latest commit of ```containerd/continuity```. The new image versions make Windows volume tests relevant, and fixes the failing ```VolumeCopyUp``` test on Windows.
Related-To: https://github.com/containerd/containerd/pull/6275
=> Update volume test images

oci/spec_opts.go, oci/spec_opts_windows.go, oci/utils_unix.go
This will help to reduce the amount of runc/libcontainer code that's used in Moby / Docker Engine (in favor of using the containerd implementation).
=> export oci.DeviceFromPath()

.github/workflows/windows-periodic.yml
This change sets the ```CONTAINERD_ROOT``` environment variable for cri-integration tests. This is needed in order for the tests to use the same containerd root as ```containerd.exe``` itself. The path should have been already set by the test suite. This issue will be properly resolved once I find the root cause of this mismatch. 
=> Set CONTAINERD_ROOT in Windows cri-integration

integration/common.go, integration/image_list.sample.toml, integration/volume_copy_up_test.go, test/build-test-images.sh
I noticed we were using some different versions of the same test
images, so changing them to be the same (can help with find/replace
if we need to update them).
=> integration: align tags of test images

integration/images/volume-copy-up/Dockerfile_windows, integration/images/volume-ownership/Dockerfile_windows
It seems that the default ACLs inherited from the parent folder on Windows Server 2022, does not include "CREATOR OWNER" as it does on Windows Server 2019. This sets explicit ACLs on test files inside volume test images.
The image build workflow will need to be manually triggered after this merges.
=> Set explicit ACL on test files

.github/workflows/ci.yml, integration/client/client_windows_test.go, integration/client/image_test.go, platforms/defaults_windows_test.go
GA for ws2022 github actions VMs launched a couple weeks ago so seems like
it's time to try out the CI on this new SKU.
This involved adding new ws2022 runs for the OS matrices in the CI, fixing up
a test in the platforms package and adding a mapping for the ws2022 container image in
integration/client.
=> Add Windows Server 2022 CI runs

cmd/containerd/builtins.go, cmd/containerd/builtins_linux.go, cmd/containerd/builtins_windows.go
This PR adds `github.com/containerd/containerd/runtime/v2` package to default builtins.
It has no platform specific dependencies, so it's safe to include this package on all supported platforms (specifically in current implementation runtime v2 is not registered on darwin).
=> Include runtime v2 in default builtins

.github/workflows/ci.yml, script/setup/install-critools, script/setup/install-dev-tools, script/setup/prepare_env_windows.ps1
https://go.dev/doc/go-get-install-deprecation
=> Do not use `go get` to install executables

diff/apply/apply_darwin.go
There was a discussion in PR https://github.com/containerd/containerd/pull/5935 on how to enable native snapshotter on Mac and how to handle bind mounts with symlinks. While it's still unclear what the final approach should be, I'd like to enable native snapshotter to be at least able to unpack things and unblock further research/experiments.
This PR takes same approach as we do for overlay to skip temp mount in the Applier: https://github.com/containerd/containerd/blob/292b0c1561cf503123ad76e6bb7e26d7fa766a0a/diff/apply/apply_linux.go#L33
cc @thehajime 
=> Unblock native snapshotter on Darwin

.github/workflows/ci.yml, .github/workflows/nightly.yml, .github/workflows/release.yml, .zuul/playbooks/containerd-build/integration-test.yaml, .zuul/playbooks/containerd-build/run.yaml, .zuul/playbooks/containerd-build/unit-test.yaml, Vagrantfile, contrib/Dockerfile.test
go1.16.11 (released 2021-12-02) includes fixes to the compiler, runtime, and the
net/http, net/http/httptest, and time packages. See the Go 1.16.11 milestone on
https://github.com/golang/go/issues?q=milestone%3AGo1.16.11+label%3ACherryPickApproved
=> [release/1.5] Update Go to 1.16.11

.github/workflows/ci.yml, .github/workflows/nightly.yml, .github/workflows/release.yml, .travis.yml, .zuul/playbooks/containerd-build/run.yaml, Vagrantfile, contrib/Dockerfile.test
go1.16.11 (released 2021-12-02) includes fixes to the compiler, runtime, and the
net/http, net/http/httptest, and time packages. See the Go 1.16.11 milestone on
https://github.com/golang/go/issues?q=milestone%3AGo1.16.11+label%3ACherryPickApproved
=> [release/1.4] Update Go to 1.16.11

.github/workflows/windows-periodic.yml
We found that some Azure resource groups are being leaked causing core quota pressure in the sub we are using.  This can happen if the final task that cleans up the rg isn't run.
We have a cleanup process that should catch these vms but the creation timestamp must be in RFC3339 format.
=> Use RFC3339 format on Windows periodic resource group creation so cleanup works

oci/spec_opts.go
This will skip `WithAdditionalGIDs` on Darwin as we currently don't support temp mounts. Also because Darwin is not exposed in OCI spec, this just checks `GOOS` instead.
=> Skip WithAdditionalGIDs on Darwin

go.mod, go.sum, images/converter/default.go, integration/client/go.mod, integration/client/go.sum, vendor/github.com/opencontainers/image-spec/specs-go/v1/index.go, vendor/github.com/opencontainers/image-spec/specs-go/v1/manifest.go, vendor/github.com/opencontainers/image-spec/specs-go/version.go, vendor/modules.txt
The OCI image spec did a v1.0.2 security release for CVE-2021-41190, however
commit 09c9270feee1d81044e29c47c3609fb0c1e4d7f5 (https://github.com/containerd/containerd/pull/6052), depends on MediaTypes that
have not yet been released by the OCI image-spec, so using current "main" instead.
full diff: https://github.com/opencontainers/image-space/compare/5ad6f50d6283...693428a734f5
=> go.mod: update image-spec to latest (v1.0.3-dev)

.github/workflows/ci.yml
As like other integration tests, Windows integration tests should not
fail-fast. So developers can see whether an issue is platform-specific
or not.
=> Don't fail-fast on Windows integration tests

integration/client/restart_monitor_test.go
Skip this test until this error can be evaluated and the appropriate test fix or environment configuration can be determined.
=> Disable restart monitor test in Windows

pkg/cri/server/sandbox_portforward_windows.go
Consistently use cioutil to prevent it being confused for Golang's ioutil.
=> cri/server: use consistent alias for pkg/ioutil

.github/workflows/ci.yml, .github/workflows/nightly.yml, .github/workflows/release.yml, .zuul/playbooks/containerd-build/integration-test.yaml, .zuul/playbooks/containerd-build/run.yaml, .zuul/playbooks/containerd-build/unit-test.yaml, Vagrantfile, contrib/Dockerfile.test
go1.16.12 (released 2021-12-09) includes security fixes to the syscall and net/http
packages. See the Go 1.16.12 milestone on the issue tracker for details:
https://github.com/golang/go/issues?q=milestone%3AGo1.16.12+label%3ACherryPickApproved
=> [release/1.5] Update Go to 1.16.12

.github/workflows/build-test-images.yml, .github/workflows/ci.yml, .github/workflows/images.yml, .github/workflows/nightly.yml, .github/workflows/release.yml, .zuul/playbooks/containerd-build/integration-test.yaml, .zuul/playbooks/containerd-build/run.yaml, .zuul/playbooks/containerd-build/unit-test.yaml, Vagrantfile, contrib/Dockerfile.test, script/setup/prepare_env_windows.ps1
go1.17.5 (released 2021-12-09) includes security fixes to the syscall and net/http
packages. See the Go 1.17.5 milestone on the issue tracker for details:
https://github.com/golang/go/issues?q=milestone%3AGo1.17.5+label%3ACherryPickApproved
go1.17.4 (released 2021-12-02) includes fixes to the compiler, linker, runtime,
and the go/types, net/http, and time packages. See the Go 1.17.4 milestone on
https://github.com/golang/go/issues?q=milestone%3AGo1.17.4+label%3ACherryPickApproved
=> Update Go to 1.17.5

.github/workflows/ci.yml, .github/workflows/nightly.yml, .github/workflows/release.yml, .travis.yml, .zuul/playbooks/containerd-build/run.yaml, Vagrantfile, contrib/Dockerfile.test
go1.16.12 (released 2021-12-09) includes security fixes to the syscall and net/http
packages. See the Go 1.16.12 milestone on the issue tracker for details:
https://github.com/golang/go/issues?q=milestone%3AGo1.16.12+label%3ACherryPickApproved
=> [release/1.4] Update Go to 1.16.12

services/server/server.go
Add timeout for `bolt.Open` options to prevent indefinitely block when bolt plugin init which won't throws any error and makes it difficult to findout the reason.
=> feat: add timeout for bolt open

pkg/cri/server/container_stats_list.go
Addresses this issue https://github.com/containerd/containerd/issues/6198
Currently for the `ListContainerStats` RPC in CRI, if a supplied `ContainerStatsFilter` is nil , the response is empty.
With the change  -  the list of stats for all containers is returned
Change also makes the `ListContainerStats` implementation consistent with CRI-O implementation
https://github.com/cri-o/cri-o/blob/main/server/container_stats_list.go
=> ListContainerStats to return stats response if ContainerStatsFilter is nil

metadata/namespaces.go, metadata/namespaces_test.go
The error message was unnecessary cryptic. `snapshot-[name]` notation
was only used here and hard to understand.
Instead it should say `snapshots on "..." snapshotter`.
=> medatada: make namespaces' deletion error less cryptic

pkg/cri/annotations/annotations.go, pkg/cri/server/sandbox_run_linux.go, pkg/cri/server/sandbox_run_linux_test.go
Today in Kubernetes, sandbox level sizing information is not available through CRI. With 1.23 (see https://github.com/kubernetes/kubernetes/pull/104886), the CRI API is updated to include an optional field in the LinuxPodSandboxConfig field which is part of the RunPodSandbox request. sandbox create request, as seen here: https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/cri-api/pkg/apis/runtime/v1alpha2/api.proto#L334-L335
Having sandbox level resource details at sandbox creation time will have large benefits for sandboxed runtimes. In the case of Kata Containers, for example, this'll allow us to better support SW/HW architectures which don't allow for resource hot plug (memory/CPU), and it'll allow for better queue sizing for virtio devices associated with the …
=> CRI update for sandbox sizing

archive/tar_test.go, cmd/ctr/commands/content/fetch.go, content/helpers.go, content/local/writer.go, image.go, images/archive/importer.go, images/handlers.go, mount/mount_linux.go, mount/temp.go, oci/spec_opts.go, pkg/cri/config/config.go, pkg/cri/opts/spec_linux.go, pkg/cri/server/events.go, pkg/process/deleted_state.go, pkg/process/exec_state.go, pkg/process/init_state.go, remotes/docker/config/hosts.go, remotes/docker/fetcher.go, remotes/docker/httpreadseeker.go, rootfs/init.go, runtime/v2/shim.go, services/introspection/service.go, services/server/server.go, snapshots/devmapper/metadata.go, snapshots/devmapper/pool_device.go, snapshots/devmapper/snapshotter.go, snapshots/lcow/lcow.go, snapshots/native/native.go, snapshots/storage/metastore_test.go, snapshots/windows/windows.go
There is a lot wrong usage of Errorf in codebase, both when doing log and return.
If error info not contains any arguments, use `errors.New` or `logrus.Error` instead.
=> refactor: functions for error log and error return

version/version.go
No changelog updates this time, fixes a regression from beta.3 https://github.com/containerd/nerdctl/pull/551
=> Prepare release notes for v1.6.0-beta.4

integration/volume_copy_up_test.go, integration/volume_copy_up_unix_test.go, integration/volume_copy_up_windows_test.go
This change enables the TestVolumeOwnership on Windows. The test assumes that the volume-ownership image is built on Windows, thus ensuring that Windows file security info (ACLs and ownership info) are attached to the C:\volumes\test_dir path.
This change also removes the need for executing ```find``` in order to get the full path to the files or folders we wish to test against on the host.
Depends-on: https://github.com/containerd/containerd/pull/6321
=> Integration: Enable TestVolumeOwnership on Windows

integration/container_update_resources_test.go, pkg/cri/opts/spec_linux.go
Initial attempt at #6302.
This is my first real containerd PR, and I'm new to the codebase, so sorry if I'm going the wrong way about implementing or testing this.
This PR attempts to add and test support for swap in the CRI server, the test is loosely based on the memory test that already existed, but with support for cgroupsv2 too. I've only been able to test this locally with cgroupsv2 so far though (I'll test with cgroupsv1 locally later, if CI can't validate there).
=> cri: add support for configuring swap

oci/utils_unix.go, oci/utils_unix_go116_test.go, oci/utils_unix_go117_test.go, oci/utils_unix_test.go
follow-up to https://github.com/containerd/containerd/pull/6306 (first commit is from that PR)
this is a quick attempt to port https://github.com/moby/moby/pull/42638 to containerd, so that we're not creating yet-another copy of libcontainer/devices/GetDevices
Allow rootless containers with privileged to mount devices that are accessible (ignore permission errors in rootless mode).
Allow rootless containers with privileged to mount devices that are accessible
(ignore permission errors in rootless mode).
This patch updates oci.getDevices() to ignore access denied errors on sub-
directories and files within the given path if the container is running with
userns enabled.
Note that these errors are _only_ ignored on paths _under_ the specified path,
and not the path itself, so if …
=> OCI: Mount (accessible) host devices in privileged rootless containers

.github/workflows/windows-periodic.yml
Considering Windows 2004's EoL on the 14th of December, 2021,
this PR removes all periodic integration testing for 2004.
=> Remove Windows integration testing for 2004.

pkg/cri/server/helpers_linux.go, pkg/seutil/seutil.go
The ability to handle KVM based runtimes with SELinux has been added as
part of d715d00.
However, that commit introduced some logic to check whether the
"container_kvm_t" label would or not be present in the system, and while
the intentions were good, there's two major issues with the approach:
1. Inspecting "/etc/selinux/targeted/contexts/customizable_types" is not
the way to go, as it doesn't list the "container_kvm_t" at all.
2. There's no need to check for the label, as if the label is invalid an
"Invalid Label" error will be returned and that's it.
With those two in mind, let's simplify the logic behind setting the
"container_kvm_t" label, removing all the unnecessary code.
Here's an output of VMM process running, considering:
* The state before this patch:
```
$ containerd --version …
```
=> seutil: Fix setting the "container_kvm_t" label

pkg/cri/server/helpers_linux.go, pkg/seutil/seutil.go
The ability to handle KVM based runtimes with SELinux has been added as
part of d715d009061edf5ed0da5aa81fe7b6d2a6b3c10c.
However, that commit introduced some logic to check whether the
"container_kvm_t" label would or not be present in the system, and while
the intentions were good, there's two major issues with the approach:
1. Inspecting "/etc/selinux/targeted/contexts/customizable_types" is not
the way to go, as it doesn't list the "container_kvm_t" at all.
2. There's no need to check for the label, as if the label is invalid an
"Invalid Label" error will be returned and that's it.
With those two in mind, let's simplify the logic behind setting the
"container_kvm_t" label, removing all the unnecessary code.
Here's an output of VMM process running, considering:
* The state before this …
=> [release/1.5] seutil: Fix setting the "container_kvm_t" label

integration/client/container_test.go
OCI hooks aren't implemented on Windows. The test will, and has been, actually
running fine on Windows because the Github runners seem to have a 'ps' binary in
the users PATH, but there's not any actual hook functionality being tested as
any of the OCI fields are ignored for Windows containers.
=> Disable TestContainerHook on Windows

Makefile
[A recent change](https://github.com/containerd/containerd/commit/27d7c50384b11d6a3c5982c7e20e89ec360d542a#diff-0aecf097aa5ef1fae976210b147ff1f50248c18d32aab75a40b9c73420b69ceaR28) altered the default target that would get run for the makefile which ended up making a standalone 'make' invocation only build the Windows shim and nothing else. This was [affecting the CI](https://github.com/kubernetes-sigs/cri-tools/runs/4403863280?check_suite_focus=true) of some other projects that relied on 'make' building containerd, ctr, and friends.
=> Fix default makefile target for windows

.github/workflows/windows-periodic.yml, script/test/cri-integration.sh, script/test/utils.sh
This change adds the following:
* Default paths to REPORT_DIR, CONTAINERD_STATE and CONTAINERD_ROOT for Windows
* Removes the need for nssm on Windows. The nssm service has issues dealing with paths that contain spaces. Currently, if ```CONTAINERD_ROOT``` and ```CONTAINERD_STATE``` contain spaces in them, ```containerd``` will fail to parse anything after that space, leading to incomplete options passed to containerd. This happens because the paths are not properly quoted, and doing so in nssm [seems to be a bit cumbersome](https://nssm.cc/usage).  Also, the ```containerd``` binary is perfectly capable of registering itself as a service in Windows, and Windows itself can take care of any failure handling of the service. NSSM is useful for binaries that do not have any kind of Windows …
=> cri-integration: Add Windows defaults and fix spaces issue

integration/container_stats_test.go
This change fixes flakiness on Windows for ```TestContainerListStatsWithSandboxIdFilter```. 
=> Fix flakiness on Windows for list stats

snapshots/devmapper/config.go, snapshots/devmapper/snapshotter.go, snapshots/devmapper/snapshotter_test.go
Lazy initialization reduces file system initialization time drastically.
This removes explicit disabling of lazy init options.
#6119 https://github.com/containerd/containerd/issues/6119
=> Enable lazy init for ext4 with devicemapper

integration/client/client_test.go
The global &daemon{} object only gets an address assigned if you call start() on it, which only gets called if you don't pass no-daemon. The aftermath of this is that running the integration tests with no-daemon just has them fail trying to create a client for containerd. This change just assigns whatever address is passed to the binary even in the no-daemon case so you can run the integration tests against an already running containerd instance.
=> Fix no-daemon flag for integration/client tests

vendor.conf, vendor/github.com/opencontainers/image-spec/specs-go/v1/index.go, vendor/github.com/opencontainers/image-spec/specs-go/v1/manifest.go, vendor/github.com/opencontainers/image-spec/specs-go/version.go
- Bring mediaType out of reserved status
- specs-go: adding mediaType to the index and manifest structures
full diff: https://github.com/opencontainers/image-spec/compare/v1.0.1...v1.0.2
=> [release/1.4] vendor: github.com/opencontainers/image-spec v1.0.2

integration/main_test.go, integration/restart_test.go
This change fixes some issues in ```TestContainerdRestart``` on Windows.
Note, this will not fix current flakiness in the CI. That is most likely caused by a bug in ```hcsshim```, described here: https://github.com/microsoft/hcsshim/pull/1249
=> Fix restart container test

integration/shim_dial_unix_test.go
Signed-off-by: haoyun <yun.hao@daocloud.io>
Only test abstract uds on linux which is only support on linux.
=> only test abstract uds on linux

Makefile.windows
Seems $(PWD) if the shell is powershell may not be inherited properly as it ends up being an empty string. The result of this is that using mingw's make with powershell is $(PWD)/bin ends up being /bin and the windows shim will get placed there. `make install` afterwards will try to find the shim at $pwd/bin and fail.
Changing to CURDIR https://www.gnu.org/software/make/manual/make.html#index-CURDIR seems to be a solution here as it's not inherited by the environment and is set by make itself so should work across any type of shell.
=> Fix $(PWD) issue for Windows makefile

cmd/ctr/commands/run/run.go, cmd/ctr/commands/run/run_unix.go, cmd/ctr/commands/run/run_windows.go, oci/spec_opts_windows.go
`--cni` flag for run command is only available for Linux:
https://github.com/containerd/containerd/blob/af1a0908d06b4f7db4a11bfc67ecc2f34baeb04b/cmd/ctr/commands/run/run_unix.go#L82-L85
But not for Windows yet. I added the flag and also the necessary set up to make networking work in Windows containers.
fixes #6305
=> fix(ctr): enable networking for Windows containers

docs/man/containerd-config.toml.5.md
- use proper markdown lists in containerd-config.toml.5.md
- document the runtime shim plugin config options. Add documentation for config options under
`plugins."io.containerd.runtime-shim.v2.shim`.
=> docs: improve plugin documentation

content/local/store_bsd.go, content/local/store_openbsd.go, content/local/store_unix.go
Use the syscall method instead of repeating the type conversions for
the syscall.Stat_t Atim/Atimespec members. This also allows to drop the
//nolint: unconvert comments.
=> content/local: use syscall.Timespec.Unix

runtime/v1/linux/task.go
Signed-off-by: haoyun <yun.hao@daocloud.io>
use _ for code consistency https://github.com/containerd/containerd/pull/5813/files#r686973662
=> fix: use _ for consistency

.github/workflows/windows-periodic.yml
This patch makes the Windows Integration GitHub workflow conditionally
execute the CI artifact upload to GCP on successful runs iff the GitHub
secrets containing the GCP access info are defined.
=> Integration: Check GCP secrets on Windows CI artifact upload.

remotes/docker/auth/fetch.go, remotes/docker/authorizer.go, remotes/docker/config/hosts.go, remotes/docker/resolver_test.go
The new AuthorizerOpt `WithFetchRefreshToken` allows fetching "refresh token" (aka "identity token", "offline token").
The fetched refresh token value can be accessed via the callback function `OnFetchRefreshToken`.
```go
// OnFetchRefreshToken is called on fetching request token.
type OnFetchRefreshToken func(ctx context.Context, refreshToken string, req *http.Request)
// WithFetchRefreshToken enables fetching "refresh token" (aka "identity token", "offline token").
func WithFetchRefreshToken(f OnFetchRefreshToken) AuthorizerOpt {
return func(opt *authorizerConfig) {
opt.onFetchRefreshToken = f
}
}
```
For HTTP GET mode (`FetchToken`), `offline_token=true` is set in the request.    https://docs.docker.com/registry/spec/auth/token/#requesting-a-token
For HTTP POST mode …
=> remotes/docker: allow fetching "refresh token" (aka "identity token", "offline token")

docs/cri/architecture.md
The referenced document was moved into the staging directory within the kubernetes repository
Signed-off-by: Jan Klippel <g1thub@kl1pp3l.de>
=> corrected link in cri architecture documentation

pkg/cri/server/instrumented_service.go
I think the correct method name is `RunPodSandbox`.
Signed-off-by: Takumasa Sakao <tsakao@zlab.co.jp>
=> Fix wrong log message

test/e2e_node/gci-init.sh
On newer COS M97 images, cgroupv2 is enabled out of the box. It is
enabled using default systemd configuration and does not have
`systemd.unified_cgroup_hierarchy` present `/proc/cmdline`. As a result, the
check for manual cgroupv2 enablement should be improved to not only check
`/proc/cmdline`, but also to see if it's enabled on the system using `stat
-fc %T /sys/fs/cgroup/`
=> test: e2e node COS cgroupv2 script

.github/workflows/windows-periodic-trigger.yml, .github/workflows/windows-periodic.yml
Following the forking of `github-google-actions/setup-gcloud` into
individual actions, the functionality for authenticating on Google
Cloud within GitHub workflows has been moved to the
`github-google-actions/auth` action.
This patch updates the Windows Periodic Integration test workflow to use
the new `auth` action, as well as switching to using Workload Identity
Federation-based authorization which is superseding the Service Account
Key-based authorization the Windows Periodic workflow was using thus far.
=> Integration: Switch to using `auth` Gcloud action in Windows workflow.

cmd/ctr/commands/containers/containers.go, cmd/ctr/commands/images/images.go, cmd/ctr/commands/leases/leases.go, cmd/ctr/commands/snapshots/snapshots.go, cmd/ctr/commands/tasks/delete.go
This commit unifies the following sub commands alias for
deleting/removing.
- containers
- tasks
- contents
- leases
- images
- snapshots
Signed-off-by: Ning Li <lining2020x@163.com>
=> ctr: Unify the delete subcommand alias

integration/images/volume-copy-up/Makefile, integration/images/volume-ownership/Makefile
Add ppc64le support to the test images volume-copy-up and volume-ownership.
For the testing, I could only verify those changes for the non Windows images, that is (amd64, arm64 and ppc64le).
As I do not own any Azure VMs, I run a modified version of the  [build-test-images.yml](https://github.com/alunsin/containerd/compare/dev/build-image-for-ppc64le...test/build-image-for-ppc64le), that only relies on the Github's VM and does not build the Windows image.
You can take a look at the workflow execution from my personal repo https://github.com/alunsin/containerd/actions/runs/1684293097
=> Add ppc64 support for test images

client.go, integration/client/go.sum
This is a effective revert of 294143bf380dbbc706e85387148c02fc2afa496d
The one thing that makes it not a total revert is this keeps the usage
of chain interceptors, which prevents us from overwriting interceptors
passed into client options.
The automatic trace injection is unnecessary overhead since callers of
this function can add the necessary interceptors when creating the
client.
=> Do not automatically inject client traces

.github/workflows/codeql.yml
CodeQL should run on pull requests to avoid post-merge surprises.
=> gha: run CodeQL scan on pull requests

pkg/cri/server/rdt_linux.go, pkg/cri/server/rdt_stub_linux.go
go 1.16 is still a stable and support Go release and requires the `+build` tag to be present.
=> Fix rdt build tags for go 1.16

integration/client/client_windows_test.go
The build number used to determine whether we need to pull the Windows Server 2022 image for the integration tests was previously hardcoded as there wasn't an hcsshim release with the build number. Now that there is and it's vendored in, this change just swaps to it.
=> Integration: Change to Windows Server 2022 build number constant

.github/workflows/ci.yml
Ensure containerd compiles for all stable versions of Go
=> Compile binaries for go1.16 and go1.17 in CI

cmd/ctr/commands/images/push.go, remotes/handlers.go, remotes/handlers_test.go
Add image handler to skip non-distributable blobs.
Add flag to ctr explicitly enable non-dist blob push -- breaking change, can flip this flag if needed, just figured it's best to have the expected handling of this blobs as a default.
=> Add support for skipping non-dist blob push

pkg/cri/server/container_stats_list.go
this cherry-pick is needed to fix 
https://github.com/kubernetes-sigs/cri-tools/pull/857
(cherry picked from commit c8a009d18cd667c0a8b13e454a110b4fa5baba03)
=> [release/1.5] add-list-stat: return container list if filter is nil

remotes/docker/scope.go, remotes/docker/scope_test.go
Signed-off-by: ye.sijun <junnplus@gmail.com>
Ref: https://github.com/containerd/nerdctl/pull/718
Empty scopes will cause `GetTokenScopes` to panic.
=> Fix empty scopes return

platforms/compare.go, platforms/compare_test.go, platforms/database.go
AMD64 variants have been standardized in https://en.wikipedia.org/wiki/X86-64#Microarchitecture_levels and are available in modern compilers to optimize for modern machines when needed. For example, starting from 1.18 Go is adding `GOAMD64` to set the minimum compatibility version. If the host doesn't support the minimum version the binary will refuse to start.
This PR makes the `platformVector` matcher understand these values `v1-v4` as variants so they can be used in image indexes. `v1` will remain the default and is normalized out so the change is not visible unless when handling images that have variants with higher value. The behavior is the same as current ARM compatibility handling: `platformVector` will match the highest compatible version.
This is especially important for the …
=> platforms: add support for matching amd64 variants

runtime/v2/shim/shim.go, runtime/v2/shim/shim_unix.go, runtime/v2/shim/shim_windows.go
This causes sigint/sigterm to trigger a shutdown of the shim.
It is needed because otherwise the v2 shim hangs system shutdown.
Fixes #5502
=> shimv2: handle sigint/sigterm

oci/spec_opts.go
In linux kernel, the umount writable-mountpoint will try to do sync-fs
to make sure that the dirty pages to the underlying filesystems. The many
number of umount actions in the same time maybe introduce performance
issue in IOPS limited disk.
When CRI-plugin creates container, it will temp-mount rootfs to read
that UID/GID info for entrypoint. Basically, the rootfs is writable
snapshotter and then after read, umount will invoke sync-fs action.
For example, using overlayfs on ext4 and use bcc-tools to monitor
ext4_sync_fs call.
```
// uname -a
Linux chaofan 5.13.0-27-generic #29~20.04.1-Ubuntu SMP Fri Jan 14 00:32:30 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
// open terminal 1
kubectl run --image=nginx --image-pull-policy=IfNotPresent nginx-pod
// open terminal 2 …
```
=> oci: use readonly mount to read user/group info

contrib/seccomp/seccomp_default.go
This system call is only available on 32- and 64-bit PowerPC, it is used
by modern programming language implementations to implement coroutine
features through userspace context switches.
moby [\[1\]][1] and systemd nspawn [\[2\]][2] already whitelist this system call so it
makes sense to whitelist it in containerd as well.
[1]: https://github.com/moby/moby/pull/43092
[2]: https://github.com/systemd/systemd/pull/9487
=> seccomp: add support for "swapcontext" syscall in default policy

remotes/docker/pusher.go, remotes/docker/pusher_test.go, remotes/docker/status.go
Fixes #6242
`dockerPusher` provides `pushWriter` which implements `content.Writer`.
However, even if `pushWriter` become abort status (i.e. `Close()` is called
before `Commit()`), `dockerPusher` doesn't recognise that status and treats that
writer as on-going.
This behaviour doesn't allow the client to retry an aborted push.
This commit fixes this issue.
This commit also adds a test to ensure that the issue is fixed.
We can repro this issue by applying the following patch to enable `PushHandler` retrying.
```diff
--- a/remotes/handlers.go
+++ b/remotes/handlers.go
@@ -22,6 +22,7 @@ import (
"io"
"strings"
"sync"
+       "time"
"github.com/containerd/containerd/content"
"github.com/containerd/containerd/errdefs"
@@ -162,6 +163,20 @@ func PushHandler(pusher Pusher, provider …
```
=> remotes: fix dockerPusher to handle abort correctly

platforms/platforms.go, platforms/platforms_test.go
fixes https://github.com/containerd/containerd/issues/6168
Commit fb0688362cafb5c24cfe6bd4f83765a0515af374 (https://github.com/containerd/containerd/pull/1403) implemented the `Normalize()` function, but marked these fields as deprecated.
It's unclear what the motivation was for this (https://github.com/containerd/containerd/pull/1403#discussion_r199289449), as the fields are part of the OCI Image spec. On Windows, the OSVersion field specifically is important when matching images (as kernel versions may not be compatible).
This patch updates platforms.Normalize() to preserve the OSVersion and OSFeatures fields.
As a follow-up, we should look at defining an appropriate string-representation for these fields (possibly as part of the OCI Spec), and update platforms.Parse() accordingly.
=> platforms.Normalize(): do not reset OSVersion and OSFeatures

RELEASES.md, releases/v1.6.0-rc.toml, version/version.go
See generated release notes https://gist.github.com/dmcgowan/fb2b125fd74d6c268fcabd7c89bb831a
Due to timing of 1.6, this also bumps support date for 1.4
=> Prepare 1.6.0-rc.2

.github/workflows/ci.yml, .golangci.yml, pkg/cri/server/sandbox_run.go, pkg/os/os_windows.go, script/setup/install-dev-tools, snapshots/testsuite/testsuite.go
Backports of:
- (mostly for a cleaner cherry-pick, but fixes some issues with man-page generating) https://github.com/containerd/containerd/pull/5839
- https://github.com/containerd/containerd/pull/5771
- https://github.com/containerd/containerd/pull/5897
=> [release/1.5 backport] GHA fixes, update GolangCI-Lint v1.42.0, and go-mdman v2.0.1 

snapshots/devmapper/README.md
Document `fs_type` and `fs_options` in `snapshots/devmapper/README.md`
Resolves: #6499
=> Document fs_type and fs_options in snapshots/devmapper/README.md

cmd/containerd-stress/exec_worker.go
For some runtimes, the container is not ready for exec until the
container's task has been started (as opposed to just having the task created).
More specifically, running containerd-stress with --exec would break
with Kata Container shim, since the sandbox is not created until a
start is issued. By starting the container's primary task before adding
exec's, we can avoid:
```
error="cannot enter container exec-container-1, with err Sandbox not running, impossible to enter the container: unknown"
```
Signed-off-by: Eric Ernst <eric_ernst@apple.com>
=> containerd-stress: start task ctr before starting execs

.dockerignore, .github/workflows/release/Dockerfile
The .github/workflows/release/Dockerfile will use working dir as docker
build context. But the .dockerignore will ignore the .github/release/...
and cause dirty. We should remove it and verify git working tree after
build.
Fix: #6484
=> fix: .dockerignore make git working tree dirty

pkg/oom/v2/v2.go
When the cgroup is removed, EventChan is closed (this was pulled in by
8d69c041c52ac688430df7fd540018bf74f341c2). This results in a nil error
being received. Don't log an error in that case but instead return.
See also: https://github.com/containerd/containerd/issues/5670
=> pkg/oom/v2: handle EventChan routine shutdown quietly

.github/workflows/ci.yml, .github/workflows/nightly.yml, .github/workflows/release.yml, .zuul/playbooks/containerd-build/integration-test.yaml, .zuul/playbooks/containerd-build/run.yaml, .zuul/playbooks/containerd-build/unit-test.yaml, Vagrantfile, contrib/Dockerfile.test
go1.16.13 (released 2022-01-06) includes fixes to the compiler, linker, runtime,
and the net/http package. See the Go 1.16.13 milestone on our issue tracker for
details:
https://github.com/golang/go/issues?q=milestone%3AGo1.16.13+label%3ACherryPickApproved
=> [release/1.5] Update Go to 1.16.13

README.md
I noticed the logo was not correct in dark mode and was hard to see, here is some fancy mark down to make the white logo appear in dark mode and the dark logo appear in light mode
=> Use white logo in github dark mode

runtime/v2/shim/shim.go, runtime/v2/shim/shim_unix.go, runtime/v2/shim/shim_windows.go
backport of https://github.com/containerd/containerd/pull/5828 (to fix https://github.com/containerd/containerd/issues/5502 for 1.5)
This causes sigint/sigterm to trigger a shutdown of the shim.
It is needed because otherwise the v2 shim hangs system shutdown.
Signed-off-by: Brian Goff <cpuguy83@gmail.com>
(cherry picked from commit 3ffb6a61130298cd27636df2b64a53e2161cdced)
Signed-off-by: Varsha Teratipally <teratipally@google.com>
=> [release/1.5] shimv2: handle sigint/sigterm

cmd/containerd-stress/density.go, cmd/containerd-stress/main.go
allow user to specify what image should be used for containerd-stress.
Signed-off-by: Eric Ernst <eric_ernst@apple.com>
=> containerd-stress: introduce option for specifying image

runtime/v2/binary.go, runtime/v2/shim_load.go
Due to time constraints, carrying https://github.com/containerd/containerd/pull/6535
=> Change file name for shim binary path

contrib/gce/cloud-init/master.yaml, contrib/gce/cloud-init/node.yaml
Prior to running the `kube-node-installation.service`, the containerd
installation should be complete as the k8s installation may have
dependencies on containerd and related binaries (e.g ctr). Add
wants/after systemd directives to ensure
`kube-node-installation.service` will only start after containerd
installation completes.
=> Wait for containerd installation in GCE scripts

docs/cri/architecture.md
I think the following context is misleading in architecture.md.
> `cri` creates and configures the pod’s network namespace using CNI;
cri creates the network namespace by itself, and then configures it using CNI; cri does not create the netns "with CNI".
So it should be better to change the wording for reducing misunderstarndings.
I've confirmed the current implement shows "cri creates the pod’s network namespace, and then configures it using CNI".
https://github.com/containerd/containerd/blob/77d53d2d230c3bcd3f02e6f493019a72905c875b/pkg/cri/server/sandbox_run.go#L127-L170
Previous commit to  architecture.md : https://github.com/containerd/cri/commit/c88e18b907f10ce10aa395631d80fd7ec41d36f3
```diff
+ * `cri` creates and configures the pod’s network namespace using CNI;
- * `cri` …
```
=> Change the context to avoid misunderstandings in architecture.md.

contrib/gce/cloud-init/master.yaml, contrib/gce/cloud-init/node.yaml
This cherrypicks https://github.com/containerd/containerd/pull/6544 to `release-1.5` branch. This will only affect k/k CI and e2e tests. 
Prior to running the `kube-node-installation.service`, the containerd
installation should be complete as the k8s installation may have
dependencies on containerd and related binaries (e.g ctr). Add
wants/after systemd directives to ensure
`kube-node-installation.service` will only start after containerd
installation completes.
=> Wait for containerd installation in GCE scripts [1.5 backport]

.github/workflows/ci.yml, .github/workflows/nightly.yml, .github/workflows/release.yml, .travis.yml, .zuul/playbooks/containerd-build/run.yaml, Vagrantfile, contrib/Dockerfile.test, script/setup/install-critools, script/setup/install-dev-tools
Includes security fixes for crypto/elliptic (CVE-2022-23806), math/big (CVE-2022-23772),
and cmd/go (CVE-2022-23773).
go1.16.14 (released 2022-02-10) includes security fixes to the crypto/elliptic,
math/big packages and to the go command, as well as bug fixes to the compiler,
linker, runtime, the go command, and the debug/macho, debug/pe, net/http/httptest,
and testing packages. See the Go 1.16.14 milestone on our issue tracker for details:
https://github.com/golang/go/issues?q=milestone%3AGo1.16.14+label%3ACherryPickApproved
full diff: https://github.com/golang/go/compare/go1.16.13...go1.16.14
go1.16.13 (released 2022-01-06) includes fixes to the compiler, linker, runtime,
and the net/http package. See the Go 1.16.13 milestone on our issue tracker for
details: …
=> [release/1.4] Update Go to 1.16.14

.github/workflows/ci.yml, .github/workflows/nightly.yml, .github/workflows/release.yml, .zuul/playbooks/containerd-build/integration-test.yaml, .zuul/playbooks/containerd-build/run.yaml, .zuul/playbooks/containerd-build/unit-test.yaml, Vagrantfile, contrib/Dockerfile.test
Includes security fixes for crypto/elliptic (CVE-2022-23806), math/big (CVE-2022-23772),
and cmd/go (CVE-2022-23773).
go1.16.14 (released 2022-02-10) includes security fixes to the crypto/elliptic,
math/big packages and to the go command, as well as bug fixes to the compiler,
linker, runtime, the go command, and the debug/macho, debug/pe, net/http/httptest,
and testing packages. See the Go 1.16.14 milestone on our issue tracker for details:
https://github.com/golang/go/issues?q=milestone%3AGo1.16.14+label%3ACherryPickApproved
full diff: https://github.com/golang/go/compare/go1.16.13...go1.16.14
=> [release/1.5] Update Go to 1.16.14

RELEASES.md, releases/v1.6.0.toml, version/version.go
The release notes introduction remains short without any major theme beyond what is covered by the highlights.
See the generated notes at https://gist.github.com/dmcgowan/12f26f01156b135cb27d3130adfc637b
=> Prepare release notes for v1.6.0

contrib/gce/cloud-init/master.yaml, contrib/gce/cloud-init/node.yaml
This cherrypicks https://github.com/containerd/containerd/pull/6544 to `release-1.4` branch. This will only affect k/k CI and e2e tests. 
Prior to running the `kube-node-installation.service`, the containerd
installation should be complete as the k8s installation may have
dependencies on containerd and related binaries (e.g ctr). Add
wants/after systemd directives to ensure
`kube-node-installation.service` will only start after containerd
installation completes.
=> [release/1.4] backport: Wait for containerd installation in GCE scripts

runtime/v2/runc/manager/manager_linux.go
If containerd-shim-runc-v2 process dead abnormally, such as received
kill -s 9 signal, panic or other unkown reasons, the containerd-shim-runc-v2
server can not reap runc container and forward init process exit event.
This will lead the container leaked in dockerd. When shim dead, containerd
will clean dead shim, here read init process pid and forward exit event
with pid at the same time.
Signed-off-by: Jeff Zvier <zvier20@gmail.com>
=> containerd-shim-runc-v2: return init pid when clean dead shim

platforms/defaults_windows.go, platforms/defaults_windows_test.go, platforms/platforms.go, platforms/platforms_other.go, platforms/platforms_windows.go
When looking into https://github.com/containerd/nerdctl/issues/751 I found that the platform Normalization function is dropping the `OSVersion` because it was marked as depreciated but this value is used throughout the windows https://github.com/containerd/containerd/blob/9c676e98dde995db46841a2c6126ad709e3fc7d7/platforms/defaults_windows.go#L36
There maybe more going on here than just this change.  For example, this may be why this code uses `Ordered` here and then adds the `osVersionPrefix`. 
This change does make it so that nerdctl will work with multiarch manifests but there may need to be more work done here.
=> Use Windows matcher when on Windows platform in all code paths

runtime/v2/runc/v1/service.go
If containerd-shim-runc-v1 process dead abnormally, such as received
kill -s 9 signal, panic or other unkown reasons, the containerd-shim-runc-v1
server can not reap runc container and forward init process exit event.
This will lead the container leaked in dockerd. When shim dead, containerd
will clean dead shim, here read init process pid and forward exit event
with pid at the same time.
Related to: #6402
Signed-off-by: Jeff Zvier <zvier20@gmail.com>
=> containerd-shim-runc-v1: return init pid when clean dead shim

runtime/v2/runc/manager/manager_linux.go, runtime/v2/runc/v1/service.go
If containerd-shim-runc-v1/v2 process dead abnormally, such as received
kill 9 signal, panic or other unkown reasons, the containerd-shim-runc-v1/v2
server can not reap runc container and forward init process exit event.
This will lead the container leaked in dockerd. When shim dead, containerd
will clean dead shim, here read init process pid and forward exit event
with pid at the same time.
cherry-pick #6452 and #6571
=> [release/1.6] runc.v1/v2: return init pid when clean dead shim

runtime/v2/runc/v1/service.go, runtime/v2/runc/v2/service.go
If containerd-shim-runc-v1/v2 process dead abnormally, such as received
kill 9 signal, panic or other unkown reasons, the containerd-shim-runc-v1/v2
server can not reap runc container and forward init process exit event.
This will lead the container leaked in dockerd. When shim dead, containerd
will clean dead shim, here read init process pid and forward exit event
with pid at the same time.
Signed-off-by: Jeff Zvier <zvier20@gmail.com>
-----
Cherry-pick from #6452 and fixes runc.v1 as well
=> [release/1.5] runc.v1/v2: return init pid when clean dead shim

Protobuild.toml, api/Protobuild.toml, api/next.pb.txt, script/setup/install-dev-tools
The new version still supports gogo/protobuf, but can be used with newer
protobuf packages if version = 2.
=> Use containerd/protobuild instead of stevvooe/protobuild

pkg/cri/server/container_update_resources_linux_test.go, pkg/cri/server/service_test.go
These unit tests don't check hugetlb. However by setting
TolerateMissingHugetlbController to false, these tests can't
be run on system without hugetlb (e.g. Debian buildd).
=> cri: relax test for system without hugetlb

oci/spec_opts.go, oci/spec_opts_linux.go, oci/spec_opts_unix.go, oci/spec_opts_windows.go, oci/spec_opts_windows_test.go
Adds support for Windows container images built by Docker
that contain the ArgsEscaped boolean in the ImageConfig. This
is a non-OCI entry that tells the runtime that the Entrypoint
and/or Cmd are a single element array with the args pre-escaped
into a single CommandLine that should be passed directly to
Windows rather than passed as an args array which will be
additionally escaped.
=> Adds support for Windows ArgsEscaped images

cmd/ctr/commands/run/run_windows.go
Adds the ability to override the default user
ContainerUser with a custom user if present in
the image or ContainerAdministrator if needed.
=> Add --user support for ctr run Windows

integration/container_volume_test.go
When mounting a file from the host into a container on windows, the container mount path must resolve to the form "C:/path" or starting the container will fail. If these tests are run from a drive other than the C:/ drive on the host, the path will not be resolved in the expected form, causing failures. This PR updates TestContainerSymlinkVolumes to explicitly mount the expected file on the C drive of the container when running on windows. 
=> Update TestContainerSymlinkVolumes to use windows path

go.mod, go.sum, integration/client/go.mod, integration/client/go.sum, vendor/github.com/Microsoft/hcsshim/internal/winapi/utils.go, vendor/modules.txt
This tag contains a fix for unpacking image content that contains non-ascii characters.
https://github.com/microsoft/hcsshim/releases/tag/v0.8.24
=> [release/1.5] go.mod: Bump hcsshim to v0.8.24

.github/workflows/build-test-images.yml, .github/workflows/ci.yml, .github/workflows/codeql.yml, .github/workflows/images.yml, .github/workflows/nightly.yml, .github/workflows/release.yml, .zuul/playbooks/containerd-build/run.yaml, Vagrantfile, contrib/Dockerfile.test, script/setup/prepare_env_windows.ps1
Addresses [CVE-2022-24921](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-24921)
go 1.16.15
--------------------
go1.16.15 (released 2022-03-03) includes a security fix to the regexp/syntax package,
as well as bug fixes to the compiler, runtime, the go command, and to the net package.
See the Go 1.16.15 milestone on the issue tracker for details:
https://github.com/golang/go/issues?q=milestone%3AGo1.16.15+label%3ACherryPickApproved
full diff: https://github.com/golang/go/compare/go1.16.14...go1.16.15
go 1.17.8
--------------------
go1.17.8 (released 2022-03-03) includes a security fix to the regexp/syntax package,
as well as bug fixes to the compiler, runtime, the go command, and the crypto/x509,
and net packages. See the Go 1.17.8 milestone on the issue tracker for details: …
=> update to go 1.16.15, 1.17.8 to address CVE-2022-24921

.github/workflows/build-test-images.yml, .github/workflows/ci.yml, .github/workflows/codeql.yml, .github/workflows/images.yml, .github/workflows/nightly.yml, .github/workflows/release.yml, .zuul/playbooks/containerd-build/run.yaml, Vagrantfile, contrib/Dockerfile.test, script/setup/prepare_env_windows.ps1
backport of https://github.com/containerd/containerd/pull/6619
Addresses [CVE-2022-24921](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-24921)
go 1.16.15
--------------------
go1.16.15 (released 2022-03-03) includes a security fix to the regexp/syntax package,
as well as bug fixes to the compiler, runtime, the go command, and to the net package.
See the Go 1.16.15 milestone on the issue tracker for details:
https://github.com/golang/go/issues?q=milestone%3AGo1.16.15+label%3ACherryPickApproved
full diff: https://github.com/golang/go/compare/go1.16.14...go1.16.15
go 1.17.8
--------------------
go1.17.8 (released 2022-03-03) includes a security fix to the regexp/syntax package,
as well as bug fixes to the compiler, runtime, the go command, and the crypto/x509,
and net packages. See …
=> [release/1.6] update to go 1.16.15, 1.17.8 to address CVE-2022-24921

.github/workflows/ci.yml, .github/workflows/nightly.yml, .github/workflows/release.yml, .zuul/playbooks/containerd-build/integration-test.yaml, .zuul/playbooks/containerd-build/run.yaml, .zuul/playbooks/containerd-build/unit-test.yaml, Vagrantfile, contrib/Dockerfile.test
Addresses [CVE-2022-24921](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-24921)
go1.16.15 (released 2022-03-03) includes a security fix to the regexp/syntax package,
as well as bug fixes to the compiler, runtime, the go command, and to the net package.
See the Go 1.16.15 milestone on the issue tracker for details:
https://github.com/golang/go/issues?q=milestone%3AGo1.16.15+label%3ACherryPickApproved
full diff: https://github.com/golang/go/compare/go1.16.14...go1.16.15
=> [release/1.5] update to go 1.16.15 to address CVE-2022-24921

docs/PLUGINS.md
I think we are recommending the version 2 configuration file format.
docs/PLUGINS.md is formatted as version 1, which can be confusing.
So I fixed the documentation.
Signed-off-by: Takumasa Sakao <tsakao@zlab.co.jp>
=> Use version 2 configuration format in docs/PLUGINS.md

integration/container_update_resources_test.go
TestUpdateContainerResources_MemoryLimit still uses old method to
check memlimit in cgroup.
BTW, should we enable cgroupsv2 integration test in CI?
=> cri: fix integration test on cgroupsv2 system

pkg/cri/server/container_update_resources_linux_test.go, pkg/cri/server/service_test.go
These unit tests don't check hugetlb. However by setting
TolerateMissingHugetlbController to false, these tests can't
be run on system without hugetlb (e.g. Debian buildd).
Signed-off-by: Shengjing Zhu <zhsj@debian.org>
(cherry picked from commit 352a8f49f7942f588a091ef5c3c49c0c0bb120e8)
=> [release/1.6] cri: relax test for system without hugetlb

.github/workflows/ci.yml, .github/workflows/windows-periodic.yml, integration/addition_gids_test.go, integration/container_log_test.go, integration/pod_dualstack_test.go, integration/pod_hostname_test.go
As suggested at https://github.com/containerd/containerd/issues/4878#issuecomment-814132549, and enhancing #5039.
I figured this was less work and less-costly than actually getting AKS and GCP accounts set up to let me run the CRI tests via the periodic job, and I don't have a regular Windows Server machine at-hand to run the tests locally.
=> Run CRI integration tests in GitHub Actions (Windows)

.github/workflows/windows-periodic.yml
This change ensures that we use a fairly recent and updated version of
the windows images used in testing. The latest tag doesn't always have
the absolute latest image as some images may contain just minor updates,
but most times they are identical to the latest version updated.
=> Use the latest tag for azure images

cmd/containerd-shim/main_unix.go, integration/images/volume-ownership/tools/get_owner_windows.go, runtime/v2/shim/shim.go
I noticed that path information showed up in the version output:
./bin/containerd-shim-runc-v1 -v
./bin/containerd-shim-runc-v1:
Version:  v1.6.0-rc.1
Revision: ad77111.m
Go version: go1.17.2
POSIX guidelines describes; https://www.gnu.org/prep/standards/html_node/_002d_002dversion.html#g_t_002d_002dversion
> The program’s name should be a constant string; don’t compute it from argv[0].
> The idea is to state the standard or canonical name for the program, not its
> file name.
Unfortunately, this code is used by multiple binaries, so we can't fully remove the use of os.Args[0], but let's make a start and just remove the path info.
POSIX guidelines describes; https://www.gnu.org/prep/standards/html_node/_002d_002dversion.html#g_t_002d_002dversion
> The program’s name should be a constant …
=> strip path-info from `-v` (version) output, and implement -v flag for containerd-shim 

integration/client/export_test.go, integration/client/import_test.go
Using a bytes buffer for this test increases the memory usage for the ```client.test``` binary on Windows to over 3 GB. Using a temporary file as a destination for the image keeps memory usage at a reasonable level.
=> Use temp file for export/import test

platforms/platforms_test.go, platforms/platforms_windows_test.go
The output of `platforms.DefaultSpec()` and the normalized version of the
default platform on 32- and 64-bit ARM are not comparable. This test
was added to validate not losing Windows-specific information during
normalize of the platform object, so for now we are moving this to be a
Windows-only test until we resolve the right behavior on ARM.
I noticed that tests on ARM64 were failing and found that #6497 added this
test; I also verified in the openlab test logs this is the new failure.
// cc: @thaJeztah 
=> Update TestNormalize to only test Windows platform

.github/workflows/ci.yml, .github/workflows/windows-periodic.yml
Since #6196, `make binaries` builds containerd-shim-runhcs-v1.exe next to containerd.exe, so there's no need to spend time checking out and building it again.
=> Don't build a second copy of containerd-shim-runhcs-v1.exe

.github/workflows/ci.yml
The GitHub Action is unstable especially on Windows (see #6618).
This change may not address the issue itself, but using the latest
version makes reporting the upstream the issue easier.
=> Upgrade golangci-lint and its GitHub Action

cmd/ctr/commands/commands.go, cmd/ctr/commands/commands_unix.go, cmd/ctr/commands/commands_windows.go, cmd/ctr/commands/run/run_windows.go, integration/main_test.go, integration/windows_device_test.go, oci/spec_opts.go, oci/spec_opts_test.go, pkg/cri/opts/spec_windows.go, pkg/cri/opts/spec_windows_test.go, pkg/cri/server/container_create_windows.go
Fixes: #4878
This implements a mapping from CRI's `Device.HostPath` into OCI's `Windows.Devices`, per discussion in #4878 and https://github.com/kubernetes/kubernetes/issues/97739.
The HostPath is interpreted as `IDType://ID` and those fields are mapped into the same-named fields in `WindowsDevice`. `class/X` is special-cased to `IDType: class, ID: X` as there is existing code in the wild that both [generates](https://github.com/aarnaud/k8s-directx-device-plugin/blob/master/cmd/k8s-device-plugin/main.go#L31) and [consumes](https://github.com/moby/moby/blob/cd049777a21bc17bcedd5eec95ace65bbba833cf/daemon/oci_windows.go#L282-L295) that particular format.
`oci.WithWindowsDevice` helper is added for adding Window Device mounts into OCI container specs for direct users of the `oci` API; on …
=> Handle CRI Device.HostPath on Windows

.github/workflows/ci.yml
The GitHub Action is unstable especially on Windows (see #6618).
This change may not address the issue itself, but using the latest
version makes reporting the upstream the issue easier.
(cherry picked from commit 622a35a4fa7c275ad45618c672d4e7d94ae87102)
=> [release/1.6] cherry-pick: Upgrade golangci-lint and its GitHub Action

cmd/ctr/commands/commands.go, runtime/v2/manager.go, runtime/v2/manager_test.go, runtime/v2/shim/util.go
addresses #6464
Slice returned by `strings.Split("./path/to/shim", ".")` is of
length 2 - first element being the empty string "". Check for this to
see if a runtime provided is relative.
With these changes, the example from #6464 becomes:
```
$ sudo ctr run  --rm --runtime=./containerd-shim-runc-v2 docker.io/library/hello-world:latest hello-world
ctr: failed to start shim: failed to resolve runtime path: invalid runtime name ./containerd-shim-runc-v2, correct runtime name should be either format like `io.containerd.runc.v1` or a full path to the binary: unknown
```
Additionally adds context to the usage for `ctr run --runtime` indicating that
absolute path to shim binary must be provided.
=> ctr: improve error relative shim path error msg

.zuul/playbooks/containerd-build/integration-test.yaml
Since 0d0b2bd4f, our tests need mkfs.xfs.
=> Make mkfs.xfs available on OpenLab's CI environment

.golangci.yml, metadata/boltutil/helpers.go, metadata/containers_test.go, metadata/images_test.go, oci/spec_opts_test.go, services/containers/helpers.go, services/images/helpers.go
Fixes: #6584
`gosec` linter is able to identify issues described in #6584
e.g.
```
$ git revert 54e95e6b880912e489529be120d4ecead80dbd90
[gosec dfc8ca1ec] Revert "fix Implicit memory aliasing in for loop"
2 files changed, 2 deletions(-)
$ make check
+ proto-fmt
+ check
GOGC=75 golangci-lint run
containerstore.go:192:54: G601: Implicit memory aliasing in for loop. (gosec)
containers = append(containers, containerFromProto(&container))
^
image_store.go:132:42: G601: Implicit memory aliasing in for loop. (gosec)
images = append(images, imageFromProto(&image))
^
make: *** [check] Error 1
```
I also disabled following two settings which prevents the linter to show a complete list of issues.
* `max-issues-per-linter (default 50)`
* `max-same-issues (default 3)`
Furthermore enabling `gosec` …
=> Enable gosec linter for golangci-lint

content/testsuite/testsuite.go, docs/ops.md, integration/client/content_test.go, labels/labels.go, metadata/content.go, metadata/content_test.go
Re-introducing the shareable namespace feature
Related PR: #5043
This PR is a re-implementation on the shareable namespace feature that was originally introduced by #5043, which was reverted due to a bug identified during testing.
The new implementation follows and extends the semantic of the existing content sharing policy, by allowing the content of a namespace (if configured as "shareable") to be accessible from other namespaces even "content_sharing_policy" is set to "isolated".
For example:
```
$ cat config.toml
[plugins]
[plugins.bolt]
content_sharing_policy = "isolated"
// 0. label the shared namespace
$ ctr ns label shared containerd.io/namespace.shareable=true
// 1. pull image into shared namespace
$ ctr -n shared i pull docker.io/library/hello-world:latest
// 2. pull the same …
```
=> Add shared content label to namespaces

.zuul.yaml
Since the jobs are relatively stable, we have official ARM binaries and
we could technically still ignore them, we should remove "voting: false"
from them.
=> Make OpenLab's CI jobs blocking

pkg/cri/opts/spec_windows.go, pkg/cri/opts/spec_windows_test.go
Currently when handling 'container_path' elements in container mounts we simply call
filepath.Clean on those paths. However, filepath.Clean adds an extra '.' if the path is a
simple drive letter ('E:' or 'Z:' etc.). Similarly, a drive path like Z:\ is also kept as
it is with an ending '\'. Either of these type of paths cause failures (with incorrect
parameter error) when creating containers via hcsshim. This commit correctly removes the
'.' or '\' at the end of the paths.
Signed-off-by: Amit Barve <ambarve@microsoft.com>
=> Bug fix for mount path handling

script/setup/install-critools
Lets see if this fixes e2e tests
=> [release/1.5] fix critools installation

go.mod, go.sum, integration/client/go.sum, vendor/github.com/containerd/go-cni/.gitignore, vendor/github.com/containerd/go-cni/Makefile, vendor/github.com/containerd/go-cni/namespace_opts.go, vendor/github.com/containerd/go-cni/opts.go, vendor/github.com/containernetworking/plugins/pkg/ns/ns_linux.go, vendor/modules.txt
https://github.com/containerd/go-cni/compare/v1.1.3...v1.1.4
=> moving up to go-cni v1.1.4

pkg/oom/v2/v2.go
When running on cgroup2, currently in a 1-container-pod-with-memory-limit configuration, no `/tasks/oom` events are generated. This is because the pod cgroup and container cgroups both get the same `memory.max` setting, and the `oom` events gets counted to the pod cgroup, while containerd monitors container cgroups for oom events. Fix that by monitoring `oom_kill` instead and reporting that.
`oom_kill` events are counted both to the pod and container cgroups.
My test case was the following kubernetes manifest:
```
apiVersion: apps/v1
kind: Deployment
metadata:
creationTimestamp: null
labels:
app: stress
name: stress
spec:
replicas: 1
selector:
matchLabels:
app: stress
strategy: {}
template:
metadata:
creationTimestamp: null
labels:
app: stress
spec:
containers:
- image: progrium/stress …
```
=> cgroup2: monitor OOMKill instead of OOM to prevent missing container events

pkg/oom/v2/v2.go
Cherry-pick (clean)
- #6323 
> When running on cgroup2, currently in a 1-container-pod-with-memory-limit configuration, no `/tasks/oom` events are generated. This is because the pod cgroup and container cgroups both get the same `memory.max` setting, and the `oom` events gets counted to the pod cgroup, while containerd monitors container cgroups for oom events. Fix that by monitoring `oom_kill` instead and reporting that.
`oom_kill` events are counted both to the pod and container cgroups.
> 
> My test case was the following kubernetes manifest:
> ```
> apiVersion: apps/v1
> kind: Deployment
> metadata:
>   creationTimestamp: null
>   labels:
>     app: stress
>   name: stress
> spec:
>   replicas: 1
>   selector:
>     matchLabels:
>       app: stress
>   strategy: {}
>   template:
> …
```
=> [release/1.5 backport] cgroup2: monitor OOMKill instead of OOM to prevent missing container events

pkg/oom/v2/v2.go
Cherry-pick (clean)
- #6323 
> When running on cgroup2, currently in a 1-container-pod-with-memory-limit configuration, no `/tasks/oom` events are generated. This is because the pod cgroup and container cgroups both get the same `memory.max` setting, and the `oom` events gets counted to the pod cgroup, while containerd monitors container cgroups for oom events. Fix that by monitoring `oom_kill` instead and reporting that.
`oom_kill` events are counted both to the pod and container cgroups.
> 
> My test case was the following kubernetes manifest:
> ```
> apiVersion: apps/v1
> kind: Deployment
> metadata:
>   creationTimestamp: null
>   labels:
>     app: stress
>   name: stress
> spec:
>   replicas: 1
>   selector:
>     matchLabels:
>       app: stress
>   strategy: {}
>   template:
> …
```
=> [release/1.6 backport] cgroup2: monitor OOMKill instead of OOM to prevent missing container events

snapshots/native/native.go
cherry-pick of https://github.com/containerd/containerd/pull/6722
(cherry picked from commit fe426227d4ccb06fc5cbe7f11aa8eefc8d77768a)
=> [release/1.5 backport] native: fix deadlock from leaving transactions open

pkg/cri/opts/container.go
backport of https://github.com/containerd/containerd/pull/6593
(cherry picked from commit ec90efbe99b97ad194fa1586cb0f1ff82bdd4915)
=> [release/1.5 backport] Make the temp mount as ready only in container WithVolumes

snapshots/devmapper/snapshotter.go, snapshots/devmapper/snapshotter_test.go
backport of https://github.com/containerd/containerd/pull/6650
fixes https://github.com/containerd/containerd/issues/6587
Two xfs file systems with same UUID can not be mounted on the same system.
However devmapper snapshots will have same UUID as original filesystem.
This patch fixes the bug by mounting a xfs file system with "nouuid" option.
(cherry picked from commit 0d0b2bd4fe0551464e1ab6adc39077e833be8746)
=> [release/1.6 backport] Mount devmapper xfs file system with "nouuid" option.

.github/workflows/ci.yml, go.mod, go.sum, integration/client/go.sum, pkg/cri/server/container_stats.go, pkg/cri/server/container_stats_list.go, pkg/cri/server/sandbox_stats.go, pkg/cri/server/sandbox_stats_list.go, vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client.go, vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go, vendor/github.com/prometheus/client_golang/prometheus/promhttp/option.go, vendor/modules.txt
backport of https://github.com/containerd/containerd/pull/6690
Update to the recent release (includes a CVE fix) of the Go prom client library
=> [release/1.6 backport] Update prometheus client vendor

go.mod, go.sum, integration/client/go.sum, vendor/github.com/containerd/go-cni/.gitignore, vendor/github.com/containerd/go-cni/Makefile, vendor/github.com/containerd/go-cni/namespace_opts.go, vendor/github.com/containerd/go-cni/opts.go, vendor/github.com/containernetworking/plugins/pkg/ns/ns_linux.go, vendor/modules.txt
backport of https://github.com/containerd/containerd/pull/6721 (re-ran go mod tidy and vendor)
(cherry picked from commit a51da91c1d5808bb3f7cc3cde83d6795d40395fe)
=> [release/1.6 backport] moving up to go-cni v1.1.4

cmd/ctr/commands/images/mount.go
`ctr images mount` with snapshotter option can't get the specified parameter value.
example:
`ctr images mount --snapshotter "aufs" docker.io/library/busybox:latest /mnt`
The actual snapshotter used by the above command is the default snapshotter--"overlayfs".
Signed-off-by: Qian Zhang <cosmoer@qq.com>
=> fix: ctr images mount with snapshotter option can't get snapshotter

runtime/v1/shim/client/client_linux.go, runtime/v2/runc/manager/manager_linux.go, runtime/v2/runc/v1/service.go, services/server/server_linux.go
depends on ~https://github.com/containerd/cgroups/pull/200~ https://github.com/containerd/cgroups/pull/202
All occurrences only passed a PID, so we can use this utility to make the code more symmetrical with their cgroups v2 counterparts.
=> Use cgroups.AddProc() for cgroups v1

.github/workflows/ci.yml, Vagrantfile
Testing containerd on an EL8 variant will be beneficial for enterprise users.
EL9 is coming soon, but we should keep maintaining EL8 CI for a couple of years for long-time stability.
Fixes #6542
=> CI: add Rocky Linux 8

.github/workflows/windows-periodic.yml, script/setup/prepare_env_windows.ps1
This change disables Windows Defender real-time monitoring on the test
workers, and increases the test timeout to 20 minutes (default is 10).
The Windows Defender real time monitoring feature scans any newly
created files for malitious contents. This takes up a lot of CPU when
expanding image archives, which contain lots of files. The CI has been
timing out due to the fact that tests take longer than 10 minutes. This
change should address that issue.
=> [Windows CI] Address some timeout issues

contrib/linuxkit/README.md
The last commit on https://github.com/linuxkit/kubernetes was on Nov 2018.
=> Remove unmaintained contrib/linuxkit

docs/cri/installation.md, docs/getting-started.md
The previous documentation was too much forcusing on the Go API and not useful for users who are not interested in implementing their own containerd client.
It was also recommending the deprecated way (cri-containerd-*.tar.gz) to install containerd and its dependencies.
The new documentation recommends the current official way to install containerd, and provides several links for end users.
This will replace the content of https://containerd.io/docs/getting-started/ after merging containerd/containerd.io#120 .
=> docs/getting-started.md: massive update

go.mod, go.sum
By taking advantage of smarter traversal of dependencies, a
`go mod tidy` using Go 1.18 remove some items from go.sum.
Signed-off-by: Tom Godkin <tomgodkin@pm.me>
=> Upgrade to Go 1.18

.golangci.yml, archive/compression/compression_test.go, namespaces/context_test.go, runtime/v2/shim/shim_test.go
Go 1.17 introduced `t.Setenv`, which automatically restores env changes on test cleanup.
It's quite handy to use instead of `os.Setenv` which requires to restore env manually. Also this PR adds a few changes to linter's config.
=> Use t.Setenv instead of os.Setenv

go.mod, go.sum, integration/client/go.mod, vendor/modules.txt
This is a follow-up to 7ede40c5ca3c8d0565798fa653402357b8c088a0 (https://github.com/containerd/containerd/pull/6739), where we pinned the version of this dependency to prevent go modules rolling it back.
This patch updates the version to use the merge-commit that merged the v1.0 release branch back to the main branch in github.com/opencontainers/image-spec, so that go modules considers it "more recent" and doesn't roll back.
Updating does not introduce changes in the vendored code, as changs of the merged commits were either already in the main branch, or only affected non-code files.
- full diff: https://github.com/opencontainers/image-spec/compare/693428a734f5...c5a74bcca799
- raw diff: https://github.com/opencontainers/image-spec/compare/693428a734f5..c5a74bcca799
Thanks to Tõnis Tiigi …
=> [release/1.6] go.mod: update image-spec to merge-commit of v1 into main

integration/client/go.mod, integration/client/go.sum
make integration currently fails due to outdated go.mod.
=> Run go mod tidy in integration tests

cmd/containerd/builtins.go, cmd/containerd/builtins_tracing.go, cmd/containerd/command/main.go, tracing/plugin/otlp.go
Tracing plugin pulls in a few heavy vendor dependencies, which is not always a requirement.
For cases, when tracing is not needed, this PR adds `no_tracing` build tag to exclude it at build time.
=> Add no_tracing tag

unpacker.go
=> [release/1.5] fix #6054  MaxConcurrentDownloads is not effect when Unpack is true

.github/workflows/windows-periodic.yml
The tty test fails on ltsc2022. Disable that test until we manage to reproduce and fix it.
=> Skip flaky test on Windows

image.go, pkg/cri/server/image_pull.go, pkg/cri/server/service.go, pkg/kmutex/kmutex.go, pkg/kmutex/kmutex_test.go, pkg/kmutex/noop.go, unpacker.go
With current design, the content backend uses key-lock for long-lived
write transaction. If the content reference has been marked for write
transaction, the other requestes on the same reference will fail fast with
unavailable error. Since the metadata plugin is based on boltbd which
only supports single-writer, the content backend can't block or handle
the request too long. It requires the client to handle retry by itself,
like OpenWriter - backoff retry helper. But the maximum retry interval
can be up to 2 seconds. If there are several concurrent requestes fo the
same image, the waiters maybe wakeup at the same time and there is only
one waiter can continue. A lot of waiters will get into sleep and we will
take long time to finish all the pulling jobs and be worse if the image
has many …
=> CRI: improve image pulling performance

cmd/containerd/command/main.go
Snapshotter service returning relative paths confuses the client (i.e.
ctr).
Closes: #6671
Signed-off-by: Eric Lin <linxiulei@gmail.com>
=> Turn paths from cmdline into absolute paths

ADOPTERS.md
We use containerd as our default runtime in Deckhouse Kubernetes Platform.
=> docs: add Deckhouse to the list of adopters

.github/workflows/windows-periodic.yml
Pin the version of the `google-github-actions/upload-cloud-storage`
action library to `0.8.0` to avoid a regression which prevents
test results being uploaded in the Windows periodic workflow.
=> Pin upload-cloud-storage action to 0.8.0 in Windows workflow.

ADOPTERS.md
Containerd support for Windows nodes in AKS has been generally available for k8s clusters 1.20 and greater since mid January. This change updates the wording in ADOPTERS.md
=> ADOPTERS: Update AKS Info

Vagrantfile, metrics/cgroups/common/type.go, metrics/cgroups/metrics_test.go, metrics/cgroups/v1/metrics.go, metrics/cgroups/v2/metrics.go
The Collector.Collect will be the field ns'Collect's callback, which be
invoked periodically with internal lock. And Collector.Add also runs
with ns.Lock in Collector.Lock, which is easy to cause deadlock.
Goroutine X:
ns.Collect
ns.Lock
Collector.Collect
Collector.RLock
Goroutine Y:
Collector.Add
Collector.Lock
ns.Lock
We should use ns.Lock without Collector.Lock in Add.
Fix: #6772
=> metrics/cgroups: fix deadlock issue in Add during Collect

pkg/cri/server/restart.go
This PR tries to decrease time duration to recover when cri service is restarted. Time needed for cri service to load db/sandboxes/containers/images is significantly high when under IO pressure. 
Time to complete recover():
* Without competing IOs + without opt: 21s
* Without competing IOs + with opt: 14s
* Competing IOs + without opt: 3m44s
* Competing IOs + with opt: 33s
Test environment:
* 250 Containers & 150 Images
* BFQ scheduler 
* Kernel version: 5.15.15-amd64
* Disk perf (limited by io.max):  120 riops + 120 wiops
* Competing IO: `fio --filename=file --size=100MB --direct=1 --rw=randrw --bs=4k --ioengine=libaio --iodepth=256 --runtime=3600 --numjobs=4 --time_based --group_reporting --name=iops-test-job --eta-newline=1`
=> Optimize loading performance for cri recover

tracing/plugin/otlp.go
When support for http/protobuf was added, the OTLP tracing processor plugin was mistakenly changed to return a raw OTLP exporter instance. Consequently, the type-assertion to a trace.SpanProcessor inside the tracing pluigin would panic if the processor plugin was configured. Modify the OTLP plugin to return a BatchSpanProcessor derived from the exporter once more.
=> tracing: fix panic on startup when configured

Vagrantfile, metrics/cgroups/common/type.go, metrics/cgroups/metrics_test.go, metrics/cgroups/v1/metrics.go, metrics/cgroups/v2/metrics.go
The Collector.Collect will be the field ns'Collect's callback, which be
invoked periodically with internal lock. And Collector.Add also runs
with ns.Lock in Collector.Lock, which is easy to cause deadlock.
Goroutine X:
ns.Collect
ns.Lock
Collector.Collect
Collector.RLock
Goroutine Y:
Collector.Add
Collector.Lock
ns.Lock
We should use ns.Lock without Collector.Lock in Add.
Fix: #6772
(cherry picked from commit 8a1280b2b604f4eff856b8ac6d0d717f2ccc0550)
------
:cherries: from #6788 
And updated `Stats` mock interface because of the protobuf dependency.
```diff
diff --git a/metrics/cgroups/metrics_test.go b/metrics/cgroups/metrics_test.go
index c362ea3b9..c71ea60a5 100644
--- …
```
=> [release/1.6] metrics/cgroups: fix deadlock issue in Add during Collect

pkg/cri/opts/spec.go
Preserve compatibility with `docker run`: https://github.com/moby/moby/blob/99b2894e17528d0f8640d91bc3c0001e5a99cb3b/daemon/create.go#L279-L282
Some build tools (notably `docker run` and `docker commit`) creates a string slice with an empty string as the first member. This gets stripped in `docker run` and works transparently if you use docker/moby as container runtime. Does not work so well in the containerd, unfortunately.
=> Do not append []string{""} to command to preserve Docker compatibility

pkg/netns/netns_linux.go
Seeing a flake in k8s e2e summary test that should not happen where network stats do not exist as reported by cadvisor. While debugging ran into docs indicating rand.Reader.Read may return < n bytes, may return 0 with no err. .. Per suggestion from @fuweid moved to rand.Read()...  While in here should not hurt to check if the "random" generated namespace already exists, because in use or because did not get torn down. If the later and still exists should do further investigation for tearing it down. 
`https://github.com/kubernetes/kubernetes/issues/109082`
=> check for duplicate nspath possibilities

snapshots/devmapper/pool_device_test.go
fixed #6627 
While executing mke2fs, 'Not enough space to build proposed filesystem while setting up superblock' is happend.
extend the disk size.
On the original issue #6627 , the architecture (ppc64le) is the cause, but it is reproduced on Ubuntu 20.04 on x86-64 and not reproduced on Ubuntu18.04 on ppc64le.
So, I think it is caused by the change in Ubuntu version.
`make root-test` result is below.
ubuntu20.04 on x86-64 (EC2)
```
+ root-test
...
--- FAIL: TestPoolDevice (1.65s)
--- FAIL: TestPoolDevice/MakeFileSystem (0.01s)
pool_device_test.go:245:
Error Trace:    pool_device_test.go:245
pool_device_test.go:103
Error:          Expected nil, but got: &exec.ExitError{ProcessState:(*os.ProcessState)(0xc0002677d0), Stderr:[]uint8(nil)}
Test:           TestPoolDevice/MakeFileSystem
Messages: …
```
=> fix pool_device_test

cmd/containerd/builtins.go, leases/plugin/local.go, pkg/cri/cri.go, plugin/plugin.go, plugin/plugin_test.go, runtime/restart/monitor/monitor.go, services/leases/service.go, services/services.go
Create lease plugin type to separate lease manager from services plugin. This allows other service plugins to depend on the lease manager.
=> Move lease manager plugin to separate package

.github/workflows/build-test-images.yml, .github/workflows/ci.yml, .github/workflows/codeql.yml, .github/workflows/images.yml, .github/workflows/nightly.yml, .github/workflows/release.yml, .zuul/playbooks/containerd-build/integration-test.yaml, .zuul/playbooks/containerd-build/run.yaml, .zuul/playbooks/containerd-build/unit-test.yaml, Vagrantfile, contrib/Dockerfile.test
go1.18.1 (released 2022-04-12) includes security fixes to the crypto/elliptic,
crypto/x509, and encoding/pem packages, as well as bug fixes to the compiler,
linker, runtime, the go command, vet, and the bytes, crypto/x509, and go/types
packages. See the Go 1.18.1 milestone on the issue tracker for details:
https://github.com/golang/go/issues?q=milestone%3AGo1.18.1+label%3ACherryPickApproved
Includes fixes for:
- CVE-2022-24675 (https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-24675)
- CVE-2022-27536 (https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-27536)
- CVE-2022-28327 (https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-28327)
go1.17.9 (released 2022-04-12) includes security fixes to the crypto/elliptic
and encoding/pem packages, as well as bug fixes to the linker …
=> update golang to 1.18.1, 1.17.9

.github/workflows/ci.yml, .github/workflows/nightly.yml, .github/workflows/release.yml, .zuul/playbooks/containerd-build/integration-test.yaml, .zuul/playbooks/containerd-build/run.yaml, .zuul/playbooks/containerd-build/unit-test.yaml, Vagrantfile, contrib/Dockerfile.test
go1.17.9 (released 2022-04-12) includes security fixes to the crypto/elliptic
and encoding/pem packages, as well as bug fixes to the linker and runtime. See
the Go 1.17.9 milestone on the issue tracker for details:
Includes fixes for:
- CVE-2022-24675 (https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-24675)
- CVE-2022-28327 (https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-28327)
=> [release/1.5] update golang to 1.17.9

contrib/seccomp/kernelversion/kernel_linux.go, contrib/seccomp/kernelversion/kernel_linux_test.go, contrib/seccomp/seccomp_default.go
Allow `ptrace(2)` by default for kernel >= 4.8
Fixes: #6802 
`kernel_linux.go` and `kernel_linux_test.go` are copied from moby project under:
https://github.com/moby/moby/tree/v20.10.14/profiles/seccomp
Testing was performed on 5.10 kernel with `strace` tool.
=> allow ptrace(2) by default for kernel >= 4.8

metrics/cgroups/v1/metrics.go, metrics/cgroups/v2/metrics.go, metrics/metrics.go
- When containerd collects metrics from shim's [Stat API](https://github.com/containerd/containerd/blob/d3aa7ee9f065d5d8773b4b38124ad6e3d6634dc2/runtime/v2/task/shim.proto#L49), there is no timeout set:
https://github.com/containerd/containerd/blob/d3aa7ee9f065d5d8773b4b38124ad6e3d6634dc2/metrics/cgroups/v2/metrics.go#L118
https://github.com/containerd/containerd/blob/d3aa7ee9f065d5d8773b4b38124ad6e3d6634dc2/metrics/cgroups/v1/metrics.go#L125
-  If the shim process is not responsive, the request blocks there, `Collect.Collect()` blocks. https://github.com/containerd/containerd/blob/d3aa7ee9f065d5d8773b4b38124ad6e3d6634dc2/metrics/cgroups/v2/metrics.go#L92
- This causes leaked goroutines and memory. Requests to prometheus metrics /v1/metrics to hangs when there is a "bad shim"
- Launch …
=> Set timeout when collecting metrics from shim's Stat

integration/client/restart_monitor_test.go, runtime/restart/monitor/change.go, runtime/restart/monitor/monitor.go, runtime/restart/restart.go, runtime/restart/restart_test.go
TL;DR: In order to be compatible with the restart policies of docker in nerdctl, we need enhance containerd's restart manager by adding a label:
`containerd.io/restart.policy`, `containerd.io/restart.count`.
Discussed in https://github.com/containerd/nerdctl/issues/945
```
policy, _ := restart.NewPolicy("on-failure")
container, err := client.NewContainer(ctx, id,
restart.WithStatus(containerd.Running),
restart.WithPolicy(policy))
```
=> Add restart policy for enhanced restart manager

remotes/docker/fetcher.go
Registry URLs are important and should be logged even the logging level is info.
Fixes #5486.
=> remotes/docker: log registry URLs as info instead of debug

runtime/restart/monitor/monitor.go
build main and run containerd failed.
```
INFO[2022-04-20T05:35:40.153277386Z] loading plugin "io.containerd.grpc.v1.sandbox-controllers"...  type=io.containerd.grpc.v1
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x98 pc=0x55d06830b312]
goroutine 45 [running]:
github.com/containerd/containerd/runtime/restart/monitor.(*monitor).monitor(0xc00011a050, {0x55d0693c0a40, 0xc00003a0c0})
/home/jun/Documents/workspace/containerd/runtime/restart/monitor/monitor.go:226 +0x272
github.com/containerd/containerd/runtime/restart/monitor.(*monitor).reconcile.func1()
/home/jun/Documents/workspace/containerd/runtime/restart/monitor/monitor.go:187 +0xab
created by …
```
=> fix nil pointer panic for monitor

runtime/restart/monitor/monitor.go
Report of @AkihiroSuda https://github.com/containerd/containerd/pull/6830#issuecomment-1103705037
I'm sorry for misunderstanding https://github.com/containerd/containerd/commit/9503d7219e2adb5906f4c396f3f47e5eb45272c5#diff-a9d90e82d0fee932f0437ab217a8ef14e4a56b4be02321de5193de0ad98e20f9L239-L249
For the case when `Task` returns not found and the restart desired to running, we need to continue to restart the container.
=> fix the restart desired to running when task not found

ADOPTERS.md
Add Google Container-Optimized OS to the list of Adopters 
since COS is widely used in testing.
=> Add Container-Optimized OS into Adopters

pkg/cri/store/container/container.go
cri: close fifos when container is deleted
Fixes: #6834
<details><summary>Testing</summary>
<p>
```
$ sudo critest -ginkgo.focus 'runtime should support removing created container'
critest version: 1.20.0-24-g53ad8bb7
Running Suite: CRI validation
=============================
Random Seed: 1650576768 - Will randomize all specs
Will run 1 of 97 specs
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
------------------------------
[k8s.io] Container runtime should support basic operations on container
runtime should support removing created container [Conformance]
/tmp/tmp.KuBJ4DNF8R/cri-tools/pkg/validate/container.go:111
[BeforeEach] [k8s.io] Container
/tmp/tmp.KuBJ4DNF8R/cri-tools/pkg/framework/framework.go:50
[BeforeEach] [k8s.io] Container …
```
=> cri: close fifos when container is deleted

integration/main_test.go, integration/sandbox_clean_remove_windows_test.go
Adds an equivalent TestSandboxRemoveWithoutIPLeakage for Windows, in which we assert that the IPs are not leaked when a Pod's HNS namespace dissapears and the Pod is deleted afterwards.
The test currently fails, as it seems that the Pod's IP remains "in use" after the Pod is deleted.
Sample output: https://paste.ubuntu.com/p/t47hmr2RyB/
=> integration: Adds Windows equivalent for TestSandboxRemoveWithoutIPLeakage

tracing/plugin/otlp.go
Backport of #6789
---
When support for http/protobuf was added, the OTLP tracing processor
plugin was mistakenly changed to return a raw OTLP exporter instance.
Consequently, the type-assertion to a trace.SpanProcessor inside the
tracing pluigin would panic if the processor plugin was configured.
Modify the OTLP plugin to return a BatchSpanProcessor derived from the
exporter once more.
Signed-off-by: Cory Snider <csnider@mirantis.com>
(cherry picked from commit 927b34e41e2ed0050dbeccbc7c3dffaeb2969949)
=> [release/1.6] tracing: fix panic on startup when configured

docs/cri/config.md, pkg/cri/config/config.go, pkg/cri/config/config_test.go, pkg/cri/server/container_create_linux.go, pkg/cri/server/container_create_linux_test.go
This commit adds a flag that enable all devices whitelisting when privileged_without_host_devices is already enabled.
Fixes #5679
Signed-off-by: Dat Nguyen <dnguyen7@atlassian.com>
=> Add flag to allow oci.WithAllDevicesAllowed on PrivilegedWithoutHostDevices

images/image.go
Signed-off-by: Zhang Kang [Kang.Zhang@intel.com](mailto:Kang.Zhang@intel.com)
=> images/image.go: typo

integration/build_local_containerd_helper_test.go, integration/build_local_containerd_helper_test_linux.go, integration/image_pull_timeout_test.go, pkg/cri/config/config.go, pkg/cri/config/config_unix.go, pkg/cri/config/config_windows.go, pkg/cri/server/image_pull.go
Kubelet sends the PullImage request without timeout, because the image size
is unknown and timeout is hard to defined. The pulling request might run
into 0B/s speed, if containerd can't receive any packet in that connection.
For this case, the containerd should cancel the PullImage request.
Although containerd provides ingester manager to track the progress of pulling
request, for example `ctr image pull` shows the console progress bar, it needs
more CPU resources to open/read the ingested files to get status.
In order to support progress timeout feature with lower overhead, this
patch uses http.RoundTripper wrapper to track active progress. That
wrapper will increase active-request number and return the
countingReadCloser wrapper for http.Response.Body. Each bytes-read
can be count and …
=> feature: support image pull progress timeout

.cirrus.yml
"uname -a" includes its hostname, which could be
cirrus-task-6102504847966208, cirrus-task-6665454801387520, ...
This is unnecessary invalidating the cache.
=> Don't use "uname -a" as Cirrus CI's cache key

go.mod, go.sum, integration/client/go.mod, integration/client/go.sum, vendor/github.com/opencontainers/selinux/go-selinux/rchcon.go, vendor/github.com/opencontainers/selinux/go-selinux/rchcon_go115.go, vendor/modules.txt
Full Changelog:
https://github.com/opencontainers/selinux/compare/v1.10.0...v1.10.1
Specifically patch https://github.com/opencontainers/selinux/pull/173 which fixes the issue: https://github.com/containerd/containerd/issues/6767
Signed-off-by: Nabeel Rana <nabeelnrana@gmail.com>
=> Bump opencontainers/selinux from 1.10.0 to 1.10.1

go.mod, go.sum, integration/client/go.sum, vendor/github.com/containerd/go-cni/.golangci.yml, vendor/github.com/containerd/go-cni/deprecated.go, vendor/github.com/containerd/go-cni/opts.go, vendor/github.com/containernetworking/cni/libcni/conf.go, vendor/github.com/containernetworking/cni/pkg/version/plugin.go, vendor/modules.txt
Cherry-pick #6868 
Signed-off-by: Michael Zappa <Michael.Zappa@stateless.net>
(cherry picked from commit 5d0730370db45eea9d72bfc67c713cc5b8ba559b)
=> [release/1.6] Update go-cni to v1.1.5 backported due to conflict in go.mod

cmd/ctr/commands/commands.go, cmd/ctr/commands/run/run_unix.go, docs/cri/config.md, docs/man/containerd-config.toml.5.md, oci/spec_opts_linux.go, oci/spec_opts_nonlinux.go, pkg/cri/config/config.go, pkg/cri/server/blockio_linux.go, pkg/cri/server/blockio_stub_linux.go, pkg/cri/server/container_create_linux.go, services/tasks/blockio_default.go, services/tasks/blockio_linux.go, services/tasks/local.go, vendor/github.com/intel/goresctrl/pkg/blockio/blockio.go, vendor/github.com/intel/goresctrl/pkg/blockio/config.go, vendor/github.com/intel/goresctrl/pkg/blockio/kubernetes.go, vendor/github.com/intel/goresctrl/pkg/blockio/oci.go, vendor/github.com/intel/goresctrl/pkg/cgroups/cgroupblkio.go, vendor/github.com/intel/goresctrl/pkg/cgroups/cgroupcontrol.go, vendor/github.com/intel/goresctrl/pkg/cgroups/cgroupid.go, vendor/github.com/intel/goresctrl/pkg/cgroups/cgroupid_linux.go, vendor/github.com/intel/goresctrl/pkg/cgroups/cgroupid_other.go, vendor/github.com/intel/goresctrl/pkg/cgroups/cgrouppath.go, vendor/github.com/intel/goresctrl/pkg/cgroups/fsi.go, vendor/github.com/intel/goresctrl/pkg/cgroups/fsimock.go, vendor/github.com/intel/goresctrl/pkg/cgroups/fsios.go, vendor/modules.txt
This PR implements support for the cgroup blockio controller.
**How it is used**
- User defines blockio classes, for example: ThrottledIO and LowLatency. Class names are not restricted, and the number of classes is not limited.
- Each class contains sets of devices (list of filenames, wildcards allowed) and blockio parameters for each set. For example, `/etc/containers/blockio.yaml` contains:
```
Classes:
ThrottledIO:
- Devices:
- /dev/vd[a-z]
ThrottleReadBps: 50M
ThrottleWriteBps: 10M
```
- User launches containerd with the blockio plugin configured to read the blockio class configuration file. For example, `/etc/containerd/config.toml` contains:
```
[plugins]
[plugins."io.containerd.internal.v1.blockio"]
config_file = "/etc/containers/blockio.yaml"
```
- User annotates container(s) in a …
=> Support for cgroups blockio

go.mod, go.sum, integration/client/go.sum, vendor/github.com/opencontainers/selinux/go-selinux/rchcon.go, vendor/github.com/opencontainers/selinux/go-selinux/rchcon_go115.go, vendor/modules.txt
- backport of https://github.com/containerd/containerd/pull/6865
- fixes https://github.com/containerd/containerd/issues/6767
- addresses https://github.com/coreos/fedora-coreos-tracker/issues/1138
(cherry picked from commit ae29594d0bcd00e19cc3e0a0a7858dc6ab8f0544)
=> [release/1.6 backport] Bump opencontainers/selinux from 1.10.0 to 1.10.1

docs/getting-started.md
Signed-off-by: Mark Rossetti <marosset@microsoft.com>
These instructions used to be hosted at https://v1-22.docs.kubernetes.io/docs/setup/production-environment/container-runtimes/#containerd but have been removed. 
It makes more sense to host them here.
=> docs: Adding windows installation steps to getting-started.md

integration/client/client_test.go, integration/client/container_linux_test.go
This test tends to fail under Cirrus CI + Vagrant. Skipping for now
since running the test on GitHub Actions would be suffice.
=> Make Cirrus CI tests more stable

.github/workflows/ci.yml, .github/workflows/nightly.yml, .github/workflows/release.yml, .github/workflows/release/Dockerfile, contrib/seccomp/seccomp_default.go
- seccomp: support riscv64
- release/Dockerfile: update Ubuntu to 22.04 for supporting riscv64
- CI: add riscv64 builds
runc needs https://github.com/opencontainers/runc/pull/3446 (https://github.com/opencontainers/runc/pull/3446/commits/f3620f37efffb23c5a0848714377a1f2b6a15942)
=> Support RISC-V 64

metadata/db.go, metadata/db_test.go, metadata/gc.go, metadata/gc_test.go
Adds a registration function to metadata which allows plugins to register resources to be garbage collected. These resources allow defining resources types which are ephemeral and stored outside the metadata plugin without extending it. The garbage collection of these resources will not fail the metadata gc process if their removal fails. These resources may be referenced by existing metadata store resources but may not be used to reference metadata store resources for the purpose of preventing garbage collection.
This is split out from my work on the new image transfer service which will use this for tracking progress streams. This could also be used in the implementation of a mount and network manager after the sandbox API is merged.
=> Add collectible resources to metadata gc

.mailmap, releases/v1.6.4.toml, version/version.go
See generated notes https://gist.github.com/dmcgowan/7604d2f3cac5da03a378f5716a8c40db
=> Prepare release notes for 1.6.4

docs/snapshotters/devmapper.md, snapshots/devmapper/metadata.go
some small nits/fixes on devmapper snapshotter documentation.
Also, curious if there is any interest in expanding these docs to include something like https://docs.docker.com/storage/storagedriver/device-mapper-driver/#how-the-devicemapper-storage-driver-works , or perhaps just including a reference to docker's devmapper documentation (can do that in this or subsequent PR).
=> devmapper docs: small fixes

.github/workflows/windows-periodic.yml
Following kubernetes-sigs/cri-tools#910 the Ginkgo reporters are left
configured with default settings and thus do not generate a JUnit report
file unless we explicitly pass a path for the outfile in the Windows
workflow when calling critest.exe.
=> Pass explicit JUnit outfile to critest.exe in Windows workflow.

Vagrantfile
Add /vagrant to "safe directory" global git config so Vagrant runs work
properly again.
Example failure: https://cirrus-ci.com/task/6459485030973440?logs=vagrant_up#L1092
(Building containerd via the Makefile runs git commands that get a `fatal: unsafe repository` error due to a CVE fix in recent versions of git)
=> (Vagrant CI) Enable git commands due to git CVE fix

.github/workflows/build-test-images.yml, .github/workflows/ci.yml, .github/workflows/codeql.yml, .github/workflows/images.yml, .github/workflows/nightly.yml, .github/workflows/release.yml, .zuul/playbooks/containerd-build/integration-test.yaml, .zuul/playbooks/containerd-build/run.yaml, .zuul/playbooks/containerd-build/unit-test.yaml, Vagrantfile, contrib/Dockerfile.test
go1.18.2 (released 2022-05-10) includes security fixes to the syscall package,
as well as bug fixes to the compiler, runtime, the go command, and the crypto/x509,
go/types, net/http/httptest, reflect, and sync/atomic packages. See the Go 1.18.2
milestone on the issue tracker for details:
https://github.com/golang/go/issues?q=milestone%3AGo1.18.2+label%3ACherryPickApproved
Full diff: http://github.com/golang/go/compare/go1.18.1...go1.18.2
Includes fixes for:
- CVE-2022-29526 (http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-29526);
(description at https://go.dev/issue/52313).
go1.17.10 (released 2022-05-10) includes security fixes to the syscall package,
as well as bug fixes to the compiler, runtime, and the crypto/x509 and net/http/httptest
packages. See the Go 1.17.10 milestone on …
=> update golang to 1.18.2, 1.17.10

Vagrantfile
Due to a git CVE, we need to mark /vagrant as a "safe" directory
otherwise building containerd inside Vagrant fails with git command
failures.
Backport of #6915 for `release/1.6`
=> [release/1.6] Allow git commands in Vagrantfile

Vagrantfile
Due to a git CVE, we need to mark /vagrant as a "safe" directory
otherwise building containerd inside Vagrant fails with git command
failures.
Cherry-pick of #6941
=> [release/1.5] cherry-pick: Allow git commands in Vagrantfile

runtime/v2/runc/manager/manager_linux.go, runtime/v2/shim/shim.go
As we know, shim starts twice. The first time we execute the shim with the
`start` arguments, the `-debug` argument is passed to the shim
process correctly. But the second time we execute shim, the debug flag
is ignored.
Signed-off-by: wllenyj <wllenyj@linux.alibaba.com>
=> shim: fix debug flag not working

.github/workflows/ci.yml
This fixes the problem that only one upload is kept per artifact name.
=> Separate windows-2019 and windows-2022 test results

pkg/cri/opts/spec_windows.go, pkg/cri/opts/spec_windows_test.go
Currently when handling 'container_path' elements in container mounts we simply call
filepath.Clean on those paths. However, filepath.Clean adds an extra '.' if the path is a
simple drive letter ('E:' or 'Z:' etc.). These type of paths cause failures (with incorrect
parameter error) when creating containers via hcsshim. This commit checks for such paths
and doesn't call filepath.Clean on them.
It also adds a new check to error out if the destination path is a C drive and moves the
dst path checks out of the named pipe condition.
Signed-off-by: Amit Barve <ambarve@microsoft.com>
(cherry picked from commit bfde58e3cdc0d16b24342886db319a2a2b0964b9)
Signed-off-by: Amit Barve <ambarve@microsoft.com>
=> [release/1.6] Bug fix for mount path handling

contrib/ansible/README.md
Update k8s doc url 
The 'http://kubernetes.io/docs/admin/addons/' seems moved to 'https://kubernetes.io/docs/concepts/cluster-administration/addons/'
=> update doc url about k8s

cmd/ctr/commands/content/fetch.go
=> cmd/ctr/commands/content: fix typo in fetch command usage

archive/compression/benchmark_test.go, archive/compression/compression_test.go
The benchmarks were deleted in #2640 but we could use that to evaluate
zstd further.
=> Restore decompression benchmarks

go.mod, go.sum, integration/client/go.mod, integration/client/go.sum, runtime/opts/opts_linux.go, services/server/server_linux.go, vendor/github.com/containerd/cgroups/README.md, vendor/github.com/containerd/cgroups/blkio.go, vendor/github.com/containerd/cgroups/cgroup.go, vendor/github.com/containerd/cgroups/control.go, vendor/github.com/containerd/cgroups/opts.go, vendor/github.com/containerd/cgroups/paths.go, vendor/github.com/containerd/cgroups/rdma.go, vendor/github.com/containerd/cgroups/systemd.go, vendor/github.com/containerd/cgroups/utils.go, vendor/github.com/containerd/cgroups/v2/devicefilter.go, vendor/github.com/containerd/cgroups/v2/ebpf.go, vendor/github.com/containerd/cgroups/v2/errors.go, vendor/github.com/containerd/cgroups/v2/manager.go, vendor/github.com/containerd/cgroups/v2/utils.go, vendor/github.com/stretchr/testify/assert/assertion_compare.go, vendor/github.com/stretchr/testify/assert/assertion_format.go, vendor/github.com/stretchr/testify/assert/assertion_forward.go, vendor/github.com/stretchr/testify/assert/assertion_order.go, vendor/github.com/stretchr/testify/assert/assertions.go, vendor/github.com/stretchr/testify/require/require.go, vendor/github.com/stretchr/testify/require/require_forward.go, vendor/modules.txt
This commit brings the resource leak fix below.
https://github.com/containerd/cgroups/pull/212
The upgrade PR in main was #6498. I didn't cherry-pick the commit due
to conflicts.
=> [release/1.5] upgrade containerd/cgroups to v1.0.3

docs/getting-started.md
PowerShell doesn't treat the variable implicitly as a string and it causes the install to fail if you're copy pasting from the docs:
I just wrapped the version string in quotes and bumped it to the latest release.
Signed-off-by: Shaun Lawrie <beatbophiphop@gmail.com>
=> Fix Windows install powershell script

services/server/config/config.go
The previous wording was causing confusion.
Fix moby/moby#43628
=> config: improve config v1 deprecation message

snapshots/overlay/overlay.go
When upperdirLabel specified, overlay Update will throw tx closed error since Commit is invoked before GetInfo
Related: #5624
=> Fix tx closed error when upperdirlabel specified

services/server/config/config.go
Cherry-pick #6972 (clean)
- - -
The previous wording was causing confusion.
Fix moby/moby#43628
=> [release/1.6] config: improve config v1 deprecation message

services/server/config/config.go
Cherry-pick #6972 (clean)
- - -
The previous wording was causing confusion.
Fix moby/moby#43628
=> [release/1.5] config: improve config v1 deprecation message

archive/tar.go
Cherry-pick https://github.com/containerd/containerd/pull/6982
Cherry-pick was not clean:
```diff
diff --git a/archive/tar.go b/archive/tar.go
index d54759641..eca6316b0 100644
--- a/archive/tar.go
+++ b/archive/tar.go
@@ -19,6 +19,7 @@ package archive
import (
"archive/tar"
"context"
+       "fmt"
"io"
"os"
"path/filepath"
```
=> [release/1.5] archive: add human-readable hint to Lchown error

cmd/ctr/commands/run/run_unix.go
The `ctr run` and `ctr container create` commands use `--label` to specify the labels, not `--labels`.
```bash
--label value                     specify additional labels (e.g. foo=bar)
```
=> ctr: fix label args used in NewContainer

Makefile
There is no Makefile target for `checkprotos` -- this is a typo of the `check-protos` target. This PR fixes those references.
Signed-off-by: Ethan Lowman <ethan.lowman@datadoghq.com>
=> build: Fix references to check-protos target in Makefile

go.mod, metadata/sandbox.go, sandbox.go
PR #6366 implemented a tree-wide change to replace github.com/pkg/errors
to errors. The new sandbox API PR #6703 had few errors.Wrap*() leftovers
and pulled github.com/pkg/errors back. This commit replaces those
leftovers by following the pattern in #6366.
Signed-off-by: Mikko Ylinen <mikko.ylinen@intel.com>
=> sandbox: replace github.com/pkg/errors with native errors

pkg/cri/io/logger_test.go, pkg/cri/server/container_create_linux_test.go, pkg/cri/server/container_create_test.go, pkg/cri/server/container_list_test.go, pkg/cri/server/container_remove_test.go, pkg/cri/server/container_start_test.go, pkg/cri/server/container_stats_list_linux_test.go, pkg/cri/server/container_status_test.go, pkg/cri/server/container_stop_test.go, pkg/cri/server/container_update_resources_linux_test.go, pkg/cri/server/helpers_linux_test.go, pkg/cri/server/helpers_test.go, pkg/cri/server/image_pull_test.go, pkg/cri/server/sandbox_list_test.go, pkg/cri/server/sandbox_run_linux_test.go, pkg/cri/server/sandbox_run_test.go, pkg/cri/server/sandbox_status_test.go, pkg/cri/server/sandbox_stop_test.go, pkg/cri/store/container/status_test.go, pkg/cri/store/image/image_test.go, pkg/cri/util/image_test.go
A majority of the tests in /pkg/cri are testing/validating multiple things per test (generally spec or options validations). This flow lends itself well to using *testing.T's Run method to run each thing as a subtest so `go test` output can actually display which subtest failed/passed.
Some of the tests in the packages in pkg/cri already did this, but a bunch simply logged what testcase was currently running without invoking `t.Run()`.
Thanks to @samuelkarp for suggesting this on another PR https://github.com/containerd/containerd/pull/6996#discussion_r884055199. I'm not married to the "TestCase" prefix for the subtest names, but it was already used for the log and a couple other `t.Run()` uses so mostly following how things already were.
=> Use t.Run for /pkg/cri tests

Makefile
- relates to https://github.com/urfave/cli/pull/1383
- follow-up to https://github.com/containerd/containerd/pull/6997
(first commit is from https://github.com/containerd/containerd/pull/6997 - I'll rebase once that's merged)
We only need the `ToMan()` as part of the `bin/gen-manpages` binary, which
generates the man-pages; other binaries don't use this code, so we can
set the `urfave_cli_no_docs` build-tag to exclude `cpuguy83/md2man` and
`russross/blackfriday` (and other dependencies) from the binaries:
Before:
ls -lh bin
total 149M
-rwxr-xr-x 1 root root  49M May 27 10:12 containerd
-rwxr-xr-x 1 root root 6.1M May 27 10:13 containerd-shim
-rwxr-xr-x 1 root root 8.1M May 27 10:13 containerd-shim-runc-v1
-rwxr-xr-x 1 root root 8.2M May 27 10:13 containerd-shim-runc-v2
-rwxr-xr-x 1 root …
=> Makefile: use urfave_cli_no_docs for binaries that don't need it

contrib/ansible/cri-containerd.yaml, docs/cri/config.md, docs/cri/crictl.md, integration/client/client_test.go, integration/client/image_test.go, integration/client/lease_test.go, integration/common.go, integration/image_list.sample.toml, pkg/cri/config/config_unix.go, pkg/cri/config/config_windows.go
A friend try to load images of kube firstly by `kubeadm config image list` and run `kubeadm init`, but he failed to start the cluster as GFW.
```
[root@paco ~]# ./kubeadm config images list
k8s.gcr.io/kube-apiserver:v1.24.1
k8s.gcr.io/kube-controller-manager:v1.24.1
k8s.gcr.io/kube-scheduler:v1.24.1
k8s.gcr.io/kube-proxy:v1.24.1
k8s.gcr.io/pause:3.7
k8s.gcr.io/etcd:3.5.3-0
k8s.gcr.io/coredns/coredns:v1.8.6
```
> kuberuntime_sandbox.go:70] "Failed to create sandbox for pod" err="rpc error: code = Unknown desc = failed pulling image \"k8s.gcr.io/pause:3.6\": Error response from daemon: Get \"https://k8s.gcr.io/v2/\": read tcp 127.0.0.1:57370->127.0.0.1:9880: read: connection reset by peer" pod="kube-system/etcd-k1"
A simple workaround for him is 
```
docker tag k8s.gcr.io/pause:3.7 …
```
=> promote pause image to 3.7 (sync with kube v1.24)

pkg/cri/store/image/image.go, reference/docker/sort.go, reference/docker/sort_test.go
`reference` package should not export Docker-inherited reference logic, the `reference/docker` package is for that. The `reference` package has a smaller and less opinionated scope.
=> Move docker reference logic to reference/docker package

integration/main_test.go, integration/windows_hostprocess_test.go, pkg/cri/server/container_create_windows.go, pkg/cri/server/container_create_windows_test.go
HostProcess containers require every container in the pod to be a HostProcess container and have the corresponding security context field set. The Kubelet usually enforces this so we'd error before even getting here, but we recently found a bug in that logic so better to be safe than sorry.
=> Add validations for Windows HostProcess CRI configs

go.mod, go.sum, integration/client/go.sum, pkg/cri/server/testing/fake_cni_plugin.go, vendor/github.com/containerd/go-cni/Makefile, vendor/github.com/containerd/go-cni/cni.go, vendor/github.com/containernetworking/cni/pkg/invoke/exec.go, vendor/modules.txt
Bringing in latest containerd/go-cni with latest cni to resolve:
https://github.com/containernetworking/cni/issues/899
=> update go-cni/for cni update fixing plugins that don't respond with version

BUILDING.md
The command for stressing containerd using `containerd-stress`, as specified in `BUILDING.md`, currently has `-t 120` to run stress test for 2 hours. However, the actual command seems to require the duration to be specified using the `-d` flag.
Signed-off-by: SilverSoldier <soldatargent@gmail.com>
=> Fix containerd-stress duration flag

.github/workflows/build-test-images.yml, .github/workflows/ci.yml, .github/workflows/codeql.yml, .github/workflows/images.yml, .github/workflows/nightly.yml, .github/workflows/release.yml, .zuul/playbooks/containerd-build/integration-test.yaml, .zuul/playbooks/containerd-build/run.yaml, .zuul/playbooks/containerd-build/unit-test.yaml, Vagrantfile, contrib/Dockerfile.test, contrib/fuzz/oss_fuzz_build.sh
go1.18.3 (released 2022-06-01) includes security fixes to the crypto/rand,
crypto/tls, os/exec, and path/filepath packages, as well as bug fixes to the
compiler, and the crypto/tls and text/template/parse packages. See the Go
1.18.3 milestone on our issue tracker for details:
https://github.com/golang/go/issues?q=milestone%3AGo1.18.3+label%3ACherryPickApproved
update golang to 1.17.11
go1.17.11 (released 2022-06-01) includes security fixes to the crypto/rand,
crypto/tls, os/exec, and path/filepath packages, as well as bug fixes to the
crypto/tls package. See the Go 1.17.11 milestone on our issue tracker for details.
https://github.com/golang/go/issues?q=milestone%3AGo1.17.11+label%3ACherryPickApproved
Hello gophers,
We have just released Go versions 1.18.3 and 1.17.11, minor point …
=> update golang to 1.18.3, 1.17.11

docs/cri/config.md, pkg/cri/annotations/annotations.go, pkg/cri/config/config.go, pkg/cri/server/container_create.go, pkg/cri/server/container_create_test.go, pkg/cri/server/image_pull.go, pkg/cri/server/image_pull_test.go, pkg/cri/server/sandbox_run.go
This is the implementation for https://github.com/containerd/containerd/issues/6657, the following lists core ideas:
1. Added `snapshotter` option in CRI per-runtime config
2. For containers related operations e.g. create containers, respect the runtime.snapshotter if set, otherwise using the global  snapshotter.
```
[plugins."io.containerd.grpc.v1.cri".containerd.runtimes.my-runtime]
snapshotter = "devmapper"
```
3. For pull images, given the runtime info is not passed along in the PullImageRequest, we used a configurable annotation key `io.kubernetes.cri/runtimehandler` to specify runtime during pull time such that the appropriate snapshotter can be used.
Pod sandbox config with annotations specifying the runtime, and image_pull will get the correct snapshotter for unpacking
```
{ …
```
=> Support runtime level snapshotter for issue 6657

oci/spec_opts.go, oci/spec_opts_darwin.go, oci/spec_opts_freebsd.go, oci/spec_opts_linux.go, oci/spec_opts_windows.go, platforms/defaults_freebsd.go
This allows running Linux containers on FreeBSD and modifies the
mounts so that they represent the linux emulated filesystems, as per:
https://wiki.freebsd.org/LinuxJails
Supersedes #5480 per convo with @gizahNL in OCI Slack chat
=> Linux containers on FreeBSD

cmd/containerd/builtins_cri.go
microVM/VM based containers are possible on Apple platforms, so no reason to not allow CRI there (though this is experimental and not something we officially support).
=> Allow CRI on Darwin

BUILDING.md, Makefile, Makefile.linux
This commit adds STATIC makefile variable to adjust LDFLAGS and build
tags accordingly.
Fixes #5824.
=> Make building static binaries simpler

integration/main_test.go, integration/windows_rootfs_size_test.go, pkg/cri/server/container_create.go, pkg/cri/server/container_create_linux.go, pkg/cri/server/container_create_other.go, pkg/cri/server/container_create_windows.go, snapshots/windows/windows.go
This change does a couple things to remove some cruft/unused functionality
in the Windows snapshotter, as well as add a way to specify the rootfs
size in bytes for a Windows container via a new field added in the CRI api in
k8s 1.24. Setting the rootfs/scratch volume size was assumed to be working
prior to this but turns out not to be the case.
Previously I'd added a change to pass any annotations in the containerd
snapshot form (containerd.io/snapshot/*) as labels for the containers
rootfs snapshot. This was added as a means for a client to be able to provide
containerd.io/snapshot/io.microsoft.container.storage.rootfs.size-gb as an
annotation and have that be translated to a label and ultimately set the
size for the scratch volume in Windows. However, this actually only worked if …
=> Windows snapshotter touch ups and new functionality

BUILDING.md, Makefile, Makefile.linux
This commit adds STATIC makefile variable to adjust LDFLAGS and build
tags accordingly.
Fixes #5824.
(cherry picked from commit 00eb74a4ca47d5ad9c7d1171a2929a3da39deee6)
=> [release/1.6] Make building static binaries simpler

archive/link_default.go, archive/link_freebsd.go, archive/tar.go, archive/tar_test.go, oci/mounts_freebsd.go, oci/utils_unix_test.go, pkg/cri/server/container_create_test.go, pkg/cri/server/sandbox_run_test.go, platforms/defaults_freebsd.go
This patch series ports a number of unit tests to FreeBSD and removes a few that test features that haven't been ported to FreeBSD yet (CRI-related).
I have not yet added a new Cirrus-CI task for these unit tests as not all tests yet pass in that environment.  Notably there are differences in behavior between ZFS and UFS which have not yet been accounted for in the tests (I haven't dug into them yet), but may require changes in [continuity](https://github.com/containerd/continuity) to be resolved.  When run in ZFS, all tests currently pass; when run in UFS (which is the default filesystem in use in Cirrus) there are a few failures.  (You can see a sample of failures [here](https://cirrus-ci.com/task/4837901690208256) if you're interested.)
=> Port (some) unit tests to FreeBSD

snapshots/overlay/overlayutils/check.go
I am trying to run containerd in docker container environment with user-namespace.
I found that the Unmount logic of this code usually takes tens of seconds when the machine is under high disk load and running multiple containers.And this will cause the startup of docker to fail
I'm not particularly sure what's causing this, but the unmount error just outputs the log and doesn't affect the execution logic of the function. So I think it would be better to change this to asynchronous execution.
This is the log of docker
time="2022-05-31T18:13:34.490264526+08:00" level=info msg="Starting up"
time="2022-05-31T18:13:34.491918527+08:00" level=debug msg="Listener created for HTTP on unix (/var/run/docker.sock)"
time="2022-05-31T18:13:34.491948011+08:00" level=debug msg="Containerd not running, …
=> fix:userattr-unmount unexpected timeout

pkg/cri/server/sandbox_run_linux.go
This pr is a part of #6911, changes include:
* Optimized redundant /dev/shm mounts.
* Added `nosuid,nodev,noexec` flags to the /dev/shm mount options.
Fixes: #6911
=> CRI: Improve the /dev/shm mount options in Sandbox.

.github/workflows/cifuzz.yml
This PR adds CIFuzz to Containerds CI. CIFuzz is a service offered by OSS-Fuzz and is recommended for all OSS-Fuzz projects. It will run all fuzzers for 10 minutes in the CI to catch low-hanging bugs and verify that no breaking changes to the fuzzing suite are introduced.
The time each fuzzer should run can be adjusted.
Only fuzzers that cover code that is affected by changes in PRs will run.
The CIFuzz documentation can be found here: https://google.github.io/oss-fuzz/getting-started/continuous-integration/
=> Run fuzzers in CI

script/setup/prepare_env_windows.ps1
After the switch to MinGW 11.2.0 in #6888, the containerd client
integration tests were crashing with an apparent  memory allocation
error as described in golang/go#46099.
This patch reverts MinGW to 10.3.0 to bypass the issue.
=> Downgrade MinGW in Windows setup scripts.

.github/workflows/fuzz.yml
Until we merge cncf/cncf-fuzzing into this repository (see #7066),
we should keep this step optional.
=> Make CI Fuzz optional

contrib/fuzz/archive_fuzzer.go, contrib/fuzz/oss_fuzz_build.sh, integration/client/go.mod, integration/client/go.sum, remotes/docker/converter_fuzz.go, remotes/docker/fetcher_fuzz.go
This PR makes CR Fuzz less noisy. The fuzzers in cncf-fuzzing are untouched yet. They will be merged later (see #7066).
=> Make CI Fuzz less noisy

cmd/containerd/builtins.go, integration/build_local_containerd_helper_test.go, metadata/plugin/plugin.go, services/server/config/config.go, services/server/server.go
Cleaner separation of the metadata plugin and makes it easier to use without starting the whole server.
Broken out from #5674
=> Move metadata plugin registration to seperate package

docs/getting-started.md
Fix doc: since containerd doesn't have the `GenerateSpec` method any longer, spec has to be generated with `WithNewSpec`
Signed-off-by: Yakul Garg <2000yeshu@gmail.com>
=> Fix Documentation Issue

cmd/ctr/commands/containers/containers.go
`ctr c create` doesn't seems to parse container's arguments correctly.
This seems related to https://github.com/urfave/cli/issues/1424 .
```console
ctr: image "-c": not found
```
This commit is a quick fix of this problem by adding `SkipArgReorder: true`.
This is the same approach as `ctr run` and `ctr t exec`.
=> ctr: Fix `ctr c create` fails to parse arguments

.github/workflows/ci.yml
There is currently an issue in the race detector in Go on Windows when
used with a newer version of GCC. The issue was first reported here:
https://github.com/golang/go/issues/46099
Fixes #7104
=> Downgrade MinGW to version 10.2.0

metadata/containers_test.go, metadata/content_test.go, metadata/db_test.go, metadata/gc_test.go, metadata/images_test.go, metadata/leases_test.go, metadata/namespaces_test.go, metadata/sandbox_test.go, metadata/snapshot_test.go
This PR replaces func returns with `t.Cleanup`,
which makes tests slightly easier to maintain as
there is no need to call `defer cancel()` everywhere.
=> Cleanup metadata tests

cmd/ctr/commands/pprof/pprof.go
Need to close the body when the status is not 200, 
otherwise, this resource will not be released.
=> Fix missing closed HTTP Body

go.mod, go.sum, integration/client/go.sum, vendor/github.com/emicklei/go-restful/v3/CHANGES.md, vendor/github.com/emicklei/go-restful/v3/README.md, vendor/github.com/emicklei/go-restful/v3/SECURITY.md, vendor/github.com/emicklei/go-restful/v3/compress.go, vendor/github.com/emicklei/go-restful/v3/container.go, vendor/github.com/emicklei/go-restful/v3/cors_filter.go, vendor/github.com/emicklei/go-restful/v3/jsr311.go, vendor/github.com/emicklei/go-restful/v3/route.go, vendor/modules.txt
This dependency had a security release and it's worth updating our dependency, but for those curious, the containerd code which uses this vendored library (pkg/cri/streaming) does not use CORS at all, which is a requirement to be able to exploit the restful CVE. Therefore containerd is not vulnerable to this exploit.
Full diff: https://github.com/emicklei/go-restful/compare/7c971ca4d0fd...v3.8.0
=> Update go-restful/v3 to latest release

diff/lcow/lcow.go
On Windows the two differs we register by default are the "windows" and "windows-lcow" differs. The diff service checks if Apply returns `ErrNotImplemented` and will move on to the next differ in the line if so. The Windows differ makes use of this to fallback to LCOW if it's determined the mount type passed is incorrect, but the LCOW differ does not return `ErrNotImplemented` for the same scenario. This puts a strict ordering requirement on the default differ entries in the config, namely that ["windows", "windows-lcow"] will work, as windows will correctly fall back to the lcow differ, but ["windows-lcow", "windows"] won't as the diff services `Apply` will just return the error directly. Not too much of an issue, but if you're hand editing a config and place lcow first it can be ran …
=> LCOW differ return ErrNotImplemented for wrong mount type

.github/workflows/ci.yml
There is currently an issue in the race detector in Go on Windows when
used with a newer version of GCC. The issue was first reported here:
https://github.com/golang/go/issues/46099
Fixes #7104
(cherry picked from commit 1ef4bda43301ef1de059346a9c37a0876eb635f3)
=> [release/1.6] Downgrade MinGW to version 10.2.0

.github/workflows/ci.yml
There is currently an issue in the race detector in Go on Windows when
used with a newer version of GCC. The issue was first reported here:
https://github.com/golang/go/issues/46099
Fixes #7104
(cherry picked from commit 1ef4bda43301ef1de059346a9c37a0876eb635f3)
=> [release/1.5] Downgrade MinGW to version 10.2.0

remotes/docker/auth/parse.go, remotes/docker/auth/parse_test.go
According to RFC 9110, quoted-string could be "".
https://datatracker.ietf.org/doc/html/rfc9110#section-11.6.1
https://datatracker.ietf.org/doc/html/rfc9110#appendix-A
Fixes #6376.
(cherry picked from commit 548c9c317ba47b7df54b96c833c9ac881c47bd90)
=> [release/1.6] Fix WWW-Authenticate parsing

contrib/seccomp/seccomp_default.go
=> seccomp: allow clock_settime64 when CAP_SYS_TIME is added

pkg/cri/server/helpers.go, pkg/cri/store/container/container.go, pkg/cri/store/image/image.go, pkg/cri/store/sandbox/sandbox.go, pkg/cri/store/snapshot/snapshot.go
All of the CRI store related packages all use the standard errdefs
errors now for if a key doesn't or already exists (ErrAlreadyExists,
ErrNotFound), but the comments for the methods still referenced
some unused package specific error definitions. This change just
updates the comments to reflect what errors are actually returned
and adds comments for some previously undocumented exported 
functions.
=> Fix out of date comments for CRI store packages

.github/workflows/ci.yml, .github/workflows/nightly.yml, .github/workflows/release.yml, .zuul/playbooks/containerd-build/integration-test.yaml, .zuul/playbooks/containerd-build/run.yaml, .zuul/playbooks/containerd-build/unit-test.yaml, Vagrantfile, contrib/Dockerfile.test
```markdown
- Update Go runtime to 1.17.12 to address CVE-2022-1705, CVE-2022-1962, CVE-2022-28131,
CVE-2022-30630, CVE-2022-30631, CVE-2022-30632, CVE-2022-30633, CVE-2022-30635,
and CVE-2022-32148.
```
----
go1.17.12 (released 2022-07-12) includes security fixes to the compress/gzip,
encoding/gob, encoding/xml, go/parser, io/fs, net/http, and path/filepath
packages, as well as bug fixes to the compiler, the go command, the runtime,
and the runtime/metrics package. See the Go 1.17.12 milestone on the issue
https://github.com/golang/go/issues?q=milestone%3AGo1.17.12+label%3ACherryPickApproved
This update addresses:
CVE-2022-1705, CVE-2022-1962, CVE-2022-28131, CVE-2022-30630, CVE-2022-30631,
CVE-2022-30632, CVE-2022-30633, CVE-2022-30635, and CVE-2022-32148.
Full …
=> [release/1.5] update golang to 1.17.12

.github/workflows/build-test-images.yml, .github/workflows/ci.yml, .github/workflows/codeql.yml, .github/workflows/images.yml, .github/workflows/nightly.yml, .github/workflows/release.yml, .zuul/playbooks/containerd-build/integration-test.yaml, .zuul/playbooks/containerd-build/run.yaml, .zuul/playbooks/containerd-build/unit-test.yaml, Vagrantfile, contrib/Dockerfile.test, contrib/fuzz/oss_fuzz_build.sh, script/setup/prepare_env_windows.ps1
```markdown
- Update Go runtime to 1.18.4 to address CVE-2022-1705, CVE-2022-1962, CVE-2022-28131,
CVE-2022-30630, CVE-2022-30631, CVE-2022-30632, CVE-2022-30633, CVE-2022-30635,
and CVE-2022-32148.
```
----
go1.18.4 (released 2022-07-12) includes security fixes to the compress/gzip,
encoding/gob, encoding/xml, go/parser, io/fs, net/http, and path/filepath
packages, as well as bug fixes to the compiler, the go command, the linker,
the runtime, and the runtime/metrics package. See the Go 1.18.4 milestone on the
issue tracker for details:
https://github.com/golang/go/issues?q=milestone%3AGo1.18.4+label%3ACherryPickApproved
This update addresses:
CVE-2022-1705, CVE-2022-1962, CVE-2022-28131, CVE-2022-30630, CVE-2022-30631,
CVE-2022-30632, CVE-2022-30633, CVE-2022-30635, and CVE-2022-32148. …
=> update golang to 1.18.4, 1.17.12

.github/workflows/build-test-images.yml, .github/workflows/ci.yml, .github/workflows/codeql.yml, .github/workflows/images.yml, .github/workflows/nightly.yml, .github/workflows/release.yml, .zuul/playbooks/containerd-build/integration-test.yaml, .zuul/playbooks/containerd-build/run.yaml, .zuul/playbooks/containerd-build/unit-test.yaml, Vagrantfile, contrib/Dockerfile.test, script/setup/prepare_env_windows.ps1
```markdown
- Update Go runtime to 1.17.12 to address CVE-2022-1705, CVE-2022-1962, CVE-2022-28131,
CVE-2022-30630, CVE-2022-30631, CVE-2022-30632, CVE-2022-30633, CVE-2022-30635,
and CVE-2022-32148.
```
----
go1.17.12 (released 2022-07-12) includes security fixes to the compress/gzip,
encoding/gob, encoding/xml, go/parser, io/fs, net/http, and path/filepath
packages, as well as bug fixes to the compiler, the go command, the runtime,
and the runtime/metrics package. See the Go 1.17.12 milestone on the issue
https://github.com/golang/go/issues?q=milestone%3AGo1.17.12+label%3ACherryPickApproved
This update addresses:
CVE-2022-1705, CVE-2022-1962, CVE-2022-28131, CVE-2022-30630, CVE-2022-30631,
CVE-2022-30632, CVE-2022-30633, CVE-2022-30635, and CVE-2022-32148.
Full …
=> [release/1.6] update golang to 1.17.12

docs/cri/config.md
Replaced tabs with spaces to follow document formatting style.
=> cri doc: fix formatting for CDI options

contrib/seccomp/seccomp_default.go
- same as https://github.com/moby/moby/pull/37242
- relates to https://github.com/moby/moby/issues/37241
- fixes https://github.com/containerd/containerd/issues/7150
This aligns the profile with docker's profile, which added this in
https://github.com/moby/moby/commit/47dfff68e4365668279e235bf8c7778b637f2517
=> seccomp: add get_mempolicy, mbind, set_mempolicy, with CAP_SYS_NICE

script/setup/install-protobuf
This is for convenience, so `make protos` can be ran from Darwin envs too.
=> Update install-protobuf script  to install protobuf on Darwin

contrib/seccomp/seccomp_default.go
Cherry-pick (clean) https://github.com/containerd/containerd/pull/7149
=> [release/1.6] seccomp: allow clock_settime64 when CAP_SYS_TIME is added

contrib/seccomp/kernelversion/kernel_linux.go, contrib/seccomp/kernelversion/kernel_linux_test.go, contrib/seccomp/seccomp_default.go
Cherry-pick (clean) https://github.com/containerd/containerd/pull/6810
=> [release/1.6] allow ptrace(2) by default for kernel >= 4.8

.cirrus.yml
We are constantly getting the message below from Cirrus CI;
> Machine type with name 'c2-standard-2' does not exist in zone 'us-central1-c'."
Seems Cirrus CI is constructing the machine type based on
the "cpu" field from the YAML file. However c2-standard's minimal vCPU
count is 4 based on the official document below.
https://cloud.google.com/compute/docs/compute-optimized-machines
=> ci: workaround Cirrus CI's INVALID_ARGUMENT

docs/man/containerd-config.toml.5.md
Sample `config.toml` has a syntax error. Gives the following error when used:
```
containerd: failed to load TOML: /etc/containerd/config.toml: (27, 47):
was expecting token [[, but got table array key cannot contain ']' instead
```
Also changed to have syntax highlighting. Syntax highlighting would have marked the error in red
=> docs: Fix sample config.toml syntax

cmd/ctr/commands/commands.go, cmd/ctr/commands/run/run_unix.go, cmd/ctr/commands/run/run_windows.go
```
$ sudo ctr run --rm --user 1000 docker.io/library/alpine:latest test id
uid=1000 gid=0(root) groups=1(bin),2(daemon),3(sys),4(adm),6(disk),10(wheel),11(floppy),20(dialout),26(tape),27(video)
```
```
$ sudo ctr run --rm --user 1000:1000 docker.io/library/alpine:latest test id
uid=1000 gid=1000
```
=> ctr: support --user for run/create

.github/workflows/ci.yml, .github/workflows/nightly.yml, .github/workflows/release.yml, .github/workflows/release/Dockerfile, contrib/seccomp/seccomp_default.go
Cherry-pick (clean):
- https://github.com/containerd/containerd/pull/6858 (due to the commit dependency)
- https://github.com/containerd/containerd/pull/6882
runc needs https://github.com/opencontainers/runc/pull/3446 
(https://github.com/opencontainers/runc/pull/3446/commits/1d7b297128d0d8914290b458333984625c4d1180)
=> [release/1.6] Support RISC-V 64

pkg/cri/server/container_stats_list.go
#7186 changed how container cpu stats are populated. Previously, UsageNanoCores were computed at the same time as populating UsageCoreNanoSeconds, and only when UsageCoreNanoSeconds could be populated.
After the change however, we attempt to compute UsageNanoCore's regardless of the state of the provided metrics. This can panic in cases where we do not yet have CPU stats (e.g if the container did not start).
This change restores the previous behavior, by skipping the computation if cpu metrics are unavailable.
=> cri_stats: handle missing cpu stats

archive/compression/benchmark_test.go, integration/client/export_test.go, integration/client/import_test.go, integration/sandbox_clean_remove_windows_test.go, pkg/cri/sbserver/container_create_linux_test.go, pkg/cri/server/container_create_linux_test.go, remotes/docker/config/docker_fuzzer_internal.go, snapshots/lcow/lcow.go
`ioutil` has been deprecated by golang. All the code in `ioutil` just
forwards functionality to code in either the `io` or `os` packages.
See https://github.com/golang/go/pull/51961 for more info.
Signed-off-by: Jeff Widman <jeff@jeffwidman.com>
=> Drop deprecated `ioutil`

go.mod, go.sum, integration/client/go.mod, integration/client/go.sum, vendor/github.com/Microsoft/hcsshim/internal/hcs/system.go, vendor/github.com/Microsoft/hcsshim/internal/hns/hnspolicy.go, vendor/github.com/Microsoft/hcsshim/internal/jobobject/iocp.go, vendor/github.com/Microsoft/hcsshim/internal/jobobject/jobobject.go, vendor/github.com/Microsoft/hcsshim/internal/jobobject/limits.go, vendor/github.com/Microsoft/hcsshim/internal/queue/mq.go, vendor/github.com/Microsoft/hcsshim/internal/winapi/iocp.go, vendor/github.com/Microsoft/hcsshim/internal/winapi/jobobject.go, vendor/github.com/Microsoft/hcsshim/internal/winapi/process.go, vendor/github.com/Microsoft/hcsshim/internal/winapi/system.go, vendor/github.com/Microsoft/hcsshim/internal/winapi/winapi.go, vendor/github.com/Microsoft/hcsshim/internal/winapi/zsyscall_windows.go, vendor/modules.txt
This contains two commits to bump hcsshim to v0.9.3 first and then v0.9.4. We'd originally planned to get main on a series of beta/pre-release tags of v0.10.0 but that has been slower than hoped, so there was an odd situation where release/1.6 was ahead of main in terms of hcsshim version. This just gets main up to speed with 1.6 for now in steps.
v0.9.3:
Brings in a new field to fix an HNS issue in ws2019 as well as
an optimization for collecting Windows stats (memory, cpu, iops).
v0.9.4:
Contains some fixes for hostprocess containers, mainly around
fixing task stats which regressed from a change in v0.9.3 and 
some improvements for queuing internal events.
=> go.mod: Bump hcsshim to v0.9.4

.github/workflows/ci.yml, Vagrantfile
Effectively a backport of #6925 from `main` but we have no Cirrus CI in `release/1.6`
=> [release/1.6] Update Fedora version to 36

go.mod, go.sum, integration/client/go.mod, integration/client/go.sum, vendor/github.com/Microsoft/hcsshim/internal/jobobject/iocp.go, vendor/github.com/Microsoft/hcsshim/internal/jobobject/jobobject.go, vendor/github.com/Microsoft/hcsshim/internal/jobobject/limits.go, vendor/github.com/Microsoft/hcsshim/internal/queue/mq.go, vendor/github.com/Microsoft/hcsshim/internal/winapi/jobobject.go, vendor/github.com/Microsoft/hcsshim/internal/winapi/process.go, vendor/github.com/Microsoft/hcsshim/internal/winapi/system.go, vendor/github.com/Microsoft/hcsshim/internal/winapi/zsyscall_windows.go, vendor/modules.txt
This tag contains some fixes for hostprocess containers, mainly around
fixing task stats which regressed from a change in v0.9.3.
https://github.com/microsoft/hcsshim/releases/tag/v0.9.4
=> [release/1.6] go.mod: Bump hcsshim to v0.9.4

integration/image_pull_timeout_test.go
The ghcr.io/containerd/registry:2.7 image does not support the ppc64le architecture, causing the TestCRIImagePullTimeout tests to fail when executed on a ppc64le device. The ghcr.io/containerd/registry:2.7 image is replaced by the ghcr.io/containerd/volume-ownership:2.1 image, allowing all tests to pass. This commit addresses issue #7197.
=> Fix CRI image pull timeout test for ppc64le

cmd/ctr/commands/resolver.go
[`httputil.DumpRequest`](https://pkg.go.dev/net/http/httputil#DumpRequest) is only for dumping incoming requests on a server.
=> Use `httputil.DumpRequestOut` for dumping client req

remotes/docker/pusher.go
For consistency with pulls, see #2052.
=> Add extra context to error when push unauthorized

integration/windows_hostprocess_test.go
Add a test to the CRI suite to validate stats functions for hostprocess
containers. hcsshim v0.9.3 had a bug in stats collection so this is
mainly for sanity and to avoid another regression.
=> Windows HostProcess container CRI stats test

rootfs/diff.go
In CreateDiff function,  we wil create view snapshot base on parent snapshot,  
view snapshot name is "`<parent snapshot KEY>`-parent-view", 
so while, It does not support concurrent operations，other user will be return to the error that the snapshot already exists.
So,  we add uniquePart() as a suffix.
=> fix: support simultaneous create diff for same parent snapshot

.github/workflows/ci.yml
- Cherry-pick (required fixup for mismatch on go-version) commit from #7206 
- Update Vagrant instances to macos-12 image (not used in `main` anymore)
=> [release/1.6] Backport: bump macos runner version

.github/workflows/ci.yml
In Github Actions `run` jobs end on first non-zero exit code.
This means that the code like this:
```
sudo -E PATH=$PATH critest --report-dir "${{github.workspace}}/critestreport" --runtime-endpoint=unix:///${BDIR}/c.sock --parallel=8
...
test $TEST_RC -ne 0 && cat ${BDIR}/containerd-cri.log
```
will never produce logs if `critest` fails.
This change uses `trap` to properly clean resources and `cat` containerd logs.
Here is an output examples when job fails [before](https://github.com/containerd/containerd/runs/7583839020) and [after](https://github.com/containerd/containerd/runs/7585473059) applying this fix.
=> Fix cleanup in critest

cmd/containerd/command/service_windows.go
🍒pick: ee0f2e9064d2ca5a69e7abc0a6957b02475e7165
Original commit desc:
--------------------------------------------------
Previously we were reassigning os.Stderr to the panic.log file we create
when getting asked to run Containerd as a Windows service. The panic.log
file was used as a means to easily collect panic stacks as Windows
services don't have regular standard IO, and the usual recommendation
is to either write to the event log or just to a file in the case of
running as a service.
One place where this panic.log flow was biting us was with shim logging,
which is forwarded from the shim and copied to os.Stderr directly which was
causing shim logs to get forwarded to this panic.log file instead of just
panics. We expose an additional `--log-file` flag if you ask to run a
windows …
=> [release/1.6] Backport: Change os.Stderr reassign for Windows service

.github/workflows/build-test-images.yml, .github/workflows/ci.yml, .github/workflows/codeql.yml, .github/workflows/images.yml, .github/workflows/nightly.yml, .github/workflows/release.yml, .zuul/playbooks/containerd-build/integration-test.yaml, .zuul/playbooks/containerd-build/run.yaml, .zuul/playbooks/containerd-build/unit-test.yaml, Vagrantfile, contrib/Dockerfile.test, contrib/fuzz/oss_fuzz_build.sh, script/setup/prepare_env_windows.ps1
Update Go runtime to 1.18.5 to address CVE-2022-32189.
Full diff:
https://github.com/golang/go/compare/go1.18.4...go1.18.5
--------------------------------------------------------
From the security announcement:
https://groups.google.com/g/golang-announce/c/YqYYG87xB10
We have just released Go versions 1.18.5 and 1.17.13, minor point
releases.
These minor releases include 1 security fixes following the security
policy:
encoding/gob & math/big: decoding big.Float and big.Rat can panic
Decoding big.Float and big.Rat types can panic if the encoded message is
too short.
This is CVE-2022-32189 and Go issue https://go.dev/issue/53871.
View the release notes for more information:
https://go.dev/doc/devel/release#go1.18.5
=> Update golang to 1.18.5, 1.17.13

.github/workflows/build-test-images.yml, .github/workflows/ci.yml, .github/workflows/codeql.yml, .github/workflows/images.yml, .github/workflows/nightly.yml, .github/workflows/release.yml, .zuul/playbooks/containerd-build/integration-test.yaml, .zuul/playbooks/containerd-build/run.yaml, .zuul/playbooks/containerd-build/unit-test.yaml, Vagrantfile, contrib/Dockerfile.test, script/setup/prepare_env_windows.ps1
Update Go runtime to 1.17.13 to address CVE-2022-32189.
Full diff:
https://github.com/golang/go/compare/go1.17.12...go1.17.13
--------------------------------------------
From the security announcement:
https://groups.google.com/g/golang-announce/c/YqYYG87xB10
We have just released Go versions 1.18.5 and 1.17.13, minor point
releases.
These minor releases include 1 security fixes following the security
policy:
encoding/gob & math/big: decoding big.Float and big.Rat can panic
Decoding big.Float and big.Rat types can panic if the encoded message is
too short.
This is CVE-2022-32189 and Go issue https://go.dev/issue/53871.
View the release notes for more information:
https://go.dev/doc/devel/release#go1.17.13
=> [release/1.6] Update golang to 1.17.13

.github/workflows/ci.yml, .github/workflows/nightly.yml, .github/workflows/release.yml, .zuul/playbooks/containerd-build/integration-test.yaml, .zuul/playbooks/containerd-build/run.yaml, .zuul/playbooks/containerd-build/unit-test.yaml, Vagrantfile, contrib/Dockerfile.test
Update Go runtime to 1.17.13 to address CVE-2022-32189.
Full diff:
https://github.com/golang/go/compare/go1.17.12...go1.17.13
------------------------------------------
From the security announcement:
https://groups.google.com/g/golang-announce/c/YqYYG87xB10
We have just released Go versions 1.18.5 and 1.17.13, minor point
releases.
These minor releases include 1 security fixes following the security
policy:
encoding/gob & math/big: decoding big.Float and big.Rat can panic
Decoding big.Float and big.Rat types can panic if the encoded message is
too short.
This is CVE-2022-32189 and Go issue https://go.dev/issue/53871.
View the release notes for more information:
https://go.dev/doc/devel/release#go1.17.13
=> [release/1.5] Update golang to 1.17.13

.github/workflows/ci.yml
Needs to be on macos-12 for CI runners to work properly after deprecation
=> [release/1.5] backport: update GitHub Actions runners to macos-12

.mailmap, releases/v1.6.7.toml, version/version.go
See: https://gist.github.com/dcantah/7e1aef7bf809270960c2814d0d976a2b
=> Prepare releases notes for 1.6.7

.github/workflows/release.yml
1.6 releases are timing out when building the release
=> [release/1.6] Update release build timeout

.github/workflows/ci.yml, .github/workflows/nightly.yml, .github/workflows/release.yml
This will significantly reduce the number of places where we have to bump Go version on our CI.
=> Use environment variable to specify Go version on CI

.github/workflows/release.yml, .github/workflows/release/Dockerfile
Partially revert 0e56e4f9ff2925d0755908f227f2b5fc9a1c4c78
Rollback the build environment from Ubuntu 22.04 to 18.04, except for riscv64 that isn't supported by Ubuntu 18.04.
Fix #7255 (`1.6.7 can't be run on Ubuntu LTS 20.04 (GLIBC_2.34 not found)`)
=> release: rollback Ubuntu to 18.04 (except for riscv64)

.github/workflows/release.yml
In the 1.6.7 release, we saw significantly longer execution time for producing builds that exceeded the previous timeout of 10 minutes, causing the workflow to fail.  After increasing to 20 minutes in the release/1.6 branch, we continued to see one failure (which succeeded on retry).
Increase to 30 minutes to provide additional buffer for the build to complete.
--------
Release builds are performed from within a Dockerfile-defined environment and do not require Go to be installed in the GitHub Actions runner environment.
-------
See https://github.com/samuelkarp/containerd/actions/runs/2805142467 for a successful run.
=> release workflow: increase timeout to 30 minutes & remove Go setup action

.github/workflows/release.yml, .github/workflows/release/Dockerfile
Backport of https://github.com/containerd/containerd/pull/7258
See https://github.com/samuelkarp/containerd/actions/runs/2806523405 for a successful run
-------------
Partially revert 0e56e4f9ff2925d0755908f227f2b5fc9a1c4c78
Rollback the build environment from Ubuntu 22.04 to 18.04, except for riscv64 that isn't supported by Ubuntu 18.04.
Fix issue 7255 (`1.6.7 can't be run on Ubuntu LTS 20.04 (GLIBC_2.34 not found)`)
(cherry picked from commit 481861020742c194f25f2694cd09be8d37d45fba)
Signed-off-by: Samuel Karp <samuelkarp@google.com>
=> [release/1.6] release: rollback Ubuntu to 18.04 (except for riscv64)

.github/workflows/release.yml
Backport of https://github.com/containerd/containerd/pull/7259
See run at https://github.com/samuelkarp/containerd/actions/runs/2807105354
----
In the 1.6.7 release, we saw significantly longer execution time for
producing builds that exceeded the previous timeout of 10 minutes,
causing the workflow to fail.  After increasing to 20 minutes in the
release/1.6 branch, we continued to see one failure (which succeeded on
retry).
Increase to 30 minutes to provide additional buffer for the build to
complete.
Signed-off-by: Samuel Karp <samuelkarp@google.com>
(cherry picked from commit f8add9263a9ba64ad4400b7c1877dbd527963fbb)
Signed-off-by: Samuel Karp <samuelkarp@google.com>
=> [release/1.5] release workflow: increase timeout to 30 minutes

.github/workflows/release.yml
Backport of https://github.com/containerd/containerd/pull/7259
See run at https://github.com/samuelkarp/containerd/actions/runs/2807107122
----
In the 1.6.7 release, we saw significantly longer execution time for
producing builds that exceeded the previous timeout of 10 minutes,
causing the workflow to fail.  After increasing to 20 minutes in the
release/1.6 branch, we continued to see one failure (which succeeded on
retry).
Increase to 30 minutes to provide additional buffer for the build to
complete.
Signed-off-by: Samuel Karp <samuelkarp@google.com>
(cherry picked from commit f8add92)
Signed-off-by: Samuel Karp <samuelkarp@google.com>
=> [release/1.6] release workflow: increase timeout to 30 minutes & remove Go setup action

oci/spec_opts.go, oci/spec_opts_linux_test.go
`WithAppendAdditionalGroups` should allow appending the group id directly instead of checking it.
=> oci: skip checking group id for WithAppendAdditionalGroups

Vagrantfile
It is used to debug if there is any flaky test cases.
---- 
REF: #7264 
----
Example: https://api.cirrus-ci.com/v1/task/5387167588417536/logs/cri_test.log
=> Vagrantfile: dump containerd log after critest

oci/spec_opts.go
- backport ofhttps://github.com/containerd/containerd/pull/6923
A container should not have access to tun/tap device, unless it is explicitly
specified in configuration.
This device was already removed from docker's default, and runc's default;
- https://github.com/opencontainers/runc/pull/3468/commits/2ce40b6ad72b4bd4391380cafc5ef1bad1fa0b31
- https://github.com/moby/moby//commit/9c4570a958df42d1ad19364b1a8da55b891d850a
Per the commit message in runc, this should also fix these messages;
> Apr 26 03:46:56 foo.bar systemd[1]: Couldn't stat device /dev/char/10:200: No such file or directory
coming from systemd on every container start, when the systemd cgroup driver
is used, and the system runs an old (< v240) version of systemd
(the message was presumably eliminated by [1]).
[1]: …
=> [release/1.6 backport] oci: WithDefaultUnixDevices(): remove tun/tap from the default devices

oci/spec_opts.go
- backport of https://github.com/containerd/containerd/pull/6923
A container should not have access to tun/tap device, unless it is explicitly
specified in configuration.
This device was already removed from docker's default, and runc's default;
- https://github.com/opencontainers/runc/pull/3468/commits/2ce40b6ad72b4bd4391380cafc5ef1bad1fa0b31
- https://github.com/moby/moby//commit/9c4570a958df42d1ad19364b1a8da55b891d850a
Per the commit message in runc, this should also fix these messages;
> Apr 26 03:46:56 foo.bar systemd[1]: Couldn't stat device /dev/char/10:200: No such file or directory
coming from systemd on every container start, when the systemd cgroup driver
is used, and the system runs an old (< v240) version of systemd
(the message was presumably eliminated by [1]).
[1]: …
=> [release/1.5 backport] oci: WithDefaultUnixDevices(): remove tun/tap from the default devices

.github/workflows/ci.yml
Backport https://github.com/containerd/containerd/pull/7232
=> [release 1.5 backport] Fix cleanup in critest

cmd/containerd-stress/cri_worker.go, cmd/containerd-stress/exec_worker.go, cmd/containerd-stress/main.go, cmd/containerd-stress/worker.go
Introduce a --cri flag, which'll run containerd-stress using the CRI,
instead of containerd's task api.
In doing so, introduce cri_worker, rename existing worker to ctr_worker and introduce
a worker interface that each of these implement.
Signed-off-by: Eric Ernst <eric_ernst@apple.com>
=> containerd-stress: add support for running through CRI

.github/workflows/ci.yml
`GOPROXY=direct` was introduced by @mxpv in https://github.com/containerd/containerd/commit/6d4429eddeaff0fa0640f4a51c66fb65702477df, but there does not seem to be any specific history for why it was set.  Our CI workflows are now failing due to https://github.com/go-yaml/yaml/issues/887, so at least for now it should help to remove this setting.
=> ci: remove GOPROXY environment variable due to https://github.com/go-yaml/yaml/issues/887

pkg/cri/opts/spec.go
Cherry-pick https://github.com/containerd/containerd/pull/6805
=> [release/1.6] Do not append []string{""} to command to preserve Docker compatibility

test/build-utils.sh
Workload identity is preferred in CI instead of GOOGLE_APPLICATION_CREDENTIALS
related: https://github.com/kubernetes/test-infra/issues/27157
/cc @dims
=> Don't fail test when GOOGLE_APPLICATION_CREDENTIALS is unset

contrib/seccomp/seccomp_default.go
Adding CAP_BPF and CAP_PERFMON
The PR adds support of `CAP_BPF` and `CAP_PERFMON` capabilities. Prior to kernel 5.8 `bpf` and `perf_event_open` requires `CAP_SYS_ADMIN`. This change enables finer control of the privilege setting, thus allowing us to run certain system tracing tools with minimal privileges.
=> Adding support of CAP_BPF and CAP_PERFMON

contrib/fuzz/daemon.go, pkg/cri/streaming/server.go
* [pkg/cri/streaming: increase ReadHeaderTimeout](https://github.com/containerd/containerd/commit/71a9fa8d212606b916fc4aa555acdb1d09010b39) 
It is follow-up of https://github.com/containerd/containerd/pull/7254. This commit will increase ReadHeaderTimeout
from 3s to 30m, which prevent from unexpected timeout when the node is
running with high-load. 30 Minutes is longer enough to get close to
before what https://github.com/containerd/containerd/pull/7254 changes.
And ideally, we should allow user to configure the streaming server if
the users want this feature.
* [contrib/fuzz/daemon.go: reformat the fileheader](https://github.com/containerd/containerd/commit/38c98bc94173b59938a7b148b45fd9360f849037) 
Align with https://github.com/containerd/project/blob/main/script/validate/template/go.txt …
=> Follow up #7254 (Switch to Go 1.19)

.github/workflows/ci.yml
This reverts commit https://github.com/containerd/containerd/commit/1ef4bda43301ef1de059346a9c37a0876eb635f3.
Previously we were downgrading mingw to work around an issue in the race
detector in Go on Windows when used with a newer version of GCC. The
issue was first reported here:
https://github.com/golang/go/issues/46099
Shortly after the release of 1.19 someone had commented this issue was
solved for them, and after trying it out in some test runs on actions
machines, it seems to be the case. Disabling ASLR got things in order, and
PIE was disabled for -race builds in 1.19, so this is likely the reason
things work now:
https://github.com/golang/go/commit/0c7fcf6bd1fd8df2bfae3a482f1261886f6313c1.
The downgrade was mostly harmless except for two shortcomings:
1. It took quite a while for …
=> Revert "Downgrade MinGW to version 10.2.0"

cmd/ctr/commands/images/import.go
Currently, `ctr import` will use loose matching as defined by [platforms.Only(..)](https://github.com/containerd/containerd/blob/595ad06de7a6e886366de9bb7f73fcced366e235/platforms/compare.go#L94), meaning in the case of platform linux/amd64 as in issue #6441 , https://github.com/containerd/containerd/issues/6441#issuecomment-1098609359, importing will also match linux/386 platform on the image-to-be-imported's index. However, that image-to-be-imported may not have both the linux/amd64 and linux/386 platform contents, resulting in a failure to unpack the image :  `ctr: content digest sha256:abc123xyz: not found`, where the content not found is the image's manifest for the other platform.
This change makes that platform matching strict such that the requested platform to import for is the …
=> ctr import: strictly match platform

.github/workflows/ci.yml, .github/workflows/windows-periodic.yml, contrib/ansible/cri-containerd.yaml, docs/cri/config.md, docs/cri/crictl.md, integration/client/client_test.go, integration/client/image_test.go, integration/images/image_list.go, integration/images/image_list.sample.toml, pkg/cri/config/config_unix.go, pkg/cri/config/config_windows.go
Signed-off-by: Paco Xu <paco.xu@daocloud.io>
Kubernetes migrated to `registry.k8s.io` since https://github.com/kubernetes/kubernetes/pull/109938.
I'm not sure if contained should migrate to it in this release cycle 1.7. Or at least, pause image should migrate to `registry.k8s.io` .
Some context can be found in 
- https://github.com/kubernetes/k8s.io/wiki/New-Registry-url-for-Kubernetes-(registry.k8s.io)
- https://github.com/kubernetes/enhancements/blob/master/keps/sig-release/3000-artifact-distribution/README.md
- https://github.com/kubernetes/kubernetes/pull/110350
- https://github.com/kubernetes/kubernetes/issues/110471
[the k8s project is moving away from k8s.gcr.io to registry.k8s.io.](https://github.com/kubernetes/kubeadm/issues/2671) 
- registry.k8s.io is currently redirecting to …
=> migrate from k8s.gcr.io to registry.k8s.io

script/setup/install-cni
The dir related to CNI should be handled with sudo if EUID != 0.
Follow-up: 8add7e5d39
=> script/setup: handle cnidir with SUDO

mount/mount_windows.go
This error was added in c5843b761596564ba05f1a7f7b70c2368baf93ab (https://github.com/containerd/containerd/pull/700), but no longer used since a5a9f91832f9f414a24626173ad5471df3abdb27 (https://github.com/containerd/containerd/pull/1969), which implemented Windows support.
=> mount: remove unused ErrNotImplementOnWindows

archive/tar.go, archive/tar_unix.go, archive/tar_windows.go
This code was copied from github.com/moby/moby/pkg/archive; https://github.com/moby/moby/commit/28842d3f093e69cf62a090a532aacba1e6ff6d1c, which got later simplified in
https://github.com/moby/moby/commit/a5aed699cfaa4d84b1b134033fb468b3a7a874f0
This patch aligns the containerd implementation with those changes, and uses `filepath.ToSlash()` unconditionally on all platforms, as it's a no-op on platforms that use a forward-slash; https://github.com/golang/go/blob/go1.19/src/path/filepath/path.go#L175-L183
=> archive: replace tarName() with filepath.ToSlash()

integration/client/client_test.go, integration/client/container_fuzzer.go, integration/client/helpers_unix.go, integration/client/helpers_windows.go, integration/client/restart_monitor_test.go, sys/filesys_windows.go
ForceRemoveAll was only used in tests/fuzzing, but added hcsshim as dependency
for the sys package. Moving this to integration/client makes the "sys" package
slightly more lightweight, and may help simplifying dependency-management.
=> sys: move ForceRemoveAll to integration/client

RELEASES.md
https://github.com/kubernetes/kubernetes/releases/v1.25.0
There seems to be no containerd related change
CRI changes are like below(v1.25 with v1.24):
- in-place resource update https://github.com/kubernetes/kubernetes/pull/111645 
- evented PLEG https://github.com/kubernetes/kubernetes/pull/111642
- user namespace https://github.com/kubernetes/kubernetes/pull/110535
- checkpoint support https://github.com/kubernetes/kubernetes/pull/104907
**containerd v1.6.8** is using **cri-api v0.23.1** that is same as **containerd v1.6.4**
=> Add kubernetes v1.25 supported version as v1.24

.github/workflows/ci.yml
Our GitHub Actions CI timeout setting was different than the config
file; we are now getting somewhat regular timeouts on the Windows
linting jobs so this should solve that and give us room in case runs
start taking longer
=> Update golangci-lint timeout to match config

metrics/cgroups/v1/oom.go
The event parameter wasn't actually used when processing oom events, likely because it's only ever available for reads.
Additionally clarify flush is for eventfds, and point to where the buffer size of 8 is coming from.
=> metrics/cgroups/v1: Remove unused event parameter

integration/container_update_resources_test.go
This comment was added in 09a0c9471bf687ebcc7d8f8594606d127b3a803e (https://github.com/containerd/containerd/pull/5163) when the Windows integration tests were enabled. The PR (microsoft/hcsshim#931) was merged, and part of hcsshim v0.9.0, and support for resource limits on Windows was added in 2bc77b8a2865efe83bc50225223555a919191f54 (https://github.com/containerd/containerd/pull/5778), so it looks like this comment is no longer current.
=> integration: TestUpdateContainerResources_MemoryLimit: remove TODO comment

.github/workflows/images.yml
Ran `actionlint` against all our actions and it found this variable that
is based on a non-existent property (there is no matrix definition in
this action yaml). The variable is also unused so simply removing it.
=> Remove unused variable from images action

go.mod, go.sum, integration/client/go.mod, integration/client/go.sum, vendor/golang.org/x/net/http2/frame.go, vendor/golang.org/x/net/http2/hpack/encode.go, vendor/golang.org/x/net/http2/hpack/hpack.go, vendor/golang.org/x/net/http2/http2.go, vendor/golang.org/x/net/http2/server.go, vendor/golang.org/x/net/http2/transport.go, vendor/modules.txt
Update to the latest version that contains a fix for CVE-2022-27664; https://github.com/golang/net/commit/f3363e06e74cdc304618bf31d898b78590103527
=> vendor: golang.org/x/net v0.0.0-20220906165146-f3363e06e74c

.github/workflows/build-test-images.yml, .github/workflows/ci.yml, .github/workflows/codeql.yml, .github/workflows/images.yml, .github/workflows/nightly.yml, .github/workflows/release.yml, Vagrantfile, contrib/Dockerfile.test, contrib/fuzz/oss_fuzz_build.sh, script/setup/prepare_env_windows.ps1
From the mailing list:
We have just released Go versions 1.19.1 and 1.18.6, minor point releases. These minor releases include 2 security fixes following the security policy:
- net/http: handle server errors after sending GOAWAY A closing HTTP/2 server connection could hang forever waiting for a clean shutdown that was preempted by a subsequent fatal error. This failure mode could be exploited to cause a denial of service.
Thanks to Bahruz Jabiyev, Tommaso Innocenti, Anthony Gavazzi, Steven Sprecher, and Kaan Onarlioglu for reporting this.
This is CVE-2022-27664 and Go issue https://go.dev/issue/54658.
- net/url: JoinPath does not strip relative path components in all circumstances JoinPath and URL.JoinPath would not remove `../` path components appended to a relative path. For example, …
=> Update to go 1.19.1, 1.18.6 to address CVE-2022-27664, CVE-2022-32190

pkg/cri/config/config_windows.go
As part of the effort of getting Windows hypervisor isolated container support working for the CRI entrypoint here, add the runhcs-wcow-hypervisor handler to the default config. This sets the correct SandboxIsolation value that the Windows shim uses to differentiate process vs. hypervisor isolation. This additionally allows io.microsoft.container* annotations for the wcow-process runtime and io.microsoft.virtualmachine* annotations for the vm based runtime.
Note that for K8s users this runtime handler will need to be configured by creating the corresponding RuntimeClass resources on the cluster as it's not the default runtime. 
~~This needs a change in the shim that actually sets the HyperV field on the runtime spec to work properly, see here: …
=> windows: Add runhcs-wcow-hypervisor runtimeclass to the default config

archive/issues_test.go, archive/tar.go, archive/tar_opts.go, diff/apply/apply_darwin.go, diff/windows/windows.go, install.go
When unpacking a TAR archive, containerd preserves file's owner: https://github.com/containerd/containerd/blob/main/archive/tar.go#L384
In some cases this behavior is not desired. In current implementation we avoid `Lchown` on Windows. Another case when this should be skipped is when using native snapshotter on darwin and running as non-root user.
This PR extracts a generic option - `WithNoSameOwner` (same as `tar --no-same-owner`) to skip `Lchown` when its not required.
=> Add NoSameOwner option when unpacking tars

pkg/cri/server/image_pull.go, remotes/docker/config/hosts.go, remotes/docker/resolver.go
issue: https://github.com/containerd/containerd/issues/7392
After configuring config_path for the cri plugin, it doesn't handle the case where the host is local. 
We also need to skipping TLS verification for localhost.
=> remotes/docker/config: Skipping TLS verification for localhost

contrib/fuzz/archive_fuzzer.go, contrib/fuzz/fuzz_FuzzImportIndex.dict, contrib/fuzz/fuzz_FuzzImportIndex.options, contrib/fuzz/oss_fuzz_build.sh
This instruments `images/` with new sanitizers/bug detectors that AdaLogics are developing to work with fuzzing. 
The plan is to start with a small part of Containerd and if everything runs well move on to the entire project. I will observe the OSS-Fuzz dashboard closely for any breakages.
No extra work is required from the Containerd side. Everything should work as usual.
@kzys 
Needs https://github.com/google/oss-fuzz/pull/8504 to be merged first - this is why CIFuzz is failing.
=> Fuzzing: Instrument with new sanitizers

snapshots/devmapper/config.go, snapshots/devmapper/snapshotter.go
This PR adds support for ext2fs for devmapper snapshotter.
We have a use-case (NetBSD) where ext4 or xfs is not an option and since adding ext2 support could be a configurable parameter (`fs_type = "ext2"` in `config.toml`), and not that intrusive, it didn't seem like such a bad idea.
FYI, we are building a custom handler to boot unikernels -- we are trying to minimize the steps to prepare the storage part, and if we could give the snapshot directly to the unikernel, that would save us the time from generating an image file or doing some other kind of hack.
=> Add ext2 fs support to devmapper snapshotter

.github/workflows/scorecards.yml
Hi, I've openned the PR in the wrong repo (https://github.com/containerd/project/issues/91 and https://github.com/containerd/project/pull/92)
Here is the activation of the Scorecard Github Action and Badge to the containerd correct repo.
Thanks!
=> Enable OpenSSF Scorecard Github Action

pkg/cri/sbserver/container_create.go, pkg/cri/sbserver/container_status.go, pkg/cri/sbserver/container_update_resources.go, pkg/cri/sbserver/helpers.go, script/test/utils.sh
`make cri-integration` wasn't properly propagating `ENABLE_CRI_SANDBOXES`, meaning we were not fully testing the `sbserver` CRI implementation.  This PR fixes that and also ports over some changes from https://github.com/containerd/containerd/pull/6517 that hadn't made it into `sbserver` (and weren't caught because CI wasn't running the tests against that implementation).
(cc @ruiwen-zhao)
=> cri-integration: propagate ENABLE_CRI_SANDBOXES

docs/cri/config.md, pkg/cri/config/config.go
Referenced CDI configuration details as requested in [this review comment](https://github.com/containerd/containerd/pull/6654/commits/c9b4ccf83ee681ccff020de3d6c67db4f35a3fd6#r842004044)
=> reference CDI configuration details

content/helpers.go, content/local/readerat.go
Allows optimized copying from a local content file into another file.
Using a `*LimitedReader` allows for an optimized copy file range to be performed when copying into a `*os.File` on Linux. Currently our custom type or use of section reader hide the source `*os.File`. 
See https://cs.opensource.google/go/go/+/refs/tags/go1.19.1:src/os/readfrom_linux.go;drc=f1b7b2fc52947711b8e78f7078c9e0bda35320d3;l=14
=> Add reader option to local content reader at

pkg/cri/sbserver/container_checkpoint.go, pkg/cri/sbserver/container_events.go, pkg/cri/server/container_checkpoint.go, pkg/cri/server/container_events.go
Replaces unimplemented errors with `status.Errorf` and grpc code `Unimplemented` set.
xref: https://github.com/containerd/containerd/pull/7410#issuecomment-1254535922
cc @dmcgowan
=> Set grpc code for unimplemented cri-api methods

cio/io.go, cio/io_test.go, cio/io_unix_test.go, cio/io_windows_test.go
Checking / is not the right way to distinguish an absolute path in
Windows.
Fixes #5786.
=> Fix LogURIGenerator on Windows

pkg/cri/server/container_checkpoint.go, pkg/cri/server/container_events.go
Signed-off-by: ruiwen-zhao <ruiwen@google.com>
This is a cherry-pick of https://github.com/containerd/containerd/pull/7417
=> [release/1.6] cherry-pick: Set grpc code for unimplemented cri-api methods

integration/client/client_test.go, integration/client/container_linux_test.go
For some shims (namely github.com/cpuguy83/containerd-shim-systemd-v1), the shim cgroup test doesn't make sense since there is only a single shim process for the entire node.
I use these integration tests to make sure the shim is compatible with the runc shims and generally works as expected. This will let me skip the shim cgroup test as there is no process for the shim to stick into the cgroup... mostly.
There is a bootstrap process as well as a PTY copier proces which do use the shim cgroup if provided, but the test is not able to check for those (unless we enable tty on the test, which is a bit arbitrary and not useful).
Signed-off-by: Brian Goff <cpuguy83@gmail.com>
=> Add test flag for skipping shim cgroup test

.github/workflows/ci.yml, Vagrantfile, script/setup/install-teststat, script/test/test2annotation.jq, script/test/test2annotation.sh
Uses teststat to parse the go test json and output markdown which will
be posted as a summary to the github action run.
Also adds annotations for failed tests so the test failure is surfaced right into the github summary.
If the error occurred for a test in the diff, the annotation will also appear in the diff at the line number of the failure.
It uses the last test log message to determine the file/line number.
One thing I noticed with this, not all log messages originate from a `_test.go`, in which case the file/line number are not attached to the annotation.
=> CI: Output a summary using GITHUB_SUMMARY

pkg/cri/server/image_pull.go, remotes/docker/config/hosts.go, remotes/docker/resolver.go
cherry pick: https://github.com/containerd/containerd/pull/7393
=> [release/1.6] remotes/docker/config: Skipping TLS verification for localhost

archive/tar.go
(cherry picked from commit 68a55fe8bdba268d0ccb301cee8a085958bf9275)
Cherry-pick of #7094 for `release/1.5`
=> [release/1.5] cherry-pick: make xattr EPERM non-fatal in createTarFile

archive/tar.go
(cherry picked from commit 68a55fe8bdba268d0ccb301cee8a085958bf9275)
Cherry-pick of #7094 for `release/1.6`
=> [release/1.6] cherry-pick: make xattr EPERM non-fatal in createTarFile

cmd/containerd-shim/main_unix.go, runtime/v2/shim/shim.go, services/server/server.go
In Go 1.16 `net.ErrClosed` was exported, removing the need to check the exact text of "use of closed network connection". The stdlib's net listeners are all setup for this to be a reality, but on Windows containerd uses the the go-winio projects named pipe implementation as the listener for services. Before version 0.6.0 this project returned a different error named `ErrPipeListenerClosed` for using a closed pipe, where this error was just an `errors.New` with the same text as `net.ErrClosed`, so checking against `net.ErrClosed` wasn't possible.
Starting in 0.6.0 go-winio has that error assigned to `net.ErrClosed` directly so this *should* be alright to finally change.
=> Swap to net.ErrClosed checks for services

docs/cri/config.md
This PR updates the url for the kata containers reference about how to use kata containers and containerd for untrusted workloads.
Signed-off-by: Gabriela Cervantes <gabriela.cervantes.tellez@intel.com>
=> cri doc: Update kata containers reference

remotes/docker/pusher.go, remotes/docker/pusher_test.go, remotes/docker/status.go
`dockerPusher` provides `pushWriter` which implements `content.Writer`. However, even if `pushWriter` become abort status (i.e. `Close()` is called before `Commit()`), `dockerPusher` doesn't recognise that status and treats that writer as on-going.
This behaviour doesn't allow the client to retry an aborted push.
This commit fixes this issue.
This commit also adds an test to ensure that the issue is fixed.
Signed-off-by: Kohei Tokunaga <ktokunaga.mail@gmail.com>
(cherry picked from commit a97564411cf8f306983915f75de774828ebbd712)
Signed-off-by: Phil Estes <estesp@gmail.com>
=> [release/1.5] cherry-pick: remotes: fix dockerPusher to handle abort correctly

docs/getting-started.md
Referencing the raw link to the containerd.service may enhance the developer experience by enabling those following the docs to use the raw link directly to `wget` or `curl` the file without additional navigation.
Signed-off-by: Kyle L Frisbie <KyleFrisbie@users.noreply.github.com>
=> use raw link to containerd.service config

.github/workflows/build-test-images.yml, .github/workflows/ci.yml, .github/workflows/codeql.yml, .github/workflows/images.yml, .github/workflows/nightly.yml, .github/workflows/release.yml, Vagrantfile, contrib/Dockerfile.test, contrib/fuzz/oss_fuzz_build.sh, script/setup/prepare_env_windows.ps1
From the mailing list:
We have just released Go versions 1.19.2 and 1.18.7, minor point releases.
- archive/tar: unbounded memory consumption when reading headers
Reader.Read did not set a limit on the maximum size of file headers. A maliciously crafted archive could cause Read to allocate unbounded amounts of memory, potentially causing resource exhaustion or panics. Reader.Read now limits the maximum size of header blocks to 1 MiB.
Thanks to Adam Korczynski (ADA Logics) and OSS-Fuzz for reporting this issue.
This is CVE-2022-2879 and Go issue https://go.dev/issue/54853.
- net/http/httputil: ReverseProxy should not forward unparseable query parameters
Requests forwarded by ReverseProxy included the raw query …
=> Update to go 1.19.2 to address CVE-2022-2879, CVE-2022-2880, CVE-2022-41715

content/helpers.go, content/helpers_test.go, remotes/docker/pusher.go, remotes/docker/pusher_test.go
Cherry-pick (clean) #6995
when a put request is retried due to the response from registry, the body of the request should be seekable. A dynamic pipe is added to the body so that the content of the body can be read again. Currently a maximum of 5 resets are allowed, above which will fail the request. A new error ErrReset is introduced which informs that a reset has occured and request needs to be retried.
also added tests for Copy() and push() to test the new functionality
Signed-off-by: Akhil Mohan <makhil@vmware.com>
(cherry picked from commit 8f4c23b69f4f21c964cc097a5156e6eb22f1ed67)
Signed-off-by: Akhil Mohan <makhil@vmware.com>
=> [release/1.6] retry request on writer reset

contrib/fuzz/archive_fuzzer.go
`TarBytes` has undergone some work with a few more improvements which makes it more suitable for the archive fuzzer.
@kzys 
=> fuzzing: create structured tar bytes in archive fuzzer

images/archive/exporter.go, images/archive/importer.go
digest.Algorithm() and digest.Encoded() may panic for invalid digests. Validate prior to calling those methods.
=> archive: validate digests before use

archive/time_windows.go
It looks like this function was converting the time (`windows.NsecToTimespec()`), only to convert it back (`windows.TimespecToNsec()`). This became clear when moving the lines together:
```go
ctimespec := windows.NsecToTimespec(ctime.UnixNano())
c := windows.NsecToFiletime(windows.TimespecToNsec(ctimespec))
```
And looking at the Golang code, it looks like they're indeed the exact reverse:
```go
func TimespecToNsec(ts Timespec) int64 { return int64(ts.Sec)*1e9 + int64(ts.Nsec) }
func NsecToTimespec(nsec int64) (ts Timespec) {
ts.Sec = nsec / 1e9
ts.Nsec = nsec % 1e9
return
}
```
While modifying this code, also renaming the `e` variable to a more common `err`.
=> archive: windows: chtimes(): remove redundant conversion

cmd/ctr/commands/images/import.go, import.go
Add a new ctr cli option, allowing the garbage collector to discard any unpacked layers after importing an image. This new option is incompatible with the no-unpack ctr import option. This addresses issue #7125.
=> Add new ctr option for discarding unpacked layers

diff/apply/apply.go
`rc.r.Read()` may return a negative `int` on an error when the reader is set to a custom content store implementation
=> diff/apply.readCounter: check negative size

integration/main_test.go, integration/restart_test.go, integration/sandbox_run_rollback_test.go, pkg/cri/server/container_update_resources_other.go, pkg/cri/server/sandbox_run.go, script/test/utils.sh
This is to fix a bug introduced in https://github.com/containerd/containerd/pull/5904.
When the network namespace is created, we need to update both container spec and sandbox metadata so that both information can persist on disk. If sandbox metadata is missing, the NetNS is considered as closed when loading sandbox during restart recovery because the NetNS.path is empty. Closed NetNS will affect network teardown in sandbox stop.
1. Add a sleep in `setupPodNetwork`, e.g. 60s
2. `sudo crictl runp sandbox.json`
3. Restart containerd
4. `sudo crictl pods` shows the <POD ID>
Before fix: `sudo crictl inspectp <POD ID>` shows `"netNamespaceClosed": true`
After fix: `sudo crictl inspectp <POD ID>` shows `"netNamespaceClosed": false`
```
ENABLE_CRI_SANDBOXES="" CONTAINERD_RUNTIME=runc …
```
=> Update container with sandbox metadata after NetNS is created

integration/main_test.go, integration/restart_test.go, integration/sandbox_run_rollback_test.go, pkg/cri/server/container_update_resources_other.go, pkg/cri/server/sandbox_run.go, script/test/utils.sh
Backport https://github.com/containerd/containerd/pull/7481 to release/1.6
```
ENABLE_CRI_SANDBOXES="" CONTAINERD_RUNTIME=runc FOCUS=TestRunPodSandboxAndTeardownCNISlow make cri-integration
```
=> [release/1.6] Update container with sandbox metadata after NetNS is created

cmd/containerd/command/service_windows.go
- relates to https://github.com/containerd/containerd/pull/7349#discussion_r990638738
- relates to https://github.com/containerd/containerd/pull/4626
The `//nolint` comment was added in https://github.com/containerd/containerd/commit/edc671d6a0192111e20578fc19531cb74fd8ce96 (https://github.com/containerd/containerd/pull/4626) to suppress the deprecation warning.
The `IsAnInteractiveSession` was deprecated, and `IsWindowsService` is marked as the recommended replacement.
For details, see https://github.com/golang/sys/commit/280f808b4a5303f80a30dd9dc62f9a042d992ad0
> CL 244958 includes isWindowsService function that determines if a
> process is running as a service. The code of the function is based on
> public .Net implementation.
>
> IsAnInteractiveSession function implements similar …
=> cmd/containerd: replace deprecated windows.IsAnInteractiveSession()

go.mod, go.sum, integration/client/go.mod, integration/client/go.sum, oci/spec_opts.go, oci/spec_opts_windows_test.go, vendor/github.com/opencontainers/image-spec/specs-go/v1/annotations.go, vendor/github.com/opencontainers/image-spec/specs-go/v1/artifact.go, vendor/github.com/opencontainers/image-spec/specs-go/v1/config.go, vendor/github.com/opencontainers/image-spec/specs-go/v1/descriptor.go, vendor/github.com/opencontainers/image-spec/specs-go/v1/manifest.go, vendor/github.com/opencontainers/image-spec/specs-go/v1/mediatype.go, vendor/github.com/opencontainers/image-spec/specs-go/version.go, vendor/modules.txt
ArgsEscaped has now been merged into upstream OCI image spec. This change removes the workaround we were doing in containerd to deserialize the extra json outside of the spec and instead just uses the formal spec types.
=> Updates oci image config to support upstream ArgsEscaped

.github/workflows/build-test-images.yml, .github/workflows/ci.yml, .github/workflows/codeql.yml, .github/workflows/fuzz.yml, .github/workflows/images.yml, .github/workflows/nightly.yml, .github/workflows/release.yml, .github/workflows/windows-periodic.yml
Updates checkout and setup-go actions to ones that run on Node.js 16.
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
=> Move up actions versions to prep for NodeJS 12 deprecation

runtime/v2/runc/v1/service.go
Like other exported methods, Stats() shouldn't assume s.container is non-nil.
Fixes #7468.
=> Stats() shouldn't assume s.container is non-nil

contrib/seccomp/seccomp_default.go
Signed-off-by: Zhuchen Wang <zcwang@google.com>
Fix #7442
=> Update the default seccomp to block socket calls to AF_VSOCK

cmd/ctr/commands/tasks/start.go, cmd/ctr/commands/tasks/tasks_unix.go, cmd/ctr/commands/tasks/tasks_windows.go
```bash
$ ctr tasks start -h
NAME:
ctr tasks start - start a container that has been created
USAGE:
ctr tasks start [command options] CONTAINER
OPTIONS:
--null-io         send all IO to /dev/null
--log-uri value   log uri
--fifo-dir value  directory used for storing IO FIFOs
--pid-file value  file path to write the task's pid
--detach, -d      detach from the task after it has started execution
```
->
```bash
$ ctr tasks start -h
NAME:
ctr tasks start - start a container that has been created
USAGE:
ctr tasks start [command options] CONTAINER
OPTIONS:
--no-pivot        disable use of pivot-root (linux only)
--null-io         send all IO to /dev/null
--log-uri value   log uri
--fifo-dir value  directory used for storing IO FIFOs
--pid-file value  file path to write the task's pid
--detach, …
```
=> fix the --no-pivot flag being ignored by `ctr tasks start`

.github/workflows/ci.yml, .github/workflows/release.yml
The release binaries are built using Ubuntu 18.04 in Docker on Ubuntu 20.04 for glibc compatibility reason (issue #7255).
Fix #7297
- - -
Test release: https://github.com/AkihiroSuda/containerd/releases/tag/v1.7.0-prealpha.202210071413
https://github.com/AkihiroSuda/containerd/actions/runs/3202415035
=> CI: update GHA instances from Ubuntu 18.04 to 20.04

pkg/cri/sbserver/sandbox_status.go, pkg/cri/server/sandbox_status.go
This should help with the flaky `TestSandboxRemoveWithoutIPLeakage`.
=> cri: PodSandboxStatus should tolerate missing task

sys/filesys_windows.go
This function was forked from Moby in 6089c1525b665876307d43fb94f9e8ed76eb40a1 (https://github.com/containerd/containerd/pull/542), which copied the whole file, but the `IsAbs()` was never used, and has no external consumers, so let's remove it.
=> sys: remove unused IsAbs() (windows)

Vagrantfile
=> Vagrantfile: explicitly specify rsync as the shared folder driver

.github/workflows/build-test-images.yml, .github/workflows/codeql.yml, .github/workflows/fuzz.yml, .github/workflows/images.yml, .github/workflows/nightly.yml, .github/workflows/windows-periodic.yml
I've opened a PR recently and fuzz CI job ran for 5 hours until I noticed and cancelled it (https://github.com/containerd/containerd/actions/runs/3253110550/jobs/5340055841).
I think it'd be sane idea to have timeouts on all CI jobs.
This PR adds `timeout-minutes` (based on recent run times) to avoid wasting node resources.
=> Add timeouts to all CI jobs

runtime/v2/bundle.go
When calling `Bundle.Delete` on Darwin, it attempts to unmount rootfs, which is not supported. This PR skips unmount for this platform, just deleting the directory would be sufficient.
=> Don't unmount on Darwin when deleting bundle

Makefile
=> Use `go env` to determine GOPATH in Makefile.

go.mod, go.sum, integration/client/go.sum, vendor/modules.txt
it's the same commit: https://github.com/matttproud/golang_protobuf_extensions/compare/v1.0.2...c182affec369
=> go.mod: matttproud/golang_protobuf_extensions v1.0.2 (use tag)

BUILDING.md
Our main branch no longer builds successfully with Go 1.17.
=> Update required Go version in BUILDING.md

tracing/plugin/otlp.go
Fix: https://github.com/containerd/containerd/issues/7540
containerd should not try to init a tracing processor when the tracing plugin itself is not loaded
Signed-off-by: Joseph Sheng <jiajun.sheng@microfocus.com>
=> containerd should not print error log that failed to init a tracing processor while the tracing plugin is not loaded

pkg/cri/server/sandbox_status.go
Backport of https://github.com/containerd/containerd/pull/7535
Cherry pick was clean except for the sbserver file, which was removed.
=> [release/1.6] cri: PodSandboxStatus should tolerate missing task

contrib/ansible/cri-containerd.yaml, docs/cri/config.md, docs/cri/crictl.md, integration/client/client_test.go, integration/client/image_test.go, integration/common.go, pkg/cri/config/config_unix.go, pkg/cri/config/config_windows.go
Cherry-pick of https://github.com/containerd/containerd/pull/7038
Signed-off-by: Paco Xu <paco.xu@daocloud.io>
(cherry picked from commit 9525b3148a3b6213a7a80f8f1e1fd016b9301669)
Signed-off-by: Sergey Kanzhelev <S.Kanzhelev@live.com>
=> [release/1.5] migrate from k8s.gcr.io to registry.k8s.io

runtime/v2/runc/v1/service.go
Like other exported methods, Stats() shouldn't assume s.container is non-nil.
Fixes #7468.
(cherry picked from commit 49a54e23cb2db8080c40383abcc180d45f0efea5)
=> [release/1.6] Stats() shouldn't assume s.container is non-nil

runtime/v2/runc/v1/service.go
Like other exported methods, Stats() shouldn't assume s.container is non-nil.
Fixes #7468.
(cherry picked from commit 49a54e23cb2db8080c40383abcc180d45f0efea5)
=> [release/1.5] Stats() shouldn't assume s.container is non-nil

remotes/docker/pusher.go, remotes/docker/pusher_test.go
goroutine1:https://github.com/containerd/containerd/blob/8abee9c8bb98237fb3936331abdd8f0a48bec05b/remotes/docker/pusher.go#L290
goroutine2: https://github.com/containerd/containerd/blob/8abee9c8bb98237fb3936331abdd8f0a48bec05b/remotes/docker/pusher_test.go#L152
Use `sync.Once` to ensure that `close(pw.pipeC)` is executed only once.
issue: https://github.com/containerd/containerd/issues/7471
=> fix pusher concurrent close channel

RELEASES.md
- Adds definition of LTS releases
- Marks 1.6 as an LTS release
The main motivation behind this addition is to support innovative work going on in containerd while continuing to maintain the most stable version of the software today. The 1.7 release will include new interfaces and implementations of core components of containerd, and while some of these may not be enabled by default in the 1.7 release, they are planned to be either enabled by default or the only options for the following 2.0 release. We expect these implementations to quickly be just as stable and reliable as what exists today, but we recognize the risk of any significant software change to core components. As a project, we must adapt and innovate along with the wider ecosystem, while continuing to be that boring stable …
=> Add long term stable release branches

RELEASES.md
The 1.5 release is not ready for End of Life and recent fixes may require further support than just security updates. This pushes out the End of Life 3 months.
=> Update 1.5 release support timeframe

Vagrantfile, contrib/Dockerfile.test, script/setup/install-cni
Replace the source of the read value, from `"$GOPATH"/src/github.com/containerd/containerd/go.mod` changing to `go.mod` or `../../go.mod`.
issue: https://github.com/containerd/containerd/issues/7472
=> fix install cni script

sys/filesys_windows.go
See individual commits for details 😄 
Ideally, we would construct this lazily, but adding a function and a
sync.Once felt like a bit "too much".
Also updated the GoDoc for some functions to better describe what they do.
The regex only matched volume paths without a trailing path-separator. In cases
where a path would be passed with a trailing path-separator, it would depend on
further code in mkdirall to strip the trailing slash, then to perform the regex
again in the next iteration.
While regexes aren't ideal, we're already executing this one, so we may as well
use it to match those situations as well (instead of executing it twice), to
allow us to return early.
The same attribute was generated for each path that was created, but always
the same, so instead of generating it in each …
=> sys: optimize and refactor MkdirAllWithACL()

remotes/docker/pusher.go, remotes/docker/pusher_test.go
cherry-pick: 63a7d8a7ff291066b0684e8a62ff598684b8056e
=> [release/1.6] fix pusher concurrent close channel

pkg/cri/io/logger.go, pkg/cri/io/metrics.go
This PR adds logging related metrics in the Containerd CRI plugin. Metrics are per Containerd instance. Metrics can be used to estimate logging completeness of Containerd and logging completeness of logging pipeline (when combined with logging agent metrics). See design details below.
```mermaid
graph LR
A[Customer Workload] -- Output --> B((stdout/stderr))
B -- Retrive --> C[Containerd]
C -- Output --> D((disk))
D -- Retrive --> E[Logging Agent]
E -- Output --> F[Sink]
G[Log Rotator] -- Rotate --> D
```
The graph above shows a common architecture of a logging pipeline. Customer workloads output their logs to stdout/stderr. [Containerd](https://containerd.io/) reads those logs and outputs them to log files on disk. Logging agents read log files from disk and exports logs to various sinks …
=> Add logging related metrics to Containerd CRI plugin

integration/client/go.mod, integration/client/go.sum, oci/spec_opts_linux.go, pkg/cri/opts/spec_linux.go, pkg/cri/sbserver/container_create_linux.go, pkg/cri/sbserver/container_create_linux_test.go, pkg/cri/sbserver/service_linux.go, pkg/cri/server/container_create_linux.go, pkg/cri/server/container_create_linux_test.go, pkg/cri/server/service_linux.go
Currently CDI registry is reconfigured on every WithCDI call, which is a relatively heavy operation.
This happens because cdi.GetRegistry(cdi.WithSpecDirs(cdiSpecDirs...)) unconditionally reconfigures the registry (clears fs notify watch, sets up new watch, rescans directories).
Moving configuration to the criService.initPlatform should result in performing registry configuration only once on the service start.
=> Configure CDI registry only on start

pkg/cri/opts/spec_windows.go, pkg/cri/sbserver/container_create_windows.go, pkg/cri/sbserver/podsandbox/sandbox_run_windows.go, pkg/cri/server/container_create_windows.go, pkg/cri/server/sandbox_run_windows.go
Was perusing around for a different TODO and saw one in pkg/cri/opts that stated that `WithWindowsNetworkNamespace` should be moved to the main containerd pkg. This was done in #6304 already (well, to the /oci pkg) so we're good to get rid of the CRI version. This additionally swaps all uses of `WithWindowsNetworkNamespace` to the oci packages impl.
=> maintenance: Remove WithWindowsNetworkNamespace from pkg/cri

cio/io_test.go, cio/io_unix_test.go, cio/io_windows_test.go
=> Fix LogURI generation-related tests on Windows.

contrib/seccomp/seccomp_default.go
This PR is to cherry-pick #7301 "Adding support of CAP_BPF and CAP_PERFMON "
=> [release/1.6] adding support of CAP_BPF and CAP_PERFMON

.mailmap, releases/v1.6.9.toml, version/version.go
Release notes: https://gist.github.com/samuelkarp/154e92eb3b86df6c4e07f7e9c9c1c04a
=> [release/1.6] Prepare release notes for v1.6.9

.github/workflows/release.yml, .github/workflows/windows-periodic.yml
Migrate from set-output call to write to new GITHUB_OUTPUT environment file.
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
Resolves #7580 
=> Update GitHub actions release workflow set output

.github/workflows/release.yml
Migrate from set-output call to write to new GITHUB_OUTPUT environment file.
Related issue: https://github.com/containerd/containerd/issues/7580
(cherry picked from commit be3987a92d6e5f10ba07a3b9925c26f3c66921cb)
=> [release/1.5] cherry-pick: Migrate away from GitHub actions set-output

.github/workflows/release.yml, .github/workflows/windows-periodic.yml
Migrate from set-output call to write to new GITHUB_OUTPUT environment file.
Related issue: https://github.com/containerd/containerd/issues/7580
(cherry picked from commit be3987a92d6e5f10ba07a3b9925c26f3c66921cb)
=> [release/1.6] cherry-pick: Migrate away from GitHub actions set-output

integration/client/container_linux_test.go, integration/client/daemon.go
Issue: #7422
* Increased context timeout to 4 sec
* Retry client connection errors until context deadline in `waitForStart`
=> Retry client connection in  waitForStart

cmd/ctr/commands/images/import.go
Currently, ctr import will use loose matching as defined by platforms.Only(), meaning in the case of platform linux/amd64 as in issue#6441, importing will also match linux/386 platform on the image-to-be-imported's index. However, that image-to-be-imported may not have both the linux/amd64 and linux/386 platform contents, resulting in a failure to unpack the image. This change makes that check strict such that the requested platform to import for is the only platform content imported. Both ctr pull and ctr export will treat the platform option as strict, so this change makes ctr import consistent with those.
resolves #6441
(cherry picked from commit 2c98a7b099b00316c0331a91927e54f85d4ec187)
=> [release/1.6] ctr import: strictly match platform

client.go, sandbox/proxy/controller.go, sandbox/proxy/store.go, services.go
Following how some of the other stores/services are returned in the client package, it makes sense to me to move the remoteFooBars in the sandbox API to a proxy sub-package under /sandbox. Given this has only been in a 1.7 beta, I hope this is fine to move around still.
=> Sandbox API: Move remote impls to /sandbox/proxy

snapshots/overlay/overlayutils/check.go
Cleaning up TODO's. If we're on >= 5.11 we need userxattr so check the kernel version to skip the manual check via mounting. It feels odd to use contrib/seccomp here but the alternative is pulling that kernel parsing code out into the main pkgs. Another is using the moby parser but that's in moby/moby which is also a dep we don't want here..
=> overlayutils: Add fastpath for userxattr check

go.mod, go.sum, integration/client/go.mod, integration/client/go.sum, vendor/github.com/Microsoft/hcsshim/internal/hcs/errors.go, vendor/modules.txt
This bumps hcsshim to include a bug fix from https://github.com/microsoft/hcsshim/commit/cae120b42536adea72101e6a358183c74a0bdac5. 
You can see the full changelog here: https://github.com/microsoft/hcsshim/releases/tag/v0.9.5
=> [release/1.6] go.mod: Bump hcsshim to v0.9.5

cmd/ctr/commands/images/import.go, import.go
Included both commits from PR #6070
fix: wrong flag type
Signed-off-by: jonyhy <yun.hao@daocloud.io>
(cherry picked from commit 933ddaa6f870e10b1164d7a4a442c0e026ba7975)
feat: support import image for specific platform
Signed-off-by: jonyhy <yun.hao@daocloud.io>
(cherry picked from commit da16d492cd07ee7089aa8b000ba48f494f193147)
=> [release/1.5] feat: support import image for specific platform

.github/workflows/build-test-images.yml, .github/workflows/ci.yml, .github/workflows/codeql.yml, .github/workflows/fuzz.yml, .github/workflows/images.yml, .github/workflows/nightly.yml, .github/workflows/release.yml, .github/workflows/windows-hyperv-periodic-trigger.yml, .github/workflows/windows-hyperv-periodic.yml, .github/workflows/windows-periodic-trigger.yml, .github/workflows/windows-periodic.yml
Hi all! I took a look at the OpenSSF Scorecard results for the containerd repo and noticed it was getting a 0/10 for the GitHub workflow token permissions check.
I followed the guidance from the scorecard tool to apply the changes in this PR. Some were automated recommendations from their linked Step Security tool, and others I applied manually based on the warnings. 
The summary of the changes is adding:
* Top level permissions for workflows that had none.
* Least privilege Job level permissions based on the knowledgebase from Step Security for certain jobs
This is still getting a 0/10 for the check due to two remaining warnings (that I'll share) but the Aggregate score increased against my fork by 1.7 points.
The remaining 2 warnings are that the `build-test-images.yml` and `images.yml` …
=> Harden GITHUB_TOKEN permissions for OSSF Scorecard

cmd/ctr/commands/resolver.go
This PR fixes ctr crash when pulling with `--http-dump` and `--http-trace` simultaneously.
```
❯ sudo -E ./bin/ctr images pull --http-dump --http-trace docker.io/library/nginx:latest
2022/11/01 16:27:47 Unsolicited response received on idle HTTP channel starting with "HTTP/1.1 204 No Content\r\nConnection: close\r\n\r\n"; err=<nil>
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x46debec]
goroutine 1 [running]:
github.com/containerd/containerd/cmd/ctr/commands.NewDebugClientTrace.func3({{0x4b62e90?, 0xc00048a3e0?}, 0x0?, 0x4a?, 0x0?})
/Users/mxpv/Github/containerd/main/cmd/ctr/commands/resolver.go:203 +0x14c
net/http.(*Transport).getConn(0xc0003e8280, 0xc000494340, {{}, 0x0, {0x4a0496b, 0x4}, …
```
=> Fix ctr crash when pulling with --http-dump and --http-trace simultaneously

cmd/ctr/commands/images/export.go
When attempting to export an image without providing a specific platform(s)( eg: `ctr i export <output.tar> <image_ref>`) , ctr returns an error: ```ctr: content digest sha256:<hash>: not found``` . ctr exports default matcher [platforms.Default() ](https://github.com/containerd/containerd/blob/8167751f569c9374a6c3ef5b39a42629577a543a/platforms/defaults_unix.go#L39), uses the [Only()](https://github.com/containerd/containerd/blob/8167751f569c9374a6c3ef5b39a42629577a543a/platforms/compare.go#L94) match comparer which matches for a single platform and all its variants (IE linux/amd64 _and_ linux/386). The index/manifest list that is pulled when using ```ctr i pull <image_ref>```( without providing ```--all-platforms``` or `--platform` options) only pulls the platform that is relevant to the …
=> ctr export strictly matching

.github/workflows/build-test-images.yml, .github/workflows/ci.yml, .github/workflows/codeql.yml, .github/workflows/images.yml, .github/workflows/nightly.yml, .github/workflows/release.yml, Vagrantfile, contrib/Dockerfile.test, contrib/fuzz/oss_fuzz_build.sh, script/setup/prepare_env_windows.ps1
Fixes a runtime bug found in #7513
=> Bump go version to 1.19.3

cmd/ctr/commands/images/import.go
Currently, ctr import will use loose matching as defined by platforms.Only(), meaning in the case of platform linux/amd64 as in issue#6441, importing will also match linux/386 platform on the image-to-be-imported's index. However, that image-to-be-imported may not have both the linux/amd64 and linux/386 platform contents, resulting in a failure to unpack the image. This change makes that check strict such that the requested platform to import for is the only platform content imported. Both ctr pull and ctr export will treat the platform option as strict, so this change makes ctr import consistent with those.
resolves #6441
(cherry picked from commit 2c98a7b099b00316c0331a91927e54f85d4ec187)
=> [release/1.5] ctr import: strictly match platform

docs/tracing.md, integration/client/go.mod, integration/client/go.sum, pkg/cri/sbserver/helpers.go, pkg/cri/sbserver/image_pull.go, pkg/cri/sbserver/image_remove.go, pkg/cri/sbserver/image_status.go, pkg/cri/sbserver/instrumented_service.go, pkg/cri/server/helpers.go, pkg/cri/server/image_pull.go, pkg/cri/server/image_remove.go, pkg/cri/server/image_status.go, pkg/cri/server/instrumented_service.go, pkg/unpack/unpacker.go, pull.go, remotes/docker/resolver.go, tracing/helpers.go, tracing/log.go, tracing/plugin/otlp.go, tracing/tracing.go
Issue: #6550
Adding Otel spans to CRI  + client methods. 
This PR adds spans in CRI ImageService apis and `pull.go`
TODO: Add spans to CRI RuntimeService APIs
* Image_pull
* image_list
* image_status
* image_fsinfo
* image_remove
=> Add tracing spans in CRI image service and pull.go

docs/hosts.md, remotes/docker/config/config_unix.go, remotes/docker/config/config_windows.go
Add support for an optional `default` registry hosts config, should no other hosts config match. Discussed in #7597
=> Support default hosts.toml configuration

platforms/cpuinfo.go
cc @dfr
I'm not sure how to do better for arm32 but at least it's a step.
See https://github.com/samuelkarp/runj/issues/33#issuecomment-1244525428 for an example of the failure.
=> Fix "getCPUInfo for OS freebsd: not implemented" on FreeBSD/arm64

cmd/ctr/commands/content/content.go, remotes/docker/fetcher.go, remotes/docker/resolver_test.go, remotes/resolver.go
Fetching blobs without foreknown descriptors is useful for using a registry as a general-purpose CAS.
Related: `oras blob fetch` ([ORAS v0.15.0](https://github.com/oras-project/oras/releases/tag/v0.15.0))
```go
readCloser, incompleteDesc, err := fetcher.(remotes.FetcherByDigest).FetchByDigest(ctx, dgst)
```
```console
$ ctr content fetch-blob docker.io/library/debian:latest sha256:43d28810c1b4c28a1be3bac8e0e40fcc472b2bfcfcda952544ed99cb874d2b1a
{"architecture":"amd64","config":{"Hostname":"","Domainname":"","User":"","AttachStdin":false,"AttachStdout":false,"AttachStderr":false,"Tty":false,"OpenStdin":false,"StdinOnce":false,"Env":["PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"],"Cmd":["bash"],"Image":"sha256:357a26ba6784f85d683e053559f71c9c8783306e53526fbe8c481eb20384 …
```
=> remotes: add `FetcherByDigest` for fetching blobs without foreknown descriptors (useful for general-purpose CAS)

cmd/ctr/commands/images/export.go
Backport of #7615
Fixes: https://github.com/containerd/containerd/issues/5895
Signed-off-by: Yasin Turan <turyasin@amazon.com>
(cherry picked from commit 78ac0046a7af3ff5beeb53d56ba627ec0cf7b32d)
Signed-off-by: Yasin Turan <turyasin@amazon.com>
=> [release/1.6] ctr export strictly match default platform

.github/workflows/build-test-images.yml, .github/workflows/ci.yml, .github/workflows/codeql.yml, .github/workflows/images.yml, .github/workflows/nightly.yml, .github/workflows/release.yml, Vagrantfile, contrib/Dockerfile.test, script/setup/prepare_env_windows.ps1
- relates to https://github.com/containerd/containerd/pull/7620
On Windows, syscall.StartProcess and os/exec.Cmd did not properly
check for invalid environment variable values. A malicious
environment variable value could exploit this behavior to set a
value for a different environment variable. For example, the
environment variable string "A=B\x00C=D" set the variables "A=B" and
"C=D".
Thanks to RyotaK (https://twitter.com/ryotkak) for reporting this
issue.
This is CVE-2022-41716 and Go issue https://go.dev/issue/56284.
This Go release also fixes https://github.com/golang/go/issues/56309, a runtime bug which can cause random memory corruption when a goroutine exits with runtime.LockOSThread() set. This fix is necessary to unblock work to replace certain uses of pkg/reexec with unshared …
=> [release/1.6] update to Go 1.18.8 to address CVE-2022-41716

.github/workflows/ci.yml, .github/workflows/nightly.yml, .github/workflows/release.yml, Vagrantfile, contrib/Dockerfile.test
- relates to https://github.com/containerd/containerd/pull/7620
On Windows, syscall.StartProcess and os/exec.Cmd did not properly
check for invalid environment variable values. A malicious
environment variable value could exploit this behavior to set a
value for a different environment variable. For example, the
environment variable string "A=B\x00C=D" set the variables "A=B" and
"C=D".
Thanks to RyotaK (https://twitter.com/ryotkak) for reporting this
issue.
This is CVE-2022-41716 and Go issue https://go.dev/issue/56284.
This Go release also fixes https://github.com/golang/go/issues/56309, a runtime bug which can cause random memory corruption when a goroutine exits with runtime.LockOSThread() set. This fix is necessary to unblock work to replace certain uses of pkg/reexec with unshared …
=> [release/1.5] update to Go 1.18.8 to address CVE-2022-41716

.github/workflows/ci.yml, .github/workflows/release.yml
Fix: #7612 , there is nightly build available for s390x, could we package it in release assets without testing same as other projects which are lack of s390x machine for testing? 
Signed-off-by: huoqifeng <huoqif@cn.ibm.com>
=> s390x: build and package s390x bin in release assets

runtime/v2/shim/util_unix.go
When creating a socket for a shim on Darwin OS, it fails with permission error:
`
create new shim socket: listen unix /var/run/containerd/s/61a930be46013380e0376220342308b188da82e446ed263125ab52ccf5f96ce6: bind: permission denied
`
On OS X socket path needs `+x` in order to be created without elevating privileges.
=> Fix shim socket permissions on Darwin

content/local/store.go, content/local/store_test.go, contrib/fuzz/content_fuzzer.go
- relates to https://github.com/opencontainers/go-digest/pull/83
Both of these were deprecated in https://github.com/opencontainers/go-digest/commit/55f675811a1b915549933c64571fd86b2676ba76 (https://github.com/opencontainers/go-digest/pull/33), but the format of the GoDoc comments didn't follow the correct format, which caused them not being picked up by tools as "deprecated".
This patch updates uses in the codebase to use the alternatives.
=> Remove uses of deprecated go-digest.NewDigestFromHex, go-digest.Digest.Hex

snapshots/overlay/overlayutils/check.go
🍒: 4b2a23e7ea4bd324aa345b4b5ffbba638d3b9d81
Original commit msg:
"Cleaning up TODO's. If we're on >= 5.11 we need userxattr so check the kernel version to skip the manual check via mounting. It feels odd to use contrib/seccomp here but the alternative is pulling that kernel parsing code out into the main pkgs. Another is using the moby parser but that's in moby/moby which is also a dep we don't want here.."
=> [release/1.6] overlayutils: Add fastpath for userxattr check

cmd/ctr/commands/images/export.go
Backport of https://github.com/containerd/containerd/pull/7615
Fixes: https://github.com/containerd/containerd/issues/5895
Signed-off-by: Yasin Turan <turyasin@amazon.com>
(cherry picked from commit 78ac0046a7af3ff5beeb53d56ba627ec0cf7b32d)
Signed-off-by: Yasin Turan <turyasin@amazon.com>
=> [release/1.5] ctr export strictly match default platform

pkg/cri/config/config.go, pkg/cri/config/config_test.go, pkg/cri/config/config_unix.go, pkg/cri/sbserver/sandbox_remove.go, pkg/cri/sbserver/sandbox_run.go, pkg/cri/sbserver/sandbox_stop.go, pkg/cri/sbserver/service.go, pkg/cri/sbserver/service_test.go
Works for #7312:
Add a new config as sandbox controller mod, which can be either
"podsandbox" or "shim". If empty, set it to default "podsandbox"
when CRI plugin inits.
Signed-off-by: Zhang Tianyang <burning9699@gmail.com>
=> Sandbox API: Add a new mode config for sandbox controller impls

oci/spec_opts_linux.go
to set realtime scheduling options.
in preparation for an upcoming PR in `nerdctl`.
=> add oci.WithCPURT

cmd/containerd-stress/density.go, cmd/ctr/commands/commands.go, cmd/ctr/commands/leases/leases.go, cmd/ctr/commands/run/run.go, cmd/ctr/commands/run/run_unix.go, cmd/ctr/commands/run/run_windows.go, cmd/gen-manpages/main.go, contrib/apparmor/template.go, images/mediatypes.go, integration/container_log_test.go, integration/main_test.go, integration/sandbox_run_rollback_test.go, metadata/gc.go, oci/spec_opts.go, pkg/cap/cap_linux.go, pkg/cri/opts/spec_windows.go, pkg/cri/sbserver/image_pull.go, pkg/cri/server/image_pull.go, services/server/config/config.go, services/server/config/config_test.go
Go 1.18 and up now provides a strings.Cut() which is better suited for splitting key/value pairs (and similar constructs), and performs better:
```go
func BenchmarkSplit(b *testing.B) {
b.ReportAllocs()
data := []string{"12hello=world", "12hello=", "12=hello", "12hello"}
for i := 0; i < b.N; i++ {
for _, s := range data {
_ = strings.SplitN(s, "=", 2)[0]
}
}
}
func BenchmarkCut(b *testing.B) {
b.ReportAllocs()
data := []string{"12hello=world", "12hello=", "12=hello", "12hello"}
for i := 0; i < b.N; i++ {
for _, s := range data {
_, _, _ = strings.Cut(s, "=")
}
}
}
```
BenchmarkSplit
BenchmarkSplit-10            8244206               128.0 ns/op           128 B/op          4 allocs/op
BenchmarkCut
BenchmarkCut-10             54411998                21.80 ns/op            0 B/op          0 …
=> replace strings.Split(N) for strings.Cut() or alternatives

docs/tracing.md, pkg/cri/sbserver/helpers.go, pkg/cri/sbserver/image_pull.go, pkg/cri/sbserver/image_remove.go, pkg/cri/sbserver/image_status.go, pkg/cri/sbserver/instrumented_service.go, pkg/cri/server/helpers.go, pkg/cri/server/image_pull.go, pkg/cri/server/image_remove.go, pkg/cri/server/image_status.go, pkg/cri/server/instrumented_service.go, pkg/unpack/unpacker.go, pull.go, remotes/docker/resolver.go, tracing/helpers.go, tracing/tracing.go
Follow up to the one of the comments in https://github.com/containerd/containerd/pull/7453#discussion_r1012470485
This PR wraps the otel Span object and implements related methods which is used during tracing instrumentation.
Also, adds a new SpanName method as discussed in https://github.com/containerd/containerd to add a common seaprator in span names /pull/7453#discussion_r1012469550 
=> Add a thin wrapper around otel Span object

cmd/ctr/commands/pprof/pprof.go
https://pkg.go.dev/runtime/pprof#pkg-notes
``` console
The debug parameter enables additional output.
Passing debug=0 writes the gzip-compressed protocol buffer described in https://github.com/google/pprof/tree/master/proto#overview.
Passing debug=1 writes the legacy text format with comments translating addresses to function names and line numbers, so that a programmer can read the profile without tools.
The predefined profiles may assign meaning to other debug values; for example, when printing the "goroutine" profile, 
debug=2 means to print the goroutine stacks in the same form that a Go program uses when dying due to an unrecovered panic.
```
I propose adding `--debug` parameter for friendly export of pprof data
=> Add `--debug` args to all subcommands of `ctr pprof`

gc/scheduler/metrics.go, gc/scheduler/scheduler.go
Fix todo
https://github.com/containerd/containerd/blob/6948d89e56752e4c8ea3cba8b1d192eba9290cef/gc/scheduler/scheduler.go#L258
> With these metrics, we can define an alert in Prometheus which is the consumer of metrics. For instance,
> 
> - alert if the GC keeps failing(N times).
> -  alert if the GC duration is above a bar(maybe 15s/1m) for N times.
> Just something we can do if we have such metrics.
> 
> I find this to-do in comments, and not in a true issue that needs it. So I have no accurate scenarios that would use these metrics. 
See https://github.com/containerd/containerd/pull/5263#issuecomment-1306714569
=> feature: add gc scheduler metrics collection count

pkg/cri/server/helpers.go, pkg/cri/store/container/status.go
In golang when copying a slice, if the slice is initialized with a desired length, then appending to it will cause the size to double.
Signed-off-by: bin liu <liubin0329@gmail.com>
=> Fix slice append error (`spec.Linux.Resources.HugepageLimits`)

releases/v1.6.10.toml, version/version.go
Release notes: https://gist.github.com/dcantah/0816c9cc55e9c8cdba1008e1d77205c9
=> [release/1.6] Prepare release notes for v1.6.10

oci/spec_opts.go, oci/spec_opts_linux_test.go
This change adds `withLinuxDevice` to take an option `followSymlinks`. An option
`WithLinuxDeviceFollowSymlinks` will call this unexported option to
follow a symlink, which will resolve a symlink before calling
`DeviceFromPath`. `WithLinuxDevice` has been changed to call
`withLinuxDevice` without following symlinks.
~~Previously DeviceFromPath used Lstat to get information about a device file, but Lstat will not follow symlinks; stat will. The use case could be using a tool like [`udev`](https://wiki.archlinux.org/title/udev) which will create symlinks to devices and wishing to attach one of these devices to a container.~~
~~It looks like `DeviceFromPath` is coming from runc, which does use Lstat instead of Stat but I didn't find any discussions as to why not resolve symlinks: …
=> add option to resolve symlinks in WithLinuxDevice

docs/cri/architecture.md
while reading the architecture of CRI plugin in docs noticed that the link is broken
Signed-off-by: Aman Sharma <amansh@vmware.com>
=> Fix broken link for CRI plugin in docs
