- cmd/gen-manpages/main.go
> Remove useless lines

- integration/client/container_linux_test.go
Signed-off-by: Ma Xinjian <maxj.fnst@fujitsu.com>
> Fix small typo

- .github/workflows/windows-periodic.yml
Allow these tests to be manually triggered as well. The name is updated to be consistent with other Github actions
> Update Windows periodic tests

- script/test/utils.sh
On Windows, we were only killing the keepalive process, and the containerd process would keep running.
keepalive and containerd have the same PGID, so we can use that information to kill both of them.
> integration: Cleanup containerd on test teardown

- pkg/cri/constants/constants.go
Merge annotations package into constant package
> scrub the stale TODO

- content/local/store.go
(cherry picked from commit edfd8d59937faeb36f40b8baeff488a6d693ef49)
Cherry pick of: #5560
> [release/1.4] cherry-pick: Change Wrapf of non-error to an actual error

- content/local/store.go
(cherry picked from commit edfd8d59937faeb36f40b8baeff488a6d693ef49)
Cherry pick of #5560
> [release/1.5] cherry-pick: Change Wrapf of non-error to an actual error

- integration/client/go.sum
Looks like i may have missed a spot.
> update integration/client go.sum

- .github/workflows/windows-periodic.yml
Signed-off-by: Adelina Tuvenie <atuvenie@cloudbasesolutions.com>
> Enable cri-integration in Windows Periodic Tests

- README.md
- docs/cri/config.md
- docs/cri/decryption.md
- docs/cri/proposal.md
- docs/hosts.md
- pkg/cri/config/config.go
- releases/README.md
- releases/v1.0.0.toml
- releases/v1.1.0.toml
- releases/v1.2.0.toml
- reports/2017-01-13.md
quick fix of a collection of doc links
> fixing some doc links

- cmd/ctr/commands/commands.go
- cmd/ctr/commands/run/run_unix.go
> allow multi gpu to be specified via ctr

- plugin/plugin_test.go
Signed-off-by: wanglei <wllenyj@linux.alibaba.com>
> Add unit test for plugin

- integration/container_restart_test.go
If a container failed to start due to a bad command, the container could not be recreated with a proper command in its stead. Adds a test that verifies this scenario.
Related: https://github.com/containerd/containerd/issues/5188
> test integration: Adds a test that restarts a failed container

- .github/workflows/ci.yml
- .github/workflows/nightly.yml
- .github/workflows/release.yml
- .travis.yml
- .zuul/playbooks/containerd-build/run.yaml
- Vagrantfile
- contrib/Dockerfile.test
Release note: Release notes: https://golang.org/doc/devel/release#go1.15
> [release/1.4] Update Go to 1.15.14

- .github/workflows/ci.yml
- .github/workflows/nightly.yml
- .github/workflows/release.yml
- .zuul/playbooks/containerd-build/integration-test.yaml
- .zuul/playbooks/containerd-build/run.yaml
- .zuul/playbooks/containerd-build/unit-test.yaml
- Vagrantfile
- contrib/Dockerfile.test
- integration/client/go.mod
- integration/client/go.sum
Cherry-pick https://github.com/containerd/containerd/pull/5722
> [release/1.5] Update Go to 1.16.6

- .mailmap
- releases/v1.4.7.toml
- version/version.go
See generated release notes https://gist.github.com/dmcgowan/c4f748b57fa62316a67e7f7441e2a385
> [release/1.4] prepare release notes for 1.4.7

- .mailmap
- releases/v1.5.3.toml
- version/version.go
See generated notes https://gist.github.com/dmcgowan/fac3c2b694ce376864b6886014c0c3d8
*Still pending a 1.4 release*
> [release/1.5] prepare release notes for 1.5.3

- releases/v1.4.8.toml
- version/version.go
See https://gist.github.com/dmcgowan/a3f609f53fd3c86fb2c72326ecb7f7b1
> [release/1.4] Prepare release notes for v1.4.8

- releases/v1.5.4.toml
- version/version.go
https://gist.github.com/dmcgowan/3b27a6507463f182efd76aa10b97b46a
> [release/1.5] Prepare release notes for v1.5.4

- diff/diff.go
- diff/walking/differ.go
https://github.com/containerd/containerd/issues/4263
Currently walking differ uses a hardcoded compressor (`compression.CompressStream(cw, compression.Gzip)`) for gzip layers and it doesn't allow the client to use customized one (e.g. different gzip compression level, gzip variants like estargz, ...). This commit solves this issue by adding an option to pass the compressor function to the differ.
This aims mainly to the BuildKit's use-case that consumes differ as a library rather than through gRPC API so this PR focuses on the change to `diff.Config` but doesn't make any changes to the gRPC API.
(When we need to support gRPC client as well in the future, we might need to introduce something like stream processor (as mentioned in #4263) but this is out of the scope of this PR.)
> Support custom compressor for walking differ

- remotes/docker/resolver.go
backport of https://github.com/containerd/containerd/pull/5504
fixes https://github.com/containerd/containerd/issues/5503
Allows redirects to be authorized if authorization is provided
for the redirected to host. The authorization will always go
to the redirect and never to the referrer.
> [release/1.4 backport] Update docker resolver to authorize redirects

- contrib/fuzz/archive_fuzzer.go
- contrib/fuzz/oss_fuzz_build.sh
- go.mod
- go.sum
- vendor/github.com/AdaLogics/go-fuzz-headers/LICENSE
- vendor/github.com/AdaLogics/go-fuzz-headers/README.md
- vendor/github.com/AdaLogics/go-fuzz-headers/consumer.go
- vendor/github.com/AdaLogics/go-fuzz-headers/go.mod
- vendor/modules.txt
Adds a fuzzer that applies a fuzzed tar archive on a directory.
Furthermore modifies the oss-fuzz build script to not move back the docker fuzzer.
> Fuzzing: Add archive fuzzer

- runtime/v2/shim.go
interface about shim build check
Signed-off-by: Yang Yang <yang8518296@163.com>
> interface about shim build check

- docs/hosts.md
> adding a little more clarity

- RELEASES.md
> add CRI support matrix to RELEASES.md

- services/server/config/config.go
- services/server/server.go
> grpc config add options tcp_client_ca_cert

- releases/v1.4.9.toml
- version/version.go
See generated release notes https://gist.github.com/dmcgowan/5dd62e57cb6322c810a5fe7ca5fb7965
> [release/1.4] Prepare release notes for v1.4.9

- runtime/v2/shim/util_unix.go
For the abstract socket address there's no need to chmod
the address's file, cause the file didn't exist actually.
Signed-off-by: Fupan Li <fupan.lfp@antgroup.com>
> runtime: fix the issue of create new socket with abstract address

- script/setup/config-selinux
- script/setup/install-cni
- script/setup/install-cni-windows
- script/setup/install-critools
- script/setup/install-protobuf
- script/setup/install-seccomp
- script/test/cri-integration.sh
- script/test/utils.sh
- test/build-test-images.sh
- test/build-utils.sh
- test/build.sh
- test/init-buildx.sh
- test/push.sh
- test/utils.sh
Noticed the special handling for Debian Jessie which (I hope) is no longer used in CI.
While at it, also fixing some quoting and linting issues that my IDE kept complaining about.
> scripts: linting fixes, and remove support for Debian Jessie (as it's EOL)

- contrib/fuzz/archive_fuzzer.go
- contrib/fuzz/content_fuzzer.go
- contrib/fuzz/oss_fuzz_build.sh
Adds two fuzzers for `images/archive.ImportIndex()` and `content.Walk()` respectively.
> Fuzzing: Add two fuzzers

- contrib/ansible/README.md
- contrib/ansible/vars/vars.yaml
releated #https://github.com/containerd/cri/issues/1624
> replace cri and point to new location

- contrib/fuzz/cap_fuzzer.go
- contrib/fuzz/content_fuzzer.go
- contrib/fuzz/cri_fuzzer.go
- contrib/fuzz/docker_fuzzer.go
- contrib/fuzz/oss_fuzz_build.sh
> Fuzzing: Add 4 fuzzers

- contrib/fuzz/containerd_import_fuzzer.go
- contrib/fuzz/oss_fuzz_build.sh
Adds a fuzzer that targets `containerd.Import`
> Fuzzing: Add fuzzer

- remotes/docker/httpreadseeker.go
Recently, this seems frequently reported as issues at #4908.
Currently, containerd doesn't restart pull when it encounters unexpected EOF of
blob strem withtout error codes.
There are cases where this lead to pull failure.
This commit tries to fix this issue.
> Fix pull fails on unexpected EOF

- docs/cri/crictl.md
Signed-off-by: kerthcet <kerthcet@gmail.com>
found some docs out of sync.
> fix document non-synchronous

- client.go
> using Hosts replace deprecated field

- runtime/v2/shim/util_unix.go
replace deprecated Dialer with ContextDialer
> replace deprecated Dialer with ContextDialer

- oci/spec_opts_linux.go
- oci/spec_opts_linux_test.go
Backport to 1.5: Fix dir support for devices #5845
> [release/1.5] Fix dir support for devices

- integration/client/restart_monitor_linux_test.go
- task.Kill() might fail in theory
- Giving a long timeout may help us to understand whether the failure
is a timing issue or not.
> integration: investigate TestRestartMonitor's failure

- script/setup/install-dev-tools
> pin protobuild version to tag

- pkg/cri/server/sandbox_remove.go
The Pod Sandbox can enter in a NotReady state if the task associated with it no longer exists (it died, or it was killed). In this state,
the Pod network namespace could still be open, which means we can't remove the sandbox, even if --force was used.
> sandbox: Allows the sandbox to be deleted in NotReady state

- pkg/cri/server/container_create_linux.go
fix #5053
Signed-off-by: scuzhanglei <greatzhanglei@gmail.com>
> cri: add devices for privileged container

- integration/containerd_image_test.go
complete integration test for pulling image with labels
ref issue: https://github.com/containerd/containerd/pull/5945
> complete integration test for pulling image with labels

- .github/workflows/ci.yml
- .github/workflows/nightly.yml
- .github/workflows/release.yml
- .zuul/playbooks/containerd-build/integration-test.yaml
- .zuul/playbooks/containerd-build/run.yaml
- .zuul/playbooks/containerd-build/unit-test.yaml
- Vagrantfile
- contrib/Dockerfile.test
> Update to Go 1.17.1

- integration/client/client_unix_test.go
> [release/1.5] CI: Switch to available latest images

- script/setup/install-runc
Release notes: https://github.com/containers/crun/releases
> CI: bump up crun to 1.0

- cmd/ctr/commands/run/run.go
- cmd/ctr/commands/run/run_unix.go
- cmd/ctr/commands/run/run_windows.go
- container_opts.go
- pkg/cri/server/container_create.go
- pkg/cri/server/helpers.go
- pkg/cri/server/helpers_test.go
- pkg/cri/server/sandbox_run.go
> Enable image config labels in ctr and CRI container creation

- content/helpers.go
- content/helpers_test.go
> [release/1.5] fix content copy to not ignore unexpected EOF

- integration/client/client_unix_test.go
- integration/client/container_linux_test.go
Same as #6015 but using containerd images
> Use github images for integration tests

- .github/workflows/ci.yml
To investigate #5748, this change collects the Vagrant VMs' IP addresses.
> gha: collect VMs' IP addresses

- integration/common.go
error strings should not be capitalized
> fix error string format

- integration/client/client_unix_test.go
- integration/client/container_linux_test.go
> [release/1.5] Use github images for integration tests

- images/archive/importer.go
A previous commit [1] made the Windows ``containerd/platforms.Default`` stricter by requiring the OS Version to have a similar OS Version as the node's OS Version.
However, tar images (from ``docker save``) do not have any OS Version information [2], causing the ``containerd/import.Import``'s ``images.FilterPlatforms`` to filter out the image entirely, which means that the ``images.SetChildrenLabels`` doesn't get to label
any children [3], which in turn will cause the Garbage Collector to remove content related to the image.
This sets a default platform for the imported image if it's a Windows image which doesn't have any OSVersion information.
[1] https://github.com/containerd/containerd/pull/5298
[2] https://github.com/containerd/containerd/blob/af1a0908d06b4f7db4a11bfc67ecc2f34baeb04b/v …
> ctr: Fixes Windows image import

- releases/v1.4.10.toml
- version/version.go
See https://gist.github.com/dmcgowan/089baf28a25ad5af17917223aa198766
> [release/1.4] prepare 1.4.10 release notes

- .mailmap
- releases/v1.5.6.toml
- version/version.go
See https://gist.github.com/dmcgowan/1d891f8aa4d267ca178c9fe423e7e53d
> [release/1.5] prepare 1.5.6 release notes

- cmd/ctr/commands/images/import.go
- import.go
Allow configuration of the platform when import image
> feat: support import image for specific platform

- contrib/ansible/tasks/k8s.yaml
cleanup k8s ansible yaml carry for https://github.com/jayonlau #5713
> cleanup k8s ansible yaml (carry for #5713) 

- integration/cri-api/pkg/apis/services.go
- integration/main_test.go
- integration/remote/remote_image.go
- integration/remote/remote_runtime.go
Extend cri remote client to accept extra grpc options.
> feat: enable integration cri remote client to call with grpc calloptions

- ADOPTERS.md
> Update ADOPTERS.md with additional uses

- integration/volume_copy_up_test.go
The image that the test is used for Windows has busybox included, which means we can use sleep.
At the moment, the test is failing with an ``Access denied`` error because the image used by the test is running as ``ContainerUser``: https://paste.ubuntu.com/p/6z9mnmnHQT/
See issue: https://github.com/containerd/containerd/issues/6183
> integration: Enables TestVolumeCopyUp for Windows

- images/converter/default.go
This commit allows hook callbacks during image conversion.
This enbles the caller additional modification for each blob descriptor.
This will be used by stargz-snapshotter image converter and by IPFS-related patches(#6175).
> converter: Allow hooks during image conversion

- pkg/cri/server/sandbox_run.go
Been looking into perf issues with running pods.. looks like one of the long poles is cni setup, this debug should help identify where more focus is needed.
DEBU[2021-11-01T09:31:42.207910789-05:00] begin cni setup                               podsandboxid=9b068ec35dfaffe5e92287db5d24731a30569d13ab88addfeb07361956d407e4
DEBU[2021-11-01T09:31:43.684393004-05:00] cni result: {...}  podsandboxid=9b068ec35dfaffe5e92287db5d24731a30569d13ab88addfeb07361956d407e4
> adds additional debug out to timebox cni setup

- script/setup/install-runc
Release notes: https://github.com/containers/crun/releases
> CI: bump up crun: 1.0 -> 1.3

- pkg/cri/server/helpers.go
add more description on `makeContainerName`
> cleanup: add more description on comment

- releases/v1.6.0-beta.toml
- version/version.go
See generated notes https://gist.github.com/dmcgowan/d9eba0f8f79c11c46734a109b6f7faef
> Prepare release notes for v1.6.0-beta.2

- container_restore_opts.go
Seems like this was the wrong error given that we are looking up image
label.
> Fix wrong error returned for image index lookup

- archive/tar_unix.go
> Close file if permission modification fails

- remotes/docker/resolver.go
Signed-off-by: Sebastian Hasler <sebastian.hasler@gmx.net>
(cherry picked from commit c0e2f4b5d2c28b22da552156dae5239935b6a343)
----
cherry-pick from #5275
> [release/1.4] Try next mirror in case of non-404 errors, too

- pkg/timeout/timeout.go
> feat: use rwmutex instead

- .mailmap
> [release/1.5] mailmap: Add Kevin Parsons

- releases/v1.4.12.toml
- version/version.go
See sample generated release notes at https://gist.github.com/dmcgowan/45121bcca37b8890fe84faca4cb70fef
> [release/1.4] Prepare release notes for v1.4.12

- releases/v1.5.8.toml
- version/version.go
See sample generated release notes at https://gist.github.com/dmcgowan/e2d2ecbad2cfa4e6c881450a3132de8e
> [release/1.5] Prepare release notes for v1.5.8

- client.go
- client_opts.go
Support customiz grpc calloptions on client side
> feat:support custom callopts on client side

- content/local/store.go
> content/local: Close the file if Seek fails

- README.md
Update wording; but really I'm trying to test something with CI
runs/automation.
> Update README.md repo->org

- ADOPTERS.md
Add VMware TKG & TCE to Containerd adopters
> Add VMware TKG & TCE to Containerd adopters

- integration/client/container_linux_test.go
- plugin/plugin.go
- runtime/v2/manager.go
- services/tasks/local.go
- services/tasks/local_freebsd.go
- services/tasks/local_unix.go
- services/tasks/local_windows.go
This needs more testing and should not be included in 1.6 release.
> Revert shim service plugin migration

- .github/workflows/ci.yml
- integration/client/client_ttrpc_test.go
- integration/client/import_test.go
- integration/client/restart_monitor_test.go
To help debug why Windows containers sometimes do not restart
> Update restart monitor test to output daemon logs on failure

- integration/restart_test.go
The CRI-plugin will setup watcher for each container after
StartContainer or RunPodSandbox. It will cleanup task(container/sandbox)
if received the exit event from watcher.
The original test design is to `Delete` sandbox container to get
NOT_READY state and expect to receive NotFound error. It depends on that
CRI-plugin cleanups container after `Delete` API. If not, the shim will
be cleanup and test code will receive `ttrpc: closed: unknown` or other
unknown error. It is flaky.
In this patch, the test will only send the kill signal and wait for the
exit event. When sandbox exits, the state will and must be NOT_READY.
```plain
// test fail log
=== RUN TestContainerdRestart
restart_test.go:92: Make sure no sandbox is running before test
restart_test.go:97: Start test sandboxes and …
```
> integration: deflake TestContainerdRestart

- snapshots/overlay/overlay.go
- snapshots/overlay/overlay_test.go
Signed-off-by: ningmingxiao <ning.mingxiao@zte.com.cn>
> fix when kernel version < 4.13rc1 by using index=off cause test error

- releases/v1.6.0-beta.toml
- version/version.go
See generated notes https://gist.github.com/dmcgowan/d9eba0f8f79c11c46734a109b6f7faef
> Prepare release notes for v1.6.0-beta.5

- ADOPTERS.md
This is a simple update of the adoption status for GKE
Signed-off-by: Sergey Kanzhelev <S.Kanzhelev@live.com>
> update the adoption status of containerd in GKE

- ADOPTERS.md
Signed-off-by: Mark Rossetti <marosset@microsoft.com>
Related to #6413 
Updating adoption status for AKS
> Updating adoption of containerd for AKS

- content/helpers.go
- content/local/writer.go
- mount/temp.go
- remotes/handlers.go
> Followup errors change

- contrib/apparmor/template.go
Makes the parser error message more helpful
> Update error message for apparmor parser

- integration/container_update_resources_test.go
- integration/volume_copy_up_test.go
- runtime/v2/runc/manager/manager_linux.go
Signed-off-by: ningmingxiao <ning.mingxiao@zte.com.cn>
> remove io/ioutil

- cmd/containerd-stress/density.go
Signed-off-by: ningmingxiao <ning.mingxiao@zte.com.cn>
> [containerd-stress] delete useless code

- tracing/plugin/otlp.go
- insecure.NewCredential was simply wrong. It has to use
otlptracegrpc.WithInsecure to disable TLS.
- context.WithTimeout is nice to have, in case the endpoint is not
correctly configured.
Otherwise, the plugin initialization blocks indefinitely.
- grpc.WithReturnConnectionError is nice to have.
Otherwise, otlptracegrpc.New returns "context deadline exceeded"
without underlying errors.
- TraceSamplingRatio should be 1.0 by default.
Otherwise, users need to configure both io.containerd.internal.v1.tracing
and io.containerd.tracing.processor.v1.otlp.
> tracing: fix OTLP tracer's initialization

- plugin/context.go
- plugin/plugin.go
- services/introspection/local.go
- services/introspection/service.go
> services/introspection: fix plugin caching to show grpc plugins

- .mailmap
- releases/v1.6.0-rc.toml
- version/version.go
See generated release notes https://gist.github.com/dmcgowan/fb2b125fd74d6c268fcabd7c89bb831a
> Prepare release notes for v1.6.0-rc.1

- integration/client/container_test.go
- runtime/v2/manager.go
ShimV2 has shim.Delete command to cleanup task's temporary resource,
like bundle folder. Since the shim server exits and no persistent store
is for task's exit code, the result of shim.Delete is always 137 exit
code, like the task has been killed.
And the result of shim.Delete can be used as task event only when the
shim server is killed somehow after container is running. Therefore,
dockerd, which watches task exit event to update status of container,
can report correct status.
Back to the issue #6429, the container is not running because the
entrypoint is not found. Based on this design, we should not send
137 exitcode event to subscriber.
This commit is aimed to remove shim instance first and then the
`cleanupAfterDeadShim` should not send event.
Similar Issue: #4769
Fix #6429 …
> fix: should not send 137 code event if cmd is notfound

- gc/gc.go
- metadata/content.go
- metadata/db.go
- metadata/gc.go
- metadata/snapshot.go
> docs: add doc-comments on GC-related methods

- .github/workflows/windows-periodic.yml
This change addresses the following issues:
* Fix fetching the public IP of the windows instance.
* Fix generation of repolist.toml.
* Resource cleanup is now run even if tests fail.
> Fix windows periodic workflow

- remotes/docker/authorizer.go
ref: https://github.com/containerd/nerdctl/issues/737
cc @AkihiroSuda
> Fix acr fetch token 400

- images/archive/importer.go
As reported, running import twice without using the compress import
option means that the content store will have existing layers during the
second import and the existing code hardcodes existing layer media type
to compressed. This fixes the issue by actually reading the header bytes
from the store and setting the media type appropriately.
Fixes: #6307
*If @dmcgowan or others know of another way to query a content blob's media type without a quick read, that might improve this solution. I couldn't easily find any way to do that.*
> Fix possibly incorrect media type default on import

- ADOPTERS.md
Signed-off-by: Andrey Smirnov <andrey.smirnov@talos-systems.com>
> docs: add Talos Linux to the list of adopters

- pkg/cri/server/rdt_linux.go
We were not properly ignoring errors from
gorestrl.rdt.ContainerClassFromAnnotations() causing the config option
to be ineffective, in practice.
> cri: fix handling of ignore_rdt_not_enabled_errors config option

- releases/v1.6.0-rc.toml
- version/version.go
> Prepare release notes for v1.6.0-rc.4

- go.mod
- go.sum
- integration/client/go.sum
- pkg/cri/server/testing/fake_cni_plugin.go
- vendor/github.com/containerd/go-cni/README.md
- vendor/github.com/containerd/go-cni/cni.go
- vendor/github.com/containerd/go-cni/namespace.go
- vendor/github.com/containerd/go-cni/opts.go
- vendor/modules.txt
> Update go-cni to v1.1.3

- integration/client/restart_monitor_test.go
With the release of hcsshim v0.9.2, this test should pass without
issues on Windows.
> [Windows][Integration] Enable TestRestartMonitor

- containerstore.go
- image_store.go
fix Implicit memory aliasing in for loop
> fix Implicit memory aliasing in for loop

- docs/getting-started.md
> Update Go version recommendation in getting started

- releases/v1.5.10.toml
- version/version.go
https://gist.github.com/dmcgowan/cf5b53785d36ec2fe9805b29dcd7f0f5
> [release/1.5] Prepare release notes for v1.5.10

- releases/v1.6.1.toml
- version/version.go
https://gist.github.com/dmcgowan/8840c0374fa0bf31bfa3965319a849e9
> [release/1.6] Prepare release notes for v1.6.1

- RELEASES.md
> Update status of 1.4 release

- contrib/fuzz/metadata_fuzzer.go
Makes the chosen opTypes more readable.
> Fuzzing: refactor metadata fuzzers

- cmd/containerd-shim/main_unix.go
- cmd/containerd-stress/exec_worker.go
- cmd/containerd-stress/main.go
- cmd/containerd-stress/worker.go
- cmd/containerd/command/main_unix.go
Just minor typo fixes.
Signed-off-by: Tomoya.Fujita <Tomoya.Fujita@sony.com>
> typo fixes under cmd.

- docs/man/containerd-config.toml.5.md
- services/server/config/config.go
Document supported log levels and formats
> document log level and format

- .github/workflows/ci.yml
- go.mod
- go.sum
- integration/client/go.sum
- pkg/cri/server/container_stats.go
- pkg/cri/server/container_stats_list.go
- pkg/cri/server/sandbox_stats.go
- pkg/cri/server/sandbox_stats_list.go
- vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_client.go
- vendor/github.com/prometheus/client_golang/prometheus/promhttp/instrument_server.go
- vendor/github.com/prometheus/client_golang/prometheus/promhttp/option.go
- vendor/modules.txt
Update to the recent release (includes a CVE fix) of the Go prom client library
> Update prometheus client vendor

- releases/v1.5.11.toml
- version/version.go
See generated release notes https://gist.github.com/dmcgowan/aaba4a45890f05a3a46ef8b6f499a89e
> Prepare release notes for v1.5.11

- snapshots/native/native.go
> native: fix deadlock from leaving transactions open

- .github/workflows/ci.yml
- releases/v1.6.2.toml
- runtime/v2/shim/shim.go
- version/version.go
See generated release notes https://gist.github.com/dmcgowan/aa9b1007a3f5865d49cfb35fa389d78b
> Prepare release notes for v1.6.2

- snapshots/native/native.go
cherry-pick of https://github.com/containerd/containerd/pull/6722
(cherry picked from commit fe426227d4ccb06fc5cbe7f11aa8eefc8d77768a)
> [release/1.6 backport] native: fix deadlock from leaving transactions open

- README.md
> Update README.md cncf landscape url

- BUILDING.md
- Makefile
- docs/cri/testing.md
Signed-off-by: Jordan Karaze <jordan.karaze@ibm.com>
> added make help for cri integration

- .github/workflows/ci.yml
- Vagrantfile
Cherry-pick https://github.com/containerd/containerd/pull/6747 (clean)
> [release/1.6] CI: add Rocky Linux 8

- contrib/gce/configure.sh
This script is used by various tests to install and configure
containerd. However, right now it's hardcoded to only support x86
and not other architectures like arm. This change will now check the
architecture of the machine the script is running on and will pull
the correct artifacts accordingly from the correct artifact store
(GCS vs Github).
Signed-off-by: Nobel Barakat <nobelbarakat@google.com>
> Adding multi-arch support for the configure.sh script

- services/server/server.go
A bbolt database has a freelist to track all pages that are available
for allocation. However writing the list takes some time and reading
the list sometimes panics.
This commit sets NoFreelistSync true for skipping the freelist entirely,
following what etcd does.
https://github.com/etcd-io/etcd/blob/v3.5.2/server/mvcc/backend/config_linux.go#L31
Fixes #4838.
> Disable writing freelist to make the file robust against data corruptions

- services/tasks/local.go
Fixes: https://github.com/containerd/containerd/issues/6787
> make consistent for checkpoint path

- pkg/netns/netns_linux.go
Cherry-pick https://github.com/containerd/containerd/pull/6806 (clean)
> [release/1.6] check for duplicate nspath possibilities

- pkg/netns/netns_linux.go
Cherry-pick https://github.com/containerd/containerd/pull/6806 (mostly clean - minor merge conflict on errors.Wrap vs fmt.Errorf)
(cherry picked from commit 147f0a7e02b16fe4d28e73c20919d9ad5af9617f)
> [release/1.5] check for duplicate nspath possibilities

- Makefile
> Build bin/gen-manpages instead of using "go run"

- image.go
- pkg/cri/server/image_pull.go
- pkg/cri/server/service.go
- pkg/kmutex/kmutex.go
- pkg/kmutex/kmutex_test.go
- pkg/kmutex/noop.go
- unpacker.go
Cherry-pick https://github.com/containerd/containerd/pull/6702 (clean)
> [release/1.6] CRI: improve image pulling performance

- pkg/cri/config/config.go
> Fix undefined error in use of errors package

- releases/v1.6.3.toml
- version/version.go
See generated release notes https://gist.github.com/dmcgowan/2e1e1923ed1417ac6c26b52b7ab50dbf
> Prepare release notes for v1.6.3

- pkg/unpack/unpacker.go
- pull.go
Move client unpacker to pkg/unpack
This new package will be used by both the client and a future service which does pull.
> Add unpack interface to be used by client

- pkg/cri/store/container/container.go
(cherry picked from commit 8710d4d014ef1b17c6f15bac4532f89429fc05a2)
:cherries: from #6842
> [release/1.6] cri: close fifos when container is deleted

- pkg/cri/store/container/container.go
(cherry picked from commit 8710d4d014ef1b17c6f15bac4532f89429fc05a2)
:cherries: from #6842
> [release/1.5] cri: close fifos when container is deleted

- .github/workflows/ci.yml
- .github/workflows/release.yml
Minor patch that will release ppc64le artifacts upon new tags.
> Create ppc64le release

- pkg/cri/opts/container.go
Signed-off-by: Kang.Zhang <Kang.zhang@intel.com>
> remove duplicate

- go.mod
- go.sum
- integration/client/go.sum
- vendor/github.com/containerd/go-cni/.golangci.yml
- vendor/github.com/containerd/go-cni/deprecated.go
- vendor/github.com/containerd/go-cni/opts.go
- vendor/github.com/containernetworking/cni/libcni/conf.go
- vendor/github.com/containernetworking/cni/pkg/version/plugin.go
- vendor/modules.txt
Signed-off-by: Michael Zappa <Michael.Zappa@stateless.net>
> Update go-cni to v1.1.5

- metadata/db.go
Fix comment
Signed-off-by: Taeho Nam <thn7440@gmail.com>
> Fix comment for metadata/db.go

- snapshots/snapshotter.go
Found a few minor fixes in comments when I was deep diving on snapshotters documentation.
Signed-off-by: Austin Vazquez <austin.vazquez.dev@gmail.com>
> docs: minor fixes in snapshots.Snapshotter comments

- contrib/ansible/README.md
Adjust the link to the k8s documentation link that has been modified
> Update k8 docurl in file

- runtime/v2/manager.go
- runtime/v2/shim_load.go
If containerd crashes while creating a container the shim process stays alive and is never
cleaned up. Details are discussed in issue containerd/containerd#6860. This fixes the code
to cleanup such shim processes on containerd restart.
Signed-off-by: Amit Barve <ambarve@microsoft.com>
> Cleanup leaked shim process

- README.md
- RELEASES.md
> containerd 1.6.4 k8s 1.24 readme announce

- integration/client/restart_monitor_test.go
These tests are launching containerd and pulling busybox there, while
other tests are using busybox from TestMain().
This commit shares busybox at least between TestRestartMonitor and
TestRestartMonitorWithOnFailurePolicy to reduce the chance of
throttling from ghcr.io.
> Share container images between TestRestartMonitor and TestRestartMonitorWithOnFailurePolicy

- Vagrantfile
addresses https://github.com/containerd/containerd/pull/6894#issuecomment-1119070630 
> move report dir option to end of line for vagrant cri tests

- pkg/cri/config/config.go
- pkg/cri/server/restart.go
- services/introspection/introspection.go
> fix some confusing typos

- cmd/ctr/commands/commands.go
> adjust format in comment

- docs/namespaces.md
- metadata/buckets.go
issue: https://github.com/containerd/containerd/issues/6944
> fix comments on metadata schema and update namespace doc

- archive/tar.go
Before:
```
$ nerdctl pull gcr.io/kubeflow-images-public/tensorflow-1.14.0-notebook-cpu:v0.7.0
FATA[0026] failed to extract layer sha256:f8a604834d388fd3d04c26e4ed832b36b617ea8a4e0b1665b9199bd10cfcb171: mount callback failed on /var/lib/containerd/tmpmounts/containerd-mount1818823128:
lchown /var/lib/containerd/tmpmounts/containerd-mount1818823128/usr/local/bin/docker-credential-gcr: invalid argument: unknown
```
After:
```
$ nerdctl pull gcr.io/kubeflow-images-public/tensorflow-1.14.0-notebook-cpu:v0.7.0
FATA[0027] failed to extract layer sha256:f8a604834d388fd3d04c26e4ed832b36b617ea8a4e0b1665b9199bd10cfcb171: mount callback failed on /var/lib/containerd/tmpmounts/containerd-mount3521205359:
failed to Lchown "/var/lib/containerd/tmpmounts/containerd-mount3521205359/usr/local/bin/docker-cr …
```
> archive: add human-readable hint to Lchown error

- go.mod
- go.sum
- integration/client/go.mod
- integration/client/go.sum
- vendor/github.com/Microsoft/hcsshim/internal/hcs/system.go
- vendor/github.com/Microsoft/hcsshim/internal/hns/hnspolicy.go
- vendor/github.com/Microsoft/hcsshim/internal/jobobject/iocp.go
- vendor/github.com/Microsoft/hcsshim/internal/jobobject/jobobject.go
- vendor/github.com/Microsoft/hcsshim/internal/jobobject/limits.go
- vendor/github.com/Microsoft/hcsshim/internal/queue/mq.go
- vendor/github.com/Microsoft/hcsshim/internal/winapi/iocp.go
- vendor/github.com/Microsoft/hcsshim/internal/winapi/jobobject.go
- vendor/github.com/Microsoft/hcsshim/internal/winapi/process.go
- vendor/github.com/Microsoft/hcsshim/internal/winapi/winapi.go
- vendor/github.com/Microsoft/hcsshim/internal/winapi/zsyscall_windows.go
- vendor/modules.txt
This tag brings in a new field to fix an HNS issue in ws2019 as well as
an optimization for collecting Windows stats (memory, cpu, iops).
https://github.com/microsoft/hcsshim/releases/tag/v0.9.3
> [release/1.6] go.mod: Bump hcsshim to 0.9.3

- contrib/fuzz/oss_fuzz_build.sh
Fixes build by using go 1.18 and using `compile_native_go_fuzzer` for the Go 1.18 fuzzer.
> Fix broken oss-fuzz build

- cmd/ctr/commands/sandboxes/sandboxes.go
"ctr s r" help suggests <pod-config.json> is taken as the first
parameter and the sandbox ID becomes next. However, only the latter
is read and used.
Add code that reads <pod-config.json> and passes it to Sanbox.
Signed-off-by: Mikko Ylinen <mikko.ylinen@intel.com>
> ctr sandbox: handle sandbox config

- archive/tar.go
Cherry-pick https://github.com/containerd/containerd/pull/6982 (Clean)
> [release/1.6] archive: add human-readable hint to Lchown error

- releases/v1.5.12.toml
- version/version.go
See generated release notes https://gist.github.com/dmcgowan/28335d8c4474f97fa124b6c6344d44c5
> Prepare release notes for v1.5.12

- go.mod
- go.sum
- integration/client/go.mod
- integration/client/go.sum
- vendor/google.golang.org/grpc/clientconn.go
- vendor/google.golang.org/grpc/encoding/encoding.go
- vendor/google.golang.org/grpc/internal/transport/controlbuf.go
- vendor/google.golang.org/grpc/internal/transport/http2_client.go
- vendor/google.golang.org/grpc/internal/transport/http2_server.go
- vendor/google.golang.org/grpc/picker_wrapper.go
- vendor/google.golang.org/grpc/server.go
- vendor/google.golang.org/grpc/stream.go
- vendor/google.golang.org/grpc/version.go
- vendor/modules.txt
> Bump grpc to v1.47.0

- go.mod
- go.sum
- integration/client/go.mod
- integration/client/go.sum
- vendor/github.com/containerd/cgroups/README.md
- vendor/github.com/containerd/cgroups/Vagrantfile
- vendor/github.com/containerd/cgroups/utils.go
- vendor/github.com/containerd/cgroups/v2/manager.go
- vendor/github.com/containerd/cgroups/v2/memory.go
- vendor/github.com/containerd/cgroups/v2/utils.go
- vendor/modules.txt
https://github.com/containerd/cgroups/compare/v1.0.3...v1.0.4
> go.mod: github.com/containerd/cgroups v1.0.4

- snapshots/overlay/overlay.go
> fix minor spelling mistake: lablel -> label

- script/setup/prepare_env_windows.ps1
> Bump Golang and MinGW versions in Windows setup script.

- cmd/ctr/commands/run/run_unix.go
(cherry picked from commit 92b7bc9edcb429ba2c242b7d70b73c6b188581ae)
cherry-pick: https://github.com/containerd/containerd/pull/6954
> [release/1.6] ctr: fix label args used in NewContainer

- services/server/server_test.go
> Make test path a constant

- cmd/ctr/commands/run/run_unix.go
(cherry picked from commit 92b7bc9edcb429ba2c242b7d70b73c6b188581ae)
cherry-pick: https://github.com/containerd/containerd/pull/6954
> [release/1.5] ctr: fix label args used in NewContainer

- docs/content-flow.md
> improve content-flow

- cmd/ctr/commands/commands.go
- cmd/ctr/commands/run/run_unix.go
Wrote this to help test https://github.com/samuelkarp/runj/commit/658737c7a87dc4f1a42b66423552b47739ed86eb; might be useful upstream for other testing as well.
> ctr: add --hostname flag to create, run

- oci/spec_opts.go
- oci/spec_opts_linux_test.go
From https://github.com/containerd/nerdctl/pull/1131/files#r899359758
> add WithAppendAdditionalGroups helper

- cmd/ctr/commands/run/run_windows.go
> Forward ctr snapshotter flags on Windows

- oci/spec_opts.go
- oci/spec_opts_linux_test.go
> add WithAdditionalGIDs test

- docs/snapshotters/devmapper.md
> fix: missing sudo for devmapper doc

- archive/tar.go
Fixes: https://github.com/containerd/containerd/issues/7093
> make xattr EPERM non-fatal in createTarFile

- oci/spec_opts.go
- oci/spec_opts_linux_test.go
> refactor: reduce duplicate code

- pkg/cri/server/instrumented_service.go
Use wrapper for ReopenContainerLog v1alpha proto.
Ref: #5619
> pkg/cri: use marshal wrapper for version convertor

- cmd/ctr/commands/content/content.go
Signed-off-by: zhanghe9702 <zhanghe9702@163.com>
fix #6846
> fix can't edit object by using ctr content edit command

- docs/snapshotters/devmapper.md
Updated some documentation for devmapper snapshotter plugin.
Made consistent use of "thin-pool", "Device Mapper" when referring to
the volume management framework, and "devmapper" when referring to the
snapshotter plugin itself.
Also added some additional resources / reorg.
> update some devmapper docs

- pkg/cri/cri.go
@mxpv @dims 
nit delta to test new e2e bucket test..
> adds a comment explaining how to disable experimental sbserver

- .github/workflows/ci.yml
- pkg/cri/store/container/status_test.go
- pkg/cri/store/sandbox/status_test.go
- script/setup/install-dev-tools
> Update and align golangci-lint version

- contrib/gce/cloud-init/node.yaml
works with infra change here: https://github.com/kubernetes/test-infra/pull/26872
> adds support for using env file for systemd boot

- cmd/ctr/commands/images/images.go
- pkg/cri/io/helpers.go
- remotes/docker/fetcher_test.go
Signed-off-by: guiyong.ou <guiyong.ou@daocloud.io>
code cleanup
> code cleanup

- test/e2e_node/gci-init.sh
For k8s e2e node tests, we want to be able to test both cgroupv1 and
cgroupv2 variants. Currently, the latest version of COS (M97) is running
as cgroupv2 and we would like the add the ability to switch to cgroupv1
for running tests on cgroupv1.
To do this, add a new flag, "CGROUP_MODE" which can be set as v1 or v2.
If the current cgroup configuration does not match the desired config,
the cgroup config will be set via `cgroup_helper` COS utility, and the
node will be rebooted.
> test: Add ability to switch between  cgroupv1 or cgroupv2 for node e2e

- pkg/ttrpcutil/client.go
> using ContextDialer instead

- containerd.service
> adds an env var commented out for sandboxed mode

- integration/build_local_containerd_helper_test.go
- pkg/cri/cri.go
- runtime/restart/monitor/monitor.go
- services.go
I need it elsewhere, but I think it'd be useful to have it as a helper, as we already use it in 3 different places across `containerd`.
> Make getServicesOpts a helper

- pkg/cri/sbserver/container_create_linux.go
- pkg/cri/server/container_create_linux.go
> replace with selinux label

- snapshots/testsuite/helpers.go
Signed-off-by: jianfei.zhang <jianfei.zhang@daocloud.io>
> test: error strings should not be capitalized

- script/setup/install-protobuf
Signed-off-by: fahed dorgaa <fahed.dorgaa@gmail.com>
> script/setup: fix protobuf for aarch64

- cmd/containerd/command/service_windows.go
Previously we were reassigning os.Stderr to the panic.log file we create
when getting asked to run Containerd as a Windows service. The panic.log
file was used as a means to easily collect panic stacks as Windows
services don't have regular standard IO, and the usual recommendation
is to either write to the event log or just to a file in the case of
running as a service.
One place where this panic.log flow was biting us was with shim logging,
which is forwarded from the shim and copied to os.Stderr directly which was
causing shim logs to get forwarded to this panic.log file instead of just
panics. We expose an additional `--log-file` flag if you ask to run a
windows service which is the main way you'd get Containerd logs, and with
this change all of the shim logging which would today end …
> Change os.Stderr reassign for Windows service

- .github/workflows/release.yml
Fixes: #7238 
Signed-off-by: Yash Singh [syash@vmware.com](mailto:syash@vmware.com)
> [release/1.5] gha: make release workflow work in forks 

- releases/v1.6.8.toml
- version/version.go
See generated notes https://gist.github.com/dmcgowan/10fe7eb6d07d2c30cfc474f79e560f00
Closes #7255
> [release/1.6] Prepare release notes for v1.6.8

- .github/workflows/ci.yml
Backport https://github.com/containerd/containerd/pull/7232
> [release 1.6 backport] Fix cleanup in critest

- RELEASES.md
> Clarify containerd 1.5.0+ for k8s 1.20,1.21

- oci/spec_opts_linux.go
- oci/spec_opts_nonlinux.go
- pkg/cri/sbserver/sandbox_portforward_linux.go
- pkg/cri/sbserver/sandbox_portforward_other.go
- pkg/cri/server/sandbox_portforward_linux.go
- pkg/cri/server/sandbox_portforward_other.go
- script/test/cri-integration.sh
Signed-off-by: Abirdcfly Fu <fp544037857@gmail.com>
> chore: remove duplicate word in comments

- cmd/containerd/command/main.go
- services/server/server.go
> delete redundent import alias and and type conversion

- integration/images/image_list.go
- pkg/cri/config/config_unix.go
- pkg/cri/config/config_windows.go
Signed-off-by: rongfu.leng <1275177125@qq.com>
issue: https://github.com/containerd/containerd/issues/7358
> feature: upgrade registry.k8s.io/pause version

- client.go
- container_opts.go
Signed-off-by: rongfu.leng <1275177125@qq.com>
ref: https://github.com/containerd/containerd/issues/6039
> feature: use client default namespace

- cmd/ctr/commands/images/pull.go
> chore: matching the casing of other flags for ctr's pull command

- cmd/ctr/commands/run/run_unix.go
For Kata Containers, starting a privileged container will fail
if passing all host devices to container due to the permission
issue, like the `privileged_without_host_devices` for CRI service,
add a `privileged-without-host-devices` to `ctr run` command will
disable passing all host devices to containers.
Signed-off-by: bin liu <liubin0329@gmail.com>
> ctr: add privileged-without-host-devices for run command

- go.mod
- go.sum
- integration/client/go.sum
- vendor/github.com/emicklei/go-restful/.gitignore
- vendor/github.com/emicklei/go-restful/.travis.yml
- vendor/github.com/emicklei/go-restful/CHANGES.md
- vendor/github.com/emicklei/go-restful/Makefile
- vendor/github.com/emicklei/go-restful/README.md
- vendor/github.com/emicklei/go-restful/container.go
- vendor/github.com/emicklei/go-restful/cors_filter.go
- vendor/github.com/emicklei/go-restful/curly.go
- vendor/github.com/emicklei/go-restful/custom_verb.go
- vendor/github.com/emicklei/go-restful/jsr311.go
- vendor/github.com/emicklei/go-restful/parameter.go
- vendor/github.com/emicklei/go-restful/path_processor.go
- vendor/github.com/emicklei/go-restful/request.go
- vendor/github.com/emicklei/go-restful/response.go
- vendor/github.com/emicklei/go-restful/route.go
- vendor/github.com/emicklei/go-restful/route_builder.go
- vendor/github.com/emicklei/go-restful/route_reader.go
- vendor/github.com/emicklei/go-restful/service_error.go
- vendor/github.com/emicklei/go-restful/web_service.go
- vendor/modules.txt
https://security.snyk.io/vuln/SNYK-GOLANG-GITHUBCOMEMICKLEIGORESTFUL-2435653
> Replace github.com/emicklei/go-restful package, versions <2.16.0

- go.mod
- go.sum
- integration/client/go.mod
- integration/client/go.sum
- vendor/github.com/opencontainers/selinux/go-selinux/doc.go
- vendor/github.com/opencontainers/selinux/go-selinux/label/label_linux.go
- vendor/github.com/opencontainers/selinux/go-selinux/label/label_stub.go
- vendor/github.com/opencontainers/selinux/go-selinux/rchcon.go
- vendor/github.com/opencontainers/selinux/go-selinux/rchcon_go115.go
- vendor/github.com/opencontainers/selinux/go-selinux/selinux_linux.go
- vendor/github.com/opencontainers/selinux/go-selinux/selinux_stub.go
- vendor/modules.txt
full diff: https://github.com/opencontainers/selinux/compare/v1.10.1...v1.10.2
> vendor: github.com/opencontainers/selinux v1.10.2

- integration/client/container_test.go
The test was essentially no-op since it didn't use a terminal.
Fixes #6249.
> TestTaskResize must use a terminal

- cmd/containerd/command/service_windows.go
Looks like this is the equivalent of the local implementation.
> cmd/containerd: use golang.org/x/sys Service.SetRecoveryActions()

- cmd/containerd/command/service_windows.go
golang.org/x/sys/windows now implements this, so we can use that instead of a local implementation.
> cmd/containerd: use golang.org/x/sys/windows.SetStdHandle()

- go.mod
- go.sum
- integration/client/go.mod
- integration/client/go.sum
- vendor/github.com/AdaLogics/go-fuzz-headers/consumer.go
- vendor/modules.txt
Get latest updates from go-fuzz-headers.
@kzys 
> bump go-fuzz-headers

- pkg/cri/io/logger.go
- pkg/cri/io/metrics.go
Signed-off-by: Sophie Liu <sophieliu@google.com>
(cherry picked from commit 3e4449862b273607d5b9abcc2192a104494234fd)
Signed-off-by: Sophie Liu <sophieliu@google.com>
> [release/1.6] Add logging volume metrics to Containerd CRI plugin

- pkg/cri/sbserver/helpers.go
- pkg/cri/sbserver/helpers_linux.go
- pkg/cri/sbserver/podsandbox/controller.go
- pkg/cri/sbserver/podsandbox/sandbox_delete.go
- pkg/cri/sbserver/sandbox_remove.go
This pr is Sansbox API work in https://github.com/containerd/containerd/issues/7312. Implemented `Controller.Delete`.
Signed-off-by: wanglei01 <wllenyj@linux.alibaba.com>
> CRI: implement Controller.Delete for SandboxAPI

- .mailmap
- releases/v1.5.14.toml
- version/version.go
Release notes: https://gist.github.com/samuelkarp/67d9195f33d1d8c94ca99f3cff07d452
> [release/1.5] Prepare release notes for 1.5.14

- .mailmap
- releases/v1.7.0-beta.toml
- version/version.go
See generated notes for https://gist.github.com/dmcgowan/18c05d167f0c0c3fe7d1d8839e6ec932
Since this is beta, some sections may be missing details and instructions which we want to add later. Including...
- List of experimental features
- How to enable sandbox API
- Transfer service description
- NRI description
- Config deprecations and migrations
> Add release notes for v1.7.0-beta.0

- .github/workflows/windows-hyperv-periodic-trigger.yml
- .github/workflows/windows-hyperv-periodic.yml
- script/test/utils.sh
> Add Workflow for running critest with Hyper-V Containers on Windows.

- contrib/fuzz/archive_fuzzer.go
Modifies the archive fuzzer to specifically require a file named either "oci-layout" or "manifest.json" in the tar.
> fuzzing: improve archive fuzzer

- runtime/v2/README.md
This PR updates runtime v2 README with sequence diagram to show flow of shim requests when running a container. I plan to add another one to depict flow with sandbox API, but it took me longer then I expected.
[Rendered version](https://github.com/containerd/containerd/blob/2da78246833b8222eae41ab63e54075411bfceb4/runtime/v2/README.md#flow)
> Add sequence diagram for shim runtime v2

- RELEASES.md
add information in backporting process related to cherry-picking main PR and related fixes
Signed-off-by: Akhil Mohan <makhil@vmware.com>
> docs: add additional info in backport process

- sys/reaper/reaper_unix.go
Signed-off-by: yaozhenxiu <946666800@qq.com>
fix comments
> fix comments

- content/content.go
Also moved the main interface (Store) to the top of the file and grouped some related interfaces together.
Fixes: #7305
Signed-off-by: Nikita Rybak <nikita.rybak@gmail.com>
> Extra documentation for content interfaces

- go.mod
- go.sum
- integration/client/go.mod
- integration/client/go.sum
- vendor/github.com/AdaLogics/go-fuzz-headers/consumer.go
- vendor/modules.txt
> fuzzing: bump go-fuzz-headers

- .github/workflows/release/Dockerfile
- Makefile
- releases/v1.7.0-beta.toml
> Release: add static binaries

- remotes/docker/resolver.go
- tracing/tracing.go
> Remove OpenTelementry imports from remotes/docker package

- snapshots/overlay/overlay.go
When GetInfo() return error, the transaction need to call Rollback().
Signed-off-by: guodong <guodong9211@gmail.com>
> tx rollback when GetInfo return error

- .github/workflows/ci.yml
- script/setup/install-dev-tools
no significant updates, just keeping up with latest version
full diff: https://github.com/cpuguy83/go-md2man/compare/v2.0.1...v2.0.2
> update github.com/cpuguy83/go-md2man/v2 to v2.0.2

- snapshots/overlay/overlay.go
Signed-off-by: guodong <guodong9211@gmail.com>
> overlayfs: remove duplicated tx rollback

- pkg/cri/sbserver/podsandbox/controller.go
- pkg/cri/sbserver/podsandbox/controller_test.go
- pkg/cri/sbserver/podsandbox/sandbox_stop.go
- pkg/cri/store/sandbox/status.go
This pr is Sansbox API work in https://github.com/containerd/containerd/issues/7312. Implemented `Controller.Status`
> Sandbox API: implement Controller.Status for SandboxAPI

- cmd/ctr/commands/content/fetch.go
- cmd/ctr/commands/images/push.go
I see there are many places to define the strings , We should make it as a const for multiplex.
> make status more readable and update easy.

- cmd/ctr/commands/images/images.go
Fix #5844.
The implementation is based on [`nerdctl image prune`](https://github.com/containerd/nerdctl/blob/272dc9c29fc1434839d3ec63194d7efa24d7c0ef/cmd/nerdctl/image_prune.go#L86).
It deletes unused images and logs deleted images and their digests.
Although `nerdctl` is recommended for daily usage, `ctr image prune` might still helpful for debugging to easily clean up leftover images.
Signed-off-by: Jin Dong <jindon@amazon.com>
> Add ctr image prune command

- pkg/transfer/streaming/stream.go
- services/streaming/service.go
- transfer.go
Allows clients to properly detect context cancellation
> Unwrap proto errors in streaming client

- cmd/ctr/commands/containers/restore.go
`ctr container restore` restores a container from a specified checkpoint. The newly restored container will have the same Spec as that of the parent container(container which was checkpointed ). If the parent container was started with a new terminal allocated (eg: `ctr run -t`) its Spec will have `{terminal : true}`, letting runc know to create a new set of file descriptors for a new pseudoterminal.
The IO for the new container that will be restored is specified via the [cio.NewCreator()](https://github.com/containerd/containerd/blob/main/cmd/ctr/commands/containers/restore.go#L90) function which takes in [cio.WithStdio](https://github.com/containerd/containerd/blob/main/cio/io.go#L106) as an argument, effectively setting the IO of the new container to be the default OS stdio. The issue …
> Refactor ctr restore to allow for tty allocation

- pkg/cri/sbserver/sandbox_run.go
> Fix context when waiting sandbox

- integration/container_event_test.go
Follow-up: https://github.com/containerd/containerd/pull/7073#discussion_r1044142416
> integration: increase timeout in container_event_test.go

- pkg/cri/streaming/portforward/httpstream.go
fix https://github.com/containerd/containerd/issues/7797
> fatal error: concurrent map iteration and map write

- pkg/cri/store/container/status.go
to fix https://github.com/containerd/containerd/issues/7806
> nil check to avoid panic on upgrade

- pkg/cri/sbserver/sandbox_status.go
> Minor fix when querying pod sandbox status

- pkg/cri/streaming/portforward/httpstream.go
> [release/1.6] concurrent map iteration and map write

- pkg/cri/store/container/status.go
Backport of #7809 to fix #7806
> [release/1.6] nil check to avoid panic on upgrade

- pkg/cri/opts/spec_linux.go
Skip automatic `if swapLimit == 0 { s.Linux.Resources.Memory.Swap = &limit }` when the swap controller is missing. (default on Ubuntu 20.04)
Fix #7828 (regression in PR #7783 "cri: make swapping disabled with memory limit")
> cri: fix `memory.memsw.limit_in_bytes: no such file or directory`

- log/logtest/log_hook.go
The logger could be called from multiple goroutines, but t.Log() is not designed for.
> Prevent a race condition in testHook

- pkg/cri/server/service.go
xref: https://go-review.googlesource.com/c/go/+/81778
> prevent Server reuse after a Shutdown

- snapshots/btrfs/btrfs.go
Signed-off-by: iyear <ljyngup@gmail.com>
For more information, please see: #7528
> Refactor metastore transaction

- pkg/cri/server/bandwidth/fake_shaper.go
- pkg/cri/server/bandwidth/unsupported.go
Reused  package 'errdefs'  for some error define
> reused package errdefs for error

- diff/walking/differ.go
- diff/windows/windows.go
- image.go
- images/archive/importer.go
- pkg/unpack/unpacker.go
- remotes/docker/schema1/converter.go
Use the defined constant `labels.LabelUncompressed` to replace the string `containerd.io/uncompressed`
> Use the const labels.LabelUncompressed

- snapshots/lcow/lcow.go
- snapshots/native/native.go
- snapshots/windows/windows.go
Signed-off-by: Junyu Liu <ljyngup@gmail.com>
close #7528 
close #7915 
It seems that only `native` is remaining.
> Refactor snapshotters metastore transaction

- cmd/ctr/commands/run/run.go
fix: https://github.com/containerd/containerd/issues/7923
> ctr/run: flags --detach and --rm cannot be specified together

- go.mod
- go.sum
- integration/client/go.sum
- vendor/github.com/pelletier/go-toml/README.md
- vendor/github.com/pelletier/go-toml/SECURITY.md
- vendor/github.com/pelletier/go-toml/marshal.go
- vendor/github.com/pelletier/go-toml/parser.go
- vendor/github.com/pelletier/go-toml/toml.go
- vendor/modules.txt
:cherries:-pick of https://github.com/containerd/containerd/pull/7932
> [release/1.6] mod: update github.com/pelletier/go-toml@v1.9.5

- runtime/v2/binary.go
- runtime/v2/shim/shim.go
- runtime/v2/shim/shim_unix.go
> shim: enable debug logging for delete

- README.md
- RELEASES.md
- ROADMAP.md
- SCOPE.md
Signed-off-by: Fish-pro <zechun.chen@daocloud.io>
> Fix syntax errors in the document

- .github/workflows/ci.yml
- .github/workflows/release.yml
- Commit 1: `CI: test release.yml on every PR`
- Commit 2: `CI: remove redundant archs from ci.yml`
> CI: test release.yml on every PR

- Vagrantfile
- contrib/Dockerfile.test
- script/setup/install-cni
backports:
- https://github.com/containerd/containerd/pull/7265
- https://github.com/containerd/containerd/pull/7484
- https://github.com/containerd/containerd/pull/7539
- fixes https://github.com/containerd/containerd/issues/7536
- https://github.com/containerd/containerd/pull/7691
- https://github.com/containerd/containerd/pull/7887
- https://github.com/containerd/containerd/pull/7908
> [release/1.6 backport] assorted updates to Vagrantfile

- runtime/v2/shim/shim_windows.go
Reused package errdefs for not supported error
> Reused package errdefs for not supported error

- integration/container_update_resources_test.go
The `TestUpdateContainerResources_MemoryLimit` test was failing when swap is disabled (just like in issue #7918). This modifies the expected swap values of the memory limit test, allowing the test to pass when swap is not enabled.
> Fix Memory Limit test

- RELEASES.md
> RELEASES.md: update release status

- .github/workflows/ci.yml
- .github/workflows/release.yml
> Clean CI yaml

- cmd/ctr/commands/pprof/pprof.go
- remotes/docker/auth/fetch.go
Signed-off-by: Fish-pro <zechun.chen@daocloud.io>
> chore: use http constants instead of string

- pkg/cri/sbserver/container_create.go
- pkg/cri/sbserver/container_execsync.go
- pkg/cri/sbserver/sandbox_run.go
- pkg/cri/server/container_create.go
- pkg/cri/server/container_execsync.go
- pkg/cri/server/sandbox_run.go
- runtime/v2/shim/util.go
- tracing/plugin/otlp.go
- tracing/plugin/otlp_test.go
Signed-off-by: Zechun Chen <zechun.chen@daocloud.io>
> chore: clean up repeated package import

- .github/workflows/ci.yml
- .github/workflows/codeql.yml
Cherry-pick:
- https://github.com/containerd/containerd/pull/8082
> [release/1.6] CI: skip some jobs when `repo != containerd/containerd`

- snapshots/devmapper/pool_device.go
Cherry-pick this bug fix [#8075 ](https://github.com/containerd/containerd/pull/8075) into 1.6 branch
(cherry picked from commit 6ae3e5df6a9dda573e57f06610474848431ba2cb)
> [release/1.6] Fix retry logic within devmapper device deactivation

- cmd/ctr/commands/run/run.go
cherry-pick: https://github.com/containerd/containerd/pull/7929
> [release/1.6] ctr/run: flags --detach and --rm cannot be specified together

- .github/workflows/release/Dockerfile
https://github.com/tonistiigi/xx/compare/v1.1.0...v1.2.1
> release: xx v1.2.1

- .github/workflows/build-test-images.yml
- .github/workflows/ci.yml
- .github/workflows/codeql.yml
- .github/workflows/images.yml
- .github/workflows/nightly.yml
- .github/workflows/release.yml
- Vagrantfile
- api/services/content/v1/content.pb.go
- contrib/Dockerfile.test
- script/setup/prepare_env_windows.ps1
"cherry-pick" the main PR #8109
> [release/1.6] Go 1.19.6

- .github/workflows/ci.yml
- .github/workflows/nightly.yml
- .github/workflows/release.yml
- .golangci.yml
- Vagrantfile
- api/services/content/v1/content.pb.go
- contrib/Dockerfile.test
"cherry-pick" the main PR #8109
> [release/1.5] Go 1.19.6

- sandbox/proxy/controller.go
Signed-off-by: Zechun Chen <zechun.chen@daocloud.io>
> Clean up repeated package import

- cmd/ctr/commands/sandboxes/sandboxes.go
- integration/remote/utils.go
- pkg/truncindex/truncindex.go
- services/introspection/service.go
Signed-off-by: Zechun Chen <zechun.chen@daocloud.io>
> Clean up error strings that start with uppercase

- cmd/ctr/commands/version/version.go
ctr version: add args check, prohibit incoming args
> ctr version: add args check

- services/sandbox/controller_service.go
options should be passed into create request
> sandbox: start sandbox with options

- cmd/ctr/commands/images/import.go
- cmd/ctr/commands/images/pull.go
- cmd/ctr/commands/images/push.go
- cmd/ctr/commands/resolver.go
- pkg/transfer/image/imagestore.go
- pkg/transfer/local/import.go
- pkg/transfer/local/pull.go
- pkg/transfer/local/push.go
- pkg/transfer/local/transfer.go
- pkg/transfer/proxy/transfer.go
- pkg/transfer/registry/registry.go
- pkg/transfer/transfer.go
- plugins/transfer/plugin.go
- remotes/resolver.go
Part of #7592   Add configuration options to local transfer service.
Signed-off-by: Tony Fang <nhfang@amazon.com>
> Add configuration options to local transfer service

- cmd/ctr/commands/images/import.go
- cmd/ctr/commands/images/pull.go
- pkg/transfer/local/import.go
- pkg/transfer/local/pull.go
- pkg/transfer/local/pull_test.go
- pkg/transfer/local/transfer.go
Part of #7592 and followup of #8062 
Add unit test to  func `getSupportedPlatform`
Fix code standard by adding a leading space to the comment block.
Signed-off-by: Tony Fang <nhfang@amazon.com>
> [transfer]Config options followup

- go.mod
- go.sum
- integration/client/go.sum
- vendor/modules.txt
> bump go-cni to v1.1.9

- RELEASES.md
So long 1.5, you were a good release!
> releases: mark 1.5 as EOL

- README.md
Resolves https://github.com/containerd/containerd/issues/8161
> Update CRI guide link

- RELEASES.md
To highlight some of the new features in v1.7 and set appropriate expectations for their use.
> Add experimental section to RELEASES.md

- cmd/ctr/commands/images/tag.go
- pkg/transfer/archive/importer.go
- pkg/transfer/image/imagestore.go
- pkg/transfer/local/tag.go
- pkg/transfer/local/transfer.go
Ref #7592 
Tag images using the `Transfer` service.
> [Feature] Transfer tag image

- go.mod
- go.sum
- integration/client/go.mod
- integration/client/go.sum
- vendor/github.com/containerd/ttrpc/server.go
- vendor/modules.txt
https://github.com/containerd/ttrpc/releases/tag/v1.2.1
> Update ttrpc to v1.2.1

- images/archive/exporter.go
- integration/client/export_test.go
:hammer_and_wrench: Fixes https://github.com/moby/buildkit/issues/1949.
It was possible to still export the docker-compatible manifest.json file, if a single platform image (as a standalone manifest) was exported, even if the WithSkipDockerManifest option was explicitly set.
To resolve this, we remove all references to skipDockerManifest to, adding it instead to the point-of-writing, simplifying the earlier logic and making it clear exactly when this manifest file should be written.
cc @tonistiigi @AkihiroSuda
> archive: consistently respect value of WithSkipDockerManifest

- cmd/containerd-stress/cri_worker.go
- cmd/containerd-stress/rlimit_freebsd.go
- cmd/containerd-stress/rlimit_unix.go
- cmd/containerd-stress/size.go
Pre-splice strings and determine whether it is a file and criCleanup check err
> Optimization containerd-stress

- pkg/cri/sbserver/service.go
- pkg/cri/sbserver/service_other.go
- pkg/cri/sbserver/service_windows.go
- pkg/cri/server/service.go
- plugins/sandbox/controller.go
1. https://github.com/containerd/containerd/pull/8255
2. https://github.com/containerd/containerd/pull/8257
3. https://github.com/containerd/containerd/pull/8277
> [release/1.7] Backport Sandbox/CRI fixes

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .devcontainer/setup.sh
- .devcontainer/welcome-message.txt
- BUILDING.md
Ref: https://cloud-native.slack.com/archives/CGEQHPYF4/p1677782367024069
A huge shoutout to @gabriel-samfira for helping me contribute this dev container. Thank you! 💟 
You can test these changes with Codespaces by simply clicking on the `Code` icon on top right side of this PR ☝️
> Adds dev container config and updates docs with Codespaces information

- cmd/ctr/commands/tasks/metrics.go
(cherry picked from commit 1be08b10f7084135718ae4937b024ac551e5de69)
cherry-pick: https://github.com/containerd/containerd/pull/8302
> [release/1.7] ctr/tasks: fix unmarshal the task metrics for cgroups v1

- images/archive/exporter.go
- integration/client/export_test.go
:cherries: Cherry-pick https://github.com/containerd/containerd/pull/8213
> [release/1.7] archive: consistently respect value of WithSkipDockerManifest

- oci/spec_opts.go
- backport of https://github.com/containerd/containerd/pull/8351
(cherry picked from commit cab056226fd8cece14d334ebb4f9084d0e3a7f47)
---
> The #8259 change added a new `WithReadonlyTempMount` that will force the mount to be readonly.
> 
> This change removes the `tryReadonlyMounts` and uses that function.
> 
> Relates to #8259 Related: [rumpl/moby#92](https://github.com/rumpl/moby/pull/92) and [moby/moby#45267](https://github.com/moby/moby/pull/45267)
> 
> Note: once this PR is good to go I will backport these to 1.6 and 1.7, this is needed for moby's migration to the containerd image store and moby uses 1.6.x
> [release/1.6 backport] oci: Use WithReadonlyTempMount when adding users/groups

- pkg/cri/sbserver/container_create_linux_test.go
- pkg/cri/server/container_create_linux_test.go
This pr is just a follow-up PR for https://github.com/containerd/containerd/pull/8136#pullrequestreview-1376865955
> Follow Up for #8136

- plugins/transfer/plugin.go
https://github.com/containerd/containerd/pull/8062 and https://github.com/containerd/containerd/pull/8193 seem to have broken image pulling using `ctr image pull --local=false`. This PR attempts to address that.
The first issue is that the new `OCIRegistry` transfer types are not registered due to the missing `import _ "github.com/containerd/containerd/pkg/transfer/registry"`. This results in the error
```
ctr: rpc error: code = Unimplemented desc = method Transfer not implemented for containerd.types.transfer.OCIRegistry to containerd.types.transfer.ImageStore
```
Once that's fixed, the next issue encountered on image pull is:
```
ctr: rpc error: code = Unknown desc = unable to initialize unpacker: snapshotter must be provided to unpack
```
This appears to be because the …
> Fix image pulling with Transfer service

- cmd/ctr/commands/commands.go
- cmd/ctr/commands/run/run.go
- cmd/ctr/commands/run/run_unix.go
- cmd/ctr/commands/run/run_windows.go
Add a flag to be able to run a container in a given sandbox.
> ctr: Add sandbox flag to ctr run

- pkg/cri/sbserver/sandbox_status.go
Currently if you're using the shim-mode sandbox server support, if your shim that's hosting the Sandbox API dies for any reason that wasn't intentional (segfault, oom etc.) PodSandboxStatus is kind of wedged. We can use the fact that if we didn't go through the usual k8s flow of Stop->Remove and we still have an entry in our sandbox store, us not having a shim mapping anymore means this was likely unintentional.
> CRI Sbserver: Make PodSandboxStatus friendlier to shim crashes

- gc/scheduler/scheduler_test.go
Avoid using sleep as a way to measure whether gc has occurred. Some systems may pause execution of the test and cause a failure if the gc thread has not yet run after the sleep in the main thread.
> Fix flaky gc sheduler test on Windows

- archive/tar_test.go
Enables tests to run on Darwin and only skip the tests which will not run.
> Update tar tests to run on Darwin

- pkg/cri/sbserver/container_remove.go
- pkg/cri/server/container_remove.go
If containerd does not see a container but criservice's container store does, then we should try to recover from this error state by removing the container from criservice's container store as well.
> Remove entry for container from container store on error

- pkg/cri/server/container_remove.go
Cherry pick commit [d9f3e38](https://github.com/containerd/containerd/commit/d9f3e387c6d8e7c89a68e6c5839813630e833764)
> [release/1.6] Remove entry for container from container store on error

- pkg/cri/sbserver/container_remove.go
- pkg/cri/server/container_remove.go
Cherry pick commit [d9f3e38](https://github.com/containerd/containerd/commit/d9f3e387c6d8e7c89a68e6c5839813630e833764)
> [release/1.7] Remove entry for container from container store on error 

- pkg/transfer/local/transfer.go
If initializing a transfer service without setting the max, a pull/push will deadlock on the first acquire.
> [transfer] avoid setting limiters when max is 0

- go.mod
- go.sum
- integration/client/go.mod
- integration/client/go.sum
- vendor/github.com/containerd/typeurl/v2/types.go
- vendor/modules.txt
fix: https://github.com/containerd/containerd/issues/8392
> bump typeurl to v2.1.1

- go.mod
- go.sum
- integration/client/go.mod
- integration/client/go.sum
- vendor/github.com/opencontainers/runtime-spec/specs-go/config.go
- vendor/github.com/opencontainers/runtime-spec/specs-go/version.go
- vendor/modules.txt
https://github.com/opencontainers/runtime-spec/compare/v1.1.0-rc.1...v1.1.0-rc.2
> go.mod: github.com/opencontainers/runtime-spec v1.1.0-rc.2

- go.mod
- go.sum
- integration/client/go.mod
- integration/client/go.sum
- vendor/github.com/containerd/ttrpc/.golangci.yml
- vendor/github.com/containerd/ttrpc/Makefile
- vendor/github.com/containerd/ttrpc/client.go
- vendor/github.com/containerd/ttrpc/server.go
- vendor/github.com/containerd/ttrpc/stream.go
- vendor/modules.txt
> Update ttrpc to v1.2.2

- go.mod
- go.sum
- integration/client/go.mod
- integration/client/go.sum
- vendor/github.com/containerd/ttrpc/.golangci.yml
- vendor/github.com/containerd/ttrpc/Makefile
- vendor/github.com/containerd/ttrpc/client.go
- vendor/github.com/containerd/ttrpc/server.go
- vendor/github.com/containerd/ttrpc/stream.go
- vendor/modules.txt
Backport of #8497 to fix #8390
> [release/1.7] Update ttrpc v1.2.2

- image.go
Many operations of image involve the acquisition of `diffIDs`, and will be repeated in one operation (eg. ctr umount).
> cache image diffIDs

- pkg/cri/opts/spec_linux.go
- pkg/cri/sbserver/container_create_linux.go
- pkg/cri/sbserver/container_create_linux_test.go
- pkg/cri/server/container_create_linux.go
- pkg/cri/server/container_create_linux_test.go
This is a cherry-pick of [the recent CDI enhancement](https://github.com/containerd/containerd/pull/8252) to  1.7
> [release/1.7] CDI: Use CRI Config.CDIDevices field for CDI injection

- go.mod
- go.sum
- integration/client/go.mod
- integration/client/go.sum
- vendor/github.com/containerd/continuity/fs/copy.go
- vendor/github.com/containerd/continuity/fs/copy_darwin.go
- vendor/github.com/containerd/continuity/fs/copy_nondarwin.go
- vendor/github.com/containerd/continuity/fs/copy_unix.go
- vendor/modules.txt
https://github.com/containerd/continuity/compare/72c70feb3081...v0.4.0
> go.mod: github.com/containerd/continuity v0.4.0

- cmd/containerd/command/main.go
- pkg/cri/cri.go
- pkg/cri/server/service.go
- plugin/context.go
- services/server/server.go
cherry-pick: https://github.com/containerd/containerd/pull/8576
(cherry picked from commit 4bfcac85fa47d0065f969249651c0ffb2c6b6810)
> [release/1.6] notify readiness when registered plugins are ready

- integration/image_pull_timeout_test.go
- pkg/cri/config/config.go
- pkg/cri/config/config_test.go
- pkg/cri/sbserver/images/image_pull.go
- pkg/cri/server/image_pull.go
issue: https://github.com/containerd/containerd/issues/8577
> Cleanup DEPRECATED TLS config

- RELEASES.md
PR is a follow-up of https://github.com/containerd/containerd/pull/8625#issuecomment-1572870746 and https://github.com/containerd/containerd/pull/8625#issuecomment-1572880620.
> docs: cherry-pick individual commits instead of merge commit

- RELEASES.md
- docs/cri/config.md
- pkg/cri/config/config.go
> [release/1.7] Remove cni conf_template deprecation

- tracing/plugin/otlp.go
This allows standard OTLP env vars to be used for configuring tracing exporters.
Note: This does mean that, as written now, if no env var is set the trace exporter will try to connect to the default OTLP address (`localhost:4318`).
I've left this alone for now, but we could detect the OTLP vars ourselves and if not set don't configure the exporter.
ref: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/exporter.md#configuration-options
> Setup otlp from env

- .github/workflows/ci.yml
Mismatch between GH actions CI settings and the config
> [release/1.6] Update lint timeout

- runtime/nsmap.go
This PR makes minor changes to the `NSMap`:
1. Change `Mutex` to `RWMutex`.
2. Move `mu.(R)Lock` down to right before accessing `objects`.
Please feel free to lmk if such change is necessary :) thanks!
> Use RWMutex in NSMap and reduce lock area

- integration/containerd_image_test.go
- pkg/cri/labels/labels.go
- pkg/cri/server/helpers.go
- pkg/cri/server/image_pull.go
- pkg/cri/server/image_pull_test.go
- pkg/cri/server/image_status.go
- pkg/cri/store/image/image.go
(cherry picked from commit fe4f8bd884ea1c2efae20291c131bd0b436659e3)
> [release/1.6] Pinned image support

- metadata/sandbox.go
1. Reduce one bucket.Bucket call.
2. Use `update` helper instead of `db.Update` as in other functions.
3. Move sandbox validate call (`s.validate`) as part of `s.write`. (currently it's called in `s.Update` but not in `s.Create`). 
For 2, actually I'm not sure if there is a preference/difference between `update` v.s. `db.Update` (and `view` v.s. `db.View`), as both seem used interchangeably in different metadata implementations. `update`/`view` checks if there is already a TX in context and reuse if there is.
https://github.com/containerd/containerd/blob/281c2b8f90105e74eec25df987df6b61533460da/metadata/bolt.go#L43
https://github.com/containerd/containerd/blob/281c2b8f90105e74eec25df987df6b61533460da/metadata/bolt.go#L53
> Minor changes to sandbox metadata

- mount/mount_freebsd.go
- mount/mount_linux.go
> Fix mount pkg typo

- cmd/containerd/command/oci-hook.go
- integration/failpoint/cmd/containerd-shim-runc-fp-v1/plugin_linux.go
- oci/spec.go
- runtime/v2/bundle.go
- runtime/v2/runc/manager/manager_linux.go
- runtime/v2/runc/util.go
Not sure I chose the best place for `ReadSpec` function, feel free to suggest a better one.
> Uncopypaste parsing of OCI Bundle spec file

- pkg/cri/streaming/portforward/httpstream.go
Try to fix the issue: https://github.com/kubernetes/kubernetes/issues/74551
> bugfix(port-forward): Correctly handle known errors

- container_opts.go
This PR combines the common part of `WithNewSnapshot` and `WithNewSnapshotView` to a helper which calls `s.View` or `s.Prepare` based on if `readonly`, similar to below funcs.
https://github.com/containerd/containerd/blob/beabd3d5d1bc610bcddbcb7d94f4d7f0b3f41fd2/container_opts_unix.go#L45
https://github.com/containerd/containerd/blob/beabd3d5d1bc610bcddbcb7d94f4d7f0b3f41fd2/metadata/snapshot.go#L299
https://github.com/containerd/containerd/blob/281c2b8f90105e74eec25df987df6b61533460da/rootfs/init.go#L44
> Dedup WithNewSnapshot and WithNewSnapshotView

- pkg/cri/streaming/portforward/httpstream.go
clean cherry-pick of https://github.com/containerd/containerd/pull/8418
---
These two errors can occur in the following scenarios:
ECONNRESET: the target process reset connection between CRI and itself.
see: #111825 for detail
EPIPE: the target process did not read the received data, causing the buffer in the kernel to be full, resulting in the occurrence of Zero Window, then closing the connection (FIN, RESET)
see: #74551 for detail
In both cases, we should RESET the httpStream.
> [release/1.7 backport] bugfix(port-forward): Correctly handle known errors

- pkg/cri/streaming/portforward/httpstream.go
clean cherry-pick of https://github.com/containerd/containerd/pull/8418
----
These two errors can occur in the following scenarios:
ECONNRESET: the target process reset connection between CRI and itself.
see: #111825 for detail
EPIPE: the target process did not read the received data, causing the buffer in the kernel to be full, resulting in the occurrence of Zero Window, then closing the connection (FIN, RESET)
see: #74551 for detail
In both cases, we should RESET the httpStream.
> [release/1.6 backport] bugfix(port-forward): Correctly handle known errors

- pkg/cri/sbserver/container_stats_list.go
- pkg/cri/sbserver/container_stats_list_test.go
fixes https://github.com/containerd/containerd/issues/8765
cri-tools fix pr:  https://github.com/kubernetes-sigs/cri-tools/pull/1202
> fix ci Linux Integration test fail

- snapshots/overlay/overlayutils/check.go
I am quite unfamiliar with the containerd codebase, but this seems to fix issue #8851 in my testing.
Fixes #8851
> Fix ro mount option being passed

- contrib/gce/configure.sh
- test/push.sh
Part of:
- https://github.com/kubernetes/test-infra/issues/29995
- https://github.com/kubernetes/test-infra/pull/30153
/cc @dims @mikebrow @akhilerm 
btw, I need someone to run /ok-to-test on this PR.
> Migrate to community bucket for node e2e tests

- pkg/cri/sbserver/sandbox_run.go
In the sbserver we should not use the GOOS, as windows hosts can run linux containers. On the sbserver we should use the platform param.
> cri/sbserver: Use platform instead of GOOS for userns detection

- pkg/cri/sbserver/container_stats_list.go
- pkg/cri/sbserver/container_stats_list_test.go
(cherry picked from commit 38f9bc3e0a8707c8191453d81ac0c5cf757a8f1f)
Fixes https://github.com/containerd/containerd/issues/8765
> [release/1.7] Port fix for Linux Integration test failure

- contrib/diffservice/service.go
- diff.go
- diff/proxy/differ.go
- services/server/server.go
1. 661e505c8239e97710bac220edf735f06027dbda
2. 32e3b76ee70fea42234b95ef01f78a13ac7c5c1d
Original PR https://github.com/containerd/containerd/pull/8399
> [release/1.7] Backport remote/proxy differ

- snapshots/overlay/overlay.go
Added the option to pass a metastore to the overlay snapshotter as an opt to allow for easier embedding in other overlay-based snapshotter projects like [stargz](https://github.com/containerd/stargz-snapshotter/pull/1340) 
#8959
> Add WithMetaStore to overlay snapshotter to allow bringing your own

- pkg/cri/sbserver/helpers.go
- pkg/cri/sbserver/metrics.go
- pkg/cri/server/helpers.go
- pkg/cri/server/metrics.go
issue https://github.com/containerd/containerd/issues/8892
> add metrics for discarding events

- pkg/cri/util/strings.go
Use sets to return sliced strings
> MergeStringSlices use sets

- releases/v1.7.4.toml
Full notes https://gist.github.com/dcantah/30e920b4373fe48980476906f56ddc8e
> [release/1.7] Prepare release notes for v1.7.4

- go.mod
- go.sum
- integration/client/go.mod
- integration/client/go.sum
- vendor/github.com/containerd/continuity/devices/mknod_freebsd.go
- vendor/github.com/containerd/continuity/driver/lchmod_unix.go
- vendor/github.com/containerd/continuity/fs/copy_unix.go
- vendor/github.com/containerd/continuity/fs/stat_atim.go
- vendor/modules.txt
https://github.com/containerd/continuity/compare/1e0d26eb2381...v0.4.2
> go.mod: github.com/containerd/continuity v0.4.2

- script/setup/install-cni
- script/setup/install-critools
- script/setup/install-runc
make repositories of dependencies like runc, crun, cni and critools configurable
> make repositories of install dependencies configurable

- snapshots/blockfile/blockfile.go
(cherry picked from commit 13ff185ba0dbdf0c104999507a8a9b0fe5479029)
The Go stdlib does not seem to have an efficient os.File.ReadFrom routine for other platforms like it does on Linux with copy_file_range. For Darwin at least we can use clonefile in its place, otherwise if we have a sparse file we'd have a fun surprise with the io.Copy approach..
We should see if there's other platforms that we can enhance here. I've forgotten what's the right route on Windows.
> [release/1.7] Blockfile: Enlighten blockfile copy on Darwin

- go.mod
- go.sum
- integration/client/go.mod
- integration/client/go.sum
- vendor/github.com/google/uuid/.travis.yml
- vendor/github.com/google/uuid/CHANGELOG.md
- vendor/github.com/google/uuid/CONTRIBUTING.md
- vendor/github.com/google/uuid/README.md
- vendor/github.com/google/uuid/node_js.go
- vendor/github.com/google/uuid/uuid.go
- vendor/modules.txt
Contains some performance improvements:
full diff: https://github.com/google/uuid/compare/v1.3.0...v1.3.1
> vendor: github.com/google/uuid v1.3.1

- cmd/containerd/command/main.go
- log/context.go
- log/context_test.go
backport of 
- https://github.com/containerd/containerd/pull/8894
- https://github.com/containerd/containerd/pull/9031
> [release/1.6 backport] log: cleanups and improvements to decouple more from logrus

- images/imagetest/content.go
- images/imagetest/size.go
- images/usage/calculator_test.go
Adds test for the usage calculation.
This also adds yet enough complicated testing packaging that can be extended for some more complicated test scenarios with higher level services such as transfer.
> Image usage test

- images/image.go
> images: Config: explicitly return nil-error

- pkg/cri/sbserver/service_linux.go
- pkg/cri/server/service_linux.go
> [release/1.7] cri: stop recommending disable_cgroup

- go.mod
- go.sum
- integration/client/go.mod
- integration/client/go.sum
- vendor/github.com/klauspost/compress/.goreleaser.yml
- vendor/github.com/klauspost/compress/README.md
- vendor/github.com/klauspost/compress/fse/bitwriter.go
- vendor/github.com/klauspost/compress/fse/compress.go
- vendor/github.com/klauspost/compress/huff0/bitwriter.go
- vendor/github.com/klauspost/compress/huff0/compress.go
- vendor/github.com/klauspost/compress/zstd/bitreader.go
- vendor/github.com/klauspost/compress/zstd/bitwriter.go
- vendor/github.com/klauspost/compress/zstd/blockenc.go
- vendor/github.com/klauspost/compress/zstd/dict.go
- vendor/github.com/klauspost/compress/zstd/encoder.go
- vendor/github.com/klauspost/compress/zstd/frameenc.go
- vendor/github.com/klauspost/compress/zstd/seqdec.go
- vendor/github.com/klauspost/compress/zstd/seqdec_amd64.s
- vendor/github.com/klauspost/compress/zstd/seqdec_generic.go
- vendor/github.com/klauspost/compress/zstd/snappy.go
- vendor/modules.txt
- Release: https://github.com/klauspost/compress/releases/tag/v1.17.0
- Diff: https://github.com/klauspost/compress/compare/v1.16.7...v1.17.0
> go.mod: Bump up github.com/klauspost/compress v1.16.7 to v1.17.0

- image.go
(cherry picked from commit a9ba33f8ff8b7ec8d4af736c68f5a73753f970ea)
> [release/1.6] Allow for images with artifacts to pull

- image.go
(cherry picked from commit a9ba33f8ff8b7ec8d4af736c68f5a73753f970ea)
> [release/1.7] Allow for images with artifacts to pull

- pkg/imageverifier/bindir/bindir.go
- pkg/imageverifier/bindir/bindir_test.go
- pkg/nri/config.go
- pkg/tomlext/toml_v2_util.go
- plugins/imageverifier/plugin.go
Fixes: https://github.com/containerd/containerd/issues/9176
> add Duration type to compatible toml v1 version

- mount/losetup_linux.go
LOOP_CONFIGURE is a new ioctl that is a lot faster than the LOOP_SET_FD+LOOP_SET_STATUS64 calls.
> Use LOOP_CONFIGURE when creating loop devices

- integration/containerd_image_test.go
- integration/images/image_list.go
- pull.go
(cherry picked from commit 7712375630ec5dc549d98a3d3d19a84348120b00)
PR in main https://github.com/containerd/containerd/pull/9215
> [release/1.7] Add a new image label if it is docker schema 1

- integration/common.go
- integration/containerd_image_test.go
- pull.go
(cherry picked from commit 7712375630ec5dc549d98a3d3d19a84348120b00)
PR in main https://github.com/containerd/containerd/pull/9215
> [release/1.6] Add a new image label if it is docker schema 1

- remotes/docker/config/hosts.go
- remotes/docker/config/hosts_test.go
The TLS fallback should only be used when the protocol is ambiguous due to provided TLS configurations and defaulting to http. Do not add TLS configurations when defaulting to http. When the port is 80 or will be defaulted to 80, there is no protocol ambiguity and TLS fallback should not be used.
Alternative to #9269
> Avoid TLS fallback when protocol is not ambiguous

- remotes/docker/authorizer.go
I ran into a problem that pulling image report error:
```
failed open: server message: invalid_token: authorization failed
```
And kubelet retry pulling the next time, it just successed.
After look into the detail I found that the image is a GPU image, 
and we limit concurrent pulling number to 4, the token fetch from 
registry will timeout in 10 minutes. when the very later layer get their
turn to download their blob, the token has become invalid.
Containerd has the policy to retry pulling when 401 returned from
the registry but if invalid authorization error returned, the cached
token didn't removed, and the next retry just don't work.
> fix bug that using invalid token to retry fetching layer

- mount/losetup_linux_test.go
After run `TestRwLoop`, there will leave a `/dev/loopX` not removed.
```go
file, err := setupLoop(backingFile, LoopParams{Autoclear: false})
```
`Autoclear` is false in `TestRwLoop`, so `/dev/loopX` will not be cleared automatically.
```
[root@containerddev containerd]# losetup
[root@containerddev containerd]# go test -v github.com/containerd/containerd/mount -test.root -run TestRwLoop
=== RUN   TestRwLoop
--- PASS: TestRwLoop (0.02s)
PASS
ok      github.com/containerd/containerd/mount  0.026s
[root@containerddev containerd]# losetup
NAME       SIZELIMIT OFFSET AUTOCLEAR RO BACK-FILE                        DIO LOG-SEC
/dev/loop0         0      0         0  0 /tmp/losetup1667762043 (deleted)   0     512
[root@containerddev containerd]# go test -v github.com/containerd/containerd/mount …
```
> test: remove /dev/loopX in TestRwLoop

- pkg/cri/config/config.go
- pkg/cri/config/config_test.go
- pkg/cri/cri.go
- pkg/deprecation/deprecation.go
Cherry-pick of https://github.com/containerd/containerd/pull/9319
> [release/1.7] cri: add deprecation warnings for mirrors, auths, and configs

- pkg/cri/server/service.go
- pkg/cri/server/service_test.go
fixes https://github.com/containerd/containerd/issues/8364
> add warning use inheritable Capabilities

- integration/client/container_linux_test.go
> integration: deflake TestIssue9103

- integration/client/container_linux_test.go
(cherry-picked from dac056f)
PR in main #9349
> [release/1.6] integration: deflake TestIssue9103

- integration/client/container_linux_test.go
(cherry-picked from https://github.com/containerd/containerd/commit/dac056fe7497157005c6b506b72bea731ccf7e9a)
PR in main https://github.com/containerd/containerd/pull/9349
> [release/1.7] integration: deflake TestIssue9103

- pkg/cri/config/config.go
- pkg/cri/config/config_test.go
- pkg/cri/cri.go
- pkg/deprecation/deprecation.go
Cherry-pick of https://github.com/containerd/containerd/pull/9319
> [release/1.6] cri: add deprecation warnings for mirrors, auths, and configs

- pkg/cri/cri.go
- pkg/cri/server/instrumented_service.go
- pkg/cri/server/service.go
- pkg/cri/server/service_test.go
- pkg/cri/server/testing/fake_warning_service.go
- pkg/deprecation/deprecation.go
- Backports https://github.com/containerd/containerd/pull/9336
- For https://github.com/containerd/containerd/issues/9312
> [release/1.6] Expose usage of cri-api v1alpha2

- unpacker.go
Adds debug message per layer unpacking and adds duration field to the existing image unpacking debug message.
(cherry picked from commit 01c442147fd084cc0e7e8b45074b940f5c6bbdba)
> [release/1.6] Enhance container image unpack client logs

- pkg/unpack/unpacker.go
Adds debug message per layer unpacking and adds duration field to the existing image unpacking debug message.
(cherry picked from commit 01c442147fd084cc0e7e8b45074b940f5c6bbdba)
> [release/1.7] Enhance container image unpack client logs

- integration/release_upgrade_linux_test.go
Add Exec-to-Existing-Running-Container case.
Part of #3757
> integration: add new binary upgrade case

- pkg/deprecation/deprecation.go
- services/snapshots/service.go
Cherry-pick of https://github.com/containerd/containerd/pull/9436
> [release/1.6] snapshots: emit deprecation warning for aufs

- integration/release_upgrade_linux_test.go
- pkg/cri/server/container_create.go
To make sure the compatibility when upgrade from 1.6-1.7, or 1.7-2.0,  we add more test cases to manipulate the containers in the pod of old version.
and we add a commit to fix the compatibility issue. that when get runtime info of sandbox, we may have to downgrade to get it from sandbox container.
> sandbox: add cri integration test case for upgrade

- go.mod
- go.sum
- vendor/github.com/containerd/continuity/fs/copy.go
- vendor/github.com/containerd/continuity/fs/dir.go
- vendor/modules.txt
continuity v0.4.3 release note: https://github.com/containerd/continuity/releases/tag/v0.4.3
> go.mod: github.com/containerd/continuity v0.4.3

- pkg/cri/config/config.go
- pkg/cri/config/config_test.go
- pkg/deprecation/deprecation.go
(cherry picked from commit 1fdefdd2242fcf704a11f1d6b5149e056ce98ed3)
Cherry-pick of https://github.com/containerd/containerd/pull/9481
> [release/1.6] Add warning for CRIU config usage

- docs/hosts.md
https://github.com/containerd/containerd/pull/4413 introduced the `ns` query string parameter to registry requests when interacting with a different host than that a given image's name. This is a nice feature, and combined with the `_default` host fallback can theoretically be used to create a registry-agnostic mirror.
This is currently a non-standard feature but I feel it's worth documenting anyway given it's been there since containerd 1.4. The relevant distribution spec change unfortunately doesn't have momentum: https://github.com/opencontainers/distribution-spec/pull/66. I'm not sure if it's worth linking/mentioning it's non-standard in the docs.
> Document `ns` query string added to mirror requests

- pkg/deprecation/deprecation.go
- runtime/restart/monitor/change.go
- runtime/restart/monitor/monitor.go
Cherry-pick of https://github.com/containerd/containerd/pull/9567
> [release/1.6] restart: containerd.io/restart.logpath warning

- integration/cri-api/pkg/apis/services.go
- integration/main_test.go
- integration/remote/remote_runtime.go
Fixes: https://github.com/containerd/containerd/issues/9475
> add get cgroupdriver from RuntimeConfig to integration

- script/setup/imgcrypt-version
- script/setup/install-imgcrypt
- full diff: https://github.com/containerd/imgcrypt/compare/v1.1.2...v1.1.9
> build(deps): bump github.com/containerd/imgcrypt to v1.1.9

- cmd/ctr/commands/content/content.go
- gc/scheduler/scheduler.go
- metadata/db.go
- pkg/cri/instrument/instrumented_service.go
- pkg/cri/io/logger.go
- pkg/cri/server/container_execsync.go
This PR moves some logs from debug level to trace level.
> Move certain debug  level logs to trace level logs

- mount/mount_unix.go
> mount: UnmountRecursive return nil if path doesn't exist

- runtime/v2/shim/shim.go
> runtime/v2: reduce shim plugin log

- releases/v2.0.0-beta.toml
- version/version.go
Update version for next beta release
> Prepare release notes for v2.0.0-beta.1

- docs/cri/config.md
This adds a missing documentation update to #9677
> Use tags.cncf.io CDI url in config.md

- pkg/cri/nri/nri_api_linux.go
1 Delete redundance code.
2 remove redundance package import "github.com/opencontainers/runtime-spec/specs-go"
> Code clean for nri_api.

- contrib/seccomp/seccomp_default.go
- core/mount/losetup_linux.go
- core/mount/mount_idmapped_linux_test.go
- pkg/cri/config/config_kernel_linux.go
- pkg/cri/config/config_kernel_linux_test.go
- pkg/kernelversion/kernel_linux.go
- pkg/kernelversion/kernel_linux_test.go
- plugins/snapshots/overlay/overlayutils/check.go
The package isn't really relevant to seccomp
> mv contrib/seccomp/kernelversion pkg/kernelversion

- integration/release_upgrade_linux_test.go
> integration: add test for recovering images

- README.md
- core/runtime/v2/README.md
- docs/PLUGINS.md
- docs/client-opts.md
- docs/getting-started.md
- docs/remote-snapshotter.md
fix package import path that was changed as part of v2 in sample code snippets.
> doc: fix package import in sample code

- cmd/containerd-shim-runc-v2/manager/manager_linux.go
/kind cleanup
/kind bug
Fix func (m manager) Info in containerd-shim-runc-v2.
> Fix func (m manager) Info in containerd-shim-runc-v2.

- docs/man/containerd-config.toml.5.md
/kind cleanup
Clean plugin indent in containerd-config.toml.5.md
> Clean plugin indent in containerd-config.toml.5.md

- .mailmap
- releases/v2.0.0-beta.toml
- version/version.go
See generated notes https://gist.github.com/dmcgowan/68f63519848bb0838623f6edf4e8ee28
> Prepare release notes for v2.0.0-beta.2

- integration/restart_linux_test.go
- internal/cri/server/podsandbox/recover.go
- internal/cri/server/podsandbox/recover_test.go
We can't set the status to Ready before task.Wait succeed.
https://github.com/containerd/containerd/pull/9463#discussion_r1452501526
> sandbox: fix podsandbox recover status issue

- cmd/ctr/commands/content/content.go
- gc/scheduler/scheduler.go
- metadata/db.go
- pkg/cri/instrument/instrumented_service.go
- pkg/cri/io/logger.go
- pkg/cri/server/container_execsync.go
Backport commit https://github.com/containerd/containerd/commit/f26196950705559c61ca7b246b1d1700638760b9 from containerd/main to release/1.7 branch
> [release/1.7] Move certain debug logs to trace logs

- cmd/ctr/commands/content/content.go
- gc/scheduler/scheduler.go
- metadata/db.go
- pkg/cri/io/logger.go
- pkg/cri/server/instrumented_service.go
Backport commit https://github.com/containerd/containerd/commit/f26196950705559c61ca7b246b1d1700638760b9 from to release/1.6 branch + fix merge conflicts
> [release/1.6] Move certain debug logs to trace logs

- integration/containerd_image_test.go
- pkg/cri/server/image_pull.go
Cherry-pick: #9732 
(cherry picked from commit 1eaf0c1f04ebc76ed6e1c6c86da3fb7decde6c60)
> [release/1.6] bug fix: make sure cri image is pinned when it is pulled outside cri

- contrib/gce/configure.sh
This reverts commit 23ebfd0305fdc9c07d4e80402887629186aba556.
setting LimitNOFILE did not work :(
> Revert "Fix for k8s nfs related tests"

- contrib/gce/configure.sh
Update gce configure.sh to use registry config_path instead of deprecated registry mirrors
> Update gce configure.sh to use registry config_path

- core/mount/losetup_linux.go
The struct is now part of sys, I forgot to remove it in the previous PR.
> Remove internal LoopConfig struct

- cmd/ctr/commands/client.go
- cmd/ctr/commands/deprecations/deprecations.go
> [release/1.7] ctr: print deprecation warnings on every invocation

- cmd/ctr/commands/client.go
- cmd/ctr/commands/deprecations/deprecations.go
> [release/1.6] ctr: print deprecation warnings on every invocation

- internal/cri/server/images/image_remove.go
PR adds new CRIImageService.RemoveImage() and moves out functionality from GRPCCRIImageService.RemoveImage()
> Add CRIImageService.RemoveImage()

- docs/cri/config.md
- integration/container_exec_test.go
- pkg/cri/config/config.go
- pkg/cri/config/config_test.go
- pkg/cri/config/config_unix.go
- pkg/cri/config/config_windows.go
- pkg/cri/server/container_execsync.go
- pkg/cri/server/container_execsync_test.go
- script/test/utils.sh
Cherry-pick: https://github.com/containerd/containerd/pull/7832/
Carry: #8828
> [release/1.6] pkg/cri: add timeout to drain exec io

- core/snapshots/snapshotter.go
In this PR i refactor snapshotter code to make it cleaner.
> refactor: clean switch statements and convert if to switch

- .github/actions/install-go/action.yml
- .github/workflows/ci.yml
- .github/workflows/release.yml
- Vagrantfile
- contrib/Dockerfile.test
- contrib/fuzz/oss_fuzz_build.sh
- script/setup/prepare_env_windows.ps1
See https://groups.google.com/g/golang-announce/c/5pwGVUPoMbg
> update to go 1.21.8, 1.22.1

- .github/workflows/ci.yml
- script/setup/upgrade_chocolaty_windows_2019.ps1
- script/setup/upgrade_mingw_windows_2019.ps1
cherry pick of #9777 
(cherry picked from commit 32bd8eff9effa0789ba933ede01a94c7a70512b3)
> [release/1.7] Move inline PS scripts into files

- .github/actions/install-go/action.yml
- .github/workflows/ci.yml
- .github/workflows/release.yml
- Vagrantfile
- contrib/Dockerfile.test
- contrib/fuzz/oss_fuzz_build.sh
- script/setup/prepare_env_windows.ps1
Cherry-pick (non-clean)
- https://github.com/containerd/containerd/pull/9932
> [release/1.7] update to go 1.21.8, 1.22.1

- .github/workflows/ci.yml
followup of #9890 
not a clean cherrypick of https://github.com/containerd/containerd/pull/9946
> [release/1.6] use a composite action to install Go

- plugins/types.go
/kind cleanup
Clean typos in plugins.
> Clean typos in plugins.

- .mailmap
- contrib/v2-migrate.sh
- releases/v2.0.0-rc.toml
- version/version.go
Tracking https://github.com/containerd/containerd/milestone/35
> Prepare release notes for v2.0.0-rc.0

- internal/cri/opts/spec_linux_opts.go
- internal/cri/server/container_create.go
/kind cleanup
Clean cri options and useless parms
> Clean cri options and useless parms

- core/transfer/archive/importer.go
Currently, `ctr image import` as well as the transfer service import with `NewImageImportStream` does not support archives that are compressed (gzip, zstd).
I've tried passing a decompressed stream like so:
```go
decompressor, err := compression.DecompressStream(f)
return nil, fmt.Errorf("failed to create stream decompressor: %w", err)
}
defer decompressor.Close()
src := tarchive.NewImageImportStream(decompressor, "")
```
However, I believe there is a bug in the proxy transfer service because it fails during `untarBlob` with `failed to read expected number of bytes: unexpected EOF`. Patching containerd, I found it errors in this line with the following parameters: `copied 34860544, size 34877440, ws.Offset 0, size-ws.Offset 34877440`: …
> Automatically decompress archives for transfer service import

- internal/cri/server/images/image_pull.go
The pause image that have been loaded before older versions already have the `io.cri-containerd.image=managed` label, and we can't add `io.cri-containerd.pinned=pinned` to its labels if we only judge the **managed label**
> cri: ensure the pause image loaded in older versions is pinned 

- docs/cri/registry.md
fixed a small typo in the docs
> docs: fix typo

- pkg/transfer/archive/importer.go
Backports the following PR to release/1.7:
- https://github.com/containerd/containerd/pull/9864
Unblocks: https://github.com/k3s-io/k3s/pull/9319
> [release/1.7] Automatically decompress archives for transfer service import

- remotes/docker/authorizer.go
cherry-pick #9274 
cc @yyb196 @dmcgowan @ktock
> [release/1.6] fix bug that using invalid token to retry fetching layer

- remotes/docker/authorizer.go
cherry-pick #9274 
cc @yyb196 @dmcgowan @ktock
> [release/1.7] fix bug that using invalid token to retry fetching layer

- go.mod
- go.sum
- vendor/github.com/containerd/nri/pkg/adaptation/adaptation.go
- vendor/modules.txt
Fixes https://github.com/containerd/containerd/issues/10085
> mod: bump github.com/containerd/nri@v0.6.1

- go.mod
- go.sum
- integration/client/go.sum
- vendor/github.com/containerd/nri/pkg/adaptation/adaptation.go
- vendor/modules.txt
Fixes https://github.com/containerd/containerd/issues/10085
(cherry picked from commit a153b2cd3223819f07d022ba97421738615c6277)
> [release/1.7] mod: bump github.com/containerd/nri@v0.6.1

- internal/cri/server/sandbox_portforward_windows.go
Account for ipv6 localhost in windows port forwarding
> Account for ipv6 localhost in windows port forwarding

- cmd/ctr/commands/content/content.go
- cmd/ctr/commands/images/import.go
- cmd/ctr/commands/images/mount.go
- cmd/ctr/commands/images/pull.go
- cmd/ctr/commands/images/tag.go
- cmd/ctr/commands/images/unmount.go
- cmd/ctr/commands/images/usage.go
- cmd/ctr/commands/run/run.go
- cmd/ctr/commands/run/run_unix.go
use errors.New to replace fmt.Errorf with no parameters will much better
> chore: use errors.New to replace fmt.Errorf with no parameters will much better

- cmd/ctr/commands/resolver.go
- remotes/docker/config/hosts.go
- remotes/docker/config/hosts_test.go
- remotes/docker/pusher_test.go
- remotes/docker/resolver.go
- remotes/docker/resolver_test.go
> [release/1.7] Update HTTP fallback to better account for TLS timeout and previous attempts

- cmd/ctr/commands/resolver.go
- remotes/docker/config/hosts.go
- remotes/docker/config/hosts_test.go
- remotes/docker/pusher_test.go
- remotes/docker/resolver.go
- remotes/docker/resolver_test.go
> [release/1.6] Update HTTP fallback to better account for TLS timeout and previous attempts

- Makefile
Makefile: update default PACKAGE to v2
> Makefile: update default PACKAGE to v2 

- internal/cri/server/service.go
> cri: introspectRuntimeFeatures: fix nil panic

- ADOPTERS.md
The italicization of Actuated was broken. This commit fixes it by adding a missing underscore.
> ADOPTERS.md: Fix Actuated italics

- core/remotes/docker/config/hosts.go
fix: https://github.com/containerd/containerd/issues/10144
> optimize error logs by providing absolute file paths

- .github/workflows/api-release.yml
Creates a new release as "containerd API x.y.z"
> Add API release action

- api/releases/v1.8.0-rc.toml
The `api/*` tags can be prepared using the release tool with https://github.com/containerd/release-tool/pull/51. If we agree on this approach, we can create a Github action to handle api tags.
----
Welcome to the api/v1.8.0-rc.0 release of containerd!  
The first dedicated release for the containerd API. This release continues the 1.x
line of API compatibility with the 9th minor release of the 1.x API.
* Add api Go module and move all protos under api ([#10151](https://github.com/containerd/containerd/pull/10151))
* Add PluginInfo to introspection API ([#9442](https://github.com/containerd/containerd/pull/9442))
* Expose usage of deprecated features ([#9258](https://github.com/containerd/containerd/pull/9258))
* Add image delete target …
> Prepare release notes for api/v1.8.0-rc.0

- core/metadata/content.go
> core/metadata: failfast on content.Commit

- integration/client/container_linux_test.go
- pkg/shim/shim.go
- pkg/shim/util_unix.go
- pkg/shim/util_windows.go
> fix: delete sockets on shim exit

- go.mod
- go.sum
- vendor/github.com/containerd/ttrpc/client.go
- vendor/modules.txt
Update ttrpc to 1.2.4  https://github.com/containerd/ttrpc/releases/tag/v1.2.4 
Full list of changes: https://github.com/containerd/ttrpc/compare/v1.2.3...v1.2.4
> Update ttrpc tag to 1.2.4

- core/runtime/v2/task_manager.go
Fixes https://github.com/containerd/containerd/issues/10249
cc: @mathias-ioki
> Provide runtime options in plugin info

- .github/actions/install-go/action.yml
- .github/workflows/ci.yml
- .github/workflows/release.yml
- Vagrantfile
- contrib/Dockerfile.test
- contrib/fuzz/oss_fuzz_build.sh
- script/setup/prepare_env_windows.ps1
Includes fix for a symlink race on remove
Backport of #10296
> [release/1.7] Update Go version to 1.21.11

- .github/actions/install-go/action.yml
- .github/workflows/ci.yml
- .github/workflows/release.yml
- Vagrantfile
- contrib/Dockerfile.test
- script/setup/prepare_env_windows.ps1
Includes fix for a symlink race on remove
Backport of #10296
> [release/1.6] Update Go version to 1.21.11

- integration/client/daemon.go
Avoid running tests when a plugin fails to load and return the init error from the plugin. This prevents the test failing later with an unhelpful error and attempting to find the actual error in the daemon logs.
In some Windows integration tests, the daemon logs are not showing making this more difficult. That should be fixed as well but this will help root cause faster.
> Fail integration test early when a plugin load fails

- go.mod
- go.sum
- vendor/github.com/Microsoft/hcsshim/hcn/hcn.go
- vendor/github.com/Microsoft/hcsshim/hcn/hcnerrors.go
- vendor/github.com/Microsoft/hcsshim/hcn/hcnglobals.go
- vendor/github.com/Microsoft/hcsshim/hcn/hcnloadbalancer.go
- vendor/github.com/Microsoft/hcsshim/hcn/hcnpolicy.go
- vendor/github.com/Microsoft/hcsshim/hcn/hcnsupport.go
- vendor/github.com/Microsoft/hcsshim/internal/hns/hnspolicy.go
- vendor/modules.txt
Update hcsshim tag to https://github.com/microsoft/hcsshim/releases/tag/v0.12.4
Full list of changes: https://github.com/microsoft/hcsshim/compare/v0.12.3...v0.12.4
> Update hcsshim tag to 0.12.4

- core/remotes/docker/resolver.go
Fixes an issue with race detector complaining about concurrent access such as with Dispatch on push.
> Adds a mutex to protect fallback host

- integration/container_volume_linux_test.go
- integration/images/volume-ownership/Dockerfile
- integration/utils_linux_test.go
- mount/mount_test.go
- mount/temp.go
- pkg/cri/opts/container.go
backports:
* https://github.com/containerd/containerd/pull/10274
* https://github.com/containerd/containerd/pull/9555
* part of https://github.com/containerd/containerd/pull/9262 (about how to setup individual containerd)
> [release/1.6] Remove overlayfs volatile option on temp mounts 

- go.mod
- go.sum
- vendor/github.com/containerd/ttrpc/README.md
- vendor/github.com/containerd/ttrpc/client.go
- vendor/github.com/containerd/ttrpc/server.go
- vendor/modules.txt
full diff: https://github.com/containerd/ttrpc/compare/v1.2.4...v1.2.5
> vendor: github.com/containerd/ttrpc v1.2.5

- go.mod
- go.sum
- integration/client/go.mod
- vendor/github.com/containerd/containerd/api/LICENSE
- vendor/modules.txt
Update with latest tagged version to prepare for v1.7.19 release in the main module
> [release/1.7] Update api version to v1.7.19

- errdefs/errdefs_deprecated.go
Cherry-pick (clean):
- https://github.com/containerd/containerd/pull/10424
> [release/1.6] errdefs: denote deprecation as a godoc comment

- internal/cri/server/sandbox_stats_list.go
Please see https://github.com/containerd/containerd/pull/10423
We should have merged in `main` first! Apologies.
> Fix for [cri] ttrpc: closed during ListPodSandboxStats

- cmd/containerd-shim-runc-v2/process/io_test.go
This PR ignores a new pidfd file descriptor that is introduced in gotip (future 1.23) and should not be considered when detecting fd leaks.
Fixes #10345
> Fix TestNewBinaryIOCleanup failing with gotip

- core/metadata/buckets.go
- core/metadata/db.go
- core/metadata/db_test.go
- core/metadata/migrations.go
- integration/container_volume_linux_test.go
- integration/issue10467_linux_test.go
- integration/release_upgrade_linux_test.go
- integration/release_upgrade_utils_linux_test.go
> core/metadata: migrate sandboxes bucket into v1

- docs/PLUGINS.md
- docs/cri/config.md
- docs/cri/registry.md
- docs/hosts.md
> docs: update for containerd v2

- cmd/containerd-shim-runc-v2/process/io_test.go
The main reason is to improve the comment about pidfd in Go 1.23+.
While at it:
- avoid slice manipulation as we only need count;
- avoid repeating "/proc/self/fd".
Updates: #10345.
> TestNewBinaryIOCleanup: fix a comment, minor rewrite

- pkg/cri/server/container_stats_list_linux.go
- pkg/cri/server/container_stats_list_linux_test.go
cherry-pick of https://github.com/containerd/containerd/commit/f6677a4ec53f95f22529f7225f0de741b9201df1
> [release/1.6] Cumulative stats can't decrease

- runtime/v2/runc/task/service.go
Backports: https://github.com/containerd/containerd/pull/10651
> [1.6 backport] Fix bug where init exits were being dropped 

- runtime/v2/runc/task/service.go
Backports: https://github.com/containerd/containerd/pull/10651
> [1.7 backport] Fix bug where init exits were being dropped

- script/test/utils.sh
xref https://github.com/containerd/containerd/pull/10579/files#r1769280024
> Enable the selinux on cri test

- internal/cri/server/sandbox_status.go
fix: https://github.com/containerd/containerd/issues/10728
> Add timestamp to PodSandboxStatusResponse for kubernetes Evented PLEG

- pkg/cri/server/sandbox_stop.go
Cherry pick of https://github.com/containerd/containerd/pull/10744 for release 1.7.22
> [release/1.7] Add check for CNI plugins before tearing down pod network

- pkg/cri/server/sandbox_stop.go
Cherry pick of #10744 for release 1.6.36
> [release/1.6] Add check for CNI plugins before tearing down pod network

- pkg/process/io_test.go
* Backports https://github.com/containerd/containerd/pull/10597 to release/1.7 branch.
The main reason is to improve the comment about pidfd in Go 1.23+.
While at it:
- avoid slice manipulation as we only need count;
- avoid repeating "/proc/self/fd".
Updates: #10345.
(cherry picked from commit 94c163209db612dbf1394e73060031953b34ac88)
> [release/1.7 backport] TestNewBinaryIOCleanup: fix a comment, minor rewrite

- .github/workflows/ci.yml
- Vagrantfile
Revert c25183ff1998f11a2f5ee49bf1d2b28781c7ee4c 1bfdccee09c6e95f6e993ae6472405b2243de33a
Fix #10816
> CI: fix vagrant

- internal/cri/server/sandbox_run.go
Rebased main branch https://github.com/containerd/containerd/pull/10800
> Handle teardown failure to avoid blocking cleanup

- pkg/sys/unshare_linux.go
- pkg/sys/unshare_linux_test.go
> Allow `setgroups` in user namespaces

- docs/containerd-2.0.md
> containerd 2.0 guide: add image verifier plugins

- docs/NRI.md
Resolves https://github.com/containerd/containerd/pull/10769#pullrequestreview-2373458715
> Update NRI documentation for containerd 2.0

- go.mod
- go.sum
- vendor/github.com/containerd/nri/pkg/runtime-tools/generate/generate.go
- vendor/modules.txt
Fixes https://github.com/containerd/nri/issues/117
> deps: bump github.com/containerd/nri

- cmd/containerd/builtins/builtins_freebsd.go
- cmd/containerd/builtins/zfs_linux.go
- go.mod
- go.sum
- vendor/github.com/containerd/zfs/v2/.gitignore
- vendor/github.com/containerd/zfs/v2/LICENSE
- vendor/github.com/containerd/zfs/v2/README.md
- vendor/github.com/containerd/zfs/v2/codecov.yml
- vendor/github.com/containerd/zfs/v2/plugin/plugin.go
- vendor/github.com/containerd/zfs/v2/zfs.go
- vendor/github.com/mistifyio/go-zfs/v3/.envrc
- vendor/github.com/mistifyio/go-zfs/v3/.gitignore
- vendor/github.com/mistifyio/go-zfs/v3/.golangci.yml
- vendor/github.com/mistifyio/go-zfs/v3/.yamllint
- vendor/github.com/mistifyio/go-zfs/v3/CHANGELOG.md
- vendor/github.com/mistifyio/go-zfs/v3/CONTRIBUTING.md
- vendor/github.com/mistifyio/go-zfs/v3/LICENSE
- vendor/github.com/mistifyio/go-zfs/v3/Makefile
- vendor/github.com/mistifyio/go-zfs/v3/README.md
- vendor/github.com/mistifyio/go-zfs/v3/Vagrantfile
- vendor/github.com/mistifyio/go-zfs/v3/error.go
- vendor/github.com/mistifyio/go-zfs/v3/lint.mk
- vendor/github.com/mistifyio/go-zfs/v3/rules.mk
- vendor/github.com/mistifyio/go-zfs/v3/shell.nix
- vendor/github.com/mistifyio/go-zfs/v3/utils.go
- vendor/github.com/mistifyio/go-zfs/v3/utils_notsolaris.go
- vendor/github.com/mistifyio/go-zfs/v3/utils_solaris.go
- vendor/github.com/mistifyio/go-zfs/v3/zfs.go
- vendor/github.com/mistifyio/go-zfs/v3/zpool.go
- vendor/modules.txt
> Add back ZFS snapshotter

- go.mod
- go.sum
- vendor/modules.txt
Updates to the tagged version, no code changes
> Update ttrpc to v1.2.6 tag

- go.mod
- go.sum
- vendor/github.com/containerd/plugin/.golangci.yml
- vendor/modules.txt
Updates to the tagged version, no code changes
> Update containerd plugin to v1.0.0

- core/remotes/docker/resolver.go
The resolver uses some log messages to indicate the next host will be used, however it would print this message even if no next host was available to try.
This patch changes the log messages to indicate the action taken, which is either "fetch failed" or if there's no other hosts to try, "trying next host".
While updating, also slightly updated the logs for consistency.
Before this patch:
DEBU[2024-10-23T20:49:29.640581097Z] resolving                                     host=registry-1.docker.io spanID=6e2b9c871009cfd9 traceID=6c65b97879548fce4372faa8375d17e6
DEBU[2024-10-23T20:49:29.640632763Z] do request                                    host=registry-1.docker.io request.header.accept="application/vnd.docker.distribution.manifest.v2+json, …
> resolver/docker: fix confusing "trying next host" log

- go.mod
- go.sum
- vendor/modules.txt
> Update errdefs to v1.0.0

- go.mod
- go.sum
- vendor/modules.txt
No changes since last rc, tag only update
> Update containerd API to v1.8.0 release

- .github/workflows/ci.yml
> Disable vagrant strict dependency checking

- go.mod
- go.sum
- vendor/github.com/containerd/typeurl/v2/types.go
- vendor/modules.txt
Fixes panic when typeurl is not found
> Update typeurl to v2.2.2

- script/setup/install-imgcrypt
Add repo env similar to other install script
> Update install-imgcrypt to allow change install repo

- internal/cri/server/images/image_pull.go
> fix: set the credentials even if not provided

- runtime/v2/runc/container.go
This PR ports #11069 to release/1.7 (with minor modification to use `logrus`).
It's not cherry picked because `runtime/v2/runc/container.go` was moved to `cmd/containerd-shim-runc-v2/runc/container.go`, and also 1.7 is still using `logrus` instead of `containerd/log` pkg.
> [release/1.7] Fix panic due to nil dereference cgroups v2

- internal/cri/server/container_start_linux.go
When kubelet enables UserNamespaceSupport feature gate, kubelet always uses non-empty UsernsOptions to setup pods. In this case, the gVisor shim is unable to parse runc.Option so that it will be unable to start container.
This change is to avoid adding IoOwner options if the UsernsOptions is for node level. Since gVisor hasn't feature subcommand yet, CRI status will report that gVisor runtime doesn't support user namespace. So it's kind of workaround to avoid compatible issue.
REF: #11091
> internal/cri: should not apply IoOwner options if it's not user namespace

- pkg/cri/sbserver/sandbox_run.go
- pkg/cri/sbserver/sandbox_run_test.go
- pkg/cri/server/sandbox_run.go
- pkg/cri/server/sandbox_run_test.go
- backport https://github.com/containerd/containerd/pull/9076
> [release/1.7 backport] Fix `ip_pref` configuration option

- plugins/cri/images/plugin.go
The cri image plugin init has a bug where, after getting FSPath for `snapshotter_i`, it always stores/overwrites it under `options.ImageFSPaths[defaultSnapshotter]` instead.
Also make a few other refactor:
1. Dedup the snapshotRoot logic.
2. Remove some unnecessary/nop logic in RuntimePlatforms for-loop.
---
Adding this to `config.toml`:
```toml
[plugins.'io.containerd.cri.v1.images'.runtime_platforms.native-runtime]
snapshotter = "native"
[plugins.'io.containerd.cri.v1.images'.runtime_platforms.overlayfs-runtime]
snapshotter = "overlayfs"
```
After this change, in containerd log:
```shell
$ sudo journalctl -u containerd | grep "Get image filesystem path"
Dec 16 01:15:34 ip-172-31-29-62 containerd[1595006]: time="2024-12-16T01:15:34.566632057Z" level=info msg="Get image filesystem path …
```
> Fix runtime platform loading in cri image plugin init

- cmd/ctr/commands/run/run.go
- contrib/apparmor/template.go
- contrib/fuzz/content_fuzz_test.go
- internal/cri/util/util.go
fix some function names in comment
> docs: fix some function names in comment

- pkg/cri/streaming/portforward/httpstream.go
fix:https://github.com/containerd/containerd/issues/11302
> [release/1.7] fix fatal error: concurrent map iteration and map write

- .devcontainer/devcontainer.json
- .github/actions/install-go/action.yml
- .github/workflows/api-release.yml
- .github/workflows/ci.yml
- .github/workflows/release.yml
- Vagrantfile
- contrib/Dockerfile.test
- contrib/fuzz/oss_fuzz_build.sh
- script/setup/prepare_env_windows.ps1
> update to go 1.24.0 / go1.23.6

- integration/image_mount_test.go
- integration/main_test.go
- internal/cri/server/container_create.go
- internal/cri/server/container_image_mount.go
- internal/cri/server/helpers.go
- internal/cri/server/sandbox_remove.go
- internal/cri/server/sandbox_run.go
- internal/cri/server/sandbox_stop.go
> Add OCI/Image Volume Source support

- docs/hosts.md
Clarify which directories containerd will search for the `hosts.toml` file when host contains a port. Plus minor formatting.
> Clarify port handling in `hosts.toml`

- .devcontainer/devcontainer.json
- .github/actions/install-go/action.yml
- .github/workflows/api-release.yml
- .github/workflows/ci.yml
- .github/workflows/release.yml
- Vagrantfile
- contrib/Dockerfile.test
- contrib/fuzz/oss_fuzz_build.sh
- script/setup/prepare_env_windows.ps1
- update build / release to go1.23.6
- run ci on go1.24.0
> [release/2.0] update build to go1.23.6, test go1.24.0

- services/diff/local.go
- services/diff/service_unix.go
- services/diff/service_windows.go
* pick https://github.com/containerd/containerd/pull/10284
> [release/1.7] Support to syncfs after pull by using diff plugin

- script/setup/install-imgcrypt
Add repo env similar to other install script
(cherry picked from commit f8819df7c4ee690315d45b57a4fddfcb970fcdd3)
> [release/1.7] Update install-imgcrypt to allow change install repo

- .github/workflows/ci.yml
Cherry-pick (not clean)
- #11427
> [release/2.0] CI: arm64-8core-32gb -> ubuntu-24.04-arm

- integration/container_stats_test.go
- integration/main_test.go
- internal/cri/server/podsandbox/sandbox_run.go
fix https://github.com/containerd/containerd/issues/11270
> Fix privileged container sysfs can't be rw because pod is ro by default

- pkg/cri/streaming/portforward/httpstream.go
cherry picked from commit 0fe9f0b52f7b700689df46d13de36e67b62486e1
> [release/1.6] fix fatal error: concurrent map iteration and map write

- pkg/archive/tar.go
This for example allowed us to gain ~5s while pulling/unpacking ghcr.io/huggingface/text-generation-inference:3.0.2 
Has impact in directories with a lot of files.
> perf(applyNaive): avoid walking the tree for each file in the same directory

- internal/nri/nri.go
- version/version.go
fix:https://github.com/containerd/containerd/issues/11485
> add name in package version

- images/image.go
- images/mediatypes.go
- remotes/handlers.go
Manual cherry-pick of https://github.com/containerd/containerd/pull/11327
> [release/1.7] Update image type checks to avoid unnecessary logs for attestations

- client/container.go
- client/task.go
- client/task_opts.go
- client/task_opts_unix.go
- core/runtime/v2/task_manager.go
- integration/client/client_unix_test.go
- integration/client/container_linux_test.go
fix: https://github.com/containerd/containerd/issues/11568
related pr: https://github.com/containerd/containerd/pull/11442 https://github.com/containerd/containerd/pull/11557
> update taskOptions based on runtimeOptions when creating a task 

- internal/cri/server/restart.go
fix container events sometimes lost when restart containerd
@mikebrow  @AkihiroSuda  @mxpv
> cri: fix lost container exit events if they arrive before info is cached

- pkg/sys/socket_unix.go
REF: https://github.com/containerd/containerd/issues/11609
> pkg/sys: improve GetLocalListener/CreateUnixSocket error message

- core/remotes/docker/pusher.go
Prevent a panic in the Docker pusher `pushWriter` object, by checking that the pipe it writes to is non `nil` before attempting to use it.
The panic was found by Moby issue #46746 (https://github.com/moby/moby/issues/46746). With this fix the panic no longer reproduces.
> Prevent panic in Docker pusher.

- plugins/transfer/plugin.go
- snapshotter_default_linux.go
- snapshotter_default_unix.go
- snapshotter_default_windows.go
(cherry picked from commit a083b669c9412eef55ee103fe2bb1dec7c6178bc)
Backported from #11641
> [release/1.7] backport: Set default differ for the default unpack config of transfer service

- .github/workflows/ci.yml
- script/critest.sh
> [release/2.0] Disable criu test on arm64

- docs/getting-started.md
Fixing install script to allow using arm64 architecture
> Fixing install instructions for Windows

- internal/cri/server/sandbox_run.go
Fix #10848 
When the netns prepara fails, it will result in missing extensions in metadata store. So store extension when create the sandbox in the store 
Additionally, some of the logs were modified, and the error messages and descriptions returned were somewhat inconsistent
- `sandboxInfo.AddExtension(...)` is to copy metadata to the extension.
- `c.client.SandboxStore().Update(..)`  is to updates metadata to the store.
/cc @mikebrow
> [CRI] store extension when create sandbox in metadata store

- core/transfer/local/pull.go
- Proposal: #9931
- Related to https://github.com/containerd/containerd/pull/8515#discussion_r1893256912
This PR enables to use the transfer service with remote snapshotters relying on [snapshot annotations](https://github.com/containerd/containerd/blob/e814b03c7488bd8982c97ecd050b33cecaf34037/pkg/snapshotters/annotations.go#L28-L45) (e.g. stargz, nydus, etc.). This is implemented by appending AppendInfoHandlerWrapper to the image handler list in the transfer service so that remote snapshotters can use these annotations for fetching layer contents.
~~For CRI integration(#8515), this flag should be enabled if the user specifies `disable_snapshot_annotations = false`.~~ ~~This feature can be enabled by `enable_remote_snapshot_annotations` field in config.toml.~~
Transfer Service appends …
> Transfer Service: enable to pass annotations to remote snapshotters

- core/remotes/docker/pusher.go
- core/remotes/docker/pusher_test.go
Instead of failing and returning the error received from the authorizer,
fall back the already existing path to handle non-nil response with a
status code indicating a failure.
Allow the Authorizer to return an error both from Authorize and from
AddResponses.
Signed-off-by: Alberto Garcia Hierro <damaso.hierro@docker.com>
> Fix cross-repo mount fallback after authorization failure

- contrib/seccomp/seccomp_default.go
This PR replaces https://github.com/containerd/containerd/pull/8361
> Add loong64 seccomp support

- .github/workflows/ci.yml
- .github/workflows/release.yml
- contrib/Dockerfile.test
- script/critest.sh
Fix CI in 1.7
Tried to also cherry-pick https://github.com/containerd/containerd/commit/027414ee5014c72f9acd6b666c8157969b6dd5ad, but it produces merge conflicts. So had to patch it manually.
> [release 1.7] Fix CI

- cmd/ctr/commands/shim/shim.go
The default computed address follows the format used by the io.containerd.runc.v2 shim, but there is no requirement that third-party shims follow the same format.  The new --shim-address option allows debugging of third-party shims with a different address format.
> ctr shim: allow override to computed shim address

- core/transfer/local/progress.go
For the progress tracker, after creating job, it doesn't mean that we have created ingest object for that job. There is race condition. We should not mark job as completed if blob is not found.
Fixes: #11758
> core/transfer/local: should not mark completed if it's not found

- cmd/containerd/command/config.go
This PR addresses one of the issues from https://github.com/containerd/containerd/issues/11747 where upon doing `containerd config dump` we don't accurately reflect the current plugin configuration.
> fix: update containerd config dump to reflect plugin config migrations.

- cmd/containerd/command/config.go
cherry-pick of d16ad8f5c500e6d32851989ac6a87f4dee1b2728 (https://github.com/containerd/containerd/pull/11748)
> [release/2.0] fix: update containerd config dump to reflect plugin config migrations.

- integration/client/container_test.go
Partially addressing issue #8422
This does not fix an underlying race in the output.
Currently the copy into the buffer is done in a go routine anyway and there is no close on the write. Are we expecting the status wait to account for the closing of the pipes? If there is a race, this should uncover it as the test will show a retry then pass.
> Add retries for flaky Windows test

- pkg/display/manifest_printer.go
Rather than exiting early with an error, just output that the content does not exist locally and continue. This is helpful for displaying multiplatform images when the content for every platform was not pulled. If a platform that did not exist locally showed up before one that did, the inspect would error out before even showing the content.
> Fix image inspect to skip over missing content

- docs/cri/config.md
Add CRI documentation about enabling Transfer Service for Image Pull by default.
Also add information about unsupported CRI Image Config options and automatic fallback mode. 
Follow up #8515
> Update CRI documentation to add information about Image Pull with Transfer Service

- internal/cri/streamingserver/doc.go
- internal/cri/streamingserver/portforward/doc.go
- internal/cri/streamingserver/portforward/httpstream.go
- internal/cri/streamingserver/portforward/websocket.go
- internal/cri/streamingserver/remotecommand/doc.go
- internal/cri/streamingserver/remotecommand/httpstream.go
- internal/cri/streamingserver/responsewriter/wrapper.go
- internal/cri/streamingserver/v1/doc.go
Addresses follow ups from code reviews from https://github.com/containerd/containerd/pull/11840
From @fuweid https://github.com/containerd/containerd/pull/11840#discussion_r2089566454
From @samuelkarp https://github.com/containerd/containerd/pull/11840#discussion_r2089685880
> follow-up changes discussed at end of review creating these packages

- pkg/archive/tar_test.go
Adds a tar test to cover symlink overrides
> Add symlink breakout test for overriden path

- .github/workflows/ci.yml
- Vagrantfile
fix: #11830 
Added jobs to ci.yml to test runc v1 using vagrant
ping @akhilerm
> [release/1.7] test: added runc v1 tests using vagrant

- pkg/oci/spec_opts_test.go
- Use testify for asserting
- Fix various unhandled errors
- Use native t.TempDir() for temporary files
> pkg/oci: cleanup some tests

- cmd/containerd-shim-runc-v2/process/init.go
- integration/container_io_leak_linux_test.go
fix:https://github.com/containerd/containerd/issues/11890
ping @AkihiroSuda  @samuelkarp  @mikebrow @mxpv
> bugfix:close container io when runtime create failed

- cmd/ctr/commands/sandboxes/sandboxes.go
Just add a new sandbox info command to print sandbox info
Signed-off-by: Ruidong Cao <caoruidong.crd@alibaba-inc.com>
> ctr:add sandbox info command to print sandbox info

- internal/cri/server/restart.go
fix https://github.com/containerd/containerd/issues/10848
I add some sleep at 
```
if err := sandboxInfo.AddExtension(podsandbox.MetadataKey, &sandbox.Metadata); err != nil {
return nil, fmt.Errorf("unable to save sandbox %q to store: %w", id, err)
}
// Save sandbox metadata to store
time.Sleep(time.Second*60)
if sandboxInfo, err = c.client.SandboxStore().Update(ctx, sandboxInfo, "extensions"); err != nil {
return nil, fmt.Errorf("unable to update extensions for sandbox %q: %w", id, err)
}
```
create a pod when containerd is running at sleep 60 restart containerd, it will happen.
> cri:fix containerd panic when can't find sandbox extension

- .github/workflows/ci.yml
- core/content/testsuite/testsuite.go
- internal/cri/executil/exec_test.go
We have seen the following intermittent/transient failures for a while now on windows CIs. Trying to fix them
> Fix intermittent test failures on Windows CIs

- .github/workflows/build-test-images.yml
- .github/workflows/ci.yml
- .github/workflows/windows-hyperv-periodic.yml
- .github/workflows/windows-periodic.yml
- core/content/testsuite/testsuite.go
- integration/images/volume-copy-up/Makefile
- integration/images/volume-ownership/Makefile
Backport the following commits:
(https://github.com/containerd/containerd/commit/12daca5f644b63ca42a34a3d6c28cdf02084bd23)
(https://github.com/containerd/containerd/commit/117179ae1af952cbf1d006938270e57c3a777e4b)
> [release/2.1] Backport windows test fixes

- .github/workflows/build-test-images.yml
- .github/workflows/ci.yml
- .github/workflows/windows-periodic.yml
- content/testsuite/testsuite.go
- integration/images/volume-copy-up/Makefile
- integration/images/volume-ownership/Makefile
Backport the following commits:
(https://github.com/containerd/containerd/commit/12daca5f644b63ca42a34a3d6c28cdf02084bd23)
(https://github.com/containerd/containerd/commit/117179ae1af952cbf1d006938270e57c3a777e4b)
> [release/1.6] Backport windows test fixes

- .github/workflows/build-test-images.yml
- .github/workflows/ci.yml
- .github/workflows/windows-hyperv-periodic.yml
- .github/workflows/windows-periodic.yml
- content/testsuite/testsuite.go
- integration/images/volume-copy-up/Makefile
- integration/images/volume-ownership/Makefile
Backport the following commits:
(https://github.com/containerd/containerd/commit/12daca5f644b63ca42a34a3d6c28cdf02084bd23)
(https://github.com/containerd/containerd/commit/117179ae1af952cbf1d006938270e57c3a777e4b)
> [release/1.7] Backport windows test fixes

- internal/cri/server/container_checkpoint_linux.go
This pull request modifies the restore code to avoid image pull if the base image is already cached locally by containerd.
Fixes: #11901
> restore: skip pull for existing base image

- .mailmap
Removes duplicates in release notes.
> Update mailmap for austinvazquez

- RELEASES.md
> 1.6 is EOL
