cmd/ctr/commands/commands.go
cmd/ctr/commands/commands_unix.go
cmd/ctr/commands/images/mount.go
cmd/ctr/commands/images/push.go
cmd/ctr/commands/snapshots/snapshots.go

We should keep the lower case letter for flag info

keep the lower case letter for flag info

---

cmd/containerd/command/main.go

There have "oci-hook" sub-command , but the describe info is wrong for that..

complement sub-command note for containerd-main

---

content/helpers.go
content/helpers_test.go
remotes/docker/pusher.go
remotes/docker/pusher_test.go

This is not a clean cherry-pick of #6995 
cherry-pick #7473 (clean / fix )
when a put request is retried due to the response from registry, the body of the request should be seekable. A dynamic pipe is added to the body so that the content of the body can be read again. Currently a maximum of 5 resets are allowed, above which will fail the request. A new error ErrReset is introduced which informs that a reset has occured and request needs to be retried.
also added tests for Copy() and push() to test the new functionality

[release/1.5] retry request on writer reset

---

script/setup/install-gotestsum

Now the ci go-version is "1.19.3".
Maybe change the gotestsum to the v1.8.2 for match go1.19.
[gotestsum release](https://github.com/gotestyourself/gotestsum/releases/tag/v1.8.2)

gotestsum match go version 1.19

---

pkg/shutdown/shutdown.go

Currently these are not used, but I found them convenient to use in sandboxed shim's `WaitSandbox`, to block caller until someone else shutdowns the shim.

Expose Done and Err in Shutdown service

---

pkg/cri/config/config.go
pkg/cri/config/config_unix.go
pkg/cri/config/config_windows.go
pkg/cri/server/sandbox_run.go

Signed-off-by: Fei Su <sofat1989@126.com>
```release-note
can set up the network serially by CNI plugins
```
Indeed we have two CNI plugins which have independent CNI configuration files. For example
```
tnet.conf ztio.conf
```
We want to run these two plugins serially. because running CNI plugin in `ztio.conf` will depend on some configurations set by the CNI plugin in `tnet.conf`.
By default, containerd will run them parallelly. So it may fail randomly.
For CNI interface, there is a function `SetupSerially` reserved for setting up serially. So we want that there is a flag in the config file of containerd to control this.
The expected config in config.toml:
```
[plugins."io.containerd.grpc.v1.cri".cni]
max_conf_num = 2
setup_serially = true
```

can set up the network serially by CNI plugins

---

BUILDING.md

When i build containerd in CentOS Stream 9 ,  build err , tips the "btrfs/ioctl.h: No such file or directory"
Follow the docs , and try to install : yum install btrfs-progs-devel
But there have no package for centos9 , So search the centos web , for fix the build problem.
I refer the web is  
[centos](https://cbs.centos.org/koji/buildinfo?buildID=32944)
[build issue](https://github.com/containerd/containerd/issues/3488)
After i install the rpm , then its fine for me..

fix build containerd in centos9

---

client.go

I think the platform will be processd later .
Like the image.go or.. others..
```
func NewImage(client *Client, i images.Image) Image {
return &image{
client:   client,
i:        i,
platform: client.platform,
}
}
```

Missed out `platform interface` when reused the conn for Client.

---

pkg/cri/annotations/annotations.go
pkg/cri/sbserver/container_create_linux.go
pkg/cri/sbserver/container_create_linux_test.go
pkg/cri/sbserver/container_create_windows.go
pkg/cri/sbserver/container_create_windows_test.go
pkg/cri/sbserver/podsandbox/sandbox_run_linux.go
pkg/cri/sbserver/podsandbox/sandbox_run_linux_test.go
pkg/cri/sbserver/podsandbox/sandbox_run_windows.go
pkg/cri/sbserver/podsandbox/sandbox_run_windows_test.go
pkg/cri/server/container_create_linux.go
pkg/cri/server/container_create_linux_test.go
pkg/cri/server/container_create_windows.go
pkg/cri/server/container_create_windows_test.go
pkg/cri/server/sandbox_run_linux.go
pkg/cri/server/sandbox_run_linux_test.go
pkg/cri/server/sandbox_run_windows.go
pkg/cri/server/sandbox_run_windows_test.go

Containerd already has annotations for pod name an pod namespace this PR introduces an annotation for pod uid. This will be helpful for projects like inspektor-gadget to simplify getting [metadata ](https://github.com/inspektor-gadget/inspektor-gadget/blob/e332776435abbad634178b3ed2a535d2d330b7e0/pkg/container-collection/options.go#L600)about pods.

cri: add pod uid annotation

---

.github/workflows/scorecards.yml

Allow actions/checkout in scorecards workflow to use latest v3 commit.
Resolves `save-state` command usage warnings.
Latest run: https://github.com/containerd/containerd/actions/runs/3510597304/jobs/5880546790
Related issue: https://github.com/containerd/project/issues/95

Resolve Scorecards GitHub Actions workflow warnings

---

contrib/seccomp/seccomp_default.go

Follow up to 94faa70df4d78538605bb492010954a7e3bec67a. The commit referenced allowed `ptrace` calls in the default seccomp profile following the usual tracing security checks in for Kernels newer than 4.8. Kernels prior to this version are susceptible to [CVE-2019-2054](https://github.com/advisories/GHSA-qgfr-27qf-f323).  Moby's default had allowed for `ptrace` for kernels newer than 4.8 at the time the commit was created. The current [seccomp default](https://github.com/moby/moby/blob/master/profiles/seccomp/default_linux.go#L405-L417) has been updated to include `process_vm_read` and `process_vm_write`. Mirror that policy to complete the classic ptrace set of APIs.
Signed-off-by: Juan Sebastian Hoyos Ayala <juan.s.hoyos@outlook.com>

Add process_vm read and write calls to default seccomp profile

---

runtime/v2/runc/manager/manager_linux.go
runtime/v2/runc/v1/service.go
runtime/v2/shim/shim.go

The shim based on the file *shim/shim.go* no longer needs to use public flag to publish events, instead using the `TTRPC_ADDRESS` environment variable, we can remove the meaningless use of containerdBinary
Of course, for compatibility we still need to support `--publish-binary` flag.

runtime/v2/shim: clean up the use of containerdBinary

---

integration/sandbox_run_rollback_test.go
pkg/cri/sbserver/podsandbox/helpers.go
pkg/cri/sbserver/podsandbox/sandbox_delete.go
pkg/cri/sbserver/podsandbox/sandbox_run.go
pkg/cri/sbserver/podsandbox/sandbox_stop.go
pkg/cri/sbserver/restart.go
pkg/cri/sbserver/sandbox_run.go
pkg/cri/sbserver/sandbox_status.go

This pull request ports #5904 and #7481 to the sbserver implementation in the CRI plugin.  Since sbserver is still incomplete, this PR is currently working around the incomplete parts.  However, it does pass all the integration tests and is working.
I'd like to get this merged as we continue to work on the Sandbox API since the integration tests enabled by this PR will help catch behavior regressions.
(cc @qiutongs)

[port #5904 to sbserver] Setup pod network after creating the sandbox container

---

.github/workflows/windows-hyperv-periodic.yml
.github/workflows/windows-periodic.yml

Upgrade actions/github-script from v3 to v6 to resolve Node.js 12 and `set-output` command warnings.
Upgrade google-github-actions/upload-cloud-storage from v0.8.0 to v0.10.4 to resolve `set-output` command warnings.
Upgrade actions/checkout from v2 to v3 to resolve Node.js 12 warnings.
Remove references to `set-output` command from workflow.
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
Latest Windows Periodic Run: https://github.com/containerd/containerd/actions/runs/3510720613
Latest Windows Hyper-V Periodic Run: https://github.com/containerd/containerd/actions/runs/3510698554
Related issue: …

Resolve warnings in Windows GitHub Actions periodic workflows

---

go.mod
go.sum
integration/client/go.mod
integration/client/go.sum
vendor/modules.txt

go.mod doesn't always do a great job on keeping the dependencies grouped in the
right block; 2b60770c4b210e769d2fcbeaf25588af9494a822 added an extra "require"
block, after which things went downward.
This patch is grouping them back in the right block to nudge it in the right
direction.
While the version isn't used (as it's replaced), let's keep it somewhat
in line with reality :)
This was updated in 470d3ee057de19a1d6cf8f7f94d9d98980d2a08d, but we
only needed the ebpf update. As nothing depends on this module anymore,
other than for the stats package (which didn't change in between), we
can (for now) roll it back to v1.0.4, and just force the newer ebpf
package.
Things rolled back (doesn't affect vendored code);
https://github.com/containerd/cgroups/compare/7083cd60b721..v1.0.4

integration/client: fix go.mod grouping, containerd to v1.7.0-beta.0, cgroups back to v1.0.4

---

pkg/cri/sbserver/container_create.go
pkg/cri/sbserver/podsandbox/helpers.go
pkg/cri/sbserver/podsandbox/helpers_test.go
pkg/cri/sbserver/podsandbox/sandbox_run.go
pkg/cri/sbserver/sandbox_run.go
pkg/cri/sbserver/sandbox_status.go
pkg/cri/sbserver/service.go
services/sandbox/controller_local.go

This PR fixes sandbox API so it can properly call sandboxed shims.
Also refactored and removed duplicated code from `podsandbox` package.
--
Added a few commits to further decouple sbserver from pause container (and left bunch of todos for the remaining work)

Fix sandbox API when calling sandboxed shims

---

contrib/apparmor/template.go

Fixes https://github.com/containerd/containerd/issues/7695. The default profile allows processes within the container to trace others, but blocks reads/traces. This means that diagnostic facilities in processes can't easily collect crash/hang dumps. A usual workflow used by solutions like crashpad and similar projects is that the process that's unresponsive will spawn a process to collect diagnostic data using ptrace. seccomp-bpf, yama ptrace settings, and CAP_SYS_PTRACE already provide security mechanisms to reduce the scopes in which the API can be used. This enables reading from /proc/* files provided the tracer process passes all other checks.
Signed-off-by: Juan Hoyos <juan.s.hoyos@outlook.com>

Add ptrace readby and tracedby to default AppArmor profile

---

go.mod
go.sum
integration/client/go.sum
vendor/modules.txt

This module made a whoopsie, and updated to `google.golang.org/protobuf` in a patch release, but `google.golang.org/protobuf` is not backward compatible with `github.com/golang/protobuf`.
Updating the minimum version to v1.0.4 which corrects this, to prevent users of containerd as a module from accidentally pulling in the wrong version:
- v1.0.3 switched to use `google.golang.org/protobuf`; https://github.com/matttproud/golang_protobuf_extensions/compare/v1.0.2..v1.0.3
- This was reverted in v1.0.4 (which is the same as v1.0.2); https://github.com/matttproud/golang_protobuf_extensions/compare/v1.0.3..v1.0.4
- And a `v2` was created instead; https://github.com/matttproud/golang_protobuf_extensions/releases/tag/v2.0.0

go.mod: golang_protobuf_extensions v1.0.4 - prevent incompatible versions

---

go.mod
go.sum
integration/client/go.sum
vendor/modules.txt

- same as https://github.com/containerd/containerd/pull/7721
This module made a whoopsie, and updated to `google.golang.org/protobuf` in a patch release, but `google.golang.org/protobuf` is not backward compatible with `github.com/golang/protobuf`.
Updating the minimum version to v1.0.4 which corrects this, to prevent users of containerd as a module from accidentally pulling in the wrong version:
- v1.0.3 switched to use `google.golang.org/protobuf`; https://github.com/matttproud/golang_protobuf_extensions/compare/v1.0.2..v1.0.3
- This was reverted in v1.0.4 (which is the same as v1.0.2); https://github.com/matttproud/golang_protobuf_extensions/compare/v1.0.3..v1.0.4
- And a `v2` was created instead; https://github.com/matttproud/golang_protobuf_extensions/releases/tag/v2.0.0

[release/1.6] go.mod: use golang_protobuf_extensions v1.0.4 to prevent incompatible versions

---

pkg/cri/annotations/annotations.go
pkg/cri/server/container_create_linux.go
pkg/cri/server/container_create_linux_test.go
pkg/cri/server/container_create_windows.go
pkg/cri/server/container_create_windows_test.go
pkg/cri/server/sandbox_run_linux.go
pkg/cri/server/sandbox_run_linux_test.go
pkg/cri/server/sandbox_run_windows.go
pkg/cri/server/sandbox_run_windows_test.go

This PR is cherry-pick for ["cri: add pod uid annotation"](https://github.com/containerd/containerd/pull/7697)
Created an test pod in a Kubernetes environment with complied binaries, shows following annotations:
```
cat /run/containerd/io.containerd.runtime.v2.task/k8s.io/1733e7a76be7ee5c026275bb563de617e1e5723164a1f07903469a320d5a67a4/config.json
...
...
"annotations": {
"io.kubernetes.cri.container-name": "test-pod-9240",
"io.kubernetes.cri.container-type": "container",
"io.kubernetes.cri.image-name": "mirror.gcr.io/library/alpine:latest",
"io.kubernetes.cri.sandbox-id": "08880aefad635b5735451d8e933536ca4d715378f3bd94cd35bc8cab77884095",
"io.kubernetes.cri.sandbox-name": "test-pod-9240",
"io.kubernetes.cri.sandbox-namespace": "default",
"io.kubernetes.cri.sandbox-uid": …
```

[release/1.6] cri: add pod uid annotation

---

pull.go

use MaxConcurrentDownloads instead of MaxConcurrentUploadedLayers to limit max concurrent layer downloads while pulling an image.
Signed-off-by: guodong <guodong9211@gmail.com>

use MaxConcurrentDownloads instead of MaxConcurrentUploadedLayers

---

integration/sandbox_clean_remove_windows_test.go
pkg/cri/sbserver/helpers.go
pkg/cri/server/helpers.go

This PR adds nullptr checks before dereferencing pointers in pkg/cri/server/helpers.go copyResourcesToStatus() function. The function was introduced as part of [this](https://github.com/containerd/containerd/pull/6517/files#diff-013b0386f279e1c4bfe5d539426d97d8a48ea75a0aa7fc0775cf0fdaf52eb907) PR.
While running some hcsshim tests, containerd crashed with a panic due to nullptr dereference and this PR attempts to fix that.

Check for nullptr before dereferencing

---

leases/lease.go
leases/lease_test.go

Fixes an edge case where `WithLabels` would overwrite `WithExpiration` on a lease when using both client options and a expire value is not provided via labels. A user may expect the maps to be merged.
For example, see https://github.com/containerd/containerd/blob/main/cmd/ctr/commands/images/mount.go#L75-L81

Fix order of operations when setting lease labels

---

integration/sandbox_clean_remove_windows_test.go
pkg/cri/server/helpers.go

Porting commit 08d5879f3215e6484a82d39633bd5d57228202dc from containerd main to release/1.6 branch. 
This PR adds nullptr checks before dereferencing pointers in pkg/cri/server/helpers.go copyResourcesToStatus() function. The function was introduced as part of [this](https://github.com/containerd/containerd/pull/6517/files#diff-013b0386f279e1c4bfe5d539426d97d8a48ea75a0aa7fc0775cf0fdaf52eb907) PR.
While running some hcsshim tests, containerd crashed with a panic due to nullptr dereference and this PR attempts to fix that.
Signed-off-by: Kirtana Ashok <Kirtana.Ashok@microsoft.com>
(cherry picked from commit 08d5879f3215e6484a82d39633bd5d57228202dc)
Signed-off-by: Kirtana Ashok <Kirtana.Ashok@microsoft.com>

[release/1.6] Added nullptr checks to pkg/cri/server and sbserver

---

archive/tar.go
archive/tar_opts.go
archive/tar_test.go

`WithModTimeUpperBound` sets the upper bound value of the `ModTime` property of the tar entry structs.
`WithSourceDateEpoch` now implies `WithModTimeUpperBound` too, in addition to `WithWhiteoutTime` (https://github.com/containerd/containerd/pull/7478).
For 
- moby/buildkit#3296

archive: set WithModTimeUpperBound when WithSourceDateEpoch is set

---

leases/lease.go
leases/lease_test.go

Fixes an edge case where `WithLabels` would overwrite `WithExpiration` on a lease when using client options.
(cherry picked from commit c4dee237f57a7f7895aaaf32cae6ab312019014a)

[release/1.6] cherry-pick: Fix order of operations when setting lease labels

---

leases/lease.go
leases/lease_test.go

Fixes an edge case where `WithLabels` would overwrite `WithExpiration` on a lease when using client options.
(cherry picked from commit c4dee237f57a7f7895aaaf32cae6ab312019014a)

[release/1.5] cherry-pick: Fix order of operations when setting lease labels

---

README.md
RELEASES.md

Update to point to containerd/project documentation that lists a new
way to report a security vulnerability on Github directly.

docs: Add extra security instructions

---

docs/ops.md

update the obsolete docs  for current 1.7 version .

upgrade the ops.md output for current 1.7 version .

---

contrib/seccomp/seccomp_default.go

In #7693 we added two ptrace related syscalls for kernels >= 4.8, however I believe the syscall names had a minor typo.
Both the [man page](https://man7.org/linux/man-pages/man2/process_vm_readv.2.html) and the [docker seccomp default](https://github.com/moby/moby/blob/master/profiles/seccomp/default_linux.go#L405-L417) that was being compared show the syscalls are named:
`process_vm_readv`
`process_vm_writev` 
(This is also the syscall name we use later in this file when `CAP_SYS_PTRACE` is checked [here](https://github.com/containerd/containerd/blob/main/contrib/seccomp/seccomp_default.go#L639-L640))
It may be worth trying to confirm (using [a toy program](https://gist.github.com/FergusInLondon/fec6aebabc3c9e61e284983618f40730) that uses the `process_vm_ready` syscall) that this now …

Fix process_vm_* syscall names in seccomp

---

cmd/containerd-stress/density.go

/kind bug
Fix panic , when user input --count 0 or <0 meaningless number.
before is :
fix after is:

fix panic when containerd-stress density --count 0

---

rootfs/diff.go

Cherry-pick into 1.6:
- https://github.com/containerd/containerd/pull/7204
This makes it possible to run `rootfs.CreateDiff` multiple times simultaneously.
Original PR message:
"""
In CreateDiff function, we wil create view snapshot base on parent snapshot,
view snapshot name is "`<parent snapshot KEY>`-parent-view",
so while, It does not support concurrent operations，other user will be return to the error that the snapshot already exists.
So, we add uniquePart() as a suffix.
"""
(cherry picked from commit 344431cdd48ec19b73fdc5d36f056eb7bee5154b)
Signed-off-by: Paweł Gronowski <pawel.gronowski@docker.com>

[release/1.6] fix: support simultaneous create diff for same parent snapshot

---

releases/v1.5.15.toml
version/version.go

----
containerd 1.5.15
Welcome to the v1.5.15 release of containerd!
The fifteenth patch release for containerd 1.5 includes various fixes including a
long time issue with CNI resource leakage.
* **Fix CNI leaks by changing pod network setup order in CRI plugin** ([#7464](https://github.com/containerd/containerd/pull/7464))
* **Fix request retry on push** ([#7479](https://github.com/containerd/containerd/pull/7479))
* **Fix lease labels unexpectedly overwriting expiration** ([#7746](https://github.com/containerd/containerd/pull/7746))
* Akihiro Suda
* Wei Fu
* Phil Estes
* …

Prepare release notes for v1.5.15

---

tracing/plugin/otlp.go
tracing/plugin/otlp_test.go
vendor/go.opentelemetry.io/otel/sdk/trace/tracetest/exporter.go
vendor/go.opentelemetry.io/otel/sdk/trace/tracetest/recorder.go
vendor/go.opentelemetry.io/otel/sdk/trace/tracetest/span.go
vendor/modules.txt

Add unit tests to NewExporter and NewTracer for opentelemetry tracing support
The unit tests feed input of different combination of the cfg, then check the expected output
This PR is part of [issue 7493](https://github.com/containerd/containerd/issues/7493)
Signed-off-by: Tony Fang <nenghui.fang@gmail.com>
Unit test ran locally:
```
$ go test -v -run TestNewExporter
=== RUN   TestNewExporter
=== RUN   TestNewExporter/Test_http/protobuf_protocol,_expect_no_error
otlp_test.go:72: input: {http://localhost:4318 http/protobuf false}
otlp_test.go:76: output: <nil>
=== RUN   TestNewExporter/Test_invalid_endpoint,_expect_ErrInvalidArgument_error
otlp_test.go:72: input: {http://localhost
:4318 http/protobuf false}
otlp_test.go:76: output: OpenTelemetry endpoint "http://localhost\n:4318" is …
```

Add unit test to Opentelemetry tracing

---

remotes/handlers.go

Before this required a full content.Store so that it could annotate distribution sources.
With this change PushContent can be used with just a content.Provider. If the content.Provider is also a content.Manager then distribution sources will be updated accordingly.
This allows people to use this function with a significantly implementation.
---
I was trying to use remotes.PushContent to implement push directly from an OCI tarball only to realize this wants the full content.Store which I had no interest in implementing for a read-only tarball.

Change PushContent to require only Provider

---

.github/workflows/build-test-images.yml
.github/workflows/ci.yml
.github/workflows/codeql.yml
.github/workflows/images.yml
.github/workflows/nightly.yml
.github/workflows/release.yml
Vagrantfile
contrib/Dockerfile.test
script/setup/prepare_env_windows.ps1

- relates to https://github.com/containerd/containerd/pull/7765
Includes security fixes for net/http (CVE-2022-41717, CVE-2022-41720), and os (CVE-2022-41720).
These minor releases include 2 security fixes following the security policy:
- os, net/http: avoid escapes from os.DirFS and http.Dir on Windows
The os.DirFS function and http.Dir type provide access to a tree of files rooted at a given directory. These functions permitted access to Windows device files under that root. For example, os.DirFS("C:/tmp").Open("COM1") would open the COM1 device. Both os.DirFS and http.Dir only provide read-only filesystem access.
In addition, on Windows, an os.DirFS for the directory \(the root of the current drive) can permit a maliciously crafted path to escape from the drive and access any path on …

[release/1.6] update to go1.18.9

---

.github/workflows/ci.yml
.github/workflows/nightly.yml
.github/workflows/release.yml
Vagrantfile
contrib/Dockerfile.test

- relates to https://github.com/containerd/containerd/pull/7765
Includes security fixes for net/http (CVE-2022-41717, CVE-2022-41720), and os (CVE-2022-41720).
These minor releases include 2 security fixes following the security policy:
- os, net/http: avoid escapes from os.DirFS and http.Dir on Windows
The os.DirFS function and http.Dir type provide access to a tree of files rooted at a given directory. These functions permitted access to Windows device files under that root. For example, os.DirFS("C:/tmp").Open("COM1") would open the COM1 device. Both os.DirFS and http.Dir only provide read-only filesystem access.
In addition, on Windows, an os.DirFS for the directory \(the root of the current drive) can permit a maliciously crafted path to escape from the drive and access any path on …

[release/1.5] update to go1.18.9

---

.github/workflows/build-test-images.yml
.github/workflows/ci.yml
.github/workflows/codeql.yml
.github/workflows/images.yml
.github/workflows/nightly.yml
.github/workflows/release.yml
Vagrantfile
contrib/Dockerfile.test
contrib/fuzz/oss_fuzz_build.sh
script/setup/prepare_env_windows.ps1

Includes security fixes for net/http (CVE-2022-41717, CVE-2022-41720), and os (CVE-2022-41720).
These minor releases include 2 security fixes following the security policy:
- os, net/http: avoid escapes from os.DirFS and http.Dir on Windows
The os.DirFS function and http.Dir type provide access to a tree of files rooted at a given directory. These functions permitted access to Windows device files under that root. For example, os.DirFS("C:/tmp").Open("COM1") would open the COM1 device. Both os.DirFS and http.Dir only provide read-only filesystem access.
In addition, on Windows, an os.DirFS for the directory \(the root of the current drive) can permit a maliciously crafted path to escape from the drive and access any path on the system.
The behavior of os.DirFS("") has changed. Previously, …

update to go1.19.4, go1.18.9

---

.cirrus.yml
Vagrantfile

v7.0.0 does not boot. v6.0.0 was not released.

CI: Vagrant: pin rockylinux/8 to v5.0.0

---

snapshots/overlay/overlayutils/check.go

Fixes #7770
It uses [statfs](https://man7.org/linux/man-pages/man2/statfs.2.html) to check if the dir provided to [NeedsUserXAttr](https://github.com/containerd/containerd/blob/0fa51f54dfee239c606b837aaa8c8ae6b28a9c4a/snapshots/overlay/overlayutils/check.go#L110) function is on a tempfs.
For detail information see #7770

fix: check for tmpfs when evaluating if userxattr is needed

---

snapshots/overlay/overlayutils/check.go

[release/1.6] fix: check for tmpfs when evaluating if userxattr should be used

---

remotes/docker/resolver.go

I was interested in the status code returned by the registry, so I traced some code to find `ErrUnexpectedStatus`, and maybe that info can be made more accessible.
Signed-off-by: Hsing-Yu (David) Chen <davidhsingyuchen@gmail.com>

docs: Authorizer.Authorize could return ErrUnexpectedStatus

---

integration/container_event_test.go
integration/cri-api/pkg/apis/services.go
integration/remote/remote_runtime.go
pkg/cri/sbserver/container_create.go
pkg/cri/sbserver/container_events.go
pkg/cri/sbserver/container_remove.go
pkg/cri/sbserver/container_start.go
pkg/cri/sbserver/container_stop.go
pkg/cri/sbserver/events.go
pkg/cri/sbserver/helpers.go
pkg/cri/sbserver/sandbox_remove.go
pkg/cri/sbserver/sandbox_run.go
pkg/cri/sbserver/service.go
pkg/cri/server/container_create.go
pkg/cri/server/container_events.go
pkg/cri/server/container_remove.go
pkg/cri/server/container_start.go
pkg/cri/server/container_stop.go
pkg/cri/server/events.go
pkg/cri/server/helpers.go
pkg/cri/server/sandbox_remove.go
pkg/cri/server/sandbox_run.go
pkg/cri/server/service.go

This PR adds container event support (https://github.com/kubernetes/enhancements/issues/3386) to containerd, by implementing GetContainerEvents() CRI API that supports single-caller and returns all container events (i.e. not filtered by container ID or other filters) to the caller.
Tests Done
1. Integration test TestContainerEvents added.
2. Manually tested by
a. Creating a k8s cluster with k8s version evented pleg support and containerd from this PR.
b. Deploying an simple Job and verifying the pod status turned to Running -> Terminating, and then disappeared
> 
To-do list before un-drafting:

Add container event support to containerd

---

task.go

Fixes #7357
If a container is restored from a checkpoint that has a configuration error, the task for the restored container is created, but fails to start and is left in the state CREATED with a PID of 0. 
In the original issue, the induced error comes from call to `task.Start`:
```
ctr: OCI runtime restore failed: namespace {"not" ""} does not exist: unknown
```
The main task created from a *restored* container will always be PID 0 before the task is explicitly started
https://github.com/containerd/containerd/blob/e1abaeb3862827d3f507c092d5c1c99e0968a8fc/cmd/ctr/commands/containers/restore.go#L107
I had originally intended to make a change on the go-runc side to prevent PID 0 tasks from even being created, but given that restored tasks are assigned a PID at `task.Start`, that would have …

allow client to remove created tasks with PID 0

---

.github/workflows/ci.yml
.github/workflows/nightly.yml

Resolves minor issues when running GitHub Actions CI locally using nektos/act for Linux jobs.
Sync package index and automatic yes to apt repository prompts.
Tested using the following:
```
act --job integration-linux --privileged --secret GITHUB_TOKEN
act --job linux --privileged --secret GITHUB_TOKEN
```
Still have a few issues with one or two test suites, e.g. mounts and snapshots/overlay, however it has proven useful for fast feedback checks of CI updates.

Enable GitHub Actions local Linux CI runs

---

.github/workflows/release.yml

Resolve NodeJS 12 and command deprecation warnings by upgrading docker/setup-buildx-action and crazy-max/ghaction-github-runtime packages.
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
Last release: https://github.com/containerd/containerd/actions/runs/3643283543
Related-issue: https://github.com/containerd/project/issues/95

Upgrade GitHub actions packages in release workflow

---

contrib/fuzz/archive_fuzzer.go

Currently the fuzzer does not check all the files in the tar archive which it should. This pr fixes that.

fuzzing: improve archive fuzzer

---

.mailmap
releases/v1.7.0-beta.toml
version/version.go

----
containerd 1.7.0-beta.1
Welcome to the v1.7.0-beta.1 release of containerd!  
The previous 1.6 release has also become a long term stable release for users who prefer releases with mostly stability improvements and wish to wait a few releases for new functionality.
_This is …

Prepare release notes for v1.7.0-beta.1

---

pkg/cri/sbserver/image_pull.go
pkg/cri/sbserver/metrics.go
pkg/cri/server/image_pull.go
pkg/cri/server/metrics.go

/cc @cpuguy83  
Fixes #7241
This pr tries to add some metrics for image pulling.
1. Guage: in-progress pulls counts
2. Counter: image pull error counts
- Should this count by registry or image name?
- Should we add the failure reason as a metric label?
3. Histogram: throughout(image pull time for 1 MiB) group by the registry
image throughout may be related to CPU/disk io/network.
Further options to add for image pulling:
1. max_concurrent_downloads: default 3. This may be related to the image pulling speed. https://github.com/containerd/containerd/pull/2920
2. Histogram: [Need Discussion] image-pull time group by the registry(maybe not proper as size may be different.)
3. Histogram: image size
4. image_pull_progress_timeout of contained configuration(default 1m0s)
TODO(some unfinished …

add metrics for image pulling: error; in progress count; thoughput 

---

integration/container_update_resources_test.go
pkg/cri/opts/spec_linux.go
pkg/cri/sbserver/container_update_resources_linux_test.go
pkg/cri/server/container_update_resources_linux_test.go

OCI runtime spec defines [memory.swap](https://github.com/opencontainers/runtime-spec/blob/main/config-linux.md?plain=1#L325) as 'limit of memory+Swap usage' so setting them to equal should disable the swap (limits for cgroup v1). Also, this change should make containerd behaviour same as other runtimes e.g [cri-dockerd](https://github.com/Mirantis/cri-dockerd/blob/master/core/helpers_linux.go#L45)/[dockershim](https://github.com/kubernetes/kubernetes/blob/v1.23.0/pkg/kubelet/dockershim/helpers_linux.go#L116) and won't be [impacted](https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/kuberuntime/kuberuntime_container_linux.go#L94) when user turn on 'NodeSwap' (https://github.com/kubernetes/enhancements/issues/2400) feature.
We hit this issue in …

cri: make swapping disabled with memory limit

---

.github/workflows/ci.yml
script/setup/install-dev-tools

Bumps golangci-lint from `v1.49.0` to `v1.50.1`

Bump golangci-lint to v1.50.1

---

go.mod
go.sum
integration/client/go.mod
integration/client/go.sum
vendor/github.com/Microsoft/hcsshim/internal/cow/cow.go
vendor/github.com/Microsoft/hcsshim/internal/hcs/system.go
vendor/modules.txt

This bumps shim tag to include a fix from 
[microsoft/hcsshim @ 5d5b21088e7fc80eeea5172e573c8fa68f3de046](https://github.com/microsoft/hcsshim/commit/5d5b21088e7fc80eeea5172e573c8fa68f3de046)
Change log for hcsshim v0.9.6 can be seen [here](https://github.com/microsoft/hcsshim/releases/tag/v0.9.6).

[release/1.6] go.mod: Bump hcsshim to v0.9.6

---

integration/container_update_resources_test.go
pkg/cri/opts/spec_linux.go
pkg/cri/server/container_update_resources_linux_test.go

Cherry pick for ["cri: make swapping disabled with memory limit"](https://github.com/containerd/containerd/pull/7783)

[release/1.6] cri: make swapping disabled with memory limit

---

task.go

cherry-pick https://github.com/containerd/containerd/pull/7787/commits/80839f11e2ea6759eed4b5e616d65cb59258a5f3
If a container is restored from a checkpoint that has a configuration error, the task for the restored container is created, but fails to start and is left in the state CREATED with a PID of 0. Before this change, the only way to remove this task was to find the PID of the shim monitoring the task and kill that process. Now, ctr t rm <task> will work on tasks that result in the CREATED state with PID 0.
(cherry picked from commit 80839f11e2ea6759eed4b5e616d65cb59258a5f3)

[release/1.6] allow client to remove created tasks with PID 0

---

go.mod
go.sum
integration/client/go.mod
integration/client/go.sum
vendor/github.com/Microsoft/hcsshim/internal/cow/cow.go
vendor/github.com/Microsoft/hcsshim/internal/hcs/system.go
vendor/modules.txt

This bumps shim tag to include a fix from [microsoft/hcsshim @ 619117bc0844a5d3e9e29f3a24303b7bce5ab9d0](https://github.com/microsoft/hcsshim/commit/619117bc0844a5d3e9e29f3a24303b7bce5ab9d0)
The change log can be viewed [here](https://github.com/microsoft/hcsshim/compare/v0.8.24...v0.8.25)
Signed-off-by: Kirtana Ashok <Kirtana.Ashok@microsoft.com>

[release/1.5] go.mod: Bump hcsshim to v0.8.25

---

contrib/gce/configure.sh

cherry pick #7771 (not clean) 
add support to fetch and download containerd tarball from GCS buckets that require authentication.
GCS_BUCKET_TOKEN should have read access to the bucket from which artifacts are to be fetched. The token is expected to be present in the instance metadata of the VM, similar to other node environment variables
To use this in tests from kubernetes, a new node env can be added as follows [here](https://github.com/kubernetes/test-infra/blob/master/config/jobs/containerd/containerd/containerd-presubmit-jobs.yaml#L182). `<your_gcs_bucket_token>` can be fetched from a secret or from an env.
```
-node-env=GCS_BUCKET_TOKEN=<your_gcs_bucket_token>
```

[release/1.6] support fetching containerd from non public GCS buckets

---

releases/v1.6.13.toml
version/version.go

----
containerd 1.6.13
Welcome to the v1.6.13 release of containerd!
The thirteenth patch release for containerd 1.6 contains a various fixes and updates.
* **Update overlay snapshotter to check for tmpfs when evaluating usage of userxattr** ([#7788](https://github.com/containerd/containerd/pull/7788))
* **Update hcsschim to v0.9.6 to fix resource leak on exec** ([#7808](https://github.com/containerd/containerd/pull/7808))
* **Make swapping disabled with memory limit in CRI plugin** ([#7815](https://github.com/containerd/containerd/pull/7815))
* **Allow clients to remove created tasks with PID 0** ([#7816](https://github.com/containerd/containerd/pull/7816))
* **Fix concurrent map iteration and map write in CRI port forwarding** …

[release/1.6] Prepare release notes for v1.6.13

---

pkg/cri/sbserver/helpers.go
pkg/cri/sbserver/restart.go
pkg/cri/sbserver/sandbox_portforward_linux.go
pkg/cri/sbserver/sandbox_run.go
pkg/cri/sbserver/sandbox_status.go
pkg/cri/server/helpers.go
pkg/cri/server/restart.go
pkg/cri/server/sandbox_portforward_linux.go
pkg/cri/server/sandbox_run.go
pkg/cri/server/sandbox_status.go

We do a ton of host networking checks around the CRI plugin, all mainly doing the same thing of checking the different quirks on various platforms (for windows are we a HostProcess pod, for linux is namespace mode the right thing, darwin doesn't have CNI support etc.) which could all be bundled up into a small helper that can be re-used.

CRI: Add host networking helper

---

contrib/gce/configure.sh

Reverts containerd/containerd#7823
The changes is causing continuous failure in [containerd-node-e2e-1.6](https://testgrid.k8s.io/sig-node-containerd#containerd-node-e2e-1.6) and [containerd-node-e2e-features-1.6](https://testgrid.k8s.io/sig-node-containerd#containerd-node-e2e-features-1.6), because the actual blob is not getting downloaded as per [logs](https://storage.googleapis.com/kubernetes-jenkins/logs/ci-containerd-node-e2e-1-6/1603606906058838016/artifacts/tmp-node-e2e-3d5a02a8-ubuntu-gke-2204-1-24-v20220623/containerd-installation.log)

Revert "[release/1.6] support fetching containerd from non public GCS buckets"

---

go.mod
go.sum
integration/client/go.mod
integration/client/go.sum
pkg/cri/opts/spec_linux.go
vendor/github.com/containerd/cgroups/README.md
vendor/github.com/containerd/cgroups/Vagrantfile
vendor/github.com/containerd/cgroups/utils.go
vendor/github.com/containerd/cgroups/v2/manager.go
vendor/github.com/containerd/cgroups/v2/memory.go
vendor/github.com/containerd/cgroups/v2/utils.go
vendor/modules.txt

Cherry-pick #7836
Skip automatic `if swapLimit == 0 { s.Linux.Resources.Memory.Swap = &limit }` when the swap controller is missing. (default on Ubuntu 20.04)
Fix issue 7828 (regression in PR 7783 "cri: make swapping disabled with memory limit")
(cherry picked from commit 41575038819551c255ea2385dfe6c63cb7048dca)

[release/1.6] cri: fix `memory.memsw.limit_in_bytes: no such file or directory`

---

releases/v1.6.14.toml
version/version.go

After #7838 
Generated Release Notes
----
containerd 1.6.14
Welcome to the v1.6.14 release of containerd!
The fourteenth patch release for containerd 1.6 fixes a regression in the CRI plugin related to swap
* **Fix `memory.memsw.limit_in_bytes: no such file or directory` error in CRI plugin** ([#7838](https://github.com/containerd/containerd/pull/7838))
* Akhil Mohan
* Kazuyoshi Kato
<details><summary>3 commits</summary>
<p>
* [`1347d7c87`](https://github.com/containerd/containerd/commit/1347d7c87b01fb27b44a8c3f16b1e8c18ca656bc) Prepare release notes for v1.6.14
* Revert "[release/1.6] support fetching containerd from …

Prepare release notes for v1.6.14

---

snapshots/devmapper/snapshotter.go
snapshots/overlay/overlay.go
snapshots/storage/metastore.go

Most snapshotters end up manually handling the rollback logic, either by calling `t.Rollback()` in every failure path, setting up a custom defer func to log on certain errors, or just deferring `t.Rollback()` even for `snapshotter.Commit()` which *will* cause `t.Rollback()` to return an error afaict, but it's just never checked and luckily bolt handles this alright...
The devmapper snapshotter has a solution to this which is to have a method that starts either a read-only or writable transaction inside the method, and you pass in a callback to do your bidding. Any failures are rolled back, and if it's a writable transaction the method will handle the commit for you. This seems like the right model to me, it removes the burden from the snapshot author to remember to either defer/call …

metastore: Add WithTransaction convenience method

---

integration/client/snapshot_test.go
snapshots/overlay/overlay_test.go
snapshots/testsuite/issues.go
snapshots/testsuite/testsuite.go

One of the cases wouldn't work on overlayfs, but other cases and/or
snapshotters should be tested.

Enable checkRename test

---

integration/restart_test.go
pkg/cri/server/sandbox_run.go

Fixes https://github.com/containerd/containerd/issues/7843
Due to when we were updating the pod sandboxes underlying container
object, the pointer to the sandbox would have the right info, but
the on-disk representation of the data was behind. This would cause
the data returned from loading any sandboxes after a restart to have
no CNI result or IP information for the pod.
This change does an additional update to the on-disk container info
right after we invoke the CNI plugin so the metadata for the CNI result
and other networking information is properly flushed to disk.
I think RunPodSandbox is annoyingly hairy.. It's kind of scary how even the smallest refactorings in this code can cause regressions that aren't immediately noticeable, and are even harder to catch in review

CRI: Fix no CNI info for pod sandbox on restart

---

integration/restart_test.go
pkg/cri/server/sandbox_run.go

🍒pick: 3ee6dd5c1bca441d1ec4988cbaebadbfbcfde525
Due to when we were updating the pod sandboxes underlying container object, the pointer to the sandbox would have the right info, but the on-disk representation of the data was behind. This would cause the data returned from loading any sandboxes after a restart to have no CNI result or IP information for the pod.
This change does an additional update to the on-disk container info right after we invoke the CNI plugin so the metadata for the CNI result and other networking information is properly flushed to disk.

[release/1.6] CRI: Fix no CNI info for pod sandbox on restart

---

integration/restart_test.go
pkg/cri/server/sandbox_run.go

🍒pick: 3ee6dd5c1bca441d1ec4988cbaebadbfbcfde525
Due to when we were updating the pod sandboxes underlying container object, the pointer to the sandbox would have the right info, but the on-disk representation of the data was behind. This would cause the data returned from loading any sandboxes after a restart to have no CNI result or IP information for the pod.
This change does an additional update to the on-disk container info right after we invoke the CNI plugin so the metadata for the CNI result and other networking information is properly flushed to disk.

[release/1.5] CRI: Fix no CNI info for pod sandbox on restart

---

platforms/cpuinfo.go
platforms/cpuinfo_linux.go
platforms/cpuinfo_linux_test.go
platforms/cpuinfo_other.go
platforms/database.go

This PR is to fix cpu architecture detection issues [#4109](https://github.com/containerd/containerd/issues/4109), [#21](https://github.com/uraimo/run-on-arch-action/issues/21), [#1146](https://github.com/docker/for-linux/issues/1146) when images/containers in ARM arch were built/executed on x86 host. The root cause of the issue is the getCPUVariant function looks for  "Cpu architecture" field in /proc/cpuinfo to determine the actual ARM variant. The function will fail if the ARM containers/images ran in a user-mode emulated environment(like qemu) on a x86 host whose /proc/cpuinfo doesn't have "Cpu architecture" field and whose content is shared with ARM containers. 
The PR adds a fall back func to get cpu variant from **_uname machine field_** through a system call if the previous method …

Fix cpu architecture detection issue on linux/arm

---

.github/workflows/ci.yml
script/critest.sh

It was assuming containerd was ready right after starting.
But it depends GitHub actions' performance.
In addition to that, this commit extracts the script from ci.yml.

Check containerd's readiness before calling critest

---

labels/validate.go
labels/validate_test.go

Like stargz and nydus remote snapshotter, some snapshots lables are introduced and passed to snapshotter from containerd automatically. The label keys' lengths are all longer than 10. Most of them are around 40-50 chars.
The limitation of 10 characters makes it harder to debug what label is not appropriate. So we'd better print more of the wrong label.
Signed-off-by: Changwei Ge <gechangwei@bytedance.com>

image/label: print more characters of label keys

---

pkg/unpack/unpacker.go

Avoid using canceled context in unpacker cleanup

---

pkg/cri/sbserver/metrics.go
pkg/cri/sbserver/sandbox_run.go
pkg/cri/sbserver/sandbox_stop.go
pkg/cri/sbserver/update_runtime_config.go
pkg/cri/server/metrics.go
pkg/cri/server/sandbox_run.go
pkg/cri/server/sandbox_stop.go
pkg/cri/server/update_runtime_config.go

Add network plugin metrics.
The metrics are the same that were used in dockershim/kubelet until it was deprecated in kubernetes 1.23
https://github.com/kubernetes/kubernetes/blob/release-1.23/pkg/kubelet/dockershim/network/metrics/metrics.go
Fixes: https://github.com/containerd/containerd/issues/7801
Signed-off-by: Antonio Ojea <aojea@google.com>

add network plugin metrics

---

cmd/ctr/commands/run/run_windows.go

related pr: https://github.com/containerd/containerd/pull/6670
Keep the same extra information settings as in unix:
https://github.com/containerd/containerd/blob/6c8c4271661d658c381a97cebd53e3b382bb17dd/cmd/ctr/commands/run/run_unix.go#L242-L244

fix `ctr tasks kill` does not remove cni network under windows

---

oci/spec_opts_test.go
snapshots/devmapper/metadata.go

Reused define error in package 'errdefs' , like ```errdefs.ErrNotFound and errdefs.ErrAlreadyExists, errdefs.ErrNotImplemented```

Reused errdefs define error

---

oci/spec_opts.go
pkg/cri/sbserver/container_create_test.go
pkg/cri/server/container_create_test.go

A domainname field was recently added to the OCI spec. Prior to this folks would need to set this with a sysctl, but now runtimes should be able to setdomainname(2). There's an [open change to runc](https://github.com/opencontainers/runc/pull/3600) at the moment to add support for this so I've just left testing as a couple spec validations in CRI until that's in and usable.

oci: Add WithDomainname

---

remotes/docker/resolver.go

Use defer to close `resp.Body` within a double loop will cause a resource leak.

Fix incorrect defer usage and refactor judgement

---

pkg/cri/sbserver/service.go

Like [pkg/cri/server/service.go](https://github.com/containerd/containerd/pull/7165/commits) commit , I have no idea why not commit this one, like ```pkg/cri/sbserver/service.go ``` 
They may be the same logic..
:cold_sweat::cold_sweat:
If mine understanding is wrong , please tell me...

CRI sbserver: Prevent server reuse after Shutdown

---

contrib/fuzz/oss_fuzz_build.sh

As go.mod import runc 1.1.4 , So change the ```contrib/fuzz/oss_fuzz_build.sh``` to follow branch 1.1

make runc 1.1 for oss_fuzz_build.sh

---

RELEASES.md

According to https://github.com/kubernetes/kubernetes/pull/110618, v1.26 removed cri v1alpha2 support

add kube v1.26: remove v1alph2 cri support

---

client.go
container_opts.go
integration/main_test.go
integration/pod_userns_linux_test.go
pkg/cri/opts/spec_linux.go
pkg/cri/sbserver/container_create_linux.go
pkg/cri/server/container_create.go
pkg/cri/server/container_create_linux.go
pkg/cri/server/container_create_linux_test.go
pkg/cri/server/container_create_other.go
pkg/cri/server/container_create_windows.go
pkg/cri/server/helpers_linux.go
pkg/cri/server/sandbox_run.go
pkg/cri/server/sandbox_run_linux.go
pkg/cri/server/sandbox_run_linux_test.go
pkg/cri/server/sandbox_run_other.go
pkg/cri/server/sandbox_run_windows.go
pkg/netns/netns_linux.go
pkg/netns/netns_other.go
pkg/netns/netns_windows.go
snapshots/snapshotter.go
snapshotter_opts_unix.go
snapshotter_opts_windows.go

Hi!
This PR implements support for user namespace in Kubernetes pods. I'm opening the PR to see if you think this approach is sound, I'll add tests later, of course, but don't need to wait on that to see if this direction makes sense.
The 3 subitems listed in #7063 are solved in some way here, but not all possible solutions are implemented. In particular:
* The netns problem: it is solved in the first commit (Let OCI runtime create netns when userns is used) and, as requested by Mike Brown in a community meeting, I left intact the code-path that are used today.
* Ownership of the rootfs: three possible solutions are listed there. I chose just to take the commits from PR #7310, that uses a chown and adds the notion of capabilities, to say if some snapshotter supports idmap mounts (support …

Add support for user namespaces in stateless pods (KEP-127)

---

pkg/cri/server/container_create_linux_test.go

This is the first follow-up PR that after #7679 is merged. 
This was suggested here:
https://github.com/containerd/containerd/pull/7679#discussion_r1058171608
Signed-off-by: Rodrigo Campos <rodrigoca@microsoft.com>

cri: Shadow variables to avoid t.Parallel() issues

---

cmd/ctr/commands/content/content.go

The current `ctr content list` will print the labels in random order due to the map, and the result will be different each time it is executed, which is inconvenient to use.
Now the labels are sorted to ensure that the result is the same each time

`ctr contents ls` sorts the labels of the content

---

pkg/cri/server/container_create_linux.go
pkg/cri/server/container_create_linux_test.go
pkg/cri/server/helpers_linux.go

This is a follow-up to address one item of this comment by @fuweid: https://github.com/containerd/containerd/pull/7679#pullrequestreview-1231373767
The first commit fixes an issue running the tests (assert vs require, so the function result can be nil by mistake instead of failing early).
The second commit is the follow-up itself. I didn't use reflect, as it _might_ be too slow to use on the container creation path. But this means we need to update sameUsernsConfig() if the runtime.UserNamespace type changes. Let me know if you prefer to use reflect here.
The third commit just removes a variable that is not really helpful. It is a cosmetic change, no functional change.

Validate userns container config is consistent with sandbox userns config

---

integration/images/image_list.go

Saw rate limit errors locally (not on CI)

integration/images: switch away from Docker Hub to avoid rate limit

---

Vagrantfile

rootless overlayfs is compatible with SELinux since kernel 5.13

Vagrantfile: install-rootless-podman: remove `setenforce 0`

---

integration/common.go

[release/1.6] integration/images: switch away from Docker Hub to avoid rate limit

---

metadata/db.go
metadata/gc.go
metadata/gc_test.go
metadata/plugin/plugin.go
metadata/snapshot.go
services/snapshots/snapshotters.go

Removes the snapshot event publishing from the snapshot service.
Cleans up metadata plugin registration into separate packages.
Adds an option to metadata db to add a publisher. Adds event
publishing to prepare, commit, and remove snapshot operations.
Adds remove snapshot event to garbage collection.
Adds snapshotter field to snapshot events
----
This is useful for snapshot caches which attempt to track current snapshots based on creation and deletion events. Most snapshots are not removed through the API, but through garbage collection. The end goal being the removal of the inefficient snapshot syncer in the CRI plugin

Move snapshot event publishing into metadata store

---

pkg/cri/server/service_linux.go
pkg/cri/server/service_other.go
pkg/cri/server/service_windows.go

Comments in initPlatform for Windows states that the options were Linux specific. Additionally properly wrap an error after trying to setup CDI on Linux.

CRI: Comment cleanup/misc fixes

---

integration/container_update_resources_test.go

Fix #7890
Tested on Ubuntu 22.10, with swapon and swapoff:
```console
$ GITHUB_WORKSPACE="" ENABLE_CRI_SANDBOXES="" CONTAINERD_RUNTIME=io.containerd.runc.v2 FOCUS=TestUpdateContainerResources_Memory make cri-integration
...
=== RUN   TestUpdateContainerResources_MemorySwap
container_update_resources_test.go:161: Create a sandbox
INFO[0000] Using the following image list: {Alpine:docker.io/library/alpine:latest BusyBox:docker.io/library/busybox:latest Pause:registry.k8s.io/pause:3.8 ResourceConsumer:registry.k8s.io/e2e-test-images/resource-consumer:1.10 VolumeCopyUp:ghcr.io/containerd/volume-copy-up:2.1 VolumeOwnership:ghcr.io/containerd/volume-ownership:2.1}
main_test.go:663: Image "registry.k8s.io/pause:3.8" already exists, not pulling.
container_update_resources_test.go:174: Create a …
```

Fix TestUpdateContainerResources_Memory* on cgroup v2 hosts

---

Vagrantfile

SELinux has been enforcing since commit a7f24b29c20fa4c4257a8f5ea15922e8bb53450c (PR #4698, v1.5.0)

Vagrantfile: fix comments about SELinux

---

Vagrantfile

Fix the following error with VirtualBox:
```
VirtualBox Provider:
* The following settings shouldn't exist: disk
```

Vagrantfile: fix disk resize error with VirtualBox

---

cmd/ctr/commands/oci/oci.go

This adds in a simple flag to control what platform the spec it generates is for. Useful to easily get a glance at what's the default across platforms.
```shell
dcantah@dcantah:~/go/src/github.com/containerd/containerd/bin$ ./ctr oci spec --platform linux
{
"ociVersion": "1.0.2-dev",
"process": {
"user": {
"uid": 0,
"gid": 0
},
"cwd": "/",
"capabilities": {
"bounding": [
"CAP_CHOWN",
"CAP_DAC_OVERRIDE",
"CAP_FSETID",
"CAP_FOWNER",
"CAP_MKNOD",
"CAP_NET_RAW",
"CAP_SETGID",
"CAP_SETUID",
"CAP_SETFCAP",
"CAP_SETPCAP",
"CAP_NET_BIND_SERVICE",
"CAP_SYS_CHROOT",
"CAP_KILL",
"CAP_AUDIT_WRITE"
],
"effective": [
"CAP_CHOWN",
"CAP_DAC_OVERRIDE",
"CAP_FSETID",
"CAP_FOWNER",
"CAP_MKNOD",
"CAP_NET_RAW",
"CAP_SETGID",
"CAP_SETUID",
"CAP_SETFCAP",
"CAP_SETPCAP",
"CAP_NET_BIND_SERVICE",
"CAP_SYS_CHROOT", …
```

ctr: Add platform flag to 'oci spec' command

---

.golangci.yml
cio/io_unix_test.go
cmd/containerd-stress/density.go
content/local/store.go
errdefs/grpc_test.go
images/converter/default.go
metadata/db.go
pkg/cap/cap_linux_test.go
pkg/cri/sbserver/container_create.go
pkg/cri/sbserver/instrumented_service.go
pkg/cri/sbserver/podsandbox/helpers.go
pkg/cri/server/container_create.go
pkg/cri/server/instrumented_service.go
reference/docker/normalize.go

`dupword` linter prevents duplicated words in the source code.
This PR updates `.golangci.yml` and removes some duplicates.

Enable dupword linter

---

.github/workflows/ci.yml

Previously the project-checks action was failing sometimes due to hitting GitHub API rate limits. Since no token was supplied, the rate limits were only 60 requests/hour keyed off the IP address of the runner.
Now, passing GITHUB_TOKEN secret through to project-checks, we have a limit of 1000 requests/hour for the whole repo. This should alleviate the rate limits that were being seen.
I believe it is safe to pass this secret as project-checks is also owned by the containerd organization. The secret is also scoped to the actions run, and is invalidated upon completion.
project-checks version is also updated to the version that supports repo-access-token input.

CI: Pass GITHUB_TOKEN to containerd/project-checks

---

docs/tracing.md

It should be "daemon"
Signed-off-by: Changwei Ge <gechangwei@bytedance.com>

docs: fix a typo in tracing documentation

---

contrib/Dockerfile.test
contrib/Dockerfile.test.d/docker-entrypoint.sh

For ease of running the entire tests locally
```
cd contrib
docker build -t containerd-test -f Dockerfile.test --target integration ..
docker run --privileged containerd-test
docker build -t containerd-test -f Dockerfile.test --target cri-integration ..
docker run --privileged --sysctl net.ipv6.conf.all.disable_ipv6=0 containerd-test
docker build -t containerd-test -f Dockerfile.test --target critest ..
docker run --privileged --sysctl net.ipv6.conf.all.disable_ipv6=0 containerd-test
```
Tested on Ubuntu 22.10 (amd64, cgroup v2).
Known issues:
- cri-integration and critest: require `--sysctl net.ipv6.conf.all.disable_ipv6=0` to avoid
errors like `failed to set bridge addr: could not add IP address to "cni0": permission denied`
- critest: Often fails due to Docker Hub rate limits. Fix is …

contrib/Dockerfile.test: add "integration", "cri-integration", "critest" stages

---

.cirrus.yml
Vagrantfile
integration/container_stats_test.go
integration/main_test.go
integration/nri_test.go
integration/volume_copy_up_test.go
integration/volume_copy_up_unix_test.go

Fix #7889 
- - -
The snapshot size is no longer tested in `container_stats_test.go`, due to
- https://github.com/containerd/containerd/issues/7909
The name of the GID 65534 differs across distros.
("nogroup" on Debian derivatives, "nobody" on Red Hat derivatives)
Enable SELinux relabeling
SELinux relabeling does not seem implemented for NRI yet
https://github.com/containerd/nri/pull/16#discussion_r1060654853

Cirrus CI (Fedora 37, Rocky 8): enable cri-integration

---

.mailmap
releases/v1.7.0-beta.toml
version/version.go

Generated Release Notes (truncated, see full generates notes [here](https://gist.github.com/dmcgowan/18c05d167f0c0c3fe7d1d8839e6ec932))
-----
Welcome to the v1.7.0-beta.2 release of containerd!  
The previous 1.6 release has also become a long term stable release for users who …

Prepare release notes for v1.7.0-beta.2

---

services/streaming/service.go
transfer.go

Prevent a race where a client may attempt to use a stream before it is registered.
Addresses #7885

Fix race between stream registration and use

---

.github/workflows/ci.yml

Backport #7913
----
Previously the project-checks action was failing sometimes due to hitting GitHub API rate limits. Since no token was supplied, the rate limits were only 60 requests/hour keyed off the IP address of the runner.
Now, passing GITHUB_TOKEN secret through to project-checks, we have a limit of 1000 requests/hour for the whole repo. This should alleviate the rate limits that were being seen.
I believe it is safe to pass this secret as project-checks is also owned by the containerd organization. The secret is also scoped to the actions run, and is invalidated upon completion.
project-checks version is also updated to the version that supports repo-access-token input. …

[release/1.6] CI: Pass GITHUB_TOKEN to containerd/project-checks

---

metadata/db.go
pkg/cleanup/context.go
pkg/cleanup/context_test.go
pkg/unpack/unpacker.go
rootfs/diff.go
runtime/v1/linux/bundle.go
runtime/v1/linux/runtime.go
runtime/v2/manager.go
runtime/v2/shim.go
runtime/v2/shim_load.go

Provides a couple helpers functions that provide a background context for running cleanup jobs while preserving the original context values. These new contexts will not inherit any errors or cancellations from the original context.

Add cleanup package for context management during cleanup

---

releases/v1.6.15.toml
version/version.go

Generate notes
----
containerd 1.6.15
Welcome to the v1.6.15 release of containerd!
The fifteenth patch release for containerd 1.6 fixes an issue with CNI in the CRI plugin
* **Fix no CNI info for pod sandbox on restart in CRI plugin** ([#7848](https://github.com/containerd/containerd/pull/7848))
* Akihiro Suda
* Danny Canter
* Wei Fu
<details><summary>5 commits</summary>
<p>
* [`883899eae`](https://github.com/containerd/containerd/commit/883899eaed4ab95e3c415b5937438b4439796bfc) Prepare release notes for v1.6.15
* [release/1.6] integration/images: switch away from Docker Hub to avoid rate limit …

[release/1.6] Prepare release notes for v1.6.15

---

docs/content-flow.md

The digest of the image [redis:5.0.9](https://hub.docker.com/layers/library/redis/5.0.9/images/sha256-9bb13890319dc01e5f8a4d3d0c4c72685654d682d568350fd38a02b1d70aee6b) has changed and is now updated to the latest digest.
And content labels have also changed, the descriptions of these labels will be updated

docs/content-flow: update the description of the content labels 

---

plugin/plugin_test.go

Tracing was moved to plugin in PR #6001.
Add tracing related plugins to the plugin registration test. 
Signed-off-by: Tony Fang <nenghui.fang@gmail.com>

Add tracing plugin test

---

archive/tar_test.go

The previous test wasn't highly meaningful because 5 * (100 * Millisecond) is smaller than a second.

archive: improve TestSourceDateEpoch

---

go.mod
go.sum
integration/client/go.mod
integration/client/go.sum
vendor/github.com/pelletier/go-toml/README.md
vendor/github.com/pelletier/go-toml/SECURITY.md
vendor/github.com/pelletier/go-toml/marshal.go
vendor/github.com/pelletier/go-toml/parser.go
vendor/github.com/pelletier/go-toml/toml.go
vendor/modules.txt

Full diff: https://github.com/pelletier/go-toml/compare/v1.9.3...v1.9.5
This contains https://github.com/pelletier/go-toml/commit/fed1464066413075eac02cd4dc368b5221845541.  Without that fix, an invalid config.toml file can cause a panic.
v1.9.5 is the last release prior to v2.0.0, which is a larger change.

mod: update github.com/pelletier/go-toml@v1.9.5

---

integration/container_stats_test.go

Fix #7936  - random failures on Windows CRI Integration test TestContainerConsumedStats(context timeout).
This PR is to reapply the previous [commit](https://github.com/containerd/containerd/pull/7892/commits/76d68b080ef69407129a5925ae5b97f1c9010dea) change on [TestContainerConsumedStats](https://github.com/containerd/containerd/pull/7892/commits/76d68b080ef69407129a5925ae5b97f1c9010dea#diff-2885e285816541779f8967567923949ba6195e3a517479cef9813c813ac63d1dL106) back to Windows platform. 
Signed-off-by: Tony Fang <nenghui.fang@gmail.com>

Fix Flaky Windows CRI Integration test on TestContainerConsumedStats

---

pkg/cri/opts/spec_linux.go
pkg/cri/sbserver/container_update_resources_linux_test.go
pkg/cri/server/container_update_resources_linux_test.go

Fixes #7918 
Tested on Ubuntu 20.04 w/o swap controller:
```
$ stat -fc %T /sys/fs/cgroup/
tmpfs
$ la -la /sys/fs/cgroup/memory/memory.memsw.limit_in_bytes
ls: cannot access '/sys/fs/cgroup/memory/memory.memsw.limit_in_bytes': No such file or directory
$  go test -v ./pkg/cri/sbserver/ -run TestUpdateOCILinuxResource
=== RUN   TestUpdateOCILinuxResource
=== RUN   TestUpdateOCILinuxResource/should_be_able_to_patch_the_unified_map
=== RUN   TestUpdateOCILinuxResource/should_be_able_to_update_each_resource
=== RUN   TestUpdateOCILinuxResource/should_skip_empty_fields
=== RUN   TestUpdateOCILinuxResource/should_be_able_to_fill_empty_fields
--- PASS: TestUpdateOCILinuxResource (0.00s)
--- PASS: TestUpdateOCILinuxResource/should_be_able_to_patch_the_unified_map (0.00s)
--- PASS: …
```

cri: Fix TestUpdateOCILinuxResource for host w/o swap controller

---

.github/workflows/build-test-images.yml
.github/workflows/ci.yml
.github/workflows/codeql.yml
.github/workflows/images.yml
.github/workflows/nightly.yml
.github/workflows/release.yml
Vagrantfile
contrib/Dockerfile.test
contrib/fuzz/oss_fuzz_build.sh
script/setup/prepare_env_windows.ps1

[release go1.19](https://golang.google.cn/doc/devel/release#go1.19)
```
go1.18.10 (released 2023-01-10) includes fixes to cgo, the compiler, the linker, and the crypto/x509, net/http, and syscall packages. See the [Go 1.18.10 milestone](https://github.com/golang/go/issues?q=milestone%3AGo1.18.10+label%3ACherryPickApproved) on our issue tracker for details.
```
and 
```
go1.19.5 (released 2023-01-10) includes fixes to the compiler, the linker, and the crypto/x509, net/http, sync/atomic, and syscall packages. See the [Go 1.19.5 milestone](https://github.com/golang/go/issues?q=milestone%3AGo1.19.5+label%3ACherryPickApproved) on our issue tracker for details.
```

update to go1.19.5, go1.18.10

---

pkg/cri/sbserver/container_create.go
pkg/cri/sbserver/container_create_test.go
pkg/cri/sbserver/podsandbox/controller.go
platforms/platforms.go
sandbox/controller.go
sandbox/proxy/controller.go

Follow up for https://github.com/containerd/containerd/pull/7928
We should expose Go types in interfaces instead of using generated API.
This PR replaces `types.Platform` with specs `Platform`.
I will follow up with `Controller` changes separately.

Use specs Platform instead of generated API

---

oci/spec.go
oci/spec_opts_test.go
oci/spec_test.go
pkg/cri/opts/spec_darwin_opts.go
pkg/cri/sbserver/container_create.go
pkg/cri/sbserver/container_create_other_test.go
pkg/cri/sbserver/container_create_test.go

Adds a very basic spec for Darwin platform and mounts passed from CRI (mostly useful for VMs on Darwin)

Add basic spec and mounts for Darwin

---

metadata/gc.go

Use local variable for rt when iterating collectors
When iterating collectors, rt should be stored in a local variable. Otherwise `gcnode` could contain random types.
In the sample debugging output below, the rt value should be 11 in my case, but it has value 8 instead, which is the stream resource.
```
time="2023-01-13T21:28:06.129285403Z" level=debug msg="[GC] key: containerd.io/gc.ref.network, ks: containerd.io/gc.ref.network.cni-loopback/lo, vs: default/cni-loopback/8ddd3dce5cb55a7e32c27d2b69878c3fd9b946bdc73749a081621bf91e47b90f/lo, rt: 8"
```

use local variable for rt when iterating collectors

---

.github/workflows/release/Dockerfile

A build was hanging with `UBUNTU_VERSION=20.04`
```
...
=> [base 3/5] RUN APT-GET update &&  apt-get install -y dpkg-dev git make pkg-config                                                                            73.2s
=> => # questions will narrow this down by presenting a list of cities, representing
=> => # the time zones in which they are located.
=> => #   1. Africa      4. Australia  7. Atlantic  10. Pacific  13. Etc
=> => #   2. America     5. Arctic     8. Europe    11. SystemV
=> => #   3. Antarctica  6. Asia       9. Indian    12. US
=> => # Geographic area:
...
```

release/Dockerfile: set DEBIAN_FRONTEND=noninteractive

---

pkg/cri/sbserver/container_create_linux_test.go
pkg/cri/sbserver/helpers.go
pkg/cri/sbserver/image_pull.go
pkg/cri/sbserver/sandbox_run.go

Backport the following CRI PRs to sandboxed CRI:
- https://github.com/containerd/containerd/pull/7882 (the majority of code already carried by https://github.com/containerd/containerd/pull/7928)
- https://github.com/containerd/containerd/pull/7685
- https://github.com/containerd/containerd/pull/7661
- https://github.com/containerd/containerd/pull/7393

Backport changes to sandboxed CRI

---

services/namespaces/local.go

Keep same with delete namespace
https://github.com/containerd/containerd/blob/main/services/namespaces/local.go#L201-L211

fix incorrect namespace of event when create/update namespace

---

remotes/docker/pusher.go
remotes/docker/pusher_test.go

:bug: Fixes https://github.com/containerd/containerd/issues/7972
In the refactor from #6995, the error handling was substantially reworked, and changed the types of errors returned - this caused issues in retry logic downstream in BuildKit (see https://github.com/docker/build-push-action/issues/761). BuildKit uses this error result from this function [to determine whether to retry the push or not](https://github.com/jedevc/buildkit/blob/40bc1b316f6ce2be69ed522dc6d531ef1d3323e8/util/resolver/retryhandler/retry.go#L54-L76).
Notably, in the case of a network error, instead of propagating the error through to return from `pushWriter.Write` (as previously), it would be propagated through to `pushWriter.Commit` - however, this is too late, since we've already closed the `io.Pipe` by the time we …

pushWriter: correctly propagate errors

---

remotes/docker/pusher.go
remotes/docker/pusher_test.go

- backport of https://github.com/containerd/containerd/pull/7985
- fixes https://github.com/containerd/containerd/issues/7972
- relates to https://github.com/containerd/containerd/pull/6995
- relates to https://github.com/docker/build-push-action/issues/761
In the refactor from 926b9c72f61b5be6bf8d952512f1d0932fbaf898, the error handling was substantially reworked, and changed the types of errors returned.
Notably, in the case of a network error, instead of propogating the error through to return from pushWriter.Write (as previously), it would be propagated through to pushWriter.Commit - however, this is too late, since we've already closed the io.Pipe by the time we would have reached this function. Therefore, we get the generic error message  "io: read/write on closed pipe" for *every …

[release/1.6 backport] pushWriter: correctly propagate errors

---

pkg/cri/sbserver/helpers.go
pkg/cri/server/helpers.go
pkg/cri/store/container/status.go

- relates to https://github.com/containerd/containerd/pull/7661/files#r1085825940
Some of this code was originally added in b7b1200dd3716c88312f6ce8fafdb2c2881edb29, which likely meant to initialize the slice with a length to reduce allocations, however, instead of initializing with a zero-length and a capacity, it initialized the slice with a fixed length, which was corrected in commit 0c63c42f8183d13c2c106c01f5bb3560d39b3295.
This patch initializes the slice with a zero-length and expected capacity.

pkg/cri: optimize slice initialization

---

.github/workflows/release/Dockerfile

- backport of https://github.com/containerd/containerd/pull/7969
A build was hanging with `UBUNTU_VERSION=20.04`
```
...
=> [base 3/5] RUN APT-GET update &&  apt-get install -y dpkg-dev git make pkg-config                                                                            73.2s
=> => # questions will narrow this down by presenting a list of cities, representing
=> => # the time zones in which they are located.
=> => #   1. Africa      4. Australia  7. Atlantic  10. Pacific  13. Etc
=> => #   2. America     5. Arctic     8. Europe    11. SystemV
=> => #   3. Antarctica  6. Asia       9. Indian    12. US
=> => # Geographic area:
...
```
(cherry picked from commit d1e1a164604ef900a067d9b293b791d5e0daf75f)
Signed-off-by: …

[release/1.6 backport] release/Dockerfile: set DEBIAN_FRONTEND=noninteractive

---

.github/workflows/build-test-images.yml
.github/workflows/ci.yml
.github/workflows/codeql.yml
.github/workflows/images.yml
.github/workflows/nightly.yml
.github/workflows/release.yml
Vagrantfile
contrib/Dockerfile.test
script/setup/prepare_env_windows.ps1

go1.18.10 (released 2023-01-10) includes fixes to cgo, the compiler, the linker, and the crypto/x509, net/http, and syscall packages. See the Go 1.18.10 milestone on the issue tracker for details:
https://github.com/golang/go/issues?q=milestone%3AGo1.18.10+label%3ACherryPickApproved
full diff: https://github.com/golang/go/compare/go1.18.9...go1.18.10

[release/1.6] update to go1.18.10

---

.github/workflows/ci.yml
.github/workflows/nightly.yml
.github/workflows/release.yml
Vagrantfile
contrib/Dockerfile.test

go1.18.10 (released 2023-01-10) includes fixes to cgo, the compiler, the linker, and the crypto/x509, net/http, and syscall packages. See the Go 1.18.10 milestone on the issue tracker for details:
https://github.com/golang/go/issues?q=milestone%3AGo1.18.10+label%3ACherryPickApproved
full diff: https://github.com/golang/go/compare/go1.18.9...go1.18.10

[release/1.5] update to go1.18.10

---

pkg/cri/server/helpers.go
pkg/cri/store/container/status.go

- backport of https://github.com/containerd/containerd/pull/7661
- (partial) backport of https://github.com/containerd/containerd/pull/7994 (the `sbserver` is not in the 1.6 branch)
In golang when copy a slice, if the slice is initialized with a desired length, then appending to it will cause the size double.
(cherry picked from commit 0c63c42f8183d13c2c106c01f5bb3560d39b3295)

[release/1.6 backport] Fix slice append error

---

.github/workflows/build-test-images.yml
.github/workflows/ci.yml
.github/workflows/codeql.yml
.github/workflows/images.yml
.github/workflows/nightly.yml
.github/workflows/release.yml
.github/workflows/windows-periodic-trigger.yml
.github/workflows/windows-periodic.yml

- partial backport of https://github.com/containerd/containerd/pull/7599 (some files are not in the release/1.6 branch)
(cherry picked from commit a270d6e8ae1a9575d21283bafc60967f6ed40d3f)

[release/1.6 backport] Harden GITHUB_TOKEN permissions

---

integration/container_update_resources_test.go
pkg/cri/opts/spec_linux.go
pkg/cri/server/container_update_resources_linux_test.go

backports of:
- (partial backport, as the sbserver is not in 1.6) https://github.com/containerd/containerd/pull/7946
- https://github.com/containerd/containerd/pull/7893

[release/1.6 backport] assorted test-fixes

---

remotes/docker/pusher.go
remotes/docker/pusher_test.go

- backport of https://github.com/containerd/containerd/pull/7985
- fixes https://github.com/containerd/containerd/issues/7972
- relates to https://github.com/containerd/containerd/pull/6995
In the refactor from 926b9c72f61b5be6bf8d952512f1d0932fbaf898, the error handling was substantially reworked, and changed the types of errors returned.
Notably, in the case of a network error, instead of propogating the error through to return from pushWriter.Write (as previously), it would be propagated through to pushWriter.Commit - however, this is too late, since we've already closed the io.Pipe by the time we would have reached this function. Therefore, we get the generic error message  "io: read/write on closed pipe" for *every network error*.
This patch corrects this behavior to ensure that the …

[release/1.5 backport] pushWriter: correctly propagate errors

---

snapshots/overlay/overlay.go

- backport of https://github.com/containerd/containerd/pull/6978
- relates to https://github.com/containerd/containerd/pull/5624
When upperdirLabel specified, overlay Update will throw tx closed error since Commit is invoked before GetInfo
(cherry picked from commit 9f9ebbd99103bb60b0b0b45be8d9520b8c047b44)

[release/1.6 backport] Fix tx closed error when upperdirlabel specified

---

integration/common.go

Backport https://github.com/containerd/containerd/pull/7888 via :cherries:-pick of https://github.com/containerd/containerd/pull/7900
(cherry picked from commit a5ea5935b7e65b189f893eca1e95e501a7aeb716)
(cherry picked from commit 0f4062c9be0155861a1907dd1e1fe54b38c1d5ac)
Signed-off-by: Samuel Karp <samuelkarp@google.com>

[release/1.5] integration/images: switch away from Docker Hub to avoid rate limit

---

releases/v1.7.0-beta.toml
version/version.go

----
containerd 1.7.0-beta.3
Welcome to the v1.7.0-beta.3 release of containerd!  
The previous 1.6 release has also become a long term stable release for users who prefer releases with mostly stability improvements and wish to wait a few releases for new …

Prepare release notes for v1.7.0-beta.3

---

releases/v1.5.17.toml
version/version.go

----
containerd 1.5.17
Welcome to the v1.5.17 release of containerd!
The seventeenth patch release for containerd 1.5 includes various fixes and updates.
* **Update shim to fail fast on dial error** ([#7953](https://github.com/containerd/containerd/pull/7953))
* **Fix no CNI info for pod sandbox on restart** ([#7849](https://github.com/containerd/containerd/pull/7849))
* **Fix push error propagation** ([#7998](https://github.com/containerd/containerd/pull/7998))
* Akihiro Suda
* Wei Fu
* Danny Canter
* Justin Chadwell
* Phil Estes
* Samuel Karp …

[release/1.5] Prepare release notes for v1.5.17

---

RELEASES.md

Update the release date to better coincide with Kubernetes 1.23 end of life and the containerd 1.7 release.

Update the EOL date for 1.5 release

---

releases/v1.6.16.toml
version/version.go

generated release notes
----
containerd 1.6.16
Welcome to the v1.6.16 release of containerd!
The sixteenth patch release for containerd 1.6 includes various bug fixes and updates.
* **Fix push error propagation** ([#7990](https://github.com/containerd/containerd/pull/7990))
* **Fix slice append error with HugepageLimits for Linux** ([#7995](https://github.com/containerd/containerd/pull/7995))
* **Update default seccomp profile for PKU and CAP_SYS_NICE** ([#8001](https://github.com/containerd/containerd/pull/8001))
* **Fix overlayfs error when upperdirlabel option is set** ([#8002](https://github.com/containerd/containerd/pull/8002))
* …

[release/1.6] Prepare v1.6.16

---

pkg/cri/server/metrics.go
pkg/cri/server/sandbox_run.go
pkg/cri/server/sandbox_stop.go
pkg/cri/server/update_runtime_config.go

Add network plugin metrics.
The metrics are the same that were used in dockershim/kubelet until it was deprecated in kubernetes 1.23
https://github.com/kubernetes/kubernetes/blob/release-1.23/pkg/kubelet/dockershim/network/metrics/metrics.go
Signed-off-by: Antonio Ojea <aojea@google.com>

[release/1.6] add network plugin metrics

---

.github/workflows/release.yml
.github/workflows/release/Dockerfile
releases/v1.7.0-beta.toml

Ubuntu 18.04 will reach its End of Standard Support in April 2023: https://wiki.ubuntu.com/Releases
By updating Ubuntu from 18.04 to 20.04, the dynamically-linked glibc version is bumped up from 2.27 to 2.31.
The dynamically linked containerd binary still seems to be compatible with CentOS 7 (glibc 2.17).
The runc binary in the `cri-containerd(-cni)-<VERSION>-linux-<ARCH>.tar.gz` bundle no longer works on CentOS 7, though, but this is acceptable, as the `cri-containerd(-cni)` bundle has been deprecated since containerd 1.6.
```
$ ldd /usr/local/sbin/runc
linux-vdso.so.1 =>  (0x00007fffee9c4000)
libpthread.so.0 => /lib64/libpthread.so.0 (0x00007eff48721000)
libseccomp.so.2 => /lib64/libseccomp.so.2 (0x00007eff484e0000)
libc.so.6 => /lib64/libc.so.6 (0x00007eff48112000) …
```

release: Ubuntu 18.04 -> 20.04 (glibc 2.27 -> 2.31)

---

integration/client/client_unix_test.go
integration/images/image_list.go

It is kind of race because `sleep 1s` is short live process.
See: https://github.com/containerd/containerd/issues/7965#issuecomment-1383218025
Fixes: #7965

deflake: TestContainerPids

---

runtime/v2/README.md
runtime/v2/binary.go

Noticed the cwd behavior noted for Windows also applies to FreeBSD now.
https://github.com/containerd/containerd/blob/f82ae8a9225728969b66926a7128d1aa3040a257/runtime/v2/binary.go#L154

runtime docs: Clarify delete cwd behavior

---

pkg/cri/sbserver/events.go
pkg/cri/sbserver/podsandbox/controller.go
pkg/cri/sbserver/podsandbox/sandbox_delete.go
pkg/cri/sbserver/podsandbox/sandbox_run.go
pkg/cri/sbserver/sandbox_remove.go
pkg/cri/sbserver/sandbox_run.go
pkg/cri/sbserver/service.go

We should not generate PLEG container events for sandboxes unless its `podsandbox` containers.

Move PLEG events for pause container under podsandbox package

---

pkg/cri/sbserver/cni_conf_syncer.go
pkg/cri/server/cni_conf_syncer.go

/etc/cni has to be readable for non-root users (0755), because /etc/cni/tuning/allowlist.conf is used for rootless mode too. This file was introduced in CNI plugins 1.2.0 (containernetworking/plugins#693), and its path is hard-coded.

cri: mkdir /etc/cni with 0755, not 0700

---

pkg/cri/server/cni_conf_syncer.go

Cherry-pick:
- #8020
(cherry pick was not clean, as the `sbserver` is missing in the `release/1.6` branch)
- - -
/etc/cni has to be readable for non-root users (0755), because /etc/cni/tuning/allowlist.conf is used for rootless mode too. This file was introduced in CNI plugins 1.2.0 (containernetworking/plugins PR 693), and its path is hard-coded.

[release/1.6] cri: mkdir /etc/cni with 0755, not 0700

---

cmd/ctr/commands/snapshots/snapshots.go
container.go
contrib/snapshotservice/service.go
diff.go
docs/snapshotters/README.md
mount/mount.go
mount/mount_freebsd.go
mount/mount_linux.go
mount/mount_linux_test.go
mount/mount_unix.go
mount/mount_unsupported.go
mount/mount_windows.go
mount/temp.go
pkg/process/init.go
runtime/v1/linux/runtime.go
runtime/v1/shim/service.go
runtime/v2/bundle.go
runtime/v2/runc/container.go
runtime/v2/runc/manager/manager_linux.go
runtime/v2/runc/v1/service.go
runtime/v2/shim.go
runtime/v2/shim_load.go
services/diff/local.go
services/snapshots/service.go
services/tasks/local.go
snapshots/proxy/proxy.go

Fixes #7839
---
- Add Target to mount.Mount
- Add UnmountAllRecursive to unmount deepest mount first for a list of mount.Mount.
- Add UnmountRecursive to unmount deepest mount first for a given target, using /proc/mountinfo.
Signed-off-by: Edgar Lee <edgarhinshunlee@gmail.com>

Use mount.Target to specify subdirectory of rootfs mount

---

integration/client/client_test.go
integration/client/go.mod
integration/client/go.sum
integration/client/tracing.go

This PR is to address #7493
This PR adds 
Integration test to tracing at client side on image pull following steps:
-   Create an in-memory exporter and global tracer provider
-   Pull image with client which should create spans
-   Check if there are spans in the exporter
Those steps can be used for other tracing related integration tests too.
Signed-off-by: Tony Fang <nhfang@amazon.com>

Add integration test to opentelemetry tracing on image pull

---

docs/getting-started.md

`*` was left out and therefore the `.\bin` directory is also copied over, other than only the files, while the following commands assume the files are copied to `$Env:ProgramFiles\ccontainerd`
Signed-off-by: Anthony Nandaa <profnandaa@gmail.com>

fix(docs): minor fix on the windows installation steps

---

go.mod
go.sum
integration/client/go.sum
vendor/github.com/containerd/nri/README.md
vendor/github.com/containerd/nri/pkg/adaptation/adaptation.go
vendor/github.com/containerd/nri/pkg/adaptation/plugin.go
vendor/github.com/containerd/nri/pkg/adaptation/plugin_linux.go
vendor/github.com/containerd/nri/pkg/adaptation/plugin_other.go
vendor/github.com/containerd/nri/pkg/net/socketpair_unix.go
vendor/github.com/containerd/nri/pkg/net/socketpair_windows.go
vendor/github.com/containerd/nri/pkg/runtime-tools/generate/helpers_linux.go
vendor/github.com/containerd/nri/pkg/runtime-tools/generate/helpers_other.go
vendor/modules.txt

Pull in NRI [commit b3cabdec0657](https://github.com/containerd/nri/commit/b3cabdec06578b193da387b1bee4fd23aea8808e) to fix a recently discovered panic/crash.

go.mod: update github.com/containerd/nri.

---

pkg/epoch/epoch.go

For determinism of human-readable string representation. e.g., "2023-01-10T12:34:56Z" vs "2023-01-10T21:34:56+09:00"

pkg/epoch: drop timezone

---

pkg/cri/server/image_pull.go
pkg/cri/server/image_pull_test.go
pkg/snapshotters/annotations.go
pkg/snapshotters/annotations_test.go

Now the user of remote snapshotter labels appended by CRI plugin is not only stargz-snapshotter but also several remote snapshotter implementations in the community. (There is also discussion to use them from non-snapshotter tool https://github.com/moby/moby/pull/44810)
- cvmfs-snapshotter: https://github.com/cvmfs/cvmfs/blob/cvmfs-2.10.0/snapshotter/cvmfs/cvmfs.go#L16-L24
- nydus-snapshotter: https://github.com/containerd/nydus-snapshotter/blob/v0.5.0/pkg/label/label.go#L10-L13
- soci-snapshotter: https://github.com/awslabs/soci-snapshotter/blob/714f1a971e676fada47cb4c983b4728d06bab309/service/cri.go#L45-L55
- overlaybd-snapshotter: https://github.com/containerd/accelerated-container-image/blob/0369b9a8b54d10bae575f4cafb323f28497b5330/pkg/snapshot/overlay.go#L117-L118
- …

Export remote snapshotter label handler

---

mount/mount_unix.go

This commit fixes the cleanup failure of containers with custom location of rootfs.
Recently `mount.UnmountAll` invocations have been relaced by [`mount.UnmountRecursive`](https://github.com/containerd/containerd/blob/e307f87971391efb47eef4487e93be4cfd36fe85/mount/mount_unix.go#L29). When `""`(empty path) is passed to `mount.UnmountAll`, it simply ignores that path and returns immediately without error. However, `mount.UnmountRecursive` accepts such argument and try to perform unmounting on the root directory. Containers with custom rootfs location cause invocations of `mount.UnmountRecursive` with `""`. https://github.com/containerd/containerd/blob/e307f87971391efb47eef4487e93be4cfd36fe85/pkg/process/init.go#L310
It results in cleanup failure of containers and unmounting of mountpoints …

Make argument validation of `mount.UnmountRecursive` compatible to `mount.UnmountAll`

---

pkg/cri/sbserver/sandbox_run.go

Wire up sandbox controller to sandbox exit monitor. This will make sure that pod sandbox status is up to date and kubelet will not retry stopping sandbox.

Fix sandbox exit monitor

---

go.mod
go.sum
integration/client/go.mod
integration/client/go.sum
vendor/github.com/Microsoft/hcsshim/.gitignore
vendor/modules.txt

This PR bumps hcsshim tag from v0.10.0-rc.4 to [v0.10.0-rc.5](https://github.com/microsoft/hcsshim/releases/tag/v0.10.0-rc.5). Ran go mod tidy/vendor.
The full changelog between v0.10.0-rc4...v0.10.0-rc5 can be seen [here](https://github.com/microsoft/hcsshim/compare/v0.10.0-rc.4...v0.10.0-rc.5).
Signed-off-by: Kirtana Ashok <Kirtana.Ashok@microsoft.com>

go.mod: Bump hcsshim to v0.10.0-rc.5

---

pkg/cri/server/image_pull.go
pkg/cri/server/image_pull_test.go
pkg/snapshotters/annotations.go
pkg/snapshotters/annotations_test.go

- backport of https://github.com/containerd/containerd/pull/8036 (cherry picked from commit dbf384a5a857b635e0ea8b160645be81e60b3858)
- relates to https://github.com/containerd/containerd/pull/8036#issuecomment-1412229046
> I wonder if this could make sense for a 1.6 patch release if it would help transitioning. Overall it seems fairly low risk, but it's not a "bug-fix" or "security-fix", so not sure if it would qualify (would be nice though!)
---
⚠️ I had conflicts in:
- pkg/cri/server/image_pull.go
- pkg/cri/server/image_pull_test.go
The conflicts were in adjacent line changes; I looked at the "parent" commit for https://github.com/containerd/containerd/pull/8036  (https://github.com/containerd/containerd/commit/753bfd6575ece15de49b3df786a9e60fc24cbf55), and the code that was moved did …

[release/1.6 backport] Export remote snapshotter label handler

---

.github/workflows/ci.yml

The binary location was moved since
https://github.com/kubernetes-sigs/cri-tools/pull/1085.
Fixes #8073.

Add critest.exe in $PATH

---

snapshots/devmapper/pool_device.go

This should fix #7712
Found an issue with the retry logic when device or resource is busy

Fix retry logic within devmapper device deactivation

---

content/helpers.go
remotes/handlers.go

OCI added support for a `data` field in a descriptor. This field is expected to contain the content being pointed to by the descriptor.
As an example of this see: [docker.io/tianon/true@sha256:434c266719c0dc4e936294efa36f66aed4f50a414ea495a234dce16454153478](https://explore.ggcr.dev/?image=tianon/true@sha256:434c266719c0dc4e936294efa36f66aed4f50a414ea495a234dce16454153478)
```json
{
"config": {
"data": "ewoJImFyY2hpdGVjdHVyZSI6ICJhbWQ2NCIsCgkiY29uZmlnIjogewoJCSJDbWQiOiBbCgkJCSIvdHJ1ZSIKCQldCgl9LAoJImNyZWF0ZWQiOiAiMjAxNC0wMS0yNVQyMzoxMTowOVoiLAoJImhpc3RvcnkiOiBbCgkJewoJCQkiY3JlYXRlZCI6ICIyMDE0LTAxLTI1VDIzOjExOjA5WiIsCgkJCSJjcmVhdGVkX2J5IjogIm5hc20gLW8gL3RydWUgaHR0cHM6Ly9naXRodWIuY29tL3RpYW5vbi9kb2NrZXJmaWxlcy9ibG9iLzRhMWRkMjM0ZmEyZTY3MWM5MjljMDk5Mjk3MDliZjMzYWZmZGM1OTcvdHJ1ZS90cnVlLmFzbSIKC …
```

fetch: Use data from descriptor when available.

---

releases/v1.6.17.toml
version/version.go

----
containerd 1.6.17
Welcome to the v1.6.17 release of containerd!
The seventeenth patch release for containerd 1.6 includes various updates.
* **Add network plugin metrics** ([#8018](https://github.com/containerd/containerd/pull/8018))
* **Update mkdir permission on /etc/cni to 0755 instead of 0700** ([#8030](https://github.com/containerd/containerd/pull/8030))
* **Export remote snapshotter label handler** ([#8054](https://github.com/containerd/containerd/pull/8054))
* **Add support for default hosts.toml configuration** ([#8065](https://github.com/containerd/containerd/pull/8065))
* Akihiro Suda
* Derek …

[release/1.6] Prepare release notes for v1.6.17

---

.github/workflows/ci.yml
.github/workflows/codeql.yml
.github/workflows/fuzz.yml

For running CI in a non-upstream repo

CI: skip some jobs when `repo != containerd/containerd`

---

.github/workflows/ci.yml
.github/workflows/codeql.yml

Cherry-pick:
- https://github.com/containerd/containerd/pull/8082

[release/1.5] CI: skip some jobs when `repo != containerd/containerd`

---

pkg/apparmor/apparmor.go
pkg/apparmor/apparmor_linux.go

- Revert of https://github.com/containerd/containerd/pull/5519
This reverts commit https://github.com/containerd/containerd/commit/1acca8bba36e99684ee3489ea4a42609194ca6b9.
As stated in the Godoc, this function is intended to check for presence of `apparmor_parser`. Changing this regressed the public API of containerd, and directly contradicts the way that this function is consumed inside of containerd itself:
* https://github.com/containerd/containerd/blob/fdfdc9bfc0f865a43c88171110615d1510fad3bc/pkg/apparmor/apparmor.go#L20
* https://github.com/containerd/containerd/blob/fdfdc9bfc0f865a43c88171110615d1510fad3bc/pkg/cri/sbserver/helpers_linux.go#L85
* https://github.com/containerd/containerd/blob/fdfdc9bfc0f865a43c88171110615d1510fad3bc/pkg/cri/server/helpers_linux.go#L144
This has lead …

Revert `apparmor_parser` regression

---

pkg/apparmor/apparmor.go
pkg/apparmor/apparmor_linux.go

- Backport of https://github.com/containerd/containerd/pull/8086
- Revert of https://github.com/containerd/containerd/pull/5519
This reverts commit https://github.com/containerd/containerd/commit/1acca8bba36e99684ee3489ea4a42609194ca6b9.
As stated in the Godoc, this function is intended to check for presence of `apparmor_parser`. Changing this regressed the public API of containerd, and directly contradicts the way that this function is consumed inside of containerd itself:
* https://github.com/containerd/containerd/blob/fdfdc9bfc0f865a43c88171110615d1510fad3bc/pkg/apparmor/apparmor.go#L20
* https://github.com/containerd/containerd/blob/fdfdc9bfc0f865a43c88171110615d1510fad3bc/pkg/cri/sbserver/helpers_linux.go#L85
* https://github.com/containerd/containerd/blob/fdfdc9bfc0f865a43c8817111061 …

[release/1.6 backport] Revert `apparmor_parser` regression 

---

snapshots/devmapper/pool_device.go

Cherry-pick this bug fix [#8075 ](https://github.com/containerd/containerd/pull/8075) into 1.6 branch
(cherry picked from commit 6ae3e5df6a9dda573e57f06610474848431ba2cb)

[release/1.5] Fix retry logic within devmapper device deactivation

---

pkg/cri/server/helpers.go

In https://github.com/containerd/containerd/pull/7764 it was made so that generic runtime options in the containerd toml config file would get passed to shims regardless of if containerd knew of the type beforehand and could supply the struct. However, this was only added for the sandbox server fork here and not the regular ol' CRI server. This change just mirrors the parts that need to be plopped in pkg/cri/server

CRI: Mirror generic toml runtime config under server

---

contrib/apparmor/template.go

- equivalent of https://github.com/moby/moby/pull/44960 in moby
These conditions were added in docker in https://github.com/moby/moby/commit/8cf89245f5b5f9abb066f599cb69bfe0202bae5d to account for old versions of debian/ubuntu (apparmor_parser < 2.8.95) that lacked some options;
> This allows us to use the apparmor profile we have in contrib/apparmor/
> and solves the problems where certain functions are not apparent on older
> versions of apparmor_parser on debian/ubuntu.
Those patches were from 2015/2016, and all currently supported distro versions should now have more current versions than that. Looking at the oldest supported versions;
Ubuntu 18.04 "Bionic":
apparmor_parser --version
AppArmor parser version 2.12
Copyright (C) 1999-2008 Novell Inc.
Copyright 2009-2012 Canonical Ltd. …

contrib/apparmor: remove version-dependent rules

---

pkg/cri/sbserver/helpers_test.go
pkg/cri/sbserver/helpers_windows_test.go
pkg/cri/server/helpers_test.go
pkg/cri/server/helpers_windows_test.go

Add the following tests for `hostNetwork` helper function
- when host process is true in the `PodSandboxConfig` hostNetwork returns true
- when host process is false in the `PodSandboxConfig` hostNetwork returns false
--------
- when network is pod `hostNetwork` returns false
- when network is node `hostNetwork` returns true

test: add hostNetwork tests for both windows and linux

---

integration/container_event_test.go
pkg/cri/sbserver/events.go
pkg/cri/sbserver/helpers.go
pkg/cri/sbserver/podsandbox/sandbox_delete.go
pkg/cri/sbserver/podsandbox/sandbox_run.go
pkg/cri/sbserver/sandbox_run.go
pkg/cri/server/helpers.go

Signed-off-by: ruiwen-zhao <ruiwen@google.com>
This is a follow up action item of supporting Kubernete's Evented PLEG feature (https://github.com/kubernetes/enhancements/issues/3386). Now that https://github.com/kubernetes/kubernetes/pull/114351 merged, kubelet can handle nil PodSandboxStatus, containerd can send events with nil PodSandboxStatus.
Note that this PR also contains reverting part of https://github.com/containerd/containerd/pull/8007 (i.e. moving PLEG event generation back to sbserver) This is needed because we need the event generation to be in sbserver/ to be able to get PodSandboxStatus. More details in https://github.com/containerd/containerd/pull/8007#issuecomment-1416341393. 
fixes https://github.com/containerd/containerd/issues/7785

Send container events with nil PodSandboxStatus

---

pkg/cri/sbserver/sandbox_run.go
sandbox/controller.go

Allow sandboxed shims access `PodSandboxConfig` when creating a sandbox, this way shims can configure many things - DNS, ports, etc.
/cc @dcantah this might be useful for your use case too.

[sandbox] Use options to pass PodSandboxConfig to shims

---

platforms/defaults_windows.go
platforms/defaults_windows_test.go
platforms/platforms_windows_test.go

The background for this change:
1. Windows host-process containers do not have an OS version set
2. Buildx v0.10 started pushing manifest lists by default, but it never has the OSVersion in the platform data (not that there is any way to specify what particular OS version you want). The change means that containerd cannot run images created with the new buildx on Windows because there is no matching OSVersion in the list of manifests.
Fixes #8070
Fixes #7431

Add fallback for windows platforms without osversion

---

go.mod
go.sum
integration/client/go.sum
pkg/cri/sbserver/sandbox_run.go
pkg/cri/server/sandbox_run.go
vendor/github.com/containerd/go-cni/.golangci.yml
vendor/github.com/containerd/go-cni/namespace_opts.go
vendor/github.com/containerd/go-cni/result.go
vendor/github.com/containerd/go-cni/testutils.go
vendor/github.com/containerd/go-cni/types.go
vendor/github.com/containerd/go-cni/types_others.go
vendor/github.com/containerd/go-cni/types_windows.go
vendor/modules.txt

There is a new CNI capability argument, cgroupPath, where runtimes can pass cgroup paths to CNI plugins.
(see: https://github.com/containernetworking/cni/pull/936)
Implement that.
Signed-off-by: Casey Callendrello <cdc@isovalent.com>

cni: pass in the cgroupPath capability argument

---

pkg/cri/annotations/annotations.go
pkg/cri/sbserver/container_create.go
pkg/cri/sbserver/podsandbox/sandbox_run_linux.go
pkg/cri/sbserver/podsandbox/sandbox_run_other.go
pkg/cri/sbserver/podsandbox/sandbox_run_windows.go
pkg/cri/server/container_create_linux.go
pkg/cri/server/container_create_other.go
pkg/cri/server/container_create_windows.go
pkg/cri/server/sandbox_run_linux.go
pkg/cri/server/sandbox_run_other.go
pkg/cri/server/sandbox_run_windows.go

!windows and !linux weren't getting passed the sandbox annotations. 
This additionally adds in a commit on top to refactor how these annotations were getting passed. All of the CRI sandbox and container specs all get assigned almost the exact same default annotations (sandboxID, name, metadata, container type etc.) so I added a helper to return the right set for a sandbox or regular workload container.

CRI: Pass sandbox annotations to _other platforms

---

plugins/sandbox/controller.go
runtime/v2/binary.go
runtime/v2/bridge.go
runtime/v2/manager.go
runtime/v2/shim.go
runtime/v2/shim/shim.go
runtime/v2/shim_load.go
sandbox/bridge.go

- Adds a unified (TTRPC + GRPC) clients for TaskService and SandboxService.
- Shim client support
- Introduce shim bootstrap params (a JSON payload returned in stdout from Shim.Start to specify protocol, shim caps, etc).

Initial GRPC shims support

---

platforms/defaults_windows.go
platforms/defaults_windows_test.go
platforms/platforms_windows_test.go

The background for this change:
1. Windows host-process containers do not have an OS version set
2. Buildx v0.10 started pushing manifest lists by default, but it never has the OSVersion in the platform data (not that there is any way to specify what particular OS version you want). The change means that containerd cannot run images created with the new buildx on Windows because there is no matching OSVersion in the list of manifests.
(cherry picked from commit 8442521645bac4a3198a1dce56ca08147f7a8e59)

[1.6] Add fallback for windows platforms without osversion

---

releases/v1.5.18.toml
version/version.go

Generated notes 
----
containerd 1.5.18
Welcome to the v1.5.18 release of containerd!
The eighteenth patch release for containerd 1.5 includes fixes for CVE-2023-25153 and CVE-2023-25173
along with a security update for Go.
* **Fix supplementary groups not being set up properly** ([GHSA-hmfx-3pcx-653p](https://github.com/containerd/containerd/security/advisories/GHSA-hmfx-3pcx-653p))
* **Fix OCI image importer memory exhaustion** ([GHSA-259w-8hf6-59c2](https://github.com/containerd/containerd/security/advisories/GHSA-259w-8hf6-59c2))
* **Update Go to 1.19.6** ([#8112](https://github.com/containerd/containerd/pull/8112))
* Akihiro Suda …

[release/1.5] Prepare release notes for v1.5.18

---

releases/v1.6.18.toml
version/version.go

----
containerd 1.6.18
Welcome to the v1.6.18 release of containerd!
The eighteenth patch release for containerd 1.6 includes fixes for CVE-2023-25153 and CVE-2023-25173
along with a security update for Go.
* **Fix OCI image importer memory exhaustion** ([GHSA-259w-8hf6-59c2](https://github.com/containerd/containerd/security/advisories/GHSA-259w-8hf6-59c2))
* **Fix supplementary groups not being set up properly** ([GHSA-hmfx-3pcx-653p](https://github.com/containerd/containerd/security/advisories/GHSA-hmfx-3pcx-653p))
* **Revert removal of `/sbin/apparmor_parser` check** ([#8087](https://github.com/containerd/containerd/pull/8087))
* **Update Go to 1.19.6** ([#8111](https://github.com/containerd/containerd/pull/8111)) …

[release/1.6] Prepare release notes for v1.6.18

---

pkg/cri/sbserver/sandbox_portforward_linux.go
pkg/cri/server/sandbox_portforward_linux.go
pkg/process/init.go

Signed-off-by: yulng [wei.yang@daocloud.io](mailto:wei.yang@daocloud.io)
Usually, go routine is represented by goroutine
Thanks

fix: 'go routine' should be 'goroutine'

---

integration/client/container_fuzzer.go

The introduction of FuzzIntegNoTearDownWithDownload is confusing with the duplicate names in container fuzzer.
Signed off by: Jiongchi Yu [jcyu.2022@phdcs.smu.edu.sg](mailto:jcyu.2022@phdcs.smu.edu.sg)

docs: fix function names in fuzzing test documentation

---

pkg/cri/config/config.go

The config registry mirror is still in version 1.7 and may plan to delete at 2.0
”Removal of this and other deprecations are not immediate. Yes, we've been considering removing all v1 deprecations when we move to v2, yes perhaps EOY perhaps sometime next year. We've been discussing the possibility of providing migration tooling for config and metadata. It is just as likely we will attempt to carry v1 and early v2 release versions of certain services (esp. CRI) at the same time to allow for opt in testing. The hosts.toml config is very similar to docker hosts.toml, if that helps.
"
from the https://github.com/kubernetes/kubernetes/issues/110312#issuecomment-1146040643_ 
And https://github.com/containerd/containerd/blame/main/docs/cri/registry.md#L14 is also showd " remove in containerd …

pkg/cri/config: fix Mirrors deprecation comment

---

.mailmap
releases/v1.7.0-beta.toml
version/version.go

Generated notes (See unabridged version in [gist](https://gist.github.com/dmcgowan/18c05d167f0c0c3fe7d1d8839e6ec932))
------
Welcome to the v1.7.0-beta.4 release of containerd!  
The previous 1.6 release has also become a long term stable release for users who prefer releases …

Prepare release notes for v1.7.0 beta.4

---

runtime/v2/shim.go

[Recent work](https://github.com/containerd/containerd/pull/8052) added the ability to use grpc for shims, it'd be nice to have a debug (or info perhaps) log to show what protocol and addr the shim sent over.

runtime/v2: Log BootstrapParams

---

pkg/cri/store/sandbox/sandbox.go

Fixes panic produced by containerd when cri metrics are enabled.
The panic was observed with containerd 1.6.18 and k8s 1.23.16.
We started seeing this issue when on k8s side, we enabled the feature gate PodAndContainerStatsFromCRI
```
fatal error: concurrent map read and map write
goroutine 24245 [running]:
runtime.throw({0x55555c169112?, 0xc003f0b340?})
/usr/local/go/src/runtime/panic.go:992 +0x71 fp=0xc00575c6c8 sp=0xc00575c698 pc=0x55555aed5511
runtime.mapaccess1(0x55555c7717e0?, 0xc00145ee10?, 0x40?)
/usr/local/go/src/runtime/map.go:415 +0x1f7 fp=0xc00575c708 sp=0xc00575c6c8 pc=0x55555aeaccd7
github.com/containerd/containerd/pkg/cri/store/sandbox.(*Store).UpdateContainerStats(0xc00145eea0, {0xc001d4d140?, 0xc00179a240?}, 0xc003f28a00) …
```

Fix concurrent writes for UpdateContainerStats

---

BUILDING.md

There is currently no mention of OS requirement in BUILDING.md under the Building containerd from source section. It is mentioned that containerd is available for Linux and Windows in README.md, but I find it worth noting that a flawed build is possible on macOS.

Add macOS build note

---

cmd/containerd/command/main.go
cmd/ctr/commands/content/prune.go
diff/apply/apply.go
diff/lcow/lcow.go
diff/windows/windows.go
events/exchange/exchange.go
integration/client/client_test.go
integration/client/go.mod
log/context.go
pkg/transfer/local/pull.go
pkg/unpack/unpacker.go
remotes/docker/authorizer.go
remotes/docker/resolver.go
remotes/handlers.go
runtime/v1/linux/runtime.go
runtime/v1/shim/client/client.go
runtime/v1/shim/service.go
runtime/v2/shim/shim.go
services/content/contentserver/contentserver.go
snapshots/btrfs/btrfs.go
snapshots/devmapper/snapshotter.go

When logging with custom fields, like:
```go
log.G(ctx).WithFields(logrus.Fields{ ... })...
```
you're forced to do two imports
```go
"github.com/containerd/containerd/log"
"github.com/sirupsen/logrus"
```
This PR adds a type alias to log package, so we end up with just one import:
```go
"github.com/containerd/containerd/log"
log.G(ctx).WithFields(log.Fields{})
```
Which often reduces the number of imports and makes log package a bit nicer.

Add Fields type alias to log package

---

runtime/v2/shim.go

We pass in a callback using the ttrpc.WithOnClose functionality
for shims that use ttrpc, but with the newly added ability to use
GRPC for shims this was left as a follow-up. 
This change introduces a new grpcConn wrapper type for the connection
that exposes a method to get notified when the users callback has run,
the same in functionality as TTRPC's `UserOnCloseWait`. The callback
gets passed in in a new `grpcDialContext` function that will:
1. Dial the connection as normal
2. Spin off a goroutine that will monitor the connections state
until it transitions to idle or shutdown and will then run the
callback.

runtime/v2: Call onCloseWithShimLog for grpc shims

---

contrib/apparmor/apparmor_test.go
contrib/apparmor/template.go

This code was no longer used now that the version-dependent rules were
removed from the template in 30c893ec5cba64de1bca0a2a9d3f92423f3ec0d7.

contrib/apparmor: remove code related to apparmor_parser version

---

go.mod
go.sum
integration/client/go.mod
integration/client/go.sum
vendor/github.com/Microsoft/hcsshim/internal/hcs/process.go
vendor/modules.txt

This PR bumps hcsshim tag to [v0.9.7](https://github.com/microsoft/hcsshim/releases/tag/v0.9.7)
Full changelog between v0.9.6 and v0.9.7 can be seen [here](https://github.com/microsoft/hcsshim/compare/v0.9.6...v0.9.7).

[release/1.6] go.mod: Bump hcsshim to v0.9.7

---

runtime/v2/logging/logging.go

- When tracing code, it was a bit hard to understand what the third parameter is.
- The current comment should be enough to understand how to use `LoggerFunc`, and people who want to learn more can click into the doc link.

docs: add more comment to logging.LoggerFunc

---

pkg/cri/sbserver/image_pull.go
pkg/cri/sbserver/image_pull_test.go

The snapshotter annotation definitions and related functions have been public in the new package snapshotter. So we can safely remove the duplicated code from CRI.

CRI: remove duplicated snapshotters code

---

runtime/v2/README.md

This updates the runtime/v2 README to state the experimental GRPC support for shims and how to choose the protocol.

docs: Show how to select GRPC for shims

---

.mailmap
releases/v1.7.0-rc.toml
version/version.go

Generated release notes below, see [full release notes](https://gist.github.com/dmcgowan/4727450456569524c44fa1829276ecd1)
----
Welcome to the v1.7.0-rc.0 release of containerd!  
The previous 1.6 release has also become a long term stable release for users who prefer releases …

Prepare release notes for v1.7.0-rc.0

---

releases/v1.6.19.toml
version/version.go

Welcome to the v1.6.19 release of containerd!
The nineteenth patch release for containerd 1.6 contains runtime fixes and additions for Windows platforms
* Update hcsshim to v0.9.7 to include fix for graceful termination and pause containers ([#8153](https://github.com/containerd/containerd/pull/8153))
<details><summary>2 commits</summary>
<p>
* [release/1.6] go.mod: Bump hcsshim to v0.9.7 ([#8153](https://github.com/containerd/containerd/pull/8153))
* [`f488a6241`](https://github.com/containerd/containerd/commit/f488a6241b7fa87746026de1a947c57d311751e8) Update hcsshim tag to v0.9.7
</p>
</details>
* …

[release/1.6] Prepare release notes for v1.6.19

---

script/setup/install-protobuf

This PR updates `script/setup/install-protobuf`:
- Removes most of the case/if branches
- Adds `aarch_64` for OSX and Linux

Rework install-protobuf script and add new targets

---

runtime/v2/README.md
runtime/v2/binary.go
runtime/v2/shim.go
runtime/v2/shim/shim.go
runtime/v2/shim/util.go
runtime/v2/shim_test.go

For 2.0 we are planning on introducing an update to the shim protocol to support a wider range of capabilities. While the updates to the shim protocol are not fully decided, we can introduce versioning now to keep newer "v3 or however we version it" shims compatible with shim v2 in 1.7 or at the very least able to handle the incompatibility gracefully. This will make it easier to finalize on a shim protocol in 2.0 that is both backwards compatible and have the flexibility we know we need for plugin use cases.
- Adds additional environments for consistency 
- Document existing environment variables
- Adds a test for the JSON response parsing
Parts of the updated protocol and this can also be backported to 1.6 for the same compatibility guarantees

Add version to shim protocol

---

.github/workflows/ci.yml

This patch is meant to prevent test timeouts on Windows as [new tests are added/enabled](https://github.com/containerd/containerd/actions/runs/4298442869/jobs/7492617454) on it.

Increase CI workflow timeout on Windows.

---

docs/historical/design/data-flow.md

I'm aware it's a historical doc, but it's still useful to get a rough understanding of containerd, so I feel it may be worth it to fix the typos :) Please let me know if no modification is wanted to these historical docs, thanks!

docs: fix typos in historical/design/data-flow.md

---

runtime/v2/shim/shim.go
runtime/v2/shim/util.go

Adds environment variable to shim start command. I forgot to add this one in the previous PR.

Add max shim version environment variable

---

metadata/db.go
plugins/streaming/manager.go

Ensure that lock is released and stream is closed.
The call to `ms.Close()` causes the deadlock since it attempts to acquire a lock the collection already has, it should only be calling `Close` on the stream.

Fix streaming manager deadlock on collection

---

cmd/ctr/commands/run/run.go
cmd/ctr/commands/run/run_unix.go
cmd/ctr/commands/run/run_windows.go
cmd/ctr/commands/tasks/start.go
cmd/ctr/commands/tasks/tasks_unix.go
cmd/ctr/commands/tasks/tasks_windows.go

`ctr tasks start` supports resolving to uid/gid mappings from spec.
For `ctr run`, the NewContainer function will also set the uid/gid mapping.
https://github.com/containerd/containerd/blob/6c8c4271661d658c381a97cebd53e3b382bb17dd/cmd/ctr/commands/run/run_unix.go#L162-L173
For uid/gid mappings that already exist in the container spec, there is no need for the `ctr tasks start` command to ignore it

ctr/tasks: support remapped UID/GID

---

pkg/transfer/local/transfer.go
plugins/transfer/plugin.go

Fix #8179 
This PR creates a new struct to take user facing configurations and separate the input from internal structures to avoid config loading issue from the internal structures. 
Signed-off-by: Tony Fang <nhfang@amazon.com>

Create config struct to take user input

---

.mailmap
releases/v1.7.0-rc.toml
version/version.go

Generated release notes below, see [full release notes](https://gist.github.com/dmcgowan/4727450456569524c44fa1829276ecd1)
_We are waiting on a few more v1.7 fixes before merging and cutting this rc_
----
Welcome to the v1.7.0-rc.1 release of containerd!  
The previous 1.6 …

Prepare release notes for v1.7.0-rc.1

---

docs/cri/config.md
integration/container_exec_test.go
pkg/cri/config/config.go
pkg/cri/config/config_test.go
pkg/cri/config/config_unix.go
pkg/cri/config/config_windows.go
pkg/cri/sbserver/container_execsync.go
pkg/cri/sbserver/container_execsync_test.go
pkg/cri/server/container_execsync.go
pkg/cri/server/container_execsync_test.go
script/test/utils.sh

By default, the child processes spawned by exec process will inherit standard io file descriptors. The shim server creates a pipe as data channel. Both exec process and its children write data into the write end of the pipe. And the shim server will read data from the pipe. If the write end is still open, the shim server will continue to wait for data from pipe.
So, if the exec command is like `bash -c "sleep 365d &"`, the exec process is bash and quit after create `sleep 365d`. But the `sleep 365d` will hold the write end of the pipe for a year! It doesn't make senses that CRI plugin should wait for it.
For this case, we should use timeout to drain exec process's io instead of waiting for it.
Fixes: #7802

pkg/cri: add timeout to drain exec io

---

pkg/epoch/epoch.go
pkg/epoch/epoch_test.go

Fixes https://github.com/containerd/containerd/issues/8200
Before this change, the following invocations would cause the unit test to fail:
```
$ SOURCE_DATE_EPOCH="" go test -v ./pkg/epoch
=== RUN   TestSourceDateEpoch
epoch_test.go:38: SOURCE_DATE_EPOCH is already set to "", unsetting
=== RUN   TestSourceDateEpoch/WithoutSourceDateEpoch
epoch_test.go:44: 
Error Trace:	/home/samuelkarp/go/src/github.com/containerd/containerd/pkg/epoch/epoch_test.go:44
Error:      	Received unexpected error:
invalid SOURCE_DATE_EPOCH value "": strconv.ParseInt: parsing "": invalid syntax
Test:       	TestSourceDateEpoch/WithoutSourceDateEpoch
=== RUN   TestSourceDateEpoch/WithSourceDateEpoch
=== RUN   TestSourceDateEpoch/WithInvalidSourceDateEpoch
time="2023-03-03T14:54:13-08:00" level=warning …
```

epoch: fix unit test when SOURCE_DATE_EPOCH is set

---

plugins/sandbox/controller.go

CreateSandbox states "failed to start sandbox". This is quite confusing when you're perusing logs and trying to pinpoint how far a shim got in its execution.
Example of what you'd get from k8s: `error="failed to create sandbox \"35ec3d335ff8baf64d89c09f79279280741b1f8822dfdc8aaf338f20e437a571\": failed to start sandbox 35ec3d335ff8baf64d89c09f79279280741b1f8822dfdc8aaf338f20e437a571`

Sandbox: Fix/enhance error messages for Create

---

pkg/cri/sbserver/sandbox_stats.go
pkg/cri/sbserver/sandbox_stats_linux.go
pkg/cri/sbserver/sandbox_stats_list.go
pkg/cri/sbserver/sandbox_stats_other.go
pkg/cri/sbserver/sandbox_stats_windows.go
pkg/cri/sbserver/sandbox_stats_windows_test.go
pkg/cri/server/sandbox_stats.go
pkg/cri/server/sandbox_stats_linux.go
pkg/cri/server/sandbox_stats_list.go
pkg/cri/server/sandbox_stats_other.go
pkg/cri/server/sandbox_stats_windows.go
pkg/cri/server/sandbox_stats_windows_test.go

Implements `ListPodSandboxStats` and `PodSandboxStats` for Windows.
Part of https://github.com/kubernetes/enhancements/issues/2371
Currently is using the branch from https://github.com/kubernetes/kubernetes/pull/110754 for the CRI API updates that were needed for Windows
Still need to add some tests and refactor some of the linux functionality to be able to implement `UsageNanoCores`.  
I made a [custom build of crictl](https://github.com/kubernetes-sigs/cri-tools/compare/master...jsturtevant:windows-cri-only-stats?expand=1) that can handle the windows stats but can use any version that has the `statsp` command.

[cri] Implement CRI Pod and Container stats for Windows

---

plugins/sandbox/controller.go

Currently if create fails the shim will just be kind of stuck in limbo. This calls shutdown to allow the shim to exit, and then invokes shim delete.

Sandbox: Delete shim+shutdown sandbox on create failure

---

.mailmap
releases/v1.7.0-rc.toml
version/version.go

Release notes for v1.7.0-rc.2. The release is close, just a few more dependencies to update and PRs in the milestone. See the full release notes at https://gist.github.com/dmcgowan/4727450456569524c44fa1829276ecd1
----
Welcome to the v1.7.0-rc.2 release of containerd!  
This release still adheres to our backwards compatibility guarantees and users who do not use or enable new functionality should use this release with the same stability expectations.
The …

Add release notes for v1.7.0-rc.2

---

.golangci.yml
archive/tar.go
archive/tarheader/tarheader.go
archive/tarheader/tarheader_unix.go

These strings were resolved using the user information on the host filesystem and were decreasing reproducibility.
For :
- moby/buildkit#3688

archive: disable looking up usernames and groupnames on the host

---

integration/client/image_test.go
labels/labels.go
remotes/docker/handler.go
remotes/docker/handler_test.go
remotes/handlers.go

Add a public const for "containerd.io/distribution.source" in `labels` package and replace hardcoded usages.

labels: Add LabelDistributionSource

---

releases/v1.7.0-rc.toml
version/version.go

The last release candidate before the final release 🤞 After this release, main will be temporarily frozen for non-release related changes until 1.7.0 final release. Full notes at https://gist.github.com/dmcgowan/4727450456569524c44fa1829276ecd1
---
Welcome to the v1.7.0-rc.3 release of containerd!  
This release is the last major release of containerd 1.x before 2.0.
This release still adheres to our backwards compatibility guarantees and users who do not use or enable new functionality should use this release with the same stability …

Prepare release notes for v1.7.0-rc.3

---

.golangci.yml
archive/tar.go
archive/tarheader/tarheader.go
archive/tarheader/tarheader_unix.go

(currently based on top of https://github.com/containerd/containerd/pull/8229)
- backport of https://github.com/containerd/containerd/pull/8220
- addresses https://github.com/moby/buildkit/issues/3688

[release/1.6 backport] archive: disable looking up usernames and groupnames on the host

---

.github/workflows/build-test-images.yml
.github/workflows/ci.yml
.github/workflows/codeql.yml
.github/workflows/images.yml
.github/workflows/nightly.yml
.github/workflows/release.yml
Vagrantfile
contrib/Dockerfile.test
script/setup/prepare_env_windows.ps1

> go1.19.7 (released 2023-03-07) includes a security fix to the crypto/elliptic package,
> as well as bug fixes to the linker, the runtime, and the crypto/x509 and syscall
> packages.
> See the Go 1.19.7 milestone on our issue tracker for details.
https://go.dev/doc/devel/release#go1.19.minor

[release/1.6] Go 1.19.7

---

RELEASES.md
pkg/cri/config/config.go

These deprecations were mentioned in `pkg/cri/config/config.go` but not mentioned in `RELEASES.md`.

RELEASES.md: describe the deprecated config properties

---

RELEASES.md
releases/v1.7.0.toml
version/version.go

Final 1.7.0 release
Full release notes at https://gist.github.com/dmcgowan/4727450456569524c44fa1829276ecd1
----
Welcome to the v1.7.0 release of containerd!
This release is the last major release of containerd 1.x before 2.0.
This release still adheres to our backwards compatibility guarantees and users who do not use or enable new functionality should use this release with the same stability expectations.
The previous 1.6 release has also become a long term stable release for users who prefer releases with mostly stability improvements and wish to wait a few releases for new …

Prepare release notes for v1.7.0

---

RELEASES.md
runtime/restart/monitor/change.go
runtime/restart/monitor/monitor.go
runtime/restart/restart.go

"containerd.io/restart.logpath" has been deprecated since containerd v1.5, in favor of "containerd.io/restart.loguri":
https://github.com/containerd/containerd/blob/v1.7.0/RELEASES.md#deprecated-features

Remove "containerd.io/restart.logpath" label (deprecated since v1.5)

---

plugins/sandbox/controller.go

CreatedAt was being used as the ExitedAt timestamp, and Info from the shim response wasn't being set on the response.

Sandbox: Correct/add some fields to Status()

---

plugins/sandbox/controller.go

[Made a change a bit ago](https://github.com/containerd/containerd/pull/8204) to cleanup the shim on CreateSandbox failures and noted that we should probably do the same on Start as well as nothing gets cleaned up otherwise, and nothing states that a sandbox server/shim should exit itself if Create/Start fail. Ideally this could be hooked up to some subsystem in containerd that'd do it for us, but for now to allow developing/prototyping sandbox shims this makes things much friendlier.

Sandbox: Cleanup shim on Start failure

---

integration/client/restart_monitor_test.go
runtime/restart/monitor/monitor.go

fix: https://github.com/containerd/containerd/issues/8095

Fix restarting containers that are being paused

---

pkg/cri/sbserver/service.go
pkg/cri/sbserver/service_other.go
pkg/cri/sbserver/service_windows.go
pkg/cri/server/service.go

In the CRI server initialization a syncgroup is setup that adds to the counter for every cni config found/registered. This functions on platforms where CNI is supported/theres an assumption that there will always be the loopback config. However, on platforms like Darwin where there's generally nothing registered the Wait() on the syncgroup returns immediately and the channel used to return any Network config sync errors is closed. This channel is one of three that's used to monitor if we should Close the CRI service in containerd, so it's not great if this happens.

CRI: Don't always close netConfMonitor channel

---

RELEASES.md
docs/PLUGINS.md
services/server/config/config.go
services/server/config/config_test.go
services/server/server.go

`version = 1` has been deprecated since containerd v1.5, and replaced by `version = 2`.
https://github.com/containerd/containerd/blob/main/docs/PLUGINS.md#version-header

Remove support for config.toml `version = 1`

---

cmd/ctr/commands/run/run_unix.go
cmd/ctr/commands/run/run_windows.go

When using `ctr run --cni --config`, the cni metadata is not set to the container,  so the `ctr task kill` does not remove the cni network

adding cni metadata to the container in the `ctr run --config`

---

pkg/cri/opts/spec_windows_opts.go

This error message currently does not provide useful information, because the `src` value that is interleaved will have been overridden by the call to `osi.ResolveSymbolicLink`. This stores the original `src` before the `osi.ResolveSymbolicLink` call so the error message can be useful.

fix: 'failed to resolve symlink' error messaging

---

diff/walking/differ.go
mount/mount.go
mount/mount_test.go
mount/temp.go

Taking over https://github.com/containerd/containerd/pull/6114 as it hasn't had activity in a while. Happy to close this PR if the original author wants to do it himself though :) 
------------
This adds an (exported) function to make overlay mounts readonly, which is necessary (with the overlayfs driver) to prevent the mounts from entering an unknown state and not working properly.
Also addressed some of the comments on the initial PR.
- https://github.com/moby/buildkit/pull/1100

Add `ReadonlyMounts` to make overlay mounts readonly

---

go.mod
go.sum
integration/client/go.mod
integration/client/go.sum
vendor/modules.txt

This PR bumps hcsshim tag to [v0.9.8](https://github.com/microsoft/hcsshim/releases/tag/v0.9.8)
Full changelog between v0.9.7 and v0.9.8 can be seen [here](https://github.com/microsoft/hcsshim/compare/v0.9.7...v0.9.8).

[release/1.6]go.mod: Bump hcsshim tag to v0.9.8

---

diff/walking/differ.go
mount/mount.go
mount/mount_test.go
mount/temp.go

Backport of https://github.com/containerd/containerd/pull/8259
--------------------
Backporting since we'd like to use this in:
- https://github.com/moby/moby/pull/44964
- https://github.com/moby/buildkit/pull/1100
the changes do functionally change the code in `diff/walking/differ.go` - `Compare()` to make the temp mount readonly. I don't think that should introduce any issues (and addresses https://github.com/containerd/containerd/issues/6077) but I thought it worth mentioning.

[release/1.7 backport] Add `WithReadonlyTempMount` to create readonly temporary mounts

---

oci/spec_opts.go
oci/spec_opts_linux.go
oci/spec_opts_unix.go
oci/spec_opts_windows.go
oci/spec_opts_windows_test.go

This PR cherry picks commit de3d999 from main branch
Adds support for Windows container images built by Docker that contain the ArgsEscaped boolean in the ImageConfig. This is a non-OCI entry that tells the runtime that the Entrypoint and/or Cmd are a single element array with the args pre-escaped into a single CommandLine that should be passed directly to Windows rather than passed as an args array which will be additionally escaped.
(cherry picked from commit de3d9993f5d2e4a2fe124b7572ea565c5caeb674)

[release/1.6] Adds support for Windows ArgsEscaped images

---

diff/walking/differ.go
mount/mount.go
mount/mount_test.go
mount/temp.go

Backport of https://github.com/containerd/containerd/pull/8259
--------------------
Backporting since we'd like to use this in:
- https://github.com/moby/moby/pull/44964
- https://github.com/moby/buildkit/pull/1100
the changes do functionally change the code in `diff/walking/differ.go` - `Compare()` to make the temp mount readonly. I don't think that should introduce any issues (and addresses https://github.com/containerd/containerd/issues/6077) but I thought it worth mentioning.

[release/1.6 backport] Add `WithReadonlyTempMount` to create readonly temporary mounts

---

oci/spec_opts.go

Mounts are not supported on Darwin, so carry the trick used on Windows for Darwin (e.g. defer uid:gid lookups).

Defer uid lookups on Darwin

---

oci/spec_opts.go

Backport https://github.com/containerd/containerd/pull/8312 to release 1.7

[backport 1.7] Defer uid lookups on Darwin

---

snapshots/devmapper/plugin/plugin.go

This is not really an error in most cases as most people do not use devmapper, however this shows up as an error in the logs and in the plugin service when querying the plugins.

devmapper plugin: skip plugin when not configured

---

go.mod
go.sum
integration/client/go.mod
integration/client/go.sum
vendor/github.com/containerd/ttrpc/server.go
vendor/modules.txt

Fix fd leak on connection reset
This change is already in main and release/1.7 with ttrpc 1.2

[release/1.6] Update ttrpc to v1.1.1

---

Protobuild.toml
api/Protobuild.toml

* `github.com/containerd/containerd/runtime/v1/shim/v1` has been removed
* The api's overrides configuration only needs to be in the *api/Protobuild.toml* file

Cleanup protobuild config

---

go.mod
go.sum
integration/client/go.mod
integration/client/go.sum
oci/spec_opts.go
oci/spec_opts_windows_test.go
vendor/github.com/opencontainers/image-spec/specs-go/v1/annotations.go
vendor/github.com/opencontainers/image-spec/specs-go/v1/artifact.go
vendor/github.com/opencontainers/image-spec/specs-go/v1/config.go
vendor/github.com/opencontainers/image-spec/specs-go/v1/descriptor.go
vendor/github.com/opencontainers/image-spec/specs-go/v1/index.go
vendor/github.com/opencontainers/image-spec/specs-go/v1/manifest.go
vendor/github.com/opencontainers/image-spec/specs-go/v1/mediatype.go
vendor/github.com/opencontainers/image-spec/specs-go/version.go
vendor/modules.txt

This PR cherry picks commit [d4b9dade1382875712099964c413f4277a3257c4 ](https://github.com/containerd/containerd/commit/d4b9dade1382875712099964c413f4277a3257c4) from main
ArgsEscaped has now been merged into upstream OCI image spec. This change removes the workaround we were doing in containerd to deserialize the extra json outside of the spec and instead just uses the formal spec types.
(cherry picked from commit d4b9dade1382875712099964c413f4277a3257c4)

[release/1.6]Updates oci image config to support upstream ArgsEscaped

---

pkg/cri/sbserver/container_create.go
pkg/cri/sbserver/container_create_linux.go
pkg/cri/sbserver/container_create_linux_test.go
pkg/cri/sbserver/container_create_other.go
pkg/cri/sbserver/container_create_test.go
pkg/cri/sbserver/container_create_windows.go
pkg/cri/sbserver/helpers.go
pkg/cri/sbserver/helpers_linux.go

In current implementation we exclude Linux specific mounts if we run on Windows/Darwin.
We should keep those if the target sandbox shim is running Linux containers.

Keep linux mounts for linux sandboxes on Windows/Darwin

---

releases/v1.6.20.toml
version/version.go

See generated release notes below
----
Welcome to the v1.6.20 release of containerd!
The twentieth patch release for containerd 1.6 contains various fixes and updates.
* **Disable looking up usernames and groupnames on host** ([#8230](https://github.com/containerd/containerd/pull/8230))
* **Add support for Windows ArgsEscaped images** ([#8273](https://github.com/containerd/containerd/pull/8273))
* **Update hcsshim to v0.9.8** ([#8274](https://github.com/containerd/containerd/pull/8274))
* **Fix debug flag in shim** ([#8288](https://github.com/containerd/containerd/pull/8288))
* **Add `WithReadonlyTempMount` to support readonly temporary mounts** ([#8299](https://github.com/containerd/containerd/pull/8299))
* **Update ttrpc to fix file descriptor leak** …

[release/1.6] Prepare release notes for v1.6.20

---

pkg/cri/sbserver/podsandbox/sandbox_run_linux.go
pkg/cri/sbserver/podsandbox/sandbox_run_linux_test.go
pkg/cri/server/sandbox_run_linux.go
pkg/cri/server/sandbox_run_linux_test.go

If you are running a pod with user namespace enabled you might see EPERM errors while mounting resolv.conf without these options.
This was discovered while we were debugging: https://github.com/opencontainers/runc/issues/3770

Add noexec nodev and nosuid to sandbox /etc/resolv.conf mount bind.

---

container.go
integration/client/container_test.go
integration/client/go.mod
task.go
task_opts.go

fix: https://github.com/containerd/containerd/issues/8207
https://github.com/containerd/containerd/blob/5da7e2c097952bce07ed5874355dedff72c9c343/pkg/cri/server/container_start.go#L124-L126
Although the runtime path is set in the cri server, the runtime path is not set to the `request` in the NewTask
Add `TaskInfo.RuntimePath` field to prevent overwriting `TaskInfo.runtime`, directly overwriting TaskInfo.runtime may cause exceptions to other `NewTaskOpts`

fix the task setting the runtime path

---

pkg/cri/sbserver/podsandbox/sandbox_run_linux.go
pkg/cri/sbserver/podsandbox/sandbox_run_linux_test.go
pkg/cri/server/sandbox_run_linux.go
pkg/cri/server/sandbox_run_linux_test.go

If you are running a pod with user namespace enabled you might see EPERM errors while mounting resolv.conf without these options.
This was discovered while we were debugging: https://github.com/opencontainers/runc/issues/3770
cherry-pick: #8309

[release/1.7] Add noexec nodev and nosuid to sandbox /etc/resolv.conf mount bind.

---

images/archive/exporter.go
integration/client/export_test.go

:cherries: Cherry-pick https://github.com/containerd/containerd/pull/8213
Cherry-pick of the tests isn't completely clean, since the tests have changed since 1.6 to use temporary files instead of in-memory buffers.

[release/1.6] archive: consistently respect value of WithSkipDockerManifest

---

.github/workflows/build-test-images.yml
.github/workflows/ci.yml
.github/workflows/codeql.yml
.github/workflows/images.yml
.github/workflows/nightly.yml
.github/workflows/release.yml
Vagrantfile
contrib/Dockerfile.test
script/setup/prepare_env_windows.ps1

go1.19.8 (released 2023-04-04) includes security fixes to the go/parser, html/template, mime/multipart, net/http, and net/textproto packages, as well as bug fixes to the linker, the runtime, and the time package. See the Go 1.19.8 milestone on our issue tracker for details:
https://github.com/golang/go/issues?q=milestone%3AGo1.19.8+label%3ACherryPickApproved
full diff: https://github.com/golang/go/compare/go1.19.7...go1.19.8
Further details from the announcement on the mailing list:
We have just released Go versions 1.20.3 and 1.19.8, minor point releases. These minor releases include 4 security fixes following the security policy:
- go/parser: infinite loop in parsing
Calling any of the Parse functions on Go source code which contains `//line`
directives with very large line numbers can …

[release/1.6] update go to go1.19.8

---

oci/spec_opts.go

The #8259 change added a new `WithReadonlyTempMount` that will force the mount to be readonly.
This change removes the `tryReadonlyMounts` and uses that function. 
Relates to https://github.com/containerd/containerd/pull/8259
Related: https://github.com/rumpl/moby/pull/92 and https://github.com/moby/moby/pull/45267
Note: once this PR is good to go I will backport these to 1.6 and 1.7, this is needed for moby's migration to the containerd image store and moby uses 1.6.x

oci: Use WithReadonlyTempMount when adding users/groups

---

.github/workflows/build-test-images.yml
.github/workflows/ci.yml
.github/workflows/codeql.yml
.github/workflows/images.yml
.github/workflows/nightly.yml
.github/workflows/release.yml
Vagrantfile
contrib/Dockerfile.test
script/setup/prepare_env_windows.ps1

- backport of https://github.com/containerd/containerd/pull/8352
go1.20.3 (released 2023-04-04) includes security fixes to the go/parser, html/template, mime/multipart, net/http, and net/textproto packages, as well as bug fixes to the compiler, the linker, the runtime, and the time package. See the Go 1.20.3 milestone on our issue tracker for details:
https://github.com/golang/go/issues?q=milestone%3AGo1.20.3+label%3ACherryPickApproved
full diff: https://github.com/golang/go/compare/go1.20.2...go1.20.3
go1.19.8 (released 2023-04-04) includes security fixes to the go/parser, html/template, mime/multipart, net/http, and net/textproto packages, as well as bug fixes to the linker, the runtime, and the time package. See the Go 1.19.8 milestone on our issue tracker for details: …

[release/1.7 backport] update go to go1.20.3, go1.19.8

---

oci/spec_opts.go

- backport of https://github.com/containerd/containerd/pull/8351
(cherry picked from commit cab056226fd8cece14d334ebb4f9084d0e3a7f47)
---
> The #8259 change added a new `WithReadonlyTempMount` that will force the mount to be readonly.
> 
> This change removes the `tryReadonlyMounts` and uses that function.
> 
> Relates to #8259 Related: [rumpl/moby#92](https://github.com/rumpl/moby/pull/92) and [moby/moby#45267](https://github.com/moby/moby/pull/45267)
> 
> Note: once this PR is good to go I will backport these to 1.6 and 1.7, this is needed for moby's migration to the containerd image store and moby uses 1.6.x

[release/1.7 backport] oci: Use WithReadonlyTempMount when adding users/groups

---

.github/workflows/ci.yml

The latest setup-go action caches the Go pkg cache and may have several minute-per-run speed improvement on CI runs which have to fill the pkg cache.

Update to setup-go@v4 action

---

pkg/cri/sbserver/container_create_linux.go
pkg/cri/sbserver/container_create_linux_test.go
pkg/cri/server/container_create_linux.go
pkg/cri/server/container_create_linux_test.go

I found a bug in setting `runtime.Spec.Process.User.additionalGids` in CRI server/sbserver.
If `LinuxContainerSecurityContext.{RunAsUser,RunAsUsername}` are empty, contained should fallback to the container image's `Config.User` for resolving the primary user and use it to inspect /etc/group in the container image for resolving `additionalGids`. But containerd always fallback to `0`.
__Fortunately, in the use of Kubernetes+containerd, the bug does NOT happen__ because kubelet always fills out `LinuxContainerSecurityContext.RunAsUser` from the image status ([code](https://github.com/kubernetes/kubernetes/blob/40deade20db9abb09c0812878c4fd8fb58af99e7/pkg/kubelet/kuberuntime/kuberuntime_container.go#L306)) when image's `Config.User` is not empty. So …

[CRI] fix additionalGids: it should fallback to imageConfig.User when securityContext.RunAsUser,RunAsUsername are empty

---

pkg/cri/sbserver/container_stats_list.go
pkg/cri/sbserver/container_stats_list_linux.go
pkg/cri/sbserver/container_stats_list_linux_test.go
pkg/cri/sbserver/container_stats_list_test.go

Backport stats changes from CRI to sbserver:
- https://github.com/containerd/containerd/pull/7186
- https://github.com/containerd/containerd/pull/7198
cc @jsturtevant @endocrimes

[sbserver] Backport CRI stats patches to sandboxed CRI 

---

runtime/v2/README.md
runtime/v2/manager.go

`containerd-shim-runc-v1` has been removed， update `containerd-shim-runc-v1` in readme and example to `containerd-shim-runc-v2`

update the version of the runc shim in the readme and examples

---

go.mod
go.sum
integration/client/go.mod
integration/client/go.sum
vendor/github.com/opencontainers/runtime-tools/validate/capabilities/validate_unsupported.go
vendor/modules.txt

- relates to https://github.com/containerd/containerd/pull/7957 https://github.com/containerd/containerd/pull/7957#pullrequestreview-1244814968
The actual version is replaced, so only "optics"
The replace rule was actually downgrading the package by one commit;
https://github.com/opencontainers/runtime-tools/compare/946c877fa809...2e043c6bd626

go.mod: remove redundant replace, and some cleaning-up

---

pkg/cri/server/container_create_linux_test.go
pkg/cri/server/container_create_test.go
pkg/cri/server/container_create_windows_test.go
pkg/cri/server/container_list_test.go
pkg/cri/server/container_remove_test.go
pkg/cri/server/container_start_test.go
pkg/cri/server/container_stats_list_linux_test.go
pkg/cri/server/container_stats_list_test.go
pkg/cri/server/container_status_test.go
pkg/cri/server/container_stop_test.go
pkg/cri/server/container_update_resources_linux_test.go
pkg/cri/server/helpers_linux_test.go
pkg/cri/server/helpers_selinux_linux_test.go
pkg/cri/server/helpers_test.go
pkg/cri/server/image_pull_test.go
pkg/cri/server/sandbox_list_test.go
pkg/cri/server/sandbox_run_linux_test.go
pkg/cri/server/sandbox_run_test.go
pkg/cri/server/sandbox_stats_windows_test.go
pkg/cri/server/sandbox_status_test.go
pkg/cri/server/sandbox_stop_test.go
pkg/cri/server/streaming_test.go
pkg/cri/server/update_runtime_config_test.go

Using array to build sub-tests is to avoid random pick. The shuffle thing should be handled by go-test framework. And we should capture range var before runing sub-test.

pkg/cri/server: sub-test uses array and capture range var

---

oci/spec_opts.go

- relates to https://github.com/containerd/containerd/pull/8259
- relates to https://github.com/containerd/containerd/pull/8351 https://github.com/containerd/containerd/pull/8351#pullrequestreview-1375706340
Commit cab056226fd8cece14d334ebb4f9084d0e3a7f47 removed the tryReadonlyMounts utility, in favor of mounts.ReadOnlyMounts() that was added in commit daa3a7665eaa2e33a965376106e02d358925c132.
That change made part of the comment redundant, because mounts.ReadOnlyMounts handles both overlayfs read-only mounts (by skipping the workdir mounts), and sets the "ro" option for other mount-types, but the reason why we're using a read-only mount is still relevant, so restoring that part of the comment.

oci: partially restore comment on read-only mounts for uid/gid uses

---

contrib/diffservice/service.go
diff.go
diff/proxy/differ.go
services/server/server.go

Adds support for the "diff" type proxy plugin. This allows for out of process diff plugins to be used using the existing proxy plugin framework. The `contrib` addition makes it easier to implement such plugins, similar to the `snapshotservice` in `contrib`. 
Moves the client proxy out of the client package to a package under `diff`, similar to our other client proxies.
A simple example is at https://gist.github.com/dmcgowan/93a19e4183493b46c5bf8cc3d5be9e59
Since we already have support for multiple differs (similar to how we have support for multiple snapshotters), configuring is easy. Just add the proxy plugin and update the diff service to use it (add it before walking to try the proxy first).
```
...
[plugins."io.containerd.service.v1.diff-service"]
default = ["proxydiff", "walking"] …
```

Add support for proxy differ

---

pkg/cri/sbserver/container_create_linux_test.go
pkg/cri/sbserver/container_create_test.go
pkg/cri/sbserver/container_create_windows_test.go
pkg/cri/sbserver/container_list_test.go
pkg/cri/sbserver/container_remove_test.go
pkg/cri/sbserver/container_start_test.go
pkg/cri/sbserver/container_stats_list_linux_test.go
pkg/cri/sbserver/container_stats_list_test.go
pkg/cri/sbserver/container_status_test.go
pkg/cri/sbserver/container_stop_test.go
pkg/cri/sbserver/container_update_resources_linux_test.go
pkg/cri/sbserver/helpers_test.go
pkg/cri/sbserver/images/image_pull_test.go
pkg/cri/sbserver/images/image_status_test.go
pkg/cri/sbserver/images/service_test.go
pkg/cri/sbserver/podsandbox/helpers_linux_test.go
pkg/cri/sbserver/podsandbox/helpers_selinux_linux_test.go
pkg/cri/sbserver/podsandbox/helpers_test.go
pkg/cri/sbserver/podsandbox/sandbox_run_linux_test.go
pkg/cri/sbserver/podsandbox/sandbox_run_test.go
pkg/cri/sbserver/sandbox_list_test.go
pkg/cri/sbserver/sandbox_run_test.go
pkg/cri/sbserver/sandbox_stats_windows_test.go
pkg/cri/sbserver/sandbox_status_test.go
pkg/cri/sbserver/sandbox_stop_test.go
pkg/cri/sbserver/streaming_test.go
pkg/cri/sbserver/update_runtime_config_test.go

Using array to build sub-tests is to avoid random pick. The shuffle
thing should be handled by go-test framework. And we should capture
range var before runing sub-test.

pkg/cri/sbserver: sub-test uses array and capture range var

---

go.mod
go.sum
integration/client/go.mod
integration/client/go.sum
vendor/github.com/opencontainers/runtime-tools/validate/capabilities/validate_unsupported.go
vendor/modules.txt

- backport of https://github.com/containerd/containerd/pull/8395
---
- relates to https://github.com/containerd/containerd/pull/7957 https://github.com/containerd/containerd/pull/7957#pullrequestreview-1244814968
The actual version is replaced, so only "optics"
The replace rule was actually downgrading the package by one commit;
https://github.com/opencontainers/runtime-tools/compare/946c877fa809...2e043c6bd626

[release/1.7] go.mod: remove redundant replace, and some cleaning-up

---

services/server/config/config.go
services/server/server.go

Allow the proxy plugin configuration to define the platform for the plugin. This is useful when supporting multiple platforms and trying to match a plugin based on the platform. By default, the plugin will have the default platform, similar to other snapshotters.

Add platform config to proxy plugins

---

plugins/transfer/plugin.go

Export transfer config fields.
Determine differ based on platform or config.
Get snapshotter from metadata store.
Follow up from #8272 (should be cherry-picked together)

Update transfer configuration

---

oci/spec_opts.go

- backport of https://github.com/containerd/containerd/pull/8397
---
- relates to https://github.com/containerd/containerd/pull/8259
- relates to https://github.com/containerd/containerd/pull/8351 https://github.com/containerd/containerd/pull/8351#pullrequestreview-1375706340
Commit cab056226fd8cece14d334ebb4f9084d0e3a7f47 removed the tryReadonlyMounts utility, in favor of mounts.ReadOnlyMounts() that was added in commit daa3a7665eaa2e33a965376106e02d358925c132.
That change made part of the comment redundant, because mounts.ReadOnlyMounts handles both overlayfs read-only mounts (by skipping the workdir mounts), and sets the "ro" option for other mount-types, but the reason why we're using a read-only mount is still relevant, so restoring that part of the comment.
(cherry picked from …

[release/1.7 backport] oci: partially restore comment on read-only mounts for uid/gid uses

---

oci/spec_opts.go

- backport of https://github.com/containerd/containerd/pull/8397
---
- relates to https://github.com/containerd/containerd/pull/8259
- relates to https://github.com/containerd/containerd/pull/8351 https://github.com/containerd/containerd/pull/8351#pullrequestreview-1375706340
Commit cab056226fd8cece14d334ebb4f9084d0e3a7f47 removed the tryReadonlyMounts utility, in favor of mounts.ReadOnlyMounts() that was added in commit daa3a7665eaa2e33a965376106e02d358925c132.
That change made part of the comment redundant, because mounts.ReadOnlyMounts handles both overlayfs read-only mounts (by skipping the workdir mounts), and sets the "ro" option for other mount-types, but the reason why we're using a read-only mount is still relevant, so restoring that part of the comment.
(cherry picked from …

[release/1.6 backport] oci: partially restore comment on read-only mounts for uid/gid uses

---

README.md
releases/README.md

- add the new testgrid dashboard information into the release doc and readme so that it can act as CI signal for a containerd release

doc: update CI signal information in README

---

code-of-conduct.md
docs/cri/config.md
docs/rootless.md
pkg/netns/netns_linux.go

The code base links to few external repos whose default branch changed from master to main. 
Although those links still work(github will redirect to the new default branch), seems it's better to update the link. 
Verified updated links work OK through browser. 
Signed-off-by: Tony Fang nhfang@amazon.com

[doc]Update external repo links that changed default branch to main

---

runtime/v2/runc/container.go

When `(*task.CheckpointTaskRequest).Options` is nil, it will panic
```
Apr 14 23:39:33 caiwei-master containerd[1219760]: panic: runtime error: invalid memory address or nil pointer dereference
Apr 14 23:39:33 caiwei-master containerd[1219760]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x79b9c0]
Apr 14 23:39:33 caiwei-master containerd[1219760]: goroutine 97 [running]:
Apr 14 23:39:33 caiwei-master containerd[1219760]: github.com/containerd/containerd/runtime/v2/runc.(*Container).Checkpoint(0xc00020c540?, {0xb706c0, 0xc000242060}, 0xc000340050)
Apr 14 23:39:33 caiwei-master containerd[1219760]:         /Users/icebergu/workspace/containerd/runtime/v2/runc/container.go:483 +0xc0
Apr 14 23:39:33 caiwei-master containerd[1219760]: …
```

runtime/shim: fix the nil checkpoint options

---

.github/workflows/ci.yml

Let's give a try to the new Github Merge Queues feature - [Pull request merge queue (public beta)](https://github.blog/changelog/2023-02-08-pull-request-merge-queue-public-beta/) and [Managing a merge queue](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#triggering-merge-group-checks-with-github-actions)

Run CI when adding a PR to a merge queue

---

go.mod
go.sum
integration/client/go.mod
integration/client/go.sum
vendor/github.com/opencontainers/runc/libcontainer/user/user.go
vendor/modules.txt

release notes: https://github.com/opencontainers/runc/releases/tag/v1.1.6
full diff: opencontainers/runc@v1.1.5...v1.1.6
This is the sixth patch release in the 1.1.z series of runc, which fixes
a series of cgroup-related issues.
Note that this release can no longer be built from sources using Go
1.16. Using a latest maintained Go 1.20.x or Go 1.19.x release is
recommended. Go 1.17 can still be used.
- systemd cgroup v1 and v2 drivers were deliberately ignoring UnitExist error
from systemd while trying to create a systemd unit, which in some scenarios
may result in a container not being added to the proper systemd unit and
cgroup.
- systemd cgroup v2 driver was incorrectly translating cpuset range from spec's
resources.cpu.cpus to systemd unit property (AllowedCPUs) in case of more
than 8 …

vendor: github.com/opencontainers/runc v1.1.7

---

container.go
integration/client/container_test.go
integration/client/go.mod
task.go
task_opts.go

cherry-pick: https://github.com/containerd/containerd/pull/8208
Added a new commit https://github.com/containerd/containerd/commit/c0e128624a8d6a02bb7d2ab3d29369f54791b68e that skips TestContainerStartWithAbsRuntimePath if the runtime is v1

[release/1.7] fix the task setting the runtime path

---

diff/proxy/differ.go

Unexpected results should not cause panic

Fix panic when differ returns empty result

---

.github/workflows/windows-hyperv-periodic.yml
.github/workflows/windows-periodic.yml

The critest binary build directory has changed following kubernetes-sigs/cri-tools#1085 to also include the OS and architecture, so the Azure-based Windows workflows needed to be updated to account for the new path.

Windows integration: fix critest binary path in Azure-based workflow.

---

ADOPTERS.md

Add faasd and actuated into the ADOPTERS file
Having spoken to @AkihiroSuda and @estesp at KubeCon, I wanted to get this PR up.
I've also heard from several people that they found the code in faasd useful as an example of how they could use containerd and containerd with CNI in their own projects.
* faasd is free and open source - and added in alphabetical order
* actuated is a hybrid SaaS service where customers run containerd and Firecracker on their own hosts, and the control plane and scheduler are managed - added later in the file since it's a commercial adopter.
See the PR commit diff for more details
Thanks for containerd 😄

Add faasd and actuated into the ADOPTERS file

---

.github/workflows/build-test-images.yml
.github/workflows/ci.yml
.github/workflows/codeql.yml
.github/workflows/images.yml
.github/workflows/nightly.yml
.github/workflows/release.yml
Vagrantfile
contrib/Dockerfile.test
script/setup/prepare_env_windows.ps1

go1.20.4 (released 2023-05-02) includes three security fixes to the html/template package, as well as bug fixes to the compiler, the runtime, and the crypto/subtle, crypto/tls, net/http, and syscall packages. See the Go 1.20.4 milestone on our issue tracker for details:
https://github.com/golang/go/issues?q=milestone%3AGo1.20.4+label%3ACherryPickApproved
release notes: https://go.dev/doc/devel/release#go1.20.4
full diff: https://github.com/golang/go/compare/go1.20.3...go1.20.4
from the announcement:
> These minor releases include 3 security fixes following the security policy:
>
> - html/template: improper sanitization of CSS values
>
>   Angle brackets (`<>`) were not considered dangerous characters when inserted
>   into CSS contexts. Templates containing multiple actions separated by a …

update go to go1.20.4, go1.19.9

---

pkg/cri/sbserver/container_stats_list_linux.go
pkg/cri/server/container_stats_list_linux.go

This is essentially the same change as https://github.com/containerd/containerd/pull/8302, but for the CRI server. 
Without this fix, the kubelet fails to collects stats with:
`time="2023-05-03T00:47:28.890947681Z" level=error msg="ListContainerStats failed" error="failed to convert to cri containerd stats format: failed to decode container metrics for \"6fb75f811841004943a338064d05f643b797afac8c09786551a0d5c0865c20b7\": failed to obtain cpu stats: unexpected metrics type: &Metrics{Pids:&PidsStat{Current:13,Limit:18446744073709551615,XXX_unrecognized:[],},CPU:&CPUStat{UsageUsec:1224890,UserUsec:1179817,SystemUsec:45073,NrPeriods:0,NrThrottled:0,ThrottledUsec:0,XXX_unrecognized:[],},Memory:&MemoryStat{Anon:12480512,File:8192,KernelStack:212992,Slab:260032,Sock:12288,Shmem:0,FileMapped:0,Fil …

cri: Fix umarshal metrics

---

pkg/cri/sbserver/container_stats_list_linux.go
pkg/cri/server/container_stats_list_linux.go

This is essentially the same change as https://github.com/containerd/containerd/pull/8335, but for the CRI server. 
Without this fix, the kubelet fails to collects stats with:
`time="2023-05-03T00:47:28.890947681Z" level=error msg="ListContainerStats failed" error="failed to convert to cri containerd stats format: failed to decode container metrics for \"6fb75f811841004943a338064d05f643b797afac8c09786551a0d5c0865c20b7\": failed to obtain cpu stats: unexpected metrics type: &Metrics{Pids:&PidsStat{Current:13,Limit:18446744073709551615,XXX_unrecognized:[],},CPU:&CPUStat{UsageUsec:1224890,UserUsec:1179817,SystemUsec:45073,NrPeriods:0,NrThrottled:0,ThrottledUsec:0,XXX_unrecognized:[],},Memory:&MemoryStat{Anon:12480512,File:8192,KernelStack:212992,Slab:260032,Sock:12288,Shmem:0,FileMapped:0,Fil …

[release/1.7] cri: Fix umarshal metrics

---

pkg/cri/opts/spec_opts.go

This pointer to an issue never got updated after the CRI plugin was absorbed into the main containerd repo as an in-tree plugin.

cri: update WithoutDefaultSecuritySettings comment

---

content/local/store.go
pkg/cri/opts/container.go
runtime/v2/shim_load.go

There was a couple uses of Readdir/ReadDir here where the only thing the return value was used for was the Name of the entry. This is exactly what Readdirnames returns, so we can avoid the overhead of making/returning a bunch of interfaces and calling lstat everytime in the case of Readdir(-1).
https://cs.opensource.google/go/go/+/refs/tags/go1.20.4:src/os/dir_unix.go;l=114-137

Change to Readdirnames for some cases

---

pkg/transfer/local/transfer.go
plugins/transfer/plugin.go

Backports for transfer service
#8272
#8416
#8466

[release/1.7] Transfer service backports

---

go.mod
go.sum
integration/client/go.mod
integration/client/go.sum
vendor/github.com/containerd/typeurl/v2/types.go
vendor/modules.txt

(cherry picked from commit ecb693ec746fc01d585f226504d681a64d2d124a)
cherry-pick: https://github.com/containerd/containerd/pull/8494
Note: `taskServer.Checkpoint` of containerd-shim-runc-* v1.7.0 may panic
https://github.com/containerd/containerd/blob/e39c5c4b3b1a620310526949696d2d307ec55498/runtime/v2/runc/container.go#L468-L479
**Due to https://github.com/containerd/containerd/issues/8392, v1.7.0 containerd will not access shim's Checkpoint, but other versions (<= v1.6.\* and >= v1.7.1) may cause panic for v1.7.0 shim**
shim v1.7.1+ that includes this pr will not panic due to this issue when accessing taskServer.Checkpoint

[release/1.7] bump typeurl to v2.1.1

---

.github/workflows/ci.yml
.golangci.yml
pkg/cri/sbserver/images/image_pull.go
pkg/cri/server/image_pull.go
remotes/docker/config/hosts.go
script/setup/install-dev-tools

Release note: https://github.com/golangci/golangci-lint/releases/tag/v1.52.2
`revive` seems to become (very) strict by the following newly added rules (seems related to https://github.com/mgechev/revive/pull/799). Especially `unused-parameter` reports a lot of "unused-parameter" errors (e.g. unused `ctx context.Context` argument on a function)
- if-return
- empty-block
- superfluous-else
- unused-parameter
- unreachable-code
- redefines-builtin-id
This commit disables them for now but let me know if we need them.
This commit also addresses the following linter errors:
```
remotes/docker/config/hosts.go:335:2: directive `//nolint:unused` is unused for linter "unused" (nolintlint)
//nolint:unused
^
pkg/cri/server/image_pull.go:346:38: directive `//nolint:staticcheck // TODO(thaJeztah): …
```

Bump up golangci-lint to v1.52.2

---

container.go

[Task(context.Context, cio.Attach) (Task, error)](https://github.com/containerd/containerd/blob/main/container.go#L62-L69) comment does not explicitly mention that we can load the IO for the running task.
this confusion occured [here](https://github.com/containerd/nerdctl/pull/2128#discussion_r1151888490)
**expected improvement :**
Add comment to explicitly mention that it is possible to Load the IO for the running task

improve container Task comment

---

.github/workflows/ci.yml

https://github.com/actions/setup-go/issues/368 and https://github.com/opencontainers/runc/pull/3820#issuecomment-1501426479 discuss issues with the cache key for actions/setup-go@v4.  Rather than reverting the upgrade to v4 (per discussion in https://github.com/containerd/containerd/pull/8372), disable caching explicitly.

.github: disable cache for actions/setup-go@v4

---

runtime/v2/shim_load.go

Follow-up to #8489. We don't need to call Close in the err and success cases, we can just do it after Readdirnames returns.
Thanks @fuweid

Simplify closing bundle dir fd

---

.mailmap
releases/v1.7.1.toml
version/version.go

Prepare release notes for v1.7.1
Hold for #8499
Full notes at https://gist.github.com/dmcgowan/cba095c327c70328f3787dbb31984d8b
----
Welcome to the v1.7.1 release of containerd!
The first patch release for containerd 1.7 includes many fixes to CRI
sandbox mode, various other fixes, runc update, and important fixes in
core dependencies such as ttrpc and typeurl.
* **Throw not supported error when UID or GID mappings provided** ([#8211](https://github.com/containerd/containerd/pull/8211))
* **Cleanup shim on start failure** ([#8282](https://github.com/containerd/containerd/pull/8282))
* **Fix premature close of CRI service when there are no CNI configuration monitors** ([#8282](https://github.com/containerd/containerd/pull/8282))
* **Avoid UID lookup from mount on Darwin** …

[release/1.7] Prepare release notes for v1.7.1

---

plugin/plugin.go
plugin/plugin_supported.go
plugin/plugin_unsupported.go

- updates https://github.com/containerd/containerd/issues/563
**Disclaimer: not 100% if we want all of these changes; I started this branch because I wanted to remove the Go 1.8 stub, but it turned out to be more complicated than that (see below)**; decided to push it as a branch either way for consideration.
- we don't support go < 1.8. this restriction as added because plugin support  requires go 1.8 or up, but with such old versions being EOL, this check was   rather redundant
- add back arm64 support; in 6bd0710831cb0796e903b7e9e41ca33214913620 (https://github.com/containerd/containerd/pull/645), non-amd64 was disabled, pending golang/go#17138, which was tracking arm64 support, and  is now resolved. It's unclear if architectures other than amd64 and arm64 are  supported, so keeping it …

plugin: remove go < 1.8 stub, enable on windows and arm64

---

pkg/cri/opts/spec_linux.go
pkg/cri/sbserver/container_create_linux.go
pkg/cri/sbserver/container_create_linux_test.go
pkg/cri/server/container_create_linux.go
pkg/cri/server/container_create_linux_test.go

This PR updates CRI and makes use of new CRI fields Config.CDIDevices to perform CDI injection.
Previously CDI device names were passed through annotations.
We don't remove annotation support just yet as we want to maintain compatibility with Containerd versions that only support CDI annotations.

CDI: Use CRI Config.CDIDevices field for CDI injection

---

archive/tar_opts_windows.go
snapshots/windows/windows.go

It seems that in certain situations, like having the containerd root and state on a file system hosted on a mounted VHDX, we need SeSecurityPrivilege when opening a file with winio.ACCESS_SYSTEM_SECURITY. This happens in the base layer writer in hcsshim when adding a new file.
Enabling SeSecurityPrivilege allows the containerd root to be hosted on a vhdx.
Potentially fixes #8206

Fix access denied on mounted vhdx root

---

snapshots/testsuite/issues.go

For https://github.com/containerd/fuse-overlayfs-snapshotter/pull/53#issuecomment-1543442048
> CI failing
> 
> ```
> $ go test -exec rootlesskit -test.v -test.root -test.run TestFUSEOverlayFS/Rename
> === RUN   TestFUSEOverlayFS
> === RUN   TestFUSEOverlayFS/Rename
> === PAUSE TestFUSEOverlayFS/Rename
> === CONT  TestFUSEOverlayFS/Rename
>     issues.go:142: Check snapshots failed: failed to create snapshot 2: failed to apply: rename /tmp/snapshot-suite-fuse-overlayfs-2521667602/work/prepare434549372/dir1 /tmp/snapshot-suite-fuse-overlayfs-2521667602/work/prepare434549372/dir2: invalid cross-device link
>     helpers.go:66: drwx------       4096 /tmp/snapshot-suite-fuse-overlayfs-2521667602
>     helpers.go:66: drwxrwxr-x       4096 /tmp/snapshot-suite-fuse-overlayfs-2521667602/root
> …
```

snapshots/testsuite: Rename: fix fuse-overlayfs incompatibility

---

snapshots/testsuite/issues.go

Cherry-pick:
- https://github.com/containerd/containerd/pull/8507

[release/1.7 backport] snapshots/testsuite: Rename: fix fuse-overlayfs incompatibility

---

pkg/cri/sbserver/container_create.go
pkg/cri/sbserver/container_create_linux.go
pkg/cri/sbserver/container_create_linux_test.go

The oci.WithUser option was being applied in container_create_linux.go
instead of the cross plat buildLinuxSpec method. There's been recent
work to try and make every spec option that can be applied on any platform
able to do so, and this falls under that. However, WithUser on linux platforms
relies on the containers SnapshotKey being filled out, which means the spec
option needs to be applied during container creation.
To make this a little more generic, I've created a new platformSpecOpts
method that handles any spec opts that rely on runtime state (rootfs mounted
for example) for some platforms, or just platform options that we still don't
have workarounds for to be able to specify them for other platforms
(apparmor, seccomp etc.) by internally calling the already existing …

CRI: Support Linux username for !linux platforms

---

script/setup/install-seccomp

Looks like the runc folks bumped almost a year ago
- https://github.com/search?q=repo%3Aopencontainers%2Frunc%202.5.4&type=code
- https://github.com/opencontainers/runc/pull/3481/files
Context: query on slack - https://cloud-native.slack.com/archives/CGEQHPYF4/p1684243817550399

Bump seccomp version to be the same as one in runc repo

---

services/tasks/local.go

when we call `ctr container checkpoint --task <container> <checkpoint-image>` multiple times to checkpoint the container, the checkpoint image will not  include `MediaTypeContainerd1CheckpointConfig`, `MediaTypeContainerd1Checkpoint ` and `MediaTypeContainerd1CheckpointOptions` layers
The checkpoint image content before fixing:
```json
{
"schemaVersion":2,
"manifests":[
{
"mediaType":"application/vnd.docker.distribution.manifest.v2+json",
"digest":"sha256:1a893424c6b027d8a00695250292acaedfe8934ecde540810eb3d95791f29b83",
"size":737,
"annotations":{
"io.containerd.image.name":"docker.io/library/ubuntu:latest",
"org.opencontainers.image.ref.name":"latest"
}
},
{
"mediaType":"application/vnd.oci.image.layer.v1.tar+gzip",
"digest":"sha256:f17dd931073b2c7c15fea1aabe34addde6aa303dfcb70ad4ac64b2f …
```

fix unable to checkpoint the container more than once

---

go.mod
go.sum
integration/client/go.mod
integration/client/go.sum
vendor/github.com/containerd/ttrpc/server.go
vendor/modules.txt

Includes fix for handling of wrapped errors
Backport similar to #8497 but from ttrpc 1.1

[release/1.6] Update ttrpc to 1.1.2

---

cmd/containerd/builtins/builtins_linux.go
cmd/containerd/builtins/builtins_unix.go
docs/snapshotters/README.md
snapshots/blockfile/blockfile.go
snapshots/blockfile/blockfile_loopsetup_test.go
snapshots/blockfile/blockfile_other_test.go
snapshots/blockfile/blockfile_test.go
snapshots/blockfile/plugin/plugin.go
snapshots/testsuite/testsuite.go
snapshots/testsuite/testsuite_unix.go
snapshots/testsuite/testsuite_windows.go

A simple generic snapshotter using block files. It is designed to be cross-platform similar to the generic native snapshotter. 
- It can be paired with a differ to unpack in environments that do not support mounting.
- Loopback mounts can be used for local mounts on Linux
- VM runtimes can utilize virtio-blk rather than virtio-fs
- Base scratch image can be provided with any configuration rather than relying on snapshotter to generate. Snapshot just disabled if no scratch image provided.
- Copying blockfiles is very efficient on filesystems which support reflink/CoW/clone
Similar to #3130

Add blockfile snapshotter

---

.github/workflows/build-test-images.yml
integration/images/volume-copy-up/Makefile
integration/images/volume-ownership/Makefile

This change updates the default windows image SKU used to the ```latest``` tag. This should always be around, and should be regularly updated to something close to the actual latest image available. For generating images, the ```latest``` tag should be safe to use.
We also disable provenance. See: https://github.com/docker/buildx/issues/1509#issuecomment-1378454396 
One important note before triggering this workflow. Github has introduced a new permissions system for ```ghcr.io```. Before running this workflow, someone with write access to the repo will have to navigate to https://ghcr.io/containerd/volume-copy-up and https://ghcr.io/containerd/volume-ownership and click on ```Package settings``` on the right hand side. Once there, under ```Actions repository access```, you will need to …

Fix image workflow

---

metadata/buckets.go

Related Sandbox API #6703 and some optimization
1. Add sandboxes object
2. Optimize indentation of parent and child objects
3. replace `//` to `/* ..*/` to avoid go fmt

[sandbox] Optimize metadata Schema notes to correctly match metadata structures

---

docs/remote-snapshotter.md

This commit fixes a broken link. This commit also updates the description about the image handler. It now mentions about
`github.com/containerd/containerd/pkg/snapshotters` package.

docs/remote-snapshotter.md: update links and description

---

cmd/containerd/command/main.go
pkg/cri/cri.go
pkg/cri/sbserver/service.go
pkg/cri/server/service.go
plugin/context.go
services/server/server.go

Fix: [#8468](https://github.com/containerd/containerd/issues/8468)
Added `RegisterReadiness` func to `InitContext` to allow plugins to register themselves as required plugins which will be waited for the readiness before systemd notification is sent. This PR only registers CRI plugin to address [#8468](https://github.com/containerd/containerd/issues/8468).

notify readiness when registered plugins are ready

---

contrib/ansible/cri-containerd.yaml
docs/cri/config.md
docs/cri/crictl.md
integration/images/image_list.go
integration/images/image_list.sample.toml
pkg/cri/config/config_unix.go
pkg/cri/config/config_windows.go

Upgrade `containerd` use `registry.k8s.io/pause` version default version to `3.9`.

upgrade registry.k8s.io/pause version

---

docs/NRI.md

These changes fix a spelling error found within the NRI plugin documentation (`NRI.md`) kept within the `docs` project directory.
In `docs/NRI.md`, the following spelling mistake was resolved:
* a misspelled word `respository` has been corrected to `repository`, [following Merriam-Webster's spelling of the word](https://www.merriam-webster.com/dictionary/repository).

Fix: Correct the spelling of repository within the NRI plugin documentation.

---

integration/image_pull_timeout_test.go

Fixes test which requires static content to match a GHCR-located image which was recently updated.
(cherry picked from commit 579b5596c592003f39078ea7bcb46fd2868286bd)

[release/1.7] Cherry-pick: Update volume-ownership image with latest hashes

---

mount/mount_linux.go
mount/mount_linux_test.go

This PR adds handling and a test case for a `commondir` of `.` which could cause a `slice bounds out of range` error when compacting `lowerdir`. 
This was reported by OSS-Fuzz: https://oss-fuzz.com/testcase-detail/6548471126818816

Add handling of a '.' commondir and bounds checking to mount_linux

---

image.go
images/image.go
pkg/unpack/unpacker.go

Several bits of code unmarshal image config JSON into an `ocispec.Image`, and then immediately create an `ocispec.Platform` out of it, but then discard the original image *and* miss several potential platform fields (most notably, `variant`).
Because [`ocispec.Platform`](https://github.com/opencontainers/image-spec/blob/50b6194995ebfd16d933ce16064898d6b7f60249/specs-go/v1/descriptor.go#L52-L72) is a strict subset of [`ocispec.Image`](https://github.com/opencontainers/image-spec/blob/50b6194995ebfd16d933ce16064898d6b7f60249/specs-go/v1/config.go#L80-L114), most of these can be updated to simply unmarshal the image config directly to `ocispec.Platform` instead, which allows these additional fields to be picked up appropriately.
We can use `tianon/raspbian` as a concrete reproducer to …

Fix several conversions of "ocispec.Image" to "ocispec.Platform"

---

cmd/ctr/commands/run/run_unix.go

This pull request adds two new flags to `ctr run` command. The flags allow specifying [cpuset](https://www.kernel.org/doc/Documentation/cgroup-v1/cpusets.txt) details. "cpus" defines the CPU cores the container is allowed to use, while "mems" defines the memory nodes. Having these flags in ctr allows testing cpu and memory pinning capabilities.

Add cpuset flags to 'ctr run'

---

pkg/cri/config/config.go

from this doc https://github.com/containerd/containerd/blob/main/docs/cri/registry.md#configure-registry-credentials get this info.

update auths code comment

---

.github/workflows/windows-hyperv-periodic.yml
.github/workflows/windows-periodic.yml

This patch switches the Azure-based Windows workflows to using the vanilla `2019-Datacenter` Azure SKU following the deprecation of the old specialized `2019-Datacenter-with-Containers-smalldisk` SKU which was previously used.

Windows Integration: Switch Azure-based CI to vanilla 2019 image.

---

cmd/ctr/commands/run/run_unix.go
integration/client/go.mod
integration/client/go.sum
oci/spec_opts.go
pkg/cri/opts/spec_linux.go
pkg/cri/opts/spec_nonlinux.go

This change adds support for requesting CDI devices to `ctr` command line.
This means that, assuming the relevant CDI specification exists, the following command can be used to run a container with access to the required device:
```
crt run --rm -ti --device=nvidia.com/gpu=all {{CONTAINER_ID}}
``` 
The requested devices are injected directly into the generated OCI runtime specification as `ctr` does not use the CRI.
This mirrors how device nodes are handled in that they are resolved locally and the edits are applied to the container config before calling the Create API.
Some minor cleanup / refactoring that makes this addition simpler was also done.
This builds on the work to add CDI support to the containerd server:
* https://github.com/containerd/containerd/pull/6654
* …

Add support for CDI devices to ctr run command

---

RELEASES.md
docs/cri/config.md
pkg/cri/config/config.go

As discussed in the issue https://github.com/containerd/containerd/issues/8596 It is a helpful feature at many places and no replacement readily available

Remove cni conf_template deprecation

---

cio/io_unix.go

PR fixes #8326 ([tested locally on my side](https://github.com/containerd/nerdctl/pull/2128#issuecomment-1491209753)). I'm not an expert of containerd though, so I'm not 100% sure if this has any negative side effects, and I appreciate any guidance on how this should be approached, thanks!

fix: cio.Cancel() should close the pipes

---

events/plugin/plugin.go
integration/build_local_containerd_helper_test.go
integration/client/go.mod
integration/client/go.sum
metadata/plugin/plugin.go
plugin/context.go
services/images/local.go
services/server/server.go

Events from the init context have been replaced by the events plugin and marked for removal in 2.0.

Remove events from init context

---

remotes/docker/resolver.go

Go deprecation comments must be formatted to have an empty comment line before them. Fix the formatting to make sure linters and editors detect that these are deprecated.

remotes/docker: ResolverOptions: fix deprecation comments

---

remotes/docker/resolver.go

- backport of https://github.com/containerd/containerd/pull/8619
Go deprecation comments must be formatted to have an empty comment line before them. Fix the formatting to make sure linters and editors detect that these are deprecated.
(cherry picked from commit 52997ea983fb8b655d4946552369d811fc3770de)

[release/1.6 backport] remotes/docker: ResolverOptions: fix deprecation comments

---

remotes/docker/resolver.go

- backport of https://github.com/containerd/containerd/pull/8619
Go deprecation comments must be formatted to have an empty comment line before them. Fix the formatting to make sure linters and editors detect that these are deprecated.
(cherry picked from commit 52997ea983fb8b655d4946552369d811fc3770de)

[release/1.7 backport] remotes/docker: ResolverOptions: fix deprecation comments

---

cio/io_unix.go

PR is a backport for #8334 (82ec62b).

[release/1.7] fix: cio.Cancel() should close the pipes

---

pkg/cri/sbserver/sandbox_stats_windows.go
pkg/cri/sbserver/sandbox_stats_windows_test.go
pkg/cri/server/sandbox_stats_windows.go
pkg/cri/server/sandbox_stats_windows_test.go

The [initial PR](https://github.com/containerd/containerd/pull/7099) had a check for nil metrics but after some refactoring in the PR the test case that was suppose cover HPC was missing a scenario where the metric was not nil but didn't contain any metrics. This fixes that case and adds a testcase to cover it.

Fix issue for HPC pod metrics

---

diff.go

- backport of https://github.com/containerd/containerd/pull/8460
⚠️ I had to adjust the patch because 3784c1c9170d8f3af247f95a34817250a1ca2b93 (https://github.com/containerd/containerd/pull/8399) is not in the 1.7 branch, and moved this function from diff.go to proxy/diff.go
^^ I also don't know if that means that this patch is not needed without the other PR in this branch (/cc @dmcgowan)
(cherry picked from commit 0d975230e1862110d7885d490bc8d20c9caada30)

[1.7 backport] Fix panic when remote differ returns empty result

---

.mailmap
releases/v1.7.2.toml
version/version.go

Full notes: https://gist.github.com/dcantah/a36f91855eb96f412c912896829b8c13
containerd 1.7.2
Welcome to the v1.7.2 release of containerd!
The second patch release for containerd 1.7 includes enhancements to CRI sandbox mode, 
Windows snapshot mounting support, and CRI and container IO bug fixes.
* **Publish sandbox events** ([#8613](https://github.com/containerd/containerd/pull/8613))
* **Make stats respect sandbox's platform** ([#8604](https://github.com/containerd/containerd/pull/8604))
* **Mount snapshots on Windows** ([#8616](https://github.com/containerd/containerd/pull/8616))
* **Notify readiness when registered plugins are ready** ([#8584](https://github.com/containerd/containerd/pull/8584))
* **Fix cio.Cancel() should close pipes** …

[release/1.7] Prepare release notes for v1.7.2

---

pkg/process/init.go
pkg/process/init_state.go
pkg/process/utils.go

Code optimization:
* Remove `atomicBool` from `pkg/process/utils.go` and use standard library `atomic.Bool`

Replace `atomicBool` with the standard library `atomic.Bool`

---

cmd/ctr/commands/commands.go
pkg/atomicfile/file.go
pkg/atomicfile/file_test.go
pkg/cri/sbserver/update_runtime_config.go
pkg/cri/server/update_runtime_config.go
runtime/v2/shim/util.go

The 10-containerd-net.conflist file generated from the conf_template should be written atomically so that partial writes are not visible to CNI plugins. This is accomplished by writing a temporary file, syncing, and renaming over the destination file name.
Partial/inconsistent writes can occur due to:
1. A CNI plugin attempting to read the file while containerd is writing it (both in the case of a newly-generated file or in the case of a re-generated file via a subsequent call to UpdateRuntimeConfig).
2. Concurrent calls to UpdateRuntimeConfig leading to multiple active writers of the same file
The above mechanism explicitly protects against (1) as all writes are to a file with a temporary name.
There is no explicit protection against multiple, concurrent CRI calls to UpdateRuntimeConfig. …

cri: write generated CNI config atomically

---

RELEASES.md
pkg/cri/config/config.go

Cherry-pick of PR #8606 missed the v1.7.2 milestone:
- #8638

RELEASES.md: de-deprecation of CNI conf_template will be v1.7.3

---

pkg/cri/sbserver/sandbox_stats_windows.go
pkg/cri/sbserver/sandbox_stats_windows_test.go
pkg/cri/server/sandbox_stats_windows.go
pkg/cri/server/sandbox_stats_windows_test.go

Backport for https://github.com/containerd/containerd/pull/8626
cherry-pick of https://github.com/containerd/containerd/pull/8626/commits/738c4c6fa5198fe087fae831d71a1944cba8df7e
need slight modification due to 1.7 missing refactor of the tests (https://github.com/containerd/containerd/commit/4192ca8f8cd6e35d56b65818cef4131c72be10f9)

[release/1.7] Fix issue for HPC pod metrics

---

BUILDING.md

Document the protocol buffer setup script and make note of external proto files that must be added for successful generation. Addresses issue #8551.

Document Protocol Buffer Setup

---

pkg/cri/sbserver/sandbox_stats_windows.go
pkg/cri/sbserver/sandbox_stats_windows_test.go
pkg/cri/server/sandbox_stats_windows.go
pkg/cri/server/sandbox_stats_windows_test.go

When a container is just created, exited state the container will not have stats. A common case for this in k8s is the init containers for a pod. They will be present in the listed containers but will not have a running task and there for no stats.
This type of check to prevent querying containers there were not in valid state was in kubelet at some point: https://github.com/kubernetes/kubernetes/issues/98509

[CRI] Windows Pod Stats: Add a check to skip stats for containers that are not running.

---

pkg/transfer/local/progress.go

Need to release `ticker` when `HandleProgress` has finished. 
It will cause memory leak if we do not stop it.

fix release `ticker` correctly in `HandleProgress`

---

task.go

The contract for `cio/io.go/IO` states that a call to `Close()` will always be preceded by a call to `Cancel()` -
https://github.com/containerd/containerd/blob/f3a07934b49bf142925a5913e3e19f3528eda0d2/cio/io.go#L59 which isn't being held up here.
Furthermore, the call to `Close()` here makes the subsequent `Wait()` moot, and causes issues to consumers (see: https://github.com/moby/moby/issues/45689) – basically, if we close before `Wait()`ing, there will be times where the pipes get closed while task IO (stdin/stdout/whatever) is still being piped, so we lose task output.
It seems from
https://github.com/containerd/containerd/blob/f3a07934b49bf142925a5913e3e19f3528eda0d2/task.go#L338 that the `Close()` should be called there, the call removed in this commit is unnecessary/erroneous.

task: don't `close()` io before `cancel()`

---

integration/images/image_list.go
integration/main_test.go
integration/volume_copy_up_test.go
pkg/cri/opts/container.go
pkg/cri/sbserver/container_create.go
pkg/cri/server/container_create.go
script/test/cri-integration.sh

Images may be created with a VOLUME stanza pointed to drive letters that are not C:. Currently, an image that has such VOLUMEs defined, will cause containerd to error out when starting a container.
This change skips copying existing contents to volumes that are not C:. as an image can only hold files that are destined for the C: drive of a container.
Fixes: https://github.com/containerd/containerd/issues/8171
Tests will be added in a separate PR, as we also need to update the [volume-copy-up image](https://github.com/containerd/containerd/tree/main/integration/images/volume-copy-up) to include a ```D:``` volume.

Fix non C volumes on Windows

---

integration/client/container_linux_test.go

I noticed while fixing up https://github.com/containerd/containerd/pull/8617 that `TestShimOOMScore` has no timeout, making it so that if it never receives the task exit event it's expecting, the test hangs for (many) minutes.

integration/client: add timeout to `TestShimOOMScore`

---

.github/workflows/ci.yml

This reverts commit fa2016d58ada2438d0af51a522b528dc228cb4ba
Previously we were downgrading mingw to work around an issue in the race detector in Go on Windows when used with a newer version of GCC. The issue was first reported here:
golang/go#46099
Shortly after the release of 1.19 someone had commented this issue was solved for them, and after trying it out in some test runs on actions machines, it seems to be the case. Disabling ASLR got things in order, and PIE was disabled for -race builds in 1.19, so this is likely the reason things work now:
https://github.com/golang/go/commit/0c7fcf6bd1fd8df2bfae3a482f1261886f6313c1.
The downgrade was mostly harmless except for two shortcomings:
1. It took quite a while for the package to get downloaded+installed.
2. Chocolatey would frequently …

[release/1.6] Revert "Downgrade MinGW to version 10.2.0"

---

client.go
integration/client/container_test.go
pkg/cri/sbserver/service.go
pkg/cri/server/service.go
plugin/plugin.go
remotes/docker/handler.go
runtime/v2/manager.go
task.go

Really tiny gains here, and doesn't significantly impact readability:
BenchmarkSprintf
BenchmarkSprintf-10    11528700     91.59 ns/op   32 B/op  1 allocs/op
BenchmarkConcat
BenchmarkConcat-10    100000000     11.76 ns/op    0 B/op  0 allocs/op

replace some basic uses of fmt.Sprintf()

---

cmd/containerd/command/publish.go
container.go
container_checkpoint_opts.go
container_opts.go
events.go
integration/sandbox_run_rollback_test.go
metadata/containers.go
pkg/cri/sbserver/container_update_resources.go
pkg/cri/sbserver/events.go
pkg/cri/sbserver/events_test.go
pkg/cri/sbserver/podsandbox/sandbox_run_test.go
pkg/cri/server/container_update_resources.go
pkg/cri/server/events.go
pkg/cri/server/events_test.go
pkg/cri/server/sandbox_run_test.go
pkg/transfer/archive/exporter.go
pkg/transfer/archive/importer.go
pkg/transfer/registry/registry.go
pkg/transfer/streaming/stream.go
pkg/transfer/streaming/writer.go
protobuf/any.go
runtime/v2/shim/publisher.go
sandbox.go
services/transfer/service.go
task.go

Avoid shadowing / confusion with Go's "any" built-in type.

avoid "any" as variable name

---

integration/containerd_image_test.go
pkg/cri/labels/labels.go
pkg/cri/sbserver/images/image_pull.go
pkg/cri/sbserver/images/image_pull_test.go
pkg/cri/sbserver/images/image_status.go
pkg/cri/sbserver/images/service.go
pkg/cri/server/helpers.go
pkg/cri/server/image_pull.go
pkg/cri/server/image_pull_test.go
pkg/cri/server/image_status.go
pkg/cri/store/image/image.go

Signed-off-by: Aditi Sharma <adi.sky17@gmail.com>
This PR marks containerd sandbox/pause image as Pinned image, pinned images are not garbage collected by Kubelet.
Currently it only marks sandbox image as pinned.
fixes: https://github.com/containerd/containerd/issues/6352

CRI Pinned image support

---

.github/workflows/ci.yml

update vagrant box to fedora 37 as fedora 36 went EOL on 16-05-2023

[release/1.6] update test box to fedora 37

---

platforms/cpuinfo.go
platforms/cpuinfo_linux.go
platforms/cpuinfo_linux_test.go
platforms/cpuinfo_other.go
platforms/database.go

The PR #7636 to fix cpu architecture detection issue on emulated ARM platform was part of release 1.7, but not in 1.6.
Since docker cli and many others utilize containerd/platforms to [parse platform info](https://github.com/docker/cli/blob/master/cli/command/container/create.go#L10) and depends on [containerd 1.6](https://github.com/docker/cli/blob/master/vendor.mod#LL13C6-L13C6), we should backport it to the long term support release. 
This PR is to cherry pick #7636 into release 1.6.

[release/1.6] Fix cpu architecture detection issue on emulated ARM platform

---

snapshots/overlay/overlay.go
snapshots/overlay/overlay_test.go
snapshots/overlay/plugin/plugin.go

Allows default mount options to be provided through configuration. This allows configurations to use options supported by the kernel without requiring an update to the overlay plugin.
Note: this still wouldn't be appropriate for the volatile option, an additional change would be necessary to strip the "volatile" option on temp mounts.  Such as https://github.com/containerd/containerd/pull/8402/files#diff-5adff636c3210a8801cbc84d4431a5ee66e8bab1985a88fd59c6e895b604914c

[overlay] add configurable mount options to overlay snapshotter

---

integration/client/convert_test.go

Microsoft announced the removal of nondistributable layers from their images today. This makes the convert test fail since it assumes the first layer is nondistributable on Windows during the test.

No more nondistributable layers in MS registry

---

.github/workflows/ci.yml

Remove `push` event (e.g. don't run the CI once merged). Instead it'll be added to the merge queue and built from there.
https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#triggering-merge-group-checks-with-github-actions

Don't run CI on push

---

runtime/v2/runc/container.go
runtime/v2/runc/task/service.go

- Fixes #8557 
- Closes #8598 
eventSendMu is causing severe lock contention when multiple processes start and exit concurrently. Replace it with a different scheme for maintaining causality w.r.t. start and exit events for a process which does not rely on big locks for synchronization.
Keep track of all processes for which a Task(Exec)Start event has been published and have not yet exited in a map, keyed by their PID. Processing exits then is as simple as looking up which process corresponds to the PID. If there are no started processes known with that PID, the PID must either belong to a process which was started by s.Start() and before the s.Start() call has added the process to the map of running processes, or a reparented process which we don't care about. Handle the former case by …

runtime/v2/runc: handle early exits w/o big locks

---

pkg/cri/sbserver/sandbox_stats_windows.go
pkg/cri/sbserver/sandbox_stats_windows_test.go
pkg/cri/server/sandbox_stats_windows.go
pkg/cri/server/sandbox_stats_windows_test.go

backport for #8633
Cherry-pick of 28a5199ff61ad4d90cbb692b2bdc4bc0ba30b43b
need slight modification of tests due to 1.7 missing refactor of the tests (https://github.com/containerd/containerd/commit/4192ca8f8cd6e35d56b65818cef4131c72be10f9)

[release/1.7] [cri] Windows Pod Stats: Add a check to skip stats for containers that are not running

---

integration/client/convert_test.go

Microsoft announced the removal of nondistributable layers from their images today. This makes the convert test fail since it assumes the first layer is nondistributable on Windows during the test.
(cherry picked from commit 38b0f970f01846fb201a1bbe0dded1ad5c61b44f)

[release/1.7] cherry-pick: No more nondistributable layers in MS registry

---

integration/client/convert_test.go

Microsoft announced the removal of nondistributable layers from their images today. This makes the convert test fail since it assumes the first layer is nondistributable on Windows during the test.
(cherry picked from commit 38b0f970f01846fb201a1bbe0dded1ad5c61b44f)

[release/1.6] cherry-pick: No more nondistributable layers in MS registry

---

test/build.sh

/cc @dims 
The change in https://github.com/kubernetes/test-infra/pull/29824 failed because of an unbound variable.
Now, this change requires some changes in the jobs that grab containerd binaries from GCS.
```
REDACTED  C02CW0CDP3YY  ~  Desktop  Git  test-infra   kubetest2  1⚑  $  grep -r containerd-staging .
./jobs/e2e_node/containerd/containerd-release-1.7/env:CONTAINERD_DEPLOY_PATH: 'cri-containerd-staging/containerd/release-1.7'
./jobs/e2e_node/containerd/containerd-release-1.6/env:CONTAINERD_DEPLOY_PATH: 'cri-containerd-staging/containerd/release-1.6'
./jobs/e2e_node/containerd/containerd-release-1.6-presubmit/env:CONTAINERD_DEPLOY_PATH: 'cri-containerd-staging'
./jobs/e2e_node/containerd/containerd-main-presubmit/env:CONTAINERD_DEPLOY_PATH: 'cri-containerd-staging' …
```

Fix unbound variable used by Prow

---

runtime/v2/runc/container.go
runtime/v2/runc/task/service.go

- backport of https://github.com/containerd/containerd/pull/8617
- fixes https://github.com/containerd/containerd/issues/8557
:warning: ran into conflicts in `service.handleProcessExit` / `service.checkProcesses`, due to these commits not being in the 1.6 branch;
- Cleanup logrus imports https://github.com/containerd/containerd/commit/6f34da5f80f8e56ec6b0449a163af5d5096af50a
- Remove gogoproto.stdtime https://github.com/containerd/containerd/commit/80b825ca2ce0f4e9c1618303cbbc043448fe9515
----
eventSendMu is causing severe lock contention when multiple processes start and exit concurrently. Replace it with a different scheme for maintaining causality w.r.t. start and exit events for a process which does not rely on big locks for synchronization.
Keep track of all processes for which a …

[release/1.6 backport] runtime/v2/runc: handle early exits w/o big locks

---

services/streaming/service.go

Use a `*typeurl.Any` and nil pointer to indicate if the marshal result is saved.
Another approach might be just marshal the empty response as part of `InitFn`? 🤔️
```golang
var emptyResponse typeurl.Any
...
InitFn: func(ic *plugin.InitContext) (interface{}, error) {
...
emptyResponse, err = typeurl.MarshalAny(&ptypes.Empty{})
return nil, err
}
...
return &service{manager: i.(streaming.StreamManager)}, nil
},
```

Save marshalled empty response in streaming service

---

metadata/content.go

Current implmentation iterates the label bucket to check if `labels.LabelSharedNamespace` exists and is `true`. I think we can get by key directly.

Remove unnecessary label bucket loop

---

image.go
images/archive/exporter.go
images/image.go

It might be a personal preference, the `ConfigPlatform` helper is duplicated 3 times so might be good to move to a separate helper func.
It also removes a duplicated digest validate call.

Dedup config platform helper

---

client.go
import.go
task.go
task_opts.go

This PR removes `task.writeIndex` which is duplicated with the same helper in `client.go` (`writeIndex`).
Also move `decodeIndex` to `client.go` to collocate it with `writeIndex`.

Remove duplicated `writeIndex` func

---

pkg/cri/sbserver/helpers_windows.go
pkg/cri/server/helpers_windows.go

https://github.com/golang/go/issues/32088 was never accepted or implemented in 1.14.

Reword Windows file related TODO

---

pkg/epoch/epoch.go
pkg/epoch/epoch_test.go

- related: https://github.com/docker/buildx/pull/1908
Teeny-tiny optimizations:
BenchmarkSprintf-10       37735996    32.31  ns/op  0 B/op  0 allocs/op
BenchmarkItoa-10         591945836     2.031 ns/op  0 B/op  0 allocs/op
BenchmarkFormatUint-10   593701444     2.014 ns/op  0 B/op  0 allocs/op
These tests were failing on my macOS; could be the precision issue (like on
Windows), or just because they're "too fast".
=== RUN   TestSourceDateEpoch/WithoutSourceDateEpoch
epoch_test.go:51: 
Error Trace:	/Users/thajeztah/go/src/github.com/containerd/containerd/pkg/epoch/epoch_test.go:51
Error:      	Should be true
Test:       	TestSourceDateEpoch/WithoutSourceDateEpoch
Messages:   	now: 2023-06-23 11:47:09.93118 +0000 UTC, v: 2023-06-23 11:47:09.93118 +0000 UTC
This patch:
- updates the …

pkg/epoch: extract parsing SOURCE_DATE_EPOCH to a function

---

metadata/gc.go

This makes it easier to debug GC-related issues, where a reference is unexpectedly released.

log when a lease expires

---

integration/client/container_test.go

I think NullIO is fine on Windows now. We have it as an option in ctr, it's used for the pod sandbox container in CRI, and the code doesn't listen on pipes if the fifo paths are empty. Lets see if CI agrees..

Integration: Align empty IO func on Windows

---

Makefile

There was a todo for the windows variant of dependency installation that hinted at making an install-hcsshim.sh script, however Windows today doesn't rely on a standalone OCI runtime binary that gets invoked by the shim. Rather, container creation/management is all handled by the shim itself in-proc. Due to this, `make` or `make binaries` basically fulfills that purpose as it clones hcsshim and builds the shim along with containerd.
If anyone knows of some other dependencies that are required (or nice to haves) for windows let me know and we can hi-jack this PR to add them instead.

Makefile: Remove hcsshim related TODO

---

log/context.go

Partial backport of https://github.com/containerd/containerd/pull/8143, to make consuming `github.com/containerd/containerd/log` easier for those on the 1.6 LTS branch. Given the original commit is large and invasive, it seemed better to go for the direct result, rather than make a dirty cherry-pick (and miss many usages in this branch).
Motivated in large part by https://github.com/moby/moby/pull/45799, but likely useful to other projects as well.
The original PR body is reproduced below:
---
When logging with custom fields, like:
```go
log.G(ctx).WithFields(logrus.Fields{ ... })...
```
you're forced to do two imports
```go
"github.com/containerd/containerd/log"
"github.com/sirupsen/logrus"
```
This PR adds a type alias to log package, so we end up with just one import:
```go …
```

[1.6] Add Fields type alias to log package

---

script/setup/install-runhcs-shim

cherrypick #7989 (clean)
Adding support to run install hcsshim from the local clone. If local not available the clone from the repo.
(cherry picked from commit 77e51e9b03dc0e308ff8349d672c32e7865ccdf2 and b9b44ed5c537382c092048bc089be227a7627401 and squashed)

[release/1.6 backport] Adding support to run hcsshim from local clone

---

script/setup/install-critools

critools 1.27.0 uses ginkgo 2.9.2 https://github.com/kubernetes-sigs/cri-tools/blob/v1.27.0/go.mod#L12.
This can avoid those ginkgo warning in CI (https://github.com/containerd/containerd/pull/8752#issuecomment-1611334816).
https://github.com/containerd/containerd/actions/runs/5401559918/jobs/9811676884

Update ginkgo to match cri-tools' version

---

client.go
cmd/ctr/commands/images/convert.go
cmd/ctr/commands/images/export.go
cmd/ctr/commands/images/pull.go
pkg/transfer/local/push.go
platforms/platforms.go
runtime/v2/manager.go

Often we need to parse a list of platform strings, so this PR adds a `ParseAll` helper in `platforms` package to do this and reduce some duplication.

Add a platform.ParseAll helper

---

script/setup/install-critools

cherry pick https://github.com/containerd/containerd/pull/8758
Update ginkgo version to match cri-tools and avoid deprecation warning in CI.

[release/1.6 backport] Update ginkgo to match cri-tools' version

---

script/setup/install-critools

cherry pick https://github.com/containerd/containerd/pull/8758
Update ginkgo version to match cri-tools and avoid deprecation warning in CI.

[release/1.7 backport] Update ginkgo to match cri-tools' version

---

integration/client/container_linux_test.go

backports https://github.com/containerd/containerd/pull/8664

[release/1.7 backport] integration/client: add timeout to `TestShimOOMScore`

---

go.mod
go.sum
integration/client/go.mod
integration/client/go.sum
vendor/github.com/containerd/cgroups/v3/README.md
vendor/github.com/containerd/cgroups/v3/cgroup1/blkio.go
vendor/github.com/containerd/cgroups/v3/cgroup1/cgroup.go
vendor/github.com/containerd/cgroups/v3/cgroup1/control.go
vendor/github.com/containerd/cgroups/v3/cgroup1/memory.go
vendor/github.com/containerd/cgroups/v3/cgroup1/opts.go
vendor/github.com/containerd/cgroups/v3/cgroup1/pids.go
vendor/github.com/containerd/cgroups/v3/cgroup1/rdma.go
vendor/github.com/containerd/cgroups/v3/cgroup1/systemd.go
vendor/github.com/containerd/cgroups/v3/cgroup1/utils.go
vendor/github.com/containerd/cgroups/v3/cgroup1/v1.go
vendor/github.com/containerd/cgroups/v3/cgroup2/devicefilter.go
vendor/github.com/containerd/cgroups/v3/cgroup2/manager.go
vendor/github.com/containerd/cgroups/v3/cgroup2/utils.go
vendor/modules.txt

This brings in a ton of great improvements, most notably for the containerd daemon is performance improvements for cgroups1 and 2 for gathering stats, as well as some fixes for enabling controllers and deleting v1 cgroups.
Relevant work for the daemon:
1. https://github.com/containerd/cgroups/pull/293
2. https://github.com/containerd/cgroups/pull/296
3. https://github.com/containerd/cgroups/pull/281
4. https://github.com/containerd/cgroups/pull/291
5. https://github.com/containerd/cgroups/pull/278
6. https://github.com/containerd/cgroups/pull/283

go.mod: Update cgroups to 3.0.2

---

api/services/diff/v1/diff.pb.go
api/services/diff/v1/diff.proto
archive/tar.go
archive/tar_test.go
diff/diff.go

The whiteout timestamps are no longer set to the source date epoch. The source date epoch still applies to non-whiteout files.
Discussion happened in https://github.com/moby/buildkit/pull/3560#discussion_r1247003628

archive: use 1970-01-01 as the whiteout timestamp

---

.github/workflows/nightly.yml

since libseccomp is required only for building runc and we are only building containerd binaries in nightly, the libseccomp-dev dependency is removed

ci: remove libseccomp-dev installation for nightly

---

runtime/v2/runc/container.go
runtime/v2/runc/task/service.go

- backport of #8617 
- fixes #8557 
⚠️ ran into a conflict in `service.handleProcessExit` / `service.checkProcesses`, due to commit 6f34da5f80f8e56ec6b0449a163af5d5096af50a not being in the 1.7 branch.
-----
eventSendMu is causing severe lock contention when multiple processes start and exit concurrently. Replace it with a different scheme for maintaining causality w.r.t. start and exit events for a process which does not rely on big locks for synchronization.
Keep track of all processes for which a Task(Exec)Start event has been published and have not yet exited in a map, keyed by their PID. Processing exits then is as simple as looking up which process corresponds to the PID. If there are no started processes known with that PID, the PID must either belong to a process which was started …

[release/1.7 backport] runtime/v2/runc: handle early exits w/o big locks

---

runtime/events.go
runtime/v2/runc/task/service.go
runtime/v2/runc/util.go

Every shim implementation needs to select a correct publisher topic when posting events, so move it out of Linux-only runc code to the place where other shims can also use it
Otherwise, shims have to copy-paste this code. For example, see runj: https://github.com/samuelkarp/runj/blob/8158e558a361aff1f265a8feed7ad765da5c61b5/containerd/shim.go#L144-L172

Move GetTopic function out of runc shim

---

go.mod
go.sum
integration/client/go.mod
integration/client/go.sum
vendor/github.com/containerd/cgroups/v3/README.md
vendor/github.com/containerd/cgroups/v3/cgroup1/blkio.go
vendor/github.com/containerd/cgroups/v3/cgroup1/cgroup.go
vendor/github.com/containerd/cgroups/v3/cgroup1/control.go
vendor/github.com/containerd/cgroups/v3/cgroup1/memory.go
vendor/github.com/containerd/cgroups/v3/cgroup1/opts.go
vendor/github.com/containerd/cgroups/v3/cgroup1/pids.go
vendor/github.com/containerd/cgroups/v3/cgroup1/rdma.go
vendor/github.com/containerd/cgroups/v3/cgroup1/systemd.go
vendor/github.com/containerd/cgroups/v3/cgroup1/utils.go
vendor/github.com/containerd/cgroups/v3/cgroup1/v1.go
vendor/github.com/containerd/cgroups/v3/cgroup2/devicefilter.go
vendor/github.com/containerd/cgroups/v3/cgroup2/manager.go
vendor/github.com/containerd/cgroups/v3/cgroup2/utils.go
vendor/modules.txt

This brings in a ton of great improvements, most notably for the containerd daemon is performance improvements for cgroups1 and 2 for gathering stats, as well as some fixes for enabling controllers and deleting v1 cgroups.
Relevant work for the daemon:
1. https://github.com/containerd/cgroups/pull/293
2. https://github.com/containerd/cgroups/pull/296
3. https://github.com/containerd/cgroups/pull/281
4. https://github.com/containerd/cgroups/pull/291
5. https://github.com/containerd/cgroups/pull/278
6. https://github.com/containerd/cgroups/pull/283

[release/1.7] go.mod: Update cgroups to 3.0.2

---

contrib/diffservice/service.go
contrib/snapshotservice/service.go
diff/proxy/differ.go
mount/mount.go
oci/spec.go
pkg/transfer/archive/exporter.go
pkg/transfer/image/imagestore.go
platforms/platforms.go
services/diff/local.go
services/introspection/local.go
services/snapshots/service.go
snapshots/proxy/proxy.go
snapshots/snapshotter.go

In many of the core packages we have local types, and then their corresponding over the wire structures used for folks interacting via GRPC. In all these cases we have duplicated code that handles the conversions from our internal types to the generated structures. Ideally these conversions could just live next to the definitions for the internal types, and that's what this change sets out to do. I split this into four commits to make it easier if some of these aren't wanted, but the commits contain helpers to do conversions for:
1. mount (Mount)
2. oci (Descriptor)
3. snapshots (Kind, Usage, Info)
4. platforms ([]Platform)

Add From/ToProto helpers 

---

integration/client/container_checkpoint_test.go
integration/client/container_linux_test.go
integration/client/container_test.go

All of the tests using this didn't need stdin/err (one of them not even stdout), so we can just leave them "empty" and change to a withStdout naming to make it more obvious.

integration/client: Rework withBytesBuffers

---

.github/workflows/nightly.yml

since libseccomp is required only for building runc and we are only building containerd binaries in nightly, the libseccomp-dev dependency is removed. Foreign arch repositories are now removed since crossbuild-essential-* packages are {arm64, ppc64el,..} cross compiler packages for amd64 and arch specific repositories are not required.
clean cherry-pick of #8768 
(cherry picked from commit a9cb6090e2a2abe2b8625c60e4dee499e9291fb3)

[release/1.7 backport] ci: remove libseccomp-dev installation for nightly

---

cmd/ctr/commands/content/content.go
remotes/docker/fetcher.go
remotes/resolver.go

accept mediatype header is required for some layers, add additional field for client.
Fixes #8743

remotes: allow FetchByDigest client to pass mediatype as header

---

.github/workflows/build-test-images.yml
.github/workflows/ci.yml
.github/workflows/codeql.yml
.github/workflows/images.yml
.github/workflows/nightly.yml
.github/workflows/release.yml
Vagrantfile
contrib/Dockerfile.test
script/setup/prepare_env_windows.ps1

go1.20.5 (released 2023-06-06) includes four security fixes to the cmd/go and runtime packages, as well as bug fixes to the compiler, the go command, the runtime, and the crypto/rsa, net, and os packages. See the Go 1.20.5 milestone on our issue tracker for details:
https://github.com/golang/go/issues?q=milestone%3AGo1.20.5+label%3ACherryPickApproved
full diff: https://github.com/golang/go/compare/go1.20.4...go1.20.5
- cmd/go: cgo code injection The go command may generate unexpected code at build time when using cgo. This may result in unexpected behavior when running a go program which uses cgo.
This may occur when running an untrusted module which contains directories with newline characters in their names. …

update go to go1.20.5, go1.19.10

---

cio/io.go
runtime/restart/monitor/change.go

The nerdctl run/create --restart always -dt with tty does not automatically restart. When the process of the container be killed, the containerd shows log :
```
error="failed to create shim task: OCI runtime create failed: runc create failed: cannot allocate tty if runc will detach without setting console socket: unknown"
```
Because the spec contains the {terminal : true} , it cannot be started successfully.
So the PR is to fix https://github.com/containerd/nerdctl/issues/2296 , like the same way as https://github.com/containerd/containerd/pull/7673

Fix the automatically restart issue when using LogURI and Terminal together

---

plugins/sandbox/controller.go
sandbox/controller.go
sandbox/proxy/controller.go

We'd wanted to swap to mount.Mount after target was introduced. That time is now :)
This funnily enough was what led to the rabbit hole of https://github.com/containerd/containerd/pull/8757 as I didn't want to add local from/toProto functions *again* just for this.

Sandbox: Change to mount.Mount for CreateOptions

---

pkg/cri/sbserver/podsandbox/sandbox_run_linux.go
pkg/cri/server/sandbox_run_linux.go
pkg/cri/server/sandbox_run_linux_test.go

userns.RunningInUserNS() checks if the code calling that function is running inside a user namespace. But we need to check if the container we will create will use a user namespace, in that case we need to disable the sysctl too (or we would need to take the userns mapping into account to set the IDs).
This was added in PR:
https://github.com/containerd/containerd/pull/6170/
And the param documentation says it is not enabled when user namespaces are in use:
https://github.com/containerd/containerd/pull/6170/files#diff-91d0a4c61f6d3523b5a19717d1b40b5fffd7e392d8fe22aed7c905fe195b8902R118
I'm not sure if the intention was to disable this if containerd is running inside a userns (rootless, if that is even supported) or just when the pod has user namespaces.
Out of an abundance of caution, I'm …

Fix net.ipv4.ping_group_range with userns

---

pkg/cri/sbserver/podsandbox/sandbox_run_linux.go
pkg/cri/server/sandbox_run_linux.go
pkg/cri/server/sandbox_run_linux_test.go

This is a backport of #8779 for release/1.7. This bug was triggered with containerd 1.7.1 and k3s, so backporting it to the 1.7 branch

[release/1.7] Fix net.ipv4.ping_group_range with userns

---

.cirrus.yml

- addresses https://github.com/containerd/containerd/pull/8714#issuecomment-1619859423
I saw Cirrus CI / Vagrant BOX:rockylinux/8@5.0.0 failing during setting up Vagrant, which may be due to other scripts provisioning the machine;
Reading package lists...
apt-get install -y libvirt-daemon libvirt-daemon-system vagrant vagrant-libvirt
E: Could not get lock /var/lib/dpkg/lock-frontend. It is held by process 2496 (apt-get)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), is another process using it?
Configure dpkg to wait for locks to be released instead of failing. I used 60 second as timeout, which is relatively long, but given that the Vagrant checks are known to take some time to run, is probably fine.

Cirrus CI: configure apt-get to wait for locks

---

snapshots/blockfile/blockfile_loopsetup_test.go

Modify the loopback size in the blockfile snapshotter test setup. Set the loopback size to 16MB when the page size is greater than 4096. This prevents smaller storage devices from running out of free space while the test is running. Addresses issue #8767.

Modify loopback size

---

remotes/docker/resolver.go
remotes/docker/resolver_test.go

Backport https://github.com/containerd/containerd/pull/8748 to 1.6
Fix #8742
It can be reproduced with the added test:
```shell
$ go test -race ./remotes/docker/...
?       github.com/containerd/containerd/remotes/docker/schema1 [no test files]
==================
WARNING: DATA RACE
Read at 0x00c0003e08a0 by goroutine 189:
runtime.mapaccess2_faststr()
/usr/local/go/src/runtime/map_faststr.go:108 +0x0
github.com/containerd/containerd/remotes/docker.NewResolver()
/home/azureuser/code/containerd/remotes/docker/resolver.go:157 +0x22c
github.com/containerd/containerd/remotes/docker.runBasicTest()
...
$ go test -race ./remotes/docker/...
?       github.com/containerd/containerd/remotes/docker/schema1 [no test files]
ok      github.com/containerd/containerd/remotes/docker 0.677s
ok …
```

[release/1.6] Resolve docker.NewResolver race condition

---

remotes/docker/resolver.go
remotes/docker/resolver_test.go

Backport #8748 to 1.7
Fix #8742
It can be reproduced with the added test:
```shell
$ go test -race ./remotes/docker/...
?       github.com/containerd/containerd/remotes/docker/schema1 [no test files]
==================
WARNING: DATA RACE
Read at 0x00c0003e08a0 by goroutine 189:
runtime.mapaccess2_faststr()
/usr/local/go/src/runtime/map_faststr.go:108 +0x0
github.com/containerd/containerd/remotes/docker.NewResolver()
/home/azureuser/code/containerd/remotes/docker/resolver.go:157 +0x22c
github.com/containerd/containerd/remotes/docker.runBasicTest()
...
$ go test -race ./remotes/docker/...
?       github.com/containerd/containerd/remotes/docker/schema1 [no test files]
ok      github.com/containerd/containerd/remotes/docker 0.677s
ok      github.com/containerd/containerd/remotes/docker/auth …
```

[release/1.7] Resolve docker.NewResolver race condition

---

pkg/cri/sbserver/sandbox_stats_linux.go
pkg/cri/sbserver/sandbox_stats_list.go
pkg/cri/sbserver/sandbox_stats_windows.go
pkg/cri/sbserver/sandbox_stats_windows_test.go
pkg/cri/server/sandbox_stats_linux.go
pkg/cri/server/sandbox_stats_list.go
pkg/cri/server/sandbox_stats_windows.go
pkg/cri/server/sandbox_stats_windows_test.go

When the pods are transitioning there are several cases where containers might not be in valid state. There were several cases where the stats where failing hard but we should just continue on as they are transient and will be picked up again when kubelet queries for the stats again.
I've found these after running the e2e tests in https://github.com/kubernetes/kubernetes/pull/116968 several times.

[cri] Handle pod transition states gracefully while listing pod stats

---

.github/workflows/build-test-images.yml
.github/workflows/ci.yml
.github/workflows/codeql.yml
.github/workflows/images.yml
.github/workflows/nightly.yml
.github/workflows/release.yml
Vagrantfile
contrib/Dockerfile.test
script/setup/prepare_env_windows.ps1

go1.19.10 (released 2023-06-06) includes four security fixes to the cmd/go and runtime packages, as well as bug fixes to the compiler, the go command, and the runtime. See the Go 1.19.10 milestone on our issue tracker for details:
https://github.com/golang/go/issues?q=milestone%3AGo1.19.10+label%3ACherryPickApproved
full diff: https://github.com/golang/go/compare/go1.19.9...go1.19.10
- cmd/go: cgo code injection The go command may generate unexpected code at build time when using cgo. This may result in unexpected behavior when running a go program which uses cgo.
This may occur when running an untrusted module which contains directories with newline characters in their names. Modules which are retrieved using …

[release/1.6] update go to go1.19.10

---

.github/workflows/build-test-images.yml
.github/workflows/ci.yml
.github/workflows/codeql.yml
.github/workflows/images.yml
.github/workflows/nightly.yml
.github/workflows/release.yml
Vagrantfile
contrib/Dockerfile.test
script/setup/prepare_env_windows.ps1

- backport of https://github.com/containerd/containerd/pull/8714
go1.20.5 (released 2023-06-06) includes four security fixes to the cmd/go and runtime packages, as well as bug fixes to the compiler, the go command, the runtime, and the crypto/rsa, net, and os packages. See the Go 1.20.5 milestone on our issue tracker for details:
https://github.com/golang/go/issues?q=milestone%3AGo1.20.5+label%3ACherryPickApproved
full diff: https://github.com/golang/go/compare/go1.20.4...go1.20.5
- cmd/go: cgo code injection The go command may generate unexpected code at build time when using cgo. This may result in unexpected behavior when running a go program which uses cgo.
This may occur when running an untrusted module …

[release/1.7 backport] update go to go1.20.5, go1.19.10

---

pkg/cri/server/image_pull_test.go

- relates to https://github.com/kubernetes/k8s.io/issues/4780
These are not actually being pulled, just removing the deprecated k8s.gcr.io from the code-base. While at it, also renamed / removed vars that shadowed with package-level definitions

pkg/cri/server: TestImageGetLabels: use registry.k8s.io

---

.github/workflows/build-test-images.yml
.github/workflows/ci.yml
.github/workflows/codeql.yml
.github/workflows/images.yml
.github/workflows/nightly.yml
.github/workflows/release.yml
Vagrantfile
contrib/Dockerfile.test
script/setup/prepare_env_windows.ps1

- backport of https://github.com/containerd/containerd/pull/8804
go1.20.6 (released 2023-07-11) includes a security fix to the net/http package, as well as bug fixes to the compiler, cgo, the cover tool, the go command, the runtime, and the crypto/ecdsa, go/build, go/printer, net/mail, and text/template packages. See the Go 1.20.6 milestone on our issue tracker for details.
https://github.com/golang/go/issues?q=milestone%3AGo1.20.6+label%3ACherryPickApproved
Full diff: https://github.com/golang/go/compare/go1.20.5...go1.20.6
- net/http: insufficient sanitization of Host header
The HTTP/1 client did not fully validate the contents of the Host header. A maliciously crafted Host header could inject additional …

[release/1.7 backport] Update Go to 1.20.6,1.19.11

---

.cirrus.yml

- backport of https://github.com/containerd/containerd/pull/8776
I saw Cirrus CI / Vagrant BOX:rockylinux/8@5.0.0 failing during setting up Vagrant, which may be due to other scripts provisioning the machine;
Reading package lists...
apt-get install -y libvirt-daemon libvirt-daemon-system vagrant vagrant-libvirt
E: Could not get lock /var/lib/dpkg/lock-frontend. It is held by process 2496 (apt-get)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), is another process using it?
Configure dpkg to wait for locks to be released instead of failing. I used 60 second as timeout, which is relatively long, but given that the Vagrant checks are known to take some time to run, is probably fine.
(cherry picked from commit 6a913ac82e4b396677310038ad5cb93252d42cc2)

[release/1.7 backport] Cirrus CI: configure apt-get to wait for locks

---

.github/workflows/build-test-images.yml
.github/workflows/ci.yml
.github/workflows/codeql.yml
.github/workflows/images.yml
.github/workflows/nightly.yml
.github/workflows/release.yml
Vagrantfile
contrib/Dockerfile.test
script/setup/prepare_env_windows.ps1

relates to https://github.com/containerd/containerd/pull/8804
go1.19.11 (released 2023-07-11) includes a security fix to the net/http package, as well as bug fixes to cgo, the cover tool, the go command, the runtime, and the go/printer package. See the Go 1.19.11 milestone on our issue tracker for details:
https://github.com/golang/go/issues?q=milestone%3AGo1.19.11+label%3ACherryPickApproved
Full diff: https://github.com/golang/go/compare/go1.19.10...go1.19.11
net/http: insufficient sanitization of Host header
The HTTP/1 client did not fully validate the contents of the Host header. A maliciously crafted Host header could inject additional headers or entire requests. The HTTP/1 client now refuses to send requests …

[release/1.6] update go to go1.19.11

---

docs/PLUGINS.md
docs/garbage-collection.md
docs/hosts.md
docs/man/containerd-config.toml.5.md
docs/managed-opt.md
docs/ops.md
docs/stream_processors.md
docs/tracing.md
snapshots/devmapper/README.md

backport of:
- https://github.com/containerd/containerd/commit/195fc74244043d4ca3fd47cb2498e77fb6df95ec
- https://github.com/containerd/containerd/pull/6613
- https://github.com/containerd/containerd/pull/7174
Also had to add an extra commit for this branch, because 84cebafe8f6e69bbd1d9b80873eedd95847b9214 removed the "plugins.linux" example from the docs, so the follow-up commit didn't update that part of the docs (195fc74244043d4ca3fd47cb2498e77fb6df95ec)

[release/1.6 backport] Use version 2 configuration format in docs

---

Makefile
releases/cri-containerd.DEPRECATED.txt

- backport of https://github.com/containerd/containerd/pull/8019
(cherry picked from commit b473c2922f6fb8e2d7dca86d4717a7dfbba03032)
----
Add the following document (`"cri-containerd.DEPRECATED.txt"`) in the deprecated `cri-containerd-*` bundles, to provide more visibility:
```
The "cri-containerd-(cni-)-VERSION-OS-ARCH.tar.gz" release bundle has been deprecated since containerd 1.6,
does not work on some Linux distributions, and will be removed in containerd 2.0.
Instead of this, install the following components separately, either from the binary or from the source:
* containerd:  https://github.com/containerd/containerd/releases
* runc:        https://github.com/opencontainers/runc/releases
* CNI plugins: https://github.com/containernetworking/plugins/releases
The CRI plugin has been …
```

[release/1.6 backport] release: Add "cri-containerd.DEPRECATED.txt" in the deprecated cri-containerd-* bundles

---

cmd/containerd/command/main.go
log/context.go
pkg/cri/cri.go
runtime/v2/binary.go

we're in the process of adopting the containerd/log package in moby; getting more types in the release branches helps with the transition :)
- backport of https://github.com/containerd/containerd/pull/8441
(cherry picked from commit 370be0c18f52a026eb08e6b381518f3ae68b3969)

[release/1.7 backport] Move logrus setup code to log package

---

cmd/containerd/command/main.go
log/context.go
pkg/cri/cri.go
runtime/v2/binary.go

we're in the process of adopting the containerd/log package in moby; getting more types in the release branches helps with the transition :)
- backport of https://github.com/containerd/containerd/pull/8441
(cherry picked from commit 370be0c18f52a026eb08e6b381518f3ae68b3969)

[release/1.6 backport] Move logrus setup code to log package

---

metadata/containers_test.go

- backport of https://github.com/containerd/containerd/pull/7350
- addresses https://github.com/containerd/containerd/pull/8822#issuecomment-1635747185
This assertion is flaky on Windows.
Because of Go, Windows' time.Now resolution is lower than Linux.
(cherry picked from commit 407703f092f7cb920314d1e271fe67829b4beb30)

[release/1.6 backport] Make checkContainerTimestamps less strict on Windows

---

pkg/cri/store/sandbox/sandbox.go

- backport of https://github.com/containerd/containerd/pull/8130
(cherry picked from commit a48dbefc151f86fa382446014c41ea34308f743c)
---
Fixes panic produced by containerd when cri metrics are enabled.
The panic was observed with containerd 1.6.18 and k8s 1.23.16.
We started seeing this issue when on k8s side, we enabled the feature gate PodAndContainerStatsFromCRI
```
fatal error: concurrent map read and map write
goroutine 24245 [running]:
runtime.throw({0x55555c169112?, 0xc003f0b340?})
/usr/local/go/src/runtime/panic.go:992 +0x71 fp=0xc00575c6c8 sp=0xc00575c698 pc=0x55555aed5511
runtime.mapaccess1(0x55555c7717e0?, 0xc00145ee10?, 0x40?)
/usr/local/go/src/runtime/map.go:415 +0x1f7 fp=0xc00575c708 sp=0xc00575c6c8 pc=0x55555aeaccd7 …
```

[release/1.6 backport] Fix concurrent writes for UpdateContainerStats

---

cmd/ctr/commands/commands.go
pkg/atomicfile/file.go
pkg/atomicfile/file_test.go
pkg/cri/sbserver/update_runtime_config.go
pkg/cri/server/update_runtime_config.go
runtime/v2/shim/util.go

- backport of https://github.com/containerd/containerd/pull/8609
- fixes https://github.com/containerd/containerd/issues/8607
----
The 10-containerd-net.conflist file generated from the conf_template should be written atomically so that partial writes are not visible to CNI plugins. This is accomplished by writing a temporary file, syncing, and renaming over the destination file name.
Partial/inconsistent writes can occur due to:
1. A CNI plugin attempting to read the file while containerd is writing it (both in the case of a newly-generated file or in the case of a re-generated file via a subsequent call to UpdateRuntimeConfig).
2. Concurrent calls to UpdateRuntimeConfig leading to multiple active writers of the same file
The above mechanism explicitly protects against (1) as all writes …

[release/1.7 backport] cri: write generated CNI config atomically

---

pkg/cri/server/container_create_linux.go
pkg/cri/server/container_create_linux_test.go

(partial) backport of:
- https://github.com/containerd/containerd/pull/8136
- https://github.com/containerd/containerd/pull/8370
:warning: conflict due to `sbserver` not being in this branch, so ignore those files
Also removed https://github.com/containerd/containerd/commit/50740a1a0ce283888853155272c5962e1d2e7076 from the backport, as it requires go1.18 (and we still verify on go1.17)
---
I found a bug in setting `runtime.Spec.Process.User.additionalGids` in CRI server/sbserver.
If `LinuxContainerSecurityContext.{RunAsUser,RunAsUsername}` are empty, contained should fallback to the container image's `Config.User` for resolving the primary user and use it to inspect /etc/group in the container image for resolving `additionalGids`. But containerd always fallback to `0`.
__Fortunately, in …

[release/1.6 backport] [CRI] fix additionalGids: it should fallback to imageConfig.User when securityContext.RunAsUser,RunAsUsername are empty

---

.github/workflows/nightly.yml

since libseccomp is required only for building runc and we are only building containerd binaries in nightly, the libseccomp-dev dependency is removed. Foreign arch repositories are now removed since crossbuild-essential-* packages are {arm64, ppc64el,..} cross compiler packages for amd64 and arch specific repositories are not required.
not a clean cherrypick of #8768 as libbtrfs is still needed in release/1.6
(cherry picked from commit a9cb6090e2a2abe2b8625c60e4dee499e9291fb3)

[release/1.6 backport] ci: remove libseccomp-dev installation for nightly

---

integration/failpoint/cmd/containerd-shim-runc-fp-v1/plugin_linux.go
runtime/v2/example/example.go
runtime/v2/runc/pause/sandbox.go
runtime/v2/runc/task/service.go
runtime/v2/shim/shim.go

Set `shim.ttrpcService` and `shim.ttrpcServerOptioner` to exported interfaces so that implementers can use them to check.
for https://github.com/containerd/containerd/pull/8746#discussion_r1243436939

shim: change ttrpcService and ttrpcServerOptioner to exported interfaces

---

go.mod
go.sum
integration/client/go.sum
vendor/github.com/emicklei/go-restful/v3/CHANGES.md
vendor/github.com/emicklei/go-restful/v3/README.md
vendor/github.com/emicklei/go-restful/v3/SECURITY.md
vendor/github.com/emicklei/go-restful/v3/compress.go
vendor/github.com/emicklei/go-restful/v3/constants.go
vendor/github.com/emicklei/go-restful/v3/container.go
vendor/github.com/emicklei/go-restful/v3/cors_filter.go
vendor/github.com/emicklei/go-restful/v3/filter_adapter.go
vendor/github.com/emicklei/go-restful/v3/jsr311.go
vendor/github.com/emicklei/go-restful/v3/parameter.go
vendor/github.com/emicklei/go-restful/v3/request.go
vendor/github.com/emicklei/go-restful/v3/response.go
vendor/github.com/emicklei/go-restful/v3/route.go
vendor/github.com/emicklei/go-restful/v3/route_builder.go
vendor/github.com/emicklei/go-restful/v3/web_service.go
vendor/modules.txt

I cherry-picked #8221 and ran `go mod tidy` and `go mod vendor` like #8271. Silences a false alert about [CVE-2022-1996](https://github.com/advisories/GHSA-r48q-9g5r-8q2h). containerd is not affected by this CVE.
Resolves #8168

Update go-restful to v3.10.1 in release/1.6

---

.github/workflows/ci.yml

- `release.yml` continues to use Ubuntu 20.04 for glibc compatibility
- cgroup v1 is no longer tested with Ubuntu, but still tested with Rocky 8

.github/workflows/ci.yml: upgrade Ubuntu from 20.04 to 22.04

---

pkg/cri/opts/spec_linux_opts.go

If kubelet passes the swap limit (default memory limit = swap limit ), it is configured for container irrespective if the node supports swap. This results in following error:
```
Jul 20 18:14:22.460: INFO: At 2023-07-20 17:58:34 +0000 UTC - event for coredns-5dd5756b68-6fvpf: {kubelet ip-10-0-116-157.us-west-2.compute.internal} Failed: Error: failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error setting cgroup config for procHooks process: open /sys/fs/cgroup/memory/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod05d8a876_3004_479d_baa8_eac4f3309f4d.slice/cri-containerd-coredns.scope/memory.memsw.limit_in_bytes: no such file or directory: unknown
``` …

cri: memory.memsw.limit_in_bytes: no such file or directory

---

cmd/ctr/commands/images/images.go

`ctr images check -q` shouldn't output images which were not unpacked.

fix: `ctr images check -q` outputs not unpacked images

---

pkg/epoch/epoch.go
pkg/epoch/epoch_test.go

`strconv.Itoa(int(tm.Unix()))` rounds the time to 32-bit int on 32-bit hosts

pkg/epoch: fix Y2038 on 32-bit hosts

---

pkg/cri/opts/spec_linux.go

If kubelet passes the swap limit (default memory limit = swap limit ), it is configured for container irrespective if the node supports swap.
(cherry picked from commit 06f18c69d22b81fe040596d50f32d6bca2079a3d)

[release/1.6] cri: memory.memsw.limit_in_bytes: no such file or directory

---

contrib/gce/configure.sh
test/push.sh

Part of:
- kubernetes/test-infra#29995
- kubernetes/test-infra#30153
Backport of #8862
(cherry picked from commit 98974117b36a3752c74bb3ba743968efbd10707e)

[release/1.6] migrate to community owned bucket for node e2e tests

---

pkg/cri/opts/spec_linux_opts.go

If kubelet passes the swap limit (default memory limit = swap limit ), it is configured for container irrespective if the node supports swap.
(cherry picked from commit 06f18c69d22b81fe040596d50f32d6bca2079a3d)

[release/1.7] cri: memory.memsw.limit_in_bytes: no such file or directory

---

integration/containerd_image_test.go
pkg/cri/store/image/image.go

A image usually has multiple references, so as long as one of the references has `io.cri-containerd.pinned=pinned` label, then the image is pinned.
Reproducing current issues
```bash
$ ctr -n k8s.io images pull --label=io.cri-containerd.pinned=pinned docker.io/library/busybox:1.36
$ crictl --debug images
// ignore something
&Image{Id:sha256:a416a98b71e224a31ee99cff8e16063554498227d2b696152a9c3e0aa65e5824,RepoTags:[docker.io/library/busybox:1.36],RepoDigests:[],Size_:2224229,Uid:nil,Username:,Spec:nil,Pinned:false,}
```
> Of course, if we ctr manually remove the image reference containing the label, `Pinned` will still be true, but will become false after restarting.
> 
> Although it would be possible to set Pinned strictly based on the labels of the image references, it would be …

cri: fix using the labels to pin image

---

snapshots/overlay/overlayutils/check.go

Backport of #8852 to create the effect of adding #7008 to `release/1.6` (which was never done), and then applying the recent fix in #8852 so that both issues are solved for this LTS branch.
------
"ro" was not parsed out of the string, so it was passed as part of data to mount().
This would lead to mount() returning an invalid argument code. Separate out the "ro" option, much like "userxattr", which will allow the MS-RDONLY mountflag to get set.
Signed-off-by: Ben Foster <bpfoster@gmail.com>
(cherry picked from commit f3daf32c73656c5baa93acdca323295c61113cc3)

[release/1.6] backport: ro option for userxattr mount check + cherry-pick: Fix ro mount option being passed

---

snapshots/overlay/overlayutils/check.go

Clean cherry pick of f3daf32c73656c5baa93acdca323295c61113cc3 (#8852) into `release/1.7`
-------
"ro" was not parsed out of the string, so it was passed as part of data to mount().
This would lead to mount() returning an invalid argument code. Separate out the "ro" option, much like "userxattr", which will allow the MS-RDONLY mountflag to get set.
Signed-off-by: Ben Foster <bpfoster@gmail.com>
(cherry picked from commit f3daf32c73656c5baa93acdca323295c61113cc3)

[release/1.7] cherry-pick: Fix ro mount option being passed

---

integration/volume_copy_up_test.go
pkg/cri/sbserver/container_create.go
pkg/cri/sbserver/container_create_test.go
pkg/cri/server/container_create.go

Runc 1.1 throws a warning when using rel destination paths, and runc 1.2 is planning to thow an error (i.e. won't start the container).
Let's just make this an abs path in the only place it might not be: the mounts created due to `VOLUME` directives in the Dockerfile.
---
We discussed this issue in today's containerd community meeting and decided to make this small PR that should fix it, and if this is merged without concerns, backport it to 1.6 and 1.7.
cc @mikebrow

cri: Don't use rel path for image volumes

---

cio/io.go
cio/io_unix_test.go

Before this PR, if a stdin/stdout/stderr stream is nil, and the corresponding FIFO is not an empty string, a panic will occur when `Read`/`Write` of the nil stream is invoked in `io.CopyBuffer`.

fix: allow attaching to any combination of stdin/stdout/stderr

---

.github/workflows/build-test-images.yml
.github/workflows/ci.yml
.github/workflows/codeql.yml
.github/workflows/images.yml
.github/workflows/nightly.yml
.github/workflows/release.yml
Vagrantfile
contrib/Dockerfile.test
script/setup/prepare_env_windows.ps1

Includes a fix for CVE-2023-29409
go1.20.7 (released 2023-08-01) includes a security fix to the crypto/tls package, as well as bug fixes to the assembler and the compiler. See the Go 1.20.7 milestone on our issue tracker for details:
- https://github.com/golang/go/issues?q=milestone%3AGo1.20.7+label%3ACherryPickApproved
- full diff: https://github.com/golang/go/compare/go1.20.6...go1.20.7
go1.19.12 (released 2023-08-01) includes a security fix to the crypto/tls package, as well as bug fixes to the assembler and the compiler. See the Go 1.19.12 milestone on our issue tracker for details.
- https://github.com/golang/go/issues?q=milestone%3AGo1.19.12+label%3ACherryPickApproved
- full diff: https://github.com/golang/go/compare/go1.19.11...go1.19.12
From the mailing list announcement: …

update to go1.20.7, go1.19.12

---

platforms/platforms.go

Clarify the docs about how normalization is performed for `amd64/arm64`. There are no functional changes as this is already the behavior in the implementation.
ref: https://github.com/moby/buildkit/issues/4082

platforms: clarify docs for amd64/arm64 variant normalization

---

.github/workflows/build-test-images.yml
.github/workflows/ci.yml
.github/workflows/codeql.yml
.github/workflows/images.yml
.github/workflows/nightly.yml
.github/workflows/release.yml
Vagrantfile
contrib/Dockerfile.test
script/setup/prepare_env_windows.ps1

- backport of https://github.com/containerd/containerd/pull/8904
Includes a fix for CVE-2023-29409
go1.20.7 (released 2023-08-01) includes a security fix to the crypto/tls package, as well as bug fixes to the assembler and the compiler. See the Go 1.20.7 milestone on our issue tracker for details:
- https://github.com/golang/go/issues?q=milestone%3AGo1.20.7+label%3ACherryPickApproved
- full diff: https://github.com/golang/go/compare/go1.20.6...go1.20.7
go1.19.12 (released 2023-08-01) includes a security fix to the crypto/tls package, as well as bug fixes to the assembler and the compiler. See the Go 1.19.12 milestone on our issue tracker for details.
- https://github.com/golang/go/issues?q=milestone%3AGo1.19.12+label%3ACherryPickApproved
- full diff: …

[release/1.7 backport] update to go1.20.7, go1.19.12

---

.github/workflows/build-test-images.yml
.github/workflows/ci.yml
.github/workflows/codeql.yml
.github/workflows/images.yml
.github/workflows/nightly.yml
.github/workflows/release.yml
Vagrantfile
contrib/Dockerfile.test
script/setup/prepare_env_windows.ps1

Includes a fix for CVE-2023-29409
go1.19.12 (released 2023-08-01) includes a security fix to the crypto/tls package, as well as bug fixes to the assembler and the compiler. See the Go 1.19.12 milestone on our issue tracker for details.
- https://github.com/golang/go/issues?q=milestone%3AGo1.19.12+label%3ACherryPickApproved
- full diff: https://github.com/golang/go/compare/go1.19.11...go1.19.12
From the mailing list announcement:
[security] Go 1.20.7 and Go 1.19.12 are released
Hello gophers,
We have just released Go versions 1.20.7 and 1.19.12, minor point releases.
- crypto/tls: restrict RSA keys in certificates to <= 8192 bits
Extremely large RSA keys in certificate chains can cause a client/server
to expend …

[release/1.6] update to go1.19.12

---

.github/workflows/release.yml

Resolve NodeJS 12 and command deprecation warnings by upgrading docker/setup-buildx-action and crazy-max/ghaction-github-runtime packages.
[https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/)
[https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
(cherry picked from commit 14a38e12b78c857ebb01ffb724ab604ca9ffdc38)
clean cherry pick of #7794

[release/1.6 backport] Upgrade GitHub actions packages in release workflow

---

cio/io.go
cio/io_unix_test.go

PR is a backport for https://github.com/containerd/containerd/pull/8316 (687a5f51a80cf573efb545fc5e0e138d10b3bf83).

[release/1.7] fix: allow attaching to any combination of stdin/stdout/stderr

---

Makefile

Required for distros that wanna use their local version and can't have some (possibly failing) git commands being run here.

Makefile: allow REVISION be overwritten by environment

---

pkg/cri/server/container_create.go

This is a backport of: https://github.com/containerd/containerd/pull/8885 for 1.6.
---
Runc 1.1 throws a warning when using rel destination paths, and runc 1.2 is planning to thow an error (i.e. won't start the container).
Let's just make this an abs path in the only place it might not be: the mounts created due to `VOLUME` directives in the Dockerfile.
Signed-off-by: Rodrigo Campos <rodrigoca@microsoft.com>
(cherry picked from commit 2d64ab8d79a0bb18a089de37a5fbfc8eb5ab720d)

 [release/1.6] cri: Don't use rel path for image volumes

---

pkg/cri/sbserver/container_create.go
pkg/cri/sbserver/container_create_test.go
pkg/cri/server/container_create.go

This is a backport of: #8885 for 1.7. 
---
Runc 1.1 throws a warning when using rel destination paths, and runc 1.2 is planning to thow an error (i.e. won't start the container).
Let's just make this an abs path in the only place it might not be: the mounts created due to `VOLUME` directives in the Dockerfile.
Signed-off-by: Rodrigo Campos <rodrigoca@microsoft.com>
(cherry picked from commit 2d64ab8d79a0bb18a089de37a5fbfc8eb5ab720d)

[release/1.7] cri: Don't use rel path for image volumes

---

docs/NRI.md

branch "pr/proto/draft" in NRI doesn't exist anymore it's better to delete this line

delete checkout branch in doc

---

Makefile

There still was one place that's calling the `go` command directly instead of using the $(GO) variable.
Fixes: 9ea25634bddccbcd4c45a7e552a147ff7f50aaab

Makefile: fix overriding go command

---

go.mod
go.sum
integration/client/go.mod
integration/client/go.sum
platforms/defaults_windows.go
vendor/github.com/Microsoft/hcsshim/osversion/platform_compat_windows.go
vendor/github.com/Microsoft/hcsshim/osversion/windowsbuilds.go
vendor/modules.txt

This PR does the following:
- Update hcsshim tag to 0.9.10 + go mod tidy/vendor
- Uses the function introduced by https://github.com/microsoft/hcsshim/pull/1843 to invoke stable ABI compliant function in windows platform matcher. (In this PR, this change is limited to platforms/default_windows.go file. platform/default_windows_test.go file has some new tests added).
Exact platform match is required for OS Versions < WS2022. The exact version match is not needed in versions > WS2022 due to stable ABI compliance.

[release/1.6] Add stable ABI support in windows platform matcher + update hcsshim tag

---

.github/workflows/ci.yml
Vagrantfile
script/resize-vagrant-root.sh

- UEFI now has to be enabled
- The root device is now `/dev/mapper/rocky-root`. The resize script doesn't work for `/dev/mapper/*` yet, but the test passes without resizing it.

CI: update Rocky Linux to 8.8

---

snapshots/overlay/overlay.go
snapshots/overlay/overlay_test.go
snapshots/overlay/plugin/plugin.go

We have several issues related to `umount` which can cause unexpected IO pressure. Backporting #8676 is kind of workaround for the users who are using release/1.6 LTS. They can add `volatile` option to avoid syncfs in the kernel (>=5.10). 
Related issues: #8698, #7496, #8931, #8647 (In #8647, the container in pods failed to start and kubelet kept restart it and there were a lot of umount syscall when containerd deleted the tasks)
-----
Cherry-pick: #8676 #8542

[release/1.6] Cherry-pick: [overlay] add configurable mount options to overlay snapshotter

---

pkg/transfer/streaming/stream.go
platforms/defaults_windows.go
platforms/defaults_windows_test.go
platforms/platforms.go
platforms/platforms_other.go
platforms/platforms_windows.go

This PR does the following:
-  Uses the function introduced by https://github.com/microsoft/hcsshim/pull/1821 to invoke stable ABI compliant function in windows platform matcher.  (In this PR, this change is limited to platforms/default_windows.go file. platform/default_windows_test.go file has some new tests added).
Exact platform match is required for OS Versions < WS2022. The exact version match is not needed in versions > WS2022 due to stable ABI compliance.

Invoke stable ABI compliant platform check in windows matcher

---

Vagrantfile
integration/issue7496_linux_test.go
integration/issue7496_shutdown_linux_test.go
pkg/cri/sbserver/events.go
pkg/cri/sbserver/podsandbox/sandbox_delete.go
pkg/cri/server/events.go
runtime/v2/shim.go

When the shim unmounts overlayfs rootfs, kernel will force syncfs if there is no [volatile](https://docs.kernel.org/filesystems/overlayfs.html#volatile-mount) option. In order to reproduce the high IO pressure, this patch uses `strace` to delay the `umount2` syscall.
* [pkg/cri/server: fix leaked shim issue](https://github.com/containerd/containerd/commit/5b053a6b609e808ec6698cd68e5f76e1f27afc68)
* [pkg/cri/sbserver: fix leaked shim issue for podsandbox mode](https://github.com/containerd/containerd/commit/e8aeedeb9a2f6481816447109cf7835b5e994e15)
> NOTE: I don't merge three commits into one because it's easy to backport to v1.6.
Fixes: #7496 #8931
Within current design, if the shim is killed before task-service.Delete API call, the callback on connect close will send `137` exit code …

*: fix leaked shim caused by high IO pressure

---

integration/client/client_windows_test.go
integration/client/image_test.go
integration/sandbox_clean_remove_windows_test.go

create a process to mirror container images from 3rd parties into our ghcr.io/containerd domain.
issue: https://github.com/containerd/containerd/issues/8898

feat: replace mcr.microsoft.com registry to ghcr.io/containerd registry

---

content/helpers.go
services/content/contentserver/contentserver.go

`content.Copy` is a little verbose due to `cw.Status() + seekReader` being repeated 3 times. This PR (1st commit) remove extra duplications.
The second commit is a minor change to `contentserver`: 1. use the `infoToGRPC` helper; 2. predefine a empty var instead of creating a new one in every return, similar to other packages. It's a minor change so I just included in this PR as a separate commit. I can create a separate PR or remove it from this PR if that's better.
Thanks

Simplify `content.Copy` logic

---

pkg/cri/opts/spec_linux.go

cgroupv1HasHugetlb() and cgroupv2HasHugetlb() may return errors, but nobody (there's just one call site anyways) ever cares. So drop the unnecessary code.

cri: spec_linux: drop unused retvals

---

defaults/defaults_freebsd.go
defaults/defaults_linux.go
defaults/defaults_unix.go

@samuelkarp's https://github.com/samuelkarp/runj is a de facto default FreeBSD runtime.
This change creates a set of defaults for FreeBSD setting `wtf.sbk.runj.v1` as the default runtime.

FreeBSD: set default runtime

---

BUILDING.md
cmd/containerd/command/notify_no_systemd.go
cmd/containerd/command/notify_systemd.go

Make the rather obscure systemd notification build-time optional by setting 'no_systemd' tag and so skip dependencies on around 9kLoC vendor code.

cmd: containerd: allow building w/o systemd notify

---

cmd/ctr/commands/tasks/metrics.go

The error return value is always nil, so we don't need it at all.

ctr: metrics: drop unused retval from printWindowsStats()

---

Makefile

Distros usually like to install docs, so add a rule for that, so dist maintainers don't need to care about the details.

Makefile: add rule for installing documentation

---

RELEASES.md

Since a recent contributor edited the synced version of this in the website (containerd.io) repo, we should just update the main repo and let the auto-sync PR get these 2 files back in sync with the latest releases.

Update to latest releases in RELEASES.md

---

Makefile

Distros tend to change this to specific locations (eg. on MVCC installs), therefore introduce a generic environment variable that's a common practise since 30+ years and thus already well known and supported by distros.

Makefile: allow overriding the binary executable target dir

---

cmd/containerd/command/main.go
log/context.go
log/context_test.go
remotes/docker/resolver.go

We'll probably still have some way to go, but this PR attempts to make consumers of this package less coupled to logrus.
These are still aliases, but allowing consumers to use the types defined by this package allows us to switch definitions at some point.
Testify was only used for a basic assertion. Remove the dependency,
in preparation of (potentially) moving this package to a separate
module.
Also updated the level descriptions with their documentation from
logrus.
While other log-levels are not currently used in containerd itself,
they can be returned by `GetLevel()`, and are accepted (no error) by
`SetLevel()`. We should either accept those values, or produce an
error (in `SetLevel()`), but given that there's other ways to set the
log-level, we should probably acknowledge that this …

log: cleanups and improvements to decouple more from logrus

---

archive/compression/compression.go

Fixes https://github.com/containerd/containerd/issues/8873 by updating an outdated RFC draft link to a working RFC link.

archive/compression: update out of date RFC draft link

---

pkg/cri/sbserver/sandbox_stats_windows.go
pkg/cri/sbserver/sandbox_stats_windows_test.go
pkg/cri/server/sandbox_stats_windows.go
pkg/cri/server/sandbox_stats_windows_test.go

CommitMemory was added to k8s CRI 1.28 by these changes - https://github.com/kubernetes/kubernetes/pull/119238. This PR populates commit memory for windows memory usage stats

Populate commit memory for windows memory usage stats

---

.github/workflows/ci.yml

It will be easy to debug flaky testcase if we can provide kernel log by `dmesg -T -f kern`.

.github/workflows: add dmesg step for integration-linux 

---

archive/tarheader/tarheader_unix.go

This update addresses an issue where the stat call on FreeBSD could return -1 for regular files. This led to incorrect Devmajor and Devminor values, which should be zero in such cases. Refer to the discussion on this bug in the following PR:
https://github.com/containerd/containerd/pull/5991.
The code change now handles this scenario appropriately.

archive/tarheader: fix FreeBSD hdr for regular files

---

remotes/docker/pusher.go
remotes/handlers.go

Relate to the https://github.com/containerd/nerdctl/issues/2279,
The ctr has the same issue.
I push the local image to harbor with ctr  , and ctr nerdctl shows the wrong upload rate .
The command line show the rate of upload is 374 B/s, But the actual upload speed is much greater.
The issue is because of layer upload process bar is skipped. So the PR is to fix it. And If the layer exists in the registry, the upload size is 0.
After the Fix the rate of upload is 318 KB/s, It's correct.
The PR can also fix the `nerctl push`

Fix ctr push image can't show right rate 

---

cmd/ctr/commands/images/import.go

When platorm option was not set, ctr export would use platforms.DefaultStrict() , but ctr import would use platforms.Default(). For x86_64 platform, the matching result is not as expected. I don't think it's reasonable. Therefore, I update default platform matcher when ctr import to platforms.DefaultStrict().

Update default platform matcher when ctr import

---

go.mod
pkg/cri/sbserver/podsandbox/sandbox_run.go
pkg/cri/sbserver/sandbox_run.go
pkg/cri/sbserver/sandbox_stats_list.go
pkg/cri/server/sandbox_stats_list.go
pkg/process/io.go
plugins/streaming/manager.go
runtime/v2/shim.go
snapshots/devmapper/config.go
snapshots/devmapper/config_test.go
snapshots/devmapper/pool_device.go
snapshots/devmapper/snapshotter.go
snapshots/devmapper/snapshotter_test.go
snapshots/storage/metastore.go

Remove `github.com/hashicorp/go-multierror` and replace with `errors.Join` in std.
Some concept equivalents:
`var errs multierror.Error` = `var errs []error`
`errs = multierror.Append(errs, err)` = `errs = append(errs, err)`
`multierror.ErrorOrNil(errs)` = `errors.Join(errs)`
`errs.WrappedErrors()` = `err.(interface{ Unwrap() []error }).Unwrap()`
One behavior difference between `multierror.Append` and `errors.Join` is that the former will append to an existing multierror if it is (so the new one has a length of N + 1), while the latter will create a new `joinError` which includes previous error and the new one (so the new one has a length of 2)
https://go.dev/play/p/ryeimUucDyb
I think the recommended use pattern of `errors.Join` is to have a `errs [] error` to save all the errors along …

Remove hashicorp/go-multierror dependency

---

cmd/ctr/commands/snapshots/snapshots.go
integration/client/daemon_config_linux_test.go
integration/nri_test.go
oci/spec_opts.go
pkg/cri/sbserver/container_create_windows.go
pkg/cri/sbserver/helpers.go
pkg/cri/server/container_create_windows.go
pkg/cri/server/helpers.go
pkg/cri/streaming/remotecommand/exec.go
remotes/docker/fetcher_fuzz.go
remotes/docker/fetcher_test.go
snapshots/storage/bolt.go

Teeny-tiny optimizations:
BenchmarkSprintf-10       37735996    32.31  ns/op  0 B/op  0 allocs/op
BenchmarkItoa-10         591945836     2.031 ns/op  0 B/op  0 allocs/op
BenchmarkFormatUint-10   593701444     2.014 ns/op  0 B/op  0 allocs/op

replace some fmt.Sprintfs with strconv

---

cmd/ctr/commands/images/images.go
cmd/ctr/commands/images/inspect.go
pkg/display/manifest_printer.go

This tool is helpful for debugging and generally inspecting image content
Example output
```
$ ctr images inspect docker.io/library/alpine:latest
docker.io/library/alpine:latest
│    Created: 2023-04-16 07:55:00.700351928 +0000 UTC
│    Updated: 2023-08-22 22:51:11.741909909 +0000 UTC
└── application/vnd.docker.distribution.manifest.list.v2+json @sha256:7144f7bab3d4c2648d7e59409f15ec52a18006a128c733fcff20d3a4a54ba44a (1638 bytes)
├── application/vnd.docker.distribution.manifest.v2+json @sha256:c5c5fda71656f28e49ac9c5416b3643eaa6a108a8093151d6d1afc9463be8e33 (528 bytes)
│   │    Platform: linux/amd64
│   ├── application/vnd.docker.container.image.v1+json @sha256:7e01a0d0a1dcd9e539f8e9bbd80106d59efbdf97293b3d38f5d7a34501526cdb (1471 bytes)
│   └── …
```

ctr: images inspect

---

snapshots/overlay/overlay.go
snapshots/overlay/overlay_test.go
snapshots/overlay/plugin/plugin.go

We have several issues related to umount which can cause unexpected IO pressure. Backporting https://github.com/containerd/containerd/pull/8676 is kind of workaround for the users who are using release/1.7. They can add volatile option to avoid syncfs in the kernel (>=5.10).
Related issues: https://github.com/containerd/containerd/issues/8698, https://github.com/containerd/containerd/issues/7496, https://github.com/containerd/containerd/issues/8931, https://github.com/containerd/containerd/issues/8647 (In https://github.com/containerd/containerd/issues/8647, the container in pods failed to start and kubelet kept restart it and there were a lot of umount syscall when containerd deleted the tasks)
Cherry-pick: https://github.com/containerd/containerd/pull/8676 …

[release/1.7] Cherry-pick: [overlay] add configurable mount options to overlay snapshotter

---

Vagrantfile
integration/issue7496_linux_test.go
integration/issue7496_shutdown_linux_test.go
pkg/cri/sbserver/events.go
pkg/cri/sbserver/podsandbox/sandbox_delete.go
pkg/cri/server/events.go
runtime/v2/shim.go

Cherry-pick: #8954 
[pkg/cri/sbserver: fix leaked shim issue for podsandbox mode](https://github.com/containerd/containerd/commit/b4f480fb30f71ec15055cab0421aa16258ac4b58): I change the content to use logrus instead of log.L.Infof.
[integration: issue7496 case should work for runc.v2 only](https://github.com/containerd/containerd/pull/9003/commits/090aa0ea80d0245e36cfdf51955016754abe2436): The test case should skip when the default runtime is runc.v1 or io.containerd.runtime.v1.linux.

[releases/1.7] *: fix leaked shim caused by high IO pressure

---

Vagrantfile
integration/issue7496_linux_test.go
pkg/cri/server/container_stop.go
pkg/cri/server/events.go
pkg/cri/server/sandbox_stop.go

Cherry-pick: https://github.com/containerd/containerd/pull/8954
[integration: add case to reproduce](https://github.com/containerd/containerd/commit/d8f824200cdc39410bf9a4d110073186d6864f64) https://github.com/containerd/containerd/issues/7496: Update: change imports and use pb's field instead of GetXXX.
[pkg/cri/server: add criService as argument when handle exit event](https://github.com/containerd/containerd/commit/ab21d60d27d1d7c87423e9b4ecb076358762e89b): The patch doesn't work with releases/1.6. It needs to add criService as argument when handle exit event.
[integration: issue7496 case should work for runc.v2 only](https://github.com/containerd/containerd/pull/9004/commits/c91469f76404b753ba249188593391e937f6a701): The test case should skip when the default runtime is runc.v1 or …

[releases/1.6] *: fix leaked shim caused by high IO pressure

---

cmd/containerd/command/main.go
log/context.go
log/context_test.go
remotes/docker/resolver.go

- backport of https://github.com/containerd/containerd/pull/8894

[release/1.7 backport] log: cleanups and improvements to decouple more from logrus

---

go.mod
go.sum
integration/client/go.mod
integration/client/go.sum
vendor/github.com/containerd/continuity/devices/mknod_freebsd.go
vendor/github.com/containerd/continuity/driver/lchmod_unix.go
vendor/github.com/containerd/continuity/fs/copy_unix.go
vendor/github.com/containerd/continuity/fs/stat_atim.go
vendor/modules.txt

- https://github.com/containerd/containerd/pull/9011

[release/1.7 backport] go.mod: github.com/containerd/continuity v0.4.2

---

releases/v1.7.5.toml
version/version.go

See https://gist.github.com/dmcgowan/164caef1ebe8a08ac55c44dc68bd5cd3
----
Welcome to the v1.7.5 release of containerd!
The fifth patch release for containerd 1.7 fixes a versioning issue from
the previous release and includes some internal logging API changes.

[release/1.7] Prepare release notes for 1.7.5

---

cmd/ctr/commands/run/run.go

If a mount destination is specified both in the default spec and in a --mount option, remove the default mount before adding new mounts.  This allows overriding the default sysfs mount, for example.

ctr: allow run to override mounts

---

RELEASES.md

Explicitly mentioned a possibility to take feature backports to support new Kubernetes releases.
See https://github.com/containerd/containerd/pull/8943#issuecomment-1689110782 for more details.

Update LTS description

---

container.go
remotes/docker/config/hosts.go

From the Go docs:
>  1. ..."For a nil slice, the number of iterations is 0." https://go.dev/ref/spec#For_range
Both `info.RootFS` and `host.clientPairs` are slices. Therefore, an additional nil check for before the loop is unnecessary.

Remove redundant nil check

---

snapshots/blockfile/plugin/plugin.go

This was the only option not configurable from the toml for the plugin. This is useful if you want to restart containerd and try a different blockfile for the snapshotter.

Blockfile: Expose RecreateScratch option

---

script/setup/install-cni
script/setup/install-critools
script/setup/install-runc

make repositories of dependencies like runc, crun, cni and critools configurable
(cherry picked from commit 7a0ad09a0d5edcd40555a998e0e065e6dda43acc)
clean cherry-pick of #9021

[release/1.7 backport] make repositories of install dependencies configurable

---

script/setup/install-cni
script/setup/install-critools
script/setup/install-runc

make repositories of dependencies like runc, crun, cni and critools configurable
(cherry picked from commit 7a0ad09a0d5edcd40555a998e0e065e6dda43acc)
not a clean cherry-pick of #9021

[release/1.6 backport] make repositories of install dependencies configurable

---

log/context.go

- updates https://github.com/containerd/containerd/pull/8894
This reverts commit 778ac302b27278b25bb2dabfc1cda99780cbc60b.
(slightly modified, due to changes that were merged after that).
The reverted commit had two elements;
- Make `G` an actual function to improve the documentation
- Prevent `G` from being overwritten externally
From the commit that's reverted:
> The `G` variable is exported, and not expected to be overwritten
> externally. Defining it as a function also documents it as a function
> on https://pkg.go.dev, instead of a variable; https://pkg.go.dev/github.com/containerd/containerd@v1.6.22/log#pkg-variables
While it's unclear if the ability to replace the implementation was _intentional_, it's this part that some external consumers were (ab)using.
We should look into that …

Revert "log: define G() as a function instead of a variable"

---

log/context.go

- backport of https://github.com/containerd/containerd/pull/9031
- updates https://github.com/containerd/containerd/pull/8894
- update https://github.com/containerd/containerd/pull/9001
This reverts commit 778ac302b27278b25bb2dabfc1cda99780cbc60b.
(slightly modified, due to changes that were merged after that).
The reverted commit had two elements;
- Make `G` an actual function to improve the documentation
- Prevent `G` from being overwritten externally
From the commit that's reverted:
> The `G` variable is exported, and not expected to be overwritten
> externally. Defining it as a function also documents it as a function
> on https://pkg.go.dev, instead of a variable; https://pkg.go.dev/github.com/containerd/containerd@v1.6.22/log#pkg-variables
While it's unclear if the ability to …

[release/1.7 backport] Revert "log: define G() as a function instead of a variable"

---

pkg/transfer/local/import.go

- For remote snapshotters, the unpack phase serves as an important step for preparing the remote snapshot. With the missing `unpacker.Wait`, the snapshotter `Prepare` context is always canceled.
- This patch allows remote snapshotter based archives to be imported via the transfer service or `ctr image import`

Add missing unpacker.Wait for image import

---

contrib/fuzz/oss_fuzz_build.sh

With the upgrade of go 1.21, current ossfuzz building crashes with the following error message:
```bash
/usr/bin/ld: /usr/bin/ld: DWARF error: invalid or unhandled FORM value: 0x25
fuzz_FuzzLoadDefaultProfile.a(000021.o): in function `_cgo_9c8efe9babca_C2func_res_search':
cgo_unix_cgo_res.cgo2.c:(.text+0x32): undefined reference to `__res_search'
/usr/bin/ld: fuzz_FuzzLoadDefaultProfile.a(000021.o): in function `_cgo_9c8efe9babca_Cfunc_res_search':
cgo_unix_cgo_res.cgo2.c:(.text+0x81): undefined reference to `__res_search'
clang-15: error: linker command failed with exit code 1 (use -v to see invocation)
```
Fix it by adding two CXX environment variables: `lresolv` and `pthread`.
P.S. Same issues only appear on drivers using `compile_go_fuzzer`. Maybe the variables will be not necessary …

fuzzing: fix ossfuzz building error

---

pkg/cri/sbserver/restart.go

The failed to recover state message didn't include the ID making this not as useful as it could be..
This additionally moves some of the other logs to include the id for the sandbox/container as a field instead of part of a format string.

CRI: Include sandbox ID in failed to recover error

---

pkg/cri/sbserver/container_create.go
pkg/cri/sbserver/container_create_linux.go
pkg/cri/sbserver/container_create_linux_test.go

Backport: https://github.com/containerd/containerd/pull/8464
The oci.WithUser option was being applied in container_create_linux.go instead of the cross plat buildLinuxSpec method. There's been recent work to try and make every spec option that can be applied on any platform able to do so, and this falls under that. However, WithUser on linux platforms relies on the containers SnapshotKey being filled out, which means the spec option needs to be applied during container creation.
To make this a little more generic, I've created a new platformSpecOpts method that handles any spec opts that rely on runtime state (rootfs mounted for example) for some platforms, or just platform options that we still don't have workarounds for to be able to specify them for other platforms (apparmor, seccomp …

[release/1.7] CRI: Support Linux usernames for !linux platforms

---

cmd/ctr/commands/run/run_unix.go
integration/client/container_idmapped_linux_test.go
mount/mount_idmapped_linux.go
mount/mount_linux.go
snapshots/overlay/overlay.go
snapshots/overlay/overlay_test.go
snapshots/overlay/overlayutils/check.go
snapshots/overlay/plugin/plugin.go
sys/subprocess_unsafe_linux.go
sys/userns_unsafe_linux.go

<html>
<body>
<p style="box-sizing: border-box; margin-bottom: 16px; margin-top: 0px !important; color: rgb(36, 41, 46); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">Hi,<br style="box-sizing: border-box;">this is this is initial support of idmapped mount points in containerd. The original …

RFC: Initial support of idmapped mount points

---

docs/getting-started.md

fix #9049
Modify the parameter `-Path` to reference a folder, so `Copy-Item` create the destination folder.
Remove `-Container:$false` that flatten the hierarchy folder.

fix(docs): fix on the windows installation script

---

content/local/store.go
content/testsuite/testsuite.go

make ref tryLocking times configurable to reduce the amount of
time the lock is held
fixes: #8790
Signed-off-by: jerryzhuang <zhuangqhc@gmail.com>

content: reduce the contention between ref lock and boltdb lock

---

cmd/ctr/commands/content/fetch.go
cmd/ctr/commands/images/pull.go
content/content.go
pkg/display/manifest_printer.go
remotes/handlers.go

When a blob does not exist locally, rather than erroring on info lookup, inherit the parent distribution sources. Push is able to succeed even if the blob does not exist locally when a cross repository mount is done. This is a common operation pushing a multi-platform image to the same registry but different namespace.
This gets around a premature not found error on push when looking up the source labels. The push API was not designed to abort push so early in the process, any not found should only error the process when coming from the content open.
Update the ctr defaults to something more sensible, this reduces the number of user errors on push after pull.

push: inherit distribution sources from parent

---

go.mod
go.sum
integration/client/go.mod
integration/client/go.sum
vendor/github.com/Microsoft/hcsshim/osversion/platform_compat_windows.go
vendor/modules.txt

This PR updates hcsshim tag to v0.11.0 to bring in https://github.com/microsoft/hcsshim/commit/640a5606a855a275cda5b8862221ae32b09b6a35

[release/1.7] Update hcsshim tag to v0.11.0

---

.github/workflows/build-test-images.yml
.github/workflows/ci.yml
.github/workflows/codeql.yml
.github/workflows/images.yml
.github/workflows/nightly.yml
.github/workflows/release.yml
Vagrantfile
contrib/Dockerfile.test
script/setup/prepare_env_windows.ps1

go1.20.8 (released 2023-09-06) includes two security fixes to the html/template package, as well as bug fixes to the compiler, the go command, the runtime, and the crypto/tls, go/types, net/http, and path/filepath packages. See the Go 1.20.8 milestone on our issue tracker for details:
https://github.com/golang/go/issues?q=milestone%3AGo1.20.8+label%3ACherryPickApproved
full diff: https://github.com/golang/go/compare/go1.20.7...go1.20.8
[security] Go 1.21.1 and Go 1.20.8 are released
Hello gophers,
We have just released Go versions 1.21.1 and 1.20.8, minor point releases.
These minor releases include 4 security fixes following the security policy:
- cmd/go: go.mod toolchain directive allows arbitrary execution The go.mod toolchain directive, introduced in Go …

[release/1.6] update to go1.20.8

---

.github/workflows/build-test-images.yml
.github/workflows/ci.yml
.github/workflows/codeql.yml
.github/workflows/images.yml
.github/workflows/nightly.yml
.github/workflows/release.yml
Vagrantfile
contrib/Dockerfile.test
script/setup/prepare_env_windows.ps1

go1.20.8 (released 2023-09-06) includes two security fixes to the html/template package, as well as bug fixes to the compiler, the go command, the runtime, and the crypto/tls, go/types, net/http, and path/filepath packages. See the Go 1.20.8 milestone on our issue tracker for details:
https://github.com/golang/go/issues?q=milestone%3AGo1.20.8+label%3ACherryPickApproved
full diff: https://github.com/golang/go/compare/go1.20.7...go1.20.8
[security] Go 1.21.1 and Go 1.20.8 are released
Hello gophers,
We have just released Go versions 1.21.1 and 1.20.8, minor point releases.
These minor releases include 4 security fixes following the security policy:
- cmd/go: go.mod toolchain directive allows arbitrary execution The go.mod toolchain directive, introduced in Go …

[release/1.7] update to go1.20.8

---

.github/workflows/build-test-images.yml
.github/workflows/ci.yml
.github/workflows/codeql.yml
.github/workflows/images.yml
.github/workflows/nightly.yml
.github/workflows/release.yml
Vagrantfile
contrib/Dockerfile.test
contrib/fuzz/oss_fuzz_build.sh
script/setup/prepare_env_windows.ps1

go1.21.1 (released 2023-09-06) includes four security fixes to the cmd/go, crypto/tls, and html/template packages, as well as bug fixes to the compiler, the go command, the linker, the runtime, and the context, crypto/tls, encoding/gob, encoding/xml, go/types, net/http, os, and path/filepath packages. See the Go 1.21.1 milestone on our issue tracker for details:
https://github.com/golang/go/issues?q=milestone%3AGo1.21.1+label%3ACherryPickApproved
full diff: https://github.com/golang/go/compare/go1.21.0...go1.21.1
[security] Go 1.21.1 and Go 1.20.8 are released
Hello gophers,
We have just released Go versions 1.21.1 and 1.20.8, minor point releases.
These minor releases include 4 security fixes following the security policy:
- cmd/go: go.mod toolchain directive …

update to go1.21.1, go1.20.8

---

cmd/ctr/commands/images/mount.go
leases/lease.go
leases/lease_test.go

- relates to https://github.com/moby/moby/pull/46383#discussion_r1321652839
- don't define a type, but just an ad-hoc struct
- use a single slice with test-cases; this allows IDE's to pick up the
table as a test-table (which allows (re-)running individual tests)
- make use of testify's assert.Equal to compare the results, instead
of a DIY loop over the expected values.
This adds a new WithLabel function, which allows to set a single label on
a lease, without having to first construct an intermediate `map[string]string`.

leases: add WithLabel

---

content/content.go
remotes/handlers.go

Backport #9029 
When a blob does not exist locally, rather than erroring on info
lookup, inherit the parent distribution sources. Push is able
to succeed even if the blob does not exist locally when a cross
repository mount is done. This is a common operation pushing a
multi-platform image to the same registry but different namespace.
`ctr` change not included because it is a behavior change

[release/1.7] push: inherit distribution sources from parent

---

pkg/transfer/streaming/stream.go
platforms/defaults_windows.go
platforms/defaults_windows_test.go
platforms/platforms.go
platforms/platforms_other.go
platforms/platforms_windows.go

This PR ports the following commit for stable ABI support to containerd/release/1.7 and fixes dependencies on transfer service.
(cherry picked from commit cfb30a31a8507e4417d42d38c9a99b04fc8af8a9 and 823e0420eb3cd3eebbf15472cda0cfac85da14f6)

[release/1.7] Invoke Stable ABI compatibility function in windows platform matcher

---

releases/v1.7.6.toml
version/version.go

See generated notes https://gist.github.com/dmcgowan/b08faac622b051c72b282b9e63610998
----
Welcome to the v1.7.6 release of containerd!
The sixth patch release for containerd 1.7 contains various fixes and updates.
* **Fix log package for clients overwriting the global logger** ([#9032](https://github.com/containerd/containerd/pull/9032))
* **Fix blockfile snapshotter copy on Darwin** ([#9047](https://github.com/containerd/containerd/pull/9047))
* **Add support for Linux usernames on non-Linux platforms** ([#9015](https://github.com/containerd/containerd/pull/9015))
* **Update Windows platform matcher to invoke stable ABI compability function** ([#9069](https://github.com/containerd/containerd/pull/9069))
* **Update Golang to 1.20.8** …

[release/1.7] Prepare release notes for 1.7.6

---

remotes/docker/pusher.go
remotes/docker/pusher_test.go
remotes/docker/status.go

This makes it possible to check whether content didn't actually need to be pushed to the remote registry and was cross-repo mounted or already existed.

remotes/docker: Add Mounted and Exists push status

---

api/types/platform_helpers.go
pkg/transfer/archive/exporter.go
pkg/transfer/image/imagestore.go
platforms/cpuinfo_linux.go
platforms/cpuinfo_linux_test.go
platforms/cpuinfo_other.go
platforms/errors.go
platforms/platforms.go
services/introspection/local.go

This cleans up the platforms package from dependencies that are not strictly
needed. This is in preparation of making this package a separate module, which
can be shared by plugins, and containerd versions (as well as external consumers),
- Remove dependency on the errdefs package: most uses of these error
definitions were used internally, and other errors may not be useful
for external consumers as sentinel errors.
- ErrInvalidArgument may be a potential exception, although a look at
current uses of this package shows that there's no special handling of
invalid parameters vs other errors (all would boil down to "the passed
platform is invalid" (either the format, or parsing is not implemented
on a specific platform)
- Remove uses of the convenience "Platform" alias in favor of using the …

platforms: isolate from errdefs and api dependencies

---

cmd/containerd/builtins/builtins.go
docs/image-verification.md
pkg/imageverifier/bindir/bindir.go
pkg/imageverifier/bindir/bindir_test.go
pkg/imageverifier/bindir/processes_unix.go
pkg/imageverifier/bindir/processes_windows.go
pkg/imageverifier/bindir/testdata/verifier_templates/verifier_test_input_output_management.go.tmpl
pkg/imageverifier/bindir/testdata/verifiers/accept_reason_a.go
pkg/imageverifier/bindir/testdata/verifiers/accept_reason_b.go
pkg/imageverifier/bindir/testdata/verifiers/accept_reason_c.go
pkg/imageverifier/bindir/testdata/verifiers/large_stderr.go
pkg/imageverifier/bindir/testdata/verifiers/large_stderr_chunked.go
pkg/imageverifier/bindir/testdata/verifiers/large_stdout.go
pkg/imageverifier/bindir/testdata/verifiers/large_stdout_chunked.go
pkg/imageverifier/bindir/testdata/verifiers/reject_reason_d.go
pkg/imageverifier/bindir/testdata/verifiers/slow_child_process.go
pkg/imageverifier/image_verifier.go
pkg/transfer/local/pull.go
pkg/transfer/local/transfer.go
plugin/plugin.go
plugins/imageverifier/path_unix.go
plugins/imageverifier/path_windows.go
plugins/imageverifier/plugin.go
plugins/transfer/plugin.go

Implements https://github.com/containerd/containerd/issues/6691
See the added docs for configuration details. To test, run a command like `ctr image pull --local=false index.docker.io/library/alpine@sha256:c75ac27b49326926b803b9ed43bf088bc220d22556de1bc5f72d742c91398f69`.
The simplest verifier binaries for testing can be something like this:
```
#!/usr/bin/env bash
echo Approved
```
or 
```
#!/usr/bin/env bash
echo Rejected
exit 1
```
Real implementations would need to parse the `-name` and `-digest` flags.

Add image verifier transfer service plugin system based on a binary directory

---

pkg/epoch/epoch.go
pkg/epoch/epoch_test.go

Ref: #9090 
Removing SourceDateEpochOrNow() as it's both unused and inherently causes "flaky" test failures due to reliance on timer resolution of the underlying operating system as decided here: https://github.com/containerd/containerd/issues/9090#issuecomment-1721437930

Refactor: Removing inherently flaky and unused SourceDateEpochOrNow function.

---

remotes/docker/pusher.go
remotes/docker/pusher_test.go
remotes/docker/status.go

Backport https://github.com/containerd/containerd/pull/8330
This makes it possible to check whether content didn't actually need to be pushed to the remote registry and was cross-repo mounted or already existed.
(cherry picked from commit dfc7590d5a49d0cbd3151e5a53bf5c677acb0477)

[release/1.7] remotes/docker: Add MountedFrom and Exists push status

---

go.mod
go.sum
integration/client/go.sum
vendor/github.com/containerd/nri/Makefile
vendor/github.com/containerd/nri/client.go
vendor/modules.txt

This version no longer has a dependency on containerd, cutting down the number of circular dependencies.
full diff: https://github.com/containerd/nri/compare/v0.4.0...v0.5.0

vendor: github.com/containerd/nri v0.5.0

---

image.go
images/usage/calculator.go

Creates a new `pkg/usage` to handle usage calculation. Updates the client to use this new package. This is to help plugins be able to make usage calculations without importing the whole client.

Add usage package

---

oci/spec_opts.go
oci/spec_opts_linux_test.go

The inheritable capabilities set should never be larger than the bounding capabilities set. When a base spec is provided with non-empty inheritable capabilities today, the container will fail to run when those capabilities are explicitly dropped. This issue is only seen when a base spec with inheritable capabilities is explicitly provided in the configuration file, the default spec already removed inheritable capabilities in https://github.com/containerd/containerd/security/advisories/GHSA-c9cp-9c75-9v8c. Since the container is unable to start with this setup, there is no security concern. It may be worth a discussion whether more should be done to warn users who may have set this in their configuration before the GHSA, whether through logging or our documentation.
The error seen when …

Support for dropping inheritable capabilities

---

remotes/docker/pusher.go
remotes/docker/pusher_test.go
remotes/docker/status.go

Backport https://github.com/containerd/containerd/pull/8330
This makes it possible to check whether content didn't actually need to be pushed to the remote registry and was cross-repo mounted or already existed.
(cherry picked from commit dfc7590d5a49d0cbd3151e5a53bf5c677acb0477)

[release/1.6] remotes/docker: Add MountedFrom and Exists push status

---

pkg/netns/netns_linux.go

Improve godoc for func `NewNetNS` and `NewNetNSFromPID`.
Fixes: #8923 
The current doc is unclear about the name of the created netns, and the meaning of `baseDir`. The godoc is updated with the clarity.

Improve doc of func NewNetNS

---

api/runtime/sandbox/v1/sandbox.proto

Similar to the other types:
- https://github.com/bryantbiggs/containerd/blob/c3694aaf879e7e1b6f17c6e723a1e46cc5e94f01/api/runtime/sandbox/v1/sandbox.proto#L67
- https://github.com/bryantbiggs/containerd/blob/c3694aaf879e7e1b6f17c6e723a1e46cc5e94f01/api/runtime/sandbox/v1/sandbox.proto#L89
Without this, we are unable to derive the correct source for the Metric type in https://github.com/containerd/rust-extensions

fix: Add `containerd` to the message type reference

---

go.mod
go.sum
integration/client/go.mod
integration/client/go.sum
vendor/github.com/Microsoft/hcsshim/internal/hcs/process.go
vendor/modules.txt

Fix closing stdin (https://github.com/microsoft/hcsshim/pull/1899): fix an issue introduced in [v0.10.0-rc.3], which resulted in the close request not being forwarded if stdin was nil. The fix moves the nil check to after the modify request, to let the process handle it.
full diff: https://github.com/Microsoft/hcsshim/compare/v0.11.0...v0.11.1
[v0.10.0-rc.3]: https://github.com/microsoft/hcsshim/commit/3e090b05a82c0e226e26c0d1e2ae89d336d7ff69

[release/1.7] vendor: github.com/Microsoft/hcsshim v0.11.1

---

pkg/cri/sbserver/images/service.go
pkg/cri/sbserver/images/service_test.go
pkg/cri/server/service.go
pkg/cri/server/service_test.go
pkg/cri/store/image/fake_image.go
pkg/cri/store/image/image.go

Removing the `github.com/containerd/containerd` dependency from internal packages one package at a time.

Update CRI image store to not use containerd client

---

pkg/cri/sbserver/events.go
plugins/sandbox/controller.go
services/sandbox/controller_service.go
services/tasks/local.go

Observations:
When a shim process is unexpectedly killed in a way that was not initiated through containerd - containerd reports the pod as not ready but the containers as running. This results in kubelet repeatedly sending container kill requests that fail since containerd cannot connect to the shim.
Note: This behavior is seen only for sandbox shims 
Changes:
- In the container exit handler, treat `err: Unavailable` as if the container has already exited out
- When attempting to get a connection to the shim, if the controller isn't available assume that the shim has been killed (needs to be done since we have a separate exit handler that cleans up the reference to the shim controller - before kubelet has the chance to call StopPodSandbox) …

Sandbox: Handle unexpected shim kill events

---

docs/user-namespaces/README.md

crun 1.4.3 as well as runc 1.1 both support to open bind-mounts before dropping privileges, as they are inaccessible after switching to the user namespace. So that is the minimum version to use with containerd 1.7.
Also, since containerd 2.0 we use idmap mounts for files mounted in the container created by containerd (like etc/hostname, etc/hosts, etc.), we require newer OCI runtimes too. However, as the kubelet doesn't request idmap mounts for kube volumes, we can technically lower the kernel version used.

docs/userns: Clarify requirements for k8s 1.25/1.26

---

image.go

This allows images that might have additional artifacts or no layers to pull content and still start properly.  This follows the same pattern as in the transfer service: https://github.com/containerd/containerd/blob/main/pkg/unpack/unpacker.go#L188
Without this change you get `mismatched image rootfs and manifest layers` at the import and run steps.  This isn't really true as the layers and manifest layers can match and while potentially still having other layers that would correspond to artifacts.
After several iterations of working with OCI artifacts for WASM with #8699 and feedback from users trying it out on runwasi, it was determined that the minimal number of changes to containerd would be beneficial so we could potentially use this in containerd today (via backport).
Some tests in …

Allow for images with artifacts layers to pull and run

---

cmd/containerd/command/config.go
integration/build_local_containerd_helper_test.go
services/server/config/config.go
services/server/config/config_test.go
services/server/server.go

Adds a warning when an unknown field is found in the plugin configuration. Uses the interface for go-toml v2.

Add warning for plugin configs with unknown fields

---

mount/lookup_unix.go
mount/mount.go
mount/mount_unix.go
mount/temp_unix.go
pkg/cri/sbserver/helpers_linux.go
pkg/cri/sbserver/podsandbox/helpers_linux.go
pkg/cri/server/helpers_linux.go

Fix usages of `mountinfo.PrefixFilter`
It says: The prefix path **must be absolute, have all symlinks resolved, and cleaned**. But those requirements are violated in lots of places.
What happens when it is given a non-canonicalized path is that `mountinfo.GetMounts` will not find mounts.
The trivial case is:
```
$ mkdir a && ln -s a b && mkdir b/c b/d && mount --bind b/c b/d && cat /proc/mounts | grep -- '[ab]/d'
/dev/sdd3 /home/user/a/d ext4 rw,noatime,discard 0 0
```
We asked to bind-mount b/c to b/d, but ended up with mount in a/d.
So, mount table always contains canonicalized mount points, and it is an error to look for non-canonicalized paths in it.
Signed-off-by: Marat Radchenko <marat@slonopotamus.org>

Fix usages of `mountinfo.PrefixFilter`

---

images/archive/exporter.go
images/handlers.go
images/image.go

By aligning with the `mediatypes.go` helpers, there is a single source of truth for the mediatype checks in the `images/` package tree, and we can remove some case statements. By dropping case statements, branching logic can be simplified and made more obvious, with less nesting.

images: use mediatype helpers

---

docs/user-namespaces/README.md
script/test/utils.sh
snapshots/overlay/overlay.go
snapshots/overlay/plugin/plugin.go
snapshotter_opts_unix.go

This makes the user opt-in before falling back to an expensive recursive chown when overlayfs and userns are used.
This is done only for the overlayfs snapshotter, as that is the only one that supports a faster option (idmap mounts). Other snapshotters can add the same once they support idmap mounts or some other faster alternative.
While I was there, I expanded the note on the containerd 1.7 limitations, to show why it is very expensive the recursive chown.
Fixes: #9068 
---
cc @AkihiroSuda

Require opt-in for rootfs chown when idmap mounts is not supported

---

docs/transfer.md

I believe these are now implemented in 1.7 with the conclusion of https://github.com/containerd/containerd/issues/7592 and its respective PRs that have been merged

docs: Update `transfer` service docs to reflect completed implementations for `1.7`

---

services/server/server.go

When readiness is registered on initialization, the plugin must not fail. When such a plugin fails, containerd will hang on the readiness condition.
fixes #9139

Require plugins to succeed after registering readiness

---

pkg/cri/cri.go

`NewCRIService()` may easily fail and its error has to be ignored unless the CRI plugin is in the `required_plugins` list.
Now this has to be called before `RegisterReadiness()`, as PR #9153 `Require plugins to succeed after registering readiness` was merged on 2023-09-29.
Fix #9163: `[Regression in main (2023-09-29)]: containerd-rootless.sh doesn't start up`

cri: call RegisterReadiness after NewCRIService

---

pkg/cri/sbserver/service_linux.go
pkg/cri/server/service_linux.go

Disabling cgroup is no longer needed since cgroup v2

cri: stop recommending disable_cgroup

---

.github/workflows/ci.yml

1.19 is end of life, continue to run with 1.20 but ensure builds with 1.21.
Testing to see if this fixes windows compilation errors.
Related to #9072

[release/1.7] Build binaries with 1.21.1

---

pkg/cri/sbserver/events.go
plugins/sandbox/controller.go
services/sandbox/controller_service.go
services/tasks/local.go

- backport of https://github.com/containerd/containerd/pull/9112
When a shim process is unexpectedly killed in a way that was not initiated through containerd - containerd reports the pod as not ready but the containers as running. This results in kubelet repeatedly sending container kill requests that fail since containerd cannot connect to the shim.
Changes:
- In the container exit handler, treat `err: Unavailable` as if the container has already exited out
- When attempting to get a connection to the shim, if the controller isn't available assume that the shim has been killed (needs to be done since we have a separate exit handler that cleans up the reference to the shim controller - before kubelet has the chance to call StopPodSandbox) …

[release/1.7] Handle unexpected shim kill events

---

pkg/cri/cri.go
services/server/server.go

Fixes hang when plugin which registers readiness fail. Additional fix in CRI to register readiness later on in its initialization.
Backport #9153 #9164

[release/1.7] Require plugins to succeed after registering readiness

---

.github/workflows/ci.yml

After using mingw v13.1.0, windows 2019 CI fails.
```bash
shell: C:\Program Files\PowerShell\7\pwsh.EXE -command ". '{0}'"
env:
GO_VERSION: 1.21.1
Cannot find file at '..\\lib\mingw\tools\install\mingw[6](https://github.com/containerd/containerd/actions/runs/6380072801/job/17314029501?pr=9177#step:5:6)4\bin\mingw32-make.exe' (C:\ProgramData\Chocolatey\lib\mingw\tools\install\mingw64\bin\mingw32-make.exe). This usually indicates a missing or moved file.
Cannot find file at '..\\lib\mingw\tools\install\mingw64\bin\mingw32-make.exe' (C:\ProgramData\Chocolatey\lib\mingw\tools\install\mingw64\bin\mingw32-make.exe). This usually indicates a missing or moved file.
```
No idea why the make command is not found. Pin the version to fix it.
REF: …

ci-fix: pin the mingw version 12.2.0.3042023

---

integration/container_stats_test.go
integration/container_stop_test.go
integration/container_without_image_ref_test.go
integration/containerd_image_test.go
integration/image_pull_timeout_test.go
integration/sandbox_run_rollback_test.go
integration/truncindex_test.go

Fix some assertions for integ tests
This patch fixes a few cases in integ tests where arguments are passed to `Equal` methods in incorrect order. The func signature needs `expected` and `actual` in the 2nd, and 3rd places respectively. Before this patch the test failure messages are confusing.
```
func Equal(t TestingT, expected interface{}, actual interface{}, msgAndArgs ...interface{})
```

Fix some assertions for integ tests

---

remotes/docker/config/hosts.go
remotes/docker/config/hosts_test.go
remotes/docker/resolver.go
remotes/docker/resolver_test.go

When a endpoint is configured for http and has a tls configuration, always try to the tls connection and fallback to http when the tls connections fails from receiving an http response. This fixes an issue with default localhost endpoints which get defaulted to http with insecure tls also configured but are using tls.
Fixes #9157

remotes: always try to establish tls connection when tls configured

---

container_opts.go
integration/client/export_test.go
oci/spec_opts.go
pkg/display/manifest_printer.go
pkg/snapshotters/annotations.go
pkg/transfer/local/pull.go
pkg/unpack/unpacker.go
remotes/docker/converter.go
remotes/docker/fetcher.go
remotes/docker/pusher.go
remotes/handlers.go
signals.go

- Follow-up to https://github.com/containerd/containerd/pull/9154
Take advantage of the mediatype helpers from the `images` package throughout the rest of the project, also taking the opportunity to simplify some conditional logic where possible.

Use mediatype helpers in more places

---

remotes/docker/resolver.go
remotes/docker/resolver_test.go

Follows up from https://github.com/containerd/containerd/pull/3400, https://github.com/containerd/containerd/pull/3868, https://github.com/containerd/containerd/pull/5275, and possibly more that I'm missing.
Previously, we would return the first non-404 error from a host.
This is logical, however, it can result in confusing errors to the user:
- e.g. we have an HTTP host, and an HTTPS host.
If the image does not exist, we return "http: server gave HTTP response to HTTPS client". This is technically correct, however, the user is easily confused - the most relevant error in this case is the 404 error.
- e.g. we have a broken HTTP host that returns 5XX errors, and a HTTP host with authentication.
On the request for an image, we return the 5XX error directly. However, we have a host later on …

docker: return most relevant error from docker resolution

---

.github/workflows/ci.yml

go 1.19 is EOL and doesn't work well with windows-2019 in CI.
Cherry-pick from https://github.com/containerd/containerd/pull/9167
This should fix the windows-2019 failures.

[release/1.6] Build binaries with 1.21.1

---

containerd.service

This is the equivalent of https://github.com/moby/moby/pull/45534 (_see for additional insights and review discussion_), and replaces an earlier PR attempt: #7566 (_original author is not responding to feedback_)
Closes: #7566
---
Remove `LimitNOFILE` from `containerd.service` to rely on the systemd v240 implicit default of `1024:524288`. On supported platforms with systemd prior to v240, packagers are expected to patch the service with an explicit `LimitNOFILE=1024:524288`.
- `1024` soft limit is an implicit default, avoiding unexpected breakage. Software that needs a higher limit should request to raise the soft limit for its process.
- `524288` hard limit is an implicit default since systemd v240 and is adequate for most processes (_half of the historical limit from `fs.nr_open` of …

fix: Remove `LimitNOFILE` from `containerd.service`

---

remotes/docker/pusher.go
remotes/docker/pusher_test.go

`MountedFrom` was mistakenly prefixed with the whole target repository instead of just the registry hostname.
Also adjusted the test cases to use the registry hostname.

remotes/docker: Fix MountedFrom prefixed with target repository

---

pkg/cri/sbserver/images/image_pull.go
pkg/cri/sbserver/images/image_pull_test.go
pkg/cri/server/image_pull.go
pkg/cri/server/image_pull_test.go

Pass the passed in context into some nested function calls, and wrap errors instead of %+v.

CRI: Snapshotter per runtime handler adjustments

---

remotes/docker/config/hosts.go
remotes/docker/config/hosts_test.go
remotes/docker/resolver.go
remotes/docker/resolver_test.go

When a endpoint is configured for http and has a tls configuration, always try to the tls connection and fallback to http when the tls connections fails from receiving an http response. This fixes an issue with default localhost endpoints which get defaulted to http with insecure tls also configured but are using tls.
Backport of #9182
Fixes a regression in how localhost is handled with tls

[release/1.7] remotes: always try to establish tls connection when tls configured

---

remotes/docker/config/hosts.go
remotes/docker/config/hosts_test.go
remotes/docker/resolver.go
remotes/docker/resolver_test.go

When a endpoint is configured for http and has a tls configuration, always try to the tls connection and fallback to http when the tls connections fails from receiving an http response. This fixes an issue with default localhost endpoints which get defaulted to http with insecure tls also configured but are using tls.
Backport of #9182
Fixes a regression in how localhost is handled with tls

[release/1.6] remotes: always try to establish tls connection when tls configured

---

remotes/docker/pusher.go
remotes/docker/pusher_test.go

`MountedFrom` was prefixed with the whole target repository instead of just the registry hostname.
Also adjust the test cases to use the registry hostname.
(cherry picked from commit 859c2651e5f3e8a76c1b427a1be99b76d7169b46)
backport: https://github.com/containerd/containerd/pull/9187

[release 1.7] remotes/docker: Fix MountedFrom prefixed with target repository

---

remotes/docker/pusher.go
remotes/docker/pusher_test.go

`MountedFrom` was prefixed with the whole target repository instead of just the registry hostname.
Also adjust the test cases to use the registry hostname.
Signed-off-by: Paweł Gronowski <pawel.gronowski@docker.com>
(cherry picked from commit 859c2651e5f3e8a76c1b427a1be99b76d7169b46)
backport: https://github.com/containerd/containerd/pull/9187

[release 1.6] remotes/docker: Fix MountedFrom prefixed with target repository

---

cmd/containerd/command/config.go
plugin/plugin.go
services/server/config/config.go
services/server/server.go
services/server/server_test.go

As we split apart plugins or rename plugins, the configuration options move. Without migration, the move appears as a breaking change to users since previous values may be ignored without an updated config. This change allows plugins to migrate the values from the old plugin or name without breaking users. In order to accomplish this, we will need to bump the config version in every containerd major/minor release which contains a new config migration. We should also be able to avoid completely deprecating older config versions after this change (version 1 will remain deprecated as we have no migration for it).

Add support for plugin config migration

---

pkg/cri/server/service_linux.go

[release/1.6] cri: stop recommending disable_cgroup

---

oci/spec_opts.go
oci/spec_opts_nonwindows.go
oci/spec_opts_nonwindows_test.go
oci/spec_opts_test.go
oci/spec_opts_windows.go
oci/spec_opts_windows_test.go

Fixes:   #https://github.com/containerd/nerdctl/issues/2485
Windows Containers have a default path already configured at bootup. [WithDefaultPathEnv](https://github.com/containerd/containerd/blob/d015c99b2ec990c914a4b4546ec10d61cd947ab0/oci/spec_opts.go#L193C58-L193C72%60) overwrites this with a unix path

Fix windows default path overwrite

---

pkg/cri/sbserver/sandbox_run.go
pkg/cri/sbserver/sandbox_run_test.go
pkg/cri/server/sandbox_run.go
pkg/cri/server/sandbox_run_test.go

Currently, `containerd` treats `ip_pref = "ipv6"` the same as `ip_pref = "cni"`, because the loop meant to select the first IPv6 address instead selects the first IP address of any kind.
This problem has been allowed to go unnoticed because the test case said to check the behavior when the first input address is an IPv4 address is actually providing an IPv6 address first.
This PR corrects both of the above.

Fix `ip_pref` configuration option

---

Makefile

Allow overriding GO_BUILD_FLAGS via environment, do distros can easily inject additionally required build flags (eg. -buildvcs=false).

Makefile: allow overriding GO_BUILD_FLAGS via environment

---

Makefile
integration/client/container_linux_test.go
integration/failpoint/cmd/runc-fp/issue9103.go
integration/failpoint/cmd/runc-fp/main.go
runtime/v2/runc/task/service.go
script/setup/install-failpoint-binaries

After pr #8617, create handler of containerd-shim-runc-v2 will
call handleStarted() to record the init process and handle its exit.
Although init process wouldn't quit so early in normal circumstances.
But if this screnario occurs, handleStarted() will call
handleProcessExit(), which will cause deadlock because create() had
acquired s.mu, and handleProcessExit() will try to lock it again.
So I add handleProcessExitNoLock() function which will not lock s.mu.
It can safely be called in create handler without deadlock.
Fix: #9103

containerd-shim-runc-v2: avoid potential deadlock in create handler

---

Makefile
cmd/containerd/command/oci-hook.go
integration/client/container_linux_test.go
integration/failpoint/cmd/containerd-shim-runc-fp-v1/plugin_linux.go
integration/failpoint/cmd/runc-fp/issue9103.go
integration/failpoint/cmd/runc-fp/main.go
oci/spec.go
runtime/v2/bundle.go
runtime/v2/runc/manager/manager_linux.go
runtime/v2/runc/task/service.go
runtime/v2/runc/util.go
script/setup/install-failpoint-binaries

- relates to https://github.com/containerd/containerd/pull/8617
- backports https://github.com/containerd/containerd/pull/8780
- backports https://github.com/containerd/containerd/pull/9104
- fixes https://github.com/containerd/containerd/issues/9103
---
After pr #8617, create handler of containerd-shim-runc-v2 will
call handleStarted() to record the init process and handle its exit.
Although init process wouldn't quit so early in normal circumstances.
But if this screnario occurs, handleStarted() will call
handleProcessExit(), which will cause deadlock because create() had
acquired s.mu, and handleProcessExit() will try to lock it again.
So I add handleProcessExitNoLock() function which will not lock s.mu.
It can safely be called in create handler without deadlock.

[release/1.7 backport] containerd-shim-runc-v2: avoid potential deadlock in create handler

---

.github/workflows/build-test-images.yml
.github/workflows/ci.yml
.github/workflows/codeql.yml
.github/workflows/images.yml
.github/workflows/nightly.yml
.github/workflows/release.yml
Vagrantfile
contrib/Dockerfile.test
contrib/fuzz/oss_fuzz_build.sh
script/setup/prepare_env_windows.ps1

go1.21.2 (released 2023-10-05) includes one security fixes to the cmd/go package,
as well as bug fixes to the compiler, the go command, the linker, the runtime,
and the runtime/metrics package. See the Go 1.21.2 milestone on our issue
https://github.com/golang/go/issues?q=milestone%3AGo1.21.2+label%3ACherryPickApproved
full diff: https://github.com/golang/go/compare/go1.21.1...go1.21.2
[security] Go 1.21.2 and Go 1.20.9 are released
Hello gophers,
We have just released Go versions 1.21.2 and 1.20.9, minor point releases.
- cmd/go: line directives allows arbitrary execution during build
"//line" directives can be used to bypass the restrictions on "//go:cgo_" …

update to go1.21.3, go1.20.10

---

cmd/ctr/commands/images/tag.go

check if the target tag that is to be created using ctr image tag is valid and does not contain any forbidden characters.
A new flag `--skip-reference-check`  has been added so that this check for forbidden characters can be skipped. 
Fixes #8844

prevent ctr from creating tags with forbidden characters

---

Makefile
Vagrantfile
cmd/containerd/command/oci-hook.go
integration/client/container_linux_test.go
integration/client/go.mod
integration/client/go.sum
integration/failpoint/cmd/containerd-shim-runc-fp-v1/plugin_linux.go
integration/failpoint/cmd/runc-fp/issue9103.go
integration/failpoint/cmd/runc-fp/main.go
oci/spec.go
runtime/v2/bundle.go
runtime/v2/runc/manager/manager_linux.go
runtime/v2/runc/task/service.go
runtime/v2/runc/util.go
script/setup/install-failpoint-binaries

- relates to https://github.com/containerd/containerd/pull/8617
- backports https://github.com/containerd/containerd/pull/8780
- backports https://github.com/containerd/containerd/pull/9104
- fixes https://github.com/containerd/containerd/issues/9103
---
After pr #8617, create handler of containerd-shim-runc-v2 will
call handleStarted() to record the init process and handle its exit.
Although init process wouldn't quit so early in normal circumstances.
But if this screnario occurs, handleStarted() will call
handleProcessExit(), which will cause deadlock because create() had
acquired s.mu, and handleProcessExit() will try to lock it again.
So I add handleProcessExitNoLock() function which will not lock s.mu.
It can safely be called in create handler without deadlock.

[release/1.6 backport] containerd-shim-runc-v2: avoid potential deadlock in create handler

---

RELEASES.md
services/server/config/config.go
services/server/config/config_test.go
services/server/server.go

A follow up to the plugin config migration, this introduces migration of the configuration file for each version. This also removes the deprecation of version 1, instead introducing a v1->v2 migration. Having built in migration makes the configuration much easier to use within the code since the configuration can always assumed to be at the latest.
Migration time is also added to the log so users will see how much time is saved on startup by running the config migration tool.

Introduce top level config migration

---

runtime/v2/shim/shim.go

In current implementation we exit shim entry point when publisher gets closed.
This behavior will ignore all remaining callbacks registered in shutdown manager.
Instead we should wait for shutdown manager to finish execing all callbacks and only after that exit the shim process.

Exit shim when shutdown manager is done

---

cmd/ctr/commands/run/run_unix.go
oci/spec_opts.go

Issue: https://github.com/containerd/containerd/issues/9078
Add `cpu-burst` param to ctr command, make it support CPU Burst in containerd.

add cpu-burst param to ctr command

---

archive/compression/benchmark_test.go
archive/compression/compression.go
archive/compression/compression_test.go

Intel ISA-L is Intel's open source (BSD) library that outperforms both gzip and pigz. This commit checks and uses igzip if available.

Use Intel ISA-L's igzip if available

---

remotes/docker/authorizer.go
remotes/docker/resolver_test.go

When a credential handler is provided but no basic auth credentials are provided, handle the error specifically rather than treating the credentials as not implemented. This allows a clearer error to be provided to users rather than a confusing not implemented error or generic unauthorized error.
Currently there is no way for the caller to know why the authorization did not work since only the registry's unhandled authorization error is returned. This handles cases where either a user has provided a credential handler but has no saved logins or has token secrets but the registry requested basic auth.
Add unit tests for the basic auth case.

remotes: add handling for missing basic auth credentials

---

pkg/cri/cri.go
services/server/server.go

Fixes hang when plugin which registers readiness fail. Additional fix in CRI to register readiness later on in its initialization.
Backport https://github.com/containerd/containerd/pull/9153 https://github.com/containerd/containerd/pull/9164

[release/1.6] Require plugins to succeed after registering readiness 

---

integration/containerd_image_test.go
integration/images/image_list.go
pull.go

Resolve https://github.com/containerd/containerd/issues/9202
This PR adds a new image label if it is docker schema 1. With the new label, users can find the docker schema1 usage by running `ctr images`
```
$ sudo /usr/local/bin/crictl pull docker.io/progrium/stress:latest
$ sudo ctr -n k8s.io images ls
REF                                                                     TYPE                                       DIGEST                                                                  SIZE     PLATFORMS   LABELS                                                                                                                                               
docker.io/progrium/stress:latest                                        application/vnd.oci.image.manifest.v1+json …
```

Add a new image label if it is docker schema 1

---

RELEASES.md
services/server/config/config.go
services/server/server.go

We, containerd, suggest user to use binary plugins or RPC-based plugins. Since go plugin has too many restrictions, I'm not sure that how many users use the go plugin to extend the core function in the production.
Based on the fact that we put a lot of effort to make external plugins better, suggest to deprecate go-plugin type plugin in v2.0 and remove it in v2.1
REF: https://github.com/containerd/containerd/pull/556

deprecated: go-plugin library as runtime plugin

---

go.mod
go.sum
integration/client/go.mod
integration/client/go.sum
vendor/github.com/klauspost/compress/README.md
vendor/modules.txt

- Release note: https://github.com/klauspost/compress/releases/tag/v1.17.1
- Full changelog: https://github.com/klauspost/compress/compare/v1.17.0...v1.17.1

go.mod: bump up github.com/klauspost/compress from v1.17.0 to v1.17.1

---

go.mod
go.sum
integration/client/go.mod
integration/client/go.sum
vendor/google.golang.org/grpc/internal/transport/http2_server.go
vendor/google.golang.org/grpc/server.go
vendor/google.golang.org/grpc/version.go
vendor/modules.txt

server: prohibit more than MaxConcurrentStreams handlers from running at once (CVE-2023-44487).
In addition to this change, applications should ensure they do not leave running tasks behind related to the RPC before returning from method handlers, or should enforce appropriate limits on any such work.
- https://github.com/grpc/grpc-go/compare/v1.57.0...v1.57.1

vendor: google.golang.org/grpc v1.57.1

---

remotes/docker/authorizer.go
remotes/docker/resolver.go
remotes/docker/resolver_test.go
remotes/errors/errors.go

When a credential handler is provided but no basic auth credentials are provided, handle the error specifically rather than treating the credentials as not implemented. This allows a clearer error to be provided to users rather than a confusing not implemented error or generic unauthorized error.
Add unit tests for the basic auth case.
Backport #9234
(cherry picked from commit 51c9ffe468f8752d851ab6efda61a2f55026edfc)

[release/1.6] remotes: add handling for missing basic auth credentials

---

go.mod
go.sum
integration/client/go.mod
integration/client/go.sum
vendor/github.com/opencontainers/image-spec/specs-go/v1/descriptor.go
vendor/github.com/opencontainers/image-spec/specs-go/v1/layout.go
vendor/github.com/opencontainers/image-spec/specs-go/version.go
vendor/modules.txt

Release note: https://github.com/opencontainers/image-spec/releases/tag/v1.1.0-rc5

go.mod: bump up github.com/opencontainers/image-spec to v1.1.0-rc5

---

images/archive/exporter.go
images/archive/importer.go
integration/client/export_test.go
integration/client/import_test.go

- depends on https://github.com/containerd/containerd/pull/9251
full diff: https://github.com/opencontainers/image-spec/compare/v1.1.0-rc4...v1.1.0-rc5

replace some hardcoded strings with ocispec consts

---

integration/client/container_test.go

The point of this test is to see that we successfully can get all of the pids running in the container and they match the number expected, but for Windows this concept is a bit different. Windows containers essentially go through the usermode boot phase of the operating system, and have quite a few processes and system services running outside of the "init" process you specify. Because of this, there's not a great way to say "there should only be N processes running" like we can ensure
for Linux. 
With all that said, on Windows check that we're at least greater than one ("init"+system services).

Integration: Alter TestContainerPids for Windows

---

services/server/config/config.go
services/server/server.go

Allows external plugins to define exports.
Relevant for allowing external snapshotters to indicate the root directory such as for #9216

Add exports to proxy plugin config

---

pkg/cri/server/container_stats_list.go
pkg/cri/server/container_status_test.go
pkg/cri/server/images/imagefs_info.go
pkg/cri/server/images/imagefs_info_test.go
pkg/cri/server/images/service.go
pkg/cri/server/images/service_test.go
pkg/cri/server/images/snapshots.go
pkg/cri/server/sandbox_stats_windows.go
pkg/cri/server/sandbox_stats_windows_test.go
pkg/cri/server/service.go
pkg/cri/server/test_config.go
pkg/cri/store/snapshot/snapshot.go
pkg/cri/store/snapshot/snapshot_test.go

Before snapshotter per runtime, CRI only supports a global snapshotter. So a snapshot can be uniquely identified by `snapshot_key`. With snapshotter per runtime enabled, there may be multiple snapshotters used by CRI. So only (snapshotter_id, snapshot_key) can uniquely identify a snapshot. Also extends CRI/store/snapshot/Store to support multiple snapshotters.

CRI: use (snapshotter_id, snapshot_key) to uniquely identify snapshots

---

.github/workflows/build-test-images.yml
.github/workflows/ci.yml
.github/workflows/codeql.yml
.github/workflows/images.yml
.github/workflows/nightly.yml
.github/workflows/release.yml
Vagrantfile
contrib/Dockerfile.test
script/setup/prepare_env_windows.ps1

- alternative to https://github.com/containerd/containerd/pull/9227, keeping 1.20.x for building, and test 1.21.3
----
go1.20.9 (released 2023-10-05) includes one security fixes to the cmd/go package,
as well as bug fixes to the go command and the linker. See the Go 1.20.9
milestone on our issue tracker for details:
https://github.com/golang/go/issues?q=milestone%3AGo1.20.9+label%3ACherryPickApproved
full diff: https://github.com/golang/go/compare/go1.20.8...go1.20.9
[security] Go 1.21.2 and Go 1.20.9 are released
Hello gophers,
We have just released Go versions 1.21.2 and 1.20.9, minor point releases.
- cmd/go: line directives allows arbitrary execution during build
"//line" directives …

[release/1.7] update to go1.20.10, test go1.21.3

---

pkg/cri/server/service.go
pkg/cri/server/test_config.go

Avoid calling out to the client to get a sandbox controller and instead setup the list of controllers on initialization. This fixes a test failure which does not set the client.

Initialize sandbox controller list on CRI server creation

---

integration/failpoint/cmd/containerd-shim-runc-fp-v1/plugin_linux.go
integration/issue7496_linux_test.go
integration/issue7496_shutdown_linux_test.go
runtime/v2/binary.go
runtime/v2/bridge.go
runtime/v2/example/example.go
runtime/v2/manager.go
runtime/v2/process.go
runtime/v2/runc/container.go
runtime/v2/runc/manager/manager_linux.go
runtime/v2/runc/task/service.go
runtime/v2/shim.go
runtime/v2/shim/shim.go
runtime/v2/shim/util.go
runtime/v2/shim_load.go
runtime/v2/shim_test.go

- Switch runc shim to task service v3, that was introduced as experimental in 1.7.
- To keep backward compatibility, this PR updates client bridge to support both ttrpc v2/v3 and grpc v3.
- Since we now care about both address and version, the PR reworks how we restore shims - we write `bootstrap.json` file with the whole `BootstrapParam` struct instead of just `address` file. Also current restore was broken as we didn't really use bootstrap params before.
- NOTE: Shims are no longer required to write `address` file. In current implementation both the daemon and shims can write this file, which vagues responsibilities. containerd takes care of it from now on.

Switch runc shim to task service v3 and fix restore

---

mount/mount_idmapped_linux.go
mount/mount_idmapped_linux_test.go
mount/mount_linux.go
snapshots/overlay/overlayutils/check.go
sys/userns_unsafe_linux.go

It's followup for #5890.
The containerd-shim process depends on the mount package to init rootfs
for container. For the container enable user namespace, the mount
package needs to fork child process to get the brand-new user namespace.
However, there are two reapers in one process (described by the
following list) and there are race-condition cases.
1. mount package
2. sys.Reaper as global one which watch all the SIGCHLD.
Currently, we use pipe to ensure that child process is alive. However,
the pide file descriptor can be hold by other process, which the child
process cannot exit by self. We should use [kill(2)][kill] to ensure the
child process exit. But we might kill the wrong process if the child process
might be reaped by containerd-shim and the PID might be reused by other
process. …

idmapped: use pidfd to avoid pid reuse issue

---

metadata/sandbox.go
pkg/cri/server/sandbox_remove.go

The sandbox might be recovered from v1.x release. It doesn't have metadata bucket. We should ignore the not-found error.
How to reproduce the issue:
```bash
➜  containerd git:(main) sudo ctr version
Client:
Version:  1.6.22
Revision: 8165feabfdfe38c65b599c4993d227328c231fca
Go version: go1.19.11
Server:
Version:  1.6.22
Revision: 8165feabfdfe38c65b599c4993d227328c231fca
UUID: be4216aa-8a2e-4305-9186-efeacd2d9a17
➜  containerd git:(main) cat /tmp/pod.json
{
"metadata": {
"name": "nginx-sandbox",
"namespace": "default",
"attempt": 1,
"uid": "hdishd83djaidwnduwk28bcsb"
},
"log_directory": "/tmp",
"linux": {
}
}
➜  containerd git:(main) sudo crictl runp /tmp/pod.json
616ea1cc657c57e80abf74e707a8177878ac2ec1ab7c346b4adb7bc0fadf986e
➜  containerd git:(main) sudo crictl pods
POD ID …
```

pkg/cri: should ignore no sandbox bucket

---

script/setup/install-protobuf

- backport of https://github.com/containerd/containerd/pull/7237
(cherry picked from commit 426fcfbc5281b0f1912584f086f9de04682c583a)

[release/1.6 backport] fix protobuf aarch64

---

.github/workflows/ci.yml

Disable windows-2019 integration tests until mingw issue is fixed.
Better disable test than merge with red tests. Re-enable this with fix.

Disable windows-2019 integration test temporarily

---

.github/workflows/ci.yml
integration/remote/util/util_windows.go

Release note of golangci-lint v1.55.0: https://github.com/golangci/golangci-lint/releases/tag/v1.55.0

ci: bump up golangci-lint to v1.55.0

---

contrib/fuzz/builtins.go
contrib/fuzz/builtins_linux.go
contrib/fuzz/builtins_unix.go
contrib/fuzz/builtins_windows.go
contrib/fuzz/containerd_import_fuzzer.go
contrib/fuzz/daemon.go

Avoid importing the cmd libraries and create the server instance directly from the server library.
Removes the dependency on cmd which is blocking the submodule PR.

fuzz: update go fuzz to directly instantiate server

---

remotes/docker/pusher.go
remotes/docker/pusher_test.go

When the HTTP fallback is used, the scheme changes from HTTPS to HTTP which can cause a mismatch on redirect, causing the authorizer to get stripped out. Since the redirect host must match the redirect host in this case, credentials are only sent to the same origin host that returned the redirect.
This fixes an issue for a push getting a 401 unauthorized on the PUT request even though credentials are available.
A likely fix for the issue in #9283

Check scheme and host of request on push redirect

---

go.mod
go.sum
integration/client/go.mod
integration/client/go.sum
vendor/github.com/klauspost/compress/zstd/enc_best.go
vendor/modules.txt

fixes data corruption with zstd output in "best"
full diff: https://github.com/klauspost/compress/compare/v1.17.1...v1.17.2
relates to https://x.com/sh0dan/status/1716342769671655791?s=20

vendor: github.com/klauspost/compress v1.17.2

---

remotes/docker/config/hosts.go
remotes/docker/config/hosts_test.go
remotes/docker/pusher.go
remotes/docker/pusher_test.go

Backport
- Avoid TLS fallback when protocol is not ambiguous #9283
- Check scheme and host of request on push redirect #9294

[release/1.7] Fix ambiguous tls fallback

---

releases/v1.7.8.toml
version/version.go

----
Welcome to the v1.7.8 release of containerd!
The eighth patch release for containerd 1.7 contains various fixes and updates.
* **Fix ambiguous TLS fallback** ([#9299](https://github.com/containerd/containerd/pull/9299))
* **Update Go to 1.20.10** ([#9265](https://github.com/containerd/containerd/pull/9265))
* **Add a new image label on converted schema 1 images** ([#9252](https://github.com/containerd/containerd/pull/9252))
* **Fix handling for missing basic auth credentials** ([#9235](https://github.com/containerd/containerd/pull/9235))
* **Fix potential deadlock in create handler for containerd-shim-runc-v2** ([#9209](https://github.com/containerd/containerd/pull/9209))
Please try out the release binaries and report any …

[release/1.7] Prepare release notes for v1.7.8

---

remotes/docker/config/hosts.go
remotes/docker/config/hosts_test.go
remotes/docker/pusher.go
remotes/docker/pusher_test.go

Backport
- Avoid TLS fallback when protocol is not ambiguous #9283
- Check scheme and host of request on push redirect #9294

[release/1.6] Fix ambiguous tls fallback

---

cmd/containerd-stress/main.go
cmd/containerd/command/main.go
cmd/ctr/app/main.go
docs/ops.md

Minor enhancement to the CLI `containerd`, `ctr`, and `containerd-stress` printed output when running with the `--help` flag. 
Ensures those `--help` output descriptions are consistently uppercase (minus those starting with containerd)  in addition to the `ops.md` doc reference to the `containerd --help` output is accurate.

Update cli --help output for consistency

---

integration/windows_hostprocess_test.go
pkg/cri/server/container_create_windows_test.go
pkg/cri/server/container_execsync.go

fixes: https://github.com/containerd/containerd/issues/9037
The PR https://github.com/containerd/containerd/pull/8198 fixed this for CRI but missed clearing the commandline in the forked SB server. This simply adds that back in.

CRI: Handle ArgsEscaped for new Sb Server by clearing commandline in spec

---

pkg/cri/config/config.go
pkg/cri/config/config_test.go
pkg/cri/cri.go
pkg/deprecation/deprecation.go

These haven't been removed from `main` yet, so opening them here and then will backport.

cri: add deprecation warnings for mirrors, auths, and configs

---

.github/workflows/ci.yml
Vagrantfile

This Vagrant on Mac job has been broken for a while. Instead this change moves Vagrant to larger Linux workers that provide nested virtualization.
Our main branch did something similar (moving to Cirrus CI to larger GitHub-hosted runners) already as #8919.

[release/1.6] ci: Use Vagrant on ubuntu-latest-4-cores

---

.mailmap
releases/v2.0.0-beta.toml
version/version.go

This is an early draft for the 2.0.0 release notes but will let us start cutting the beta releases.
The checked in release notes are shorter and will utilize https://github.com/containerd/release-tool/pull/45 for generating the highlight notes which were included in the checked in version in prior releases. These are generated from pull request titles and labels, currently the notes look like...
---
Welcome to the v2.0.0-beta.0 release of containerd!  
as well as the removal of features which were deprecated in 1.x. …

Prepare release notes for 2.0.0-beta.0

---

client/container_checkpoint_opts.go

runtime v1 is deprecated, and this error appears to be unused.

client: remove obsolete ErrCheckpointRWUnsupported

---

integration/issue7496_linux_test.go
integration/issue7496_shutdown_linux_test.go
runtime/v1/linux/task.go

```go
// Delete the initial process and container
func (s *Service) Delete(ctx context.Context, r *ptypes.Empty) (*shimapi.DeleteResponse, error) {
p, err := s.getInitProcess()
return nil, err
}
if err := p.Delete(ctx); err != nil {
return nil, errdefs.ToGRPC(err)
}
// The client might canceled the request but the shim service still
// moved on. The `delete(s.processes, s.id)` was executed
// successfully. So the next Delete call will return `container
// must be created` error. The client side should ignore this
// issue.
s.mu.Lock()
delete(s.processes, s.id)
s.mu.Unlock()
s.platform.Close()
return &shimapi.DeleteResponse{
ExitStatus: uint32(p.ExitStatus()),
ExitedAt:   protobuf.ToTimestamp(p.ExitedAt()),
Pid:        uint32(p.Pid()),
}, nil
}
```
introduced by #9003 …

[release/1.7] fix: shimv1 leak issue

---

pkg/cri/config/config.go
pkg/cri/config/config_kernel_linux.go
pkg/cri/config/config_kernel_linux_test.go
pkg/cri/config/config_kernel_other.go

Fixes: https://github.com/containerd/containerd/issues/8636
add verify when enable  unprivileged kernel version whether less than 4.11.

add verify kernel version when enable unprivileged

---

contrib/fuzz/cri_sbserver_fuzzer.go
contrib/fuzz/cri_server_fuzzer.go
integration/image_pull_timeout_test.go
pkg/cri/cri.go
pkg/cri/instrument/instrumented_service.go
pkg/cri/sbserver/service.go
pkg/cri/server/service.go
pkg/cri/server/service_test.go
pkg/cri/server/testing/fake_warning_service.go
pkg/deprecation/deprecation.go

This PR reports the usage of the deprecated v1alpha2 api by hooking warning service into instrumented_service.
Since v1alpha2 is removed from main, I am submitting the PR directly against release/1.7.

[release/1.7] Expose usage of cri-api v1alpha2

---

docs/PLUGINS.md
docs/man/containerd-config.toml.5.md
runtime/v2/README.md

Add documentation as to how containerd uses multiple runtimes, how to configure them in the config file, and how to invoke them using CLI. Based on an [extended conversation in Slack](https://cloud-native.slack.com/archives/C4RJZ9Z6Y/p1694435552169529) with input provided by @AkihiroSuda and @mikebrow 
With this in place, hopefully the next person with the same questions will have immediate answers, and not require an extended Slack conversation.
Two key points:
1. I am not 100% sure I got it correct; the point of the PR is to capture those learnings and document them, providing an opportunity to correct errors.
2. The very last line is a `TODO`, as I am not sure why we have the config file entries at all, if both the shim name/path and binary name are provided as gRPC parameters (or in …

document runtime and shim configuration and selection

---

.github/workflows/build-test-images.yml
.github/workflows/ci.yml
.github/workflows/codeql.yml
.github/workflows/images.yml
.github/workflows/nightly.yml
.github/workflows/release.yml
Vagrantfile
contrib/Dockerfile.test
script/setup/prepare_env_windows.ps1

- alternative to https://github.com/containerd/containerd/pull/9226, keeping 1.20.x for building, and test 1.21.3
----
go1.20.9 (released 2023-10-05) includes one security fixes to the cmd/go package,
as well as bug fixes to the go command and the linker. See the Go 1.20.9
milestone on our issue tracker for details:
https://github.com/golang/go/issues?q=milestone%3AGo1.20.9+label%3ACherryPickApproved
full diff: https://github.com/golang/go/compare/go1.20.8...go1.20.9
[security] Go 1.21.2 and Go 1.20.9 are released
Hello gophers,
We have just released Go versions 1.21.2 and 1.20.9, minor point releases.
- cmd/go: line directives allows arbitrary execution during build
"//line" directives …

[release/1.6] update to go1.20.10, test go1.21.3

---

go.mod
integration/release_upgrade_linux_test.go
integration/release_upgrade_utils_linux_test.go

RIP legacy CRI in https://github.com/containerd/containerd/pull/9228. 
The pull request is to init release upgrade testing cases to check sandbox-like CRI implementation is compatible with v1.x release. It's part of [#3757 ](https://github.com/containerd/containerd/issues/3757#issuecomment-1768775256)

integration: init release upgrade testing

---

integration/issue7496_linux_test.go
runtime/v1/linux/task.go

```go
// Delete the initial process and container
func (s *Service) Delete(ctx context.Context, r *ptypes.Empty) (*shimapi.DeleteResponse, error) {
p, err := s.getInitProcess()
return nil, err
}
if err := p.Delete(ctx); err != nil {
return nil, errdefs.ToGRPC(err)
}
// The client might canceled the request but the shim service still
// moved on. The `delete(s.processes, s.id)` was executed
// successfully. So the next Delete call will return `container
// must be created` error. The client side should ignore this
// issue.
s.mu.Lock()
delete(s.processes, s.id)
s.mu.Unlock()
s.platform.Close()
return &shimapi.DeleteResponse{
ExitStatus: uint32(p.ExitStatus()),
ExitedAt:   protobuf.ToTimestamp(p.ExitedAt()),
Pid:        uint32(p.Pid()),
}, nil
}
```
introduced by #9004 …

[release/1.6] fix: shimv1 leak issue

---

pkg/cri/config/config_unix.go

Fixes: https://github.com/containerd/containerd/issues/6924
current we add verify kernel version when enable unprivileged https://github.com/containerd/containerd/pull/9172, so we can default enable unprivileged icmp and ports.

add default enable unprivileged icmp/ports

---

.golangci.yml

- relates to https://github.com/opencontainers/runc/issues/3028

golangci-lint: enable depguard to prevent re-introducing libcontainer

---

pkg/cri/labels/labels.go
pkg/cri/server/container_create.go
pkg/cri/server/helpers.go
pkg/cri/server/helpers_test.go
pkg/cri/server/nri.go
pkg/cri/server/podsandbox/helpers.go
pkg/cri/server/podsandbox/helpers_test.go
pkg/cri/server/podsandbox/recover.go
pkg/cri/server/podsandbox/sandbox_run.go
pkg/cri/server/restart.go

remove the duplication of labels used in cri/server and move them to a common package cri/labels

refactor labels used in cri server

---

ADOPTERS.md

remove project from ADOPTERS as it is now inactive.
Follow up of : https://github.com/containerd/containerd.io/pull/203

adopters.md: remove Eliot project

---

runtime/v2/shim/shim.go
services/server/config/config_test.go
services/server/server.go

Also some minor refactor/fixes;
These logs were already using structured logs, so include "id" as a field,
which also prevents the id being quoted (and escaped when printing);
time="2023-11-15T11:30:23.745574884Z" level=info msg="loading plugin \"io.containerd.internal.v1.shutdown\"..." runtime=io.containerd.runc.v2 type=io.containerd.internal.v1
time="2023-11-15T11:30:23.745612425Z" level=info msg="loading plugin \"io.containerd.ttrpc.v1.pause\"..." runtime=io.containerd.runc.v2 type=io.containerd.ttrpc.v1
time="2023-11-15T11:30:23.745620884Z" level=info msg="loading plugin \"io.containerd.event.v1.publisher\"..." runtime=io.containerd.runc.v2 type=io.containerd.event.v1
time="2023-11-15T11:30:23.745625925Z" level=info msg="loading plugin \"io.containerd.ttrpc.v1.task\"..." …

services/server, runtime/v2/shim: use structured log for plugin ID

---

pkg/unpack/unpacker.go

Adds debug message per layer unpacking and adds duration field to the existing image unpacking debug message.
Enabled debug logging and pulled a remote container image using containerd client.
```
DEBU[0002] layer unpacked                                duration=1.85479628s layer="sha256:ee649e0574bc181056f3ad7d6cfbbf11df90636ee21663254099ee9b61f7daa1"
DEBU[0002] image unpacked                                chainID="sha256:f0d9a81fc6ee8ceecb397caab06f344911c5e6cb7f9ab2830a151852f2d36041" config="sha256:c8cd5ac90067a1bd4ecd9569d4fc873a9a2d905c13be255cb8a8a76f4b499988" duration=1.857971524s
```

Enhance container image unpack client logs

---

releases/v1.7.9.toml
version/version.go

Welcome to the v1.7.9 release of containerd!
The ninth patch release for containerd 1.7 contains various fixes and updates.
* **update runc binary to v1.1.10::** ([#9359](https://github.com/containerd/containerd/pull/9359))
* **vendor: upgrade OpenTelemetry to v1.19.0 / v0.45.0** ([#9301](https://github.com/containerd/containerd/pull/9301))
* **Expose usage of cri-api v1alpha2** ([#9336](https://github.com/containerd/containerd/pull/9336))
* **integration: deflake TestIssue9103** ([#9354](https://github.com/containerd/containerd/pull/9354))
* **fix: shimv1 leak issue** ([#9344](https://github.com/containerd/containerd/pull/9344))
* **cri: add deprecation warnings for mirrors, auths, and configs** ([#9327](https://github.com/containerd/containerd/pull/9327))
* **Update hcsshim tag to …

[release/1.7] Add release notes for v1.7.9

---

pkg/cri/store/image/image.go
pkg/cri/store/image/image_test.go

fix: https://github.com/containerd/containerd/issues/9328
A image is pinned when any of its references has the pinned label.
When none of the references to a image have the pinned label, the image is not pinned.

cri: fix update of pinned label for images

---

go.mod
go.sum
integration/client/go.sum
vendor/github.com/emicklei/go-restful/.gitignore
vendor/github.com/emicklei/go-restful/.travis.yml
vendor/github.com/emicklei/go-restful/CHANGES.md
vendor/github.com/emicklei/go-restful/Makefile
vendor/github.com/emicklei/go-restful/README.md
vendor/github.com/emicklei/go-restful/container.go
vendor/github.com/emicklei/go-restful/cors_filter.go
vendor/github.com/emicklei/go-restful/curly.go
vendor/github.com/emicklei/go-restful/custom_verb.go
vendor/github.com/emicklei/go-restful/jsr311.go
vendor/github.com/emicklei/go-restful/parameter.go
vendor/github.com/emicklei/go-restful/path_processor.go
vendor/github.com/emicklei/go-restful/request.go
vendor/github.com/emicklei/go-restful/response.go
vendor/github.com/emicklei/go-restful/route.go
vendor/github.com/emicklei/go-restful/route_builder.go
vendor/github.com/emicklei/go-restful/route_reader.go
vendor/github.com/emicklei/go-restful/service_error.go
vendor/github.com/emicklei/go-restful/web_service.go
vendor/modules.txt

Remove CVE-2022-1996 from containerd binary upgrading go-restful to 2.16.0
https://github.com/advisories/GHSA-r48q-9g5r-8q2h

[Release/1.6] CVE-2022-1996 fix for go-restful

---

README.md
RELEASES.md
docs/PLUGINS.md
docs/client-opts.md
docs/content-flow.md
docs/garbage-collection.md
docs/getting-started.md
docs/namespaces.md
docs/ops.md
docs/remote-snapshotter.md

This change is to update Go module and package references in code examples and documentation for the containerd v2.0 release.
1. Manually validated Godoc links
2. Walk through of getting started example using new references.
```
2023/11/16 01:04:53 Successfully pulled docker.io/library/redis:alpine image
2023/11/16 01:04:53 Successfully created container with ID redis-server and snapshot with ID redis-server-snapshot
1:C 16 Nov 2023 01:04:53.831 # WARNING Memory overcommit must be enabled! Without it, a background save or replication may fail under low memory condition. Being disabled, it can also cause failures without low memory condition, see https://github.com/jemalloc/jemalloc/issues/1328. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the …
```

Update documentation for containerd v2.0 packages

---

integration/containerd_image_test.go
pkg/cri/store/image/image.go
pkg/cri/store/image/image_test.go

https://github.com/containerd/containerd/pull/8867 and https://github.com/containerd/containerd/pull/9338 are complete fixes for the pinned image, so I cherry-picked them in one pr
(cherry picked from commit https://github.com/containerd/containerd/commit/7f7ba31b649f0d3224bd780e17f264f1ef4c3833)
(cherry picked from commit https://github.com/containerd/containerd/commit/2e014fa2ac27d7c7d89d639d1cecb47ad70b98e8)

[release/1.6] cri: fix using the pinned label to pin image

---

pkg/cri/server/podsandbox/controller.go

introduced by 09723a61755ffe5312ac7f0f65949f10b5931b91
----
The lease plugin doesn't have service type. So, like image/container apis, they needs lease plugin.
```
=== CONT  TestCRIImagePullTimeout/HoldingContentOpenWriter
log_hook.go:47: time="2023-11-17T23:32:54.448668709+08:00" level=info msg="metadata content store policy set" func=plugin.init.1.func1 file="/home/fuwei/go/src/github.com/containerd/containerd/metadata/plugin/plugin.go:134" policy=shared testcase=TestCRIImagePullTimeout/HoldingContentOpenWriter
build_local_containerd_helper_test.go:120:
Error Trace:    /home/fuwei/go/src/github.com/containerd/containerd/integration/build_local_containerd_helper_test.go:120
/home/fuwei/go/src/github.com/containerd/containerd/integration/image_pull_timeout_test.go:113
Error: …
```

fix: podsandbox depends on Lease plugin

---

.mailmap
releases/v1.6.25.toml
version/version.go

containerd 1.6.25
Welcome to the v1.6.25 release of containerd!
The twenty-fifth patch release for containerd 1.6 contains various fixes and updates.
* **Check whether content did not needs to be pushed to remote registry and cross-repo mounted or already existed** ([#9111](https://github.com/containerd/containerd/pull/9111))
* **Soft deprecate log package** ([#9105](https://github.com/containerd/containerd/pull/9105))
* **Always try to establish tls connection when tls configured** ([#9189](https://github.com/containerd/containerd/pull/9189))
* **CRI: stop recommending disable_cgroup** ([#9169](https://github.com/containerd/containerd/pull/9169))
* **Allow for images with artifacts layers to pull** ([#9150](https://github.com/containerd/containerd/pull/9150))
* **Require plugins to …

[release/1.6] Prepare release notes for v1.6.25

---

integration/build_local_containerd_helper_test.go
integration/image_pull_timeout_test.go
pkg/cri/config/config.go
pkg/cri/config/config_unix.go
pkg/cri/config/config_windows.go
pkg/cri/server/images/image_pull.go
remotes/docker/httpreadseeker.go

Close connection if no more data. It's to fix false alert filed by image
pull progress.
```
dst = OpenWriter (--> Content Store)
src = Fetch
Open (--> Registry)
Mark it as active request
Copy(dst, src) (--> Keep updating total received bytes)
^
|  (Active Request > 0, but total received bytes won't be updated)
v
defer src.Close()
content.Commit(dst)
```
Before migrating to transfer service, CRI plugin doesn't limit global
concurrent downloads for ImagePulls. Each ImagePull requests have 3 concurrent
goroutines to download blob and 1 goroutine to unpack blob. Like ext4
filesystem [1][1], the fsync from content.Commit may sync unrelated dirty pages
into disk. The host is running under IO pressure, and then the content.Commit
will take long time and block other goroutines. If httpreadseeker …

fix: ImagePull should close http connection if there is no available data to read.

---

.github/workflows/ci.yml
.golangci.yml

golangci-lint v1.55.2: https://github.com/golangci/golangci-lint/releases/tag/v1.55.2
This PR also fixes  .golangci.yml not to contain directories that don't exist.

Bump up golangci-lint to v1.55.2 and tiny fix on .golangci.yml

---

remotes/handlers.go

- related to: https://github.com/containerd/containerd/pull/9029
Propagate parent distribution source labels to each of its children even if they're not missing. This allows to cross-repo mount blobs when the child content has different distribution source label from its parent manifest/index. This could happen when different parts of image were fetched from different sources.
This extends the behavior from https://github.com/containerd/containerd/pull/9029 to all content (not only the missing content).

push: always inherit distribution sources from parent

---

cmd/containerd-stress/cri_worker.go

The ticker will leak in the case `tctx.Done()`

fix ticker leak

---

integration/build_local_containerd_helper_test.go
integration/image_pull_timeout_test.go
pkg/cri/config/config.go
pkg/cri/config/config_unix.go
pkg/cri/config/config_windows.go
pkg/cri/server/image_pull.go
remotes/docker/httpreadseeker.go

Cherry-picking https://github.com/containerd/containerd/pull/9369 to 1.7

[release/1.7] fix: ImagePull should close http connection if there is no available data to read.

---

pkg/dialer/dialer_windows.go

This commit fixes the dialer function to make sure that "npipe://" prefix is trimmed, just like the way it is done in the Unix counterpart, `./dialer_unix.go:50`
This will also unblock some downstream work going on in buildkit; setting up integration tests to run on Windows - https://github.com/moby/buildkit/pull/4432
/cc. @gabriel-samfira

pkg/dialer: minor fix on dialer function for windows

---

cmd/containerd-stress/main.go

This change removes the hard-coded containerd endpoint for CRI test
and use the address in the config which would honor the CLI flag.

containerd-stress: use config address for CRI test

---

.mailmap
releases/v1.7.10.toml
version/version.go

Welcome to the v1.7.10 release of containerd!
The tenth patch release for containerd 1.7 contains various fixes and updates.
* **Enhance container image unpack client logs** ([#9379](https://github.com/containerd/containerd/pull/9379))
* **cri: fix using the pinned label to pin image** ([#9381](https://github.com/containerd/containerd/pull/9381))
* **fix: ImagePull should close http connection if there is no available data to read.** ([#9409](https://github.com/containerd/containerd/pull/9409))
* Wei Fu
* Iceber Gu
* Austin Vazquez
* Phil Estes
* Samuel Karp
* ruiwen-zhao
<details><summary>10 commits</summary>
<p>
* …

Add release notes for v1.7.10

---

remotes/docker/fetcher.go
remotes/docker/fetcher_test.go

Golang net/http already transparently supports gzip compression.
This adds support for zstd compression
-----------------
This PR takes over https://github.com/containerd/containerd/pull/7563 since @ndeloof is no longer working on this as per https://github.com/containerd/containerd/pull/7563#discussion_r1107591429.
Also took the chance to address some small comments in the previous PR.

Support gzip and zstd HTTP transport compression to fetch remote resources

---

oci/spec_opts.go
oci/spec_opts_nonwindows.go
oci/spec_opts_nonwindows_test.go
oci/spec_opts_test.go
oci/spec_opts_windows.go
oci/spec_opts_windows_test.go

Windows Containers have a default path already configured at bootup. WithDefaultPathEnv overwrites this with a unix path
(cherry picked from commit 7d636908746beb1330dad76fb86bb8235e1303cc without any additional changes)

[release/1.7] Windows default path overwrite fix

---

oci/spec_opts.go
oci/spec_opts_nonwindows.go
oci/spec_opts_nonwindows_test.go
oci/spec_opts_test.go
oci/spec_opts_windows.go
oci/spec_opts_windows_test.go

Windows Containers have a default path already configured at bootup. WithDefaultPathEnv overwrites this with a unix path
(cherry picked from commit 7d636908746beb1330dad76fb86bb8235e1303cc without any additional changes)

[release/1.6] Windows default path overwrite fix

---

content/content.go
remotes/handlers.go

Backport https://github.com/containerd/containerd/pull/9029 and https://github.com/containerd/containerd/pull/7763 (for clean cherry-pick)
When a blob does not exist locally, rather than erroring on info
lookup, inherit the parent distribution sources. Push is able
to succeed even if the blob does not exist locally when a cross
repository mount is done. This is a common operation pushing a
multi-platform image to the same registry but different namespace.
ctr change not included because it is a behavior change (like in the 1.7 backport).

[release/1.6] push: inherit distribution sources from parent

---

runtime/v2/shim.go

This is mostly to workaround an issue with gRPC based shims after containerd restart. If a shim dies while containerd is also down/restarting, on reboot grpc.DialContext with our current set of DialOptions will make us wait for 100 seconds per shim even if the socket no longer exists or has no listener.

runtime/v2: net.Dial gRPC shim sockets before trying grpc

---

pkg/deprecation/deprecation.go
services/tasks/local.go
services/tasks/local_darwin.go
services/tasks/local_freebsd.go
services/tasks/local_unix.go
services/tasks/local_windows.go

```
$ sudo bin/ctr deprecations list
ID                                           LAST OCCURRENCE                   MESSAGE    
io.containerd.deprecation/runtime-v1         2023-12-01T07:26:57.614014991Z    The `io.containerd.runtime.v1.linux` runtime is deprecated since containerd v1.4 and removed in containerd v2.0. Use the `io.containerd.runc.v2` runtime instead.
io.containerd.deprecation/runtime-runc-v1    2023-12-01T07:27:34.505898489Z    The `io.containerd.runc.v1` runtime is deprecated since containerd v1.4 and removed in containerd v2.0. Use the `io.containerd.runc.v2` runtime instead.
```

[release/1.7] tasks: emit warning for v1 runtime and runc v1 runtime

---

runtime/v2/shim.go

This is mostly to workaround an issue with gRPC based shims after containerd restart. If a shim dies while containerd is also down/restarting, on reboot grpc.DialContext with our current set of DialOptions will make us wait for 100 seconds per shim even if the socket no longer exists or has no listener.
(cherry picked from commit 0bc9633414126c3296e26b39848bd26f3b7e838c)

[release/1.7] runtime/v2: net.Dial gRPC shim sockets before trying grpc

---

cmd/containerd-shim-runc-v2/process/init.go

The runtime-spec just merged this PR:
https://github.com/opencontainers/runtime-spec/pull/1224
This means that it is now possible to request idmap mounts by specifying "idmap" or "ridmap" in the mount options, without any mappings.
Let's add a check to see if they are requested in that way too.

pkg/process: Check using idmap mount options too

---

snapshots/windows/windows.go

If a snapshot removal fails (during garbage collection), the entire garbage collection operation is cancelled. This is problematic because once cleanup of any snapshot fails no other snapshots will be cleaned and the disk usage will just keep increasing.
Solution is to return snapshot removal errors wrapped as "ErrFailedPrecondition" errors. The garbage collectors continues cleanup if the error is of this type.

Don't block snapshot garbage collection on Remove failures

---

pkg/cri/config/config.go
pkg/cri/config/config_test.go
pkg/deprecation/deprecation.go

Part of #9312 
This is the rest of the CRI configs that are deprecated other than `CriuPath`, which is separate (it's a runc option in the v2 runtimes).

[release/1.7] cri: add deprecation warnings for deprecated CRI configs

---

pkg/cri/instrument/instrumented_service.go

Previous https://github.com/containerd/containerd/pull/9336 added warnings for the usage of cri-api `Status` and `Version`. 
There are some use cases where clients might use cri-apis without calling those two apis. For example, 
1. client uses crictl to pre-pull container images,
2. client uses `ContainerStatus` to find the container for a certain pid for monitoring purposes.
Therefore, this PR adds warning to all cri-api v1alpha2 apis.

[release/1.7] Add cri-api v1alpha2 usage warning to all api calls

---

.github/workflows/build-test-images.yml
.github/workflows/ci.yml
.github/workflows/codeql.yml
.github/workflows/images.yml
.github/workflows/nightly.yml
.github/workflows/release.yml
Vagrantfile
contrib/Dockerfile.test
script/setup/prepare_env_windows.ps1

- relates to https://github.com/containerd/containerd/pull/9351
go1.20.12 (released 2023-12-05) includes security fixes to the go command,
and the net/http and path/filepath packages, as well as bug fixes to the
compiler and the go command. See the Go 1.20.12 milestone on our issue
- https://github.com/golang/go/issues?q=milestone%3AGo1.20.12+label%3ACherryPickApproved
- full diff: https://github.com/golang/go/compare/go1.20.11...go1.20.12
from the security mailing:
[security] Go 1.21.5 and Go 1.20.12 are released
Hello gophers,
We have just released Go versions 1.21.5 and 1.20.12, minor point releases.
- net/http: limit chunked data overhead
A malicious HTTP sender can use chunk extensions …

[release/1.6] update to go1.20.12, test go1.21.5

---

snapshots/windows/windows.go

- backport of https://github.com/containerd/containerd/pull/9465
If a snapshot removal fails (during garbage collection), the entire garbage collection operation is cancelled. This is problematic because once cleanup of any snapshot fails no other snapshots will be cleaned and the disk usage will just keep increasing.
Solution is to return snapshot removal errors wrapped as "ErrFailedPrecondition" errors. The garbage collectors continues cleanup if the error is of this type.
(cherry picked from commit ad96fded4cafe550e1291d89f3a869397b14ae83)

[release/1.7] Don't block snapshot garbage collection on Remove failures

---

.github/workflows/release/Dockerfile
.github/workflows/release/Dockerfile.dockerignore

Ignore previous release-artifacts so that repeated builds rebuild them. Before this patch, building the dockerfile multiple times would rebuild the binaries, but would not produce a new release-artifact (`.tar.gz`), because the make target would not trigger if the file was already present.
With this patch, existing release-artifacts are no longer copied into the Dockerfile, which prevents this, as well as saving some time copying files that won't be used.
I also added `.DS_Store` files to the ignore-file. These files are generated on macOS when navigating the filesystem, and would cause the build to fail if present, as well as invalidating the build-cache;
docker buildx build --build-arg RELEASE_VER=main --build-arg UBUNTU_VERSION=22.04 --build-arg GO_VERSION=1.21.5 -f …

release: add .dockerignore to fix repeated builds

---

.github/workflows/build-test-images.yml
.github/workflows/ci.yml
.github/workflows/codeql.yml
.github/workflows/images.yml
.github/workflows/nightly.yml
.github/workflows/release.yml
Vagrantfile
contrib/Dockerfile.test
script/setup/prepare_env_windows.ps1

- relates to https://github.com/containerd/containerd/pull/9351
go1.20.12 (released 2023-12-05) includes security fixes to the go command,
and the net/http and path/filepath packages, as well as bug fixes to the
compiler and the go command. See the Go 1.20.12 milestone on our issue
- https://github.com/golang/go/issues?q=milestone%3AGo1.20.12+label%3ACherryPickApproved
- full diff: https://github.com/golang/go/compare/go1.20.11...go1.20.12
from the security mailing:
[security] Go 1.21.5 and Go 1.20.12 are released
Hello gophers,
We have just released Go versions 1.21.5 and 1.20.12, minor point releases.
- net/http: limit chunked data overhead
A malicious HTTP sender can use chunk extensions …

[release/1.7] update to go1.20.12, test go1.21.5

---

releases/v1.6.26.toml
version/version.go

---
containerd 1.6.26
Welcome to the v1.6.26 release of containerd!
The twenty-sixth patch release for containerd 1.6 contains various fixes and updates.
* **Fix windows default path overwrite issue** ([#9441](https://github.com/containerd/containerd/pull/9441))
* **Update push to inherit distribution sources from parent** ([#9453](https://github.com/containerd/containerd/pull/9453))
* **Mask `/sys/devices/virtual/powercap` path in runtime spec and deny in default apparmor profile** ([GHSA-7ww5-4wqc-m92c](https://github.com/containerd/containerd/security/advisories/GHSA-7ww5-4wqc-m92c))
* **Emit deprecation warning for AUFS snapshotter usage** ([#9448](https://github.com/containerd/containerd/pull/9448))
* **Emit deprecation warning for v1 runtime usage** …

[release/1.6] Prepare release notes for v1.6.26

---

releases/v1.7.11.toml
version/version.go

---
containerd 1.7.11
Welcome to the v1.7.11 release of containerd!
The eleventh patch release for containerd 1.7 contains various fixes and updates including
one security issue.
* **Fix Windows default path overwrite issue** ([#9440](https://github.com/containerd/containerd/pull/9440))
* **Update push to always inherit distribution sources from parent** ([#9452](https://github.com/containerd/containerd/pull/9452))
* **Update shim to use net dial for gRPC shim sockets** ([#9458](https://github.com/containerd/containerd/pull/9458))
* **Fix otel version incompatibility** ([#9483](https://github.com/containerd/containerd/pull/9483))
* **Fix Windows snapshotter blocking snapshot GC on remove failure** ([#9482](https://github.com/containerd/containerd/pull/9482))
* …

[release/1.7] Prepare release notes for v1.7.11

---

.github/workflows/ci.yml
mount/mount_idmapped_linux_test.go
script/setup/install-critools

There are many Kubernetes clusters running on ARM64. Enable ARM64 runner
is to commit to support ARM64 platform officially.

*: enable ARM64 runner

---

go.mod
go.sum
vendor/github.com/pelletier/go-toml/v2/.gitignore
vendor/github.com/pelletier/go-toml/v2/README.md
vendor/github.com/pelletier/go-toml/v2/SECURITY.md
vendor/github.com/pelletier/go-toml/v2/ci.sh
vendor/github.com/pelletier/go-toml/v2/unmarshaler.go
vendor/modules.txt

Release note: https://github.com/pelletier/go-toml/releases/tag/v2.1.1

go.mod: Bump up github.com/pelletier/go-toml to v2.1.1

---

.github/workflows/links.yml
.lycheeignore
README.md
docs/cri/installation.md
docs/historical/cri/proposal.md
docs/historical/reports/2017-01-13.md
releases/v1.1.0.toml

Docs tend to outdate very quickly. 
This PR adds a nightly job to periodically verify links are not broken in our docs.
Results will be reported in the job's summary.
The job will run independently from others and will not affect others if broken links found. This helps to maintain better doc quality and allows to identify problems quicker.
Output example:
<details>
</details>

Add nighly job to verify doc links (and fix broken links)

---

.github/dependabot.yml

This will only apply to the `main` branch.
The interval is set to `weekly`, with `open-pull-requests-limit: 10`.

CI: enable dependabot

---

pkg/cri/config/config.go
pkg/cri/server/helpers.go
pkg/cri/server/helpers_test.go
pkg/cri/server/runtime_config_linux.go
pkg/cri/server/sandbox_run.go
plugins/types.go

This PR moves GenerateRuntimeOptions() to the cri config package as this function is directly accessing information from the structures defined in pkg/cri/config/config.go anyway.
Also, this change will be useful to have for the image pull per runtime class feature where we would need to initialize list of platform matchers for each runtime.

Move GenerateRuntimeOptions() to pkg/cri/config

---

oci/spec_opts.go
oci/spec_opts_linux_test.go

Scratch images don't necessarily have the /etc/group file, so we shouldn't fail if opening/parsing it is not needed: if all the group to add are numeric.

WithAppendAdditionalGroups: better /etc/group handling 

---

.github/dependabot.yml

See https://github.blog/changelog/2023-06-30-grouped-version-updates-for-dependabot-public-beta/

dependabot: enable groups

---

oci/spec_opts.go
oci/spec_opts_linux_test.go

Backport of https://github.com/containerd/containerd/pull/9494
Scratch images don't necessarily have the /etc/group file, so we shouldn't fail if opening/parsing it is not needed: if all the group to add are numeric.
(cherry picked from commit 1398186ca7e40089868f8183652249d3e13c9dd2)

[release/1.7 backport] WithAppendAdditionalGroups: better /etc/group handling

---

integration/remote/remote_runtime.go

This caused golangci-lint to fail in https://github.com/containerd/containerd/pull/9535

integration: fix format string for klog.Infof

---

.github/workflows/ci.yml
script/setup/install-critools

There are many Kubernetes clusters running on ARM64. Enable ARM64 runner is to commit to support ARM64 platform officially.
(cherry picked from commit cb5a48e6453da65c4b8e5694ec5ed88f72b19737)
not a clean cherry-pick of #9456

[release/1.7] *: enable ARM64 runner

---

pkg/cri/config/config.go
pkg/cri/config/config_test.go
pkg/deprecation/deprecation.go

cherry-pick of https://github.com/containerd/containerd/pull/9469

[release/1.6] cri: add deprecation warnings for deprecated CRI configs
