- oci/spec_opts.go
- oci/spec_opts_linux_test.go
Backport of https://github.com/containerd/containerd/pull/9494
Scratch images don't necessarily have the /etc/group file, so we shouldn't fail if opening/parsing it is not needed: if all the group to add are numeric.
(cherry picked from commit 1398186ca7e40089868f8183652249d3e13c9dd2)
> [release/1.6 backport] WithAppendAdditionalGroups: better /etc/group handling

- tracing/plugin/otlp.go
Before this, containerd would always print an error when shutting down;
ERRO[2023-12-07T14:35:00.070333131Z] failed to close plugin                        error="context canceled" id=io.containerd.internal.v1.tracing
> tracing/plugin: newTracer: ignore context.Canceled errors on Close()

- README.md
Fix CI badge links to filter only `merge_group` events as main branch now uses `merge_group` to push changes. This will give a more accurate representation of the status of CI rather than showing the complete status of CI workflow.
> docs: fix CI badge in README

- pkg/dialer/dialer_windows.go
cherry-pick commit 8e91edb71e29c84333cca20894991d244144696f
Backport of #9412
> [release 1.7] backport: fix on dialer function for windows

- pkg/deprecation/deprecation.go
- runtime/restart/monitor/change.go
- runtime/restart/monitor/monitor.go
> [release/1.7] restart: containerd.io/restart.logpath warning

- runtime/v2/shim/util.go
Fixes ae7021300
In ae7021300 the WritePidFile and WriteAddress functions were changed to use AtomicFile instead of os.CreateFile. However, AtomicFile creates a temporary file and then changes its permissions with os.Chmod which alters the previously observed behavior of os.CreateFile which takes the system's umask into account.
This means that on Linux-based systems these files suddenly became world writable (#9363). The address file has since been removed, but pid-file was still created as world writable. This commit explicitly requests 0644 permissions as even on systems without default umask of 0022 there is no reason to have these two files world writable.
(cherry picked from commit 088d5cfbd23f06727c9d872dbe690f00d4f9be53)
> shim: Create pid-file with 0644 permissions

- pkg/cri/instrument/instrumented_service.go
Correct error code helps clients to decide when it should retry request.
> fix: return gRPC code "unavailable" if server is not initialized yet

- client/import.go
- content/helpers.go
- images/archive/exporter.go
- integration/client/export_test.go
- integration/client/import_test.go
Allow importing/exporting archives which doesn't have all the referenced blobs. 
This allows to export/import an image with only some of the platforms available locally while still persisting the full index.
> The blobs directory MAY be missing referenced blobs, in which case the missing blobs SHOULD be fulfilled by an external blob store.
https://github.com/opencontainers/image-spec/blob/v1.0/image-layout.md#blobs
> import/export: Support references to missing content 

- diff/windows/cimfs.go
- snapshots/windows/cimfs.go
CimFS is available only on WS 2022 OS builds with revision >= 2031. This check was added to the CimFS init() function but this causes multiple other plugin loads to fail if the host OS build does not support the above mentioned. Hence moving this function to CimFS operation functions to let the init() go through successfully.
> Fix CimFS plugin init error

- content/helpers.go
- images/archive/exporter.go
- import.go
- integration/client/export_test.go
- integration/client/go.mod
- integration/client/import_test.go
- backport: https://github.com/containerd/containerd/pull/9554
- backport: https://github.com/containerd/containerd/pull/9154/commits/377c5ca9cd4b44e8e1cd13e0aa46e2db77f16d7f
Allow importing/exporting archives which doesn't have all the referenced blobs. 
This allows to export/import an image with only some of the platforms available locally while still persisting the full index.
> The blobs directory MAY be missing referenced blobs, in which case the missing blobs SHOULD be fulfilled by an external blob store.
https://github.com/opencontainers/image-spec/blob/v1.0/image-layout.md#blobs
> [release/1.7 backport] import/export: Support references to missing content 

- .github/workflows/windows-hyperv-periodic.yml
- .github/workflows/windows-periodic.yml
This is a follow up to the [investigation](https://github.com/containerd/containerd/pull/9601#issuecomment-1877679153) found after these jobs started to fail.  
This uses the "latest" tag for the VM image so we get updates regularly with out needing to up date the jobs monthly.
fyi @kiashok
> [Windows] Use latest VM image in CI to get Windows updates regularly

- client/import.go
- cmd/ctr/commands/images/import.go
- integration/client/import_test.go
This PR introduces an option for assigning `labels` at the `import` step.
The current implementation provides a way to label images at the pull(fetch) step, and labeling images at the import step reduces additional steps.
related
- https://github.com/kubernetes-sigs/kind/pull/3444 
- https://github.com/kubernetes-sigs/kind/issues/3441
Fixes #9505
> add label flags to ctr import

- runtime/v2/shim/util.go
Fixes ae7021300
In ae7021300 the WritePidFile and WriteAddress functions were changed to use AtomicFile instead of os.CreateFile. However, AtomicFile creates a temporary file and then changes its permissions with os.Chmod which alters the previously observed behavior of os.CreateFile which takes the system's umask into account.
This means that on Linux-based systems these files suddenly became world writable (#9363). This commit explicitly requests 0644 permissions as even on systems without default umask of 0022 there is no reason to have these two files world writable.
This should be affecting only 1.6 (introduced in 1.6.22) and 1.7 as 2.0+ uses boostrap.json to store the address file (not sure about the pid file, but WritePidFile also uses 0666 in release/2.0 and master) and 1.5 does …
> [release/1.7] shim: Create pid-file and address with 0644 permissions

- runtime/v2/shim/util.go
- backport of https://github.com/containerd/containerd/pull/9571
- relates to https://github.com/containerd/containerd/pull/8609 / https://github.com/containerd/containerd/pull/8826
Fixes ae7021300
In ae7021300 the WritePidFile and WriteAddress functions were changed to use AtomicFile instead of os.CreateFile. However, AtomicFile creates a temporary file and then changes its permissions with os.Chmod which alters the previously observed behavior of os.CreateFile which takes the system's umask into account.
This means that on Linux-based systems these files suddenly became world writable (#9363). The address file has since been removed, but pid-file was still created as world writable. This commit explicitly requests 0644 permissions as even on systems without default umask of 0022 there …
> [release/1.6 backport] shim: Create pid-file with 0644 permissions

- content/content.go
- images/archive/exporter.go
- images/usage/calculator.go
- pkg/cri/store/image/image.go
- pkg/display/manifest_printer.go
The interface that combines both content.InfoProvider and content.Provider was duplicated in multiple places - create one directly in `content` package and use it instead.
> content: Add InfoReaderProvider

- integration/main_test.go
- integration/sandbox_run_rollback_test.go
- pkg/cri/server/base/sandbox_info.go
- pkg/cri/server/events.go
- pkg/cri/server/podsandbox/controller.go
- pkg/cri/server/podsandbox/controller_test.go
- pkg/cri/server/podsandbox/helpers.go
- pkg/cri/server/podsandbox/recover.go
- pkg/cri/server/podsandbox/sandbox_delete.go
- pkg/cri/server/podsandbox/sandbox_run.go
- pkg/cri/server/podsandbox/sandbox_status.go
- pkg/cri/server/podsandbox/sandbox_stop.go
- pkg/cri/server/podsandbox/store.go
- pkg/cri/server/podsandbox/types/podsandbox.go
- pkg/cri/server/restart.go
- pkg/cri/server/sandbox_run.go
- pkg/cri/server/sandbox_status.go
- pkg/cri/server/sandbox_stop.go
- pkg/cri/server/service.go
For decoupling of podsandbox controller to cri service, podsandbox controller should create its own cache of PodSandbox object.
> sandbox: remove sandboxStore from podsandbox controller

- plugins/sandbox/controller.go
When using a grpc shim, if a scenario arises where both containerd and the shim process are killed, a situation arises where calls to `StopPodSandbox` after a containerd restart would fail citing reasons that the sandbox can't be found or a connection cannot be made to it.
This change treats such situations as non-failure cases so that the cleanup process can continue.
> Handle failure when stopping a sandbox

- .github/workflows/build-test-images.yml
- .github/workflows/ci.yml
- .github/workflows/codeql.yml
- .github/workflows/images.yml
- .github/workflows/nightly.yml
- .github/workflows/release.yml
- Vagrantfile
- contrib/Dockerfile.test
- script/setup/prepare_env_windows.ps1
- related: https://github.com/containerd/containerd/pull/9623
go1.20.13 (released 2024-01-09) includes fixes to the runtime and the crypto/tls package. See the Go 1.20.13 milestone on our issue tracker for details:
- https://github.com/golang/go/issues?q=milestone%3AGo1.20.13+label%3ACherryPickApproved
- full diff: https://github.com/golang/go/compare/go1.20.12...go1.20.13
go1.21.6 (released 2024-01-09) includes fixes to the compiler, the runtime, and the crypto/tls, maps, and runtime/pprof packages. See the Go 1.21.6 milestone on our issue tracker for details:
- https://github.com/golang/go/issues?q=milestone%3AGo1.21.6+label%3ACherryPickApproved
- full diff: https://github.com/golang/go/compare/go1.21.5...go1.21.6
> [release/1.6] update to go1.20.13, test go1.21.6

- .github/workflows/build-test-images.yml
- .github/workflows/ci.yml
- .github/workflows/codeql.yml
- .github/workflows/images.yml
- .github/workflows/nightly.yml
- .github/workflows/release.yml
- Vagrantfile
- contrib/Dockerfile.test
- script/setup/prepare_env_windows.ps1
- related: https://github.com/containerd/containerd/pull/9623
go1.20.13 (released 2024-01-09) includes fixes to the runtime and the crypto/tls package. See the Go 1.20.13 milestone on our issue tracker for details:
- https://github.com/golang/go/issues?q=milestone%3AGo1.20.13+label%3ACherryPickApproved
- full diff: https://github.com/golang/go/compare/go1.20.12...go1.20.13
go1.21.6 (released 2024-01-09) includes fixes to the compiler, the runtime, and the crypto/tls, maps, and runtime/pprof packages. See the Go 1.21.6 milestone on our issue tracker for details:
- https://github.com/golang/go/issues?q=milestone%3AGo1.21.6+label%3ACherryPickApproved
- full diff: https://github.com/golang/go/compare/go1.21.5...go1.21.6
> [release/1.7] update to go1.20.13, test go1.21.6

- releases/v1.6.27.toml
- version/version.go
Prepare release notes for v1.6.27
----
Welcome to the v1.6.27 release of containerd!
The twenty-seventh patch release for containerd 1.6 contains various fixes and updates.
* **Improve `/etc/group` handling when appending groups** ([#9543](https://github.com/containerd/containerd/pull/9543))
* **Update runc binary to v1.1.11** ([#9597](https://github.com/containerd/containerd/pull/9597))
* **Remove runc import** ([#9606](https://github.com/containerd/containerd/pull/9606))
* **Update shim pidfile permissions to 0644** ([#9613](https://github.com/containerd/containerd/pull/9613))
* **Update Go version to 1.20.13** ([#9625](https://github.com/containerd/containerd/pull/9625))
* **Emit deprecation warning for CRIU config usage** ([#9448](https://github.com/containerd/containerd/pull/9448))
* …
> [release/1.6] Prepare release notes for v1.6.27

- client/client.go
- cmd/ctr/commands/images/mount.go
- cmd/ctr/commands/images/usage.go
- defaults/defaults_snapshotter_linux.go
- defaults/defaults_snapshotter_unix.go
- defaults/defaults_snapshotter_windows.go
- integration/client/client.go
- integration/client/client_test.go
- integration/client/image_test.go
- integration/client/snapshot_test.go
- integration/image_pull_timeout_test.go
- pkg/cri/config/config_unix.go
- pkg/cri/config/config_windows.go
- pkg/transfer/local/pull.go
- pkg/transfer/local/pull_test.go
- plugins/transfer/plugin.go
Move the DefaultSnapshotter constants to the defaults package. Fixes issue #8226.
> Move DefaultSnapshotter constants

- .github/workflows/ci.yml
- integration/container_update_resources_test.go
- script/setup/install-cni
- script/setup/install-critools
Carry #9557 
Cherry: 
* https://github.com/containerd/containerd/pull/9456 
* https://github.com/containerd/containerd/pull/6595 : arm64 runner enables cgroupv2 and we need to backport this fix as well.
> [release/1.6] carry #9557 - enable ARM CI

- .github/workflows/ci.yml
actions/upload-artifact@v4 marks artifacts as immutable. Thus, tests which use matrix should have a unique artifact name while using upload-artifact github action
Ref: https://github.com/actions/upload-artifact/releases/tag/v4.0.0
Artifact name modified as per the migration steps here https://github.com/actions/upload-artifact/blob/1eb3cb2b3e0f29609092a73eb033bb759a334595/docs/MIGRATION.md?plain=1#L47
> ci: make artifact name unique in linux integration

- docs/cri/config.md
- pkg/cri/config/config_unix.go
CDI support is required by the [Kubernetes Device Plugin framework](https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/4009-add-cdi-devices-to-device-plugin-api)
The support is [enabled by default in the Kubernetes 1.29](https://github.com/kubernetes/kubernetes/blob/v1.29.0/pkg/features/kube_features.go#L1047).
It would be great to have it enabled by default in the Containerd.
> config: enable CDI by default

- client/image.go
When trouble shooting the soci-snapshotter, i ran into this error message:
```
Jan 15 03:41:52 ip-172-31-34-36.ec2.internal containerd[61824]: time="2024-01-15T03:41:52.716007163Z" level=info msg="apply failure, attempting cleanup" error="failed to extract layer sha256:961e93cda9dd918dbe26aca24cccd6c5db05176850d2c53476d881df5d0d4816: failed to get reader from content store: content digest sha256:9457426d68990df190301d2e20b8450c4f67d7559bdb7ded6c40d41ced6731f7: not found" key="extract-708941494-FkPj sha256:961e93cda9dd918dbe26aca24cccd6c5db05176850d2c53476d881df5d0d4816"
```
it would have been easier to debug if the image name was apparent in the error message itself (instead of trying to track down all the SHA's for layer id? digest? etc)
> include image name in error message

- cmd/ctr/commands/images/export.go
- cmd/ctr/commands/images/import.go
- cmd/ctr/commands/images/pull.go
- cmd/ctr/commands/images/push.go
- cmd/ctr/commands/images/tag.go
Prior to this commit, `--local=false` had to be explicitly specified to opt-in to the transfer service
> ctr: use transfer service by default

- .github/workflows/ci.yml
"Larger" runners are no longer required for nested virt with Linux
> CI: use standard GHA runners

- core/mount/mount_test.go
- core/mount/temp.go
Will address https://github.com/containerd/containerd/issues/6406. Which will allow us to use volatile w/overlay mounts.
> Remove overlayfs volatile option on temp mounts

- cmd/containerd/command/config.go
- cmd/containerd/server/config/config.go
- cmd/containerd/server/config/config_test.go
- integration/client/migration_test.go
- integration/client/testdata/default-1.6.toml
- integration/client/testdata/default-1.7.toml
- pkg/cri/server/base/cri_base.go
- plugins/transfer/plugin.go
Adds tests for the config migration and fixes a few issues and inconsistencies with the config.
Updated the default unpack config to be empty and apply the default during init. There might be a better solution here to keep the default config showing up in the toml, but need to look more into the way we merge configurations. Currently we always merge the given configuration over the default. When there is a non-empty slice defined as the default, it ends up always appending with our current merge mode.
> Add migration tests

- content/content.go
- images/archive/exporter.go
- adapt: https://github.com/containerd/containerd/pull/9607
Create interface that combines both content.InfoProvider and content.Provider in `content` package.
(cherry picked from commit 8235665e7ea8c41725c747cb6a5149918db58410)
> [release/1.7] content: Add InfoReaderProvider

- pkg/cri/server/sandbox_run.go
We should set sandbox CreatedAt first time when we create sandbox struct,
and then set sandbox CreatedAt second time after container started.
Before this commit, we just set sandbox CreatedAt after container
started, but if network create failed, the sandbox time is the
default time, which is 269 years ago, so we need to set sandbox
CreatedAt at first, even if an error occurred before start container.
> pod: CreatedAt time will be 269 years ago if create cri network failed

- cmd/containerd/builtins/builtins.go
- cmd/containerd/builtins/builtins_freebsd.go
- cmd/containerd/builtins/builtins_linux.go
- cmd/containerd/builtins/builtins_unix.go
The walker plugin isn't used on Windows so it shouldn't be loaded. It results in:
```
ctr: rpc error: code = Unknown desc = failed to extract layer sha256:14cf21987a8be92c5cd8ca93777bdf9535cd176cc50ff972ab8f93e884fe7e30: failed to mount C:\Users\jstur\AppData\Local\Temp\containerd-mount4084806450: no Files folder in layer 2081
```
Fixes https://github.com/containerd/containerd/issues/8563
After https://github.com/containerd/containerd/pull/9432 the local transfer service fails to pull Windows containers because it incorrectly selects the wrong differ. See https://github.com/containerd/containerd/issues/8563 for details on the failures with the transfer service.
The issue arises because the `platform.Parse`/`Format` doesn't pass the all the required info and would be fixed by …
> Remove walker diff plugin for Windows

- cmd/ctr/commands/content/content.go
- core/remotes/docker/fetcher.go
A media type string passed via `WithMediaType()` was not propagated to a descriptor returned by `FetchByDigest()`.
Follow-up to:
- #8744
> remotes: FetchByDigest: propagate media type from config to desc

- contrib/seccomp/seccomp_default.go
The following syscalls were added since kernel v5.16 (34f7173491c45cca5c19643b54cc6f9fe0f92f04):
- v5.17 (libseccomp v2.5.4): set_mempolicy_home_node
- v6.5  (libseccomp v2.5.5): cachestat
- v6.6  (libseccomp v2.5.5): fchmodat2, map_shadow_stack
- v6.7  (libseccomp v2.5.5): futex_wake, futex_wait, futex_requeue
[Not covered in this commit]
- v6.8-rc1: statmount, listmount, lsm_get_self_attr, lsm_set_self_attr, lsm_list_modules
ref:
- `syscalls: update the syscall list for Linux v5.17` (libseccomp v2.5.4) https://github.com/seccomp/libseccomp/commit/d83cb7ac252db91e9ca9c372ea4743e02ba97c50
- `all: update the syscall table for Linux v6.7-rc3`  (libseccomp v2.5.5) https://github.com/seccomp/libseccomp/commit/53267af3fb56eed93a50b8ef92f41825c97a7813
> seccomp: kernel 6.7

- integration/container_event_test.go
- integration/main_test.go
- internal/eventq/eventq.go
- internal/eventq/eventq_test.go
- pkg/cri/server/container_events.go
- pkg/cri/server/helpers.go
- pkg/cri/server/service.go
A solution to multiple subscribers and dropped events.
The current approach uses a large buffered channel which has no option except to eventually drop events if there are no subscribers. One explored approach of throwing those into goroutines may end up leaking those goroutines if the events are never subscribed to. This solution attempts to use a timeout for the events and discard them if there are no subscribers after a given amount of time. There is no limit to the number of events it will queue up before discarding, so it may be ideal to have this be configurable.
Fixes #8892
Closes #7318
Alternative to
#9652 
#8916
> Add support for multiple subscribers to CRI container events

- .github/workflows/links.yml
Should be disabled in forks 
Fixes https://github.com/containerd/containerd/issues/9701
> Disable Links workflow in forks 

- core/remotes/docker/auth/fetch.go
- core/remotes/docker/authorizer.go
The authorization code in remotes/docker/authorizer.go currently ignores OAuth token expiration times that are provided by the issuer, instead relying on the caller to inform it of authentication failures to learn of token invalidations. This is slightly inefficient because round-trip requests to the server can be made using tokens that the client knows are expired, and requires the client to reauthorize more often that is strictly necessary. This PR tracks the token-issuer-provided expiration time along with the token itself and preemptively refreshes expired tokens when authorization requests are received for expired tokens.
I believe this the bearer auth case of https://github.com/containerd/containerd/issues/6377, though I noticed it in a slightly different context: we encountered …
> remotes/docker/authorizer.go: refresh OAuth tokens when they expire

- RELEASES.md
- docs/cri/config.md
- integration/container_volume_linux_test.go
- pkg/cri/config/config.go
- pkg/cri/config/config_kernel_linux.go
- pkg/cri/config/config_kernel_other.go
- pkg/cri/config/config_test.go
- pkg/cri/opts/spec_linux_opts.go
- pkg/cri/server/container_create.go
- pkg/cri/server/container_create_linux_test.go
- plugins/cri/runtime/plugin.go
Prior to this commit, `readOnly` volumes were not recursively read-only and could result in compromise of data;
e.g., even if `/mnt` was mounted as read-only, its submounts such as `/mnt/usbstorage` were not read-only.
This commit utilizes runc's "rro" bind mount option to make read-only bind mounts literally read-only. The "rro" bind mount options is implemented by calling `mount_setattr(2)` with `MOUNT_ATTR_RDONLY` and `AT_RECURSIVE`.
The "rro" bind mount options requires kernel >= 5.12, with runc >= 1.1 or a compatible runtime such as crun >= 1.4.
When the "rro" bind mount options is not available, containerd falls back to the legacy non-recursive read-only mounts by default.
The behavior is configurable via `/etc/containerd/config.toml`:
```toml
version = 2 …
```
> cri: make read-only mounts recursively read-only

- defaults/defaults_differ_windows.go
- plugins/transfer/plugin.go
- plugins/transfer/plugin_defaults_other.go
- plugins/transfer/plugin_defaults_windows.go
When using the transfer service on Windows 2022+ the additional differ causes the following error:
```
ctr -n k8s.io i pull docker.io/sigwindowstools/kube-proxy:v1.23.1-calico-hostprocess
docker.io/sigwindowstools/kube proxy:v1.        fetching image content
└──manifest (c48ba3477127)                      already exists
├──config (066f734ecf45)                     already exists
├──layer (034b2f457cdf)                      already exists
├──layer (ada5b21af3a9)                      already exists
├──layer (ed001f67f319)                      already exists
└──layer (5cbcfd29d56a)                      already exists
application/vnd.docker.distribution.manifest.v2+json sha256:c48ba34771272db7411cd5151f2af179577d135e747c4f0f11c9e13250d69ca4
Pulling from OCI Registry …
```
> Add a default differ for Windows that matches the snapshotter when using transfer service

- plugins/gc/scheduler.go
- plugins/gc/scheduler_test.go
- plugins/restart/monitor.go
Remove some duplicated duration parsers for TOML.
Consume one from `tomlext` package that we've introduced recently.
> Remove duplicated TOML duration parsers

- integration/issue7496_linux_test.go
Support inject delay running with the old version (4.x) of strace for test case
Only the newer version of strace can support `--detach-on` options and set time duration with human readable string.
In the 4.x version of strace, using `-b` to replace `--detach-on`, and injecting a delay with int usecs.
> Support inject delay running with the old version (4.x) of strace for test case

- docs/NRI.md
- integration/client/testdata/default-1.7.toml
- pkg/nri/config.go
As discussed this in the last community meetings, we'd like to flip NRI on by default in 2.0. The consensus was that this should be safe to do and there was no opposing opinions voiced. Hence this PR flips the default from disabled to enabled and updates the documentation accordingly.
> Flip NRI on by default.

- .github/workflows/ci.yml
- script/setup/upgrade_chocolaty_windows_2019.ps1
- script/setup/upgrade_mingw_windows_2019.ps1
This PR moves out a few inline PS1 scripts into dedicated files to keep `ci.yml` size minimal.
> [CI] Move inline PS scripts into files

- core/metadata/db.go
- core/metadata/images.go
- core/metadata/snapshot.go
- internal/cri/server/images/image_pull.go
- internal/cri/server/images/image_remove.go
- internal/cri/server/images/service.go
- plugins/cri/images/plugin.go
- plugins/services/images/local.go
The metadata store is in the best place to handle events directly after the database has been updated. This prevents every user of the image store interface from having to know whether or not they are responsible for publishing events and avoid double events if the grpc local service is used.
Note: originally we did not do event publishing in the metadata store since a transaction can ride the context and events should be published after a successful transaction. Managing transactions above the metadata store is not currently used, but doing so would require managing the events separately. If we want to support this pattern better in the future we can queue up events during a transaction and publish them on success at the end.
> Move image event publishing to metadata store

- integration/containerd_image_test.go
- internal/cri/server/images/image_pull.go
Fixes: #9726 
Update the `CRIImageService.UpdateImage` routine to pass image ref to `getLabels` so that a CRI image could be correctly pinned if it's pulled outside of CRI, e.g. via `ctr image pull`.
> bug fix: make sure cri image is pinned when it is pulled outside cri

- .github/actions/install-go/action.yml
- .github/workflows/build-test-images.yml
- .github/workflows/ci.yml
- .github/workflows/codeql.yml
- .github/workflows/fuzz.yml
- .github/workflows/images.yml
- .github/workflows/nightly.yml
This PR moves `setup-go` step into a separate composite action that can be called from other workflows. This significantly reduced the number of places where we need to change go versions.
> Extract setup-go step into composite action

- README.md
Issue:
N/A
Description:
The links GitHub Action workflow is failing after a refactor to move the CRI package from pkg/cri to internal/cri.
> Fix CRI link in readme

- .github/workflows/scorecards.yml
Issue:
N/A
Description:
Fixes scorecards workflow showing NodeJS 16 deprecation warnings.
Testing performed:
Ran scorecards workflow in fork:
Before
After
Unclear why this was not picked up by the dependabot automation, this [commit](https://github.com/containerd/containerd/commit/f9303d04ded5dc1c560ef23a1b87c66ae24a0579) seems to suggest it should have gone from v2 to v3.
> Update codeql-action/upload-sarif dependency in scorecards workflow

- integration/containerd_image_test.go
- pkg/cri/sbserver/image_pull.go
- pkg/cri/server/image_pull.go
Cherry-pick: #9732 
(cherry picked from commit 1eaf0c1f04ebc76ed6e1c6c86da3fb7decde6c60)
> [release/1.7] bug fix: make sure cri image is pinned when it is pulled outside cri

- internal/cri/server/sandbox_status.go
- internal/cri/server/sandbox_status_test.go
We added support for userns but we weren't showing it in the
PodSandboxStatus.
Let's just show the whole nsOpts, so we don't forget in the future
either if something else inside there changes.
Please note that this will expose the content of nsOpts.TargetId that we
weren't exposing before. But that seemed like a bug to me.
> Include userns info in cri/server PodSandboxStatus

- contrib/gce/configure.sh
on 2/7 the k8s upstream jobs picked up a new version of ubuntu kernel and some of the NFS related jobs started failing:
- https://testgrid.k8s.io/sig-node-containerd#containerd-e2e-ubuntu&width=20
- https://testgrid.k8s.io/sig-node-containerd#image-validation-ubuntu-e2e&width=20
We had the same issue with `kops` based tests as well which we fixed by setting `LimitNOFILE` explicitly to a known previous value:
https://github.com/kubernetes/kops/pull/16329
So we want to see if fixing this in the install scripts for the CI jobs works for us. Also note the pending PR here:
https://github.com/containerd/containerd/pull/9660
and the note back from 2019:
https://github.com/containerd/containerd/issues/3201#issuecomment-481720276
> Fix for k8s nfs related tests probably caused by `ulimit` changes

- docs/remote-snapshotter.md
N/A
Remote snapshotter document update for unpacker link to point to new location after refactor.
Links workflow passes in fork.
> Fix unpacker link in remote snapshotter docs

- internal/cri/config/config.go
- internal/cri/server/status.go
- internal/cri/server/status_test.go
Propagate the deprecation list to CRI runtime conditions.
```console
{                                                                                
"status": {                                                                                                                                                      
"conditions": [                                                              
{                          
"type": "RuntimeReady",   
"status": true,                
"reason": "",            
"message": ""           
},                        
{                        
"type": "NetworkReady",                                                  
"status": true,              
"reason": "",                                                            
"message": ""                  
}, …
```
> cri: propagate deprecation list to runtime status

- pkg/events/exchange/exchange.go
Move high volume event publishing and forwarding logs to trace logs.
> Move high volume event logs to Trace level

- pkg/cri/config/config.go
- pkg/cri/server/status.go
- pkg/cri/server/status_test.go
> [release/1.7] cri: propagate deprecation list to runtime status

- pkg/cri/config/config.go
- pkg/cri/server/status.go
- pkg/cri/server/status_test.go
> [release/1.6] cri: propagate deprecation list to runtime status

- integration/cri-api/pkg/apis/services.go
- integration/image_pull_timeout_test.go
- integration/main_test.go
- integration/release_upgrade_linux_test.go
- integration/remote/remote_image.go
- internal/cri/server/container_status_test.go
- internal/cri/server/images/image_pull.go
- internal/cri/server/podsandbox/controller.go
- internal/cri/server/podsandbox/sandbox_run.go
- internal/cri/server/service.go
Starting with k8s cri-api v0.29.1, CRI supports new runtime handler flag. This flag is intended to be used for image pull, remove, status.
P.S. : The intent of this PR is to just merely pass the newly added runtime handler flag (added in v0.29.* k8s cri) to CRIImageService.PullImage() as it does not currently have access to the whole PullImageRequest value. It is only given the sandboxConfig and would need runtime handler as well for supporting image pull per runtime class.
> Pass runtimehandler from CRI to pull image request

- events/exchange/exchange.go
(cherry picked from commit 4dcf089fa30ebc3a733edbaedc79130c21a9b887)
> [release/1.7] Move high volume event logs to Trace level

- cmd/containerd/command/config.go
- cmd/containerd/server/config/config.go
- cmd/containerd/server/config/config_test.go
- cmd/containerd/server/server.go
- cmd/containerd/server/server_test.go
- contrib/fuzz/daemon.go
- plugins/cri/cri.go
- plugins/cri/images/plugin.go
- plugins/cri/runtime/plugin.go
- version/version.go
Moving the config version prevents needing to importing config from under `cmd` into `plugins` or `internal`. Even if we move `config` out of `cmd`  to `internal`, we will still want the version accessible for importers to handle config migration.
> Move config version to version package

- events/exchange/exchange.go
(cherry picked from commit 4dcf089fa30ebc3a733edbaedc79130c21a9b887)
> [release/1.6] Move high volume event logs to Trace level

- cmd/containerd/server/config/config.go
- cmd/containerd/server/config/config_test.go
Closes #9745 
Previously, resolveImports would apply a glob filter if the path contained any '*', or otherwise convert relative paths to absolute. This meant that it was impossible to specify globs with paths relative to the main config file.
This commit first resolves relative to absolute paths, then applies the glob filter (if any). A test case is added to ensure that this now works as expected.
> Fix config import relative path glob

- integration/client/container_linux_test.go
- integration/client/container_test.go
In current implementation, there a few tests specific to `runc-fp`, so we have the following check to exclude them for `crun`:
```go
if os.Getenv("RUNC_FLAVOR") == "crun" {
t.Skip("skip it when using crun")
}
```
We also run tests for rust-shim in rust-extensions and these tests fail.
This PR flips the logic for `RUNC_FLAVOR` env, so we don't have to pretend to be `crun`.
> Run failpoints tests only for runc

- .github/workflows/ci.yml
Currently, we maintain a list of required jobs that needs to be green in order to be merged via the merge queue. There is no mask support, so each job has to be added individually.
This causes problems for matrix jobs, as each time when OS, Go version, or platform changes, a corresponding update has to be made in the UI.
This PR workarounds this problem and adds another jobs, which reports status of all jobs it depends on (including jobs with matrices). The job has a fixed title, which can be added to the UI just once.
> Workaround "required job statuses" job list

- integration/cri-api/pkg/apis/services.go
- integration/issue7496_linux_test.go
- integration/issue7496_shutdown_linux_test.go
- integration/release_upgrade_linux_test.go
- integration/release_upgrade_utils_linux_test.go
- integration/remote/remote_runtime.go
Summary:
* Add some helper functions to reduce duplicate code in upgrade testsuite
* Change Runtime.Status proto so that we can dump CRI configuration by API
* Add some checkers to ensure there is no leaky resources after upgrade
* Add failpoint in existing recover case: new release containerd should take over dead shim correctly
* Add new case to check new release containerd can parse metric data from existing shim created by previous release.
Closes: #3757 
> NOTE: We should create new issue to track test suite in windows platform. For linux, I think we can close #3757 if this one is acceptable.
> test: update upgrade test suite in integration

- RELEASES.md
- client/pull.go
- core/remotes/docker/schema1/converter.go
- integration/client/client_test.go
- integration/client/client_unix_test.go
- integration/containerd_image_test.go
- pkg/deprecation/deprecation.go
Schema 1 (`application/vnd.docker.distribution.manifest.v1+prettyjws`) has been officially deprecated since containerd v1.7 (PR #6884).
We have planned to remove the support for Schema 1 in containerd v2.0, but this removal may still surprise some users.
So, in containerd v2.0 we will just disable it by default.
The support for Schema 1 can be still enabled by setting an environment variable `CONTAINERD_ENABLE_DEPRECATED_PULL_SCHEMA_1_IMAGE=1` (`ctr` users need to specify `--local` too), however, this workaround will be completely removed in containerd v2.1.
Schema 2 was introduced in Docker 1.10 (Feb 2016), so most users should have been already using Schema 2 or OCI.
- - -
Depends on:
- - -
Backup: https://github.com/AkihiroSuda/containerd/commit/bac85b89506ddebdc7b9615242894c7a21d5d024 …
> Disable the support for Schema 1 images

- internal/cri/server/container_create.go
- internal/cri/server/container_create_test.go
As `setupSandboxFiles` was done in sandbox controller, it is difficult for CRI server to know if the remote controller did when creating container. If the controller didn't, CRI would add a OCI mount whose hostPath doesn't exist!
To make it safe, CRI createContainer should check if the hostPath exist.
> cri: Stat host sandbox files before adding them

- contrib/nvidia/nvidia.go
- integration/client/container_test.go
Prestart Hook is deprecated and can be replaced with CreateRuntime hook; As we update the runtime-spec version to v1.2.0.
> replace deprecated Prestart to CreateRuntime hook

- core/metrics/cgroups/cgroups.go
- plugins/restart/monitor.go
- plugins/types.go
Adds a plugin type for container monitor. This avoids making the internal plugin type require service plugins since internal plugins should be loaded earlier.
Rename the task monitor type to avoid confusion.
Add config migration for new plugin types to pass existing migration tests.
> Add container monitor plugin type for restart

- core/content/helpers.go
- core/content/helpers_test.go
- core/remotes/docker/pusher.go
While investigating https://github.com/docker/buildx/issues/1726, I found a couple of timing issues when using the docker pusher.
I discovered these issues in a test environment, hopefully should be able to duplicate from: https://gist.github.com/jedevc/ffb16d1319618d116df89e327d3bd589.
Copying the information from the commit messages (see them individually for more details):
- copy: remove wrapping io.NopCloser from push writer pipe (fixes a deadlock)
- copy: check if writer was closed before setting a pipe (fixes a panic)
- copy: improve error detection from closed pipes (fixes edge cases where #7985 doesn't quite work, because reading from the error channel is racy)
- copy: remove max number of ErrResets (should fix https://github.com/docker/buildx/issues/1726, where the original error …
> Fix various timing issues with docker pusher

- RELEASES.md
Since the 2.0 release process has started, there are concerns about how we will generally handle our remaining 1.x releases. Since 1.6 is an LTS release and 1.7 is not, there is valid concern that Go importers will be stuck on an EOL 1.x release while using 1.6 LTS. The maintainers have been aware of this issue and want to have our releases doc reflect our commitment to LTS and generally providing the support needed by all users.
More to come for the 2.0 release in terms of how much support we will provide on Go package stability and compatibility for 2.x libraries talking to 1.x daemons.
Opening this up early in the release cycle to have time for discussion and get majority vote from maintainers.
> Update 1.7 support timeline

- plugins/gc/scheduler.go
On startup `gcTimeSum` might work fast and return `0`, so on this case the algorithm turns in infinity loop which simple consume CPU on timer which fires without any interval.
Closes: https://github.com/containerd/containerd/issues/5089
> Prevent GC from schedule itself with 0 period.

- pkg/transfer/local/import.go
- snapshots/overlay/overlay.go
Fixes #9826 
Backports the following PRs to `release/1.7`:
- https://github.com/containerd/containerd/pull/8945
- https://github.com/containerd/containerd/pull/9028
Unblocks https://github.com/k3s-io/k3s/pull/9319
> [release/1.7] Add WithMetaStore to overlay snapshotter and missing unpacker.Wait for image import

- .github/workflows/ci.yml
- client/snapshotter_opts_unix.go
- plugins/snapshots/overlay/overlay.go
- plugins/snapshots/overlay/overlay_test.go
- plugins/snapshots/overlay/plugin/plugin.go
Issue:
N/A
Description:
This change updates golangci-lint to v1.56.1 which has Go 1.22 support.
Additionally it renames some internal variables and a public facing overlay snapshotter option to resolve revive lint warnings.
Testing:
Lint is successful on all platforms
> Update golangci-lint version to v1.56.1 and resolve warnings

- .github/workflows/ci.yml
It's trying to fix CI issue https://github.com/containerd/containerd/pull/9855
https://github.com/containerd/containerd/actions/runs/8015987871/job/21897145968?pr=9855
> NOTE: Maybe we should maintain a script to download critools, like what we do in linux platform. cc @kiashok
> .github: windows should use fix critool version

- .github/workflows/build-test-images.yml
- .github/workflows/ci.yml
- .github/workflows/codeql.yml
- .github/workflows/images.yml
- .github/workflows/nightly.yml
- .github/workflows/release.yml
- .github/workflows/windows-periodic.yml
N/A
The GitHub Actions CI for branch release/1.6 is showing some deprecation warnings for GitHub Actions packages which are running NodeJS 16.
e.g. a recent release/1.6 PR showed 39 annotated warnings just for CI workflow.
This is a backport for GitHub Actions CI packages to resolve deprecation warnings in release/1.6 branch workflows:
1. https://github.com/containerd/containerd/commit/3ca95282eadaa82cb97d7deabb32f5524c710660
2. https://github.com/containerd/containerd/commit/f6a9c6966572921bd046113442b95e30a7062d5a
3. https://github.com/containerd/containerd/commit/36b12cbcbb2c90812790896c2ab66ecc91a3664b
4. https://github.com/containerd/containerd/commit/9133ad811dd5e3004ab58c9c511d6a385f288e38
5. https://github.com/containerd/containerd/commit/4c1ebe33bd8b548a26fad2f26d196f90879eae8d …
> [release/1.6] Backport GitHub actions package updates

- .github/workflows/build-test-images.yml
- .github/workflows/ci.yml
- .github/workflows/codeql.yml
- .github/workflows/fuzz.yml
- .github/workflows/images.yml
- .github/workflows/nightly.yml
- .github/workflows/release.yml
- .github/workflows/scorecards.yml
- .github/workflows/windows-hyperv-periodic.yml
- .github/workflows/windows-periodic.yml
N/A
The GitHub Actions CI for branch release/1.7 is showing some deprecation warnings for GitHub Actions packages which are running on NodeJS 16.
e.g. a recent release/1.7 PR showed 39 annotated warnings just for CI workflow alone.
This is a backport for GitHub Actions CI packages to resolve deprecation warnings in release/1.7 branch workflows:
1. https://github.com/containerd/containerd/commit/3ca95282eadaa82cb97d7deabb32f5524c710660
2. https://github.com/containerd/containerd/commit/f6a9c6966572921bd046113442b95e30a7062d5a
3. https://github.com/containerd/containerd/commit/36b12cbcbb2c90812790896c2ab66ecc91a3664b
4. https://github.com/containerd/containerd/commit/9133ad811dd5e3004ab58c9c511d6a385f288e38
5. https://github.com/containerd/containerd/commit/4c1ebe33bd8b548a26fad2f26d196f9087 …
> [release/1.7] Backport GitHub actions package updates

- go.mod
- go.sum
- vendor/go.etcd.io/bbolt/bucket.go
- vendor/modules.txt
full diff: https://github.com/etcd-io/bbolt/compare/v1.3.8...v1.3.9
> vendor: go.etcd.io/bbolt v1.3.9

- core/images/mediatypes.go
This PR enables to support zstd compression over docker media types.
Before this change, containerd is unable to pull zstd compressed images and is returning the following error log:
```
ATA[0005] pulling image: failed to pull and unpack image "registry.somewhere.io/image:jb-zstd": failed to extract layer sha256:2be6f9ac9ccbcab5c4ea65a6ff0df74002b910d8a52e9147cf1dbc0a38f01azz: failed to get stream processor for application/vnd.docker.image.rootfs.diff.tar.zstd: no processor for media-type: unknown 
```
> mediatypes: support zstd compression

- integration/build_local_containerd_helper_test.go
- internal/cri/config/config.go
- internal/cri/server/container_create.go
- internal/cri/server/container_stats_list.go
- internal/cri/server/podsandbox/controller.go
- internal/cri/server/podsandbox/controller_test.go
- internal/cri/server/podsandbox/recover.go
- internal/cri/server/podsandbox/recover_test.go
- internal/cri/server/podsandbox/sandbox_run.go
- internal/cri/server/podsandbox/sandbox_status.go
- internal/cri/server/podsandbox/sandbox_stop.go
- internal/cri/server/podsandbox/types/podsandbox.go
- internal/cri/server/podsandbox/types/podsandbox_test.go
- internal/cri/server/restart.go
- internal/cri/server/sandbox_remove.go
- internal/cri/server/sandbox_run.go
- internal/cri/server/sandbox_service.go
- internal/cri/server/sandbox_status.go
- internal/cri/server/sandbox_stop.go
- internal/cri/server/service.go
- internal/cri/server/service_test.go
- internal/cri/store/sandbox/sandbox.go
- plugins/cri/cri.go
To make codes clean, CRI can store a Sandbox client in each sandbox in cache, and call the APIs in the client directly, so that we don't need to find the Controller everytime we need to call APIs of sandbox controller.
> sandbox: use sandboxService in CRI plugin instead of calling controller API directly

- RELEASES.md
As part of the package cleanup for 2.0, we can now consider making our Go client API stable. Add an explicit statement about this to RELEASES.md and which packages are considered stable. The packages which are not intended for clients to import are called out as well. 
Close #3554
> Add Go client stability in RELEASES.md for 2.0

- core/images/archive/exporter.go
While digging into [buildkit issue #4595](https://github.com/moby/buildkit/issues/4595), we noticed that this would also be appropriate to add into containerd to better match spec.
> adds mediatype to oci index record

- .github/workflows/ci.yml
- .golangci.yml
- content/helpers_test.go
- integration/remote/util/util_windows.go
- metadata/containers_test.go
- metadata/images_test.go
- pkg/cri/sbserver/image_pull.go
- pkg/cri/server/image_pull.go
- remotes/docker/config/hosts.go
- script/setup/install-dev-tools
- tracing/plugin/otlp.go
- tracing/plugin/otlp_test.go
update golangci-ilnt to v1.56.1
Not a clean cherry-pick of:
(cherry picked from commit 6e2c915a441f32eb82f2af5743626470eab96753)
(cherry picked from commit 9fc407d8cf534d1b2c25698cd790e85a9935109c)
(cherry picked from commit 6a759713ad8cc88a802727280d17fe5a5b798966)
Changes in commit 926ceb036223d8ac05cd918c7a4c0825bb9c0640 will be no longer required once we move completely to go version > 1.22.0
> [release/1.7] Update golangci-lint to v1.56.1

- pkg/cri/sbserver/image_pull.go
- pkg/cri/sbserver/metrics.go
- pkg/cri/server/image_pull.go
- pkg/cri/server/metrics.go
/kind bug
Cherry-pick of https://github.com/containerd/containerd/pull/8337 into `release/1.7` branch.
> [release/1.7] Register imagePullThroughput and count with MiB

- cmd/containerd-shim-runc-v2/task/service.go
fixes https://github.com/containerd/containerd/issues/9719
alternative to https://github.com/containerd/containerd/pull/9775 without extra locks/goroutines/etc (ty for the idea @corhere!).
-----------------------
TLDR: https://github.com/containerd/containerd/issues/9719
Long form: Communication is hard. In https://github.com/containerd/containerd/commit/5cd6210ad055ec3a0fc263fdde382191c52c40ce, we reworked the v2 runc shim event handling to reduce lock contention, since before, in order to preserve exit event order, we were just putting big locks around `s.Create` and `s.processExits`, which broke down under load (see https://github.com/containerd/containerd/issues/8557).
In reality, the difficult part of preserving exit event order is "early exits" – we never want a `TaskExit` event to …
> runc-shim: process exec exits before init (w/o extra locks!)

- content/helpers.go
- content/helpers_test.go
- remotes/docker/pusher.go
Backport of #8379, cc @dmcgowan.
It would be nice to be able to grab this update downstream for buildkit/buildx, see https://github.com/docker/buildx/issues/2232#issuecomment-1973377335.
> [release/1.7] Backport fix various timing issues with docker pusher

- client/client.go
- cmd/containerd/server/server.go
- core/content/proxy/content_reader.go
- core/content/proxy/content_store.go
- core/content/proxy/content_writer.go
- core/events/proxy/remote_events.go
Some services may be proxied to ttrpc clients. As part of our client stabilization, we should remove grpc types from interfaces where we can to prevent having to add new interfaces just for ttrpc later. Follow on PRs to handle other proxy interfaces but first want to get in initial idea for approach and see what issues there are.
Note: In cases where we want to support both ttrpc and grpc clients, it makes senes to wrap the grpc in the ttrpc client since the ttrpc client is the smaller interface and compatible with the grpc interface.
> Add ttrpc to proxy interfaces

- .github/actions/install-go/action.yml
- .github/workflows/build-test-images.yml
- .github/workflows/ci.yml
- .github/workflows/codeql.yml
- .github/workflows/fuzz.yml
- .github/workflows/images.yml
- .github/workflows/nightly.yml
- .github/workflows/release.yml
- BUILDING.md
- Vagrantfile
- contrib/Dockerfile.test
- contrib/apparmor/apparmor.go
- contrib/fuzz/oss_fuzz_build.sh
- contrib/seccomp/seccomp.go
- go.mod
- go.sum
- integration/client/go.mod
- script/setup/prepare_env_windows.ps1
- go1.21.6 (released 2024-01-09) includes fixes to the compiler, the runtime, and the crypto/tls, maps, and runtime/pprof packages. See the Go 1.21.6 milestone on our issue tracker for details. https://github.com/golang/go/issues?q=milestone%3AGo1.21.6+label%3ACherryPickApproved
- go1.22.0 (released 2024-02-06) Go 1.22.0 is a major release of Go. Read the Go 1.22 Release Notes for more information. https://go.dev/doc/go1.22
Cherry picks :
- #9786 (not a clean cherry pick)
- #9794
- #8957 (not a clean cherry pick)
- #9288
- The PR has lot of cherry pick commits because all the related commits to build / test and run the CI on go1.21.0 are currently dependent on the changes in the other cherry-picks. The only PR that could be cherry-picked independently was #9786, but that would again …
> [release/1.7] update to go 1.21.6, test 1.22.0

- runtime/v2/runc/task/service.go
Backport https://github.com/containerd/containerd/pull/9828.
-----------------------------
https://github.com/containerd/containerd/commit/5cd6210ad055ec3a0fc263fdde382191c52c40ce was also backported to 1.7, hence we should backport the fix to https://github.com/containerd/containerd/issues/9719.
> [release/1.7] runc-shim: process exec exits before init

- runtime/v2/runc/task/service.go
Backport https://github.com/containerd/containerd/pull/9828.
-----------------------------
https://github.com/containerd/containerd/commit/5cd6210ad055ec3a0fc263fdde382191c52c40ce was also backported to 1.6, hence we should backport the fix to https://github.com/containerd/containerd/issues/9719.
> [release/1.6] runc-shim: process exec exits before init

- pkg/sys/oom_linux_test.go
Temporary skip while we find root cause of GHA environment changes causing failure.
> Disable OOM set score unpriv test temporarily

- plugins/snapshots/windows/cimfs.go
- plugins/snapshots/windows/common.go
- plugins/snapshots/windows/windows.go
CimFS layers don't need to create a new scratch VHD per image. The scratch VHDs used with CimFS are empty so we can just create one VHD and copy it for every scratch snapshot. (Note that UVM VHDs are still unique per image because the VHD information is embedded in the UVM BCD during import)
> Don't create new scratch VHD per image for CimFS

- sys/oom_linux_test.go
Temporary skip while we find root cause of GHA environment changes causing failure.
(cherry picked from commit 723306d0ed80ce2ca01f8782daa673ca3db4645c)
> [release/1.7] Disable OOM set score unpriv test temporarily

- sys/oom_linux_test.go
Temporary skip while we find root cause of GHA environment changes causing failure.
(cherry picked from commit 723306d0ed80ce2ca01f8782daa673ca3db4645c)
> [release/1.6] Disable OOM set score unpriv test temporarily

- .github/actions/install-go/action.yml
- .github/workflows/ci.yml
- Vagrantfile
- contrib/Dockerfile.test
- script/setup/prepare_env_windows.ps1
Similar to:
- https://github.com/containerd/containerd/pull/9932
Carry #9934
> [release/1.6] update to go 1.21.8, 1.22.1

- .github/workflows/ci.yml
The binaries job in CI is not respecting the Go version specified in the matrix.
This change updates the binaries job in CI to use the Go version specified in the matrix.
> Use the Go toolchain in CI matrix to build binaries

- .github/workflows/ci.yml
#9946
(cherry picked from commit 7ac9d6909c6b75fbf345368fee8a4b5764c5df27)
clean cherry-pick of #9946
> [release/1.7] Backport use Go toolchain in CI matrix to build binaries

- releases/v1.6.29.toml
- version/version.go
Notes generated using new highlights feature in the release tools. The `impact/changelog` label on PRs is used and `area/cri` to group the changes.
----
containerd 1.6.29
Welcome to the v1.6.29 release of containerd!
The twenty-ninth patch release for containerd 1.6 contains various fixes and updates.
* Fix config import relative path glob ([#9835](https://github.com/containerd/containerd/pull/9835))
* Move high volume event logs to Trace level ([#9824](https://github.com/containerd/containerd/pull/9824))
* Move certain debug logs to trace logs ([#9762](https://github.com/containerd/containerd/pull/9762))
* Add timeout to drain exec io ([#9768](https://github.com/containerd/containerd/pull/9768))
* Propagate deprecation list to runtime status …
> [release/1.6] Prepare release notes for v1.6.29

- README.md
- RELEASES.md
Updating our kubernetes support table for k8s v1.29, and adding a row for the 1.30 alpha that is expected to roughly coincide with our 2.0 release schedule.
> add k8s 1.29 and 1.30preview to support table

- .github/workflows/release.yml
- releases/v1.6.30.toml
- version/version.go
v1.6.29 had a bug in the release configuration. Since that tag is pushed, we will skip that release and fix it in v1.6.30 tag. Verification that release configuration succeeds https://github.com/dmcgowan/containerd/actions/runs/8208839100. This was my mistake, any change to the release configuration should be tested in fork before pushing upstream.
Keeping 1.6.28 as the previous release for this build.
----
containerd 1.6.30
Welcome to the v1.6.30 release of containerd!
The thirtieth patch release for containerd 1.6 contains various fixes and updates
as well as a build fix which prevented the v1.6.29 tag from being released.
* Update builds to go 1.21.8 ([#9945](https://github.com/containerd/containerd/pull/9945))
* Fix config import relative path glob …
> [release/1.6] Prepare v1.6.30

- go.mod
- go.sum
- vendor/modules.txt
- follow-up to https://github.com/containerd/containerd/pull/9958
commit 10c7f03b3b42dd36a421bca5f436a8da6def83dc updated google.golang.org/protobuf to v1.33.0, which addresses CVE-2024-24786, however a follow-up post on the Golang security list issued a warning that the v1.33.0 update introduced a breaking change, causing compatibility with github.com/golang/protobuf to be broken;
> A small correction: This vulnerability applies when the UnmarshalOptions.DiscardUnknown
> option is set (as well as when unmarshaling into any message which contains a
> google.protobuf.Any). There is no UnmarshalUnknown option.
>
> In addition, version 1.33.0 of google.golang.org/protobuf inadvertently
> introduced an incompatibility with the older github.com/golang/protobuf
> module. …
> vendor: github.com/golang/protobuf v1.5.4

- .github/workflows/release.yml
#9890 backported some CI updates to release/1.6. This included a change to the release workflow which removed the environment variable for the Go version because the workflows were moved to use the install Go composite action. The issue is the environment variable was still needed for the build job in the release workflow. The result was the v1.6.29 (#9950) release could not be completed and a fix had to be rolled forward in v1.6.30 (#9952).
This change will run the release workflow on PR to release/1.6 branch to catch issues from changes to the release workflow.
(cherry picked from commit ffabc8a296691418d07f042d489987b67d0ddde1)
Partial cherry-pick of #7968
Status check failed before #9952 which includes release workflow fix.
> [release/1.6] Backport test release on PR

- plugins/transfer/plugin.go
This allows arm64 to pull armhf images.
Before this change the transfer service would reject pulls for armhf on
an arm64 machine, or indeed any such platform variant mismatches.
I would argue that its a bit weird for the transfer service to reject a
pull at all since there are legitamate reasons to want to pull images
for other architectures, however that's a more philosophical change.
In the case where I ran into this, I have an arm64 machine running
an armhf containerd in an armhf container (for running some basic sanity
checks during packaging).
Tests started failing once `ctr` was moved to use the transfer service
by default.
Fixes #9980
> transfer: Platform matcher should match multiple platforms

- images/archive/exporter.go
Cherry pick for adding the mediatype to oci index record. :)
(cherry picked from commit 17ea3959bc3aa32ac9670983c765c6b28402f618)
> [release/1.6] adds mediatype to oci index record

- images/archive/exporter.go
Cherry pick for adding the mediatype to oci index record. :)
(cherry picked from commit 17ea3959bc3aa32ac9670983c765c6b28402f618)
> [release/1.7] adds mediatype to oci index record

- internal/cri/server/sandbox_portforward_windows.go
Remove dependance on wincat.exe for port forwarding on windows
> Change port forwarding on windows

- cmd/ctr/app/main.go
Set `DisableSliceFlagSeparator = true`
urfave/cli/v2 uses ',' as default string slice separator. That means '--mount type=bind,src=/src,des=/des,options=rbind:rw' will be token as four bind mount options.
Fixes: #10003
reference:
https://github.com/urfave/cli/pull/1582
DisableSliceFlagSeparator is a global setting.
Before updating urfave/cli to v2,  ctr doesn't support to take `--<option>  foo1=bar1,foo2=bar2` as `--<option> foo1=bar1 --<option>  foo2=bar2`.
So I think set `DisableSliceFlagSeparator = true` is compatible with before
> ctr: fix parsing mount options

- go.mod
- go.sum
Resolves #9969
The module github.com/mitchellh/osext is no longer available via source. The issue is it is currently a indirect dependency via containerd/aufs@v1.0.0 (see https://github.com/containerd/aufs/issues/49#issuecomment-2024098076) and Microsoft/hcsshim@v0.9.10.
This change excludes the github.com/mitchellh/osext indirect dependency to resolve compile from source use case issue due to dependency no longer being available.
```
go clean -modcache
export GOPROXY=direct
go mod tidy
go mod vendor
```
* Go mod exclude directive - https://go.dev/doc/modules/gomod-ref#exclude
> [release/1.7] Fix compile from version control system (source) use case

- internal/cri/server/sandbox_stats_list.go
Should hopefully fix #10013. It seems we can end up in a spot where the sandbox store still has a listing for a pod, whereas containerds underlying store has removed it. It might be better to shield the caller (k8s) from these transient errors.
> Add IsNotFound case to ListPodSandboxStats

- go.mod
- go.sum
Resolves #9969
The module github.com/mitchellh/osext is no longer available via source. The issue is it is currently a indirect dependency via containerd/aufs@v1.0.0 (see https://github.com/containerd/aufs/issues/49#issuecomment-2024098076) and Microsoft/hcsshim@v0.9.10.
This change excludes the github.com/mitchellh/osext indirect dependency to resolve compile from source use case issue due to dependency no longer being available.
```
go clean -modcache
export GOPROXY=direct
go mod tidy
go mod vendor
```
* Go mod exclude directive - https://go.dev/doc/modules/gomod-ref#exclude
> [release/1.6] Fix compile from version control system (source) use case

- internal/cri/opts/spec_darwin_opts.go
- internal/cri/opts/spec_linux_opts.go
- internal/cri/opts/spec_windows_opts.go
Since the commit of https://github.com/golang/go/commit/72e77a7f41bbf45d466119444307fd3ae996e257 in Golang 1.19, the order of mounts is unexpected. In some situations, this leads to unexpected results.
This PR changes `sort.Sort()` to `sort.Stable()` to keep the order of mounts stable after sorting.
Fix https://github.com/containerd/containerd/issues/9978
> fix(cri): fix unexpected order of mounts since go 1.19

- runtime/v2/runc/task/service.go
backports https://github.com/containerd/containerd/pull/9999
(cherry picked from commit 6d00c3ada8b094aa3a2aa73a396cd2243de3f59f)
> [release/1.7] Fix runc shim to only defer init process exits

- runtime/v2/runc/task/service.go
Backports https://github.com/containerd/containerd/pull/9999
(cherry picked from commit 6d00c3ada8b094aa3a2aa73a396cd2243de3f59f)
> [release/1.6] Fix runc shim to only defer init process exits

- releases/v1.6.31.toml
- version/version.go
Notes need to be re-generated after #10038 merges; Fixes #10036 for `release/1.6`
> [release/1.6] Prepare for v1.6.31 release

- releases/v1.7.15.toml
- version/version.go
Notes need to be recreated once #10037 merges. Fixes #10036 for `release/1.7`
> [release/1.7] Prepare for v1.7.15 release

- docs/tracing.md
Add a **Manual instrumentation** section in `docs/tracing.md` and added details about how to use the tracing APIs to manual instrument spans in containerd.
Also added a section to list the naming conventions to follow.
> Update tracing documentation to add details about manual instrumentation

- pkg/cri/server/sandbox_stats_list.go
Fixes #10013. It seems we can end up in a spot where the sandbox store still has a listing for a pod, whereas containerds underlying store has removed it. It might be better to shield the caller (k8s) from these transient errors.
(cherry picked from commit 2474a99c3084aa2c2239a827130c1972bf7724c5)
> [release/1.7] Add IsNotFound case to ListPodSandboxStats

- core/remotes/docker/pusher_test.go
- core/remotes/docker/resolver.go
The pusher supports fallback from HTTPS to HTTP using `HTTPFallback`. But the current implementation of `HTTPFallback` doesn't reset the request body on fallback so the body is used twice.  When the pusher uploads the manifest using `HTTPFallback`, it results in `io: read/write on closed pipe` error because the request body is a `*io.PipeReader` that can't be used twice. This commit fixes this issue by modifying `HTTPFallback` to reset the request body on fallback, using `http.Request.GetBody()`.
Reusing the request body didn't happen when uploading the layer because the pusher correctly selects the scheme based on Location header and avoids fallback. This commit also fixes the test to cover the code path of uploading the manifest with fallback.
- The same error is observed also in …
> remote: Fix HTTPFallback fails when pushing manifest

- pkg/cri/opts/spec_linux.go
- pkg/cri/opts/spec_windows.go
> [release/1.6] fix(cri): fix unexpected order of mounts since go 1.19

- remotes/docker/pusher_test.go
- remotes/docker/resolver.go
Backporting  #10031
The pusher supports fallback from HTTPS to HTTP using `HTTPFallback`. But the current implementation of `HTTPFallback` doesn't reset the request body on fallback so the body is used twice.  When the pusher uploads the manifest using `HTTPFallback`, it results in `io: read/write on closed pipe` error because the request body is a `*io.PipeReader` that can't be used twice. This commit fixes this issue by modifying `HTTPFallback` to reset the request body on fallback, using `http.Request.GetBody()`.
Reusing the request body didn't happen when uploading the layer because the pusher correctly selects the scheme based on Location header and avoids fallback. This commit also fixes the test to cover the code path of uploading the manifest with fallback.
- The same error is …
> [release/1.7] remote: Fix HTTPFallback fails when pushing manifest

- integration/client/client.go
- integration/client/client_unix.go
- integration/client/client_windows.go
- integration/client/client_windows_test.go
If the containerd/containerd/defaults.DefaultAddress is used , it causes failures if containerd is already running on the default address and the tests are run without the 'no-daemon' flag. 
It would be good to use a different containerd sock address for integration tests
> Use different containerd sock address for integration test client

- internal/cri/annotations/annotations.go
- internal/cri/server/podsandbox/sandbox_run.go
- internal/cri/server/podsandbox/sandbox_run_linux.go
- internal/cri/server/podsandbox/sandbox_run_other.go
- internal/cri/server/podsandbox/sandbox_run_windows.go
We are working on a feature to enable the guest image pulling on the confidential-containers, and we would greatly appreciate containerd’s assistance in this matter. we hope containerd could share the pause image name and add it to the annotations so that we can pass it to the guest.
Fixes: #9418
> cri: add sandbox image name to annotations

- core/diff/apply/apply_linux.go
Use the Syncfs wrapper function defined in the golang.org/x/sys/unix package instead of manually wrapping it in doSyncFs.
> core/diff/apply: use unix.Syncfs

- core/mount/mount_idmapped_linux.go
This also replaces the PPidFD constant with the definition in x/sys/unix
> Replace direct waitid syscall with unix.Waitid

- integration/client/client.go
- integration/client/client_windows.go
- integration/client/client_windows_test.go
(cherry picked from commit 5b6ae0f796f3d6e3e499d37785e93e167aef0fe1)
P.S: This is a direct cherry-pick without any additional change.
> [release/1.7] Use different containerd sock address in tests

- core/metrics/cgroups/v1/oom.go
- core/mount/mount_idmapped_linux.go
- pkg/archive/link_freebsd.go
- pkg/oom/v1/v1.go
- pkg/sys/eintr_unix.go
We have quite a few pieces of code laying around containerd that all loop and ignore eintr as they make syscalls directly
(or use a unix/syscall wrapper) because there's no stdlib equivalent. This adds a small utility to pkg/sys that we can use for all of these spots, and then uses it to actually replace them
> pkg/sys: Add helper to ignore eintr

- pkg/cri/opts/spec_darwin_opts.go
- pkg/cri/opts/spec_linux_opts.go
- pkg/cri/opts/spec_windows_opts.go
backport #10021 
cc @estesp @mxpv
> [release/1.7] fix(cri): fix unexpected order of mounts since go 1.19

- internal/cri/server/container_create.go
Per https://github.com/kubernetes/enhancements/tree/master/keps/sig-windows/1981-windows-privileged-container-support#container-mounts
the default working directory for `hostProcess` containers should be `C:\hpc`,
however the current default is set to windows default which is `C:\`.
> fix default working directory `hostProcess`

- pkg/cri/sbserver/container_create.go
Per https://github.com/kubernetes/enhancements/tree/master/keps/sig-windows/1981-windows-privileged-container-support#container-mounts the default working directory for `hostProcess` containers should be `C:\hpc`, however the current default is set to windows default which is `C:\`.
Signed-off-by: Maksim An <maksiman@microsoft.com>
(cherry picked from commit c7ea06a69bdf9147758353b4eb12bb78240fbda8)
> [release/1.7] backport: fix default working directory `hostProcess`

- gc/scheduler/scheduler.go
On startup `gcTimeSum` might work fast and return `0`, so on this case the algorithm turns in infinity loop which simple consume CPU on timer which fires without any interval.
Use `5ms` as fallback to have interval `245ms` for that case.
Backport of https://github.com/containerd/containerd/pull/9795 into 1.6 branch
Closes: https://github.com/containerd/containerd/issues/5089
> [release/1.6] Prevent GC from schedule itself with 0 period.

- gc/scheduler/scheduler.go
On startup `gcTimeSum` might work fast and return `0`, so on this case the algorithm turns in infinity loop which simple consume CPU on timer which fires without any interval.
Use `5ms` as fallback to have interval `245ms` for that case.
Backport of https://github.com/containerd/containerd/pull/9795 into 1.7 branch
Closes: https://github.com/containerd/containerd/issues/5089
> [release/1.7] Prevent GC from schedule itself with 0 period.

- .github/actions/install-go/action.yml
- .github/workflows/ci.yml
- .github/workflows/release.yml
- Vagrantfile
- contrib/Dockerfile.test
- contrib/fuzz/oss_fuzz_build.sh
- script/setup/prepare_env_windows.ps1
go1.21.9 (released 2024-04-03) includes a security fix to the net/http package, as well as bug fixes to the linker, and the go/types and net/http packages. See the Go 1.21.9 milestone for more details; https://github.com/golang/go/issues?q=milestone%3AGo1.21.9+label%3ACherryPickApproved
- http2: close connections when receiving too many headers
Maintaining HPACK state requires that we parse and process all HEADERS and CONTINUATION frames on a connection. When a request's headers exceed MaxHeaderBytes, we don't allocate memory to store the excess headers but we do parse them. This permits an attacker to cause an HTTP/2 endpoint to read arbitrary amounts of header data, all associated with a request which is going …
> update to go1.21.9, go1.22.2

- pkg/cri/sbserver/sandbox_portforward_windows.go
- pkg/cri/server/sandbox_portforward_windows.go
This PR is a partial change from commit [b97ef91fb7212f512487fc1e28106050ad2f5766](https://github.com/containerd/containerd/commit/b97ef91fb7212f512487fc1e28106050ad2f5766)
This change only adds support for port forwarding on Windows host process containers by establishing connection to localhost at the requested port since HPCs share the network namespace of the host. 
This PR does not change any existing behavior for process isolated or hyperV containers since we'd like to limit changes on a release branch.
> [release/1.7] Add support for HPC port forwarding

- cmd/ctr/commands/resolver.go
- core/remotes/docker/config/hosts.go
- core/remotes/docker/config/hosts_test.go
- core/remotes/docker/pusher_test.go
- core/remotes/docker/resolver.go
- core/remotes/docker/resolver_test.go
A few relevant changes here to make the HTTP fallback more robust:
- Handle TLS handshake timeout, as some HTTP servers may just not return anything to the TLS handshake attempt
- If a previous fallback has already occurred with the same host using the same transport, immediately fallback to HTTP and do not copy the body
- Avoid returning an empty TLS configuration when no TLS has been configured in ctr, this avoids a TLS configuration always set and forcing fallback when using ctr
Fixes #10014
> Update HTTP fallback to better account for TLS timeout and previous attempts

- contrib/apparmor/template.go
Fix:
- containerd/nerdctl#2730
Caused by:
> kernel: audit: type=1400 audit(1713840662.766:122): apparmor="DENIED" operation="signal" class="signal"
> profile="nerdctl-default" pid=366783 comm="runc" requested_mask="receive" denied_mask="receive" signal=kill
> peer="/usr/local/bin/rootlesskit"
The issue is known to happen on Ubuntu 23.10 and 24.04 LTS. Doesn't seem to happen on Ubuntu 22.04 LTS.
> apparmor: add `signal (receive) peer=/usr/local/bin/rootlesskit,`

- .github/actions/install-go/action.yml
- .github/workflows/ci.yml
- .github/workflows/release.yml
- Vagrantfile
- contrib/Dockerfile.test
- contrib/fuzz/oss_fuzz_build.sh
- script/setup/prepare_env_windows.ps1
- backport https://github.com/containerd/containerd/pull/10104
go1.21.9 (released 2024-04-03) includes a security fix to the net/http package, as well as bug fixes to the linker, and the go/types and net/http packages. See the Go 1.21.9 milestone for more details; https://github.com/golang/go/issues?q=milestone%3AGo1.21.9+label%3ACherryPickApproved
- http2: close connections when receiving too many headers
Maintaining HPACK state requires that we parse and process all HEADERS and CONTINUATION frames on a connection. When a request's headers exceed MaxHeaderBytes, we don't allocate memory to store the excess headers but we do parse them. This permits an attacker to cause an HTTP/2 endpoint to read arbitrary …
> [release/1.7 backport] update to go1.21.9, go1.22.2

- contrib/apparmor/template.go
> [release/1.7] apparmor: add `signal (receive) peer=/usr/local/bin/rootlesskit,`

- .github/actions/install-go/action.yml
- .github/workflows/ci.yml
- .github/workflows/release.yml
- Vagrantfile
- contrib/Dockerfile.test
- script/setup/prepare_env_windows.ps1
- backport https://github.com/containerd/containerd/pull/10104
go1.21.9 (released 2024-04-03) includes a security fix to the net/http package, as well as bug fixes to the linker, and the go/types and net/http packages. See the Go 1.21.9 milestone for more details; https://github.com/golang/go/issues?q=milestone%3AGo1.21.9+label%3ACherryPickApproved
- http2: close connections when receiving too many headers
Maintaining HPACK state requires that we parse and process all HEADERS and CONTINUATION frames on a connection. When a request's headers exceed MaxHeaderBytes, we don't allocate memory to store the excess headers but we do parse them. This permits an attacker to cause an HTTP/2 endpoint to read arbitrary …
> [release/1.6 backport] update to go1.21.9, go1.22.2

- pkg/cri/sbserver/sandbox_run.go
- pkg/cri/server/sandbox_run.go
Cherry-pick
- #9673 
There was no merge conflict, but the commit was amended to cover sbserver.
> [release/1.7] pod: CreatedAt time will be 269 years ago while creating cri network failed.

- pkg/cri/cri.go
- pkg/cri/server/service.go
- plugin/plugin.go
- services/server/config/config.go
- services/server/server.go
- snapshots/blockfile/plugin/plugin.go
- snapshots/btrfs/plugin/plugin.go
- snapshots/devmapper/plugin/plugin.go
- snapshots/native/plugin/plugin.go
- snapshots/overlay/plugin/plugin.go
Fixes #10095 in 1.7
This PR backports 4 changes:
1) https://github.com/containerd/containerd/pull/8417 - Allows proxy plugins to have platforms (not strictly necessary to fix the issue, but I thought it would be less weird to keep this than to take a newer change to ProxyPlugins without the older one)
2) https://github.com/containerd/containerd/pull/9253 - Allows proxy plugins to have exports (e.g. root)
3) https://github.com/containerd/containerd/pull/10073 - Exports root paths for a number of snapshotters that didn't already have them
4) https://github.com/containerd/containerd/pull/9216 - Uses exported `root` key for snapshotter root if present.
The result of this is that you can tell containerd about a remote snapshotter's root like:
```
[proxy_plugins.soci]
type = "snapshot"
address …
```
> [release/1.7] Fix CRI snapshotter root path when not under containerd root

- plugins/cri/images/plugin.go
- plugins/cri/images/plugin_test.go
Adjust code sequence in `migrateConfig` to migrate `pinned_images` and `registry` first even when `containerd` does not exist.
Fix: #10120
> fix migrateConfig for io.containerd.cri.v1.images

- version/version.go
----
Welcome to the v2.0.0-rc.r1 release of containerd!  
* Enable Transfer service to use registry configuration directory ([#9908](https://github.com/containerd/containerd/pull/9908))
* Configure otel from env instead of config.toml …
> Prepare release notes for v2.0.0-rc.1

- docs/getting-started.md
This commit fixes the duplicate copy and configure steps for the Windows powershell scripts.
fixes #9887
It also adds the architecture as a variable in preparation for the ARM64 support that is coming.
> fix(docs): fix duplicate instructions for windows installation

- contrib/apparmor/template.go
/usr/sbin/runc is confined with "runc" profile[1] introduced in AppArmor v4.0.0. This change breaks stopping of containers, because the profile assigned to containers doesn't accept signals from the "runc" peer. AppArmor >= v4.0.0 is currently part of Ubuntu Mantic (23.10) and later.
The issue is reproducible both with nerdctl and ctr clients. In the case of ctr, the --apparmor-default-profile flag has to be specified, otherwise the container processes would inherit the runc profile, which behaves as unconfined, and so the subsequent runc process invoked to stop it would be able to signal it.
Test commands:
root@cloudimg:~# nerdctl run -d --name foo nginx:latest
3d1e74bfe6e7b2912d9223050ae8a81a8f4b73de0846e6d9c956c1e411cdd95a
root@cloudimg:~# nerdctl stop foo
FATA[0000] 1 errors:
unknown …
> apparmor: Allow confined runc to kill containers

- releases/v1.7.16.toml
- version/version.go
Welcome to the v1.7.16 release of containerd!
* Wei Fu
* Danny Canter
* Kazuyoshi Kato
* Phil Estes
* Samuel Karp
* Brian Goff
* Rodrigo Campos
* Akihiro Suda
* Bin Tang
* David Porter
* Edgar Lee
* Evan Lezar
* Kirill A. Korinsky
* Kohei Tokunaga
* Maksim An
* Paweł Gronowski
* 张钰10307750
* 沈陵
<details><summary>44 commits</summary>
<p>
* Fix CRI snapshotter root path when not under containerd root ([#10096](https://github.com/containerd/containerd/pull/10096))
* [`a8ebceb97`](https://github.com/containerd/containerd/commit/a8ebceb972efdc5ead7535640f531972a95280cb) CRI: "Fix" imageFSPath behavior
* …
> Add release notes for v1.7.16

- ADOPTERS.md
Adds Syself Autopilot to adopters. Syself Autopilot is a managed kubernetes solution that uses containerd as the default CRI runtime. Added at the end since it's a commercial adopter.
> Add Syself Autopilot to adopters

- plugins/cri/runtime/plugin.go
- extracting first 2 (non controversial?) commits from https://github.com/containerd/containerd/pull/9489
Log the config as a field instead of as part of the log message.
Before this:
INFO[2023-12-07T14:58:43.515360429Z] loading plugin                                id=io.containerd.tracing.processor.v1.otlp type=io.containerd.tracing.processor.v1
INFO[2023-12-07T14:58:43.515787512Z] loading plugin                                id=io.containerd.internal.v1.tracing type=io.containerd.internal.v1
INFO[2023-12-07T14:58:43.515974429Z] loading plugin                                id=io.containerd.internal.v1.cri type=io.containerd.internal.v1
INFO[2023-12-07T14:58:43.516037887Z] Start cri plugin with config {PluginConfig:{ContainerdConfig:{Snapshotter:overlayfs DefaultRuntimeName:runc …
> pkg/cri/server/base: use structured log for CRI plugin startup and log config as embedded JSON

- .github/actions/install-go/action.yml
- .github/workflows/release.yml
- BUILDING.md
- Vagrantfile
- contrib/Dockerfile.test
- contrib/fuzz/oss_fuzz_build.sh
- go.mod
- script/setup/install-runc
- script/setup/prepare_env_windows.ps1
Depended by k8s.io/cri-api >= v0.30.0 (Kubernetes v1.30)
https://github.com/kubernetes/cri-api/blob/v0.30.0/go.mod#L5
- #10019
- #10108
> go.mod: go 1.22

- docs/snapshotters/README.md
- docs/snapshotters/blockfile.md
Based on [this Slack discussion thread](https://cloud-native.slack.com/archives/C4RJZ9Z6Y/p1714059264248929), I captured how to use the block file snapshotted, what its use case is, and how it works.
I am fairly certain that there are errors in here, but if we can capture this here and correct it, it will be known for future users and contributors, and might save people from having to answer the same questions over again on Slack 😄 
Input to this is based on insights from @fuweid @samuelkarp @dcantah 
There are 2 or 3 `TODO` comments here, where I either had open questions or was missing something. Help appreciate there.
> document usage and design of blockfile snapshotter

- docs/man/containerd-config.toml.5.md
Correct the typo in the documentation from `configuraton ` to `configuration `
> docs: correct the typo in the documentation

- core/content/content.go
- core/metadata/content.go
- plugins/content/local/writer.go
This PR mitigates a lock contention where `PullImage` [holds](https://github.com/containerd/containerd/blob/c4c3c6ea568ce0cfbcf754863abadeea37d77c8f/core/metadata/content.go#L577) the metadata lock while [flushing](https://github.com/containerd/containerd/blob/c4c3c6ea568ce0cfbcf754863abadeea37d77c8f/plugins/content/local/writer.go#L95) in-flight writes to the disk.  This can block concurrent `CreateContainer` and `PullImage` calls for an extended period of time.
> Perform file sync outside of lock on Commit

- client/container.go
- client/container_restore_opts.go
instead of a locally defined const
> container.Checkpoint(), WithRestoreImage(): use ocispec.AnnotationRefName

- core/content/helpers.go
A downstream library (related to uploading cache blobs in s3) needs a read seeker to be able to do its own multipart upload. 
This flattens the memory usage a lot in our case.
See: https://github.com/moby/buildkit/pull/4551
Feels like this could be an ok addition here, totally understand if you don't want it, or if you want it differently ( happy to update though ! ).
Edit: Here are some logs of a buildkit build with GC logs on:
Before(same image):
```
#31 preparing build cache for export
gc 75 @150.145s 0%: 0.018+1.0+0.004 ms clock, 0.29+0.14/3.9/5.5+0.071 ms cpu, 8344->8344->8344 MB, 8344 MB goal, 0 MB stacks, 0 MB globals, 16 P
gc 76 @150.188s 0%: 0.029+0.99+0.004 ms clock, 0.46+0.26/3.5/7.4+0.065 ms cpu, 8344->8344->8344 MB, 8344 MB goal, 0 MB stacks, 0 MB globals, 16 P
gc 77 …
```
> content: add a BlobReadSeeker to allow multipart blob uploads

- core/transfer/local/pull.go
- core/transfer/local/transfer.go
- plugins/transfer/plugin.go
Reduce the interface for local transfer service to match pattern of all optional arguments as opts or in config object.
> Cleanup local transfer interface

- services/server/config/config.go
Once 2.0 is released, the config version is bumped to 3 which is backwards incompatible with version 2. While we do not need to handle version 3 in 1.6 and 1.7 release, we should error out if the config version is higher than the max supported version. This will provide a clear error when an unsupported config version is used rather have containerd subtly error or use an unexpected configuration.
> [release/1.7] Handle unsupported config versions

- cmd/containerd-shim-runc-v2/process/init.go
- cmd/containerd-shim-runc-v2/process/utils.go
- core/runtime/v2/task_manager.go
This commit gets rid of the TODO by moving the check to use the pluginInfo() infrastructure (#9442).
The check is only enforced for shims that return info that can be read as type runtime.Features. For shims that don't provide that, we just ignore it, as those shims might not be affected by this.
NOTE: Since Kubernetes 1.30, the kubelet checks that the container runtime supports all the features for user namespaces (iow, it checks idmap mounts support too) and, if the runtime doesn't support them, it just rejects the pod creation without sending it to the runtime. That makes it less of an issue, as this PR is not really needed now for kubernetes >= 1.30 workloads. However, it is the right thing to do (we shouldn't rely on k8s doing it, we should check it here too), and it is still …
> core/runtime: Check shim PluginInfo to enforce idmap support

- client/transfer.go
- core/streaming/proxy/streaming.go
- core/transfer/proxy/transfer.go
Use the same proxy pattern to support ttrpc and grpc clients.
Relevant for #9965
> Add support for ttrpc in transfer and streaming service

- cmd/ctr/commands/shim/shim.go
Fix `ctr shim` command.
The shim command is broken due to task API version upgrade.
* Before change
```
$ sudo bin/ctr shim --id test state
ctr: rpc error: code = Unimplemented desc = service containerd.task.v2.Task
```
* After change
```
$ sudo bin/ctr shim --id test state
{
"id": "test",
"bundle": "/run/containerd/io.containerd.runtime.v2.task/default/test",
"pid": 285466,
"status": 2,
"stdin": "/run/containerd/fifo/3865965001/test-stdin",
"stdout": "/run/containerd/fifo/3865965001/test-stdout",
"terminal": true,
"exited_at": {
"seconds": -62135596800
}
}
```
> Update ctr shim subcommand to task v3

- Makefile
- go.mod
- go.sum
- releases/README.md
- vendor/github.com/containerd/containerd/api/LICENSE
- vendor/modules.txt
Updates containerd API from v0.0.0 to tagged version
Also...
- Adds new `make clean-vendor` command in Makefile to remove any replace statement for the API
- Updates `make protos` to add replace line to go module if it results in changes to the api
- Updates release procedure to mention removal of replace statement
We should be able to keep the replace line as temporary and added only when there are updates. Hopefully adding to make file will make it easier to manage.
> Update containerd api to v1.8.0-rc.0

- internal/cri/server/container_checkpoint_linux.go
For the first version of containerd's "Forensic Container Checkpointing" support the error message if the CRIU binary is not found was deliberately wrong to not break Kubernetes e2e_node tests.
Now that the e2e_node tests have been adapted, containerd can return the correct error message.
Depends on https://github.com/kubernetes/kubernetes/pull/123886
> Return correct error if CRIU binary is missing

- .github/workflows/ci.yml
since go.mod got updated to go1.22, 1.22 is the minimum version to build containerd. even if 1.21.9 is the version present on the host, go command will build using 1.22.0 go version.
Ref: https://github.com/akhilerm/containerd/actions/runs/8967614368/job/24625463053#step:4:16, even though 1.21.9 was installed, the final binary was built using 1.22.0 (version from go.mod)
> remove go1.21.9 from CI matrix

- client/sandbox.go
The PID of sandbox client is not used by anywhere, and I think for some kind of sandbox, it may not have a pid. so I removed PID method in this PR, and for sandboxed Task we can get the connection of Task API directly from the endpoint of the sandbox, so I add a Endpoint call there. And so the Metadata method, which is required to get all information of the sandbox.
Needs to rebase after #9736
> sandbox: modify sandbox client

- pkg/dialer/dialer_unix.go
- pkg/shim/util_unix.go
This just replaces some type casts to check whether a few dial errors are a specific syscall with the stdlibs errors.As/errors.Is pals.
> Chore: Simplify some syscall error checks

- pkg/cri/cri.go
- pkg/cri/server/service.go
- plugin/plugin.go
- services/server/config/config.go
- services/server/server.go
- snapshots/btrfs/plugin/plugin.go
- snapshots/devmapper/plugin/plugin.go
- snapshots/native/plugin/plugin.go
- snapshots/overlay/plugin/plugin.go
Fixes https://github.com/containerd/containerd/issues/10095 in 1.6
Related to the release/1.7 backport #10096
This PR backports 4 changes:
1. https://github.com/containerd/containerd/pull/8417 - Allows proxy plugins to have platforms (not strictly necessary to fix the issue, but I thought it would be less weird to keep this than to take a newer change to ProxyPlugins without the older one)
2. https://github.com/containerd/containerd/pull/9253 - Allows proxy plugins to have exports (e.g. root)
3. https://github.com/containerd/containerd/pull/10073 - Exports root paths for a number of snapshotters that didn't already have them
4. https://github.com/containerd/containerd/pull/9216 - Uses exported root key for snapshotter root if present.
The result of this is that you can tell containerd …
> [release/1.6] Fix CRI snapshotter root path when not under containerd root

- core/transfer/streaming/reader.go
- internal/cri/config/config.go
- internal/cri/io/container_io.go
- internal/cri/io/exec_io.go
- internal/cri/io/helpers.go
- internal/cri/server/container_create.go
- internal/cri/server/container_execsync.go
- pkg/cio/io.go
currently, CRI plugin only support container io by named pipes. but in some scenario named pipes may not work for some kind of sandboxes, for example, for VM based sandboxes, It is not easy to hotplug the named pipe into the vm. So for those kind of runtimes, they have to transfer io in some other way.
But if containerd support io streams by the streaming api, the shim process or the sandbox can serve the Streaming API of containerd, and containerd can create streams for the container stdios.
needs rebase after #9736
> cri: support io by streaming API

- .github/workflows/ci.yml
- .golangci.yml
golangci-lint v1.58.0: https://github.com/golangci/golangci-lint/releases/tag/v1.58.0
This also fixes the following warnings:
```
WARN [config_reader] The configuration option `run.skip-dirs` is deprecated, please use `issues.exclude-dirs`.
WARN [lintersdb] The name "vet" is deprecated. The linter has been renamed to: govet.
```
> CI: bump up golangci-lint to v1.58.0

- integration/main_test.go
- integration/remote/remote_image.go
- integration/remote/remote_runtime.go
- integration/remote/util/util_unix.go
- integration/remote/util/util_windows.go
Fun times: In grpc 1.63 `grpc.Dial` and a few of the options we use (`grpc.WithBlock`) are deprecated in favor of the no-IO variant `grpc.NewClient`. The uses in the integration tests should be easy to swap however as they don't use `grpc.WithBlock` anyways, so that's what this change aims to do. This also removes some `context.WithTimeout`'s as I don't see anywhere the context is actually used in `grpc.Dial` if you don't also specify `grpc.WithBlock` (and it's especially not used now with `grpc.NewClient` as it doesn't even take in a context).
> Integration: Change to grpc.NewClient

- .github/workflows/ci.yml
We have a few jobs on CI that are quite flaky lately (examples [1](https://github.com/containerd/containerd/pull/10075), [2](https://github.com/containerd/containerd/pull/10151)), which makes merging PR particularly challenging:
Since we run full suite of tests in each PR anyway, I think we could ease merge queue requirements a bit and remove vagrants tests for now.
> Don't require vagrant tests in merge queues

- .github/actions/install-go/action.yml
- .github/workflows/api-release.yml
- .github/workflows/ci.yml
- .github/workflows/release.yml
- Vagrantfile
- contrib/Dockerfile.test
- contrib/fuzz/oss_fuzz_build.sh
- script/setup/prepare_env_windows.ps1
Go 1.22.3 release includes bug fixes for the core net/http package.
Full release notes: https://go.dev/doc/devel/release#go1.22.minor
This change updates the Go tooling in CI to Go 1.22.3.
> Update tooling to Go 1.22.3 for net/http bug fixes

- core/mount/mount_linux.go
resolves https://github.com/moby/buildkit/issues/4667
refer: https://github.com/moby/buildkit/issues/4667#issuecomment-2095055243
> Preserve Unprivileged locked flags during remount of bind mounts

- metadata/snapshot.go
- metadata/snapshot_test.go
Currently the metadata snapshotter is not consistently adding keys to a
lease when already exists is returned. When a lease is provided, any
already exists errors should add the relevant key to the lease. It is
not expected that clients must explicitly lease a key after calling
Prepare/Commit.
Backport of https://github.com/containerd/containerd/pull/10187
> [release/1.6] Update metadata snapshotter to lease on already exists

- metadata/snapshot.go
- metadata/snapshot_test.go
Currently the metadata snapshotter is not consistently adding keys to a
lease when already exists is returned. When a lease is provided, any
already exists errors should add the relevant key to the lease. It is
not expected that clients must explicitly lease a key after calling
Prepare/Commit.
Backport of #10187
> [release/1.7] Update metadata snapshotter to lease on already exists

- cmd/ctr/commands/images/pull.go
- core/unpack/unpacker.go
When a set of layers are provided to the unpacker, then the unpacker should still fetch them regardless of whether they will be used for unpack. The image handler filters are responsible for removing content which is not intended to be fetched. Currently there is no way to use an unpacker and also fetch all platforms.
Now that we have a more expressive unpacker configuration, we could update the ctr options to be clearer.
> Unpack fetch all

- .github/actions/install-go/action.yml
- .github/workflows/ci.yml
- .github/workflows/release.yml
- Vagrantfile
- contrib/Dockerfile.test
- contrib/fuzz/oss_fuzz_build.sh
- script/setup/prepare_env_windows.ps1
Go 1.21.10 and 1.22.3 release includes bug fixes for the core net/http package.
Full release notes: https://go.dev/doc/devel/release#go1.21.minor, https://go.dev/doc/devel/release#go1.22.minor
This change updates the Go tooling in CI to Go 1.21.10 and 1.22.3
(cherry picked from commit 25c2f690a8e031193bcbc1e82a7de33da647fc58)
> [release/1.7] Update tooling to Go 1.21.10, 1.22.3 for net/http bug fixes

- .github/actions/install-go/action.yml
- .github/workflows/ci.yml
- .github/workflows/release.yml
- Vagrantfile
- contrib/Dockerfile.test
- script/setup/prepare_env_windows.ps1
Go 1.21.10 and 1.22.3 release includes bug fixes for the core net/http package.
Full release notes: https://go.dev/doc/devel/release#go1.21.minor, https://go.dev/doc/devel/release#go1.22.minor
This change updates the Go tooling in CI to Go 1.21.10 and 1.22.3
(cherry picked from commit 25c2f690a8e031193bcbc1e82a7de33da647fc58)
> [release/1.6] Update tooling to Go 1.21.10, 1.22.3 for net/http bug fixes

- contrib/fuzz/oss_fuzz_build.sh
Related to switching from AdamKorcz/instrumentation@dev to main branch; this change is required to make the switch and pass CI in google/oss-fuzz: https://github.com/google/oss-fuzz/pull/11953
> Update instrumentation fuzzer with new flag

- mount/mount_linux.go
> [release/1.6] Preserve CL_UNPRIVILEGED locked flags during remount of bind mounts

- mount/mount_linux.go
Backport of #10200 
This will allow moby/buildkit to pick up the change as they are still on containerd v1.7
> [release/1.7] Preserve CL_UNPRIVILEGED locked flags during remount of bind mounts

- go.mod
- go.sum
- integration/client/go.mod
- integration/client/go.sum
- vendor/github.com/containerd/ttrpc/client.go
- vendor/modules.txt
Update ttrpc to 1.2.4  https://github.com/containerd/ttrpc/releases/tag/v1.2.4 
Full list of changes: https://github.com/containerd/ttrpc/compare/v1.2.3...v1.2.4
> [release/1.7] Update ttrpc tag to 1.2.4

- services/server/config/config.go
Once 2.0 is released, the config version is bumped to 3 which is backwards incompatible with version 2. While we do not need to handle version 3 in 1.6 and 1.7 release, we should error out if the config version is higher than the max supported version. This will provide a clear error when an unsupported config version is used rather have containerd subtly error or use an unexpected configuration.
Backport of #10165
> [release/1.6] Handle unsupported config versions

- cmd/ctr/commands/images/pull.go
- pkg/unpack/unpacker.go
When a set of layers are provided to the unpacker, then the unpacker should still fetch them regardless of whether they will be used for unpack. The image handler filters are responsible for removing content which is not intended to be fetched. Currently there is no way to use an unpacker and also fetch all platforms.
This fixes an issues where the transfer service pull could error out if specifying all platforms but only providing an unpack configuration for a subset.
Backports #10202
> [release/1.7] Unpack fetch all

- mount/losetup_linux.go
Optimization for creating loop devices on kernels >= 5.8 would be nice to have in release/1.7.
This change backports #9211 and follow on changes #9805, #9813 to release/1.7.
> [release/1.7] Use LOOP_CONFIGURE when creating loop devices

- docs/cri/registry.md
- docs/hosts.md
Update registry config guide to use CRI service plugin type added in https://github.com/containerd/containerd/pull/9681
```
-       // CRIImagePlugin implements a cri image service
-       CRIImagePlugin plugin.Type = "io.containerd.cri.image.v1"
+       // CRIServicePlugin implements a cri service
+       CRIServicePlugin plugin.Type = "io.containerd.cri.v1"
```
Fix: #10074
> docs: update registry config guide

- docs/cri/config.md
- internal/cri/io/container_io.go
- internal/cri/io/exec_io.go
- internal/cri/io/helpers.go
- internal/cri/server/restart.go
sandbox address should be in the form of
<ttrpc|grpc>+<unix|vsock|hvsock>://<uds-path|vsock-cid:vsock-port|uds-path:hvsock-port> 
for example: ttrpc+hvsock:///run/test.hvsock:1024
or: grpc+vsock://1111111:1024
and the Stdin/Stdout/Stderr will add a `streaming_id` as a parameter of the url result form is:
<ttrpc|grpc>+<unix|vsock|hvsock>://<uds-path|vsock-cid:vsock-port|uds-path:hvsock-port>?streaming_id=<stream-id> for example ttrpc+hvsock:///run/test.hvsock:1024?streaming_id=111111 or grpc+vsock://1111111:1024?streaming_id=222222
Change the current logic of add a `streaming` in the path, because unix domain socket or hybrid vsock alread have the path field and add a `streaming` suffix makes the logic complecated.
> fix: modify streaming io url and add docs of sandboxer and io_type

- releases/v1.7.17.toml
- version/version.go
----
Welcome to the v1.7.17 release of containerd!
The seventeenth patch release for containerd 1.7 contains various fixes and updates.
* Use LOOP_CONFIGURE when creating loop devices ([#10209](https://github.com/containerd/containerd/pull/10209))
* Update unpacker to fetch all provided content ([#10233](https://github.com/containerd/containerd/pull/10233))
* Preserve CL_UNPRIVILEGED locked flags during remount of bind mounts ([#10210](https://github.com/containerd/containerd/pull/10210))
* Update metadata snapshotter to lease on already exists ([#10198](https://github.com/containerd/containerd/pull/10198))
* Handle unsupported config versions ([#10165](https://github.com/containerd/containerd/pull/10165))
* Fix deadlock when writing to pipe blocks …
> [release/1.7] Prepare release notes for v1.7.17

- internal/cri/server/images/image_pull_test.go
This is a non-functional change, that fixes the following typos:
* Snashotter -> Snapshotter
* expectSnapshotter -> expectedSnapshotter
* expectErr -> expectedErr
* exiting-runtime -> existing-runtime
> images: tests: Fix typos in the tests

- .mailmap
- version/version.go
----
Welcome to the v2.0.0-rc.2 release of containerd!  
* Preserve Unprivileged locked flags during remount of bind mounts ([#10200](https://github.com/containerd/containerd/pull/10200))
* Add api Go module and move all protos under api …
> Prepare release notes for v2.0.0-rc.2

- docs/cri/config.md
- internal/cri/config/config.go
- internal/cri/config/config_unix.go
- internal/cri/config/config_windows.go
- internal/cri/server/sandbox_run.go
- internal/cri/server/sandbox_run_linux.go
- internal/cri/server/sandbox_run_other.go
- internal/cri/server/sandbox_run_windows.go
- internal/cri/server/service_linux.go
The CNI maintainers intend on deprecating the loopback plugin. This approach where we set the lo interface to up is similar to what CRI-O does. We (@mikebrow ) decided to have a flag to disable/enable and eventually we will go with removing the flags and just always setting the lo interface to up.
> Add support to set loopback to up

- go.mod
- go.sum
- integration/client/go.mod
- integration/client/go.sum
- vendor/github.com/Microsoft/go-winio/fileinfo.go
- vendor/github.com/Microsoft/hcsshim/.gitattributes
- vendor/github.com/Microsoft/hcsshim/.gitignore
- vendor/github.com/Microsoft/hcsshim/Protobuild.toml
- vendor/github.com/Microsoft/hcsshim/README.md
- vendor/github.com/Microsoft/hcsshim/cmd/containerd-shim-runhcs-v1/options/runhcs.pb.go
- vendor/github.com/Microsoft/hcsshim/cmd/containerd-shim-runhcs-v1/stats/stats.pb.go
- vendor/github.com/Microsoft/hcsshim/internal/regstate/zsyscall_windows.go
- vendor/github.com/Microsoft/hcsshim/internal/winapi/winapi.go
- vendor/github.com/Microsoft/hcsshim/pkg/go-runhcs/runhcs.go
- vendor/modules.txt
go-winio breaks on go1.22 (at runtime) due to alignment issues. This prevents an error while extracing layers:
Invalid access to memory location
See:
- https://github.com/golang/go/issues/65069
- https://github.com/moby/moby/pull/47743
- https://github.com/microsoft/go-winio/pull/312
Related:
- https://github.com/kubernetes-sigs/cri-tools/pull/1387#issuecomment-2120481609
> [release/1.6] Bump hcsshim and go-winio for go1.22 compat

- .mailmap
- releases/v1.6.32.toml
- version/version.go
---
Welcome to the v1.6.32 release of containerd!
The thirty-second patch release for containerd 1.6 contains various fixes and updates.
* Handle unsupported config versions ([#10234](https://github.com/containerd/containerd/pull/10234))
* Preserve CL_UNPRIVILEGED locked flags during remount of bind mounts ([#10212](https://github.com/containerd/containerd/pull/10212))
* Update metadata snapshotter to lease on already exists ([#10199](https://github.com/containerd/containerd/pull/10199))
* Update apparmor template to allow confined runc to kill containers ([#10130](https://github.com/containerd/containerd/pull/10130))
* Prevent GC from schedule itself with 0 period. ([#10103](https://github.com/containerd/containerd/pull/10103))
* Configure otel from env instead of …
> [release/1.6] Prepare release notes for v1.6.32

- core/images/image.go
"unknown" platform should not be returned from `Platforms()` as a valid platform type for an image.
Fixes: #10196
> core/image: fix usage of "unknown" platform

- .github/workflows/release.yml
Partial #10262 
This change disables marking of containerd 1.6 releases as latest. This change backports https://github.com/containerd/containerd/commit/21d3fedf44335e1a971b9099e79eb0cba450d092 which updates the `action-gh-release` package from v1 to v2 which adds the `make_latest` functionality required by the change.
> [release/1.6] Explicitly set release latest to false

- .github/workflows/release.yml
Partial #10262 
This change enables marking of containerd 1.7 releases as latest. This change backports https://github.com/containerd/containerd/commit/21d3fedf44335e1a971b9099e79eb0cba450d092 which updates the `action-gh-release` package from v1 to v2 which adds the `make_latest` functionality required by the change.
> [release/1.7] Explicitly set release latest to true

- core/sandbox/controller.go
- core/sandbox/proxy/controller.go
- internal/cri/server/container_create.go
- internal/cri/server/container_create_test.go
- internal/cri/server/images/service.go
- internal/cri/server/podsandbox/controller.go
- internal/cri/server/sandbox_service.go
- internal/cri/server/service.go
- internal/cri/server/service_test.go
- plugins/sandbox/controller.go
Commit 3c8469a78269d9ba2ead4798d4469d95f8c3cdd5 (https://github.com/containerd/containerd/pull/7958) removed uses of the api types.Platform type from public interfaces, instead using the type from the OCI image spec.
For convenience, it also introduced an alias in the platforms package. While this alias allows packages that already import containerd's platforms package (now a separate module), it may also cause confusion (it's not clear that it's an alias for the OCI type), and for packages that do not depend on containerd's platforms package / module may now be resulting in an extra dependency.
Let's remove the use of this alias, and instead use the OCI type directly.
> remove uses of platforms.Platform alias

- contrib/ansible/cri-containerd.yaml
- docs/cri/config.md
- docs/cri/crictl.md
- integration/client/testdata/default-1.6.toml
- integration/client/testdata/default-1.7.toml
- integration/images/image_list.go
- integration/images/image_list.sample.toml
- internal/cri/config/config.go
- internal/cri/server/images/image_pull_test.go
- plugins/cri/images/plugin_test.go
Upgrade containerd use registry.k8s.io/pause version default version to 3.10
> update pause image to 3.10

- core/sandbox/proxy/controller.go
- internal/cri/server/events.go
For remote sandbox controllers, the controller process may restart, we have to retry if the error indicates that it is the grpc disconnection.
> sandbox: do retry for wait to remote sandbox controller

- api/go.mod
A higher go build version is not required for the API and this will help some [downstream projects test the change which are currently blocked on 1.22 upgrade](https://github.com/moby/moby/pull/46982).
> Update api minimum Go version to 1.21

- pkg/cri/sbserver/container_create.go
- pkg/cri/sbserver/container_create_test.go
- pkg/cri/sbserver/podsandbox/controller.go
- plugins/sandbox/controller.go
- sandbox/controller.go
- sandbox/proxy/controller.go
Commit 3c8469a78269d9ba2ead4798d4469d95f8c3cdd5 removed uses of the api types.Platform type from public interfaces, instead using the type from the OCI image spec.
For convenience, it also introduced an alias in the platforms package. While this alias allows packages that already import containerd's platforms package (now a separate module), it may also cause confusion (it's not clear that it's an alias for the OCI type), and for packages that do not depend on containerd's platforms package / module may now be resulting in an extra dependency.
Let's remove the use of this alias, and instead use the OCI type directly.
Equivalent of 446e63579cba6d375b229305e113ea4ed756822b (https://github.com/containerd/containerd/pull/10273) in main.
> [release/1.7] remove uses of platforms.Platform alias

- .github/workflows/release.yml
Partial #10262 
This change disables marking of containerd mainline releases as latest.
> Explicitly set release latest to false

- core/mount/mount_test.go
- core/mount/temp.go
- integration/container_volume_linux_test.go
- integration/images/volume-ownership/Dockerfile
- internal/cri/opts/container.go
Remove volatile option when CRI prepares image volumes.
Fixes: #10228
> *: export RemoveVolatileOption for CRI image volumes

- core/transfer/local/push.go
Currently transfer service doesn't handle conflict among pushing of duplicated blobs and pushing an image with duplicated blobs fails.
This commit fixes this issue by using [`dockerPusher.Writer`](https://github.com/containerd/containerd/blob/21c244d4369856c2b81fdcf9af75645f712f5d04/core/remotes/docker/pusher.go#L49-L53) that detects the conflict and allow retrying using [`content.OpenWriter`](https://github.com/containerd/containerd/blob/21c244d4369856c2b81fdcf9af75645f712f5d04/core/content/helpers.go#L131) helper. `content.OpenWriter` is already used by [`remotes.PushHandler`](https://github.com/containerd/containerd/blob/21c244d4369856c2b81fdcf9af75645f712f5d04/core/remotes/handlers.go#L156) to handle duplicated blobs safely.
But transfer service doesn't use this so it (and `ctr i …
> Transfer: Push: fix failure on pushing duplicated blobs

- .github/workflows/ci.yml
Update to latest rockylinux version.
The rockylinux/8 link is broken in vagrant cloud as the URL it points to was moved from their pub repository (https://dl.rockylinux.org/pub/rocky/8.9/images/x86_64/Rocky-8-Vagrant-Libvirt-8.9-20231119.0.x86_64.box gives us 404 during CI) to vault (https://dl.rockylinux.org/vault/rocky/8.9/images/x86_64/Rocky-8-Vagrant-Libvirt-8.9-20231119.0.x86_64.box is new link but not redirected to).
> Update rockylinux vagrant build

- .github/actions/install-go/action.yml
- .github/workflows/api-release.yml
- .github/workflows/ci.yml
- .github/workflows/release.yml
- Vagrantfile
- contrib/Dockerfile.test
- contrib/fuzz/oss_fuzz_build.sh
- script/setup/install-runc
- script/setup/prepare_env_windows.ps1
Includes fix for a symlink race on remove.
Updates 1.21 to 1.21.11 for runc install which also includes the symlink fix.
> Update Go version to 1.22.4

- releases/v1.6.33.toml
- version/version.go
Depends on #10299
----
Welcome to the v1.6.33 release of containerd!
The thirty-third patch release for containerd 1.6 contains various updates along
with an updated version of Go. Go 1.22.4 and 1.21.11 include a fix for a symlink
time of check to time of use race condition during directory removal.
* Update Go version to 1.21.11 ([#10299](https://github.com/containerd/containerd/pull/10299))
* Migrate log imports to `github.com/containerd/log` ([#10271](https://github.com/containerd/containerd/pull/10271))
* Migrate `errdefs` package to `github.com/containerd/errdefs` ([#10267](https://github.com/containerd/containerd/pull/10267))
* Fix usage of "unknown" platform ([#10268](https://github.com/containerd/containerd/pull/10268))
Please try out the release binaries and …
> [release/1.6] Prepare release notes for v1.6.33

- releases/v1.7.18.toml
- version/version.go
Depends on #10298
----
Welcome to the v1.7.18 release of containerd!
The eighteenth patch release for containerd 1.7 contains various updates along
with an updated version of Go. Go 1.22.4 and 1.21.11 include a fix for a symlink
time of check to time of use race condition during directory removal.
* Update Go version to 1.21.11 ([#10298](https://github.com/containerd/containerd/pull/10298))
* Remove uses of `platforms.Platform` alias ([#10277](https://github.com/containerd/containerd/pull/10277))
* Migrate log imports to `github.com/containerd/log` ([#10269](https://github.com/containerd/containerd/pull/10269))
* Migrate errdefs package to `github.com/containerd/errdefs` ([#10266](https://github.com/containerd/containerd/pull/10266))
* Fix usage of "unknown" platform …
> [release/1.7] Prepare release notes for v1.7.18

- cmd/ctr/commands/images/pull.go
This commit fixes `ctr` ignored `--label` flag when using transfer service.
> ctr: pull: Do not ignore labels when transfer service is used

- cmd/ctr/commands/images/push.go
- core/transfer/image/imagestore.go
- core/transfer/local/push.go
- core/transfer/transfer.go
This commit enables to specify platforms for pushing images using the transfer service, which was one of the commented TODOs. This also fixes `ctr i push` to pass platform flags to the transfer service.
> Transfer: Push: Enable to specify platforms

- pkg/cri/server/container_create_windows.go
Change in 989f1ec54f6764020447b03020b97592312c5f85 assumed a single
place (pkg/cri/sbserver) where this had to be fixed.
Commit in main branch for reference:
(cherry picked from commit c7ea06a69bdf9147758353b4eb12bb78240fbda8)
> [release/1.7]: HPC working directory fix in pkg/cri/server code

- .github/workflows/ci.yml
golangci-lint v1.59.1: https://github.com/golangci/golangci-lint/releases/tag/v1.59.1
> CI:  bump up golangci-lint to v1.59.1

- core/remotes/docker/config/hosts.go
- core/remotes/docker/config/hosts_test.go
- core/remotes/docker/resolver.go
- core/remotes/docker/resolver_test.go
- core/remotes/docker/resolver_unix.go
- core/remotes/docker/resolver_windows.go
When no port is specified in host, allow falling back from 443 to 80 when http is specified along with a TLS configuration. This increases the cases when https can be preferred and fixes a case where fallback does not happen after a connection refused where previously Docker would have fallen back.
Related to https://github.com/moby/buildkit/issues/4915 which uses same approach
> Allow fallback across default ports

- cmd/ctr/commands/images/import.go
- cmd/ctr/commands/images/pull.go
- cmd/ctr/commands/images/push.go
Following up: https://github.com/containerd/containerd/pull/10318#issuecomment-2159573558
ctr currently silently ignores several flags by default (without --local) and the user can't know which flags are supported until they see the code. This commit fixes ctr to return an explicit error when it finds an unsupported flag.
> ctr: return explicit errors for flags unsupported by transfer service

- internal/cri/server/podsandbox/sandbox_run_linux_test.go
Debian has started building packages with usernamespaces
to disable network access and similar isolation features. The
containerd package executes a unit test that fails in that
scenario, see https://bugs.debian.org/1070411
The code contains a conditional on whether it is running in
usernamepsace. This commit expands the unit test to cover
this behavior; it was previously untested.
The easiest way to reproduce this issue is to prefix the test
invocaiton with 'unshare -nr go test [...]'
Signed-off-by: Reinhard Tartler <siretart@gmail.com>
> Allow running test in usernamespace

- integration/client/daemon.go
- snapshots/devmapper/plugin/plugin.go
Checks plugin load success and fixes devmapper always failing when not configured
> [release/1.7] Fail integration test early when a plugin load fails

- version/version.go
----
Welcome to the v2.0.0-rc.3 release of containerd!  
* Add type alias for event Envelope ([#10279](https://github.com/containerd/containerd/pull/10279))
* Preserve Unprivileged locked flags during remount of bind mounts …
> Prepare v2.0.0-rc.3 release

- pkg/tracing/helpers.go
- pkg/tracing/log.go
- pkg/tracing/plugin/otlp.go
- pkg/tracing/tracing.go
While the hook is intended to be used with logrus, we don't need to have
the direct import; use the aliases provided by the containerd/log module
instead.
Check `span.IsRecording()` first, as it's a more lightweight check than
`span.SpanContext().IsValid()`
> pkg/tracing: remove direct use of logrus, and fix some linting issues

- integration/container_volume_linux_test.go
- integration/images/volume-ownership/Dockerfile
- integration/utils_linux_test.go
- mount/mount_test.go
- mount/temp.go
- pkg/cri/opts/container.go
backports:
* https://github.com/containerd/containerd/pull/10274
* https://github.com/containerd/containerd/pull/9555
* part of https://github.com/containerd/containerd/pull/9262 (about how to setup individual containerd)
> [release/1.7] Remove overlayfs volatile option on temp mounts 

- cmd/containerd/server/config/config.go
- cmd/containerd/server/server.go
fixes #10313 
This change allows proxy plugins to declare capabilities that get registered with the plugin.
For example, a remote snapshotter can declare that it supports native idmapping like:
```
[proxy_plugins.soci]
type=snapshot
address=/run/soci-snapshotter-grpc/soci-snapshotter-grpc.sock
capabilities=["id-map"]
```
> Allow proxy plugins to have capabilities

- core/remotes/docker/auth/fetch.go
Before this, during a call to the docker resolver, we would generate span wrappers for each HTTPRequest correctly, however, as the docker resolver reaches out to the docker authorizer, it could create HTTP requests (for fetching tokens) that would not be wrapped in any span.
This can result in rather confusing traces, e.g. something like:
remotes.docker.resolver.HTTPRequest
HTTP HEAD (fetch index, fails with 401)
HTTP GET (fetch token)
remotes.docker.resolver.HTTPRequest
HTTP HEAD (fetch index)
remotes.docker.resolver.HTTPRequest
HTTP GET (fetch manifest)
By adding a span into the FetchToken, this trace becomes a little easier to consume:
remotes.docker.resolver.HTTPRequest
HTTP HEAD (fetch index, fails with 401)
remotes.docker.resolver.FetchToken
HTTP GET (fetch token) …
> auth: add span to FetchToken helpers

- .github/workflows/ci.yml
- Vagrantfile
Fixes the broken vagrant builds
(cherry picked from commit 08c1e12e9b5eabacd6f3a3f328cad618f1221e09)
> [release/1.6] Update Fedora and EL linux version in vagrant

- .github/workflows/stale.yml
Following guidance from https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs#example-setting-the-github_token-permissions-for-one-job-in-a-workflow
> Reduce scope of permissions in stale workflow

- .golangci.yml
- sandbox/bridge.go
- services/introspection/service.go
- relates to https://github.com/containerd/containerd/pull/10266
- relates to https://github.com/containerd/containerd/pull/10189
Use of the errdefs package was removed in 308341a4464bd723630d3df19a5df20aa252af9f but found their way back in through 3be919f3c023f776e5db1b162f642d79a36312a8
This patch removes the imports.
Prevent accidental imports of the packages that moved to a separate
module, but that are now an alias.
> [release/1.7] remove imports of errdefs package, and add depguard linter 

- tracing/plugin/otlp.go
This was broken due to 9360e37169f2ba3135f7a6f39a3ab7c9231abbd6 (backport from main).
The backport should not have broken the toml config so this more or less restores that.
This treats the env vars as preferred.
It is not perfect since, as an example, `Endpoint` could be set on the config and the env to set the protocol could be set and these could conflict, however I think this is an unlikely scenario and people should use one or the other, not both.
This change converts the config into the relevant environment variables before initializing tracers.
Fixes #10358
> [release/1.7] Fix support for OTLP config

- .golangci.yml
- relates to https://github.com/containerd/containerd/pull/10368#discussion_r1646854987
- relates to https://github.com/containerd/containerd/pull/10367
This was introduced in 136e1b72d8330d43b9cedf051a0b745cf70df9ee, but missed during review.
> [release/1.7] golangci-lint fix typo in depguard message

- pkg/cri/server/container_create_windows.go
cherry picked from commit 33b62936ea56c85183331ad2b1d9cb3c76dce8da in release/1.7 branch
No additional changes to the original commit
> [release/1.6] Fix HPC working directory in pkg/cri/server code

- core/metadata/buckets.go
The godoc should properly show the formatting of the database structure and sections explaining it.
How it looks today...
https://pkg.go.dev/github.com/containerd/containerd/v2@v2.0.0-rc.3/core/metadatamisformatted
Now from godoc with this change...
> Cleanup metadata godoc

- go.mod
- go.sum
- integration/client/go.mod
- integration/client/go.sum
- vendor/github.com/containerd/ttrpc/README.md
- vendor/github.com/containerd/ttrpc/client.go
- vendor/github.com/containerd/ttrpc/server.go
- vendor/modules.txt
- backport https://github.com/containerd/containerd/pull/10372
full diff: https://github.com/containerd/ttrpc/compare/v1.2.4...v1.2.5
(cherry picked from commit b323e9eec62e1863422bc45ac1135132f0122aa5)
> [release/1.7 backport] vendor: github.com/containerd/ttrpc v1.2.5

- .github/workflows/api-release.yml
- .github/workflows/ci.yml
- .github/workflows/release.yml
- plugins/snapshots/devmapper/snapshotter_test.go
- add ubuntu-24 github action runners into the test matrix
- all runners have been updated to ubuntu-24 except the job where release binaries are built. Its still kept at ubuntu-20 for maintaining compatibility
Notes to reviewers:
- The vagrant and ovmf package used is still kept at the ubuntu-22 versions since the vagrant sources are not yet available in the ubuntu-24 repository. 
- The ovmf package is pinned at an older version because newer packages will cause the boot to fail for the VM.  Ref: https://changelogs.ubuntu.com/changelogs/pool/main/e/edk2/edk2_2024.02-2/changelog
```
.
edk2 (2023.11-2) unstable; urgency=medium
* ovmf: Remove dangling symlink to removed 2M image:
- /usr/share/OVMF/OVMF_CODE.ms.fd
.
```
> ci: enable ubuntu-24 runners

- .github/workflows/api-release.yml
- api/releases/v1.7.19.toml
Like in the main branch, the API module must be tagged first and go.mod updated before a release which includes api changes.
Test run: https://github.com/dmcgowan/containerd/releases/tag/api%2Fv1.7.19-rc.0
----
Welcome to the api/v1.7.19 release of containerd!
The first dedicated release for the containerd 1.7 API. This release is
separately tagged from the main 1.7.x releases after the v1.7.18
release but follows the versioning.
* Add API go module ([#10189](https://github.com/containerd/containerd/pull/10189))
* Akhil Mohan
* Phil Estes
<details><summary>7 commits</summary>
<p>
* [`436feeb0d`](https://github.com/containerd/containerd/commit/ …
> [release/1.7] Prepare release notes for api v1.7.19

- cmd/containerd-shim-runc-v2/manager/manager_linux.go
- cmd/ctr/commands/pprof/pprof.go
- cmd/ctr/commands/shim/pprof.go
- cmd/ctr/commands/shim/shim.go
- integration/client/container_linux_test.go
- integration/issue7496_linux_test.go
- pkg/shim/shim.go
- pkg/shim/shim_unix.go
- pkg/shim/shim_windows.go
- pkg/shim/util_unix.go
Adding pprof capability to containerd-runc-shim-v2.
This makes the shim to expose an additional debugging endpoint when running in DEBUG mode. And users can capture pprof data via ctr:
```
NAME:
ctr shim pprof - Provide golang pprof outputs for containerd-shim
USAGE:
ctr shim pprof command [command options] 
COMMANDS:
block         Goroutine blocking profile
goroutines    Dump goroutine stack dump
heap          Dump heap profile
profile       CPU profile
threadcreate  Goroutine thread creating profile
trace         Collect execution trace
help, h       Shows a list of commands or help for one command
OPTIONS:
--help, -h  Show help (default: false)
```
e.g. To capture the heap profile for the shim hosting container "test":
```
ctr shim --id test pprof heap >heap.prof 
```
> Add pprof to runc-shim

- core/metadata/bolt.go
- core/metadata/content.go
- core/metadata/db.go
The boltdb instance in metadata is only used for getting transactions and can also be overriden via the context to have a wider control of the transaction boundary. Using the transactor interface allows callers of metadata to have more control of the transaction lifecycle.
Since boltdb must be fsync'ed on commit, operations which perform many database operations can be costly and slow. While providing transactor via context can be used to group together operations, it does not provide a way to manage the commit fsyncs more globally.
This change is not functional but an interface change that would be good to get into for 2.0.
> Use the transactor interface in metadata

- pkg/reference/reference.go
- pkg/reference/reference_test.go
These were straight concatenations of strings; reduce some allocations by
removing fmt.Sprintf for this.
Before / After:
BenchmarkSplitObject-10        2785656    428.1 ns/op     416 B/op    13 allocs/op
BenchmarkSplitObjectNew-10    13510520     88.2 ns/op       0 B/op     0 allocs/op
The behavior of this function is quite counter-intuitive, as it preserves
the delimiter in the result. This function should probably have been an
internal function, as its use for external consumers would be very limited,
but let's at least document the (surprising) behavior for those that are
considering to use it.
It appears that BuildKit is currently the only (publicly visible) external
consumer of this function; I am planning to inline its functionality in
Spec.Digest() and to deprecate this function so …
> pkg/reference: reduce allocations and improve GoDoc

- reference/reference.go
- reference/reference_test.go
- Backport of https://github.com/containerd/containerd/pull/10393
- with the intent to backport https://github.com/containerd/containerd/pull/10394 after this, so that it can be removed for v2.0
:point_right: note that the `pkg/reference` package is still at `reference` in the 1.7 branch, but Git was happy to cherry-pick the changes and apply them to the right files :tada:
> [release/1.7 backport] reference: reduce allocations and improve GoDoc

- go.mod
- go.sum
- integration/client/go.mod
- integration/client/go.sum
- vendor/github.com/Microsoft/hcsshim/hcn/hcn.go
- vendor/github.com/Microsoft/hcsshim/hcn/hcnerrors.go
- vendor/github.com/Microsoft/hcsshim/hcn/hcnglobals.go
- vendor/github.com/Microsoft/hcsshim/hcn/hcnloadbalancer.go
- vendor/github.com/Microsoft/hcsshim/hcn/hcnpolicy.go
- vendor/github.com/Microsoft/hcsshim/hcn/hcnsupport.go
- vendor/github.com/Microsoft/hcsshim/internal/hns/hnspolicy.go
- vendor/modules.txt
The backport PR:
https://github.com/microsoft/hcsshim/commit/6749c2f4196edcd51cfbd85dcb0f411613b7de82 / https://github.com/microsoft/hcsshim/pull/2187 (https://github.com/microsoft/hcsshim/pull/2188)
Along with [another fix ](https://github.com/microsoft/hcsshim/commit/eaeb4bcc5a00be5ba9a5578ba45b5096cedd69f9)checked in a while ago.
> [release/1.6] Updating hcsshim vendoring to 0.9.12 to include an important backported fix

- go.mod
- go.sum
- integration/client/go.mod
- integration/client/go.sum
- vendor/github.com/Microsoft/hcsshim/hcn/hcn.go
- vendor/github.com/Microsoft/hcsshim/hcn/hcnerrors.go
- vendor/github.com/Microsoft/hcsshim/hcn/hcnglobals.go
- vendor/github.com/Microsoft/hcsshim/hcn/hcnloadbalancer.go
- vendor/github.com/Microsoft/hcsshim/hcn/hcnpolicy.go
- vendor/github.com/Microsoft/hcsshim/hcn/hcnsupport.go
- vendor/github.com/Microsoft/hcsshim/internal/hns/hnsendpoint.go
- vendor/github.com/Microsoft/hcsshim/internal/hns/hnspolicy.go
- vendor/modules.txt
The backport PR: 
- https://github.com/microsoft/hcsshim/commit/6749c2f4196edcd51cfbd85dcb0f411613b7de82 / https://github.com/microsoft/hcsshim/pull/2187
Since hcsshim vendoring was on 11.5 before, this included changes from 11.6-11.7 as well. 
https://github.com/microsoft/hcsshim/compare/v0.11.5...v0.11.7
> [release/1.7] Updating hcsshim vendoring to 0.11.7 to include an important backported fix

- reference/reference.go
- backport https://github.com/containerd/containerd/pull/10394
- depends on / stacked on https://github.com/containerd/containerd/pull/10395
The behavior of this function is quite counter-intuitive, as it preserves
the delimiter in the result, and its use for external consumers would be
very limited.
Spec.Digest no longer uses this function, and it appears that BuildKit is
currently the only (publicly visible) external consumer of it.
This patch deprecates the function.
> [release/1.7 backport] reference: deprecate SplitObject

- pkg/reference/reference.go
- pkg/reference/reference_test.go
- follow-up to / stacked on https://github.com/containerd/containerd/pull/10393
The behavior of this function is quite counter-intuitive, as it preserves
the delimiter in the result, and its use for external consumers would be
very limited.
Spec.Digest no longer uses this function, and it appears that BuildKit is
currently the only (publicly visible) external consumer of it.
This patch deprecates the function.
> pkg/reference: deprecate SplitObject, and remove for v2.0

- pkg/fsverity/fsverity_linux.go
- pkg/fsverity/fsverity_other.go
- pkg/fsverity/fsverity_test.go
- plugins/content/local/store.go
- plugins/content/local/store_test.go
- plugins/content/local/writer.go
The Linux Kernel [fs-verity](https://www.kernel.org/doc/html/latest/filesystems/fsverity.html) feature can be utilized to verify the integrity of blob data in the content store. Enabling fs-verity on the blob data allows fs-verity to verify the integrity of the data at the time it is read. A read error will occur if fs-verity detects any _accidental_ corruption of the data.
Here, containerd will enable fs-verity on the content blob files if it determines that both the kernel and the filesystem support fs-verity operations.
Addresses issue #3849 and issue #953.
> Fsverity content verification

- internal/cri/nri/nri_api_linux.go
- internal/cri/nri/nri_api_other.go
- internal/cri/server/service.go
- internal/nri/nri.go
- plugins/cri/cri.go
A nil CRIImplementation field can cause a nil pointer dereference and panic during startup recovery.
Prior to this change, the nri.API struct would have a nil cri (CRIImplementation) field after nri.NewAPI until nri.Register was called.  Register is called mid-way through initialization of the CRI plugin, but recovery for containers occurs prior to that.  Container recovery includes establishing new exit monitors for existing containers that were discovered.  When a container exits, NRI plugins are given the opportunity to be notified about the lifecycle event, and this is done by accessing that CRIImplementation field inside the nri.API.  If a container exits prior to nri.Register being called, access to the CRIImplementation field can cause a panic.
Here's the call-path:
* The CRI …
> cri: ensure NRI API never has nil CRI

- internal/cri/server/container_stats.go
- internal/cri/server/container_stats_list.go
- internal/cri/server/container_stats_list_test.go
- internal/cri/server/sandbox_stats_linux.go
This reduces latency of ListPodSandboxStats() by avoiding calling shim API Task().
Prior to this commit, the latency of calling ListPodSandboxStats() with 35 sandboxes (one container per sandbox) took 450ms. Mostly it was due to calling Task() to each container's shim, which took 10ms.
However, the pid count has already been present in collected cgroup metrics so this commit reuses that info to improve performance. It also means Windows platform would still need to call Task().
After this commit, the latency of ListPodSandboxStats() is about 120ms.
> cri: get pid count from container metrics

- pkg/cri/cri.go
- pkg/cri/nri/nri_api_linux.go
- pkg/cri/nri/nri_api_other.go
- pkg/cri/sbserver/service.go
- pkg/cri/server/service.go
- pkg/nri/nri.go
(Backport of https://github.com/containerd/containerd/pull/10401)
A nil CRIImplementation field can cause a nil pointer dereference and panic during startup recovery.
Prior to this change, the nri.API struct would have a nil cri (CRIImplementation) field after nri.NewAPI until nri.Register was called.  Register is called mid-way through initialization of the CRI plugin, but recovery for containers occurs prior to that.  Container recovery includes establishing new exit monitors for existing containers that were discovered.  When a container exits, NRI plugins are given the opportunity to be notified about the lifecycle event, and this is done by accessing that CRIImplementation field inside the nri.API.  If a container exits prior to nri.Register being called, access to the …
> [release/1.7 backport] cri: ensure NRI API never has nil CRI

- releases/v1.7.19.toml
- version/version.go
----
Welcome to the v1.7.19 release of containerd!
The nineteenth patch release for containerd 1.7 contains various updates and
splits the main module from the api module in preparation for the same change
in containerd 2.0. Splitting the modules will allow 1.7 and 2.x to both exist
as transitive dependencies without running into API registration errors.
Projects should use this version as the minimum 1.7 version in preparing to
use containerd 2.0 or to be imported alongside it.
* Fix support for OTLP config ([#10360](https://github.com/containerd/containerd/pull/10360))
* Add API go module ([#10189](https://github.com/containerd/containerd/pull/10189))
* Remove overlayfs volatile option on temp mounts ([#10332](https://github.com/containerd/containerd/pull/10332))
* …
> [release/1.7] Prepare release notes for v1.7.19

- .github/actions/install-go/action.yml
- .github/workflows/api-release.yml
- .github/workflows/ci.yml
- .github/workflows/release.yml
- Vagrantfile
- contrib/Dockerfile.test
- contrib/fuzz/oss_fuzz_build.sh
- script/setup/prepare_env_windows.ps1
go1.22.5 (released 2024-07-02) includes security fixes to the net/http package, as well as bug fixes to the compiler, cgo, the go command, the linker, the runtime, and the crypto/tls, go/types, net, net/http, and os/exec packages. See the [Go 1.22.5 milestone](https://github.com/golang/go/issues?q=milestone%3AGo1.22.5+label%3ACherryPickApproved) for more details
This version has fix for [CVE-2024-24791](https://github.com/advisories/GHSA-hw49-2p59-3mhj)
Release notes: https://go.dev/doc/devel/release#go1.22.5
> update go version to 1.22.5

- errdefs/errdefs_deprecated.go
golangci-lint can now raise an error when the deprecated errdefs package is used:
> SA1019: "github.com/containerd/containerd/errdefs" is deprecated:
> use [github.com/containerd/errdefs]. (staticcheck)
> [release/1.7] errdefs: denote deprecation as a godoc comment

- .github/actions/install-go/action.yml
- .github/workflows/api-release.yml
- .github/workflows/ci.yml
- .github/workflows/release.yml
- Vagrantfile
- contrib/Dockerfile.test
- contrib/fuzz/oss_fuzz_build.sh
- script/setup/prepare_env_windows.ps1
go1.21.12 (released 2024-07-02) includes security fixes to the net/http package, as well as bug fixes to the compiler, the go command, the runtime, and the crypto/x509, net/http, net/netip, and os packages. See the [Go 1.21.12 milestone](https://github.com/golang/go/issues?q=milestone%3AGo1.21.12+label%3ACherryPickApproved) for more details.
This version has fix for [CVE-2024-24791](https://github.com/advisories/GHSA-hw49-2p59-3mhj)
Release notes: https://go.dev/doc/devel/release#go1.21.12
> [release/1.7] update to go1.21.12 / go1.22.5

- .github/actions/install-go/action.yml
- .github/workflows/ci.yml
- .github/workflows/release.yml
- Vagrantfile
- contrib/Dockerfile.test
- script/setup/prepare_env_windows.ps1
go1.21.12 (released 2024-07-02) includes security fixes to the net/http package, as well as bug fixes to the compiler, the go command, the runtime, and the crypto/x509, net/http, net/netip, and os packages. See the [Go 1.21.12 milestone](https://github.com/golang/go/issues?q=milestone%3AGo1.21.12+label%3ACherryPickApproved) for more details.
This version has fix for [CVE-2024-24791](https://github.com/advisories/GHSA-hw49-2p59-3mhj)
Release notes: https://go.dev/doc/devel/release#go1.21.12
> [release/1.6] update to go1.21.12 / go1.22.5

- pkg/cri/server/sandbox_stats_list.go
Similar to https://github.com/containerd/containerd/pull/10023 we have another symptom that shows up in k8s CI job(s)
Some example CI runs are: (click on `Kubernetes e2e suite: [It] [sig-node] NodeProblemDetector [NodeFeature:NodeProblemDetector] should run without error` to expand to see the error, you click on `Archive` link to get to the kubelet and containerd logs as well)
- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-alpha-enabled-default/1808526993558343680
- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-alpha-enabled-default/1808495031716155392
- https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-kubernetes-e2e-gci-gce-alpha-enabled-default/1808464328827867136
- …
> Fix for `[cri] ttrpc: closed` during ListPodSandboxStats

- pkg/cio/io.go
- pkg/cio/io_unix.go
- pkg/cio/io_windows.go
Windows requires that stderr is an empty string when running a container with TTY. In Containerd, [pkg/cio/io.go#L298:L302](https://github.com/containerd/containerd/blob/4a18adcfca4e37e829c0d3174bd04d4cbf222f9a/pkg/cio/io.go#L298:L302), the Stderr is set to a value, e.g.
```go
res = "binary:///C:/_xxx_/nerdctl.exe?_NERDCTL_INTERNAL_LOGGING=C%3A%5CProgramData%5Cnerdctl%5C052055e3"
``` 
which causes microsoft/hcsshim [service_internal.go#L127](https://github.com/microsoft/hcsshim/blob/8beabacfc2d21767a07c20f8dd5f9f3932dbf305/cmd/containerd-shim-runhcs-v1/service_internal.go#L127) to fail to create a new task.
To address this issue, we refactor `TerminalLogURI()` and `TerminalBinaryIO` functions by adding an optional parameter that specifies whether stderr should be set to an empty string …
> [Windows] Set stderr to empty string when using terminal on Windows

- .github/workflows/links.yml
- contrib/ansible/README.md
All our Github actions should have top level read permission to explicitly limit scope.
Related to #10338
> Add read permission limit on link workflow

- oci/spec_opts.go
- oci/spec_opts_linux_test.go
Cherry pick for - https://github.com/containerd/containerd/pull/8356
The inheritable capabilities set should never be larger than the bounding capabilities set. When a base spec is provided with non-empty inheritable capabilities today, the container will fail to run when those capabilities are explicitly dropped. This issue is only seen when a base spec with inheritable capabilities is explicitly provided in the configuration file, the default spec already removed inheritable capabilities in https://github.com/containerd/containerd/security/advisories/GHSA-c9cp-9c75-9v8c. Since the container is unable to start with this setup, there is no security concern. It may be worth a discussion whether more should be done to warn users who may have set this in their configuration before the GHSA, …
> [release/1.7] Support for dropping inheritable capabilities

- oci/spec_opts.go
- oci/spec_opts_linux_test.go
Cherry pick for - https://github.com/containerd/containerd/pull/8356
The inheritable capabilities set should never be larger than the bounding capabilities set. When a base spec is provided with non-empty inheritable capabilities today, the container will fail to run when those capabilities are explicitly dropped. This issue is only seen when a base spec with inheritable capabilities is explicitly provided in the configuration file, the default spec already removed inheritable capabilities in https://github.com/containerd/containerd/security/advisories/GHSA-c9cp-9c75-9v8c. Since the container is unable to start with this setup, there is no security concern. It may be worth a discussion whether more should be done to warn users who may have set this in their configuration before the GHSA, …
> [release/1.6] Support for dropping inheritable capabilities

- pkg/archive/tar.go
This PR includes the name of the affected file in the error, just like the error a few lines above does.
This change makes it *much* easier to identify the cause of race conditions where the size of a copied file changes during the execution of `HandleChange()`.
---
In my case, I was building a Docker image which had a `RUN` command that inadvertantly kept a process running in the background, constantly writing to a log file.  This caused a race condition in `copyBuffered()` where the header size determined here:
https://github.com/containerd/containerd/blob/ca6a8a56a5155013d1118f703f188021c3ec949d/pkg/archive/tar.go#L584-L585
was smaller than the number of bytes written via `copyBuffered()` later in the function:
https://github.com/containerd/containerd/blob/ca6a8a56a5155013d1118f703f1880 …
> Include file path in tar copy errors

- pkg/cri/sbserver/podsandbox/sandbox_run_linux.go
- pkg/cri/sbserver/podsandbox/sandbox_run_linux_test.go
- pkg/cri/server/sandbox_run_linux.go
- pkg/cri/server/sandbox_run_linux_test.go
If we find that DNSConfig is provided and empty (not nil), we should not replace it with the host's resolv.conf.
Also adds tests.
> [release/1.7] CRI: An empty DNSConfig != unspecified

- pkg/cri/sbserver/sandbox_status.go
Currently if you're using the shim-mode sandbox server support, if your shim that's hosting the Sandbox API dies for any reason that wasn't intentional (segfault, oom etc.) PodSandboxStatus is kind of wedged. We can use the fact that if we didn't go through the usual k8s flow of Stop->Remove and we still have an entry in our sandbox store, us not having a shim mapping anymore means this was likely unintentional.
> [release/1.7] CRI Sbserver: Make PodSandboxStatus friendlier to shim crashes

- pkg/cri/server/sandbox_run_linux.go
- pkg/cri/server/sandbox_run_linux_test.go
If we find that DNSConfig is provided and empty (not nil), we should not replace it with the host's resolv.conf.
Also adds tests.
> [release/1.6] CRI: An empty DNSConfig != unspecified

- internal/cri/server/sandbox_stats_list.go
ListPodSandboxStats() involves shim API calls for each sandbox to collect aggregated stats. So the total latency is proportional to the count of running sandboxes. 
This commit will optimize that to approximately same latency of 1 sandbox.
> cri: optimize ListPodSandboxStats with parallelism

- docs/content-flow.md
Per the discussion in slack with @Kern-- ; once he shared the info, let's capture it and make it broadly available.
> update documentation for content-flow

- releases/v1.6.34.toml
- version/version.go
----
Welcome to the v1.6.34 release of containerd!
The thirty-fourth patch release for containerd 1.6 contains various fixes
and updates.
* Remove overlayfs volatile option on temp mounts ([#10333](https://github.com/containerd/containerd/pull/10333))
* Update runc binary to v1.1.13 ([#10335](https://github.com/containerd/containerd/pull/10335))
* Handle empty DNSConfig differently than unspecified ([#10463](https://github.com/containerd/containerd/pull/10463))
* Fix HPC working directory in pkg/cri/server code ([#10361](https://github.com/containerd/containerd/pull/10361))
* Support for dropping inheritable capabilities ([#10470](https://github.com/containerd/containerd/pull/10470)) …
> Prepare release notes for v1.6.34

- releases/v1.7.20.toml
- version/version.go
----
Welcome to the v1.7.20 release of containerd!
The twentieth patch release for containerd 1.7 contains various fixes
and updates.
* Support for dropping inheritable capabilities ([#10469](https://github.com/containerd/containerd/pull/10469))
* Make PodSandboxStatus friendlier to shim crashes ([#10461](https://github.com/containerd/containerd/pull/10461))
* Handle empty DNSConfig differently than unspecified ([#10462](https://github.com/containerd/containerd/pull/10462))
* Fix for `[cri] ttrpc: closed` during ListPodSandboxStats ([#10423](https://github.com/containerd/containerd/pull/10423))
* Akihiro Suda
* Phil Estes
* Akhil Mohan
* Bryant …
> Prepare release notes for v1.7.20

- client/client.go
- cmd/ctr/commands/images/export.go
- core/images/archive/importer.go
- internal/nri/container.go
- pkg/oci/spec_opts.go
There's a couple spots where we know exactly how large the destination buffer should be, so pre-size these to avoid any reallocs to a higher capacity.
> Avoid potential reallocs by pre-sizing some slices

- core/snapshots/storage/metastore.go
The ParentIDs array in the Snapshot type is populated in the reverse order i.e the immediate parent is at the 0th index and the oldest parent is at the last index. It can be seen here:
https://github.com/containerd/containerd/blob/main/core/snapshots/storage/bolt.go#L492 When applying these layers, the parent layer at the last index should be applied first and the parent layer at the 0th index should be applied last. However, the comment above the Snapshot type says the exact opposite thing.  This commit fixes that comment.
> Fix incorrect comment about ordering of parent layers

- cio/io.go
- cio/io_unix.go
- cio/io_windows.go
Windows requires that stderr is an empty string when running a container with TTY. In Containerd, [pkg/cio/io.go#L298:L302](https://github.com/containerd/containerd/blob/4a18adcfca4e37e829c0d3174bd04d4cbf222f9a/pkg/cio/io.go#L298:L302), the Stderr is set to a value, e.g.
```go
res = "binary:///C:/_xxx_/nerdctl.exe?_NERDCTL_INTERNAL_LOGGING=C%3A%5CProgramData%5Cnerdctl%5C052055e3"
``` 
which causes microsoft/hcsshim [service_internal.go#L127](https://github.com/microsoft/hcsshim/blob/8beabacfc2d21767a07c20f8dd5f9f3932dbf305/cmd/containerd-shim-runhcs-v1/service_internal.go#L127) to fail to create a new task.
To address this issue, we refactor `TerminalLogURI()` and `TerminalBinaryIO` functions by adding an optional parameter that specifies whether stderr should be set to an empty string …
> [release/1.7] [Windows] Set stderr to empty string when using terminal on Windows.

- cio/io.go
- cio/io_unix.go
- cio/io_windows.go
Windows requires that stderr is an empty string when running a container with TTY. In Containerd, [pkg/cio/io.go#L298:L302](https://github.com/containerd/containerd/blob/4a18adcfca4e37e829c0d3174bd04d4cbf222f9a/pkg/cio/io.go#L298:L302), the Stderr is set to a value, e.g.
```go
res = "binary:///C:/_xxx_/nerdctl.exe?_NERDCTL_INTERNAL_LOGGING=C%3A%5CProgramData%5Cnerdctl%5C052055e3"
``` 
which causes microsoft/hcsshim [service_internal.go#L127](https://github.com/microsoft/hcsshim/blob/8beabacfc2d21767a07c20f8dd5f9f3932dbf305/cmd/containerd-shim-runhcs-v1/service_internal.go#L127) to fail to create a new task.
To address this issue, we refactor `TerminalLogURI()` and `TerminalBinaryIO` functions by adding an optional parameter that specifies whether stderr should be set to an empty string …
> [release/1.6] [Windows] Set stderr to empty string when using terminal on Windows

- plugins/services/introspection/local.go
The /var/lib/containerd/io.containerd.grpc.v1.introspection/uuid file stores a UUID to identify the particular containerd daemon responding to requests.  The file should either exist with a UUID, or not exist. However, it has been observed that the file can be truncated with 0 bytes, which will then fail to be parsed as a valid UUID.
As a defensive practice, detect a 0-length file and overwrite with a new UUID rather than failing.
Fixes: https://github.com/containerd/containerd/issues/10491
> introspection: regenerate UUID if state is empty

- pkg/deprecation/deprecation.go
Some CRI config properties had removal postponed until v2.1 in https://github.com/containerd/containerd/pull/9966. Update the associated deprecation warnings to match the new removal version.
> deprecation: update warnings for CRI config fields

- pkg/oci/utils_unix.go
Issue:
https://github.com/containerd/containerd/issues/9857
With this fix, we have such new error message:
>time="2024-02-22T16:12:00.555149600Z" level=error msg="CreateContainer within sandbox "d23af3219cb27228623cf8168ec27e64e836ed44f2b2f9cf784f0529a7f92e1e" for &ContainerMetadata{Name:compute,Attempt:0,} failed" error="failed to generate container "c6c1877ec55219a3726c589dc280f6f79dbbeff3b21efa243bf96fb89481d04d" spec: failed to generate spec: get device path: /var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/publish/pvc-3c1b28fb-683e-4bf5-9869-c9107a0f1732/20291c6b-62c3-4456-be8a-fbeac118ec19 containerPath: /dev/disk-0 error: not a device node"
Added information like `/var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/publish/pvc-3c1b28fb-683e-4bf5-9869-c9107a0f1732/20291c …
> Add file name to device type check failure message

- pkg/deprecation/deprecation.go
Cherry-pick of https://github.com/containerd/containerd/pull/10509
Some CRI config properties had removal postponed until v2.1 in https://github.com/containerd/containerd/pull/9966. Update the associated deprecation warnings to match the new removal version.
(cherry picked from commit f9146c0516c7cd92814cfded33958f048b950c0e)
> [release/1.7] deprecation: update warnings for CRI config fields

- internal/cri/server/sandbox_stop.go
Similar to sandbox removal, the stop of a sandbox should be a noop if the sandbox has not been found.
Found during: https://github.com/kubernetes-sigs/cri-tools/pull/1535
> Make `StopPodSandbox` RPC idempotent

- internal/cri/server/container_stop.go
Similar to container removal, the stop of a container should be a noop if the container has not been found.
Found during: https://github.com/kubernetes-sigs/cri-tools/pull/1536
> Make `StopContainer` RPC idempotent

- client/task_opts.go
fix: https://github.com/containerd/containerd/issues/10441
Using a simpler way, tasks with a PID of 0 are treated as the special kind of tasks.
> client: fix tasks with PID 0 cannot be forced to delete

- cmd/containerd/server/server.go
**Issue:** https://github.com/containerd/containerd/issues/10502 (specifically [this comment](https://github.com/containerd/containerd/issues/10502#issuecomment-2251896725) about fixing the default state dir creation with expected perms 0711)
There are a couple directories that get created under the default
state directory ("/run/containerd") even when containerd is configured
to use a different location for its state directory. Create the default
state directory even if containerd is configured to use a different
state directory location. This ensure pkg/shim and pkg/fifo won't create
the default state directory with incorrect permissions when calling
os.MkdirAll for their respective subdirectories.
> Ensure /run/containerd gets created with correct perms

- pkg/cri/sbserver/container_stop.go
- pkg/cri/server/container_stop.go
Similar to container removal, the stop of a container should be a noop if the container has not been found.
Found during: https://github.com/kubernetes-sigs/cri-tools/pull/1536
Manual cherry-pick of #10521.
> [release/1.7]  Make `StopContainer` RPC idempotent

- pkg/cri/server/sandbox_stop.go
Similar to sandbox removal, the stop of a sandbox should be a noop if the sandbox has not been found.
Found during: https://github.com/kubernetes-sigs/cri-tools/pull/1535
(cherry picked from commit c6cea95d95a66afe14c465adc7c43f03565bf7ea)
Manual cherry-pick of https://github.com/containerd/containerd/pull/10520
> [release/1.6] Make `StopPodSandbox` RPC idempotent

- plugins/services/diff/local.go
- plugins/services/diff/service_unix.go
- plugins/services/diff/service_windows.go
this commit  https://github.com/containerd/containerd/pull/9401 just support for cri interface,I want a global config to pull with syncfs.
because ctr and nerdctl pull or load need this feature.
I think let diff plugin do this is better than cri .
@fuweid
> support to syncfs after pull by using diff plugin

- docs/content-flow.md
Just a minor thing I noticed when reading the docs, currently the end of the document is rendered as code.
> docs/content-flow: fix code fence delimiter

- script/setup/install-runc
- fixes https://github.com/containerd/containerd/issues/10553
- relates to https://github.com/opencontainers/runc/pull/4270
- relates to https://github.com/containerd/containerd/pull/10334
- relates to https://github.com/containerd/containerd/pull/10335
- relates to https://github.com/containerd/containerd/pull/10336
runc v1.1.13 introduced an option to customize the version (as printed by the `--version` flag) through a `VERSION` Make variable / environment variable (see [1]).
This variable collided with the `VERSION` environment variable used by containerd for the same purpose, which lead to `runc` binaries built using the version of containerd;
runc --version
runc version 1.7.20
commit: v1.1.13-0-g58aa9203
...
This patch explicitly sets the `VERSION` variable to the version of runc …
> script/setup/install-runc: fix runc using incorrect version

- pkg/cri/server/container_create_windows.go
This reverts commit 086e1f56e446740466b113a04f201e2040ae5a22 because HPCs in containerd/release/1.6 use Job objects and do not expect the default working directory to be `C:\hpc`.
> [release/1.6] Revert "[release/1.7]: HPC working directory fix in pkg/cri/server code"

- script/setup/install-runc
- backport https://github.com/containerd/containerd/pull/10556
- fixes https://github.com/containerd/containerd/issues/10553
runc v1.1.13 introduced an option to customize the version (as printed by the `--version` flag) through a `VERSION` Make variable / environment variable (see [1]).
This variable collided with the `VERSION` environment variable used by containerd for the same purpose, which lead to `runc` binaries built using the version of containerd;
runc --version
runc version 1.7.20
commit: v1.1.13-0-g58aa9203
...
This patch unsets the `VERSION` variable to bring prevent it from being inherited and to bring back the previous behavior.
Before this patch:
docker build -t containerd-test -f contrib/Dockerfile.test .
docker run -it --rm --env VERSION=1.7.20 containerd-test sh -c …
> [release/1.7 backport] script/setup/install-runc: fix runc using incorrect version

- script/setup/install-runc
- backport https://github.com/containerd/containerd/pull/10556
- fixes https://github.com/containerd/containerd/issues/10553
runc v1.1.13 introduced an option to customize the version (as printed by the `--version` flag) through a `VERSION` Make variable / environment variable (see [1]).
This variable collided with the `VERSION` environment variable used by containerd for the same purpose, which lead to `runc` binaries built using the version of containerd;
runc --version
runc version 1.7.20
commit: v1.1.13-0-g58aa9203
...
This patch unsets the `VERSION` variable to bring prevent it from being inherited and to bring back the previous behavior.
Before this patch:
docker build -t containerd-test -f contrib/Dockerfile.test .
docker run -it --rm --env VERSION=1.7.20 containerd-test sh -c …
> [release/1.6 backport] script/setup/install-runc: fix runc using incorrect version

- pkg/process/io_test.go
This PR ignores a new pidfd file descriptor that is introduced in gotip (future 1.23) and should not be considered when detecting fd leaks.
Fixes #10345
(cherry picked from commit f0aecaa2e2a28e3950a2afac1c6b45b2d9543462)
Cherry pick https://github.com/containerd/containerd/pull/10346
> [release/1.6] Fix TestNewBinaryIOCleanup failing with gotip

- pkg/process/io_test.go
This PR ignores a new pidfd file descriptor that is introduced in gotip (future 1.23) and should not be considered when detecting fd leaks.
Fixes #10345
(cherry picked from commit f0aecaa2e2a28e3950a2afac1c6b45b2d9543462)
Cherry pick #10346
> [release/1.7] Fix TestNewBinaryIOCleanup failing with gotip

- releases/v1.6.35.toml
- version/version.go
----
Welcome to the v1.6.35 release of containerd!
The thirty-fifth patch release for containerd 1.6 contains various fixes
and updates.
* deprecation: update warnings for CRI config fields ([#10525](https://github.com/containerd/containerd/pull/10525))
* Phil Estes
* Samuel Karp
* Kazuyoshi Kato
* Sascha Grunert
* Akihiro Suda
* Erikson Tung
* Iceber Gu
* Mauri de Souza Meneguzzo
* TinaMor
* Wei Fu
* rongfu.leng
<details><summary>23 commits</summary>
<p>
* [`849650ab7`](https://github.com/containerd/containerd/commit/849650ab7268ae16d659492d6f942eaca67ecbd3) Prepare release notes for v1.6.35
* Fix …
> [release/1.6] Prepare release notes for v1.6.35

- cmd/containerd-shim-runc-v2/process/io_test.go
When running the test on Ubuntu focal (kernel version 5.4), the symlink for pidfd is anon_inode:[pidfd].
Updates: #10345
> Fix TestNewBinaryIOCleanup on Go 1.23 and Linux 5.4

- client/client.go
- client/container.go
- client/process.go
- client/task.go
- core/metadata/containers.go
- core/metadata/sandbox.go
- internal/cri/instrument/instrumented_service.go
- internal/cri/server/container_attach.go
- internal/cri/server/container_create.go
- internal/cri/server/container_exec.go
- internal/cri/server/container_execsync.go
- internal/cri/server/container_remove.go
- internal/cri/server/container_start.go
- internal/cri/server/container_stop.go
- internal/cri/server/images/image_status.go
- internal/cri/server/sandbox_remove.go
- internal/cri/server/sandbox_run.go
- internal/cri/server/sandbox_stop.go
- pkg/tracing/tracing.go
Rebased from main.
Most of the conflicts were resolved by replacing import from "github.com/containerd/containerd/tracing" with "github.com/containerd/containerd/v2/pkg/tracing". Also manually added the changes to internal/cri/instrument/instrumented_service.go` since the file location has now changed.
---
Rev 2
* Addressing this [comment](https://github.com/containerd/containerd/pull/7616#discussion_r1051198511) about adding additional spans at the instrumented service layer. Instead of creating a new span, we can simply use the span created at the gRPC layer and add additional attributes to it. Instrumented service is anyways a thin layer that does not require a new span of its own. Instead we capture and record the error in the parent span itself.
* Similar to Runtime APIs, we will …
> Add tracing spans to CRI runtime service apis

- .devcontainer/devcontainer.json
- .github/actions/install-go/action.yml
- .github/workflows/api-release.yml
- .github/workflows/ci.yml
- .github/workflows/release.yml
- Vagrantfile
- contrib/Dockerfile.test
- contrib/fuzz/oss_fuzz_build.sh
- script/setup/prepare_env_windows.ps1
- https://github.com/golang/go/issues?q=milestone%3AGo1.22.6+label%3ACherryPickApproved
- full diff: https://github.com/golang/go/compare/go1.22.5...go1.22.6
go1.22.6 (released 2024-08-06) includes fixes to the go command, the compiler, the linker, the trace command, the covdata command, and the bytes, go/types, and os/exec packages. See the Go 1.22.6 milestone on our issue tracker for details.
> update to go1.22.6

- .github/actions/install-go/action.yml
- .github/workflows/ci.yml
- .github/workflows/release.yml
- Vagrantfile
- contrib/Dockerfile.test
- script/setup/prepare_env_windows.ps1
- https://github.com/golang/go/issues?q=milestone%3AGo1.22.6+label%3ACherryPickApproved
- full diff: https://github.com/golang/go/compare/go1.22.5...go1.22.6
go1.22.6 (released 2024-08-06) includes fixes to the go command, the compiler, the linker, the trace command, the covdata command, and the bytes, go/types, and os/exec packages. See the Go 1.22.6 milestone on our issue tracker for details.
go1.21.13 (released 2024-08-06) includes fixes to the go command, the covdata command, and the bytes package. See the Go 1.21.13 milestone on our issue tracker for details.
(cherry picked from commit 228914a5e533db62f2637267c26b0093b6e8625e)
NOTE: not a clean cherry-pick
> [release/1.6] update to go1.21.13 / go1.22.6

- pkg/cri/instrument/instrumented_service.go
- pkg/cri/server/service_test.go
This helps gather more accurate API usage data that informs efforts on how to safely migrate containerd clients to 2.0.
/cc @samuelkarp @tallclair 
Tested manually on workstation.
```shell
15:28:17 $ sudo bin/ctr -a /tmp/containerd.sock deprecations list --format=json
15:29:13 $ go run main.go
15:29:52 $ sudo bin/ctr -a /tmp/containerd.sock deprecations list --format=json
[
{
"id": "io.containerd.deprecation/cri-api-v1alpha2",
"message": "CRI API v1alpha2 is deprecated since containerd v1.7 and removed in containerd v2.0. Use CRI API v1 instead.",
"lastOccurrence": "2024-08-09T22:29:15.605544912Z"
}
]
15:30:38 $ go run main.go
15:31:02 $ sudo bin/ctr -a /tmp/containerd.sock deprecations list --format=json
[
{
"id": "io.containerd.deprecation/cri-api-v1alpha2",
"message": "CRI API v1alpha2 …
```
> [release/1.7] Ensure the CRIAPIV1Alpha2 warning's lastOccurrence is accurate

- cmd/containerd/command/config.go
- cmd/containerd/command/main.go
- cmd/containerd/command/publish.go
- cmd/ctr/commands/client.go
The `Context` struct from `urfave/cli` nests the `context.Context` struct. We should pass that context object as the parameter instead of instantiating a new one
> use ctx object from cliContext instead of a creating a new one

- cmd/ctr/commands/shim/shim.go
`shim state` is useful for querying the state of a shim, but:
* non-primary tasks cannot be queried for shims that have grouping enabled
* the new `containerd.task.v3.Task` is not supported by old shims
These two commits make it possible to do this:
```
$ sudo ./ctr -n k8s.io shim --id 3b550a5e0de89fa884b3ff67c20e25fbf7c27ec993573396bc311d2d410b4679 state -t 202761c5d8438602627f6ef90919950601c43695684166ee6168937a014f935d --api-version 2
{
"id": "202761c5d8438602627f6ef90919950601c43695684166ee6168937a014f935d",
"bundle": "/run/containerd/io.containerd.runtime.v2.task/k8s.io/202761c5d8438602627f6ef90919950601c43695684166ee6168937a014f935d",
"pid": 57518,
"status": 2,
"stdout": "/run/containerd/io.containerd.grpc.v1.cri/containers/202761c5d8438602627f6ef90919950601c43695684166ee6168937a014f …
```
> ctr: shim state for secondary tasks & shim state query for old shims

- pkg/cri/server/instrumented_service.go
- pkg/cri/server/service_test.go
This helps gather more accurate API usage data that informs efforts on how to safely migrate containerd clients to 2.0.
This is a chery-pick of #10571.
/cc @samuelkarp @tallclair
/hold
Waiting on 1.7 PR to be merged first.
> [release/1.6] Ensure the CRIAPIV1Alpha2 warning's lastOccurrence is accurate

- pkg/process/io_test.go
When running the test on Ubuntu focal (kernel version 5.4), the symlink for pidfd is anon_inode:[pidfd].
Updates: #10345, #10555
(cherry picked from commit 8ef73c5dd50e89a7c2fdb92343e11be77660510a)
Backport #10562
> [release/1.6] Fix TestNewBinaryIOCleanup on Go 1.23 and Linux 5.4

- pkg/process/io_test.go
When running the test on Ubuntu focal (kernel version 5.4), the symlink for pidfd is anon_inode:[pidfd].
Updates: #10345, #10554
(cherry picked from commit 8ef73c5dd50e89a7c2fdb92343e11be77660510a)
Backport #10562
> [release/1.7] Fix TestNewBinaryIOCleanup on Go 1.23 and Linux 5.4

- .devcontainer/devcontainer.json
- .github/actions/install-go/action.yml
- .github/workflows/api-release.yml
- .github/workflows/ci.yml
- .github/workflows/release.yml
- Vagrantfile
- contrib/Dockerfile.test
- contrib/fuzz/oss_fuzz_build.sh
- core/remotes/docker/fetcher_test.go
- integration/client/container_linux_test.go
- internal/cleanup/context_test.go
- internal/cri/server/container_checkpoint_linux.go
- pkg/filters/parser.go
- plugins/services/content/contentserver/contentserver.go
- script/setup/prepare_env_windows.ps1
- add go1.23.0 to build and test matrix
- fix lint errors reported due to https://github.com/golang/go/issues/60529
> Add go 1.23.0

- .github/actions/install-go/action.yml
- .github/workflows/api-release.yml
- .github/workflows/ci.yml
- .github/workflows/release.yml
- BUILDING.md
- Vagrantfile
- contrib/Dockerfile.test
- contrib/fuzz/oss_fuzz_build.sh
- go.mod
- integration/client/go.mod
- script/setup/prepare_env_windows.ps1
- add go1.23.0, drop go1.21.x
- update golangci-lint to 1.60.1
Release binaries will be now built with go1.22.6
> [release/1.7] add go1.23.0, drop go1.21.x

- script/setup/install-dev-tools
- relates to https://github.com/containerd/containerd/pull/10338
The current version was updated in 65031eadec262d783db25456a8bbca1eed1956b7,
and looks to be
- 1 commit ahead of v1.2.3; https://github.com/containerd/ttrpc/compare/v1.2.3...faba5896a9c4d7b65495cb9b2c02531feb1434d6
- slightly behind of v1.2.4; https://github.com/containerd/ttrpc/compare/faba5896a9c4d7b65495cb9b2c02531feb1434d6...v1.2.4
This patch upstreas it to the current (v1.2.5) version, aligning it with
the version used in `go.mod`;
https://github.com/containerd/ttrpc/compare/faba5896a9c4d7b65495cb9b2c02531feb1434d6...v1.2.5
The OpenSSF scorecard is complaining about these two dependencies being
installed without a patch version specified;
Warn: goCommand not pinned by hash: script/setup/install-dev-tools:27
Warn: …
> script/setup/install-dev-tools: update protoc-gen-go-ttrpc to v1.2.5, specify patch versions

- RELEASES.md
add k8s 1.31 to the supported version for containerd. 
NOTES:
- containerd 1.7.20+ is added since it is tested as part of release-branch-jobs [here](https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes/sig-release/release-branch-jobs/1.31.yaml#L772)
- the corresponding version in 1.6 series is also used for the LTS version
> docs: add k8s 1.31 to support matrix

- README.md
This PR adds OpenSSF Scorecard Badge in the README file.
Hi, I'm Harshita. I’m working with [CNCF and the Google Open Source Security Team for the GSoC 2024 term](https://github.com/cncf/mentoring/issues/1196). We are collaborating to enhance security practices across various CNCF projects. The goal is to improve security for all CNCF projects by both using OpenSSF Scorecards and implementing its security improvements.
The project already has the Scorecard GitHub Action running, so adding the scorecard badge would be quite handy. So that the results can be shown as a badge in the repository's README. This badge serves as a quick indicator of the project's security posture, helping users and contributors evaluate the project's security practices quickly.
> Added the OpenSSF Scorecard Badge

- go.mod
- integration/client/go.mod
- relates to https://github.com/containerd/containerd/pull/10596#discussion_r1721294997
Commit 3b263d082cb09a2911150135a760508527557a0e updated the version of Go used to build containerd to go1.22, but also updated the version in go.mod.
As there's currently not a requirement for go1.22, we can keep this at the minimum required version, and revert it to go1.21.
> [release/1.7] go.mod: keep minimum go version at go1.21

- cmd/containerd/builtins/builtins.go
- cmd/containerd/server/server.go
- integration/build_local_containerd_helper_test.go
- plugins/content/local/plugin/plugin.go
Update the local content plugin to register itself in a consistent way as other plugins. This also allows the separate package to define its own configuration more cleanly.
Not sure why this one didn't get updated with the other plugins. We will want the local content plugin to have its own configuration for verity though, it will be cleaner in its own package like everything else.
> Register local content plugin from separate package

- releases/v1.7.21.toml
- version/version.go
---
Welcome to the v1.7.21 release of containerd!
The twenty-first patch release for containerd 1.7 contains various fixes
and updates.
* Fix failed force deletion for tasks with PID 0 ([#10523](https://github.com/containerd/containerd/pull/10523))
* Regenerate introspection UUID if state is empty ([#10510](https://github.com/containerd/containerd/pull/10510))
* Set stderr to empty string when using terminal on Windows. ([#10499](https://github.com/containerd/containerd/pull/10499))
* Move builds to Go 1.22 and add support for testing with 1.23 ([#10596](https://github.com/containerd/containerd/pull/10596))
* Borrow latest wsstream from k8s v1.31.x to 1.7 ([#10575](https://github.com/containerd/containerd/pull/10575))
* Ensure the CRIAPIV1Alpha2 warning's lastOccurrence is …
> [release/1.7] Prepare release notes for v1.7.21

- .github/workflows/release.yml
#10504
Added attestation step using https://github.com/actions/attest-build-provenance/
But I'm unable to test it because of token privileges.
> Generate attestation for artifacts during release

- .mailmap
- go.mod
- go.sum
- vendor/github.com/containerd/containerd/api/LICENSE
- vendor/modules.txt
- version/version.go
----
Welcome to the v2.0.0-rc.4 release of containerd!  
* Add Update API for sandbox controller ([#9903](https://github.com/containerd/containerd/pull/9903))
* Preserve Unprivileged locked flags during remount of bind mounts …
> Prepare release notes for  v2.0.0-rc.4

- pkg/gc/gc.go
- pkg/gc/gc_test.go
If a node can be reached by, e.g., 100 nodes, then it will be added to `grays` 100 times (and `refs` will be called 100 times for this node). This PR avoids this by **pre-marking** a node as non-white right after it's added to `grays`.
My understanding from the code is we can/should avoid such duplications in `grays` (and duplicated `refs(node)` calls within a `Tricolor` call).
1. `Tricolor` is single-thread GC, and only called once by `DB.getMarked`
https://github.com/containerd/containerd/blob/4cfeb7b19ea3127a936048705b2ed3cda2d7f13d/core/metadata/db.go#L516
2. `getMarked` is only called once by `DB.GarbageCollect` which holds a write lock to `DB`: https://github.com/containerd/containerd/blob/4cfeb7b19ea3127a936048705b2ed3cda2d7f13d/core/metadata/db.go#L372-L376
3. So there should be …
> Improve gc tricolor by avoiding revisiting nodes

- internal/cri/server/container_stats_list.go
- internal/cri/server/container_stats_list_test.go
During removal of the container a stat value might be reported as zero; in this case the calculation could end up with an extremely large number.  If the cumulative stat decreases report zero.
fixes https://github.com/kubernetes/kubernetes/issues/114057
> Cumulative stats can't decrease

- .github/actions/install-go/action.yml
- .github/workflows/ci.yml
- .github/workflows/release.yml
- BUILDING.md
- Vagrantfile
- contrib/Dockerfile.test
- script/setup/install-dev-tools
- script/setup/prepare_env_windows.ps1
- add go1.23.0 to testing matrix and move builds and releases to go1.22.6
- update golangci-lint to 1.60.1
Release binaries will be now built with go1.22.6
> [release/1.6] move builds to go1.22 and testing to go1.23

- plugins/services/containers/local.go
- plugins/services/events/service.go
- plugins/services/events/ttrpc.go
- plugins/services/images/local.go
- plugins/services/leases/service.go
- plugins/services/namespaces/local.go
- plugins/services/transfer/service.go
Some services create a new `ptypes.Empty` pointer for every request. An improvement is to pre-define a pointer var and reuse the same one, which should reduce some heap allocation/gc/etc.
The pattern is already used in some other services; this PR just makes it consistent in all services.
https://github.com/containerd/containerd/blob/300fd770a019f09d65622b006a234a995870c0d3/plugins/services/tasks/local.go#L64
https://github.com/containerd/containerd/blob/2ac2b9c909fb64f4d06958a0ca2f556bec348d05/plugins/services/snapshots/service.go#L46
https://github.com/containerd/containerd/blob/300fd770a019f09d65622b006a234a995870c0d3/plugins/services/content/contentserver/contentserver.go#L44
> Avoid repeated ptypes.Empty creation by predefining it as a var

- pkg/cri/sbserver/container_stats_list.go
- pkg/cri/sbserver/container_stats_list_test.go
- pkg/cri/server/container_stats_list.go
- pkg/cri/server/container_stats_list_test.go
cherry-pick of f6677a4ec53f95f22529f7225f0de741b9201df1
> [release/1.7] Cumulative stats can't decrease

- core/sandbox/proxy/controller.go
- plugins/sandbox/controller.go
- plugins/services/images/helpers.go
- plugins/services/images/local.go
- plugins/services/sandbox/controller_service.go
The sandbox <-> proto conversions functions already exists at
https://github.com/containerd/containerd/blob/26d6fd0c3fe505ad3bb1525c4514ef21c19c24d4/core/sandbox/helpers.go#L27
Also removed a duplicated desc <-> proto conversion functions in a separate commit.
> Remove duplicated sandbox <-> proto conversion functions

- cmd/containerd-shim-runc-v2/task/service.go
Based off of https://github.com/containerd/containerd/pull/10647 and https://github.com/containerd/containerd/pull/10634 (and with inspiration from https://github.com/containerd/containerd/pull/10650), replaced `s.pendingExecs` with `s.runningExecs`. The logic is changed to keep track of running execs instead of pending execs, and handling a pending/prestarted exec the same as a running exec, which significantly simplifies the shim exit processing logic.
closes https://github.com/containerd/containerd/issues/10589
-------------------------
This PR rewrites and simplifies a lot of the shim exit processing logic to reduce it's complexity, and also handle the case where the container doesn't have it's own pid-namespace, which means that we're not guaranteed to receive the init exit last. …
> runc-shim: fix races/prevent init exits from being dropped

- integration/client/container_linux_test.go
- integration/failpoint/cmd/runc-fp/delayexec.go
- integration/failpoint/cmd/runc-fp/main.go
- integration/failpoint/const.go
- pkg/fifosync/fifo_unix.go
This issue was caused by a race between init exits and new exec process tracking inside the shim. The test operates by controlling the time between when the shim invokes "runc exec" and when the actual "runc exec" is triggered. This allows validating that races for shim state tracking between pre- and post-start of the exec process do not exist.
Relates to https://github.com/containerd/containerd/issues/10589
Marked as WIP until the fix is merged.
/cc @laurazard @corhere
> integration: regression test for issue 10589

- .github/actions/install-go/action.yml
- .github/workflows/ci.yml
- .github/workflows/release.yml
- Vagrantfile
- contrib/Dockerfile.test
- script/setup/prepare_env_windows.ps1
- https://github.com/golang/go/issues?q=milestone%3AGo1.27.7+label%3ACherryPickApproved
- full diff: https://github.com/golang/go/compare/go1.22.6...go1.22.7
- go/parser: stack exhaustion in all Parse* functions
Calling any of the Parse functions on Go source code which contains
deeply nested literals can cause a panic due to stack exhaustion.
This is CVE-2024-34155 and Go issue https://go.dev/issue/69138.
- encoding/gob: stack exhaustion in Decoder.Decode
Calling Decoder.Decode on a message which contains deeply nested
structures can cause a panic due to stack exhaustion.
This is a follow-up to CVE-2022-30635.
Thanks to Md Sakib Anwar of The Ohio State University for reporting
this issue.
This is CVE-2024-34156 …
> [release/1.6] update to go1.22.7, go1.23.1

- .github/actions/install-go/action.yml
- .github/workflows/api-release.yml
- .github/workflows/ci.yml
- .github/workflows/release.yml
- Vagrantfile
- contrib/Dockerfile.test
- contrib/fuzz/oss_fuzz_build.sh
- script/setup/prepare_env_windows.ps1
- https://github.com/golang/go/issues?q=milestone%3AGo1.27.7+label%3ACherryPickApproved
- full diff: https://github.com/golang/go/compare/go1.22.6...go1.22.7
- go/parser: stack exhaustion in all Parse* functions
Calling any of the Parse functions on Go source code which contains
deeply nested literals can cause a panic due to stack exhaustion.
This is CVE-2024-34155 and Go issue https://go.dev/issue/69138.
- encoding/gob: stack exhaustion in Decoder.Decode
Calling Decoder.Decode on a message which contains deeply nested
structures can cause a panic due to stack exhaustion.
This is a follow-up to CVE-2022-30635.
Thanks to Md Sakib Anwar of The Ohio State University for reporting
this issue.
This is CVE-2024-34156 …
> [release/1.7] update to go1.22.7, go1.23.1

- integration/client/container_linux_test.go
- integration/failpoint/cmd/runc-fp/delayexec.go
- integration/failpoint/cmd/runc-fp/main.go
- integration/failpoint/const.go
- pkg/fifosync/fifo_unix.go
Manual cherry-pick of https://github.com/containerd/containerd/pull/10649
This issue was caused by a race between init exits and new exec process tracking inside the shim. The test operates by controlling the time between when the shim invokes "runc exec" and when the actual "runc exec" is triggered. This allows validating that races for shim state tracking between pre- and post-start of the exec process do not exist.
Relates to https://github.com/containerd/containerd/issues/10589
/cc @laurazard @corhere
> [release/1.7] integration: regression test for issue 10589

- integration/client/container_linux_test.go
- integration/failpoint/cmd/runc-fp/delayexec.go
- integration/failpoint/cmd/runc-fp/main.go
- integration/failpoint/const.go
- pkg/fifosync/fifo_unix.go
Manual cherry-pick of https://github.com/containerd/containerd/pull/10649
This issue was caused by a race between init exits and new exec process tracking inside the shim. The test operates by controlling the time between when the shim invokes "runc exec" and when the actual "runc exec" is triggered. This allows validating that races for shim state tracking between pre- and post-start of the exec process do not exist.
Relates to https://github.com/containerd/containerd/issues/10589
/cc @laurazard
> [release/1.6] integration: regression test for issue 10589

- .devcontainer/devcontainer.json
- .github/actions/install-go/action.yml
- .github/workflows/api-release.yml
- .github/workflows/ci.yml
- .github/workflows/release.yml
- Vagrantfile
- contrib/Dockerfile.test
- contrib/fuzz/oss_fuzz_build.sh
- script/setup/prepare_env_windows.ps1
- https://github.com/golang/go/issues?q=milestone%3AGo1.23.1+label%3ACherryPickApproved
- full diff: https://github.com/golang/go/compare/go1.23.0...go1.23.1
- go/parser: stack exhaustion in all Parse* functions
Calling any of the Parse functions on Go source code which contains
deeply nested literals can cause a panic due to stack exhaustion.
This is CVE-2024-34155 and Go issue https://go.dev/issue/69138.
- encoding/gob: stack exhaustion in Decoder.Decode
Calling Decoder.Decode on a message which contains deeply nested
structures can cause a panic due to stack exhaustion.
This is a follow-up to CVE-2022-30635.
Thanks to Md Sakib Anwar of The Ohio State University for reporting
this issue.
This is CVE-2024-34156 …
> update to go1.23.1, go1.22.7

- releases/v1.6.36.toml
- version/version.go
containerd 1.6.36
Welcome to the v1.6.36 release of containerd!
The thirty-sixth patch release for containerd 1.6 contains various fixes
and updates.
* Ensure the CRIAPIV1Alpha2 warning's lastOccurrence is accurate ([#10582](https://github.com/containerd/containerd/pull/10582))
* Update to go1.22.7, go1.23.1 ([#10680](https://github.com/containerd/containerd/pull/10680))
* Cumulative stats can't decrease ([#10671](https://github.com/containerd/containerd/pull/10671))
* Fix memory leak with `kubectl exec` >= 1.30.0 ([#10574](https://github.com/containerd/containerd/pull/10574))
* Fix bug where init exits were being dropped ([#10676](https://github.com/containerd/containerd/pull/10676))
* Update runc binary to 1.1.14 ([#10667](https://github.com/containerd/containerd/pull/10667))
* Ensure …
> Prepare release notes for v1.6.36

- releases/v1.7.22.toml
- version/version.go
containerd 1.7.22
Welcome to the v1.7.22 release of containerd!
The twenty-second patch release for containerd 1.7 contains various fixes
and updates.
* Update to go1.22.7, go1.23.1 ([#10679](https://github.com/containerd/containerd/pull/10679))
* Cumulative stats can't decrease ([#10670](https://github.com/containerd/containerd/pull/10670))
* Fix bug where init exits were being dropped ([#10675](https://github.com/containerd/containerd/pull/10675))
* Update runc binary to 1.1.14 ([#10668](https://github.com/containerd/containerd/pull/10668))
* Samuel Karp
* James Sturtevant
* Laura Brehm
* Akhil Mohan
* Akihiro Suda
* Cory Snider …
> Prepare release notes for v1.7.22

- internal/cri/opts/spec_opts.go
- internal/cri/server/podsandbox/helpers_linux.go
- internal/cri/server/podsandbox/sandbox_run.go
- internal/cri/server/podsandbox/sandbox_run_linux.go
- internal/cri/server/podsandbox/sandbox_run_linux_test.go
- internal/cri/server/podsandbox/sandbox_run_other_test.go
- internal/cri/server/podsandbox/sandbox_run_test.go
- internal/cri/server/podsandbox/sandbox_run_windows_test.go
- internal/cri/server/sandbox_run.go
- internal/cri/server/sandbox_run_linux.go
- internal/cri/server/sandbox_run_other.go
- internal/cri/server/sandbox_run_windows.go
- pkg/sys/namespace_linux.go
- pkg/sys/namespace_linux_test.go
- pkg/sys/unshare_linux.go
- pkg/sys/unshare_linux_test.go
For pod-level user namespaces, it's impossible to force the container runtime
to join an existing network namespace after creating a new user namespace.
According to the capabilities section in [user_namespaces(7)][1], a network
namespace created by containerd is owned by the root user namespace. When the
container runtime (like runc or crun) creates a new user namespace, it becomes
a child of the root user namespace. Processes within this child user namespace
are not permitted to access resources owned by the parent user namespace.
If the network namespace is not owned by the new user namespace, the container
runtime will fail to mount /sys due to the [sysfs: Restrict mounting sysfs][2]
patch.
Referencing the [cap_capable][3] function in Linux, a process can access a
resource if:
* The …
> internal/cri: simplify netns setup with pinned userns

- client/container_opts_unix.go
- client/snapshotter_opts_unix.go
- cmd/ctr/commands/run/run_unix.go
- integration/client/container_linux_test.go
- internal/userns/idmap.go
- internal/userns/idmap_test.go
Enhance user namespace implementation to support multi-entry uid/gid mappings.
This is 1st patch (out of 2) that supports multiple entries of uid/gid configurations. This patch focuses on the "slow" path that requires `chown` on every file in the root FS. uidmapped mounts implementation will be covered in a separate PR.
This implementation has changes in the following area:
1. Ported the `IdentityMapping` implementation from `idtools` package in Moby.
2. Added a few container opt funcs to take multiple uid/gid mappings.
3. Allowing multiple `--uidmap, --gidmap` options in `ctr run` command.
4. Fixed a bug where special file permissions like setuid, setgid or sticky bits are lost during `chown`
An sample command to run a container with remapped `foo` user:
```
ctr run --uidmap …
```
> Support multiple uid/gid mappings [1/2]

- internal/cri/server/container_create.go
#5002 image annotation can helpful for debugging and auditing the workload. However, when an image has multiple tags, the image originally obtained may not be the one actually specified by the user. Starting from cri-api v0.28.0, a UserSpecifiedImage field is added to ImageSpec. It is more appropriate to use UserSpecifiedImage.
> [cri] use 'UserSpecifiedImage' to set the image-name annotation

- version/version.go
Generated release notes. This will not be the last RC, we need at least one more after https://github.com/containerd/errdefs/pull/19
Full diff at https://gist.github.com/dmcgowan/68f63519848bb0838623f6edf4e8ee28
----
Welcome to the v2.0.0-rc.5 release of containerd!  
* Add Update API for …
> Prepare release notes for v2.0.0-rc.5

- core/unpack/unpacker.go
When an upstream client (e.g. kubelet) stops or restarts, the CRI connection to the containerd gets interrupted which is treated as a cancellation of context which subsequently cancels an ongoing operation, [including an image pull](https://github.com/containerd/containerd/blob/2ca3ff87255a4aa6b4244cb942033d45b6d44546/internal/cri/server/images/image_pull.go#L169). This generally gets followed by containerd's GC routine that tries to delete the prepared snapshots for the image layer(s) corresponding to the image in the pull operation that got cancelled. However, if the upstream client immediately retries (or starts a new) image pull operation, containerd initiates a new image pull and starts unpacking the image layers into snapshots. This may create a race condition: the GC routine …
> Fix the race condition during GC of snapshots when client retries

- script/setup/install-runc
This PR adds the trap statement in the install runc script to clean up the temporary files and ensure we are not leaving them.
> script/setup/install-runc: Add trap statement to clean up tmp files

- Makefile
- cmd/containerd-shim-runc-v2/main_tracing.go
- integration/failpoint/cmd/containerd-shim-runc-fp-v1/plugin_linux.go
- internal/pprof/plugin.go
- pkg/shim/shim.go
- pkg/tracing/plugin/ttrpc.go
- plugins/types.go
1. Makefile: shim tags so that adding `no_grpc` does not override other build tags
2. Move the shim pprof handler into a plugin and gate by the `shim_tracing` build tag (like we do the otel plugins)
3. Move the ttrpc otel interceptors into plugins so that we aren't directly importing the otelttrpc package even when we aren't building with shim_tracing.
On the plugin side, I figure there'd be some discussion on how to properly deal with plugin types/referencing in code.
This reduces the runc shim binary size to 7.1MB and RSS down to about 11.5MB.
> More shim imports cleanup

- unpacker.go
When an upstream client (e.g. kubelet) stops or restarts, the CRI connection to the containerd gets interrupted which is treated as a cancellation of context which subsequently cancels an ongoing operation, including an image pull. This generally gets followed by containerd's GC routine that tries to delete the prepared snapshots for the image layer(s) corresponding to the image in the pull operation that got cancelled. However, if the upstream client immediately retries (or starts a new) image pull operation, containerd initiates a new image pull and starts unpacking the image layers into snapshots. This may create a race condition: the GC routine (corresponding to the failed image pull operation) trying to clean up the same snapshot that the new image pull operation is preparing, thus …
> [release/1.6] Fix the race condition during GC of snapshots when client retries

- core/runtime/v2/shim.go
`boostrap.json` should be `bootstrap.json`
> core/runtime: Fix a typo in error message

- .github/workflows/ci.yml
* Backports https://github.com/containerd/containerd/pull/10781 to release/1.6 branch.
This change upgrades the runner images in CI to macOS 13. macOS 12 runners are being deprecated.
See https://github.com/actions/runner-images/issues/10721 for more information.
(cherry picked from commit 7b1809851348d33b0b06729aa50b82a343ea8c80)
> [release/1.6 backport] Update runner images to macOS13

- .github/workflows/ci.yml
* Backports https://github.com/containerd/containerd/pull/10781 to release/1.7
This change upgrades the runner images in CI to macOS 13. macOS 12 runners are being deprecated.
See https://github.com/actions/runner-images/issues/10721 for more information.
(cherry picked from commit 7b1809851348d33b0b06729aa50b82a343ea8c80)
> [release/1.7 backport] Update runner images to macOS13

- .devcontainer/devcontainer.json
- .github/actions/install-go/action.yml
- .github/workflows/api-release.yml
- .github/workflows/ci.yml
- .github/workflows/release.yml
- Vagrantfile
- contrib/Dockerfile.test
- contrib/fuzz/oss_fuzz_build.sh
- script/setup/prepare_env_windows.ps1
Update tooling to Go 1.23.2 and 1.22.8
> go1.23.2 (released 2024-10-01) includes fixes to the compiler, cgo, the runtime, and the maps, os, os/exec, time, and unique packages. See the [Go 1.23.2 milestone](https://github.com/golang/go/issues?q=milestone%3AGo1.23.2+label%3ACherryPickApproved) on our issue tracker for details.
- https://github.com/golang/go/issues?q=milestone%3AGo1.23.2+label%3ACherryPickApproved
- full diff: https://github.com/golang/go/compare/go1.23.1...go1.23.2
> go1.22.8 (released 2024-10-01) includes fixes to cgo, and the maps and syscall packages. See the [Go 1.22.8 milestone](https://github.com/golang/go/issues?q=milestone%3AGo1.22.8+label%3ACherryPickApproved) on our issue tracker for details.
- https://github.com/golang/go/issues?q=milestone%3AGo1.22.8+label%3ACher …
> update to go1.23.2,go1.22.8

- contrib/gce/configure.sh
- test/e2e_node/init.yaml
The pull-containerd-node-e2e-1-7-sandboxed job will set ENABLE_CRI_SANDBOXES for containerd 1.7 and enable us to validate that the sbserver backend works with e2e tests.
> [release/1.7] prow: allow ENABLE_CRI_SANDBOXES to be configured

- .github/actions/install-go/action.yml
- .github/workflows/ci.yml
- .github/workflows/release.yml
- Vagrantfile
- contrib/Dockerfile.test
- script/setup/prepare_env_windows.ps1
* Backports https://github.com/containerd/containerd/pull/10772
(cherry picked from commit 46f5a0d9392f13f5f1402f314e6246e692e64428)
> [release/1.6 backport] update to go1.23.2,go1.22.8

- .github/actions/install-go/action.yml
- .github/workflows/api-release.yml
- .github/workflows/ci.yml
- .github/workflows/release.yml
- Vagrantfile
- contrib/Dockerfile.test
- contrib/fuzz/oss_fuzz_build.sh
- script/setup/prepare_env_windows.ps1
* Backports https://github.com/containerd/containerd/pull/10772
(cherry picked from commit 46f5a0d9392f13f5f1402f314e6246e692e64428)
> [release/1.7 backport] update to go1.23.2,go1.22.8

- .github/workflows/ci.yml
fix: https://github.com/containerd/containerd/issues/10812
xref: https://github.com/golangci/golangci-lint-action/pull/1029
> [release/1.7] bump golangci/golangci-lint-action from 4 to 6

- .github/workflows/ci.yml
Informed that "the sponsored subscription from the CNCF and Ampere is running out at the end of the month."; testing a GH actions arm64 runner now that we have access via the CNCF enterprise plan.
> Switch from actuated.dev to GH Action runners for arm64

- .github/workflows/ci.yml
* Backports https://github.com/containerd/containerd/pull/9963 to 1.7
* Backports https://github.com/containerd/containerd/pull/10821 to 1.7
> [release/1.7 backport] Switch from actuated.dev to GH Action runners for arm64

- .github/workflows/ci.yml
* Backports https://github.com/containerd/containerd/pull/9963 to 1.6
* Backports https://github.com/containerd/containerd/pull/10821 to 1.6
> [release/1.6 backport] Switch from actuated.dev to GH Action runners for arm64

- releases/v1.7.23.toml
- version/version.go
----
Welcome to the v1.7.23 release of containerd!
The twenty-third patch release for containerd 1.7 contains various fixes
and updates.
* Add errdefs aliases ([#10792](https://github.com/containerd/containerd/pull/10792))
* Allow proxy plugins to have capabilities ([#10731](https://github.com/containerd/containerd/pull/10731))
* Revert errdefs package migration ([#10712](https://github.com/containerd/containerd/pull/10712))
* Add check for CNI plugins before tearing down pod network ([#10767](https://github.com/containerd/containerd/pull/10767))
* Fix the race condition during GC of snapshots when client retries ([#10763](https://github.com/containerd/containerd/pull/10763)) …
> [release/1.7] Prepare release notes for v1.7.23

- core/mount/mount_linux.go
This fixes #10704 . Big kudos to @mbaynton for reporting this issue with lot of details, nailing it down to containerd lines of code and showing all the log lines to understand the big picture of what was happening.
PR #5890 added code to unmount and delete the tmp directories for each layer of the overlayfs that is idmapped (idmap support for overlayfs needs to idmap each layer). The thing is, it was using os.RemoveAll() which will remove all recursively and not skipping it if the unmount failed. Therefore, if the unmount fails this is removing the rootfs of the container.
This PR just changes this to:
1. Do the mount detached: this means if the mount is busy (as reported in issue #10704), it will work just fine, make the mount unavailable for new accesses and the actual unmount is done …
> Fix data loss in rootfs overlayfs when unmount of tmp dirs fail with idmap mounts

- core/metrics/cgroups/v1/metrics.go
- core/metrics/cgroups/v2/metrics.go
This pr comes from not updating https://github.com/containerd/containerd/pull/9195.
Although this bug will only happen in 1.7, for the consistency of the code, the main will be updated first, and then cherry picked to 1.7
related pr for release/1.7: https://github.com/containerd/containerd/pull/10814
> metrics: Use UnmarshalTo instead of UnmarshalAny

- metrics/cgroups/v1/metrics.go
- metrics/cgroups/v2/metrics.go
This pr comes from not updating https://github.com/containerd/containerd/pull/9195, and it only works for release/1.7, it didn't have this problem in 1.6 on 2.x
---
Unmarshal `io.containerd.cgroups.v1.Metrics` with `UnmarshalAny` in 1.7+ (don't track which version it started with, but the latest version still has this issue) will first be parsed as [github.com/containerd/cgroups/stats/v1.Metrics](https://github.com/containerd/containerd/blob/923bb1f33d018b9c0cc8a2ef6c89f02517246e86/vendor/github.com/containerd/cgroups/stats/v1/metrics.pb.go#L705).
> If UnmarshalAny in a unit test it shouldn't have this problem because it's not importing the wrong Metrics
This is due to hcsshim causing the dependency to have both [github.com/containerd/cgroups/stats/v1/](https://github.com/containerd/contai …
> [release/1.7] metrics: Use UnmarshalTo instead of UnmarshalAny

- docs/containerd-2.0.md
Addresses #10694
This change adds containerd 2.0 documentation to provide more background to some of the major changes coming in 2.0. The intention is to be supplementary to releases notes and other  communications for the upcoming changes.
> Add containerd 2.0 doc

- internal/cri/server/podsandbox/sandbox_status.go
- internal/cri/server/sandbox_status.go
- internal/cri/types/sandbox_info.go
This field has been deprecated since 1.3. I think we can remove it as part of 2.0 deprecation?
The tracking issue mentioned in the code comment: https://github.com/containerd/cri/issues/1064
The release note mentioning the deprecation of this field:
https://github.com/containerd/containerd/pull/3492#:~:text=runtimeHandler%20field%20is%20moved%20from%20the%20sandbox%20info%20into%20status
> Remove deprecated cri SandboxInfo RuntimeHandler

- client/client.go
- client/services.go
- cmd/containerd/server/server.go
- core/sandbox/proxy/controller.go
- internal/cri/server/podsandbox/controller.go
- internal/cri/server/restart.go
- plugins/cri/cri.go
- plugins/services/sandbox/controller_service.go
- plugins/types.go
We can not handle the task in the pod sandbox as a sandboxed Task because podsandbox controller rely on task plugin to create pause container, If the task handle rely on podsandbox controller, it will make a cyclic dependency of plugins.
So In this PR, We add a new PodSandboxPlugin type for the podsandbox controller, Shim sandbox controller and other user defined sandbox controllers will be kind of SandboxControllerPlugin. and the subsequent PR of sandboxed Task will rely on this PR to handle sandboxed Task in sandbox of SandboxControllerPlugin.
> sandbox: make podsandbox controller plugin type of PodSandboxPlugin

- docs/containerd-2.0.md
Format link text to be less technical.
- transfer.md -> "Transfer Service" (document's title)
- backticks around Go pkg link text.
- Quotes around links to other document sections.
> Format link text in containerd 2.0 doc for readability

- containerd.service
containerd launches runc, which communicates via dbus with systemd to start transient units. Thus, containerd should have an `After` dependency on `dbus.service` to prevent dbus from being shut down concurrently with containerd.
> Add After=dbus.service to containerd.service

- docs/tracing.md
This change updates tracing documentation to reference the preferred method for setting OpenTelemetry exporter configuration for the daemon.
> Update tracing docs for containerd 2.0

- pkg/cri/server/sandbox_run.go
Cherry-pick of #10770 for release 1.6
---
Created pod-config.json as per crictl docs
```
root@7611fd8b15fd:/src# create pod-config.json
echo "{
\"metadata\": {
\"name\": \"nginx-sandbox\",
\"namespace\": \"default\",
\"attempt\": 1,
\"uid\": \"65fb5845de97d8a4\"
},
\"log_directory\": \"/tmp\",
\"linux\": {
}
}
" | tee pod-config.json
```
```
root@2f8f343b8881:/src# crictl runp pod-config.json
E1005 18:00:26.719186   23199 remote_runtime.go:176] "RunPodSandbox from runtime service failed" err="rpc error: code = Unknown desc = failed to setup network for sandbox \"df615a04a1ba1eef496b5e64f8a7a4a2eb8b188e35f2442a8ba1f5f54a169b8c\": cni plugin not initialized"
FATA[0001] run pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox …
```
> [release/1.6] Handle teardown failure to avoid blocking cleanup

- containerd.service
Backports https://github.com/containerd/containerd/pull/10798
containerd launches runc, which communicates via dbus with systemd to start transient units. Thus, containerd should have an `After` dependency on `dbus.service` to prevent dbus from being shut down concurrently with containerd.
(cherry picked from commit 18e4ea9a6c5378a175e5090ca4052d0b2ff742df)
> [release/1.6 backport] Add After=dbus.service to containerd.service

- containerd.service
Backports https://github.com/containerd/containerd/pull/10798
containerd launches runc, which communicates via dbus with systemd to start transient units. Thus, containerd should have an `After` dependency on `dbus.service` to prevent dbus from being shut down concurrently with containerd.
(cherry picked from commit 18e4ea9a6c5378a175e5090ca4052d0b2ff742df)
> [release/1.7 backport] Add After=dbus.service to containerd.service

- docs/containerd-2.0.md
While some warnings were available in earlier versions, the first "complete" implementation was in 1.7.12 and 1.6.27.
https://github.com/containerd/containerd/issues/9312 tracks that initial set of warnings.
> docs: update min version for deprecation warnings

- cmd/containerd/server/config/config.go
- cmd/containerd/server/config/config_test.go
Hi all, This is a spin-off from the following PR https://github.com/containerd/containerd/pull/7347 (which I suggest we close, since I'm afraid the long history there, and non-essential improvements that I've included obfuscate the PR.). My hope is, that this more concise PR is easier to review.
This PR focuses on a very small change targetting 2.0.0, and I've included a unit test to demonstrate the difference it makes. Without the code change, the unit test would fail with: [make-test-fail.txt](https://github.com/containerd/containerd/files/14694561/make-test-fail.txt)
**Summary**
The change proposed in this PR allows various drop-in configuration toml files to configure _parts_ of a Plugin.
For example, starting with the following containerd `config.toml`, it includes a bunch of …
> Allow sections of Plugins to be merged, and not overwritten as entire sections.

- go.mod
- go.sum
- vendor/github.com/containerd/containerd/api/LICENSE
- vendor/modules.txt
- version/version.go
----
Welcome to the v2.0.0-rc.6 release of containerd!  
* Add Update API for sandbox controller ([#9903](https://github.com/containerd/containerd/pull/9903))
* Configure otel from env instead of config.toml ([#8970](https://github.com/containerd/containerd/pull/8970))
* Enable …
> Prepare release notes for v2.0.0-rc.6

- .github/workflows/ci.yml
crun is usually used on Fedora, RHEL, and similar distros. So it makes more sense to run crun tests on Fedora.
Ubuntu jobs are removed, because inflating the number of the jobs will result in making the flakiness rate much worse.
> CI: move crun from Ubuntu to Fedora

- plugins/content/local/locks.go
- plugins/content/local/locks_test.go
- plugins/content/local/store.go
- plugins/content/local/writer.go
This allows multiple writers to not lock if they operate in different roots.
See also https://github.com/moby/buildkit/issues/3270#issuecomment-1323606958
> Lock store writer per digest and writer.

- BUILDING.md
I was getting the following error when running the sample `go test` commands.
```
no Go files in /tmp/containerd
```
Also the example `sudo go test -v -run "TestContainerList" ./integration/client -test.root` outputted a lot of logs, so I excluded them from the example.
<details>
<summary>Test Output</summary>
```shell
$ sudo go test -v -run "TestContainerList" ./integration/client -test.root
time="2024-10-08T00:18:58Z" level=info msg="Using the following image list: {Alpine:ghcr.io/containerd/alpine:3.14.0 BusyBox:ghcr.io/containerd/busybox:1.36 Pause:registry.k8s.io/pause:3.10 ResourceConsumer:registry.k8s.io/e2e-test-images/resource-consumer:1.10 VolumeCopyUp:ghcr.io/containerd/volume-copy-up:2.2 VolumeOwnership:ghcr.io/containerd/volume-ownership:2.1 …
```
> Update sample `go test` commands in BUILDING.md

- plugins/content/local/store.go
- plugins/content/local/store_test.go
A contentstore can be created on top of readonly path and should not fail unless there is an attempt to write into it.
Currently this fails because new ingest directory is created always, meaning for example that you can't create a store to read blobs from OCI layout without it contaminating the OCI layout files.
> local: avoid writing to content root on readonly store

- cmd/containerd/server/config/config.go
- cmd/containerd/server/config/config_test.go
Fix #10905
The following config is automatically migrated without raising an error.
```toml
disabled_plugins=["cri"]
```
↓
```toml
version = 3
disabled_plugins = ["io.containerd.grpc.v1.cri"]
```
> config: v1Migrate: support DisabledPlugins and RequiredPlugins

- plugins/services/snapshots/service.go
- combine consecutive "WithField" calls to "WithFields", as multiple calls is known to be expensive.
- include a "snapshotter" field in logs to allow correlating actions with specific snapshotters.
> services/snapshots: include name of snapshotter in debug logs

- RELEASES.md
* CRI v1alpha2 was removed in v1.26, not in v1.27 https://github.com/kubernetes/kubernetes/blob/v1.26.0/CHANGELOG/CHANGELOG-1.26.md?plain=1#L482
* Kubernetes releases prior to v1.29 have already reached their EOL: https://kubernetes.io/releases/
> RELEASES.md: k8s: fix CRI v1alpha2 removal release, remove old releases

- docs/containerd-2.0.md
- CRI support for user namespaces (PR #8803)
- CRI support for recursive read-only mounts (PR #9787)
- CDI is enabled by default (PR #9621)
> docs/containerd-2.0.md: add more highlights

- api/releases/v1.8.0.toml
No more API changes are being considered for api/v1.8.0 and containerd v2.0.0
Relevant to #10858
> Prepare release notes for api/v1.8.0

- integration/client/container_test.go
ListPids may not pick up the sh subprocess yet when it is first run. To make this test more resilient, retry fetching the processes if only a single pid is found for a short time.
(cherry picked from commit bddeba8250f14f5697520a13cee08ad04b1aa11e)
Backport of #10933
> [release/1.7] Make TestContainerPids more resilient

- integration/client/container_test.go
ListPids may not pick up the sh subprocess yet when it is first run. To make this test more resilient, retry fetching the processes if only a single pid is found for a short time.
(cherry picked from commit bddeba8250f14f5697520a13cee08ad04b1aa11e)
Backport of #10933
> [release/1.6] Make TestContainerPids more resilient

- services/snapshots/service.go
Backports https://github.com/containerd/containerd/pull/10919 to 1.7 branch
- combine consecutive "WithField" calls to "WithFields", as multiple calls is known to be expensive.
- include a "snapshotter" field in logs to allow correlating actions with specific snapshotters.
(cherry picked from commit 4594f5cac18f3d46b54666b20698b2aa7861c3f2)
> [release/1.7] services/snapshots: include name of snapshotter in debug logs

- services/snapshots/service.go
Backports https://github.com/containerd/containerd/pull/10919 to 1.6 branch
- combine consecutive "WithField" calls to "WithFields", as multiple calls is known to be expensive.
- include a "snapshotter" field in logs to allow correlating actions with specific snapshotters.
(cherry picked from commit 4594f5cac18f3d46b54666b20698b2aa7861c3f2)
> [release/1.6] services/snapshots: include name of snapshotter in debug logs

- README.md
- RELEASES.md
- releases/cri-containerd.DEPRECATED.txt
- releases/v2.0.0.toml
- version/version.go
containerd 2.0.0
Welcome to the v2.0.0 release of containerd!
See [containerd 2.0](https://github.com/containerd/containerd/blob/main/docs/containerd-2.0.md) documentation for details on what is new and has changed in this release.
* Allow sections of Plugins to be merged, and not overwritten as entire sections. …
> Prepare release notes for v2.0.0

- test/build.sh
Helps match tgz file name to the same format when we build under arm64 as well, we are only trying to change the `-` to `.` here and there's no need to specify `amd64`
> Avoid arch info in the sed/replace when building cri-cni-containerd.tar.gz

- test/build.sh
Cherry pick of https://github.com/containerd/containerd/pull/10964 to `release/2.0` branch
> [release/2.0] Avoid arch info in the sed/replace when building cri-cni-containerd.tar.gz 

- .github/workflows/ci.yml
Fixes broken vagrant builds
From #10950
> [release/1.6] backport: Disable vagrant strict dependency checking

- .github/workflows/release.yml
This change makes it so 2.0 tags are marked as latest releases.
> [release/2.0] ci: enable marking 2.0 releases as latest

- .devcontainer/devcontainer.json
- .github/actions/install-go/action.yml
- .github/workflows/api-release.yml
- .github/workflows/ci.yml
- .github/workflows/release.yml
- Vagrantfile
- contrib/Dockerfile.test
- contrib/fuzz/oss_fuzz_build.sh
- script/setup/prepare_env_windows.ps1
- go1.23.3 (released 2024-11-06) includes fixes to the linker, the runtime, and the net/http, os, and syscall packages. See the Go 1.23.3 milestone on our issue tracker for details. 
https://github.com/golang/go/issues?q=milestone%3AGo1.23.3+label%3ACherryPickApproved
- go1.22.9 (released 2024-11-06) includes fixes to the linker. See the Go 1.22.9 milestone on our issue tracker for details
https://github.com/golang/go/issues?q=milestone%3AGo1.22.9+label%3ACherryPickApproved
> update to go1.23.3 / go1.22.9

- .github/workflows/ci.yml
Fixes broken vagrant builds
From #10950 
(cherry picked from commit ae73e30130811fba51716b9e70ea86cb0dd42193)
> [release/1.7] backport: Disable vagrant strict dependency checking

- internal/fsverity/fsverity_test.go
1. Fix nil pointer dereference:
Nil pointer deference happens when `IsEnabled` returns `false, nil` and `err.Error()` is called on nil value.
2. Fix test fail
Currently test fails when `IsEnabled` returns `false, nil`, i don't think it's fine (plus it only happens on one architecture, `s390x`), so i changed it to only accept `false, err`, or this test should also report `false, nil`?
3. Fix minor/major device numbers resolving:
Taken from https://tip.golang.org/src/cmd/vendor/golang.org/x/sys/unix/dev_linux.go
Current formulas for resolving major/minor device numbers is incorrect, which leads to warnings like this:
```
=== RUN   TestEnable
fsverity_test.go:51: invalid device: device mount not found for device id 3:0
--- SKIP: TestEnable (0.04s)
=== RUN   TestIsEnabled
--- PASS: …
```
> fsverity_test.go: fix nil pointer derefence, fix test fail, fix minor/major device numbers resolving

- test/build.sh
Cherry pick of https://github.com/containerd/containerd/pull/10964 to release/1.7 branch
> [release/1.7] Avoid arch info in the sed/replace when building cri-cni-containerd.tar.gz

- .github/workflows/release.yml
This change makes it so new tags of 1.7.x are not marked as latest over 2.0 releases.
> [release/1.7] ci: disable marking 1.7 releases as latest

- .github/actions/install-go/action.yml
- .github/workflows/ci.yml
- .github/workflows/release.yml
- Vagrantfile
- contrib/Dockerfile.test
- script/setup/prepare_env_windows.ps1
- go1.23.3 (released 2024-11-06) includes fixes to the linker, the runtime, and the net/http, os, and syscall packages. See the Go 1.23.3 milestone on our issue tracker for details.
https://github.com/golang/go/issues?q=milestone%3AGo1.23.3+label%3ACherryPickApproved
- go1.22.9 (released 2024-11-06) includes fixes to the linker. See the Go 1.22.9 milestone on our issue tracker for details
https://github.com/golang/go/issues?q=milestone%3AGo1.22.9+label%3ACherryPickApproved
> [release/1.6] update build to go1.22.9, test go1.23.3

- .github/actions/install-go/action.yml
- .github/workflows/api-release.yml
- .github/workflows/ci.yml
- .github/workflows/release.yml
- Vagrantfile
- contrib/Dockerfile.test
- contrib/fuzz/oss_fuzz_build.sh
- script/setup/prepare_env_windows.ps1
- go1.23.3 (released 2024-11-06) includes fixes to the linker, the runtime, and the net/http, os, and syscall packages. See the Go 1.23.3 milestone on our issue tracker for details.
https://github.com/golang/go/issues?q=milestone%3AGo1.23.3+label%3ACherryPickApproved
- go1.22.9 (released 2024-11-06) includes fixes to the linker. See the Go 1.22.9 milestone on our issue tracker for details
https://github.com/golang/go/issues?q=milestone%3AGo1.22.9+label%3ACherryPickApproved
> [release/1.7] update build to go1.22.9, test go1.23.3

- pkg/testutil/helpers.go
Backports fix #10901 to release 1.7.
Currently any upstream consumers importing libraries both containerd 1.7 and the newest continuity (v0.4.4) will experience the same issue, so without this fix an upgrade is impossible.
> [release/1.7 backport] testutil: avoid conflict with continuity/testutil

- go.mod
- go.sum
- vendor/github.com/containerd/typeurl/v2/types.go
- vendor/github.com/containerd/typeurl/v2/types_gogo.go
- vendor/modules.txt
Backport of #10992
Includes fix for unmarshaling of registered types
Bumps [github.com/containerd/typeurl/v2](https://github.com/containerd/typeurl) from 2.2.2 to 2.2.3.
- [Release notes](https://github.com/containerd/typeurl/releases)
- [Commits](https://github.com/containerd/typeurl/compare/v2.2.2...v2.2.3)
---
updated-dependencies:
- dependency-name: github.com/containerd/typeurl/v2 dependency-type: direct:production update-type: version-update:semver-patch ...
(cherry picked from commit 01c489141c37e27b71370ab26ab28347b17f4284)
> [release/2.0] bump github.com/containerd/typeurl/v2 from 2.2.2 to 2.2.3

- internal/fsverity/fsverity_linux.go
I found out that `unix.Syscall(..., uintptr(unsafe.Pointer(&return_value)))` returns very big value.
If syscall returns `128` (not verity, just example) on other systems, it returns `549755813888` on `s390x`, so `fsverity.IsEnabled` is almost incorrect. Note that `128 << 32 == 549755813888`. 
This happens because `s390x` is Big Endian, whereas other ones are Little Endian.
One fix is to change `attr` variable type to `int32` , but this won't work if containerd is compiled against or used on system where C `int` is not 4 bytes wide.
This PR includes change of `attr` variable type to `int32`.
> fsverity_linux.go: Fix fsverity.IsEnabled() for big endian systems

- RELEASES.md
- docs/containerd-2.0.md
* Correctly reference the only schema 1 mediatype containerd supports.
* Document that `--local` is required for `ctr` when pulling schema 1 images
* Document CRI users more clearly
Fixes https://github.com/containerd/containerd/issues/10998
> docs: update schema 1 deprecation information

- .github/workflows/ci.yml
This reverts commit ae73e30130811fba51716b9e70ea86cb0dd42193.
Vagrant v2.4.3 is released ([CHANGELOG](https://github.com/hashicorp/vagrant/blob/v2.4.3/CHANGELOG.md)), and has the fix mentioned in https://github.com/containerd/containerd/pull/10950
> Revert "Disable vagrant strict dependency checking"

- contrib/v2-migrate.sh
A few fixes that came up using the script
> Fix runtimeoptions location in v2 migration script

- internal/fsverity/fsverity_test.go
Cherry-picks (clean) https://github.com/containerd/containerd/pull/10972 to release/2.0 branch.
> [release/2.0] fsverity_test.go: fix nil pointer derefence, fix test fail, fix minor/major device numbers resolving

- core/metadata/content.go
- plugins/services/content/store.go
Other similar events were already moved to the metadata store. The metadata store has more information that can be used for a future content created event.
Will be needed to fully implement #10508
> Move content events to metadata

- integration/images/image_list.go
- integration/main_test.go
- integration/pod_userns_linux_test.go
- internal/cri/server/container_start.go
- internal/cri/server/container_start_linux.go
- internal/cri/server/container_start_other.go
The containerd-shim creates pipes and passes them to the init container as stdin, stdout, and stderr for logging purposes. By default, these pipes are owned by the root user (UID/GID: 0/0). The init container can access them directly through inheritance.
However, if the init container attempts to open any files pointing to these pipes (e.g., /proc/1/fd/2, /dev/stderr), it will encounter a permission issue since it is not the owner. To avoid this, we need to align the ownership of the pipes with the init process.
Fixes: #10598
> *: should align pipe's owner with init process

- content/local/store.go
- content/local/store_test.go
* Backports https://github.com/containerd/containerd/pull/10894
A contentstore can be created on top of readonly path and should not fail unless there is an attempt to write into it.
Currently this fails because new ingest directory is created always, meaning for example that you can't create a store to read blobs from OCI layout without it contaminating the OCI layout files.
(cherry picked from commit 3cc2343de020fa448138ce0283e8a142c05b6856)
> [release/1.7 backport] local: avoid writing to content root on readonly store

- Makefile
- integration/failpoint/cmd/loopback-v2/main.go
- integration/issue10244_loopback_linux_test.go
- script/setup/install-failpoint-binaries
Adding test cases to cover CNI v2 loopback options, as mentioned in issue #10244 
Loopback (lo) is expected to be set to on for localhost in all containers of a pod, regardless of whether the `use_internal_loopback` option is set to `true` or `false` within containerd config (`/etc/containerd/config.toml`)
Two tests have been added in `integration/issue10244_container_exec_test.go` - one to validate the above for when the `use_internal_loopback` property is set to `false` (default value), and one for when it is set to `true`
> Add tests for CNI v2 loopback options

- internal/cri/server/container_stats_list.go
- internal/cri/server/container_stats_list_test.go
toContainerStats should not error when a container that is passed to as part of the container array is not found in containerStore. That might happen when a container is removed before its sandbox is (probably removed after buildTaskMetricsRequest is called).
Without this fix the toContainerStats would fail metric collection for all containers in the argument list.
Fixes #10796
> make ListContainerStats handle container that is removed before its sandbox

- remotes/docker/config/hosts.go
- remotes/docker/config/hosts_test.go
- remotes/docker/resolver.go
- remotes/docker/resolver_test.go
- remotes/docker/resolver_unix.go
- remotes/docker/resolver_windows.go
- backport: https://github.com/containerd/containerd/pull/10286
When no port is specified in host, allow falling back from 443 to 80 when http is specified along with a TLS configuration. This increases the cases when https can be preferred and fixes a case where fallback does not happen after a connection refused where previously Docker would have fallen back.
- backport: https://github.com/containerd/containerd/pull/10342
Fixes an issue with race detector complaining about concurrent access such as with Dispatch on push.
> [release/1.7 backport] Fix retry logic and concurrency issue with http fallback

- pkg/cri/sbserver/events.go
- pkg/cri/server/events.go
cherry pick from main , if container is exited log exited event is necessary.
> [release/1.7] internal/cri: log ctr's exit event on info level

- internal/cri/config/config.go
RELEASES.md specifies these will be removed in 2.1: https://github.com/containerd/containerd/blob/v2.0.0/RELEASES.md#deprecated-config-properties
> Clarify release for deprecated registry field removals

- .github/workflows/ci.yml
Vagrant integration (rockylinux/9@4.0.0) CIs are failing because the box download URL link no longer works.
https://github.com/containerd/containerd/actions/runs/12002473354/job/33454590732
The link (https://vagrantcloud.com/rockylinux/boxes/9/versions/4.0.0/providers/libvirt/amd64/vagrant.box) redirects to (https://dl.rockylinux.org/pub/rocky/9.4/images/x86_64/Rocky-9-Vagrant-Libvirt-9.4-20240509.0.x86_64.box) which was moved to (https://dl.rockylinux.org/vault/rocky/9.4/images/x86_64/Rocky-9-Vagrant-Libvirt-9.4-20240509.0.x86_64.box)
(`dl.rockylinux.org/pub` -> `dl.rockylinux.org/vault`, similar to https://github.com/containerd/containerd/pull/10297).
https://github.com/containerd/containerd/pull/10304 changes rocky8.9 to almalinux/8,
similarly, this one changes rocky9.4 to almalinux/9. …
> Move rockylinux 9.4 to almalinux/9 in CI

- .github/workflows/ci.yml
Cherry pick https://github.com/containerd/containerd/pull/11050
(cherry picked from commit 288001f68c5fd34cfbdc7284f14375a3762b8ff4)
> [release/2.0] Move rockylinux 9.4 to almalinux/9 in CI

- .github/workflows/release.yml
Followup to https://github.com/containerd/containerd/pull/10543#pullrequestreview-2261825978 to attest artifacts prior to creating the release. This also should address containerd project's signed releases action item in CNCF CLO monitor Reference: [containerd CLO monitor](https://clomonitor.io/projects/cncf/containerd), [scorecard checks doc](https://github.com/ossf/scorecard/blob/main/docs/checks.md#signed-releases)
This allows the attestation to be published with the release artifacts. The trade-off is if create release were to fail (potentially due to GitHub outage), then artifacts have already been attested and published to GitHub attestations. This should be an acceptable trade-off as maintainers with write access can manually upload the containerd tarballs to GitHub or roll forward …
> Publish attestation as release artifact

- .github/workflows/ci.yml
similar to https://github.com/containerd/containerd/pull/11050.
Since the current `ci.yml` has some refactor (matrix.box -> matrix.include.box|cgroup_driver|runc), the original commit cannot be cherry picked directly, so just made the change directly here.
> [release/1.7] Move rockylinux 9.4 to almalinux/9 in CI

- .github/workflows/ci.yml
Similar to https://github.com/containerd/containerd/pull/11050.
The CI in 1.6 branch actually doesn't have rocky9, but since it's still being supported, we probably should add it (almalinux/9) to its CI.
> [release/1.6] Add almalinux/9 in CI

- pkg/archive/compression/compression.go
- plugins/diff/walking/differ.go
- plugins/diff/windows/windows.go
The differ should be able to generate zstd compressed layers when provided with the zstd media type.
Added the unknown compression type to handle cases when compression is done via a plugin but should be differentiated from no compression.
> Update differ to handle zstd media types

- .github/workflows/release.yml
Backports https://github.com/containerd/containerd/pull/11049 to 2.0
(cherry picked from commit 3961dc9c8cb0e31925e45a2273bbdc06412be262)
> [release/2.0] Publish attestation as release artifact

- cmd/containerd-shim-runc-v2/manager/manager_linux.go
> The task_dir successfully cleans when the file is absent.

- cmd/containerd-shim-runc-v2/runc/container.go
Fix #11001
When the shim creates a container within `NewContainer`, the cgroups v1/v2 may be nil due to errors.
https://github.com/containerd/containerd/blob/566f9f48db6f6bc7dbd76d70aa425afbee7b0d0a/cmd/containerd-shim-runc-v2/runc/container.go#L149-L166
However, a `nil` pointer of `*cgroupsv2.Manager` type *is not* an `nil` interface{}. And it can be converted back to `*cgroupsv2.Manager` type (the resulted var will be `nil`) which causes nil deference panic in `Start` in the above issue. (sample: https://go.dev/play/p/ZThwvj1n3g8)
https://github.com/containerd/containerd/blob/566f9f48db6f6bc7dbd76d70aa425afbee7b0d0a/cmd/containerd-shim-runc-v2/task/service.go#L316-L317
The fix is to return directly on error (to avoid `container.cgroup = cg `), so the switch in `Start` will match neither …
> Fix panic due to nil dereference cgroups v2

- .devcontainer/devcontainer.json
- .github/actions/install-go/action.yml
- .github/workflows/api-release.yml
- .github/workflows/ci.yml
- .github/workflows/release.yml
- Vagrantfile
- contrib/Dockerfile.test
- contrib/fuzz/oss_fuzz_build.sh
- script/setup/prepare_env_windows.ps1
- go1.23.4 (released 2024-12-03) includes fixes to the compiler, the runtime, the trace command, and the syscall package. See the Go 1.23.4 milestone on our issue tracker for details.
https://github.com/golang/go/issues?q=milestone%3AGo1.23.4+label%3ACherryPickApproved
- go1.22.10 (released 2024-12-03) includes fixes to the runtime and the syscall package. See the Go 1.22.10 milestone on our issue tracker for details. 
https://github.com/golang/go/issues?q=milestone%3AGo1.22.10+label%3ACherryPickApproved
> update to go1.23.4 / go1.22.10

- runtime/v2/runc/container.go
This PR ports #11069 to release/1.6 (with minor modification due to that 1.6 uses logrus and containerd/cgroups v1.0.4).
> [release/1.6] Fix panic due to nil dereference cgroups v2

- .github/workflows/release/Dockerfile
This fixes compatibility with alpine 3.21 and file 5.46+
- Fix additional possible `xx-cc`/`xx-cargo` compatibility issue with Alpine 3.21
- Support for Alpine 3.21
- Fix `xx-verify` with `file` 5.46+
- Fix possible error taking lock in `xx-apk` in latest Alpine without `coreutils`
full diff: https://github.com/tonistiigi/xx/compare/v1.2.1...v1.6.1
> update xx to v1.6.1 for compatibility with alpine 3.21 and file 5.46+

- cmd/ctr/commands/images/pull.go
Currently if neither `--all-platforms` nor `--platform` is specified in `ctr i pull`, it will pull using the default platform, but skip the unpack step (if using transfer service). However, we should apply the `default platform` to unpack as well.
```shell
containerd [main]  ➜ sudo ctr i pull --snapshotter=overlayfs docker.io/library/alpine:latest
...
containerd [main]  ➜ sudo ctr snapshot ls
KEY PARENT KIND
containerd [ctr-pull-transfer-service]  ➜ sudo ctr i pull --snapshotter=overlayfs docker.io/library/alpine:latest
...
containerd [ctr-pull-transfer-service]  ➜ sudo ctr snapshot ls
KEY                                                                     PARENT KIND
sha256:75654b8eeebd3beae97271a102f57cdeb794cc91e442648544963a7e951e9558        Committed
```
> ctr pull should unpack for default platform when transfer service is used

- integration/client/migration_test.go
- integration/client/testdata/custom-1.7.toml
- plugins/cri/cri.go
- plugins/cri/cri_test.go
It seems CRI GRPC plugin config cannot be migrated (other than `disable_tcp_service`). This PR make sure all fields in v3 `plugins."io.containerd.grpc.v1.cri"` are migrated from v2 `plugins."io.containerd.grpc.v1.cri"`.
Running `sudo ./bin/containerd -c test.toml config migrate` on this v2 cri grpc config:
```toml
version = 2
[plugins]
[plugins."io.containerd.grpc.v1.cri"]
disable_tcp_service = true
stream_server_address = '127.1.1.1'
stream_server_port = '15000'
stream_idle_timeout = '5h0m0s'
enable_tls_streaming = true
[plugins.'io.containerd.grpc.v1.cri'.x509_key_pair_streaming]
tls_cert_file = '/path/to/cert.pem'
tls_key_file = '/path/to/key.pem'
```
The migrated `plugins."io.containerd.grpc.v1.cri"` in main branch (only default values):
```toml
[plugins.'io.containerd.grpc.v1.cri'] …
```
> Complete cri grpc plugin config migration

- go.mod
- go.sum
- vendor/github.com/containerd/go-cni/README.md
- vendor/github.com/containerd/go-cni/cni.go
- vendor/github.com/containerd/go-cni/testutils.go
- vendor/modules.txt
This PR updates go-cni with the latest version. It provides the CNI Status verb. To make use of this new verb users will need to specify the CNI Version 1.1.0 in the CNI Configuration.
> Update go-cni for CNI STATUS

- .github/actions/install-go/action.yml
- .github/workflows/ci.yml
- .github/workflows/release.yml
- Vagrantfile
- contrib/Dockerfile.test
- script/setup/prepare_env_windows.ps1
- go1.22.10 (released 2024-12-03) includes fixes to the runtime and the syscall package. See the Go 1.22.10 milestone on our issue tracker for details. 
https://github.com/golang/go/issues?q=milestone%3AGo1.22.10+label%3ACherryPickApproved
- go1.23.4 (released 2024-12-03) includes fixes to the compiler, the runtime, the trace command, and the syscall package. See the Go 1.23.4 milestone on our issue tracker for details.
https://github.com/golang/go/issues?q=milestone%3AGo1.23.4+label%3ACherryPickApproved
> [release/1.6] update build to go1.22.10, test go1.23.4

- .github/actions/install-go/action.yml
- .github/workflows/api-release.yml
- .github/workflows/ci.yml
- .github/workflows/release.yml
- Vagrantfile
- contrib/Dockerfile.test
- contrib/fuzz/oss_fuzz_build.sh
- script/setup/prepare_env_windows.ps1
- go1.22.10 (released 2024-12-03) includes fixes to the runtime and the syscall package. See the Go 1.22.10 milestone on our issue tracker for details.
https://github.com/golang/go/issues?q=milestone%3AGo1.22.10+label%3ACherryPickApproved
- go1.23.4 (released 2024-12-03) includes fixes to the compiler, the runtime, the trace command, and the syscall package. See the Go 1.23.4 milestone on our issue tracker for details.
https://github.com/golang/go/issues?q=milestone%3AGo1.23.4+label%3ACherryPickApproved
> [release/1.7] update build to go1.22.10, test go1.23.4

- cmd/ctr/commands/images/import.go
- cmd/ctr/commands/images/mount.go
- cmd/ctr/commands/images/pull.go
- cmd/ctr/commands/run/run.go
- cmd/ctr/commands/run/run_unix.go
- cmd/ctr/commands/run/run_windows.go
- cmd/ctr/commands/snapshots/snapshots.go
this [commit](https://github.com/containerd/containerd/pull/9401) Added sync-fs support for cri interface, but not ctr.
this [commit](https://github.com/containerd/containerd/pull/10284) Added global configuration but not flexible enough.
@fuweid PTAL
> cmd/ctr: allow user to syncfs during unpacking image locally

- internal/cri/server/cni_conf_syncer.go
xref: https://github.com/containerd/containerd/issues/6490
xref: https://github.com/containerd/containerd/pull/7224
Deleting and recreating confDir is an error that causes containerd to remain in the **cni plugin not initialized** state forever and will not work until containerd is restarted.
But instead of re-executing the '**newCNINetConfSyncer**' function here, I think it's better to simply throw an error. Specific decisions (such as stopping or restarting containerd or recreate the confDir) should be determined by external error handling:
```golang
select {
case eventMonitorErr = <-eventMonitorErrCh:
case streamServerErr = <-streamServerErrCh:
case cniNetConfMonitorErr = <-cniNetConfMonitorErrCh:
}
.......
if cniNetConfMonitorErr != nil {
return fmt.Errorf("cni network conf monitor …
```
> Report an error when cni confDir removed

- pkg/imageverifier/bindir/bindir_test.go
When VeriftImage returns an error, the first return value may be set to nil (this is the case for timeouts). When that is the case, it makes no point trying to access its fields later in the test. Let's use testify/require instead of testify/assert here to ensure the test halts upon failure.
> test: prevent segfault in imageverifier test

- .mailmap
- releases/v2.0.1.toml
- version/version.go
----
Welcome to the v2.0.1 release of containerd!
The first patch release for containerd 2.0 includes a number of bug fixes and improvements.
* Fix apply IoOwner options when not in user namespace ([#11151](https://github.com/containerd/containerd/pull/11151))
* Fix cri grpc plugin config migration ([#11140](https://github.com/containerd/containerd/pull/11140))
* Support CNI STATUS Verb ([containerd/go-cni#123](https://github.com/containerd/go-cni/pull/123))
* Update differ to handle zstd media types ([#11068](https://github.com/containerd/containerd/pull/11068))
* Update runc binary to v1.2.3 ([#11142](https://github.com/containerd/containerd/pull/11142))
* Fix panic due to nil dereference cgroups v2 ([#11098](https://github.com/containerd/containerd/pull/11098)) …
> [release/2.0] Prepare release notes for v2.0.1

- script/setup/install-dev-tools
`script/setup/install-dev-tools` currently installs v1.54.2, which cannot be built with `GOPROXY=direct` as it takes a dependency on `go.tmz.dev/musttag` which no longer exists. This is fixed in [v1.56.0](https://github.com/golangci/golangci-lint/releases/tag/v1.56.0) where the dependency was replaced with `go-simpler.org/musttag`.
```bash
$ go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.54.2
go: downloading go.tmz.dev/musttag v0.7.2
../go/pkg/mod/github.com/golangci/golangci-lint@v1.54.2/pkg/golinters/musttag.go:4:2: unrecognized import path "go.tmz.dev/musttag": https fetch: Get "https://go.tmz.dev/musttag?go-get=1": dial tcp: lookup go.tmz.dev on 127.0.0.1:53: no such host
```
This PR updates the script to match the version of the linter used in the …
> Update golangci-lint version in dev tools script

- .github/workflows/ci.yml
- .golangci.yml
Updates to the latest golangci 1.60. This will can backported, separately we can move ahead to latest release.
The exportloopref is deprecated for copyloopvar with Go 1.22+. We can enable this separately, it requires changes in over 100 places.
> Update golangci to 1.60.3

- go.mod
- go.sum
- pkg/namespaces/ttrpc.go
- pkg/namespaces/ttrpc_test.go
- vendor/github.com/containerd/ttrpc/metadata.go
- vendor/github.com/containerd/ttrpc/server.go
- vendor/modules.txt
ttrpc 1.2.7 adds a new `MD.Clone` method, which is based on golang's `http.Header.Clone` and more efficient (https://github.com/containerd/ttrpc/pull/177).
This PR upgrades ttrpc to 1.2.7 and replace `copyMetadata` with `MD.Clone`.
> bump up ttrpc to use its MD.Clone

- BUILDING.md
- cmd/containerd/server/server.go
- cmd/containerd/server/server_no_plugins.go
- cmd/containerd/server/server_plugins.go
Add a `no_dynamic_plugins` build tag to disable `plugins` in containerd, which makes it significantly smaller when used.
Similar to https://github.com/containerd/containerd/pull/11203 but for v2.0. See https://github.com/containerd/containerd/issues/11202 for context.
[Plugins are deprecated in v2.0 and will be removed in v2.1](https://github.com/containerd/containerd/blob/v2.0.1/RELEASES.md#deprecated-features) so this PR targets `release/2.0`, and it shouldn't be necessary to do a similar one for `main`.
> [release/2.0] Add a build tag to disable std `plugin` import

- core/unpack/unpacker.go
- core/unpack/unpacker_test.go
This PR optimizes the chain ID calculation in unpack so we only (pre-)calculate the chain ID for every layer **exactly once**, by calling `identity.ChainIDs(diffIDs)` with the full list of diffIDs.
Currently in `unpack` for every layer_i, we calculate the chain id of its parent layer_i-1 and layer_i *repeatedly*, by calling `identity.ChainID(diffIDs)` with diffIDs till layer_i. This involves:
1. Copy `diffIDs` to a new slice
2. Calculate chain ID for every index (by calling `ChainIDs`)
3. Return the final one as result of `identity.ChainID(diffIDs)`.
Also added a benchmark test showing that `identity.ChainIDs` is 5-50x faster than `identity.ChainID`, and 5-50x less allocations.
```shell
$ go test -bench=. -benchmem ./core/unpack
goos: linux
goarch: amd64
pkg: …
```
> Avoid duplicated chain ID calculation in unpack

- cmd/containerd-shim-runc-v2/task/service.go
- integration/container_tty_leak_linux_test.go
Fixes: https://github.com/containerd/containerd/issues/11160
Tldr; this issue turned out to be a regression in v1.7.22 (#10651) where init container object is never deleted in a running shim.
It seems like that the init/exec process's console object are closed by golang's gc. In #10651, init container is added to `containerInitExit` to track its exit status, but never got removed. This prevented gc from deleting the object, and closing the console FD.
This is okay in regular case, there the shim will exit with the init container. But in CRI, the shim has the lifetime of a POD, therefore container objects will accumulate within the shim.
I think we should delete the init objects from the map on task deletion.
cc @laurazard
> make sure console master tty is closed on task exit

- script/test/utils.sh
The config_file var wasn't set when CONTAINERD_CONFIG_FILE env was passed, thus it should use  CONTAINERD_CONFIG_FILE instead of config_file to access the containerd conf file.
> ci: fix the issue of config_file unset

- releases/v1.7.25.toml
- version/version.go
----
Welcome to the v1.7.25 release of containerd!
The twenty-fifth patch release for containerd 1.7 contains various fixes
and updates.
* Update runc binary to v1.2.4 ([#11238](https://github.com/containerd/containerd/pull/11238))
* Fix proto conflicts and update to 1.8 API ([#11184](https://github.com/containerd/containerd/pull/11184))
* Fix `ip_pref` configuration option ([#11223](https://github.com/containerd/containerd/pull/11223))
* Fix panic due to nil dereference cgroups v2 ([#11099](https://github.com/containerd/containerd/pull/11099))
* Akihiro Suda
* Wei Fu
* Akhil Mohan
* Henry Wang
* Jin Dong
* …
> [release/1.7] Prepare release notes for v1.7.25

- RELEASES.md
The documentation around Go client API didn't align with the stability and GRPC API changes released with containerd v2.0.
> Clarify Go client API guidance

- core/remotes/docker/config/hosts.go
- core/remotes/docker/registry.go
- internal/cri/server/images/image_pull.go
The default transport are used in 3 places:
1. `ConfigureDefaultRegistries` (no `hosts_dir` is set)
2. `ConfigureHosts` (when `hosts_dir` is set)
3. in cri service
2 and 3 use/duplicate the same default transport, whereas 1 uses go's default Client/Transport
This PR moves the default transport to a common funcion (can pass in tls config).
> Unify default transport in docker resolver

- plugins/cri/runtime/plugin.go
- plugins/cri/runtime/plugin_test.go
Fix #10959
In current cri runtime config migration, it only changes `sandbox_mode` to `sandboxer` but left fields that are already moved to cri image/grpc services in place. That causes confusing `WARN` from toml parsing for cri runtime config, because those leftover cri image/grpc config fields don't have entries in `Runtime` config struct.
This PR explicitly skips those fields that are moved to cri image/grpc during cri runtime config migration, thus avoiding the `WARN`s.
---
Test using the 1.7 default config.toml
After this PR:
> Notice these warnings are expected, because they are all deprecated.
```shell
$ sudo ./bin/containerd --config integration/client/testdata/default-1.7.toml config migrate
WARN[0000] Ignoring unknown key in TOML for plugin       error="strict mode: fields in …
```
> Remove confusing warning in cri runtime config migration

- Makefile
Otherwise its a matter of luck that the man directory is created before man page generation.
Bug: https://bugs.gentoo.org/880057
This is GNU Make syntax as I'm under the impression that GNU Make is the chosen flavour of make.
```
$ make --shuffle=3620861772 man -j1
+ man/containerd-config.toml.5
go-md2man -in "docs/man/containerd-config.toml.5.md" -out "man/containerd-config.toml.5"
open man/containerd-config.toml.5: no such file or directory
make: *** [Makefile:302: man/containerd-config.toml.5] Error 1 shuffle=3620861772
```
> Use a order-only-prerequisite for mandir creation

- releases/v2.0.2.toml
- version/version.go
Generated release note
- - -
containerd 2.0.2
Welcome to the v2.0.2 release of containerd!
The second patch release for containerd 2.0 includes a number of bug fixes and improvements.
* Jin Dong
* Akihiro Suda
* Kazuyoshi Kato
* Henry Wang
* Krisztian Litkey
* Phil Estes
* Samuel Karp
* Akhil Mohan
* Brian Goff
* Chongyi Zheng
* Mike Brown
* Pierre Gimalac
* Wei Fu
<details><summary>22 commits</summary>
<p>
* * cdaf4dfb4 Prepare release notes for v2.0.2
* * 0d9aa65eb Merge pull request #11259 from k8s-infra-cherrypick-robot/cherry-pick-11257-to-release/2.0
* * eb125e1dd Update platforms to latest rc
* * c334ae68b Merge pull …
> Prepare release notes for v2.0.2

- cmd/ctr/commands/run/run_unix.go
- internal/cri/opts/spec_linux.go
- pkg/cdi/oci_opt.go
- pkg/oci/spec_opts.go
The CDI device injection spec opt was mistakenly added to the OCI
package which brought in an unintended dependency on CDI and its
transitive dependencies.
Not going to move it to an internal package since it may still be useful for clients. Its early enough in 2.0 to clean this up before it clients start utilizing and making it more difficult to move without breaking someone. This was quickly caught in buildkit which uses the spec opts but does not need/want those transitive dependencies pulled in.
> Move CDI device spec out of the OCI package

- integration/client/container_fuzz_test.go
Several Fuzz integration tests on Github Action panic due to unable to find containerd binary in `PATH`.
https://github.com/containerd/containerd/actions/runs/12719253904/job/35459145214
```
2025-01-11 00:37:14,414 - root - INFO - Running fuzzer: fuzz_FuzzIntegCreateContainerNoTearDown.
...
================== Job 1 exited with exit code 77 ============
...
failed to start daemon: failed to start daemon: exec: "containerd": executable file not found in $PATH:
panic: fatal [recovered]
panic: fatal
```
After this fix:
https://github.com/containerd/containerd/actions/runs/12720677667/job/35462684827?pr=11249
```
2025-01-11 03:33:44,550 - root - INFO - Running fuzzer: fuzz_FuzzIntegCreateContainerNoTearDown.
...
================== Job 0 exited with exit code 0 ============
...
INFO:        2 …
```
> Fix panics in CI fuzz integration tests

- core/mount/mount_idmapped_linux.go
- core/mount/mount_idmapped_linux_test.go
- core/mount/mount_linux.go
- core/mount/mount_linux_test.go
- plugins/snapshots/overlay/overlayutils/check.go
This is an additional safeguard against inadvertent data modification or deletion as a follow-up from #10721.
Tests covering the lifecycle of the temporary idmap mounts and integrity of the underlying lower layer data is also included in the normal and failed-unmount case.
Fixes #10704
From the discussion in #10721 I had three goals:
* @fuweid's request to add the read-only flag to the temporary mounts by adjusting `IdMapMount`'s signature to accept mount options.
* Add tests
* One way to simplify the logic determining the path to remove during cleanup, we already have the path to remove so no need to use `filepath.Dir` / `filepath.Join` on a particular layer's path. Not sure if this is exactly what @AkihiroSuda had in mind with [comment](https://github.com/containerd/containerd/pull/10721 …
> Make ovl idmap mounts read-only

- core/runtime/v2/binary.go
fix: https://github.com/containerd/containerd/issues/9902
logrus doesn't support fields with functions which a new field Cancel was added to exec.Cmd from GO 1.20, which is of type func() error
```
Failed to obtain reader, failed to marshal fields to JSON, json: unsupported type: func() error
```
> log: avoid using unsupported field by logrus

- client/snapshotter_opts_unix.go
- cmd/ctr/commands/run/run_unix.go
- core/mount/mount_idmapped_linux.go
- core/mount/mount_idmapped_linux_test.go
- integration/client/container_idmapped_linux_test.go
- internal/cri/server/container_start_linux.go
- internal/userns/idmap.go
- internal/userns/idmap_test.go
- plugins/snapshots/overlay/overlay.go
- plugins/snapshots/overlay/overlay_test.go
This is a follow-up PR of the previous #10307 to support multiple id mappings for ID mapped mounts.
* Added 'WithUserNSRemapperLabels()' to take multiple uid/gid mappings
* Updated 'ctr' to call the new func in case of '--remap-labels'
* Updated built-in overlay SN to handle labels with multiple mappings. It's also updated to create mount options for multiple mappings, e.g. 'uidmap=0:666:1000,1000:6666:64536'
* Updated 'GetUsernsFD()' to parse a string of multiple mappings
* CRI code is not changed
* It still calls 'WithRemapperLabels()' which takes a single mapping entry
* I believe it's okay because kubelet currently only passes a single mapping entry to the runtime
* If required, CRI just needs to call 'WithUserNSRemapperLabels()' to handle multiple mappings
> Support multiple uid/gid mappings [2/2]

- client/client.go
- client/client_opts.go
the client package provides a WithDialOpts option, however, dial-options passed to override all defaults that are set in containerd. This makes it difficult to expand the defaults with custom options, as this requires copying the defaults, and trying to keep those in sync (e.g. see [moby#48617]).
This patch introduces a new `WithExtraDialOpts` option which, unlike `WithDialOpts` are appended to, instead of overriding, previous options. This allows setting custom options, while maintaining containerd's defaults.
Also unlike `WithDialOpts`, this option can be used multiple times to allow additional options to be set.
[moby#48617]: https://github.com/moby/moby/pull/48617
> client: add WithExtraDialOpts option

- .devcontainer/devcontainer.json
- .github/actions/install-go/action.yml
- .github/workflows/api-release.yml
- .github/workflows/ci.yml
- .github/workflows/release.yml
- Vagrantfile
- contrib/Dockerfile.test
- contrib/fuzz/oss_fuzz_build.sh
- script/setup/prepare_env_windows.ps1
- go1.23.5 (released 2025-01-16) includes security fixes to the crypto/x509 and net/http packages, as well as bug fixes to the compiler, the runtime, and the net package. See the Go 1.23.5 milestone on our issue tracker for details.
https://github.com/golang/go/issues?q=milestone%3AGo1.23.5+label%3ACherryPickApproved
- go1.22.11 (released 2025-01-16) includes security fixes to the crypto/x509 and net/http packages, as well as bug fixes to the runtime. See the Go 1.22.11 milestone on our issue tracker for details.
https://github.com/golang/go/issues?q=milestone%3AGo1.22.11+label%3ACherryPickApproved
> update to go1.23.5 / go1.22.11

- .github/actions/install-go/action.yml
- .github/workflows/api-release.yml
- .github/workflows/ci.yml
- .github/workflows/release.yml
- Vagrantfile
- contrib/Dockerfile.test
- contrib/fuzz/oss_fuzz_build.sh
- script/setup/prepare_env_windows.ps1
- go1.23.5 (released 2025-01-16) includes security fixes to the crypto/x509 and net/http packages, as well as bug fixes to the compiler, the runtime, and the net package. See the Go 1.23.5 milestone on our issue tracker for details. https://github.com/golang/go/issues?q=milestone%3AGo1.23.5+label%3ACherryPickApproved
- go1.22.11 (released 2025-01-16) includes security fixes to the crypto/x509 and net/http packages, as well as bug fixes to the runtime. See the Go 1.22.11 milestone on our issue tracker for details. https://github.com/golang/go/issues?q=milestone%3AGo1.22.11+label%3ACherryPickApproved
> [release/1.7] update build to go1.22.11, test go1.23.5

- cmd/ctr/commands/run/run_unix.go
- internal/cri/opts/spec_linux.go
- pkg/cdi/oci_opt.go
- pkg/oci/spec_opts.go
The CDI device injection spec opt was mistakenly added to the OCI package which brought in an unintended dependency on CDI and its transitive dependencies.
(cherry picked from commit e20f7f4a2425c005d85855abfd4556d7b4ccbf87)
Backport of #11262 with only the first commit. The function should remain and be marked deprecated in 2.0.
> [release/2.0] Move CDI device spec out of the OCI package

- internal/cri/nri/nri_api_linux.go
- internal/cri/nri/nri_api_other.go
- internal/cri/server/container_create.go
- internal/cri/server/container_remove.go
- internal/cri/server/container_start.go
- internal/cri/server/container_stop.go
- internal/cri/server/container_update_resources.go
- internal/cri/server/sandbox_remove.go
- internal/cri/server/sandbox_run.go
- internal/cri/server/sandbox_stop.go
- internal/nri/nri.go
Update NRI deps to v0.8.0 and fix racy initial NRI plugin synchronization wrt. event processing by blocking plugin synchronization altogether during CRI event processing.
Notes: this PR does not pull in the latest tagged NRI version (v0.9.0) to keep the blast radius smaller. We can pull in NRI v0.9.0 if that is preferred. That would also pull in support for NRI WASM plugins and the related wazero and go-plugin dependency bits.
> [release/2.0] fix initial sync race of registering NRI plugins.

- plugins/sandbox/controller.go
Fix https://github.com/containerd/containerd/issues/11320
This is a shim-sandbox-controller side bug other than `LoadExistingShims`, as that function is also used in `TaskManager` and it passes the dirs correctly:
https://github.com/containerd/containerd/blob/8efbc01b9689ff254b7078fd59747a72f522b4db/core/runtime/v2/task_manager.go#L75
https://github.com/containerd/containerd/blob/8efbc01b9689ff254b7078fd59747a72f522b4db/core/runtime/v2/task_manager.go#L81
https://github.com/containerd/containerd/blob/8efbc01b9689ff254b7078fd59747a72f522b4db/core/runtime/v2/task_manager.go#L97-L98
> Fix state/root bug in shim sandbox controller

- go.mod
- integration/nri_linux_test.go
- integration/nri_test.go
- internal/cri/nri/nri_api_linux.go
The NRI plugins define hooks on the Pod and the Container lifecycle and provide contextual information for each of them in the corresponding hooks.
The StopPodSandbox hook already has the namespaces created and the plugins using that hook may require that information, so we should be able to do a best effort to pass it down to the NRI plugins.
NRI is the perfect complement to CNI for developing complex network integrations with the runtimes, since it allow to define priorities and create stateful plugins that run in the most important hooks of the Pod lifecycle, overcoming the current CNI limitations, this commit adds integration tests for this
> nri: make OCI spec available on StopPodSandbox

- RELEASES.md
This is an implementation of the changes the maintainers discussed around improving our release schedule and support lifecycle.
Major changes:
- Moving to time based releases, with releases initially every 6 months
- Changing the LTS policy to be as needed and supported by volunteer owners
- Scheduled date for 2.1 release (May 7th, 2025) along with proposed beta/rc timeframe
- Scheduled date for 2.2 release (November 5th, 2025, one year after 2.0 and a week before Kubecon NA)
- Setting End-of-Life for 1.6 (July 23rd, 2025, unless maintainers volunteer to extend this)
- Setting End-of-Life for 1.7 (March 10, 2026, unless maintainers volunteer to extend this)
- More roles and ownership of release process
> Update RELEASES.md for new release schedule and LTS policy

- .github/workflows/ci.yml
Matches the 1.7 and mainline release configuration for vagrant.
Testing if we can get `release/1.6` vagrant CI working again.
> [release/1.6] Update vagrant host OS to fix Vagrant CI runs

- integration/container_tty_leak_linux_test.go
- runtime/v2/runc/task/service.go
Backports https://github.com/containerd/containerd/pull/11161 to release/1.7 branch
The cherry-pick for https://github.com/containerd/containerd/pull/11161/commits/652e4d0b10490c4c2cfc94791ea80b5a16ff38ea is not clean as some of the test utility functions are slightly different in release/1.7 and I included a skip for runc shimv1 integration testing which does not support sandbox.
> [release/1.7] make sure console master tty is closed on task exit

- contrib/apparmor/apparmor.go
- contrib/seccomp/seccomp.go
- internal/cri/server/container_create_linux_test.go
go:noinline was added in https://github.com/containerd/containerd/pull/8957#issuecomment-1678829933 to workaround go func inline in go 1.21.
This PR removes the restriction by constructing a `sepcs.Spec`, calling the resulted `oci.SpecOpts`, comparing if the final `specs.Spec`s are still the same.
> Remove noinline in seccomp/apparmor SpecOpts

- internal/cri/server/sandbox_status.go
This reverts commit b5290726d2bfac0245de6d685dfd37ec9c1f4647.
Fixes: https://github.com/containerd/containerd/issues/11312
> Revert "Add timestamp to PodSandboxStatusResponse for kubernetes Evented PLEG"

- .golangci.yml
The latest golangci-lint-action enabled config schema check:
https://github.com/golangci/golangci-lint-action/releases/tag/v6.5.0
> Changes
feat: verify with the JSONSchema by default by @ldez in https://github.com/golangci/golangci-lint-action/pull/1171
On 1.7 release branch we are using golangci-lint version 1.60.3, which has removed the deprecated `skip-dirs` field ([see its json schema](https://github.com/golangci/golangci-lint/blob/master/jsonschema/golangci.v1.60.jsonschema.json)), thus failing the 1.7 CI.
It doesn't fail on 1.6 because we use version 1.55.0.
> [release/1.7] Move `run.skip-dirs` to `issues.exclude-dirs` in golangci-lint config

- .golangci.yml
The new golangci-lint action upgrade enabled golangci-lint config verification (from release note in https://github.com/containerd/containerd/pull/11397):
> v6.5.0
> What's Changed
> Changes
> feat: verify with the JSONSchema by default by [@​ldez](https://github.com/ldez) in [golangci/golangci-lint-action#1171]
That exposed a bug in our config where `issues.exclude-dirs` was put as `linters-settings.exclude-dirs` by accident:
https://github.com/containerd/containerd/actions/runs/13380233408/job/37367383920?pr=11397
```
jsonschema: "linters-settings" does not validate with "/properties/linters-settings/additionalProperties": additional properties 'exclude-dirs' not allowed
Failed executing command with error: the configuration contains invalid elements
```
The change was initially …
> Move `linters-settings.exclude-dirs` to `issues.exclude-dirs` in golangci-lint config

- plugins/snapshots/devmapper/pool_device_test.go
fix: https://github.com/containerd/containerd/issues/11347
/cc @deitch
> move the device after the options when using mkfs.ext4

- core/remotes/docker/fetcher.go
- pkg/archive/compression/compression.go
Hello there, with @co42, we found that decompressing zstd files with `zstd.WithDecoderLowmem(false),` improved unpacking performances for zstd blobs.
On the main branch the effect on total pull time is very limited, because we download a bit slowly. But this PR compounds greatly with #10177, we could lower download time by 14s ( from ~2min (with gzip, without #10177 and without #11337 ) to around ~30s (with zstd rebuild, #10177, with #11337 and this PR)  for a version of `ghcr.io/huggingface/text-generation-inference:3.0.2` that was rebuilt with `force-compression=true`.
| baseline WithDecoderLowmem(true)  (`time -v containerd`)                                             | after WithDecoderLowmem(false) (`time -v containerd`)                                               |   | …
> perf(zstd): deactivate the low mem decoder

- .github/actions/install-go/action.yml
- .github/workflows/api-release.yml
- .github/workflows/ci.yml
- .github/workflows/release.yml
- Vagrantfile
- contrib/Dockerfile.test
- contrib/fuzz/oss_fuzz_build.sh
- script/setup/prepare_env_windows.ps1
- build/release on go1.23.6
- add go1.24.0 into the CI matrix and remove go1.22.x
> [release/1.7] update build to go1.23.6, test go1.24.0

- docs/snapshotters/erofs.md
- plugins/snapshots/erofs/erofs_linux.go
- plugins/snapshots/erofs/erofs_linux_test.go
- plugins/snapshots/erofs/plugin/plugin_linux.go
Add fsverity support to erofs snapshotter to enable data integrity verification for erofs layers:
- Add an config option `EnableFsverity` for erofs snapshotter
- Add fsverity verification during mount operations
- Enable fsverity on erofs layers during commit
The feature can be enabled via config.toml, such as:
```toml
[plugins.'io.containerd.snapshotter.v1.erofs']
root_path = ''
ovl_mount_options = []
enable_fsverity = true
```
> erofs-snapshotter: add fsverity support

- integration/container_tty_leak_linux_test.go
- runtime/v2/runc/task/service.go
cherry-pick of https://github.com/containerd/containerd/pull/11161
supersedes #11322 with fixes to backport incompatibilities.
> [release/1.6] make sure console master tty is closed on task exit

- .github/workflows/ci.yml
GHA now provides ARM runners for free
https://github.blog/changelog/2025-01-16-linux-arm64-hosted-runners-now-available-for-free-in-public-repositories-public-preview/
> CI: arm64-8core-32gb -> ubuntu-24.04-arm

- pkg/imageverifier/bindir/bindir_test.go
Fixes https://github.com/containerd/containerd/issues/11417
This test produces zombies when PID 1 does not properly reap child processes. Modifies the test to ignore these processes in the meantime.
@samuelkarp @lalitc375
> Ignore defunct verifier procs in test

- pkg/oom/v1/v1.go
- pkg/oom/v2/v2.go
Compared with package `pkg/shim`, package `core/events` is more suitable as the dependency for the oom watcher functions(`pkg/oom`).
> pkg: prevent oom watcher from depending on shim pkg

- releases/v1.6.37.toml
- version/version.go
----
containerd 1.6.37
Welcome to the v1.6.37 release of containerd!
The thirty-seventh patch release for containerd 1.6 contains various fixes
and updates.
* Update runc binary to v1.2.5 ([#11396](https://github.com/containerd/containerd/pull/11396))
* Fix the race condition during GC of snapshots when client retries ([#10764](https://github.com/containerd/containerd/pull/10764))
* Update the container exit log to info level ([#11008](https://github.com/containerd/containerd/pull/11008))
* Handle teardown failure to avoid blocking cleanup ([#10778](https://github.com/containerd/containerd/pull/10778))
* Add check for CNI plugins before tearing down pod network ([#10766](https://github.com/containerd/containerd/pull/10766))
* Fix console TTY leak in runc shim …
> Prepare release notes for v1.6.37

- releases/v1.7.26.toml
- version/version.go
--
containerd 1.7.26
Welcome to the v1.7.26 release of containerd!
The twenty-sixth patch release for containerd 1.7 contains various fixes
and updates.
* Add support for syncfs after unpack ([#11267](https://github.com/containerd/containerd/pull/11267))
* Update runc binary to v1.2.5 ([#11395](https://github.com/containerd/containerd/pull/11395))
* Fix race between serve and immediate shutdown on the server ([containerd/ttrpc#175](https://github.com/containerd/ttrpc/pull/175))
* Reject oversized messages from the sender ([containerd/ttrpc#171](https://github.com/containerd/ttrpc/pull/171))
* Fix fatal concurrency error in port forwarding ([#11306](https://github.com/containerd/containerd/pull/11306))
* Fix initial sync race when registering NRI plugins …
> [release/1.7] Prepare release notes for v1.7.26

- core/runtime/v2/task_manager.go
Previously, PluginInfo was called with task options as the primary value, resulting in opts.BinaryName being omitted. Consequently, the containerd-shim-runc-v2 fell back to the system's runc binary in the PATH rather than the explicitly specified one. This change inverts the option fallback by preferring runtime options over task options, ensuring the correct binary is used for the PluginInfo request.
At Netflix, we maintain runc in both /usr/bin (which lacks support for user namespaces) and at a custom path. This issue surfaced when enabling user namespaces and encountering the error:
Error: failed to create containerd task: failed to validate OCI runtime
features: idmap mounts not supported: missing `mountExtensions.idmap`
entry in the `features` command
Although the `features` command …
> Prefer runtime options for PluginInfo request

- go.mod
- go.sum
- vendor/modules.txt
- vendor/tags.cncf.io/container-device-interface/pkg/cdi/cache.go
Update CDI dependency to v0.8.1. That pulls in a fix for a SIGSEGV/panic, which in principle could be triggered if we're out of file descriptors while we're instantiating the CDI cache.
> [release/2.0] go.{mod,sum}: bump CDI deps to v.0.8.1.

- internal/cri/nri/nri_api_linux.go
- internal/cri/nri/nri_api_other.go
- internal/cri/server/container_create.go
- internal/cri/server/container_remove.go
- internal/cri/server/container_start.go
- internal/cri/server/container_stop.go
- internal/cri/server/container_update_resources.go
- internal/cri/server/sandbox_remove.go
- internal/cri/server/sandbox_run.go
- internal/cri/server/sandbox_stop.go
- internal/nri/nri.go
This is essentially #11329 cherry-picked to the main branch.
Update NRI deps to v0.8.0 and fix racy initial NRI plugin synchronization wrt. event processing by blocking plugin synchronization altogether during CRI event processing.
Notes: this PR does not pull in the latest tagged NRI version (v0.9.0) to keep the blast radius smaller. We can pull in NRI v0.9.0 if that is preferred. That would also pull in support for NRI WASM plugins and the related wazero and go-plugin dependency bits.
> cri,nri: fix initial sync race of registering NRI plugins.

- core/content/proxy/content_writer.go
- core/content/testsuite/testsuite.go
- backport https://github.com/containerd/containerd/pull/11441
- fixes https://github.com/containerd/containerd/issues/11440
The remote content writer proxy already has the capability to break up
large files into multiple writes, but the current API doesn't recognize
when it's about to exceed the limits and attempts to send the data over
grpc in one message instead of breaking it into multiple messages.
This changes the behavior of `Write` to automatically break up the size
of the content based on the max send message size.
(cherry picked from commit f25f36c334144d87233e06b0de90522ebd97e144)
> [release/2.0] Update remote content to break up writes to avoid grpc message size limits

- releases/v2.0.3.toml
- version/version.go
----
containerd 2.0.3
Welcome to the v2.0.3 release of containerd!
The third patch release for containerd 2.0 includes various bug fixes and updates.
* Update remote content to break up writes to avoid grpc message size limits ([#11457](https://github.com/containerd/containerd/pull/11457))
* Update runc binary to v1.2.5 ([#11394](https://github.com/containerd/containerd/pull/11394))
* Fix privileged container sysfs can't be rw because pod is ro by default ([#11456](https://github.com/containerd/containerd/pull/11456))
* Fix recursive RLock() mutex acquisition ([containerd/go-cni#126](https://github.com/containerd/go-cni/pull/126))
* Fix initial sync race when registering NRI plugins ([#11329](https://github.com/containerd/containerd/pull/11329))
Please try out the release …
> [release/2.0] Prepare release notes for v2.0.3

- internal/cri/server/service.go
As 'Kubelet Evented PLEG' is still alpha not having any subscribers to CRI events is pretty normal, so lower the log level.
Fixes #11108 
CC @dmcgowan
> Log "container event discarded" as Info

- containerd.service
As we are not setting `DefaultDependencies=no`, containerd.service
'will have dependencies of type Requires= and After= on sysinit.target'
https://www.freedesktop.org/software/systemd/man/latest/systemd.service.html#Default%20Dependencies
and sysinit.target already has After=local-fs.target
https://www.freedesktop.org/software/systemd/man/latest/bootup.html#System%20Manager%20Bootup
Reported-by: @VannTen (https://github.com/containerd/containerd/pull/10798#issuecomment-2519644335)
> Remove After=local-fs.target from containerd.service

- docs/snapshotters/erofs.md
- plugins/snapshots/erofs/erofs_linux.go
1. force the use of loop devices for single-layer images
```
Currently, containerd cannot dynamically select between EROFS block
or file-based mounting approaches based on the specific runtime (or
the Linux kernel version of the runtime) due to its static mount
structure.
For example, the EROFS snapshotter fails on Linux 5.4 (Ubuntu 20.04)
with `bin/nerdctl run --net=host --snapshotter=erofs busybox:latest`:
FATA[0005] failed to mount {Type:erofs Source:/var/lib/containerd/
io.containerd.snapshotter.v1.erofs/snapshots/1/layer.erofs Target:
Options:[ro]} on "/tmp/initialC1374142795": block device required
Temporarily fix this by appending `-oloop` for single-layer images.
The upcoming mount manager will make it better.
```
2. clear IMMUTABLE_FL only for committed snapshots
```
Otherwise, …
```
> erofs-snapshotter: two bug-fixes

- docs/cri/config.md
It seems that runtime_path is missing in the Full configuration of CRI Plugin Config.
> docs: add CRI Plugin Config runtime_path

- plugins/snapshots/devmapper/blkdiscard/blkdiscard.go
- plugins/snapshots/devmapper/pool_device.go
fix:https://github.com/containerd/containerd/issues/11328
busybox image 
```
/ # blkdiscard --version
blkdiscard: unrecognized option '--version'
BusyBox v1.36.1 (2023-12-04 19:44:32 UTC) multi-call binary.
Usage: blkdiscard [-o OFS] [-l LEN] [-s] DEVICE
Discard sectors on DEVICE
-o OFS  Byte offset into device
-l LEN  Number of bytes to discard
-s      Perform a secure discard
```
> device mapper:fix sometimes blkdiscard doesn't have --version flags

- contrib/gce/configure.sh
use the shim bundled with cri-cni-containerd tar rather than using the shim present on the host machine for running e2e
Fixes: https://github.com/kubernetes/kubernetes/issues/130590
> e2e: use the shim bundled with containerd artifact

- .github/workflows/release.yml
Ubuntu 20.04 GitHub Actions runners are deprecated. This change updates the release runner to use Ubuntu 24.04.
https://github.com/actions/runner-images/issues/11101
> ci: update GitHub Actions release runner to ubuntu-24.04

- go.mod
- go.sum
- vendor/github.com/opencontainers/runtime-spec/specs-go/config.go
- vendor/github.com/opencontainers/runtime-spec/specs-go/version.go
- vendor/modules.txt
Update runtime-spec to v1.2.1
Full changelist can be found here: https://github.com/opencontainers/runtime-spec/compare/v1.2.0...v1.2.1
> Update runtime-spec to v1.2.1

- core/images/image.go
- core/images/mediatypes.go
- core/remotes/handlers.go
- fixes: https://github.com/moby/moby/issues/49042
Fix unnecessary log spam when dealing with BuildKit images containing attestation manifests.
Before this patch, calling `image.Children` on an image built with BuildKit would produce unnecessary `encountered unknown type application/vnd.in-toto+json; children may not be fetched` debug logs, because the media type is neither a known layer or config type.
Make the `image.Children` aware of the attestation layers and don't attempt to traverse them.
Don't produce `reference for unknown type: application/vnd.in-toto+json` warning logs when pushing/fetching an image containing the attestation manifests.
> Don't produce unnecessary logs when encountering attestations

- .devcontainer/devcontainer.json
- .github/actions/install-go/action.yml
- .github/workflows/api-release.yml
- .github/workflows/ci.yml
- .github/workflows/release.yml
- Vagrantfile
- contrib/Dockerfile.test
- contrib/fuzz/oss_fuzz_build.sh
- script/setup/prepare_env_windows.ps1
- go1.23.7 (released 2025-03-04) includes security fixes to the net/http package, as well as bug fixes to cgo, the compiler, and the reflect, runtime, and syscall packages. See the [Go 1.23.7 milestone](https://github.com/golang/go/issues?q=milestone%3AGo1.23.7+label%3ACherryPickApproved) on our issue tracker for details
- go1.24.1 (released 2025-03-04) includes security fixes to the net/http package, as well as bug fixes to cgo, the compiler, the go command, and the reflect, runtime, and syscall packages. See the [Go 1.24.1 milestone](https://github.com/golang/go/issues?q=milestone%3AGo1.24.1+label%3ACherryPickApproved) on our issue tracker for details.
> [release/2.0] update build to go1.23.7, test go1.24.1

- .devcontainer/devcontainer.json
- .github/actions/install-go/action.yml
- .github/workflows/api-release.yml
- .github/workflows/ci.yml
- .github/workflows/release.yml
- Vagrantfile
- contrib/Dockerfile.test
- contrib/fuzz/oss_fuzz_build.sh
- script/setup/prepare_env_windows.ps1
- go1.23.7 (released 2025-03-04) includes security fixes to the net/http package, as well as bug fixes to cgo, the compiler, and the reflect, runtime, and syscall packages. See the [Go 1.23.7 milestone](https://github.com/golang/go/issues?q=milestone%3AGo1.23.7+label%3ACherryPickApproved) on our issue tracker for details
- go1.24.1 (released 2025-03-04) includes security fixes to the net/http package, as well as bug fixes to cgo, the compiler, the go command, and the reflect, runtime, and syscall packages. See the [Go 1.24.1 milestone](https://github.com/golang/go/issues?q=milestone%3AGo1.24.1+label%3ACherryPickApproved) on our issue tracker for details.
> update to go1.23.7 / go1.24.1

- .github/actions/install-go/action.yml
- .github/workflows/ci.yml
- .github/workflows/release.yml
- .golangci.yml
- Vagrantfile
- contrib/Dockerfile.test
- script/setup/prepare_env_windows.ps1
- go1.23.7 (released 2025-03-04) includes security fixes to the net/http
package, as well as bug fixes to cgo, the compiler, and the reflect,
runtime, and syscall packages. See the Go 1.23.7 milestone on our issue
tracker for details
- go1.24.1 (released 2025-03-04) includes security fixes to the net/http
package, as well as bug fixes to cgo, the compiler, the go command, and
the reflect, runtime, and syscall packages. See the Go 1.24.1 milestone
on our issue tracker for details.
> [release/1.6] update build to go1.23.7, test go1.24.1

- RELEASES.md
> add k8s 1.32 to support table and as tested containerd supported branches at the time of release

- internal/nri/nri.go
- version/version.go
cherry-pick from https://github.com/containerd/containerd/pull/11518/commits
> [release/2.0] Fix incorrect runtime name being passed to NRI

- client/client.go
- related to: https://github.com/containerd/containerd/issues/11507
Fix the gRPC client dialer not using the timeout passed by the containerd client timeout option.
Commit 63b4688175 replaced the usage of deprecated `grpc.DialContext` with `grpc.NewClient`.
However, the `dialer.ContextDialer` relied on the context deadline to propagate the timeout:
https://github.com/containerd/containerd/blob/388fb336b0a458e2cf64212072743e622a3f44c7/vendor/google.golang.org/grpc/clientconn.go#L216
This assumption is now broken, because `grpc.NewClient` doesn't do any initial connection and defers it to the first RPC usage.
This commit passes the timeout to the connection dialer, so the timeout will be applied to **every** connection attempt (not just the first).
Signed-off-by: Paweł Gronowski …
> client: Respect `client.WithTimeout` option

- integration/client/export_test.go
I am verifying some lint idea in my project see https://github.com/alingse/sundrylint/pull/10
it report the function call with repeat args from a sub-function call.
we think the sub-function call is heavy, so the repeat args probably a copy-and-paste mistake.
I check the top 200 github repos, and found this repo has this case.
> fix: repeat args from sub-func call

- releases/v1.6.38.toml
- version/version.go
----
containerd 1.6.38
Welcome to the v1.6.38 release of containerd!
The thirty-eighth patch release for containerd 1.6 contains various fixes
and updates.
* Fix fatal map concurrency error in httpstream ([#11319](https://github.com/containerd/containerd/pull/11319))
* Jin Dong
* Akhil Mohan
* Phil Estes
* Akihiro Suda
* Kohei Tokunaga
* Samuel Karp
* ningmingxiao
<details><summary>16 commits</summary>
<p>
* [`eee34bac2`](https://github.com/containerd/containerd/commit/eee34bac2c401b3e4381594e99f6220bf8258c9c) Prepare release notes for v1.6.38
* update build to go1.23.7, test go1.24.1 …
> [release/1.6] Prepare release notes for v1.6.38

- .mailmap
- releases/v1.7.27.toml
- version/version.go
----
containerd 1.7.27
Welcome to the v1.7.27 release of containerd!
The twenty-seventh patch release for containerd 1.7 contains various fixes
and updates.
* Akhil Mohan
* Jin Dong
* Phil Estes
* Akihiro Suda
* Krisztian Litkey
* Samuel Karp
<details><summary>13 commits</summary>
<p>
* update build to go1.23.7, test go1.24.1 ([#11515](https://github.com/containerd/containerd/pull/11515))
* [`a39863c9f`](https://github.com/containerd/containerd/commit/a39863c9fd52abb50895a4b6f653cf501a2e3388) update build to go1.23.7, test go1.24.1
* Remove hashicorp/go-multierror dependency and fix CI ([#11499](https://github.com/containerd/containerd/pull/11499)) …
> [release/1.7] Prepare release notes for v1.7.27

- releases/v2.0.4.toml
- version/version.go
----
containerd 2.0.4
Welcome to the v2.0.4 release of containerd!
The fourth patch release for containerd 2.0 includes various bug fixes and updates.
* Respect `client.WithTimeout` option on connect ([#11536](https://github.com/containerd/containerd/pull/11536))
* Update image type checks to avoid unnecessary logs for attestations ([#11537](https://github.com/containerd/containerd/pull/11537))
* Fix incorrect runtime name being passed to NRI ([#11529](https://github.com/containerd/containerd/pull/11529))
* Akihiro Suda
* Paweł Gronowski
* Akhil Mohan
* Phil Estes
* Samuel Karp
* ningmingxiao
<details><summary>16 commits</summary>
<p>
* …
> [release/2.0] Prepare release notes for v2.0.4

- pkg/oci/spec_opts.go
- pkg/oci/spec_opts_linux_test.go
- duplicated by / closes https://github.com/containerd/containerd/pull/11559
https://github.com/containerd/containerd/actions/runs/13911860592/job/38927588065?pr=11554
```
Error: pkg/oci/spec_opts_linux_test.go:108:3: The copy of the 'for' variable "testCase" can be deleted (Go 1.22+) (copyloopvar)
testCase := testCase
^
Error: pkg/oci/spec_opts.go:598:1: File is not properly formatted (gofmt)
// and the OCI Runtime Spec has no definition about the max UID,
^
```
> Fix CI lint error

- RELEASES.md
- docs/cri/config.md
- internal/cri/config/config.go
- internal/cri/config/config_test.go
- internal/cri/config/config_unix.go
- internal/cri/config/config_windows.go
- internal/cri/server/service_linux.go
- internal/cri/server/service_windows.go
- pkg/deprecation/deprecation.go
- plugins/cri/runtime/plugin.go
- plugins/cri/runtime/plugin_test.go
Fix https://github.com/containerd/containerd/issues/10710, this PR adds a new cri CNI config `bin_dirs` that is similar to `bin_dir` but accepts a list of bin dirs. This PR includes:
commit 1: support his new `bin_dirs` field:
1. Add this new `bin_dirs` field;
2. In `ValidateRuntimeConfig`, make sure only one of `bin_dir` and `bin_dirs` is set.
commit 2: make `bin_dirs` as default, and migrate `bin_dir` to `bin_dirs`:
1. Change default to setting `bin_dirs` instead of `bin_dir`.
2. Mark `bin_dir` as DEPRECATED.
3. In ConfigMigration, migrate `bin_dir` in version 2 to `bin_dirs` in version 3.
4. Add a deprecation warning for `bin_dir`.
> Support multiple cni plugin bin dirs

- internal/cri/config/config.go
This patch primarily aims to align the TOML and JSON formats for the ``MaxContainerLogLineSize`` configuration  in CRI.
> Update max container log line size json field

- .devcontainer/setup.sh
- .github/workflows/ci.yml
- script/setup/install-cni
Many PRs have been blocked, especially some with label `cherry-pick/2.0`
The [issue](https://github.com/containernetworking/plugins/issues/1121) had been over 4 months
`CNI plugins` is not the focus in e2e test, and updates and releases here should also not be blocked by `CNI plugins`
cc @AkihiroSuda
> downgrade cni version in CI test

- core/runtime/v2/shim.go
When containerd restarts and the shim connection is successfully restored, but stopping the container at this time will result in an error log due to using the wrong context
1 start pod 
```
crictl runp [pod.json]
crictl create [sandboxid] [container.json] [pod.json]
crictl start [containerid]
```
2 restart containerd.
3 stop pod by `crictl stop [containerid]
containerd log:
```
...
ERRO[2025-03-04T16:03:02.137448237+08:00] copy shim log after reload                    error="read /proc/self/fd/10: file already closed" namespace=k8s.io
...
```
Introduced by https://github.com/containerd/containerd/pull/5174
> fix: call checkCopyShimLogError(shimCtx) to avoid expected error log flood

- go.mod
- go.sum
- integration/client/go.sum
- vendor/github.com/go-jose/go-jose/v3/jwe.go
- vendor/github.com/go-jose/go-jose/v3/jws.go
- vendor/modules.txt
Updates the indirect dependency of go-jose to v3.0.4. 
This update is mainly to silence the scanners for [CVE-2025-27144](https://github.com/advisories/GHSA-c6gw-w398-hv78), although containerd itself is not affected. 
`go-jose/v3` is a dependency of `github.com/containers/ocicrypt` which is a dependency of `github.com/containerd/imgcrypt`. Directly updating `imgcrypt` also updates min go version to 1.23.0 and also moves to `go-jose/v4`, which seemed like a larger change than just updating the dependency directly.
> [release/1.7] vendor: github.com/go-jose/go-jose/v3 v3.0.4

- internal/cri/server/podsandbox/events.go
When the RunPodSandbox interface fails due to an upstream context cancellation or other reasons, HandleEvent encounters a nil pointer because the PodSandbox.Container field is nil, resulting in a panic.
I discovered this issue in the kubernetes/kubernetes repository.
PR https://github.com/kubernetes/kubernetes/pull/127122 aims to address this by passing the context to the container runtime, resolving the issue where container creation and image pulling actions cannot be canceled.
Previously, the tests in this PR worked fine, but after the CI in the k/k repository switched to containerd 2.0, many tests in this PR started failing.
While investigating the error, I captured the following error in the containerd logs:
```
Mar 23 14:25:14 kind-worker containerd[15009]: …
```
> Fix the panic caused by the failure of RunPodSandbox

- defaults/defaults_linux.go
- defaults/defaults_unix_nolinux.go
- plugins/transfer/plugin_defaults_other.go
Set default differ for the default unpack config of transfer service.
Without explicit "unpack_config" configuration for the Transfer plugin, the plugin will pick the first Diff plugin that matches the platform. In my tests it selected the "erofs" diff plugin.
Without this change:
```
$ sudo ctr i pull docker.io/library/hello-world:latest
....
application/vnd.oci.image.index.v1+json sha256:7e1a4e2d11e2ac7a8c3f768d4166c2defeb09d2a750b010412b6ea13de1efb19
Pulling from OCI Registry (docker.io/library/hello-world:latest)        elapsed: 3.3 s  total:  41.2 K  (12.6 KiB/s)
ctr: rpc error: code = Unimplemented desc = method Transfer not implemented for containerd.types.transfer.OCIRegistry to containerd.types.transfer.ImageStore
```
Error logs shows:
```
Apr 01 21:23:33 ip-172-31-63-131 …
```
> Set default differ for the default unpack config of transfer service

- core/remotes/docker/config/hosts.go
If `host.caCerts, host.clientPairs, host.skipVerify` are all `nil` and `host.skipVerify` not `nil`, `explicitTLS` will be set to be `true` instead of `false`. It was introduced in a recent PR (https://github.com/containerd/containerd/pull/11106/files#diff-e7f5d2c5cace7ca9b430942cd78869ccd2afca84505360099e61090d207605bfL169-L170)
Also made a refactor (commit2) to move host TLSConfig update to a separate function. The current `ConfigureHosts` is a bit too long and not easy to follow.
> [hosts] wrong explicitTLS value when dialTimeout is set

- .github/workflows/release.yml
- .github/workflows/release/Dockerfile
- releases/v2.1.0-beta.toml
Upgrade to Ubuntu 22.04, as Ubuntu 20.04 is no longer supported.
EL8 (glibc 2.28) and EL9 (glibc 2.34) users may have to use static binaries, Docker's RPMs, or their own builds.
> release: use Ubuntu 22.04 (glibc 2.35)

- defaults/defaults_snapshotter_linux.go
- defaults/defaults_snapshotter_unix.go
- plugins/transfer/plugin_defaults_other.go
(cherry picked from commit a083b669c9412eef55ee103fe2bb1dec7c6178bc)
Cherry-pick (backport due to reorganization of defaults) of #11641
> [release/2.0] backport: Set default differ for the default unpack config of transfer service

- internal/cri/server/container_create.go
- internal/cri/server/service.go
- internal/cri/server/status.go
This patch changes `criService.runtimeHandlers` from
a slice to a map, so we don't need to for-loop slice
in `createContainer`.
It also refactors `introspectRuntimeHandler` a bit
so it can be called given a single `config.Runtime`.
This will help implement extracting runtime config
to separate files (https://github.com/containerd/containerd/issues/9296).
> change criService.runtimeHandlers slice to a map

- core/remotes/docker/auth/fetch.go
- core/remotes/docker/authorizer.go
- core/remotes/docker/resolver_test.go
- core/remotes/docker/scope.go
https://docs.docker.com/registry is deprecated and doesn't have that content
anymore, link to https://distribution.github.io/distribution instead.
Signed-off-by: Alberto Garcia Hierro <damaso.hierro@docker.com>
> chore: fix broken links to https://docs.docker.com/registry

- .devcontainer/devcontainer.json
- .github/actions/install-go/action.yml
- .github/workflows/api-release.yml
- .github/workflows/ci.yml
- .github/workflows/release.yml
- Vagrantfile
- contrib/Dockerfile.test
- contrib/fuzz/oss_fuzz_build.sh
- script/setup/prepare_env_windows.ps1
- update go 1.24.2, 1.23.8 for build and testing
- use go1.23.8 as the default go version for running in CI and making release binaries.
NOTE: This is done so that when release/2.1 branch cut happens, the 2.1 release uses 1.23.x for building release binaries rather than 1.24.x. Once the 2.1 release is out, this patch will be reverted and go1.24.x will be made the default in the main branch
> ci: update go 1.24.2, 1.23.8

- releases/v2.0.5.toml
- version/version.go
Changes to release script tested at https://github.com/dmcgowan/containerd/actions/runs/14508353681
----
containerd 2.0.5
Welcome to the v2.0.5 release of containerd!
The fifth patch release for containerd 2.0 includes various bug fixes and updates.
* Update ImageService to delete images synchronously ([#11599](https://github.com/containerd/containerd/pull/11599))
* Prevent panic on zero length push ([#11698](https://github.com/containerd/containerd/pull/11698))
* Set default differ for the default unpack config of transfer service ([#11688](https://github.com/containerd/containerd/pull/11688))
* Update taskOptions based on runtimeOptions when creating a task ([#11618](https://github.com/containerd/containerd/pull/11618)) …
> [release/2.0] Prepare release notes for v2.0.5

- .devcontainer/devcontainer.json
- .github/actions/install-go/action.yml
- .github/workflows/api-release.yml
- .github/workflows/ci.yml
- .github/workflows/release.yml
- Vagrantfile
- contrib/Dockerfile.test
- contrib/fuzz/oss_fuzz_build.sh
- script/setup/prepare_env_windows.ps1
Backport of #11705 modified for 2.0, keeps 1.23.8 as the version for releases and includes update to 1.24.2 for build and test
> [release/2.0] Update go to 1.23.8

- core/remotes/docker/authorizer.go
- core/remotes/docker/config/hosts.go
- core/remotes/docker/config/hosts_resolver_test.go
- core/remotes/docker/resolver.go
- internal/cri/server/images/image_pull.go
Fix #8912
This PR fixes 3 issues:
1. `containerd/version` is added as user-agent first. This will overwrite customized user-agent header, as golang only read [the first `User-Agent` value](https://github.com/golang/go/blob/go1.23.0/src/net/http/h2_bundle.go#L9188-L9191).
2. per-host headers in `hosts.toml` are not attached to auth requests.
3. global headers in `cri.config.registry.header` are not attached to auth requests.
**Test**
With this hosts.toml and containerd config:
```toml
server = "registry-1.docker.io"
[header]
User-Agent = "server-agent"
x-server-custom-1 = "custom server header"
[host."registry-1.docker.io".header]
User-Agent = "mirror-agent"
x-mirror-custom-1 = "custom mirror header"
[plugins.'io.containerd.cri.v1.images'.registry]
config_path = '/etc/containerd/certs.d' …
```
> Add cri headers and hosts.toml header to auth requests

- client/container.go
- client/task.go
1. Fix the error variable used in the defer function within the `Restore` method.
2. Ensure consistent variable naming in the same context for the other two locations in *./client*
> client: fix returned error in the defer function

- plugins/diff/erofs/differ_linux.go
- plugins/snapshots/erofs/erofsutils/mount_linux.go
Unlike the walking differ, which implements a generic method to accommodate all kinds of snapshotters, the EROFS differ is just implemented for EROFS and EROFS snapshotter so it can utilize the recent [DiffDirChanges()](https://github.com/containerd/continuity/pull/145) to avoid traversing the entire rootfs directory in order to improve `nerdctl commit` performance.
Additionally, I think `baseDir` is unnecessary too (in principle, only `upperdir` is useful for OCI format convention).  However, addressing this requires more work, so left as is for now.
It's also useful to implement a customized Compare() method for EROFS differ so that we can dump the native EROFS-formatted blob to the content store later.
> erofs-differ: implement fast differ with DiffDirChanges()

- integration/issue10467_linux_test.go
- integration/release_upgrade_linux_test.go
- integration/release_upgrade_utils_linux_test.go
Update release upgrade tests to test 1.7 and 2.0
Fix 1.7 config to match previous version which allowed upgrade to 2.x.
NOTE: 
I might be slightly misunderstanding how the shim load will work after upgrade, but it seems there is still valid configurations for 1.7 that would not load, although possibly cases that a normal user would not run into. It seems the `runtime_path` for 1.7 will not be respected after upgrade and it will fallback to resolving based on the runtime type. This needs to be investigated more but was not previously covered by these tests. The issues manifests as the shim manager attempting to connect to the older shim with task v3.
> Fix upgrade tests for 1.7

- .github/workflows/ci.yml
Vagrant setup is broken in all branches due to dependency resolution conflict:
```bash
$ vagrant plugin install vagrant-libvirt
...
Installing the 'vagrant-libvirt' plugin. This can take a few minutes...
Vagrant failed to properly resolve required dependencies. These
errors can commonly be caused by misconfigured plugin installations
or transient network issues. The reported error is:
conflicting dependencies csv (= 3.2.8) and csv (= 3.3.4)
Activated csv-3.3.4
which does not match conflicting dependency (= 3.2.8)
Conflicting dependency chains:
csv (= 3.3.4), 3.3.4 activated
versus:
csv (= 3.2.8)
Gems matching csv (= 3.2.8):
csv-3.2.8
```
The workaround suggested in https://github.com/hashicorp/vagrant/issues/13510#issuecomment-2431163553 seems to work.
> [CI] Fix vagrant

- internal/cri/server/container_create.go
- internal/cri/server/podsandbox/controller.go
- internal/cri/server/podsandbox/types/podsandbox.go
Fix #11708 
The exit of the `work container` will call `shutdown` at 1.7, but only call `shutdown` when the sandbox exits at 2.0.
```
// some processes about shim.Task
kill    ->    delete    ->   shutdown     
( callback by backoff by wait )
// https://github.com/containerd/containerd/blob/fb4c30d4ede3531652d86197bf3fc9515e5276d9/core/runtime/v2/shim.go#L529-L532C46
// Don't shutdown sandbox as there may be other containers running.
// Let controller decide when to shutdown.
if !sandboxed {
if err := s.waitShutdown(ctx); err != nil {
```
Based on the above code, it seems to be an issue with gvisor, and the shim connection (write close at shim side) should be closed when call `delete` rpc.
Above, could solve problem #11708, but not sure it's worth.
If there were clearer documentation …
> cri: do not set sandbox id when using podsandbox type

- internal/cri/server/container_create.go
- internal/cri/server/podsandbox/controller.go
- internal/cri/server/podsandbox/types/podsandbox.go
(cherry picked from commit 4b4e6f7c693e3739deed20ed5832ede137b41b3e)
This is a manual cherry-pick of https://github.com/containerd/containerd/pull/11735 since there were merge conflicts.  Opening as a draft until https://github.com/containerd/containerd/pull/11735 is merged.
> [release/2.0] Fix issue preventing some v2 shims from shutting down properly

- remotes/docker/auth/fetch.go
- remotes/docker/authorizer.go
Cherry-pick  https://github.com/containerd/containerd/pull/8735 to 1.7
Got bitten by this on our workloads when pulling large container images. It'd great to have this patch in current LTS.
(depends on CI changes in https://github.com/containerd/containerd/pull/11722)
> [release 1.7] remotes/docker/authorizer.go: invalidate auth tokens when they expire.

- core/snapshots/storage/metastore.go
- plugins/metadata/plugin.go
This PR exposes BoltDB options via TOML configuration.
On certain ephemeral environments its possible to squeeze a significant performance gains via more precise boltDB configuration by going async.
In our case we were able to reduce pull time under certain (heavy) conditions from 30s to just a few seconds.
Additionally this PR introduces optional args in `MetaStore` to allow (external) snapshotters configure boltDB options for same reasons.
```toml
bin/containerd config default
[plugins.'io.containerd.metadata.v1.bolt']
content_sharing_policy = 'shared'
no_sync = true
```
Troubleshooting and research credits belong to @xinyangge-db 
> We found that the checkpoint image pull timeout is due to frequent lock contentions on containerd’s metadata db, and the lock contention occurs because …
> Add no_sync option to boost boltDB performance on ephemeral environments

- internal/cri/server/metrics.go
This was producing different metric names which can break metric collection. Reverting to the previous "cri" subsystem so metrics are consistent across 1.X and 2.X.
Fixes #11745
> Revert criserver metrics subsystem back to cri

- client/client.go
- client/services.go
- core/transfer/registry/registry.go
- docs/cri/config.md
- integration/build_local_containerd_helper_test.go
- integration/build_local_containerd_helper_test_linux.go
- integration/client/restart_monitor_test.go
- integration/image_pull_timeout_test.go
- internal/cri/config/config.go
- internal/cri/config/config_test.go
- internal/cri/server/images/image_pull.go
- internal/cri/server/images/image_pull_test.go
- internal/cri/server/images/service.go
- plugins/cri/images/plugin.go
- plugins/transfer/plugin.go
- plugins/types.go
This PR is to update CRI to optionally use transfer service for image pull.  
Part of #8227 
1. Create a new CRI config `ImagePullWithTransferService` to specify whether to use transfer service for image pull
2. Move CRI image pull related configs to server side, i.e. transfer service. 
The PR is still in progress, put out to for early review and utilize CI for integration tests.
> Update CRI to use transfer service for image pull by default

- plugins/diff/erofs/differ_linux.go
- Based on https://github.com/containerd/containerd/pull/11744
If the layer media type is expected as an EROFS native layer, copy the content as the layer blob.
> erofs-differ: support EROFS native image layers

- .golangci.yml
- internal/cri/bandwidth/linux.go
- internal/lazyregexp/lazyregexp.go
- internal/lazyregexp/lazyregexp_test.go
- pkg/identifiers/validate.go
- pkg/progress/writer.go
- pkg/reference/reference.go
- pkg/sys/filesys_windows.go
- similar to https://github.com/moby/moby/pull/48166
Based on the "lazyregexp" package in golang.org/x/mod;
https://cs.opensource.google/go/x/mod/+/refs/tags/v0.19.0:internal/lazyregexp/lazyre.go;l=66-78
This package allows defining regular expressions that should not be
compiled until used, but still providing validation to prevent
invalid regular expressions from producing a panic at runtime.
The lazyregexp package provides a subset of the methods provided
by "regexp" and only implements the methods used in the codebase.
Additional methods can be added when needed.
> use lazyregexp to compile regexes on first use

- core/unpack/unpacker.go
- plugins/transfer/plugin.go
The snapshotter and differ are fully plug-able today, however experimentation can be limited by the media types supported by unpack. This change allows specifying the config and layer media types to use for a platform unpack configuration alongside the snapshotter and differ.
Experimentation for new types is still limited to using the platform and rootfs keys defined by OCI. Anything beyond that would need something much different than the current unpacker anyway. This adds stricter checks for the rootfs field type when unpacking an OCI image. OCI requires this value to be set to "layers", however we should also consider an empty value the same as layers to avoid breaking. Any non-"layers" value can be used for experimentation though.
> Add support for unpacking custom media types 

- api/releases/v1.9.0-rc.toml
Relatively small release. The first rc will begin the 2.1 freeze.
Items to merge before rc.0
---
containerd api/v1.9.0-rc.0
Welcome to the api/v1.9.0-rc.0 release of containerd!  
The 10th release for the containerd 1.x API aligns with the containerd 2.1 release.
* Akihiro Suda
* Davanum Srinivas
* Phil Estes
* Adrian Reber
* Jin Dong
* Philip Laine
<details><summary>11 commits</summary>
<p>
* [`ac594cec3`](https://github.com/containerd/containerd/commit/ac594cec33654a733191aff46416e2979cf46068) Add release notes for api v1.9.0-rc.0
* Add content create event ([#11006](https://github.com/containerd/containerd/pull/11006))
* …
> Add release notes for api v1.9.0-rc.0

- .mailmap
- RELEASES.md
- go.mod
- go.sum
- releases/v2.1.0-rc.toml
- vendor/github.com/containerd/containerd/api/LICENSE
- vendor/modules.txt
- version/version.go
This will officially begin the 2.1 freeze
---
containerd 2.1.0-rc.0
Welcome to the v2.1.0-rc.0 release of containerd!  
The first minor release of containerd 2.x focuses on continued stability alongside
new features and improvements. This is the first time-based released for containerd.
Most the feature set and core functionality has long been stable and harderened in production
environments, so now we transition to a balance of timely delivery of new functionality
with the same high confidence in stability and performance.
* Add no_sync option to boost boltDB performance on ephemeral environments ([#10745](https://github.com/containerd/containerd/pull/10745))
* Add content create event ([#11006](https://github.com/containerd/containerd/pull/11006))
* …
> Add release notes for v2.1.0-rc.0

- internal/cri/nri/nri_api_linux.go
Use internal CRI resource conversion functions instead of the ones which were recently dropped from core NRI to get rid of a direct NRI dependency on CRI.
> nri: replace type conversion functions removed from NRI.

- docs/user-namespaces/README.md
- docs/user-namespaces/config.json
While we are there, bash should not be the process, it should be sh. In the bare-bone image used in the example, bash is not present (or not present anymore?).
Fixes: #11575 
---
@lamabro23 can you test if this fixes it for you too?
> docs: Fix typos to run userns with ctr

- .github/workflows/ci.yml
- script/critest.sh
The kernel in the latest ubuntu 22.04 runner image has been updated to 6.8.0-1027-azure, which has the fix for the ipv6 MARK bug. The runner image 20250427.1.0 with this has been now completely rolled out to github actions runners. Hence reverting the change to disable the IPv6 test.
Ref: https://github.com/actions/runner-images/blob/84a341f3224f622b1724b2c3511eab85de1ca40c/images/ubuntu/Ubuntu2204-Readme.md
This reverts commit 70db1bd00fb5db7c3958da4aefac0c41c89bb654.
> Revert "disable portmap test in ubuntu-22 to make CI happy"

- internal/cri/bandwidth/linux.go
- internal/cri/setutils/doc.go
- internal/cri/setutils/empty.go
- internal/cri/setutils/int.go
- internal/cri/setutils/set.go
- internal/cri/setutils/string.go
- internal/cri/store/image/image.go
- internal/cri/store/image/image_test.go
- internal/cri/util/strings.go
one of N PRs to clean up / eliminate our k8s.io vendor impact to only external apis that carry no k8s.io internal baggage like the min golang version definition in go.mod
https://github.com/kubernetes/kubernetes/issues/130799
> cloning k8s apimachinery set utils no longer vendoring apimachinery

- integration/main_test.go
- integration/remote/remote_image.go
- integration/remote/remote_runtime.go
- internal/cri/bandwidth/linux.go
- plugins/cri/runtime/plugin.go
one of N PRs to clean up / eliminate our k8s.io vendor impact to only external apis that carry no k8s.io internal baggage like the min golang version definition in go.mod
https://github.com/kubernetes/kubernetes/issues/130799
This one eliminates direct use of k8s.io/klog.. however there still remain incidental vendor use of klog so this PR leaves // TODO: mikebrow remove this klog inititialization func once we are no longer vendoring k8s.io/klog ... Which should come soon, that or we'll just remove this init function and see if we can live with the default klog log levels used in vendor code and/or see if we can also separate klog (e.g. where ever streaming ends up).
> removes use of klog from containerd repo

- internal/cri/clock/README.md
- internal/cri/clock/clock.go
- internal/cri/clock/testing/fake_clock.go
- internal/cri/clock/testing/simple_interval_clock.go
- internal/cri/server/events/events.go
- internal/cri/server/events/events_test.go
one of N PRs to clean up / eliminate our k8s.io vendor impact to only external apis that carry no k8s.io internal baggage like the min golang version definition in go.mod
https://github.com/kubernetes/kubernetes/issues/130799
this one all but finishes out clearing out our use of k8s/utils/* leaving only utils/exec which will be part of the streaming bucket of changes
> clones k8s utils clock for cri server events to remove dependency on k8s/utils/clock internal utility 

- cmd/containerd-shim-runc-v2/process/io.go
- cmd/containerd/server/server.go
- core/content/testsuite/testsuite.go
- core/images/usage/calculator.go
- core/metadata/containers.go
- core/metadata/content.go
- core/metadata/content_test.go
- core/metadata/db.go
- core/metadata/images.go
- core/metadata/leases.go
- core/metadata/snapshot.go
- core/metrics/cgroups/v1/oom.go
- core/remotes/docker/fetcher_test.go
- core/snapshots/benchsuite/benchmark_test.go
- core/transfer/streaming/writer.go
- core/unpack/unpacker.go
- integration/client/content_test.go
- internal/cri/server/images/image_pull.go
- internal/cri/server/images/image_pull_test.go
We've long been able to use these and they have a couple great benefits:
1. Forces you to always access them atomically. With the pointer variants it's completely valid to access the regular ol' int64/uint32 etc. without using the atomic.* methods. These wrappers don't provide access to the underlying value so it forces correct usage always.
2. Conveys intent much better. Seeing the type be atomic.Int32 immediately lets the reader know that this var will be used in a concurrent context, and we no longer need comments like "this MUST be accessed atomically" or similar.
> Use Go 1.19 atomic wrappers everywhere

- core/remotes/docker/fetcher.go
- core/remotes/docker/fetcher_fuzz_test.go
- core/remotes/docker/fetcher_test.go
- core/remotes/docker/pusher.go
- core/remotes/docker/resolver.go
Add a retry on 500, 503, 504 errors when there are no remaining hosts and the previous request did have the same 50x error.
This is still a more conservative approach to retry on 50x and will not apply to mirrors. Previously there was concerns about too aggressively retrying mirrors rather than quickly moving to the next host. We can try the last host more aggressively as well with the same logic not applying to the mirrors.
> Retry registry operations once on 50x if last host

- go.mod
- internal/cri/bandwidth/interfaces.go
- internal/cri/bandwidth/linux.go
- internal/cri/bandwidth/utils.go
- internal/cri/resourcequantity/amount.go
- internal/cri/resourcequantity/amount_test.go
- internal/cri/resourcequantity/doc.go
- internal/cri/resourcequantity/math.go
- internal/cri/resourcequantity/math_test.go
- internal/cri/resourcequantity/quantity.go
- internal/cri/resourcequantity/quantity_example_test.go
- internal/cri/resourcequantity/quantity_test.go
- internal/cri/resourcequantity/scale_int.go
- internal/cri/resourcequantity/scale_int_test.go
- internal/cri/resourcequantity/suffix.go
one of N PRs to clean up / eliminate our k8s.io vendor impact to only external apis that carry no k8s.io internal baggage like the min golang version definition in go.mod
filtered out/removed the following portions of the cloned package to keep the size reasonable for parsing to and from said k8s resource quantities for the CRI api:
- deepcopy
- marshal/unmarshal gogo proto fields
- grpc proto messaging
- marshal/unmarshal as CBOR format
https://github.com/kubernetes/kubernetes/issues/130799
> clones k8s apimachinery resource quantity for cri annotation parsing

- core/runtime/v2/shim.go
- core/runtime/v2/shim_manager.go
- core/runtime/v2/task_manager.go
- integration/issue10467_linux_test.go
- integration/release_upgrade_linux_test.go
- internal/cri/server/container_create.go
- internal/cri/server/podsandbox/controller.go
- internal/cri/server/podsandbox/types/podsandbox.go
Since the v2.0.0 release, the shim manager has attempted to use a single ttrpc connection to manage multiple containers through one shim server. However, this approach may introduce compatibility issues with older shims. According to the [current documentation](https://github.com/containerd/containerd/blob/main/core/runtime/v2/README.md?plain=1#L227), container resources are cleaned up via the `shim delete` binary call, which is triggered as a callback when the connection is closed. To ensure compatibility, containerd should always invoke the shim start binary to establish a new connection—regardless of the shim type—if the shim version is lower than `3`.
This patch enables containerd to invoke the shim start binary call, but doing so reveals another issue:
* A running pod is using an …
> [carry-11761] core/runtime: should invoke shim binary if it doesn't support Sandbox API

- .mailmap
- RELEASES.md
- go.mod
- go.sum
- releases/v2.1.0.toml
- vendor/modules.txt
- version/version.go
----
Welcome to the v2.1.0 release of containerd!
The first minor release of containerd 2.x focuses on continued stability alongside
new features and improvements. This is the first time-based released for containerd.
Most the feature set and core functionality has long been stable and harderened in production
environments, so now we transition to a balance of timely delivery of new functionality
with the same high confidence in stability and performance.
* Add no_sync option to boost boltDB performance on ephemeral environments ([#10745](https://github.com/containerd/containerd/pull/10745))
* Add content create event ([#11006](https://github.com/containerd/containerd/pull/11006))
* Erofs snapshotter and differ …
> Prepare release notes for v2.1.0

- .github/workflows/release.yml
We just released 2.1, these are now the latest.
> [release/2.0] .github: do not mark 2.0 releases as latest

- core/metadata/db.go
- core/runtime/v2/shim_load.go
- core/runtime/v2/shim_manager.go
- core/runtime/v2/task_manager.go
- internal/cleanup/context.go
- internal/cleanup/context_test.go
the `cleanup.Background` utility was introduced in f606c4eba7386f64a8b4db9a5b2b88ef16e42657,
at which time the project used go1.19, and Go's stdlib context did not yet
have [`context.WithoutCancel`], which was introduced in go1.21.
This patch replaces `cleanup.Background` for `context.WithoutCancel`, which
is near-identical, and part of go stdlib;
`cleanup.Background`:
```go
type clearCancel struct {
context.Context
}
func (cc clearCancel) Deadline() (deadline time.Time, ok bool) {
return
}
func (cc clearCancel) Done() <-chan struct{} {
return nil
}
func (cc clearCancel) Err() error {
return nil
}
// Background creates a new context which clears out the parent errors
func Background(ctx context.Context) context.Context {
return clearCancel{ctx}
}
```
`context.WithoutCancel`:
```go
// …
```
> replace "cleanup.Background" for "context.WithoutCancel"

- integration/main_test.go
many ci error because of time out on almalinux
```
default:     sandbox_clean_remove_test.go:108:
default:         	Error Trace:	/root/go/src/github.com/containerd/containerd/integration/sandbox_clean_remove_test.go:108
default:         	Error:      	Received unexpected error:
default:         	            	timeout exceeded
default:         	Test:       	TestSandboxRemoveWithoutIPLeakage
default:         	Messages:   	sandbox state should become NOTREADY
default:     sandbox_clean_remove_test.go:116: Should still be able to find the pod ip in host-local checkpoint
default:     sandbox_clean_remove_test.go:119: Should be able to stop and remove the sandbox
default: time="2025-05-08T02:00:25Z" level=info msg="[RuntimeService] StopPodSandbox …
```
> ci:fix ci timeout on almalinux

- cmd/ctr/commands/client.go
if containerd is not running.
old version
```
time ctr t ls
WARN[0010] Failed to check deprecations                  error="connection error: desc = \"transport: Error while dialing: dial unix:///run/containerd/containerd.sock: timeout\""
ctr: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing: dial unix:///run/containerd/containerd.sock: timeout"
real    0m10.020s
user    0m0.154s
sys     0m0.171s
```
```
❯ time nerdctl  ps
FATA[0000] cannot access containerd socket "/run/containerd/containerd.sock": no such file or directory 
real    0m0.020s
user    0m0.008s
sys     0m0.015s
```
> ctr:make sure containerd socket exist before create client

- core/runtime/v2/binary.go
- core/runtime/v2/shim.go
I noticed that the "cleaning up after shim disconnected" was logged as a warning, but I couldn't find a reason why it was considered a warning ( and didn't see an error attached to the log);
INFO[2025-05-07T08:57:56.576773500Z] ignoring event                                container=589c33c88591a9936cb8fd64453e4b0c1357ae2f79d975c34645ff8f0aa10485 module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
INFO[2025-05-07T08:57:56.576938958Z] shim disconnected                             id=589c33c88591a9936cb8fd64453e4b0c1357ae2f79d975c34645ff8f0aa10485 namespace=moby
WARN[2025-05-07T08:57:56.577356208Z] cleaning up after shim disconnected           id=589c33c88591a9936cb8fd64453e4b0c1357ae2f79d975c34645ff8f0aa10485 namespace=moby
INFO[2025-05-07T08:57:56.577393417Z] …
> core/runtime/v2: cleanup shim-cleanup logs

- .github/workflows/ci.yml
- .github/workflows/release.yml
- update CI runners to ubuntu 24.04
- remove integration testing for v1 shim because neither ubuntu 22 or 24 enables cgroupv1 and the shimv1 tests fail on those runners
> [release/1.6]: Fix CI

- internal/cri/config/config.go
Config deprecations were postponed to 2.2:
https://github.com/containerd/containerd/pull/11684
> Update removal version for deprecated registry config fields

- internal/cri/server/podsandbox/events.go
if use exec to do some health check will generate many exec exited events log.
fix:https://github.com/containerd/containerd/issues/11836
@AkihiroSuda  @mxpv  can you review this pr ? It is easily to review. Thanks.
> cri:use debug level when receive exec process exited events

- docs/snapshotters/erofs.md
- plugins/diff/erofs/differ_linux.go
1.  erofs-differ: fix EROFS native image support
```
A dumb bug was just found after I worked out a usable native
converter [1], instead of relying on some prebuilt image..
[1] https://github.com/erofs/erofs-container-toolkit
```
2. docs/snapshotters/erofs.md: a tip for improved performance
```
It's preferred to use `--sort=none` (erofs-utils 1.8.2+) to avoid
tar data twice due to stricter data ordering.
See: https://git.kernel.org/xiang/erofs-utils/c/e97530622872
```
> erofs-snapshotter: a fix for native image support and a performance tip

- contrib/ansible/README.md
In the step1 of the documentation, after the git clone, it is necessary to move in the folder of the source of the git clone
> docs(ansible): fix the folder in step1

- pkg/oci/spec_opts.go
- pkg/oci/spec_opts_test.go
Some of these options are designed to be a no-op when used on a Spec that doesn't match the platform for the option. However, if the given plaform was not present, they would panic.
This patch:
- Adds an early-return for options that are only applied on a specific platform.
- Update the GoDoc for these functions to describe they're a no-op on other platforms.
- Adds some rudimentary unit-tests to verify their behavior.
> pkg/oci: prevent panic for some platform-specific options

- core/mount/mount_linux.go
if use containerd api  in container to create container will return error:
```
failed to create container: failed to mount /tmp/containerd-mount530130800: no such file or directory.
```
It is misleading because /tmp/containerd-mount530130800  exists.
ref:https://github.com/containerd/containerd/issues/11849
after this commit 
```
failed to create container: failed to mount /tmp/containerd-mount4215502267: mount source: overlay, target: /tmp/containerd-mount4215502267, fstype: overlay, flags: 0, data: lowerdir=/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/31/fs:/var/lib/containerd/io.containerd.snapshotter.v1.overlayfs/snapshots/1/fs,index=off, err: no such file or directory
```
> client:improve mount error message

- contrib/seccomp/seccomp_default.go
reference: https://github.com/seccomp/libseccomp/commit/f01e67509e45c672f4bdd643d94d90867cc19d90 (libseccomp v2.6.0)
- v6.8:
* listmount (https://github.com/torvalds/linux/commit/b4c2bea8ceaa50cd42a8f73667389d801a3ecf2d)
* lsm_get_self_attr, lsm_set_self_attrs (https://github.com/torvalds/linux/commit/a04a1198088a1378d0389c250cc684f649bcc91e)
* lsm_list_modules (https://github.com/torvalds/linux/commit/ad4aff9ec25f400608283c10d634cc4eeda83a02)
* statmount (https://github.com/torvalds/linux/commit/46eae99ef73302f9fb3dddcd67c374b3dffe8fd6)
- v6.9:
* mseal (https://github.com/torvalds/linux/commit/8be7258aad44b5e25977a98db136f677fa6f4370)
- v6.11:
* uretprobe (https://github.com/torvalds/linux/commit/190fec72df4a5d4d98b1e783c333f471e5e5f344)
- v6.12:
* riscv_hwprobe …
> seccomp: kernel v6.13 (libseccomp v2.6.0)

- core/transfer/local/import.go
the copy is modified but `idx.Manifests` is returned.
This prevented the import to work, because the annotation was missing.
> fix import for local transfer service

- core/transfer/local/transfer.go
- core/unpack/unpacker.go
Avoid using internal interfaces for exported types and always prefer using interfaces over structs to limit unused imports.
> Remove internal interface from unpacker interface

- .github/workflows/ci.yml
- Vagrantfile
fix: https://github.com/containerd/containerd/issues/11830
Added jobs to ci.yml to test runc v1 using vagrant
ping @akhilerm
> [release/1.6] test: added runc v1 support in vagrant

- core/unpack/unpacker.go
- plugins/services/transfer/service.go
- plugins/transfer/plugin.go
1. Update differ selection in transfer service to prefer default
Currently the erofs differ will be chosen and cause pulls to fail with not implemented errors.
We should also consider whether the differ should have an export configuration which limits which snapshotters it should be used with
2. Add debug log when transfer returns not implemented
Currently the error details are not included in the output error and there is no log. One of the reasons a the transferer was skipped could be do to a specific component which is not implemented (such as trying to use erofs differ) or unsupported image (pulling schema1). This information is useful to find a bad configuration.
We could also consider returning this error detail to the caller, it could be relevant in in the schema 1 case to indicate …
> Fix transfer differ selection

- plugins/snapshots/erofs/erofs_linux.go
Commit fb6dd2cf15fa ("client:improve mount error message") changed the return value into a wraped error message, which causes the ENOTBLK check doesn't work. Fix it now.
Thanks @aadhar-agarwal for reporting.
> erofs-snapshotter: fix to work with wrapped errors

- integration/client/import_test.go
`TestExportAndImportMultiLayer` has been very flaky due to upstream registry throttling/unavailability. E.g.,
https://github.com/containerd/containerd/actions/runs/15168768477/job/42653479864
```shell
log_hook.go:47: time="2025-05-21T17:42:37.345336659Z" level=debug msg="fetch failed" func=docker.dockerFetcher.open file="/home/runner/work/containerd/containerd/core/remotes/docker/fetcher.go:470" digest="sha256:5178da1ca6af8a14a235f58eb31955ca5f4c72f950d35f9bb67a8bd20232d840" error="unexpected status code https://mcr.microsoft.com/v2/windows/nanoserver/blobs/sha256:5178da1ca6af8a14a235f58eb31955ca5f4c72f950d35f9bb67a8bd20232d840: 503 Service Unavailable" mediatype=application/vnd.docker.image.rootfs.foreign.diff.tar.gzip size=116254563 testcase=TestExportAndImportMultiLayer …
```
> Fetch image with default platform only in TestExportAndImportMultiLayer

- integration/image_volume_linux_test.go
- integration/main_test.go
- internal/cri/server/container_image_mount.go
Following up https://github.com/containerd/containerd/pull/10579, this PR adds the [`subpath`](https://kubernetes.io/docs/concepts/storage/volumes/#using-subpath) support for image volume mount.
Fix #11580
As discussed in https://github.com/containerd/containerd/pull/11533#issuecomment-2722862811, we don't want to bump up to go 1.24 in containerd 2.1, so it PR may not be merged before 2.1. But want to share it early so I can get some early feedback and iterate. :)
> [KEP-4639] Support image volume mount subpath

- core/runtime/v2/shim.go
- core/runtime/v2/shim_load.go
- integration/issue10467_linux_test.go
- integration/release_upgrade_linux_test.go
Previously, to address issue https://github.com/containerd/containerd/issues/11708, PR https://github.com/containerd/containerd/pull/11793 changed containerd to always
invoke the shim binary to establish shim connections, rather than reusing the
sandbox shim. However, this change did not ensure that the Shutdown API was
called to stop the shim process.
Starting with containerd v2.0.0, the Shutdown API is only invoked for sandbox
containers (when container.SandboxID is empty). This approach works for
groupable shims, where multiple containers share a single socket address and
only require a single Shutdown call. However, for non-groupable shims, each
container requires its own Shutdown call during cleanup to avoid leaking shim
processes.
Additionally, PR …
> *: properly shutdown non-groupable shims to prevent resource leaks

- pkg/oci/spec_opts_linux.go
- pkg/oci/spec_opts_nonlinux.go
These were introduced in c818a6b13dae8af18fc1a2f6209524450aef56ba, refactored in 808b223536e6553ddee2944d7ec6bc6d86e0da88 and bdd84abf056b153b3e37883884e91c52f98e15b9, and moved in a2d1a8a8653fd5cfe97a9860a5f8ce8a600c2b01, but none provided a motivation for using a variable / alias for these.
Based on the above, I assume the use of a variable was purely convenience, the there's no intent for packages to be able to override them, so this patch changes these to be a regular function.
> pkg/oci: don't use vars for WithAllKnownCapabilities, WithAllCurrentCapabilities

- core/runtime/v2/shim.go
```
log.G(ctx).WithField("id", s.ID()).WithError(shimErr).Debug("failed to delete task") 
```
default log level is debug is not appropriate
A picture of a cute animal (not mandatory but encouraged)
> shim-v2:improve shim error message

- pkg/oci/spec_opts.go
- relates to https://github.com/containerd/containerd/pull/2269
This variable was introduced in 062c3a00ef74222827399a013283650450e93c42, which didn't describe it as intentional to be able to override the option.
Based on the above, I assume the use of a variable was purely convenience, the there's no intent for packages to be able to override them, so this patch changes these to be a regular function.
> pkg/oci: don't use var for WithPrivileged

- .devcontainer/devcontainer.json
- .github/actions/install-go/action.yml
- .github/workflows/api-release.yml
- .github/workflows/ci.yml
- .github/workflows/release.yml
- Vagrantfile
- contrib/Dockerfile.test
- contrib/fuzz/oss_fuzz_build.sh
- script/setup/prepare_env_windows.ps1
This change bumps the golang version used in CI to Go 1.24.4.
>  go1.24.4 (released 2025-06-05) includes security fixes to the crypto/x509, net/http, and os packages, as well as bug fixes to the linker, the go command, and the hash/maphash and os packages. See the Go 1.24.4 milestone on our issue tracker for details. 
full diff: https://github.com/golang/go/compare/go1.24.3...go1.24.4
> ci: bump golang 1.24.4 in build and release

- .devcontainer/devcontainer.json
- .github/actions/install-go/action.yml
- .github/workflows/api-release.yml
- .github/workflows/ci.yml
- .github/workflows/release.yml
- Vagrantfile
- contrib/Dockerfile.test
- contrib/fuzz/oss_fuzz_build.sh
- script/setup/prepare_env_windows.ps1
This change backports CI updates for Golang 1.23.10 and 1.24.4 for release/2.1 build and release CI.
Note: not a clean cherry-pick as mainline is no longer on Go 1.23.
(cherry picked from commit 415df38927a5050bc897bec5480caa2c3d99652d)
> [release/2.1] ci: bump golang [1.23.10,1.24.4] in build and release

- core/runtime/v2/shim.go
- core/runtime/v2/shim_load.go
- core/runtime/v2/shim_manager.go
- core/runtime/v2/task_manager.go
- integration/issue10467_linux_test.go
- integration/release_upgrade_linux_test.go
- integration/release_upgrade_utils_linux_test.go
- internal/cri/server/container_create.go
- internal/cri/server/podsandbox/controller.go
- internal/cri/server/podsandbox/types/podsandbox.go
Backport following pull requests:
* part of https://github.com/containerd/containerd/pull/11510
* https://github.com/containerd/containerd/pull/11793
* https://github.com/containerd/containerd/pull/11916
Closes: #11828
> [release/2.0] core/runtime: should invoke shim binary if it doesn't support Sandbox API 

- core/remotes/errors/errors.go
- core/transfer/proxy/transfer.go
Currently when using the transfer service the registry error type is not returned to the client over grpc, with this change the client can access the full body to decode the registry error message.
> Fix registry errors with transfer service

- core/remotes/docker/errcode.go
- core/remotes/docker/fetcher_test.go
- core/remotes/docker/pusher.go
- core/remotes/docker/resolver.go
Currently the registry error does not include details or allow the caller access to the original error body.
> Update fetcher errors to include full registry error

- core/content/helpers.go
- core/remotes/docker/fetcher.go
- core/remotes/docker/fetcher_test.go
Before: ( mutipart fetching needs to be conf'ed )
```
ctr i pull public.ecr.aws/mountpoint-s3-csi-driver/aws-mountpoint-s3-csi-driver:v1.14.1
...
application/vnd.docker.distribution.manifest.list.v2+json sha256:e64728220f5cc60477e9dd5415b33a7bb0cc024dbf8fe25eba8397b9f30c3a62
Pulling from OCI Registry (public.ecr.aws/mountpoint-s3-csi-driver/aws-mountpoint-s3-csi-driver:v1.14.1) elapsed: 23.1s  total:   0.0 B  (0.0 B/s)
ERRO[0035] progress stream failed to recv                error="error reading from server: EOF"
ctr: error reading from server: EOF
```
It is worth noting that when we don't know the size of the file, multipart fetching will be disabled.
> Fix multipart fetch issue when the server does not return content length

- releases/v2.1.3.toml
- version/version.go
See generated release notes
Waiting on
----
containerd 2.1.3
Welcome to the v2.1.3 release of containerd!
The third patch release for containerd 2.1 contains various fixes and updates
to address pull issues with some registries.
* Fix import for local transfer service ([#12000](https://github.com/containerd/containerd/pull/12000))
* Fix registry errors with transfer service ([#11979](https://github.com/containerd/containerd/pull/11979))
* Fix fetch always adding range to requests ([#12001](https://github.com/containerd/containerd/pull/12001))
* Update fetcher errors to include full registry error ([#11997](https://github.com/containerd/containerd/pull/11997))
* …
> [release/2.1] Prepare release notes for v2.1.3

- .github/workflows/build-test-images.yml
- .github/workflows/ci.yml
- .github/workflows/windows-hyperv-periodic.yml
- .github/workflows/windows-periodic.yml
- integration/client/helpers_unix.go
- integration/client/helpers_windows.go
- integration/image_load_test.go
- integration/images/volume-copy-up/Makefile
- integration/images/volume-ownership/Makefile
This change backports the Windows runner image updates for Windows 2019 deprecation to release/2.0.
(cherry picked from commit 2f1948a503fbd7c3d053c3a19b2b06045fdeea4b)
Note: not a clean cherry-pick; edited to include a copy of Windows 2025 constant copied from Microsoft/hcsshim@v0.13.0
> [release/2.0] Enable CIs to run on WS2022 and WS2025

- .gitignore
- Makefile
- script/test/cri-integration.sh
- script/test/utils.sh
Adds support for creating coverage report for the target `make cri-integration`, the output of the coverage report is as follows
```
mode: atomic
github.com/containerd/containerd/v2/client/client.go:80.13,90.31 8 1
github.com/containerd/containerd/v2/client/client.go:90.31,96.3 1 0
github.com/containerd/containerd/v2/client/client.go:101.56,103.25 2 22
github.com/containerd/containerd/v2/client/client.go:103.25,104.35 1 58
github.com/containerd/containerd/v2/client/client.go:104.35,106.4 1 0
github.com/containerd/containerd/v2/client/client.go:108.2,108.24 1 22
github.com/containerd/containerd/v2/client/client.go:108.24,110.3 1 22
github.com/containerd/containerd/v2/client/client.go:112.2,116.32 2 22
github.com/containerd/containerd/v2/client/client.go:116.32,118.3 1 0
```
> Add coverage support for CRI integration tests

- .devcontainer/devcontainer.json
- .github/actions/install-go/action.yml
- .github/workflows/api-release.yml
- .github/workflows/ci.yml
- .github/workflows/release.yml
- Vagrantfile
- contrib/Dockerfile.test
- contrib/fuzz/oss_fuzz_build.sh
- script/setup/prepare_env_windows.ps1
This change backports golang updates for release/2.0 build and release.
Note: not clean cherry-picks as mainline is no longer have Go 1.23 support.
(cherry picked from commit fea77e15b544d82525912ee8bc9924955e99519a)
(cherry picked from commit 415df38927a5050bc897bec5480caa2c3d99652d)
> [release/2.0] ci: bump golang [1.23.10, 1.24.4] in build and release

- .github/workflows/ci.yml
- .github/workflows/release.yml
For jobs which do not require a version matrix, such as some testing runs, use the latest runner image. Pinning the images unnecessarily causes more work later on when deciding when to upgrade and may cause more issues when older images brownout. It is preferable to catch issues when the latest is updated for jobs that should not be version dependent.
> Update GHA runners to use latest image for most jobs

- integration/client/container_test.go
```
2025-06-21T04:06:35.2568615Z     default: === NAME  TestContainerExecLargeOutputWithTTY
2025-06-21T04:06:35.2569711Z     default:     container_test.go:1981: expected exec exit code 0 but received 129
2025-06-21T04:06:35.2615723Z     default: --- FAIL: TestContainerExecLargeOutputWithTTY (21.46s)
2025-06-21T04:06:35.2641056Z     default: panic: runtime error: slice bounds out of range [-20:] [recovered]
2025-06-21T04:06:35.2641837Z     default: 	panic: runtime error: slice bounds out of range [-20:]
2025-06-21T04:06:35.2642348Z     default: 
2025-06-21T04:06:35.2642687Z     default: goroutine 1469 [running]:
2025-06-21T04:06:35.2643204Z     default: testing.tRunner.func1.2({0x16b2400, 0xc000abe8a0})
2025-06-21T04:06:35.2643830Z     default: 	/usr/local/go/src/testing/testing.go:1734 …
```
> ci:fix ci TestContainerExecLargeOutputWithTTY panic

- internal/cri/streamingserver/portforward/httpstream.go
Fixes: #12033 
Change the logging output of a struct to only list the pointer value to remove the traversal of a map that is not thread safe and can at times generate a concurrent map write error.
Related to a similar fix in 1.7.x via #11302.
Will backport to `release/2.1` as-is; to fix `release/2.0` we will have to submit a PR to upstream k/k because this streaming code was still in the vendored kubelet code
> Fix port forward error logger to not cause concurrent write

- docs/snapshotters/erofs.md
- internal/erofsutils/mount_linux.go
- plugins/diff/erofs/differ_linux.go
Derive filesystem UUIDs (`lsblk -o +UUID`) from the OCI layer digests (although diffIDs are better in principle, but they're unavailable by differs in advance) rather than generating a random one.
This allows EROFS to uniquely identify each layer using the content-addressable filesystem UUID.
Note: currently **uuid.NewSHA1(uuid.NameSpaceURL, []byte("erofs:blobs/"+desc.Digest))** is used to generate filesystem UUIDs.
> erofs-differ: fix filesystem UUID for tar-converted layers

- internal/cri/server/container_stats_list.go
- internal/cri/server/sandbox_stats_windows.go
- internal/cri/server/sandbox_stats_windows_test.go
**Summary**
Fixes Windows container memory stats by correctly aggregating CommitMemoryBytes and handling missing stats gracefully.
**Key Changes**
Fixed aggregation of `CommitMemoryBytes` in `appendMemoryPodStats`
Mapped `MemoryUsageCommitBytes` to container `UsageBytes`
Handled nil stats without breaking pod-level reporting
Added tests for missing memory stats and updated assertions
**Bug**
Pod-level memory stats were incomplete due to missing CommitMemoryBytes aggregation. This fix ensures accurate reporting across containers.
**Testing**
New test for missing stats
All existing tests pass
Improved test clarity and coverage
> fix(cri): Correct Commit Memory Aggregation for Windows Containers

- integration/container_io_leak_linux_test.go
- pkg/process/init.go
This change backports https://github.com/containerd/containerd/pull/11885 to 1.6 stable branch.
(cherry picked from commit e6708bddfbede5405ed0f262d69fc356988b84ef)
> [release/1.6] bugfix:close container io when runtime create failed

- client/client.go
- client/task.go
- related to: https://github.com/containerd/containerd/issues/11507
When moving to gRPC 1.64 (commit 63b4688175) the usage of the deprecated `grpc.DialContext` was replaced with `grpc.NewClient`. However, this change also required to drop the `WithBlock` option, which made sure that the connection is actually established before returning.
Now, `grpc.NewClient` doesn't attempt to perform the connection but defers it to the actual first RPC.
Querying the default runtime on client creation breaks that property depending on whether the default namespace is set or not.
This commit moves the `runtime` field initialization behind a `sync.Once` and defers it to the first time the field actually needs to be used.
> client/New: Don't unlazy the gRPC connection implicitly

- docs/snapshotters/erofs.md
- plugins/snapshots/erofs/erofs_linux.go
- plugins/snapshots/erofs/plugin/plugin_linux.go
Enabling the IMMUTABLE_FL file attribute causes dirty data to be flushed synchronously at least on EXT4[1], which can greatly impact container launch performance.  In contrast, the overlayfs snapshotter does not use `syncfs` by default.
Most users may not need IMMUTABLE_FL, let's make IMMUTABLE_FL optional to align with the behavior of the overlayfs snapshotter and recover the original performance.
0. containerd toml file:
``` toml
[plugins."io.containerd.differ.v1.erofs"]
mkfs_options = ["-T0", "--mkfs-time", "--sort=none"]
```
1. tensorflow image
Test commands:
``` sh
$ nerdctl image pull --snapshotter=X --unpack="false" tensorflow/tensorflow:2.19.0
$ time nerdctl container --snapshotter=X run -d tensorflow/tensorflow:2.19.0 /bin/sh
```
Results:
```
overlayfs                 | 0m18.748s …
```
> erofs-snapshotter: make IMMUTABLE_FL optional to recover performance

- .github/workflows/build-test-images.yml
- .github/workflows/ci.yml
- .github/workflows/windows-hyperv-periodic.yml
- .github/workflows/windows-periodic.yml
- integration/images/volume-copy-up/Makefile
- integration/images/volume-ownership/Makefile
TestCRISuite on WS2025 seems to have regressed. There are other sig-windows failures on test grid as well https://testgrid.k8s.io/sig-windows-signal#capz-windows-master-2025. Removing WS2025 temporarily while we continue to look into the failures to unblock merge queue.
> Remove WS2025 from CIs due to test failures

- docs/snapshotters/erofs.md
- plugins/snapshots/erofs/erofs_linux.go
- plugins/snapshots/erofs/plugin/plugin_linux.go
backport https://github.com/containerd/containerd/pull/12072
To fix erofs snapshotter performance regression due to IMMUTABLE_FL.
> [release/2.1] erofs-snapshotter: make IMMUTABLE_FL optional

- core/runtime/v2/shim_load.go
While testing some things in moby, which involved removing storage paths, I noticed some errors being printed for non-existing paths. As this function is meant to delete the directories, it should probably be fine to consider it idempotent (as further processing in the function also does).
> core/runtime/v2: shimManager.cleanupWorkDirs ignore non-existing path

- internal/cri/opts/spec_opts.go
- internal/cri/server/container_create.go
- internal/cri/server/container_create_windows_test.go
Commit passes the CPU affinity values namely cpu mask and group to runtime spec from container config.
> Plumb windows CPU affinity values to runtime spec

- contrib/fuzz/oss_fuzz_build.sh
Related to #12007 
This change removes the additional fuzzers from AdamKorcz/instrumentation repository. This is to unblock changes in containerd release/1.7 stable branch where the fuzzing workflow is failing due to compilation issues caused by higher Go toolchain requirement in mainline.
> Remove additional fuzzers from instrumentation repo

- Vagrantfile
Workaround for https://github.com/containerd/containerd/issues/12124
Fedora 39 cloud image is now available on archive. i.e. https://archives.fedoraproject.org/pub/archive/fedora/linux/releases/39/Cloud/x86_64/images/
> [release/1.6] ci: use fedora 39 archive

- .github/actions/install-go/action.yml
- .github/workflows/ci.yml
- .github/workflows/release.yml
- Vagrantfile
- contrib/Dockerfile.test
- script/setup/prepare_env_windows.ps1
> go1.24.5 (released 2025-07-08) includes security fixes to the go command, as well as bug fixes to the compiler, the linker, the runtime, and the go command. See the [Go 1.24.5 milestone](https://github.com/golang/go/issues?q=milestone%3AGo1.24.5+label%3ACherryPickApproved) on our issue tracker for details.
full diff: https://github.com/golang/go/compare/go1.24.4...go1.24.5
> go1.23.11 (released 2025-07-08) includes security fixes to the go command, as well as bug fixes to the compiler, the linker, and the runtime. See the [Go 1.23.11 milestone](https://github.com/golang/go/issues?q=milestone%3AGo1.23.11+label%3ACherryPickApproved) on our issue tracker for details.
full diff: https://github.com/golang/go/compare/go1.23.10...go1.23.11 …
> [release/1.6] ci: bump Go 1.23.11, 1.24.5

- internal/nri/config.go
Set up NRI for producing otel trace spans.
> nri: enable otel traces in NRI.

- .github/actions/install-go/action.yml
- .github/workflows/api-release.yml
- .github/workflows/ci.yml
- .github/workflows/release.yml
- Vagrantfile
- contrib/Dockerfile.test
- contrib/fuzz/oss_fuzz_build.sh
- script/setup/prepare_env_windows.ps1
> go1.24.5 (released 2025-07-08) includes security fixes to the go command, as well as bug fixes to the compiler, the linker, the runtime, and the go command. See the [Go 1.24.5 milestone](https://github.com/golang/go/issues?q=milestone%3AGo1.24.5+label%3ACherryPickApproved) on our issue tracker for details.
full diff: https://github.com/golang/go/compare/go1.24.4...go1.24.5
> go1.23.11 (released 2025-07-08) includes security fixes to the go command, as well as bug fixes to the compiler, the linker, and the runtime. See the [Go 1.23.11 milestone](https://github.com/golang/go/issues?q=milestone%3AGo1.23.11+label%3ACherryPickApproved) on our issue tracker for details.
full diff: https://github.com/golang/go/compare/go1.23.10...go1.23.11 …
> [release/1.7] ci: bump Go 1.23.11, 1.24.5

- releases/v1.7.28.toml
- version/version.go
--
containerd 1.7.28
Welcome to the v1.7.28 release of containerd!
The twenty-eighth patch release for containerd 1.7 contains various fixes
and updates.
* Akhil Mohan
* Akihiro Suda
* Phil Estes
* Austin Vazquez
* Henry Wang
* Iain Macdonald
* Jin Dong
* Swagat Bora
* Wei Fu
* Yang Yang
* madraceee
<details><summary>54 commits</summary>
<p>
* [`b01b809f8`](https://github.com/containerd/containerd/commit/b01b809f89a27e19ff7531e1b88df07d2f40de97) Prepare release notes for v1.7.28
* [release/1.7] Backport windows test fixes ([#12121](https://github.com/containerd/containerd/pull/12121))
* …
> [release/1.7] Prepare release notes for v1.7.28

- .github/workflows/node-e2e.yml
Copying the same change made to k8s infra testing to remove Alpha gated features from standard end to end testing runs
Ref: kubernetes/test-infra#35198
Ref: #12137
> Remove Alpha gate from k8s e2e runs

- releases/v2.1.4.toml
- version/version.go
----
containerd 2.1.4
Welcome to the v2.1.4 release of containerd!
The fourth patch release for containerd 2.1 contains various fixes and updates.
* Fix containerd panic when sandbox extension is missing ([#12076](https://github.com/containerd/containerd/pull/12076))
* Update status response to return stable order for runtime handlers ([#12054](https://github.com/containerd/containerd/pull/12054))
* Fix lazy gRPC connection mode waiting for connect on client creation ([#12079](https://github.com/containerd/containerd/pull/12079))
* Fix resolve deadlock issue in docker fetcher open ([#12127](https://github.com/containerd/containerd/pull/12127))
* Update erofs snapshotter to make immutable optional ([#12091](https://github.com/containerd/containerd/pull/12091))
* Fix erofs …
> [release/2.1] Prepare release notes for v2.1.4

- core/metrics/cgroups/metrics_test.go
Noticed a minor typo in the `metrics/cgroups` regression test, `collecter` instead of `collector`. Fixed to keep it consistent across other tests
cc @mikebrow @fuweid
> Fix typo in regression test (metrics/cgroups)

- core/remotes/docker/config/hosts.go
- core/remotes/docker/config/hosts_test.go
- docs/hosts.md
This PR cherry-picks the commit from #11106 and applies it to release/2.0.
The original PR was marked for backporting to 2.0
> [release/2.0] Backport Add dial timeout field to hosts toml configuration #11106

- pkg/sys/unshare_linux.go
UnshareAfterEnterUserns() creates a pidfd via os.StartProcess() with CLONE_PIDFD but fails to close the file descriptor in any code path, resulting in a file descriptor leak for every container that uses user namespace isolation.
The leak occurs because:
- The pidfd is created when PidFD field is set in SysProcAttr
- The defer block only calls PidfdSendSignal() and pidfdWaitid()
- No code path calls unix.Close(pidfd) to release the file descriptor
This causes one pidfd leak per container launch when user namespace isolation is enabled (e.g., Kubernetes pods with hostUsers: false). In production environments with high container churn, this can exhaust the system's file descriptor limit.
Fix the leak by adding a defer statement immediately after process creation that ensures …
> sys: fix pidfd leak in UnshareAfterEnterUserns

- core/runtime/v2/shim.go
Fixes: #12176
Also needs to be backported to release/2.0 and release/2.1
> fix: create bootstrap.json with 0644 permission

- .devcontainer/devcontainer.json
- .github/actions/install-go/action.yml
- .github/workflows/api-release.yml
- .github/workflows/ci.yml
- .github/workflows/release.yml
- Vagrantfile
- contrib/Dockerfile.test
- contrib/fuzz/oss_fuzz_build.sh
- script/setup/prepare_env_windows.ps1
This change bumps the golang version used in CI to Go 1.24.6.
> go1.24.6 (released 2025-08-06) includes security fixes to the database/sql and os/exec packages, as well as bug fixes to the runtime. See the [Go 1.24.6 milestone](https://github.com/golang/go/issues?q=milestone%3AGo1.24.6+label%3ACherryPickApproved) on our issue tracker for details.
full diff: https://github.com/golang/go/compare/go1.24.5...go1.24.6
> ci: bump Go 1.24.6

- .github/actions/install-go/action.yml
- .github/workflows/api-release.yml
- .github/workflows/ci.yml
- .github/workflows/release.yml
- Vagrantfile
- contrib/Dockerfile.test
- contrib/fuzz/oss_fuzz_build.sh
- script/setup/prepare_env_windows.ps1
This change backports https://github.com/containerd/containerd/pull/12180 to release/1.7 branch to bump the golang version used in CI to Go 1.23.12, 1.24.6.
> go1.23.12 (released 2025-08-06) includes security fixes to the database/sql and os/exec packages, as well as bug fixes to the runtime. See the [Go 1.23.12 milestone](https://github.com/golang/go/issues?q=milestone%3AGo1.23.12+label%3ACherryPickApproved) on our issue tracker for details.
full diff: https://github.com/golang/go/compare/go1.23.11...go1.23.12
> go1.24.6 (released 2025-08-06) includes security fixes to the database/sql and os/exec packages, as well as bug fixes to the runtime. See the [Go 1.24.6 milestone](https://github.com/golang/go/issues?q=milestone%3AGo1.24.6+label%3ACherryPickApproved) on our issue tracker for …
> [release/1.7] ci: bump Go 1.23.12, 1.24.6

- cmd/ctr/commands/snapshots/snapshots.go
snapshotter.Mounts() maybe get empty Options for different snapshot service.
Empty Options will produce invalid mount command from printMounts:
```
$ ctr -n flintlock snapshot --snapshotter devmapper mount /mnt flintlock/flintlock/demo-2/01K24ZRN9EFAVQVNGXQS26BYVG/root
mount -t ext4 /dev/mapper/fc-dev-thinpool-snap-19 /mnt -o
$ cmd=$(ctr -n flintlock snapshot --snapshotter devmapper mount /mnt flintlock/flintlock/demo-2/01K24ZRN9EFAVQVNGXQS26BYVG/root)
$ $cmd
mount: option requires an argument -- 'o'
Try 'mount --help' for more information.
```
> Fix ctr snapshot mount produce invalid mount command for empty option

- .github/workflows/ci.yml
Initial release of Go 1.25 has arrived.
> The latest Go release, version 1.25, arrives in [August 2025](https://go.dev/doc/devel/release#go1.25.0), six months after [Go 1.24](https://go.dev/doc/go1.24). Most of its changes are in the implementation of the toolchain, runtime, and libraries. As always, the release maintains the Go 1 promise of compatibility. We expect almost all Go programs to continue to compile and run as before.
Ref: https://go.dev/doc/go1.25
> ci: add Go 1.25.0

- archive/compression/compression.go
- diff/walking/differ.go
- diff/windows/windows.go
The differ should be able to generate zstd compressed layers when provided with the zstd media type.
(cherry picked from commit 17f7858b4e2e31b447410f66d0100b816c1fe6b3)
> [release/1.7]  cherry-pick Update differ to handle zstd media types

- pkg/netns/netns_linux.go
fix: https://github.com/containerd/containerd/issues/11958
Previously, when unix.Mount failed, the returned nsPath was set to "", causing the deferred cleanup (os.RemoveAll(nsPath)) to silently fail and leave behind orphaned netns mount point files.
This commit changes the return statement to preserve the actual nsPath value even on error, ensuring that the cleanup logic in the deferred function works as intended.
> fix: preserve nsPath on mount failure to ensure cleanup

- core/mount/mount_linux.go
- core/mount/mount_linux_test.go
This PR fixes:
*  an issue where we can panic the go runtime by running a function that is nil if we take some error paths (containerd daemon continues to run fine, though) 
* the cleanup function was also adding noise to the logs on error paths (printing we failed to delete a directory, although we never created it, etc.)
* The cleanup function didn't retry unmounting and could end up leaking mounts (#12139)
While we are there, I took the opportunity to add tests for the cleanup function and test these issues, as well as previous issues we encounter, are fixed.
Please see individual commits for more details. I think it's simpler to review by checking each commit too.
PR #5890 introduced the issues in the cleanup function.
Fixes: #12139
> core/mount: Fix doPrepareIDMappedOverlay cleanup function

- core/metadata/gc.go
- core/metadata/gc_test.go
- docs/garbage-collection.md
Add backreference labels for an object. This allows objects to be referred to by objects which already exist without updating the labels on the original object or referred to by objects which do not yet exist. This is useful for ephemeral objects as well as objects with a 1 to many relationship.
Use cases:
- Dependent images ("dangling" images)
- Ephemeral container objects (such as streams, networks, or mounts)
- OCI referrers (1 to many relationship)
> Add support for back references in the garbage collector

- docs/cri/config.md
`cgroup_writable` field was introduced in - https://github.com/containerd/containerd/pull/11131, this PR updates the documentation to include the field.
> Add documentation for cgroup_writable field

- core/mount/mount_idmapped_linux.go
- core/mount/mount_idmapped_linux_test.go
- core/mount/mount_linux.go
- core/mount/mount_linux_test.go
- plugins/snapshots/overlay/overlayutils/check.go
Backport various overlayfs related user namespace fixes and improvements
This backports various fixes related to the following issues:
Issue #12048
Issue #12139
And pulls in 1e3d10dc2 ("Make ovl idmap mounts read-only") as
a dependency.
These patches make:
1. The temporary idmap'ed bind mounts r/o and not MNT_DETACHED,
which prevents accidental modification and makes unmount semantics
more clear
2. Makes far less bind mounts happen per overlayfs, greatly improving
performance which was shown to be devastating enough to kill the node
3. Retries on umount errors (a common containerd pattern) for the temporary
bind mounts to prevent leaking mounts on long running containerd daemons
These are great improvements to the stability of containerd when using
user namespaces + overlayfs.
> [release/2.0] Backport various overlayfs related user namespace fixes and improvements

- core/mount/temp.go
- integration/pod_userns_linux_test.go
- internal/cri/opts/container.go
This PR fixes the "copy-up" used in `VOLUME` directives if the path in the rootfs has some contents AND the pod is using user-namespaces (it was working fine if the rootfs didn't have content for the volume path).
The issue is that when doing the copy-up, we screw up the permissions in the userns case. This is explained in more detail in the commit msg (c&p below). Also, I've added an integration test that test the copy-up with userns. It's based in the existing copy-up test case, that is testing already a lot of things.
The copy-up integration test adapted for userns fails without this PR (and works with this, of course :)). I've also added to the test to check the file permissions, for completeness, although it wasn't needed to detect this bug.
Below the commit msg with the long …
> cri: Fix userns with container image VOLUME mounts that need copy

- core/mount/temp.go
- integration/pod_userns_linux_test.go
- internal/cri/opts/container.go
This backports: https://github.com/containerd/containerd/pull/12218
Fixes: https://github.com/containerd/containerd/issues/11852 in the 2.1 branch
> [release/2.1] Backport userns container image volume with copy-up fixes

- script/setup/install-runhcs-shim
No idea why it blames lock during fetching.
```bash
...
* [new tag]           v0.9.9           -> v0.9.9
error: cannot lock ref 'refs/tags/v0.6.3': Unable to create 'C:/Users/runneradmin/AppData/Local/Temp/tmp.N2FTxfARN9/.git/refs/tags/v0.6.3.lock': File exists.
Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
+ cleanup
+ rm -rf /tmp/tmp.N2FTxfARN9
```
> install-runhcs-shim: fetch target commit instead of tags 

- ADOPTERS.md
Looks like one of the adopters has closed its doors and their infrastructure has finally been shutdown meaning the link is causing failures for lychee CI.
This change removes the entry from adopters for D2iQ Konvoy which has closed it doors.
> docs: remove shutdown adopter D2iQ Konvoy

- pkg/cio/io.go
Preserve all errors encountered, instead of only the last one.
> pkg/cio: Close(): use errors.Join to return all errors

- RELEASES.md
- add k8s 1.34 into support matrix
- remove k8s 1.30 as its EOL in upstream
> doc: add k8s 1.34 into support matrix

- RELEASES.md
Extend the LTS support window for the 1.7 release branch to September 2026. The footnote asterisk is escaped to ensure correct rendering on the hugo site.
This change reflects the decision made during the community meeting, where @samuelkarp and I volunteered to provide extended support beyond the standard two-year LTS period. The existing support from @containerd/committers remains in place until March 2026.
> docs: Update 1.7 LTS support timeline

- cmd/ctr/commands/images/pull.go
- core/diff/apply/apply.go
- core/diff/diff.go
- core/diff/proxy/differ.go
- core/transfer/local/progress.go
- core/transfer/local/pull.go
Adds unpack to transfer service.
See https://asciinema.org/a/6bJRKKKuqkAVV51GjN8SBSeYu
A few notes...
- we could order the progress lines better to make it easier to follow
- remote differ will not have the progress but the proxy will at least send start and end progress
> Tar unpack progress through transfer service

- cmd/containerd/command/config.go
- defaults/defaults_unix.go
- defaults/defaults_windows.go
We've reworked config merging strategy in 2.0 - https://github.com/containerd/containerd/pull/9982
This change adds `/etc/containerd/conf.d/*.toml` to the default configuration to allow configs drop-ins without the need to change root configuration file. 
```bash
❯ bin/containerd config default
...
imports = ['/etc/containerd/conf.d/*.toml']
```
> Add conf.d include in the default config

- .github/workflows/ci.yml
- .github/workflows/node-e2e.yml
The Kubernetes Node E2E workflow has proven to be stable:
https://github.com/containerd/containerd/actions/workflows/node-e2e.yml
To ensure these tests pass before merging, this change integrates the workflow into the required CI checks.
> Make E2E workflow a required check

- api/releases/v1.10.0-beta.toml
Prepare release notes for api/v1.10.0-beta.0 now that there is an api change to go into the 2.2 release. 
----
containerd api/v1.10.0-beta.0
Welcome to the api/v1.10.0-beta.0 release of containerd!  
The 11th release for the containerd 1.x API aligns with the containerd 2.2 release.
* Add mount manager ([#12063](https://github.com/containerd/containerd/pull/12063))
* Wei Fu
<details><summary>4 commits</summary>
<p>
* Add mount manager ([#12063](https://github.com/containerd/containerd/pull/12063))
* [`8db301086`](https://github.com/containerd/containerd/commit/8db3010865ae9926aed6c5e476a7c6b2413b44d5) Add mounts api service
* …
> Prepare release notes for api/v1.10.0-beta.0

- .github/workflows/api-release.yml
The switch to actions/download-artifacts v5.0.0 changed the output path to no longer include the name specified by upload.
See the WhatsNew section https://github.com/actions/download-artifact?tab=readme-ov-file#v5---whats-new for description of the behavior change.
Note that the regular non-api release still works because that uses multiple artifacts, which did not have a behavior change.
Run without fix:
[API Release](https://github.com/dmcgowan/containerd/actions/runs/18326085735)
Run with fix:
[API Release](https://github.com/dmcgowan/containerd/actions/runs/18326830075)
> Fix gha api release file path
